### ISSUE TITLE
{"status":"fail","message":"Uploaded image isn't in the right format"}

### ISSUE THREAD

**Issue by capsload** [mgp25/Instagram-API#1]
Hey.

Just getting this message.
```
REQUEST: media/configure/
```
`DATA: ig_sig_key_version=4&signed_body=XXXXX.%7B%22caption%22%3Anull%2C%22upload_id%22%3A%221448545521442%22%2C%22source_type%22%3A3%2C%22edits%22%3A%7B%22crop_zoom%22%3A1%2C%22crop_center%22%3A%5B0%2C0%5D%2C%22crop_original_size%22%3A%5B1000%2C1000%5D%2C%22black_pixels_ratio%22%3A0%7D%2C%22device%22%3A%7B%22manufacturer%22%3A%22asus%22%2C%22model%22%3A%22Nexus+7%22%2C%22android_version%22%3A22%2C%22android_release%22%3A%225.1%22%7D%2C%22_csrftoken%22%3Anull%2C%22_uuid%22%3A%22XXXXXXXff%22%2C%22_uid%22%3Anull%7D`
```
RESPONSE: {"status":"fail","message":"Uploaded image isn't in the right format"}
```

Tried it in PNG, JPG,

200x200
500x500
1000x1000

what should i change?

**Comment by mgp25** [comment]
@capsload use jpg format.

**Comment by capsload** [comment]
I did that.
Do you have a example jpg for me that is working?

**Comment by capsload** [comment]
ok it worked now :o

**Comment by mgp25** [comment]
@capsload great :smile: 

Remember to quote debug next time

Regards

**Comment by capsload** [comment]
Do you know thats one of the most things i waited for? Uploading Images to instagram through PHP script makes things so beautiful :3 Thank you again @mgp25 !

I sent you a mail about 2 days ago, to me@mgp25. - can you check that out ? (Subject; WhatsApp..)

:P

**Comment by mgp25** [comment]
@capsload send me your email

**Comment by capsload** [comment]
trash --- AT --- pauschi.de

**Comment by mgp25** [comment]
@capsload i didnt receive any mail of yours

**Comment by capsload** [comment]
mgp25 then its ven000m.com --- AT --- gmail.com ;-)

**Comment by pseeker** [comment]
Good afternoon!
not work upload photos.
upload_id takes the value null

REQUEST: media/configure/ 

DATA: ig_sig_key_version=4&signed_body=917b86125d2d13dee03ae93833a7c9430b04629ea845d03c0cc76bef643c3ff8.%7B%22caption%22%3A%22test%22%2C%22upload_id%22%3Anull%2C%22source_type%22%3A3%2C%22edits%22%3A%7B%22crop_zoom%22%3A1%2C%22crop_center%22%3A%5B0%2C0%5D%2C%22crop_original_size%22%3A%5B750%2C750%5D%2C%22black_pixels_ratio%22%3A0%7D%2C%22device%22%3A%7B%22manufacturer%22%3A%22asus%22%2C%22model%22%3A%22Nexus+7%22%2C%22android_version%22%3A22%2C%22android_release%22%3A%225.1%22%7D%2C%22_csrftoken%22%3A%228693ae4a67e05fccc7c2eb768721b869%22%2C%22_uuid%22%3A%2206eea4b2-57c8-4e0e-9d14-408aa9831bdc%22%2C%22_uid%22%3A%222296651124%22%7D RESPONSE: Oops, an error occurred.

**Comment by pseeker** [comment]
var $resp line number 197
return Array:

HTTP/1.1 100 Continue
Date: Thu, 03 Dec 2015 07:13:43 GMT

HTTP/1.1 500 INTERNAL SERVER ERROR
Server: nginx
Date: Thu, 03 Dec 2015 07:13:44 GMT
Content-Type: text/html; charset=utf-8
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
X-Instagram-Ssl-Everywhere: True
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Set-Cookie: csrftoken=8693ae4a67e05fccc7c2eb768721b869; expires=Thu, 01-Dec-2016 07:13:44 GMT; Max-Age=31449600; Path=/
Connection: keep-alive
Content-Length: 25

Oops, an error occurred.

**Comment by mgp25** [comment]
@pseeker open a new issue. Check if you are using a good path for `$photo`, and try running it in localhost

Ragards

**Comment by ankitatejani84** [comment]
@mgp25  i need help
 when I post PNG image i got error 
`400 73B RESPONSE: {"message": "Uploaded image isn't in the right format", "status": "fail"} Something went wrong: Uploaded image isn't in the right format.`
