### ISSUE TITLE
Function deleteMedia problem

### ISSUE THREAD

**Issue by OwlGreenApple** [mgp25/Instagram-API#1016]
Hi i have a problem,

i cant delete media with latest stable version(1.6.1). 
it could be done with 1.4 version
whats happen ?

it says 
<pre>
InstagramException in Instagram.php line 1854:
InstagramAPI\MediaDeleteResponse : could not delete
</pre>

**Comment by SteveJobzniak** [comment]
Don't know. But it works in the latest development version (master). It will take some time until we're done and release the next stable, 2.x. Lots of work to do and many functions are changing a lot.

So I'll leave this ticket open for 1.6.1 users to try to help each other. All of our development focus is on 2.x.

**Comment by mgp25** [comment]
@OwlGreenApple tested on both, and works. 

Regards

**Comment by OwlGreenApple** [comment]
@mgp25 is that works with default sigkey & sigkey version ? (1.6.1)
if that works, whats the problem with my errors ?

Regards

**Comment by OwlGreenApple** [comment]
@SteveJobzniak Sorry i don't mean to be rude, appreciate your hard work man.

**Comment by SteveJobzniak** [comment]
@OwlGreenApple Okay thanks, glad to hear that. I'll edit my post to not call you out publicly. I was angry because you came in here with such an offtopic post after a huge portion of my life went into fixing this project for free. ;-)

**Comment by OwlGreenApple** [comment]
Hi @SteveJobzniak Dont you mind to explain me how to read $i->getRecentActivity() 
using example code will be great, is this using guzzle ?
I read there are no function on class ActivityNewsResponse, only public variable.
Please help me ;)
