### ISSUE TITLE
Upload photo example with location

### ISSUE THREAD

**Issue by adrianofoschi** [mgp25/Instagram-API#1019]
Can you provide an example of photo upload with "location" ?
Thanks you

**Comment by mgp25** [comment]
You can set your own location here:

```php
    public function uploadPhoto($photo, $story = false, $caption = null, $location = null, $upload_id = null, $filter = null)
```

Ill try to add info to wiki soon

Regards

**Comment by Diddlik** [comment]
How should location look like?
