### ISSUE TITLE
Delete media

### ISSUE THREAD

**Issue by TinBoyko** [mgp25/Instagram-API#102]
Can't delete media. It getting error "status":"fail","message":"Please update your Instagram app to delete photos". I've changed Instagram version in user-agent  to "Instagram 7.18.2", but still no luck.

**Comment by mgp25** [comment]
Read wiki, extract sig key according to that version

Regards

**Comment by TinBoyko** [comment]
I have Instagram 7.14.0 installed.I've allready extracted sig key from it, in user-agent changed to the same version. It's wont work. Or i need to update app to latest version?

p.s Sorry for my english.
