### ISSUE TITLE
PHP Fatal error:  Class 'InstagramAPI\HttpInterface' not found

### ISSUE THREAD

**Issue by monajalal** [mgp25/Instagram-API#1021]
Can you please provide more details on how to run examples?

```
mona@pascal:~/computer_vision/instagram/Instagram-API/examples$ php PaginationExample.php 
PHP Warning:  include(../../../../vendor/autoload.php): failed to open stream: No such file or directory in /home/mona/computer_vision/instagram/Instagram-API/examples/PaginationExample.php on line 3
PHP Warning:  include(): Failed opening '../../../../vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /home/mona/computer_vision/instagram/Instagram-API/examples/PaginationExample.php on line 3
PHP Fatal error:  Class 'InstagramAPI\HttpInterface' not found in /home/mona/computer_vision/instagram/Instagram-API/src/Instagram.php on line 66

```

**Comment by beshoo1** [comment]
Alsalm Alykom Mona :) كيف الحال
Please Note that @mgp25  is updating the HttpInterface class !

**Comment by SteveJobzniak** [comment]
@monajalal Hi. Please try again with the commit I just pushed.

And be sure that you've installed Instagram-API via Composer, so that you have all dependencies. :-)

**Comment by SteveJobzniak** [comment]
Here's the necessary change, if you want to backport it to 1.6.1:

https://github.com/mgp25/Instagram-API/commit/60140694c60e433b8fbb24ca84af3216cabff676

Alternatively, you can use the somewhat unstable and in flux `dev-master` version of the API to get the patch:

```
composer require mgp25/instagram-php dev-master
```

**Comment by monajalal** [comment]
Hi @SteveJobzniak thanks a zillion! I confirm that after I did git pull in `cd ..` and then wrote my username and password in that `PaginationExample.php` the following command worked correctly:
`mona@pascal:~/computer_vision/instagram/Instagram-API/examples$ php PaginationExample.php 
`Also, is there a rate limit here and how much is that? 
For imgur Python API there's 12500 API request per day. 
*I wonder things like getting all the comments from an image for say 10k images is sensible within a week or not? What do you suggest for this purpose?
