### ISSUE TITLE
Add support for uploading videos to timeline albums

### ISSUE THREAD

**Issue by ping** [mgp25/Instagram-API#1025]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Describe your issue

Not really an issue but since photo album posting is supported but not yet video albums, I'd like to provide some information for that implementation.

1. For videos, when chunk posting to upload.instagram.com, you may need to specify a ``Cookie`` value in the request header
    ```php
    # something like
    $headers['Cookie'] = 'sessionid=' . $sessionId;
    ```
    where ``$sessionId`` is the ``sessionid`` cookie value. Without this header, you'll get a 403 "StagedUpload not found" response when posting the last chunk. This extra header is only required for album video posting. Regular video posts are not affected.

2. Aspect ratio of the media item should be 1:1. I have not tested if IG will reject a media that is not 1:1 but based on the official app behavior, it seems like only square cropped media is supported.

I can't submit a PR as yet since the HTTP interface is undergoing rewrite and I'm not caught up with the changes. I'm also unfamiliar with the Guzzle framework.

Hope this bit of info helps in any case.

**Comment by SteveJobzniak** [comment]
Thanks for the info. This feature will probably take a long time. We're done with `request()` and `uploadVideo()` in HttpInterface. The other functions in there are not done at all. And those are the highest priority.

As for implementing videos in albums, I have some ideas and will start implementing the basic shell of it now so that it's ready for adding video support later.

**Comment by SteveJobzniak** [comment]
Related commits:

https://github.com/mgp25/Instagram-API/commit/0959247da02e6720d9902fc4d2f65b4ec731e989
https://github.com/mgp25/Instagram-API/commit/f47b8c0f4b28b90f7cb8e2d7a723d5b7d1a560f5

**Comment by SteveJobzniak** [comment]
Nearly finished:

https://github.com/mgp25/Instagram-API/commit/b080c4a357cf7592b2c4168ec9a61e1f3bb0767a

Now @mgp25 will be reverse engineering the necessary endpoint for configuring videos to albums. And that's it. This feature will be done in a moment! :)

**Comment by mgp25** [comment]
@ping done https://github.com/mgp25/Instagram-API/commit/7d600bd6ce03725636d5c696f2ae33cf102d4e74

**Comment by SteveJobzniak** [comment]
@ping Turns out some more work was needed but we will be done within a few hours.

**Comment by SteveJobzniak** [comment]
@ping Okay I just finished the code. All upload functions have been revised. They are now:

```
uploadTimelinePhoto()
uploadStoryPhoto()
uploadTimelineVideo()
uploadStoryVideo()
uploadAlbum()
```
