### ISSUE TITLE
InstagramAPI\FollowerAndFollowingResponse : Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by monajalal** [mgp25/Instagram-API#1026]
How should I handle this? Specially if I am running a script and don't want to get interrupted? I prefer to wait 10 min or so rather than the script falling apart during execution.

Thanks for tips!

result of running this code:
```
30     $helper = null;
 31     $followers = [];
 32
 33     do {
 34         if (is_null($helper)) {
 35             $helper = $i->getUserFollowers(220004286);
 36         } else {
 37             $helper = $i->getUserFollowers(220004286, $helper->getNextMaxId());
 38         }
 39
 40         $followers = array_merge($followers, $helper->getUsers());
 41     } while (!is_null($helper->getNextMaxId()));
 42
 43     echo "My followers: \n";
 44     foreach ($followers as $follower) {
 45        echo '- '.$follower->getUsername()."\n";
 46     }
```
That said, after a while of waiting I could get 17k followers usernames:
```
$ wc -l people
17960 people
```
Basically I am looking for a technique to automate this!

**Comment by mgp25** [comment]
You need to use try and catch blocks to catch exceptions, and add all your logic in your script.

Not API issue

Regards

**Comment by SteveJobzniak** [comment]
Instagram does not allow people to query their API too fast. sleep(6) for a six second sleep between every API call is enough to never get rate limited. Or you can catch the [InstagramException](https://github.com/mgp25/Instagram-API/blob/master/src/InstagramException.php), look for the `\InstagramAPI\ErrorCode::INTERNAL_API_THROTTLED` error code in its `getCode()`, and implement some custom logic to pause.

Both of which are outside the scope of this ticket system. We're here for fixing the API. Not for customer support. Because this is a free library and we're coding it as a hobby.

**Comment by monajalal** [comment]
@SteveJobzniak thanks for the tip, for example this code worked for me

```
33     $helper = null;
 34     $followers = [];
 35 
 36     do {
 37         if (is_null($helper)) {
 38             $helper = $i->getUserFollowers(220004286);
 39         } else {
 40             $helper = $i->getUserFollowers(220004286, $helper->getNextMaxId());
 41         }
 42 
 43         $followers = array_merge($followers, $helper->getUsers());
 44     } while (!is_null($helper->getNextMaxId()));
 45 
 46     echo "Followers: \n";
 47     foreach ($followers as $follower) {
 48        try {
 49             echo '- '.$follower->getUsername()."\n";
 50        }
 51        catch (InstagramException $ie) {
 52             echo $ie.getCode();
 53             sleep(6);
 54        }
 55 
 56     }
```
Does Instagram have 5000 requests limit per hour for getting media or user info?

Thanks both,
Mona

**Comment by WolfKOTTO** [comment]
So does this mean that I can never get my account back?

**Comment by shivenmian** [comment]
@SteveJobzniak what's the difference between the ThrottledException and this BadRequestException (please wait few minutes)? Both seem to be exceptions thrown when you cross the rate limit.

**Comment by SteveJobzniak** [comment]
@shivenmian `ThrottledException` is for HTTP status "429 Too Many Requests", `BadRequestException` is for HTTP status "400 Bad Request" (which can happen anytime if you send bad parameters to a function).

**Comment by adolfousier** [comment]
Guys I've find a solution to my problem here, I encountered the same message after and api issue, no way to login, I just find out that when I change from wifi to mobile data, it's stop immediately and get back to work. Give a test and letme know if it work out for you.

@adolfousier instagram.
