### ISSUE TITLE
Getting n number of followers

### ISSUE THREAD

**Issue by Azamatjon** [mgp25/Instagram-API#1029]
Good day, I know that you can add the question like as duplicated, but I couldn't find the answer for my question.  I am having trouble when I get N number of followers. It is giving but so many. How can I get exactly n number of followers. This is my code, what is wrong in my code?....
`$i->getSelfUserFollowers(10)`
Can you give an example of getting 10 followers?

**Comment by mgp25** [comment]
Hello, use this example: https://github.com/mgp25/Instagram-API/blob/master/examples/PaginationExample.php

And then take first 10 elements of the array

Regards
