### ISSUE TITLE
what is correct schema for $contacts  in syncFromAdressBook()

### ISSUE THREAD

**Issue by zerodwide** [mgp25/Instagram-API#103]
dear @mgp25 
previously i requested contact sync and you kindly added to API, thanks a lot about that.

but now that i'm testing it, it results in failure.
it seems given schema for $contacts is not correct.

**CODE:**

$contacts = array(
  array(
    'first_name' => 'whatever',
    'phone_numbers' => array('34123456789'),
    'email_addresses' => array('whatever@gmail.com')
  )
);

$i->syncFromAdressBook($contacts);

**DEBUG:**

REQUEST: address_book/link/?include=extra_display_name,thumbnails
RESPONSE: {"status":"fail","message":"Invalid arguments"}

**Comment by mgp25** [comment]
Use a proxy, and update the function

Regards

**Comment by rocxteady** [comment]
Replace these lines:
`$data = [
        'contacts'  => json_encode($contacts, true),
      ];`
With these:
`$data = "contacts=".json_encode($contacts, true);`

**Comment by mgp25** [comment]
@rocxteady +1 added in next commit
