### ISSUE TITLE
need code

### ISSUE THREAD

**Issue by josephanwar2** [mgp25/Instagram-API#1030]
Hello dear,
I am new in github
and need code (any language) for increase video views for instagram, please help me for that
thank you

**Comment by mgp25** [comment]
![](http://s2.quickmeme.com/img/69/690524ec233ec9fa86f81ef4d6007b5f7379ae1127924560bb9a8829abed0951.jpg)

**Comment by josephanwar2** [comment]
thanks for reply
but can you tell me why it is "invalid" "Not related" "Won't do"
as I said, I am new here :)

**Comment by mgp25** [comment]
Because thats spoofing and spamming, not cool

**Comment by josephanwar2** [comment]
ahaaa
thanks, you are right

**Comment by beshoo1** [comment]
@josephanwar2 you may track how Instagram do that by using such proxy and do the PHP code  . please DO NOT share it
