### ISSUE TITLE
SettingsMysql.php throwing errors

### ISSUE THREAD

**Issue by zuexo** [mgp25/Instagram-API#1032]
There are two issues that are raised in SettingsMysql.php:
1.) Errors are thrown for unknown columns (uuid, device_id, phone_id).
2.) When I provide PDO to Instagram class, 'dbName' defaults to 'instagram' even though I used different dbName when constructing PDO.
```php
try {
    $dbHost = "localhost";
    $dbName = "instagram_test";
    $pdo = new \PDO("mysql:host={$dbHost};dbname={$dbName}", $dbUsername, $dbPassword, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
    $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
    $pdo->query("SET NAMES UTF8");
    $pdo->setAttribute(PDO::ERRMODE_WARNING, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    throw $e;
}

$i = new \InstagramAPI\Instagram($debug, false, [
    'type'  => 'mysql',
    'pdo' => $pdo
]);
```

**Comment by SteveJobzniak** [comment]
Read the source, specifically the constructor for the MySQL Settings Adapter:

https://github.com/mgp25/Instagram-API/blob/master/src/Utils/SettingsMysql.php

You're missing two values. I'll let you figure it out :) It's right there in the constructor.

**Comment by zuexo** [comment]
I know that I can set dbName with argument. I just don't get it why do I need to provide db name for the  second time if you can get db name from PDO.

**Comment by SteveJobzniak** [comment]
I'll change that. But you're still missing settings. Read the constructor.

**Comment by SteveJobzniak** [comment]
Improved:

https://github.com/mgp25/Instagram-API/commit/86392102dc7f9da066ee31231dac395b3c77a2bd

Now just include the other settings you missed. ;-)

**Comment by zuexo** [comment]
I don't get it. What other settings am I missing and will that fix errors for missing columns?
I tried like:
```php
$i = new \InstagramAPI\Instagram($debug, false, [
    'type'  => 'mysql',
    'pdo' => $pdo,
    'name' => $dbName,
    'tablename' => "user_settings"
]);
```
But neither name or tablename get passed to SettingsMysql construct and I get following error:
PHP Notice:  Undefined index: db_name in vendor/mgp25/instagram-php/src/Utils/SettingsAdapter.php on line 33

**Comment by SteveJobzniak** [comment]
```php
    public function __construct($mysqlOptions)
    {
        $this->instagramUsername = $mysqlOptions['instagramUsername'];
        if (isset($mysqlOptions['dbTableName'])) {
            $this->dbTableName = $mysqlOptions['dbTableName'];
        }
        if (isset($mysqlOptions['pdo'])) {
            // Pre-provided PDO object.
            $this->pdo = $mysqlOptions['pdo'];
        } else {
            // We should connect for the user.
            $username = is_null($mysqlOptions['dbUsername']) ? 'root' : $mysqlOptions['dbUsername'];
            $password = is_null($mysqlOptions['dbPassword']) ? '' : $mysqlOptions['dbPassword'];
            $host = is_null($mysqlOptions['dbHost']) ? 'localhost' : $mysqlOptions['dbHost'];
            $dbName = is_null($mysqlOptions['dbName']) ? 'instagram' : $mysqlOptions['dbName'];
            $this->connect($username, $password, $host, $dbName);
        }
        $this->autoInstall();
        $this->populateObject();
    }

```

READ.

**Comment by zuexo** [comment]
Since latest commit only pdo parameter is needed and it works
```php
$i = new \InstagramAPI\Instagram($debug, false, [
    'type'  => 'mysql',
    'pdo' => $pdo
]);
```

I still don't get it how adding any other parameter will fix missing columns in my table.
