### ISSUE TITLE
Making logIn Faster

### ISSUE THREAD

**Issue by LanchaBasualdo** [mgp25/Instagram-API#1036]
@mgp25 hi.
would you mind telling which of these functions are esential to the `login()` function so as to comment those which are not and make the login process faster? For example: what are the `syncFeatures` or the `megaphoneLog` functions. Why should we return the `explore()`? 
```
$test = $this->syncFeatures();
$this->autoCompleteUserList();
//$this->timelineFeed();
$this->getRankedRecipients();
$this->getRecentRecipients();
$this->megaphoneLog();
//$this->getv2Inbox();
$this->getRecentActivity();
$this->getReelsTrayFeed();

return $this->explore();
```
Thanks for your time

**Comment by SteveJobzniak** [comment]
https://github.com/mgp25/Instagram-API/commit/589306a94afd5465b77bd56942da92ec96c2fc7f

**Comment by LanchaBasualdo** [comment]
@stevejobzniak thanks for the repaly
How can I hash the logged in session after the program ends so as not to be logging in each time the programs starts?

**Comment by SteveJobzniak** [comment]
LanchaBasualdo: Store it in SettingsFile or SettingsMysql.

To use SettingsFile (the easiest to setup):

```php
$i = new \InstagramAPI\Instagram($debug, $truncatedDebug, [
    'type'             => 'file',
    'settings_path' => $yourPath
]);
```

**Comment by LanchaBasualdo** [comment]
thanks! and sorry

**Comment by SteveJobzniak** [comment]
:)

**Comment by SteveJobzniak** [comment]
@LanchaBasualdo I have to change my old recommendation. 6 hours is the highest we can recommend without you becoming banned by Instagram.

Read this new commit, which caps the new "refresh interval" parameter at no more than 6 hours:

https://github.com/mgp25/Instagram-API/commit/27e310d161647a9767aa407c7761c3e507a90cd3

Lots of comments have been added to explain why this is needed.

But 6 hours between state refreshes should be enough for anybody!

**Comment by LanchaBasualdo** [comment]
Great! I will check it
Thanks for the heads up!
