### ISSUE TITLE
getProfileData() needs update

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1038]
The `./http/Response/ProfileResponse.php` class is either outdated globally (many things use it), or perhaps just for getProfileData queries. Its fields do not match what's retrieved by the server. The server gives a "user" subarray instead, with lots of new values.

@mgp25 This is your expertise area. I don't know if I would break other API calls by editing ProfileResponse. So please investigate this outdated profile-response when you have time. :-)

```php
            $response = $i->getProfileData();
            var_dump($response); // Everything except getFullResponse() will be NULL.
```

**Comment by SteveJobzniak** [comment]
I noticed that `$i->searchUsername()` returns a `http/Response/UsernameInfoResponse.php` which properly handles the $user subarray. So my guess is that getProfileData() will need that fix.

But other things that use ProfileResponse may not need the fix. So it's possible that getProfileData() will need an entirely new http/Response type class.

**Comment by beshoo1** [comment]
@SteveJobzniak , is that mean end user has to change functions names or attributes  ?

PS: Thank you for the proxy help :)

**Comment by mgp25** [comment]
Fixed https://github.com/mgp25/Instagram-API/commit/4c7492c494479984dcda1ac6d482894ce5d6f7d7
