### ISSUE TITLE
Will need to fix all chained ternary operators

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1039]
Just a reminder to myself to fix all ternary operators. They lack parenthesis which means they don't select the correct path.

**Comment by Lastwisher** [comment]
Any refferance ?

**Comment by SteveJobzniak** [comment]
@Lastwisher Someone wrote code that looks like `true ? true ? true ? true : false` which is not a proper use of ternary operators. There needs to be parenthesis, otherwise PHP selects the final "false" every time.

To find all these chained operators I used a grep:

```php

$ grep -REl "\\?.+:.+\\?" .

./src/Utils/SettingsAdapter/Memcached.php
./src/Utils/SettingsAdapter.php
```

Going to rewrite them now.
