### ISSUE TITLE
How to get location list with another language e.g(russian language)

### ISSUE THREAD

**Issue by Azamatjon** [mgp25/Instagram-API#1042]
Good day, I have an issue. I am having location list  with `$i->searchFBLocation("usa")` but I need for another place that has written with another language e.g. `$i->searchFBLocation("москва")` how to do it?
PS It is not not giving list of locations with another language
Thanks....

**Comment by SteveJobzniak** [comment]
I think cyrillic is supposed to work. Maybe the location search API is using the wrong string encoding. This will need investigating.

**Comment by SteveJobzniak** [comment]
@Azamatjon Where are your strings coming from? If from a user/webpage, perhaps your encoding is windows-1251 (cyrillic).

Please try converting all strings to utf-8 before searching via our API. See if that works.

http://php.net/manual/en/function.mb-convert-encoding.php

Use this to convert to UTF-8 from whatever format your string is in.

Be sure to provide all 3 parameters to that function.

**Comment by mgp25** [comment]
@Azamatjon fixed in commit https://github.com/mgp25/Instagram-API/commit/9802f92a10174a5b6c52569160b42af052a85eb7

**Comment by SteveJobzniak** [comment]
@Azamatjon The issue was found, but also be sure your strings are UTF-8. That's what instagram expects. You may often have to use mb_convert_encoding.

**Comment by Azamatjon** [comment]
Thanks. I will try it later
