### ISSUE TITLE
How can I get all the media of a public user having its idea (or its $user) ?

### ISSUE THREAD

**Issue by monajalal** [mgp25/Instagram-API#1045]
Hi, 
I looked at the src/Instagram.php but couldn't find an appropriate function. Hence, what is the function to grab all the medias of a public user?

is this correct?
```
    $userfeed = $i->getUserFeed(53112486);
    var_dump($userfeed);

```
Feed sometimes could mean what I seen when I click on home icon. I guess I am looking for my timeline info.
Thanks,
Mona

**Comment by SteveJobzniak** [comment]
@monajalal Yes getUserFeed is correct. Feed = their timeline. You must also paginate it, as in PaginateExample.
