### ISSUE TITLE
Need a return from function directMessage

### ISSUE THREAD

**Issue by adamasantares** [mgp25/Instagram-API#1050]
It's will be great to have some return from directMessage() for check of result. Thank you.

**Comment by SteveJobzniak** [comment]
@adamasantares What result are you interested in? All functions throw InstagramException if the API call fails. So if nothing is thrown, it worked!

**Comment by SteveJobzniak** [comment]
But I have to say that the class in general is not well documented. I didn't write it. The fact that they throw exceptions isn't clear. I've been fixing docblocks where I've been working, but can't do it everywhere.

I will now fix the docblocks about all of the direct* functions, and will also make them return exactly what the server replied.

**Comment by SteveJobzniak** [comment]
@adamasantares They now return the server response, but there's nothing of value in there. Still, you may enjoy it. And now you know they throw an exception.

**Comment by adamasantares** [comment]
@SteveJobzniak 

hey! Sorry I was ill for a couple of last weeks and missed your answer. The problem is that I cannot understand what is going when I call that method. I'm sending a messages, but only one message of (let's say) 3 messages will sent. And I didn't get any exceptions. So looks like message sent, because no exceptions, but may be no exceptions because no error returned, but some other response type from instagram received with problem description? So, now I'm still have a problem with messages sending... I check the responses and in all of them I see "status = ok". But them not really delivered to user :(

**Comment by jpmoney5065** [comment]
@adamasantares Maybe it has to do with accounts being detected spam/bot? 

Obviously this happens with posting and following on some accounts, where Instagram will return a `status:ok`, but the follow or post won't actually have worked.

**Comment by adamasantares** [comment]
@jpmoney5065 

I'm not sure about that. Actually I don't use this package for spamming. It's used for sending responses to clients from CRM system. There are no too much outgoing messages.

All messages sending to already opened chats in instagram direct (clients writen first).

Ok, I found that in response of directMessage I can get ID of sent message, so I plan to make checks for exists message with same ID in thread (chat) after message sent.

**Comment by SteveJobzniak** [comment]
@adamasantares 

@jpmoney5065 

> The problem is that I cannot understand what is going when I call that method. I'm sending a messages, but only one message of (let's say) 3 messages will sent. And I didn't get any exceptions. So looks like message sent, because no exceptions

That was a brief bug in 2.x beta. We generated the same Message ID every time so only 1 message worked. That bug has been fixed for a few days.
