### ISSUE TITLE
deleteMedia problem

### ISSUE THREAD

**Issue by kiros32** [mgp25/Instagram-API#1052]
Hi

I got this error while on media delete

```$instagram->deleteMedia($idOfMyMedia);```

```POST:  media/***/delete/
DATA: ig_sig_key_version=4&signed_body=***.{"_uuid":"***","_uid":"***","_csrftoken":"***","media_id":***}
← 400 	 51B
RESPONSE: {"status": "fail", "message": "invalid parameters"}

Exception 'InstagramAPI\InstagramException' with message 'InstagramAPI\MediaDeleteResponse : invalid parameters'```

**Comment by SteveJobzniak** [comment]
@kiros32 I can see from the message that you are using version 1.6.1.

Upgrade to 2.x beta and try it instead. I've successfully deleted media with 2.x. See the announcement thread here for instructions:

https://github.com/mgp25/Instagram-API/issues/1046

**Comment by SteveJobzniak** [comment]
Oh and please let me know if that solves it for you. I am curious, but I think it will!

**Comment by kiros32** [comment]
Ok

I did
```composer require mgp25/instagram-php dev-master```

But problem is the same.
```$this->client->deleteMedia(***);```

```POST:  media/***/delete/
DATA: ig_sig_key_version=4&signed_body=***.{"_uuid":"***","_uid":"***","_csrftoken":"***","media_id":***}
← 400 	 51B
RESPONSE: {"message": "invalid parameters", "status": "fail"}

Exception 'InstagramAPI\InstagramException' with message 'InstagramAPI\MediaDeleteResponse: invalid parameters.'

**Comment by SteveJobzniak** [comment]
@kiros32 Okay you don't have the correct media id: `{"message": "invalid parameters", "status": "fail"}`. You must own the media, and you must provide the exact media ID to the function.

**Comment by kiros32** [comment]
Yes you are right. I used pk , not id.

**Comment by narayac** [comment]
Hello, my friend, did the deletemedia work
Thank you

**Comment by SteveJobzniak** [comment]
@narayac Yes he said above that it worked when he used the "getId()" of the media.
