### ISSUE TITLE
uploading video stopped working

### ISSUE THREAD

**Issue by noorzaie** [mgp25/Instagram-API#1055]
response :

`{"configure_delay_ms": "6500", "result": "deprecated", "status": "ok"}`

please don't close issue! :|

**Comment by mgp25** [comment]
@noorzaie that is a correct response, right after that you will see a photo upload request and then a configure one.

 Nothing wrong in here, if you thing there is still any error, post full debug log (from video upload to last requests)

**Comment by noorzaie** [comment]
no. after this response, your code stops and doesn't upload the thumbnail. I changed the code to upload thumbnail after this response and now it works.
