### ISSUE TITLE
How to add new line to the caption of uploaded photo?

### ISSUE THREAD

**Issue by Azamatjon** [mgp25/Instagram-API#1056]
I am doing like this `$i->uploadPhoto($photo, sprintf('My caption #tag1 #tag2 %c Something', 10);` All texts are deriving but only my new line char is not showing. Please  help me to do that, don't close the issue...

**Comment by mgp25** [comment]
@Azamatjon you can't do a line break in caption.

And if you use 2.x (source from master), the function has been renamed to `uploadTimelinePhoto`

**Comment by Azamatjon** [comment]
Isn't there any way to do it, but when I do it with my phone it works perfect (new line), I thought phones and your API's uses same way...

**Comment by Azamatjon** [comment]
I mean same API

**Comment by mgp25** [comment]
@Azamatjon i tried in my device, there is no way to add a new line, you can add lot of spaces to simulate a new line but no `\n` as far as i know

**Comment by Azamatjon** [comment]
Thank you, for your trying....I close the issue
