### ISSUE TITLE
uploadTimelineAlbum - not working

### ISSUE THREAD

**Issue by needyourhelp** [mgp25/Instagram-API#1058]
Thank you for best API but album function (uploadAlbum or uploadTimelineAlbum) doesnt work. I tried uploadAlbum and i saw new update today it's also not working?
 
What's problem ? Others functions are working. (photo upload, upload story etc. all of them working except album.)

> RESPONSE: {"message": "Invalid Parameters", "status": "fail", "error_type": "missing_parameters"}

**Comment by SteveJobzniak** [comment]
Try clicking the button you just clicked. It is called: **New issue**...

Then try reading the message you see in the text box, instead of just deleting the message and wasting my time.
