### ISSUE TITLE
Instagram delete uploaded photo

### ISSUE THREAD

**Issue by nanashel** [mgp25/Instagram-API#106]
Hi,
I'm trying to post some photos to instagram:
First upload attempt success, photo shown in account, thats ok. But next attempts returns:
**Login -> ok
Upload photo->returns ok+uploaded_id
Logout -> ok**
After few seconds instagram deleting photo.
Cleaned all .dat files, tried without logout, tried to test time intervals.
Finnaly:
After 2-3 days history repeats: First photo ok, next not, but instagram returns uploaded_id.
Maybe someone has ideas what wrong?
Thx in advance!

**Comment by mgp25** [comment]
@nanashel if you account is flagged or you are trying to upload the same photo, your account wont be able to upload photos.

**Comment by nanashel** [comment]
i use 100% different photos and 100% unique.
How can I check is my account is flagged?

**Comment by mgp25** [comment]
If you upload a photo and is not published, the account is flagged
