### ISSUE TITLE
About Login() in loop .

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#1065]
Dear All , Regarding this Doc:
https://github.com/mgp25/Instagram-API/commit/27e310d161647a9767aa407c7761c3e507a90cd3

There is an advice to run the login() each time we run the script , Let's say i have a long term script 
Which collect Followers in loop and there is a sleep(1000); between each loop .

Is that recommendation mean i have to run the login()  each time loop start ? 

```
for(.....){
$i->login();
......[ Get Followers ]...........
sleep(1000);
}
```

Is that what document mean !and when we call login() it will decide to load form session or force login ?

Thank you , and best regards

**Comment by beshoo1** [comment]
What  invalid ! 
It is a Question regarding a a comments in the API which it is not clear!

**Comment by mgp25** [comment]
do always login

**Comment by beshoo1** [comment]
Thank you,
