### ISSUE TITLE
how to use checkpoint ?

### ISSUE THREAD

**Issue by rizkihape** [mgp25/Instagram-API#1067]
i'm not understand for your example code,please tell me about this :(

**Comment by mrmlrgit** [comment]
imho, checkpoint need to use Guzzle and SettingsAdapter
also, useragent in checkpoint must something from android, may be windows
using iPhone ua in checkpoint and android ua in API - is suspicious, imho

**Comment by rizkihape** [comment]
the $code is input type ?

**Comment by mgp25** [comment]
@rizkihape it is outdated + see the example

I'll update eventually, nevertheless, if you want to send a pull request, it will be welcomed
