### ISSUE TITLE
usersFriendship always return null

### ISSUE THREAD

**Issue by aldasv** [mgp25/Instagram-API#1068]
> POST: friendships/show_many/
DATA: _uuid=...&user_ids=4532843931,25025320,522070796&_csrftoken=...
← 200 367B
RESPONSE: {"friendship_statuses": {"25025320": {"incoming_request": false, "following": true, "outgoing_request": false, "is_private": false}, "4532843931": {"incoming_request": false, "following": true, "outgoing_request": false, "is_private": false}, "522070796": {"incoming_request": false, "following": true, "outgoing_request": false, "is_private": true}}, "status": "ok"}

> object(InstagramAPI\FriendshipsShowManyResponse)#8 (4) {
  ["friendship_statuses"]=>
  array(3) {
    [25025320]=>
    object(InstagramAPI\FriendshipStatus)#17 (11) {
      ["following"]=>
      bool(true)
      ["followed_by"]=>
      NULL
      ["incoming_request"]=>
      bool(false)
      ["outgoing_request"]=>
      bool(false)
      ["is_private"]=>
      bool(false)
      ["is_blocking_reel"]=>
      NULL
      ["is_muting_reel"]=>
      NULL
      ["blocking"]=>
      NULL
      ["status"]=>
      NULL
      ["message"]=>
      NULL
      ["fullResponse"]=>
      NULL
    }
    [4532843931]=>
    object(InstagramAPI\FriendshipStatus)#18 (11) {
      ["following"]=>
      bool(true)
      ["followed_by"]=>
      NULL
      ["incoming_request"]=>
      bool(false)
      ["outgoing_request"]=>
      bool(false)
      ["is_private"]=>
      bool(false)
      ["is_blocking_reel"]=>
      NULL
      ["is_muting_reel"]=>
      NULL
      ["blocking"]=>
      NULL
      ["status"]=>
      NULL
      ["message"]=>
      NULL
      ["fullResponse"]=>
      NULL
    }
    [522070796]=>
    object(InstagramAPI\FriendshipStatus)#23 (11) {
      ["following"]=>
      bool(true)
      ["followed_by"]=>
      NULL
      ["incoming_request"]=>
      bool(false)
      ["outgoing_request"]=>
      bool(false)
      ["is_private"]=>
      bool(true)
      ["is_blocking_reel"]=>
      NULL
      ["is_muting_reel"]=>
      NULL
      ["blocking"]=>
      NULL
      ["status"]=>
      NULL
      ["message"]=>
      NULL
      ["fullResponse"]=>
      NULL
    }
  }
  ["status"]=>
  string(2) "ok"
  ["message"]=>
  NULL
  ["fullResponse"]=>
  object(stdClass)#13 (2) {
    ["friendship_statuses"]=>
    object(stdClass)#10 (3) {
      ["25025320"]=>
      object(stdClass)#9 (4) {
        ["incoming_request"]=>
        bool(false)
        ["following"]=>
        bool(true)
        ["outgoing_request"]=>
        bool(false)
        ["is_private"]=>
        bool(false)
      }
      ["4532843931"]=>
      object(stdClass)#11 (4) {
        ["incoming_request"]=>
        bool(false)
        ["following"]=>
        bool(true)
        ["outgoing_request"]=>
        bool(false)
        ["is_private"]=>
        bool(false)
      }
      ["522070796"]=>
      object(stdClass)#12 (4) {
        ["incoming_request"]=>
        bool(false)
        ["following"]=>
        bool(true)
        ["outgoing_request"]=>
        bool(false)
        ["is_private"]=>
        bool(true)
      }
    }
    ["status"]=>
    string(2) "ok"
  }
}

**Comment by SteveJobzniak** [comment]
Thanks for the report. Maybe the endpoint has changed.

**Comment by SteveJobzniak** [comment]
Wait a minute... I just read your log now...

Nope everything is working properly. Everything in the RESPONSE part is being mapped to those objects.

Objects are used for many times and don't always have all info. NULL in many fields is normal.
