### ISSUE TITLE
Todo: Add separate script for triggering mobile "reset password" endpoint

### ISSUE THREAD

**Issue by mrmlrgit** [mgp25/Instagram-API#1073]
I did not found in this API anything to **force** password reset by email
as I know, in mobile app you can do this without captcha (which is in web version)

![image](https://cloud.githubusercontent.com/assets/18467285/23833937/40fcc7be-0756-11e7-9b90-39e0a96f36c7.png)

**Comment by SteveJobzniak** [comment]
Hmm, the API functions are all for logged in users. So I dunno, it would require some thinking about where to put such a function. Probably as a separate script.

**Comment by mrmlrgit** [comment]
ok, I see

**Comment by SteveJobzniak** [comment]
No guarantees that this will get done, but keeping it open to think about it in a few days.

**Comment by icedragon** [comment]
Oh ) 
secret point - "you can do this without captcha" ))


Excuse me for no pull requests and old project style

code:
`    public function signInHelp($user)
    {
        $data = json_encode([
            'username_or_email' => $user,
            "phone_number"  => "",
            '_csrftoken'    => $this->token,
            'guid'          => $this->uuid,
            'device_id'     => $this->device_id,
        ]);

        return $this->http->request('accounts/sign_in_help/', SignatureUtils::generateSignature($data), true, true)[1];
    }
`

**Comment by SteveJobzniak** [comment]
@mrmlrgit I thought about it some more and this feature would mostly help bad guys. Regular users could get into their account via "forgot password" on the web/mobile if they ever (when?!) forget their password. But bad guys could use this to automate password reset emails. Won't do it sorry. :)
