### ISSUE TITLE
I have error at run checkpoint.php in CMD

### ISSUE THREAD

**Issue by skvoshiz** [mgp25/Instagram-API#1074]
![screenshot_1](https://cloud.githubusercontent.com/assets/15720360/23834248/34adbd20-0764-11e7-9493-81eaeb17ebcf.png)
How i can fix it?

**Comment by SteveJobzniak** [comment]
checkpoint is an old script, not sure it even works anymore.

**Comment by mangledbottles** [comment]
The checkpoint is outdated, Instagram has done it an entirely new way now.

1. To start the checkpoint you must log in
2. Then Instagram returns an error saying checkpoint with a URL to go to
3. Once you go there, the number and code is pretty much the same as in the old version
