### ISSUE TITLE
Todo: Move old scripts to "outdated" folder, update examples

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1076]
Depends on: https://github.com/mgp25/Instagram-API/issues/1075

After that, the next step is to update all examples to use the PSR-4 autoloading to avoid code repetition. And rewrite all examples (the current pagination method is very nasty and can be rewritten to just 2-3 lines instead).

And all old bonus-scripts need to be moved to an "outdated" folder so that people stop trying to use them until mgp25 has had time to rewrite them. (And they contain lots of old code repetition. The new ones will use HttpInterface via the autoloader instead.)

**Comment by mgp25** [comment]
Task done + probably (mostly sure) wont giving support to:

- checkpoint
- Registration

**Comment by SteveJobzniak** [comment]
@mgp25 Fantastic! :)
