### ISSUE TITLE
Private Messages

### ISSUE THREAD

**Issue by wehmoen** [mgp25/Instagram-API#108]
Hi,

is it possible to create and reply to private messages and message requests?

Kind regards,

wehmoen

**Comment by mgp25** [comment]
Yes, it's possible but you need to code it

Regards

**Comment by wehmoen** [comment]
Can you give me the api endpoint for this?

**Comment by mgp25** [comment]
I don't have it, but can be easily captured by disabling cert pinning.

Regards

**Comment by wehmoen** [comment]
What do you mean with "disabling cert pinning"?

**Comment by mgp25** [comment]
@wehmoen in order to capture the traffic and see all the requests, you need to disable the cert pinning, there are a lot of guides and info in google :yum: 

Regards
