### ISSUE TITLE
Both directMessage and directShare not working

### ISSUE THREAD

**Issue by mpooleery** [mgp25/Instagram-API#1084]
Code:
```

<?php

include '../../../../vendor/autoload.php';
require '../src/Instagram.php';

/////// CONFIG ///////
$username = '*****';
$password = '*********';
$debug = true;
$mediaId = '1459881917038355109_3537261993';
//////////////////////

$i = new \InstagramAPI\Instagram($debug);

$i->setUser($username, $password);

try {
    $i->login(); 

    echo 'Login success!'; 
    $i->directShare('mpooleery','1459881917038355109_3537261993', 'Your photo looks good.  Can we talk?'); 
    $i->directMessage('mpooleery','Your photo looks good.  Can we talk?'); 
} catch (Exception $e) { 
    echo 'something went wrong '.$e->getMessage()."\n"; 
    exit(0); 
} 
?> 

```
Truncated error log (post login, which was successful):

Login success!POST:  direct_v2/threads/broadcast/media_share/?media_type=photo
→ 638B
← 500 	 25B
RESPONSE: Oops, an error occurred.
something went wrong No response from server. Either a connection or configuration error.**

Hi @mgp25, @SteveJobzniak, I have been trying to get either of these functions to work, but without success.  Were these tested by others?

TIA!

**Comment by frrakn** [comment]
You need to use the usernameId and not the username as part of the method call.

**Comment by mpooleery** [comment]
@frrakn Thank you!  That seemed to work, but only for a few tries.  Other times, it looks like it went through, but the message or share didn't actually happen.  Has this happened to you?

**Comment by SteveJobzniak** [comment]
@mpooleery It was a bug which only allowed you to post 1 message per thread. Now fixed.

**Comment by mpooleery** [comment]
Thanks a lot!  It is working now!  Do you have an email I can reach you (apart from here)?

Thanks,
Manoj Pooleery <https://www.linkedin.com/in/manojpooleery>,
Skype: mpooleery.
