### ISSUE TITLE
Transcode error: Video file does not contain duration.

### ISSUE THREAD

**Issue by usef-enayati** [mgp25/Instagram-API#1086]
#uploadTimelinePhoto:
InstagramAPI\ConfigureVideoResponse: Transcode error: Video file does not contain duration.

Source:
if($type = 'image') {
     $uploaded = $this->i->uploadTimelinePhoto($upload,$caption);
      }

**Comment by mgp25** [comment]
@usef-enayati if you upload a photo, that can't happen. Review your code

Regards

**Comment by SteveJobzniak** [comment]
@mgp25 I finally know what he's done wrong.

The old code doesn't warn users if they lack ffmpeg. It just does nothing and returns null.

So he does not have FFmpeg installed. Hence video duration we send to server in his case is null.

I will make all ffmpeg-functions throw exceptions if FFmpeg is missing.

**Comment by SteveJobzniak** [comment]
Fixed https://github.com/mgp25/Instagram-API/commit/8f38bd8306b81f91c5066d2a4327c137ad22f275
