### ISSUE TITLE
Ideas? Severe bug in HD media delivery

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1088]
**WIPED THIS THREAD. FIX COMING.**

**Comment by SteveJobzniak** [comment]
Interestingly, it also seems like Instagram.php::_checkSettings always rebuilds the device and its User-agent every time the Instagram app version changes, which means the old code doesn't even maintain the agent statically. Weird. That looks like another bug to me.

**Comment by ping** [comment]
That's an interesting catch. Can you dump ``video_versions`` for both HD and non-HD devices? If you can provide the username whose feed has HD videos, I'd love to check it out for myself.

**Comment by SteveJobzniak** [comment]
I have done more testing: This situation only affects video files. Not photos (jpgs). Not video thumbnails (jpg). Just videos (mp4s).

@ping I'll see if I have time to make a test-file for this later.

**Comment by md726** [comment]
@SteveJobzniak I'm not sure if this is related to the user-agent as well, but I noticed with 2.x that image_versions2->candidates don't contain the highest available resolution of images. For example item with code BRsmBb9BEEY holds two candidates - in my example 750x547 and 240x175 - while the values in [original_width] and [original_height] say 1080x788 which I can verify with the Instagram Website that also servers the one with 1080x788

**Comment by joseflorido** [comment]
I think this is someway related with the other issue I posted about cropped
images. Some time ago the image versions included always many versions,
including square and original size, now it only includes two sizes.

**Comment by mgp25** [comment]
UA improvement + fix comming soon

**Comment by md726** [comment]
@jonataa It might be not related to the UA, at least I just tried a few agents with newer Android version and devices with bigger screen resolution but still no success with larger images. For now I'll keep on using my function that just removes the size part from the image url like for example s750x750/

`Instagram 10.8.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_US)`
`Instagram 10.8.0 Android (23/6.0.1; 480dpi; 1080x1920; samsung/Verizon; SCH-I545; jfltevzw; qcom; en_US)`
`Instagram 10.8.0 Android (23/6.0.1; 560dpi; 1440x2560; samsung; SM-G935T; hero2qltetmo; qcom; en_US)`

**Comment by SteveJobzniak** [comment]
I'm working on this now, I've written a user agent tester and am compiling a list of good and bad agents.

We're going to switch to a list of maybe 5 popular, super high resolution modern phone models. That way we'll still get lost in all the statistical noise (I bet they've got at least 200k users per popular phone model), and we'll have some very reliable devices instead of the current random madness.

There's also a huge problem with the old User-Agent generation which we won't make public. I'm going to rewrite the generation today to make it indistinguishable from real devices.

**Comment by SteveJobzniak** [comment]
And @md726: No, User-Agent has zero to do with ImageCandidates. They are always the same no matter what your device is.

Instagram only changes video URLs based on device.

**Comment by SteveJobzniak** [comment]
Okay my rewrite of User-Agent is close to done now. The issue will be solved soon. :-)

**Comment by SteveJobzniak** [comment]
Fun fact, this is how the analysis was done:

1. Query a narcissist's timeline. Someone sure to have lots of HD videos of themselves. Such as SelenaGomez or JustinBieber.
2. Scan for all videos.
3. Check their resolutions. The highest-quality "HD" videos are all 640 pixels wide (the height doesn't matter and can be less or more than 640).
4. If the user agent is bad, you will not get the maxres 640px-wide versions of the videos. You'll only get 480px wide or lower.

We'll soon have a rewritten UserAgent class, which is cleaner, reliably generates/upgrades agents, solves some serious problems of the previous generator, and most importantly: Only contains a list of about 6 different device models. Very popular, ultra-high resolution phones, guaranteed to give us max-res media for years to come. The agents I've researched are popular enough that we'll get lost in the statistical noise of all the Instagram users in the world.

**Comment by SteveJobzniak** [comment]
Okay after a lot of research and a ton of rewriting... it's finally solved. Enjoy.

https://github.com/mgp25/Instagram-API/commit/9fc3cddbc3d9c86a43c7cc96af5dfc533bfaee4e
