### ISSUE TITLE
Tried new version to upload video but got Upload of "ySV3L3L.mp4" failed. Instagram's server returned an unexpected reply.

### ISSUE THREAD

**Issue by thedangler** [mgp25/Instagram-API#1089]
Before I dump all the information, is there a specific type or size the video can be?

Thank you

**Comment by SteveJobzniak** [comment]
@thedangler It means Instagram's server is bugged out and has deleted all of your uploaded video chunks. I will edit that error message to be clearer.

But you should check $e->getCode(), for `ErrorCode::INTERNAL_UPLOAD_FAILED` and decide however you want to handle their server issue.

**Comment by SteveJobzniak** [comment]
```php
            throw new InstagramException("Upload of \"{$videoFilename}\" failed. Instagram's server returned an unexpected reply and is probably overloaded.", ErrorCode::INTERNAL_UPLOAD_FAILED);
```

**Comment by thedangler** [comment]
Ok? over loaded from what? my video was only 3MB?
I used the upload video example in the source code.

**Comment by SteveJobzniak** [comment]
@thedangler Overloaded from 7 billion people on this planet.
