### ISSUE TITLE
Can't Upload image

### ISSUE THREAD

**Issue by margibs** [mgp25/Instagram-API#109]
Hi I'm new to this instagram api was trying to upload an image but no luck :( 

`RESPONSE: REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=fcde999918ba6c6184ac452c4df7e976ece1ae37a56c93f3d4428a1da8056b3b.{"upload_id":null,"camera_model":"HM1S","source_type":3,"date_time_original":"2016:03:22 09:32:31","camera_make":"XIAOMI","edits":{"crop_original_size":[460,460],"crop_zoom":1.3333334,"crop_center":[0.0,-0.0]},"extra":{"source_width":460,"source_height":460},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"7a63803396c5da113987ce39288620f1","_uuid":"785fdd4b-8396-4341-852b-c366a0c25a29","_uid":"382881379","caption":"first sample"} RESPONSE: Oops, an error occurred. REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=81f9bc415afba5dec32ad2657605751aea99403c013e9213e4b5b3dfe54ec47b.{"_uuid":"785fdd4b-8396-4341-852b-c366a0c25a29","_uid":"382881379","id":"382881379","_csrftoken":"7a63803396c5da113987ce39288620f1","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status":"ok"}`

that's what the debugger says hope you can help me with it thanks

**Comment by mgp25** [comment]
@margibs you didnt upload the image correctly.

See:  `"upload_id":null`

Check it. Debug when uploading the media

Regards

**Comment by margibs** [comment]
Hi I'm passing the right path on the upload file

`$photo = 'C:\xampp\htdocs\social\public\uploads\instagram.png';
 $insta->uploadPhoto(public_path($photo), $caption = "Sample");`

what am I doing wrong with this code?

**Comment by wehmoen** [comment]
I also had the same problems under Windows. Try it with Linux. This works for me :)

**Comment by margibs** [comment]
thanks wehmoen. I want to try it on my online server what I'm I have a php version of 5.5.9 can't update it now cause I have a running sites on it.

**Comment by iq0n** [comment]
Try the following:

$photo = '**C:/xampp/htdocs/social/public/uploads/instagram.png**'  //forwardslashes

maybe it works...can't test right now but i think it worked for me @WIN 8.1 64Bit

**Comment by margibs** [comment]
I did @iq0n  still no luck but will try to figure it out on linux thanks for the comment.

**Comment by iq0n** [comment]
@margibs Then maybe your file is corrupt?

**Comment by margibs** [comment]
@iq0n 
where should I put this code?

$configure = $this->configure($upload['upload_id'], $photo, $caption);

**Comment by wehmoen** [comment]
Please post full debug log :)
