### ISSUE TITLE
Square cropped image missing from candidates list in response

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#1090]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Code:

```php
require("vendor/autoload.php");
$i = new \InstagramAPI\Instagram($debug);
$i->settingsAdapter = array(
  "type"       => "mysql"
);

$i->setUser(***, ****);

try {
  $mediafr = $i->mediaInfo('1471990490073506703_3065633702');
} catch (Exception $e) {
  echo $e->getMessage();
}

```

Error/Log/var_dump:

```php
POST: media/1471990490073506703_3065633702/info/ DATA: ig_sig_key_version=4&signed_body=0f6eda381e06ec0fc33724c3fa8010554f8d760223ee7a46042e42ab5c7902ff.{"_uuid":"b4c5a355-53cc-4b08-afbd-8d94fbfe20b1","_uid":4780792838,"_csrftoken":"pkTheTyKgMfWAG0g0YG4YHJi50Ba81qd","media_id":"1471990490073506703_3065633702"} ← 200 1.35kB RESPONSE: {"auto_load_more_enabled": true, "more_available": false, "num_results": 1, "items": [{"taken_at": 1489694962, "pk": 1471990490073506703, "id": "1471990490073506703_3065633702", "device_timestamp": 1489694958453, "media_type": 1, "code": "BRtj41BlaOP", "client_cache_key": "MTQ3MTk5MDQ5MDA3MzUwNjcwMw==.2", "filter_type": 0, "image_versions2": {"candidates": [{"height": 443, "width": 745, "url": "http://scontent-amt2-1.cdninstagram.com/t51.2885-15/e35/17333899_1325351507499954_3775508413346217984_n.jpg?ig_cache_key=MTQ3MTk5MDQ5MDA3MzUwNjcwMw%3D%3D.2"}, {"height": 142, "width": 240, "url": "http://scontent-amt2-1.cdninstagram.com/t51.2885-15/s240x240/e35/17333899_1325351507499954_3775508413346217984_n.jpg?ig_cache_key=MTQ3MTk5MDQ5MDA3MzUwNjcwMw%3D%3D.2"}]}, "original_width": 745, "original_height": 443, "user": {"profile_pic_id": "1438221642744908472_3065633702", "is_unpublished": false, "profile_pic_url": "http://scontent-amt2-1.cdninstagram.com/t51.2885-19/s150x150/16124364_578168955721740_7217400916943568896_a.jpg", "is_private": false, "friendship_status": {"following": false, "outgoing_request": false}, "is_favorite": false, "pk": 3065633702, "full_name": "ENIGMA SAPIOSEXUAL", "username": "duchess3.14", "is_verified": false, "has_anonymous_profile_picture": false}, "organic_tracking_token": "eyJzaWduYXR1cmUiOiIiLCJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7InNlcnZlcl90b2tlbiI6IjE0ODk3MjY1MzU1OTh8MTQ3MTk5MDQ5MDA3MzUwNjcwM3w0NzgwNzkyODM4fDU5MWJjMTEwMGZmZTcwMDcyY2JkOGUyODA2ODVmNTQ4ZjYxMGJhMjBkYTVhODNkMGFjNDhkYjVlNGFhNzZiZjciLCJ1dWlkIjoiMjMxMDZlMWY2MTliNDA0YmI5ZTM1MzQ5YzExZDA1ZjQxNDcxOTkwNDkwMDczNTA2NzAzIiwiaXNfYW5hbHl0aWNzX3RyYWNrZWQiOmZhbHNlfX0=", "like_count": 104, "top_likers": [], "has_liked": false, "comment_likes_enabled": false, "has_more_comments": true, "next_max_id": 17851324111164377, "max_num_visible_preview_comments": 2, "preview_comments": [{"text": "Her husband/boyfriend coming home early \ud83d\ude02\ud83d\ude02\ud83d\ude02", "bit_flags": 0, "user": {"is_verified": false, "profile_pic_url": "http://scontent-amt2-1.cdninstagram.com/t51.2885-19/s150x150/12093281_194937600837787_1466783660_a.jpg", "is_private": false, "pk": 2225307517, "full_name": "Bruce", "username": "mrbruce69miller"}, "created_at_utc": 1489702478, "status": "Active", "type": 0, "pk": 17862050857082668, "user_id": 2225307517, "created_at": 1489702478, "media_id": 1471990490073506703, "content_type": "comment"}, {"text": "Cumming before me .", "bit_flags": 0, "user": {"profile_pic_id": "1433298123115967522_1319780053", "profile_pic_url": "http://scontent-amt2-1.cdninstagram.com/t51.2885-19/s150x150/16123710_391199004561546_5679464525150027776_a.jpg", "is_private": false, "pk": 1319780053, "full_name": "MelluvsMel", "username": "melluvsmel", "is_verified": false}, "created_at_utc": 1489710281, "status": "Active", "type": 0, "pk": 17851324111164377, "user_id": 1319780053, "created_at": 1489710281, "media_id": 1471990490073506703, "content_type": "comment"}], "comment_count": 79, "caption": null, "caption_is_edited": false, "photo_of_you": false, "can_viewer_save": true}], "status": "ok"
```

----

### Describe your issue
The list of image candidate versions does not include a cropped square version that I believe it use to include before. Maybe the response itself changed or some bug was introduced?

Example:
MediaId: 1471990490073506703_3065633702
Only includes two versions:

- http://scontent-amt2-1.cdninstagram.com/t51.2885-15/e35/17333899_1325351507499954_3775508413346217984_n.jpg

- http://scontent-amt2-1.cdninstagram.com/t51.2885-15/s240x240/e35/17333899_1325351507499954_3775508413346217984_n.jpg

But does not include this other existing one (squared):

- http://scontent-amt2-1.cdninstagram.com/t51.2885-15/e35/c151.0.443.443/17333899_1325351507499954_3775508413346217984_n.jpg

**Comment by SteveJobzniak** [comment]
Their API replies have nothing to do with our library. We include all results they send us.

My theory: getUserFeed() includes squares, because they need to show squares in the list of images. But mediaInfo() (which will be renamed to getMediaInfo, oops, missed one), has no need for squares since it's only called when you view an actual image in-detail.

**Comment by joseflorido** [comment]
Thanks!

The thing is that getUserFeed() doesn't include squares anymore, it used to, and same for tag and place feeds. So, looks like they changed their response recently. Looking at the Android client, they are now showing non-squared images (ugly!), [screenshot here](https://www.dropbox.com/s/xribm5wragnp99o/Screenshot_20170317-094407.png?dl=0).

For now I will just manipulate the URLs to add the cropping parameters their image server needs and will keep an eye to see if the response goes back to include squared images.

Thanks again!

**Comment by SteveJobzniak** [comment]
@joseflorido Interesting. I guess they hated the autocropping's random image focus.

Anyway here are new renames for consistency:

https://github.com/mgp25/Instagram-API/commit/8dc32594c436295b88b1d7e94c0fb5fba7a81fec

I discovered the problem thanks to you pointing out mediaInfo. There were a handful of getters that didn't have a get-prefix and that has now been fixed.

**Comment by thinhpc** [comment]
Sorry for recomment in this. But something is wrong.

I try liamcottle library(which current not support anymore) to get mediainfo and it still get many square candidates in response:
[liamcottle.txt](https://github.com/mgp25/Instagram-API/files/1082454/liamcottle.txt)

and this is mgp25 get mediainfo response. Don't have square candidates:
[mgp25.txt](https://github.com/mgp25/Instagram-API/files/1082456/mgp25.txt)

this is post link:
https://www.instagram.com/p/BT-rNdFF-qy/
 
Hope @mgp25 can find out why.

**Comment by SteveJobzniak** [comment]
@thinhpc All reversed APIs talk to Instagram. The lists of media files comes from Instagram. We don't control the list.

The only reason why ours has no square candidates, and why liam (who ripped off our code) gets square candidates, is because we emulate a much newer version of the Instagram app.

Instagram delivers different content for different versions of their app. Now you know why we get no squares. ;-)
