### ISSUE TITLE
Warning: filesize(): stat failed for http://...

### ISSUE THREAD

**Issue by wowDaiver** [mgp25/Instagram-API#1093]
I cannot upload Video via url because php functions do not work with remote files...
What solutions are there?

**Comment by SteveJobzniak** [comment]
Download it and then give it to our class, you moron.

**Comment by SteveJobzniak** [comment]
Download it and then give it to our class from your local disk, you moron. Sorry, I feel like calling you a moron is an insult to morons.

This has to be the most pointless and obviously solved ticket I've ever seen.

**Comment by wowDaiver** [comment]
The moron is the one who copied the correct code for idiotic. In the previous version there was no such dependence.

**Comment by SteveJobzniak** [comment]
We never, ever intended you to be able to upload from URLs. That was a bug which happened because PHP's file reading functions work on URLs.

And the previous version read the whole file into memory. So a 100mb video would need 100mb of RAM.

The new version reads it in 4 pieces of 25mb each.

filesize() does not work on URLs. And we won't add that. Period. Especially because video uploads need to be retried up to 10 times which means 10 damn downloads+uploads.

Stop being a moron and just download the video yourself to a temp folder and then send it to our API.

**Comment by SteveJobzniak** [comment]
In fact I am now going to add some code to make it impossible to upload photos from URLs too. Both videos and photos will now refuse URLs.

**Comment by wowDaiver** [comment]
It is necessary to use a temporary directory I guessed right, the question was just about the ability to upload files directly. Maybe you've kept a method to do this. After the explanation it became clear why it is not worth doing. Was it difficult to say at once? And please excuse and not to call names for my English...

Code which works successfully:

`$tmpfname = tempnam("/tmp", "REP");`
`unlink($tmpfname);`
`$videoExt = pathinfo($post['url'], PATHINFO_EXTENSION);`
`if (strlen($videoExt) == 0) {`
`   $videoExt = 'mp4'; // Fallback.`
`}`
`$uploaded_file = file_get_contents($post['url']);`
`file_put_contents($tmpfname . "." . $videoExt, $uploaded_file);`
`try {`
`    $response = $this->ig->uploadTimelineVideo($tmpfname . "." . $videoExt, $post['caption']);`
`[...]`

**Comment by SteveJobzniak** [comment]
@wowDaiver We get a lot of people with very dumb tickets here and are tired of it. Normally we don't even reply.

But I am glad you understand why URLs should not be used. And your new solution looks fine. A bit mess but it's the right idea. ;)

**Comment by SteveJobzniak** [comment]
Here's an example of the stupidity we get daily:

https://github.com/mgp25/Instagram-API/issues/1094

That's someone who is asking us about his personal project where he isn't even using our Instagram-API. Sigh.

And we get people asking about how to code in Python.

Just all kinds of morons. And we're tired of it. ;-)
