### ISSUE TITLE
{"status": "fail", "message": "Text is missing"}

### ISSUE THREAD

**Issue by pishnok** [mgp25/Instagram-API#1094]
hi,i trying to send direct message . . .

i get this  :
{"status": "fail", "message": "Text is missing"}

my request :
$header = make_header("{'recipient_users':'2894270461,4332918657','thread_ids':'0','Text':'test','client_context':'{$guid}'}"); 

where is the problem from?

**Comment by mgp25** [comment]
@pishnok there is a debug log built-in, please copy and paste your debug log

and copy and paste your script code

Regards

**Comment by SteveJobzniak** [comment]
@pishnok Wtf is make_header? That is not our function. Closing for unrelated.

And "Text is missing" is their API reply and means you are not supplying whatever the hell that is.

**Comment by SteveJobzniak** [comment]
@pishnok Wtf is make_header? That is not our function. Closing for totally unrelated to this API. You are lucky we even responded to this idiocy.

And "Text is missing" is their API reply and means you are not supplying whatever the hell that is.

**Comment by pishnok** [comment]
I apologize for this type of question  -=(#

scrip:
`<?php
include 'db.php';
$id_user=$_GET['id_user'];
$id_user_me=$_GET['id_user_me'];
$stook= '3';
$num= '1';
$login_url = "accounts/login/";

$guid = make_Guid();

$device_id = 'android-'.$guid;


    $username_id;        // Username ID
    $token;              // _csrftoken
    $isLoggedIn = false; // Session status
    $rank_token;         // Rank token

function request($url,$post_data,$cookies,$post,$username){

    $agent = 'Instagram 10.7.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)';

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://i.instagram.com/api/v1/'.$url);
    curl_setopt($ch, CURLOPT_USERAGENT, $agent);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    if($post){
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
                    
    }

    if($cookies) {
     
        curl_setopt($ch, CURLOPT_COOKIEFILE,'cok/'.$username.'.txt');
          
   


    } else {
        curl_setopt($ch, CURLOPT_COOKIEJAR,'cok/'.$username.'.txt');
  
    

        
            }
 
    return curl_exec($ch);
          
}   

function make_Guid() {
    return sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
      mt_rand(0, 0xffff), 
      mt_rand(0, 0xffff),
      mt_rand(0, 0xffff),
      mt_rand(0, 0x0fff) | 0x4000,
      mt_rand(0, 0x3fff) | 0x8000,
      mt_rand(0, 0xffff), 
      mt_rand(0, 0xffff),
      mt_rand(0, 0xffff)
);

}
function make_header($req){
    $req = str_replace("'",'"',$req);
    $sig = hash_hmac('sha256', $req, '9b3b9e55988c954e51477da115c58ae82dcae7ac01c735b4443a3c5923cb593a', false);
    return 'ig_sig_key_version=5&signed_body='.$sig.'.'.str_replace("+","%20",str_replace("-","%2D",urlencode($req)));
    
        
};

  

  $txt = file_get_contents('cok/'.$username.'.txt');
  $txt1 = strchr($txt,"csrftoken");
  $sec= str_replace("csrftoken", "", $txt1 );
  $ssss= substr($sec,0,33);
  $ssss= trim($ssss) ;

  

 $header = make_header("{'recipient_users':'2894270461,4332918657','thread_ids':'0','text':'slm','client_context':'{$guid}'}"); 
  $post = request('direct_v2/threads/broadcast/text/',$header,true,true,$username);
  echo $post;
   
  $tedad =substr_count($post,'ok') ;
 // echo $tedad;
  if($tedad== "1"){

}
else{
// echo "دوباره وارد شوید";
 
}
  

?>`

**Comment by mgp25** [comment]
Im sorry, that's not API related. Locking issue
