### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by mangledbottles** [mgp25/Instagram-API#1095]
Connection Issue
---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Code:

```php
include './instagram/vendor/autoload.php';
require './instagram/vendor/mgp25/instagram-php/src/Instagram.php';

$i = new \InstagramAPI\Instagram(true, false);

$i->setProxy("5.63.**.**", 9999, "****", "****");
#or
$i->setProxy("http://5.63.**.**:9999:****:****");

$i->setUser($username, $password);

try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}

$followers = $i->getSelfUsersFollowing();
var_dump($followers);
```

---

### Describe your issue
There seems to be a problem when using a proxy. In versions previous to all these new updates, using a proxy worked fine. However, now when using a proxy, the response on debug is blank and seems functions don't execute.

The functions works fine without proxy, but when implemented -> no response. The proxy does work with Instagram, works on the app & website. When I looked through the 'src/instagram.php', there no longer seems to be the same proxy setter as this has been changed to guzzle.

I would have to believe this is either a bug or a function that has been removed accidentally with all the new updates!

Thanks :)

**Comment by SteveJobzniak** [comment]
Hi! Thanks for taking the time to provide a proper report. :) The proxy must now be specified in Guzzle format. Check the source code in src/Instagram.php for "setProxy".

And the Guzzle proxy string format? Research it online. ;-)

**Comment by mangledbottles** [comment]
Thanks Steve :)
To anyone who gets stuck on this, here is solution:

```php
# when proxy doesnt need authentication
$i->setProxy(['proxy' => 'tcp://192.168.1.1:8080']);

# when proxy needs authentication
$i->setProxy("http://user:pass@5ip:port");
```

Reference: http://docs.guzzlephp.org/en/latest/request-options.html#proxy

**Comment by SteveJobzniak** [comment]
@mangledbottles Nice of you to share that for anyone who finds this ticket later! 👍  :-) I wish all users were this nice.

Anyway, I haven't really researched much about their format, but I suspect that `tcp://192.168.1.1:8080` is for SOCKS proxies, and `http://user:pass@5ip:port` is for HTTP proxies.

As for your first example, it's misformatted since we're actually setting the "proxy" array key to wahtever you've given us via setProxy().

So this:

```php
$i->setProxy(['proxy' => 'tcp://192.168.1.1:8080']);
```

Should actually be written like this:

```php
$i->setProxy('tcp://192.168.1.1:8080');
```

Basically, in Guzzle's example docs of:

```php
$client->request('GET', '/', [
    'proxy' => [
        'http'  => 'tcp://localhost:8125', // Use this proxy with "http"
        'https' => 'tcp://localhost:9124', // Use this proxy with "https",
        'no' => ['.mit.edu', 'foo.com']    // Don't use a proxy with these
    ]
]);
```

Our setProxy() is setting the inner array's contents:

```php
    [
        'http'  => 'tcp://localhost:8125', // Use this proxy with "http"
        'https' => 'tcp://localhost:9124', // Use this proxy with "https",
        'no' => ['.mit.edu', 'foo.com']    // Don't use a proxy with these
    ]
```

So anything that you can pass into "proxy" in Guzzle will work in this library.

Kinda pointless though, since we always do all API requests over HTTPS, and we don't have any need for blocking different hosts via "no".

So really, all people should do is pass in a single string, which gives us this final correct format:

```php
// Socks proxy? Not sure.
$i->setProxy('tcp://192.168.1.1:8080');

// HTTP proxy needing authentication.
$i->setProxy('http://user:pass@5ip:port');
```

Enjoy! :)

**Comment by mangledbottles** [comment]
Thanks again xD @SteveJobzniak

**Comment by cosinus90** [comment]
I'm still unable to use socks proxy with authentication.
My attemts:

`
	$ig->setProxy('tcp://user:pass@1.2.3.4:15098');
	$ig->setProxy('socks5://user:pass@1.2.3.4:15098');
	$ig->setProxy('socks5h://user:pass@1.2.3.4:15098');

 	$ig->setProxy([
		'proxytype' => CURLPROXY_SOCKS5, 'proxy'=>"1.2.3.4:15098", 'proxyuserpwd'=>'user:pass'
	]); 
`



in the same time curl works fine with the following options
`['proxytype' => CURLPROXY_SOCKS5, 'proxy'=>"1.2.3.4:15098", 'proxyuserpwd'=>'user:pass']	`

Any ideas?
