### ISSUE TITLE
filter_type is not applied to uploaded photos,  filtered image is not available in my instagram

### ISSUE THREAD

**Issue by dkozlov** [mgp25/Instagram-API#1096]
## PLEASE FOLLOW THE GUIDE BELOW, OTHERWISE WE WILL DELETE YOUR TICKET WITHOUT ANSWERING IT

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include below *code* that will replicate the error, and the *error log/traceback*.

Code:

```php
include __DIR__.'/../vendor/autoload.php';
require '../src/Instagram.php';

/////// CONFIG ///////
$username = 'user';
$password = 'password';
$debug = true;
$truncatedDebug = false;

$photo = '/home/user/1.jpg';     // path to the photo
$caption = 'test';     // caption
///////////////////////

$i = new \InstagramAPI\Instagram($debug, $truncatedDebug);

$i->setUser($username, $password);

try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}

try {
    $i->uploadTimelinePhoto($photo, $caption, null, 'Moon');
} catch (Exception $e) {
    echo $e->getMessage();
}
```

### Describe your issue

filter_type is not applied to uploaded photos,  filtered image is not available in my instagram

**Comment by SteveJobzniak** [comment]
Thank you for the properly filled out issue report! 👍 

The problem is that you need to provide filter choice as one of Instagram's internal numbers.

The `$location` and $filter` parameters are not well documented.

**Comment by dkozlov** [comment]
Could you please provide correct $filter parameters? Because the default parameters in repo are not working properly.
