### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by siputra12** [mgp25/Instagram-API#1097]
Why always like this
Array ( [0] => HTTP/1.1 400 Bad Request Content-Language: en Cache-Control: private, no-cache, no-store, must-revalidate Date: Sun, 19 Mar 2017 07:30:50 GMT Vary: Cookie, Accept-Language Content-Type: application/json Pragma: no-cache Expires: Sat, 01 Jan 2000 00:00:00 GMT Set-Cookie: mid=WM4zqgABAAHqzI8cZzybeNUCI2EK; expires=Sat, 14-Mar-2037 07:30:50 GMT; Max-Age=630720000; Path=/ Set-Cookie: csrftoken=nMyVBqXeeIOlDjag6s5l5kABxkAOIdft; expires=Sun, 18-Mar-2018 07:30:50 GMT; Max-Age=31449600; Path=/; Secure Connection: keep-alive Content-Length: 48 [1] => {"status": "fail", "message": "invalid request"} )

I use script instagram regristation, please help me, i have follow your script

**Comment by SteveJobzniak** [comment]
Registration script is outdated and will be deleted. It's mostly used by spammers, which we hate and do not allow.
