### ISSUE TITLE
Images sent via API are not search by tags

### ISSUE THREAD

**Issue by sofer-eg** [mgp25/Instagram-API#11]
I was sending image via this API, add some tags in caption, from another user make search by tag, and do not found any posts. When i do the same manually from instagram app, post found by tag.
Same thing when i send post to user via direct, user see label "No photo to display".
At the same moment I, and my followers can see uploaded images in feed.

**Comment by ruscon** [comment]
> Same thing when i send post to user via direct, user see label "No photo to display".
:+1:

**Comment by Werewolve** [comment]
Same here! Images sending via this api are not indexed and could not be found by hashtags from other users. Seemingly is Instagram still recognize that these image are not uploaded on the official way!

**Comment by rpw98** [comment]
I'm having the same issue. Photos uploaded can't be shared via direct message.

**Comment by rpw98** [comment]
Tried the latest version. Same result, photos can't be shared via direct message :-(

**Comment by rpw98** [comment]
Apparently Instagram can tell these photos were not uploaded from their app.

**Comment by mgp25** [comment]
Images are now found by tags.

Regards
