### ISSUE TITLE
User Feed API Pagination

### ISSUE THREAD

**Issue by putraxor** [mgp25/Instagram-API#110]
User's feeds only get last 18 posts

**Comment by RageBrahimi** [comment]
Please search before you post an issue. Use similar method as [here](https://github.com/mgp25/Instagram-API/issues/54)
**HINT:** It's the Max ID part you need.

**Comment by xteraflopx** [comment]
@putraxor Damn, do you just come on to Github and complain about how the code doesn't do what you want? Do you realize that this uses the Instagram PRIVATE API and is against their terms of use? mgp25 isn't your slave to develop software for you. People like him and I spent weeks reverse engineering the app and figuring out everything by ourselves. What are you going to do when mgp25 no longer updates this repository? Are you just going to give up? How about you figure something out for yourself!
