### ISSUE TITLE
Announcement: New Feature: ImageAutoResizer Class

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1101]
We're getting closer to the official release of 2.x. And what better way to celebrate it than with a fantastic new class by the brilliant @valga!

This class lets you provide any input image, and it will automatically process the image to crop and resize it to match your desired specifications, while also ensuring that the specifications (aspect, size, file format) fit Instagram's requirements.

With this class, there will be no more server rejections of our image files. And we can create cute square images or whatever other (allowed) aspect we want! :-) ✌️ 

Note that you must use the class manually on every image, and tell us to upload the paths you get from the class. Read src/Utils/ImageAutoResizer.php. It is very well documented. Use your brains! ;-)

**Comment by SteveJobzniak** [comment]
Now Merged: https://github.com/mgp25/Instagram-API/commit/52dff97e68ba552116dfabc4669ac43248188d85.

**Comment by golches** [comment]
the picture must be file :( we can't use a javascript canvas base64 image

**Comment by SteveJobzniak** [comment]
2.x is being released as we speak. Closing this thread. It will be covered in the release thread.
