### ISSUE TITLE
get all followers of user

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#1103]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

###Context of my question

When I'm trying to get all followers from a user sometimes instagram return a pagination token like 
"KEEA4N8OqM2rQhQoXgCSQU52FElWAvYUTHYUzY0AApxOdhSQQ5Vw9kx2FPVaA2kQTXYUF8oCEzFOdhSbjIDUY012FBbI2d6j3VYA" 
and sometimes it returns the number of users already loaded: 200 -> 400 -> 600 ....

In the case 1, after few requests i'm getting repeated users, so if I dont check if the users is already on my list I will be leading to infinite loop that answers me the same users

In the case 2, instagram limits the pagination to 1800, so i can't load more than 2000 users.

###Questions:
Is it an expected behavior? or i am doing something wrong in my code

I cant really identify the standard that makes instagram return the pagination number, or token since it for the same userId it seams to return both possibilities... does anyone know?

I'm trying to construct an statistics page that show which are the most active followers, if most of engagement on one feed comes from followers or just curious users and things like this... actually i didn't test yet with users with more than 10k followers, I'm limiting my tests to 8k but even with this restriction is not working properly

**Comment by mgp25** [comment]
@bolds07 Expected behaviour + duplicated issue. You will find more info about this in closed issues

Regards

**Comment by bolds07** [comment]
i read all the issues related to it and nobody had an explanation about that....

I can't see a maximum limit to pagination or repeated return on getFollowers as an expected behavior since on my cellphone i can scroll down for hours the followers of any famous instagramer...
