### ISSUE TITLE
Direct dialogs

### ISSUE THREAD

**Issue by CashCode** [mgp25/Instagram-API#1104]
Hey! Is there any option to use pagination in ->getV2Inbox() ?
It shows only first 20 dialogs.
Is there any method to read dialog fully? Couldn't find it...
Thanks!

**Comment by mgp25** [comment]
```php
public function getV2Inbox(
        $cursorId = null)
```

Use `cursorId` in the same way as `maxId`. Please read source before opening a new issue

Regards

**Comment by CashCode** [comment]
Thanks, now I found in github sources, all is well documented 👍 
I have installed from composer, there was no comments and no parameter $cursorId
Looks like that
```
    /**
     * I dont know this yet.
     *
     * @throws InstagramException
     *
     * @return V2InboxResponse v2 inbox data
     */
    public function getv2Inbox()
    {
        return $this->request('direct_v2/inbox/')->getResponse(new V2InboxResponse());
    }
```

**Comment by mgp25** [comment]
@CashCode no problem. New release is almost done, so you can migrate to master code

Regards
