### ISSUE TITLE
timelineFeed, how to get id?

### ISSUE THREAD

**Issue by vasiliilevkovskii** [mgp25/Instagram-API#1106]
## PLEASE FOLLOW THE GUIDE BELOW, OTHERWISE WE WILL DELETE YOUR TICKET WITHOUT ANSWERING IT

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [ x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

How to get id from timelineFeed()? Problem with [media_or_ad] Object

My code:

    $a = $i->timelineFeed();
    $items = $a->getFeedItems(); 
    
    $id = $items[0]->getId();           //not work

Response:
// print_r ($items[0);

stdClass Object
(
    [media_or_ad] => stdClass Object
        (
            [taken_at] => 1490009291
            [pk] => 1474627275411771777
            [id] => 1474627275411771777_533211544
            ............

**Comment by SteveJobzniak** [comment]
@vasiliilevkovskii Works in dev-master (2.x beta, see announcement thread ticket about it).

```php
require __DIR__.'/vendor/autoload.php';

$ig = new \InstagramAPI\Instagram(true);

$ig->setUser($username, $password);
$ig->login();

$feed = $ig->getTimelineFeed(); // works
$items = $feed->getFeedItems();
$id = $items[0]->getId();

var_dump($id);
```
