### ISSUE TITLE
Announcement: CODE GUIDELINES WHICH **MUST** BE FOLLOWED!

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1110]
With 2.x ~very close to release~ released, it is time to _enforce_ code quality standards to prevent this project from completely breaking down into a buggy shitpile again.

🔴 🔴 🔴 

**These strongly enforced guidelines _ensure_ that we will never destroy the project by slowly slipping back into the horrible, extremely buggy, undocumented mess that was v1.x of this library.**

🔴 🔴 🔴 

Years of unfiltered pull requests and idiocy had lead 1.x to a total mess where some contributors clearly hadn't even bothered to take 5 _seconds_ to check their code. If you can't do it properly, then ask _someone else_ to do the changes.

There is now a document which, among other things, describes PSR-4 class autoloading, clean commits, how to handle/document exceptions, how to structure function arguments, naming clear variables, always adding/updating PHPdoc blocks, and how to verify that your changes don't _break everything_ when performing big changes to existing functions or adding brand new functions and classes.

https://github.com/mgp25/Instagram-API/blob/master/CONTRIBUTING.md

That document is not some weak, loose "recommendation". It's a _total requirement_, to prevent turning this project into a totally broken, buggy mess again. Skipping those steps just means other people will have to work twice as hard to fix your broken contributions. It's not nice to your fellow humans to expect them to take on _your_ responsibilities.

Everyone who wants to contribute again needs to familiarize themselves with _everything_ in that document. Nobody wants to go back to the broken, buggy mess.

Here's hoping for a new future where 2.x of this library won't break _every week_ from shitty, sloppy "contributions" anymore.

Thank you. 🌻 And a big thank you to everyone who _thinks_ before they commit, and who has helped out on this project in the past!

**Comment by PendoNL** [comment]
Just a totally unrelated comment: but I'm unable to donate using PayPal from the Netherlands.. might want to fix that for an incoming extra for all your efforts! Great work!

**Comment by SteveJobzniak** [comment]
@PendoNL Wow, that would be _deeply_ appreciated after 22 tough days of having absolutely no life at all and slaving over this code every waking moment (sadly true). The project founder is mgp25, and I joined this project 22 days ago due to the total mess it was in and how badly it needed a rewrite. I'm the no-life madman responsible for the massive 2.x rewrite and am currently at 218 tasks finished in these three weeks.

The code was a total mess and this has been a _lot_ more work than I ever anticipated. It's finally object-oriented, clean and stable and really nice to use in your projects... And _I'm_ about ready to _collapse_... I never asked anyone for anything in return for this huge rewrite. If you want to help soothe the wounds (it sounds like you want to give thanks for all the insanely hard work ;-)), then sure, my personal PayPal is stevejobzniak at justarmindale.com, and it should work fine. It's up to you. I'd definitely really appreciate it! Your message stunned me.

**Comment by PendoNL** [comment]
Don't expect amounts, I'll donate what I can mis at the moment! But I greatly appreciate open-source work and all efforts put into things like this. Without people like yourself and @mgp25 I wouldn't be able to built what I need. So many thanks for the hard work, I for one can't wait for v2 to be released! 

I've started using the code since last sunday actually, still facing some little problems at the moment but it's starting to become clearer every time (geo-checks by IG, the saved cookies per account, etc.). At the moment I'm unable to post using the code (login succeeds), hopefully I'll get that sorted out soon enough.

Anyway, as I said: thanks for all the input. I'll definitely will put something into both of you PP accounts as token of my appreciation for the work!

**Comment by SteveJobzniak** [comment]
@PendoNL Aww that is so sweet of you. I just received the email from PayPal. Thank you so much, it certainly makes me very happy that you appreciate my hard work that much. A donation was something I never expected and I am very grateful. <3

You definitely started using this project at the right time. I began the rewrite because the old code was extremely buggy and unusable and I decided to help fix it. Now my own personal Instagram project (using this library) is long-done and uses 2.x of this library, with really clean and stable code, exceptions, object oriented programming, fast Guzzle HTTP communication, reliable settings-storage, and about a hundred bugs fixed. It's a nice feeling to have a strong, object-oriented library that can be trusted.

We're very close to release now. I'm working on the last thing we need before release: The ability to add special cookies to timeline album uploads. After that, it's release-ready. So while I don't like giving estimates (in case we find an issue and have to delay), I would say maybe 1-2 days until officially releasing 2.x. :-)

Anyway, thank you so much again for the donation, you certainly made my life brighter after this hard and exhausting work. :-)

**Comment by PendoNL** [comment]
Haha, you're very welcome!

2.x sounds great, I might update my dependences to use the dev-master branch sooner! Since the project isn't that big yet I recon the switch shouldn't be too hard. 

P.s. I found the bug: images should be jpg and not png. Which is a little bit strange, because I tested the platform using PNG's yesterday and they only started to return errors in the evening. Everything looks fine now, tweaked the script a little bit. I'm finally able to schedule and publish posts for my clients without having to open 3 different app's and Instagram profiles!

**Comment by SteveJobzniak** [comment]
@PendoNL The switch to 2.x is pretty easy. Mostly these things:

- Wipe your old settings storage (file, mysql, whatever). Just delete it completely. The new format is totally different. If you used the old default file-storage, the settings are hidden in vendor/mgp25/instagram-api/src/data/. In 2.x the default path is vendor/mgp25/instagram-api/sessions/. Anyway just delete that.

- All internal response classes and object model classes are moved, but most have the same names as before. A handful have been renamed. Mostly, this would involve you doing something like `use InstagramAPI\Response\Model as IGModel;` and then `IGModel\Item`, `IGModel\User`, etc, anywhere that you previously used `\InstagramAPI\Item` etc.

- Many public-facing functions have been renamed to more logical names. Just grep the new source for your old calls and if you can't find them, find the new name. I think I've kept the in-progress thread up to date with the list of changes.

- Exceptions are totally different now, you no longer use getCode(). You get unique ones per-error. So you can now do `catch \InstagramAPI\Exception\EndpointException $e` to catch function-specific errors, and then just $e->getMessage() to see what Instagram told you is the problem. And there's about a dozen other exceptions. But ALL of them derive from `\InstagramAPI\Exception\InstagramException`.

- There are new utility classes you will like. Look at `src/InstagramID.php` and `src/ImageAutoResizer.php`. The latter will take your PNG and make it a JPG automatically (just create a class instance with your original input image, and getFile() on the class instance to get a processed path, and then send that good image path to the upload-function), and it's probably a good idea for most users to always run all images through it since it validates and auto-crops and auto-resizes so that you won't get any file upload errors. AND it's written intelligently so it only processes the input file if it's an illegal size, format or ratio.

**Comment by PendoNL** [comment]
Impressive! I think it's all going to be even easier for me since just a few things affect my application. It's purely used for login and posting images, no other functions. Maybe a suggestion: in my code I've used code like this when a login fails (I then force a user to re-enter their password to make sure it's valid, I haven't found a specific error message when authorisation on instagram.com is needed, but I'll sort that out with the next tests).

```php
@unlink('../vendor/mgp25/instagram-api/src/data/' . $this->username);
```

It would come in very handy if there was a function like `$instagram->emptyCacheFor('username');` or something. As far as I could see, the logout() method doesn't do that. Or did I mis something?

Sorry for spamming your thread by the way. Might not be the right place to ask.

**Comment by SteveJobzniak** [comment]
@PendoNL It's fine (to talk in this thread).

As for the exceptions you're after:

`InstagramAPI\Exception\LoginRequiredException`: Means the server is telling you that you are logged out and need to login again.

`InstagramAPI\Exception\CheckpointRequiredException`: Means the server is telling you that you must validate your account (by logging in via Instagram.com or the real app, and answering a "code" test via email or SMS). The most common reason that you get this error is that you moved your local script to a server. They detect the new geolocation that has never been on your account before, and they lock it for safety. But after a single unlock to verify the new location, you are fine to keep using the API from your new server/location! :)

And as for your question about unlinking... No, you don't need to do that. We do not store your password. Every time you call setUser() you provide the password to us, and we use that to relogin if we need to.

Btw: Always, always, always call login() every time after you've called setUser(). It does some critically important things to look like a real app client and avoids you getting banned by Instagram.

So look at the new `examples/` folder of the 2.x tree. It has clean examples for how to use the API.

**Comment by SteveJobzniak** [comment]
Let me know if you have more questions. I do not mind at all.

**Comment by SteveJobzniak** [comment]
Now to explain why unlinking/deleting the session-folder contents is *VERY* dangerous:

Every time that we need to create a new settings-storage for a user, we generate a new DEVICE FINGERPRINT. And if you keep deleting the settings, we will never have a chance to reuse the old fingerprint. So Instagram will see HUNDREDS of different hardware devices connected to that user's account. It means byebye, banban account.

**Comment by SteveJobzniak** [comment]
One last thing: Don't use our private API for any user-apps you are building. You must use Instagram's official API for that. Because our API is not made to handle more than maybe 10 users. More than that and your IP risks getting silently blacklisted as a badguy by Instagram. They count the number of "devices per household", and you cannot safely have more than 5-10 devices on an IP for them to think you are still REAL APP USERS.

**Comment by SteveJobzniak** [comment]
For the accounts you've already gotten flagged: I suggest that you go to Instagram.com and change the password on those accounts. That will clear all of the dangling "loose" hardware fingerprints from that user account. It basically tells Instagram to de-authorize every currently authorized device fingerprint.

And lastly: Yet again, if this is for a multi-user application where people are logging in to Instagram via you, then you must use the official (free) 3rd party API, by submitting an app description to Instagram and getting an API key. They allow 5000 API requests per USER per hour, exactly the same as the private API. And their official API won't lead to you getting blacklisted as a bot due to having tons of users, if that's what you're intending to have.

**Comment by SteveJobzniak** [comment]
Think of it like this: This unofficial API is emulating a REAL Android device connected to the account. Every time you login, it's like you buy an Android phone, install Instagram on it, and login to the account.

Instagram will not believe you if you have 200 different phones connected to a single account. ;-) They will ban you.

**Comment by SteveJobzniak** [comment]
That is why we re-use the session (aka previously "data") folder. And that is why we maintain all cookies, etc, just like the REAL app does.

As for `logout()`: All it does is pretty pointlessly just telling Instagram to log out from your session. Maybe that unregisters the device on their end, I don't know, we'd have to check their server code. ;-)

**Comment by SteveJobzniak** [comment]
Oh and as for their blacklisting, and its effects: It's a silent blacklisting. Things will SEEM to work. But you can never again register new accounts via that IP address. And ANY account you log in to via that IP will trigger security checks (checkpoint) locking of the account you tried to use. It's a bad situation to be in.

As it says in the terms for this private repo: It's not intended for mass-user usage. It's for small private projects (scrapers, statistics generators, etc, fun little projects).

**Comment by SteveJobzniak** [comment]
I'll clarify one more thing: `setUser()`'s password field is ONLY used by us during the subsequent `login()` call, and ONLY if our cached device-session (cookies) has been invalidated/expired/is missing/whatever.

Because exactly like the official app: The user logs in ONCE, and then they remain logged in forever. The app just keeps "working" with no need to login every time.

**Comment by SteveJobzniak** [comment]
I don't mind chatting here and using this thread to help you out. I can just delete all the offtopic discussion afterwards. So let me know if you have any question at all! :-)

**Comment by PendoNL** [comment]
Great response, more than I expected to get! So first of: the application I use is just for myself and one of my clients Instagram. I'll make sure to keep the maximum in mind or I'll sort out to use proxies if I even get that much clients. I won't go over too many devices anytime soon and I definitely won't use it for spamming purposes, most posts are even manually submitted.

The reason I'm clearing the data directory is because of the following (but correct me if it's still bad practice): once I'm logged in using your code I can use the API, but once I change my password it keeps using the old data and isn't updating the data directory with a new fingerprint/token. I had to remove the data folder in order to get the new password to work. Maybe it's a bug in the script? I'm not sure.. I'll try to stick to your setup as mentioned above as much as possible.

One thing I'm curious about is how does Instagram handle public networks? Like, in large communities/open areas where many people might use Instagram. Do these accounts get flagged aswel? I'd say that besides not connecting too many accounts from the same IP address, not posting daily is also a good practice (f.e. I'm posting max 3 posts per account per week. Meanwhile they're not used by the server).

Thanks again for the info!

**Comment by PendoNL** [comment]
Also, what if I manage the accounts of multiple clients from my office. Would that mean these accounts are in danger aswel? Or is this a different use case since they share the same device ID?

**Comment by SteveJobzniak** [comment]
@PendoNL Ah, just you and a friend/client is perfect. That's definitely a good use for this library then! And this library supports much more features than the official API, since we really act like a real device.

And good point about proxies. We support proxies very reliably now in 2.x with `setProxy()`. You can definitely solve it that way. 5-10 users ("devices") per IP is the limit to keep in mind.

I'll also clarify: Every time you re-use an existing settings-storage for a username (aka "we find the user in the settings-storage"), then we re-use the same hardware fingerprint (in 2.x.) for everything. So each user will only get assigned 1 random device ID the first time it's created, and then it will forever re-use that settings-storage ("device id" etc) even if you change password and need to relogin etc. So the 'sessions' storage is really critical and should not be messed with. At least the '-settings.dat' file. The cookies file can safely be deleted (but there's no need to do that either).

As for checking if a password is wrong, in 2.x the login() call throws `\InstagramAPI\Exception\IncorrectPasswordException` in that case.

Now, for the "how does it handle public networks?" question, the answer seems to be that they manually whitelist those IPs.

As for the "what if I manage multiple clients from my office?". Well, every username gets a totally unique device ID. Our library does not re-use a single device ID for all accounts. Because Instagram doesn't handle multiple accounts on 1 device ID very well. It will somewhat reliably let 2 users have the same device ID, but 3+ it will start randomly dropping logged in sessions. So we instead generate 1 "device fingerprint" per-USERNAME.

**Comment by SteveJobzniak** [comment]
So as for whether they are in danger: They're in danger if you keep deleting the settings-storage, or if you exceed the max allowed devices-per-IP limits.

If you have 5-10 logins at most, then they're going to be fine. And you should never delete the settings-storage...

Now about that...

**Comment by SteveJobzniak** [comment]
> once I'm logged in using your code I can use the API, but once I change my password it keeps using the old data and isn't updating the data directory with a new fingerprint/token. I had to remove the data folder in order to get the new password to work. Maybe it's a bug in the script? I'm not sure.. I'll try to stick to your setup as mentioned above as much as possible.

That was probably a bug in 1.x of this library. I remember fixing a serious login bug if the user password has changed/old session has expired.

In 2.x `login()` perfectly detects when your session is invalid, and re-logs you in using the new password (but same device fingerprint via settings).

**Comment by PendoNL** [comment]
Sounds like I'm best of upgrading to 2.x already. I'll remove all references that delete the storage folder as I understand it's importance. Thanks for pointing that out before I'm in trouble ;-)

Maybe it's easy for them to distinguish open networks from server IPs by simple running some cli commands to see available websites etc. on the IP. I guess it's pretty easy to find out if an IP response to certain ports a regular network won't respond to. 

To sum it all up; this would be the best setup possible:

```php
$i->setUser("user", "pass");

try
{

    $i->login();

    try 
    {

        $i->uploadPhoto([..]);

    } catch(\InstagramAPI\Exception\InstagramException $e) {

        // an instagram error occured while post

    }

} catch(\InstagramAPI\Exception\IncorrectPasswordException $e) {

    // Business logic to force a user to check and set their password again

} catch(\InstagramAPI\Exception\CheckpointRequiredException $e) {

    // Business logic to let a user approve the login on instagram.com

} catch(\InstagramAPI\Exception\InstagramException $e) {

    // Catch all other errors here
    // I can assume the password is correct, right?!

}
```

**Comment by SteveJobzniak** [comment]
@PendoNL I think I researched this a long time ago and they had some website where you can apply to be whitelisted as a public hotspot/cafe on all Facebook/Instagram sites actually. ;-)

And yes your code looks right. setUser can actually throw too in 2.x. (stuff like no username provided), so put it in the try-catch.

Also, I suggest changing your vars from `$i` to `$ig`, since $i is a loop variable and we've moved to $ig for that reason. Still short, and much better.

And yes, your exception annotations are correct!

InstagramException is a nice catch-all for anything. If you only want to catch specifically error messages for API endpoints like the `uploadTimelinePhoto()` call in 2.x (it's no longer `uploadPhoto()` with tons of messy parameters)., then catch EndpointException. That's the error that happen when an endpoint says something endpoint-specific such as "User not found" etc.

As for image handling: Remember to use `$resized = new ImageAutoResizer($photoFilename); $ig->uploadTimelinePhoto($resized->getFile(), ...);`. Note that the autoresizer auto-deletes the trash file after it falls out of scope. Read its class code, it is very well documented. :-)

One more thing: Please let me know when you have copy-pasted/ctrl-S/printed to PDF or whatever the contents of this page, I need to delete the messages to prevent helping spammers avoid detection ;)

**Comment by SteveJobzniak** [comment]
We can still keep talking after that, I just need to delete all old messages

**Comment by PendoNL** [comment]
Go ahead! I've PDF'ed this convo! Thanks a ton so far for the help. I'm currently switching over to the 2.x branch!

**Comment by SteveJobzniak** [comment]
@PendoNL Excellent to hear! :-) Should go well. My own personal project is pretty big and took like 30 minutes to just search-and-replace various moved Model items, handling new exceptions, deleting old Settings storage, and updating any renamed/changed function calls.

**Comment by PendoNL** [comment]
I think I'm almost ready for the first test aswel. This is the final setup for the post method:

```php
            $ig = new Instagram(false, false);

try {
    $ig->setUser("user", "password");
    $ig->login();

    try {

        $ig->uploadTimelinePhoto(
            $post_path,
            ['caption' => $post_caption]
        );
        // Photo is published, send notifications etc.

    } catch (\InstagramAPI\Exception\EndpointException $e) {
        // Endpoint error, login is correct, log error and act accordingly
        // Increase retry counter and stop after 5 tries for any error
    } catch (\InstagramAPI\Exception\InstagramException $e) {
        // Could be anything, log error and act accordingly
        // Increase retry counter and stop after 5 tries for any error
    }
} catch(\InstagramAPI\Exception\IncorrectPasswordException $e) {
    // Deactivate the account and force the user to re-enter their password
} catch(\InstagramAPI\Exception\CheckpointRequiredException $e) {
    // Deactivate account and tell the user to approve the checkpoint
} catch(\InstagramAPI\Exception\InstagramException $e) {
    // Deactivate account & log message for investigation
}
```

Looks about right?

**Comment by SteveJobzniak** [comment]
Yeah! That looks great. And yes `uploadTimelinePhoto` throws `EndpointException` if it fails, and then its getMessage() will show what the server said was wrong.

All more serious errors (like bad session credentials etc) will throw other exceptions such as `LoginRequiredException`. So you know that if you get an EndpointException, it ONLY means: The general state of the client is fine, but there was some problem with your specific API call (bad parameters etc).

That's one of the great things about this rewrite. Proper exceptions make life easy! :-)

Here's what I would change:

```php
        $resized = new \InstagramAPI\ImageAutoResizer($post_path);
        $ig->uploadTimelinePhoto(
            $resized->getFile(),
            ['caption' => $post_caption]
        );
```

That class is magical. It will re-use the original file if it's actually valid on Instagram, otherwise it will re-encode, autocrop and autoresize it as-needed so that the server will accept it. It also handles things like image rotation etc (making sure your images with rotation EXIF metadata show up in correct rotation on Instagram).

And as soon as the $resized object goes out of scope and gets `__destruct()`-ed, it will autodelete any temp file it created. So we made it as easy as possible for users to use. :-)

Since you let people upload any file, you should use that class.

**Comment by SteveJobzniak** [comment]
You can even let your users do cool things like make square images.

Just like this:

```php
        $resized = new \InstagramAPI\ImageAutoResizer($post_path, null, 1, 1); // 1:1 ratio, default autofocus
        $ig->uploadTimelinePhoto(
            $resized->getFile(),
            ['caption' => $post_caption]
        );
```

**Comment by PendoNL** [comment]
I think I just beat you to adding the resizer class ;-) The application I built uses an online square-cropper saving the image at 640x640. Since we want a clean looking IG profile for me and my client, I want it to be filled with nice looking squares. My guess is the ImageAutoResizer is not needed, but I've added it anyway, just to be safe!

**Comment by SteveJobzniak** [comment]
@PendoNL Ahh! Ours limits the square to Instagram's max (1080x1080), and doesn't down-upsize. So if you always want 640x640 then you don't need autoresizer. Just be sure that your file is: 640x640, JPG.

**Comment by PendoNL** [comment]
Will do, thanks for mentioning that! I'll make sure larger images can be used in the future. That's an issue I need to tackle in the cropper another time. They're 640x640 JPGs for sure! They're "hard" resized to those dimensions and converted to jpg when saved.

**Comment by SteveJobzniak** [comment]
@PendoNL Ah. Well you can take our ImageAutoResizer code and edit it for your own needs (make a clone of it) and make it do resizing to 640x640. If you no longer wanna call an external website's "please crop this for us" all the time. ;-)

**Comment by PendoNL** [comment]
Many, many, many thanks for your help @SteveJobzniak! I'm currently testing the migration to 2.x on the dev-master branch. So far logging in works as expected. Moving on to the new post test but I'm pretty sure that won't fail due to your help either.

**Comment by PendoNL** [comment]
Posts are working aswel! Flawless!! Kudos to your work mate. Too bad no one took the time to respond in the past 22 hours to your issue.

**Comment by SteveJobzniak** [comment]
@PendoNL Thanks a lot for the warm words. There's pretty often an atmosphere in open source where people just leech and don't care, and just ask for more all the time (thanks are usually "Thanks, great! Please add this too..."). I contribute anyway, but it certainly warms my heart when people take a few minutes out of their day to show appreciation. :-)

Going to bed now, will probably have finished 2.x tomorrow. We'll see! If we're lucky and nothing else comes up. ;-) Good night and take care.

**Comment by PendoNL** [comment]
Just letting you know the live (staging) version of the app is working perfectly using 2.x!

**Comment by SteveJobzniak** [comment]
@PendoNL Hi again. The release of 2.x is happening this evening, right now. It was delayed a bit by a sudden, complete rewrite of the configure() and settings-systems, because they were both still a huge mess. Now they're totally rewritten.

Since you use settings-files and have been using 2.x for a while, you'll be happy to know that those are going to be auto-migrated to the File storage 2.0 format. Just be sure that they're in the `sessions/` folder and are named as `sessions/username/username-settings.dat`. It will be detected as v1.x data and will be upgraded to 2.x.
