### ISSUE TITLE
My uploaded photos does not appear on the search/hashtag page.

### ISSUE THREAD

**Issue by Cappystarj0e** [mgp25/Instagram-API#1112]
The upload is successful.

But...

When I use hashtags in the photographs, my pics do not appear on the pages of the hashtag.
For example, upload any image using a hashtag #abcd.
Then look at the #abcd search page.
You will not see that picture there.

I think instagram understands that this image is sent from the computer
and does not show it on the page of hashtag.

**Comment by dsidious1** [comment]
I have same problem. Sometimes pictures and vids isn't visible on certain devices, usually on iPhone.

**Comment by mgp25** [comment]
Duplicate issue. Please search topic in closed issues

Regards
