### ISSUE TITLE
Custom Thumbnail for timeline video

### ISSUE THREAD

**Issue by samdonato** [mgp25/Instagram-API#1114]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

### Describe your issue

Running example code to upload uploadTimelineVideo, I get the error "You must have FFmpeg to generate video thumbnails". ffmpeg is installed, but I would consider it sketchy and would like to skip thumbnail generation and provide my own which was possible before the latest update. 

Can I skip FFmpeg and use my own thumbnail?

**Comment by richellyitalo** [comment]
Same problem.

**Comment by mgp25** [comment]
@samdonato @richellyitalo for multiple reason, we should do the same as instagram, otherwise people could fake the thumbnail and the video could be something totally different.

Thats why we are not implementing this at the moment. But if that is something you really want, you can easily change the code your own and set a custom thumbnail.

Regards

**Comment by samdonato** [comment]
@richellyitalo and anyone else, I know my videos will always have a custom thumbnail that works on IG, so I did this. In Instagram.php, _uploadVideo function, replace the line
`$this->client->uploadPhotoData($type, $videoFilename, 'videofile', $uploadParams['upload_id']);`
**with this**
`$this->client->uploadPhotoData($type, $metadata['thumbnail_image'], 'photofile', $uploadParams['upload_id']);`
Then in your call to uploadTimelineVideo, add thumbnail_image like this:
`$ig->uploadTimelineVideo($fileName, ['caption' => $caption, 'thumbnail_image' => $thumbFileName]);`
