### ISSUE TITLE
Error SSL Certified on run localhost

### ISSUE THREAD

**Issue by richellyitalo** [mgp25/Instagram-API#1115]
## PLEASE FOLLOW THE GUIDE BELOW, OTHERWISE WE WILL DELETE YOUR TICKET WITHOUT ANSWERING IT

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Whene I run in localhost, 
the message show to me 
"Network: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)."

It's normal?

**Comment by mgp25** [comment]
@richellyitalo well thats no an API issue, anyway you can always as a CAinfo in your php ini or enviroment.

Other alternarive is disable SSL verification, using the provided function in the API:
- setVerifySSL(false)

Let me know if that fixed it

Regards

**Comment by richellyitalo** [comment]
OK, thanks!
