### ISSUE TITLE
Something went wrong: InstagramAPI\ConfigureResponse : Other media configure error: b'E3v4zLVnwi'

### ISSUE THREAD

**Issue by IngJuanRojas** [mgp25/Instagram-API#1117]
POST: media/configure/ 

DATA: ig_sig_key_version=4&signed_body=e0004d99dc4883942697563a5352aca51de21cbf987046ba3a481ec925effa81.{"_csrftoken":"kVqS1BFWtoXOgZezSTIjNXEmfXFd3Bb1","media_folder":"Instagram","source_type":4,"_uid":"255236307","_uuid":"461a896b-4d3f-450b-97e7-cbe118d6a588","caption":"#primerpost","upload_id":"1490394013663","device":{"manufacturer":"Archos","model":"A80RG11","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[3264,3264],"crop_center":[0,0],"crop_zoom":1},"extra":{"source_width":3264,"source_height":3264}} ← 500 75B 

RESPONSE: {"message": "Other media configure error: b'E3v4zLVnwi'", "status": "fail"}

Hi everyone!

Im trying uploadPhoto to Instagram with the example!
I think that i'm making a mistake here! You can help me to solve this?

Im still trying, but if any of you can help me, i will appreciate so much!

Thanks for the help!!!

**Comment by mgp25** [comment]
@IngJuanRojas 

Instagram only allows images between 320px-1080px width.

Regards
