### ISSUE TITLE
New line not working

### ISSUE THREAD

**Issue by alibehroozi** [mgp25/Instagram-API#1118]
Hello
I'm trying to post an image with a caption including new line ( \r\n )
But it doesn't work and new line does not appear correctly.

Please help
Thanks

**Comment by Nks** [comment]
@alibehroozi version?

**Comment by mgp25** [comment]
@alibehroozi i think Instagram doesnt support new line, anyway make sure it is double quotes`" "` instead of single one `' '`.

This is also a duplicate issue, you should search before opening a new issue

Regards

**Comment by ping** [comment]
I did a little testing.

Instagram does support line breaks but not consecutive line breaks.

Example: https://www.instagram.com/p/BSCoDz7Du7k/ (media ID: 1477919811501485796_25025320) has 2 ``\n`` line breaks, one before "This post is in celebration..." and one before "Photos by...".


Single line breaks work, example: "Apples are\nGood for you"
```
Apples are
Good for you
```
Consecutive line breaks become spaces, example: "Apples are\nGood for you.\n\n!!!"
```
Apples are
Good for you !!!
```

**Comment by mgp25** [comment]
@ping thanks for the info! 😄

**Comment by ping** [comment]
Can confirm \n line breaks work with current master.

```php
$api = new \InstagramAPI\Instagram(false);
$api->setUser('x', 'x');
$api->login();

$mediaId = '12345678900_12345';
$editedMedia = $api->editMedia($mediaId, "OMG\nChristmas Sales\n\nSo... #salesarebad #walletbuster\n\n!!!" );
var_dump($editedMedia->getMedia()->getCaption()->getText());
```

var_dump:
```
string(58) "OMG
Christmas Sales

So... #salesarebad #walletbuster !!!"
```

**Comment by 83lipe** [comment]
i no understand the issue 1118, i edit posted media to replace to correct caption?

**Comment by SteveJobzniak** [comment]
@83lipe No. The edit command is just used in his example. You need to provide a caption in that example string format to uploadPhoto, if you want to upload with newlines in caption.

**Comment by 83lipe** [comment]
I use \n but post with \n and not new line... 
:(

**Comment by SteveJobzniak** [comment]
@83lipe https://stackoverflow.com/questions/7890217/making-a-new-line-with-single-quotes

**Comment by 83lipe** [comment]
i try, not work, to post direct from php as test ok, but i receive text from database, with line break eg, when posted on instagram , is posted without line break.

**Comment by SteveJobzniak** [comment]
@83lipe So you are telling us that if you post from PHP, with `"this\ncaption"` it works, but if you get text from your own database it fails.

Jesus christ, you are testing my patience. Do you want to get banned from this repo for being an idiot? This is not our problem! Fix your own code! We support newlines in caption and we have shown you in 5 different messages how to do it!

**Comment by 83lipe** [comment]
No man.
I receive from database:

"Test new line
.
Test new line
.
Test final line."

If i post direct , the post show:

Test new line.Test new line.Test final line.

if i put \n into text eg

"Test new line\n.\nTest new line\n.\nTest final line."

when posted show:

Test new line\n.\nTest new line\n.\nTest final line.

only this.

I not know if your api have method to fix this, only this.

**Comment by SteveJobzniak** [comment]
New line is working. Use newline characters. Which in PHP is written via `"\n"` like this: `"this\nhas\nnewlines"`.

You seem to be sending literal `backslash + n`, which is not a newline and is not our problem. You need to send the newline character. Google it. Locking this discussion because we've already shown you how to do this multiple times in multiple tickets.

**Comment by nevazhnoo** [comment]
```
$caption = "Line1\u{2063}\nLine2\u{2063}\n\u{2063}\nLine3";
/*
Line1
Line2

Line3
*/
```
