### ISSUE TITLE
multiple account process

### ISSUE THREAD

**Issue by musacivak** [mgp25/Instagram-API#112]
Hello,

im using 2 account with loop, but after a certain time return a error message "login_required".

construct
                $this->instagram = new Instagram($user['username'], $user['password'], true);
                $this->instagram->login();

destruct
                $this->instagram->logout();

Please help this problem, thanks.

debug

REQUEST: si/fetch_headers/?challenge_type=signup&guid=f4dd83be089b44dbaa495ee5089f5f26 RESPONSE: {"status":"ok","shift":18,"header":"qSwBhRi7ONobJZe5Hv4XLDr2YEaztug3","edges":100,"iterations":10,"size":42} REQUEST: accounts/login/ DATA: ig_sig_key_version=4&signed_body=ee3a52924403e75298418ca0d54dc551826547b4e68e8e11ef40ef094ddca2aa.{"device_id":"android-68dd09b9ff11f0df","guid":"3afa6240-a605-4d40-95e2-f4fabe7fda76","phone_id":"a0065f54-b510-419a-9fd7-721f0cce21ae","username":"xxx","password":"xxx","login_attempt_count":"0"} RESPONSE: {"status":"ok","errors":{"error":["Sorry, there was a problem with your request."]}}

**Comment by mgp25** [comment]
You can have multiple accounts using different instances, itss not API related but programming.

Regards
