### ISSUE TITLE
Instagram Signature Key

### ISSUE THREAD

**Issue by mgp25** [mgp25/Instagram-API#1120]
Hello users!

Hope you are enjoying [release 2.0](https://github.com/mgp25/Instagram-API/releases/tag/v2.0)! :tada:

In order to have always the latest features and have a consistent API, i have done something interesting to obtain instagram signature key easily and automated.

In order to achieve this, i need an Android device that will be used by my Key Extraction Server, so if you have any phisical device you can send me, or any donation to obtain one, will be awesome.

This is not something strictly required, but that will make the API key always up to date which is always nice.

If you have any question regarding to this, any recommendation or so, ill be happy to hear them.

Regards

_mgp25_

**Comment by mgp25** [comment]
I would like to thank @joseflorido for his donation. New device will arrive early this week and i will be able to make updates and changes faster!

Thanks for contributing to the project! :smile:

Regards

**Comment by SteveJobzniak** [comment]
Hooray! :)

**Comment by Riyaz7364** [comment]
anyone can help to generate cookie from android device?
