### ISSUE TITLE
Best way to getUserFeed

### ISSUE THREAD

**Issue by necromind** [mgp25/Instagram-API#1122]
What is the best way to use getUserFeed? If user will be "private" i will take error. I think its not good.
1. getUserFeed -> if error dont see him.
2. getUsernameInfo first and if no "private" -> getUserFeed 
What is way more native and safe ?

**Comment by mgp25** [comment]
@necromind both are okay. Instagram app does both of the cases. In the case one you will get something like this:

```json
{
	"message": "Not authorized to view user",
	"status": "fail"
}
```
Which is normal behaviour and ok.

In the second case you can do a previous verification, but it is not required at all

Regards

**Comment by SteveJobzniak** [comment]
@necromind In case 1, it will throw an `EndpointException` with `Not authorized to view user` inside of the `$e->getMessage()` on the exception.

Those messages are not guaranteed to remain the same. So most futureproof way would be if you write your code to get user info and check if private. Or if you just write a general catch for endpointexception and treat them all as access denied.
