### ISSUE TITLE
getMediaLikers not getting an entire response or generating pagination

### ISSUE THREAD

**Issue by ital0** [mgp25/Instagram-API#1127]
Hello!
I'm trying to get all likers of a media, but when the counter reaches 999, doesn't get anything else.

**My request:**
`$instagram->getMediaLikers("1477189258486079998_28857573");`

**My response count:**
![screenshot_20170328_091020](https://cloud.githubusercontent.com/assets/5700402/24404158/7ed6f568-1396-11e7-83f9-374ec3a2e002.png)

**And the last key of my reponse (0 -> 998):**
![screenshot_20170328_091045](https://cloud.githubusercontent.com/assets/5700402/24404167/876abac0-1396-11e7-9c37-5b18b6719c88.png)

I have no key for pagitination. There's a way to build that pagination or get all results?

**Comment by mgp25** [comment]
@ital0 it is a normal behaviour, responses are okay. Instagram App does the same.

This is an already answered issue. Please search in the closed issues before opening a new one

Regards
