### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by mbergwall2222** [mgp25/Instagram-API#1134]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

Hi! I was able to register accounts using this private api a few weeks ago, but all of a sudden now this api does not have any of the register functionality in it. It just disappeared. What happened? How can I get this back?

**Comment by mgp25** [comment]
I removed it because it was used Inappropriately. You can still register an account using your device and then use it here

Regards

**Comment by jpmoney5065** [comment]
Also you can register accounts via web browser at instagram.com 

For people like me with no smartphone :)
