### ISSUE TITLE
Understanding API Exception

### ISSUE THREAD

**Issue by bestofsam** [mgp25/Instagram-API#1137]
Dear All , first of all this is a question which is not API related.

When i do follow user via : 
`$instagram->follow('UserId');`

this is the response :

GET:  friendships/show/4083603251/
```
← 200    115B
RESPONSE: {"incoming_request": false, "outgoing_request": false, "followed_by": false, "following": false, "is_muting_reel": false, "is_private": false, "is_blocking_reel": false, "status": "ok", "blocking": false}
```
The status attribute is OK, but the  following is false.
it seem instagram block the follow endpoint , but as i know , instagram return feedback_required with spam true status Exception.

in this situation , how to know if the process complete correctly !
checking the  "getFollowing()" is true ?
how can check if instagram temporary block the endpoint ?

so what's going on ? please advice.

bestofsam 
Regards

**Comment by mgp25** [comment]
@bestofsam if you try to follow someone and it is not followed, you are flagged as spammer by Instagram. You can check it because you havent followed the user actually.

You are probably giving the API a bad usage. So i close this issue

Regards
