### ISSUE TITLE
Is that fine with php stable ver 7.0 ++

### ISSUE THREAD

**Issue by OwlGreenApple** [mgp25/Instagram-API#1138]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- x[ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->setUser('yourusername', 'yourpassword');
    $ig->login();
    $result = $ig->comment('14123451234567890_1234567890', "Hello World");
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

RESPONSE: {"status": "fail", "message": "Sorry, the comment data may have been corrupted."}

InstagramAPI\Response\CommentResponse: Sorry, the comment data may have been corrupted.
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below, for example:

GET /api/v1/si/fetch_headers/?guid=123456abcdeff19cc2f123456&challenge_type=signup HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
X-IG-Connection-Type: mobile(UMTS)
X-IG-Capabilities: 3ToAAA==
Accept-Language: en-US
Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; mid=WFI52QABAAGrbKL-ABCDEFGHIJK
User-Agent: Instagram 10.3.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept-Encoding: gzip, deflate, sdch
```

Response:

```http
# Please provide your capture below, for example:

HTTP/1.1 200 OK
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Thu, 15 Dec 2016 08:50:19 GMT
Content-Type: application/json
Set-Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; expires=Thu, 14-Dec-2017 08:50:19 GMT; Max-Age=31449600; Path=/; secure
Connection: keep-alive
Content-Length: 16

{"status": "ok"}
```
---

### Describe your issue

Hi 

Im trying to connecting (just login). using mgp25 ver 2 with PHP Version 7.0.17
There are no errors(blank space, no response for logs) but its not saved on database. It works well with PHP Version 5.6.19
There is my syntax
<pre>
		try {
			$i = new Instagram(true,true); 
			$i->settingsAdapter = array(
				"type"       => "mysql",
				"db_host"       => Config::get('myconfig.DB_HOST'),
				"db_name"   => Config::get('myconfig.DB_DATABASE'),
				"db_username"   => Config::get('myconfig.DB_USERNAME'),
				"db_password"   => Config::get('myconfig.DB_PASSWORD'),
			);		
			$i->setUser("username", "password");
					$i->setProxy("http://userproxy:passproxy@hostproxy:portproxy",intval("portproxy"),"userproxy","passproxy");
					$i->login();
		} catch (Exception $e) {
			return $e->getMessage();
		}
				

</pre>

Notes : already put host on Remote MySQL, and checking firewall

**Comment by zuexo** [comment]
@OwlGreenApple First of all you should provide storage configuration when creating Instagram class and secondly instead of `"type"  => "mysql"`, it should be `"storage" => "mysql"`.

```php
$i = new Instagram(true, true, [
	"storage"       => "mysql",
	"db_host"       => Config::get('myconfig.DB_HOST'),
	"db_name"   => Config::get('myconfig.DB_DATABASE'),
	"db_username"   => Config::get('myconfig.DB_USERNAME'),
	"db_password"   => Config::get('myconfig.DB_PASSWORD'),
]);
```

**Comment by mgp25** [comment]
Will add this info in wiki.

Regards

**Comment by aitte2** [comment]
V2 uses a new storage system. Be sure to do what zuexo said, and you can also delete your old v1 db table. The new mysql storage uses a different table name and a nice, futureproofed table structure.

**Comment by OwlGreenApple** [comment]
@aitte2 @zuexo it works.. thank you

**Comment by OwlGreenApple** [comment]
@aitte2 @zuexo so its completely different with mysql before. 
Can you give example code for read settings field please :) ??
