### ISSUE TITLE
Issues on Starting the Project

### ISSUE THREAD

**Issue by 9787954511** [mgp25/Instagram-API#1139]
Hi,
I am trying to use the mgp25 instagram-API in my project.

I am checking the example from the github. I am running the code from the example path. require file is included. But i am getting error 500 in this line:: 
```php
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
```

Tried in different type, Can anyone help me out.
My Folder Structure was this i cloned.
![apiinsta](https://cloud.githubusercontent.com/assets/3214829/24577842/70aa3468-16f3-11e7-86f8-bdbb9c306a3a.png)

Please help me out where to start the initial code.. Where to load the autoload. 
I am using PHP 7.0.
I am using corePHP
Tried from root directory as well as. Any Namespace issues?

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

/////// CONFIG ///////
$username = 'test';
$password = 'testpasswrd';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->setUser($username, $password);
    $ig->login();
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
```

**Comment by mgp25** [comment]
Have you read [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ) and closed issues before opening this issue? I suppose not. That is answered in a closed issue and in the [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ)

You can find examples [here](https://github.com/mgp25/Instagram-API/tree/master/examples)

Regards

**Comment by 9787954511** [comment]
okay thank you, i will check that.
