### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by lkp111138** [mgp25/Instagram-API#114]
I have found a variable called '$recimient_users', in line 286 of Instagram.php, which seemed not defined.
Maybe you mean '$recipeint_users'?

**Comment by RageBrahimi** [comment]
Noted here [here](https://github.com/mgp25/Instagram-API/issues/65). Please search before you post an issue.

**Comment by mgp25** [comment]
If you find any typo, better send a pull request

regards
