### ISSUE TITLE
Two factor auth

### ISSUE THREAD

**Issue by neo22s** [mgp25/Instagram-API#1140]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Hello, how can we do a Two factor authentication? I can not find any example , if thats even possible.

thanks a lot.

**Comment by mgp25** [comment]
Hello @neo22s, there is no two factor auth support yet. Maybe if i have some time ill add this.

Regards

**Comment by neo22s** [comment]
ok, that was fast! WOW congrats guys.

A pity now all the code I have done does not work on 2.0.

**Comment by mgp25** [comment]
@neo22s 

```php
<?php

include __DIR__.'/Instagram-API/vendor/autoload.php';

$i = new \InstagramAPI\Instagram(true, true); // DEBUG ON

$i->setUser($username, $password);

try {
    $loginResponse = $i->login();

    if (!is_null($loginResponse) && $loginResponse->getTwoFactorRequired()) {
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();
        
         // I added this line so i could write in the code in CLI.
         // You can replace this line with the logic you want. 
         // Verification code will be received via SMS.
        $verificationCode = trim(fgets(STDIN));
        $i->twoFactorLogin($verificationCode, $twoFactorIdentifier);
    }
} catch (Exception $e)
{
  // Do something
}
```

**Comment by neo22s** [comment]
thanks!

**Comment by CristianHG2** [comment]
Is there any way of doing this with email instead of SMS?

**Comment by SteveJobzniak** [comment]
@CristianHG2 No... Instagram does not have that.

**Comment by SteveJobzniak** [comment]
@CristianHG2 No... Instagram does not have that feature. Only SMS exists.

![image2](https://user-images.githubusercontent.com/22373193/31578618-18e90b06-b125-11e7-9967-55724ff41fcd.png)
