### ISSUE TITLE
getUserInfoById() not working if profile closed

### ISSUE THREAD

**Issue by Chinyaev** [mgp25/Instagram-API#1141]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
$name = $user->username;
$id = $user->pk;
...
$info = $i->getUserInfoByName($name)->user; // it's work always
$info = $i->getUserInfoById($id)->user; // it's not work if profile closed


```

Error Log/var_dump:

```php
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'string' not found in /var/www/insta/vendor/netresearch/jsonmapper/src/JsonMapper.php:541 Stack trace: #0 /var/www/insta/vendor/netresearch/jsonmapper/src/JsonMapper.php(371): JsonMapper->createInstance('string') #1 /var/www/insta/vendor/netresearch/jsonmapper/src/JsonMapper.php(260): JsonMapper->mapArray(Array, Array, 'string') #2 /var/www/insta/vendor/netresearch/jsonmapper/src/JsonMapper.php(275): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\Model\User)) #3 /var/www/insta/vendor/mgp25/instagram-php/src/Client.php(433): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\UserInfoResponse)) #4 /var/www/insta/vendor/mgp25/instagram-php/src/Request.php(105): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\UserInfoResponse), Object(stdClass), true, NULL) #5 /var/www/insta/vendor/mgp25/instagram-php/src/Instagram.php(2310): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\UserInfoResponse)) #6 /var/www/insta/app/Jobs/subAndLikes.php(213): InstagramAPI\Instagram->getUserInfoById('2848783932') #7 [internal function]: App\Jobs\subAndLikes->handle() #8 /var/www/insta/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array) #9 /var/www/insta/bootstrap/cache/compiled.php(9951): Illuminate\Container\Container->call(Array) #10 /var/www/insta/bootstrap/cache/compiled.php(10066): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\subAndLikes)) #11 /var/www/insta/bootstrap/cache/compiled.php(10044): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\subAndLikes)) #12 /var/www/insta/bootstrap/cache/compiled.php(9954): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #13 /var/www/insta/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\subAndLikes), false) #14 /var/www/insta/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array) #15 /var/www/insta/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire() #16 /var/www/insta/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(152): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions)) #17 /var/www/insta/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions)) #18 /var/www/insta/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default') #19 [internal function]: Illuminate\Queue\Console\WorkCommand->fire() #20 /var/www/insta/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array) #21 /var/www/insta/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array) #22 /var/www/insta/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #23 /var/www/insta/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #24 /var/www/insta/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #25 /var/www/insta/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #26 /var/www/insta/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #27 /var/www/insta/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #28 /var/www/insta/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #29 {main} [] []
```

---

### Describe your issue

method getUserInfoById() not working if profile closed.

**Comment by mgp25** [comment]
@Chinyaev it seems you havent read the examples or the wiki. You are doing it wrong.

If you want to get user you need to do this:

```php
$info = $i->getUserInfoById($id)->getUser;
```

For each var, you use a getter. And it works always. Please make sure you have read wiki and examples before opening an issue

Regards

**Comment by Chinyaev** [comment]
ok, but it's not working too.

**Comment by mgp25** [comment]
@Chinyaev i tried the same piece of code that you posted, even the same id which was in the exception you have posted `->getUserInfoById('2848783932')` and yes it is working perfectly, i tried a couple of times without any issue. 

Make sure you are using latest release v2.0. And your code should be like this:

```php
$name = $user->getUsername;
$id = $user->getPk;
...
$info = $i->getUserInfoByName($name)->getUser;
$info = $i->getUserInfoById($id)->getUser; 
```

**Comment by aitte2** [comment]
Maybe this fixed it? https://github.com/mgp25/Instagram-API/commit/f3b27281cba84550d8c8ce175b9163b2a9da08db

**Comment by mgp25** [comment]
Yes, in any case, use always latest commit @ master, everything is stable and safe to sync with it

Regards

**Comment by Chinyaev** [comment]
@aitte2 thank you!
@mgp25 i'm use stable version 2.0.

**Comment by Timkzn** [comment]
Hi everyone,

I faced with absolutely the same issue.
I tried all the ways you proposed and it didn't help(
The code "$i->getUserInfoById($id)" throws PHP Fatal error regardless of putting "->getUser()" in the end or not.

It happens not only with private accounts - even with the public ones. But that's strange that I can access the account info by logging in from one account, but get this error when try to do the same from another one...

I also use the stable version 2.0.
I would very appreciate if you try find and fix this issue.

Thanks a lot in advance!

**Comment by bisht-sanjeet** [comment]
Does not work for me too. 

$ig->getUserInfoById(787132);

With or without "->getUser()"

getting 
Fatal error:  Class 'string' not found in C:\xampp\htdocs\insta2\vendor\netresearch\jsonmapper\src\JsonMapper.php on line 544

Works for my id the account which I'm logged in and the id 2848783932 used by mgp25 for testing 

But does not give user details of my friends 
or for the open accounts like 
instagram - 25025320
9gag - 259220806
therock - 232192182
natgeo - 787132

They all are open and popular accounts but they are giving error. 

Thanks :)

**Comment by Timkzn** [comment]
Hi all,

Looks like I found the solution.
It's fixed in the next commit:
https://github.com/mgp25/Instagram-API/commit/f3b27281cba84550d8c8ce175b9163b2a9da08db

Just change the file 'src/Response/Model/User.php' by modifying the string 63 from ' * @var string[]' to ' * @var Link[]'

**Comment by mgp25** [comment]
Like i said above, use latest commit from master...

Regards

**Comment by bisht-sanjeet** [comment]
Thanks working now. 
I usually download the code.
