### ISSUE TITLE
How to mock instagram response?

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [mgp25/Instagram-API#1143]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
### Describe your issue

How to mock instagram response? I need it to test my app without touching real instagram endpoints.
I know how to use Mockery, phpunit, etc, but can't figure out how to mock instagram response correctly.
The best would be to mock guzzle response, but i can not swap the guzzle handler.

**Comment by mgp25** [comment]
@Vasiliy-Bondarenko i don't know :/ but it is not an API issue. You can always test with a test account.

Regards
