### ISSUE TITLE
How to Get a list of recently tagged media

### ISSUE THREAD

**Issue by ALYREZA** [mgp25/Instagram-API#1145]
I want to limit Count of tagged media to return.
for example take only 5 of most recently of `getHashtagFeed`
like [Instagram Developer Documentation](https://www.instagram.com/developer/endpoints/tags/)

**Comment by mgp25** [comment]
@ALYREZA i dont know if that is possible in this API. When you are using the Instagram App, there isnt an option to specify how many results we want. What you can do instead, is taking from the items array the number of elements you want from it.

If you want, you can try adding a new param ' count'  and try if Instagram server answer with a limited response.

Remember that this API is based in the Instagram App

Regards
