### ISSUE TITLE
Quality of the uploaded image

### ISSUE THREAD

**Issue by NourdineMazali** [mgp25/Instagram-API#1148]
Hi there, 
your script works perfectly, had some issues with image format error, but got sorted out after changing to jpg, wondering why the quality of the uploaded image on instagram is not as good as the uploaded photo?, is there anyway to better the quality.

Thanks again for this repo.

**Comment by mgp25** [comment]
@NourdineMazali the photo data is directly uploaded to instagram server, no modification of the image is done in the API side. Instagram can compress the image server side, if you want to improve the quality of the uploaded photo, the best option is to upload a bigger image (dimmensions)

Regards
