### ISSUE TITLE
Handle authentication Data Login

### ISSUE THREAD

**Issue by OwlGreenApple** [mgp25/Instagram-API#1150]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->setUser('yourusername', 'yourpassword');
    $ig->login();
    $result = $ig->comment('14123451234567890_1234567890', "Hello World");
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

RESPONSE: {"status": "fail", "message": "Sorry, the comment data may have been corrupted."}

InstagramAPI\Response\CommentResponse: Sorry, the comment data may have been corrupted.
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below, for example:

GET /api/v1/si/fetch_headers/?guid=123456abcdeff19cc2f123456&challenge_type=signup HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
X-IG-Connection-Type: mobile(UMTS)
X-IG-Capabilities: 3ToAAA==
Accept-Language: en-US
Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; mid=WFI52QABAAGrbKL-ABCDEFGHIJK
User-Agent: Instagram 10.3.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept-Encoding: gzip, deflate, sdch
```

Response:

```http
# Please provide your capture below, for example:

HTTP/1.1 200 OK
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Thu, 15 Dec 2016 08:50:19 GMT
Content-Type: application/json
Set-Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; expires=Thu, 14-Dec-2017 08:50:19 GMT; Max-Age=31449600; Path=/; secure
Connection: keep-alive
Content-Length: 16

{"status": "ok"}
```
---

### Describe your issue

Explanation of your issue goes here.

Please make sure the description is worded well enough to be understood, and with as much context and examples as possible.

We reserve the right to close your ticket without answer if you can't bother spending a few minutes to write a helpful report for us.

Hi
I wanna ask something.
How to handle if we already stored cookies(on sql dbase). And then for some reason instagram reset(changes) the password for that account. How to handle situation like that ?

i tried with 
<pre>
$i->setUser("username", "wrong password");
</pre>

and then still got true on 
<pre>
dd($i->isLoggedIn);
</pre>

and there are no "status : fail" on debug result

I need to make code like handle Two Factor Login, in authentication.
1. For changed password
2. For error confirmation (need confirmation SMS or email).

**Comment by mgp25** [comment]
@OwlGreenApple hello, there is no support at for confirmation via SMS or email. You will need to use your device to unlock your account

By the way, when you are posting the request in the issue, try to be concrete, the request and response you posted has no relation with the issue. You posted an error log that is related to `CommentResponse` but you are asking how to handle confirmation and data storage.

See `Storagehandler.php`

Regards

**Comment by OwlGreenApple** [comment]
@mgp25 that is default new issues, should be ignored. i edit my question box

**Comment by OwlGreenApple** [comment]
@mgp25 
my loginresponse give null result(wrong password).
<pre>
$login_response = $i->login();
dd($login_response);
</pre>

and there debug log (response from login request)
<pre>
RESPONSE: {"error_type": "bad_password", "buttons": [{"action": "dismiss", "title": "Try Again"}], "status": "fail", "error_title": "Incorrect password for sapiterbang369", "message": "The password you entered is incorrect. Please try again.", "invalid_credentials": true}
</pre>

anw from that debug log how to read or parse it to variable on code ? 

Best regards,

**Comment by OwlGreenApple** [comment]
I change the instagram password via handphone, after succes(stored cookies). and then i tried to execute login again. my last comment show login response and debug log after i change instagram password. and still trying to login with old password(wrong one).

**Comment by mgp25** [comment]
@OwlGreenApple you need to change the password using your device. Read the wiki to see how getter works and catch exceptions to manage errors

Regards

**Comment by aitte2** [comment]
@OwlGreenApple The `setUser()` just sets the user used by `login()`. The password is checked by `login()` not by `setUser()`. And `isLoggedIn==true` is just a guess until you have actually used `login()`.

**Comment by aitte2** [comment]
@OwlGreenApple I found and fixed a bug about login:

https://github.com/mgp25/Instagram-API/pull/1152

When that is merged you can once again find bad passwords by doing:

```php
try {
$i->login();
} catch (\InstagramAPI\Exception\IncorrectPasswordException $e) {
   // wrong password...
}
```

**Comment by OwlGreenApple** [comment]
@aitte2 yeah i know setUser() for set username, & password only. I just showed my piece of code for describe that trying to login again use a wrong password, after got cookies with correct password.

Thanks for help for error password & fixing about login response :)

Best regards,

**Comment by OwlGreenApple** [comment]
@aitte2 
how to catch if user using 2 factor authentication ? at login process

i think this code on wiki is not work : 
<pre>
    $ig->setUser($username, $password);
    $loginResponse = $ig->login();

    if (!is_null($loginResponse) && $loginResponse->getTwoFactorRequired()) {
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();

         // I added this line so i could write in the code in CLI.
         // You can replace this line with the logic you want.
         // Verification code will be received via SMS.
        $verificationCode = trim(fgets(STDIN));
        $ig->twoFactorLogin($verificationCode, $twoFactorIdentifier);
    }
</pre>
$loginResponse give nothing result.

I need just to know, do not need something to handle like code above.
already tried with many exception but it cant handle to find if users use 2factor auth
<pre>
               try {
//normal login process
               }
		catch (\InstagramAPI\Exception\IncorrectPasswordException $e) {
			return $e->getMessage();
		}
		catch (\InstagramAPI\Exception\CheckpointRequiredException $e) {
			return $e->getMessage();
		}
		catch (\InstagramAPI\Exception\FeedbackRequiredException $e) {
			return $e->getMessage();
		}
		catch (\InstagramAPI\Exception\LoginRequiredException $e) {
			return $e->getMessage();
		}
		catch (\InstagramAPI\Exception\InstagramException $e) {
			return $e->getMessage();
		}		
		catch (Exception $e) {
			return $e->getMessage();
		}
</pre>

**Comment by aitte2** [comment]
@OwlGreenApple Like this:

https://github.com/mgp25/Instagram-API/blob/master/examples/twoFactorLogin.php

Notice how it does login inside try-block. If a non-twofactor error happens, it throws an error that you can catch. If a twofactor-error happens, you know it via `if (!is_null($loginResponse) && $loginResponse->getTwoFactorRequired()) {`.

getTwoFactorRequired is true or false and is provided by Instagram:

https://github.com/mgp25/Instagram-API/blob/master/src/Response/LoginResponse.php

That's it. Any other problem is not this API's fault.

**Comment by RezaMasoudi** [comment]
why always return Password exception but password is true
