### ISSUE TITLE
 Perhaps there should be equa ?

### ISSUE THREAD

**Issue by orionchikby** [mgp25/Instagram-API#1151]
Hi,
Perhaps there should be equal (=>)?

https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1824
https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1795

----
```
 'edits'=> [
                  'length'          => 0.00,
.......
....
..
```

**Comment by mgp25** [comment]
It is okay ewith `=>`, its an array

Although we should update this `0.00, // TODO! Should this always be zero?`
Since the length isnt 0

Regards

**Comment by anonyzm** [comment]
Don't think this is okey!
 'edits' should be key to the value, not just an unknown element with value 'edits'.

Should definately be like this:
`'edits' => [
                        'length'          => 0.00, // TODO! Should this always be zero?
                        'cinema'          => 'unsupported',
                        'original_length' => 0.00,
                        'source_type'     => 'library',
                        'start_time'      => 0,
                        'camera_position' => 'unknown',
                        'trim_type'       => 0,
                    ],`
It's definately your mistype.

Your array looks like this: 
`Array
(
    [date_time_original] => 2
    [scene_type] => 1
    [disable_comments] => 
    [upload_id] => 1
    [source_type] => 0
    [scene_capture_type] => standard
    [date_time_digitized] => 2
    [geotag_enabled] => 
    [camera_position] => back
    [0] => edits
    [1] => Array
        (
            [filter_strength] => 1
            [filter_name] => IGNormalFilter
        )

)`

**Comment by mgp25** [comment]
@anonyzm yes, what you said is okay, but the other user pointed to other line

**Comment by aitte2** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1795

https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1824

Yes both need to change from `'edits', [` to `'edits'     => [`.

**Comment by mgp25** [comment]
@aitte2 yup, will change it in a while. Thanks for reporting it

Regards
