### ISSUE TITLE
How to catch exception properly?

### ISSUE THREAD

**Issue by nubinter** [mgp25/Instagram-API#1154]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

---

### Describe your issue

Hi I am trying the new API and I loved it. But in this new API I don't know how to catch exception properly. I am using laravel for my project. I try to catch the login required exception by deleting my session and retrieve my timeline feeds without login. But the problem is I can't catch the exception so I can call the login function.
I already try this code
```
try {
} catch (\InstagramAPI\Exception\LoginRequiredException $e) {
	echo 'Something went wrong: '.$e->getMessage()."\n";
}
```
and also this code : 
```
try {
} (\Exception\LoginRequiredException $e) {
	echo 'Something went wrong: '.$e->getMessage()."\n";
	exit(0);
}
```
and : 
```
try {
} (\Exception $e) {
	echo 'Something went wrong: '.$e->getMessage()."\n";
	exit(0);
}
```

but none of them can catch the exception correctly. 
Thank You.

**Comment by mgp25** [comment]
@nubinter this is not an API related issue but a programming issue. Next time search in google.

You need to place `login` inside the try block, otherwise what do you want to catch?

Reference: https://secure.php.net/manual/en/language.exceptions.php

**Comment by nubinter** [comment]
@mgp25 Yes I know this is not an api issue I just don't know where to ask.
In my above example of course I have a code inside the try block. my complete codes are like this :
```
try {
   $username = $i->getUserInfo($username);
   return $username;
} catch (\InstagramAPI\Exception $e) {
 echo 'Something went wrong: '.$e->getMessage()."\n"; 
}
```
I got Laravel error page that show LoginRequiredException on Client.php line xxx

Isn't that mean there is an exception to catch?

**Comment by aitte2** [comment]
@nubinter Always call `login()` after every `setUser()`, if you do not want to be banned by Instagram.

**Comment by mgp25** [comment]
@nubinter if you want to catch login exception, login should be inside a try block. And again, this is not an API issue. 

And if you have any doubt, you can see examples here: https://github.com/mgp25/Instagram-API/tree/master/examples

Read php manual and wiki

Regards

**Comment by aitte2** [comment]
@mgp25 In his first post at the top here, the guy said he is trying to "get his timeline feed" and catch the "LoginRequiredException" to only call login() when he has become logged out.

I just told him to always call login().

Hey @nubinter read this:

https://github.com/mgp25/Instagram-API/blob/3cbbba64a032c1d1e9de27c5a73d77d780b4271c/src/Instagram.php#L343

**Comment by nubinter** [comment]
So the point is to always login whenever the script start running? Won't it be make the script take a long time to run?
