### ISSUE TITLE
why upload images always cropped?

### ISSUE THREAD

**Issue by ykbh** [mgp25/Instagram-API#1155]
in this function
 // Now, configure the photo
                        $conf = SendRequest('media/configure/', true, $new_data, $agent, true);

how to replace with my original size? 
ex 150px x 250px

**Comment by Nks** [comment]
@ykbh Are you sure that you are using this package?

**Comment by mgp25** [comment]
@ykbh images arent cropped by the API. You have a class, you can optionally use to crop your images which is `ImageAutoResizer` but it is not implemented by default. You can add it into your project if you want.

Make sure you are using latest commit from master

Regards
