### ISSUE TITLE
Instagram Account Verification

### ISSUE THREAD

**Issue by usamawaleed** [mgp25/Instagram-API#1159]
HI, 
I am using mgp25 via composer into my project for posting on Instagram accounts but I am facing an issue when ever I connect a different account using your Instagram-API I receive login error i.e "checkpoint_required". after that  when I open my instagram account at instagram.com I see a notification that 
" Instagram detect something wrong with my account and need verification i.e (email verification OR SMS verification) "

could you please guide me how can I avoid this thing,

Best Regards
usama waleed

**Comment by mangledbottles** [comment]
There used to be a function for both of these but they were removed in the latest update since they were outdated.

It is now a must for Instagram accounts to be Email or SMS verified on login. I will get the endpoints and requests and make a pull request soon.

In the meantime, if the app allows you do that. I know there can be an issue where it only allows the same device ID.

Regards :)

**Comment by mgp25** [comment]
@usamawaleed Yes, use the account always in the same IP. If you need to unlock it, do it manually

@mangledbottles dont do any pull request or anything. That was removed to avoid f****** spammers. Doing this it will only make easier to spam and we dont want that.

Regards

**Comment by usamawaleed** [comment]
HI sir,
first of all thank you for your reply, could you please tell me or provide a little sample code for using IP with login request.
Let me provide you a scenario, for example  if my hosting server is from U.S.A and my user from Australia want to use my system for posting on their Instagram account then he will provide their account credentials and submit, on submit i am using following code for authenticating their account 

       `     	
         $debug = false;

     	$i = new \InstagramAPI\Instagram($username, $password, $debug);

     	try {
     		$i->login(true);
     	} catch (\Exception $e) {
		      echo $e->getMessage();
     	}
      `
please tell me where I can use IP with login request, 
Best Regards

**Comment by mgp25** [comment]
@usamawaleed it is explained in the wiki: https://github.com/mgp25/Instagram-API/wiki

Regards
