### ISSUE TITLE
How to use SOCKS5 proxy? 

### ISSUE THREAD

**Issue by vnikolay** [mgp25/Instagram-API#1160]
I tried:
$ig->setProxy('tcp://127.0.0.1:9150');
But it gives me an error:
Something went wrong: Network: cURL error 56: Received HTTP code 501 from proxy after CONNECT (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
I tried other strings, but it does not work too.

**Comment by mgp25** [comment]
` $ig->setProxy('socks5://127.0.0.1:9150');`

**Comment by SteveJobzniak** [comment]
@vnikolay Wiki updated:
https://github.com/mgp25/Instagram-API/wiki#setting-a-proxy

**Comment by vnikolay** [comment]
Thank you! It's very useful.

**Comment by hasanitman** [comment]
hello
can u explain where should i add the code (proxy)
i want ue it for live broadcast

**Comment by hasanitman** [comment]
> Thank you! It's very useful.

i have same problem, can tell me just where should i put it?
