### ISSUE TITLE
next_max_id always returning null for getUserFollowers() 

### ISSUE THREAD

**Issue by OwlGreenApple** [mgp25/Instagram-API#1161]
Hi im trying to grab followers from username but why next_max_id always returning null ?
Is that bug ?

my code like : 
<pre>
	$userFollowers = $i->getUserFollowers("173560420",null); //cr7 id
        // $userFollowers = $i->getUserFollowers("173560420"); //cr7 id
	$maxId = $userFollowers->getNextMaxId();
	echo $maxId;
	dd($userFollowers);
</pre>
both of that code returning null for next_maxt_id

**Comment by mgp25** [comment]
@OwlGreenApple please get used to post always the request and response of the function. Could you please post it?

**Comment by OwlGreenApple** [comment]
@mgp25 There are bunch alot of data. I was delete partially of logs so it can be write on this comment..
<pre>
GET: friendships/173560420/followers/?rank_token=3222531200_fdf5e69b-b2c5-49a7-af98-5807f91096fe ← 200 497.35kB RESPONSE: {"page_size": 200, "status": "ok", "big_list": false, "users": [{"is_private": false, "username": "rich_tyga_tz", "full_name": "\ud83c\uddf7 \ud83c\uddee \ud83c\udde8 \ud83c\udded \ud83c\udde6 \ud83c\uddf7 \ud83c\udde9", "profile_pic_id": "1487528509340897892_1957932763", "pk": 1957932763, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17818739_398493333858669_1008474659156393984_a.jpg", "is_verified": false}, {"is_private": false, "username": "giovannicapozzo17", "full_name": "Giovanni Capozzo ~", "profile_pic_id": "1467577145073579588_210764558", "pk": 210764558, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17265479_1982518278636067_2721776296517435392_a.jpg", "is_verified": false}, {"is_private": false, "username": "romka_exfrash", "full_name": "\ud83d\udca5\ud83d\udca5\ud83d\udca5\u0420\u043e\u043c\u0430\u043d\ud83d\udca5\ud83d\udca5\ud83d\udca5", "profile_pic_id": "1320346408011920023_1435293013", "pk": 1435293013, "has_anonymous_profile_picture": false, "profile_pic_url": "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17126332_1134358620043114_8136048169055158272_a.jpg", "is_verified": false}, {"is_private": false, "username": "mas_aponk", "full_name": "\u0271\u03b1\u0282 \u03b1\u03c1\u03c3\u0273k", "profile_pic_id": "1473818012405660780_4783990246", "pk": 4783990246, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17332653_267210997054330_7174446704203137024_a.jpg", "is_verified": false}, {"is_private": false, "username": "bowie_47_klariis", "full_name": "BOWIE'47", "pk": 1924129334, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/12407229_1308558549170593_1566913252_a.jpg", "is_verified": false}, {"is_private": false, "username": "destisupit", "full_name": "", "profile_pic_id": "1487079476188887648_488927055", "pk": 488927055, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17662369_267258773733858_5200866355032621056_a.jpg", "is_verified": false}, {"is_private": false, "username": "mihir_kakadiya7", "full_name": "M\u00cdH\u00cf\u0158 007.)),_#)_!", "profile_pic_id": "1468183384715348508_3128769630", "pk": 3128769630, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17267808_1251823968258731_1606284280843993088_a.jpg", "is_verified": false}, {"is_private": false, "username": "llanerajohn", "full_name": "John Llanera", "profile_pic_id": "1481551108455096529_1416271213", "pk": 1416271213, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17587139_1528810020496882_3271217521230872576_a.jpg", "is_verified": false}, {"is_private": true, "username": "emretugceylmz", "full_name": "emretugceylmz", "profile_pic_id": "1487882641499517056_4565619112", "pk": 4565619112, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17438339_619798638215143_5919547583474171904_a.jpg", "is_verified": false}, {"is_private": false, "username": "king_mans", "full_name": "king_mans \u265a", "pk": 1294538869, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/12383216_822545707856918_496700177_a.jpg", "is_verified": false}, {"is_private": false, "username": "_davidgildelacanal_", "full_name": "David Gil De La Canal", "profile_pic_id": "1460498419973231324_304662580", "pk": 304662580, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/16908726_441211482876876_1763988556465831936_a.jpg", "is_verified": false}, {"is_private": false, "username": "sebebimsin.2736", "full_name": "sule", "profile_pic_id": "1488282596403408946_5065315611", "pk": 5065315611, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17818979_1256334844473830_8395003425347076096_a.jpg", "is_verified": false}, {"is_private": true, "username": "nermeenyasser99", "full_name": "Nermeen Yasser", "profile_pic_id": "1485576883600732514_1919938419", "pk": 1919938419, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17662955_1017402408392231_2549657608139046912_a.jpg", "is_verified": false}, {"is_private": false, "username": "__wu.1", "full_name": "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17662709_1312308875523212_4858139028647575552_a.jpg", "is_verified": false}, {"is_private": false, "username": "anggarisya", "full_name": "angga risya pratama", "pk": 5066225874, "has_anonymous_profile_picture": true, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "is_verified": false}, {"is_private": true, "username": "omercan_sqt", "full_name": "\u00d6meR \u2606", "profile_pic_id": "1477014176383487758_2872639680", "pk": 2872639680, "has_anonymous_profile_picture": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17438983_431703957169970_1535395214263320576_a.jpg", "is_verified": false}]}
FollowerAndFollowingResponse {#208 ▼
  +users: array:7488 [▶]
  +next_max_id: null
  +page_size: 200
  +big_list: false
  +status: "ok"
  +message: null
  +fullResponse: {#225 …4}
}
</pre>

**Comment by mgp25** [comment]
@OwlGreenApple i just tried the same piece of code with the same username id, and im getting a `next_max_id` value.

```php
$i->getUserFollowers('173560420');
```

If your account is flagged or unverified, Instagram can refuse you to send you a `next_max_id`.  The code works and there is no bug on the API side.

```
object{5}
  page_size: 200
  big_list:	true
  users [200]
  status: ok
  next_max_id:	AQCvlNx8xyNH0c3tc7CntYbobQZxnqDzGrAcCLiftzkUxSLgi-6ZqAFvMn6oNylkL4mXOrzh-_Hs2sM12YCq1ny6sGSGcqgBipgXFzV7YH6pjQ
```

Regards
