### ISSUE TITLE
NetworkException

### ISSUE THREAD

**Issue by alex051186** [mgp25/Instagram-API#1162]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

Error Log/var_dump:

```php
2017-04-08 20:05:19
[66.249.79.154][-][-][error][InstagramAPI\Exception\NetworkException]
exception 'InstagramAPI\Exception\NetworkException' with message
'Network: cURL error 28: Operation timed out after 30558 milliseconds
with 0 out of 0 bytes received (see
http://curl.haxx.se/libcurl/c/libcurl-errors.html).' in
/home/abc.com/public_html/vendor/mgp25/instagram-php/src/Client.php:525
Stack trace:
#0
/home/abc.com/public_html/vendor/mgp25/instagram-php/src/Client.php(615):
InstagramAPI\Client->_guzzleRequest('GET', 'https://i.insta...',
Array)
#1
/home/abc.com/public_html/vendor/mgp25/instagram-php/src/Client.php(720):
InstagramAPI\Client->_apiRequest('GET', 'feed/tag/cruxsl...', Array,
Array)
#2
/home/abc.com/public_html/vendor/mgp25/instagram-php/src/Request.php(108):
InstagramAPI\Client->api('feed/tag/cruxsl...', NULL, true, false)
#3
/home/abc.com/public_html/vendor/mgp25/instagram-php/src/Instagram.php(3001):
InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\TagFeedResponse))
#4 /home/abc.com/public_html/controllers/SiteController.php(237):
InstagramAPI\Instagram->getHashtagFeed('cruxsluts')
```

---

### Describe your issue

I don't know why, but our server report many error, anyone have idea ?
Many thank

**Comment by mgp25** [comment]
@alex051186 please read the error. Have you read the error?

```
exception 'InstagramAPI\Exception\NetworkException' with message
'Network: cURL error 28: Operation timed out after 30558 milliseconds
with 0 out of 0 bytes received (see
http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

Instagram is refusing to connect to your server or proxy

**Comment by alex051186** [comment]
Yes, thank you for your comment 👍
