### ISSUE TITLE
Something went wrong: Network: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

### ISSUE THREAD

**Issue by alexferra** [mgp25/Instagram-API#1167]
getting this error:

Something went wrong: Network: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

I searched closed issue, but most of them people are just told to go read somewhere else. I went there and I haven't been able to find anything. Is there anyway I can find a way to run an example.  I'm running one of the examples run under example folders but I'm getting this.  I'm using wampserver64 on localhost , thanks

I modified php.ini file and still get the error!
curl.cainfo = "C:\Users\Ale\Downloads\5719158-master\cacert.pem
and I downloaded and tried different cacert.pem files

**Comment by jpmoney5065** [comment]
Not an API issue. The problem is with you php installation. It can't locate your cert.

**Comment by mgp25** [comment]
Took me exactly, 2 seconds to search in google and find this: https://stackoverflow.com/questions/24372942/ssl-error-unable-to-get-local-issuer-certificate

Next time, i will close issue directly
