### ISSUE TITLE
Direct Share Thread Ids

### ISSUE THREAD

**Issue by Fire7** [mgp25/Instagram-API#1168]
https://github.com/mgp25/Instagram-API/blob/master/src/Client.php#L1344

Should we don't send threadId if it exist (not new thread)? Why? 
Just interesting in protocol.
I can make PR with threadId option.

**Comment by mgp25** [comment]
@Fire7 i have never used direct share, but if it sends the existing thread id when using an existing thread, then you can send a PR.

Reagards

**Comment by orionchikby** [comment]
work for me

in **Instagram.php**

public function directMessage(
        $recipients,
        $text,
        $threadId = 0) **//add**
    {
        return $this->client->directShare(
            'message',
            $recipients,
            [
                'text' => $text,
                'threadId' => $threadId **//add**
            ]
        );
    }


in **Client.php**
public function directShare{
......


$bodies[] = [
            'type' => 'form-data',
            'name' => 'thread_ids',
            'data' => isset($shareData['threadId'])? '["'.$shareData['threadId'].'"]':'["0"]', **//add**
        ];

**Comment by aitte2** [comment]
@orionchikby What is the point of sending a threadId? And should it be able to send more than one thread ID? The field is called "thread_ids" and takes an array. "[0]" is an array.

**Comment by aitte2** [comment]
Before proceeding we must figure out if threadId should always be a single ID or if it should sometimes be multiple Ids, because Instagram names the field "thread_ids" which is suspicious.

If I have understood things right so far, here is how I would do the change, since thread IDs always matter:

```php
Instagram.php:

    public function directMessage(
        $recipients,
        $text,
        $threadId = "0")
    {
        return $this->client->directShare(
            'message',
            $recipients,
            [$threadId],
            [
                'text' => $text,
            ]
        );
    }


Client.php:

    /**
     * @param string[] $threadIds Threads to share into. Use ["0"] to create a new thread.
     */
    public function directShare(
        $shareType,
        $recipients,
        array $threadIds,
        array $shareData)
....
      $bodies[] = [
            'type' => 'form-data',
            'name' => 'thread_ids',
            'data' => $threadIds
        ];

**Comment by Fire7** [comment]
I have parsed original instagram traffic from device and here is some conclusions:

There are no "recipient_users" field at all. Instagram manipulate only with thread_id (not thread_id**s**) value. Also where are _csrftoken, _uuid like in another cases and some field "action" that always equal to 'send_item'.

And I found "direct_v2/create_group_thread/" method that manipulated with "recipient_users" and calls every time before open NEW thread (even if it was opened previosly but still empty). It returns Thread object with all data includes threadId.

I have done modifications in library, but can't test it yet. So, I will make PR when I can.

**Comment by aitte2** [comment]
@Fire7 Be careful, iOS traffic is not same as Android traffic.

**Comment by mgp25** [comment]
Threads_ids can be existing ones too:

Wher s is a string with threads id concatenated.
```java
("thread_ids", "[" + s + "]");
```

And about what @aitte2 said:
> What is the point of sending a threadId? Is it to ensure that the shared media/message gets sent to an existing discussion instead of creating a new discussion? Isn't that what "recipients" takes care of?

I haven't tested it, but i guess that's correct.

Keep in mind that these features are being used for Instagram Live (mqtt protocol), Instagram doesnt use these features over https anymore.

when @valga finishes his port, tests will be done.

Regards
