### ISSUE TITLE
[ Question ] About Video Upload and aspect ratio

### ISSUE THREAD

**Issue by bestofsam** [mgp25/Instagram-API#1169]
Dear Flock , Thank you for this lib , it's save my day each time,

There is a class for resizing photos which is work as charm.
But what about videos ? can we some how apply same algorithm on a video  file in order to let video meat instagram aspect ratio.

Regards.

**Comment by Triden** [comment]
Theoretically, this is possible, but it requires a lot of resources. Easier to convert on a computer.
