### ISSUE TITLE
"login_required" error message when try to login

### ISSUE THREAD

**Issue by tatarine** [mgp25/Instagram-API#117]
Hi! I try to login using login() method, but I get "login_required" error message. Am I doing something wrong?

````
$i = new Instagram($username, $password, $debug);

try {
    $i->login();
} catch (InstagramException $e) {
    echo $e->getMessage();
    exit();
}
````

**Comment by mgp25** [comment]
@tatarine post the response

**Comment by tatarine** [comment]
```
Array
(
    [0] => HTTP/1.1 200 OK
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
X-Instagram-Ssl-Everywhere: True
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Fri, 01 Apr 2016 18:52:07 GMT
Content-Type: application/json
Set-Cookie: csrftoken=60a4221d39ebfe4ac234e6227b9d0826; expires=Fri, 31-Mar-2017 18:52:07 GMT; Max-Age=31449600; Path=/
Connection: close
Content-Length: 84


    [1] => Array
        (
            [status] => ok
            [errors] => Array
                (
                    [error] => Array
                        (
                            [0] => Sorry, there was a problem with your request.
                        )

                )

        )

)

```

**Comment by mgp25** [comment]
and the request if possible

**Comment by tatarine** [comment]
```
REQUEST: accounts/login/
DATA: ig_sig_key_version=4&signed_body=15526ea845cb577fe75d4946db2bf130eb1b8c9b60075608edd37dd1aef78ad3.{"device_id":"android-246f88a9d327f51e","guid":"d20e7817-c574-4286-935c-e04b9d5e5193","phone_id":"80ce5483-9905-4869-bd39-f80f3f9a893d","username":"USERNAME","password":"PASSWORD","login_attempt_count":"0"}
```

**Comment by mgp25** [comment]
@tatarine seems okay, remove data files and retry again, I just tested it, and works fine

Regards

**Comment by tatarine** [comment]
It's strange, I removed data files, but got the same error. Then I used another account and I get checkpoint_required everytime, then I go to instagram, enter the confirmation code, and then, again, I get checkpoint_required.

**Comment by michelank** [comment]
Hi, I got the same problem.

My logs:

GET /api/v1/friendships/autocomplete_user_list/ HTTP/1.1
Host: i.instagram.com
User-Agent: Instagram 7.19.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Connection: close
Accept: */*
Content-type: application/x-www-form-urlencoded; charset=UTF-8
Cookie2: $Version=1
Accept-Language: en-US
REQUEST: friendships/autocomplete_user_list/ RESPONSE: {"status":"fail","message":"login_required"}


GET /api/v1/feed/timeline/ HTTP/1.1
Host: i.instagram.com
User-Agent: Instagram 7.19.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Connection: close
Accept: */*
Content-type: application/x-www-form-urlencoded; charset=UTF-8
Cookie2: $Version=1
Accept-Language: en-US
REQUEST: feed/timeline/ RESPONSE: {"status":"fail","message":"login_required"}


GET /api/v1/direct_v2/inbox/? HTTP/1.1
Host: i.instagram.com
User-Agent: Instagram 7.19.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Connection: close
Accept: */*
Content-type: application/x-www-form-urlencoded; charset=UTF-8
Cookie2: $Version=1
Accept-Language: en-US
REQUEST: direct_v2/inbox/? RESPONSE: {"status":"fail","message":"login_required"}

**Comment by webfreaks** [comment]
I have this problem too. In the server I got error. But, when I login in from localhost, Everything okay.

**Comment by shineme** [comment]
The same problem

**Comment by DaveOff** [comment]
same problem....

**Comment by Biscuri** [comment]
Same problem, my response with debug:

GET:  feed/timeline?rank_token=4829094848_986189cc-7eb1-4340-a737-79c1be7d6805&ranked_content=true
â† 400 	 67B
RESPONSE: {"message": "login_required", "logout_reason": 2, "status": "fail"}
