### ISSUE TITLE
Private service

### ISSUE THREAD

**Issue by mgp25** [mgp25/Instagram-API#1171]
Hello everyone, 

starting today, i'll be offering a private service. What is this service about?

- You will get all Instagram data (signature key, version, experiments...) as soon as a version comes out. (Instagram updates their app every 3 days in average).
- All these data will be exclusive only for the subscribers of this service
- Direct online support for API questions.

 Why Instagram signature and other data is so important? The adoption ratio of new versions is very high, and if you want your app or service to be stable and in the best performance possible it is highly recommended to always have these data updated. Keeping these data updated also makes the account less likely to be blocked.

With this service, you can contact with me directly via email or skype and i'll  answer your all your questions related to Instagram API.

Price: 100 eur/month
Email: me@mgp25.com

**Comment by jpmoney5065** [comment]
100 euro a month LOL
What's your target market with this, spammers?

**Comment by GuilhermeFM** [comment]
@jpmoney5065 The same people who comes here every day asking question like: "how do i break the apk ssl pinning" or "how do i map all the endpoint". If i was him i would drop this repo and offer a documented end point for instagram that passes through their undocumented one abstracting all the troubles that comes with the "hacking" of the app... and i would charge large amount of money for this.

**Comment by matheuseduardo** [comment]
> "If i was him".. "and i would charge large amount of money for this."

↑↑↑ LOL, BR IS BR 🇧🇷

All the time, I could only see the "spirit" of fighting the giants.
In a collaborative way. And suddenly this announcement.

And EVEN if this is true, I should/will respect his will.
It's a ***really great work***! And he deserves it!

**Comment by anonyzm** [comment]
I must admit, that u should do something with ur latest versions before offering any payed service. Used to use 1.5.1 version for a long time with like 10 000 posts coming out every day and the percentage of unpublished posts was about 2-3%. But after migrating to newest version it became 15%!!!
Very large amount of "other media configure" and "facebook error" 500 occured. Also a strange bug with empty response on video uploading via chunks appeared (from time to time).

**Comment by mgp25** [comment]
@jpmoney5065 people with apps not spammers, there are lot of people with great tools and they need support or help, i receive about 50 mails daily, so that is why. And sure, not spammers are allowed, thats the first rule.

All the API is free, im just giving a personalized support for creators.

@matheuseduardo the API still will be free and ill be continue updating it for free, dont get confused, what im offering is a personalized support and giving updates just when they need it.

@anonyzm What im offering is not the API, is latest data of constants and direct support


Just to clarify, the API will be continue to be free, ill keep updating the API as i have done all this time. This service is  exclusively for people with apps that needs to be updated very quickly or needs to be very stable. And the direct option to contact with me directly.

Please dont get consufed. I receive over 50 mails daily, and sometimes even more, not only with this prohect but more. Ill continue to answer issues here as always. But i need to monetize some of the time i invest doing all this for free.

If you have any question, i'll be happy to answer it.

Regards

**Comment by anonyzm** [comment]
@mgp25 i definately understand this, u r doing a great job! 
But seriosly, how can u consult people wanting "apps that needs to be updated very quickly or needs to be very stable", when ur app is working wrong way in different cases. 
There are really great problems with posting. U may not mention this, when u work with 10 profiles and several posts per day, but when u work with like 1000 profiles and get 1000 / 10000 posts unpublished - this really means something is going very wrong. Especially with "other media configure". 
If u are interested, I can give u a large feedback via PM (consisting of logs of many unpublished posts and their guzzle request params).

**Comment by mgp25** [comment]
@anonyzm i did lots of tests and all passed correctly. Keep in mind that this is not an API for mass publishments and it is not thought for that. So far the API works very stable and with almost no issues. 

Anyway, you can get in touch with me via mail and tell me with more details

---
Im going to close this issue, it seems people is unhappy with this and dont appreciate all what is done. Anyway, ill continue with this API.

Happy week

Regards

**Comment by matheuseduardo** [comment]
@mgp25 Really thank you for all your great work. Sorry my "misunderstanding". I just don't agree with *another* position commented here. **Best regards**!

**Comment by aitte2** [comment]
@anonyzm You are probably just caught. Instagram has much stronger antispam detection since around march 2017. You can google this fact.
