### ISSUE TITLE
HTTP Error 400 Bad Request after 10th April Update

### ISSUE THREAD

**Issue by fragiledream** [mgp25/Instagram-API#1172]
I am not sure what changed but for whatever requests I do, IG is sending HTTP Error 400 Bad Requests and this is happening after the 10th April Update.

**Comment by mgp25** [comment]
@fragiledream please can you post the debug log? Without that, i can do anything. Please, next time remember to post full details and debug log.

Regards

**Comment by fragiledream** [comment]
I know you are not obligated to help me but I was actually using your API on one of my private program. So, I don't exactly have the debugging info offered in your API. However, I can show you the response I am getting from IG:

`{"message": "feedback_required", "spam": true, "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_can_signup/", "feedback_appeal_label": "Report problem", "feedback_ignore_label": "OK", "feedback_action": "report_problem", "status": "fail", "error_type": "signup_block"}`

`+		response	{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Pragma: no-cache
  Vary: Cookie
  Vary: Accept-Language
  Cache-Control: no-store, must-revalidate, no-cache, private
  Date: Thu, 13 Apr 2017 08:59:56 GMT
  Set-Cookie: rur=FRC; Path=/
  Set-Cookie: csrftoken=TFNLfYRADdNwEgmULchD9D0kPrh6aOk2; expires=Thu, 12-Apr-2018 08:59:56 GMT; Max-Age=31449600; Path=/; Secure
  Connection: keep-alive
  Content-Length: 511
  Content-Language: en
  Content-Type: application/json
  Expires: Sat, 01 Jan 2000 00:00:00 GMT
}}	System.Net.Http.HttpResponseMessage
`

**Comment by mgp25** [comment]
@fragiledream your account is flagged as spam and blocked by Instagram. Read the `feedback_message`:

> "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again > later. We restrict certain content and actions to protect our community. Tell us if you think we > made a mistake."

Regards
