### ISSUE TITLE
How to get more than 200 friendship requests at a time?

### ISSUE THREAD

**Issue by rainwater11** [mgp25/Instagram-API#1176]
Using getPendingFriendshipRequests appears to limit the amount of friendship requests to 200.
Here is the response to that function:
```
InstagramAPI\Response\FollowerAndFollowingResponse Object
(
    [users] => Array
        (
        ...
        )
    [big_list] =>
    [page_size] => 200
    [status] => ok
)
```
Is it possible to change big_list to true? If that is possible, then maybe we could get more than 200 at a time.

**Comment by mgp25** [comment]
Duplicated

**Comment by rainwater11** [comment]
> Duplicated
Where is the other one?

**Comment by MrLuit** [comment]
https://github.com/mgp25/Instagram-API/issues/602
