### ISSUE TITLE
aspect ration validation

### ISSUE THREAD

**Issue by golches** [mgp25/Instagram-API#1178]
this picture can't pass aspect ratio validation even if it is under 0.80

http://imgur.com/R1Iqk4t

**Comment by aitte2** [comment]
Not legal.

    /**
     * Lowest allowed aspect ratio (4:5, meaning portrait).
     *
     * These are decided by Instagram. Not by us!
     *
     * @var float
     *
     * @see https://help.instagram.com/1469029763400082
     */
    const MIN_RATIO = 0.8;
    /**
     * Highest allowed aspect ratio (1.91:1, meaning landscape).
     *
     * These are decided by Instagram. Not by us!
     *
     * @var float
     */
    const MAX_RATIO = 1.91;

**Comment by golches** [comment]
picture width 326 height 408 =======> ratio 0.799
 so picture meet the instagram rules ratio is between 0.80>0.799>1.91

**Comment by mgp25** [comment]
![wait wut](https://www.mememaker.net/static/images/memes/4552515.jpg)


What kind of logic do you use? 0.799 is not greater than 1.91

If your ratio is 0.799 and the min is 0.80 and the max is 1.91, you are not in between of these

>0.799 < 0.80

Correct values should be in between:

>0.80 < x < 1.91

Greater than 0.80 and less than 1.91

Regards

**Comment by golches** [comment]
sorry its not me its my little brother, and he drink alot yesterday XD
