### ISSUE TITLE
Class 'string' not found in JsonMapper.php

### ISSUE THREAD

**Issue by SkyNeT-ProD** [mgp25/Instagram-API#1179]
**Code executed** 
```
        public function goGetUsernameInfo($user)
        {
            if(is_numeric($user))
                return $this->_ig->getUserInfoById($user)->getUser();

            return $this->_ig->getUserInfoByName($user)->getUser();
        }
```
**The problem**
```
Fatal error: Uncaught Error: Class 'string' not found in /vendor/netresearch/jsonmapper/src/JsonMapper.php:544
Stack trace:
#0 /vendor/netresearch/jsonmapper/src/JsonMapper.php(376): JsonMapper->createInstance('string')
#1 /vendor/netresearch/jsonmapper/src/JsonMapper.php(265): JsonMapper->mapArray(Array, Array, 'string')
#2 /vendor/netresearch/jsonmapper/src/JsonMapper.php(280): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\Model\User))
#3 /vendor/mgp25/instagram-php/src/Client.php(433): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\UserInfoResponse))
#4 /vendor/mgp25/instagram-php/src/Request.php(105): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\UserInfoResponse), Object(stdClass), true, NULL)
#5 /vendor/mgp25/instagram-php/src/Instagram.php(2310): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\UserInfoResponse))
#6 /www/myinsta/class in /vendor/netresearch/jsonmapper/src/JsonMapper.php on line 544
```

**Error always thrown for this one**
> GET:  users/4943440220/info/
> ← 200 	 735B
> RESPONSE: {"user": {"pk": 4943440220, "username": "profile_journal", "full_name": "Top Models By Profile Journal", "is_private": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/17819012_450551855336703_6232283587022946304_n.jpg", "profile_pic_id": "1483012099478564261_4943440220", "is_verified": false, "has_anonymous_profile_picture": false, "media_count": 68, "geo_media_count": 0, "follower_count": 5762, "following_count": 5756, "biography": "Top Models from all over the \ud83c\udf0e \nEvery day a new girl\ud83d\udc6f 2017\ud83d\udd25 Send us your photo and we will upload it. We also running weekly competition \ud83d\udd25", "external_url": "", "usertags_count": 0, "is_favorite": false, "has_chaining": true, "hd_profile_pic_versions": [{"width": 320, "height": 320, "url": "http://scontent.cdninstagram.com/t51.2885-19/s320x320/17819012_450551855336703_6232283587022946304_n.jpg"}, {"width": 640, "height": 640, "url": "http://scontent.cdninstagram.com/t51.2885-19/s640x640/17819012_450551855336703_6232283587022946304_n.jpg"}], "hd_profile_pic_url_info": {"url": "http://scontent.cdninstagram.com/t51.2885-19/17819012_450551855336703_6232283587022946304_n.jpg", "width": 1080, "height": 1080}, "profile_context": "Followed by millionsslay, sneakers_clothes_hoes, nicklocker71 + 5 more", "profile_context_links_with_user_ids": [{"start": 12, "end": 24}, {"start": 26, "end": 47}, {"start": 49, "end": 61}, {"start": 64, "end": 70}], "profile_context_mutual_follow_ids": [4544179072, 277204513, 4146922855], "is_business": false, "include_direct_blacklist_status": true, "auto_expand_chaining": false}, "status": "ok"}

> Same for this pk : 4979013099

**Work without any error**
> GET:  users/1934286080/info/
> ← 200 	 557B
> RESPONSE: {"user": {"pk": 1934286080, "username": "alam_fung", "full_name": "LAM JING FUNG", "is_private": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/16230408_1275383495882483_2150591001004081152_a.jpg", "profile_pic_id": "1443235258177781828_1934286080", "is_verified": false, "has_anonymous_profile_picture": false, "media_count": 61, "geo_media_count": 0, "follower_count": 462, "following_count": 1311, "biography": "Drawing\u2665\u266a      \nDOTA2\u2665 (\u0e07 \u2022\u0300_\u2022\u0301)\u0e07\nBIGBANG\u2665  \u265a", "external_url": "", "has_biography_translation": true, "usertags_count": 4, "is_favorite": false, "has_chaining": true, "hd_profile_pic_versions": [{"width": 320, "height": 320, "url": "http://scontent.cdninstagram.com/t51.2885-19/s320x320/16230408_1275383495882483_2150591001004081152_a.jpg"}, {"width": 640, "height": 640, "url": "http://scontent.cdninstagram.com/t51.2885-19/s640x640/16230408_1275383495882483_2150591001004081152_a.jpg"}], "hd_profile_pic_url_info": {"url": "http://scontent.cdninstagram.com/t51.2885-19/16230408_1275383495882483_2150591001004081152_a.jpg", "width": 960, "height": 960}, "is_business": false, "include_direct_blacklist_status": true, "auto_expand_chaining": false}, "status": "ok"}
> 

**_The only difference that I can see is the pk is bigger for profile_journal compared to all the others accounts that I tested._**

**Comment by SteveJobzniak** [comment]
You can fix it like this by editing the file manually:

https://github.com/mgp25/Instagram-API/commit/f3b27281cba84550d8c8ce175b9163b2a9da08db

**Comment by samet05203** [comment]
I didnt understand how can I solve problem
Fatal error: Class 'JsonMapper' not found in C:\AppServ\www\instaposter\vendor\mgp25\instagram-php\src\Client.php on line 170
