### ISSUE TITLE
wrong use of empty in library

### ISSUE THREAD

**Issue by golches** [mgp25/Instagram-API#1180]
in line 201 you use `empty($this->settings->get('uuid'))` so it returne 
`Can't use method return value in write context`, 
and after a little searching on google, it say you can't use a function return within `empty()` and the right use is 
```
$uuid=$this->settings->get('uuid');
if(empty($uuid))
```
after i did that i obtain a new error wich is explained in #1173 

and i use the the last version of library, and php is 7.0

**Comment by SteveJobzniak** [comment]
@golches I see. It means _you_ are **actually running** PHP 5.4 or even older than that! You definitely do _not_ have PHP 5.6 (the minimum version we support) and you definitely do **not** have 7.0. ;-)

In PHP 5.6 and 7.0, empty() supports function calls, which is how we use it:

```php
php > echo phpversion();
7.0.17
php > var_dump(empty(trim('  ')));
bool(true)

php > echo phpversion();
5.6.30
php > var_dump(empty(trim('  ')));
bool(true)
```

Here is what PHP docs say:

http://php.net/empty
```
Note:
Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.
```

See "Prior to 5.5". Meaning **you** are using PHP 5.4 or older.

Also, your other ticket (#1173) is for the same reason. Old versions before PHP 5.6 did not support `[]` arrays format and only supported `array()` format.

Please fix your PHP installation and don't make more tickets until you run 5.6 or newer. :-)

You can check PHP version with "php -v" from terminal, or with "echo phpversion();" in a script.

There is no way at all that you are using PHP 5.6+.
