### ISSUE TITLE
Bug: Facebook OTA Field Encoding

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1181]
Current values:

```
+ $ ag FACEBOOK_OTA_FIELDS
src/Constants.php
28:    const FACEBOOK_OTA_FIELDS = 'update%257Bdownload_uri%252Cdownload_uri_delta_base%252Cversion_code_delta_base%252Cdownload_uri_delta%252Cfallback_to_full_update%252Cfile_size_delta%252Cversion_code%252Cpublished_date%252Cfile_size%252Cota_bundle_type%252Cresources_checksum%257D';

src/Instagram.php
783:        ->addParams('fields', Constants::FACEBOOK_OTA_FIELDS)
```

That heavily encoded string looks wrong and is almost guaranteed a bug. Because remember that all addParams() are run through `http_build_query()` in Request.php, which will do URL-encoding of all % and other special signs:

```php
            $endpoint = $this->_url.'?'.http_build_query($this->_params);
```

Which means that our constant:

`php > echo http_build_query(['fields' => 'update%257Bdownload_uri%252Cdownload_uri_delta_base%252Cversion_code_delta_base%252Cdownload_uri_delta%252Cfallback_to_full_update%252Cfile_size_delta%252Cversion_code%252Cpublished_date%252Cfile_size%252Cota_bundle_type%252Cresources_checksum%257D']);`

Gets encoded again and will actually be added to the URL query as:

`fields=update%25257Bdownload_uri%25252Cdownload_uri_delta_base%25252Cversion_code_delta_base%25252Cdownload_uri_delta%25252Cfallback_to_full_update%25252Cfile_size_delta%25252Cversion_code%25252Cpublished_date%25252Cfile_size%25252Cota_bundle_type%25252Cresources_checksum%25257D`

That's a whopping **triple layers of URL encoding** and definitely something that Instagram's server won't understand at all.

Anyway, let's backtrack a bit and look at the current constant value (which is a dual-layered URL encoding), **after we URLdecode** it ONCE:

`update%7Bdownload_uri%2Cdownload_uri_delta_base%2Cversion_code_delta_base%2Cdownload_uri_delta%2Cfallback_to_full_update%2Cfile_size_delta%2Cversion_code%2Cpublished_date%2Cfile_size%2Cota_bundle_type%2Cresources_checksum%7D`

Still encoded... So let's URLdecode it again:

`update{download_uri,download_uri_delta_base,version_code_delta_base,download_uri_delta,fallback_to_full_update,file_size_delta,version_code,published_date,file_size,ota_bundle_type,resources_checksum}`

So as you can see, the current constant as-stored in Constants.php already has two layers of URL-encoding on it. And we're adding a 3rd layer with http_build_query.

@mgp25 My guess is that we want to send the _final_ URL query exactly as you had written it in the constants. In that case, we must simply URLdecode it _once_ in our constants, so that http_build_query() properly adds only a 2nd layer of URL-decoding, as Instagram wants it.

In short: If this theory is correct, we just need to update the constant to the following:

`const FACEBOOK_OTA_FIELDS = 'update%7Bdownload_uri%2Cdownload_uri_delta_base%2Cversion_code_delta_base%2Cdownload_uri_delta%2Cfallback_to_full_update%2Cfile_size_delta%2Cversion_code%2Cpublished_date%2Cfile_size%2Cota_bundle_type%2Cresources_checksum%7D';`

After that updated constant goes through http_build_query, it will become the exact query string that was currently stored in the constants.

I don't have the server logs to verify if this is right (perhaps we even need to do full URL-decoding of all two layers) so I'll leave this one to you to figure out with this info. :-) My guess is that we only need to decode a single layer, though. In that case, the new constant in the above paragraph is all we need.

**Comment by mgp25** [comment]
Fixed: https://github.com/mgp25/Instagram-API/commit/3aca20ed3ddfef7b9c4817c19c03af387fc9b265
