### ISSUE TITLE
Constants Update 

### ISSUE THREAD

**Issue by Diddlik** [mgp25/Instagram-API#1184]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

I just wanted to ask if updating Constants is no longer planned or with delay for all not paid users?
If so, would you like to say which constants must be updated on Instagram app update?

**Comment by mgp25** [comment]
@Diddlik updating constants will be done when strictly required. Mostly all the constants + check if endpoints has changed

Regards
