### ISSUE TITLE
What function to read DM share

### ISSUE THREAD

**Issue by OwlGreenApple** [mgp25/Instagram-API#1186]
Hei,

What function to read DM share ?
<pre>
      4 => ThreadItem {#267 ▼
        +item_id: "27501916801398989864057131503714304"
        +item_type: "reel_share"
        +text: null
        +media_share: null
        +media: null
        +user_id: "1476017426"
        +timestamp: "1490881897179619"
        +client_context: "b46ef568-ea60-4e96-a755-69afdf535876"
        +status: null
        +message: null
        +fullResponse: null
      }
</pre>

item type : reel_share. I cant found  function to do that on wiki or Instagram class. 
I need something to do with item_id so i can see the data. thank you

**Comment by mgp25** [comment]
@OwlGreenApple it is not implemented

Regards

**Comment by OwlGreenApple** [comment]
Im so sad.. so only displaying the message text, cant display our message to stories of other people.

@mgp25

**Comment by mgp25** [comment]
Im sad too, i want a healthy smoothie but its sold out
