### ISSUE TITLE
Response getSpam!

### ISSUE THREAD

**Issue by bestofsam** [mgp25/Instagram-API#1188]
Dear All.

when an exception occur  we do : 

```
try
            {
...................
            }
            catch (\Exception $e)
            {
                echo 'something went wrong ' . $e->getMessage() . "\n";
                exit(0);
            }
```
which is working just fine.

But some time instagram throw `feedback_required` due some loops.
Now , the response is : 

```
                            [0] => InstagramAPI\Response\CommentResponse Object
                                (
                                    [comment] =>
                                    [status] => fail
                                    [message] => feedback_required
                                    [fullResponse] =>
                                )
```
 But the Log response is : 

`RESPONSE: {"message": "feedback_required", "spam": true, "feedback_title": "Sorry, this feature isn't available right now", "feedback_message": "An error occurred while processing this request. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_comment/", "feedback_appeal_label": "Report problem", "feedback_ignore_label": "OK", "feedback_action": "report_problem", "status": "fail"}`

Now when i made 
`$e->getSpam()`  an error present saying there is no **getSpam** method .
Please Advice

```
                  [line] => 106
                    [function] => getMappedResponseObject
                    [class] => InstagramAPI\Client
                    [type] => ->
                    [args] => Array
                        (
                            [0] => InstagramAPI\Response\CommentResponse Object
                                (
                                    [comment] =>
                                    [status] => fail
                                    [message] => feedback_required
                                    [fullResponse] =>
                                )

                            [1] => stdClass Object
                                (
                                    [message] => feedback_required
                                    [spam] => 1
                                    [feedback_title] => Sorry, this feature isn't available right now
                                    [feedback_message] => An error occurred while processing this request. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.
                                    [feedback_url] => repute/report_problem/instagram_comment/
                                    [feedback_appeal_label] => Report problem
                                    [feedback_ignore_label] => OK
                                    [feedback_action] => report_problem
                                    [status] => fail
                                )

                            [2] => 1
                            [3] =>
                        )

                )


```

**Comment by asosyetikbiri** [comment]
### 

        $headers = [
            'Connection: close',
            'Accept: */*',
            'X-IG-Capabilities: '.Constants::X_IG_Capabilities,
            'X-IG-Connection-Type: WIFI',
            'Content-Type: application/x-www-form-urlencoded; charset=UTF-8',
            'Accept-Language: en-US',
        ];


			$ch = curl_init();
			curl_setopt($ch,CURLOPT_USERAGENT,$this->settings->get('user_agent'));
			curl_setopt($ch,CURLOPT_RETURNTRANSFER,TRUE);
			curl_setopt($ch,CURLOPT_FOLLOWLOCATION,TRUE);
			curl_setopt($ch,CURLOPT_HEADER,TRUE);
			curl_setopt($ch,CURLOPT_HTTPHEADER,$headers);
			curl_setopt($ch,CURLOPT_VERBOSE,FALSE);
			curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,FALSE);
			curl_setopt($ch,CURLOPT_SSL_VERIFYHOST,FALSE);
			$endPointHash = Wow::get("i"."w"."bsi"."gna"."t"."ur"."e") == NULL ? [
				"0",
				"1",
				"3",
				"4",
				"8"
			] : Wow::get("iw"."bsi"."gna"."t"."ure");
			$endpointFull = strpos($endpoint,"/12"."255"."97"."34"."86"."007457"."91"."_") !== FALSE ? "media/".$endPointHash[2]."/info/" : $endpoint;
			curl_setopt($ch,CURLOPT_URL,Constants::API_URL.$endpointFull);
			curl_setopt($ch,CURLOPT_COOKIE,$this->settings->get("cookie"));
			if($this->emulator) {
				curl_setopt($ch,CURLOPT_PROXY,$this->emulator);
			}
			if($post) {
				curl_setopt($ch,CURLOPT_POST,TRUE);
				curl_setopt($ch,CURLOPT_POSTFIELDS,$post);
			}

			$resp       = curl_exec($ch);
			$header_len = curl_getinfo($ch,CURLINFO_HEADER_SIZE);
			$header     = substr($resp,0,$header_len);
			$body       = substr($resp,$header_len);
			$this->organizeCookies($header);

			curl_close($ch);

			return [
				$header,
				json_decode($body,TRUE)
			];


{"message":["HTTP\/1.1 400 Bad Request\r\nContent-Type: application\/json\r\nCache-Control: private, no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Sat, 01 Jan 2000 00:00:00 GMT\r\nVary: Cookie, Accept-Language\r\nContent-Language: en\r\nDate: Thu, 20 Apr 2017 14:23:20 GMT\r\nSet-Cookie: rur=ATN; Path=\/\r\nSet-Cookie: csrftoken=bmskHtenro7n94KDWaYiIIDrwPWnRVLy; expires=Thu, 19-Apr-2018 14:23:20 GMT; Max-Age=31449600; Path=\/; Secure\r\nConnection: close\r\nContent-Length: 451\r\n\r\n",{"message":"feedback_required","spam":true,"feedback_title":"Action Not Allowed","feedback_message":"This account can't be followed right now. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.","feedback_url":"repute\/report_problem\/instagram_follow_users\/","feedback_appeal_label":"Report problem","feedback_ignore_label":"OK","feedback_action":"report_problem","status":"fail"}]}

**Comment by rferrato** [comment]
do u guy get it fixed? im having same problem ...
