### ISSUE TITLE
please help me get each user from getSelfUsersFollowing return

### ISSUE THREAD

**Issue by fanliv** [mgp25/Instagram-API#1196]
as I know, this code bellow can get a list of my following users
`$following = $ig->getSelfUsersFollowing ();`

please tell me how to get each user from this to unfollow them with 
`unfollow(string $userId);`

**Comment by mgp25** [comment]
Iterate and unfollow them one by one.

Regards

**Comment by fanliv** [comment]
@mgp25 I want to know what getSelfUsersFollowing function return, a string, an array, or a list?
how do I unfollow from this? something like `$following->unfollow();`

**Comment by mgp25** [comment]
@fanliv have you read the documentation? It is detailed there. You can also dump the variable or even set debug to true to see the actual response.

About the `unfollow` it is well explained too. You can find all the documention in the wiki and in the source code. You can use shortcuts to get where you want ( ctrl + f / cmd + f )

Regards

**Comment by mgp25** [comment]
@fanliv do a var_dump of `getSelfUsersFollowing` and post it here. This is most PHP than API stuff

**Comment by fanliv** [comment]
[var_dump log.TXT](https://github.com/mgp25/Instagram-API/files/947529/var_dump.log.TXT)
it's too long, and I paste it in to attach file

**Comment by mgp25** [comment]
@fanliv do you see that there is an array ("users") with 136 elements right?.

You need to do `getUsers()` now you have that array and you can iterate it.

When you get one of these elements, you can do `getPk()` which is the `username_id`. I recommend you to practice and test it. 

Examples in this repo might help you

Regards

**Comment by fanliv** [comment]
@mgp25 Thank you very much! I got it.
I've learned php from a few days ago, sorry about some noob question.
Thank you again!

**Comment by fanliv** [comment]
@mgp25 one more question: how many user can I unfollow per day (per hour, per min)?

**Comment by DanielSokil** [comment]
60 unfollow/follow hour
