### ISSUE TITLE
Issue after 10th April update

### ISSUE THREAD

**Issue by fragiledream** [mgp25/Instagram-API#1197]
Hey,

Firstly, I want to thank you for the API. I know you have removed the registration module to avoid misuse by spammers but I am using your API for a while now for personal usage. It seems that after 10th April update, the registration method you showed here won't work as it always either returns HTTP Error 400 bad requests with a response message having _"spam": "true"_ and/or the account is insta banned. I can create through the browser/manually without any problem though, so it's not an IP thing.

I would really appreciate if you can offer some insight.

**Comment by mgp25** [comment]
I wont be giving support to registration stuff.

Regards
