### ISSUE TITLE
How to add caption on story single photo?

### ISSUE THREAD

**Issue by zerotolerance** [mgp25/Instagram-API#1198]
Hi,

How to add caption and user tags on story single photo?

For example:

[Link](http://hizliresim.com/4POM8q)

[UserTag and Text Example](http://hizliresim.com/7qZNgP)

**Comment by mgp25** [comment]
@zerotolerance it is not implemented yet, at least not in a friendly user way

Regards

**Comment by SteveJobzniak** [comment]
@zerotolerance I am pretty sure that's a client-side feature and is generated as an image inside the app before sending to the server.

So if you want something like that you need a image editing library for PHP to add text/stuff to your image. Or you may have to write it yourself if no library exists.

Functions like this can do it: http://php.net/manual/en/function.imagettftext.php
