### ISSUE TITLE
REQUEST: find users by phone numbers

### ISSUE THREAD

**Issue by zerodwide** [mgp25/Instagram-API#12]
Hi @mgp25, thanks for great work!
Instagram can upload mobile contact numbers to its server and find out which one has Instagram account and let you to follow.

it would be awesome feature if you could add this to API!

thanks in advance.

**Comment by Stepkaa** [comment]
Yep, this is actually more interesting then uploading photos. But there is a very high chance to have accounts instantly banned for searching mobile numbers. On mobile version it takes, like, 3-5 syncs to get a ban (not permanent though).

**Comment by zerodwide** [comment]
@Stepkaa i didn't meant to instantly syncing lots of numbers, i thinking about an app that be universal among all social apps!
you simply install it, and it will help you to find out all of social apps of one single contact!
and soon more functionality could be added, like having chat with them in any social you like.

for example, i am member of 4 social apps like whatsapp, telegram, instagram, tango. 
when i open my "universal social app" (weird name :D) and look for one of my friend from contacts, i see in all social he is member of, and simply see his/her profile! and in future have conversation with him/her on that social, by chat in whatsapp or send message in direct of instagram, or following!

i believe it would be so amazing app!

**Comment by mgp25** [comment]
```php
$contacts = array(
  array(
    'first_name' => 'whatever',
    'phone_numbers' => array('34123456789'),
    'email_addresses' => array('whatever@gmail.com')
  )
);

$i->syncFromAdressBook($contacts);
```
https://github.com/mgp25/Instagram-API/commit/5f82b3d26ba2a6ea4945cefe17a607777f67749a

**Comment by instauser** [comment]
Hey, did they change something on that endpoint? The exact example you gave isn't working for me:

REQUEST: address_book/link/?include=extra_display_name,thumbnails
RESPONSE: {"status":"fail","message":"Invalid arguments"}

**Comment by Stepkaa** [comment]
Captured traffic from iPhone, but all seems to be the same: 
`'contacts=[{"phone_numbers":["+xxxxxxxxxxx"],"first_name":"Alexander","email_addresses":["xxx@xxx.com"]}]' \`

**Comment by moghis** [comment]
can i get Users **just** with phone number in this api
