### ISSUE TITLE
How get top media by hashtag?

### ISSUE THREAD

**Issue by likhatskiy** [mgp25/Instagram-API#1200]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Request to "feed/tag/{$hashtagString}/" (method getHashtagFeed in code) returns only new media? but dont return top media. How i can get from instagram top media by hashtag?

**Comment by mgp25** [comment]
@likhatskiy yes, that function returns both, `ranked_items` is what you call top media, other items are recent ones.

Regards
