### ISSUE TITLE
Problems with response to reels_tray

### ISSUE THREAD

**Issue by iSanechek** [mgp25/Instagram-API#1201]
Hi guys. I have one offtopic question. 
I do call the endpoint `request('feed/reels_tray/')` and get response for the majority of users with null items, but using official app of these users have new and old items. How to solve this problem?

**Comment by SteveJobzniak** [comment]
I have actually noticed that Instagram has changed the reels_tray behavior recently. It used to be very fast at detecting new stories. Now it can take an hour for someone's new story to appear in the reels_tray API. Which is weird. But the app is faster at seeing their stories there.

Perhaps they've separated that API into two separate calls.

Anyway... the reels_tray lists every person who has media. But if they are far back in the list (unlikely that people will look at them) they will be NULL, probably to save server bandwidth.

You can use one of the two "direct" story feed APIs to look at individual users instead, to always get the latest stories. The reels tray is not reliable.

**Comment by iSanechek** [comment]
Thank you for reply.

**Comment by mgp25** [comment]
@iSanechek use this function instead: `getReelsMediaFeed()`

And yes, it is what the app uses, and it contains all the items

Regards
