### ISSUE TITLE
Image is getting distorted.

### ISSUE THREAD

**Issue by vishal2947** [mgp25/Instagram-API#1202]
HI guys,

When i am posting images using API, some of the images are getting distorted i.e their aspect ratio gets changed. For ex: this image:
https://www.instagram.com/p/BTSEd6Uhn4O/

And actual image:
https://www.facebook.com/AyushPokharelArt/photos/a.172329333122267.1073741828.166978933657307/429854337369764/?type=3&theater&notif_t=like&notif_id=1493092938029598

When i am uploading same image using Instagram app directly, it is working without any issue. Please help!

**Comment by SteveJobzniak** [comment]
I guess the image file has metadata that sets a different pixel aspect ratio. And the official app reads that metadata and processes it and writes a correct final image.

We have an image processor too but it doesn't handle changing pixel aspect ratio, but you can try anyway to see if it helps:

```php
$resized = new \InstagramAPI\ImageAutoResizer($photo_filename);
$ig->uploadTimelinePhoto($resized->getFile(), ['caption' => $captionText]);
```

**Comment by vishal2947** [comment]
Now i am getting error message " Class 'InstagramAPI\ImageAutoResizer' not found".

**Comment by SteveJobzniak** [comment]
@vishal2947 Update to 2.x of the API, it was added in 2.x.

Preferably use dev-master because it has many new, small fixes:

```
composer require mgp25/instagram-php dev-master
```

**Comment by vishal2947** [comment]
Totally working...:) Thanks a ton..

**Comment by SteveJobzniak** [comment]
@vishal2947 Wow sweet! :)

**Comment by MwSpaceLLC** [comment]
I man, upgrade sdk and change class to work publish:

1) composer require mgp25/instagram-php

2) Change your $var in any new resize class:

`// Adjust the photo size
 $resizer = new \InstagramAPI\Media\Photo\InstagramPhoto($photo);
`
by man 😎
