### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by pr0ph0z** [mgp25/Instagram-API#1203]
I try to upload photo but the unnecessary response is out.
![qqq](https://cloud.githubusercontent.com/assets/17337978/25378036/5e235e58-29d3-11e7-9638-6f0637ca5aac.png)

**Comment by mgp25** [comment]
@pr0ph0z i dont know what you mean. And please post debug log dont do image captures of it, it makes us a pain to search things in that. Give more details and post (not image) the debug log.

Regards
