### ISSUE TITLE
 why the object unsets all variables when using $_POST?

### ISSUE THREAD

**Issue by MUHAMMADIR** [mgp25/Instagram-API#1204]
I'm using InstagramAPI to create a script; but it has a strange bug! when I assign the variables directly such as `$mediaId='156000005198888521'`, it works well. But if I assign it by` $mediaId=$_POST['abc']`, when I define a new object of the API such as `$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug)`, that object **unsets(deletes)** **all variables** in the script. I'm sure about it because I can` var_dump()` or `echo` all variables before line `$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug)`, but after this line I can't do that. how can I solve it? this is my script code:
```
set_time_limit(0);
date_default_timezone_set('UTC');

require '/home/me/vendor/autoload.php';

/////// CONFIG ///////
$username = 'no_ideaw';
$password = '***********';
$debug = true;
$truncatedDebug = false;
$mediaId = $_POST['abc'];
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try{
    $ig->setUser($username, $password);
    $ig->login();
} catch(\Exception $e){
    echo 'something went wrong:'.$e->getMessage();
}
try{
    $ig->like($mediaId);
} catch(\Exception $e){
    echo 'something went wrong:'.$e->getMessage();
}

?>
```

**Comment by MUHAMMADIR** [comment]
also u can see this screen shot of how I send the variable and its output in terminal.
[see photo](https://ibb.co/dQdkVk)
@mgp25  @SteveJobzniak

**Comment by SteveJobzniak** [comment]
Hi! What a funny ticket. Lots of confidence about wrong conclusions. ;-)

> when I define a new object of the API such as $ig = new \InstagramAPI\Instagram($debug, $truncatedDebug), that object unsets(deletes) all variables in the script

No it doesn't. How do you think we are able to `$ig->setUser($username, $password);` if our library deleted all variables in the script? ;-)

And there is nothing in our library that edits `$_POST` or `$_GET`.

And there is no code in our library that calls `unset()`.

I still took it seriously and here's my results:

```php
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require 'vendor/autoload.php';

/////// CONFIG ///////
$username = 'no_ideaw';
$password = '***********';
$debug = true;
$truncatedDebug = false;
$mediaId = $_GET['abc'];
//////////////////////
echo 'before new class: '.$mediaId.PHP_EOL;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
echo 'after new class: '.$mediaId.PHP_EOL;
$mediaId = 'sss';
echo 'after new class: '.$mediaId.PHP_EOL;

try{
    //$ig->setUser($username, $password);
    //$ig->login();
} catch(\Exception $e){
    echo 'something went wrong:'.$e->getMessage();
}
try{
    //$ig->like($mediaId);
} catch(\Exception $e){
    echo 'something went wrong:'.$e->getMessage();
}

?>
```

```
$ php-cgi -f test.php abc=1324324
before new class: 1324324
after new class: 1324324
after new class: sss
```
