### ISSUE TITLE
How turn GuzzleHttp\Client debug On/Of

### ISSUE THREAD

**Issue by lonlyman** [mgp25/Instagram-API#1206]
the debug option dos not affect GuzzleHttp\Client debug function , how to turn it on or of ?

**Comment by SteveJobzniak** [comment]
We do not have such a feature. Why do you need it? We only care about debugging server queries/responses, which is what the debug option shows. If there is a guzzle problem it throws an exception, i.e. if your proxy is bad or if the connection timed out.

I can't think of any scenario where we would want to see ultra-detailed HTTP traffic.

**Comment by SteveJobzniak** [comment]
Closing due to 2 days of inactivity and no reason to add this.
