### ISSUE TITLE
Can't Unlock Checkpoint Required

### ISSUE THREAD

**Issue by nubinter** [mgp25/Instagram-API#1207]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [x] Other

### Describe your issue

Hello again
I know this will be flag as invalid, but again I don't know where to ask. I have an account and been using it for a few months now since v1 api. Now, I don't know what happen but I can't pass the checkpoint_required. I already unlock it manually using Instagram Official Application, but still have checkpoint_required if I try to login again. I also try to unlock it via instagram using my phone browser, but no difference. Do you guys know what could be the possibility of it? I am using another Instagram account but there is no problem with it.

**Comment by mgp25** [comment]
Yes, because you are probably using the account in a server which is in location A, and you are verifying/unlocking your account in location B. Because of these 2 locations, you are getting that. Use it in the same network/location

Regards

**Comment by nubinter** [comment]
Thanks mgp25

What confused me is my othe account is normal. And the othe strange thing is In this account if I want to unlock the checkpoint, the location show the wrong country. My server located in UK, and other account the checkpoint unlocking show UK, except this troublesome account, it show Indonesia. is there a chance if I deactivated this account and activated it back the problem will go away?

**Comment by alyssazyx** [comment]
Hi guys. i need your help, :( i tried logging in my instagram account but everytime I do so, there's always a challenge required. i tried to remove my email, change my password but its always the same. then i tried to login my friends account and then it required challenge also. pls help me :( im no tech geek pls @nubinter

**Comment by mgp25** [comment]
Login using your device

Regards

**Comment by muthu-kc** [comment]
You can send challenge code from the same server and verify then you will get user session.
