### ISSUE TITLE
Get blocked user list

### ISSUE THREAD

**Issue by passion1989** [mgp25/Instagram-API#1208]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Is there any API for getting my blocked user list?
In Instagram app / Settings, you can see blocked user list by you.
I tried to search the API for it. It seems relationships API can retrieve it.
By searching, I can find only this one.

```php
public function getUserFriendship($userId)
{
         return $this->request("friendships/show/{$userId}/")->getResponse(new Response\Model\FriendshipStatus());
}
```
On this response, can check this user blocked me or not.

By using this API, can't retrieve my blocked user list.

Is there any API like this; `/"friendships/blocked/`

**Comment by mgp25** [comment]
@passion1989 here you go: https://github.com/mgp25/Instagram-API/commit/cd5ac4fae09ccf2e9ae4127318dc70f38f8233ff

```php
    $i->getBlockedList();
```
