### ISSUE TITLE
Facebook | Error (HTTP code 502)

### ISSUE THREAD

**Issue by anonyzm** [mgp25/Instagram-API#1209]
Good day!
Getting rather big percent of Facebook | Error response when doing photo configure.
It seems to be not connected to any parameters of post, cause sometimes i got this error, then repost same message and everything goes OK.
Also this sympthom is really-really annoying, cause after getting this error, sometimes post is getting published, and sometimes not...
Have any1 had the same problem?

It shows up like the exception "_No response from server. Either a connection or configuration error._"

**Here is the response.** It has 502 http response code.
`<!DOCTYPE html> <html lang="en" id="facebook"> <head> <title>Facebook | Error</title> <meta charset="utf-8"> <meta http-equiv="cache-control" content="no-cache"> <meta http-equiv="cache-control" content="no-store"> <meta http-equiv="cache-control" content="max-age=0"> <meta http-equiv="expires" content="-1"> <meta http-equiv="pragma" content="no-cache"> <meta name="robots" content="noindex,nofollow"> <style> html, body { color: #141823; background-color: #e9eaed; font-family: Helvetica, Lucida Grande, Arial, Tahoma, Verdana, sans-serif; margin: 0; padding: 0; text-align: center; } #header { height: 30px; padding-bottom: 10px; padding-top: 10px; text-align: center; } #icon { width: 30px; } h1 { font-size: 18px; } p { font-size: 13px; } #footer { border-top: 1px solid #ddd; color: #9197a3; font-size: 12px; padding: 5px 8px 6px 0; } </style> </head> <body> <div id="header"> <a href="//www.facebook.com/"> <img id="icon" src="//static.xx.fbcdn.net/images/logos/facebook_2x.png" /> </a> </div> <div id="core"> <h1 id="sorry">Sorry, something went wrong.</h1> <p id="promise"> We're working on it and we'll get it fixed as soon as we can. </p> <p id="back-link"> <a id="back" href="//www.facebook.com/">Go Back</a> </p> <div id="footer"> Facebook <span id="copyright"> © 2017 </span> <span id="help-link"> · <a id="help" href="//www.facebook.com/help/">Help Center</a> </span> </div> </div> <script> document.getElementById('back').onclick = function() { if (history.length > 1) { history.back(); return false; } }; // Adjust the display based on the window size if (window.innerHeight < 80 || window.innerWidth < 80) { // Blank if window is too small document.body.style.display = 'none'; }; if (window.innerWidth < 200 || window.innerHeight < 150) { document.getElementById('back-link').style.display = 'none'; document.getElementById('help-link').style.display = 'none'; }; if (window.innerWidth < 200) { document.getElementById('sorry').style.fontSize = '16px'; }; if (window.innerWidth < 150) { document.getElementById('promise').style.display = 'none'; }; if (window.innerHeight < 150) { document.getElementById('sorry').style.margin = '4px 0 0 0'; document.getElementById('sorry').style.fontSize = '14px'; document.getElementById('promise').style.display = 'none'; }; </script> </body> </html>`

**Headers:**
`"headers":{
"User-Agent":"Instagram 10.9.0 Android (23/6.0.1; 640dpi; 1440x2392; LGE/lge; RS988; h1; h1; en_US)",
"Connection":"keep-alive",
"Accept":"*/*",
"Accept-Encoding":"gzip, deflate, sdch",
"X-IG-Capabilities":"3ToAAA==",
"X-IG-Connection-Type":"WIFI",
"X-IG-Connection-Speed":"2364kbps",
"X-FB-HTTP-Engine":"Liger",
"Content-Type":"application/x-www-form-urlencoded; charset=UTF-8",
"Accept-Language":"en-US"
},`

Any ideas how to solve it?

**Comment by SubodhDahal** [comment]
I was having the same issue yesterday. It was working until some point then I started getting the exception `No response from server. Either a connection or configuration error.` I tried loading instagram.com from the browser but I got `Oops, an error occurred. ` message. Other sections of the site except the homepage could be loaded, if I loaded them from their urls. I also tried accessing that account from the mobile app, but it couldn't display the feeds. Other sections seemed to work fine. The only way to get the feed working again was to reset the password. I haven't tried doing anything with the api since, because I think it's some sort of security implementation by Instagram and I don't want my account to get banned.

**Comment by anonyzm** [comment]
Found out, that it is a problem of huge images, that comes out if u turn off resolution validation =/

**Comment by jpmoney5065** [comment]
@anonyzm can you expand on the conclusions you came to?

**Comment by mgp25** [comment]
@jpmoney5065 the problem is that he is using a modified version of the API which we dont support, he commented out image size validation.

Please this issue tracker is only for the API with no modification

Regards
