### ISSUE TITLE
GetSaveFeed pagination not working.

### ISSUE THREAD

**Issue by zerotolerance** [mgp25/Instagram-API#1210]
Hi,

GetSaveFeed pagination not working.

`$this->instagram->getSavedFeed(""AQCWNN54pKS8bYU4ZryPJ5u4TT54JQICpzRPOvaA4HGapRSyopCKaFaCcvzCUDI5bLn8eNT98GC6DPN1cnsjQ6pU42M4eKbNkkJsrEudS8RRug"");`

The same results always return.

**Comment by zerotolerance** [comment]
Sorry,

The version on it is not up to date.

```
return $this->request('feed/saved/')
        ->addPost('_uuid', $this->uuid)
        ->addPost('_uid', $this->account_id)
        ->addPost('_csrftoken', $this->token)
        ->setSignedPost(true)
        ->getResponse(new Response\SavedFeedResponse());

"mgp25/instagram-php": "^2.0",
```
MaxId not added.

**Comment by SteveJobzniak** [comment]
Hello, yes you need dev-master version for maxId parameter. :-)
