### ISSUE TITLE
Network: cURL error 6: Could not resolve host: i.instagram.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

### ISSUE THREAD

**Issue by shobi888** [mgp25/Instagram-API#1211]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

<?php
set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'/vendor/autoload.php';
/////// CONFIG ///////
$username = 'xxxxx';
$password = 'xxxxx';
$debug = true;
$truncatedDebug = false;
//////////////////////
/////// MEDIA ////////
$photoFilename = '../images/1.png';
$captionText = 'null';
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {

    $ig->setUser($username, $password);
    $ig->login();
} catch (\Exception $e) {
    echo 'Something wrong with login: '.$e->getMessage()."\n";
    exit(0);
}
try {
    $ig->uploadTimelinePhoto($photoFilename, ['caption' => $captionText]);
} catch (\Exception $e) {
    echo 'Something went wrong with photo upload: '.$e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

Network: cURL error 6: Could not resolve host: i.instagram.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below, for example:

GET /api/v1/si/fetch_headers/?guid=123456abcdeff19cc2f123456&challenge_type=signup HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
X-IG-Connection-Type: mobile(UMTS)
X-IG-Capabilities: 3ToAAA==
Accept-Language: en-US
Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; mid=WFI52QABAAGrbKL-ABCDEFGHIJK
User-Agent: Instagram 10.3.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept-Encoding: gzip, deflate, sdch
```

Response:

```
---

### Describe your issue

Whenever I am trying to run example (photo upload ) code I am getting error though I have installed through composer but I am not getting the solution please help me.

Thanks

**Comment by mangledbottles** [comment]
Are you running on localhost or on server?

**Comment by shobi888** [comment]
i am running on live server

**Comment by shobi888** [comment]
@mangledbottles please help me

**Comment by mgp25** [comment]
@shobi888 not API issue, check if your DNS are okay

Search in google:

- http://www.cloudypoint.com/Tutorials/discussion/php-solved-curl-errno6-after-about-a-day-of-work/
- https://stackoverflow.com/questions/1341644/curl-and-https-cannot-resolve-host
- ...

Regards

**Comment by shobi888** [comment]
@mgp25 
Sir I tried everything please help me ...
I am getting the same error
