### ISSUE TITLE
story notification 

### ISSUE THREAD

**Issue by hadikmsh** [mgp25/Instagram-API#1212]
Hi 
i start to use mgp/25 instagram package and util now it works well but i think sth wrong with getUserStoryFeed method.
normally when we see a story in instagram app its send a notification to whom we have seen his story but with  this method no notification have been sent.
when i test getReelsMediaFeed method and getUserReelMediaFeed method i see that they dont work too.
i want to know why this happen and how can i fix that.
thank you.

**Comment by SteveJobzniak** [comment]
That is because the app calls `/v1/media/seen/` endpoint with a list of story media IDs + their taken_at + the time() of when they were seen.

That endpoint is not implemented here.

**Comment by mgp25** [comment]
Will add this feature later tonight

Regards

**Comment by hadikmsh** [comment]
thank you.
i implement a method that  called a post to /v1/media/seen with
_uuid
_uid
_csrftoken
media_id
taken_at
timestamp
parameter 
but it do not work.
can you explain me how i can implement it or what is the parameter name of this call and what type of call should it be?

**Comment by mgp25** [comment]
Just wait for tonight. Ill do it

**Comment by mgp25** [comment]
Added: https://github.com/mgp25/Instagram-API/commit/5650c9b5a1c5fa32fa2973820aa9eae4f6e5e569

@SteveJobzniak check this function, notice the url. It is running under `/v2` like some other endpoints, if you have the time, it would be nice to have a function in the request class, to do something like: `setV2(true)`

Regards

**Comment by SteveJobzniak** [comment]
Hello @hadikmsh the function has been refactored to be even easier to use. Now you can just send in an array of one or more Item objects (easiest way to mark a whole story seen is to send the whole getItems() array from the user's story feed).

Commit: https://github.com/mgp25/Instagram-API/commit/eac134eda64d1f0a505ddfe40be83e373a2abc71

**Comment by riddict** [comment]
Can be something like this implemented too on new messages?

**Comment by hadikmsh** [comment]
Hello @SteveJobzniak @mgp25 
 Thank you so much
