### ISSUE TITLE
getUsernameId Response

### ISSUE THREAD

**Issue by pr0ph0z** [mgp25/Instagram-API#1213]
Hello, i'm trying to use getUsernameId() function, but it return this
`GET: users/pr0ph0z/usernameinfo/ ← 200 519B RESPONSE: {"user": {"pk": 532700051, "username": "pr0ph0z", "full_name": "Radisa", "is_private": false, "profile_pic_url": "http://scontent-sit4-1.cdninstagram.com/t51.2885-19/13827251_1569023386736850_577518702_a.jpg", "profile_pic_id": "1302599483741370668_532700051", "is_verified": false, "has_anonymous_profile_picture": false, "media_count": 39, "geo_media_count": 0, "follower_count": 280, "following_count": 194, "biography": "Welcome to my visual dairy.\nForever a happy soul.\nPecandu oksigen.\nCP: pr0ph0z23@gmail.com , @pr0ph0z", "external_url": "", "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "can_convert_to_business": true, "can_create_sponsor_tags": false, "usertags_count": 26, "usertag_review_enabled": false, "has_chaining": false, "hd_profile_pic_url_info": {"url": "http://scontent-sit4-1.cdninstagram.com/t51.2885-19/13827251_1569023386736850_577518702_a.jpg", "width": 150, "height": 150}, "is_business": false, "show_conversion_edit_entry": true}, "status": "ok"} 532700051`

which i execute with the following code:
`echo json_decode($ig->getUsernameId("pr0ph0z"));`

but when i execute with
`$ig->getUsernameId("pr0ph0z");`

it didn't show the 532700051 in the last.

how can i manage the output? is it possible to just display the 532700051?
and how to remove the `GET: users/pr0ph0z/usernameinfo/ ← 200 519B RESPONSE:` ? thank you.

**Comment by mgp25** [comment]
@pr0ph0z you are already taken the id only. Please look careful to your code, you have debug enabled. And read the wiki and examples

Regards

**Comment by SteveJobzniak** [comment]
@pr0ph0z You need `var_dump()` to look at variables. `json_decode()` is something completely different. This is not about API. This is a basic PHP question. Good luck.
