### ISSUE TITLE
New messages count

### ISSUE THREAD

**Issue by CashCode** [mgp25/Instagram-API#1217]
Hey!
I have few questions for all the time using your api.
1) Is there any option to see unread messages count (like in right top corner in instagram app) and to detect unread thread?
2) I use v2inbox(), but is there any method specially for tick events, which will be calling every few seconds to see new messages count (maybe pending inbox and other things)?
3) How can I get account info (profile_pic / etc) for account which is connected with login()?  
4) login() function is calling with 6 hours max parameter. I want to clarify: it means that the chain of functions from _sendLoginFlow() every 6 hours at least or it means login() must be called every 6 hours of physical time to avoid troubles?
5) why is getTimelineFeed() called every time? It's for immitation client or I can remove it?
6) Is there any limit for query to avoid block. Can I call function every second? Can I make multithread calls or it will block?
Thanks! )

**Comment by mgp25** [comment]
1) not yet
2) not yet
3) `getSelfUserInfo()`
4) Every 6 hours, we send all loginFlow.
5) It is there for some reason, if you delete or remove something of the API is up to you. Do it under your own risk.
6) If there is a limit i woudnt tell. Simply use the API legally

**Comment by SteveJobzniak** [comment]
3. Also `getCurrentUser()` which is like getSelfUserInfo but different endpoint which gives much more (account-personal) details.
4 & 5. The code comments for login() and _sendLoginFlow() fully explains those reasons. Look at the source code in src/Instagram.php. And yes you should call login() at least every 6 hours. And if you do that, I recommend setting the max parameter to 5.5 hours to ensure that the 6th hour will do a full refresh.
6. There is a lot of limiting going on. Try using the phoen app and spam the "get more comemnts" button on a big post. After some time it'll say "failed to get more comments". That's the API limiting. They have a global limit of 5000 queries/hour per account according to their official docs but personally I've never been able to approach anything faster than 1 API query every ~6 seconds or you risk getting throttled. That's just how Instagram works. They expect a human with a finger to be scrolling through an app, thinking, looking at stuff, reading, etc. They do not expect multithreading and super fast shit. ;-)

**Comment by CashCode** [comment]
Thanks for your answers. I use it legal, maybe I will test some limits by myself and show you results later.
I little question, I use getV2inbox() to parse inbox, but it's all the same. Is there any parameter to mark a thread, which has new messages? 
Should I compare timestamps or something?) 
https://i.imgur.com/awLZ9G9.png

**Comment by riddict** [comment]
@CashCode Hi, if you find a way to mark a thread for new reply, please kindly update it here. I also want to know how to do it.
