### ISSUE TITLE
Howto Get getSelfUserFollowers in order Old First

### ISSUE THREAD

**Issue by linadlight** [mgp25/Instagram-API#1218]
Dear all 

I know how to use this API , and i know that i can load getSelfUserFollowers in an array with pagination.
and reverse the array.

But is there a way to ask instagram to return Old followers first , since when you use this api , it show you the latest following users.

If some one have 16K  it will take time and a lot of request will send to instagram

With Respect

**Comment by mgp25** [comment]
@linadlight i dont know if this is possible yet, maybe Instagram will add this feature in the future

Regards

**Comment by SteveJobzniak** [comment]
The app lists the latest followers/followings first, and the same happens on the website. So I think it's impossible to get them in reverse order, sorry.
