### ISSUE TITLE
LikedFeed Max ID is not working anymore

### ISSUE THREAD

**Issue by kurtextrem** [mgp25/Instagram-API#1219]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)

---

### Describe your issue

Currently the liked feed returns a "next_max_id", a long integer. E.g. `150252438510624582`.
However, when doing another request with that int as `max_id` parameter value, the exact same response comes back, with the exact same `next_max_id` (so to say pagination isn't working as the next page is the first page).
Not sure what else could help to work on this issue.

**Comment by SteveJobzniak** [comment]
How many values are you getting before next_max_id repeats itself?

Because Instagram's API (and app) repeats the same response over and over if you try to get more than what their API allows you to get. As you can see here about getUserFollowings: https://github.com/mgp25/Instagram-API/issues/602

Maybe the same problem here. Which is that Instagram delivers the first answers but then just repeats the old answers/old maxId over and over again.

**Comment by kurtextrem** [comment]
The response contains 21 items and even the second request returns the exact same (10-15sec difference between the requests) (I do have more than 21 liked items)

**Comment by SteveJobzniak** [comment]
@kurtextrem Okay I finally had time to test this.

My test code is like this:

```php
try {
    // Starting at "null" means starting at the first page.
    $maxId = null;
    do {
        var_dump($maxId); // Output the ID of the page we're going to request

        // Request the page corresponding to maxId.
        $response = $ig->getLikedMedia($maxId);

        var_dump(count($response->getItems())); // Output how many items we found on this page.

        // Now we must update the maxId variable to the "next page".
        // This will be a null value again when we've reached the last page!
        // And we will stop looping through pages as soon as maxId becomes null.
        $maxId = $response->getNextMaxId();

        sleep(1);
    } while ($maxId !== null); // Must use "!==" for comparison instead of "!=".
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

So it starts at page 1 (maxId = null), then it loops until it finds a null maxId.

My results:

```
NULL
int(21)
string(19) "<censored>"
int(21)
string(19) "<censored again to protect my account>"
int(5)
```

So, 1st page (maxId = null) contained 21 items plus a new non-null maxId. We take that new maxId and request the next page.

The 2nd page contained 21 items plus another new non-null maxId, which was different from the previous page's ID.

The 3rd and final page contained 5 items and a null maxId, showing me that I had reached the final page. And the loop ended.

This test was ran successfully with v2.0 of this library. And with dev-master of this library too (with exactly the same results).

If you're using an older version of the library, just upgrade and it may fix it.

If not, Instagram is silently blocking features on your account. It can happen for various reasons. We cannot help with that.

**Comment by kurtextrem** [comment]
Thank you so much, your answer is helpful. 
I have overlooked your question as I've read your comment in my email account and then replied on the web (my bad) - I do see all of my likes there.

**Comment by SteveJobzniak** [comment]
Okay, you're seeing all of your likes in the app? Then your account may perhaps not be limited.

All you can do now is install 2.0/dev-master of this library, and write a small test script using my code I posted above. Don't use any of your own old code since there may be bugs in your code causing the issue. The code above works and is bug free. Just make a small test script with login, debug off (to not clutter the acreen), and the code.

If it still doesn't work then your account is messed up for some reason.

**Comment by kurtextrem** [comment]
The issue was "simpler" than expected: JavaScript rounded the last 3 numbers when parsing the JSON.

**Comment by SteveJobzniak** [comment]
@kurtextrem omg...

**Comment by SteveJobzniak** [comment]
@kurtextrem Don't come back here. You're getting banned from this repo for wasting our time with Javascript without even telling us you weren't using our library.
