### ISSUE TITLE
This is why we need a checkpoint/email/sms script to be updated

### ISSUE THREAD

**Issue by lonlyman** [mgp25/Instagram-API#1225]
Dear support
Thank you for this wonderful work , upstanding 
As we all know this lib support proxy via the guzzlephp, which is very impressive.

But as all we know , to pass checkpoint we have to log via web or mobile to pass this.

Now as far as the most of us use a proxy (let's be honest), now when we use proxy , we have to make the verification via it.

So i kindly as the other of this Lib , please kindly may you update the    checkpoint script.

I do respect your point of view that you want to limit spammers , which is understandable , but do not update registration but checkpoint is something very important for all users.
We can not judge all users that all of them is SPAMMERS , but we can try our best to sort them out.

Thats why i side don't update registration script. but for the good of all , the check point hase to get a chance .

Thank you and best regards

**Comment by lonlyman** [comment]
@mgp25 , any reply will be appreciated

**Comment by SteveJobzniak** [comment]
@lonlyman I am getting more and more convinced that you are a spammer. Here are your posts about this project:

https://github.com/mgp25/Instagram-API/issues?utf8=✓&q=involves%3Alonlyman

1. You asked about "Unfollow" giving a 404 error for a user. Spammers always follow & unfollow people. Most other people never unfollow. And definitely don't do it via API.

2. You asked how to read "feedback" title, and your own quoted error message was "duplicate comment", like a spammer posting the same message on multiple posts.

3. You asked how to get detailed Guzzle debugging, which is suspicious.

4. You want to use proxies, and proxies are very important to you, which is almost only used by spammers.

5. You want email checkpoint scripts again, just like a spammer would want. Normal users never reach checkpoint.

In short: Fuck off?
