### ISSUE TITLE
Live Broadcast

### ISSUE THREAD

**Issue by dontakethat** [mgp25/Instagram-API#1226]
- [ X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X ] Feature request (request for new functionality)
- [ X] Question
- [ ] Other

https://i.instagram.com/api/v1/live/create/
Gives me instagram rmtp but i can not go live. Please help

**Comment by mgp25** [comment]
Will be done in near future or maybe never.

Regards
