### ISSUE TITLE
How to attach a location to an image upload?

### ISSUE THREAD

**Issue by wonderifficapps** [mgp25/Instagram-API#1227]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
---

### Describe your issue
I'm trying to figure out  how to add a location to a photo upload.  I've looked at the code, but I'm not exactly sure how to fill in the data of the $location object.

                $location = new InstagramAPI\Response\Model\Location;
		$location->name = "Los Angeles, California";
		$location->external_source = "212999109";
			
	   $metadata = array(
              'caption' => $msg,
              'location' => $location,
            );
		
		try {
			$i->uploadTimelinePhoto($tempfiletouse, $metadata);
			}
	   catch (Exception $e) 
			{
			$e->getMessage();
			echo "Error2: ".$e->getMessage().PHP_EOL;
			return false;
			}

**Comment by mgp25** [comment]
In theory, you should take that from `searchFBLocation()` function. Parse the items, take the location you want and do that:

```php
		
   $metadata = array(
          'caption' => $msg,
          'location' => $location,
        );
```
It is explained also in a closed issue

Regards

**Comment by SteveJobzniak** [comment]
@wonderifficapps @mgp25 

Be sure to first try `searchLocation`. As we discovered in another issue, that's the one that the app uses when it lists its proposed locations when uploading a media file with geo coordinates.

Read this discussion:

https://github.com/mgp25/Instagram-API/issues/1185

As for building the location yourself: You CAN do it the way you are doing, by creating an object and setting the properties (there are two ways to set the properties, either call `$location->setExternalSource('x')` or use `$location->external_source = 'x'`). If you do that, you must fill all info exactly like you found it on an official location object an earlier time.
