### ISSUE TITLE
Similar Users

### ISSUE THREAD

**Issue by djstanley** [mgp25/Instagram-API#123]
When you visit somebodies profile and click the arrow to the right of "+ FOLLOW", then click "See All" you get a list of similar users.

I don't have a rooted android so cannot capture the endpoint, but if somebody could capture which endpoints this contacts I will code the addition of the feature.

Cheers.

**Comment by dfanara** [comment]
You don't need a rooted android to sniff the endpoint. You can do it with Fiddler 4, just install the root certificate and tell your phone to use it's proxy and you will be able to capture all traffic between your phone and the internet.

**Comment by djstanley** [comment]
Unless you have this working I think you're mistaken. Instagram uses SSL certificate pinning, you need to use a tool like trust killer (https://github.com/iSECPartners/Android-SSL-TrustKiller) which disables this.

**Comment by dfanara** [comment]
Oh OK, I wasn't aware of pinned SSL certificates, I just assumed that you'd
be able to install the new root certificate on your device and everything
would be good to go. I have this setup working, but I'm also running
Cyanogenmod so it's not really locked down.  I'll see if I can find out
more information for this endpoint later today.

**Comment by djstanley** [comment]
Cool if anyone can post this I'll get coding a pull request...

**Comment by djstanley** [comment]
Anybody?

**Comment by sauceman40** [comment]
Hey, doesn't look like this has been implemented yet - but the web client endpoint (at least when viewing network traffic through the Network tab in Chrome) as of today has the form:

https://www.instagram.com/graphql/query/?query_id=17845312237175864&variables={"id":"user_id_as_string"}
