### ISSUE TITLE
Problem hashtags in caption

### ISSUE THREAD

**Issue by kikemarto** [mgp25/Instagram-API#1230]
Good night, I have a problem,

When uploading an image, when searching for hashtag, the image does not appear in the search list. How do I solve this?

Greetings.

**Comment by ping** [comment]
This is a [known problem](https://github.com/mgp25/Instagram-API/wiki/FAQ#my-photo-doesnt-appear-when-searching-hashtags). Please review the FAQ and other documents as [explicitly instructed](https://github.com/mgp25/Instagram-API/blob/master/.github/ISSUE_TEMPLATE.md#before-submitting-an-issue-make-sure-you-have) in the future.
