### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by mgp25** [mgp25/Instagram-API#1231]
For years I’ve given free support but there are so many questions that it takes up hours of my day every day. So I've decided to begin offering 2 types of subscriptions:

**Free user:**
- Bug reports
- New feature ideas
- Other stuff must be helped by each other/wiki; we'll close question-tickets with generic replies about wiki links, source code reading, and linking to the subscriber feature if you want to have personal help.

**Subscriber (20 eur/m):**
- Personal help with any API question

**Premium subscriber (100 eur/m):**
- Personal help with any API question
- Deep integration
- Latest Instagram keys/signature, which means better compatibility
- Granted the [PREMIUM license](https://github.com/mgp25/Instagram-API/blob/master/LICENSE_PREMIUM) for the duration of the subscription

**Note 1:** API will continue to be updated regardless of subscriptions. Keys will be updated only when they stop working.
**Note 2:** All information can be found in the source code, examples, wiki, FAQ and in already answered issues. Issues will be closed directly pointing to the issue tracker, source code and wiki.
**Note 3:** Collaborators, and contributors with substantial high-quality commits, are considered to be premium subscribers.

**Note 4:  API will continue to be updated regardless of subscriptions and will be free as always**. ALL info can be found in the repository. 

Read all the intro and notes, please.

Regards

**Contact or questions:** me [ @ ] mgp25.com

**Comment by jpmoney5065** [comment]
Donations are cool.

But publicly setting up  a for-profit service is a bad idea. 

You are breaking the law, violating Facebook EULA, and using their IP. Also technically violating github ToS.

Be careful, this could get the whole repo shut down. And watch out for lawsuits!

Good luck!

**Comment by jonatanfroes** [comment]
You're right. A lot of people make money with this API. You need to make too. I'll join the Subscriber plan.

Go ahead!

**Comment by SteveJobzniak** [comment]
Hey everyone!

Mgp and I have spoken spoke about this and I fully support him in this decision. His reverse engineering of the API is the _whole reason_ that all of your fun, personal Instagram projects can be made! In fact, all other Instagram API projects for all other languages come from people copying this project's work! (For example, if there's been a small mistake here, they've all copied that to "their" projects, proving that the others were just copying this repo. 😄 )

The fact is that mgp has worked very hard for years on reversing every new Instagram features and answering people's questions for free, _every day_. All of the work with the project has become like a job to him. And like any job I think he _absolutely_ deserves compensation for his time. The API is still free and open source, but if people want personal help with their questions and extra access as described above, now you've got the option to subscribe to that extra layer of support.

Good luck and have fun everyone! :-)

@jonatanfroes Thanks for subscribing to him. That's awesome! :-)

**Comment by matheuseduardo** [comment]
I totally support @mgp25 and still wanna **contribute more**.
**Awesome** job and fair decision!

**Comment by dsidious1** [comment]
Hello.

Can I ask, "Deep integration" - what is that means? What kind of work?

**Comment by DanielSokil** [comment]
Heck Yeah! @mgp25
Great Idea

**Comment by GarlandM** [comment]
Does the keys include iOS keys?

**Comment by Hugolopez2** [comment]
Hi, I have this error, "Something went wrong: You must have FFprobe to analyze video details." , I can´t upload video, could you help me?

**Comment by robdiberlin** [comment]
Can I ask if it's possible to get instagram app ads access points to boost posts and videos. 
If yes, can this be done with a premium sub?

**Comment by SteveJobzniak** [comment]
@robdiberlin I think, and hope, that you mean about the official Instagram Ads feature that lets businesses advertise their posts in the timeline feeds of people's front page.

If so, it belongs under the Business group:

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Business.php

And none of us have any Instagram Business account so we can't test those features. I'll let @mgp25 answer the rest of your question, though.

**Comment by robdiberlin** [comment]
@SteveJobzniak oh yap, sorry if I am confusing you guys. We have a business account and want to use instagram IN-APP advertising options. So yes, the official Instagram Ads Feature where you can "boost" or "promote" your posted posts. 

Thank you for your response :)

**Comment by mgp25** [comment]
@robdiberlin yes, that is covered in the subscription aswell, since im with exams right now, i wont be able to do it before 14 July. A business account will be required in order to do the tests

**Comment by Skylerz** [comment]
hi @mgp25 i was planning to make a web app with your private api. how i can credit the api to you and your co-creator and can we add a facebook login ?

**Comment by mgp25** [comment]
@Skylerz if you want to discuss what features you want, better via mail

Regards

**Comment by SteveJobzniak** [comment]
@Skylerz @mgp25 The license is GPLv3. The fundamental rule of GPLv3 is that any project which uses GPLv3 code must also release its own source code publicly. We did that to try to prevent all the people making money from this API without contributing any back. Here is a quick guide to GPLv3: http://www.gnu.org/licenses/quick-guide-gplv3.html

**Comment by SteveJobzniak** [comment]
@Skylerz The library is licensed under the RPL-1.5 for general users, and a PREMIUM license for premium subscribers. All information has now been clarified in the Readme:

https://github.com/mgp25/Instagram-API/blob/master/README.md#license

For the record, subscriptions are going solely to mgp25. I am not part of that and I don't want to be part of that. He deserves it for all he has done by open-sourcing this library and working on it over many years, going deep into the app's source code, working super hard reverse engineering _all_ new Instagram features, and endlessly helping people with their tickets every day until he had so many dumb emails and tickets that he could write a book about them (hehe).

During all of his hard work he has constantly had to watch other Instagram libraries rip off his work (he put in some mistakes on purpose and other libraries copied those mistakes from him too), and seeing websites making money off of his work without contributing _anything_ back at all. It has been very tiring and thankless work...

So if he's perhaps one day able to make open source his living then _everyone_ would benefit from that. I know for a fact that people would prefer this library to continue to live on and grow for many years to come.

**Comment by alexok** [comment]
@SteveJobzniak 
I want to add functionality for the business account, with whom can I discuss this?
I already wrote to the post @mgp25

**Comment by mgp25** [comment]
@alexok please resend email, i have lots of mails and sometimes it takes me some time to answer it.

If you want to add any functionality, you can send any PR. We'll review it

Regards

**Comment by alexok** [comment]
@mgp25 I repeated the email

**Comment by prateek-resiliencesoft** [comment]
Have you made any file by which we can increase impression/reach for business profile posted image?

**Comment by bgreeson** [comment]
Appreciate what you are doing. If I can utilize some of this myself, then I will gladly contribute. The big barrier to entry for me is the RE and getting the up to date keys. It sounds like you are helping a lot of folks.

**Comment by shukshin-ivan** [comment]
It's a great project, thanks. How do people supposed to post their ideas? As new issues or as comments to this one? 
Instagram app has an opportunity to post media (with link to Instagram post I beleive) to another social networks like facebook and vkontakte. Is it already done via some hidden parameter or not yet?

**Comment by mgp25** [comment]
@shukshin-ivan it is already implemented. Please stick to the purpose of this issue. If you want to ask or change topic, open a new issue.

**Comment by Mahmoudmrmaterial** [comment]
hi 
i want to use instagram private api in android 
i see your library  and i send request in android as you .
the instagram response is  : 
{
    "message": "Please update your Instagram app to continue following.",
    "status": "fail"
}
i work on it 4 days ....
can you help me  ?

**Comment by teamquatro** [comment]
Hi. Is there any limit requests to the API if I use free version? And where I can see all API responses with response description? Sometimes I'm getting response: InstagramAPI\Response: feedback_required. And I don't know what it's mean.
Thank's so much!

**Comment by robdiberlin** [comment]
Hey Guys, thank you for this library! I love it and use it for insights on my account! 

Did you guys already found out, while reverse engineering, how instagram choose the 1000 accounts in the getMediaLikers() function? As far as I know, Instagram just response ~1000 Accounts, right?
I thought instagram shows the very first 1000 likers. But then I checked that IG shows 1000 likers + likes from accounts I am following! 

...I try to get more insights on my likers and also to block spam accounts.
Maybe you guys know how instagram choose those 1000 likers(accounts).

Thanks a lot,
best 
R

**Comment by SteveJobzniak** [comment]
Please keep this ticket on-topic.

**Comment by mhhg78** [comment]
hi there,
how to get media id whit post's link?

**Comment by LeaVerou** [comment]
How does one subscribe?

**Comment by mgp25** [comment]
@LeaVerou you can contact with me via email. Email can be found in my github profile.

Regards

**Comment by zezeljquantox** [comment]
Is there any way to get posts from home page of logged in user (getting feeds of users which the logged in user is following)?
So far, i successfully got items from user timeline page and explorer page.

**Comment by test24853** [comment]
"Deep integration" what does that stand for?

**Comment by 01010000101001100** [comment]
Hey @mgp25! Will this stop working once Instagram completely deprecate its current API?

**Comment by mohammadraquib** [comment]
Hey @mgp25  If I'll pay for the subscription, can I get the API for sending views on a video?

**Comment by smileytechguy** [comment]
@mgp25 I was wondering if you had any plans of perhaps starting a Patreon page?  It might be easier to drive donations of any amount, and make it easier for users to register for a subscription level.  I've found it works well for I do with a reasonably small fee, so you might want to use it as well.

**Comment by iain-mildner** [comment]
@mgp25 check your paypal. thanks for your help.

**Comment by pascallammers** [comment]
Hey @mgp25 !
I wrote you an email earlier today about the 100euro/month premium subscriber option.
How can we pay this service? 
Thanks in advance :)

**Comment by checho221** [comment]
@mgp25 could you support us on nodejs version? we can pay...

**Comment by burakbuylu** [comment]
Hello,

We want to exceed Challenge required page.. We have many problems.. If we will exceed this problem with you we can buy premium subs. from you.

Thanks in advance ♥

**Comment by sergeykomlev** [comment]
@dakiesse, you found a support?

**Comment by 2xdswu** [comment]
Hey @mgp25 I've sent you an email regarding the purchase of the latest key for the 100E/M but however I didn't get any response as well.

**Comment by gold-dev** [comment]
Hi!
I am interested if the function “sendChallengeCode” could be restored (it existed earlier but was cut out) after getting the subscription. Maybe you have solution how to tackle this issue?  
Looking forward to your reply!

**Comment by mgarmash** [comment]
@mgp25 does Premium license support still available? Sent you an email, waiting for reply.

**Comment by resatugurulu** [comment]
I could also have information about premium license support.

**Comment by JRoy** [comment]
Please refer to #2655 for any future discussion of subscriptions

Thanks
