### ISSUE TITLE
Getting sidecar/carousel media from user feed

### ISSUE THREAD

**Issue by goldworld18** [mgp25/Instagram-API#1234]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ X] Question
- [ ] Other

---

Gteetings,

How can I use the API to tell if a photo is a carousel\sidecar when I query for a specific user feed?
I use this function:" getUserFeed"

I get the the photos, including the **main** carousel one, but there is no indication that this is a carousel photo and the response doesn't have any of its inner photos.

When I use the "getTimelineFeed" functions to get my own timeline, it does have info about carousels.

**Comment by mgp25** [comment]
1. https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/Item.php#L53
2. https://github.com/mgp25/Instagram-API/wiki#managing-responses

Regards

**Comment by SteveJobzniak** [comment]
This is a fair question which we haven't explained anywhere, so I'll answer it so that others can find it in the future.

This is how to find out if a getUserFeed item is an album:

```php
if ($item->getMediaType() == \InstagramAPI\Response\Model\Item::ALBUM) {
    $subItems = $item->getCarouselMedia(); // Contains all the items in that album.
}
```

You see the media type is ALBUM. The items are in getCarouselMedia. And those are of this type:

https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/CarouselMedia.php

Any future questions like this can be solved by looking in the src/Response/Model folder to see what data is available on objects. :)

**Comment by goldworld18** [comment]
This is the problem, I've even manually checked the "media_type" property, and even when the item is an album for sure (I've checked about 5 from different users), it is set to "1" (aka normal photo) and not "8" (album).
For videos it works, it set to "2".

**Comment by mgp25** [comment]
Please, check the item with the following response.

1. https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/Item.php#L53
2. https://github.com/mgp25/Instagram-API/wiki#managing-responses

**Comment by SteveJobzniak** [comment]
>This is the problem, I've even manually checked the "media_type" property, and even when the item is an album for sure (I've checked about 5 from different users), it is set to "1" (aka normal photo) and not "8" (album). For videos it works, it set to "2".

The "media_type = 8 (ALBUM)" value comes from the server reply. The server just gives us a feed of all timeline items. We do not set any object values. Instagram does. So what you think is an album is not an album.

Please show us a timeline which isn't working for you.

**Comment by SteveJobzniak** [comment]
@goldworld18 Okay nevermind. No need for us to check any of your timelines. I was getting concerned when you said the media_types were always wrong, and decided to investigate if Instagram has changed anything.

But good news @mgp25, this guy is just doing something wrong (not sure what). There's no problem with our library. Albums in feeds still work.

I used the instagram account (official feed), which has many albums. And I wrote a small script which loops until it finds an album in their timeline. And indeed it found the 1st available album. Zero problems.

Code:

```php
try {
    $maxId = null;
    do {
        $response = $ig->getUserFeed('25025320', $maxId);

        $items = $response->getItems();
        foreach ($items as $item) {
            if ($item->getMediaType() == \InstagramAPI\Response\Model\Item::ALBUM) {
                $subItems = $item->getCarouselMedia(); // Contains all the items in that album.

                echo "Found album: " . $item->getCode() . PHP_EOL;
                var_dump($subItems);
                exit;
            }
        }

        $maxId = $response->getNextMaxId();
    } while ($maxId !== null);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

Result:

```
Found album: BSCoDz7Du7k
```

http://instagram.com/p/BSCoDz7Du7k

This test was done with "composer require mgp25/instagram-php dev-master".

@goldworld18 So good luck with this issue, it's not a library issue.

**Comment by ganego** [comment]
Found this API project via google but I use Python and wrote parts I needed myself some time ago. Now something does not work and I had a look at this project here.

I have the same problem, that media_type will always be 1 or 2 when I want to get all medias for a single user (what getUserFeed does in your API) and I query api v1 via: `https://i.instagram.com/api/v1/feed/user/USERID/`
This works and I get a list of all medias just fine, but as said, won't give proper media_type. Now saw that you wrote about v2 api but when I use `https://i.instagram.com/api/v2/feed/user/USERID/` I simply get a "Page not found" HTML file back instead of json. I saw that in one of your config files you use this path for the v2 api, so I assume it's correct.
Any ideas why v1 works fine but v2 does not?

**Comment by mgp25** [comment]
@ganego v2 only works with a few endpoints yet, the rest remains in v1. 

Regards

**Comment by ganego** [comment]
I cannot test the php right now, but from what I read above it seems you can get the info if a media is an albums/sidecars for one user via querrying `/feed/user/USERID/`, correct? (Timeline.php function getUserFeed). 
For example if I were to query `britneyspears` aka id `12246775` your API can give me the info that the second media is a sidecar/album, yes (via `media_type` as written above)?
So it either has to use api v2 or how do you do this?
Thank you

**Comment by mgp25** [comment]
@goldworld18 to do that with v1. Parse the response, every item has each own `media_type`.

```php
\InstagramAPI\Response\Model\Item::ALBUM equals to 8 (int)

\InstagramAPI\Response\Model\Item::PHOTO equals to 1 (int)

\InstagramAPI\Response\Model\Item::VIDEO equals to 2 (int)
```

So as you can see in the code, it takes each item and check its type:

```php
        foreach ($items as $item) {
            if ($item->getMediaType() == \InstagramAPI\Response\Model\Item::ALBUM) {
                $subItems = $item->getCarouselMedia(); // Contains all the items in that album.

                echo "Found album: " . $item->getCode() . PHP_EOL;
                var_dump($subItems);
                exit;
            }
        }
```

If the item matches with `\InstagramAPI\Response\Model\Item::ALBUM`, then you can get the info about that.

Regards

**Comment by ganego** [comment]
@goldworld18 
What header do you use? 
I use this useragent to get it to work with v1 `Instagram 10.3.2 (iPhone7,2; iPhone OS 9_3_3; en_US; en-US; scale=2.00; 750x1334) AppleWebKit/420+` (otherwise you get an instant login_required back).

**Comment by goldworld18** [comment]
@ganego 
I can't check for it for the next several days because I don't have access, but I can tell you that I copied the whole header from the one in this project. Also, you must use api v1 for this request.

**Comment by ganego** [comment]
Oh I just found out, you just have to pass ?version=2 to the `https://i.instagram.com/api/v1/`. But thank you for the tip I would not have thought of this (querying v1/ with a parameter version=2).
