### ISSUE TITLE
send comment without login

### ISSUE THREAD

**Issue by mR-Rian** [mgp25/Instagram-API#1236]
hi  , thank's for sharing i want to send comment without login 

       ->addPost('user_breadcrumb', Utils::generateUserBreadcrumb(mb_strlen($commentText)))
        ->addPost('idempotence_token', Signatures::generateUUID(true))
        ->addPost('_uuid', $this->uuid)
        ->addPost('_uid', $this->account_id)
        ->addPost('_csrftoken', $this->token)
        ->addPost('comment_text', $commentText)
        ->addPost('containermodule', 'comments_feed_timeline')
        ->addPost('radio_type', 'wifi-none')

i dont have username and password BUT
i have _csrftoken and _uid 
is that enough ? or another thing is necessary ?

**Comment by mgp25** [comment]
Invalid issue format.

Login must be done always, if session exists activity flow is sent, otherwise login flow is sent.

Please, read wiki and example code. Seen debug log may help you.
