### ISSUE TITLE
naming issue when fetching is_ properties from response object

### ISSUE THREAD

**Issue by juicytuna** [mgp25/Instagram-API#1238]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ 1] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ 1] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [1 ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ 1] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [1 ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->setUser('yourusername', 'yourpassword');
    $ig->login();
    $result = $ig->comment('14123451234567890_1234567890', "Hello World");
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

RESPONSE: {"status": "fail", "message": "Sorry, the comment data may have been corrupted."}

InstagramAPI\Response\CommentResponse: Sorry, the comment data may have been corrupted.
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below, for example:

GET /api/v1/si/fetch_headers/?guid=123456abcdeff19cc2f123456&challenge_type=signup HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
X-IG-Connection-Type: mobile(UMTS)
X-IG-Capabilities: 3ToAAA==
Accept-Language: en-US
Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; mid=WFI52QABAAGrbKL-ABCDEFGHIJK
User-Agent: Instagram 10.3.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept-Encoding: gzip, deflate, sdch
```

Response:

```http
# Please provide your capture below, for example:

HTTP/1.1 200 OK
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Thu, 15 Dec 2016 08:50:19 GMT
Content-Type: application/json
Set-Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; expires=Thu, 14-Dec-2017 08:50:19 GMT; Max-Age=31449600; Path=/; secure
Connection: keep-alive
Content-Length: 16

{"status": "ok"}
```
---

### Describe your issue

When fetching is_ properties from a response object we have to call it like so:

"is_verified" => $user->isIsVerified();

In pre 2.0 versions we called it like this:

"is_verified" => $user->isVerified();

This looks cleaner and makes more sense. Just a minor thing but I thought you might want to check it out. Thanks.

**Comment by mgp25** [comment]
@juicytuna you can use `getIsVerified()` like other properties. ill check it

Regards

**Comment by SteveJobzniak** [comment]
@juicytuna Sorry but this was one of many big bugs in 1.x. Which has now been fixed.

You _think_ you want to call `isVerified()`, but that's not right. There is _no_ property called `verified`. The property is called `is_verified`.

The format of access functions is: `get<property>`, `set<property>` and `is<property>`.

In 1.x, the "is" function was totally broken.

1. It returned the actual value instead of a true/false ("is").
2. It didn't work.

Here's a demonstration of why it does not work:

**Save this file as AutoResponseFunctionSetter.php, it comes from 1.x:**

```php
<?php

namespace InstagramAPI;

class AutoResponseFunctionSetter
{
    public function __call($function, $args)
    {
        $underScoreNames = $this->camelCaseToUnderScore($function);
        if (strpos($underScoreNames, '_') === false) {
            return false;
        }
        list($functionType, $propName) = explode('_', $underScoreNames, 2);
        echo "underscorenames: ".$underScoreNames.PHP_EOL;
        echo "func: ".$functionType.PHP_EOL;
        echo "prop: ".$propName.PHP_EOL;

        switch ($functionType) {
            case 'get':
                if (!property_exists($this, $propName)) {
                    throw new \Exception("Wrong function $function");
                }

                return $this->$propName;
                break;
            case 'set':
                if (!property_exists($this, $propName)) {
                    throw new \Exception("Wrong function $function");
                }
                $this->$propName = $args[0];
                break;
            case 'is':
                if (!property_exists($this, $underScoreNames)) {
                    throw new \Exception("Wrong function $function");
                }

                return $this->$underScoreNames;
                break;
        }
    }

    public function camelCaseToUnderScore($input)
    {
        preg_match_all('!([A-Z][A-Z0-9]*(?=$|[A-Z][a-z0-9])|[A-Za-z][a-z0-9]+)!', $input, $matches);
        $ret = $matches[0];
        foreach ($ret as &$match) {
            $match = $match == strtoupper($match) ? strtolower($match) : lcfirst($match);
        }

        return implode('_', $ret);
    }
}
```

**Save this file as test.php:**

```php
<?php

require 'AutoResponseFunctionSetter.php';

class Foo extends \InstagramAPI\AutoResponseFunctionSetter
{
    public $is_verified = 'xxx';
    public $foo = 'bar';
}

$x = new Foo();

var_dump($x);
var_dump($x->isVerified());
var_dump($x->isFoo());
```

Result:

```
// result of var_dump($x):
object(Foo)#1 (2) {
  ["is_verified"]=>
  string(3) "xxx"
  ["foo"]=>
  string(3) "bar"
}

// result of var_dump($x->isVerified()):
underscorenames: is_verified
func: is
prop: verified
string(3) "xxx"

// result of var_dump($x->isFoo()):
underscorenames: is_foo
func: is
prop: foo
PHP Fatal error:  Uncaught Exception: Wrong function isFoo in AutoResponseFunctionSetter.php:34
```

See? Broken as hell.

It has been fixed, so that all functions behave correctly: `get<property>`, `set<property>` and `is<property>`. Your property is called "is_verified", so the correct way to get it is: `getIsVerified()` and `isIsVerified()`.

**Comment by SteveJobzniak** [comment]
And before you say "Well, if the user types `isVerified()`, how about checking if a property `is_verified` exists and returning that?". Well then I say: What do you do with an object with properties `verified` AND `is_verified` on it? Which ones does `isVerified()` want then?

The answer is that we must be explicit about what exact property we want: `is<propertyname`. In your case: `isIsVerified()`.

Sorry.

**Comment by juicytuna** [comment]
Fair enough. That did lead to some confusion when I was using 1.x tbh. 
Going forward I'll just use 'get' now that I know it works for all properties, Nice and simple.

Thanks for taking your time to respond.

**Comment by SteveJobzniak** [comment]
@juicytuna Yeah, you can definitely use `getIsVerified()` to get the actual value of any property, even "is"-properties.

Here's the difference:

- The `is<property>` prefix in 2.x doesn't return the property value. It returns either TRUE or FALSE, depending on whether the property's value evaluates to something true or something false.
- The `get<property>` prefix returns the actual value.
- So if the value is actually NULL, then `isIsVerified()` would return FALSE, and `getIsVerified()` would return NULL.

As long as you're aware of that, you can use either method.

And it's fine to use the getter as long as you use a "truthy" comparison, such as `if ($foo->getIsVerified())`.

**Comment by juicytuna** [comment]
Understood. Back to using isIsVerified() as I'm not sure if I was checking for false or !false throughout my scripts.
