### ISSUE TITLE
Composer Update

### ISSUE THREAD

**Issue by LanchaBasualdo** [mgp25/Instagram-API#1239]
Guys, I do hope and believe this is a "api issue", after `composer update` a million times, removing and re-requiring the api, I continue to get a late version of it:

I have confirmed this:
In the master's Instagram-API/src/Response/Model/User.php file
where as the file here on github has 
`    public $profile_context_mutual_follow_ids; // getUserInfoById prop`
`   /**
     * @var Link[]
     */
`
from line 69 to 72
I have` @var string[]`
and asking with a valid id in string form for `getUserFollowings($userId)`
I continue to get : `Class 'string' not found in...`

I hope this is an issue, cause I don't wanna bother your.
Regards

**Comment by mgp25** [comment]
@LanchaBasualdo are you using latest code from master branch?

`composer require mgp25/instagram-php dev-master`

**Comment by LanchaBasualdo** [comment]
No, I thought that was a development brach. 
Sorry guys

**Comment by mgp25** [comment]
@LanchaBasualdo try it, and let me know if everything okay

**Comment by LanchaBasualdo** [comment]
It is, no problems by far
