### ISSUE TITLE
Delete thread implementation

### ISSUE THREAD

**Issue by CashCode** [mgp25/Instagram-API#1240]
Hello!
Could you make implementation of dialog deleting?
Btw, when you read messages from dialog it doesn't mark as 'seen'. Is there any way to mark them?
Regards

**Comment by mgp25** [comment]
@CashCode Yes, ill add that eventually, send me image captures (to my email) so i can try myself and get the requests. No ETA.

Regards

**Comment by OwlGreenApple** [comment]
@mgp25 @CashCode hi hows this delete & mark as seen works ?

**Comment by SteveJobzniak** [comment]
@OwlGreenApple It's coming via https://github.com/mgp25/Instagram-API/pull/1259

But do NOT comment there asking us to speed up. It's discussion for developers only.
