### ISSUE TITLE
"there was a problem with your request" issue

### ISSUE THREAD

**Issue by passion1989** [mgp25/Instagram-API#1243]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

/////// CONFIG ///////
$username = ''; // I entered my Instagram username
$password = '';  // I entered my Instagram password
$debug = true;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->setUser($username, $password);
    $ig->login();
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

// Please provide your error log/dump here, for example:
Response:
# Please provide your capture below, for example:
{"message": "Sorry, there was a problem with your request.", "status": "fail", "error_type": "sentry_block"}

---

### Describe your issue
I downloaded and installed stable version 2.0 to my own server. and tried to run examples/accessingValues.php for checking Instagram login.
But it gives above issue. "sentry_block" 

There was no changes on the file except of putting my username and password.

Do I need to pull the latest code on main branch?
or what do I need to do?
I can't use your repository's code. Please help me.

Regards

**Comment by mgp25** [comment]
Read FAQ

**Comment by passion1989** [comment]
What does sentry_block error mean?

This is the response for detected spam/bot behavior. Stop using the api in whatever way that triggered this reponse.

without login API call, how can I use your code base?
Please let me know the solution

**Comment by SteveJobzniak** [comment]
Your server is probably part of a IP network that has had spammers on it. Instagram has blacklisted its network/IP.
