### ISSUE TITLE
Metadata storyphoto.

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1245]
The code

`$metadata` = ['caption' => 'My awesome caption'];

$ig->uploadStoryPhoto($photoFile, $metadata);`

Is no longer working. The upload works, but the metadata caption is not showing up.

**Comment by SteveJobzniak** [comment]
Hi Matthijs.

We have no examples telling anyone to use the "caption" metadata choice in `uploadStoryPhoto()`. In fact we have no examples of using `uploadStoryPhoto()` at all.

But perhaps you saw that the `uploadStoryPhoto()` function has a comment which says where to look for the list of supported metadata fields.

And I just noticed that we accidentally didn't mention that caption isn't used for stories. I've fixed the code comment now.

Stories don't have captions. The text you see on top of images in the app are burned in by the app before uploading to Instagram. To do the same, you would need to use an image editor to add text before uploading your story image.
