### ISSUE TITLE
Json Mapper error

### ISSUE THREAD

**Issue by aryanbaghi** [mgp25/Instagram-API#1246]
I have got this error on some posts:

```PHP Fatal error:  Uncaught Error: Class 'string' not found in /opt/instagram/instagram-crawler/vendor/netresearch/jsonmapper/src/JsonMapper.php:544
Stack trace:
#0 /opt/instagram/instagram-crawler/vendor/netresearch/jsonmapper/src/JsonMapper.php(376): JsonMapper->createInstance('string')
#1 /opt/instagram/instagram-crawler/vendor/netresearch/jsonmapper/src/JsonMapper.php(265): JsonMapper->mapArray(Array, Array, 'string')
#2 /opt/instagram/instagram-crawler/vendor/netresearch/jsonmapper/src/JsonMapper.php(280): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\Model\User))
#3 /opt/instagram/instagram-crawler/vendor/mgp25/instagram-php/src/Client.php(433): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\UserInfoResponse))
#4 /opt/instagram/instagram-crawler/vendor/mgp25/instagram-php/src/Request.php(105): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\UserInfoResponse), Object(stdClass), true, NULL)
#5 /opt/instagram/instagram-crawler/vendor/mgp25/instagram-php/src/Instagram in /opt/instagram/instagram-crawler/vendor/netresearch/jsonmapper/src/JsonMapper.php on line 544```

**Comment by mgp25** [comment]
@aryanbaghi provide steps to reproduce this issue. (code, ...)

**Comment by aryanbaghi** [comment]
@mgp25 Code example:
``` 
$feed = $this->instagram->getUserFeed(1478920737, $maxid);
foreach($feed->getItems() as $key => $post) {
}
```
by the way I am using latest code.

**Comment by SteveJobzniak** [comment]
@aryanbaghi I already see the error. From your stack trace:

**0 /opt/instagram/instagram-crawler/vendor/netresearch/jsonmapper/src/JsonMapper.php(376): JsonMapper->createInstance('string')**
**3 /opt/instagram/instagram-crawler/vendor/mgp25/instagram-php/src/Client.php(433): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\UserInfoResponse))**

You are using a function to get user info, and you are not using dev-master. You are using 2.0.

To fix, do this: `composer require mgp25/instagram-api dev-master`

We will release 2.1 sometime after we're done with some other implementations. For now you must run dev-master to fix this issue.

**Comment by SteveJobzniak** [comment]
Here are the other closed tickets about this:

https://github.com/mgp25/Instagram-API/issues/1179

https://github.com/mgp25/Instagram-API/issues/1141
