### ISSUE TITLE
Endpoint /address_book/link/ has been deprecated

### ISSUE THREAD

**Issue by idb-** [mgp25/Instagram-API#1247]
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---

Response:

```http
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Content-Language: en
Date: Mon, 15 May 2017 09:50:06 GMT
Set-Cookie: <redacted>
Set-Cookie: <redacted>
Set-Cookie: <redacted>
Connection: keep-alive
Content-Length: 90

{"users": [], "warning": "This endpont is deprecated, please use find_v2", "status": "ok"}```
---

Requests made to this endpoint yield no users and return a warning.

**Comment by mgp25** [comment]
@idb- im going to check it, test it, and when done ill send the changes

Thanks for reporting this.

Regards

**Comment by Alex-Bogdanov** [comment]
Sorry for re-issuing, but does this API method `public function linkAddressBook($contacts)` available in the project or still hasn't yet reversed from IG mobile app, i.e can I link my contacts list using your project?
Thanks

**Comment by Mineroboter** [comment]
Is this function going to be updated or what is the current status about this issue, since I can't link my address book and I'm getting the same warning.

**Comment by cafemafia** [comment]
I have the same problem and cannot find method for find_v2.

**Comment by JRoy** [comment]
This function is being updated for the next version

**Comment by cafemafia** [comment]
So what's the url of find_v2 api ?
I didn't find it.

**Comment by JRoy** [comment]
The app still uses the same request, they just gzip its contents.

See #2569

**Comment by cafemafia** [comment]
> 
> 
> The app still uses the same request, they just gzip its contents.
> 
> See #2569

Tried using gzip but still getting:
{"users":[],"warning":"This endpont is deprecated, please use find_v2","status":"ok"}

**Comment by JRoy** [comment]
Well the app still uses it, when the app changes, so will we
