### ISSUE TITLE
Can't send message using direct_share

### ISSUE THREAD

**Issue by tyran53red** [mgp25/Instagram-API#1248]
I got this message when try to send post using direct_share

> Response text

`HTTP/1.1 400 Bad Request
Content-Type: application/json
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Content-Language: en
Date: Mon, 15 May 2017 13:06:42 GMT
Set-Cookie: rur=PRN; Path=/
Set-Cookie: csrftoken=; expires=Mon, 14-May-2018 13:06:42 GMT; Max-Age=31449600; Path=/; Secure
Connection: keep-alive
Content-Length: 54
{"message": "Thread does not exist", "status": "fail"}
`
I got it when debugging your library. By default, it doesn't show this problem. It just continues work, but don't send the message. But method direct_message works fine. So can you please help me with this problem?
P.S. All worked fine last week, but stopped on Thursday.

**Comment by mgp25** [comment]
@tyran53red if you dont provide debug log (requests + responses) + code this issue will be considered as invalid. Please provide the information described above.

**Comment by tyran53red** [comment]
This is my example. Set your credentials and path. After just run the example. You will see that direct_message works but not direct_share
[directMessageAndShare.php.zip](https://github.com/mgp25/Instagram-API/files/1001275/directMessageAndShare.php.zip)

**Comment by mgp25** [comment]
Invalid + old code + not updated + havent read wiki.

Regards
