### ISSUE TITLE
No view count in getUserStoryFeed

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1249]
When I make a request for the users story:

```php
$ig = new \InstagramAPI\Instagram();
$ig->setUser($this->session->userdata('ig_u'), $this->session->userdata('ig_p'));
$ig->login();

$userId = $ig->getUsernameId('snapboardnl');
$user = $ig->getUserInfoById($userId);
$ig->getUserStoryFeed($userId)
```

The view_count in the response gives NULL while the app shows there are views. Can this be fixed?

**Comment by SteveJobzniak** [comment]
1. Many people assume we are the ones building the objects/their values. We are not. It all comes from the Instagram server. `NULL` in a field means the Instagram server did not send any value for that field.
2. Most objects we have are re-used for lots of different responses, most server responses do not fill every field.

So I can tell you with certainty that getUserStoryFeed has no view_count value via their server. I don't know how the app does it.

**Comment by matthijsotterloo** [comment]
Okay clear. Maybe someone else knows how to get this view count?

**Comment by SteveJobzniak** [comment]
@matthijsotterloo You can try running with $debug=true, to see what the JSON reply from the server contains. Then see if the view count is contained in some other field.

I do get a bit concerned about your usage, by the way: `$ig->setUser($this->session->userdata('ig_u'), $this->session->userdata('ig_p'));`... Looks like you're asking people to login with their username and password on your own website. That's password-phishing, very illegal.

**Comment by matthijsotterloo** [comment]
I'm using this API to build some kind of dashboard for a customer. 
It's not for big usage ;)

**Comment by SteveJobzniak** [comment]
Okay good, that's fine. ;)

**Comment by SteveJobzniak** [comment]
Excellent work matthijs. For future reference it was fixed by this pull request:

https://github.com/mgp25/Instagram-API/pull/1251
