### ISSUE TITLE
Trying To Login

### ISSUE THREAD

**Issue by rizkihape** [mgp25/Instagram-API#125]
Hello, 
I'm trying to login with html
but it's not redirect when users login
how its work ?

`<form method="POST">
 	<input type="username" name="username" />
 	<input type="password" name="password" />
 	<input type="submit" name="submit" value="Login">
 </form>`

and PHP FIles is

`require 'src/Instagram.php';
$username = $_SESSION['username'];
$password = $_SESSION['password'];
$debug = false;
$i = new Instagram($username,$password,$debug);
try {
	$login= $i->login();
} catch (InstagramException $e) {
	$e->getMessage();
	exit();
}
if ($login) {
	echo "<script>window.location='user.php'</script>";
}`

**Comment by dfanara** [comment]
$password = $_POST['password']
$username = $_POST['username']

You never fetch the username or password from the post data. It's an issue with the implementation, not the library itself.

**Comment by rizkihape** [comment]
i'm trying with $_POST, its seems.

**Comment by mgp25** [comment]
Not API issue, use google
