### ISSUE TITLE
Can't send message using direct_share V2.0

### ISSUE THREAD

**Issue by tyran53red** [mgp25/Instagram-API#1250]
> I updated code to version V2.0. But the message is same.

[directMessageAndShare-2.php.zip](https://github.com/mgp25/Instagram-API/files/1001820/directMessageAndShare-2.php.zip)

I checked direct_message and direct_photo. This two methods works without any problem. But for me is very important to use direct_share. Can somebody help me? I spent for this problem a lot of time and I just don't know what can be wrong. Thanks!

**Comment by SteveJobzniak** [comment]
For reference your old ticket was https://github.com/mgp25/Instagram-API/issues/1248

Thanks for updating to 2.0 and trying that.

Unfortunately, the direct sharing functions are not stable. They were always just half-finished and they are now being replaced with Realtime client.

Your error message says you are not providing a thread ID to direct sharing. Sorry we can't and won't help with that. If you subscribe to support service (https://github.com/mgp25/Instagram-API/issues/1231) we can help more.

**Comment by tyran53red** [comment]
What type of subscription I need to solve this problem?

**Comment by SteveJobzniak** [comment]
Hi. For extra help like this it would be:

Subscriber (20 eur/m):
- Any API question

For that we will investigate and spend time trying to solve it, and hopefully find an answer. But we can't guarantee that it's solvable right now.

**Comment by tyran53red** [comment]
Maybe I could donate little bit more money for faster solve of my issue and the guaranteed result?

**Comment by mgp25** [comment]
No
