### ISSUE TITLE
Something went wrong: InstagramAPI\Response\ConfigureResponse: Uploaded image isn't in the right format.

### ISSUE THREAD

**Issue by ebenk26** [mgp25/Instagram-API#1253]
Hi,
i already follow ur guide also from wiki
but message like above always appear

here is my code : 

> $photoFilename = 'C:/xampp/htdocs/myproject/assets/img/legal.jpg';
> $captionText = 'Captions';
> 
> $ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
> 
> try {
> 	$ig->setUser($username, $password);
> 	$ig->login();
> } catch (\Exception $e) {
> 	echo 'Something went wrong: '.$e->getMessage()."\n";
> 	exit(0);
> }
> 
> try {
> 	$ig->uploadTimelinePhoto($photoFilename, ['caption' => $captionText]);
> } catch (\Exception $e) {
> 	echo 'Something went wrong: '.$e->getMessage()."\n";
> }

i also try C:\xampp\htdocs\myproject\assets\img\legal.jpg and linked my photo on my web and use http://myproject.com/assets/img/legal.jpg but its appear same message

here the respons:

> RESPONSE: {"upload_id": "1495002194157", "status": "ok"} POST: media/configure/ DATA: ig_sig_key_version=4&signed_body=38c74b296e9607461e021858ab7fe2364bdd25f0fc8393f62b6ecdabc483b6d4.{"_csrftoken":"BHcdci1xyvLCYDRKJnF0lhOynlEaX9bc","_uid":"4203648947","_uuid":"0fe66ece-b1a2-4630-8d48-949bb378c0ff","edits":{"crop_original_size":[101,101],"crop_zoom":1,"crop_center":[0,0]},"device":{"manufacturer":"samsung","model":"SM-G930F","android_version":"23","android_release":"6.0.1"},"extra":{"source_width":101,"source_height":101},"caption":"Captions","source_type":4,"media_folder":"Camera","upload_id":"1495002194157"} ← 400 73B RESPONSE: {"message": "Uploaded image isn't in the right format", "status": "fail"}

 can u help me what i missing?

**Comment by mgp25** [comment]
@ebenk26 the same exact issue has already been answered, check issue tracker. And please read the response, it takes you 5 seconds

Regards
