### ISSUE TITLE
Sentry block, again

### ISSUE THREAD

**Issue by estgold** [mgp25/Instagram-API#1255]
Hello, i use this project for some actions in the instagram, but last week when i login a get this error from instagram.
I'm trying to change ip via proxy, wait time, finding another IG_SIG_KEY's and nothing help me. I was blocked may be i think, but if i use a web-client or android app i don't have a any kind of problems.

**Comment by yazhog** [comment]
Same issue. 
I can send you login/password one off accounts with same problem.

**Comment by SteveJobzniak** [comment]
Read closed tickets about this.
