### ISSUE TITLE
Backup method crashes if user has "gallery"

### ISSUE THREAD

**Issue by riartem** [mgp25/Instagram-API#1256]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
// In user's feed need at least one media with type "gallery" (multiple images)
$ig->backup('backup');
```

Error Log:

```php
Fatal error: Uncaught Error: Call to a member function getUrl() on null in 
vendor/mgp25/instagram-php/src/Instagram.php:3527
```

---

### Describe your issue

Backup method crashes when trying to backup user with at least one media with type "gallery" (multiple images).

**Comment by SteveJobzniak** [comment]
@riartem Thanks for discovering this problem. I'll add support for backing up albums now.

**Comment by SteveJobzniak** [comment]
@riartem Hello, I finished the backup() rewrite and added some more features that will make you happy. :) Read changes in: https://github.com/mgp25/Instagram-API/commit/1c91df00c6282f5badacfa1ca2377a7b9ea47ddd

**Comment by SteveJobzniak** [comment]
@riartem Be sure to do this to get local time in the filenames when backing up:

```php
date_default_timezone_set('Europe/Kiev'); // your local timezone
$ig->backup('backup/');
```

**Comment by riartem** [comment]
@SteveJobzniak Thank you so much! I already checked the commit and I'm happy :) Will test soon

**Comment by SteveJobzniak** [comment]
@riartem Sweet, let me know how it goes :)

**Comment by riartem** [comment]
@SteveJobzniak Tested. Now works fine with albums. Dates and times sets too (including "modified" property). 
Good job!

**Comment by SteveJobzniak** [comment]
@riartem Great, thanks for reporting this :) Take care!
