### ISSUE TITLE
Problem with permisssion

### ISSUE THREAD

**Issue by roysG** [mgp25/Instagram-API#1257]
First of all, thank you for you awesome plugin,
I get errors of permission, i also tried allow the permision by commands:

chown -R ubnutu:ubuntu vendor
chown -R ubnutu:ubuntu vendor g+rw /path/to/webserver/www

Warning: mkdir(): Permission denied in /var/www/html/vendor/mgp25/instagram-php/src/Settings/Storage/File.php on line 379

Warning: chmod(): No such file or directory in /var/www/html/vendor/mgp25/instagram-php/src/Settings/Storage/File.php on line 380

Fatal error: Uncaught InstagramAPI\Exception\SettingsException: The "/var/www/html/vendor/mgp25/instagram-php/src/../sessions/" folder is not writable. in /var/www/html/vendor/mgp25/instagram-php/src/Settings/Storage/File.php:383 Stack trace: #0 /var/www/html/vendor/mgp25/instagram-php/src/Settings/Storage/File.php(50): InstagramAPI\Settings\Storage\File->_createFolder('/var/www/html/v...') #1 /var/www/html/vendor/mgp25/instagram-php/src/Settings/StorageHandler.php(70): InstagramAPI\Settings\Storage\File->openLocation(Array) #2 /var/www/html/vendor/mgp25/instagram-php/src/Settings/Factory.php(154): InstagramAPI\Settings\StorageHandler->__construct(Object(InstagramAPI\Settings\Storage\File), Array) #3 /var/www/html/vendor/mgp25/instagram-php/src/Instagram.php(147): InstagramAPI\Settings\Factory::createHandler(Array) #4 /var/www/html/info.php(10): InstagramAPI\Instagram->__construct() #5 {main} thrown in /var/www/html/vendor/mgp25/instagram-php/src/Settings/Storage/File.php on line 383

What do i miss?

**Comment by roysG** [comment]
I just added permission 777 and it worked

**Comment by samdoidge** [comment]
Also happening for me. Permission 777 causes a problem when running composer install later on - I think we should re-open this issue.

**Comment by brkrtp** [comment]
same +1

**Comment by SteveJobzniak** [comment]
Answer: Think and read this. Do not open any tickets about it.

https://stackoverflow.com/questions/5165183/apache-permissions-php-file-create-mkdir-fail
