### ISSUE TITLE
Instagram removes the posts

### ISSUE THREAD

**Issue by onlymaj** [mgp25/Instagram-API#126]
Hey , I'm using this API and it works good . But after some mins Instagram remove my posts automatically. Is there any configuration needed to solve this problem . tnx

**Comment by verseal** [comment]
@onlymaj don't use hashtags

**Comment by mgp25** [comment]
That happens when Instagram flags your account because of using the API in a bad way or spamming.
Instagram can also flag by IP, meaning all the accounts created under the same IP will be flagged too.

It works perfectly i just tried it

Regards

**Comment by onlymaj** [comment]
@mgp25 What do you mean by "using the API in a bad way" ? i just set the user/pass and a caption. is that the problem ? also i used your default IG_SIG_KEY for my script . Do i need to populate my device signature and use it ?
