### ISSUE TITLE
[dev] Composer repositories for sublibraries

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1263]
It turns out that composer ignores `"repositories"` of sublibraries. Whenever someone installs this composer library, it becomes a sublibrary of their own project and our "repositories" list is ignored.

So `composer require mgp25/instagram-php dev-master` now leads to "requires ratchet/pawl dev-ping-pull -> no matching package found."

I guess composer does this to protect against people maliciously replacing famous packagist libraries with their own hacked versions. Or perhaps because they only have one "vendor" folder and Composer can't distinguish between multiple versions (official release vs a sublibrary's fork, etc), so it ignores sublibrary forks.

Seems the only solutions are either A) the original repos must merge the pull requests, or B) before requiring our dev-master of this library, people must first edit their composer.json manually and add our "repositories" chunk to it (which should work in theory, but I just tested and can't get that to work either, actually):

```json
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/valga/php-http-proxy-react"
        },
        {
            "type": "git",
            "url": "https://github.com/valga/Pawl"
        }
    ]
```

I know that the goal is to remove the repo forks when the pulls are merged but the authors of those repos have been very slow at merging, unfortunately.

Anyway, since @valga owns the forks, I'll assign you. Any ideas?

**Comment by SteveJobzniak** [comment]
I just found that Composer themselves documents this problem:

https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

**Comment by valga** [comment]
Well, I did not know that. Sorry for breaking this repo.

See #1265.

**Comment by SteveJobzniak** [comment]
@valga Hehe, absolutely no problem, none of us could have known that composer doesn't load repositories of sublibraries. :) It's not a very common scenario and (probably like you) I've only used repos in my projects never in libraries, so I never saw this limitation of composer before.

I like your solution of copying the necessary edited .php files to our repo so that we have them until they're officially merged. Very good idea! Has been merged now.

Thanks for rescuing `dev-master` so quickly, before people noticed that they couldn't clone the repo. ^_^ And thanks again for the amazing work!

Btw, I get notifications even for closed tickets/pulls, so if there's anything we need to discuss you can just easily message via the original pull or any of the tickets related to it. :)

**Comment by SteveJobzniak** [comment]
@valga Hi, fyi this is the commit that needs to be reverted when they've merged the pull requests upstream:

https://github.com/mgp25/Instagram-API/commit/ae376f0a31c7d2d2e6336c4241102271e1672235
