### ISSUE TITLE
Login using API

### ISSUE THREAD

**Issue by shadowgroundz** [mgp25/Instagram-API#1268]
Hello, i have some question. Can I use login API from "Instagram" to login into this API?

**Comment by mgp25** [comment]
Wiki: https://github.com/mgp25/Instagram-API/wiki

**Comment by shadowgroundz** [comment]
Sorry bro, I mean using official Instagram API to login this API

**Comment by mgp25** [comment]
No. In the wiki it is explained which kind of login we do.

Regards
