### ISSUE TITLE
Extracting key with gikdb.art

### ISSUE THREAD

**Issue by dubmartin** [mgp25/Instagram-API#127]
I know this isn't to do with your project, but is kind of related so thought maybe someone might have some ideas. If this doesn't belong, accept my apologies and delete as you see fit.

So, am trying to extract the key in instagram 7.0.20 (latest release came out a few days ago) on a nexus5 using gidb.art.

All seems to go well and after selecting the device and viewing the list of processes to attach to, my list does not appear to have any apps (com.XXX.android for example) listed. 

It is as if it is a cropped list. If I start to use an app and refresh the list of processes, occasionally I can get lucky and view the app com.XXX.android in the list of processes.

Beginning to pull my hair out at this, anyone got any ideas as to what is going on? Perhaps how to increase the size of the list of processes to show all?

cheers

**Comment by mgp25** [comment]
Hi, not API issue.

Regards
