### ISSUE TITLE
Can't send only direct photo using directPhoto()

### ISSUE THREAD

**Issue by f0rtis** [mgp25/Instagram-API#1271]
Hi. I'm trying send only photo without text using method directPhoto($recipients, $photoFilename, $text = null), as text isn't required:

```
$imgPath = $this->saveImageForSending($base64img);
  if (!$imgPath) { // can't create an image for some reasons.
    return false;
  }
$result = $api->directPhoto($to->service_id, $imgPath);
```

But in debug i'm receiving:

> POST:  direct_v2/threads/broadcast/upload_photo/
> → 61.37kB
> ← 500 	 25B
> RESPONSE: Oops, an error occurred.

File is exists, and data from file collected successfully.

**Comment by mgp25** [comment]
@f0rtis dont recommend you to use these functions yet. We are updating them. You can follow the work here: https://github.com/mgp25/Instagram-API/pull/1259

Regards
