### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by DanielSokil** [mgp25/Instagram-API#1275]
Could someone show an example of getSelfUserFollowers, I went along the paginationExample.php. Still couldn't get anything out of it. 
What I have Tried.
'
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->setUser($username, $password);
    $ig->login();
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
    $details = $ig->getCurrentUser();
    echo $details;
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
' 

Response I Get:
Recoverable fatal error: Object of class InstagramAPI\Response\UserInfoResponse could not be converted to string in /opt/lampp/htdocs/PHP/one.php on line 27

**Comment by SteveJobzniak** [comment]
That error message is answered in many closed tickets so you didn't search closed tickets before making a new one... for exampled https://github.com/mgp25/Instagram-API/issues/1246

**Comment by DanielSokil** [comment]
Thank You!
