### ISSUE TITLE
search media deleted

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#1276]
Question. In the old version it was easy to find an error: "Media deleted". In the new version, I can not track it, even outputting all query results. Everywhere the status of approx. You come from the phone, copyright infringement. Can anyone tell?

**Comment by SteveJobzniak** [comment]
??? Needs more info.

**Comment by Triden** [comment]
I apologize for having poorly explained. For some reason, I can not catch this error. An example of an error is: #944
Usually, it arises due to copyright infringement of background music videos.
{"status": "fail", "message": "Media deleted."}

**Comment by SteveJobzniak** [comment]
Status:fail will trigger an exception.

Catch the exception and look at its details. You find examples for exception details in the examples folder.

**Comment by Triden** [comment]
@SteveJobzniak Thank you. Still not a modest question. Does the project bring enough money. What would be interesting for them to do? I've already tried to translate twice, but for some reason my card does miss.

**Comment by Triden** [comment]
@SteveJobzniak
Still do not understand. In the old version, when you request media / configure /? Video = 1
The information is contained. In the new version, this information for some reason does not come across, it just says that everything is loaded. But in fact there is no.
This is old version:
![screenshot_4](https://cloud.githubusercontent.com/assets/16622856/26516160/c38242da-428a-11e7-9804-0829929f732b.png)
