### ISSUE TITLE
Missing Endpoint in Instagram-API

### ISSUE THREAD

**Issue by rafalbednarczuk** [mgp25/Instagram-API#1278]
Sniffing android instagram app I saw one endpoint which isn't included in Instagram-API, it may lead to detect Instagram-API as a bot. Endpoint is:
https://logger.instagram.com/method/logging.clientevent

**Comment by mgp25** [comment]
Wont be implemented

Regards

**Comment by SteveJobzniak** [comment]
@rafalbednarczuk API is already detected as bot. Just don't be evil and you will be fine!

**Comment by SteveJobzniak** [comment]
@rafalbednarczuk API is already detected as fake by IG for MANY reasons and we can't do anything about that. Just don't be evil and you will be fine!

**Comment by rafalbednarczuk** [comment]
I thought you are trying to prevent it from detect. I don't use your API, but I thought you missed this endpoint
