### ISSUE TITLE
ReLogin with wrong password possible

### ISSUE THREAD

**Issue by mario898989** [mgp25/Instagram-API#1279]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question
- [ ] Other

---
Whenever i login successfully and then re login with wrong password, it will still send me isloggedin = true even if i forcelogin = true. How can I clearly check if username and pass is right? Does the problem maybe come from wrong permissions set to the sessions folder or files? I really cant get it to work properly.

try {
	$ig->setUser($username, $password);
	$ig->login();
} catch (\Exception $e) {
	echo 'Something went wrong: '.$e->getMessage()."\n";
	die();
}

//erst nach erfolgreichem login
if($ig->isLoggedIn){
	try{
		$user_id = $ig->getUsernameId($username);

**Comment by mgp25** [comment]
@mario898989 by doing `$ig->login();` you are not re-login, you are just using the previous session, if you want to login again, `$ig->login(true);` 

Please, this is explained in the wiki and other issues, search before opening a new issue

Regards

**Comment by mario898989** [comment]
Hi,I wrote in the issue that I am using Login(true)...Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [mgp25/Instagram-API] ReLogin with wrong password possible (#1279)Von: mgp25 An: mgp25/Instagram-API Cc: mario898989 ,Mention @mario898989 by doing $ig->login(); you are not re-login, you are just using the previous session, if you want to login again, $ig->login(true);
Please, this is explained in the wiki and other issues, search before opening a new issue
Regards

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mgp25/Instagram-API","title":"mgp25/Instagram-API","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mgp25/Instagram-API"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mgp25 in #1279: @mario898989 by doing `$ig-\u003elogin();` you are not re-login, you are just using the previous session, if you want to login again, `$ig-\u003elogin(true);` \r\n\r\nPlease, this is explained in the wiki and other issues, search before opening a new issue\r\n\r\nRegards"}],"action":{"name":"View Issue","url":"https://github.com/mgp25/Instagram-API/issues/1279#issuecomment-304162285"}}}

**Comment by mgp25** [comment]
@mario898989 if you want, delete the session then, check `session` folder.

And if you want further support post debug log. And this is not an API issue, you are probably doing something wrong at your side

Regards

**Comment by mario898989** [comment]
Ok I will do that! Sorry for inconvenience but i read all the docs and still did not find a solution maybe there is a permission issue at my side. anyway thank you very much for your fast support.

**Comment by SteveJobzniak** [comment]
@mario898989 I did research.

Instagram has this rule of login(true):

`password`
`passwordX`
`Xpassword`

All 3 are accepted. Where "X" is "1 single character of any kind".

I think they do this to make sure people can paste their password even if it has whitespace at start or end.

They do not accept 2 or more leading/trailing chars. And they do not accept 1 leading and 1 trailing.

Just 1 leading OR 1 trailing.

That's the issue here. You're testing with the right password + 1 character.

**Comment by mario898989** [comment]
Hi,

yes now when i think back you are right. when i inserted a total other word it was behaving right. but when i tried with one wrong character at the end it accepted. That is why i opened the issue.

Thank you very much for your help!
