### ISSUE TITLE
Cant get pk of user

### ISSUE THREAD

**Issue by vickryab** [mgp25/Instagram-API#1284]
Hi, i wanna ask. i had see this question before in this link https://github.com/mgp25/Instagram-API/issues/688

i cant get a pk value, its working while i use getUsername() but not with getPk();
it says Fatal error: Uncaught Error: Call to undefined method InstagramAPI\User::getPk() in E:\xampp\htdocs\scrape.php:19 Stack trace: #0 {main} thrown in E:\xampp\htdocs\scrape.php on line 19

this is my code 	 

 $feed = $ig->getMediaComments('1514036847012982930_4022248261',$maxId=null);
	  $ambil = $feed->getComments();
foreach($ambil as $data){
	$cek = $data->getUser();
	echo "<br><br><br>";
	print_r($cek->getUsername());
	print_r($cek->getPk());
}

and this is the raw of the code that i want to get
InstagramAPI\User Object
(
    [username:protected] => jodi_ruddickk
    [has_anonymous_profile_picture:protected] => 
    [is_favorite:protected] => 
    [profile_pic_url:protected] => http://scontent-sin6-1.cdninstagram.com/t51.2885-19/s150x150/18443212_1681977731842660_6644265049147834368_a.jpg
    [full_name:protected] => Jodi ;)
    [pk:protected] => 1704803199
    [is_verified:protected] => 
    [is_private:protected] => 1
    [coeff_weight:protected] => 0
    [friendship_status:protected] => 
)

i'v seen before that requires a php 5.7, but my php is 7.0 and still not working. 
thanks foor your answer

**Comment by aitte2** [comment]
"Uncaught Error: Call to undefined method InstagramAPI\User::getPk()"

You are using an old version of this lib. There is no "InstagramAPI\User" class in the new one.

Upgrade.
