### ISSUE TITLE
Some methods are called after login

### ISSUE THREAD

**Issue by michelank** [mgp25/Instagram-API#129]
Why do we have theses methods after login? They didn't do nothing with the return. Is it used just to seem an original use of the App?

```php
$this->syncFeatures();
$this->autoCompleteUserList();
$this->timelineFeed();
$this->getv2Inbox();
$this->getRecentActivity();
```

The same to the endpoint below that is called before the login in the respective method:
`si/fetch_headers/?challenge_type=signup&guid=`

**Comment by michelank** [comment]
The same to the endpoint below that is called before the login in the respective method:
"si/fetch_headers/?challenge_type=signup&guid="

**Comment by wehmoen** [comment]
The Instagram App does the same after successful log in.
