### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by sara89pr** [mgp25/Instagram-API#1291]
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->setUser('yourusername', 'yourpassword');
    $ig->login();
    $result = $ig->comment('14123451234567890_1234567890', "Hello World");
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

RESPONSE: {"status": "fail", "message": "Sorry, the comment data may have been corrupted."}

InstagramAPI\Response\CommentResponse: Sorry, the comment data may have been corrupted.
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below, for example:

GET /api/v1/si/fetch_headers/?guid=123456abcdeff19cc2f123456&challenge_type=signup HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
X-IG-Connection-Type: mobile(UMTS)
X-IG-Capabilities: 3ToAAA==
Accept-Language: en-US
Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; mid=WFI52QABAAGrbKL-ABCDEFGHIJK
User-Agent: Instagram 10.3.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept-Encoding: gzip, deflate, sdch
```

Response:

```http
# Please provide your capture below, for example:

HTTP/1.1 200 OK
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Thu, 15 Dec 2016 08:50:19 GMT
Content-Type: application/json
Set-Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; expires=Thu, 14-Dec-2017 08:50:19 GMT; Max-Age=31449600; Path=/; secure
Connection: keep-alive
Content-Length: 16

{"status": "ok"}
```
---

### Describe your issue

Explanation of your issue goes here.

Please make sure the description is worded well enough to be understood, and with as much context and examples as possible.

We reserve the right to close your ticket without answer if you can't bother spending a few minutes to write a helpful report for us.

**Comment by SteveJobzniak** [comment]
> We reserve the right to close your ticket without answer if you can't bother spending a few minutes to write a helpful report for us.

**Comment by sara89pr** [comment]
Hi 
excuse me for my bad post.
this is what i was trying to say:
i have a big problem.i have started working with mgp/25 instagram package and it have work well but today i have got an error when i trying to login with my account. 
this is that error: Sorry, there was a problem with your request. 
i can login to my account with instagram original app and i can login with mgp/25 with other accounts but i can not login with my account with mgp/25. 
please help me to fix that. 
thank you.

**Comment by SteveJobzniak** [comment]
@sara89pr Hi. Okay we need to see the debug log of the error happening.

Run with $debug=true and paste the whole error message. Then we can see.

**Comment by OwlGreenApple** [comment]
@SteveJobzniak i think i have a same problem with her it says "message": "Sorry, there was a problem with your request."

there is my debug result
<pre>
POST: qe/sync/ DATA: ig_sig_key_version=4&signed_body=33b2dbd5a57681fc4619091078ffddf6d0cdc18bb562bf1b90bda8c50c58fb34.{"id":"f8478d0a-c657-4533-8b30-678845b3da61","experiments":"ig_android_sms_consent_in_reg,ig_android_flexible_sampling_universe,ig_android_background_conf_resend_fix,ig_restore_focus_on_reg_textbox_universe,ig_android_analytics_data_loss,ig_android_gmail_oauth_in_reg,ig_android_phoneid_sync_interval,ig_android_stay_at_one_tap_on_error,ig_android_link_to_access_if_email_taken_in_reg,ig_android_non_fb_sso,ig_android_family_apps_user_values_provider_universe,ig_android_reg_inline_errors,ig_android_run_fb_reauth_on_background,ig_fbns_push,ig_android_reg_omnibox,ig_android_show_password_in_reg_universe,ig_android_background_phone_confirmation_v2,ig_fbns_blocked,ig_android_access_redesign,ig_android_please_create_username_universe,ig_android_gmail_oauth_in_access,ig_android_reg_whiteout_redesign_v3"} ← 200 493B RESPONSE: {"experiments": [{"name": "ig_android_sms_consent_in_reg", "group": "launch_0307", "params": [{"name": "show_sms_consent", "value": "true"}]}, {"name": "ig_android_background_conf_resend_fix", "group": "launch", "params": [{"name": "fix_enabled", "value": "true"}]}, {"name": "ig_android_phoneid_sync_interval", "group": "test_6_hours", "params": [{"name": "fully_synced", "value": "604800"}, {"name": "partially_synced", "value": "21600"}]}, {"name": "ig_android_stay_at_one_tap_on_error", "group": "test_0308", "params": [{"name": "stay_on_error", "value": "true"}]}, {"name": "ig_android_non_fb_sso", "group": "test_20160629", "params": [{"name": "support_non_fb_sso", "value": "true"}]}, {"name": "ig_android_family_apps_user_values_provider_universe", "group": "test", "params": [{"name": "should_provide_user_values", "value": "true"}]}, {"name": "ig_fbns_push", "group": "fbns_test", "params": [{"name": "boot", "value": "enabled"}, {"name": "is_enabled", "value": "enabled"}, {"name": "networ... GET: si/fetch_headers/?challenge_type=signup&guid=93d95c4eda484ca784d2aa053fc9a5f0 ← 200 16B RESPONSE: {"status": "ok"} POST: accounts/login/ DATA: ig_sig_key_version=4&signed_body=c04c259cc4dbd57628033a022e9a98accb493c178c9ca7a0cb5c27075beb0a5f.{"phone_id":"2c9711e7-9de8-4908-8a58-acfd4206ec79","_csrftoken":"IPIPD5ztkJd3F7D9AUAZrNrhCx3j3ohV","username":"xxx","guid":"93d95c4e-da48-4ca7-84d2-aa053fc9a5f0","adid":"30f4892c-5b59-47ee-9c6f-c26711ed48db","device_id":"android-9b083b3862333d0c","password":"xxx","login_attempt_count":0} ← 400 108B RESPONSE: {"message": "Sorry, there was a problem with your request.", "status": "fail", "error_type": "sentry_block"} fin
</pre>

**Comment by SteveJobzniak** [comment]
@OwlGreenApple Oh... this says it all:

`RESPONSE: {"message": "Sorry, there was a problem with your request.", "status": "fail", "error_type": "sentry_block"}`

Sentry block means that Instagram has blocked your account's ability to use this library, because of A) spamming or B) repeatedly and heavily misusing APIs, in a way humans would never call them.

Instagram has improved their detection recently so this is expected. But I have never gotten sentry blocked personally because I behave, never send spam, and I sleep() a long time before every API call so that their servers don't get angry at me.

There is no way to get unblocked.

**Comment by SteveJobzniak** [comment]
Thanks both of you for making me aware of what a sentry_block error server JSON dump looks like (since I've never had sentry block myself). Our detection of that problem wasn't good, since we showed the generic "Sorry..." message the server sent us, and you guys were confused about what the actual problem was.

This new commit doesn't help you guys, but it will avoid further tickets like this. Because the error detection has been improved in https://github.com/mgp25/Instagram-API/commit/e2cb24c16765a808759d90a18572618f98de07c4, so that people can now see the actual reason:

```
It turns out that Instagram sometimes returns a very generic "Sorry,
there was a problem with your request." message string when there's an
error. In that case, they usually have a separate "error_type" variable
describing the actual reason.

So the sentry_block error was thrown as a normal "EndpointException"
with an unknown error reason, which is definitely not what we intended.

This new code instead uses the "error_code" as the server message in
that scenario, so that we properly detect the actual error reason from
the API.

Example server JSON: {"message": "Sorry, there was a problem with your
request.", "status": "fail", "error_type": "sentry_block"}

After this fix, we will now throw the proper exception for that and
other related errors:

Fatal error: Uncaught InstagramAPI\Exception\SentryBlockException:
InstagramAPI\Response\SyncResponse: Sentry block. in ...

This should also eliminate all the tickets we keep getting about "Sorry,
there was a problem...". Since people will now see their actual error.
```
