### ISSUE TITLE
FFmpeg failed to generate a video thumbnail

### ISSUE THREAD

**Issue by lazyboy1801** [mgp25/Instagram-API#1293]
hi, 
I upload video, server reported : 
RESPONSE: {"result": "deprecated", "configure_delay_ms": "6500", "status": "ok"} Something went wrong: FFmpeg failed to generate a video thumbnail.
I installed FFmpeg.I tested FFmpeg, it still works normally.
I checked by command : 
ffmpeg -i C:\Users\PHP-VAN-THU\Desktop\videodemo\sample.mp4 -vf fps= C:\xampp\htdocs\testapi\uploads\sample.png
It has created the image file sample.png in folder upload.I do not know why it does not work, help me!

**Comment by valga** [comment]
I just got the same issue.

@SteveJobzniak, old ffmpeg versions do not accept `-f singlejpeg`. They use `-f mjpeg`. Since you have new version, please check if it works with mjpeg.

**Comment by SteveJobzniak** [comment]
@valga Thanks, I remember looking at that "singlejpeg" format when working on 2.x and thinking maybe we should use mjpeg.

Apparently "singlejpeg" is an alias for "1 frame of mjpeg", if I remember right. So we can probably rewrite it to mjpeg with no bad effects.

I'll investigate!

**Comment by SteveJobzniak** [comment]
@valga Alright!

```
$ diff -s testMJPEG.jpg testSINGLE.jpg 
Files testMJPEG.jpg and testSINGLE.jpg are identical
```

So like I thought, singlejpeg is an alias for "-f mjpeg -vframes 1" to get 1 frame of MJPEG. But since we already do -vframes 1, it's totally pointless. They do the same thing.

All we have to do is change to -f mjpeg, to support old ffmpeg versions?
