### ISSUE TITLE
Problem in installing api through composer

### ISSUE THREAD

**Issue by wp-src** [mgp25/Instagram-API#1294]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue
Hi, First of all thanks for the nice open source library.

I have an issue in installing this library on my existing project through composer.
When i try install it with composer in a new folder, the process is successful but when i try install it on my project which is based on yii2 advanced framework, composer gives this error : 

> Your  requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for mgp25/instagram-php dev-master -> satisfiable by mgp25/instagram-php[dev-master].
>     - Conclusion: remove netresearch/jsonmapper v0.11.0
>     - Conclusion: don't install netresearch/jsonmapper v0.11.0
>     - mgp25/instagram-php dev-master requires netresearch/jsonmapper ^1.0 -> satisfiable by netresearch/jsonmapper[v1.0.0, v1.1.0, v1.1.1].
>     - Can only install one of: netresearch/jsonmapper[v1.0.0, v0.11.0].
>     - Can only install one of: netresearch/jsonmapper[v1.1.0, v0.11.0].
>     - Can only install one of: netresearch/jsonmapper[v1.1.1, v0.11.0].
>     - Installation request for netresearch/jsonmapper (locked at v0.11.0) -> satisfiable by netresearch/jsonmapper[v0.11.0].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

I searched open and closed issues and tried using dev-master at the end of command but same error.
I also tried removing netresearch/jsonmapper and again tried installing this repo but that not worked too,
actually when i try removing netresearch/jsonmapper composer gives this error : 

> netresearch/jsonmapper is not required in your composer.json and has not been removed
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Generating autoload files

When i look at vendor i can see netresearch/jsonmapper already exists, but im not sure if this is the issue ?

Thanks.

**Comment by SteveJobzniak** [comment]
Hi, thanks for the detailed error report, we like that!

> When i look at vendor i can see netresearch/jsonmapper already exists, but im not sure if this is the issue ?

Yes, read your error message:

```
- Conclusion: don't install netresearch/jsonmapper v0.11.0
- mgp25/instagram-php dev-master requires netresearch/jsonmapper ^1.0 -> satisfiable by netresearch/jsonmapper[v1.0.0, v1.1.0, v1.1.1].
- Can only install one of: netresearch/jsonmapper[v1.0.0, v0.11.0].
- Can only install one of: netresearch/jsonmapper[v1.1.0, v0.11.0].
- Can only install one of: netresearch/jsonmapper[v1.1.1, v0.11.0].
```

We require JSONMapper 1.x. But you've already got JSONMapper 0.x.

Composer can only install one version of a library into the "vendor" folder, so your other project is conflicting. They should upgrade themselves to the latest JSONMapper like we have. ;) Not our issue, sorry.
