### ISSUE TITLE
GoodDevices no longer gets HD videos

### ISSUE THREAD

**Issue by ping** [mgp25/Instagram-API#1297]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
require("./vendor/autoload.php");
date_default_timezone_set('UTC');

try {
    $debug = false;
    $api = new \InstagramAPI\Instagram($debug);
    $api->setUser('somebody', 'password');
    $api->login();

    // https://www.instagram.com/p/BL5hkEHDyd5/
    $mediaId = '1367271575733086073_2958144170';
    $media = $api->media->getInfo($mediaId);
    var_dump($api->device->getUserAgent());
    var_dump($media->getItems()[0]->getVideo_versions());

} catch (Exception $e) {
    echo $e->getMessage();
}
```

Error Log/var_dump:

```php
string(101) "Instagram 10.15.0 Android (24/7.0; 380dpi; 1080x1920; OnePlus; ONEPLUS A3010; OnePlus3T; qcom; en_US)"
array(3) {
  [0] =>
  class InstagramAPI\Response\Model\VideoVersions#863 (7) {
    public $url =>
    string(104) "https://scontent-lax3-2.cdninstagram.com/t50.2886-16/14824995_1405058032855842_1493033715599671296_n.mp4"
    public $type =>
    int(101)
    public $width =>
    int(320)
    public $height =>
    int(320)
    public $status =>
    NULL
    public $message =>
    NULL
    public $fullResponse =>
    NULL
  }
  [1] =>
  class InstagramAPI\Response\Model\VideoVersions#855 (7) {
    public $url =>
    string(104) "https://scontent-lax3-2.cdninstagram.com/t50.2886-16/14824995_1405058032855842_1493033715599671296_n.mp4"
    public $type =>
    int(103)
    public $width =>
    int(320)
    public $height =>
    int(320)
    public $status =>
    NULL
    public $message =>
    NULL
    public $fullResponse =>
    NULL
  }
  [2] =>
  class InstagramAPI\Response\Model\VideoVersions#851 (7) {
    public $url =>
    string(104) "https://scontent-lax3-2.cdninstagram.com/t50.2886-16/14824995_1405058032855842_1493033715599671296_n.mp4"
    public $type =>
    int(102)
    public $width =>
    int(320)
    public $height =>
    int(320)
    public $status =>
    NULL
    public $message =>
    NULL
    public $fullResponse =>
    NULL
  }
}
```
---
### Describe your issue

The HD video bug (previously reported in #1088) appears to be back. I tested all 6 of the devices defined in ``GoodDevices.php`` and the problem is consistent. We can't seem to retrieve the 640px-wide video resolutions anymore, at least not with the current configurations.

Using dev-master, but I believe release also has the same problem.

**Comment by SteveJobzniak** [comment]
Wow wtf. That's weird.

When I came up with the fix, it was totallt proven that Instagram used the device model name to deliver HD or not. I could use the exact same user session and just vary a single field in the user agent header (the device model) while keeping everything else in the agent identical, and it gave me HD videos.

So that proved that they look at device models.

I am sure they haven't blacklisted our models, because we use super popular phone user agents, so they can't have demoted those HD devices to non-HD.

Any theories about why it suddenly broke?

1. Maybe the test media we use no longer has HD?
2. Maybe they stop delivering HD URLs when the user-agent client app version gets too old.

I will check some things later when I wake up.

**Comment by SteveJobzniak** [comment]
In the meantime, could you please run devtools/checkDevices.php in dev-master and report your results?

**Comment by SteveJobzniak** [comment]
Okay I got out of bed to run the test... and luckily, everything is still working perfectly.

The checkDevices test runs through some known videos with HD-width (640px wide), and uses all of our official devices, and lastly tries with a non-HD device.

Results: All devices got HD videos. The non-HD one did not get HD. All results are exactly as expected!

```
$ php checkDevices.php 

[Instagram 10.15.0 Android (24/7.0; 380dpi; 1080x1920; OnePlus; ONEPLUS A3010; OnePlus3T; qcom; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...OK.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...OK.
DEVICE OK.

[Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2392; LGE/lge; RS988; h1; h1; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...OK.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...OK.
DEVICE OK.

[Instagram 10.15.0 Android (24/7.0; 640dpi; 1440x2560; HUAWEI; LON-L29; HWLON; hi3660; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...OK.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...OK.
DEVICE OK.

[Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2560; ZTE; ZTE A2017U; ailsa_ii; qcom; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...OK.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...OK.
DEVICE OK.

[Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...OK.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...OK.
DEVICE OK.

[Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G930F; herolte; samsungexynos8890; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...OK.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...OK.
DEVICE OK.

[Instagram 10.15.0 Android (17/4.2.2; 240dpi; 1080x1920; samsung; SM-G350; cs02; hawaii_ss_cs02; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...Bad response: 480x599.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...Bad response: 480x480.
THIS DEVICE IS BAD AND DOES NOT SUPPORT HD VIDEOS!
```

Then, I thought about your video... so I tested it too, with the code you listed:

```php
try {
    $debug = false;
    $api = new \InstagramAPI\Instagram($debug);
    $api->setUser('somebody', 'password');
    $api->login();

    // https://www.instagram.com/p/BL5hkEHDyd5/
    $mediaId = '1367271575733086073_2958144170';
    $media = $api->media->getInfo($mediaId);
    var_dump($api->device->getUserAgent());
    var_dump($media->getItems()[0]->getVideoVersions());

} catch (Exception $e) {
    echo $e->getMessage();
}
```

Result:

```
string(110) "Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_US)"
array(3) {
  [0]=>
  object(InstagramAPI\Response\Model\VideoVersions)#70 (7) {
    ["url"]=>
    string(102) "http://scontent-amt2-1.cdninstagram.com/t50.2886-16/14833054_193645091041391_5908929505195458560_n.mp4"
    ["type"]=>
    int(101)
    ["width"]=>
    int(640)
    ["height"]=>
    int(640)
    ["status"]=>
    NULL
    ["message"]=>
    NULL
    ["fullResponse"]=>
    NULL
  }
  [1]=>
  object(InstagramAPI\Response\Model\VideoVersions)#42 (7) {
    ["url"]=>
    string(103) "http://scontent-amt2-1.cdninstagram.com/t50.2886-16/14829905_1144383745655245_1448796059257012224_n.mp4"
    ["type"]=>
    int(103)
    ["width"]=>
    int(480)
    ["height"]=>
    int(480)
    ["status"]=>
    NULL
    ["message"]=>
    NULL
    ["fullResponse"]=>
    NULL
  }
  [2]=>
  object(InstagramAPI\Response\Model\VideoVersions)#62 (7) {
    ["url"]=>
    string(103) "http://scontent-amt2-1.cdninstagram.com/t50.2886-16/14829905_1144383745655245_1448796059257012224_n.mp4"
    ["type"]=>
    int(102)
    ["width"]=>
    int(480)
    ["height"]=>
    int(480)
    ["status"]=>
    NULL
    ["message"]=>
    NULL
    ["fullResponse"]=>
    NULL
  }
}
```

Finally I decided to try your EXACT device:

```php
try {
    // Fake the user agent:
    $device = new \InstagramAPI\Devices\Device(
        \InstagramAPI\Constants::IG_VERSION,
        \InstagramAPI\Constants::USER_AGENT_LOCALE,
        '24/7.0; 380dpi; 1080x1920; OnePlus; ONEPLUS A3010; OnePlus3T; qcom',
        false
    );

    $api->device = $device;
    $api->client->updateFromCurrentSettings();

    // https://www.instagram.com/p/BL5hkEHDyd5/
    $mediaId = '1367271575733086073_2958144170';
    $media = $api->media->getInfo($mediaId);
    var_dump($device);
    var_dump($api->device->getUserAgent());
    var_dump($media->getItems()[0]->getVideoVersions());
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

Result:

```
object(InstagramAPI\Devices\Device)#39 (13) {
  ["_appVersion":protected]=>
  string(7) "10.15.0"
  ["_userLocale":protected]=>
  string(5) "en_US"
  ["_deviceString":protected]=>
  string(66) "24/7.0; 380dpi; 1080x1920; OnePlus; ONEPLUS A3010; OnePlus3T; qcom"
  ["_userAgent":protected]=>
  string(101) "Instagram 10.15.0 Android (24/7.0; 380dpi; 1080x1920; OnePlus; ONEPLUS A3010; OnePlus3T; qcom; en_US)"
  ["_androidVersion":protected]=>
  string(2) "24"
  ["_androidRelease":protected]=>
  string(3) "7.0"
  ["_dpi":protected]=>
  string(6) "380dpi"
  ["_resolution":protected]=>
  string(9) "1080x1920"
  ["_manufacturer":protected]=>
  string(7) "OnePlus"
  ["_brand":protected]=>
  NULL
  ["_model":protected]=>
  string(13) "ONEPLUS A3010"
  ["_device":protected]=>
  string(9) "OnePlus3T"
  ["_cpu":protected]=>
  string(4) "qcom"
}
string(101) "Instagram 10.15.0 Android (24/7.0; 380dpi; 1080x1920; OnePlus; ONEPLUS A3010; OnePlus3T; qcom; en_US)"
array(3) {
  [0]=>
  object(InstagramAPI\Response\Model\VideoVersions)#42 (7) {
    ["url"]=>
    string(102) "http://scontent-amt2-1.cdninstagram.com/t50.2886-16/14833054_193645091041391_5908929505195458560_n.mp4"
    ["type"]=>
    int(101)
    ["width"]=>
    int(640)
    ["height"]=>
    int(640)
    ["status"]=>
    NULL
    ["message"]=>
    NULL
    ["fullResponse"]=>
    NULL
  }
  [1]=>
  object(InstagramAPI\Response\Model\VideoVersions)#41 (7) {
    ["url"]=>
    string(103) "http://scontent-amt2-1.cdninstagram.com/t50.2886-16/14829905_1144383745655245_1448796059257012224_n.mp4"
    ["type"]=>
    int(103)
    ["width"]=>
    int(480)
    ["height"]=>
    int(480)
    ["status"]=>
    NULL
    ["message"]=>
    NULL
    ["fullResponse"]=>
    NULL
  }
  [2]=>
  object(InstagramAPI\Response\Model\VideoVersions)#59 (7) {
    ["url"]=>
    string(103) "http://scontent-amt2-1.cdninstagram.com/t50.2886-16/14829905_1144383745655245_1448796059257012224_n.mp4"
    ["type"]=>
    int(102)
    ["width"]=>
    int(480)
    ["height"]=>
    int(480)
    ["status"]=>
    NULL
    ["message"]=>
    NULL
    ["fullResponse"]=>
    NULL
  }
}
```

**Comment by ping** [comment]
On a lark, I tested with another account and it returned the HD resolutions like you've shown.

So... It looks like it's something tagged on the user account on the server side based on used devices. The account that I used for testing is logged on primarily on a super old iphone (non-HD).

Super weird. So we know now that logging on to a "new" HD device with the api doesn't quite ensure that you get served HD resolutions.

The results below are from my main testing account (the one logged on the old iphone).

```
[Instagram 10.15.0 Android (24/7.0; 380dpi; 1080x1920; OnePlus; ONEPLUS A3010; OnePlus3T; qcom; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...Bad response: 320x399.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...Bad response: 320x320.
THIS DEVICE IS BAD AND DOES NOT SUPPORT HD VIDEOS!

[Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2392; LGE/lge; RS988; h1; h1; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...Bad response: 320x399.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...Bad response: 320x320.
THIS DEVICE IS BAD AND DOES NOT SUPPORT HD VIDEOS!

[Instagram 10.15.0 Android (24/7.0; 640dpi; 1440x2560; HUAWEI; LON-L29; HWLON; hi3660; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...Bad response: 320x399.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...Bad response: 320x320.
THIS DEVICE IS BAD AND DOES NOT SUPPORT HD VIDEOS!

[Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2560; ZTE; ZTE A2017U; ailsa_ii; qcom; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...Bad response: 320x399.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...Bad response: 320x320.
THIS DEVICE IS BAD AND DOES NOT SUPPORT HD VIDEOS!

[Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...Bad response: 320x399.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...Bad response: 320x320.
THIS DEVICE IS BAD AND DOES NOT SUPPORT HD VIDEOS!

[Instagram 10.15.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G930F; herolte; samsungexynos8890; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...Bad response: 320x399.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...Bad response: 320x320.
THIS DEVICE IS BAD AND DOES NOT SUPPORT HD VIDEOS!

[Instagram 10.15.0 Android (17/4.2.2; 240dpi; 1080x1920; samsung; SM-G350; cs02; hawaii_ss_cs02; en_US)]
* Checking 1451670806714625231_460563723 (should be: 640x799)...Bad response: 320x399.
* Checking 1264771449117881030_460563723 (should be: 640x360)...OK.
* Checking 1435631390916900349_460563723 (should be: 640x640)...Bad response: 320x320.
THIS DEVICE IS BAD AND DOES NOT SUPPORT HD VIDEOS!
```

**Comment by SteveJobzniak** [comment]
So that concludes it. There's absolutely no problem with HD videos. The good devices are still good devices! :)

And yes I was going to suspect some kinda feature-banning by Instagram on your particular account. They do that sometimes, for many things and many reasons.

But I don't think it has anything to do with your account "being primarily used with a non-HD iPhone". Because the checkDevices test I showed you above shows me getting HD video with all good devices, and non-HD as soon as the user agent is changed to a non-HD device. So they only look at user agent. They don't look at account or UUID. It's still the same cookie session. Only the user agent changes. And it instantly affects whether HD videos are given or not.

Still, perhaps your device UUID in the library has been blacklisted. What happens if you delete your user-session storage / database row for that account and let our dev-master library generate a brand new UUID and device ID etc and re-login anew?

**Comment by ping** [comment]
Have already tried deleting the sessions earlier while I was trying to debug which of the 6 devices will work.

Unless I'm mistaken,``rm -rf vendor/mgp25/instagram-php/src/sessions/`` should have wiped everything right?

**Comment by SteveJobzniak** [comment]
Yeah that wipes all cookies and device settings for all users.

Okay well since changing UUID doesn't fix it, that unfortunately concludes that they've specifically banned that feature on that account. I have no idea why.

**Comment by ping** [comment]
Yeah, it's weird. I'll have to fudge around more to see if I can undo that "ban" (everything else works fine though, even posting photos and stuff).

Apologies for false alarm and for keeping you up. Have a good night!

**Comment by SteveJobzniak** [comment]
As I explained earlier, the checkDevices test runs like this:

- Log in with the usual UUID + device.
- Then, re-using the exact same cookies/session (without any relogin inbetween), we just vary the user agent and run the same "get media info" query over and over, with different agents.
- Again, all queries are using the exact same cookies + UUID etc. It just varies the agent.
- The result is that the agent affects whether HD videos are returned. HD agents get the HD videos, non-HD get non-HD videos. And the changeover is instant.

So that proves they only care about user-agent. They _don't_ look at UUID, cookies, other devices logged onto the same account (your iPhone theory), etc.

Therefore my guess is that they've marked your account as "don't give it any HD videos".

Why or how? I have no idea. They're known to block certain features for bot-like behaviors, but I can't think of why they would want to block HD video access. Perhaps you've been leeching lots of HD videos via that account and they want to lower your bandwidth usage. That's a weak theory but it's _a_ theory. :D

**Comment by SteveJobzniak** [comment]
@ping Thanks, I got worried enough to startle me out of bed. Haha. I'm going back now. Let us know if you find out any other info that helps. And I hope you get it sorted out for your sake.

**Comment by ping** [comment]
@SteveJobzniak lol you replied just as I did.

This test account is only used to test the API, so um no, I don't bother to leech IG videos. I mean, it's not like IG videos are wildly entertaining. 😃 

Will pop back with updates if I figure out something.
