### ISSUE TITLE
directMessage

### ISSUE THREAD

**Issue by wrux** [mgp25/Instagram-API#1299]
I am trying to send a message using the API but I am getting a weird response. Here's what i'm getting (replaced the IDs with x):

There are non-existing participants in [xxxx, xxxxxxxxxx].

Here's my code i'm using to send the request:

```
$ig->directMessage(
  [
    'thread' => $messages->getThread()->getThreadId()
  ],
  'Hello'
);
```

Is this an issue with my code or my IG accounts i'm using to test? I have already sent a message between the two accounts in the IG app and the thread exists, it's just not working for me

**Comment by SteveJobzniak** [comment]
Hi. You are using 2.0 which has broken direct messaging functions. And you are using those broken function parameters incorrectly. Get dev-master if direct messaging is important. ;)

**Comment by wrux** [comment]
Awesome, thankyou

**Comment by SteveJobzniak** [comment]
@wrux The `dev-master` has now become very stable. The request-collections are complete. So I think you can safely rely on it. Not much work left until `3.0` is released!

**Comment by wrux** [comment]
Ok thankyou, I am also willing to pay for the subscription fee talked about in your other post. Another question; what format are timestamps? It looks too large to be a unix timestamp

**Comment by SteveJobzniak** [comment]
@wrux Thank you for that. :)

Abou timestamps: `getTakenAt()` for media is a normal unix timestamp. Some other Instagram timestamps use their own special microseconds time from their own epoch. Here's an article where someone reversed what their epoch is:

https://carrot.is/coding/instagram-ids.html

Have fun :)

**Comment by mr-landerson** [comment]
https://discord.gg/KnkHVD8
