### ISSUE TITLE
Instagram Follow Limits

### ISSUE THREAD

**Issue by rifatozkancomtr** [mgp25/Instagram-API#13]
instagram stuck to follow limits..
owgram.com the process crashes account for more than I'm using, but when members
If you solve the problem would donate 50 euro

**Comment by mgp25** [comment]
@rifatozkancomtr explain better, i dont understand what you mean

**Comment by rifatozkancomtr** [comment]
instagram followers account gets stuck when sending limits
Can you give Skype?

**Comment by rifatozkancomtr** [comment]
500k user pass list I want to make without getting stuck on the limit all the track

**Comment by rifatozkancomtr** [comment]
how many connections error

**Comment by mgp25** [comment]
Still dont understand whats your issue. Post code and debug log or explain better for further support

Regards

**Comment by gerchicov-bp** [comment]
@rifatozkancomtr hello. Do you still need info about follow limits? I currently investigated some
