### ISSUE TITLE
Script fails on AWS?

### ISSUE THREAD

**Issue by Yakito** [mgp25/Instagram-API#1302]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ x ] Question
- [ ] Other

Anyone testing this script on an AWS LightSail instance? Since yesterday I started getting an error when trying to run it on my instance (it was working fine). This is the error:
```
PHP Fatal error:  Uncaught Code 1: InstagramAPI\TimelineFeedResponse : login_required
  thrown in /opt/bitnami/apache2/htdocs/src/Instagram.php on line 1958
```

When I run the same code on my local machine it is working fine.

Just wanted to know if this is a block from instagram to AWS instances or it is something I might be doing wrong.

Thanks a lot!

**Comment by mgp25** [comment]
@Yakito make sure you have logged in or copy sessions folder to your server. Do `$i->login();`

As the error says, `login is required`, so just logining in would work. Also i recommend you to turn on debug log, so you can see server response. 

Not API issue, and it should work in AWS.

Regards

**Comment by Yakito** [comment]
Hi, thanks. I am obviously logging in on my code. Also, again, the code
(the exact same was working before and works on localhost)
I would suggest leaving the thread open until someone can confirm the
script is working for them on aws lightsail

Thanks

On Jun 3, 2017 8:09 PM, "mgp25" <notifications@github.com> wrote:

@Yakito <https://github.com/yakito> make sure you have logged in or copy
sessions folder to your server. Do $i->login();

As the error says, login is required, so just logining in would work. Also
i recommend you to turn on debug log, so you can see server response.

Not API issue, and it should work in AWS.

Regards

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mgp25/Instagram-API/issues/1302#issuecomment-306006879>,
or mute the thread

**Comment by SteveJobzniak** [comment]
Hi. You are using an ancient version of this library. That may be why.

There is now 2.0 stable, and 3.0 in dev-master nearly ready for release.

**Comment by Yakito** [comment]
Hi, thanks, I will test it with the latest version, although I am pretty sure I am using 2.0. and I am not sure if that is the case why it would work alright in localhost. 
I will reply here after I make some tests. Thanks for your time.

**Comment by SteveJobzniak** [comment]
@Yakito "Code 1: InstagramAPI\TimelineFeedResponse : login_required" that is a 1.x error message. ;)

**Comment by Yakito** [comment]
Thanks a lot @SteveJobzniak ! Unfortunately I can not make it work, even after updating to 2.0 via composer

The error is still

```
bitnami@ip-172-26-14-172:~/htdocs/vendor/mgp25/instagram-php/examples$ /opt/bitnami/php/bin/php uploadPhoto.php
GET:  feed/timeline?rank_token=2903766685_3c7750c0-6525-4c83-b3b8-0b7a6b0f6423&ranked_content=true
← 400 	 67B
RESPONSE: {"message": "login_required", "logout_reason": 2, "status": "fail"}

Something went wrong: InstagramAPI\TimelineFeedResponse : login_required
```

But again, the script works perfectly on my localhost. There is something going on with AWS Lightsail since the exact same code has been working for me for the past 2 months. I will make some tests with a DigitalOcean instance to check if it fails there too. I keep you posted.

**Comment by Yakito** [comment]
**Update**
the script works perfectly on DigitalOcean instances. My guess is that there is something going on with AWS Lightsail connections to IG. When I get the time I will investigate further. I might try connecting via VNC to see what happens. Thanks for the support!

**Comment by SteveJobzniak** [comment]
@Yakito Okay... hmm. Sometimes, Instagram bans certain webhost IPs/networks due to too many spammers using them. Maybe that's it. But I don't know what error you will see when they ban your network, so I don't know if they send login_required. Maybe. We can't help with this though. Good luck and feel free to post the answer if you find it. Others may get helped by it later.
