### ISSUE TITLE
Hashtag unicode language

### ISSUE THREAD

**Issue by iMaryam95** [mgp25/Instagram-API#1305]
When i used ** getHashtagFeed('hello'); ** it works.
but when used  ** getHashtagFeed('انتخابات'); **

EmptyResponseException
No response from server. Either a connection or configuration error.

**Comment by iMaryam95** [comment]
urlencode() worked

**Comment by aitte2** [comment]
@iMaryam95 I fixed this in the developer version (upcoming version) so you will not need to do urlencode manually anymore after you use the new version. https://github.com/aitte2/Instagram-API/commit/6face47ae219fb4ec75cbafa7e53015b59d05119

If you want early access to the new version:
`composer require mgp25/instagram-php dev-master`
