### ISSUE TITLE
cron isnull

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#1307]
The script is launched via cron. Inside the script, the required script is called through the "system()". Why does guzzle return an empty response from the instagram. The is_null exception is thrown. Nobody faced with this? It was necessary inside the cron script, to call the required script via curl. That is, it works well if you manually start it. If through the "system()" does not work. Do you have any guesswork?

**Comment by SteveJobzniak** [comment]
1. This is not English. I can barely understand what you are saying.
2. This is not a library issue. It's some problem with your system. Not our responsibility.
3. I am running my own script via cron: Cron launches a PHP script, which then launches my main PHP script via `exec("php <mainscript.php>");`. All works perfectly.
