### ISSUE TITLE
Examples seem to be partially broken

### ISSUE THREAD

**Issue by nikilster** [mgp25/Instagram-API#1308]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

The code are the two examples 'accessingValues.php' and 'uploadPhoto.php' *unedited* except for adding my username and password.

**accessingValues.php**
Error:
Fatal error: Call to a member function getPopularFeed() on null in /Users/---directories-omitted---/accessingValues.php on line 26

**uploadPhoto.php**
(For this code, I also provided an example image, $photoFilename, and $captionText)
Fatal error: Call to a member function uploadPhoto() on null in /Users/---directories-omitted---/uploadPhoto.php on line 31

---

### Describe your issue

The examples are throwing errors when trying to run them out of the box.  Did some experimenting and it seems like setUser and login works but the $ig->discover and $ig-timeline objects are null.

Similarly in another test I ran, the $ig->getUserInfoById call works but the $userResponse->getUsername() seemed to throw an error.

**Comment by mgp25** [comment]
@nikilster all the examples are working fine. Make sure you have latest code from master, do the following thing:

```
composer require mgp25/instagram-php dev-master
```

After that, your code will be updated and examples will work.

Regards

**Comment by nikilster** [comment]
@mgp25 Thanks so much for the help!! :)

Might want to update the Readme to reflect that, it currently says:

![screenshot 2017-06-06 10 21 55](https://user-images.githubusercontent.com/1175050/26842856-10a92040-4aa3-11e7-8d8d-87540de8c538.png)

So I used the stable branch in the first line and then spent a couple hours trying to figure out why examples weren't working.  Just curious what was going on.

**Comment by nikilster** [comment]
Ohhhh was it because I pulled the example from github and installed the main master via composer?
 (Assuming the underlying implementation had changed)

**Comment by mgp25** [comment]
@nikilster correct

**Comment by samdoidge** [comment]
Also ran into this issue, v2 is selected by default on require
