### ISSUE TITLE
Image upload error

### ISSUE THREAD

**Issue by RedGhostMe** [mgp25/Instagram-API#131]
Can't upload photo.
Api need update:

RESPONSE: {"status":"fail","message":"Please update your Instagram app to continue posting photos"}

**Comment by wehmoen** [comment]
You need to extract ig_sig_key from the Instagram App and replace the one in the Constants.php with it.

**Comment by RedGhostMe** [comment]
How can I do it? Could you write the key here, if you have already done it?

**Comment by wehmoen** [comment]
See here: https://github.com/mgp25/Instagram-API/wiki/Technical-information#extracting-instagrams-signature-key

**Comment by RedGhostMe** [comment]
Thanks, but given sig_key c1c7d84501d2f0df05c378f5efb9120909ecfb39dff5494aa361ec0deadb509a
does not work
Could you write the actual key?

**Comment by wehmoen** [comment]
You have to extract it yourself. The linked page is a step by step guide
