### ISSUE TITLE
The second and all next messages aren't delivered via direct message

### ISSUE THREAD

**Issue by GRLeo** [mgp25/Instagram-API#1310]
I have a problem with a Python implementation https://github.com/danleyb2/Instagram-API/issues/40 but probably there is the same problem with the original PHP tool.

After the initialization only the first message is delivered ok. The second and all next messages aren't delivered. There is no error message.

In the response['items'] the first and the second message somehow have the same timestamp and item_id.

**Comment by mgp25** [comment]
@GRLeo be sure yo use latest code from master, so far everything works perfectly. Make sure to do:

```
composer require mgp25/instagram-php dev-master
```

Regards
