### ISSUE TITLE
Live broadcasting to Instagram

### ISSUE THREAD

**Issue by itsMoji** [mgp25/Instagram-API#1311]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Hi
Is it possible to broadcast a live video using the API ?
for example broadcast live using a local video or webcam or anything except Instagram app

**Comment by matthijsotterloo** [comment]
Hi @itsMoji,

Live broadcasting is not supported in the API right now.
But feel free to create a PR to add support for this. 

In [https://github.com/mgp25/Instagram-API/blob/master/src/Request/Live.php](this) file you can find all the supported calls regarding the live functionality.

Matthijs

**Comment by itsMoji** [comment]
Thanks for your response @matthijsotterloo,
I don't know how to do this or what is the endpoint or even it is possible or not.

**Comment by mgp25** [comment]
@itsMoji it will be added eventually, no ETA

Regards
