### ISSUE TITLE
Error uploading Photo 

### ISSUE THREAD

**Issue by Vshri** [mgp25/Instagram-API#1315]
Undefined property: `InstagramAPI\Instagram::$timeline`

This is my Code:

```php
require __DIR__.'/vendor/autoload.php';

$username = 'XXXXXXX';
$password = 'XXXXXXXXXX';
$debug = true;
$truncatedDebug = false;

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

$photoFilename = 'files/Jellyfish.jpg';
$captionText = 'Through Api';

try {
    $ig->setUser($username, $password); 
    $ig->login(); 
    $ig->timeline->uploadPhoto($photoFilename, ['caption' => $captionText]);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

```
and on call function `$ig->login();` array is been displayed on page , can you please tell me form where this array is displayed and how to hide that.

Thanks!!

**Comment by Vshri** [comment]
Hey,
 I found solution for uploading photo
Replaced $ig->uploadTimelinePhoto($photoFilename, ['caption' => $captionText]);
instead  $ig->timeline->uploadPhoto($photoFilename, ['caption' => $captionText]);

But please guide me to hide the response from $ig->login(); which is been displayed on page

Thank you!!

**Comment by aitte2** [comment]
You're running the latest development examples. If you want examples for the library version you've installed look in your `vendor/mgp25/instagram-api/examples/` folder.

To turn off debug set `$debug=false`.

**Comment by mgp25** [comment]
@aitte2 i need to add like 4-6 more functions, review everything and if its okay its done. I dont like to say any ETA since i dont know, but if i have to say something i would say at the end of the month.

Regards

**Comment by Vshri** [comment]
It works Thanks you so much guys

**Comment by aitte2** [comment]
@mgp25 Thank you and good luck with everything. :)
