### ISSUE TITLE
Class property conflict

### ISSUE THREAD

**Issue by Sparknsk** [mgp25/Instagram-API#1316]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->setUser('yourusername', 'yourpassword');
    $ig->login();
    $post = $ig->media->getInfo('...')->getItems()[0];
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

InstagramAPI\Response\MediaInfoResponse and InstagramAPI\ResponseTrait define the same property ($status) in the composition of InstagramAPI\Response\MediaInfoResponse. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed
```

**Comment by aitte2** [comment]
@Sparknsk I want to help make this library perfect, so I tried to reproduce it but found that it's not a bug, it's a warning, and it only happens on PHP 5 with `error_reporting(E_ALL | E_STRICT);` (strict error reporting). It doesn't even happen on PHP 7 with strict error reporting.

Here's the message I got in PHP 5: `Strict Standards: InstagramAPI\Response\MediaInfoResponse and InstagramAPI\ResponseTrait define the same property ($status) in the composition of InstagramAPI\Response\MediaInfoResponse. This might be incompatible, to improve maintainability consider using accessor methods in traits instead.`

It's just a duplicate property defined in both a trait and a class. I've fixed all responses with duplicate properties in this pull request:

https://github.com/mgp25/Instagram-API/pull/1317
