### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by jpcastro4** [mgp25/Instagram-API#1319]
First I want to thank the creators and maintainers of the code. A fantastic tool of great value. I hope I can contribute to this soon.

## Problem

I am trying to run the code as a Codeigniter library. I organized the autoload and everything went well.
But I have an error where the GuzzleHttp \ HandlerStack class is not found

```php
spl_autoload_register(function ($class) {
    // project-specific namespace prefix
    $prefix = 'InstagramAPI\\';

    // For backwards compatibility
    $customBaseDir = '';
    
    // base directory for the namespace prefix
    $baseDir = $customBaseDir ?: __DIR__ . '/';

    // does the class use the namespace prefix?
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // no, move to the next registered autoloader
        return;
    }

    // get the relative class name
    $relativeClass = substr($class, $len);

    // replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with .php
    $file = rtrim($baseDir, '/') . '/' . str_replace('\\', '/', $relativeClass) . '.php';

    // if the file exists, require it
    if (file_exists($file)) {
        require $file;
    }else{

    	echo 'Não consegui incluir {$file}';
    }
});
```

> Fatal error: Class 'GuzzleHttp\HandlerStack' not found in C:\wamp\www\instapost\application\libraries\Instagram\Client.php on line 151

The includes should be done in the autoload but from what I have observed they are all correct. If someone can give me a light.

**Comment by mgp25** [comment]
@jpcastro4 have you used composer?

```
composer require mgp25/instagram-php dev-master
```

**Comment by jpcastro4** [comment]
I checked the installation and everything went well. But now I'm getting the following error:

> CURL error 60: SSL certificate problem: unable to get local issuer certificate (see `http://curl.haxx.se/libcurl/c/libcurl-errors.html).

I'm developing my application on localhost

**Comment by mgp25** [comment]
@jpcastro4 that is no API issue, but you can find more information here:

https://stackoverflow.com/questions/21114371/php-curl-error-code-60

Also you can find more in Google.

Regards

**Comment by jpcastro4** [comment]
Yes of course. Anyway thank you too much for the availability. I'm already researching a way to solve. Thank you very much.
