### ISSUE TITLE
mgp25/instagram-php/src/Realtime.php on line 7

### ISSUE THREAD

**Issue by mfaridii** [mgp25/Instagram-API#1320]
error in realtimeClient.php ->

Fatal error: Cannot use InstagramAPI\Realtime\Client as Client because the name is already in use in /Applications/XAMPP/xamppfiles/htdocs/mnmn/vendor/mgp25/instagram-php/src/Realtime.php on line 7

**Comment by mgp25** [comment]
@mfaridii you are probably using an outdated code, please update to latest code from master

Regards

**Comment by mfaridii** [comment]
@mgp25 
 mgp25/instagram-api version dev-master
