### ISSUE TITLE
mgp25/instagram-php/src/Realtime.php on line 7

### ISSUE THREAD

**Issue by mfaridii** [mgp25/Instagram-API#1321]
mgp25/instagram-api version dev-master
error in realtimeClient.php ->
Fatal error: Cannot use InstagramAPI\Realtime\Client as Client because the name is already in use in /Applications/XAMPP/xamppfiles/htdocs/mnmn/vendor/mgp25/instagram-php/src/Realtime.php on line 7

**Comment by valga** [comment]
Will fix it.
