### ISSUE TITLE
Two-factor code being sent twice.

### ISSUE THREAD

**Issue by jackbrown1993** [mgp25/Instagram-API#1323]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ X] Question
- [ ] Other
---

Question: Is it possible to perform two-factor authentication without needing to call $ig->login twice?

Hello,

I am trying to implement two-factor authentication in an app that I am building and here is my current workflow:

First the User enters username and password which submits to my server, I have a login function on my server which looks something like this

```
function login ($username, $password, $twoFactorCode = NULL) {
//Attempt login
    try {
        $ig->setUser($username, $password);
        $loginResponse = $ig->login();
        
        //Check if user requires 2 factor
        if (!is_null($loginResponse) && $loginResponse->getTwoFactorRequired()) {
            //Has user already provided code?
            $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();
            if ($twoFactorCode != NULL) {
                $ig->twoFactorLogin($two_factor_code, $twoFactorIdentifier);
            } else {
            //If my mobile app see's this response it will prompt user for two factor code, they will then // 
            //send $username, $password and $twoFactorCode to this function again
            echo '2_factor';
            http_response_code(401);
            exit(0);
            return false;
            }
        }
}

```
However this causes the two-factor code to be sent by Instagram twice, which makes sense because I am calling $ig->login twice, however, I can't see a way of doing this without calling the login function twice, I thought of doing a check to see if the user has provided $twoFactorCode and if so jump straight to the $ig->twoFactorLogin however this requires a $twoFactorIdentifier input which I believe you can only get by calling $ig->login so unless I store $twoFactorIdentifier from the first request and store it until the user submits the second request with the $twoFactorCode but I am hoping there is a more efficient way to achieve this 👍 

Jack.

**Comment by jpmoney5065** [comment]
Have you tried:

Storing `$twoFactorIdentifier` somewhere when `$twoFactorCode`  equals null.
When your login functions runs, check to see if `$twoFactorIdentifier` has been stored in the last X minutes, if it has then directly run `$ig->twoFactorLogin()`

**Comment by jackbrown1993** [comment]
@jpmoney5065 I did suggest in the last few lines of my comment, I don't see any issue in this but just wanted to check I wasn't missing anything obvious if there is an easier method :)

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/examples/twoFactorLogin.php

**Comment by jackbrown1993** [comment]
Hello @mgp25 I did check the examples but using STDIN isn't an option hence my question, should I just store $twoFactorIdentifier somewhere as suggested by @jpmoney5065 ?

**Comment by mgp25** [comment]
@jackbrown1993 yes, thats seems a good workaround

**Comment by jackbrown1993** [comment]
@mgp25 Thank you.

**Comment by jackbrown1993** [comment]
@mgp25 The only small issue with this is not being able to store the $twoFactorIdentifier with the user_id, as I can't get the user_id until the user is logged in. Having to store in the database using the username/email provided at login.
