### ISSUE TITLE
The photo file "http://localhost/project/assets/upload.jpg" does not exist on disk.

### ISSUE THREAD

**Issue by jpcastro4** [mgp25/Instagram-API#1324]
I'm using the library example but I get the error returning that the image does not exist on the disk.

...?

**Comment by jpcastro4** [comment]
I do not remember reading in the documentation that a default folder is required for uploads. It's needed?

**Comment by mgp25** [comment]
@jpcastro4 the error says it all. The file you are trying to upload doesn't exist or the path isnt correct.

Regards

**Comment by prasetyo-jeanu** [comment]
How to upload image/video from URL

**Comment by jpcastro4** [comment]
Continuo recebendo o mesmo erro. Já movi o projeto para outra pasta e continua o mesmo. Desisto!!!
