### ISSUE TITLE
After update to the latest code,  i get (undefined method InstagramAPI ) 

### ISSUE THREAD

**Issue by instagramlover** [mgp25/Instagram-API#1326]
Dear Support . (i am sorry for my bad english).
I am new to github , so i am sorry if my question does not meet the rules of the forum.

After Updating to the latest version of the lib, i start getting a tons of  
 Call to `undefined method InstagramAPI\Instagram::getUserFeed(); ` (and other functions )
while it was works without any problem with the previews version .

Now i did check the wiki in order to see if the name of the function has been changed or not  since there is no change-log , but it seems it is not the case . 
```
getUserFeed(string $userId, null/string $maxId=null, null/int $minTimestamp=null) : \InstagramAPI\Response\UserFeedResponse
Get a user's timeline feed.
```
Now the code of getUserFeed is : 

```
 $i = new \InstagramAPI\Instagram(true, false, ['storage' => 'memcached']);
try {
    $i->setUser($username, $password);
    $i->login();
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try
        {
            $helper = null;
            do
            {
                if (is_null($helper))
                {
                    $helper = $i->getUserFeed($user_id);
                }
                else
                {
                    $helper = $i->getUserFeed($user_id, $helper->getNextMaxId());
                }
                foreach ($helper->getItems() as $item)
                {
                    print $item;
                }
            } while (!is_null($helper->getNextMaxId()));

        }
        catch (\Exception $e)
        {
            print_r($e);
        }
```

the output log : it is ok just when i reach the getUserFeed error return 

```
GET:  feed/timeline/?ranked_content=true&rank_token=5459650662_3a85668e-a1e1-4c9b-8323-7c061464254e
← 200    17.29kB
RESPONSE: {"num_results": 8, "more_available": true, "auto_load_more_enabled": true, "feed_items": [{"media_or_ad": {"taken_at": 1...........
```

**Comment by jackbrown1993** [comment]
Try

`$i->timeline->getUserFeed`

Jack.

**Comment by instagramlover** [comment]
Oh my god not again. thy promised  that there is no renaming function after v2.0  :( any way i think we will expect a new wiki to follow

**Comment by aitte2** [comment]
@instagramlover The dev-master is for 3.0, a new major version. The wiki is for current official release (2.0).

3.0 has sorted the mess of having hundreds of random functions that were so hard to find. They are all in easy and logical function groups now.

Look here:

https://github.com/mgp25/Instagram-API/tree/master/src/Request

**Comment by instagramlover** [comment]
@aitte2 +1
