### ISSUE TITLE
$ig->account->getCurrentUser()

### ISSUE THREAD

**Issue by mfaridii** [mgp25/Instagram-API#1328]
$json = $ig->account->getCurrentUser(); // v dev
echo json_encode($json);
follower_count: null
media_count: null
following_count: null

**Comment by mgp25** [comment]
Issue doesn't follow the proper format. Therefore is considered as invalid.

Regards

**Comment by aitte2** [comment]
Use $ig->people->getSelfInfo()

**Comment by mfaridii** [comment]
thank @mgp25 @aitte2
