### ISSUE TITLE
List of metadata fields

### ISSUE THREAD

**Issue by davidenco** [mgp25/Instagram-API#1332]
There is no list of available metadata fields in the documentation. Should there be?

**Comment by mgp25** [comment]
@davidenco you need to be more specific. What do you mean by metadata fields? And the wiki is not updated yet.

Regards

**Comment by SteveJobzniak** [comment]
@davidenco Follow the trail of comments. `timeline->uploadPhoto()` for example says something like `@see Internal::configureSinglePhoto() for available metadata fields`. Then you go to src/Request/Internal.php and look at the code of configureSinglePhoto. In that code is a list of metadata fields. Do some digging. The list is near the top of the function it tells you to look at.

This answers the question for everybody who finds this issue later.
