### ISSUE TITLE
Question : is it possible to add link to an uploaded media ?

### ISSUE THREAD

**Issue by mrbinr** [mgp25/Instagram-API#1335]
Before all, i want to congratulate you for this api which is a really good job !

I've seen in this post https://later.com/blog/add-links-instagram-stories/ that it is possible to add  link to an uploaded media, and i would like to know if it's possible with this api ?

Best Regards
Pascall

**Comment by matthijsotterloo** [comment]
Hi @mrbinr,

This hasn't been implemented yet.
But feel free to code it yourself and open a PR.

**Comment by SteveJobzniak** [comment]
@mrbinr @matthijsotterloo Adding links to stories in a Business-account feature. We don't have any Business account so we can't do anything about those features.

We have like two functions in our Business function group, and both of those are outdated. They were contributed by someone long ago and were just ported forwards. We have no way to test them or add other business features:

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Business.php

Sorry.
