### ISSUE TITLE
Protected Response

### ISSUE THREAD

**Issue by jpr0k99** [mgp25/Instagram-API#1338]
I apologize in advance for this very basic question.  
In running the getUserFollowers method all the results are protected.  How must one structure the request to get back data that can be read by another function.

I see there is a public getFollowers() function within FollowerResponse however, have not been able to get this to work.  

Any guidance is appreciated and again, sorry for the very basic question.

Thank you for your work on this extremely robust API.

object(InstagramAPI\FollowerResponse)#26 (5) {
  ["followers":protected]=>
  array(40) {
    [0]=>
    object(InstagramAPI\User)#134 (24) {
      ["username":protected]=>
      string(15) "max_houghton_23"
      ["has_anonymous_profile_picture":protected]=>
      bool(false)
      ["is_favorite":protected]=>

**Comment by mgp25** [comment]
Hello, this is not API issue. I recommend you to search how php objects works, there are plenty of guides available in internet.

Regards!

**Comment by jpr0k99** [comment]
Yes, understood.  thank you.

**Comment by mgp25** [comment]
I forgot to say that there are examples so you can see how its done. `examples` folder

Regards

**Comment by aitte2** [comment]
@mgp25 @jpr0k99 This kind of "InstagramAPI\FollowerResponse" and "InstagramAPI\User" object names means they are using the oldest version of library (1.x). 

Upgrade to latest: `composer require mgp25/instagram-php dev-master` :)

**Comment by jpr0k99** [comment]
ok, thank you for the additional information.  based on the examples I was able to get it working.  I will also update to the latest version.
