### ISSUE TITLE
Story screenshots

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1343]
Hi,

Couldn't figure it out, is there a way to get the amount of times a screenshot has been made of a story? I checked the server response using the `debug = 'true'` but it isn't included in the `$ig->story->getUserStoryFeed($ig->account_id);` call.

Thanks!

**Comment by SteveJobzniak** [comment]
Does the app display a "screenshot counter" for that statistic anywhere? My guess is no. If the answer is No then there is no such statistic.

**Comment by matthijsotterloo** [comment]
The app does display how many times a screenshot has been taken of a photo/video.

**Comment by SteveJobzniak** [comment]
Huh... okay, maybe that info is in the same API that lista the names of all viewers, which some other person asked about.

**Comment by matthijsotterloo** [comment]
That might be possible. I don't have any experience with capturing the network requests, so I hope you'll have some time to take a look at this.

**Comment by SteveJobzniak** [comment]
Maybe related:

https://github.com/mgp25/Instagram-API/issues/1325

**Comment by matthijsotterloo** [comment]
Also, is there a way to see the disappearing messages sent trough Direct Message?

**Comment by SteveJobzniak** [comment]
Hmm, @valga would know the answer to that. He implemented the direct messaging. :)

**Comment by valga** [comment]
@matthijsotterloo, if you are in `unified_inbox` experiment, you can view all disappearing messages in you direct threads as items with type `raven_media`. If you are not in that experiment, you should call `direct->getVisualInbox()` to list all direct threads with disappearing messages, and then call `direct->getVisualThread()` for each thread.

Also, as far as I know, Instagram counts screenshots only for stories sent via direct. There is `expiring_media_action_summary` field in `DirectThreadItem` class that holds some stats, including screenshot counter.

And you can use Realtime to receive screenshot notifications in realtime.

**Comment by matthijsotterloo** [comment]
@valga Makes sense! Thanks :)
