### ISSUE TITLE
Uploading Photo

### ISSUE THREAD

**Issue by Baronsindo** [mgp25/Instagram-API#1344]
when ever i try to uploade a pict i get that error 

Call to undefined method InstagramAPI\Instagram::uploadTimelinePhoto()

this is my code 

                <?php
                require __DIR__ . '/../vendor/autoload.php';
                $ig = new \InstagramAPI\Instagram(TRUE, FALSE);
                //log in
                try {
                    $ig->setUser('MyUsername', 'Mypasss');
                    $ig->login();
                    echo $ig->getUsernameId('sup.quotes');

                } catch (Exception $e) {
                    echo 'Error in Log in ';
                }
                //
                $metadata = ['caption' => 'My awesome caption'];

                $ig->uploadTimelinePhoto('ads.png', $metadata);
                ?>

**Comment by matthijsotterloo** [comment]
The wiki needs to be updated.
Use `$ig->timeline->uploadPhoto` for uploading to your timeline.

**Comment by mgp25** [comment]
For Gods sake. Please read the wiki and the examples, is that hard to do that?

Have a nice weekend btw

Regards
