### ISSUE TITLE
Search followers By Username

### ISSUE THREAD

**Issue by instagramlover** [mgp25/Instagram-API#1346]
Hello ,
In instagram when you go to the users who follow you , there is a search bar you can type the name of the user and it will return a list of your followers .

Is this available in this API ? since i can not find anything related in the pepole class.

**Comment by LanchaBasualdo** [comment]
I hope you are asking this on purpose just to bother the creators of this api because your question makes you look really dumb.
Have you even tried the getFollowers function?
Please close this issue.

Regards
Lancha

**Comment by instagramlover** [comment]
getFollowers will return Followers by passing the user_id and will not return by "user_name"

>>you look really dumb. 
I am sorry , kindly respect others time !
