### ISSUE TITLE
Get all stories

### ISSUE THREAD

**Issue by EphramDoyle** [mgp25/Instagram-API#1347]
Hi,

I am using an old version of Instagram for android where I can listen to the SSL requests with Charles Proxy (on PC I did not).

When I get the stories `'feed/reels_tray/'` not all users have items as you say.
One option is to make individual requests to each user at` 'feed/user/USER_ID/reel_media/'`
But that is too heavy…
I found another option listening the app but I can not imitate it.
For that it is necessary to send a POST to `'feed/reels_media/'` with all the ids (PKs) and this returns the items of all.
But I can not form the post correctly. I always get the message:
`"Message": "Invalid user list"...`
Any ideas? Thanks!

**Comment by mgp25** [comment]
@EphramDoyle hello, this is not API issue. With this API you can get all stories. You can search in the code, it is all well documented.

Regards
