### ISSUE TITLE
How to get people who viewed media story ?

### ISSUE THREAD

**Issue by lazyboy1801** [mgp25/Instagram-API#1349]
`[0] => InstagramAPI\Response\Model\Item Object
                (
                    [taken_at] => 1497944494
                    [pk] => 1541192586445019904
                    [id] => 1541192586445019904_1983941523
                    [device_timestamp] => 1497944493688
                    [media_type] => 1
                    [code] => BVjan3lhVsA
                    [client_cache_key] => MTU0MTE5MjU4NjQ0NTAxOTkwNA==.2
                    [filter_type] => 0
                    [attribution] => 
                    [image_versions2] => InstagramAPI\Response\Model\Image_Versions2 Object
                        (
                            [candidates] => Array
                                (
                                    [0] => InstagramAPI\Response\Model\HdProfilePicUrlInfo Object
                                        (
                                            [url] => http://instagram.fhan4-1.fna.fbcdn.net/t51.9792-15/e35/19410922_141154263113147_2683541952187596800_n.jpg?ig_cache_key=MTU0MTE5MjU4NjQ0NTAxOTkwNA%3D%3D.2
                                            [width] => 640
                                            [height] => 640
                                            [status] => 
                                            [message] => 
                                            [fullResponse] => 
                                        )

                                    [1] => InstagramAPI\Response\Model\HdProfilePicUrlInfo Object
                                        (
                                            [url] => http://instagram.fhan4-1.fna.fbcdn.net/t51.9792-15/s240x240/e35/19410922_141154263113147_2683541952187596800_n.jpg?ig_cache_key=MTU0MTE5MjU4NjQ0NTAxOTkwNA%3D%3D.2
                                            [width] => 240
                                            [height] => 240
                                            [status] => 
                                            [message] => 
                                            [fullResponse] => 
                                        )

                                )

                            [status] => 
                            [message] => 
                            [fullResponse] => 
                        )

                    [original_width] => 640
                    [original_height] => 640
                    [view_count] => 
                    [organic_tracking_token] => eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjljYzVlZjJhNzhiNDQ1YmVhMWViNjhmYzQwMGFjODBiMTU0MTE5MjU4NjQ0NTAxOTkwNCIsInNlcnZlcl90b2tlbiI6IjE0OTgwMjk3MjI2Nzh8MTU0MTE5MjU4NjQ0NTAxOTkwNHwxOTgzOTQxNTIzfGUwOGMwMzZjZjVjNDhiYzFiYjg2Y2U3ODE2MTQ0NmNkY2ZkYzZhYmNmYmQ2OGQ0OTAyZTViYzZiODU3ZTg5ZDMifSwic2lnbmF0dXJlIjoiIn0=
                    [has_more_comments] => 
                    [max_num_visible_preview_comments] => 4
                    [preview_comments] => Array
                        (
                        )

                    [comments_disabled] => 
                    [reel_mentions] => Array
                        (
                        )

                    [story_cta] => 
                    [caption_position] => 0
                    [expiring_at] => 1498030894
                    [is_reel_media] => 1
                    [next_max_id] => 
                    [carousel_media] => 
                    [comments] => 
                    [comment_count] => 0
                    [caption] => 
                    [caption_is_edited] => 
                    [photo_of_you] => 
                    [video_versions] => 
                    [has_audio] => 
                    [video_duration] => 
                    [user] => InstagramAPI\Response\Model\User Object
                        (
                            [username] => grsvn12
                            [has_anonymous_profile_picture] => 
                            [is_favorite] => 
                            [profile_pic_url] => https://instagram.fhan4-1.fna.fbcdn.net/t51.2885-19/s150x150/13561712_1240525582638175_1060943594_a.jpg
                            [full_name] => grs
                            [pk] => 1983941523
                            [is_verified] => 
                            [is_private] => 
                            [coeff_weight] => 
                            [friendship_status] => 
                            [hd_profile_pic_versions] => 
                            [byline] => 
                            [search_social_context] => 
                            [unseen_count] => 
                            [mutual_followers_count] => 
                            [follower_count] => 
                            [social_context] => 
                            [media_count] => 
                            [following_count] => 
                            [is_business] => 
                            [usertags_count] => 
                            [profile_context] => 
                            [biography] => 
                            [geo_media_count] => 
                            [is_unpublished] => 
                            [allow_contacts_sync] => 
                            [show_feed_biz_conversion_icon] => 
                            [profile_pic_id] => 1283182478911910106_1983941523
                            [auto_expand_chaining] => 
                            [can_boost_post] => 
                            [is_profile_action_needed] => 
                            [has_chaining] => 
                            [include_direct_blacklist_status] => 
                            [can_see_organic_insights] => 
                            [can_convert_to_business] => 
                            [convert_from_pages] => 
                            [show_business_conversion_icon] => 
                            [show_conversion_edit_entry] => 
                            [show_insights_terms] => 
                            [can_create_sponsor_tags] => 
                            [hd_profile_pic_url_info] => 
                            [usertag_review_enabled] => 
                            [profile_context_mutual_follow_ids] => 
                            [profile_context_links_with_user_ids] => 
                            [has_biography_translation] => 
                            [business_contact_method] => 
                            [category] => 
                            [direct_messaging] => 
                            [fb_page_call_to_action_id] => 
                            [is_call_to_action_enabled] => 
                            [public_phone_country_code] => 
                            [public_phone_number] => 
                            [contact_phone_number] => 
                            [latitude] => 
                            [longitude] => 
                            [address_street] => 
                            [zip] => 
                            [city_id] => 
                            [city_name] => 
                            [public_email] => 
                            [is_needy] => 
                            [external_url] => 
                            [external_lynx_url] => 
                            [email] => 
                            [country_code] => 
                            [birthday] => 
                            [national_number] => 
                            [gender] => 
                            [phone_number] => 
                            [needs_email_confirm] => 
                            [status] => 
                            [message] => 
                            [fullResponse] => 
                        )

                    [likers] => Array
                        (
                        )

                    [like_count] => 0
                    [preview] => 
                    [has_liked] => 
                    [explore_context] => 
                    [explore_source_token] => 
                    [explore] => 
                    [impression_token] => 
                    [usertags] => 
                    [media_or_ad] => 
                    [media] => 
                    [stories] => 
                    [top_likers] => 
                    [suggested_users] => 
                    [comment_likes_enabled] => 
                    [can_viewer_save] => 1
                    [has_viewer_saved] => 
                    [location] => 
                    [lat] => 
                    [lng] => 
                    [story_locations] => Array
                        (
                        )

                    [algorithm] => 
                    [status] => 
                    [message] => 
                    [fullResponse] => 
                )`

**Comment by matthijsotterloo** [comment]
Please fill a normal issue report. This way we can not help with this.

**Comment by mgp25** [comment]
@lazyboy1801 Duplicate issue + you are using outdated code

Regards
