### ISSUE TITLE
JSON property "preview" must be an array, string given

### ISSUE THREAD

**Issue by David-Kurniawan** [mgp25/Instagram-API#1352]
### JSON property "preview" must be an array, string given Issue

I cannot get userfeed from this id

`$user = $ig->getUserFeed(2010703843);`
`echo "<pre>";`
` print_r($user);`
result:

> JSON property "preview" must be an array, string given

**Comment by mgp25** [comment]
@David-Kurniawan please update to latest master code and use as shown in the examples.

`$i->timeline->getUserFeed('2010703843');`

Regards

**Comment by SteveJobzniak** [comment]
Works for me in `dev-master` as said by mgp25.

**Comment by David-Kurniawan** [comment]
@mgp25 You are my hero... thank you very much!

@SteveJobzniak Yes, this is work

:dancer:
