### ISSUE TITLE
Failed to init Realtime: Can not subscribe to inbox

### ISSUE THREAD

**Issue by rpw98** [mgp25/Instagram-API#1353]
I was trying to test realtimeClient example but I got this error:

Failed to init Realtime: Can not subscribe to inbox

For whatever reason, maybe a new Instagram change, recent "direct_v2/inbox" calls returns no subscription information. Maybe that is the cause?

Thank you!

**Comment by dish615** [comment]
i'm getting this as well! is there another way to get the subscription info?

**Comment by dish615** [comment]
i'm using Charles to sniff and i noticed a new uri endpoint - /api/v1/push/register/. this might be how instagram switched it's sub method? i don't know though...

**Comment by valga** [comment]
Well, Instagram is deprecating WebSocket client (Telegraph) in favor of MQTT one since 10.26.0. It seems that someone has failed there, because I have `"is_telegraph_enabled":"1"` in my experiments, but `direct_v2/inbox` doesn't have `subscription`. Or they made it intentionally to force kill Telegraph, I don't know.

**Comment by mgp25** [comment]
@valga although PR was okay, error persists. I have reopened this issue so you can check it later

**Comment by valga** [comment]
@mgp25 hmm, the only scenario to have mentioned error now is:
1) receive valid subscription model in inbox response;
2) start websocket client;
3) receive event with must_refresh flag;
4) receive null for subscription model in inbox response.

So, either you have _another_ error or Instagram is targeting our implementation. Post your RTC debug log, and I will verify that.

**Comment by mgp25** [comment]
@valga i tested `realtimeClient.php`.

**Debug log**
(Some data and responses are omitted)

```
POST:  feed/timeline/
RESPONSE: OK

POST:  feed/timeline/
RESPONSE: OK

[13:33:36] [rtc] starting websocket client

GET:  direct_v2/inbox/?persistentBadging=true
RESPONSE: OK

[!!!] Failed to init Realtime: Can not subscribe to inbox.
```

**Comment by valga** [comment]
Your log is from unfixed version, because it starts WebSocket client before checking `direct_v2/inbox/` response.

**Comment by mgp25** [comment]
@valga you are right, totally my fault. I thought i synced my code with master, it wasnt. 

Everything running flawlessly.

Regards 😄

**Comment by rpw98** [comment]
Thank you. But how to test it? When I run the realtimeClient example, it stopped here:

[mqtt] Setting up keepalive timer to 900.0 seconds [12:19:15] [mqtt] Subscribing to topics ig/live_notification_subscribe/1752589573, ig/u/v1/1752589573 [12:19:15] [mqtt] Sending message {"sub":["ig/live_notification_subscribe/1752589573","ig/u/v1/1752589573"]} to topic /pubsub [12:19:16] [mqtt] Connection has been closed [12:19:16] [mqtt] Existing keepalive timer has been cancelled

It appears collection was closed as soon as subcribe message was sent. Is it right?

**Comment by rpw98** [comment]
Based on my understanding of the code, all of those happens *before* connection. It appears connection was never successful. It just closes right away.

**Comment by valga** [comment]
@rpw98, it isn't right. Connection should stay opened. But it is very hard to tell why it is being closed constantly for you. Please answer to following questions:
1. Do you use proxy?
2. What OS/PHP version do you have?
3. Do you have event or libev or libevent extension(s) installed? If no, will something change after its installation?

**Comment by rpw98** [comment]
Thanks for your reply. 

No, I do not use proxy. 
I'm using latest wamp server on Windows 7. Php version is 5.6.30. I'm not sure about libevent. I don't I have it. Is it a must?

**Comment by valga** [comment]
I just downloaded PHP 5.6.30 for Windows, and `realtimeClient.php` works with it out of the box. It seems you have something with your network that drops MQTT connections. Do you have some firewall/antivirus software running?

Event extension is recommended, because it speeds up Realtime client. But it is not a must, so don't bother about it.

**Comment by SteveJobzniak** [comment]
Aww, I'm sorry to see this trouble valga. Anyway, he made a new ticket for this issue:

https://github.com/mgp25/Instagram-API/issues/1363

**Comment by rpw98** [comment]
@valga I don't have firewall/antivirus software running. And Instagram on my phone works under the same network. Very strange :-(
