### ISSUE TITLE
Wiki access request

### ISSUE THREAD

**Issue by Julian-O** [mgp25/Instagram-API#1354]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [N/A] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ N/A] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [X] Other

---

### Describe your issue

I would like to make some edits to your wiki, but it is currently configured to only allow access to "Collaborators". 

Planned edits:
* Copy-edit of FAQ - especially punctuation and capitalisation.
* Some tips about some causes of 500 server errors.

If you would like these edits, please either add me as a collaborator, or open up Wiki editing to the public.

**Comment by mgp25** [comment]
@Julian-O Hello,

For many reason i think wiki should be kept private. Nevertheless, if you want to add anything or do any modification, you can post it here or send it to my mail and ill do the changes.

If you want to be a collaborator, we need to be sure you know how API works. Every commit is done will be checked, and if they are good enough, you will be upgrade to a collaborator. This is done this way, to prevent the code to get messy in the future.

Thanks 😄 

Regards

**Comment by Julian-O** [comment]
Thank you, but I am not interested in editing the code. I am also not interested in describing the changes like "There should be an apostrophe between the I and the m in the seventh line." That would be too painful.

If the contents of the Wiki were in a readme or text document, I could change it in GitHub and you could review it, but GitHub's Wiki system doesn't support that.

**Comment by SteveJobzniak** [comment]
@Julian-O Try to clone it locally and edit it that way: `git clone https://github.com/mgp25/Instagram-API.wiki.git`

**Comment by Julian-O** [comment]
@SteveJobzniak: That doesn't allow a pull request.

Here's the updated file. Do with it what you will.

[FAQ.zip](https://github.com/mgp25/Instagram-API/files/1099831/FAQ.zip)

**Comment by SteveJobzniak** [comment]
@Julian-O Thanks, the new table of contents look much nicer. I've now inserted all of your changes, and I also did some more rewrites since the FAQ was outdated.

https://github.com/mgp25/Instagram-API/wiki/FAQ

**Comment by Julian-O** [comment]
@SteveJobzniak: "This is an internal Instagram server error, and should only be temporary."

It might not be temporary. I've received them for passing badly sized images.

**Comment by mgp25** [comment]
@Julian-O its specified there too:

--- 

This is an internal Instagram server error, and should only be temporary.

Note: This is NOT an API issue. Please so don't open any issue related to this.

Some causes that have been reported by our users:

 - **Uploaded photos must be an acceptable size and shape; they are not resized by the server.**
 - EXIF data may cause an uploaded photo to be rejected.
 - Incorrectly configured HTTP proxies may trigger this error.

**Comment by Julian-O** [comment]
I understand but by saying it "should" only be temporary, you are contradicting the text further down. How about "might only be temporary" instead?

**Comment by SteveJobzniak** [comment]
@Julian-O Okay I rewrote it: https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-the-500-http-error-code-mean
