### ISSUE TITLE
emojis

### ISSUE THREAD

**Issue by aquarius1727** [mgp25/Instagram-API#1355]
Hello Guys,

I was trying to use directMessage with emojis on text....how can i add emoji to it?

Go this link here for emojis https://apps.timwhitlock.info/emoji/tables/unicode#block-6c-other-additional-symbols

tried this but doesn't work
$resp = $ig->directMessage('5534942321', '&#x1f604');
$resp = $ig->directMessage('5534942321', '& # x 1 f 6 0 4 ;'); ->without space
$resp = $ig->directMessage('5534942321', '&#1f604;');
$resp = $ig->directMessage('5534942321', '\xF0\x9F\x98\x81');

**Comment by mgp25** [comment]
@aquarius1727 you are using an outdated core. I recommend ou to update to latest mater code.

If you have UTF-8 enabled, you can paste the emoji directly.


$ig->direct->sendText('5534942321', :smile:)

Regards

**Comment by aquarius1727** [comment]
damn it that is what im thinking before... awesome! thanks a lot @mgp25
