### ISSUE TITLE
getUserFollowings pagination is not working

### ISSUE THREAD

**Issue by Yahixi** [mgp25/Instagram-API#1358]
Hello,

Since a few days ago the pagination of the function getUserFollowings is not working, it returns all the following users of the account. This problem arised since the other pagination problems appear. The pagination problems of other functions are resolved but this is still broken. How could I fix it?

Thanks

**Comment by SteveJobzniak** [comment]
Diiekjeickerkcikgkkekgif

**Comment by SteveJobzniak** [comment]
Discuss this in the other open ticket.
