### ISSUE TITLE
Capcha

### ISSUE THREAD

**Issue by Arei15** [mgp25/Instagram-API#136]
I put like in Instagram and I  get enter the captcha in Instagram.Is there a way around this?

**Comment by wehmoen** [comment]
At the moment there aren't any workarounds for this.

**Comment by mgp25** [comment]
Ofcouse, but later

**Comment by Arei15** [comment]
mgp25, Mayby, you have ansver, I can write code, please write your mind for this quastion.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/issues/60#issuecomment-204697746

**Comment by Arei15** [comment]
If i write uploud video,  you write ansver?))))

**Comment by mgp25** [comment]
Yes

**Comment by Arei15** [comment]
Tomorrow or  today.

**Comment by Arei15** [comment]
public string UploadVideo(byte[] previewData, byte[] videoData, string caption)
        {
            string upload_id = ((long)(DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0)).TotalSeconds).ToString();

            string uuid = Guid.NewGuid().ToString();

            #region Upload video

            {
                Uri uri = new Uri(HttpUrl + "upload/video/");

                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
                request.Method = "POST";
                request.UserAgent = UserAgent;
                request.Host = "i.instagram.com";
                request.UseDefaultCredentials = true;
                request.AllowAutoRedirect = false;
                request.KeepAlive = true;
                request.CookieContainer = new CookieContainer();
                request.CookieContainer.Add(uri, _cookies);

                byte[] upload_video_data_array = Encoding.UTF8.GetBytes($"upload_id={upload_id}&media_type=2&_uuid={uuid}&_csrftoken={_csrftoken}");

                using (Stream stream = request.GetRequestStream())
                {
                    stream.Write(upload_video_data_array, 0, upload_video_data_array.Length);
                }

                try
                {
                    using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                    {
                        using (StreamReader reader = new StreamReader(response.GetResponseStream()))
                        {
                            dynamic node = new JNode(reader.ReadToEnd());

                            if (node != null)
                            {
                                if (node.ContainsKey("video_upload_urls"))
                                {
                                    JList urls = node.video_upload_urls;

                                    if (urls != null)
                                    {
                                        if (urls.Count > 0)
                                        {
                                            string url = urls[3].url.Replace("\\u0026", "&").Replace("\\", "");

                                            string job = urls[3].job;

                                            if (!string.IsNullOrEmpty(url) && !string.IsNullOrEmpty(job))
                                            {
                                                long chunk = Convert.ToInt64(Math.Floor(videoData.Length / 4.0));

                                                long last = (videoData.Length - (chunk * 4));

                                                List<byte> data = videoData.ToList();

                                                for (int i = 0; i < 4; i++)
                                                {
                                                    long start = (i * chunk);

                                                    long end = ((i + 1) * chunk) + ((i == 3) ? last : 0);

                                                    #region Upload chunk

                                                    Uri chunk_uri = new Uri(url);
                                                    HttpWebRequest chunk_request = (HttpWebRequest)WebRequest.Create(chunk_uri);
                                                    chunk_request.Method = "POST";
                                                    chunk_request.Host = "upload.instagram.com";
                                                    chunk_request.Accept = "*/*";
                                                    chunk_request.Headers.Add("Cookie2", "$Version=1");
                                                    chunk_request.ContentType = "application/octet-stream";
                                                    chunk_request.ContentLength = end - start;
                                                    chunk_request.Headers.Add("Session-ID", upload_id);
                                                    chunk_request.Headers.Add("Content-Disposition", "attachment; filename=\"2.mov\"");
                                                    chunk_request.UserAgent = UserAgent;
                                                    chunk_request.UseDefaultCredentials = true;
                                                    chunk_request.Headers.Add("Content-Range", $"bytes {start}-{end - 1}/{videoData.Length}");
                                                    chunk_request.Headers.Add("job", job);
                                                    chunk_request.AllowAutoRedirect = false;
                                                    chunk_request.CookieContainer = new CookieContainer();
                                                    chunk_request.CookieContainer.Add(chunk_uri, _cookies);
                                                    chunk_request.KeepAlive = true;

                                                    byte[] chunk_data = data.GetRange((int)start, (int)(end - start)).ToArray();

                                                    using (Stream chunk_stream = chunk_request.GetRequestStream())
                                                    {
                                                        chunk_stream.Write(chunk_data, 0, chunk_data.Length);
                                                    }

                                                    HttpWebResponse chunk_response = (HttpWebResponse)chunk_request.GetResponse();

                                                    chunk_response.Close();

                                                    #endregion
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                catch
                {
                    return null;
                }
            }

            #endregion

            #region Upload preview

            {
                Uri uri = new Uri(HttpUrl + "upload/photo/");
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
                request.Method = "POST";
                request.UserAgent = UserAgent;
                request.Host = "i.instagram.com";
                request.Accept = "*/*";
                request.ContentType = $"multipart/form-data; boundary={uuid}";
                request.Headers.Add("Cookie2", "$Version=1");
                request.UseDefaultCredentials = true;
                request.AllowAutoRedirect = false;
                request.CookieContainer = new CookieContainer();
                request.CookieContainer.Add(uri, _cookies);
                request.KeepAlive = true;
                
                string data = string.Empty;

                data += $"\r\n\r\n--{uuid}\r\n";
                data += $"Content-Disposition: form-data; name=\"upload_id\"\r\n";
                data += $"\r\n";
                data += $"{upload_id}\r\n";
                data += $"--{uuid}\r\n";
                data += $"Content-Disposition: form-data; name=\"_uuid\"\r\n";
                data += $"\r\n";
                data += $"{uuid}\r\n";
                data += $"--{uuid}\r\n";
                data += $"Content-Disposition: form-data; name=\"_csrftoken\"\r\n";
                data += $"\r\n";
                data += $"{_csrftoken}\r\n";
                data += $"--{uuid}\r\n";
                data += $"Content-Disposition: form-data; name=\"image_compression\"\r\n";
                data += $"\r\n";
                data += "{\"lib_name\":\"jt\",\"lib_version\":\"1.3.0\",\"quality\":\"100\"}\r\n";
                data += $"--{uuid}\r\n";
                data += $"Content-Disposition: form-data; name=\"photo\"; filename=\"pending_media_{upload_id}.jpg\"\r\n";
                data += $"Content-Type: application/octet-stream\r\n";
                data += $"Content-Transfer-Encoding: binary\r\n\r\n";

                byte[] begin_block = Encoding.UTF8.GetBytes(data);

                byte[] end_block = Encoding.UTF8.GetBytes($"\r\n--{uuid}--");
                
                request.ContentLength = (begin_block.Length + previewData.Length + end_block.Length);

                try
                {
                    using (var stream = request.GetRequestStream())
                    {
                        stream.Write(begin_block, 0, begin_block.Length);
                        stream.Write(previewData, 0, previewData.Length);
                        stream.Write(end_block, 0, end_block.Length);
                    }
                }
                catch 
                {
                    return null;
                }
                
                try
                {
                    HttpWebResponse response = (HttpWebResponse)request.GetResponse();

                    response.Close();
                }
                catch
                {
                    return null;
                }
            }

            #endregion

            #region Configure video

            {
                string configure = $"{{\"caption\":\"{caption}\",\"upload_id\":\"{upload_id}\",\"source_type\":\"3\", \"camera_position\":\"unknown\",\"extra\":{{\"source_width\":1280,\"source_height\":720}},\"clips\":[{{\"length\":10.0,\"creation_date\" :\"2016-04-09T19:03:32-0700\",\"source_type\":\"3\",\"camera_position\":\"back\"}}],\"poster_frame_index\":0,\"audio_muted\":false,\"filter_type\":\"0\",\"video_result\":\"deprecated\",\"_csrftoken\":\"{_csrftoken}\",\"_uuid\":\"{uuid}\",\"_uid\":\"{UserId}\"}}";
 
                string signature = GetSignature(configure);

                byte[] signed = Encoding.UTF8.GetBytes("signed_body=" + Uri.EscapeDataString(signature + "." + configure) + "&ig_sig_key_version=4");

                Uri uri = new Uri(HttpsUrl + "media/configure/?video=1");

                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
                request.Method = "POST";
                request.UserAgent = UserAgent;
                request.Host = "i.instagram.com";
                request.Accept = "*/*";
                request.CookieContainer = new CookieContainer();
                request.CookieContainer.Add(uri, _cookies);
                request.ContentLength = signed.Length;

                try
                {
                    using (Stream stream = request.GetRequestStream())
                    {
                        stream.Write(signed, 0, signed.Length);
                    }
                }
                catch
                {
                    return null;
                }

                try
                {
                    using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                    {
                        using (Stream stream = response.GetResponseStream())
                        {
                            using (StreamReader reader = new StreamReader(stream))
                            {
                                return reader.ReadToEnd();
                            }
                        }
                    }
                }
                catch (WebException e)
                {
                    //var resp = new StreamReader(e.Response.GetResponseStream()).ReadToEnd();

                    return null;
                }
            }

            #endregion
        }

**Comment by Arei15** [comment]
@mgp25 Done, now you.

**Comment by mgp25** [comment]
@Arei15 send me a mail

**Comment by Arei15** [comment]
@mgp25 Sent a mail to me@mgp25.com
