### ISSUE TITLE
Option to check if thread has new messages?

### ISSUE THREAD

**Issue by CashCode** [mgp25/Instagram-API#1360]
Hey. Wrote about it month ago, you said it was not implemented. 
getInbox() has field unseen_count, but how to know which tread has unseen messages and which has not?
I really cant find this option, have read all documentation and even tried getVisualInbox(), but it returns something useless.
Thanks.

**Comment by matthijsotterloo** [comment]
This is not implemented. 
Feel free to make a PR.

**Comment by CashCode** [comment]
I think it's about detection, not about making addition queries.

**Comment by valga** [comment]
`DirectThread` model has `unseen_count` field since a1576f868bf32c2e414029742eb0a09d330762fa.

**Comment by CashCode** [comment]
**valga**, of course I know about this parameter.
But:
1) it doesn't seems to be equal to the number in right top corner in the app.
2) how to know which one is read? You might read the top one thread and the others (old ones) would be not read. 
For example, attached screen of inbox. Let's gess it shows 1 unread message. How should I know it's second one or first one from top? It's sorted by time, not by read.
![photo_2017-06-30_23-17-13](https://user-images.githubusercontent.com/8258294/27752681-f19b53f2-5dea-11e7-8bb8-36574bcd9d25.jpg)
