### ISSUE TITLE
EndpointException: Not eligible for chaining.

### ISSUE THREAD

**Issue by tcz** [mgp25/Instagram-API#1362]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
<?php

require __DIR__.'/vendor/autoload.php';

$ig = new \InstagramAPI\Instagram();

$username = 'xxx';
$password = 'xxx';
$debug = true;
$truncatedDebug = false;

try {
    $ig->setUser($username, $password);
    $ig->login();
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

$userId = '1207029270';

$userInfo = $ig->getUserInfoById($userId);
$feed = $ig->getUserFeed($userId);
$suggestedUsers = $ig->getSuggestedUsers($userId);

```

Error Log/var_dump:

```php

PHP Fatal error:  Uncaught InstagramAPI\Exception\EndpointException: Not eligible for chaining. in /Users/xxx/crawler2/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:88
Stack trace:
#0 /Users/xxx/crawler2/vendor/mgp25/instagram-php/src/Client.php(437): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'Not eligible fo...')
#1 /Users/xxx/crawler2/vendor/mgp25/instagram-php/src/Request.php(105): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\SuggestedUsersResponse), Object(stdClass), true, NULL)
#2 /Users/xxx/crawler2/vendor/mgp25/instagram-php/src/Instagram.php(2988): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\SuggestedUsersResponse))
#3 /Users/xxx/crawler2/errortest.php(24): InstagramAPI\Instagram->getSuggestedUsers('1207029270')
#4 {main}
  thrown in /Users/xxx/crawler2/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php on line 88

```

### Describe your issue

Every few request (3-4) to `getSuggestedUsers` gets this error. Seemingly it doesn't depends on the target account, happens with any other account too.

**Comment by mgp25** [comment]
@tcz you are using outdated code. Make sure to have latest code and review code changes and documentaiton before opening a new issue. Also check examples.

```php
$ig->timeline->getUserFeed($userId);
```

Regards

**Comment by tcz** [comment]
It's the stable composer version. Should I point to master instead?

**Comment by SteveJobzniak** [comment]
@tcz Yes master is now very stable and is in the final stages, but we simply won't mark it as 3.0 until a few more functions are added.

However I don't think master will help with this aince the actual endpoint call for that one hasn't been changed since 2.0 as far as I can remmeber.

Instagram is saying that the user ID you gave them has no "chaining" users. Chaining is their word for "suggested/related users". If the same user fails the first try but works when you retry, I have a theory: Their server probably first fails to find any related users because they have no data for that user (because nobody has recently visited their profile), then it queues the "build related users tree" job on their backend server, generates related users, and then your subsequent calls will succeed.

**Comment by tcz** [comment]
Thanks for the explanation, that makes total sense. Eventual consistency
ftw!

Btw superb library, thank you for all your work put into it!

**Comment by SteveJobzniak** [comment]
@tcz Thanks for the thank-you note. It has been extremely hard work and it's lovely to hear it's appreciated. :-)
