### ISSUE TITLE
Add link to Story Post

### ISSUE THREAD

**Issue by SoleSS** [mgp25/Instagram-API#1364]
I have looked through examples and Instagram.php in search of metadata tag for Story Link, but couldn't find it...
Does the API supports adding link to story? and if yes - then what metadata key i have to use?
and: i couldn't find the list of available metadata keys :)

**Comment by mgp25** [comment]
@SoleSS link in story works only for business and verified accounts, we are focusing in average users, so wont be added, at least for now.

When i have time ill write them in the wiki, meanwhile you can have a look at the `configure` functions

Regards
