### ISSUE TITLE
A bug with length video

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#1365]
https://instagram.fhen2-1.fna.fbcdn.net//t50.2886-16//19217932_468047713529254_2990439484568371200_n.mp4

This video is longer than a minute by 3 milliseconds. He missed his instagram. ThrowIfIllegalVideoDetails will not miss it. This is a small bug.
Maybe it can be done like this?
$VideoDetails['duration'] > 60.1
or 60.05

**Comment by mgp25** [comment]
@Triden is not a bug. They probably have a tiny range that is still considered valid. You can cut the video length into exactly 60 seconds easily with ffmpeg and then do the upload.

Regards
