### ISSUE TITLE
Enable usertags in Internal::configureSinglePhoto()

### ISSUE THREAD

**Issue by e-ht** [mgp25/Instagram-API#1366]
Would be handy to enable usertag posting for single photo uploads. If I get it working I'll send a pull request.

**Comment by SteveJobzniak** [comment]
Hi. I agree. The problem is that usertags are complex. Users will need to provide an array with user ids and x/y coordinates (in 0-1 float range) for each user. We never settled on a way to document that format. Unfortunately users must provide the ID and the coordinates of where to place the tag.

**Comment by SteveJobzniak** [comment]
We have the src/Request/Usertag.php file which has tagUser, which is the closest thing we've gotten to supporting usertags and socumenting the format.

**Comment by SteveJobzniak** [comment]
Halfway done. Most of the work was creating this function for validating usertag arrays:

https://github.com/mgp25/Instagram-API/commit/9f7b967c677eeeef677906b20005af6b02722855

**Comment by SteveJobzniak** [comment]
Was a bit more work than expected but now we've finally got usertag support when uploading timeline photos. And all places in the code that accepts usertags now validates the data using the new system. It has also become much easier to manually edit media to add tags later. You can just call the Media::edit() function in the same way as Usertag::tagMedia() but with more than one user in the array.

https://github.com/mgp25/Instagram-API/commit/9f7b967c677eeeef677906b20005af6b02722855

https://github.com/mgp25/Instagram-API/commit/1366972d9ae055bec6d750e60ee3d6c61f70f3a7

https://github.com/mgp25/Instagram-API/commit/e6ed3f93916e3855161b149398609e8f3cff0ce9

https://github.com/mgp25/Instagram-API/commit/24d35ede7b0a87c9fa000d401177b1f1a3fc0116

https://github.com/mgp25/Instagram-API/commit/cff077d440dd661eeaa2dc1f4106f274cacd0cfd

https://github.com/mgp25/Instagram-API/commit/5f2e03878ff2e816170660fb68aefba64e06d6f8

https://github.com/mgp25/Instagram-API/commit/39caa4fd216dab2dac2013e4647f42316efa02c4

https://github.com/mgp25/Instagram-API/commit/483ff2c4bf39b8ce26ca79e813d375448704edd0

Please do not use this for spamming.

**Comment by mgp25** [comment]
@SteveJobzniak it will be used for spamming unfortunately.

**Comment by SteveJobzniak** [comment]
@mgp25 :(

**Comment by SteveJobzniak** [comment]
Well, when I think about it... it's Instagram's job to ban users that mass-tag other people. So it's fine. Let them spam and force Instagram to improve their anti-spam detection. ;-) "If user.tagstoomanypeople or user.tagstoooften { ban:SPAM }" ;-)

**Comment by mgp25** [comment]
John Wick is my friend, and I will told him to chase down anyone who spam. Im serious about it

**Comment by SteveJobzniak** [comment]
lol 👍  ⚔️

**Comment by e-ht** [comment]
Lmao at this thread. Thanks Steve you have officially freed up my weekend.

**Comment by SteveJobzniak** [comment]
@e-ht lol, I'm happy to hear that. Spend that time wisely instead. Like drinking beer.
