### ISSUE TITLE
Extract ig_sig_key

### ISSUE THREAD

**Issue by wehmoen** [mgp25/Instagram-API#137]
Hi,

I tried to exract the ig_sig_key with the tutorials from the wiki.

The first way fails with the message:

````
make[1]: Entering directory '/home/wehmoen/Dokumente/arminject-master2'
[armeabi-v7a] Compile++ thumb: hook <= main.cpp
[armeabi-v7a] Compile++ thumb: hook <= hook.cpp
[armeabi-v7a] Compile++ thumb: hook <= report.cpp
[armeabi-v7a] Compile++ thumb: hook <= io.cpp
[armeabi-v7a] SharedLibrary  : libhook.so
[armeabi-v7a] Install        : libhook.so => libs/armeabi-v7a/libhook.so
[armeabi-v7a] Compile++ thumb: injector <= main.cpp
[armeabi-v7a] Executable     : injector
[armeabi-v7a] Install        : injector => libs/armeabi-v7a/injector
make[1]: Leaving directory '/home/wehmoen/Dokumente/arminject-master2'
python test.py
@ Pushing files to /data/local/tmp ...
@ Starting com.instagram.android/.activity.MainTabActivity ...
@ Injection into PID 24379 starting ...
--------- beginning of /dev/log/main
--------- beginning of /dev/log/system
I/LIBHOOK (24379): LIBRARY LOADED FROM PID 24379.
I/LIBHOOK (24379): Found 89 loaded modules.
I/LIBHOOK (24379): Installing 1 hooks.

´´´´

The app is opened but when I logged in successfully nothing happens in the console window.


The second way doesn't work because the download page is unreachable.

Are there other ways to find the ig_sig_key?

**Comment by dubmartin** [comment]
arm inject didn't work for me. I had to go the gikdebug route. And that didn't work as detailed for me either, but with some fiddling it should get the code for you

**Comment by mgp25** [comment]
Not API issue. Well, maybe there are other alternatives to extract it, but the one mentioned in the wiki is the easiest and fastest way

Regards

**Comment by michelank** [comment]
@mgp25 
I'm developing mine app yet, so I'm using the key of this repository. When I put in production I need to use mine key, right?

Is there any limit to use each key? How many accounts could I log-in with it

**Comment by dubmartin** [comment]
From what I understand, the key is specific to the instagram apk.

so instagram app 7.20 has a key, 7.19 has a different key. Thus everyone using the same app version uses the same key, so you can use one key for unlimited users

**Comment by michelank** [comment]
Why they're are extracting the key? Could everyone use the same of the
repository?

On Wed, Apr 20, 2016, 22:55 dubmartin <notifications@github.com> wrote:

> From what I understand, the key is specific to the instagram apk.
>
> so instagram app 7.20 has a key, 7.19 has a different key. Thus everyone
> using the same app version uses the same key, so you can use one key for
> unlimited users
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Instagram-API/issues/137#issuecomment-212692986>
>
-- 
Michel Ank

**Comment by dubmartin** [comment]
> **From what I understand,**

> Could everyone use the same of the repository?
yes

**Comment by dubmartin** [comment]
I just want to emphasise "from what I understand". I may be wrong :)

**Comment by h-2-0** [comment]
@wehmoen 

Did you manage to get the key?

**Comment by mangledbottles** [comment]
@h-2-0 did you check the WIKI first? lol
https://github.com/mgp25/Instagram-API/wiki/Technical-information#extracting-instagrams-signature-key

**Comment by h-2-0** [comment]
@mangledbottles, 
Yes, I have tried two out of the tree techniques.

**Comment by h-2-0** [comment]
@mangledbottles 
Update: As of today I've tried all three techniques unsuccessfully. :/

**Comment by GuilhermeFM** [comment]
Key of version 10.3.2: 5ad7d6f013666cc93c88fc8af940348bd067b68f0dce3c85122a923f4f74b251
Extracted using debugging method.

**Comment by h-2-0** [comment]
@GuilhermeFM! 

That's so awesome!!! Thanks so much. :D

**Comment by mgp25** [comment]
@h-2-0 if it doesnt work to you it because you are unexperienced

Regards
