### ISSUE TITLE
get last shared live video

### ISSUE THREAD

**Issue by itsMoji** [mgp25/Instagram-API#1370]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
### Describe your issue

Hi.
Instagram introduce a new feature a few days ago and it's share live streams to story for next 24 hours. 

https://techcrunch.com/2017/06/20/instagram-live-video-replays/

I've try Account::getCurrentUser() , People::getSelfInfo() and Story::getUserStoryFeed() but the last saved live video doesn't exist.

would you please implement this?

Thanks

**Comment by mgp25** [comment]
We'll eventually add this. If you want an ETA, proabably between today and 9^12 years

Regards

**Comment by SteveJobzniak** [comment]
@mgp25 Just a small note... If you do implement this, let's put it in the Live group. It's on the "story" icon in the app, but it would be kinda weird for us to put it in "Story" since people expect Live-related features in the "Live" request-group.

So something like `Live::getLiveReplays($userId)` would be a logical way to find it (func name of course would depend on the endpoint URL, this is just a suggestion).

**Comment by itsMoji** [comment]
@mgp25 @SteveJobzniak i wanna work on this but i can't capture Instagram endpoints because it's use SSL pinning.
I've worked a lot to bypass it's ssl pinning but haven't any result yet :(
can you help me about this please?

( sorry for my English )

**Comment by zuexo** [comment]
@mgp25 @SteveJobzniak Replays are returned in `feed/reels_tray/` endpoint just like live broadcasts.
As far as I know there is no new endpoints for this. All you have to do is update ig version and sig key.

**Comment by SteveJobzniak** [comment]
@zuexo Cool, thanks a lot for that info. Because of the subscriber feature we can't update the repo's version and key to the latest, but we'll someday get to the required version. In fact, I think we'll soon bump to 10.26.0 because @valga needs it for some features. Perhaps that'll be enough to get replays in tray.

**Comment by itsMoji** [comment]
@mgp25 
@SteveJobzniak 
Hi.
I've extracted the last Instagram signature key (v 10.29.0) and put in the API and live replays now available on ```Story::getUserStoryFeed($userId)```

Can i send a pull request for this (because of subscriber)?

**Comment by SteveJobzniak** [comment]
@itsMoji (deleted message) Thanks, but no. If you do that we'll break our promise to the subscribers that help motivate us to work on this API. It is hard and endless work.

Do not mention your delete message again, or we'll have to take action.

We will eventually get to the replays feature later, in natural progression of time.

**Comment by SteveJobzniak** [comment]
Now available in 10.26.0 update in `dev-master`. It's in reels-tray feed and in ONE of the "get user story feed" functions (there's a comment on that function so that you can find it).
