### ISSUE TITLE
Get Location Feed returns less posts than it should

### ISSUE THREAD

**Issue by Biscuri** [mgp25/Instagram-API#1372]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

### Code:

```
function getByLocation($instagram, $location, $limit, $maxId = null){
    $items = $instagram->getLocationFeed($location);
    $maxid = $items->next_max_id;
    $data = extractPosts($items->items, $location);
    $data = array_slice($data, 0, $limit);
    return $data;
}

function extractPosts($items, $q){
    $data = [];
    foreach ($items as $item) {
        $data[] = [
            'src' => str_replace('http:', '', $item->image_versions2->candidates[0]->url),
            'link' => 'https://www.instagram.com/p/'.$item->code.'/?taken-by='.$q,
            'caption' => $item->caption->text
        ];
    }

    return $data;
}
```

### Parameters:

limit=10
location=161624570580262

### Error, only appears on debug mode:

```
<br />
<b>Fatal error</b>:  Uncaught exception 'JsonMapper_Exception' with message 'JSON property &quot;request_id&quot; does not exist in object of type InstagramAPI\RankedRecipientsResponse' in C:\Users\linceweb\ProjetosLince\webservice\instagram\vendor\netresearch\jsonmapper\src\JsonMapper.php:158
Stack trace:
#0 C:\Users\linceweb\ProjetosLince\webservice\instagram\vendor\mgp25\instagram-php\src\Instagram.php(1851): JsonMapper-&gt;map(Object(stdClass), Object(InstagramAPI\RankedRecipientsResponse))
#1 C:\Users\linceweb\ProjetosLince\webservice\instagram\vendor\mgp25\instagram-php\src\Instagram.php(310): InstagramAPI\Request-&gt;getResponse(Object(InstagramAPI\RankedRecipientsResponse))
#2 C:\Users\linceweb\ProjetosLince\webservice\instagram\vendor\mgp25\instagram-php\src\Instagram.php(160): InstagramAPI\Instagram-&gt;getRankedRecipients()
#3 C:\Users\linceweb\ProjetosLince\webservice\instagram\index.php(89): InstagramAPI\Instagram-&gt;login(true)
#4 {main}
  thrown in <b>C:\Users\linceweb\ProjetosLince\webservice\instagram\vendor\netresearch\jsonmapper\src\JsonMapper.php</b> on line <b>158</b><br />
```

---

There is a lot of irrelevant request logs on debug mode, so I picked only the ones that might be useful, for readability.

### Requests and responses:

```GET:  friendships/autocomplete_user_list/?version=2
â† 429 	 80B
RESPONSE: {"message": "Please wait a few minutes before you try again.", "status": "fail"}

GET:  feed/timeline?rank_token=4829094848_212b91ff-ddd4-4bac-9e85-07f3d21e051b&ranked_content=true
â† 200 	 228B
RESPONSE: {"num_results": 0, "more_available": false, "auto_load_more_enabled": true, "feed_items": [], "is_direct_v2_enabled": true, "next_max_id": null, "status": "ok", "_messages": [{"time": 1498737314.27, "key": "update_push_token"}]}

GET:  direct_v2/ranked_recipients?show_threads=true
â† 200 	 148B
RESPONSE: {"ranked_recipients": [], "expires": 7200, "filtered": true, "request_id": "", "rank_token": "c90efb10-334d-4945-9c6d-c86e503a81b3", "status": "ok"}
```

### Result, when not in debug mode:

> [{"src":"https:\/\/instagram.fssa2-1.fna.fbcdn.net\/t51.2885-15\/s640x640\/e15\/19534538_131841224062850_695797762947547136_n.jpg?ig_cache_key=MTU0NjQyMzkyNzUwMzUwNTI0Ng%3D%3D.2","link":"https:\/\/www.instagram.com\/p\/BV2AF5nAsde\/?taken-by=161624570580262","caption":"Sess\u00e3o itinerante, Bairro Jardim Ac\u00e1ssia."},{"src":"https:\/\/instagram.fssa2-1.fna.fbcdn.net\/t51.2885-15\/e35\/19228394_1919146758367672_5007886301827956736_n.jpg?ig_cache_key=MTU0MDY1MTY2MTg0ODQyMzMzNQ%3D%3D.2","link":"https:\/\/www.instagram.com\/p\/BVhfoYTFyun\/?taken-by=161624570580262","caption":"Atendimento domiciliar pela Secretaria Municipal de Sa\u00fade de Feira de Santana \ud83d\udc75\ud83c\udffc\ud83d\udc75\ud83c\udffc\ud83d\udc75\ud83c\udffc #feiradesantana #fisioterapia"},{"src":"https:\/\/instagram.fssa2-1.fna.fbcdn.net\/t51.2885-15\/sh0.08\/e35\/p750x750\/17817913_1894627517447750_9012871652408557568_n.jpg?ig_cache_key=MTQ4NzM3ODU0MzMxOTM4NDU2OQ%3D%3D.2","link":"https:\/\/www.instagram.com\/p\/BSkOueZFwH5\/?taken-by=161624570580262","caption":"Dia de agradecer por apenas mais uma vit\u00f3ria no futuro maravilhoso que te espera! Importador, comerciante, jogador de futebol,  irm\u00e3o de Leo e agora: ADMINISTRADOR! Cila, voc\u00ea me enche de orgulho! \ud83d\udc68\ud83c\udffe\u200d\ud83c\udf93 #ap\u00f3smuitasl\u00e1grimas #missamaislinda"}]

### Issue:

I'm using GetLocationFeed function to get the posts from the following [location](https://www.instagram.com/explore/locations/274948798/dispensario-santana/)

The problem is, I'm only getting 3 posts, no matter what, but, as we can see on the link, there is a lot more posts the API isn't retrieving.

I got the location external_id using the method searchLocation, wich can be found on Parameters section above.

Also, on debug mode, there is that error and no result, but with debug off, it doesn't display any error, only the result.

Is it normal to get only these 3 posts? Why? Or, if is an code or API issue, I would appreciate a little help.

Thanks in advance.

**Comment by SteveJobzniak** [comment]
This is super old v1.0 code from over a year ago. We do not support it.

Upgrade to dev-master (the soon to be released v3.0 code):

```composer require mgp25/instagram-php dev-master```

**Comment by SteveJobzniak** [comment]
After you have upgraded to dev-master (aka 3.0), and try the code again, please write in this ticket and I will re-open it and help you.

**Comment by mgp25** [comment]
@Biscuri you are using an outdated code. Use latest code from master. Not API issue, you got what the server says.

Regards

**Comment by SteveJobzniak** [comment]
@Biscuri Okay, here's the answers:

1. The error you saw on debug was that your OLD version of the library lacked some properties in the server-response. That was already fixed long ago in the master-version!

2. The latest code still only returns 3 items for that location ID. I tried with both the Instagram location PK (274948798) and the Facebook location ID (161624570580262), and both give the same 3 posts. So yes their server only has 3 posts for that location.

I don't know where the others come from.

Edit: I figured it out... "num_results" is the number "3", but the actual array count in "ranked_items" is 9 items, and there is a next_max_id.

So this is for everyone else: NEVER TRUST "num_results". ;p

Just use next_max_id and loop as much as you want and you will get lots of posts for this location!

**Comment by SteveJobzniak** [comment]
As for your other error: "Code 429 	 80B RESPONSE: {"message": "Please wait a few minutes before you try again.", "status": "fail"}" it means you are flooding their server too fast with too many requests. Stop and `sleep()` more often. Look at our latest paginate example: https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php

In v1.0 of the library it used to auto-retry until the request worked (which was very bad). In v2.0 and newer of this library you can no longer flood Instagram. As soon as you've been throttled by Instagram you will get an error via a Throttled exception and must handle them yourself. So from 2.0+ you must write smarter code with sleep() etc to avoid spamming their server.

Just look at the paginationExample for a good sleep() amount. Yes 5 seconds between page requests. In fact, even that is not enough in many cases (if you let it run for a long time, even 5 seconds will get throttled). Around 6 seconds of sleep between all requests is truly safe.

**Comment by Biscuri** [comment]
Thanks for the analysis @SteveJobzniak. Updated the API to dev-master and refactored the code, everything is working fine now.

**Comment by SteveJobzniak** [comment]
@Biscuri Thanks for your nice message. Almost nobody bothers to say thanks. I am happy the solution worked for you and that you took the time to let me know it was appreciated. :)

**Comment by SteveJobzniak** [comment]
@Biscuri Oh and you may also enjoy this code. It is a function for doing API retries:
https://github.com/mgp25/Instagram-API/issues/1272#issuecomment-303110645
