### ISSUE TITLE
Removing stories

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1373]
Is there a way to remove stories? I was unable to find it, but maybe I missed it haha.
If not, would someone be able to implement this?

**Comment by mgp25** [comment]
Hello @matthijsotterloo, you can delete stories with the same function used to delete normal posts like photos, videos and album

Regards

**Comment by SteveJobzniak** [comment]
@mgp25 Actually, it doesn't work with the media delete function. Try:

`$ig->story->getUserStoryFeed($ig->account_id)` to get the items.

Then `$ig->media->delete()` on the PK or ID of the story item. It will say "ok, media now deleted" or whatever, but the story will still exist in your feed (even after app restart). So I had to delete it with the app instead.

**Comment by mgp25** [comment]
@SteveJobzniak the story is deleted with the same endpoint as the other media. And its the same format as media. PK_UID. 

I have checked it before answering @matthijsotterloo

**Comment by SteveJobzniak** [comment]
@mgp25 Hmm sorry, you were right! I suppose they were caching my story reel from my last app start. But actually checking the endpoint itself reveals that the reel media IS removed this way.

```php
    //$ig->story->uploadPhoto('cat.jpg');
    $res = $ig->story->getUserStoryFeed($ig->account_id);
    $item = $res->getReel()->getItems()[0];
    $id = $item->getId(); // format: "154805584592833_12345"
    $ig->media->delete($id, 'PHOTO');
    $res = $ig->story->getUserStoryFeed($ig->account_id); // no longer has the media!
```

@matthijsotterloo See the code above for how to remove story media!

**Comment by matthijsotterloo** [comment]
@SteveJobzniak Thanks! I assume that `PHOTO` will become `VIDEO` when it's a video/boomerang right?

**Comment by SteveJobzniak** [comment]
@matthijsotterloo The possible values right now are `PHOTO` and `VIDEO` and `ALBUM`, as the parameter description says. Use them in that way. Or just use $item->getMediaType() to let it detect automatically.

`$ig->media->delete($item->getId(), $item->getMediaType());`
