### ISSUE TITLE
No request for Photos of me (Tagged of me)

### ISSUE THREAD

**Issue by wondersoftwares671** [mgp25/Instagram-API#1374]
First all, Thank you very much for these api's. It helps me a lot. But i can't find request URL for getting 'Photos of Me'(Tagged of me Photos) and for other users. Please provide me request url that would be more helpful to me. Thank you again for this great work. 
Have a nice day!

**Comment by mgp25** [comment]
@wondersoftwares671 actually is so easy to find it, that i will let you search it for yourself:

https://github.com/mgp25/Instagram-API/tree/master/src/Request

If you are on windows/linux you can use (ctrl + f). In case you are a macOS user, you can use (cmd + f).

It's pretty intuitive, everything is organized in groups so it wont take you more than 5 minutes.

Regards

**Comment by wondersoftwares671** [comment]
Hi, Thank you for your quick response. I tried to find this function in almost all files. 
I found Liked, Saved, Feeds, HashTags and everything but unable to find function for getting media tagged of me.
As i can get liked media by this url request,
`public function like(
        $mediaId)
    {
        return $this->ig->request("media/{$mediaId}/like/")
            ....
    }`
Same as above I want to get post of people tagged me in post. So please suggest me the link. I've already seen every function in every files. and also tried myself by requesting,
`"media/{$mediaId}/tagged/",
"media/{$mediaId}/photosofme/",
"/user/USERID/tagMedia/" and more i don't remember`.
Please suggest me correct url. 
Thank you. You doing great!

**Comment by mgp25** [comment]
You arent searching further enough

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Usertag.php

**Comment by wondersoftwares671** [comment]
OMG! is this function "getUserFeed" what i am looking for?
