### ISSUE TITLE
InboxV2 issue with unseen messages [2]

### ISSUE THREAD

**Issue by CashCode** [mgp25/Instagram-API#1375]
Same issue that in https://github.com/mgp25/Instagram-API/issues/1360
It's not solved:
1. unseen_count shows strange count of unread messages, it doesn't seems to be equal to the number in right top corner in the app.
2. how to know which one is read? You might read the top one thread and the others (old ones) would be not read.
For example, attached screen of inbox. Let's guess it shows 1 unread message. How should I know it's second one or first one from top? It's sorted by time, not by read. 
<img src="https://user-images.githubusercontent.com/8258294/27758111-eaff2318-5e15-11e7-9599-a2c7314bbb1c.jpg" width=200>

**Comment by mgp25** [comment]
@CashCode i have never checked that, and it took me 1 minute to realize how its checked by looking at the response. Please, take your time to see the response, and what differences are between each thread. If you need a better way to see the response use http://jsoneditoronline.org/

1. `unseen_count`: number of unread threads.
2. Please check the response, its easier to check it than opening a new issue

```php
$i->direct->getInbox();
```

Regards
