### ISSUE TITLE
Real time comments subscription

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [mgp25/Instagram-API#1376]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Is there any way to subscribe to comments in realtime client.
I've tried 
```php
    $ig->setUser($username, $password);
    $ig->login();
    $ig->push->setPreferences(['comments' => 3]);
```
before instantiating a loop, but it does not make any difference.
i log all received events - there is nothing connected to comments in it.

**Comment by valga** [comment]
> Is there any way to subscribe to comments in realtime client.

No, because Instagram uses Realtime only for Direct and Live.

**Comment by Vasiliy-Bondarenko** [comment]
@valga, ok, but how instagram on android gets immediate notifications about comments? some other mechanism? if so - why?

**Comment by mgp25** [comment]
Back in the day they were using GCM - https://developers.google.com/cloud-messaging/

These services are used by many companies, like WhatsApp, used for push notifications.

I dont know if Instagram is still using something based on Google CM

**Comment by Vasiliy-Bondarenko** [comment]
I've tried to detect some requests in proxy. I blocked all requests to *.facebook.* 
And i still got notification about new comment. So apparently - yes. GCM or FCM is used. the question is - how we can hook in to it and get those comment notifications?

I've tried to find some kind of PHP FCM package, but with no luck yet. I've found packages only for sending messages, but not for receiving. But i'm pretty sure it must be possible. 

Do you have any idea?

**Comment by SteveJobzniak** [comment]
@Vasiliy-Bondarenko GCM = Google Cloud Messaging. It's Google's system for android OS/app notifications. To get those notifications you must have their Android app ID and subscribe to Google's notification server via Instagram's server and associate your fake-Android notification receiver with your Instagram account.

We will not implement this so don't ask anymore. It has nothing to do with Instagram's API.

**Comment by valga** [comment]
@Vasiliy-Bondarenko It is ready for tests: #1459.
