### ISSUE TITLE
Incorrect timestamp on directThread

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1377]
Hi,

Not sure if this is a bug in the API or a bug in the response from Instagram but when using the following code:

```
$direct = $ig->direct->getInbox();
$threads = $direct->inbox->threads;

foreach ($threads as $thread) {                                 
	$thread_fetch = $ig->direct->getThread($thread->thread_id);
	
	foreach($thread_fetch->thread->items as $item) {
		var_dump($item->timestamp);
	}
}
```

The timestamp is not in the usual unix timestamp format like the other timestamps the API returns, I have this feeling that it's not the timestamp that's being returned but some kind of `id`. Any clue what could be the problem here?

**Comment by mgp25** [comment]
All values returned are dirctly from Instagram server, we dont manipulate anything, so what you get is what Instagram is sending.

Timestamps are correct.

1498899595267023 = 1498899595.267023 secs

Regards
