### ISSUE TITLE
Uncaught Error: Class _Message not found

### ISSUE THREAD

**Issue by pascalbros** [mgp25/Instagram-API#1378]
Hi guys,
I think this is a stupid question but I don't know how to solve it.

I installed Instagram-API with `composer install` and everything went fine, then I tried to run an example: accessingValues.php and what I get is this error message:

```Fatal error: Uncaught Error: Class '\InstagramAPI\Response\Response\Model\_Message' not found in /Users/pascal/Projects/instagram/vendor/netresearch/jsonmapper/src/JsonMapper.php:544 Stack trace: #0 /Users/pascal/Projects/instagram/vendor/netresearch/jsonmapper/src/JsonMapper.php(376): JsonMapper->createInstance('\\InstagramAPI\\R...') #1 /Users/pascal/Projects/instagram/vendor/netresearch/jsonmapper/src/JsonMapper.php(265): JsonMapper->mapArray(Array, Array, '\\InstagramAPI\\R...') #2 /Users/pascal/Projects/instagram/src/Client.php(569): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\TimelineFeedResponse)) #3 /Users/pascal/Projects/instagram/src/Client.php(797): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\TimelineFeedResponse), Object(stdClass), Object(GuzzleHttp\Psr7\Response)) #4 /Users/pascal/Projects/instagram/src/Client.php(883): InstagramAPI\Client->_apiRequest('POST', 1, 'feed/timeline/', Array, Array) #5 /Users/pascal/Projects/instagram/src/Request.php(292): Instagram in /Users/pascal/Projects/instagram/vendor/netresearch/jsonmapper/src/JsonMapper.php on line 544```

The _Message class exists and is in place, how can I solve this issue?

Thanks

**Comment by mgp25** [comment]
@pascalbros it works perfectly. Make sure your setup is correctly.

```
composer require mgp25/instagram-php dev-master
```

Regards

**Comment by SteveJobzniak** [comment]
I also verified this now just to be sure. `accessingValues.php` works perfectly in the latest dev-master.

**Comment by SteveJobzniak** [comment]
I also wondered why you got this error. So I checked v2.0's tree, and checked TimelineFeedResponse. But it looks fine (it refers to `@var Model\_Message[]` which was correct). So I have no idea why your code is trying to load `'\InstagramAPI\Response\Response\Model\_Message'`. (Note the double `Response\Response\` path)... Weird. Delete your `vendor` folder and reinstall the `dev-master` version of this library.

**Comment by SteveJobzniak** [comment]
Sorry, I just realized what the bug is. It is a problem with JSONMapper. I will fix it tomorrow when I wake up.

**Comment by SteveJobzniak** [comment]
@pascalbros Fixed:

https://github.com/mgp25/Instagram-API/commit/2ac1c01588e22736c60dc0d64f8dd15a3f041a99
