### ISSUE TITLE
[Review] Need review of the new media location editing feature

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1379]
I just changed `Media::edit()` to take a metadata array, so that we can support multiple types of edits later:

https://github.com/mgp25/Instagram-API/commit/3ed7d7e0b2c56fea2dbf58635e58feb184466eea

Then, I added support for location editing:

https://github.com/mgp25/Instagram-API/commit/b27189ffea566c9910c7e8f98bbc024af9f1c54b

It works, but there are two problems that need to be checked:

1. Compare against the real photo + video + album "edit location" requests of the official app, to be sure this data is being sent correctly for all 3 cases.
2. Implement the "remove location" API call the same way as the app. Right now I added a `die()` call to exit execution if someone tries to send `false` to remove the location.

**Comment by mgp25** [comment]
@SteveJobzniak 

1. So far seems good. I'll do a further research this weekend, but its okay.
2. Added.

**Comment by SteveJobzniak** [comment]
@mgp25 

1. Okay sounds good. And yeah it works so far!
2. Perfect, thanks for the quick fix. Removing location works now!
