### ISSUE TITLE
sendLink() don't working

### ISSUE THREAD

**Issue by marwel06** [mgp25/Instagram-API#1380]
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php
in this file, sendLink() don't working. Hashtag, profile, text working but sendLink function don't working. Please update.

**Comment by SteveJobzniak** [comment]
"sendLink don't working" is code language for "It works, but Instagram has detected spam links from this guy and blocks this fucker's account so he cannot send his spam-links".
