### ISSUE TITLE
Login takes forever, is it normal?

### ISSUE THREAD

**Issue by renang** [mgp25/Instagram-API#1381]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

I'm new to the API e could not find an answer to this anywhere. When I call setUser and then login, it seems to work, but it takes a very long time! Probably 20 minutes or so. Am I doing something wrong, or missing a configuration somewhere? Or is that behavior to be expected? Thanks.

**Comment by mgp25** [comment]
Not API issue, probably your connection or proxy.

Regards

**Comment by SteveJobzniak** [comment]
For other people's info in the future: A full login should take maybe 5 seconds. A resume should take maybe 1-2 seconds. So no it's not normal, but it's not our API. Something about your connection.

**Comment by renang** [comment]
Thanks for the response. I've tried on two completely different networks, and the same happens. Any suggestions on what I could look at? It works, but it takes a very long time.

**Comment by SteveJobzniak** [comment]
Run with debug=true, look at what it gets stuck at. Also edit our vendor/mgp25/instagram-php/src/Client.php file to chnage its "new GuzzleClient" call to enable debugging in guzzle to see all network traffic. Good luck.
