### ISSUE TITLE
deleteItem

### ISSUE THREAD

**Issue by CashCode** [mgp25/Instagram-API#1382]
1) How about adding "thread delete" option?
deleteItem() works only with small items.
2) Few functions have 'unseen count' field. But which one is original right top corner?
Sometimes I dont need full inbox, only want to know is there new messages or not.
Regards :+1:

**Comment by mgp25** [comment]
@CashCode 

1. we'll be adding features everytime we can. No ETA.
2. Check this: https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php
+ Duplicate. This has been answered in a previous issue.

Regards
