### ISSUE TITLE
Blocking Risk

### ISSUE THREAD

**Issue by erfansahaf** [mgp25/Instagram-API#1389]
First of all, I'm sorry for asking this question in Issues.
I just wanted to know is there any possibility to get blocked by the Instagram because of working with Instagram through Orginal APIs, not Developers APIs?

Thanks for your spending time on this awesome package.

**Comment by mgp25** [comment]
Hello, Instagram will only block if you spam. If you dont spam you will be okay

Regards

**Comment by erfansahaf** [comment]
Nope, I won't spam but maybe I would work with a couple of accounts with same IP address.
Is that ok?

**Comment by erfansahaf** [comment]
@mgp25 Could you answer my last question, please?

**Comment by SteveJobzniak** [comment]
@erfansahaf From what I've read: 2-3 accounts on your IP is ok. 5 or more = bad.

**Comment by erfansahaf** [comment]
@SteveJobzniak This package or GuzzleHttp package has any option to set proxy for work with 5 or sometimes more than 5 accounts?

**Comment by mgp25** [comment]
Read wiki, search in issues. That has already been answered.

**Comment by SteveJobzniak** [comment]
Yes this package can set proxy. Look in src/Instagram.php.

**Comment by erfansahaf** [comment]
@mgp25 @SteveJobzniak Thanks, I found it.

**Comment by erfansahaf** [comment]
@SteveJobzniak @mgp25 Later.com posted an article on their blog that says using of reversed APIs increases account blocking risk: 
https://later.com/blog/auto-post-to-instagram

Have you read that? Is that true?
Excuse me for keep asking questions about blocking, I'm worried about my accounts a little bit.

**Comment by mgp25** [comment]
As i said the other day:
>Hello, Instagram will only block if you spam. If you dont spam you will be okay
Regards

And if you are so worry, create a test account and test it yourself

Regards

**Comment by SteveJobzniak** [comment]
@erfansahaf Instagram will know that you are using the reversed API, yes. They can detect it. And they will increase monitoring of all accounts that use it.

But as long as you don't spam, you have nothing to worry about.

Good luck. This ticket is now closed.
