### ISSUE TITLE
Links in direct Message

### ISSUE THREAD

**Issue by albrox** [mgp25/Instagram-API#1395]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

$ig->directMessage($idOfUser, "http://www.google.com");

### Describe your issue
When sending a direct message, which includes a link, the link is not clickable, as it would be normally when using the app itself. I think it might be that the code does not catch the preview, as the app would normally do?

**Comment by mgp25** [comment]
Duplicate: https://github.com/mgp25/Instagram-API/search?q=Links+in+direct&type=Issues&utf8=%E2%9C%93

**Comment by SteveJobzniak** [comment]
@albrox Also note that you are not sending the link like a link. You are sending it as a text message! You are calling `directMessage()` from the old 2.0 API.

Upgrade to dev-master API (3.0), via the instructions in README.md.

Then use `$ig->direct->sendLink()` instead.

**Comment by SteveJobzniak** [comment]
Update for future readers: We removed the `sendLink()` function. Instead, the regular `sendText()` now detects all links in your text message and sends them as links automatically. So just use `sendText()`.
