### ISSUE TITLE
Not being able to access functions in Direct.php

### ISSUE THREAD

**Issue by albrox** [mgp25/Instagram-API#1396]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hi, sorry this could be a really basic and noob question. But I am am unable to access the functions in the Direct.php.

I have in initialized the API, everything is working fine. Commenting, Posting, etc. 

Initilalized like this:
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
	
	##login
	try {
	    $ig->setUser($accountUsername, $accountPassword);
	    $ig->login();
	} catch (\Exception $e) {
	    echo 'Something went wrong99: '.$e->getMessage()."\n";
	    exit(0);
	}

But when trying to access a function from the Direct.php, such as: sendLink(), it seems like it is not available:
"Undefined property: InstagramAPI\Instagram::$direct"

I tried to access the function like this: $ig->direct->sendLink();

Is there a working example of one of the functions in the Direct.php? Thank you very much.

**Comment by mgp25** [comment]
Duplicate: please search in recent closed issued. Thias has been answered many times

**Comment by albrox** [comment]
I have not found an issue addressing the integration of the Direct.php file. Sorry. This is why I asked, if someone might have a working example. I think I am doing something completely wrong maybe. Totally appreciating this great repo and your work here, but people might have different levels of understanding and some needing more help than others

**Comment by mgp25** [comment]
Are you sure you havent searched in recent issues? Sigh...
#1394

**Comment by SteveJobzniak** [comment]
I am so tired of all these tickets (like 10 so far) always trying examples from the web-folder, not from their own vendor/mgp25/instagram-php/examples folder.

A few weeks ago I put a big "**WARNING, PLEASE READ**" in the "examples" folder on the web (scroll down): https://github.com/mgp25/Instagram-API/tree/master/examples

But it doesn't seem to have helped much. Perhaps we should move the warning to above the "Examples" header? But somehow I doubt they would read anyway.

**Comment by albrox** [comment]
@SteveJobzniak I totally get how you feel and I bet I would feel the same. On the other hand, your repository seems to be very popular :) 
I was not able to find any example (dev-master) that addresses the direct.php (have searched through all of them) and @mgp25 : I can unfortunately not see, how #1394 relates to this, as it is also not addressing the direct.php

I have installed the latest dev-master. I am using that call:
`$ig->direct->sendLink( $userid, $text);`

I receive:
`Undefined property: InstagramAPI\Instagram::$direct`

besides that, the code seems to work. F.e.: `$ig->directMessage($userid, $text);` is working

**Comment by mgp25** [comment]
Man, you need to use composer to get dev-master, you havent read the readme! for gods sake...

**Comment by SteveJobzniak** [comment]
Update for future readers: We removed the `sendLink()` function. Instead, the regular `sendText()` now detects all links in your text message and sends them as links automatically. So just use `sendText()`.
