### ISSUE TITLE
Stories in location feed

### ISSUE THREAD

**Issue by Azureit** [mgp25/Instagram-API#1397]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

With this new instagram version, the endpoint feed/location/{$locationId}/ now has stories for that location that are not handled in Response\LocationFeedResponse.
This endpoint will give the latest 20 unseen stories, somehow we need to mark the stories as seen and then call the endpoint again to get the other stories, and it is not with the 'media/seen/' endpoint like we do in usual stories.
I don't have a new instagram version with the certificate pinning disabled to discover this. :(

Regards

**Comment by mgp25** [comment]
Added compatibility: https://github.com/mgp25/Instagram-API/commit/874e3f2045e20bdf70b09f752ee3c9cfaf8425ef

**Comment by DobrinAlexandru** [comment]
@Azureit You said that "With this new instagram version, the endpoint feed/location/{$locationId}/ now has stories for that location that are not handled in Response\LocationFeedResponse."

Can you give me an example for getting the latest 20 stories from Instagram location (based on new instagram version). I have spent days in a row and no luck so far

**Comment by BTopbas** [comment]
Hi;
I use this code to retreive story users of location. But cant mark as seen. Everytime retrive same stories. In application i viewed and refreshing new stories. If no new story in location stories not appear.

`$location = $i->location->getFeed("112768952070470");
$stories = $location->story->items;
foreach ($stories as $story) {
    //print_r($story);
    echo $story->user->username;
    echo "</br></br>";
}
$i->story->markMediaSeen($stories);`

This code i retrive usernames of location stories but can't marks as seen.

**Comment by niranjanshr13** [comment]
@BTopbas did you find a way to mark as seen. I am also stuck there.
