### ISSUE TITLE
How To Fix 400 Bad Request?

### ISSUE THREAD

**Issue by ntanfp** [mgp25/Instagram-API#1398]
First of all, I'm sorry for asking this question in Issues.
I'm Get error in like a photo
{"message": "Please update your Instagram app to continue liking photos", "status": "fail"}
how to fix this ?

Thank you

**Comment by Skylerz** [comment]
hi can you post your whole code here ? i am using the api now and its still working

**Comment by szokeptr** [comment]
You are probably using an older version of the API, with old constants.

**Comment by mgp25** [comment]
Sorry if im rude but,

How to read wiki and recent issues? Please how can i fix my issue
