### ISSUE TITLE
Stories in hashtag feed

### ISSUE THREAD

**Issue by Azureit** [mgp25/Instagram-API#1399]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

This is easy :) exactly like with location feed stories.
With this new instagram version, the endpoint feed/tag/{$urlHashtag}/ now has stories for that hashtag that are not handled in Response\TagFeedResponse.

As a side note, they didn't remove the nuxes from the function markMediaSeen
Tested with 10.28.0, it's like this:
"_csrftoken": "xxxxxxxxxxxxxxxxxxxxxxxx",
"_uid": "xxxxxxxxxxxx",
"_uuid": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
"nuxes": {},
"reels": {
	"xxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxx": [
		"xxxxxxxxxxx_xxxxxxxxxxx"
	],
	"xxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxx": [
		"xxxxxxxxxxx_xxxxxxxxxxx"
	],
	"xxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxx": [
		"xxxxxxxxxxx_xxxxxxxxxxx"
	],
	"xxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxx": [
		"xxxxxxxxxxx_xxxxxxxxxxx"
	]
},
"live_vods": {}

Regards

**Comment by mgp25** [comment]
@Azureit support was added in latest commits, please check. This was answered in other issue.

That was took in the latest version, still okay for this version.

Regards
