### ISSUE TITLE
Empty response 

### ISSUE THREAD

**Issue by sergey-tyan** [mgp25/Instagram-API#14]
I'm getting empty response after trying to upload a photo using uploadPhoto.php. Wiki says that IG_SIG_KEY is required. Does this mean, that using your IG_SIG_KEY (c1c7d84501d2f0df05c378f5efb9120909ecfb39dff5494aa361ec0deadb509a)  causes this empty response?

**Comment by mgp25** [comment]
@sergey-tyan if you check that script, `debug` is set to `false` so you wont see any output, the photo should be uploaded already (check your account). If you set `debug` to `true` you will see all requests/responses.

Please take a look at the wiki, there is explained everything.

Regards
