### ISSUE TITLE
Outdated API Response

### ISSUE THREAD

**Issue by francnuec** [mgp25/Instagram-API#140]
So I tried the api and got this response at login:

`{
  "status": "fail",
  "message": "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram."
}`

Could the API be different now?

**Comment by BurakDev** [comment]
https://github.com/mgp25/Instagram-API/wiki/Technical-information

Maybe Signature Key have changed

**Comment by francnuec** [comment]
Yeah. I think the signature key has changed. But apart from that, it seems the CRSF token is now included with the json data posted to the login endpoint.

Here's what I got through fiddler:

`signed_body=409b7258f59ea410316024c4c860a69d1625b41bcb056f3477975c00e7643f73.%7B%22phone_id%22%3A%22c60176d7-e2d4-4396-bc1b-fdac7ac21389%22%2C%22_csrftoken%22%3A%229cebfeb4a9c2ba22c2e59bdd134af326%22%2C%2C%22guid%22%3A%224f85a48f-4663-4e43-bc7c-7f7e1f59af1b%22%2C%22device_id%22%3A%22android-2382c02373e9e53e%22%2C%2C%22login_attempt_count%22%3A%220%22%7D&ig_sig_key_version=4`

So I removed the username and password fields, but notice the _crsftoken field? That just got included in android version 7.20.0.

**Comment by BurakDev** [comment]
Where you get the version error message ? I just coded a script unfollowing all users not following me back and it work's

**Comment by francnuec** [comment]
Wow. Maybe I'm the problem then.

I had to translate the entire code to c# as I don't use PHP much. So maybe I made an error somewhere. Would try and find it out.

I'm thinking the problem might be with the hashing part.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/commit/6d3a6bd90df4ed6e66cc6bc980045c71cdf62f46

**Comment by BurakDev** [comment]
Thanks @mgp25 ! :+1:
