### ISSUE TITLE
Error while creating Instagram instance

### ISSUE THREAD

**Issue by Vshri** [mgp25/Instagram-API#1402]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---
## Example Code:

require 'Instagram/vendor/autoload.php';

class Rialbase_Social_Instagram {
    private static $_instance   = NULL;
    private static $_INSTAGRAM  = NULL;
    public static function getInstance() {      
        try {
            if (self::$_INSTAGRAM === NULL) {
                $config     = Rialbase_Core::getConfig();
                $igConfig   = $config->instagram;   
                
                self::$_INSTAGRAM = new \InstagramAPI\Instagram($igConfig->debug, $igConfig->truncated);

            }
            if (self::$_instance === NULL) {            
                self::$_instance = new Rialbase_Social_Instagram;
            }
            return self::$_instance;            
        } catch (Exception $ex) {
            Rialbase_Core::getLogger()->debug(__METHOD__ . '::' . __LINE__ . ' EXCEPTION : ' . $ex->getMessage());
            throw $ex;
        }
    }
}

## Error Log/var_dump:
 The "/var/www/html/guesture/web/library/Instagram/vendor/mgp25/instagram-php/src/../sessions/" folder is not writable.

```

---
Hi,

I have installed api using composer,
below is my folder structure

web
  |-Rialbase
  |     |-social
  |           |-Instagram
  |-library
       |-Instagram
             | -vendor

 i am using Zend MVC Framework when i create instance i am getting the above error log, i cannot find sessions folder, Please help me out.


Thanks

**Comment by unusorin** [comment]
But what happens if the library is packaged inside a phar file?

**Comment by SteveJobzniak** [comment]
@unusorin Hi! We don't support phar files. Your best chance is to read `examples/customSettings.php` and use that method to provide a different file location (or storage backend) to store your user-settings. But I don't know if that's gonna be enough, because we may use folder paths elsewhere too. We're not going to rewrite the library to add phar support if this doesn't work.

**Comment by unusorin** [comment]
So, this is the explanation for not using a temp dir or something similar for sessions and instead using current dir? "Rewriting the hole lib to add phar support" that's funny!

**Comment by SteveJobzniak** [comment]
@unusorin Sessions are insanely important. Instagram bans you if you create too many sessions (they count amount of device ID logins per account). We will not store them in some dumb temp dir where they may get deleted.

Read the example and change your settings path and good luck.
