### ISSUE TITLE
Access reel of location story

### ISSUE THREAD

**Issue by jimmyt2003** [mgp25/Instagram-API#1407]
Is it possible to get the story of a location. When a few people post a story in a similar location I am trying to get the feed of that story. I cannot see it in the list of end points.

Example is this New York one:
![alt text](https://tctechcrunch2011.files.wordpress.com/2017/05/instagram-location-stories-explore.jpg?w=680&h=411 "New York")

Thanks in advance!

**Comment by mgp25** [comment]
@jimmyt2003 Yes, was implemented few days ago. Please, next time consider reading closed issues or pushed commits.

#1397
