### ISSUE TITLE
UploadPhoto Error ig_sig_key

### ISSUE THREAD

**Issue by RedGhostMe** [mgp25/Instagram-API#141]
RESPONSE: {"status":"ok","upload_id":"1461303949553"}

REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=9e49756b60771f8fa1d2f5539a5078056001f23f4d1642d4f85dd0fda9317d45.
RESPONSE: **{"status":"fail","message":"Please update your Instagram app to continue posting photos"}**

REQUEST: qe/expose/
DATA: ig_sig_key_version=4&signed_body=20a5fa4ac5a6b8d6a55dc9351ef631b4e8819d11472e5661b0f4f43f80db8370.{"_uuid":"f219cc2f-18ab-48f7-b50e-3ef3d83c9e35","_uid":"3105500838","id":"3105500838","_csrftoken":"deb9f31e065f443ee7e1bd0c72d43047","experiment":"ig_android_profile_contextual_feed"}
RESPONSE: {"status":"ok"}

Hello. Can you fix this please?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/commit/6d3a6bd90df4ed6e66cc6bc980045c71cdf62f46

**Comment by RedGhostMe** [comment]
????
this fix is not fix upload photo

**Comment by RedGhostMe** [comment]
I wrote a result with this version 7.19.1 and 6d3a6bd

**Comment by RedGhostMe** [comment]
????
this fix is not fix upload photo
I wrote a result with this version 7.19.1 and 6d3a6bd
