### ISSUE TITLE
Backup Bug

### ISSUE THREAD

**Issue by rudemex** [mgp25/Instagram-API#1410]
Hi guys, how are you?

I was testing the backup () function and it returns an error when it is video.
The console returns this to me.

`PHP Fatal error:  Call to a member function getUrl() on null in /Users/mex/..../deploy/vendor/mgp25/instagram-php/src/Instagram.php on line 2901`

If I find the fix to the bug, I'll let them know.

Regards!

**Comment by rudemex** [comment]
Ok, I found what the problem, in the function only define 2 types of files, photos or video, but they are not defining if it is carrousel.

I'm going to dig a little to see how to solve it.

Regards!

**Comment by mgp25** [comment]
@rudemex you are using an outdated code

**Comment by rudemex** [comment]
@mgp25 That strange, I made a composer update, delete the dependency of the json, and I reinstalled, and igue giving me the same error, this you tell me, is in l version dev? Or in the stable?


Thanks

**Comment by mgp25** [comment]
**README:** `composer require mgp25/instagram-php dev-master`

**Comment by rudemex** [comment]
sorry, but not work :/

Change the stable version 2.0 to the dev-master, but it returns an error

PHP Fatal error:  Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in /Users/mex/.../deploy/vendor/mgp25/instagram-php/src/Request.php on line 166

Look for what that line says, and it's because of the set-up constant of the version. If I force a version, I get the login, but not the backup of my account.

Regrads!

**Comment by SteveJobzniak** [comment]
@rudemex I remember this kind of error. It means you are using PHP 5.5 (or was it 5.4?) or older. They did not support isset() and empty() etc on expressions.

This library requires PHP 5.6 or newer. Even if you are running "composer require ..." as a PHP 5.6+ process, your actual PHP web process is outdated.

This is an issue with your web host configuration. Invalid.

**Comment by SteveJobzniak** [comment]
@rudemex Turns out this was not related to the old `empty()` bug. A recent commit added an `isset()` around a constant which is apparently only supported in PHP7+. It has been fixed now in #1411.

**Comment by rudemex** [comment]
hi @SteveJobzniak 

I have php 5.6, I did a test on the update they did on #1411 , I managed to login, but it does not seem to work all the rest, upload image, get info from a user, etc.

**Comment by SteveJobzniak** [comment]
@rudemex I see, you went from `2.0` to `dev-master (aka 3.0)`. All functions have been grouped now and you'll have to check all of your class-calls.

Look in the `examples/` folder for the new way to call funcs. And look in `src/Request/...` for all of the different functions. You'll find everything there, but with new names.

**Comment by rudemex** [comment]
ahhhhh ok, thanks @SteveJobzniak I'll check and let you know, thank you very much!

**Comment by rudemex** [comment]
@SteveJobzniak @mgp25 @valga  thanks guys!! its aliveee!!


I had forgotten that in the dev version, they had changed the calls, which made it easier to use them.
I do not know why my happened to the stable ... hahaha

If I find another bug, I'll let you know, thank you very much for everything !!

**Comment by SteveJobzniak** [comment]
@rudemex Hehe happy to hear that! 👍 :)
