### ISSUE TITLE
Do you keep The Devices Id?

### ISSUE THREAD

**Issue by inibah97** [mgp25/Instagram-API#1413]
I feel that this app does not keep Device Id, Which I think Device Id is an identity used by instagram to ensure that their users are valid.

195:Instagram.php 💯 $this->settings->set('device_id', Signatures::generateDeviceId());

I see that every time I make a request on this code it will use the new device id, and that's bad enough in my opinion.

What is your opinion?

**Comment by inibah97** [comment]
And I look at the data storage for the mysql, There is no place to store the device id and means you do not save the device id. I really need your opinion.

**Comment by mgp25** [comment]
@inibah97 it seems you havent read the wiki or anything in the code. Yes, we keep them
