### ISSUE TITLE
Recording live

### ISSUE THREAD

**Issue by pishnok** [mgp25/Instagram-API#1415]
Hi do not be tired,
 
How can I Recording live ?

**Comment by aitte2** [comment]
@mgp25 Omg what is going on? Github is bugging AGAIN!!! Look at these dates of these totally new tickets, lol

![github-bug](https://user-images.githubusercontent.com/18485256/36356659-49a8a1b4-14f5-11e8-8132-09b0040fb293.png)

@pishnok https://github.com/mgp25/Instagram-API/issues/1713 https://github.com/mgp25/Instagram-API/issues/1704 https://github.com/mgp25/Instagram-API/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+record+

**Comment by valga** [comment]
@aitte2 It turned out that GitHub has shadow ban too.
