### ISSUE TITLE
Check if user follows me

### ISSUE THREAD

**Issue by projectbetaalpha** [mgp25/Instagram-API#142]
I've been trying to find out the endpoint for checking if a user is following me. Don't have a rooted device so can't sniff network activity. I've checked the official API docs but endpoints are not the same, so I haven't been able to "extrapolate".
My only idea is getting all the user followers and loop through the array checking for my own userId, but I believe there has to be a better way to do the job.
If any of you guys know or can find out the endpoint I'd be happy to code the method and open a PR.
Cheers!

**Comment by mgp25** [comment]
request info about an user and it should tell you

regards

**Comment by Mrp12** [comment]
can we know with `friendship_status` array?

for example: output of `friendship_status` with this result:

```
{
"following":true,
"outgoing_request":false,
"is_bestie":false
}
```
