### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by AliKhaleghi** [mgp25/Instagram-API#1421]
Hi, I've been struggling with Two Factor Authentication, somehow I just can't get it to work.

		if(TwoFactorAuthentication)
		{
			/*
			*	$this->instagram->ig = function($debug=false,$trun_d=false){
			*	$ig = new \InstagramAPI\Instagram($debug, $trun_d);
			*	$ig->setVerifySSL(false); 
			*	return $ig;
			*	}
			*/
			$ig = $this->instagram->ig(true);
			try {
				
				$ig->setUser($this->input->post('ig_username'), $this->input->post('ig_password'));

				$loginResponse = $ig->login();

				if (!is_null($loginResponse) && $loginResponse->getTwoFactorRequired()) 
				{
					$twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();
					$_SESSION['twoFactorIdentifier'] = $twoFactorIdentifier;
					$ig->twoFactorLogin($verificationCode, $twoFactorIdentifier);
				}

			} catch (\Exception $e) 
			{
				
				switch ($e->getMessage()) {
					// I do not understand this response.
					case '.':
						echo 'proceed';
						break;
					case 'Please wait a few minutes before you try again.':
						echo 'wait';
						break;
					
					default:
						print_r($e->getMessage());	
						break;
				}  
			}
		}
whatever i try to do, doesn't work since the `$ig->login()` throws an `Exception` so the rest of the code which contains the `$twoFactorIdentifier` wont get executed so i can use it later on.
anyone facing my situation or faced and solved it ?

Any kind of help would be highly appreciated .

**Comment by AliKhaleghi** [comment]
The `TwoFactorAuthentication` condition is just a checkbox which my user would check if the instagram account has `Two Factor Authentication` on, as you could guess.

**Comment by SteveJobzniak** [comment]
1. You are misusing twoFactorLogin, you must use the code given to the user via SMS.
2. Search closed issues for two factot login.
