### ISSUE TITLE
getting stories fatal error

### ISSUE THREAD

**Issue by vallez01** [mgp25/Instagram-API#1424]
hai, 
i try to facth stories( video/images) for someuser.
 
but i getting this error

Fatal error: Call to undefined method InstagramAPI\Instagram::UsernameId
Fatal error: Call to undefined method InstagramAPI\Instagram::UserStoryFeed()

login = sucess

i use this code

`set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

/////// CONFIG ///////
$username = 'xxxxx';
$password = 'xxxxx';
$debug = true;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram();

$ig->setUser($username, $password);
$ig->login();

$userId = $ig->UsernameId('user');
$ig->UserStoryFeed($userId);

`

**Comment by solomax2014** [comment]
$userID = $ig->people->getUserIdForName('user');
$feed = $ig->story->getUserStoryFeed($userID);

**Comment by vallez01** [comment]
halo it works fine , thank you..
where i can see documentation for use some function like '->people->getUserIdForName' or '->story->getUserStoryFeed'  etc ??

**Comment by solomax2014** [comment]
./src/Request/*.php
