### ISSUE TITLE
Signed body creating

### ISSUE THREAD

**Issue by Delphian2015** [mgp25/Instagram-API#1426]
MPG25, thank you for your API.  Can someone help me and explain how to correctly create a signed body for loggin in?  I saw different ways for this. Someone uses a csrftoken, and someone don't.  What is the difference between deviceId and phoneId? And why the deviceId is the same as the uuid?

**Comment by SteveJobzniak** [comment]
We are not tech support for Instagram reverse engineering. Closed.
