### ISSUE TITLE
direct v2 как открыть переписку с конкретным человеком по его ID или username ??

### ISSUE THREAD

**Issue by alexandrKulik** [mgp25/Instagram-API#1429]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->setUser('yourusername', 'yourpassword');
    $ig->login();
    $result = $ig->comment('14123451234567890_1234567890', "Hello World");
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

RESPONSE: {"status": "fail", "message": "Sorry, the comment data may have been corrupted."}

InstagramAPI\Response\CommentResponse: Sorry, the comment data may have been corrupted.
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below, for example:

GET /api/v1/si/fetch_headers/?guid=123456abcdeff19cc2f123456&challenge_type=signup HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
X-IG-Connection-Type: mobile(UMTS)
X-IG-Capabilities: 3ToAAA==
Accept-Language: en-US
Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; mid=WFI52QABAAGrbKL-ABCDEFGHIJK
User-Agent: Instagram 10.3.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept-Encoding: gzip, deflate, sdch
```

Response:

```http
# Please provide your capture below, for example:

HTTP/1.1 200 OK
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Thu, 15 Dec 2016 08:50:19 GMT
Content-Type: application/json
Set-Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; expires=Thu, 14-Dec-2017 08:50:19 GMT; Max-Age=31449600; Path=/; secure
Connection: keep-alive
Content-Length: 16

{"status": "ok"}
```
---

### Describe your issue

Explanation of your issue goes here.

Please make sure the description is worded well enough to be understood, and with as much context and examples as possible.

We reserve the right to close your ticket without answer if you can't bother spending a few minutes to write a helpful report for us.

**Comment by mgp25** [comment]
Sorry, this is an international repository. Try to write in a language everyone can understand, it doesnt matter if the English isnt okay.

Regards

**Comment by solomax2014** [comment]
Translation of title: "How to get direct chat by people's ID or username?"

Direct использует собственные ID, т.к. там не только переписки с одним пользователем, но и с несколькими. Для получения переписки с определённым пользователем необходимо сначала найти её. Скорее всего, там будет только этот пользователь (или чат, из которого все, кроме вас, вышли). Потом получить сами сообщения и обработать. Код ниже.
---------------Translation--------------------
Direct is using it's own ID's, because there are not only user-to-user chat, there're also a multiuser conversations. So, to get user's chat at first you need to find it. I think, that there will be only this user in direct chat (but it can be also a multiuser conversation, where all users left, except you and this user). After this you can get messages and process them. Use code below.

```php
$targetUsername = "test"; // Username you need to find.
$cursor_id = null;
do {
    $inbox = $ig->direct->getInbox($cursor_id)->getInbox();
    foreach ($inbox->getThreads() as $thread)
        if (
            count($thread->getUsers()) == 1 && // There is only one user
            $thread->getUsers()[0]->getUsername() == $targetUsername && // It's our target
            // One more (a little bit unreliable) check that it isn't a multiuser chat
            $thread->getThreadTitle() == $targetUsername
        ) {
        $threadID = $thread->getThreadId();
        break;
        }
} while (!is_null($cursor_id = $inbox->getOldestCursor()));
if (!$threadID)
    die("Can't find chat with our needed user");
$thread = $ig->direct->getThread($threadID)->getThread();
foreach ($thread->getItems() as $item)
    if ($item->getItemType() == "text")
        /*
         * Process the message:
         *   $item->getTimestamp() - Timestamp it microseconds
         *     Normalization: intval(substr($item->getTimestamp(), 0, -6))
         *   $item->getUserId() - Sender's userID
         *     Username: $ig->people->getInfoById($item->getUserId())->getUser()->getUsername();
         *   $item->getText() - Text of message
         * Notice, that there can be also other item types, like "like"
         */
```

**Comment by Semne** [comment]
//Примерно так, где в переменной $username находится логин
$username='NameUser';
$userId=$igs->people->getUserIdForName($username);
$re=$igs->direct->getThread($userId);
//В последствии разбираешь ответ:
foreach ($re->thread->items as $key){
    if($key->item_type=='text'){
        echo $key->text;
    }
}
//и так далее

**Comment by solomax2014** [comment]
To collaborators: Sorry for using Russian to answer. If you need, I can translate this, but I don't think that you need to worry about this question. Anyway, if you need to translate some issues to English, you can ask me for it.

---
@Semne, ```$ig->direct->getThread()``` принимает только ID беседы и курсор, если требуется просмотреть больше сообщений.

https://github.com/mgp25/Instagram-API/blob/3af853e3f04cad3ebec5ac547a2e82c1f154391d/src/Request/Direct.php#L240

Я уже ответил на этот вопрос выше.

**Comment by Semne** [comment]
У меня несколько другой вопрос:
Не могу понять как работает $cursorId.
Не могли бы Вы дать ответ, где найти документацию на тему получения и передачи этой переменной в функции getThread() и getInbox()

**Comment by mgp25** [comment]
@Semne please write in English, i dont mind if you write in potatoe English. You can use google translate if you want.

You may wonder why i ask you to write in English. Well, the same i dont write all code and documentation in Spanish, to let all people understand every situation and information.

So please, try to write in English even if the sentence is not grammatically correct. All users will be thankful

**Comment by solomax2014** [comment]
@Semne, $cursorID работает как $maxID в аналогичных функциях. См. пример работы с $maxID [здесь](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php).
По поводу функций:
```php
getInbox($cursorId = null)
getThread($threadId, $cursorId = null)
```
По умолчанию $cursorID равен null. При последующих запросах мы получаем новый курсор, который будем подставлять в очередной запрос:
```php
// Для getInbox()
$request = $ig->direct->getInbox()->getInbox(); // Специфика работы, после получения ответа на запрос достаём из него сам список бесед
$cursorID = $request->getOldestCursor();

// Для getThread()
$thread = $ig->direct->getThread($threadID)->getThread(); // Аналогично
$cursorID = $thread->getOldestCursor();
```

При конце "прокручивания" $cursorID вновь станет null, поэтому при работе с ним применяется конструкция do..while. Пример с getInbox() можете посмотреть над вашим первым вопросом.

**Comment by solomax2014** [comment]
@mgp25, do I need to translate my answers and his questions?

**Comment by mgp25** [comment]
@solomax2014 i have translated his questions. If you add your response in English, it would be great. If an user has the same issue, they will be able to read and understand everything

**Comment by solomax2014** [comment]
@mgp25, I'll translate my answer on my own, thanks.
