### ISSUE TITLE
How send photo or text to direct?

### ISSUE THREAD

**Issue by MaximMikulich** [mgp25/Instagram-API#143]
```
direct_v2/threads/
direct_v2/threads/%s/
direct_v2/threads/%s/hide/
direct_v2/threads/%s/items/%s/delete/
direct_v2/threads/%s/leave/
direct_v2/threads/%s/mute/
direct_v2/threads/%s/unmute/
direct_v2/threads/%s/update_title/
direct_v2/threads/broadcast/
direct_v2/threads/broadcast/configure_video/
direct_v2/threads/broadcast/upload_photo/
direct_v2/threads/broadcast/upload_video/
```

How send photo or text to direct?

**Comment by onlyongunz** [comment]
seems like `direct_v2/threads/broadcast/upload_photo/` will work...
use `uploadPhoto` function as refrence to create the uploader function ._.

**Comment by MaximMikulich** [comment]
@onlyongunz do you know how send only text?

**Comment by Gordiy** [comment]
How to use direct_v2/threads/%s/items/%s/delete/ ??? Which data I must set ?

**Comment by Gordiy** [comment]
> ```
> direct_v2/threads/
> direct_v2/threads/%s/
> direct_v2/threads/%s/hide/
> direct_v2/threads/%s/items/%s/delete/
> direct_v2/threads/%s/leave/
> direct_v2/threads/%s/mute/
> direct_v2/threads/%s/unmute/
> direct_v2/threads/%s/update_title/
> direct_v2/threads/broadcast/
> direct_v2/threads/broadcast/configure_video/
> direct_v2/threads/broadcast/upload_photo/
> direct_v2/threads/broadcast/upload_video/
> ```
> How send photo or text to direct?

How to use direct_v2/threads/%s/items/%s/delete/ ??? Which data I must set ?
