### ISSUE TITLE
'user_like_burst_count' parameter in broadcast liking

### ISSUE THREAD

**Issue by solomax2014** [mgp25/Instagram-API#1430]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

There is 'user_like_count' parameter in broadcast liking method. But I found another parameter: 'user_like_burst_count' (and 'offset_to_video_start', but it's not so important, I think). What does the 'user_like_burst_count' parameter? There is also 'burst_likes' field in getLikeCount() response, so what does it mean?

**Comment by matthijsotterloo** [comment]
We use lots of models for all our functions.
So sometimes it might occur that values are not filled, this is not a bug in the API but it means it's not being returned by Instagram.

**Comment by mgp25** [comment]
@solomax2014 it is not documented yet. When we add it to the API we'll write documentation about it.

- read https://github.com/mgp25/Instagram-API/issues/1430#issuecomment-317545776

Regards
