### ISSUE TITLE
 How to use Business related functions?

### ISSUE THREAD

**Issue by azamatzhon** [mgp25/Instagram-API#1433]
Good day, First of all you made the best "Instagram API" I have ever seen. I respect your hard work, and I've interested using business functions for instagram account like as: 'Number of impressions', 'Profile views' etc. How to use Business related functions? Can you give any example related to this question? 
Regards
Azamatzhon
![instagram-business-page](https://user-images.githubusercontent.com/30475475/28634193-34719534-7258-11e7-803d-84181031fbb9.jpg)

**Comment by mgp25** [comment]
@azamatzhon we are glad you like this API. 

We focus only in the user part. There aren't business functions implemented in this API. If you want, you can subscribe to a premium plan where i can give you support in that. See #1231 for more info.

Regards
