### ISSUE TITLE
 Call to a member function markItemSeen() on null

### ISSUE THREAD

**Issue by hakanbolat** [mgp25/Instagram-API#1437]
### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

I want to mark direct messages as seen.
First I'm looking at my inbox with `$result=$i->direct->getInbox();`
Secondly I'm getting Thread with `$result2=$i->direct->getThread($thread_id);`
Then I'm determining which threads are not marked as seen.

> 
       $lastSeenItemId=$result2->thread->last_seen_at[$userId]->item_id;
        //echo $lastSeenItemId;
        $unseenitem=array();
        for($i=0;$i<count($result2->thread->items);$i++)
        {
            if($result2->thread->items[$i]->item_id!=$lastSeenItemId)
            {
                array_push($unseenitem,$result2->thread->items[$i]->item_id);
            }
            else
            {
                break;
            }
        }

Then I'm marking it with

> 
    try{
            $result3=$i->direct->markItemSeen($thread_id,$unseenitem[0]);
        }
        catch(\InstagramAPI\Exception\InstagramException $ex)
        {
            var_dump($ex);
        }
And i'm getting this error. And i cant mark it.

> Fatal error: Call to a member function markItemSeen() on null in ...

I checked ThreadId and threadItemId. it's not NULL

If I only run the markup function, I mark it without any errors. Like this.

>  try {
            $i->setUser($username, $password);
            $i->login();
        } catch (\Exception $e) {
            echo $e->getMessage();
        }
   try{
            $result=$i->direct->markItemSeen('any unseen ThreadId','ThreadItemId');
        }
        catch(\InstagramAPI\Exception\InstagramException $ex)
        {
            var_dump($ex);
        }

**Comment by szokeptr** [comment]
`Call to a member function markItemSeen() on null` means `$i->direct` is null, not the parameters, so probably the API is not initialized or you are referencing the wrong variable.

**Comment by mgp25** [comment]
@hakanbolat read https://github.com/mgp25/Instagram-API/issues/1437#issuecomment-318390995

Not API issue

Regards

**Comment by SteveJobzniak** [comment]
lol.

@mgp25 This is why I renamed all `$i = new InstagramAPI()` in our example codes.

@hakanbolat Hint 1: Read your own code... Hint 2: Think... Hint 3: `for ($i=0...`

**Comment by hakanbolat** [comment]
Omg o_0. @SteveJobzniak thank u, I never paid attention to it.

**Comment by SteveJobzniak** [comment]
Hahaha. ;)
