### ISSUE TITLE
there is no method to get blocker list

### ISSUE THREAD

**Issue by sajadabasi** [mgp25/Instagram-API#1439]
Hey, Thank you for your great codes,
I can not find any method to get blockers list there is a method to get blocked users but no method to get blockers users.
thank you,

**Comment by SteveJobzniak** [comment]
1. Look at README.md to get `dev-master`, which is the latest development code instead of 2.0.
2. Search for the word "block" in here: https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php
