### ISSUE TITLE
Caption Break Line.

### ISSUE THREAD

**Issue by 83lipe** [mgp25/Instagram-API#1441]
Hey dudes! this api very good, but i not can break line in caption text, u have idea? i receive text from textarea, i try nl2br and not works...

**Comment by SteveJobzniak** [comment]
Duplicate of https://github.com/mgp25/Instagram-API/issues/1118

**Comment by 83lipe** [comment]
i no understand the issue 1118, i edit posted media to replace to correct caption?

**Comment by mgp25** [comment]
More info: https://stackoverflow.com/questions/12994769/how-to-add-a-line-break-within-echo-in-php

You can search more about this in the repo by using the search tab at the top of the page.

Regards

**Comment by SteveJobzniak** [comment]
@83lipe No. The edit is just used as an example in that ticket. You need to provide a caption in that example string format to uploadPhoto, if you want to upload with newlines in caption.
