### ISSUE TITLE
how to remote upload video file

### ISSUE THREAD

**Issue by vallez01** [mgp25/Instagram-API#1442]
i want to upload user story video to my timeline

```php
...
elseif ($media_type == 2) {
        // Video
        $url = $item->getVideoVersions()[0]->getUrl();
        
        $caption = $item->getCaption()->getText();
      
$videoFilename = $url;
$captionText = $caption;
try {
    // Note that all video upload functions perform some automatic chunk upload
    // retries, in case of failing to upload all video chunks to Instagram's
    // server! Uploads therefore take longer when their server is overloaded.
    $ig->timeline->uploadVideo($videoFilename, ['caption' => $captionText]);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
}
...
```

Error:
`Something went wrong: The video "https://scontent-atl3-1.cdninstagram.com/t50.9756-16/16454366650_151565398849565636_2244524xxxxxxxxxxxxx_n.mp4" is empty. `

when i check open in browser url video exist, and i can play it.

**Comment by mgp25** [comment]
Hello @vallez01. This API only allows uploads of local files, that means url doesn't works as a video file. You need to download the video and then upload it using the path to the video file.

Regards

**Comment by SteveJobzniak** [comment]
And for those future people who wonder why all files must be local: Because we use external applications to check the videos and photos, and those applications only work with local files!
