### ISSUE TITLE
story feed null

### ISSUE THREAD

**Issue by vallez01** [mgp25/Instagram-API#1444]
how to write something and exit when no story feed available?

`PHP Fatal error:  Call to a member function getItems() on null`

i used   `if($variable) == NULL) ` `if($variable) == 0) ` `if (strlen($variable) == 0)` but not work

```php
$feed = $ig->story->getUserStoryFeed($userID);`

if($feed->getReel()->getItems() == NULL){

echo 'no story';
exit();
}else
{

foreach ($feed->getReel()->getItems() as $item) {

.....
```

**Comment by mgp25** [comment]
@vallez01 im happy you like the API and using it for your own projects, but keep in mind this issue tracker is only for API issues and what you are asking for is for programming issues (not API related).

If you are getting: 
`PHP Fatal error: Call to a member function getItems() on null`

It means you are trying to call `getItems()`  on null, so `getReel()` is null. So you can add another condition to check that:

```php
if (is_null($feed->getReel())) {
// stuff
}
```

Anyway, not API issue. 

Regards
