### ISSUE TITLE
The links in "directMessage" not clickable

### ISSUE THREAD

**Issue by gina4244** [mgp25/Instagram-API#1445]
## Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---
### Describe your Question:

First of all, thank you guys for your time to make us great plugin!

I succeed to send message with function "directMessage", the problem is that when i need to add some link then the link is not clickable.
(when i tried it from the app itself, the link worked)

I also searched in the issue for that bug and found closed bug with similar problem.
https://github.com/mgp25/Instagram-API/issues/1395

The answer was reference to link that search the keywords "link", but none of them was helpful.
I also saw that you have function called: "sendLink"
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php#L789

I tried to use it in the next format:
```

`$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->setUser($username, $password);
    $ig->login();

    $ig->sendLink($id,$msg);

    echo "success";

} catch (\Exception $e) {
    echo 'fail, Something went wrong: '.$e->getMessage()."\n";
}
`
```
But i got error:
Fatal error: Call to undefined method InstagramAPI\Instagram::sendLink() in .../php/sendMsgOnInstagram.php on line 20.

What function do i need to use for send link in the right way?
Thanks.

**Comment by mgp25** [comment]
Use the seach tab. Duplicate issue.

Save dev's time.

Regards

**Comment by solomax2014** [comment]
You should call this method in this way:
```php
$ig->direct->sendLink();
```

**Comment by SteveJobzniak** [comment]
@gina4244 Also note that you are not sending the link like a link. You are sending it as a normal text message! You are calling `directMessage()` from the old 2.0 API.

Upgrade to dev-master API (3.0), via the instructions in README.md.

Then use `$ig->direct->sendLink()` instead.

**Comment by gina4244** [comment]
Thank you guys for your respones,  i will check it now and let you know if everything is ok. :)

**Comment by gina4244** [comment]
I typed the command: 
$ig->direct->sendLink('1915018895','http://www.google.com");

php /Users/usr/www/test/server/routes/php/sendMsgOnInstagram.php "1915018895" 'http://www.google.co.il'

This is the error i got:
Catchable fatal error: Argument 1 passed to InstagramAPI\Request\Direct::_prepareRecipients() 
must be of the type array, string given, called in /Users/rsabah/www/selfiecash/vendor/mgp25/instagram-php/src/Request/Direct.php on line 1146 and defined in /Users/rsabah/www/selfiecash/vendor/mgp25/instagram-php/src/Request/Direct.php on line 942

I also tried to pass the ids argument as array.

What should i do?
Thanks.

**Comment by solomax2014** [comment]
@gina4244, look:
```php
// In case of already existing thread you should use threadID.
// $recipients is array, where $recipients['thread'] is thread
// Notice: it is very long integer, like "395462466546755300949774135929522645213"
// Use string type
// $recipients is array, where $recipients['thread'] is thread
$ig->direct->sendLink(array('thread' => $threadID), "some link");
// For one or more users to create a new thread
// $recipients is array, where $recipients['users'] is array of userIDs
$ig->direct->sendLink(array('users' => array(...)), "some link");
```

**Comment by gina4244** [comment]
Yes, sorry for the delay, i read the function and understand it, thank you guys!

**Comment by SteveJobzniak** [comment]
@gina4244 You can't send a "text message with a link in it". Their API doesn't support that. You have to `sendText` for the text message, and `sendLink` for the clickable link.

**Comment by valga** [comment]
> You can't send a "text message with a link in it".

Yes you can.

**Comment by SteveJobzniak** [comment]
@valga I meant if they want it to be clickable. If the link is just included as text in sendText, it apparently becomes unclickable if people's reports are true.

**Comment by valga** [comment]
> I meant if they want it to be clickable.

Read the docs for `sendLink()` method. There is an optional param for text.

**Comment by SteveJobzniak** [comment]
@valga I know, I've read it. But that's for the title/text of the link?

So kinda like `<a href="http://...">This is the text property of sendLink</a>`, meaning that the whole message gets clickable?

**Comment by valga** [comment]
App converts `https://github.com/ is good` message into something like this: `$ig->direct->sendLink($recipients, 'https://github.com/', ['text' => 'https://github.com/ is good']);`

**Comment by SteveJobzniak** [comment]
@valga Ahh, okay. Hmm, then I wonder what the app does for `https://github.com/ is good but https://bing.com/ is the best search engine`...

**Comment by valga** [comment]
@SteveJobzniak https://github.com/mgp25/Instagram-API/pull/1300#discussion_r119991542 It will send 2 links.

**Comment by SteveJobzniak** [comment]
@valga Ahh I see where I got confused:

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php#L808

`'link_urls' => json_encode([$link]),`

So it's turning a single argument into an array with a single link. But the actual endpoint supports more than one.

This makes me think:

- Option A: Leave it like it is.
- Option B: Rename it to `sendLinks()` and support multiple links as `@param string|string[] $links`.
- Option C: Remove sendLink and make `sendText()` automatically detect links in the text message and automatically do "sendLink"-code with an array of all links detected...

**Comment by SteveJobzniak** [comment]
For C, I found a regex in a bunch of StackOverflow answers:

`/\bhttps?:\/\/[^\s()<>]+(?:\([\w\d]+\)|([^[:punct:]\s]|\/))/`

Test: `This is http://foo:bar@google.com, a great site with https://bing.com. And http://github.com! And lastly http://foo.com`

It's working well: https://regex101.com/r/GoOlKP/1

**Comment by valga** [comment]
I can give you the regex from app.

**Comment by SteveJobzniak** [comment]
@valga Great!

**Comment by valga** [comment]
But I am not sure if it's legal to use it: `((?:(http|https|Http|Https|rtsp|Rtsp):\/\/(?:(?:[a-zA-Z0-9\$\-\_\.\+\!\*\'\(\)\,\;\?\&\=]|(?:\%[a-fA-F0-9]{2})){1,64}(?:\:(?:[a-zA-Z0-9\$\-\_\.\+\!\*\'\(\)\,\;\?\&\=]|(?:\%[a-fA-F0-9]{2})){1,25})?\@)?)?((?:(?:[a-zA-Z0-9 -퟿豈-﷏ﷰ-￯\_][a-zA-Z0-9 -퟿豈-﷏ﷰ-￯\_\-]{0,64}\.)+(?:(?:aero|arpa|asia|a[cdefgilmnoqrstuwxz])|(?:biz|b[abdefghijmnorstvwyz])|(?:cat|com|coop|c[acdfghiklmnoruvxyz])|d[ejkmoz]|(?:edu|e[cegrstu])|f[ijkmor]|(?:gov|g[abdefghilmnpqrstuwy])|h[kmnrtu]|(?:info|int|i[delmnoqrst])|(?:jobs|j[emop])|k[eghimnprwyz]|l[abcikrstuvy]|(?:mil|mobi|museum|m[acdeghklmnopqrstuvwxyz])|(?:name|net|n[acefgilopruz])|(?:org|om)|(?:pro|p[aefghklmnrstwy])|qa|r[eosuw]|s[abcdeghijklmnortuvyz]|(?:tel|travel|t[cdfghjklmnoprtvwz])|u[agksyz]|v[aceginu]|w[fs]|(?:δοκιμή|испытание|рф|срб|טעסט|آزمایشی|إختبار|الاردن|الجزائر|السعودية|المغرب|امارات|بھارت|تونس|سورية|فلسطين|قطر|مصر|परीक्षा|भारत|ভারত|ਭਾਰਤ|ભારત|இந்தியா|இலங்கை|சிங்கப்பூர்|பரிட்சை|భారత్|ලංකා|ไทย|テスト|中国|中國|台湾|台灣|新加坡|测试|測試|香港|테스트|한국|xn\-\-0zwm56d|xn\-\-11b5bs3a9aj6g|xn\-\-3e0b707e|xn\-\-45brj9c|xn\-\-80akhbyknj4f|xn\-\-90a3ac|xn\-\-9t4b11yi5a|xn\-\-clchc0ea0b2g2a9gcd|xn\-\-deba0ad|xn\-\-fiqs8s|xn\-\-fiqz9s|xn\-\-fpcrj9c3d|xn\-\-fzc2c9e2c|xn\-\-g6w251d|xn\-\-gecrj9c|xn\-\-h2brj9c|xn\-\-hgbk6aj7f53bba|xn\-\-hlcj6aya9esc7a|xn\-\-j6w193g|xn\-\-jxalpdlp|xn\-\-kgbechtv|xn\-\-kprw13d|xn\-\-kpry57d|xn\-\-lgbbat1ad8j|xn\-\-mgbaam7a8h|xn\-\-mgbayh7gpa|xn\-\-mgbbh1a71e|xn\-\-mgbc0a9azcg|xn\-\-mgberp4a5d4ar|xn\-\-o3cw4h|xn\-\-ogbpf8fl|xn\-\-p1ai|xn\-\-pgbs0dh|xn\-\-s9brj9c|xn\-\-wgbh1c|xn\-\-wgbl6a|xn\-\-xkc2al3hye2a|xn\-\-xkc2dl3a5ee0h|xn\-\-yfro4i67o|xn\-\-ygbi2ammx|xn\-\-zckzah|xxx)|y[et]|z[amw]))|(?:(?:25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[1-9][0-9]|[1-9])\.(?:25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[1-9][0-9]|[1-9]|0)\.(?:25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[1-9][0-9]|[1-9]|0)\.(?:25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[1-9][0-9]|[0-9])))(?:\:\d{1,5})?)(\/(?:(?:[a-zA-Z0-9 -퟿豈-﷏ﷰ-￯\;\/\?\:\@\&\=\#\~\-\.\+\!\*\'\(\)\,\_])|(?:\%[a-fA-F0-9]{2}))*)?(?:\b|$)`

**Comment by mgp25** [comment]
We should avoid as much as possible copying directly parts of the code from the apk, since it has copyright. But we have tons of code so... why not, you can always encode it so its not directly visible...

**Comment by valga** [comment]
72% of that regex is a const from Android SDK: https://developer.android.com/reference/android/util/Patterns.html#TOP_LEVEL_DOMAIN_STR

**Comment by mgp25** [comment]
@valga then no problem in that. Other apks like WhatsApp or Telegram has its own regex, but thats cool, nothing to worry about. 😄

**Comment by valga** [comment]
@mgp25 it seems that they just modified a pattern https://android.googlesource.com/platform/frameworks/base/+/81aa097/core/java/android/util/Patterns.java#115 from Android SDK, so we can use it for sure.

**Comment by SteveJobzniak** [comment]
@mgp25 @valga Their pattern doesn't work well and it's very heavy. I'm working on another regex which is working well!

https://regex101.com/r/GoOlKP/2

**Comment by SteveJobzniak** [comment]
@mgp25 @valga The one I was working on wasn't unicode-ready so I tweaked it... it's pretty close to ok now:

https://regex101.com/r/GoOlKP/4

**Comment by SteveJobzniak** [comment]
@mgp25 @valga I figured out the mystery. See edits above. The tiny issue with some weird language is something about Unicode writing-direction characters for Right-To-Left languages.

Anyway, here's the regex tested in PHP:

```
php > $rgx = '/(?:https?|rtsp):\/\/(?:\([\-\w+&@#\/%=~_|$?!:,.]*\)|[\-\w+&@#\/%=~_|$?!:,.])*(?:\([\-\w+&@#\/%=~_|$?!:,.]*\)|[\w+&@#\/%=~_|$])/iu';
php > preg_match_all($rgx, 'This is http://foo:bar@google.com/?foo=a, a great site with https://bing.com/?foo=. And HTTP://github123.com! And lastly http://foo.com/fo? What is this long URL https://github.com/what()long()url What about Russian? http://испытание.рф. What about weird language? https://சிங்கப்பூர்.com And lasagnally rtsp://bar.com', $matches); var_dump($matches);
array(1) {
  [0]=>
  array(8) {
    [0]=>
    string(32) "http://foo:bar@google.com/?foo=a"
    [1]=>
    string(22) "https://bing.com/?foo="
    [2]=>
    string(20) "HTTP://github123.com"
    [3]=>
    string(17) "http://foo.com/fo"
    [4]=>
    string(34) "https://github.com/what()long()url"
    [5]=>
    string(30) "http://испытание.рф"
    [6]=>
    string(11) "https://ச"
    [7]=>
    string(14) "rtsp://bar.com"
  }
}
```

This one works nicely, as you can see...

As for Instagram's regex, it doesn't work properly. It captures the whole message string anytime there's at least 1 link in it. So we can't use theirs.

**Comment by valga** [comment]
> As for Instagram's regex, it doesn't work properly.

Because something has lost in github. Here it is https://regex101.com/r/JakTLD/1 capturing even that weird language. Probably we can replace those non-printable chars with `\u` sequences from Android SDK pattern.

**Comment by SteveJobzniak** [comment]
@valga Oh cool, I was nearly ready to commit but I'll take a look at using that regex instead! And note in your example that turning on the unicode flag is important, so that it matches the russian URL: https://regex101.com/r/JakTLD/5

Here's the work I was doing so far:

```php
    /**
     * Extract all URLs from a text string.
     *
     * This function is Unicode-aware.
     *
     * @param string $text
     *
     * @return string[] An array of URLs. Empty if nothing was found. Note that
     *                  array indices may not be sequential, so loop with foreach!
     */
    public static function extractURLs(
        $text)
    {
        if (false !== preg_match_all(
            '/(?:https?|rtsp):\/\/(?:\([\-\w+&@#\/%=~_|$?!:,.]*\)|[\-\w+&@#\/%=~_|$?!:,.])*(?:\([\-\w+&@#\/%=~_|$?!:,.]*\)|[\w+&@#\/%=~_|$])/iu',
            $text,
            $matches
        ) && isset($matches[0])) {
            // The regex is able to match URLs such as "http://www", so we'll
            // simply filter out false positives which don't contain any period.
            $urls = array_filter($matches[0], function($v) {
                return false !== strpos($v, '.');
            });
        } else { // Regex error, should never happen...
            $urls = [];
        }

        return $urls;
    }
```

But if that huge regex works in PHP, we should use it instead (because that weird language annoys me, we should capture it too ;)).

**Comment by SteveJobzniak** [comment]
@valga Hmm, I copied the regex into PHP and yeah it contains raw binary values for some of the characters:

![screen shot 2017-07-30 at 20 26 50](https://user-images.githubusercontent.com/22373193/28755939-70065426-7565-11e7-8101-cdaf67b67f08.png)

There's a few places like that, where it contains basically binary data (unprintable characters)... And in general there's a lot of different weird control characters in it. In all my projects in my life I've avoided UTF-8 characters in source code, since they could be broken by editors... But maybe it's safe these days... Or perhaps we can write some PHP function to convert that string into one with `\uXXXX` replacements instead...

**Comment by valga** [comment]
@SteveJobzniak take in mind that Instagram uses slightly modified version of SDK patter. So `a-zA-Z0-9 -퟿豈-﷏ﷰ-￯\_\-` is `a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF` and so on. We just need to look for similar parts and replace them to ones from SDK.

**Comment by SteveJobzniak** [comment]
@valga Right. I'm actually writing a converter at the moment...

```php
$convert = ""; // that long string...

for ($i = 0, $len = mb_strlen($convert); $i < $len; ++$i) {
    $chr = mb_substr($convert, $i, 1);
    var_dump($chr);
    $ord = unpack('N', mb_convert_encoding($chr, 'UCS-4BE', 'UTF-8'));
    var_dump($ord);
}
```

It's correctly finding the values of all characters. For example the one rendered as FDCF is seen as 64975 which is indeed right.

Just some more testing, then I'll do something like "if $ord > 255; print as \uXXXX"...

**Comment by SteveJobzniak** [comment]
@valga Success! I am putting this code here in this ticket for future reference if we ever need it again. I have now written the converter which ensures that the regex is only printable ASCII (32-126), and anything else gets converted to `\x{0000}` sequences...

```php
$convert = 'the string to convert...';
$final = '';
for ($i = 0, $len = mb_strlen($convert); $i < $len; ++$i) {
    $chr = mb_substr($convert, $i, 1);
    var_dump($chr);
    $ord = unpack('N', mb_convert_encoding($chr, 'UCS-4BE', 'UTF-8'))[1];
    var_dump($ord);
    if ($ord >= 32 && $ord <= 126) { // printable ascii
        $final .= $chr;
    } else { // non-printable ascii and unicode which must be encoded
        $hex = str_pad(dechex($ord), 4, '0', STR_PAD_LEFT);
        var_dump($hex);
        $final .= '\x{'.strtoupper($hex).'}';
    }
}
var_dump($final);
```

**Comment by SteveJobzniak** [comment]
@valga @mgp25 Okay we have this "beautiful" new function now:

https://github.com/mgp25/Instagram-API/commit/0e196ca91d0733c7f9ccf9d9f3777c0a68fa0d67

:)

It perfectly extracts all URLs from any string, even Unicode URLs.

@valga About `sendLink()`: It seems like Realtime doesn't call any "send link" endpoints, so the only place to rewrite is `Direct::sendText()`?

The new `sendText()` code would be something like `$links = Utils::extractURLs($text)` and if count > 0, then send the message via the "sendLink" endpoint (with a list of all the `['fullUrl']` array key values as the list of links in the message), otherwise send it via the "sendText" endpoint.

Do any other functions need updating to this auto-sendLink logic? And I think we should totally delete the sendLink function since we'll be automating it?

**Comment by valga** [comment]
@SteveJobzniak Done in #1447.

**Comment by SteveJobzniak** [comment]
Update for future readers: We have now removed the `sendLink()` function. Instead, the regular `sendText()` now detects all links in your text message and sends them as links automatically. So just use `sendText()`.
