### ISSUE TITLE
Remaining TODOs before 3.0 stable release!

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1446]
We're pretty close to ready for the 3.0 release, but not yet... there are some things left to do...

This list is updated whenever the status of teach TODO item changes:

- [x] Review Internal.php function visibility: (See comments in https://github.com/mgp25/Instagram-API/pull/1434).
- [x] Edit Internal.php with those decisions.
- [x] Review and merge the Direct recipients fix pull request.
- [x] Review the potential extra PHP-CS-Fixer options I listed in the comment: https://github.com/mgp25/Instagram-API/pull/1436#issuecomment-318427229.
- [x] Merge the PHP-CS-Fixer pull request after it's ready.
- [x] Tweak the CS fixer to improve some options.
- [x] Review the ticket with the story dimension and aspect ratio changes and make final decisions.
- [x] Edit our media resolution/aspect checking code to use the new limits.
- [x] Implement a codestyle verification git commit hook to enforce codestyle before anything can be committed (edit: Done https://github.com/mgp25/Instagram-API/commit/71658d602b158558c05127bce592afa200e459ee)
- [x] Consider whether to tweak or automate `Direct::sendLink`. Edit: We are working on automating it. (See comments in https://github.com/mgp25/Instagram-API/issues/1445#issuecomment-318913915) Edit: Links in the text are now handled automatically by `Direct::sendText`.
- [x] Convert all `$targetFeed` values to Constants.php values instead, so that we don't have to constantly document the valid constants and ensure we write them properly. Edit: Done https://github.com/mgp25/Instagram-API/commit/2e09fe566f67e4626cd067d23b7081f2052358ab.
- [X] Implement the "session ID" generation code... Edit: Done https://github.com/mgp25/Instagram-API/commit/bdfbc4e442f8c77eae38bbd726d0c1d96e4549d3.
- [x] Possibly (probably) edit ImageAutoResizer to add support for doing story-cropping (since right now it only supports timeline-cropping). And probably make it always use exactly `0.5625` as the target ratio when cropping stories (exactly 9:16 ratio, meaning standard widescreen in portrait orientation), since 9:16 "zoomed" is how it will be displayed on most modern device screens! Edit: DONE! https://github.com/mgp25/Instagram-API/commit/3f3715870185466e3e71e6bfe7bac26f3fae114f
- [ ] Wait for @mgp25 to implement some more endpoints.
- [ ] Write a summary of all major changes and release `3.0 stable`!

**Comment by SteveJobzniak** [comment]
@valga @mgp25 Our `$targetFeed` system is great but it has grown unmaintainable since we must carefully write them properly and constantly document the list of values as reference in every function that takes that parameter...

So I'll convert them to constants now. Just to make you both aware of that! It'll help us a lot.

**Comment by SteveJobzniak** [comment]
@valga @mgp25 The feedtype constants are now implemented: https://github.com/mgp25/Instagram-API/commit/2e09fe566f67e4626cd067d23b7081f2052358ab

What a big relief! The old system made me nervous with all those carefully written strings everywhere. ;)

**Comment by SteveJobzniak** [comment]
Alright, the `MediaAutoResizer` now supports cropping media for story usage! Just provide the new `targetFeed` option with a story feed value, and it'll crop for story ratio:

https://github.com/mgp25/Instagram-API/commit/3f3715870185466e3e71e6bfe7bac26f3fae114f

**Comment by SteveJobzniak** [comment]
Finally! I'm done with all of my work. But @mgp25 just told me he's got more endpoints to add and that it'll take until mid-August until 3.0 is ready.

**Comment by SteveJobzniak** [comment]
I'll close this ticket now, since I don't know when mgp will be ready with the new endpoints. But in general, people can safely enjoy `dev-master` now. It's stable.

**Comment by solomax2014** [comment]
@SteveJobzniak, there will be "live/{$broadcastId}/get_post_live_comments/" and "live/{$broadcastId}/get_post_live_likes/" endpoints? Just I think if we have getComments() and getLikeCount(), so do we need similar methods for post lives? I have one post live in reel, but it will expire in 7 hours.

**Comment by SteveJobzniak** [comment]
@solomax2014 Hi. Yeah it'll probably be added before 3.0 release. Mgp25 is working hard on all endpoints to be sure it's all finished before 3.0. In that case they'll be added as `Live::getPostLiveComments()` and `Live::getPostLiveLikes()`.

PS: I am taking a hiatus so I won't be easy to reach, I just happened to notice your comment now. Take care! :)

**Comment by mgp25** [comment]
@solomax2014 if you tell me where should i go in the app to do that requests, i'll check. But everything in live is using real time client and not http interface, maybe @valga can answer that better since we worked in that.

**Comment by solomax2014** [comment]
@mgp25, I've found this endpoints in the decompiled apk. I think, they calls when you open post live in tray. Unfortunately, that one that I mentioned was expired, but I saved JSON results of them. I did requests just by using cookies from desktop site and fake user-agent. I don't know if it's using csrftoken and/or uuid.

**Comment by valga** [comment]
@mgp25 As far as I remember, live doesn't use realtime (actually it uses it a bit, but this functionality is not released yet). It uses RTMP for video broadcasting, and everything else is going via HTTP.

**Comment by mgp25** [comment]
@solomax2014 i have found them too, well im going to force some requests within the app and tonight ill try to add them to the API

**Comment by solomax2014** [comment]
@mgp25, I also saw some live-related endpoints in apk:
- Creating lives [related: #1311]. Like "live/create/" and "live/%s/start/". First one, as I saw in decompiled apk, has a lot of parameters, but the second has only "media_id", as I understand. And there is some events or statuses (I don't know) that, I think, related to lives. But I didn't found something like "stop the live and, maybe, save to post live".
- Joining to live [related: #1330]. "live/%s/join". And, maybe, leaving? "live/%s/leave/"
- One more parameter to liking [related: #1430]. Maybe it calls on long tap to like icon. It shows in "live/%s/get_like_count/", "live/%s/like/" and "live/%s/get_post_live_likes/".

Oh, and when I checked "starting_offset" params in postLive likes and comments, there is no error on "out of range" values. 3 mins post live and starting_offset = 300000 is ok, but no comments/likes or anything else, just next values to "like-an-offset-pagination". And now I have one post live in tray again, that was saved ~30 mins ago. Tell me, if you need broadcast_id of it.

**Comment by mgp25** [comment]
@solomax2014 i need a ended broadcast id which has comments and likes for testing, if you send me that, all endpoints will be implemented today

Regards

**Comment by solomax2014** [comment]
@mgp25,
17892222850033663 - expires in ~1-1.5 hour
17867869888148124 - expires in ~15 hours

**Comment by mgp25** [comment]
@solomax2014 i added all the `live` stuff related. You dont need '/join/` endpoint to acutally watch the broadcast. At least from the http interface.

Regards

**Comment by solomax2014** [comment]
@mgp25, thank you! But I still don't understand, how live is stopping. I understand about some timeout if it's interrupted. But usually... I don't know. I also saw some endpoints that can be related to (own?) broadcasts, like "live/%s/get_viewer_list", "live/%s/get_final_viewer_list/"... I don't know about them.

**Comment by solomax2014** [comment]
@mgp25, ok, me and @rudemex tried to launch a live on PC. And it successfully runned. See 17879976502118792 post live. Runs successfully with ffmpeg after calling start():
```
> ffmpeg -re -i video.mp4 -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 396x704 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv upload_url_from_create_call
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.25.100
  Duration: 00:00:16.28, start: 0.000000, bitrate: 293 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 396x704, 236 kb/s, 29.97 fps, 29.97 tbr, 16k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 49 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[libx264 @ 00000237e5db1740] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 00000237e5db1740] profile Constrained Baseline, level 3.0
[libx264 @ 00000237e5db1740] 264 - core 148 r2665 a01e339 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=30 keyint_min=3 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=abr mbtree=1 bitrate=400 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=1500 vbv_bufsize=6000 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'upload_url':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.25.100
    Stream #0:0(und): Video: h264 (libx264) ([7][0][0][0] / 0x0007), yuv420p, 396x704, q=-1--1, 400 kb/s, 30 fps, 1k tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.24.102 libx264
    Side data:
      unknown side data type 10 (24 bytes)
    Stream #0:1(und): Audio: mp3 (libmp3lame) ([2][0][0][0] / 0x0002), 44100 Hz, mono, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc57.24.102 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
...
```
But we don't have an idea how to stop the live. It is too long to wait 3-5 minutes timeout. Does Instagram app use some endpoint or something?

**Comment by mgp25** [comment]
@solomax2014 post all information and code here, and as soon as i can ill test it and check how to end the broadcast properly.

Regards

**Comment by solomax2014** [comment]
@mgp25. PHP code:
```php
$broadcast = $ig->live->create($height, $width);
// Getting broadcast_id and upload url
echo("broadcast_id: {$broadcast->getBroadcastId()}\r\n");
echo("upload_url: {$broadcast->getUploadUrl()}\r\n");
// GIving some time to copy-paste upload_url to ffmpeg launch command
sleep(10);
// Starting live
$start = $ig->live->start($broadcast->getBroadcastId());
// Then launch ffmpeg via command in previous comment
// ffmpeg sends video to instagram fragment by fragment
// addToPostLive() works correctly only after broadcast ending
// Calling it while live doesn't stop the broadcast
```

**Comment by mgp25** [comment]
@solomax2014 can you test a thing? Try this function at the end `getFinalViewerList()`?  Does ffmpeg closes socket properly after transmission?

**Comment by solomax2014** [comment]
@mgp25, ```getFinalViewerList()``` doesn't stop the broadcast, as I see...

**Comment by solomax2014** [comment]
@mgp25, webcam broadcast works. We need to find the devices:
```
> ffmpeg -list_devices true -f dshow -i dummy
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[dshow @ 0000025eff8ea520] DirectShow video devices (some may be both video and audio devices)
[dshow @ 0000025eff8ea520]  "Logitech HD Webcam C270"
[dshow @ 0000025eff8ea520]  "vMix Video"
[dshow @ 0000025eff8ea520]  "vMix Video External 2"
[dshow @ 0000025eff8ea520] DirectShow audio devices
[dshow @ 0000025eff8ea520]  "Microphone (HD Webcam C270)"
[dshow @ 0000025eff8ea520]  "vMix Audio"
[dshow @ 0000025eff8ea520]  "Stereo Mix (Realtek High Definition Audio)"
dummy: Immediate exit requested
```
And then select them:
```
> ffmpeg -rtbufsize 256M -re -f dshow -i video="Logitech HD Webcam C270":audio="Microphone (HD Webcam C270)" -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 396x704 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv "upload_url"
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Guessed Channel Layout for  Input Stream #0.1 : stereo
Input #0, dshow, from 'video=Logitech HD Webcam C270:audio=Microphone (HD Webcam C270)':
  Duration: N/A, start: 81888.714000, bitrate: N/A
    Stream #0:0: Video: rawvideo, bgr24, 640x480, 30 tbr, 10000k tbn, 30 tbc
    Stream #0:1: Audio: pcm_s16le, 44100 Hz, 2 channels, s16, 1411 kb/s
[libx264 @ 000001b352d18f20] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 000001b352d18f20] profile Constrained Baseline, level 3.0
[libx264 @ 000001b352d18f20] 264 - core 148 r2665 a01e339 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=30 keyint_min=3 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=abr mbtree=1 bitrate=400 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=1500 vbv_bufsize=6000 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'upload_url':
  Metadata:
    encoder         : Lavf57.25.100
    Stream #0:0: Video: h264 (libx264) ([7][0][0][0] / 0x0007), yuv420p, 396x704, q=-1--1, 400 kb/s, 30 fps, 1k tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.24.102 libx264
    Side data:
      unknown side data type 10 (24 bytes)
    Stream #0:1: Audio: mp3 (libmp3lame) ([2][0][0][0] / 0x0002), 44100 Hz, stereo, s16p, 128 kb/s
    Metadata:
      encoder         : Lavc57.24.102 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (pcm_s16le (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
```
But I still don't know about right set of ffmpeg parameters. But -rtbufsize should be first because of order of parameters. 256M is because without it I had errors that don't give you to stream:
```
[dshow @ 0000028bdc9eb920] real-time buffer [Logitech HD Webcam C270] [video input] too full or near too full (121% of size: 3041280 [rtbufsize parameter])! frame dropped!
```

**Comment by mgp25** [comment]
@solomax2014 i'll be doing some test now

**Comment by mgp25** [comment]
@SteveJobzniak i have to discuss something. Ping me when you are available

**Comment by solomax2014** [comment]
@mgp25, is there any progress on broadcasts?

**Comment by solomax2014** [comment]
@mgp25, more info about broadcasts. @rudemex found the method to stream using OBS Studio. It just needs to replace ```rtmps://live-upload.instagram.com:443/rtmp/``` in upload_url to ```rtmp://live-upload.instagram.com:80/rtmp/```. Also, you can use ```rtmp://live-upload.instagram.com:80/rtmp/``` as streaming server in settings, using the remaining part of upload_url as stream key. @rudemex tested on Mac, I tested on Windows. Proof: saved my test live as post_live 17867654593178919. Expires in 24 hours.

**Comment by pjlshd** [comment]
@solomax2014 sorry for the noob question, but I don't quite understand what you mean by "using the remaining part of upload_url as stream key.

So basically, you have to put _rtmp://live-upload.instagram.com:80/rtmp/_ as stream URL likes this:
![capture](https://user-images.githubusercontent.com/36137401/35810573-1cdde49c-0ac7-11e8-8527-c7274b2acdc3.PNG)

and what part of upload_url should we put as Stream Key? Thanks!

**Comment by solomax2014** [comment]
@pjlshd, everything after rtmps://live-upload.instagram.com:443/rtmp/ in the URL got by create()

**Comment by pjlshd** [comment]
@solomax2014 so for example, my upload_url is `rtmps://live-upload.instagram.com:443/rtmp/17923318705038620?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfbGl2ZWRhc2giOnsibGl2ZWRhc2hfbW9kZSI6InByaW1hcnkifSwiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6IjEifSwiaWdfbGl2ZV9lbmFibGVfcG9wX3ByaW1pbmciOltdLCJpZ19saXZlX2luZ2VzdGlvbl91cGRhdGVzX3RocmlmdF9lbmFibGUiOnsiZW5hYmxlZCI6IjEifX19\u0026a=ATh09taZd9jedhn3`

I assume my stream key would be `17923318705038620?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfbGl2ZWRhc2giOnsibGl2ZWRhc2hfbW9kZSI6InByaW1hcnkifSwiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6IjEifSwiaWdfbGl2ZV9lbmFibGVfcG9wX3ByaW1pbmciOltdLCJpZ19saXZlX2luZ2VzdGlvbl91cGRhdGVzX3RocmlmdF9lbmFibGUiOnsiZW5hYmxlZCI6IjEifX19\u0026a=ATh09taZd9jedhn3`

still gives me stream key error when starting stream. What am I missing?

**Comment by rudemex** [comment]
hi @pjlshd are you using the dev-master version?

**Comment by pjlshd** [comment]
@rudemex no, I'm using the regular ones (composer require mgp25/instagram-php).

**Comment by rudemex** [comment]
@pjlshd I guess that's where the error is, use the dev, it didn't cause me any problem even though it's not homologated.

regards

**Comment by pjlshd** [comment]
@rudemex tried using the dev-master version, still, no luck. Same error

**Comment by omkarkhalipe** [comment]
did it work?

**Comment by ocq57390** [comment]
Hi, noob question here. How do I obtain the stream key? I'd like to use OBS to stream.

**Comment by rudemex** [comment]
hi @ocq57390, the stream key obtain with this code.

`
substr($stream->getUploadUrl(), 42)
`

the complete code is

```
init ig login
...
$stream = $ig->live->create();
$ig->live->start($stream->getBroadcastId());
return  substr($stream->getUploadUrl(), 42);
```


regards!
