### ISSUE TITLE
Get non-followers

### ISSUE THREAD

**Issue by DarkDeal** [mgp25/Instagram-API#1449]
Hi, I'm trying to get the non-followers. I mean users that I following and their not follow back.
I try to use:
$following = $i->getSelfUsersFollowing();
$followers = $i->getSelfUserFollowers();

and to remove $followers from $following.
but the call to getSelfUserFollowers(); not return all the followers...
Thier is other way to do that?

**Comment by solomax2014** [comment]
Getting followers/following is pagination-based if there are many followers/following. You should get maxID from current response and make new requests until there will be null maxID. Use maxID parameter, read docs:
https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php#L325
https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php#L342
Notice: maybe you're using an old version of this API. I can't tell you anything about old version. But you can read the docs in API's source files. Tell me, if you need code example of using pagination.

**Comment by DarkDeal** [comment]
Thank you friend, it will be good if you have code of pagination.

**Comment by solomax2014** [comment]
@DarkDeal, there is a code, but I think you're using an old version. Anyway, you can rewrite the code or update API to dev-master branch.
```php
$maxID = null;
$users = array();
$i = 0;
$page = 0;
echo("FOLLOWING:\n");
do {
    $page++;
    echo("    PAGE $page:\n");
    $info = $ig->people->getSelfFollowing(null, $maxID);
    foreach ($info->getUsers() as $user) {
        $i++;
        echo("        $i) {$user->getUsername()}\n");
        $users[$user->getUsername()] = true;
    }
} while (!is_null($maxID = $info->getNextMaxId()));

$maxID = null;
$i = 0;
$page = 0;
echo("FOLLOWERS:\n");
do {
    $page++;
    echo("    PAGE $page:\n");
    $info = $ig->people->getSelfFollowers(null, $maxID);
    foreach ($info->getUsers() as $user) {
        $i++;
        echo("        $i) {$user->getUsername()}\n");
        if (isset($users[$user->getUsername()]))
            unset($users[$user->getUsername()]);
    }
} while (!is_null($maxID = $info->getNextMaxId()));

$i = 0;
echo("NON-FOLLOWERS:\n");
foreach ($users as $user => $value) {
    $i++;
    echo("    $i) $user\n");
}
```

**Comment by mgp25** [comment]
**Related:**
- [Pagination Example](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php)

Make sure to use latest dev-master code (it is stable):

`composer require mgp25/instagram-php dev-master`

**See more examples:**

- [Examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

**Comment by elnurxf** [comment]
Noticed on Web based app, that then you click on a followers count, modal appears with limited count of users. After debugging XHR request I came up to that there is still pagination but in slightly different way.

So first page query is (url decoded):
https://www.instagram.com/graphql/query/?query_id=17874545323001329&variables={"id":"5859709485","first":20}

Request:
```
query_id:17874545323001329
variables:{"id":"5859709485","first":20}
```

Response:

```
page_info:
end_cursor : "AQCYSZ5Mdmsi5TaOhPdvgZuGeCdLCe0Gw1NShHdf-rDO3cHOAeLqyWozOA1O-H8r4VnU6sXtmDjWStornsW99E04v_eJyAS50890lcX-5HSg3A"
has_next_page: true
```

So, next page is:

Request:

```
query_id:17874545323001329
variables:{"id":"5859709485","first":10,"after":"AQCYSZ5Mdmsi5TaOhPdvgZuGeCdLCe0Gw1NShHdf-rDO3cHOAeLqyWozOA1O-H8r4VnU6sXtmDjWStornsW99E04v_eJyAS50890lcX-5HSg3A"}
```

So, this is the way the Web-based Instagram app works like. So, maybe If we can send same variables as Web do we can paginate, BUT It's may look suspicious for this kind of request since Android app never will send requests like this.

**Comment by elnurxf** [comment]
Another case is ordering of when a user starts to follow another one. On Web-based app first come oldest ones, on this API it comes in mixed ordering.
Maybe anyone can help me with this?

Thanks!
