### ISSUE TITLE
Listen when somebody like my pic

### ISSUE THREAD

**Issue by pewh** [mgp25/Instagram-API#1450]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

My requirement is listen if somebody like my pic, and it seems https://github.com/mgp25/Instagram-API/blob/master/examples/realtimeClient.php is not available to listen `like` event. Is it possible to achieve my requirement with other ways? Thanks.

**Comment by aitte2** [comment]
Same as https://github.com/mgp25/Instagram-API/issues/1376 ?

**Comment by mgp25** [comment]
@pewh not implemented. Maybe someday, but no ETA.

Regards

**Comment by valga** [comment]
@mgp25 By the way, this one is quite easy to implement, because FBNS uses MQTT as a transport protocol. And the only tough thing is a custom Thrift-based `CONNECT` packet. May be I will do it when I have some free time. So, do you have some info on it? Because I remember you saying something about it.

**Comment by mgp25** [comment]
@valga im going to check my previous files from the research and if i find them i send them to you.

**Comment by valga** [comment]
Ok, I received a couple of pushes today. Expect a PR in a week or so.

@mgp25 `Push::register()` is not ok, because it must use unsigned POST. Also, you don't have to `json_encode()` FBNS token.

**Comment by valga** [comment]
@pewh It is ready for tests: #1459.
