### ISSUE TITLE
Need detailed explanation for relationship fields

### ISSUE THREAD

**Issue by gerchicov-bp** [mgp25/Instagram-API#1452]
method `getFriendship`
https://github.com/mgp25/Instagram-API/blob/135762808cb25bb8f3879038de022bcf1b80e0bb/src/Request/People.php

structure of response:
https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/FriendshipStatus.php

Could you explain the following?
```
    public $is_private;
    public $is_blocking_reel;
    public $is_muting_reel;
    public $blocking;
    public $is_bestie;
```

**Comment by mgp25** [comment]
@gerchicov-bp 

is the account private. Check wether is private or public.
is blocking stories. Check if its blocking stories
is muting. Check if its hiding stories.
Check if its blocking the account.
Is bestie. If you have subscribed to notification from that account.

By the name you can know what the property means.

Regards

**Comment by gerchicov-bp** [comment]
@mgp25 
Thanks. But can't retrieve `is_bestie` value - it always equals to zero. Does it work in general?

**Comment by mgp25** [comment]
@gerchicov-bp its a boolean value, you know, `0 = false` and `1 = true` ....

**Comment by gerchicov-bp** [comment]
@mgp25 I mean another thing - I don't know which actions should I perform to set this flag to 1 (true)
