### ISSUE TITLE
stopped like or like+sub

### ISSUE THREAD

**Issue by inboyansk** [mgp25/Instagram-API#1454]
Sorry for my English.
I start the task by subscription - all successfully.
I run on the likes or likes + subscriptions, performs several actions and stops. Why is that?
In this case, no errors in the logs

**Comment by mgp25** [comment]
If no debug and code or way to reproduce the same error, this issue will be considered as invalid.

**Comment by inboyansk** [comment]
There is a slightly different error, on it the tasks are left exactly with an error.
#3 {main}<br>\r\n02-08-2017 13:13:45 927 message:No response from server, connection or configure error, code: 0, line: 1897, file: /var/www/user/data/www/.com/vendor/mgp25/instagram-php/src/Instagram.php, trace: #0 /var/www/user/data/www/.com/vendor/mgp25/instagram-php/src/Instagram.php(1627): InstagramAPI\Request->getResponse(Object(InstagramAPI\FriendshipResponse))
#1 /var/www/user/data/.com/cron/job.php(1550): InstagramAPI\Instagram->follow('5817626841')

 Now I'll try to find the task's stop logs.

**Comment by mgp25** [comment]
You are using an outdated code of the API, please update the code and follow the examples

Regards
