### ISSUE TITLE
Session Load

### ISSUE THREAD

**Issue by HyzCo** [mgp25/Instagram-API#1455]
http://prntscr.com/g3w53p <- Database ScreenShot
http://prntscr.com/g3w5xs <- Code ScreenShot

How to login with cookies in the database.

	$ig->setUser($username,$password);
		$ig ->login();
 username, pass login ok but how to login with cookies in the database and How can I do with session like,follow etc.

**Comment by mgp25** [comment]
Example: https://github.com/mgp25/Instagram-API/blob/master/examples/customSettings.php

Rest of the usage its the same. The API manages it internally.

Regards

**Comment by garsamba** [comment]
çözebildiniz hocam?
