### ISSUE TITLE
Search in contact list, ranked/recent understanding

### ISSUE THREAD

**Issue by CashCode** [mgp25/Instagram-API#1457]
Hey guys. Maybe someone can explain me few questions:
1) Is there any option to search in my contact list (not in subs, in old threads)?
2) How to delete thread?
3) Whats difference between ranked recipients and recent?
Recent (getRecentRecipients()) are people with whom I talked recently? Then what means ranked (getRenkedRecipients())?

Regards.

**Comment by valga** [comment]
2. You can't delete a thread. You can either leave a group chat or hide a one-to-one thread. Take in mind that both actions will not hide a thread from other persons' inbox.

**Comment by mgp25** [comment]
1. `linkAddressBook()` you will find in the wiki and closed issues. Look `Request/People.php`
3. This one i can't tell you 100% but i guess ranked shows you the users with more preference. 

After release 3 is done. We'll write a full documentation about all functions. And as soon as i have more info i'll tell you.

Regards
