### ISSUE TITLE
Upload Photo Error with 6d3a6bd

### ISSUE THREAD

**Issue by RedGhostMe** [mgp25/Instagram-API#146]
6d3a6bd ,**last version give me next output when i try to upload photo**

RESPONSE: {"status": "ok", "upload_id": "1461786992864"}

REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=9e49756b60771f8fa1d2f5539a5078056001f23f4d1642d4f85dd0fda9317d45.
RESPONSE: {"status":"fail","message":"**Please update your Instagram app to continue posting photos**"}

REQUEST: qe/expose/
DATA: ig_sig_key_version=4&signed_body=81813d5d5d2d2d2acd4d0fcef1d98d8ce14a712e90be763704e577687fce932e.{"_uuid":"53e816fe-9d49-418a-827f-ecc19a6eaf70","_uid":"232248166","id":"232248166","_csrftoken":"5af21c07de8772841ef85ce232320510","experiment":"ig_android_profile_contextual_feed"}
RESPONSE: {"status": "ok"}

**Comment by sam4jips** [comment]
Yeah it's confirmed! Photo upload is not working...

**Comment by sam4jips** [comment]
Does anyone know how to fix this?

**Comment by wehmoen** [comment]
I use this api for 2 months and have no problems. 
But according to the error message an the api's wiki you need to update the ig_sig_key.
I use arminject for this.
https://github.com/mgp25/Instagram-API/wiki/Technical-information

**Comment by sam4jips** [comment]
@wehmoen thanks! How often do we have to update api key? Can you paste the new api key?

**Comment by wehmoen** [comment]
For best results you should update the api key with every instagram app update. But the old ig_sig_key will work for a undefined while.

With Gikdbg you can extract it from iPhone to :)
