### ISSUE TITLE
No response from server, connection or configure error!

### ISSUE THREAD

**Issue by inboyansk** [mgp25/Instagram-API#1460]
We made a site based on API, downloaded in March 2017. After that we wrote a lot in the code. Now this error often appears. What file should I edit to get rid of this problem?

No response from server, connection or configure error, code: 0, line: 1897, file: /var/www/user/data/www/.com/vendor/mgp25/instagram-php/src/Instagram.php, trace: #0 /var/www/user/data/www/.com/vendor/mgp25/instagram-php/src/Instagram.php(1360): InstagramAPI\Request->getResponse(Object(InstagramAPI\UserFeedResponse))
#1 /var/www/user/data/www/.com/vendor/mgp25/instagram-php/src/Instagram.php(1427): InstagramAPI\Instagram->getUserFeed('2083805185', '150882975386362...', NULL)
#2 /var/www/user/data/www/.com/cron/job.php(861): InstagramAPI\Instagram->getSelfUserFeed('150882975386362...')

**Comment by mgp25** [comment]
@inboyansk what website is it?
