### ISSUE TITLE
Transcode Error

### ISSUE THREAD

**Issue by juergengunz** [mgp25/Instagram-API#1466]
I am getting a transcode error for my videos, when i try to upload them to instagram.

I have no clue why. I converted the video with ffmpeg from .mov to .mp4 and then upload it via the instagram api. The Video is (720x720) 29fps. 15 MB.

Any idea?

Error:
`{"source_width":720,"source_height":720},"caption":"Test","audio_muted":"false","poster_frame_index":"0","upload_id":"1502271926234"}&ig_sig_key_version=4 ← 400 81B RESPONSE: {"message": "Transcode error: Not a single valid video stream", "status": "fail"} Something went wrong: Configuration of "test-video1.mp4" failed. All retries have failed.`

**Comment by haiduong87** [comment]
Have you modified upload coded from 4 chunks (default) to 1?

**Comment by juergengunz** [comment]
installing the libx264 and converting with that library for ffmpeg fixed my issue
