### ISSUE TITLE
My account is hacked

### ISSUE THREAD

**Issue by WolfKOTTO** [mgp25/Instagram-API#1471]

**Comment by WolfKOTTO** [comment]
9

**Comment by solomax2014** [comment]
Not an API issue. Look carefully where you're logging in and what sites/apps you're using.

**Comment by mgp25** [comment]
@WolfKOTTO This is an API, there is a lot of people using this API to create websites, some of them could be shady and can store your account and password without your permissions. 

You MUST NOT use your account with that kind of websites. Only use it with the ones the use the correct security measures and of course dont store your password in plain.

As @solomax2014 said:

> Look carefully where you're logging in and what sites/apps you're using.

Try to contact Instagram support, they maybe can help you. We are not affiliated with, authorized, maintained, sponsored or endorsed by Instagram. This is a unofficial API. You can check that the source is very clear. This API doesn't steal accounts but third party websites could do that.

Becareful the next time.

Regards
