### ISSUE TITLE
I may of have been suspended.

### ISSUE THREAD

**Issue by WolfKOTTO** [mgp25/Instagram-API#1473]
After trying everything all day long I decided to help myself get logged into Insta somehow and it says "User not found" I think Instagram thought I was a bot so :/

**Comment by WolfKOTTO** [comment]
I'm sad

**Comment by mgp25** [comment]
I'm sad too, i ordered a pizza and it never arrived.

Don't use the API with bulk requests or spamming purposes or that will happen.

Regards
