### ISSUE TITLE
Instagram API unfollow chosen user

### ISSUE THREAD

**Issue by mushfik1** [mgp25/Instagram-API#1474]
Hi, sorry I don't the right way to ask for help. Can someone help me how to only unfollow the userid that I want not random ID that this PHP class does. Thank You
` /**
     * Unfollow.
     *
     * @param string $userId
     *
     * @return array Friendship status data
     */
    public function unfollow($userId)
    {
        return $this->request("friendships/destroy/$userId/")
        ->addPost('_uuid', $this->uuid)
        ->addPost('_uid', $this->username_id)
        ->addPost('_csrftoken', $this->token)
        ->addPost('user_id', $userId)
        ->getResponse(new FriendshipResponse());
    }`

**Comment by solomax2014** [comment]
Look: https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php#L602
You must call it in this way in your code: ```$ig->people->unfollow($userId)```

**Comment by mushfik1** [comment]
My code, from VTGram, does work as it unfollows random of who I aleady followed, but I only want it to follow a userid, which I am not being able to do. What can I change in my code to follow only a userid that I specify. Thank You

**Comment by solomax2014** [comment]
People::follow() https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php#L581
```$ig->people->follow($userId)```

**Comment by mgp25** [comment]
Hello @mushfik1. Your issue has been answered in comments https://github.com/mgp25/Instagram-API/issues/1474#issuecomment-321554535 and https://github.com/mgp25/Instagram-API/issues/1474#issuecomment-321546113.

You can find more information about the functions in [/Request/People.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php)

Regards
