### ISSUE TITLE
ImageAutoResizer failed with this photo raito 

### ISSUE THREAD

**Issue by sameralhosami** [mgp25/Instagram-API#1477]
I resized a photo with ImageAutoResizer  "Photo Attached"
instagram report : 

'InvalidArgumentException' with message 'Instagram only accepts media with aspect ratios between 0.800 and 1.910. Your file "/home/public_html/photo/../../users-uploaded-images/1f6503079050660335678fc0eb6aa765__ca753deb320abe935931427adb9200bc.jpg" has a 1.9142 aspect ratio.' in /home/public_html/vendor/mgp25/instagram-php/src/Utils.php:436

Oreginal Image File : 
![unnamed](https://user-images.githubusercontent.com/30845723/29234251-02b13428-7ef6-11e7-9e28-9b0be61c4c96.png)

Resized Photo by (ImageAutoResizer)
![d71e59abafb035fd1a805b7566ddb908__c02d3c9b2c9cd7cc81674269f89f8458](https://user-images.githubusercontent.com/30845723/29234303-5ed3f47a-7ef6-11e7-9f08-cced64d5c53f.jpg)

**Comment by sameralhosami** [comment]
And why ImageAutoResizer cut the original photo , why dont resize it into a blank white photo !

Regards

**Comment by e-ht** [comment]
You will likely benefit from processing your images before attempting to post. You should also update. Instagram-API/src/MediaAutoResizer.php allows you to set more granular parameters.

**Comment by sameralhosami** [comment]
I did update the script , but as i mentioned , MediaAutoResizer CUT the photo as you can see , 
are you are referring to pre processing  the photo on photoshop then pass it to MediaAutoResizer ?

Thank you in advance

**Comment by aitte2** [comment]
Old version had a rare math bug, causing the aspect ratio issue. The new MediaAutoResizer does not produce illegal images anymore.

**Comment by valga** [comment]
> MediaAutoResizer CUT the photo as you can see.

Because it crops the photo by default. If you need to expand it, you should tell it to MediaAutoResizer by something like `new MediaAutoResizer($filename, ['operation' => MediaAutoResizer::EXPAND]);`. You could also specify custom background color for expanding (white by default). Refer to the constructor docs.

**Comment by historylife** [comment]
@valga what if you upload a small photo , smaller than 320 wide , i think the photo has to be enlarge to 320 ! correct .. have a look : 

upload#exception 'InvalidArgumentException' with message 'Instagram only accepts photos that are between 320 and 1080 pixels wide. Your file is 282 pixels wide.' in /home/myinstaranker/public_html/panel/boot/vendor/mgp25/instagram-php/src/Utils.php:399

the script dos not enlarge the photo , of at least create an empty white photo with the correct size and place the photo in the center of the white photo ! 

Please Advice
