### ISSUE TITLE
Sqlite3 report a problem

### ISSUE THREAD

**Issue by basharmasri** [mgp25/Instagram-API#1478]
Hola :)
im using sqlite as store database , and i have more than 8 account using this database 

the problem when login in an error reported :

`Sqlite3, SQLSTATE[HY000]: General error: 5 database is locked
`
i search about this error , it seems sqlite lock the database , if there is another user working with . 
how can we solve this ?

**Comment by mgp25** [comment]
This is not API related, but you can continue talking and sharing information with other users.

Some information about this issue:
> Too many processes are trying to insert too rapidly into the database which is locking the table


**Related:** [Google searches](https://www.google.es/search?q=Sqlite3,+SQLSTATE%5BHY000%5D:+General+error:+5+database+is+locked&client=firefox-b-ab&ei=KmmQWb7_Fc3SwAKGkYfICA&start=0&sa=N&biw=1152&bih=548)

Regards
