### ISSUE TITLE
login() return true on successfull login

### ISSUE THREAD

**Issue by anuj9196** [mgp25/Instagram-API#1479]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Thank you for this plugin. I'm using this in my application for multi user login. while logging. I want to cross check before saving credentials that whether user is logging or not.
```
$insta->login() 
```
must return `(bool) True or False`

Also checked with wrong password, and still no error is returned.

**Comment by mgp25** [comment]
Hello @anuj9196.

Please before opening an issue, make sure you have read all documentation from the source code.

In [Instagram.php](https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L450) you can find `login()` function. In case the login failed, an exception will be throwed (you can catch it). You can also get data if the login was successful, for more information you can see [LoginResponse.php](https://github.com/mgp25/Instagram-API/blob/master/src/Response/LoginResponse.php).

Regards

**Comment by anuj9196** [comment]
```
$ig->timeline->uploadPhoto($photoFilename, ['caption' => $captionText]);
```

Is there `timeline` in `Instagram` class ?

**Comment by mgp25** [comment]
`Request/Timeline.php`.

Please, take your time checking source and docs.

Regards
