### ISSUE TITLE
uploadPhoto doesn't return anything

### ISSUE THREAD

**Issue by soisme** [mgp25/Instagram-API#148]
Hello!

Thank you for this library.
How to get the uploaded photo ID or URL?
when i do print_r($i->uploadPhoto($photo, $caption)), it doesn't return anything although the photo was uploaded successfully. 

It is supposed to return $configure, right?
`
<?phh
        $configure = $this->configure($upload['upload_id'], $photo, $caption);
        $this->expose();
        return $configure;
?>
`

**Comment by MaximMikulich** [comment]
https://github.com/mgp25/Instagram-API/pull/116
