### ISSUE TITLE
Search in Media Likers list?

### ISSUE THREAD

**Issue by Torq07** [mgp25/Instagram-API#1481]
Hi there, i've search for function that provide searching in MediaLikers, but looks like it not been implemented yet.
I've seen other issues where guys asking about pagination for likers list and i know that pagination is impossible, cause official app didn't give such feature, but i can make a search in likers list in iOS app, so i thought that this function might be in backlog list?

**Comment by mgp25** [comment]
Hello @Torq07.

Have you checked source documentation?

You can find the function in [/Requests/Media.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Media.php)

Regards

**Comment by mgp25** [comment]
@Torq07 Let me check this and later i'll update this.

Regards

**Comment by Torq07** [comment]
Yes, i've check the source and i see only this function getLikers , which returns only 1K of likers, but i'm talking about function, which will search in whole likers list. This function is available in app, and i thought that maybe i have it in plans?

**Comment by mgp25** [comment]
@Torq07 Yup, let me finish some stuff and ill check this later 😄 

In case is not implemented, i'll do it.

Regards

**Comment by Torq07** [comment]
Great, thank you, this function will help me a lot!

**Comment by mgp25** [comment]
Hello @Torq07.

It seems that feature it is only enable in iOS. Since this API is based in android client, we will implement this feature when Instagram enable it in the Android app.

Regards

**Comment by Torq07** [comment]
I see, ok, thanks anyway!

**Comment by xavdep** [comment]
Hello everyone ! Have you some news about pagination in getLikers ? And so if Instagram enables this feature in Android api :)

Thanks
