### ISSUE TITLE
Post removal

### ISSUE THREAD

**Issue by SoleSS** [mgp25/Instagram-API#1482]
I have searched through docs, but couldn't find method for deleting posts, nor i didn't find any ids returned from uploadTimelinePhoto($photoFile, $metadata). So the question: method is available? if not: will it be? :)

**Comment by szokeptr** [comment]
https://github.com/mgp25/Instagram-API/blob/0ffb483916af07c2ae44fe1bdf4300fce3e3fa3c/src/Request/Media.php#L49
