### ISSUE TITLE
How do I broadcast from a video?

### ISSUE THREAD

**Issue by GoldenEagle66** [mgp25/Instagram-API#1486]
How do I broadcast from a video?
`$broadcast = $ig->live->create('1184', '720');
echo("broadcast_id: {$broadcast->getBroadcastId()}\<br>");
echo("upload_url: {$broadcast->getUploadUrl()}<br>");`

Then I try to load in ffmpeg 

`ffmpeg -re -i VIDEO2findingnews.mp4 -preset ultrafast -acodec aac -strict -2 -vcodec libx264 -f flv rtmps://live-upload.instagram.com:443/rtmp/17880484747125971?s_efg=eyJxZV9nc`

But returns an error

http://prntscr.com/g95tin

**Comment by mgp25** [comment]
Hello, ill write documentation at the end of the week and ill prepare examples with full documentation.

Meanwhile you can search for a closed issue where you can find more information about broadcasting

Regards

**Comment by solomax2014** [comment]
@GoldenEagle66.
1) Use quotes, because cmd thinks that ampersand is a separator for multiple commands.
2) Check that & is an &, not the %38, and that = is not a %3D, as I see on screenshot.

**Comment by GoldenEagle66** [comment]
@solomax2014 
Yes, thanks, the quotes helped
The ether like goes, but when you go you write
"Live feed download failed"

**Comment by solomax2014** [comment]
@GoldenEagle66. explain, what that means.

**Comment by GoldenEagle66** [comment]
@solomax2014 
like this
http://prntscr.com/g97jug

**Comment by solomax2014** [comment]
@GoldenEagle66, you tried to save the PC live by a phone? I don't know, how saving works. But I can tell that you can save the post live, download it and then delete it automatically (of course, if you're the owner of live), I think. Or try to make a multiple outputs in ffmpeg. Or record the live in some way.

**Comment by GoldenEagle66** [comment]
@solomax2014 
I'm trying to broadcast live on your instructions
https://github.com/mgp25/Instagram-API/issues/1446#issuecomment-320126951

**Comment by solomax2014** [comment]
@GoldenEagle66, ok. As I said in https://github.com/mgp25/Instagram-API/issues/1475, Live::create() creates the broadcastID with a link, and Live::start() is actually starts the live in app. All methods to do a broadcast that I know are listed here: https://github.com/mgp25/Instagram-API/issues/1475#issuecomment-321578664

**Comment by GoldenEagle66** [comment]
@solomax2014 
Well, I'm interested in the stream from the video, I do everything on how you wrote, but it turns out like this.
Thanks on this I'll try.
http://prntscr.com/g97jug

**Comment by solomax2014** [comment]
@GoldenEagle66, which version of ffmpeg you're using?

**Comment by GoldenEagle66** [comment]
@solomax2014 
http://prntscr.com/g9836j

**Comment by solomax2014** [comment]
@GoldenEagle66, try to use OBS or another streaming software. I said in that issue, how to change the url for them.

**Comment by GoldenEagle66** [comment]
@solomax2014 
And that you advise for the flow of video?

**Comment by solomax2014** [comment]
@GoldenEagle66, streaming programs can use the videos as source. Anyway, you can try to use ffmpeg again. I used this [32-bit](https://www.videohelp.com/download/ffmpeg-3.0.1-win32-static.7z) [64-bit](https://www.videohelp.com/download/ffmpeg-3.0.1-win64-static.7z) build.

**Comment by GoldenEagle66** [comment]
@solomax2014 
http://prntscr.com/g98jwt
http://prntscr.com/g98kd4
http://prntscr.com/g98kic

**Comment by solomax2014** [comment]
@GoldenEagle66, I don't know, what is a trouble. That is a command that worked for me:
```
ffmpeg -rtbufsize 256M -re -i video.mp4 -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv "upload_url"
```
Try this.

---
For other viewers of this issue: the second screen tells on Russian (I didn't found screen of this error on English):
```
There's a trouble when loading live
Try again later
```
I don't know the correct title of this error.
