### ISSUE TITLE
Direct sendPost bug

### ISSUE THREAD

**Issue by SaeedSoltoon** [mgp25/Instagram-API#1487]
hi,
media ID in Instagram's internal format has been changed , and regex in `sendPost` method is wrong and always throw an invalid mediaId exception.

and in `Direct.php` on `line 521` and `527` there is missing parameter for sprintf method and the parameter passed for InvalidArgumentException in a wrong way , and raise an error.

```
 Too few arguments in /vendor/mgp25/instagram-php/src/Request/Direct.php on line 521.
 Too few arguments in /vendor/mgp25/instagram-php/src/Request/Direct.php on line 527.
```

**Comment by mgp25** [comment]
Hello @SaeedSoltoon,

can you post the `media_id` you are trying to share? From here, it works perfectly.

Example of usage:

```php
$i->direct->sendPost(
      ['users' => 
            $arrayOfUsers
      ], $mediaId, 
      ['media_type' => 'photo']);
```

**Comment by SaeedSoltoon** [comment]
hi @mgp25 
the `mediaId ` is :
1583162569764769685

and i comment this line 
```
if (!preg_match('#^\d+_\d+$#D', $mediaId)) {
     throw new \InvalidArgumentException(sprintf('"%s" is not a valid media ID.',$mediaId));
}
```

**Comment by valga** [comment]
@SaeedSoltoon Although Instagram accepts short media IDs, you should use full ones just like the app. For example, full ID for you media is `1583162569764769685_10245870`, where `10245870` is owner's profile ID.

However, you are right about issues with `sprintf` args. I will fix them later.
