### ISSUE TITLE
How to paginate in searchTags?

### ISSUE THREAD

**Issue by SashaDesigN** [mgp25/Instagram-API#1489]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [* ] Question
- [ ] Other

### Describe your issue

I`m using ```$ig->searchTags((string)$tag);``` for hashtag search and want to paginate over them if response returns to me has_more=1 value. In docs, I found a way how to paginate over other types of data, but there is no described how to paginate over hashtag result. Thanks a lot for the answer, I know you're quite busy, so I read all that found on your repo before open this issue.

**Comment by mgp25** [comment]
Hello @SashaDesigN,

You are using outdated code. Make sure you are using latest source code from `dev-master`.

Also you can find an example on how to paginate in the `/examples` folder.

[paginationExample.php](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php)

Regards
