### ISSUE TITLE
Upload Photo Ratio problem

### ISSUE THREAD

**Issue by ugurozturk** [mgp25/Instagram-API#149]
RESPONSE: {"status":"fail","message":"Uploaded image isn't in an allowed aspect ratio"}

**Comment by ugurozturk** [comment]
Changed the ratio to 4:5 and it is uploaded.

Also tried another image by 1,91 : 1 ratio. But got another error this time it was png file

RESPONSE: {"status":"fail","message":"Uploaded image isn't in the right format"}

**Comment by ugurozturk** [comment]
Changed the file format to jpeg by Photoshop. And it is uploaded well.

**Comment by acuna-public** [comment]
Using Photoshop is not a solution(
