### ISSUE TITLE
Multi Curl?

### ISSUE THREAD

**Issue by okancelik** [mgp25/Instagram-API#1490]
Hello guys,

First of all thanks for this awesome class.

I want to use this class. But when i send multi request, its slowing down. Can we use guzzle with multi mode? 

Thanks.

**Comment by mgp25** [comment]
Hello @okancelik,

Although you can tweak this library, multi mode is not implemented. And if im honest, i have to say that if you make a good use of the API, multi request is not required.

I haven't wrote the Http Interface, but as far as i know, it is not implemented.

Regards
