### ISSUE TITLE
"thread-created" RTC event not firing

### ISSUE THREAD

**Issue by ashapir0** [mgp25/Instagram-API#1492]
Upon leaving a conversation, and having another user add the same users back the threadIds change although a thread-created event does not fire. When I added a new user to the same thread, it didn't produce a new threadId as expected. 

In my logs this is reflected XXX464 is the first thread (also doesn't fire thread-created), XXX841 is with the same users in a new thread and then another user is added to XXX841.

---
```php
$rtc->on('thread-created', function ($threadId, DirectThread $thread) {
  printf("Event: Thread Created, Thread %s with %s user(s)%s", $threadId, count($thread->getUsers()), PHP_EOL);
});

$rtc->on('thread-item-created', function ($threadId, $threadItemId, DirectThreadItem $threadItem) use ($repo, $ig, $manager) {
  $thread = $repo->getThread($threadId);
  printf("Event: Item Created, Thread %s with %s user(s)%s", $threadId, count($thread->getUsers()), PHP_EOL);
 });
```
Output

```php
Event: Item Created, Thread XXXXXXXXXXXX396464 with 2 user(s)
Event: Item Created, Thread XXXXXXXXXXXX312841 with 2 user(s)
Event: Item Created, Thread XXXXXXXXXXXX312841 with 3 user(s)
```

**Comment by ashapir0** [comment]
I should also clarify, these conversations were created by sending a message.

**Comment by valga** [comment]
Enable debugging for Realtime client and post a log with raw messages.

Also Instagram might use `thread-updated` event even for a new threads. You should also check this.

**Comment by valga** [comment]
@ashapir0 It has been almost two weeks since the last update. Is your issue resolved?

**Comment by mgp25** [comment]
**Issue closed due inactivity.** Feel free to open if you still face any issue.
