### ISSUE TITLE
Wrong data type in Timeline::getTimelineFeed()->getFeedItems()

### ISSUE THREAD

**Issue by solomax2014** [mgp25/Instagram-API#1494]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
$info = $ig->timeline->getTimelineFeed($maxID);
echo($info->getFeedItems()[0]->getUser()->getPk());
```

Error Log/var_dump:

```php
PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::getPk() in .\ig_story.php:XXX
Stack trace:
#0 {main}
  thrown in .\ig_story.php on line XXX

Fatal error: Uncaught Error: Call to undefined method stdClass::getPk() in .\ig_story.php on line XXX

Error: Call to undefined method stdClass::getPk() in .\ig_story.php on line XXX

Call Stack:
    0.8087     385720   1. {main}() .\ig_story.php:0
```

---

### Describe your issue

I'm using dev-master with the latest commit (https://github.com/mgp25/Instagram-API/commit/6ca6a0a5f83e4c08b9f068ce1c8b6b3f8cfce3b6)
As I see in ```$info->fullResponse->feed_items[0]```, it uses media_or_ad:
```
class stdClass#68 (1) {
  public $media_or_ad =>
  class stdClass#63 (27) {
    public $taken_at =>
    int(1503002613)
    public $pk =>
    int(1583623157990708040)
    public $id =>
    string(30) "1583623157990708040_1432672509"
    public $device_timestamp =>
    int(1503002568294)
    public $media_type =>
    int(1)
    public $code =>
    string(11) "BX6KN8uHlNI"
    public $client_cache_key =>
    string(30) "MTU4MzYyMzE1Nzk5MDcwODA0MA==.2"
    public $filter_type =>
    int(112)
    public $image_versions2 =>
    class stdClass#234 (1) {
      public $candidates =>
      array(2) {
        ...
      }
    }
    public $original_width =>
    int(1080)
    public $original_height =>
    int(1080)
    public $user =>
    class stdClass#46 (10) {
      ...
    }
    ...
  }
}
```

It also can be stories_netego, as I've seen.
media_or_ad can contain suggested_users, ad_link_type and so on.

**Comment by mgp25** [comment]
@solomax2014 fixed. Now you can do:

```php
$info = $i->timeline->getTimelineFeed();
echo($info->getFeedItems()[0]->getMediaOrAd()->getUser()->getPk());
```

Regards
