### ISSUE TITLE
Fatal error: Call to undefined method InstagramAPI\Exception\EndpointException::hasResponse() 

### ISSUE THREAD

**Issue by bodapratik** [mgp25/Instagram-API#1495]
Hello I am new to comment in github hut i have problem and i need solution 

below is code i m using 
```php
$ig = new \InstagramAPI\Instagram(false, false, [
    'storage' => 'file',
    'basefolder' => __DIR__ . "/cookies",
        ]);
$username = "xxxxx";
$password = "yyyyy";

try {
    $ig->setUser($username, $password);
    $ig->login();
} catch (\InstagramAPI\Exception\IncorrectPasswordException $e) {
    echo 'dewSomething went wrong: ' . $e->getMessage() . "\n";
    exit(0);
} catch (\Exception $e) {
    echo '11Something went wrong: ' . $e->getMessage() . "\n";
    exit(0);
}

try {
    $feeds = $ig->like("1584048803920913285"); //This post is deleted
} catch (\InstagramAPI\Exception\EndpointException $exx){
    echo 'Something went wrong (EndpointException): ' . $exx->getMessage() . "\n";
    if ($exx->hasResponse()) { // <-- VERY IMPORTANT TO CHECK FIRST!
        echo "The current exception contains a full server response:\n";
        var_dump($exx->getResponse());
        echo "Showing the 'did_delete' and 'message' values of the response:\n";
        var_dump($exx->getResponse()->getDidDelete());
        var_dump($exx->getResponse()->getMessage());
    }
} catch (Exception $ex) {
    echo $ex->getMessage();
}
```
here is i'm getting error that 
Fatal error: Call to undefined method InstagramAPI\Exception\EndpointException::hasResponse() in H:\wamp64\www\instagram_api\index.php on line 39

but I have code as per your example in 
https://github.com/mgp25/Instagram-API/blob/master/examples/exceptionDetailsExample.php 

i'm doing this research because in my project i'm getting exception response "InstagramAPI\Response: feedback_required." and i need full response what is problem 

Please help me.

Thank you

**Comment by mgp25** [comment]
Hello,

You are using an outdated code and this is a duplicate issue. For more information, you can read the `Readme`or search in [closed issues](https://github.com/mgp25/Instagram-API/issues?q=is%3Aissue+is%3Aclosed)

Regards

**Comment by bodapratik** [comment]
i recently updated composer and no updates for you repo
"mgp25/instagram-php": "^2.0"

Please suggest how to update code

**Comment by mgp25** [comment]
Hello,

It is expalined in the Readme

Regards
