### ISSUE TITLE
i cant find comment id

### ISSUE THREAD

**Issue by mehmetbeyHZ** [mgp25/Instagram-API#1496]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hi, comment id is = 1.7881184392123E+16  
and i want do this;
`media/{$commet_id}/comment_like/`
after 
`media/1.7881184392123E+16/comment_like/`  (not working this usable)
how to can i use?

**Comment by itsMoji** [comment]
Hi

you put the comment id in scientific notation format
I think you are using an outdated code use `composer update`

**Comment by mehmetbeyHZ** [comment]
yes i using lastest  version, but i coded all project code lastest version. i musnt change codes

**Comment by mgp25** [comment]
You are using an outdated code. All ID are in string format. Also i have to add that `media_id` have other format.

Make sure you use latest code from `dev-master` and read closed issues and readme

Regards
