### ISSUE TITLE
show more result in search tags

### ISSUE THREAD

**Issue by rziw** [mgp25/Instagram-API#1499]
Hi , i'm using `searchTags($query)` method and it returns results which contains just 50 of founded media with defined tag , is there any way to show more or define a number range for returning result for example show 50 to 100 in a request ?

**Comment by mgp25** [comment]
@rziw im updating the code in order to make this possible.

Will be ready in a while.

Regards

**Comment by mgp25** [comment]
Try that, there is also a `count`, but all tests i did, the max value for the response list is 50, changing this value wont change server's response. Seeing to the client, what it actually does, is exclude the ids that are already loaded.

Related commit: https://github.com/mgp25/Instagram-API/commit/f1741ea58896ea5525d97e2617cc31082cf2addc

Let me know if that works for you.

```php
$ids = [];
$x = 0;
do {
    $search = $i->hashtag->search($tag, $ids);

    foreach ($search->getResults() as $result)
    {
        $ids[] = $result->getId();
    }
} while($search->getHasMore());
```

Regards

**Comment by rziw** [comment]
it makes the result better and eventually 153 of medias was displayed but at the end this error happened : No response from server. Either a connection or configuration error.
  it seems server doesn't support more than this number of result :(

**Comment by mgp25** [comment]
@rziw with latest commit https://github.com/mgp25/Instagram-API/commit/559b3b479c6b2add2c9533d3a876a03a10422464 now it works perfectly

Regards
