### ISSUE TITLE
Collection of statistics

### ISSUE THREAD

**Issue by MaximMikulich** [mgp25/Instagram-API#150]
Guys have any idea how to implement the collection of statistics: who unsubscribed and who signed up you?

**Comment by mkanker** [comment]
I guess you should count how many and who (if you want to know who left
you) from each time you want to know.

On Sat, Apr 30, 2016, 09:46 NeatGroup <notifications@github.com> wrote:

> The guys have any idea how to implement the collection of statistics: who
> unsubscribed and who signed up you?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Instagram-API/issues/150>
>
-- 
Michel Ank

**Comment by MaximMikulich** [comment]
@mkanker If that get to know particular user, every time lists compare? and if one million subscribers?

**Comment by mkanker** [comment]
@MaximMikulich good question, I'm thinking here too, what's the best way to get how many followers and following I have, I tried to find it in the result of the called methods in the login but I didn't find nothing about the exactly number, I see the list of following, but I would need to get the whole list calling many times until the last. I guess we can have some easy way to do it.

**Comment by mkanker** [comment]
does anyone know whether we receive the quantity of followers and following in the login? because thoses numbers are showed in the instagram in our profile, are they requested when we change the tab or when we initialize/login? that's the question

**Comment by MaximMikulich** [comment]
@mgp25 @RageBrahimi @mkanker 
The next update might include statistics and other functions in Instagram. Here the material can look at the screenshots. (Are: the programmer got access to a version of Instagram for developers)
1. Browse the main photo
2. Overlay text on video
3. Ability to upload widescreen videos
4. Two-factor authentication (SMS)
5. Conversion into a business account
6. Moderation comments
7. The new design and icons (available in some users to the current version)
8. Statistics records
9. Automatically delete entries (1 hour)
10. New photo editing tools design
11. Upload video longer than 15 seconds (available to some users of the current version)
12. Account Activity
13. Ability to save photos and videos

Source: https://vc.ru/p/instagram-broken

**Comment by mkanker** [comment]
@MaximMikulich did you get any solution?
which way are you doing? I'm starting to doing this part here and I guess I would need to read everytime my followers and following list. Is there any better way?

**Comment by MaximMikulich** [comment]
@mkanker So far it has not received, at the moment I'm doing a common collection: likes, comments from all entries

**Comment by mkanker** [comment]
@MaximMikulich an another way to do this is writing a code that work with the oficial instagram api, because they have an access point that returns the complete friend list, check out:

https://www.instagram.com/developer/endpoints/relationships/

**Comment by mgp25** [comment]
The best thing is to capture requests, that way you can see requests and the responses and comparing which one does what you want.

If you have any of this, just send a pull request, ill review it and merge it if everything is okay

Regards
