### ISSUE TITLE
 One-time login

### ISSUE THREAD

**Issue by mehmetbeyHZ** [mgp25/Instagram-API#1501]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I want you to login once again after you have defined the user name and password like instagram. But I need to log in for each process in this API direction how can I use one time entry

**Comment by mgp25** [comment]
@mehmetbeyHZ you need to call always `login()` and that doesnt mean you are actually authing yourself to access Instagram. If it's the first time you are loging in, API will detect it and authenticate. In case you are already authed, it will only send a few requests (`login flow`), in order to emulate app behavior.

Regards

**Comment by mehmetbeyHZ** [comment]
I want to keep a session, do I have to constantly call the setUser () and login () functions, or is there another way?

**Comment by mgp25** [comment]
Exactly that

**Comment by mehmetbeyHZ** [comment]
For example, I invoked the setUser () and login () functions in login.php, and on the user.php page I invoked user information.
I do not want to use the setUser () and login () functions again in the user.php file. I want to directly use the function $ ig-> getUserInfoByName () directly
