### ISSUE TITLE
System not working. No error Produced

### ISSUE THREAD

**Issue by michaeldprice** [mgp25/Instagram-API#1504]
Hello,

I have tried to impliment this api with no success.

It appears the login works fine. WHen I attempt to upload a photo, I do not get any errors, however the post does not post on IG.

======================
session_start();

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/Vendors/instagram/vendor/autoload.php';

/////// CONFIG ///////
$username = 'mrwebtechllc';
$password = 'REMOVED';
$debug = true;
$truncatedDebug = false;
//////////////////////

/////// MEDIA ////////
$photoFilename = '/home/mrweb/public_html/social-media-poster/app/Vendors/instagram_old/square-image.jpg';
$captionText = 'This is a test photo using social manager.io';
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->setUser($username, $password);
    $ig->login();
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
   $ig->timeline->uploadPhoto($photoFilename, ['caption' => $captionText]);
} catch (\Exception $e) {
    die('didnt work');echo 'Something went wrong: '.$e->getMessage()."\n";
}
//////////////////////////////
Response In Browser with debug on.....
////////////////////////////////////
GET: feed/timeline?rank_token=5913637181_450e3849-ad0e-40b8-aa30-7b83fc806805&ranked_content=true ← 200 1.92kB RESPONSE: {"num_results": 1, "more_available": false, "auto_load_more_enabled": true, "feed_items": [{"media_or_ad": {"taken_at": 1503335937, "pk": 1586419282212078218, "id": "1586419282212078218_5913637181", "device_timestamp": 1503335685662, "media_type": 1, "code": "BYEF-6VFMKK", "client_cache_key": "MTU4NjQxOTI4MjIxMjA3ODIxOA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 470, "height": 470, "url": "https://scontent-ort2-1.cdninstagram.com/t51.2885-15/e35/20986980_112427676114500_6240831031503486976_n.jpg?ig_cache_key=MTU4NjQxOTI4MjIxMjA3ODIxOA%3D%3D.2"}, {"width": 240, "height": 240, "url": "https://scontent-ort2-1.cdninstagram.com/t51.2885-15/s240x240/e35/20986980_112427676114500_6240831031503486976_n.jpg?ig_cache_key=MTU4NjQxOTI4MjIxMjA3ODIxOA%3D%3D.2"}]}, "original_width": 470, "original_height": 470, "user": {"pk": 5913637181, "username": "mrwebtechllc", "full_name": "Michael Price", "is_private": false, "profile_pic_url": "https://scontent-ort2-1.cdninstagram.com/t51.2885-19/s150x150/20968586_1846680202313669_7135138660998971392_a.jpg", "profile_pic_id": "1586342001723439608_5913637181", "is_verified": false, "has_anonymous_profile_picture": false, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "is_unpublished": false}, "caption": {"pk": 17879691307084011, "user_id": 5913637181, "text": "Testing", "type": 1, "created_at": 1503335937, "created_at_utc": 1503335937, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 5913637181, "username": "mrwebtechllc", "full_name": "Michael Price", "is_private": false, "profile_pic_url": "https://scontent-ort2-1.cdninstagram.com/t51.2885-19/s150x150/20968586_1846680202313669_7135138660998971392_a.jpg", "profile_pic_id": "1586342001723439608_5913637181", "is_verified": false, "has_anonymous_profile_picture": false, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "is_unpublished": false}, "did_report_as_spam": false, "media_id": 1586419282212078218}, "caption_is_edited": false, "like_count": 1, "has_liked": true, "top_likers": [], "likers": [{"pk": 5913637181, "username": "mrwebtechllc", "full_name": "Michael Price", "is_private": false, "profile_pic_url": "https://scontent-ort2-1.cdninstagram.com/t51.2885-19/s150x150/20968586_1846680202313669_7135138660998971392_a.jpg", "profile_pic_id": "1586342001723439608_5913637181", "is_verified": false}], "comment_likes_enabled": true, "comment_threading_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "preview_comments": [], "comment_count": 0, "photo_of_you": false, "can_viewer_save": true, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjE3MjhkNjFkMjBhZjQwZWI4N2UyY2I3MGJhN2I5MzIwMTU4NjQxOTI4MjIxMjA3ODIxOCIsInNlcnZlcl90b2tlbiI6IjE1MDMzMzc5MzkzMzJ8MTU4NjQxOTI4MjIxMjA3ODIxOHw1OTEzNjM3MTgxfDNiYzVjOTY3YWYzMGVhMjBiZGJhODMxMmZmOGRlODE3NTIzODQ5NjVkYjA3NmM5ZmYxMDlhNWJhMzA1NmJmNzMifSwic2lnbmF0dXJlIjoiIn0=", "preview": "ACoq3Ft8ddp+q/8A16ZDEG3Z7OR0+nr0HtSIxE+365P4ZH5Zx+FKpISUryQze1ICUW49v++RUM0e2NiOw4wAP5UW+ZImJBTPY9sf41GGLQOSNvI4/L/GgC6IkPajyU9BTZSRESvJC/Ssj7aB/wAs2/ShjSuaSmY87V9fvH0x/dpkZk+cBQcsc/Njk9R0OR78VLA5B8s44HBHoOMEZPI4+ufao95QOQcZcDPpkgf/AKqE9LhboPzNz8i8/wC2f/iaZL5hQ7lAB6kNnp7YH86RJCrKATknBUnP59cY61Zn+4f896E7g1Yrmd9uCo7D7/4+lRl2PO1ef9v/AOxqyGEaqQMswHt0FSrICAeeaYjPsN8n7xht5I9Pwx+pPsMU24t3uEeNMcvk5PYZ46HvitHyYx/Cv5CopAFIA4HtRsMo2sL2QLOpkZu689OmeM/0/nVwymWInaV7YPB6ik705ev40CGyW4nVB0wM5xntj+uRn8qljhAUA9QB/KkESH+EfkKd5Mf91fyFAH//2Q=="}}], "megaphone": {"activator": {"activators": [{"title": "Find Contacts", "message": "See which of your friends are already on Instagram and choose who to follow.", "button": "Search Your Contacts", "type": "contact_importer_activator_type", "icon": "https://instagramstatic-a.akamaihd.net/activator/Contacts-2x.png", "confirmation_message": "Contacts Synced", "confirmation_icon": "https://instagramstatic-a.akamaihd.net/activator/Confirmation-2x.png"}, {"title": "Add Phone Number", "message": "Add your phone number so you can reset your password, find friends and more.", "button": "Add Phone Number", "type": "add_phone_number_activator_type", "icon": "https://instagramstatic-a.akamaihd.net/activator/Phone-2x.png", "confirmation_message": "Phone Number Added", "confirmation_icon": "https://instagramstatic-a.akamaihd.net/activator/Confirmation-2x.png"}], "title": "Getting Started", "is_dismissable": false, "feed_position": 0, "uuid": "505df49a328841a28494b570fdd272ed"}}, "is_direct_v2_enabled": true, "next_max_id": null, "status": "ok"}

**Comment by michaeldprice** [comment]
Would like to add, I am able to post to instagram via the mobile app, so accont should not be flagged.

**Comment by michaeldprice** [comment]
Found a php error ....
PHP Fatal error:  Call to a member function uploadPhoto() on null

$ig->timeline is NULL :(

**Comment by michaeldprice** [comment]
After including the Instagram.php file after auto load, I get this php error ....
====
PHP Fatal error:  Class 'InstagramAPI\Request\Account' not found in /home/mrweb/public_html/social-media-poster/app/Vendors/instagram/Instagram.php on line 211

The file does exist.

**Comment by mgp25** [comment]
@michaeldprice Please install this using composer as its explained in the readme. After you have the code prepared, you can look at this example: https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php

Regards

**Comment by michaeldprice** [comment]
Sorry, But I DID install using Composer. My code is also the same as the example!

PHP Fatal error:  Call to a member function uploadPhoto() on null in /home/mrweb/public_html/social-media-poster/app/ig.php on line 35

Location of ig.php
/social-media-poster/app/ig.php
Location of composer autoload.php
/social-media-poster/app/Vendors/instagram/vendor/autoload.php

**Comment by mgp25** [comment]
@michaeldprice it seems you are using latest examples with outdated code. Make sure you are using code from `dev-master`

`composer require mgp25/instagram-php dev-master`

Regards

**Comment by michaeldprice** [comment]
Thank you
