### ISSUE TITLE
Composer issue maybe due to Php version

### ISSUE THREAD

**Issue by bgreeson** [mgp25/Instagram-API#1505]
### Before submitting an issue make sure you have:
- [ X ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Feature request (request for new functionality)
- [ X] Question
- [x] Other

---

### Describe your issue

I am running into issues installing with composer. After viewing many of the closed tickets on the topic it seems others are having the same issue. This is specifically on windows. Following the instructions presented in https://github.com/mgp25/Instagram-API#installation with an empty composer.json results in the below error. My understanding of composer is that the mpg25/instagram-php will be searched against https://packagist.org/. If I search instagram-php I can find the packagist entry. So I speculate all of these issues are related to php version as I am attempting to use php 7.1.8. Is there a contraint on php version used? Error below

C:\Users\uzer\Documents\phpBot>composer require mpg25/instagram-php

  [InvalidArgumentException]
  Could not find package mpg25/instagram-php at any version for your minimum-
  stability (stable). Check the package spelling or your minimum-stability

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest]
 [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--
ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|
--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<
packages>]...

**Comment by mgp25** [comment]
@bgreeson it is not mpg it is mgp, see carefully or better, just copy as paste it from the readme.

Regards
