### ISSUE TITLE
Min ID pagination

### ISSUE THREAD

**Issue by theCVDH** [mgp25/Instagram-API#1507]
How to use the Pagination in the other direction to load only the newer images with Hashtag feed important for keep the database uptodate without to much traffic

**Comment by mgp25** [comment]
@theCVDH 

[PaginationExample.php](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php)

**Related:** Tags pagination https://github.com/mgp25/Instagram-API/issues/1499
