### ISSUE TITLE
updateProfilePicture Endpoint Error?

### ISSUE THREAD

**Issue by fusillijerry89** [mgp25/Instagram-API#1509]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [x] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
        $ig->changeProfilePicture('C:/Users/fusil_000/Dev/wamp64/www/instagram/test.jpg');
    } catch (\Exception $e) {
        echo $e->getMessage();
        exit(0);
    }
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:


! ) Fatal error: Uncaught exception 'InstagramAPI\Exception\EndpointException' with message 'invalid request.' in C:\Users\fusil_000\Dev\wamp64\www\instagram\vendor\mgp25\instagram-php\src\Exception\ServerMessageThrower.php on line 88

 InstagramAPI\Exception\EndpointException: invalid request. in C:\Users\fusil_000\Dev\wamp64\www\instagram\vendor\mgp25\instagram-php\src\Exception\ServerMessageThrower.php on line 88

Call Stack
#	Time	Memory	Function	Location
1	0.0007	241168	{main}( )	...\test.php:0
2	1.3483	3693744	InstagramAPI\Instagram->changeProfilePicture( )	...\test.php:36
3	1.3483	3694040	InstagramAPI\Client->changeProfilePicture( )	...\Instagram.php:1995
4	1.3495	3836720	InstagramAPI\Client->_apiRequest( )	...\Client.php:1256
5	1.6224	3856512	InstagramAPI\Client->getMappedResponseObject( )	...\Client.php:656
6	1.6231	3879240	InstagramAPI\Exception\ServerMessageThrower::autoThrow( )	...\Client.php:437

--


### Describe your issue

I'm not sure if I'm just retarded or the endpoint is not working.. Please advise.

**Comment by SteveJobzniak** [comment]
Hi.

1. Be sure the photo is JPG format.
2. If it still fails, try the latest `dev-master` code instead (see readme).

**Comment by fusillijerry89** [comment]
Switched to dev-master.

It works!! And thanks for the quick response Mr Jobs.
