### ISSUE TITLE
Getting more information from insights (gender percent, top locations, followers age etc.)

### ISSUE THREAD

**Issue by krypto07** [mgp25/Instagram-API#1510]
First of all, thank you for this unique api, that has almost all functions of instagram app. I had an issue when I wanted to get more information from insights. Is there any function to get more info from insights like a gender percent, top locations, followers age etc.. Thanks... 
![whatsapp image 2017-08-23 at 9 12 57 pm](https://user-images.githubusercontent.com/28821560/29623414-1f4d9698-8848-11e7-950f-14da207a3416.jpeg)
![whatsapp image 2017-08-23 at 9 12 57 pm 1](https://user-images.githubusercontent.com/28821560/29623415-21251900-8848-11e7-81d5-44a0e2a577c5.jpeg)

**Comment by mgp25** [comment]
@krypto07 hello,

these function are implemented as any of the devs has a verified (popular) account. If you want these functions to be implemented and you have an account that has these features, send me some account with this to me email (check profile) and I'll be adding these functions.

Regards

**Comment by krypto07** [comment]
@mgp25 ok, I'll send you!
