### ISSUE TITLE
Multiple account

### ISSUE THREAD

**Issue by mehmetbeyHZ** [mgp25/Instagram-API#1511]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

İ want multiple account control but at first login, i do : 
```php
$ig->setUser($username,$password);
$ig->login(); 
```
after second account login:
```php
$ig->setUser($second_username,$second_password); 
$ig->login();
```

(Afrer i logged as first account)
after i create a dropdown button.
for view page Dorpdowns:
1:This photo like as (first_account username)
2:This photo like as (second_account username)

Active account : first account but i want to like sencond account.
i did this control
```php
$ig->setUser($second_username,$second_password);
$ig->media->like($media_id);
```

but second account not liking photo?
what can i do?

**Comment by mgp25** [comment]
@mehmetbeyHZ probably because you account is flagged. I'll close this issue as it seems your account is flagged for abusing Instagram's sever. Maybe i am wrong, in that case post your debug log (only that particular request and response) and we'll check your issue.

Regards

**Comment by SteveJobzniak** [comment]
@mehmetbeyHZ You must always call login() after calling setUser otherwise you have not actually switched user.

**Comment by mgp25** [comment]
@SteveJobzniak gitter a little?
