### ISSUE TITLE
iOS Secret Key & User Agents

### ISSUE THREAD

**Issue by eurongreyjoy** [mgp25/Instagram-API#1512]
I really admire what you have done and it has benefited me a lot. However, I lack the skill to reverse engineer myself so I was wondering if it's possible for you to offer iOS secret key and a few user agents for iOS.

**Comment by mgp25** [comment]
Nope. iOS and Android API are similar in protocol but not the same, they have a lot of differences so even if you got the keys, this API wont be valid for you.

Regards
