### ISSUE TITLE
Problem creating live

### ISSUE THREAD

**Issue by pishnok** [mgp25/Instagram-API#1513]
in first step : 
live/create/            ..."status": "ok"

In the second step :
live/'.$media_id.'/start/   ..."status": "ok"

This is also a video post in ffmpeg : 
` ffmpeg -rtbufsize 256M -re -i dab.mp4 -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv "upload_url" `

i get this response
http://s8.picofile.com/file/8304646984/Untitled.png

How to solve this problem?

**Comment by aitte2** [comment]
Use old tickets to talk about this. Others have streaming successfully via ffmpeg and OpenBroadcaster OBS: https://github.com/mgp25/Instagram-API/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+live
