### ISSUE TITLE
How to repeat an Instagram post to a facebook account using this API?

### ISSUE THREAD

**Issue by shukshin-ivan** [mgp25/Instagram-API#1514]
I'm trying to find possibility to post an instagram post to a facebook account as well.

### What have I tried

I've looked through the code, but haven't found a way to post my instagram post to facebook. It must be some kind of authorization with the facebook login and then using it. I've found `fb_needs_reauth` in the code, it means, that the possibility to use facebook does exist, but I can't find it in the code or in docs. Please, help.

**Comment by mgp25** [comment]
Hello @shukshin-ivan,

that is not implemented in the API, and there is no ETA for it yet.

Regards
