### ISSUE TITLE
View Live

### ISSUE THREAD

**Issue by mehmetbeyHZ** [mgp25/Instagram-API#1515]
And I'm curious about something. How do you track the request traffic of an Instagram apk application?

**Comment by mgp25** [comment]
Patching it.

Regards

**Comment by mehmetbeyHZ** [comment]
i'm wait, when its patch?

**Comment by solomax2014** [comment]
@mehmetbeyHZ, he patches APK to bypass certificate pinning that conflicts with certificates from proxies like Fiddler and Charles. With certificate pinning you can't just set a proxy and use it - Instagram app will see untrusted certificate and give a connection error.

**Comment by xgemboy** [comment]
@mehmetbeyHZ @solomax2014 I have **bypassed SSL pinning** of latest version of Instagram APK. contact me on xgemboy@gmail.com for more details.
