### ISSUE TITLE
viewing story

### ISSUE THREAD

**Issue by GoldenEagle66** [mgp25/Instagram-API#1517]
How can I see the stories of other users?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php

**Comment by GoldenEagle66** [comment]
@mgp25 
I can not figure it out markMediaSeen 
It is possible to take an example

**Comment by mgp25** [comment]
```php  
   * @param \InstagramAPI\Response\Model\Item[] $items An array of one or more
     *                                                   story media Items.
```

Pass the story item to the function.

**Comment by GoldenEagle66** [comment]
@mgp25 
```
$respons = $ig->story->getUserStoryFeed('4212379436');
 $items = $respons->getItems();
```

but how to get the item of story ?

**Comment by mgp25** [comment]
Get the story feed from the user, then get items from the response and pass those items to the mark as seen function.

**Comment by sergeykomlev** [comment]
@mgp25 and @JRoy is it possible to detect story status "seen" or "not seen" before? or view only new stories?

I can't find this parameter in src/Response/Model/User.php and src/Response/Model/Reel.php.
