### ISSUE TITLE
How to get Gender info??

### ISSUE THREAD

**Issue by sajumani** [mgp25/Instagram-API#1519]
Hi,

How can i get gender info by userId ??

**Comment by mgp25** [comment]
Once you get the user object, then `->getGender()`.

I recommend cheking [examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

And [server responses](https://github.com/mgp25/Instagram-API/tree/master/src/Response)

Regards

**Comment by sajumani** [comment]
$debug = true;
		$instagram = new \InstagramAPI\Instagram($debug);
		$instagram->setUser("*****", "****");
		$instagram->login();
		$userId = $instagram->getUsernameId('****');
		$user = $instagram->getUserInfoById($userId);
		print_r( $user->getGender() );


BUT   Fatal error: Uncaught exception 'Exception' with message 'Unknown function getGender.

**Comment by SteveJobzniak** [comment]
@sajumani somethibt like ->getUser()->getGender() is needed. The user object is not hte top level of the response. Please read the server response objects in src/Response to know what to do.

**Comment by ch1c4um** [comment]
@SteveJobzniak Could you help with a functional example? Only place appears a getGender () function is here: https://github.com/mgp25/Instagram-API/blob/8e94d7dc586c2639e23ee201cfa6b2231c3f6f73/src/Response/Model/User.php

**Comment by mgp25** [comment]
Hello @ch1c4um, you can see a lot of examples, in concrete the following one:

- https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php
