### ISSUE TITLE
Can someone give me the latest working signature key?

### ISSUE THREAD

**Issue by Synxed** [mgp25/Instagram-API#152]
I am unable to extract it so I will really appreciate if someone can provide me the latest Instagram signature key.

I tried https://github.com/mgp25/Instagram-API/commit/6d3a6bd90df4ed6e66cc6bc980045c71cdf62f46 but the issue is still occurring.

Thank you.

**Comment by mkanker** [comment]
Which issue?

**Comment by sam4jips** [comment]
I am also looking for a new signature key... I tried extracting myself in vain... I coundn't do it! If someone can just post the new signature key...

**Comment by sam4jips** [comment]
I am also looking for a new signature key... If somebody has it and can just upload it over here that would be like great help... I tried extracting myself but it did not work...

**Comment by mgp25** [comment]
I'll update key, i need to get an android device, if anyone wants to try just hook `libstrings.so` while running the apk, during executation, the register should have stored the signature key

Regards

**Comment by icodeforlove** [comment]
```
ig_sig_key_version - 4
key - f6bcd0639ea3d279c10d4ffe49bd59f1f5045cf73c62fc33c9e45766f6cf6c63
```
