### ISSUE TITLE
Check "ig_fbns_push" is enabled before connecting Push client

### ISSUE THREAD

**Issue by crouchingtiger** [mgp25/Instagram-API#1520]
https://github.com/mgp25/Instagram-API/blob/3dc1e3bdfef0a1a6965a643283390ad1dc22e89b/examples/pushReceiver.php#L19

Just adding a suggestion here. I don't believe that FBNS push _isn't_ rolled out to everyone already, but who knows and maybe better to err on the side of caution:

``$pushEnabled = $this->ig->isExperimentEnabled('ig_fbns_push','is_enabled');``

**Comment by valga** [comment]
Don't forget about `ig_fbns_blocked` experiment.

But I will not check for these experiments until we have a GCM implementation to fall back at. No ETA on this.

**Comment by mgp25** [comment]
@valga since there is no ETA on this. Can the issue be closed?

**Comment by valga** [comment]
@mgp25 Yep, you can close it.

In fact, I think that GCM support will be removed in future, because Instagram slowly migrates to Facebook's infrastructure:
1. WebSocket => MQTT for Realtime.
2. FB uploader for videos.
3. FB uploader even for photos.
