### ISSUE TITLE
Adding location to photo upload fails

### ISSUE THREAD

**Issue by jeroenvvv** [mgp25/Instagram-API#1522]
Hey guys, I'm trying to upload images to instagram via this API, but I am unable to add any sort of location to the photos.

I can search for locations via a both `searchLocation ` and `searchFBLocation`, which returns results. But if I pick any of the results and include them to the `uploadTimelinePhoto `metadata, it uploads the photo without error, and doesn't actually add the location.

```
$metadata = [
              'caption' => 'My awesome caption',
              'location' => '$mylocationresult'
            ];
```

In which form/format does `$mylocationresult` in this case have to be?

Should it be the `external_id `or `facebook_places_id `or `pk `that gets returned? Or maybe a different form all together?

**Comment by mgp25** [comment]
Hello @jeroenvvv, you need to pass a `Location` object.
`Response\Model\Location`

Regards

**Comment by maxvergelli** [comment]
With the following code the post is uploaded but the location doesn't appear on Instagram:

                                $latitude = "20.2167";
                                $longitude = "87.4667";
                                $location_name = "Tulum, Quintana Roo";
				$location = new \InstagramAPI\Response\Model\Location;
				$location->lat = (float)$latitude;
				$location->lng = (float)$longitude;
				$location->name = $location_name;
				$instagram->timeline->uploadPhoto( $photoFilename, array('caption' => "caption text test", 'location' => $location) );

Could You give me a help? Thank You

**Comment by LoriKovari** [comment]
Hi I have also problems adding location to the post. 
I tried different approaches:
## First:
$location = $ig->location->search('40.7439862', '-73.998511')->getVenues()[0];
$metadata = [
        'caption' => $caption, 
        'location' => [
            'lat' => $location->getLat(),
            'lng' => $location->getLng(),
            'address' => $location->getAddress(),
            'external_id' => $location->getExternalId(),
            'external_id_source' => $location->getExternalIdSource(),
            'name' => $location->getName(),
        ]
    ];
I get the post on instagram but no location was setted.
## After that I tried:
I modified the location Object to have the form wich I become from instagram Api Location endpoint
and its looks like
 'location' => [
            'latitude' => 48.858386309412,
            'longitude' => 2.2945538162266,
            'name' => "Tour Eiffel",
            'id' => 2593354
        ]
but also the location is empty after posting on Insta.
Please help me , what i am doing worng? How should look like tha location object?

thanks in advance for your help
