### ISSUE TITLE
Issues  in  sending Direct Message to same user in second time.

### ISSUE THREAD

**Issue by chramkishan** [mgp25/Instagram-API#1524]
I sent a direct message and it worked fine the first time.
But when i tried to send the second message i received an Status OK but the message was not received.

So i got the result and i saw a Tread ID number "thread_id": "340282366841710300949128126314748338735"
I tried to replace the ["0"]

'type' => 'form-data',
'name' => 'thread_ids',
'data' => '["0"]',

I received a Status OK again but the message was not received again.

Any idea how to solve that?

**Comment by mgp25** [comment]
@chramkishan are you using latest code? Anyway, it is working perfectly, if you don't receive anything it is because instagram has flagged your account. I have sent some messages and it works without an issue:

I used `sendText`
```
POST:  https://i.instagram.com/api/v1/direct_v2/threads/broadcast/text/
DATA: recipient_users=[[UID]]&action=send_item&......
← 200 	 205B
RESPONSE: {"action": "item_ack", "status_code": "200", "payload": ......, "status": "ok"}
```

Regards
