### ISSUE TITLE
Question: Error when posting photo: 403 Server received incorrect upload id

### ISSUE THREAD

**Issue by CatLordOfTheKittyIslands** [mgp25/Instagram-API#1525]
Issue: 
~4% of my instagram accounts get into a state where I can no longer post via the API. 

The accounts were posting successfully for about 6 months until 8/1/2017 when they started receiving this error. 
`500 Other media configure error: b'uDZcTVUcbp'`
8/23/2017 the error changed to be 
`403 Server received incorrect upload id`

The account can still have posts created through the legit mobile application, however, since that date the account can no longer have posts created via the api. I have tried hundreds of different photos and captions, all of which work on other accounts that aren't these ~4%. I've tried removing image metadata, trying the same image on different accounts via api, comparing the requests between the working and non-working, changing phone types/id's, upgrading and downgrading IG application versions. IG versions: 9.4.0, 9.3.0, 9.2.5, 9.2.0, and 21 different types of phones. 

Disclosure: I am not using your code. I have written my own version of this library with limited features (based strongly on yours as it was a year ago, with your rewrite your code actually looks a lot closer to mine now). I am posting here hoping that someone else has seen this or that with your vast knowledge you could help me. This is the most comprehensive and helpful forum I have found for this. 

I've included a dump of the request. I promise I've checked the upload ID and it's the one they give back. 
[IG-error-clean.txt](https://github.com/mgp25/Instagram-API/files/1268445/IG-error-clean.txt)

Any help or suggestions would be appreciated!

**Comment by mgp25** [comment]
We only give support to this API.

Regards
