### ISSUE TITLE
Caption with tags in Story is Mystical and have wrong link

### ISSUE THREAD

**Issue by PoluosmakAndrew** [mgp25/Instagram-API#1526]
Hi there,

Does not work caption and tags for photos in Stories.

**Screenshots:**
Posted Story: [http://www.dropbox.com/s/hjjlzi4ekn8gdl4/IMG_5726.PNG?dl=0](http://www.dropbox.com/s/hjjlzi4ekn8gdl4/IMG_5726.PNG?dl=0)
Mystical hashtag 😏: [https://www.dropbox.com/s/vvuqqudk2nekff9/IMG_5727.PNG?dl=0](https://www.dropbox.com/s/vvuqqudk2nekff9/IMG_5727.PNG?dl=0)
Wrong hashtag link (##HELLO): [https://www.dropbox.com/s/6gkdtof3vwjoxwb/IMG_5728.PNG?dl=0](https://www.dropbox.com/s/6gkdtof3vwjoxwb/IMG_5728.PNG?dl=0)

_I'm use latest version from master (V3)_

```php
$metadata = [
             "hashtags" => [
                 [
                     "tag_name'         => "#HELLO",
                     "x"                => 0.5,
                     "y"                => 0.5,
                     "width"            => 0.3,
                     "height"           => 0.3,
                     "rotation"         => 0.0,
                     "is_sticker"       => false,
                     "use_custom_title" => false,
                 ],
             ],
             "caption" => "#HELLO ;)"
         ];
 
$this->instagram->story->uploadPhoto(APPPATH."/controllers/test.jpg", $metadata);
```

**Debug INFO**

> POST:  https://i.instagram.com/api/v1/upload/photo/
→ 17.19kB
← 200 	 46B
RESPONSE: {"upload_id": "1504265657540", "status": "ok"}
POST:  https://i.instagram.com/api/v1/media/configure_to_story/
DATA: signed_body=5103ff0f25935c130d82ddab114244a12ed6f65c7daa44913e0c50934b3c7008.{"device":{"manufacturer":"samsung","model":"SM-G930F","android_version":"23","android_release":"6.0.1"},"story_hashtags":"[{\"tag_name\":\"#HELLO\",\"x\":0.5,\"y\":0.5,\"width\":0.299999999999999988897769753748434595763683319091796875,\"height\":0.299999999999999988897769753748434595763683319091796875,\"rotation\":0,\"is_sticker\":false,\"use_custom_title\":false}]","_csrftoken":"VC4YdO5VdgqGCJ3b1MQX6rcVs8UFAZNd","client_shared_at":"1504265657","configure_mode":"1","source_type":"3","_uid":"224764138","_uuid":"13683574-55fd-4171-b13d-53774fbd4012","edits":{"crop_original_size":[672,1200],"crop_zoom":1,"crop_center":[0,-0]},"extra":{"source_width":672,"source_height":1200},"caption":"#HELLO ;)","mas_opt_in":"NOT_PROMPTED","upload_id":"1504265657540","client_timestamp":"1504265647"}&ig_sig_key_version=4
← 200 	 1.25kB
RESPONSE: {"media": {"taken_at": 1504265657, "pk": 1594218343731298238, "id": "1594218343731298238_224764138", "device_timestamp": 1504265657540, "media_type": 1, "code": "BYfzSMYg_--", "client_cache_key": "MTU5NDIxODM0MzczMTI5ODIzOA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 672, "height": 1200, "url": "https://instagram.fiev3-1.fna.fbcdn.net/t51.9792-15/e35/19152703_127580514546389_7312607697512169472_n.jpg?ig_cache_key=MTU5NDIxODM0MzczMTI5ODIzOA%3D%3D.2"}, {"width": 240, "height": 428, "url": "https://instagram.fiev3-1.fna.fbcdn.net/t51.9792-15/e35/p240x240/19152703_127580514546389_7312607697512169472_n.jpg?ig_cache_key=MTU5NDIxODM0MzczMTI5ODIzOA%3D%3D.2"}]}, "original_width": 672, "original_height": 1200, "caption_position": 0.0, "is_reel_media": true, "user": {"pk": 224764138, "username": "croffkiev", "full_name": "Andrew", "is_private": false, "profile_pic_url": "https://instagram.fiev3-1.fna.fbcdn.net/t51.2885-19/s150x150/18721828_1909830329272618_6269450421526331392_a.jpg", "profile_pic_id": "1525479110959408012_224764138", "is_verified": false, "has_anonymous_profile_picture": false, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "is_unpublished": false}, "caption": {"pk": 17869156069172473, "user_id": 224764138, "text": "#HELLO ;)", "type": 1, "created_at": 1504265659, "created_at_utc": 1504265659, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 224764138, "username": "croffkiev", "full_name": "Andrew", "is_private": false, "profile_pic_url": "https://instagram.fiev3-1.fna.fbcdn.net/t51.2885-19/s150x150/18721828_1909830329272618_6269450421526331392_a.jpg", "profile_pic_id": "1525479110959408012_224764138", "is_verified": false, "has_anonymous_profile_picture": false, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "is_unpublished": false}, "did_report_as_spam": false, "media_id": 1594218343731298238}, "caption_is_edited": false, "comment_likes_enabled": false, "comment_threading_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 4, "preview_comments": [], "comment_count": 0, "photo_of_you": false, "can_viewer_save": true, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImZlMzU0NGJjODBjNjQ5NTA5ODI1MTVhNWMwMTcxMzVkMTU5NDIxODM0MzczMTI5ODIzOCIsInNlcnZlcl90b2tlbiI6IjE1MDQyNjU2NTk2OTl8MTU5NDIxODM0MzczMTI5ODIzOHwyMjQ3NjQxMzh8NzA2NDAxZmIzNmVkMjg4YWRjNGQ1MWExZjE1MGUzOTYwMzhlZDFjZDk3YzE1ODg2NThlOWYwM2IwN2U3OWRiOSJ9LCJzaWduYXR1cmUiOiIifQ==", "expiring_at": 1504352057, "reel_mentions": [], "story_locations": [], "story_hashtags": [{"x": 0.5, "y": 0.5, "width": 0.3, "height": 0.3, "rotation": 0.0, "is_pinned": 0, "hashtag": {"name": "#HELLO", "id": 17884564981116716}}], "story_polls": [], "viewers": [], "viewer_count": 0, "viewer_cursor": null, "total_viewer_count": 0, "multi_author_reel_names": [], "story_poll_voter_infos": []}, "upload_id": "1504265657540", "status": "ok"}

**Comment by PoluosmakAndrew** [comment]
i'm add this code to method **configureSinglePhoto** (Internal.php)

```php
if($targetFeed == Constants::FEED_STORY) {
   $request->addPost('story_media_creation_date', time());
   if (!is_null($usertags)) {
      $request->addPost('reel_mentions', json_encode($usertags));
   }
}
```

Result similar to hashtags. Link to user is Mystical 🙏

**Comment by mgp25** [comment]
I have found the issue. What do you mean by mystical?

**Comment by PoluosmakAndrew** [comment]
Text not visible. After tap on empty space i can view link

https://www.dropbox.com/s/vvuqqudk2nekff9/IMG_5727.PNG?dl=0

**Comment by mgp25** [comment]
@PoluosmakAndrew you need to add an overlay with text or something. API does NOT add an overlay to your photo/story/etc. You need to modify your photo to have that text overlay.

**Comment by PoluosmakAndrew** [comment]
mm.. thanks :-)

**Comment by mgp25** [comment]
@PoluosmakAndrew i have updated the code and the example, try again. Use this:

```php
$metadata = [
             "hashtags" => [
                 [
                     "tag_name'         => "HELLO", // <<----- Here without the '#'
                     "x"                => 0.5,
                     "y"                => 0.5,
                     "width"            => 0.3,
                     "height"           => 0.3,
                     "rotation"         => 0.0,
                     "is_sticker"       => false,
                     "use_custom_title" => false,
                 ],
             ],
             "caption" => "#HELLO ;)"
         ];
 
$this->instagram->story->uploadPhoto(APPPATH."/controllers/test.jpg", $metadata);
```

Let me know if that worked for you

Regards
