### ISSUE TITLE
Mark all media items as seen (such as Story)

### ISSUE THREAD

**Issue by rodendron** [mgp25/Instagram-API#1528]
Hello,

Function "Mark story media items as seen" markMediaSeen works perfect for stories.
But when i try to send there video item or simple media item (photo) - this method does not work. I understand, that it is correct.
But maybe you know how to count+ views and reach of photo and video posts?
Regards.

**Comment by mgp25** [comment]
Hello @rodendron ,

`markMediaSeen()` is a `Story` related function, thats why is it locates in `Story.php` and not in `Media.php`. This means `markMediaSeen()` only works for stories.

About the last question, you can find the answer in the [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ)

Regards
