### ISSUE TITLE
APK HTTP Request for instagram

### ISSUE THREAD

**Issue by mehmetbeyHZ** [mgp25/Instagram-API#1529]
### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

Hi, i want following, see instagram http requests because i want i create my private class.
how can i see apk's http resuests monitor on computer?

**Comment by mgp25** [comment]
@mehmetbeyHZ You need to disable cert pinning. You will find more information in google.

Regards
