### ISSUE TITLE
RegistrationTool

### ISSUE THREAD

**Issue by kripsbro** [mgp25/Instagram-API#153]
Email: asdasdasd@mail.com
[root@server-0912-1330 examples]# php registrationTool.php
###########################
#                         #
# Instagram Register Tool #
#                         #
###########################

Username: demo
Username demo not available, try with another one

Username: askdlsakdlaskd
Username askdlsakdlaskd is available

Password: cccakdksadkasdk

Email: 232k13o12k3o21ko32@gmail.com
[root@server-0912-1330 examples]#

**Comment by kripsbro** [comment]
dont work , and didn't create anything :(

**Comment by mgp25** [comment]
@kripsbro where is the debug log? if you dont post debug log this issue is invalid

Regards

**Comment by muhammeddilaver** [comment]
RESPONSE: {"status": "ok", "errors": {"device_id": ["Too many users have been registered on this device."]}, "account_created": false}
