### ISSUE TITLE
Question: $searchQuery param for following/followers clarification

### ISSUE THREAD

**Issue by jaketoolson** [mgp25/Instagram-API#1531]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---

Calling ```$ig->people->getFollowers($userId, $searchQuery, $maxId)```, I assumed that ```$searchQuery``` would allow me to filter the followers based on constraints like: has_photo, is_private, (```has_anonymous_profile_picture=1&is_private=0```) however it appears you can only filter by username? Is this correct? If so, I wonder if renaming the ```$searchQuery``` variable to ```$query``` and updating the comment to reflect something similar to what 
[Person[search]](https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php#L358) and [Hashtag[search]](https://github.com/mgp25/Instagram-API/blob/9248fc86539db257de2e7353a8b26d04a81d1da7/src/Request/Hashtag.php#L43) has (as examples) "... The username/full name to search for."

Am I wrong in my understanding? If so, I've searched high and low for examples of query parameters, even trying various combinations (string, json, YQuery) with no luck (empty array of users returned).

Thanks.

(Closest reference(s) I found:) 
https://github.com/mgp25/Instagram-API/issues/1340#issuecomment-309242085
https://github.com/mgp25/Instagram-API/issues/585
https://github.com/mgp25/Instagram-API/issues/1341

**Comment by mgp25** [comment]
Hello @jaketoolson,

`$searchQuery' limits the userlist to the ones matching the query. So lets say there are 3 followers: `asdf`, `qwerty`, 'aszx` and `zxcv`.

If you do:

```php
$i->people->getFollowers($uid, 'as');
```

Response will contain the user list with the matching query, and in this case user list will be limited to: `asdf` and `aszx`.

Here is a real example, lets fetch `selenagomez` followers and filter it. Selena Gomez's user id is `460563723`. We are going to limit response to the following query: `ol`.

```php
$i->people->getFollowers('460563723', 'ol');
```

As you can see in the response:

```json
{"users": [{"pk": 1137588197, "username": "olga22mk", "full_name": "", "is_private": false, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/20398291_448731592176549_6727359287502307328_a.jpg", "profile_pic_id": "1566884957337854520_1137588197", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 2053255328, "username": "akos.gal.daniel", "full_name": "13 yrs old\ud83c\udded\ud83c\uddfachelsea fan\ud83c\udded\ud83c\uddfa", "is_private": false, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/21224332_575459742844965_5736735367126581248_a.jpg", "profile_pic_id": "1594880415986212542_2053255328", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 5980725935, "username": "bruceoldo2564", "full_name": "Bruce oldo", "is_private": false, "profile_pic_url": "https://scontent-amt2-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "is_verified": false, "has_anonymous_profile_picture": true}, {"pk": 5980826323, "username": "emanuelesilvaolveira2007", "full_name": "emanuele yasmin silva oliveira", "is_private": false, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/21227172_1767156853588046_7139320743669530624_a.jpg", "profile_pic_id": "1595200750980400014_5980826323", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 4373040969, "username": "jdb.sera", "full_name": "I am a 13 year old girl! Okay?", "is_private": true, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/21296637_1647712238586372_9159988090616414208_a.jpg", "profile_pic_id": "1595201764114536140_4373040969", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 571177166, "username": "ollynj", "full_name": "OJ", "is_private": true, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/16583678_1848282782111452_3494904443118288896_a.jpg", "profile_pic_id": "1454543525286204765_571177166", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 5980184887, "username": "olaf6766", "full_name": "Olaf", "is_private": false, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/21296055_1648113945222991_1512140916998012928_a.jpg", "profile_pic_id": "1595167888146548482_5980184887", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 3513500495, "username": "oleglagutov", "full_name": "Oleg Lagutov", "is_private": false, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/21041845_402232530226571_53751726162837504_a.jpg", "profile_pic_id": "1590526912152026272_3513500495", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 4711434982, "username": "olllejik", "full_name": "Oleg Polishchuk", "is_private": false, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/16789706_290514051364927_4504139882716725248_a.jpg", "profile_pic_id": "1457626241644399431_4711434982", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 5980707837, "username": "olesya_ck", "full_name": "olesya", "is_private": false, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/21227511_552369055131540_5390568467722141696_a.jpg", "profile_pic_id": "1595179029015395785_5980707837", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 3699487217, "username": "ol.night.16", "full_name": "Olesya Gula", "is_private": false, "profile_pic_url": "https://scontent-mad1-1.cdninstagram.com/t51.2885-19/s150x150/21224850_279999709150524_7026497059519725568_a.jpg", "profile_pic_id": "1593762216402649570_3699487217", "is_verified": false, "has_anonymous_profile_picture": false}, {"pk": 2290465638, "username".....
```

The user list was limited to the query.

You can see all usernames like this:

```php
$followers = $i->people->getFollowers('460563723', 'ol');

foreach($followers->getUsers() as $follower)
{
    echo $follower->getUsername(). "\n";
}
```

Hope this answered your question, if not, let me know and ill try to explain myself better.

Regards!

**Comment by jaketoolson** [comment]
@mgp25 Thank you for the detailed examples and response.

So, based off this, and to confirm, ```$searchQuery``` constrains the returned results with a fuzzy match applied to username/fullname.  

I was _hoping_ I could restrict the returned results at the request where, for example, by followers who "is_private=true" and/or "has_anonymous_profile_picture=false" but apparently not.  This would prevent me from paginating over an entire list of results where I want to filter down to, using the same example, followers whose accounts are private.

**Comment by mgp25** [comment]
@jaketoolson yes, that is exactly what Instagram does.

 There is not a way to make other type of query at the moment, if there is any update regarding to this, we will update and tell the users. Meanwhile one approach could be doing this (but still with this, if the list is very big, pagination would be required):

```php
$followers = $i->people->getFollowers('460563723', 'ol');
$filteredUsers = [];

foreach($followers->getUsers() as $follower) {
    if ($follower->getIsPrivate() && getHasAnonymousProfilePicture()) {
         $filteredUsers[] = $follower; // or $follower->getUsername() if you want to store only the username
    }
}
```

Here is an image of the feature and right now it only lets you do a simple query :confused: :

<img src="https://i.amz.mshcdn.com/t4gh2VyExsul_1GLYe-hYzLBWaw=/fit-in/1200x9600/http%3A%2F%2Fmashable.com%2Fwp-content%2Fuploads%2F2016%2F03%2Fig-search-bar-followers-following.jpg" width=300>

Regards

**Comment by jaketoolson** [comment]
@mgp25 thanks again.

At the moment, I have created a solution similar to your example above -- I paginate through the follower responses and then filter the results collection by specific criteria (isPrivate, etc etc). 

Looking forward to continued support, and I will contribute as I'm able to provide solutions and help :)

**Comment by mgp25** [comment]
@jaketoolson great! welcome to this community.

We'll be happy to see your contributions.

Have a nice weekend!

**Comment by SteveJobzniak** [comment]
I'll only comment that the reason for the differing variable names is because the first example has the word search in the function name itself already. The second one puts it in the variable name to clarify that it's for a "search query":

```php
$ig->hashtag->search($query)
$ig->people->getFollowers($id, $searchQuery)
```

**Comment by jaketoolson** [comment]
@SteveJobzniak thanks for the clarification regarding the variables.  When I saw the variable $searchQuery and read the docblock, immediately I assumed I could build a query with various parameters etc etc;  Love this library.

**Comment by SteveJobzniak** [comment]
@jaketoolson Glad to help, and I am happy that you're loving the library! Oh and in case you haven't seen it yet, version 3 stable was released a few hours ago, after five months of work. ;) So if you don't want to be on the development version anymore, you can now switch to stable.

**Comment by shivenmian** [comment]
@mgp25 @SteveJobzniak for the searching username feature `$i->people->getFollowers($uid, $searchquery);`, does the search happen through the entire follower list, or only the first 200 (i.e do we have to paginate in this or not to search accurately)?

**Comment by mgp25** [comment]
@shivenmian it's the same behavior as the official Instagram app. You can check in your device, the result you get on your device in the result you will get on the API.

I haven't tested, so i don't know, thats why i propose you to test it by yourself.

Regards
