### ISSUE TITLE
Cannot add user to existing thread

### ISSUE THREAD

**Issue by Mykke24** [mgp25/Instagram-API#1532]
Hy, when I try to execute this code I get an error

var $threadId = "304902304490823409384";
var $users = ["342234334"];

`return $this->ig->request("direct_v2/threads/{$threadId}/add_user/")
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('user_ids', json_encode($users))
            ->addPost('_uuid', $this->ig->uuid)
            ->setSignedPost(false)
            ->getResponse(new Response\DirectThreadResponse());`

Error: 400
Message: {"message": "Please specify user IDs to add", "status": "fail"}

I AM already specifing user IDs ... where am I wrong?

**Comment by mgp25** [comment]
@Mykke24 use it as the following example:

```php
$threadId = "304902304490823409384";
$users = ["342234334"];

$ig->direct->addUsersToThread($threadId, $users);
```

Regards
