### ISSUE TITLE
Cannot create group thread with 6+ members

### ISSUE THREAD

**Issue by Mykke24** [mgp25/Instagram-API#1533]
Hy guys :D 
I encountered a very weird issue today.

This code works perfectly:

```php
$users = ["1111111111", "2222222222", "33333333333", "444444444444", "555555555", "66666666"];
$threadTitle = "testTitle";

$ig->direct->createGroupThread($users, $threadTitle);
```

BUT! if you try to create a thread with 7 or more ids in the array you'll get an error from instagram.
"Please wait a minute, and try again later"

1-6 ids works fine, but 7 and up does not work.

I guess instagram is limiting the creation of group threads to 6? although it should be 15!

**Comment by mgp25** [comment]
Hello @Mykke24,

It is working perfectly for me. If you want, send me the user ids you are trying to add, and ill replicate your request. But so far, it works perfectly with more than 6 users.

Regards

**Comment by Mykke24** [comment]
I found a work around :D 
1. send message to two users -> _sendDirectItem()
2. add 10 more users to that group -> addUsersToThread()

At least it does the trick :)

Anyway this is the request data I am sending if I create a group 
Endpoint: **https://i.instagram.com/api/v1/direct_v2/create_group_thread/**

Data:
**[{data=[["ID1","ID2"]], name=recipient_users, type=form-data}, {data=MYID, name=_uid, type=form-data}, {data=THREADTITLE, name=thread_title, type=form-data}]**

Response:
**400: {"message": "invalid request", "status": "fail"}**

**Comment by mgp25** [comment]
@Mykke24 i meant the users ids, if you can send them to me i can try it

**Comment by Mykke24** [comment]
I tried with those, and it did not work
3591765697
5757165762
4547625130

could you send me your post data?

**Comment by mgp25** [comment]
Worked perfectly without any issue.

```php
    $users = ["3591765697", "5757165762", "4547625130"];
    $threadTitle = "testTitle";

    $i->direct->createGroupThread($users, $threadTitle);
```

You either are using the API in a wrong way or your account is flagged.

Regards

**Comment by Mykke24** [comment]
I rewrote the createGroupThread  for Java :) 
maybe I made a typo but cant find it

_sendDirectItem() works
addUsersToThread() works too
updateThreadTitle() works as well

account can't be flagged if those endpoints work but not createGroupThread :|
I get **{"message": "invalid request", "status": "fail"}**

**Comment by SteveJobzniak** [comment]
> I rewrote the createGroupThread for Java :)

gtfo. why do people use us as tech support for their rewrites and don't even admit it until we've wasted time troubleshooting our library.
