### ISSUE TITLE
 Cant get more than 20 threads with getInbox  (pagination $cursorId)

### ISSUE THREAD

**Issue by hustlehero** [mgp25/Instagram-API#1535]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### My issue

Hey everyone,
I want to get all direct message threads. I have more than 20 chats in my direct messages on instagram. Now my problem is, that the response only contains the first 20 chats. I have looked into the pagination example for the maxId. But i cant figure out a way to use this method for the $cursorId used in the getInbox function, since in the pagination example the maxId is used. So my question is, if there are any examples to get all direct message chats. (Not only the first 20)
Thanks so much in advance!!

**Comment by SteveJobzniak** [comment]
I don't know exactly how cursors work.

There are cursor properties in some of the inbox responses:

```
src/Response/DirectVisualInboxResponse.php
12: * @method mixed getReadCursor()
14: * @method mixed getUnreadCursor()
18: * @method bool isReadCursor()
20: * @method bool isUnreadCursor()
24: * @method setReadCursor(mixed $value)
26: * @method setUnreadCursor(mixed $value)
35:    public $read_cursor;
37:    public $unread_cursor;

src/Response/Model/DirectInbox.php
9: * @method mixed getOldestCursor()
14: * @method bool isOldestCursor()
19: * @method setOldestCursor(mixed $value)

src/Response/Model/DirectThread.php
23: * @method mixed getNewestCursor()
24: * @method mixed getOldestCursor()
47: * @method bool isNewestCursor()
48: * @method bool isOldestCursor()
71: * @method setNewestCursor(mixed $value)
72: * @method setOldestCursor(mixed $value)
```

Have you tried those values?

Also try stuff like "1", "20", etc.

**Comment by valga** [comment]
Actually I did not write the whole Direct messaging system, but the answer is `getOldestCursor()`.

**Comment by matej2** [comment]
I am having the same problem. I am trying to read all threads by pagination. I tried what @valga  mentioned but it is returning me ` Uncaught LazyJsonMapper\Exception\LazyJsonMapperException: Unknown function "getOldestCursor"` error.

This is my code: 

```
      do {
        $direct = $this->ig->direct->getInbox();
        $threads = array_merge($threads, $direct->getInbox()->getThreads());
        $this->logger->log("Unread count".$direct->getInbox()->getUnseenCount());
        $maxId = $direct->getOldestCursor();
      } while ($maxId !== null);
```
I also tried: ` $maxId = $direct->getNextMaxId();` but still returns the same error

**Comment by amirpdlll** [comment]
I have this problem too ,
this is my code
```
$direct = $Instagram->direct->getInbox(28898275610028568598146750424809472);
$threads = $direct->getInbox()->getThreads();
```

but when I use cursor as parameter for getInbox I got this error

BadRequestException: Invalid request options

how can I get all direct messages ?

thanks
