### ISSUE TITLE
Release: Instagram-API v3.0.0 Stable!

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1537]
🎉 🎉 🎉 

# Instagram-API v3.0.0

It's finally here! Version 3.0 of the library is _finally_ here! Five months of hard work (April, May, June, July and August) and almost 700 code commits since v2.0 later, our team has now finally completed the next stable evolution of this library. And we hope that you are all going to _love_ it!

Go here for more information about the news and a list of the most important changes:

https://github.com/mgp25/Instagram-API/releases

Have fun and enjoy! 🍰 ❤️

**Comment by mgp25** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 
<center><img src="https://ak6.picdn.net/shutterstock/videos/9397355/thumb/1.jpg?i10c=img.resize(height:72)" width=250></center>

And now people, don't forget to read examples and documentation carefully! 😄

**Comment by SteveJobzniak** [comment]
@mgp25 👊 Brofist. Now we can hopefully breathe for a while from all this hard work. 🤣

**Comment by mgp25** [comment]
@SteveJobzniak  👊

**Comment by mexdelgado** [comment]
congratulations!!!

**Comment by comtong** [comment]
@mgp25
hi，I have an question about video's view count,I don't find the Interface to raise view count
