### ISSUE TITLE
How does work positioning of hashtag in Story?

### ISSUE THREAD

**Issue by PoluosmakAndrew** [mgp25/Instagram-API#1538]
https://prnt.sc/ghcwv6 - This is my Story.
Orange square - this is real point in published Story.
Green square - this is point from settings 

```php
[story_hashtags] => Array
                (
                    [0] => stdClass Object
                        (
                            [x] => 0.288
                            [y] => 0.198
                            [width] => 0.474
                            [height] => 0.068625
                            [rotation] => 0
                            [is_pinned] => 0
                            [hashtag] => stdClass Object
                                (
                                    [name] => test
                                    [id] => 17841563557120538
                                )

                        )

                )
```

**Comment by mgp25** [comment]
It is explained in the following example: https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStory.php

`x` and `y` defines the position (from 0 to 1). `width` and `height` defines its size.

Regards

**Comment by SteveJobzniak** [comment]
x/y = looking at your image and your x/y values, maybe it's offset from center/middle of image?
width/height = how large to make the clickable area, as a percentage of the image width/height

**Comment by PoluosmakAndrew** [comment]
it works 🙏
x = (real X + point WIDTH * 0.5) / full WIDTH 
x and y - point of center clickable area

**Comment by SteveJobzniak** [comment]
Thanks, so you mean that X and Y is the point of the center of the clickable area? We'll update the example docs.

**Comment by PoluosmakAndrew** [comment]
yes :-)
X and Y is the point of the center of the clickable area.

**Comment by garsamba** [comment]
> yes :-)
> X and Y is the point of the center of the clickable area.

can you give a sample picture and code?
