### ISSUE TITLE
Set location when uploading a photo.

### ISSUE THREAD

**Issue by skn2215** [mgp25/Instagram-API#1539]
Hi, please tell me why geolocation is not attached in the photo?

```php
var_dump($location);

object(InstagramAPI\Response\Model\Location)#145 (19) {
  ["name"]=>
  string(13) "Paris, France"
  ["external_id_source"]=>
  NULL
  ["external_source"]=>
  string(15) "facebook_places"
  ["address"]=>
  string(0) ""
  ["lat"]=>
  float(48.8567)
  ["lng"]=>
  float(2.3508)
  ["external_id"]=>
  NULL
  ["facebook_places_id"]=>
  string(15) "110774245616525"
  ["city"]=>
  string(0) ""
  ["pk"]=>
  string(7) "6889842"
  ["short_name"]=>
  string(5) "Paris"
  ["facebook_events_id"]=>
  NULL
  ["start_time"]=>
  NULL
  ["end_time"]=>
  NULL
  ["location_dict"]=>
  NULL
  ["type"]=>
  NULL
  ["profile_pic_url"]=>
  NULL
  ["profile_pic_username"]=>
  NULL
  ["time_granularity"]=>
  NULL
}

```

```php
$metadata['location'] = $location;
$ig->timeline->uploadPhoto($photo, $metadata);
```

**Comment by mgp25** [comment]
@serega2215 can you post your debug log (request and response).

**Comment by serega2215** [comment]
Oh sure

[log.txt](https://github.com/mgp25/Instagram-API/files/1277818/log.txt)

**Comment by mgp25** [comment]
@skn2215 we have found the issue, we are updating this in a couple of minutes.

Regards

**Comment by SteveJobzniak** [comment]
This has now been fixed, but not in the way that you may have expected.

1. We were ALREADY properly generating the `facebook_places_id` POST parameter. When we were given a PROPER Location object.
2. You were using the `Location::searchFacebook` and `Location::searchFacebookByPoint` functions to find your locations. That's the wrong way.
3. We were not clear enough about telling users that those functions are WRONG, so I have now added documentation to all 3 location-search functions, telling people which one to use for media.
4. The library now throws an `InvalidArgumentException` if you try giving it a Facebook location object in the future.

Here's the code changes we did:

https://github.com/mgp25/Instagram-API/commit/5fa36a5a32a43cd34ed6ddcedd41a04723f905f9

The thing you will need to change in your own code, is to ALWAYS use `Location::search()` for attaching media locations. That's the endpoint the real app uses. And if you use that one, we will generate proper locations. If you try to still use the facebook-based searches, you'll get exceptions.
