### ISSUE TITLE
Get media_id from media_share

### ISSUE THREAD

**Issue by hustlehero** [mgp25/Instagram-API#1540]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### My issue

Hey everyone,
I got the following problem. I want to get the media_id from a media_share in direct messages.

```php
$response = $ig->direct->getThread($thread_id);
	
	foreach($response->thread->items as $item){
		var_dump($item->media_share);	
		}
```
If I run the code above I get a huge response object. Is there a way to extract the media_id of the media_share?
Maybe something along those lines....
```php

	var_dump($item->media_share->media_id);	
		
```
The code above gives me errors like :
**Trying to get property of non-object** 
 **Undefined property: InstagramAPI\Response\Model\Item::$media_id**

Thanks so much for your help in advance!

**Comment by solomax2014** [comment]
Not every item has media_share type. Use if to check the item type.
```php
$thread = $ig->direct->getThread($thread_id)->getThread();
foreach ($thread->getItems() as $item)
  if ($item->getItemType() == "media_share")
    var_dump($item->getMediaShare()->getId());
```

**Comment by hustlehero** [comment]
@solomax2014 Thanks so much!
