### ISSUE TITLE
Collections Example

### ISSUE THREAD

**Issue by KabilanV** [mgp25/Instagram-API#1543]
Can you send a code to use collections please?

**Comment by mgp25** [comment]
@KabilanV first of all, what do you mean by colletions? Give more details when opening an issue.

- [/examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [Wiki](https://github.com/mgp25/Instagram-API/wiki)

Regards

**Comment by KabilanV** [comment]
I need to get Collections from the account

**Comment by mgp25** [comment]
@KabilanV it is explained in the wiki.

You can find Account functions in the following file: [/Request/Account.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Account.php)

**Comment by KabilanV** [comment]
Its to ge the the saved Collections that I need Please

**Comment by mgp25** [comment]
`Media::getSavedFeed()`

**Comment by KabilanV** [comment]
OKay. 

Thanks a lot. 

Cheers.

**Comment by mgp25** [comment]
Please, next time take your time to check Media functions and so.

- `ctrl + F` if you are on windows/linux.
- `cmd + F` if you are on mac OS.

**Comment by SteveJobzniak** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Collection.php

**Comment by shellscape** [comment]
@SteveJobzniak there aren't any known endpoints for `collections/list` (https://github.com/mgp25/Instagram-API/blob/master/src/Request/Collection.php#L26) and the instagram API throws a 404 for the generated URL. Is that endpoint now dead or am I missing something? (probably the latter)

**Comment by SteveJobzniak** [comment]
@shellscape Hi Andrew. Uhm yes you are missing something...

```php
$list = $ig->collection->getList();
$list->printJson();
```

```
GET:  https://i.instagram.com/api/v1/collections/list/
→ 0B
← 200    86B
RESPONSE: {"items": [], "more_available": false, "auto_load_more_enabled": true, "status": "ok"}

{
    "items": [],
    "more_available": false,
    "auto_load_more_enabled": true,
    "status": "ok"
}
```

**Comment by shellscape** [comment]
@SteveJobzniak thanks for the quick notes, much appreciated. I was independently testing endpoints locally, without using the lib, to examine the finer points.  I was simply trying to grok the lib before I made use of it - I like to know how things work. Helps for when I run into something that I have to help triage. carry on 👍 🍺

**Comment by SteveJobzniak** [comment]
@shellscape Okay. Well then you should run our lib with constructor `$debug = true`, `$truncatedDebug = false`, and also make heft use of our awesome `$response->printJson()` (like in my example above).

You can learn anything about the API that way. ;-)
