### ISSUE TITLE
Catch messages

### ISSUE THREAD

**Issue by mehmetbeyHZ** [mgp25/Instagram-API#1546]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hi, how can I see all of the messages falling in the capture block. for example :
`InstagramAPI\Response\MediaInfoResponse: Media not found or unavailable.`
 
How do you get all of your media output results for the capture block?

because I want to think of it as a catch block

```php
try{
  // Api usign
}catch(Exception $e){
  if($e->getMessage() == 'InstagramAPI \ Response \ MediaInfoResponse: Media not found or unavailable. '){
  header("Location:media_not_found.php");
}

if( if($e->getMessage() == 'another result '){
 header('Location:another_location.php');
}

}
```

I mean, in short, I can see messages from the catch block. for example: `login_required` and another catch messages ..

**Comment by mgp25** [comment]
You don't need to do that. There is an example explaining that:

- [/examples/exceptionDetailsExample.php](https://github.com/mgp25/Instagram-API/blob/master/examples/exceptionDetailsExample.php)

**Comment by mehmetbeyHZ** [comment]
@mgp25  thanks
