### ISSUE TITLE
url the post

### ISSUE THREAD

**Issue by sbaikov96** [mgp25/Instagram-API#1547]
Hi! How to get direct link to the post?

```
try {
    $userId = $ig->people->getUserIdForName('instagram');
    $maxId = null;
    do {
        $response = $ig->timeline->getUserFeed($userId, $maxId);
        foreach ($response->getItems() as $item) {
            printf("[%s] https://instagram.com/p/%s/\n", $item->getId(), $item->getCode());
        }
        $maxId = $response->getNextMaxId();
        echo "Sleeping for 5s...\n";
        sleep(1);
    } while ($maxId !== null); // Must use "!==" for comparison instead of "!=".
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

**Comment by solomax2014** [comment]
Your code gives correct urls to posts. But if you need to store it as a variable:
```php
$url = sprintf("https://www.instagram.com/p/%s/", $item->getCode());
```
Maybe you mean something different. So, tell me, what you mean.

**Comment by sbaikov96** [comment]
@solomax2014 Yes, I'm sorry. I mean how to get direct link to the image that I was able to save in jpg, png, etc.

**Comment by md726** [comment]
Do you mean the jpg url of the posted item?

You can find an example how to access values here: https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php and the code inside of the src folder is well documented, too.

`$item->getImageVersions2()->getCandidates()[0]->getUrl()`

Modified as you need it would be something like 

```
try {
    $userId = $ig->people->getUserIdForName('instagram');
    $maxId = null;
    do {
        $response = $ig->timeline->getUserFeed($userId, $maxId);
        foreach ($response->getItems() as $item) {
            printf("[%s] https://instagram.com/p/%s/\n", $item->getId(), $item->getCode());
            
            // Print the Url of the first candidate
            print($item->getImageVersions2()->getCandidates()[0]->getUrl());
        }
        $maxId = $response->getNextMaxId();
        echo "Sleeping for 5s...\n";
        sleep(5);
   } while ($maxId !== null); // Must use "!==" for comparison instead of "!=".
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

**Comment by sbaikov96** [comment]
@md726 thank You very much

**Comment by solomax2014** [comment]
@sbaikov96, @md726, I need to do some corrections. We need to differ photos, videos and albums. I'll post the correct code in few minutes.

**Comment by solomax2014** [comment]
@sbaikov96, @md726, code:
```php
$userId = $ig->people->getUserIdForName('instagram');
$maxId = null;
do {
    $response = $ig->timeline->getUserFeed($userId, $maxId);
    foreach ($response->getItems() as $item) {
        printf("[%s] https://www.instagram.com/p/%s/\n", $item->getId(), $item->getCode());
        if ($item->getMediaType() == \InstagramAPI\Response\Model\Item::PHOTO)
            printf("  Photo: %s\n", $item->getImageVersions2()->getCandidates()[0]->getUrl());
        elseif ($item->getMediaType() == \InstagramAPI\Response\Model\Item::VIDEO)
            printf("  Video: %s\n", $item->getVideoVersions()[0]->getUrl());
        elseif ($item->getMediaType() == \InstagramAPI\Response\Model\Item::ALBUM) {
            $i = 1;
            foreach ($item->getCarouselMedia() as $carouselMedia) {
                if ($carouselMedia->getMediaType() == \InstagramAPI\Response\Model\Item::PHOTO)
                    printf("  Album [%02d] Photo: %s\n", $i++, $carouselMedia->getImageVersions2()->getCandidates()[0]->getUrl());
                elseif ($carouselMedia->getMediaType() == \InstagramAPI\Response\Model\Item::VIDEO)
                    printf("  Album [%02d] Video: %s\n", $i++, $carouselMedia->getVideoVersions()[0]->getUrl());
            }
        }
    }
    echo "Sleeping for 5s...\n";
    sleep(5);
} while (!is_null($maxId = $response->getNextMaxId()));
```

**Comment by md726** [comment]
@solomax2014 Wow, thanks! And sure, but I just wanted to give a hint and not code a fully developed solution. Since he asked for images, I didn't care about the other stuff that might even cause exceptions with my above post. In theory, we also need to check for the largest candidate / video version instead of simply picking the first one. I'm doing this in my own project, but when previously posting I just wanted to point him into the right direction.

**Comment by solomax2014** [comment]
@md726, the largest definition photo/video is the first in array (as I know). And there is a little notice because videos have imageVersions too, but they're used for thumbnails, as I think, so we definitely need to separate photo and video (and albums, of course).
I answered to this question previously in other issues: https://github.com/mgp25/Instagram-API/issues/1428

**Comment by mgp25** [comment]
Remember that `Item` object has a function called `getItemUrl()` which get the url of the item directly.

Regards
