### ISSUE TITLE
Get exception message without Response path

### ISSUE THREAD

**Issue by WilliamBlais** [mgp25/Instagram-API#1548]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Hi,

I looked everywhere, but I couldn't find how to get only the error message, without the Response path.

`$e->getMessage()`  gives :

`InstagramAPI\Response\LoginResponse: The username you entered doesn't appear to belong to an account. Please check your username and try again.`

I'd like to have :
`The username you entered doesn't appear to belong to an account. Please check your username and try again.`

Thanks,
William

**Comment by mgp25** [comment]
Hello @WilliamBlais,

`$e->getMessage()` provides only that message. You can split it or strip the class from the message or do a `var_dump($e)` to check the properties from inside. Or even do a `getResponse()` and access its properties like: `getResponse()->getMessage()`

Regards

**Comment by WilliamBlais** [comment]
@mgp25 Thank you very much!!
