### ISSUE TITLE
In version 3.0 getSelfUserInfo() is not working

### ISSUE THREAD

**Issue by hosberd** [mgp25/Instagram-API#1551]
In version 3.0 getSelfUserInfo() is not working. How does it work now?

**Comment by mgp25** [comment]
Hello @hosberd,

In version 3.0 there a lot of changes (you can read them in the release note). Also there are some information about how requests are done now.

The function has been renamed to `getCurrentUser()` and it belongs to the `Account` collection class.

Regards

**Comment by hosberd** [comment]
Thank you! "Also there are some information about how requests are done now." where can I find the information?

**Comment by mgp25** [comment]
Hello @hosberd, 

you can find it in:

- [Wiki](https://github.com/mgp25/Instagram-API/wiki)
- [/examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

Regards

**Comment by hosberd** [comment]
@mgp25  thank you!:)
