### ISSUE TITLE
How to deal with `feedback_required` ?

### ISSUE THREAD

**Issue by Garbolino** [mgp25/Instagram-API#1552]
Last 2 days I'm getting this response when liking posts.

{
"json":{
"message":"feedback_required",
"spam":true,
"feedback_title":"Sorry, this feature isn't available right now",
"feedback_message":"An error occurred while processing this request. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.",
"feedback_url":"repute/report_problem/instagram_like_add/",
"feedback_appeal_label":"Report problem",
"feedback_ignore_label":"OK",
"feedback_action":"report_problem",
"status":"fail"
}
I was not able to simulate this response using the device.

Thanks for helping !

**Comment by robdiberlin** [comment]
I think:
This is a tempban or Ban during spam detection trough instagram. Not an API issue. I dont know what you are doing exactly... If you are on another IP than with your device, go over the IP you got that message.
But as mgp told several times, this is not library issue ;) search for "feedback_required".

**Comment by robdiberlin** [comment]
Instagram detected you as spam. If you are not on the same IP, try to connect trough your IP you get the message from!
But as always, go and search for "feedback_required"... it's not an library issue!

**Comment by Garbolino** [comment]
Thank you! I know it's not a library issue, but maybe the community knows how to solve this problem.

**Comment by mgp25** [comment]
The problem is solved by liking less 😇 If you use API is a correct way, you wont get that message.

Regards

**Comment by Garbolino** [comment]
Well, I'm trying to do the same number of likes per hour using the device and the API, under 40. I think this number is not that big and I do not get that response using the device, only with the API.

Thank you anyway.
