### ISSUE TITLE
How safe is it?

### ISSUE THREAD

**Issue by moerphie** [mgp25/Instagram-API#1553]
Is it save to use this without changing the sig key or device list?
I'm sure Instagram has an eye on it. And you maybe get banned easier - even if you're not doing bulk requests.

**Comment by mgp25** [comment]
Hello @moerphie,

**About signature key:**

The signature key is used to verify that all data that is sent to Instagram server hasn't been modified while transmiting it to the server. The signature key is static, each version has its own signature key. So if all people are using the same Instagram app version, all of them are using the same signature key. So this is ok.

**About device list:**

We have created a set of valid devices with it user agent, and all of them are working fine and are real data from real devices. Nevertheless, you can always add your own data, thats why we added this tool:

- [/devtools/checkDevices.php](https://github.com/mgp25/Instagram-API/blob/master/devtools/checkDevices.php)


**Can i get banned using this API?**

- Short answer: No. It is safe to use the API.

- Long answer: Only if you do spam or bulk request. But this is not allowed according to API terms and conditions.


Hope i answered all your questions/doubts.

Regards

**Comment by moerphie** [comment]
Thank you, I appreciate your fast answer. 
I'm going to try that great API.

**Comment by i3130002** [comment]
What about IP address? If I run this on a php server to give q public service over it, would it be safe without using proxy to do so ?

**Comment by mgp25** [comment]
Hello @i3130002,

It is relative to the activities you are going to do. If you do a fair use of it, you don't need to worry aboy anything. Also remember that for running a public service, you need to acquire a premium license or open source your project.

**Comment by i3130002** [comment]
Well I want to schedule posting and etc, but don't really sure about the users behavior!
Also can you tell me more about permium license?

**Comment by mgp25** [comment]
@i3130002 if its something for your personal usage, you don't need to. It is explained here: #1231 + if you have any question that is not mentioned there, you can always send me an email (found in my github profile).

**Comment by i3130002** [comment]
Thank you so much.
