### ISSUE TITLE
live video started, live video ended

### ISSUE THREAD

**Issue by matif2092** [mgp25/Instagram-API#1554]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hi,

I found example file [examples/realtimeClient.php](https://github.com/mgp25/Instagram-API/blob/master/examples/realtimeClient.php). I added my account username and password. I want to get trigger events `live-started`, `live-stopped` and other callback functions written in this file. When i execute this file it displays all debug information with status OK.

```php
$ig->setUser($username, $password);
$ig->login();
```

runs successfully and no exception occurs. Control goes inside this function 
```php
$rtc->init()->then(function (\InstagramAPI\Realtime $rtc) use ($loop) {});
```
But control does not go in any callback function and not in exception and sometimes when i hit this file it displays `Bad Gateway` error.

Please help me to get live video thumbnail and post id etc as i start a live video.

**Comment by mgp25** [comment]
Hello @matif2092,

i just tried the script and works perfectly with all the events:

```
[RTC] Live broadcast xxx has been started

[RTC] Live broadcast xxx has been stopped
```

Make sure you are using latest release as is everything correctly set up.

In case you don't know how to use the API or handle responses: 

- [Wiki](https://github.com/mgp25/Instagram-API/wiki)
- [/examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

Also, from the `realtimeClient.php` example:

```php

$rtc->on('live-started', function (\InstagramAPI\Realtime\Event\Payload\Live $live) {
    printf('[RTC] Live broadcast %s has been started%s', $live->broadcast_id, PHP_EOL);
});
```

You can extract all data from the broadcast from `$live` object.

Regards

**Comment by valga** [comment]
You must never run Realtime or Push from your browser. Use command line for that.

Also, there is no `init()` method in Realtime class, so that was the original reason of `Bad Gateway` error.

**Comment by matif2092** [comment]
@mgp25 and @valga i run file from putty using command "php realtimeClient.php" and i write response in a text file. I did echo for to check how many times my loop executes. I came to know that my loop executes only once. i am using following code.
$loop = \React\EventLoop\Factory::create();
    $rtc = new \InstagramAPI\Realtime($ig, $loop);
    $rtc->init()->then(function (\InstagramAPI\Realtime $rtc) use ($loop) {
        //printf('%c its here.', PHP_EOL);
        $c = 1;
        echo $c.'<br>'; 
        $c++;
        $rtc->on('live-started', function (\InstagramAPI\Realtime\Event\Payload\Live $live) {
            printf('[RTC] Live broadcast %s has been started', PHP_EOL);
        });
        $rtc->on('live-stopped', function (\InstagramAPI\Realtime\Event\Payload\Live $live) {
            printf('[RTC] Live broadcast %s has been stopped%s', $live->broadcast_id, PHP_EOL);
        });
        $rtc->on('error', function (\Exception $e) use ($rtc, $loop) {
            printf('[!!!] Got fatal error from Realtime: %s%s', $e->getMessage(), PHP_EOL);
            $rtc->stop(); 
            $loop->stop();
        });
        $rtc->start();
    }, function (\Exception $e) {
        printf('[!!!] Failed to init Realtime: %s%s', $e->getMessage(), PHP_EOL);
        exit(0);
    });

    $loop->run(); 
It returns a lot of json data without any error. My loop is executing only once as i run file from putty. Please let me know what i am doing wrong? Thanks.

**Comment by valga** [comment]
@matif2092 As I said before, there is no `init()` method in `$rtc`. Check the latest Realtime example.

Also I think that you have `display_errors` set to `off`, so you need to call `ini_set('display_errors', 1);` to display fatal errors.

**Comment by matif2092** [comment]
Hi valga,
I have updated my library with new code using composer and all its dependencies. realtimeClient.php file run successfully. It displays all debug data and at the end of data it displays following response.
[2017-09-19 09:01:34] rtc.INFO: Setting up reconnect timer to 1 seconds. [] []
[2017-09-19 09:01:35] rtc.INFO: Connecting to edge-mqtt.facebook.com:443... [] []
[2017-09-19 09:01:35] rtc.INFO: Connection has been established [] []
[2017-09-19 09:01:35] rtc.INFO: Connected to a broker [] []
[2017-09-19 09:01:35] rtc.INFO: Setting up keepalive timer to 900 seconds [] []
[2017-09-19 09:01:35] rtc.INFO: Subscribing to pubsub topics ig/live_notification_subscribe/5919039402, ig/u/v1/5919039402 [] []
[2017-09-19 09:01:35] rtc.INFO: Sending message {"sub":["ig/live_notification_subscribe/5919039402","ig/u/v1/5919039402"]} to topic /pubsub [] []
[2017-09-19 09:01:35] rtc.INFO: Publish flow completed [] []
[2017-09-19 09:01:35] rtc.INFO: Existing keepalive timer has been canceled. [] []
[2017-09-19 09:01:35] rtc.INFO: Setting up keepalive timer to 900 seconds [] []

After running this file from putty i start a live video from Instagram account. Some times this api captures live video and returns messages Live started. I do not know what is the issues now. Is it a cache problem or some other issue? 

I have also displayed errors like this.
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

There is no error at all in the code.
Please help me solving this issue. Yesterday it worked fine for an account. Today it is not working for the same account. Please explain this also.

const PROTOCOL_LEVEL = 3;

    const PROTOCOL_NAME = 'MQTToT';

    const KEEPALIVE = 300;
    const KEEPALIVE_TIMEOUT = 60;
