### ISSUE TITLE
How to find the media_id for hashtag?

### ISSUE THREAD

**Issue by sbaikov96** [mgp25/Instagram-API#1556]
How to find the media_id for hashtag? I am sure that before this code worked

```
$maxId = null;
do {
    $result = $ig->getHashtagFeed("Муром", $maxId); // поиск по хэштегу 
    $maxId = $result->getNextMaxId(); // следющая страница
    $items = $result->getItems(); //все посты сэтим тегом на странице
    //var_dump($items);
    foreach ($items as $key) {
      echo $key->getId() . "\r\n";
    }
} while ($maxId !== null);
    echo "end";
```

And now writes 

> Uncaught Error: Call to undefined method InstagramAPI\Instagram::getHashtagFeed()

**Comment by SteveJobzniak** [comment]
Привет 😆 

Read v3.0 release info: https://github.com/mgp25/Instagram-API/releases

It explains that all functions have been renamed, an dhwere you will find the new function names.

**Comment by solomax2014** [comment]
@SteveJobzniak, wow, russian word? :D I'm suprised

**Comment by SteveJobzniak** [comment]
@solomax2014 I just saw his Russian code comments, hehe. ;-) I understand a little.
