### ISSUE TITLE
Get user live with user id

### ISSUE THREAD

**Issue by mehmetbeyHZ** [mgp25/Instagram-API#1558]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Explanation of your issue goes here.

Please make sure the description is worded well enough to be understood, and with as much context and examples as possible.

We reserve the right to close your ticket without answer if you can't bother spending a few minutes to write a helpful report for us.

Get user live with user id how can do this?

**Comment by solomax2014** [comment]
```php
$live = $ig->story->getUserStoryFeed($userID)->getBroadcast();
```

**Comment by mehmetbeyHZ** [comment]
Thanks bro @solomax2014
