### ISSUE TITLE
error on edit profile

### ISSUE THREAD

**Issue by miladcoder** [mgp25/Instagram-API#1568]
dear developer
i get "400 invalid request" on EditProfile "accounts/edit_profile/"

please help me
thanks

**Comment by SteveJobzniak** [comment]
Please re-read the issue template and give us the information it asks for.

https://github.com/mgp25/Instagram-API/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by SteveJobzniak** [comment]
Will have to close this ticket tomorrow, if you don't provide the required debug info. Read the link above.
