### ISSUE TITLE
Clear Checkpoint - Putting mobile number to verify

### ISSUE THREAD

**Issue by infoquestsolutions** [mgp25/Instagram-API#157]
After using Instagram account it ask for adding a mobile number. I have tried intercept API calls but it doesnt work says. Cookies are not available . Please help me for this.

**Comment by mgp25** [comment]
Login in your mobile device and do it from there,  i'll eventually add this some day

**Comment by infoquestsolutions** [comment]
@mgp25  can you point me in right direction ?

**Comment by mkanker** [comment]
I guess he said you should do it manually from your mobile phone.

On Tue, May 3, 2016, 16:24 infoquestsolutions <notifications@github.com>
wrote:

> @mgp25 <https://github.com/mgp25> can you point me in right direction ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Instagram-API/issues/157#issuecomment-216637969>
>
-- 
Michel Ank
