### ISSUE TITLE
Not able to share post on instagram using Instagram-API

### ISSUE THREAD

**Issue by Ujjaval91** [mgp25/Instagram-API#1571]
Hello,

I am not able to share the post using the API.

When I try to post an error message will be displayed.
The displayed error like: "EnterSomething went wrong: Called user-related function before setting the current storage user."

Note: I have added my Instagram username and password in the configuration.

Please assist.

Thanks

**Comment by SteveJobzniak** [comment]
Hi. You're using v3.0 example code with your v2.0 copy of the library. Run `composer update -o` in your project to update to v3.0 of Instagram-API.

**Comment by Ujjaval91** [comment]
Thanks for your reply.

I have updated composer. but after updating another error is occurring.
The error is displaying like "**Class 'JsonMapper' not found**".
I have searched for the error and found a solution on  [https://github.com/mgp25/Instagram-API/issues/762#issuecomment-266050674].
But i can't figure it out that, where and what code needs to update.

Please assist.

Thanks

**Comment by SteveJobzniak** [comment]
Ignore that old ticket you found, it's wrong.

`Class 'JsonMapper' not found` simply means that you don't have JsonMapper installed. Which is very weird, because our composer-rules require it and will install it for you. So something is wrong with your composer-installation.

Try to fix it by running the installation again:

`composer require mgp25/instagram-php`
`composer update -o`

If that fails, you need to delete your `composer.lock` file and manually edit your `composer.json` file (in your project folder), to remove the `"mgp25/instagram-php":...` line from your `"require"` section, and then run the installation commands above again.

If that fails too, then you need to check your own code and perhaps try creating a brand new, empty project folder and doing the composer installation in there instead.

**Comment by Ujjaval91** [comment]
Hello,

**Thanks for the response.** 
I have updated library but now image size issue is occurring.

I saw some of your suggestion like "**Instagram places all media in 1:1 aspect ratio boxes (squares).**"
and used the image of 1:1 aspect ratio but error displaying like "**Something went wrong: Instagram only accepts story media with aspect ratios between 0.560 and 0.670.
 Your file "mypath/images/images.jpg" has a 1.0000 aspect ratio.**"

I also calculate image size of aspect ratios between 0.560 and 0.670 on google and found it should be **1280X720** and used it but again it not acceptable. and displaying the error like "Something went wrong: Instagram only accepts photos that are between 320 and 1080 pixels wide."

I have tried many images but all are not acceptable.

Can you please provide me exact size or ratio that will be acceptable. 

Thanks

**Comment by Ujjaval91** [comment]
Hello,

Finally, i have done it with "720X1280" image.
But now the issue is that the image is uploading on user stories and i need to upload it as a normal post which should be visible to all.

Please assist.

Thanks

**Comment by szokeptr** [comment]
@Ujjaval91 you are using the wrong method for uploading. [See example](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php).

**Comment by Ujjaval91** [comment]
Yes @szokeptr 
I have checked and update, Now it's working fine.

I just want to confirm that it is legal to post an image using this library.
Actually, i read some article that indicates that Instagram does not allow any 3rd party applications to upload photos through its API.

I just want to confirm.
Please assist.

Thanks

**Comment by SteveJobzniak** [comment]
Instagram knows about our library. They tolerate it as long as you do not use it to spam people.

There are only 2 main things they forbid this and all other 3rd party libraries to do:

- Uploaded media with hashtags will not appear when people search for those hashtags. They do that to prevent spammers from putting ads on all hashtags. The media will only be findable via people visiting your personal timeline, or being your followers (then they get notifications if they have enabled that, and they will see you in their news feed).
- You cannot increase video views via this API.

**Comment by Ujjaval91** [comment]
ok, thanks for your suggestion.

I am using this library in my project.
But i need to comment/hide response.

Can you please suggest my name where i can comment that?

**Comment by SteveJobzniak** [comment]
@Ujjaval91 What are you talking about? The debug that shows the HTTP data and responses?

Just use `$debug = false` parameter of `InstagramAPI\Instagram()` constructor.
