### ISSUE TITLE
Add Location Tag to story

### ISSUE THREAD

**Issue by tatusea** [mgp25/Instagram-API#1573]
I've tried adding location to a story but I have not been able to.

```php
$result = $ig->location->search('40.7439862','-73.998511');
$location = $result->venues[0];
$locationname = $result->venues[0]->name;

$metadata = [
    'locations' => [
        // Note that you can add more than one hashtag in this array.
        [
	    'location'         => $location,
            'x'                => 0.5, // Range: 0.0 - 1.0
            'y'                => 0.5, // Note that x = 0.5 and y = 0.5 is center of screen.
            'width'            => 0.24305555, // Percentage: 0.0 - 1.0 0,24305555
            'height'           => 0.07347973, // Percentage: 0.0 - 1.0
            'rotation'         => 0.0,
            'is_sticker'       => false, // Don't change this value.
            'use_custom_title' => false, // Don't change this value.
        ],
        // ...
    ],
    'caption' => "#$locationname",
];

```

Is this possible to do?

Thank you very much, excuse my English.

**Comment by SteveJobzniak** [comment]
Hi. That's not possible. We support location only for non-story media.

- We will need full research about the API calls the Android app does when attaching locations to stories.
- `Utils::buildMediaLocationJSON()` will need to be refactored turn it into two functions. One which validates that a location is a non-Facebook location. Another which builds media location JSON.
- We already have a `Utils::throwIfInvalidStoryHashtags()`, and we will need another one called `Utils::throwIfInvalidStoryLocation()`. And it needs to call the function to validate that the location is a non-Facebook location, and then it needs to do code similar to the hashtag function which verifies that all fields are properly provided.
- We will need to add that location-support to the story-configurator functions all over src/Request/Internal.php.

This is a big job, and it's a very low-priority feature. If anyone wants to help with any of these steps, please let us know.

**Comment by solomax2014** [comment]
@SteveJobzniak, maybe you will make an announcement about having a rest? Because I feel that there will be many questions and issues.

**Comment by mgp25** [comment]
@solomax2014 no announcement is required. We (collaborators, all of us) will continue solving and adding things but our on time as @SteveJobzniak has said. It is okay to have issues and questions openned. Most of them are already solved it and there is a very huge community that will help for sure.

Thats it

**Comment by mgp25** [comment]
This is almost finished. It will be released this weekend.

Regards

**Comment by tatusea** [comment]
Perfect, they are idols !!

**Comment by mgp25** [comment]
Hello @tatusea,

you can now add location sticker to story media. The example has been updated:

- [uploadStory.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStory.php)

Related changes/updates: https://github.com/mgp25/Instagram-API/commit/43a81748b211072ffe1b3f0393d937f2672b0dab https://github.com/mgp25/Instagram-API/commit/383ea12573c6db37d7a5a994ea9a4bb23065eb50 and https://github.com/mgp25/Instagram-API/commit/6422d4ddf93cf8b0e5177eb30cda37e7191d73aa

Regards
