### ISSUE TITLE
Requests without authorization

### ISSUE THREAD

**Issue by kozintsev** [mgp25/Instagram-API#1575]
## Prerequisites

What requests I can perform if I do not fulfill the authorization?
Generally, can I perform requests without performing authorization?

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

**Comment by mgp25** [comment]
Hello @kozintsev ,

This API requires authentication to make any of the available requests. Once you have logged in, you don't need to authenticate again, you can reuse your session.

Regards
