### ISSUE TITLE
Hi I guess the account creation has been removed?

### ISSUE THREAD

**Issue by halitb** [mgp25/Instagram-API#1576]
Hi I guess the account creation has been removed?

**Comment by mgp25** [comment]
Your guess is right

Regards

**Comment by SteveJobzniak** [comment]
Yes, because there's almost zero legal uses for it. Everyone using the API for legal purposes has accounts already. Except spammers. Spammers want to create more accounts. And we hate spammers. 🤣

**Comment by halitb** [comment]
yanıtlar için teşekkür ederim. Ben spam için kullanmıyorum :)

**Comment by SteveJobzniak** [comment]
Good. ;)
