### ISSUE TITLE
Do not work through the proxy

### ISSUE THREAD

**Issue by alexandrKulik** [mgp25/Instagram-API#1577]
When proxy is enabled
$ ig-> setProxy ('socks5: // user: pass @ iporhost: port');
Does not allow to put like
Gives an error message
InstagramAPI \ Response \ GenericResponse: Feedback required.
Proxy working to remove the likes sign all works, like just does not work. What can be?

**Comment by akulyk** [comment]
Maybe wrong a login or password

**Comment by akulyk** [comment]
I am also Alexader Kulyk )))

**Comment by SteveJobzniak** [comment]
Enable `$debug` to see the full error message. You will see something like this:

`{"message":"feedback_required","spam":true,"feedback_title":"You\u2019re Temporarily Blocked","feedback_message":"It looks like you were misusing this feature by going too fast. You\u2019ve been blocked from using it.\n\nLearn more about blocks in the Help Center. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.","feedback_url":"WUT","feedback_appeal_label":"Report problem","feedback_ignore_label":"OK","feedback_action":"report_problem","status":"fail"}`

The reason for your situation is one of these:

1. The proxy you are using is blocked by Instagram as a "spammer proxy".
2. You are trying to do bad things too fast (such as spammer-actions: liking / following rapidly).

**Comment by alexandrKulik** [comment]
The proxy server is not blocked by instagrams. I checked it through the web version of the instagrams. It makes it OK to put the likes, and I do not spam trying to put 1 from my page, if there is no proxy, then I turn on the proxy

**Comment by SteveJobzniak** [comment]
Then enable `$debug` and show us the full error message (as in my examples above). The full message `{...}` will show what Instagram says is wrong.

**Comment by alexandrKulik** [comment]
That's what it gave out, but if I do it without proxy then it's OK, I checked it all on a new proxy bought purely for the test to find out the reason and issue this. It seems that just through the proxy do not work huskies

{"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "feedback_appeal_label": "Report problem", "feedback_ignore_label": "OK", "feedback_action": "report_problem", "status": "fail"} Something went wrong: InstagramAPI\Response\GenericResponse: Feedback required.

**Comment by SteveJobzniak** [comment]
`"spam": true` = Instagram thinks you are a spammer.

If it only happens when you use the proxy, then it's the proxy's fault.

**Comment by alexandrKulik** [comment]
And it can not be that the instream in the likes has learned to understand the proxy server or not and if so it blocks?

**Comment by SteveJobzniak** [comment]
Nah. Instagram's anti-spam is advanced. They use many parameters. So even if they know you are using a "bad proxy" they can allow safe things, but disallow other unsafe "spammy" things (liking, following, commenting).

Many spammers live in this world and they all use proxy services. Most open and most commercial proxy IPs are marked as "bad spammers" already by Instagram. So it knows that you're coming from a "bad proxy". ;-O

**Comment by alexandrKulik** [comment]
Thank you for everything

**Comment by SteveJobzniak** [comment]
No problem. Good luck.

**Comment by yoko83** [comment]
banned permanent?

**Comment by mobbidigital** [comment]
I'm having this error and I can not fix it, instagram platform
print http://prntscr.com/ih0arz

**Comment by SpaceSheepli** [comment]
@alexandrKulik @ghost is the account banned permanent?

**Comment by alicompu** [comment]
hi 
it's mine worked. with this code.
` $ig->media->comment($media->getMedia()->getId(), "Hello world");
sleep(20);`
