### ISSUE TITLE
Project Task Tracker

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1578]
We now have a task tracker, where contributors can look at the list of available work:

- https://github.com/mgp25/Instagram-API/projects

High-quality code contributions are greatly appreciated, since we are a small team and are working on this project _when we feel like it_ in our spare time. The API is already _incredibly complete_ and massive as of v3.0 stable's release. Everything _important_ has been fully implemented already.

Just because some "minor extra feature" is listed in the task manager _doesn't mean_ that we'll actually work on it. It just means it's available for work. But whether it gets added or not depends on us having time and energy _and_ that we actually _feel like_ using our free time for sitting down and programming that small feature (which we in almost 100% of all cases aren't going to use ourselves), instead of doing something _better_ with our spare time, like... going outdoors and kissing a girl! 🤣 

If you really need a specific listed feature "right now!", then the _best_ way to get something done is to jump in and code it yourself, if you have the skills to implement it properly. If so, then we'll be very happy to merge your pull request, as long as it adheres to the [coding quality standards](https://github.com/mgp25/Instagram-API/blob/master/CONTRIBUTING.md) of the project!

**Comment by mgp25** [comment]
This announcement will be closed tomorrow at 00:00.
