### ISSUE TITLE
Login only once and using session without password for a long period

### ISSUE THREAD

**Issue by vnikolay** [mgp25/Instagram-API#1579]
Can we login only once and use session without password for a long period (2-3 weeks, for example)? To login only by login name, or we have to pass password to login function every time?
Thank you!

**Comment by mgp25** [comment]
Hello @vnikolay,

When you do:

```php
$ig->login($username, $password);
```

You only authenticate once, and the followings logins, API will be reusing your session. In case you want to authenticate again:

```php
$ig->login($username, $password, true);
```

In the case above, you are forcing the API to authenticate again, so session will be removed and create a new one.

Although password is not required when the session is resued, it is recommended in case an authentication is required.

Hope i have answered your questions.

Regards

**Comment by vnikolay** [comment]
Thanks, I mean opposite thing:
The source file says:
You MUST run this function EVERY time your script runs! It handles automatic session
     * resume and relogin and app session state refresh
So it says, that login function does relogin. And I wonder, how long I can use session without relogin (do not use password)?

**Comment by mgp25** [comment]
Hello @vnikolay,

Yes, as the source says, you **must** run the call every time in your script, this guarantees the correct performance of the API. But calling `login()` doesn't mean to always authenticate. If you are already authenticated, it will only call some requests to emulate device (resume session).  If you don't force a login (re-authenticate), session will last some months (based on the cookie).

**Comment by vnikolay** [comment]
And what should I pass instead of password (this param is requirement) - any string (to use last session only)? Will that work if I pass different logins (change accounts)?

**Comment by mgp25** [comment]
@vnikolay 

> And what should I pass instead of password (this param is requirement)

The password! Although it will work with other string, you should use the password.

> Will that work if I pass different logins (change accounts)?

Yes, if you are already logged in.

You could save 5 hours waiting if you have tried before opening the issue :/

Regards
