### ISSUE TITLE
Instagram 500 Error

### ISSUE THREAD

**Issue by NilakArgento** [mgp25/Instagram-API#1580]
The last 3 days a got an error from instagram when i try to login
Status: 500 
Body: Oops, something went wrong instagram
For example from 10 tries, 8 passed and 2 not .I want to know this problem appear only for me or for something else ?

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

**Comment by mgp25** [comment]
Hello @NilakArgento,

That is answered in the [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ)

Please, make sure to read the [wiki](https://github.com/mgp25/Instagram-API/wiki) before opening a new issue.

Regards
