### ISSUE TITLE
learn the state of the mention

### ISSUE THREAD

**Issue by alexandrKulik** [mgp25/Instagram-API#1582]
Prompt in the updated version it is possible as that to learn a condition of that that there is a new mention of an account of the person which on a skin, hotjaby a status yes or not
It is possible to get new and old information through getRecentActivityInbox, but the only problem is that when the method is requested on the account, the mentioned references are marked, and I need to notify that there is, and when I open then I already put a mark about reading, as on the instagram itself.
Here is the screen: http://SSMaker.ru/935ec219/

P.S. The new library is super, many new features

**Comment by SteveJobzniak** [comment]
You already asked us this question baout `getRecentActivityInbox()` and I gave a perfect, detailed answer:

https://github.com/mgp25/Instagram-API/issues/1443

But if you want realtime notifications, like the app does it, look at the `examples/` folder for the new Realtime and Push feature examples. You will need to run a single script forever (don’t close it), so that it gets pushes/realtimes, without having to call `getRecentActivityInbox()`.

**Comment by valga** [comment]
It is possible via Push client, as it notifies you about mentions: https://github.com/mgp25/Instagram-API/blob/f5f7b961b9ded5025be2cdecc7a8633114bde2aa/src/Push.php#L21 Also Push notification object has a `BadgeCount` object in its payload: https://github.com/mgp25/Instagram-API/blob/f5f7b961b9ded5025be2cdecc7a8633114bde2aa/src/Push/Payload/BadgeCount.php#L36-L44 As you can see, there are counters for direct and activities badges in JSON data.

A note on Realtime&Push:
1. You can run Realtime and Push clients in one script: just attach them to the same loop.
2. The app runs Realtime client only when in foreground, while Push is persistent.

**Comment by SteveJobzniak** [comment]
> You can run Realtime and Push clients in one script: just attach them to the same loop.

That’s cool, I didn’t know that.

**Comment by valga** [comment]
> That’s great, I didn’t know that! :-)

There is another "hidden" feature: you can run Push and/or Realtime clients for multiple accounts in the same script. The number of clients is limited by language-specific stuff, see [a discussion on it](https://externals.io/message/100189).

**Comment by SteveJobzniak** [comment]
@valga Oh, that's fantastic too. Much less overhead from less PHP processes!

But the link you posted is something else? It's about `debug_backtrace()`. ;-)

**Comment by valga** [comment]
@SteveJobzniak It's about exception containing full stack trace (including args), and that could lead to a lot of cyclic references being created. Cyclic references can be cleaned only with GC, and GC has some cons:
1. It stops everything when running.
2. It consumes resources. There more objects you have, the more time it runs.
3. It has a limit on root buffer size, so it could just stop working at some point.

Click on a link from the last post from that discussion to see why it is related to us.

**Comment by SteveJobzniak** [comment]
Ah, I see it now. So the longer the script runs, the more circular references and the more RAM usage, until it crashes, and that happens sooner with more accounts. Ouch. ^_^ The fun times of programming. And they can't even manually `delete()` those objects because the user may be using them. Double-ouch... ;-)

**Comment by valga** [comment]
@SteveJobzniak Actually, you can add a periodic timer that runs GC like every 5 minutes, and it solves the issue with circular references. But, if you have a lot of objects, root buffer could overflow, and GC will just stop working (see [an explanation on disabling GC in composer](https://news.ycombinator.com/item?id=8686934)).

Also, it should be noted, that a lot of circular references are being produced with exceptions. So if you have  no errors (like connection timeouts, etc), there is no garbage produced at all.

**Comment by SteveJobzniak** [comment]
Ah, so manual GC in PHP understands and clears circular references and just has to be manually triggered periodically. Great, so if anyone asks about having multiple accounts on the same loop, I will point them to this thread. Thanks for the explanation! 👍

**Comment by SteveJobzniak** [comment]
@valga Btw, check this out, hopefully this idea will help you out: https://github.com/mgp25/Instagram-API/pull/1534#issuecomment-331621255

**Comment by valga** [comment]
> Ah, so manual GC in PHP understands and clears circular references and just has to be manually triggered periodically.

Moreover, GC in PHP clears **only** circular references. So you could disable it completely to save some resources (just like Seldaek did with composer), but only if you have no circular references.

**Comment by SteveJobzniak** [comment]
@valga Just FYI, I've added the Realtime/Push tips to the FAQ:

https://github.com/mgp25/Instagram-API/wiki/FAQ#is-it-possible-to-run-the-realtime-and-push-clients-in-a-single-script

👍
