### ISSUE TITLE
Postdata Empty on Upload Photo

### ISSUE THREAD

**Issue by osyduck** [mgp25/Instagram-API#1593]
Hello Sir, I will ask something. Why i didn't get postdata from uploading a picture? here is debug output

```
POST:  https://i.instagram.com/api/v1/upload/photo/
--
  | → 44.92kB
  | ← 200 	 46B
  | RESPONSE: {"upload_id": "1506676123671", "status": "ok"}
```
where is DATA ? thanks, have a nice day :)

**Comment by mgp25** [comment]
Hello @osyduck,

The post data is the raw binary data of the photo (no need of printing out that to CLI). What it shows in the debug log instead is how many data was uploaded. In your case `44.92kB`.

Regards

**Comment by ialireza** [comment]
POST: https://i.instagram.com/api/v1/upload/photo/ → 30.74kB ← 400 58B RESPONSE: Something is wrong. Please check your input and try again.
