### ISSUE TITLE
Allow to use Custom IG_SIG_KEY

### ISSUE THREAD

**Issue by ddzobov** [mgp25/Instagram-API#1594]
Can you add feature to configure custom IG_SIG_KEY in constructor?

**Comment by mgp25** [comment]
Hello @ddzobov,

that is a horrible idea, and i'm going to tell the reasons:

- Version and signature aswell as other constants are strictly related, so changing it, will break API or send wrong data to Instagram Server.
- Every version can have changes in flow, endpoints or params, if you are not checking every single detail, then it is wrong.

So answering to your question, no, we won't do that. We will be updating Singature and version, when other critical data is updated before.

Regards.
