### ISSUE TITLE
Like media has Error

### ISSUE THREAD

**Issue by amirkhh** [mgp25/Instagram-API#1595]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
$ig = new \InstagramAPI\Instagram(true, true);

$ig->login('username', 'password'); // Will resume if a previous session exists.
        
$like = $ig->media>like('1547436459727117644_4247216425');

var_dump($like);
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

InstagramAPI\Exception\FeedbackRequiredException

InstagramAPI\Response\GenericResponse: Feedback required.
```
---

### Describe your issue

Explanation of your issue goes here.

All of methods is work fine except like method, when I want to like a media I get above error. 

What do you think about that error ?

We reserve the right to close your ticket without answer if you can't bother spending a few minutes to write a helpful report for us.

**Comment by mgp25** [comment]
Hello @amirkhh,

next time use the default debug built-in system instead of posting the exception.

That happens when you abuse of the like requests or your account is flagged (detected as bot and unwanted behavior). Not API issue.

Regards
