### ISSUE TITLE
urlgen cookie

### ISSUE THREAD

**Issue by mme76** [mgp25/Instagram-API#1596]
Is anybody familiar with this cookie? Instagram servers started setting it earlier this month and it appears to contain a list of IPs the account logged from, among other things. It's not entirely clear to me at this point if the app somehow uses the contents of the cookie, to generate certain URL request parameters, as the name might suggest. In that case, this API would need to elaborate it. Or maybe it's somehow related to spam protection (strange they would send out that info, however, and for what purpose?).

**Comment by mgp25** [comment]
Hello @mme76,

that is not API related (at this moment).

Regards
