### ISSUE TITLE
How can I get $account when I receive a new message?

### ISSUE THREAD

**Issue by hosberd** [mgp25/Instagram-API#1597]
How can I get `$account` when I receive a new message? Only `$thread->inviter->username`?

```php
		$accounts = array('test_account' => '123456','test_account2' => '123456');
		$loop = \React\EventLoop\Factory::create();
		foreach ($accounts as $account => $password) {
			$api = new \InstagramAPI\Instagram($debug, $truncatedDebug);
			try {
			    $api->login($account, $password);
			} catch (\Exception $e) {
			    echo 'Something went wrong: '.$e->getMessage()."\n";
			    exit(0);
			}

			$this->fetchDirectMessages($debug, $api, $loop);

		}
		$loop->run();
```

**Comment by mgp25** [comment]
Hello @hosberd,

You can use events, for example:


```php
$push->on('direct_v2_message', function (\InstagramAPI\Push\Notification $push) {
   echo 'Message received';
});
```

And then printing the account or similar.

Example: [pushReceiver.php](https://github.com/mgp25/Instagram-API/blob/master/examples/pushReceiver.php)

Regards

**Comment by hosberd** [comment]
@mgp25 thanks!

**Comment by Niall7459** [comment]
@mgp25 Hello, thanks for the code snippet, Is there any way we can retrieve the content sent in the dm, e.g the user and message content.

I can see this in the example file.
`printf(
        'Thread ID: %s. Thread item ID: %s.%s',
        $push->getActionParam('id'),
        $push->getActionParam('x'),
        PHP_EOL
);`


Are we able to fetch an object from this id? 

Thanks
