### ISSUE TITLE
i can't get list of followers with pagination

### ISSUE THREAD

**Issue by antosha33** [mgp25/Instagram-API#1599]
it seems to me that pagination isn't working at some request. For example, I get first 200  of 4000 followers
and pagination stop. Can anybody chek it on his own script?

**Comment by mgp25** [comment]
Hello @antosha33,

This is a duplicate question. Please take some time to read:

- [Closed issues](https://github.com/mgp25/Instagram-API/issues?utf8=%E2%9C%93&q=pagination%20followers)
- [Wiki](https://github.com/mgp25/Instagram-API/wiki)
- [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ)


**Related:** https://github.com/mgp25/Instagram-API/wiki/FAQ#i-can-only-see-some-followers

Regards
