### ISSUE TITLE
getUserFeed return only 12 or 18 items

### ISSUE THREAD

**Issue by wade2k** [mgp25/Instagram-API#160]
function getUserFeed return only 12 or 18 items without max_id

**Comment by borodulin** [comment]
max_id = jsonPath('$.items[(@.length-1)].id').stringValue()

**Comment by wade2k** [comment]
thnx

**Comment by MaximMikulich** [comment]
@borodulin это чтоб отобразить все записи?)

**Comment by mgp25** [comment]
@MaximMikulich niet no russian, if you want to write do it in english

**Comment by MaximMikulich** [comment]
@mgp25 ok)

**Comment by passion1989** [comment]
@mgp25 hi, is there any API for getting recent media of current user?
GetUserFeed API is same with it?
Look forward to your reply
