### ISSUE TITLE
media->like module_name list incomplete & default params incorrect

### ISSUE THREAD

**Issue by mme76** [mgp25/Instagram-API#1602]
Since the purpose of the various `module_names` in `Media::like()` weren't entirely clear to me nor documented in the code, I decided to capture various requests, in different scenarios, to better understand what parameters need to be used and when. In order to be consistent with the latest version of the API, all the info below pertains specifically to the _10.33.0_ APK on Android. This is the summary of what I found out.

Depending on how we reached a certain post that we like (from our feed, from the explore tab, from user's profile...), a different module_name parameter is sent with the POST request. In addition to that, different module_names can have additional parameters (such as username) inside the `signed_body`.

**1) LIKES FROM THE EXPLORE TAB:**
By the default, the current code sends the `feed_contextual_post` module_name, which implies we liked the post from the Explore tab (the posts that Instagram "suggests" to you, when you press the Lens/Search icon). I'm not sure most users of the API are aware of that, but I bet that's not the behavior most people intended. In addition to that and, MOST IMPORTANTLY, simply calling `media->like($mediaId)` with the current code sends the default `feed_contextual_post` module_name parameter but NO explore_source_token! This additional parameter MUST be passed in the `$extraData` array or ALL LIKES will look completely fake to Instagram! This can happen even with just one like, so it's not related to spammers. As a reference, this is the `signed_body` that the app sends, when liking in this case (in this and all subsequent cases, the post was double tapped, hence the `d=1`):

`signed_body=xxxxx.{"explore_source_token":"...","module_name":"feed_contextual_post","media_id":"1619775657398984820_1425145034","_csrftoken":"...","radio_type":"wifi-none","_uid":"...","_uuid":"..."}&ig_sig_key_version=4&d=1`

**2) LIKES FROM THE TIMELINE:**
This very common case is currently not documented by the API. The module_name used is "feed_timeline" and this is the complete signed body:

`signed_body=xxxxx.{"module_name":"feed_timeline","media_id":"1619159512579923216_12223257","_csrftoken":"...","radio_type":"wifi-none","_uid":"...","_uuid":"..."}&ig_sig_key_version=4&d=1`

**3) LIKES FROM A USER PROFILE**
This very common case gets a bit more complicated and is currently completely mishandled by the API. First of all, we have to distinguish between the List View (when all user posts are shown vertically, one at a time, like in the timeline) and the Grid View (when user posts are shown in the typical 3x photo grid).

**3a) LIKES FROM A USER PROFILE - LIST VIEW**
The module_name used is `profile` and the app also sends the additional parameters username and user_id:

`signed_body=xxxxx.{"module_name":"profile","media_id":"1619159512579923216_12223257","_csrftoken":"...","username":"jessicaalba","user_id":"12223257","radio_type":"wifi-none","_uid":"...","_uuid":"..."}&ig_sig_key_version=4&d=1`

**3b) LIKES FROM A USER PROFILE - GRID VIEW**
If we click on a post, while on a user profile in grid view, and then like the post, the module_name used depends on the type of post:

```
media_view_profile - for carousels
photo_view_profile - for photos (the only one currently supported)
video_view_profile - for videos
```

In all cases, the app also sends the additional parameters `username` and `user_id`:

`signed_body=xxxxx.{"module_name":"media_view_profile","media_id":"1619159512579923216_12223257","_csrftoken":"...","username":"jessicaalba","user_id":"12223257","radio_type":"wifi-none","_uid":"...","_uuid":"..."}&ig_sig_key_version=4&d=1`

`signed_body=xxxxx.{"module_name":"photo_view_profile","media_id":"1605103917648313021_4536924562","_csrftoken":"...","username":"cristianogenius","user_id":"4536924562","radio_type":"wifi-none","_uid":"...","_uuid":"..."}&ig_sig_key_version=4&d=1`

`signed_body=xxxxx.{"module_name":"video_view_profile","media_id":"1614191386377565503_12223257","_csrftoken":"...","username":"jessicaalba","user_id":"12223257","radio_type":"wifi-none","_uid":"...","_uuid":"..."}&ig_sig_key_version=4&d=1`

**4) LIKES FROM A HASHTAG SEARCH**
If we search for a hashtag, then click on a result and like it, the app uses the `feed_contextual_hashtag` module_name, in addition to the `hashtag` additional parameter (currently wrong in the code):

`signed_body=xxxxx.{"module_name":"feed_contextual_hashtag","media_id":"1619586962237333172_451699044","_csrftoken":"...","radio_type":"wifi-none","_uid":"...","_uuid":"...","hashtag":"instagram"}&ig_sig_key_version=4&d=1`

**5) LIKES FROM A PLACES SEARCH**
If we search for a location, then click on a result and like it, the app uses the `feed_contextual_location` module_name, in addition to the `location_id` additional parameter (also currently wrong in the code):

`signed_body=xxxxx.{"module_name":"feed_contextual_location","media_id":"1619901575556008954_13048583","_csrftoken":"...","radio_type":"wifi-none","_uid":"...","_uuid":"...","location_id":"212988663"}&ig_sig_key_version=4&d=1`

**6) LIKES FROM THE FOLLOWINGS' ACTIVITY FEED**
If we go to the followings' activity feed (the page that says "xyz liked abc's post", "xyz liked 5 posts", "xyz started following abc" and so on...), click on a post liked by one of our followings and then like it, we have 2 cases:

**6a) LIKES FROM THE FOLLOWINGS' ACTIVITY FEED - FOLLOWING LIKED ONE POST**
If the user only liked one post ("xyz liked abc's post"), then the app uses module_name "newsfeed":

`signed_body=xxxxx.{"module_name":"newsfeed","media_id":"1619253667884716620_5991824956","_csrftoken":"...","radio_type":"wifi-none","_uid":"...","_uuid":"..."}&ig_sig_key_version=4&d=1`

**6b) LIKES FROM THE FOLLOWINGS' ACTIVITY FEED - FOLLOWING LIKED MANY POSTS**
If the user liked multiple posts ("xyz liked 5 posts"), then the app uses module_name "feed_contextual_newsfeed_multi_media_liked":

`signed_body=xxxxx.{"module_name":"feed_contextual_newsfeed_multi_media_liked","media_id":"1618653764544267352_195298654","_csrftoken":"...","radio_type":"wifi-none","_uid":"...","_uuid":"..."}&ig_sig_key_version=4&d=1`

**HEADERS**
Note that, besides the differences described above, all requests have the same structure:

```
Method: POST
URI: https://i.instagram.com/api/v1/media/..._.../like/
Body: signed_body=...
Header: [X-IG-Connection-Speed] = [890kbps]
Header: [X-IG-Connection-Type] = [WIFI]
Header: [X-IG-Capabilities] = [3boDAA==]
Header: [User-Agent] = [Instagram 10.33.0 Android (...; en_US)]
Header: [Accept-Language] = [en-US]
Header: [Connection] = [Keep-Alive]
Header: [Cookie] = [is_starred_enabled=yes; sessionid=...:{"_auth_user_id":...,"_auth_user_backend":"accounts.backends.CaseInsensitiveModelBackend","_auth_user_hash":"","_token_ver":2,"_token":"...:...:...","_platform":1,"last_refreshed":...}; mid=...; ds_user=...; ds_user_id=...; csrftoken=...; igfl=...; rur=PRN; urlgen={\]
```

**SUMMARY**
We need to update the code to correctly cover all cases above, or run the risk of potentially getting banned, even after one like. I also strongly recommend we change the default case to something else, perhaps "profile" and clearly document and detect that all correct `$extraData` parameters have been passed, instead of silently sending malformed requests, with missing or wrong parameters. Finally, I recommend we rename the $extraData parameter names to consistently match the actual parameters (`$extraData['user_id']` instead of `$extraData['userid']` and `$extraData['explore_source_token']` instead of `$extraData['exploreToken']`)

**Comment by mgp25** [comment]
Hello @mme76,

thanks for your detailed post. We are aware of this, and was discussed in the past. Right now the API as it is, is safe to use.

However, im going to add the information in the wiki so all users can't misunderstood how the function works.

After i edited the code and added all the documentation ill close the issue, meanwhile im leaving this open. Probably it will be done tomorrow morning.

Regards

**Comment by mgp25** [comment]
**Update**
 
Code is updated: https://github.com/mgp25/Instagram-API/commit/daeff0913539cc55b76362759f751f5a0eb7a911

Im going to add documentation to the wiki and this will be done! 😄

**Comment by mme76** [comment]
Great!

The names of the extra parameters in the hashtag and location search cases are still incorrect however.

**Comment by mgp25** [comment]
Hello @mme76 ,

Sorry for that! I forgot to change that. I have fixed it.

Regards

**Comment by valga** [comment]
@mgp25, @mme76 We are sending some additional HTTP headers that are missing in your request dump https://github.com/mgp25/Instagram-API/blob/53e0423358715db015c2d14c778bc02164478f74/src/Client.php#L763-L770
such as `X-FB-HTTP-Engine`, `Accept` and `Accept-Encoding`. Are they deprecated in recent app versions?

**Comment by mgp25** [comment]
@valga im going to recheck it, but back when i checked it, was okay. Nevertheless instead of changing this, we should look for the future version where we need to change headers and tweak a little the http interface to calculate the bytes headers.

Im going to post headers (apk) of current API version in some minutes.

**Comment by valga** [comment]
@SteveJobzniak Since you are being around, here is some info on new headers:
`X-IG-Bandwidth-TotalBytes-B` => total bytes received per session,
`X-IG-Bandwidth-TotalTime-MS` => total time spent on receiving responses per session,
`X-IG-Bandwidth-Speed-KBPS` => rolling average for previous 2 fields (-1 by default).

The app counts just responses with size >= 50000 bytes and time > 50ms. Any thoughts on implementing this? I don't think that random values are ok (as done with `X-IG-Connection-Speed` header).

**Comment by mgp25** [comment]
@valga 

**Headers**

"X-IG-Connection-Speed: 479kbps"
"X-IG-Bandwidth-Speed-KBPS: 607.435"
"X-IG-Bandwidth-TotalBytes-B: 4169152"
"X-IG-Bandwidth-TotalTime-MS: 4804"
"X-IG-Connection-Type: WIFI"
"X-IG-Capabilities: 3boDAA=="
"X-IG-App-ID: abc067123352xyz"
"User-Agent: Instagram 18.0.0.14.85 Android (...)"
"Accept-Language: en-US"
"Connection: Keep-Alive"
"Cookie: ....."

**Comment by valga** [comment]
@mgp25 So, they are deprecated. Also, is `X-IG-App-ID` header dynamic?

**Comment by mgp25** [comment]
@valga 

> X-IG-App-ID header dynamic?

Nope, it seems like a static ID. I can check how it is calculated.

**Comment by mgp25** [comment]
@valga the value is hardcoded in the apk along with other data:

```
e = "com.instagram.fileprovider";
f = "567067343352427";
g = "124024574287414";
h = "Instagram";
i = "f249176f09e26ce54212b472dbab8fa8";
```

**Comment by SteveJobzniak** [comment]
@valga:

> Since you are being around, here is some info on new headers:
> `X-IG-Bandwidth-TotalBytes-B` => total bytes received per session,
> `X-IG-Bandwidth-TotalTime-MS` => total time spent on receiving responses per session,
> `X-IG-Bandwidth-Speed-KBPS` => rolling average for previous 2 fields (-1 by default).

> The app counts just responses with size >= 50000 bytes and time > 50ms. Any thoughts on implementing this? I don't think that random values are ok (as done with X-IG-Connection-Speed header).

The `Client` class should handle all of that.

Here are my ideas:

### Client::updateFromCurrentSettings()

```php
$this->_totalTime = 0;
$this->_totalBytes = 0;
```

### Client::api()

```php
$start = microtime(true);
// <do the API call..., and send current values in TotalBytes/TotalTime headers>
$elapsed = ceil(1000 * (microtime(true) - $start));
$bytes = <get the size from the Guzzle response>
if ($bytes >= 50000 && $elapsed >= 50) {
    $this->_totalTime += $elapsed;
    $this->_totalBytes = += $bytes;
}
```

As for the rolling average "KBPS": Those are possible to calculate with standard algorithms. We should do what the app's APK does.

### Only remaining question...

What is a "session"? If they mean since the user's last full `login()`, then we need to store totalTime and totalBytes in the user settings storage. And we need to always reset them to 0 if the user does a full login again.

But constantly tracking time/bytes in the settings storage would cause an insane amount of disk/database-writes and JSON-serialization, since those settings would change after *every* `api()` call.

So instead, do NOT constantly write them to storage. Do something like what I did for cookie-saving. Search for `saveCookieJar` in the source code (`ag saveCookieJar -C2` shows all of them). Cookies are saved at login, at logout, at user-storage closing, and at periodic intervals during Client's work.

A simple adaptation would be to rename `Client::COOKIE_AUTOSAVE_INTERVAL` to something like `STATE_AUTOSAVE_INTERVAL` and using that interval (and the other triggers in the rest of the source code) to save the Cookies AND the totalBytes + totalTime.

Anyway, those are some ideas for how to implement the new system...

**Comment by rafaelwedbiz** [comment]
Hi, im facing same problem about likeban, im doing everything right search hash tag then make like with properly parameters but im not sending these headers:

X-IG-Bandwidth-Speed-KBPS
X-IG-Bandwidth-TotalBytes-B
X-IG-Bandwidth-TotalTime-MS

could it be the reason cuz im still geting likeban?

I've tested everything about proxies, I know it is not a proxy problem cuz i tried private,dedicated,many subnets,residential ipv4/ipv6,rotate ... and in the end i get same result likeban, i rly think it is about data send or headers but can't figured it out.

**Comment by valga** [comment]
@SteveJobzniak Not sure if you will see this, but it is still useful info.

> What is a "session"?

The app starts new session after being opened by user. So we should reset the numbers in our session refreshment code.

> But constantly tracking time/bytes in the settings storage would cause an insane amount of disk/database-writes and JSON-serialization, since those settings would change after every api() call.

Nope. Because the app ignores small and fast responses. I can't say for sure, but the app updates these headers like 1-2 times per minute.

> Those are possible to calculate with standard algorithms. We should do what the app's APK does.

Here is the algorithm from the app:
```
// Initial values
this.averageSpeed = -1;
this.totalBytes = 0;
this.totalTime = 0;
// After each received response
if (this.responseSize >= 50000 && elapsedRealtime > 50) {
      double speed = (1.0d * ((double) this.responseSize)) / ((double) elapsedRealtime);
 
      if (this.totalTime != 0) {
          speed = (((double) (this.totalBytes / this.totalTime)) + speed) / 2.0d;
      }
      this.averageSpeed = speed;
      this.totalBytes += responseSize;
      this.totalTime += elapsedRealtime;
}
```
@rafaelwedbiz Likes are being abused by spammers, so Instagram are being hard with them. It just thinks that you are not a human. Use the app if you really want to like something.

**Comment by rafaelwedbiz** [comment]
@valga use the app? u mean manually?

**Comment by mgp25** [comment]
@rafaelwedbiz yes

**Comment by rafaelwedbiz** [comment]
automatic like is not possible anymore?

**Comment by myoldusername** [comment]
@mgp25 

Regarding : 
```
media_view_profile - for carousels
photo_view_profile - for photos (the only one currently supported)
video_view_profile - for videos
```
While if i  want to like a Video , what should i do ? if the "photo_view_profile in the  only one currently supported"
should i see media type and pass the media_view_profile ?

This point is not clear even in the WIKI.

Regards

**Comment by szokeptr** [comment]
Is somebody actively working on implementing the new headers? As far as I understand, they will be needed for new app versions.
I don't have the new version(s) patched yet, but would be happy to give a hand on this if you need it.

**Comment by valga** [comment]
> Is somebody actively working on implementing the new headers?

Nope.
> If the values are reset on each session, what's the point of saving them to storage?

Because we refresh session every 30 mins (by default), and you could start some scripts often then that.
