### ISSUE TITLE
Fix configureSingleVideo story locations

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1604]
- The `location` parameter is rejected for `FEED_STORY`.
- We may need to process the location the same way we do in configureSinglePhoto.

This is how configureSinglePhoto accepts location:
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Internal.php#L182

This is how it tweaks location if the target is a story feed:
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Internal.php#L298

This is how configureSingleVideo rejects location (it and its comment must be updated to match configureSinglePhoto's way of doing it):
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Internal.php#L481

This is how configureSingleVideo uses location (it may be needing to tweak location exactly like configureSinglePhoto does above);
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Internal.php#L588

**Comment by mgp25** [comment]
Fixed: https://github.com/mgp25/Instagram-API/commit/da6b96d52987d8cc98c9c4d03751f9d0eb572df6
