### ISSUE TITLE
Instagram Polls Support

### ISSUE THREAD

**Issue by msmoosa** [mgp25/Instagram-API#1606]
Instagram allows a new sticker for Polls. Will you be adding this?

https://www.inverse.com/article/37221-how-to-make-a-poll-in-an-instagram-story

**Comment by mgp25** [comment]
Hello @msmoosa,

Yes, it is almost finished, and probably tomorrow or in a few days will be added.

Please, dont open more issues asking for features..

Regards

**Comment by mgp25** [comment]
Hello @msmoosa,

I'm working on it. it will be released in the next few days.

Please, dont open more issues asking for new features supports since there is no ETA for any of them. It will be added when a collaborator or I have time to do it. We are currently very busy :/

Regards
