### ISSUE TITLE
Get the most recent media published by a user.

### ISSUE THREAD

**Issue by itskashi** [mgp25/Instagram-API#1607]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other
---

### Describe your issue
Do you have any implementation of getting recent media by userid. Is there any way we can get the comments and likes for last 'n' posts by the user. I think the recent media API endpoint can solve this. 
Please advise.

**Comment by mgp25** [comment]
Hello @itskashi,

Yes, the functions you are talking about are implemented. You can find information in the [wiki](https://github.com/mgp25/Instagram-API/wiki)

And the functions you are looking for are in:

- [Timeline.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php)
- [Media.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Media.php)

Regards

**Comment by itskashi** [comment]
Thank you for the response. 
I am actually looking for the implementation of this end point. 
/users/{user-id}/media/recent
which I could not find in Media.php or Timeline.php.

I want to get last 30 posts and count of comments and like. This endpoint can send max 32 posts. So in only one API call, I can get 30 posts' information. 

Can you please advise. 

_
Thanks

**Comment by mgp25** [comment]
Are you sure that endpoint exists? If are you totally sure can you tell me where in the app should i go?

**Comment by itskashi** [comment]
I am talking about this
https://www.instagram.com/developer/endpoints/users/#get_users_media_recent
I think it can be added Users.php or Media.php

**Comment by mgp25** [comment]
@itskashi you need to distinguish between official API and non official API. Endpoints are not the same, neither the params. 

In this API (non official), all endpoints are from the Instagram apk. If you want any feature to be implemented, it MUST be in the Instagram app. Otherwise it wont be implemented.

Regards

**Comment by itskashi** [comment]
I see, In that case, I think timeline feed best matches to the /media/recent. Let me find about this. I will get back to you with any question. Thank you so much for the positive response. 
BTW: Do you plan to relase any doncument regarding the request/response in addition to the wiki. 
This will help other users too.
_
Thanks
