### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by roullie666** [mgp25/Instagram-API#161]
when trying to upload photo i get `checkpoint_required`
heres the log
`
REQUEST: qe/sync/
DATA: ig_sig_key_version=4&signed_body=582df91c6ee9e99969d49f7ba2a55591e6c67ec628f96a47d30d05499dd390e3.{"_uuid":"ef8f0f55-496a-45db-814e-cb45e6e65946","_uid":3144752571,"id":3144752571,"_csrftoken":"2f7b18aa1b4e335d86ec86099151e00a","experiments":"ig_creation_growth_holdout,ig_android_place_typeahead_source,ig_android_enable_share_to_whatsapp,ig_android_video_look_ahead,ig_android_direct_drawing_in_quick_cam_universe,ig_android_inline_gallery_backoff_hours_universe,ig_android_rendering_controls,ig_video_encoding_with_crf,ig_android_refill_suggested_user_megaphone,ig_android_oxygen_dynamic_maps,ig_android_direct_plus_button,ig_android_trending_thumbnail_see_all,ig_android_oxygen_static_maps,ig_android_infinite_scrolling,ig_fbns_blocked,ig_android_http_stack_experiment_christmas,ig_android_full_people_card_in_user_list,ig_android_video_stitching,ig_fbns_push,ig_android_profile_contextual_feed,ig_android_post_auto_retry,ig_fb_event_in_mixed_carousel,ig_android_direct_thread_inline_likes,ig_android_profile_button_look_more_clickable,ig_android_histogram_reporter,ig_fbns_shared_exp,ig_android_post_notification_tooltip_universe,ig_android_peek,ig_android_profanity_filter,ig_android_high_res_upload_2,ig_android_boomerang_entry,ig_android_inline_gallery_universe,ig_android_2fac,ig_android_options_app_invite,ig_android_cluster_browsing_nux,ig_android_bugreporterV2,ig_android_disable_chroma_subsampling,ig_android_feed_multi_row,ig_android_profile_picture_creation,ig_android_media_favorites,ig_android_scroll_perf_sample_rate,ig_android_maps_cluster_overlay,ig_android_inline_gallery_no_backoff_on_launch_universe,ig_android_small_tabby_cat,ig_android_user_search_null_state_entries_number,ig_android_app_ads_deeplink,ig_android_follow_in_search,ig_android_direct_emoji_picker,ig_android_add_to_last_post,ig_android_related_items,ig_android_register_push_token_on_cold_start,ig_android_add_connect_button_on_people_page,ig_android_enable_client_share,ig_android_prefetch_venue_in_composer,ig_android_promoted_posts,ig_android_trending_places,ig_android_video_cache_append,ig_android_trending_immersive_viewer,ig_android_direct_default_to_gallery,ig_android_multi_post_creation_flow,ig_android_private_follow_notif_action_inline_v3,ig_pivot_in_explore,ig_android_app_badging,ig_android_boomerang_feed_attribution,ig_android_feed_experiments,ig_android_swipeable_filters_blacklist,ig_android_default_video_icon,ig_android_direct_video_uploads,ig_android_mentions_invite_v2,ig_android_direct_thread_ui_rewrite_qe"}
RESPONSE: {"status": "fail", "lock": false, "message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/integrity/checkpoint/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss"}

REQUEST: friendships/autocomplete_user_list/
RESPONSE: {"status": "ok", "expires": 1462473357, "users": [{"username": "alissa7830", "has_anonymous_profile_picture": true, "coeff_weight": 1.0, "friendship_status": {"following": false, "incoming_request": false, "outgoing_request": false, "is_private": false}, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "Roderick", "pk": 3123984082, "is_private": false}]}
`
REQUEST: feed/timeline/
RESPONSE: {"status": "ok", "num_results": 4, "is_direct_v2_enabled": true, "auto_load_more_enabled": true, "items": [{"taken_at": 1461984302.0, "pk": 1239536629898031294, "id": "1239536629898031294_3144752571", "device_timestamp": 1461984302.0, "media_type": 1, "code": "BEzt_9fKDC-", "client_cache_key": "MTIzOTUzNjYyOTg5ODAzMTI5NA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent.cdninstagram.com/t51.2885-15/s1080x1080/e15/fr/13102325_1708538316085778_323391252_n.jpg?ig_cache_key=MTIzOTUzNjYyOTg5ODAzMTI5NA%3D%3D.2", "width": 1080, "height": 1080}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/13102325_1708538316085778_323391252_n.jpg?ig_cache_key=MTIzOTUzNjYyOTg5ODAzMTI5NA%3D%3D.2", "width": 750, "height": 750}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13102325_1708538316085778_323391252_n.jpg?ig_cache_key=MTIzOTUzNjYyOTg5ODAzMTI5NA%3D%3D.2", "width": 640, "height": 640}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s480x480/e15/13102325_1708538316085778_323391252_n.jpg?ig_cache_key=MTIzOTUzNjYyOTg5ODAzMTI5NA%3D%3D.2", "width": 480, "height": 480}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/13102325_1708538316085778_323391252_n.jpg?ig_cache_key=MTIzOTUzNjYyOTg5ODAzMTI5NA%3D%3D.2", "width": 320, "height": 320}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e15/13102325_1708538316085778_323391252_n.jpg?ig_cache_key=MTIzOTUzNjYyOTg5ODAzMTI5NA%3D%3D.2", "width": 240, "height": 240}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/13102325_1708538316085778_323391252_n.jpg?ig_cache_key=MTIzOTUzNjYyOTg5ODAzMTI5NA%3D%3D.2", "width": 150, "height": 150}]}, "original_width": 1080, "original_height": 1080, "user": {"username": "iea.domondon", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "roderick", "pk": 3144752571, "is_verified": false, "is_private": false}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImU4NTFiNzY5YzBlYjQ5NWQ4OTMxNDkyMjM4MDVlMTYwMTIzOTUzNjYyOTg5ODAzMTI5NCIsInNlcnZlcl90b2tlbiI6IjE0NjI0MzAxNTc1MjZ8MTIzOTUzNjYyOTg5ODAzMTI5NHwzMTQ0NzUyNTcxfDcxZjllMmE5ODNhYTJlOTcwOWFmNjViNzgzY2E3MGZiZDEyYzdjNTQ0MDljYTQzOGNlZGZkZmFiOWZmYzQ1MmEifSwic2lnbmF0dXJlIjoiIn0=", "likers": [], "like_count": 0, "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "comments": [], "comment_count": 0, "caption": null, "caption_is_edited": false, "photo_of_you": false}, {"taken_at": 1461983793.0, "pk": 1239532358821490759, "id": "1239532358821490759_3144752571", "device_timestamp": 1461983790.0, "media_type": 1, "code": "BEztBzvKDBH", "client_cache_key": "MTIzOTUzMjM1ODgyMTQ5MDc1OQ==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent.cdninstagram.com/t51.2885-15/s1080x1080/e15/fr/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2", "width": 1080, "height": 810}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2", "width": 750, "height": 562}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2", "width": 640, "height": 480}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s480x480/e15/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2", "width": 480, "height": 360}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2", "width": 320, "height": 240}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e15/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2", "width": 240, "height": 180}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2", "width": 150, "height": 112}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s750x750/e15/c135.0.810.810/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2.c", "width": 750, "height": 750}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s640x640/e15/c135.0.810.810/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2.c", "width": 640, "height": 640}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s480x480/e15/c135.0.810.810/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2.c", "width": 480, "height": 480}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/c135.0.810.810/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2.c", "width": 320, "height": 320}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e15/c135.0.810.810/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2.c", "width": 240, "height": 240}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/c135.0.810.810/13129544_1713017168975761_1625033745_n.jpg?ig_cache_key=MTIzOTUzMjM1ODgyMTQ5MDc1OQ%3D%3D.2.c", "width": 150, "height": 150}]}, "original_width": 1080, "original_height": 810, "user": {"username": "iea.domondon", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "roderick", "pk": 3144752571, "is_verified": false, "is_private": false}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImU4NTFiNzY5YzBlYjQ5NWQ4OTMxNDkyMjM4MDVlMTYwMTIzOTUzMjM1ODgyMTQ5MDc1OSIsInNlcnZlcl90b2tlbiI6IjE0NjI0MzAxNTc1MjZ8MTIzOTUzMjM1ODgyMTQ5MDc1OXwzMTQ0NzUyNTcxfDQ3YzMyZDIxMGRhYWJlMDg5ODdhMTJlMmQyOGE0NDViYmMzMTFkMzc5YmZmMDBmYzNlMDZhYmJkZDYzYjAwZmEifSwic2lnbmF0dXJlIjoiIn0=", "likers": [], "like_count": 0, "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "comments": [], "comment_count": 1, "caption": {"status": "Active", "user_id": 3144752571, "created_at_utc": 1461983794, "created_at": 1461983794, "bit_flags": 0, "user": {"username": "iea.domondon", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "roderick", "pk": 3144752571, "is_verified": false, "is_private": false}, "content_type": "comment", "text": "Test caption", "media_id": 1239532358821490759, "pk": 17857168333016509, "type": 1}, "caption_is_edited": false, "photo_of_you": false}, {"taken_at": 1461983791.0, "pk": 1239532341515792453, "id": "1239532341515792453_3144752571", "device_timestamp": 1461983788.0, "media_type": 1, "code": "BEztBjnqDBF", "client_cache_key": "MTIzOTUzMjM0MTUxNTc5MjQ1Mw==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent.cdninstagram.com/t51.2885-15/s1080x1080/e15/fr/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2", "width": 1080, "height": 810}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2", "width": 750, "height": 562}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2", "width": 640, "height": 480}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s480x480/e15/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2", "width": 480, "height": 360}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2", "width": 320, "height": 240}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e15/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2", "width": 240, "height": 180}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2", "width": 150, "height": 112}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s750x750/e15/c135.0.810.810/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2.c", "width": 750, "height": 750}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s640x640/e15/c135.0.810.810/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2.c", "width": 640, "height": 640}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s480x480/e15/c135.0.810.810/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2.c", "width": 480, "height": 480}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/c135.0.810.810/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2.c", "width": 320, "height": 320}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e15/c135.0.810.810/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2.c", "width": 240, "height": 240}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/c135.0.810.810/13129249_1737289553184102_306525890_n.jpg?ig_cache_key=MTIzOTUzMjM0MTUxNTc5MjQ1Mw%3D%3D.2.c", "width": 150, "height": 150}]}, "original_width": 1080, "original_height": 810, "user": {"username": "iea.domondon", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "roderick", "pk": 3144752571, "is_verified": false, "is_private": false}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImU4NTFiNzY5YzBlYjQ5NWQ4OTMxNDkyMjM4MDVlMTYwMTIzOTUzMjM0MTUxNTc5MjQ1MyIsInNlcnZlcl90b2tlbiI6IjE0NjI0MzAxNTc1MjZ8MTIzOTUzMjM0MTUxNTc5MjQ1M3wzMTQ0NzUyNTcxfDMwYzYwNDUzMTY2NDA3YmNhNTk4MjQ3Mjg1MWYxYjY2ZDAxZDlhNWI3YTRiNTY0NDk1ZDk1OWJhZWQ0NzIyNjcifSwic2lnbmF0dXJlIjoiIn0=", "likers": [], "like_count": 0, "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "comments": [], "comment_count": 1, "caption": {"status": "Active", "user_id": 3144752571, "created_at_utc": 1461983792, "created_at": 1461983792, "bit_flags": 0, "user": {"username": "iea.domondon", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "roderick", "pk": 3144752571, "is_verified": false, "is_private": false}, "content_type": "comment", "text": "Test caption", "media_id": 1239532341515792453, "pk": 17855505004000099, "type": 1}, "caption_is_edited": false, "photo_of_you": false}, {"taken_at": 1461974597.0, "pk": 1239455217685640174, "id": "1239455217685640174_3144752571", "device_timestamp": 1461974593.0, "media_type": 1, "code": "BEzbfQdKDPu", "client_cache_key": "MTIzOTQ1NTIxNzY4NTY0MDE3NA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent.cdninstagram.com/t51.2885-15/s1080x1080/e15/fr/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2", "width": 1080, "height": 810}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2", "width": 750, "height": 562}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2", "width": 640, "height": 480}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s480x480/e15/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2", "width": 480, "height": 360}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2", "width": 320, "height": 240}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e15/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2", "width": 240, "height": 180}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2", "width": 150, "height": 112}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s750x750/e15/c135.0.810.810/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2.c", "width": 750, "height": 750}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s640x640/e15/c135.0.810.810/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2.c", "width": 640, "height": 640}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s480x480/e15/c135.0.810.810/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2.c", "width": 480, "height": 480}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/c135.0.810.810/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2.c", "width": 320, "height": 320}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e15/c135.0.810.810/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2.c", "width": 240, "height": 240}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/c135.0.810.810/13129134_1768727733406720_1227124746_n.jpg?ig_cache_key=MTIzOTQ1NTIxNzY4NTY0MDE3NA%3D%3D.2.c", "width": 150, "height": 150}]}, "original_width": 1080, "original_height": 810, "user": {"username": "iea.domondon", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "roderick", "pk": 3144752571, "is_verified": false, "is_private": false}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImU4NTFiNzY5YzBlYjQ5NWQ4OTMxNDkyMjM4MDVlMTYwMTIzOTQ1NTIxNzY4NTY0MDE3NCIsInNlcnZlcl90b2tlbiI6IjE0NjI0MzAxNTc1Mjd8MTIzOTQ1NTIxNzY4NTY0MDE3NHwzMTQ0NzUyNTcxfDBkMWY2ZDgxZGE1MjM3YTExYjc2YzQwYjQ5OGQ4MGQ2N2NhZDkwMmU5YmUzODI2YWFkYzliMjk0NDg1ZWU1NzIifSwic2lnbmF0dXJlIjoiIn0=", "likers": [], "like_count": 0, "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "comments": [], "comment_count": 1, "caption": {"status": "Active", "user_id": 3144752571, "created_at_utc": 1461974598, "created_at": 1461974598, "bit_flags": 0, "user": {"username": "iea.domondon", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "roderick", "pk": 3144752571, "is_verified": false, "is_private": false}, "content_type": "comment", "text": "Test caption", "media_id": 1239455217685640174, "pk": 17855791672025487, "type": 1}, "caption_is_edited": false, "photo_of_you": false}], "more_available": false, "megaphone": {"fb_connect_upsell": {"title": "Find People to Follow", "subtitle": "Connect your Facebook account to find your friends.", "button": "Connect", "uuid": "82486bb5728d42228814551f0541a402"}}}

**Comment by mgp25** [comment]
Login using your device and then use then API

**Comment by roullie666** [comment]
Thank you for your fast response.  :)..  Now i'm getting this `Bad Request` error

**Comment by mgp25** [comment]
@roullie666 remove the .dat files and cookies from data folder and retry

**Comment by roullie666** [comment]
Removed and tried again. but still the same.
