### ISSUE TITLE
Direct Story

### ISSUE THREAD

**Issue by GoldenEagle66** [mgp25/Instagram-API#1610]
when I try to get an answer to the story in the directorate
`{
"item_id":"27809610648296811124845287766491136",
"user_id":1450877332,
"timestamp":1507562014042971,
"item_type":"story_share",
"story_share":{
"is_linked":false,
"title":"Update App",
"message":"Update your app to see this story.",
"text":""
},
"client_context":"2D18F290-E7D4-4140-8A4D-FE603BF512D3"
}`

How can you solve this?

**Comment by mgp25** [comment]
Hello, the response explains itself:

`Update your app to see this story.`

We won't update version and signature key until we implement more changes in the API, until then, you will have wait.

Regards

**Comment by GoldenEagle66** [comment]
thank you, I will wait
