### ISSUE TITLE
Unnecessary break statement

### ISSUE THREAD

**Issue by Sparknsk** [mgp25/Instagram-API#1616]
Unnecessary break statement in line 554 or it's OK at this moment?
https://github.com/mgp25/Instagram-API/blob/b2e586a1db2995bff3c3c17fc6a4731f14ef32c5/src/Request/Internal.php#L545-L563

**Comment by mgp25** [comment]
Hello @Sparknsk,

> it's OK at this moment?

Totally not! Im going to push fix in 1 minute.

Thanks for reporting this!

Regards
