### ISSUE TITLE
setUser has been removed , any changLog to follow 

### ISSUE THREAD

**Issue by myoldusername** [mgp25/Instagram-API#1618]
Thank you for the update , 

Do you have any change log to correct our code base on ? 

Thank you in advanced.

**Comment by mgp25** [comment]
Hello @myoldusername,

i would recommend you to have a look at the [wiki](https://github.com/mgp25/Instagram-API/wiki) and [examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

Regards

**Comment by myoldusername** [comment]
Thank you for the FAST replay , i know that i have to see wiki , i did that and i see all examples , but i dont know if you change any internal core functions name as from V2 to V3 , that is why i am asking you for a respective change log !

Since there is no information like "important , We change this list of function "

Regards

**Comment by mgp25** [comment]
Hello @myoldusername,

In fact, that was already done, you can find the changelog here: https://github.com/mgp25/Instagram-API/releases/tag/v3.0.0

And we wrote detailed information about the updated and breaking code changes. Please give a look at all the repo.

Regards
