### ISSUE TITLE
Wiki and like function 

### ISSUE THREAD

**Issue by myoldusername** [mgp25/Instagram-API#1620]
@mgp25 
There is unclear information  in wiki regarding like function best practices. 

Regarding : https://github.com/mgp25/Instagram-API/issues/1602

You said this:
```
media_view_profile - for carousels
photo_view_profile - for photos (the only one currently supported)
video_view_profile - for videos
```
Whis is not clear, 
if i  want to like a Video , what should i do ? if the "photo_view_profile in the  only one currently supported"
should i check  media type and pass the media_view_profile ?

This point is not clear even in the WIKI.

And regarding 

```
Liking from the followings activity feed

If the user only liked one post ("xyz liked abc's post"), then the app uses module newsfeed. If the user liked multiple posts ("xyz liked 5 posts"), then the app uses module feed_contextual_newsfeed_multi_media_liked.
```

Is this mean when i open any followings  profile time line , if i liked 1 photo ,"module newsfeed"
Ok if i like the next photo in the same time 5 sec time frame , should i start passing "feed_contextual_newsfeed_multi_media_liked" module ?

Kindly may you clarify this in order to use this library respectively. 

Regards

**Comment by aitte2** [comment]
Hm I can see 2 problems with the wiki:

1. The navigation to the right of the page does not have shortcuts to all sections, for example not to liking media, so first I didn't know there was info about liking.
2. The user profile example is unclear. Should extradata be our username and id, or the media owner's username and id? I guess it should be the media owner. Please clarify: https://github.com/mgp25/Instagram-API/wiki#liking-from-an-user-profile

**Comment by aitte2** [comment]
Also found a code issue: unlike function only understands 2 modules.

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Media.php#L223

Should probably put the like-data validator as `Utils::parseLikeParameters(Request $request, $module, array $extraData)` and make that function validate all data and add params directly to the `$request` object. Basically cut and paste the like() code into that function.

And while you're at it, this is a bug:
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Media.php#L189

` $request->addPost('hashtag', str_replace('#', '', $extraData['hashtag']));`

That is a non-UTF8 capable replace function. Very dangerous if hashtag is non-English. It can then replace inside of multibyte character and break the hashtag.

I would change it to this strict UTF8 validator instead:

http://php.net/manual/en/function.mb-strstr.php

```php
if (mb_strstr($extraData['hashtag'], '#') !== false) {
    throw new \InvalidArgumentException('Hashtag is not allowed to contain the "#" character.');
}
```

**Comment by mgp25** [comment]
Hello @aitte2,

i have some exams and therefore have less time to write proper documentation and so. I'll take care of this in the next hours.

Thanks agains for reporting bug/issues

Regards

**Comment by SteveJobzniak** [comment]
@aitte2 @mgp25 

Hey mgp if you've read my pull request, I'm sick and bored as fucking hell. I'll take care of the code changes he mentions (`_parseLikeParameters`). I have a fever and nothing to do.

You do the wiki. ;-)

PS: Merge my current pull request with `rebase & merge` asap please. All code is correct, so you can read it later. I want to merge it so I can rebase my copy on it and start doing the other fixes in a separate pull request. ;-)

**Comment by SteveJobzniak** [comment]
@myoldusername @aitte2 @mgp25 

I have refactored the like and unlike functions and fully documented all scenarios within the source code. The commit is part of my ongoing pull request:

https://github.com/mgp25/Instagram-API/pull/1619/commits/9d4b52f636d5bbe38df939488ebfef8718761de5

@myoldusername All of your questions are answered by the new code comments there. Scroll down to the bottom of that commit.

@mgp25 The wiki will need updating to match the comments I put in the source code. Or perhaps just delete the part on the wiki and tell people to read the code inside `Media::_parseLikeParameters()` since it describes everything fully.

**Comment by myoldusername** [comment]
@SteveJobzniak, nothing to say, the most wonderful coding i ever seen, clean and straightforward....

Thank you for your kindly effort to the open source community.

**Comment by SteveJobzniak** [comment]
@myoldusername Haha thank you for those nice words. ;-)

**Comment by SteveJobzniak** [comment]
The fixes have been merged to `dev-master` now:

https://github.com/mgp25/Instagram-API/commit/62553a45f05581c6f53781e025a9352726b8d4ac
