### ISSUE TITLE
Check the connection

### ISSUE THREAD

**Issue by kozintsev** [mgp25/Instagram-API#1621]
How can I check the connection and session after I run the request?
Is there such a possibility?

Can I test the connections using property $is->isLoggedIn?

Best regard, Oleg

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

**Comment by SteveJobzniak** [comment]
@kozintsev Hi. No you cannot check `$ig->isLoggedIn`. That variable is _ONLY A GUESS_. Do NOT look at that variable. It's our internal "guess"-state. Seriously, I am warning you. ;-D

After you have called `$ig->login()` successfully, _THEN_ you KNOW that you are logged in with a valid session.

The login function will verify that you are logged in with a valid session and will perform a resume/refresh/full login as-necessary.

If `login()` does not throw any exceptions, you KNOW that you're logged in.

**Comment by SteveJobzniak** [comment]
PS: If the account owner changes their password, Instagram will invalidate all sessions. If that happens AFTER you've done `login()`, then your next function call would throw a `LoginRequiredException`. You could choose to handle that ultra-rare scenario IF you want to...

**Comment by kozintsev** [comment]
Thank you, very much!
