### ISSUE TITLE
Instagram API returning all the data at once

### ISSUE THREAD

**Issue by khanof89** [mgp25/Instagram-API#1625]
I have encountered that now Instagram endpoint friendships/{$userId}/followers/ started returning more than 200 records in a call e.g in my current request I got upto 3900 results, can be managed on our side but just wanted to bring into your notice

**Comment by SteveJobzniak** [comment]
Thanks but we've already discussed that at length in the past:

**Comment by SteveJobzniak** [comment]
Thanks but we've already discussed that at length in the past:
https://github.com/mgp25/Instagram-API/issues/1340

Instagram does not seem to do it intentionally. So you should expect it to return 200 again soon.
