### ISSUE TITLE
Get comment detail

### ISSUE THREAD

**Issue by thienit5** [mgp25/Instagram-API#1628]
I use pushReceiver.php, I get notifications when new comments or messages arrive.
But notifications do not show some informations: create_time, sender name, sender_id vv..
I want to get detail informations, but I don't know how to. I only see api to get all Comments of media not for only one comment.

Can you show me how to get details of a comment.
Many thanks

**Comment by valga** [comment]
Push notifications are designed to be as lightweight as possible: they contain a minimum needed to display a notification and to open a specific screen (if requested by user). The minimum for pushes about new comments is media ID and comment ID, as shown in example: https://github.com/mgp25/Instagram-API/blob/70f34222ec5cf9d9874d779ccb8c24a2f4ef17c6/examples/pushReceiver.php#L40-L42

You can then use official or private APIs for polling media comments by given ID.

**Comment by thienit5** [comment]
Thank you, but how to get a comment information from comment_id?

**Comment by SteveJobzniak** [comment]
@thienit5 You can't. The real app doesn't have that feature.

All it does if you tap on a "you got a comment" notification is take you to the picture/video page.

**Comment by thienit5** [comment]
Thanks.
I have another issue.
I have multi accounts Instagram, how can I run pushReceiver and realtimeHttp for multi accounts

**Comment by SteveJobzniak** [comment]
@thienit5 that’s answered here:
https://github.com/mgp25/Instagram-API/wiki/FAQ#is-it-possible-to-run-the-realtime-and-push-clients-in-a-single-script

**Comment by valga** [comment]
@SteveJobzniak There is a `target_comment_id` param in media/comments endpoint that ensures you will receive a page with specific comment.

**Comment by SteveJobzniak** [comment]
@valga Oh, that's worth adding. I wonder if we should add it as `getComments($mediaId, $maxId = null, $targetCommentId = null)` or as a separate function. If maxid pagination works even when a target was requested, then we should even put the param in the middle (like with getFollowers/getFollowings, which got the searchQuery param added to the middle).

**Comment by valga** [comment]
@SteveJobzniak I don't think that `max_id` can work together with `target_comment_id`. Also, considering that there is `min_id` param to page up, we could use `array $options = []` for all of them.

**Comment by SteveJobzniak** [comment]
@valga You are right, I tried it and the server went blank and gave a blank response. ;-)

Okay here's the implementation: https://github.com/mgp25/Instagram-API/pull/1619/commits/46dedfd814ecede1dd1bc9a5b31ec0a830530d3a

@thienit5 After this is merged you will be able to go to specific comments via its `target_comment_id` option.

**Comment by SteveJobzniak** [comment]
@thienit5 This is merged in `dev-master` now :)

https://github.com/mgp25/Instagram-API/commit/895bb1a02dd4aac2ae2cfad1ca9a406da5c01ef7
