### ISSUE TITLE
Realtime client for receiving new posts

### ISSUE THREAD

**Issue by kozintsev** [mgp25/Instagram-API#1629]
I looked
Instagram-API/examples/realtimeClient.php
and I have a question...
Can I use the Realtime client to get new posts?

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

**Comment by valga** [comment]
@kozintsev Below is a complete list of events supported by Realtime client: https://github.com/mgp25/Instagram-API/blob/70f34222ec5cf9d9874d779ccb8c24a2f4ef17c6/src/Realtime.php#L15-L30

As you can see, Realtime is designed for Direct. If you want to receive notifications about new posts from people you follow, use Push client: https://github.com/mgp25/Instagram-API/blob/70f34222ec5cf9d9874d779ccb8c24a2f4ef17c6/src/Push.php#L28

It is impossible to get notifications about your own new posts. Use official API or timer-based polling for that.

**Comment by kozintsev** [comment]
@valga Thanks for the idea!
