### ISSUE TITLE
Error in sendStory method in direct

### ISSUE THREAD

**Issue by mrb4hr4m** [mgp25/Instagram-API#1631]
### Before submitting an issue make sure you have:
- [*] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [*] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [*] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [*] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [*] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [*] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

in default example . when i want send story to direct . i got this error

Error Log in JSON 👍 
{"message": "invalid request", "status": "fail"}

**Comment by SteveJobzniak** [comment]
Hi/ What are you talking about? There is no default "sendStory" example.

```
+ $ ag sendstory
src/Request/Direct.php
833:    public function sendStory(
```

See. There's 0 references to that function in our code.

**Comment by mrb4hr4m** [comment]
you are true in >> There is no default "sendStory" example

I mean in Direct.php we have sendStory method . but when i using this! i got error with 400 status code

**Comment by SteveJobzniak** [comment]
Post your sendStory code. I am sure you are sending the wrong parameters.

**Comment by mrb4hr4m** [comment]
this method want three parameters : $recipients and $options and $storyId  . i can use all of methods in Direct.php . it mean my $recipients and $options have a true value . i get the story feed from one user and test all numerical numbers in the json . but i got error again and again . pay attention . i can replay the user story on instagram mobile application . it mean : i have permission to replay the user story . but in api i got error .

**Comment by SteveJobzniak** [comment]
Are you trying to share somebody else's story via direct?

Try sharing your own, I think sendStory only lets you share own.

Please let me know. I will update the function docs if they only allow your own stories.

**Comment by valga** [comment]
@SteveJobzniak Story ID must be in `%MEDIA_PK%_%USER_PK%` format (not just numerical). Also there must be `media_type=photo/video` GET param (like in `sendPost()` method). And the request must be signed.

**Comment by SteveJobzniak** [comment]
@valga Yeah... I was surprised when I saw mgp adding the "ctype_digit" code check. I suspected it just meant that it wanted only the story's PK and that you can only send your own story... But I am not surprised to hear that it's wrong.

**Comment by SteveJobzniak** [comment]
@valga Fixing...

**Comment by valga** [comment]
@SteveJobzniak Also, there are a couple of experiments:
* `ig_android_rtc_reshare` - use Realtime client for sharing posts and stories;
* `ig_android_vertical_share_sheet_experiment/is_blast_endpoint_enabled` - we need to send `unified_broadcast_format=1` in POST (and probably something else is different).

**Comment by SteveJobzniak** [comment]
@valga Hmm, well I have no time for those.

But one thing... The `Direct::_sendDirectItem()` function does this:

```php
        return $request->setSignedPost(false)
            ->addPost('action', 'send_item')
            ->addPost('client_context', $options['client_context'])
```

So all function calls are unsigned.

I can easily fix that, but which ones should be signed?

Just `story_share`? Also `media_share`? Any others?

**Comment by SteveJobzniak** [comment]
@valga https://github.com/SteveJobzniak/Instagram-API/commit/602187bf9f0b7de5045366212f28ab3516eefb59

If other functions need signing, just let me know and I can add those too.

**Comment by valga** [comment]
@SteveJobzniak Just `story_share` request must be signed.

**Comment by SteveJobzniak** [comment]
@valga Cool, then it's already done, since I only added that one.

@mrb4hr4m I haven't got anything to test with, but you can download this .patch file:

https://github.com/SteveJobzniak/Instagram-API/commit/602187bf9f0b7de5045366212f28ab3516eefb59.patch

And apply with `patch -p1 < thepatch.txt` in the root of the repository. The new sendStory code _should_ be working now.

**Comment by mrb4hr4m** [comment]
@valga thank you . problem solved .

@SteveJobzniak thank you too . for support

**Comment by SteveJobzniak** [comment]
@mrb4hr4m Are you running with the new code-patch I posted?

**Comment by mrb4hr4m** [comment]
@SteveJobzniak problem not solved . now i testing with new code . but again got invalid request with 400 status code

**Comment by SteveJobzniak** [comment]
@mrb4hr4m Try sending your own story. I still do not think Instagram will let you share other people's story like you are trying to do.

**Comment by mrb4hr4m** [comment]
@steveJobzniak where i said i share other people`s story ? This method have an error all time . When i want to send my story to another direct ! When i want to replay a user atory to him/here direct . I checked all of them . But problem not solved . I decode the instagram main application and check it . This method should signed post and want media_type . You do them in patch file . I implement in the code . But error not solved !

**Comment by SteveJobzniak** [comment]
@mrb4hr4m 

> where i said i share other people`s story ?

Here:

> i can replay the user story on instagram mobile application . it mean : i have permission to replay the user story . but in api i got error .

You said you have permission to view the user's story, but get error sharing it.

But anyway, hmm, I wonder why it's not working for you then. Please let us know if you figure it out...

**Comment by mrb4hr4m** [comment]
@SteveJobzniak  . i don't know too . i check all of moods

**Comment by valga** [comment]
@mrb4hr4m "Invalid request." means that request is unsigned. I guess it happens because the patch from above fails to apply:
```
patching file src/Request/Direct.php
Hunk #1 FAILED at 820.
Hunk #2 succeeded at 829 with fuzz 1.
Hunk #5 FAILED at 1169.
2 out of 7 hunks FAILED -- saving rejects to file src/Request/Direct.php.rej
```
But even if you will apply it manually, you will get "Requested resource does not exist." error. It means that your "app" doesn't support stories sharing yet. So you should wait for changes to be merged into master branch, or you can checkout a branch from the fork.

@SteveJobzniak `_uid` param is required for signed requests (just to match the app, because sharing works even without it). And yes, you can share stories from others.

**Comment by SteveJobzniak** [comment]
@valga Great catch, I was in a hurry when I made the changes. I've amended the commit and added `_uid` if signedPost:

https://github.com/mgp25/Instagram-API/pull/1619/commits/8a0478782433833af726f190c94feb32b6e8292a

As for mrb4's error: Ah, yes I have done lots of changes in the Direct file so that's a good point... the patch relates to other commits. He'll have to wait until my work is merged.

I have now finally got life signs (contact) with mgp, he's not dead. I was worried. :-P

**Comment by SteveJobzniak** [comment]
@mrb4hr4m The changes are merged into master now. https://github.com/mgp25/Instagram-API/commit/5b39b57e1b2f8b623702b2d8b62b842ff61ca3fd

Update and let's see if it works for you.

**Comment by mrb4hr4m** [comment]
its too late . but problem fixed . thanks all 👍

**Comment by SteveJobzniak** [comment]
@mrb4hr4m lol yep over a month ago ;)

**Comment by mrb4hr4m** [comment]
@SteveJobzniak yeah . it's too late . :(

**Comment by SteveJobzniak** [comment]
:D
