### ISSUE TITLE
Using a custom cacert.pem in WAMP server?

### ISSUE THREAD

**Issue by david-steiner** [mgp25/Instagram-API#1632]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hi sir , i want really respect your great work and efforts to develop this amazinf instagram api, but after trying to use it i got an error ' CURL error 60: SSL certificate problem:' , i googled about 4 hours and tried many solutions but without being successful, im working in a local wamp server 3.1.0 , i required and downloaded the library using the composer command you givee, i added curl.cainfo path line in php.ini and also the cacert.pem file in C:\wamp\bin\php\php7.1.9\  , didnt worked also switched all php version from 5 to 7.1.9 and still got the error just googled and some people said i need edit version of guzzlehttp/guzzle": "~6.3 in composer.json and I puted 4 ad 6.0 instead  and tried also to update ,i really searched all this morning please i know many people will get this error
greetings

**Comment by david-steiner** [comment]
Ok i found the solution i was adding this ligne : curl.cainfo = "C:\wamp\bin\php\php7.1.9\cacert.pem" in opening manualy php.ini files in wamp/bin/php directory of all the 3 version folders, but that seem not updated even i restarted wamp, 

THE SOLUTION IS CLICK LEFT ON LUNCHED ICON OF WAMP >PHP>php.ini , then here you need scroll down to CURL section and add the ligne the save , restart the wamp , then it would solved :)

**Comment by SteveJobzniak** [comment]
Hi. Hehe okay so this is solved then. It was a WAMP usage issue.

**Comment by david-steiner** [comment]
Dear please iif you can just help me how i can use login with useragent and proxy thank you thats all

**Comment by SteveJobzniak** [comment]
Hi. src/Instagram.php has all of the proxy-setting functions.

**Comment by david-steiner** [comment]
what about CURLOPT_USERAGENT agent sir how to do please its the last one

**Comment by SteveJobzniak** [comment]
You cannot. You must have the `Instagram/VERSION` agent, which we give you.

**Comment by david-steiner** [comment]
yes i know sir its generated automatically by your code i need just know the placement of the genrator function, then i want use it to autorize the agent auth with two factor auth code

**Comment by SteveJobzniak** [comment]
Huh? The user agent is only used when talking to Instagram's API server, to identify us as the real app. So don't touch it. It must be the way it is.

As for 2 factor, it is done this way:
https://github.com/mgp25/Instagram-API/blob/master/examples/twoFactorLogin.php

And you cannot get the user agent until you have called `$ig->login()`. If you want it for something, you can do:

```php
$ig->login($username, $pasword);
$currentAgent = $ig->device->getUserAgent(); // ONLY AVAILABLE *AFTER* `login()` CALL!!!
$ig->finishTwoFactorLogin(...............
```

**Comment by david-steiner** [comment]
nop it is possible to generate  useragent and send it as parameter to instagram api/accounts/login/, i just want know which is the useragent parameter ?
 for example this is a useragent i generate it automatically

"Instagram 6.21.2 Android (15/5.4.0; 320; 1280x720; samsung; SM-N9000; SM-N9000; smdkc210; en_US)"

please help thank u

**Comment by SteveJobzniak** [comment]
We generate different user agent for every account to make you less detectable. And it is assigned on `login()`. So you cannot get it before you login via our library.

My question is why you want to get it? You want to send it to `it is possible to generate useragent and send it as parameter to instagram api/accounts/login/` ?

We already generate the agent and use it as CURL USER AGENT when we login too.

Is that what you mean? Or do you mean literally a `?agent=SOMETHING` (GET) or `agent=SOMETHING` (POST) param?

Please explain. :)

**Comment by david-steiner** [comment]
Hi thank you again for assisting, 
no i mean useragent parameter that can be sent via api request url like as the username and password , i have a class and it is sending json parameters like  this	"$data = '{"device_id":"'.$device_id.'","guid":"'.$this->guid.'","username":"'. $this->username.'","password":"'.$this->password.'","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"}';"

please now as you see how to add to this array the verification_code , two_factor_identifier , to make the device authorised because the two factor code is asked when the device is changed right? so please just help me edit my array :)

**Comment by SteveJobzniak** [comment]
Hi. Who are you sending that JSON to? To Instagram? Why?

We already have 2-factor login. Use these steps:

https://github.com/mgp25/Instagram-API/blob/master/examples/twoFactorLogin.php

**Comment by szokeptr** [comment]
@SteveJobzniak I think he is doing something that is not implemented in this API (account registration for example) and that’s why he needs it without login().

**Comment by SteveJobzniak** [comment]
@szokeptr Yeah maybe he is. But in that case, he's in the wrong place, because we only give support for this API library.
