### ISSUE TITLE
[Question] How to get media of user?

### ISSUE THREAD

**Issue by DerTechNick** [mgp25/Instagram-API#1633]
Hello,
first of all, I really appreciate your work :+1: 

Currently I'm searching for a possibility to get all media of a user. Is that possible? I've also searched in the wiki but didn't find anything.

Best regards,
Nick

**Comment by SteveJobzniak** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php
