### ISSUE TITLE
How to get direct message item detail by thread_id and item_id?

### ISSUE THREAD

**Issue by liudanking** [mgp25/Instagram-API#1636]
I know there is a API  `$ig->direct->getThread($threadID, $cursorID)`, but it returns many messages that behind `$cursorID`. 

In order to save bandwidth, is there any way to get direct message item detail by thread_id and item_id?

I have read `Direct.php`, no API found for this purpose. Any ideas?

**Comment by valga** [comment]
There is no such endpoint available at the moment. 

Use Realtime client to save bandwidth.
