### ISSUE TITLE
GET specific comment by target_comment_id does not work

### ISSUE THREAD

**Issue by thienit5** [mgp25/Instagram-API#1639]
I build a test request to get specific comment by target_comment_id like:
 $option = array("target_comment_id"=>"17891730523107661");
 $ig->media->getComments("1628726019185732957_37264670",$option);

But the result return multi comments, not specific comment.

LOG:
GET:  https://i.instagram.com/api/v1/media/1628726019185732957_37264670/comments/?target_comment_id=17891730523107661&can_support_threading=true

RESPONSE: {"comment_likes_enabled": true, "comments": [{"pk": 17844888610214176, "user_id": 6156810001, "text": "Xin chaof", "type": 0, "created_at": 1508404484, "created_at_utc": 1508404484, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false, "has_translation": true, "has_liked_comment": false, "comment_like_count": 0, "child_comment_count": 0, "preview_child_comments": [], "other_preview_users": []}, {"pk": 17903264272053035, "user_id": 6156810001, "text": "Co gi hot", "type": 0, "created_at": 1508404597, "created_at_utc": 1508404597, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false, "has_translation": true, "has_liked_comment": false, "comment_like_count": 0, "child_comment_count": 0, "preview_child_comments": [], "other_preview_users": []}, {"pk": 17879722927133103, "user_id": 6156810001, "text": "Khong co gi", "type": 0, "created_at": 1508406594, "created_at_utc": 1508406594, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false, "has_translation": true, "has_liked_comment": false, "comment_like_count": 0, "child_comment_count": 0, "preview_child_comments": [], "other_preview_users": []}, {"pk": 17846330452203331, "user_id": 6156810001, "text": "Xin chaof", "type": 0, "created_at": 1508471312, "created_at_utc": 1508471312, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false, "has_translation": true, "has_liked_comment": false, "comment_like_count": 0, "child_comment_count": 0, "preview_child_comments": [], "other_preview_users": []}, {"pk": 17904750355053788, "user_id": 6156810001, "text": "Tran duc thien", "type": 0, "created_at": 1508471885, "created_at_utc": 1508471885, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false, "has_liked_comment": false, "comment_like_count": 0, "child_comment_count": 0, "preview_child_comments": [], "other_preview_users": []}, {"pk": 17891730523107661, "user_id": 6156810001, "text": "hey hey", "type": 0, "created_at": 1508748222, "created_at_utc": 1508748222, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false, "has_liked_comment": false, "comment_like_count": 0, "child_comment_count": 0, "preview_child_comments": [], "other_preview_users": []}, {"pk": 17845421194210055, "user_id": 6156810001, "text": "OPOP", "type": 0, "created_at": 1508749609, "created_at_utc": 1508749609, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false, "has_liked_comment": false, "comment_like_count": 0, "child_comment_count": 0, "preview_child_comments": [], "other_preview_users": []}], "comment_count": 7, "caption": {"pk": 17880626881139148, "user_id": 37264670, "text": "H\u1ea3", "type": 1, "created_at": 1508379293, "created_at_utc": 1508379293, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 37264670, "username": "thienit5", "full_name": "Tran Thien", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/22427311_1166726433459426_5522250962426658816_n.jpg", "profile_pic_id": "1623147155999094025_37264670", "is_verified": false}, "did_report_as_spam": false, "has_translation": true}, "caption_is_edited": false, "has_more_comments": false, "has_more_headload_comments": false, "threading_enabled": true, "media_header_display": "none", "preview_comments": [{"pk": 17891730523107661, "user_id": 6156810001, "text": "hey hey", "type": 0, "created_at": 1508748222, "created_at_utc": 1508748222, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false}, {"pk": 17845421194210055, "user_id": 6156810001, "text": "OPOP", "type": 0, "created_at": 1508749609, "created_at_utc": 1508749609, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6156810001, "username": "tranducthienido", "full_name": "Tr\u1ea7n Thi\u1ec7n", "is_private": false, "profile_pic_url": "https://instagram.fhan5-3.fna.fbcdn.net/t51.2885-19/s150x150/20067238_1953161268276790_4828732225090486272_n.jpg", "profile_pic_id": "1617995607992405607_6156810001", "is_verified": false}, "did_report_as_spam": false}], "status": "ok"}

**Comment by valga** [comment]
It works just as intended: https://github.com/mgp25/Instagram-API/blob/38dbe0ae9c20401bb1ec4195d483b9f99effbf3d/src/Request/Media.php#L361

Filter the comments list by ID to find the one you need.

**Comment by SteveJobzniak** [comment]
Like valga said, it gets the comment plus many comments before/after it.
