### ISSUE TITLE
Get all media from specefic user

### ISSUE THREAD

**Issue by amirooo71** [mgp25/Instagram-API#1640]
hi,
how can i get all media from specefic user?(all images and videos)

**Comment by mgp25** [comment]
Hello there @amirooo71 ,

This has been answered many times, you can search for an answer in the [closed issues](https://github.com/mgp25/Instagram-API/issues).

Nevertheless, you can find all functions related to user feeds here:

- [Timeline.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php)

You will find documentation of each functions inside.

Regards
