### ISSUE TITLE
Error: "No response from server. Either a connection or configuration error."

### ISSUE THREAD

**Issue by testforlite** [mgp25/Instagram-API#1641]
I`m getting errors from some accounts: "No response from server. Either a connection or configuration error." 

Login:
$instance->login('hariet_blank','190895');

**Comment by SteveJobzniak** [comment]
https://github.com/mgp25/Instagram-API/issues?utf8=✓&q=is%3Aissue%20is%3Aclosed%20response%20connection

**Comment by mgp25** [comment]
Hi there @SteveJobzniak
