### ISSUE TITLE
How can I get all the threads?

### ISSUE THREAD

**Issue by testforlite** [mgp25/Instagram-API#1642]
I receive threads from Direct but not all of them. I receive only 40-70 threads maximum. How can I get all the threads (what function should be used for it)?

**Comment by SteveJobzniak** [comment]
You need to use pagination:

https://github.com/mgp25/Instagram-API/blob/5e0148f0bd3c833c19c0a7979c06321917dd66c8/src/Request/Direct.php#L25-L32
