### ISSUE TITLE
Image resizing now working

### ISSUE THREAD

**Issue by vishal2947** [mgp25/Instagram-API#1644]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question
- [ ] Other

---

### Describe your issue

Explanation of your issue goes here.

Whenever i am trying to post an image, i am gettting this error: Instagram only accepts media with aspect ratios between 0.800 and 1.910

In earlier version, i had this option:
 new \InstagramAPI\ImageAutoResizer($photo);

But in my current version(3.1), i am not getting this option. I want to know is there any similar option to resize image before posting in 3.1?

We reserve the right to close your ticket without answer if you can't bother spending a few minutes to write a helpful report for us.

**Comment by SteveJobzniak** [comment]
Duplicate of #1645
