### ISSUE TITLE
MediaAutoResizer - Given file is not an image.

### ISSUE THREAD

**Issue by AliKhaleghi** [mgp25/Instagram-API#1646]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors) ( Maybe ? )
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hi, I've been trying to upload a video into Instagram but there are some problems.
First of all, the API works as expected ( with regular videos ), but I'm using `PHP-FFMpeg` to add watermarks to video, after the watermark is successfully added, `instagram` returns an error which says:   

```
Configuration of "/var/www/html/uploads/3197055872.mp4" failed. You need to reupload the media (Not a single valid audio stream).
```
I've been trying to do so since before the last release.
Now I have updated the codes with the new release and hoped that the converter would solve that issue as well, but sadly it does not.
Test Case for `MediaAutoResizer` :

```php
$options = array(
	'debug'	=>	true
);
$resizer = new \InstagramAPI\MediaAutoResizer($file,$options);
var_dump($resizer->getFile());
```
The result is : 
```php
string(60) "File "/var/www/html/uploads/0228031359.mp4" is not an image."
```
Unfortunately I don't have enough knowledge in video/audio conversions but I'll keep reading about this so I can make sense of what `MediaAutoResizer` and `VideoResizer` actually does to my file, maybe I could improve it if the solution for this problem is not implanted.

I do understand that this issue could be opened in `PHP-FFMpeg` project, but since the video IS generated with the given settings ( and the watermark ) and works as expected but can not be uploaded, it should be asked here. any sort of help will be highly appreciated.
Thanks in advance.

**Comment by AliKhaleghi** [comment]
Well the problem with the class actually worked out,
after going through project files I realized that the release I have installed is not the one containing the right codes, I installed the `dev-master` version and everything is working as expected, except that the converter is not solving the `Audio Stream` problem, still getting the error
```
Configuration of "/var/www/html/uploads/3197055872.mp4" failed. You need to reupload the media (Not a single valid audio stream).
``` 
so I'm gonna close this issue and create another one.

**Comment by SteveJobzniak** [comment]
Hi @AliKhaleghi. Have you thought for a second about what the error says?

`Configuration of "/var/www/html/uploads/3197055872.mp4" failed. You need to reupload the media (Not a single valid audio stream).`

Do not open another issue about this.

Think about what the error says...

Now think a bit more.

Do you see it yet?

- `Configuration of "/var/www/html/uploads/3197055872.mp4" failed. You need to reupload the media (Not a single valid audio stream).`

- `You need to reupload the media (Not a single valid audio stream).`

- `Not a single valid audio stream.`

- `Not a single valid audio stream.`

- `Not a single valid audio stream.`

- `Not a single valid audio stream.`

- `Not a single valid audio stream.`

- `Not a single valid audio stream.`

**Comment by SteveJobzniak** [comment]
Regarding this and #1649, a future enhancement should be that we totally refuse to upload files with non-AAC audio streams or non-H264 video.
