### ISSUE TITLE
How to add one more Account in loop is already run.

### ISSUE THREAD

**Issue by thienit5** [mgp25/Instagram-API#1648]
I have a script run PUSH instances of multi accounts in same event loop.
But, while loop is running, if I add more PUSH instances of other account, this new PUSH instance does not work.
I must stop script and put function $loop->run() at the end of function $push->start() of all PUSH instances;

Can you give a way how to add more PUSH instances of others while loop is running

**Comment by SteveJobzniak** [comment]
I think I know the reason for your problem.

Every account must have its own `\InstagramAPI\Instagram()` object instance (and its own `\InstagramAPI\Push` instance). You cannot use multiple accounts on 1 instance.

**Comment by valga** [comment]
This question is actually covered by the FAQ. Let me quote it:
> But we leave that up to very advanced programmers and will not provide any assistance with such usage.

But I have a hint for you: take a look at `examples/realtimeHttp.php`. It runs an HTTP server that accepts some simple commands. You should make something like that: some command to start a Push client for the specific account and some command to stop it. But you will end up with existing storage handlers are not being safe with multiple scripts running in parallel (they might loose some data). And you will throw existing Push client and write your own, based on the raw Fbns client.

To conclude, it is indeed a very advanced topic, and nobody is going to assist you. You have been warned.
