### ISSUE TITLE
Uploading Watermarked Video into Instagram

### ISSUE THREAD

**Issue by AliKhaleghi** [mgp25/Instagram-API#1649]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors) ( Maybe ? )
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

I've been trying to upload a video into Instagram which works perfectly, But I want to add watermark to the video and then upload it, I'm using `php ffmpeg` project to add the watermark to the video, everything is working as expected until comes the time to upload the newly created `.mp4` file.
The error which Instagram keeps sending ( only for the file which was edited by `PHP FFMPEG` ) is : 
```
Configuration of "/var/www/html/uploads/8187906350.mp4" failed. You need to reupload the media (Not a single valid audio stream).
```
Here is the code which uploads the new file : 
```php

$options = array(
      'debug'	=>	true
);
$resizer = new \InstagramAPI\MediaAutoResizer($file,$options);
$send = $member->_insta->timeline->uploadVideo($resizer->getFile(), $metadata);
```
And this is the configurations I use for the video process.
```php
$watermarked_name = time().'.mp4';
$format = new FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
$format
-> setKiloBitrate(1000)
-> setAudioChannels(2)
-> setAudioKiloBitrate(256);
$video->save($format,$upload_to.$watermarked_name);
```
Well the error is kinda obvious, there is some kind of issue with the audio encoding which I know nothing about.

Any sort of help would be highly appreciated.

**Comment by mgp25** [comment]
Hello @AliKhaleghi,

This is not API issue but an issue with the video format. Maybe this website can help you with the video watermark: http://ksloan.net/watermarking-videos-from-the-command-line-using-ffmpeg-filters/

Regards

**Comment by SteveJobzniak** [comment]
Audio format must be AAC. Not Mp3.

**Comment by mgp25** [comment]
Hello there again @SteveJobzniak :-)

**Comment by SteveJobzniak** [comment]
Hi I have written to you on gitter, kept expecting to see you there. :P

**Comment by AliKhaleghi** [comment]
Thank you guys for replying, @stevejobzniak, if you could give me a sample of AAC format that’d help me a LOT !

**Comment by SteveJobzniak** [comment]
Hi. No. Research it yourself :)

**Comment by mgp25** [comment]
@AliKhaleghi google->search->AAC sample audio files

**Comment by AliKhaleghi** [comment]
Huh cool.

**Comment by AliKhaleghi** [comment]
Mhm Thanks anyways
