### ISSUE TITLE
Getting the list of "followers" of specific user ID

### ISSUE THREAD

**Issue by anonunder** [mgp25/Instagram-API#1652]
I am trying to get the list of followers by specific user, before update i was able to get the list, now i can't access the private array..

When executing the $response = $ig->people->getFollowers($userId);, i can't access to the private array. Any solutions?

**Comment by mgp25** [comment]
Hello @anonunder,

it seems you are using `dev-master` code. To get properties, follow this example:

- [accessingValues.php](https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php)

If you want to access, lets say, `users`, you need to do `->getUsers()`. If you want to access `media_items`, you need to do `->getMediaItems()`. And so on.

Regards

**Comment by SteveJobzniak** [comment]
@anonunder I think you're talking about `Virtual property access is disabled...` errors?

Already answered. Read this ticket: https://github.com/mgp25/Instagram-API/issues/1623
