### ISSUE TITLE
[SOLVED] hashtag- Search and getResults problem 

### ISSUE THREAD

**Issue by findandreplace** [mgp25/Instagram-API#1653]
Dear all : 

```
$search = $i->hashtag->search($input);
$data['results'] = $search->getResults();
print_r($data['results']);
```
how can we reach **`[name]`** and **`[media_count]`**

`Array( [0] => InstagramAPI\Response\Model\Tag Object ( [_compiledPropertyMapLink:LazyJsonMapper\LazyJsonMapper:private] => Array ( [media_count] => LazyJsonMapper\Property\PropertyDefinition Object ( [arrayDepth] => 0 [propType] => int [isObjectType] => ) [name] => LazyJsonMapper\Property\PropertyDefinition Object ( [arrayDepth] => 0 [propType] => string [isObjectType] => ) [id] => LazyJsonMapper\Property\PropertyDefinition Object ( [arrayDepth] => 0 [propType] => string [isObjectType] => ) ) [_objectData:LazyJsonMapper\LazyJsonMapper:private] => Array ( **[name] => TestTags [media_count] => 6366 [id] => 17843256937013437 )** ) `

since there is only 
`https://github.com/mgp25/Instagram-API/blob/master/src/Response/SearchTagResponse.php
`
` **@method Model\Tag[] getResults()**` and no getItem

**Comment by findandreplace** [comment]
```
$ids = [];
do {
    $search = $i->hashtag->search($tag, $ids);

    foreach ($search->getResults() as $result)
    {
        $ids[] = $result->getId();
    }
} while($search->getHasMore());
```

**Comment by SteveJobzniak** [comment]
@findandreplace Yeah you're kinda right, but here are some notes:

1. Stop using `print_r()` or `var_dump()`. It's really ugly. Use this brand new feature instead:

```php
$search->getResults()->printJson();
```

It's a feature of the new LazyJsonMapper library I added this month. You can use `printJson()` and `printPropertyDescriptions()` on any object in this API now.

More info here: https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php

2. Your solution is "right" but dangerous. In many ways.

Way number 1:

https://github.com/mgp25/Instagram-API/blob/cef2679a315ae049277b27fe7819cc94f2ab3d08/src/Request/Hashtag.php#L51-L53

(It will throw get an exception if you try to exclude 65 tags via your method.)

Way number 2:

https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php

(That is the proper way to paginate. With a `sleep()` between requests. Your current code is flooding Instagram with requests and will get blocked/throttled by their server.)

Good luck. :)
