### ISSUE TITLE
LazyJsonMapper private \UserInfoResponse

### ISSUE THREAD

**Issue by learningwithyou** [mgp25/Instagram-API#1655]
Hello dear mgp25 and Steve.

It was working before update..
`$ig->people->getSelfInfo()->user->pk`

but when i update 

> Something went wrong: Virtual property access is disabled for class 
> "\InstagramAPI\Response\UserInfoResponse".

I don't know how can i enabled for class ? 

Thank you for help.

**Comment by szokeptr** [comment]
With the new LazyJsonMapper you must use the getter functions to read the response data, you should use `$ig->people->getSelfInfo()->getUser()->getPk()`.

**Comment by learningwithyou** [comment]
@szokeptr how do you find **getPk();** ? How do you know can you tell me ?

Thank you so much.
