### ISSUE TITLE
PHP Fatal error:  Class 'LazyJsonMapper\LazyJsonMapper' not found in /vendor/mgp25/instagram-php/src/AutoPropertyMapper.php 

### ISSUE THREAD

**Issue by findandreplace** [mgp25/Instagram-API#1656]
I just update the lib and i got this error message !
`
PHP Fatal error:  Class 'LazyJsonMapper\LazyJsonMapper' not found in /vendor/mgp25/instagram-php/src/AutoPropertyMapper.php `

**Comment by SteveJobzniak** [comment]
`composer update -o`
