### ISSUE TITLE
how change stream_video_bit_rate ?

### ISSUE THREAD

**Issue by mohammadhosin** [mgp25/Instagram-API#1659]
how change stream_video_bit_rate ?
this is fixed in 786432 .
What should I add here? 

>  function create(
        $previewWidth = 700,
        $previewHeight = 980,
        $broadcastMessage = '')
    {
        return $this->ig->request('live/create/')
            ->addPost('_uuid', $this->ig->uuid)
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('preview_height', $previewHeight)
            ->addPost('stream_video_width', $previewWidth)
            ->addPost('broadcast_message', $broadcastMessage)
            ->addPost('broadcast_type', 'RTMP')
            ->addPost('internal_only', 0)
            ->getResponse(new Response\CreateLiveResponse());
    }`

**Comment by SteveJobzniak** [comment]
What are you talking about? The bitrate is not static. RTMP streaming uses VBR, variable bitrate.

Whatever number Instagram gives here does not matter:
https://github.com/mgp25/Instagram-API/blob/50e434f587f2229300122200e8bf712e3d62251f/src/Response/CreateLiveResponse.php#L143
