### ISSUE TITLE
API request limit

### ISSUE THREAD

**Issue by pankif** [mgp25/Instagram-API#1661]
What is the limit of the request to api per second / minute?

**Comment by SteveJobzniak** [comment]
Depends on the API call. Instagram counts them all differently (per api activity) and counts them all together too (total activity rate). Some are limited at 1 call per 120 seconds (any faster thna once per two minutes would lead to throttling errors). Some allow almost unlimited rate (something like 4500 calls per hour).

In general, if you wait 6.5 seconds between every API function you call, and don't do anything spammy, you should never get throttled,

**Comment by pankif** [comment]
@SteveJobzniak  Thanks for the answer! These limits are calculated for a request from a separate IP address? That is, if I log into two accounts using different proxy, then the limits will be triggered on each IP address of the proxy independently of each other?

**Comment by SteveJobzniak** [comment]
The limits are calculated with a single account on a single IP. I don't know if multiple accounts on a single IP get independent limits. But I am sure multiple accounts on DIFFERENT IPs would get independent limits, since Instagram would not know they are the same person.

**Comment by pankif** [comment]
You answered my question, thank you!

**Comment by cityvibesgr** [comment]
@pankif Did you happen to check whether multiple accounts on a single IP get independent limits? Thank you in advance.

**Comment by hxd520love** [comment]
I have the same question : **What's the limit of multiple accounts on a single IP?**
@pankif 
Thank you in advance.
