### ISSUE TITLE
Count Follow Request

### ISSUE THREAD

**Issue by osyduck** [mgp25/Instagram-API#1663]
Is it possible to count follow request?

**Comment by mgp25** [comment]
Hello @osyduck, 

Please next time, search and research before opening an issue like this, because we wont answer this kind of issues when are enough information.

```php
$response = $ig->people->getInfoByName($username);

$followers = $response->getUser()->followerCount();
```

**Comment by SteveJobzniak** [comment]
I think he means he wants to count how many people have requested to follow him?

Use this function and count the numbers in the result:

https://github.com/mgp25/Instagram-API/blob/1c2c67c4b02b41015214369b3ffa12f58834f608/src/Request/People.php#L185-L197

**Comment by osyduck** [comment]
But why max 200 users? Can i count all?

**Comment by SteveJobzniak** [comment]
@osyduck You will not get any more help until you start asking _clear_ questions, with some code examples of what you are doing and _what_ you want to achieve.
