### ISSUE TITLE
How can I get someone follow my account

### ISSUE THREAD

**Issue by amirkhh** [mgp25/Instagram-API#1666]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

I need to get a user follow my account or not, I used `getFriendships()` method in `People` class but I just get this empty output and I Can't understand this user with this instagram id follow me or not, can you help me for fix my challenge ?

Code:
```php
$isFollowMe = $this->ig->people->getFriendships([673848655]);
```

```
output:
(
            [following] => 
            [followed_by] => 
            [incoming_request] => 
            [outgoing_request] => 
            [is_private] => 1
            [is_blocking_reel] => 
            [is_muting_reel] => 
            [blocking] => 
            [is_bestie] => 
        )
```

**Comment by SteveJobzniak** [comment]
@amirkhh It's because that user does not exist. Literally:

```php
$ig->people->getInfoById(673848655); // throws NotFoundException
$ig->people->getFriendship(673848655); // throws NotFoundException
$ig->people->getFriendships([673848655]); // works but gives default response
```

Default response is: `{"friendship_statuses": {"673848655": {"following": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}}, "status": "ok"}`

**Comment by mgp25** [comment]
@amirkhh gitter

**Comment by SteveJobzniak** [comment]
It also looks like you were using `print_r()` which doesn’t show boolean true/false values and null etc. Otherwise you would have seen many false-values in your own test.

You hsould use `var_dump()` to look at objects in your version of this library.

And in the latest `dev-master` (see README for how to install it) we have a new command named `$someItem->printJson()`. It is much better because it only shows actual JSON data instead of a million different null values. You can learn more in `examples/accessingValues.php`.

**Comment by amirkhh** [comment]
Thank you so much @SteveJobzniak , You solved my problem.

I'm using var_dump now and that's work very good.

printJson() is nice.

thanks for your support.

**Comment by SteveJobzniak** [comment]
@amirkhh You're welcome. :-)
