### ISSUE TITLE
getNextMaxId, incorrect value

### ISSUE THREAD

**Issue by skn2215** [mgp25/Instagram-API#1668]
Hi. returns an incorrect value, what could be the reason?

```php
        $maxId  = null;
        $userId = $ig->people->getUserIdForName($userName);

        do {
            $response = $ig->people->getFollowers($userId, $maxId);
            var_dump($response);
            $maxId = $response->getNextMaxId();
            echo "Sleeping for 5s...\n";
            sleep(5);
        } while ($maxId !== null); // Must use "!==" for comparison instead of "!=".
```

var_dump:

```php
    ["next_max_id"]=>
    string(110) "AQBIJT-Nrzm53WaLUMrMt1MrREV2YfkM6JCC-Ird5OHJFd6jPBf_TMhqQR7hOxy96R_0Vz7zOdv9yxNgXhjttY_7WcA6nuppo7pNCLrXZniiNg"

```

**Comment by mgp25** [comment]
Hello @skn2215,

there is no issue here, it has its proper value.

Regards

**Comment by skn2215** [comment]
I do not quite understand why then the cycle always stops for 2-3 iterations?
several thousand subscribers

**Comment by mgp25** [comment]
@skn2215 that information is already posted. There are a lot of closed issues related to this one, and we have explained why that happens. Not API issue if you are wondering.

Use the search bar at the top of this repo to find the issues.

Regards
