### ISSUE TITLE
How do you get the "redirect message" media?

### ISSUE THREAD

**Issue by wictorChaves** [mgp25/Instagram-API#1670]
These are all the information I have in the "redirect message":

```
"InstagramAPI\Push\Notification::__set_state(array(
   '_json' => '{"bc":"{\\"di\\":1}","a":"https://scontent.cdninstagram.com/t51.2885-19/s150x150/22427084_1379006105560427_4701611062963731234_n.jpg","collapse_key":"direct_v2_message","badge":"1","s":"None","u":6268530506,"PushNotifID":"55cda2f7e256fH175a22f4aH55cda79142841H21","sound":"default","pi":"55cda2f7e256fH175a22f4aH55cda79142841H21","it":"wictor.123sent you a message.","m":"wictor.123 sent you a message.","ig":"direct_v2?id=340282366841710300949128174077142300032&x=27844775177168837278020018917867520"}',
   '_title' => NULL,
   '_message' => 'wictor.123 sent you a message.',
   '_tickerText' => NULL,
   '_igAction' => 'direct_v2?id=340282366841710300949128174077142300032&x=27844775177168837278020018917867520',
   '_igActionOverride' => NULL,
   '_optionalImage' => NULL,
   '_optionalAvatarUrl' => 'https://scontent.cdninstagram.com/t51.2885-19/s150x150/22427084_1379006105560427_4701611062963732480_n.jpg',
   '_collapseKey' => 'direct_v2_message',
   '_sound' => 'default',
   '_pushId' => '55cda2f7e256fH175a22f4aH55cda79142841H21',
   '_pushCategory' => NULL,
   '_intendedRecipientUserId' => '6268530506',
   '_sourceUserId' => 'None',
   '_badgeCount' =>
  InstagramAPI\Push\Payload\BadgeCount::__set_state(array(
     '_json' => '{"di":1}',
     '_direct' => 1,
     '_ds' => NULL,
     '_activities' => NULL,
  )),
   '_inAppActors' => NULL,
   '_actionPath' => 'direct_v2',
   '_actionParams' =>
  array (
    'id' => '340282366841710300949128174077142300032',
    'x' => '27844775177168837278020018917867520',
  ),
))Thread ID: 340282366841710300949128174077142300032. Thread item ID: 27844775177168837278020018917867520.
```

I tried this:

> var_export($ig->media->getInfo($push->getActionParam('id')));

```
$loop = \React\EventLoop\Factory::create();
$push = new \InstagramAPI\Push($loop, $ig, NULL);
$push->on('incoming', function (\InstagramAPI\Push\Notification $push) use ($ig){
    printf('"%s:%s"', 
            $push->getMessage(),
            PHP_EOL);
    echo "aqui: ";
    
    var_export($ig->media->getInfo($push->getActionParam('id')));
});
$push->on('like', function (\InstagramAPI\Push\Notification $push) {
    printf('Media ID: %s%s', $push->getActionParam('id'), PHP_EOL);
});
$push->on('comment', function (\InstagramAPI\Push\Notification $push) {
    printf(
        'Media ID: %s. Comment ID: %s.%s',
        $push->getActionParam('id'),
        $push->getActionParam('forced_preview_comment_id'),
        $push->getActionParam('message'),
        PHP_EOL
    );
});
$push->on('direct_v2_message', function (\InstagramAPI\Push\Notification $push) {
    printf(
        'Thread ID: %s. Thread item ID: %s.%s',
        $push->getActionParam('id'),
        $push->getActionParam('x'),
        PHP_EOL
    );
});
$push->on('error', function (\Exception $e) use ($push, $loop) {
    printf('[!!!] Got fatal error from FBNS: %s%s', $e->getMessage(), PHP_EOL);
    $push->stop();
    $loop->stop();
});
$push->start();

$loop->run();
```

But it has this error:

> Fatal error: Uncaught exception 'InstagramAPI\Exception\EmptyResponseException' with message 'No response from server. Either a connection or configuration error.' in C:\wamp64\www\Instagram\vendor\mgp25\instagram-php\src\Client.php:539
> Stack trace:
> #0 C:\wamp64\www\Instagram\vendor\mgp25\instagram-php\src\Request.php(705): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\MediaInfoResponse), NULL, Object(GuzzleHttp\Psr7\Response))
> #1 C:\wamp64\www\Instagram\vendor\mgp25\instagram-php\src\Request\Media.php(34): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\MediaInfoResponse))
> #2 C:\wamp64\www\Instagram\vendor\mgp25\instagram-php\examples\testeRedirect.php(24): InstagramAPI\Request\Media->getInfo('340282366841710...')
> #3 [internal function]: {closure}(Object(InstagramAPI\Push\Notification))
> #4 C:\wamp64\www\Instagram\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(70): call_user_func_array(Object(Closure), Array)
> #5 C:\wamp64\www\Instagram\vendor\mgp25\instagram-php\s in C:\wamp64\www\Instagram\vendor\mgp25\instagram-php\src\Client.php on line 539

**Comment by SteveJobzniak** [comment]
A push is just a simple way to tell the app to do stuff. It doesn't have any deep data about the message etc.The only interesting parts of the `InstagramAPI\Push\Notification` object are these:

```
   '_actionPath' => 'direct_v2',
   '_actionParams' =>
  array (
    'id' => '340282366841710300949128174077142300032',
    'x' => '27844775177168837278020018917867520',
  ),
```

It's telling the Instagram app to go to the `direct_v2` module and load thread with ID `id` and fetch it and scroll to item (message) with ID `x`.



To get the thread you simply have to

**Comment by SteveJobzniak** [comment]
PS: Your code is wrong. You cannot `var_export($ig->media->getInfo($push->getActionParam('id')));`. It's not a media. It's a thread message ID.

**Comment by SteveJobzniak** [comment]
One question: Why are you catching this in the `on('incoming')`? I would expect that this also fires the `on('direct_v2_message')` which is the correct place to handle the message.

**Comment by wictorChaves** [comment]
I did this but the items are old:

```
$thread_id = $push->getActionParam('id');
$itens = $ig->direct->getVisualThread($thread_id)->getItems();
```

**Comment by SteveJobzniak** [comment]
@wictorChaves I have no idea. Maybe you load the thread too fast before it has updated on the server. What happens if you `getVisualThread` now? Does it have the new item?

**Comment by wictorChaves** [comment]
Ele sempre retorna com as mesma imagens, as imagens novas não chegam:

```

$push->on('direct_v2_message', function (\InstagramAPI\Push\Notification $push) use ($ig) {
    printf(
            'Thread ID: %s. Thread item ID: %s.%s', $push->getActionParam('id'), $push->getActionParam('x'), PHP_EOL
    );
    $thread_id = $push->getActionParam('id');
    $array = $ig->direct->getVisualThread($thread_id)->getItems();
    $urls = array();
    if (is_array($array)) {
        foreach ($array as $i => $item) {
            $candidates = $item->getRavenMedia()->getImageVersions2()->getCandidates();
            foreach ($candidates as $j => $candidate) {
                $urls[$i][$j] = $candidate->getUrl();
            }
        }
    } else {
        echo "nao array";
    }
    echo '--------------------------------------------------------';
    foreach ($urls as $item) {
        foreach ($item as $url) {
            echo $url . "\n";
        }
    }
    echo '--------------------------------------------------------';

    //var_export($ig->direct->getThread($thread_id));
});
```

**Comment by SteveJobzniak** [comment]
@wictorChaves Hmm. And what was the difference between getVisualThread vs getThread?

**Comment by wictorChaves** [comment]
I don´t know

**Comment by SteveJobzniak** [comment]
Me neither a feeling makes me guess that getThread is the correct one to get all messages. Have you tried looking in that one for the message ID?

**Comment by SteveJobzniak** [comment]
@valga Thanks for the answer. Excellent, I've documented them to avoid more confusion: https://github.com/mgp25/Instagram-API/commit/b89130510dd04fa827e13dc4d84b62cb11b29e11

 :)

**Comment by wictorChaves** [comment]
I can create an event, type:

`$push->on ('send_message' ...`

And through it send message via socket?

**Comment by SteveJobzniak** [comment]
@wictorChaves Did you seriously just ask us if you can type `$push->on('some_magic_thing_i_want_to_do'` and magically send messages, without implementing any other code? Did you seriously just ask us that?

**Comment by wictorChaves** [comment]
I know, that's precisely why I'm asking.

**Comment by SteveJobzniak** [comment]
The answer is no. You can't type `DoSomethingMagic()`.

Someone would have to implement that function. You can't just invent imagined Push events without adding any code for them.
