### ISSUE TITLE
The photo is duplicated when publishing in timeline or stories.

### ISSUE THREAD

**Issue by frontalinilucas** [mgp25/Instagram-API#1671]
When I upload photo in timeline or stories, the photo is duplicated.

```php
$ig = new \InstagramAPI\Instagram(false, true);
$ig->login(XXX, XXX);
$ig->story->uploadPhoto("img2.jpg", $metadata);
```

**Comment by SteveJobzniak** [comment]
Uhm, no it's not?

You're probably running your code twice?

**Comment by mgp25** [comment]
Hello @frontalinilucas,

you are probably running the code twice, but that is not API issue. Please, check your code, and if you still face the same issue, post all your script code.

Regards

**Comment by frontalinilucas** [comment]
This is my code, it is upload in heroku. And then run this code by GET and post twice.

require('../vendor/autoload.php');

$ig = new \InstagramAPI\Instagram(false, true);
$ig->login(XXX, XXX);

$MIN_PROPORCION_IMAGE_INSTA = 0.6;
$img_src = imagecreatefromstring(file_get_contents("img.png"));
$new_width = imagesx($img_src);
$new_height = $new_width / $MIN_PROPORCION_IMAGE_INSTA;
$img_dest = imagecrop($img_src, ['x' => 0, 'y' => 385, 'width' => $new_width, 'height' => $new_height]);
imagejpeg($img_dest, "img2.jpg", 100);

$metadata = [
    'hashtags' => [
        // Note that you can add more than one hashtag in this array.
        [
            'tag_name'         => 'test', 
            'x'                => 0.5, // Range: 0.0 - 1.0
            'y'                => 0.5, // Note that x = 0.5 and y = 0.5 is center of screen.
            'width'            => 0.24305555, // Percentage: 0.0 - 1.0
            'height'           => 0.07347973, // Percentage: 0.0 - 1.0
            'rotation'         => 0.0,
            'is_sticker'       => false, // Don't change this value.
            'use_custom_title' => false, // Don't change this value.
        ],
    ],
    'caption' => '#test This is a great API!',
];

try {
$ig->story->uploadPhoto("img2.jpg", $metadata);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

$ig->logout();

**Comment by mgp25** [comment]
@frontalinilucas 

Why are you doing?

```php
$MIN_PROPORCION_IMAGE_INSTA = 0.6;
$img_src = imagecreatefromstring(file_get_contents("img.png"));
$new_width = imagesx($img_src);
$new_height = $new_width / $MIN_PROPORCION_IMAGE_INSTA;
$img_dest = imagecrop($img_src, ['x' => 0, 'y' => 385, 'width' => $new_width, 'height' => $new_height]);
imagejpeg($img_dest, "img2.jpg", 100);
```

You can do this instead:

```php
$resizer = new \InstagramAPI\Media\Photo\PhotoResizer($photoFilename);
$ig->story->uploadPhoto($resizer->getFile(), $metadata);
```

Easier right?

Another thing:

```php
$ig->logout();
```

You shouldn't do that. When you use Instagram in your device, are you constantly logging out? The same happens here, you keep using the same session. No need to `logout()`.

It seems your script is being run twice, im sorry but it is not API issue, check wether you are doing the same request twice or so.

Regards

**Comment by frontalinilucas** [comment]
Ok, thanks. I'll check the code.

I am using the logout because it returns 500 code, and then login in Instagram App and it makes me verify that it's me, because it detected a suspicious login.
And then there it returns 200 and it works.
