### ISSUE TITLE
Installation Step

### ISSUE THREAD

**Issue by putuoka** [mgp25/Instagram-API#1679]
Hi, i have successfully run the composer and this is the results in my local https://i.imgur.com/pC9dseg.png what should i do now? i willing to try using PHP built-in web server something like PHP -S localhost:3 but i don't know where's the root folder? should i install xampp or wamp? please enlightning me

**Comment by mgp25** [comment]
Hello @putuoka,

Not API related issue + read wiki + see examples + read F.A.Q.
