### ISSUE TITLE
can we accept multiple follow request through same api call ?

### ISSUE THREAD

**Issue by hsingla94** [mgp25/Instagram-API#1680]
can we pass a userid array here, i want to accept request real fast. Max limit is 200 i know, I was using a tool on internet before but it is not working now, So thought to take a initiative myself

         public function approveFriendship(
         $userId)
        {
         return $this->ig->request("friendships/approve/{$userId}/")
            ->addPost('_uuid', $this->ig->uuid)
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('user_id', $userId)
            ->addPost('radio_type', 'wifi-none')
            ->getResponse(new Response\FriendshipResponse());
         }
Thanks in advance.

**Comment by mgp25** [comment]
The thing i hate the most is spammers. Im sorry but there is no place here for you

Regards
