### ISSUE TITLE
Mimic  instagram calls and version 

### ISSUE THREAD

**Issue by myoldland** [mgp25/Instagram-API#1682]
Hello , 
First of all i am new here , and Thank you for this great job , hopefully it will last for 10 years :+1: 
Well , before start using the lib with my project , i have some concerns i like to share.

## Instagram app version
By reviewing the code : 
`    const IG_VERSION = '12.0.0.7.91';` 

While the current instagram  version `21.0.0.11.62`

I can understand that we can not match the latest instagram version , but there is at least 7 releases between the lib and the current version , which mean instagram may stop all old versions and ask users to upgrade , is this right ?

## Mimic  instagram calls
After a lot of search , i failed to patch latest version of instagram after a lot of tries. do you have a copy of the patched APK you can share ?
But if you are working on `12.0.0.7.91` then we will have the same problem .

More over , i note by sniffing an old instagram version that instagram do some extra calls to the end points which this lib dont.
May be it is the different between my test version  and `12.0.0.7.91` .

## In Summary
1- I am sure that you are aware about that , and may be you know that is safe to use this lib even with this different between current instagram version  and the  const IG_VERSION, but i want to be sure

2- I like to be able to sniff latest instagram version  , and i dont find any way to do that , even by patching via recompile the APK , sure i tried to change the cafetiere part , but it seems not work at all. 
So is there any Documentation talking about the latest version  and how to patch it .

3- Dos instagram care about the ` IG_VERSION`  or `IG_SIG_KEY ` , which is easy to extract , Thanks to Wiki description.

4- I know , instagram will know eventually that the call is not coming  form the real app , but at least we try to respect how instagram works , i am sure you are donig that , i note how the lib is login and try to mimic instagram login process , but i have these concerns  and i will be very happy to share what we know to  contributing / enrichment  open source community.

With kindly Regards
MyOldLand / Jess Brawn

**Comment by mgp25** [comment]
@myoldland 

1. We **always** use safe data for Instagram API users.
2. You will need to learn reverse engineering then.
3. Yes, in fact, these are very important values, but there are also some changes along with version update.
4. As the 1. says, we **always** use safe data, that means, we replicate as much as possible app behavior.

In case you want latest Instagram signature key, data and so, you can always acquire a premium licence subscription (explained in other opened issue).

Regards
