### ISSUE TITLE
Anyone figured out video_dash_manifest in stories?

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1683]
I noticed that some stories recently have some extra DASH data. Not all stories. Just a few of them!

```
"is_dash_eligible": 1,
"video_dash_manifest": "a bunch of XML describing dash streaming URLs"
```

So a few stories now have `video_versions` as usual, but _also_ DASH streaming URLs.

It seems logical to me that the quality of the DASH URL is going to be less than the quality of the top-quality `video_versions` file, since [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) is a segmented and recompressed (into multiple bitrates per segment) livestream format, whereas the top-quality static MP4 has always been the best publically available static file on the server.

So: Has anyone figured out what Instagram is doing with the DASH-ing of _some_ stories?

**Comment by valga** [comment]
The word "segmented" reminds me of segmented video uploader, that is being rolled out.

**Comment by SteveJobzniak** [comment]
@valga Yeah good point, it may be tied to that... It's going to need some watching to figure out if the quality of the segments will be better or worse than the normal `video_versions` files...

**Comment by SteveJobzniak** [comment]
I also noticed that the DASH manifest has XML with something like "format quality="sd"". So it looks like their dash metadata is HD-ready if they wanna turn that on in the future.

**Comment by SteveJobzniak** [comment]
Here's some censored data, which interestingly shows that segment duration is 2 seconds (not 5 as you discovered). And note again: This dash stuff is rare. It happens for some users, for some of their stories. It may be an experiment Instagram is trying on some users and which isn't always on.

`"video_dash_manifest": "<MPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" minBufferTime=\"PT1.500S\" type=\"static\" mediaPresentationDuration=\"PT0H0M5.700S\" maxSegmentDuration=\"PT0H0M2.000S\" profiles=\"urn:mpeg:dash:profile:isoff-on-demand:2011,http://dashif.org/guidelines/dash264\"><Period duration=\"PT0H0M5.700S\"><AdaptationSet segmentAlignment=\"true\" maxWidth=\"640\" maxHeight=\"854\" maxFrameRate=\"30\" par=\"360:640\" lang=\"eng\" subsegmentAlignment=\"true\" subsegmentStartsWithSAP=\"1\"><Representation id=\"[CENSORED MEDIA PK]vd\" mimeType=\"video/mp4\" codecs=\"avc1.4d401e\" width=\"640\" height=\"1138\" frameRate=\"30\" sar=\"5121:5120\" startWithSAP=\"1\" bandwidth=\"1878081\" FBQualityClass=\"sd\" FBQualityLabel=\"640w\"><BaseURL>https://[CDNHOST]/v/t72.14836-16/[FILENAME]_n.mp4?oh=[ENCRYPTION KEY]&amp;oe=[ENCRYPTION KEY]</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"920-987\"><Initialization range=\"0-919\"/></SegmentBase></Representation><Representation id=\"CENSORED MEDIA PK]v\" mimeType=\"video/mp4\" codecs=\"avc1.4d401e\" width=\"480\" height=\"854\" frameRate=\"30\" sar=\"1281:1280\" startWithSAP=\"1\" bandwidth=\"1267178\" FBQualityClass=\"sd\" FBQualityLabel=\"480w\"><BaseURL>https://[CDNHOST]/v/t72.14836-16/[FILENAME]_n.mp4?oh=[ENCRYPTION KEY]&amp;oe=[ENCRYPTION KEY]</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"919-986\"><Initialization range=\"0-918\"/></SegmentBase></Representation><Representation id=\"[CENSORED MEDIA PK]v\" mimeType=\"video/mp4\" codecs=\"avc1.4d401e\" width=\"360\" height=\"640\" frameRate=\"30\" sar=\"1:1\" startWithSAP=\"1\" bandwidth=\"862999\" FBQualityClass=\"sd\" FBQualityLabel=\"360w\"><BaseURL>https://[CDNHOST]/v/t72.14836-16/[FILENAME]_n.mp4?oh=[ENCRYPTION KEY]&amp;oe=[ENCRYPTION KEY]</BaseURL><SegmentBase indexRangeExact=\"true\" indexRange=\"899-966\"><Initialization range=\"0-898\"/></SegmentBase></Representation></AdaptationSet></Period></MPD>"`

We learn a few things:

1. They have a new `"v"` URL flag: `/v/` and I don't know its purpose.
2. They have a new media type URL flag: `/t72.14836-16/`.
3. They use `?oe=...&oh=...` encryption keys to protect the URLs. The data can only be read via those keys. This is the same URL protection system Facebook uses. However, the keys are universal (same for every account that views the media).

**Comment by SteveJobzniak** [comment]
As for the new media type flag, I have analyzed and documented those in the past.

Here's the format: `t<media type a>.<media type origin><media type origin filetype>-<media type b>.`

I don’t know their reason for having two “media type” identifiers (which I’ve called “a” and “b” above), but it’s very likely that one means “type category” (such as Video or Image) and the other means “subtype” (such as MP4 or JPG). So if they add other file formats in the future, they are very likely to add a different combination of media types.

All MP4 videos used the pattern `t50.####-16`, and all JPG images (both normal images, and still-image previews for videos) used the pattern `t51.####-15`.

As for the remaining fields: `<media type origin>` was always `288` for media that comes from timelines, and `979` for media that comes from stories. And the `<media type origin filetype>` was `5` for JPG images in timelines and `6` for MP4 videos in stories, and `2` for JPG images in stories and `3` for MP4 videos in stories.

Putting it all together gave us these four Instagram media types:

- `/t50.2886-16/` = MP4 Videos in Timelines.
- `/t51.2885-15/` = JPG Images in Timelines.
- `/t50.9793-16/` = MP4 Videos in Stories.
- `/t51.9792-15/` = JPG Images in Stories.

That's why the new one is such a weird outlier... `/t72.14836-16/` The `-16` means MP4. The rest is weird... We have type A = 72. And we have origin = 1483. And origin filetype = 6. It goes against all of their previous rules...

But my guess is: The new type refers to protected media (media with oh+oe URL encryption keys).

**Comment by SteveJobzniak** [comment]
Instagram keeps experimenting...

I saw a story deliver `video_versions` URLs with `/vp/t<i forgot>/<oh encryption key>/<oe encryption key>/<filename>.mp4`.

News is `/vp/` and the way of putting encryption keys in the URL path instead of the `?query`.

But when I reloaded the info to report the exact data to this thread, the whole thing had switched to `?oh=...&oe=...` as usual.

So I think we need to relax and wait for perhaps 2 weeks until Instagram has finished their experiments and decided on their new CDN formats...

**Comment by SteveJobzniak** [comment]
I can draw ONE conclusion though: Instagram is being moved more and more onto Facebook's URL protection system, with oh/oe keys that guard access to files, and even expire after a while (to prevent resharing).

**Comment by SteveJobzniak** [comment]
They continue to experiment...

Now, even photos have `/vp/` in the URL. I thought it may have meant "video protected" but clearly not since jpgs are protected too.

And now they protect the `/e##/` flag. That flag controls the writing of the EXIF FBMD tag. Which is "just a harmless tag, right?". Wrong. By including that flag or any other flag which relies on their server-side image processor, you cause their server to recompress the whole file. It literally loads the JPG, then writes a new one to the browser (at god-knows-what-quality %), and adds the EXIF "FBMD" tag.

This sucks. They're basically going closer and closer to facebook, where it's impossible to clean up URLs to retrieve original, unmodified files. Sigh.
