### ISSUE TITLE
getHomeChannelFeed return null items

### ISSUE THREAD

**Issue by rmiran** [mgp25/Instagram-API#1684]
hi!
please help me
getHomeChannelFeed return null items!
Is there a solution?

**my code:**

```
<?php
set_time_limit(0);


require __DIR__.'/vendor/autoload.php';

/////// CONFIG ///////
$username = 'myusername';
$password = '*****';
$debug = false;
$truncatedDebug = false;
//////////////////////


$ig=new \InstagramAPI\Instagram($debug,$truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
    $res = $ig->discover->getHomeChannelFeed();
    $items = $res->getItems();
   header('Content-type: application/json');
    echo json_encode($items);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

**output :** 

> {
> "pk": null,
> "id": null,
> "media_type": null,
> "code": null,
> "visibility": null,
> "taken_at": null,
> "device_timestamp": null,
> "client_cache_key": null,
> "filter_type": null,
> "attribution": null,
> "image_versions2": null,
> "original_width": null,
> "original_height": null,
> "view_count": null,
> "viewer_count": null,
> "organic_tracking_token": null,
> "comment_count": null,
> "has_more_comments": null,
> "max_num_visible_preview_comments": null,
> "preview_comments": null,
> "comments": null,
> "comments_disabled": null,
> "reel_mentions": null,
> "story_cta": null,
> "caption_position": null,
> "expiring_at": null,
> "is_reel_media": null,
> "next_max_id": null,
> "carousel_media": null,
> "carousel_media_type": null,
> "caption": null,
> "caption_is_edited": null,
> "photo_of_you": null,
> "video_versions": null,
> "has_audio": null,
> "video_duration": null,
> "user": null,
> "likers": null,
> "like_count": null,
> "preview": null,
> "has_liked": null,
> "explore_context": null,
> "explore_source_token": null,
> "explore": null,
> "impression_token": null,
> "usertags": null,
> "media": null,
> "stories": null,
> "top_likers": null,
> "suggested_users": null,
> "is_new_suggestion": null,
> "comment_likes_enabled": null,
> "can_viewer_save": null,
> "has_viewer_saved": null,
> "location": null,
> "lat": null,
> "lng": null,
> "story_locations": null,
> "algorithm": null,
> "channel": null,
> "gating": null,
> "story_hashtags": null,
> "ad_action": null,
> "is_dash_eligible": null,
> "video_dash_manifest": null,
> "number_of_qualities": null,
> "injected": null,
> "placeholder": null,
> "social_context": null,
> "icon": null,
> "media_ids": null,
> "media_id": null,
> "thumbnail_urls": null,
> "large_urls": null,
> "media_infos": null,
> "value": null,
> "collapse_comments": null,
> "ad_metadata": null,
> "link": null,
> "link_text": null,
> "link_hint_text": null,
> "iTunesItem": null,
> "ad_link_type": null,
> "ad_header_style": null,
> "dr_ad_type": null,
> "android_links": null,
> "force_overlay": null,
> "hide_nux_text": null,
> "overlay_text": null,
> "overlay_title": null,
> "overlay_subtitle": null,
> "playback_duration_secs": null,
> "url_expire_at_secs": null,
> "is_sidecar_child": null,
> "comment_threading_enabled": null,
> "collection_id": null,
> "collection_name": null,
> "cover_media": null,
> "saved_collection_ids": null,
> "boosted_status": null,
> "boost_unavailable_reason": null,
> "viewers": null,
> "viewer_cursor": null,
> "total_viewer_count": null,
> "multi_author_reel_names": null,
> "reel_share": null,
> "story_polls": null,
> "organic_post_id": null,
> "sponsor_tags": null,
> "story_poll_voter_infos": null,
> "imported_taken_at": null,
> "lead_gen_form_id": null,
> "ad_id": null,
> "actor_fbid": null
> }

**Comment by SteveJobzniak** [comment]
Search closed issues for "null". You will find many answers about this. That is how the old API works (v3.0 and earlier). We use PHP objects which have tons of properties, and not everything is filled.

If you want the next (in development) v4.0 of this API, download `dev-master` (see README). It does not have the NULLs anymore.
