### ISSUE TITLE
Not initializing API

### ISSUE THREAD

**Issue by snake302** [mgp25/Instagram-API#1686]
Hi there!

1) I have installed composer with all dependences and  mgp25/instagram-php.
2) I copied code from "/var/www/html/vendor/mgp25/instagram-php/examples" example to my directory.
3) Code crashing after 4 API initializing

Can you pls help me to solve this issue? I am trying to fix it around 2 hours...

<img width="669" alt="screen shot 2017-11-10 at 12 57 08" src="https://user-images.githubusercontent.com/1431423/32653073-96a8efb4-c617-11e7-83da-b214e30fffac.png">
<img width="269" alt="screen shot 2017-11-10 at 12 57 01" src="https://user-images.githubusercontent.com/1431423/32653075-9a8abb30-c617-11e7-825b-4515a6d4be4b.png">
<img width="306" alt="screen shot 2017-11-10 at 12 58 54" src="https://user-images.githubusercontent.com/1431423/32653081-9c43d290-c617-11e7-9d40-2fc7081e95bc.png">

**Comment by snake302** [comment]
Solved by giving permission 777.

**Comment by SteveJobzniak** [comment]
Probably had no write permissions of data storage.

https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-the-500-http-error-code-mean
