### ISSUE TITLE
people->follow() does not seem to work

### ISSUE THREAD

**Issue by snkp1** [mgp25/Instagram-API#1689]
follow() does not seem to work. It does not return any error, but the 'following' status remains "false".
unfollow() still works.

simple code to test:
----------------

$username = 'xxx';
$password = 'xxx';
$id_to_follow = '10206720';

$ig = new \InstagramAPI\Instagram(true, true);
$ig->login($username, $password);
$response = $ig->people->follow($id_to_follow);
var_dump($response);

----------------

debug:

POST: https://i.instagram.com/api/v1/friendships/create/10206720/ DATA: signed_body=c13bc91613c13ee09b336943a5d89af78a175e495727cc14dfb24b08635b13ee.{"_csrftoken":"LyOpdrUBfkr7TlIfnEBiYJn55GA2wpPh","user_id":"10206720","radio_type":"wifi-none","_uid":"5035292234","_uuid":"41e36f78-c746-41e2-9bde-226b84cbf022"}&ig_sig_key_version=4 ← 200 195B RESPONSE: {"friendship_status": {"following": false, "followed_by": false, "blocking": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "status": "ok"}

and response:
object(InstagramAPI\Response\FriendshipResponse)[62]
  public 'friendship_status' => 
    object(InstagramAPI\Response\Model\FriendshipStatus)[48]
      public 'following' => boolean false
      public 'followed_by' => boolean false
      public 'incoming_request' => boolean false
      public 'outgoing_request' => boolean false
      public 'is_private' => boolean false
      public 'is_blocking_reel' => null
      public 'is_muting_reel' => null
      public 'blocking' => boolean false

**Comment by SteveJobzniak** [comment]
Hmm. This is you:

![you](https://user-images.githubusercontent.com/22373193/32668450-e4eccff8-c63d-11e7-8c9d-82ae418c0645.png)

Are you doing anything spammy? Mass likes? Mass comments? Mass following?

**Comment by snkp1** [comment]
yes that's one account. I tried with others accounts and also didn't work.
not spamming, not mass likes, not mass comments. 

every other function works perfectly. except the follow().

**Comment by mgp25** [comment]
@SteveJobzniak this guy is @snkpsnkp

**Comment by SteveJobzniak** [comment]
@snkp1 @snkpsnkp Hey you have been unblocked again. Mgp, probably rightly, suspected that you're spamming and following lots of people. Because you said that the function "stopped working a few days ago" (meaning it worked before that). Meaning you've probably followed enough people that Instagram said "enough! this is a spammer who randomly follows people!".

If you're not spamming, then we apologize. Please explain even more in detail what has happened. Can you list your accounts where the function has stopped working?

**Comment by albrox** [comment]
I do have a similar issue. I am working with several accounts and I have one account, that does not seem to follow. If i switch to another one, it works. 
The account is not blocked. I can follow people manually on the web interface.
Is there btw a function to check if a certain account is following my account or if I am following the user already?
