### ISSUE TITLE
Feature request and/or a thing for researching: Live with friends

### ISSUE THREAD

**Issue by solomax2014** [mgp25/Instagram-API#1690]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

There's a new feature in Instagram: live with friends. I don't know if existing methods in this API can work with them. Anyway. I've decompiled new APK and found some of the endpoints (and params, that I see in code) that can be related:
- ```"live/%s/request_to_join/"```
- ```"live/%s/get_join_requests/"```
- ```"live/%s/broadcast_event/"``` (it's located in ```livewith``` folder, so it can be related)
- - ```"event_type"```
- - ```"offset_to_video_start"```
- - ```"client_version"```
- - ```"event_user_id"```
- ```"live/%s/get_join_request_counts/"``` (from ```livewith``` again)
- - ```"last_fetch_ts"```

Maybe I'm missing something, but here are things that I've found. Of course, needs to be verified through capturing.

EDIT: One note here: I have a Windows 10 Instagram app, that make a notification when there is a new live with a friend, So maybe it's also a point for push/realtime notifications research.

**Comment by mgp25** [comment]
Will check it tomorrow

Regards

**Comment by SteveJobzniak** [comment]
Hmm. Don't rush this. Needs research.

Seems like the feature is named "Live with Friends", and affects both live and replays.

https://www.theverge.com/2017/10/24/16534830/live-instagram-broadcast-with-friend-update

Ugh Instagram and their neverending new features...

**Comment by solomax2014** [comment]
@mgp25, @SteveJobzniak, the most interesting part for me if there are two separated broadcasts or there is one that was merged by server. Btw, can usual live be transformed into live with friend by inviting that friend and in other direction, after friend's disconnecting? Is it an another live/liveID after inviting? So many questions...

**Comment by solomax2014** [comment]
@mgp25, @SteveJobzniak, just received WIndows 10 app (push?) notification about this kind of live:
```USER1 is going live now with USER2.```

**Comment by mgp25** [comment]
@solomax2014 try to give only android related data. Information from other platform will be considered.

And yes, i have data about that in Instagram, in any of the cases, notifications it is something @valga is doing. I'll soon add the different requests made to do a shared live.

**Comment by valga** [comment]
Push: just a version bump is required. And then we will be able to document `livewith` pushes.

Realtime: as far as I can see, it is used as some kind of control channel for `livewith` broadcasts. The app calls `live/%s/confirm/` endpoint with some data from realtime event payload. But I could be wrong about that.

And speaking of new features, I just saw some realtime events for video calls.

**Comment by solomax2014** [comment]
I've found that in some lives (at least, that was started alone and other user was invited then) it is just a split screen, everything works good just like usual lives (I'm telling this just by looking at some live captures from my monitoring script). Maybe it isn't something new, just writing this fact here.

**Comment by SteveJobzniak** [comment]
Thanks @solomax2014. This feature is complicating things and none of us are working on it right now (December is a bad month for work heh). And any extra info such as what you posted will help. :-)

**Comment by xcentgroup** [comment]
@solomax2014 Hey Max, i saw that you found a solution how a user can join to other user streams.
I tried this endpoint $this->request("live/{$broadcastId}/join/") but it is not working, maybe you have a solution?

Thanks!!!

**Comment by solomax2014** [comment]
@xcentgroup, if I recall correctly, it requires some internal parameters, can't remember which. Anyway I don't know how joining works, I only found that endpoint.

**Comment by HarryRowolt** [comment]
Do you see the endpoint to livestream in this new APK? "end" doesn't seem to work....

**Comment by rinaldohack** [comment]
Is this already possible to do from API?

**Comment by rossmase** [comment]
Glad to see others are requesting this as would love to see this feature. Is this possible currently from the API?

Thanks!

**Comment by milad74yari** [comment]
Did someone find a way to join to Live?

[https://github.com/mgp25/Instagram-API/issues/2095](url)

**Comment by mgp25** [comment]
I close this issue. We'll be working on these requests and which is the best way to implement webRTC features.

Regards

**Comment by victorjln** [comment]
Hi there, 
Is there any solution here to add a friend to the live ? I guess it should be written in [Live](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Live.php) but I cant find the request. Thanks.
