### ISSUE TITLE
move session from file to database

### ISSUE THREAD

**Issue by letungit90** [mgp25/Instagram-API#1691]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

At first, thank for this great package.
I am using Instagram-API in my project, i am using default file session.
Now i want to change the session to database, so can i copy session now from file to database ?
and if i change the server ip, do i have to login again to get the new session ? or the session is not relative with the server IP ?

**Comment by SteveJobzniak** [comment]
https://github.com/mgp25/Instagram-API/blob/master/examples/customSettings.php

To copy from file to database is not supported natively but it can be done...

Wait, I will code an example for you soon.

**Comment by SteveJobzniak** [comment]
@letungit90 Ugh, it was gonna be a quick example, but required 3 hours of refactoring to make it possible. I hope you are happy with this and let me know it was appreciated. ;-P

https://github.com/mgp25/Instagram-API/commit/7d974cbf9b33a823c40ec5cdead28565bc45460e

https://github.com/mgp25/Instagram-API/commit/f97bf1ef2ad0d9916cb6c8793719739e0cc0c2c4
