### ISSUE TITLE
Tracking count of API calls

### ISSUE THREAD

**Issue by chicag0** [mgp25/Instagram-API#1692]
I'd like to keep  track of how many times I am hitting the IG api over a certain time period.  Is there a single place that I could add a bit of code to do this?

**Comment by mgp25** [comment]
Hello, that should be done at your side, not in the API side.

```
counter

if something:
    do ig Call
    counter +1
```

Regards

**Comment by SteveJobzniak** [comment]
Hi. Yes you can count API calls either here:

https://github.com/mgp25/Instagram-API/blob/32f6c7289b052ff397bc6a5cea805f2139627652/src/Client.php#L780

Or here:

https://github.com/mgp25/Instagram-API/blob/master/src/ClientMiddleware.php

**Comment by SteveJobzniak** [comment]
PS: I agree with mgp. We will not add an official counter. But you asked about how you can personally modify our code to add a count. You can use one of the files I listed.

And if you use composer-patches (Google it, we will not help), you can setup an autopatch that applies your change every time you update code via composer.

**Comment by mgp25** [comment]
@SteveJobzniak can you gitter now?

**Comment by SteveJobzniak** [comment]
@mgp25 Sure, in five minutes

**Comment by chicag0** [comment]
Thanks, yes as I said in my post, I was looking for the best place where I could add a counter, I was not expecting you to modify the code.

**Comment by mgp25** [comment]
@SteveJobzniak dont forget please

**Comment by SteveJobzniak** [comment]
@mgp25 omfg sorry, I got lost in family dinner. Bad timing.
