### ISSUE TITLE
Issue with lazy json

### ISSUE THREAD

**Issue by BaderAlmudarra** [mgp25/Instagram-API#1693]
Hi,

Recently after the LazyJsonMapper was introduced to this library, I was able to return the response of a specific call like this:
`$feed = $ig->hashtag->getFeed('yourTag')->asJson();`

And when I need the output of most recent items, I can only specify which item to return, in the following case it will return the first item in most recent items.
`
$feed = $ig->hashtag->getFeed('yourTag')->getItems()[0]->asJson();`

However, I am unable to return the output of response sub-items such as items, ranked items or users as json:

For example, the following code won't work.
`$feed = $ig->hashtag->getFeed('yourTag')->getRankedItems()->asJson();`

I don't want to use loops or to return the whole response (larger size => higher traffic), I just want to return the needed part of the response in json format.

**Comment by mgp25** [comment]
```php
$results = json_decode($i->hashtag->search('yourTag')->asJson(), true);
$wantedResponse = json_encode($results['results']);
```

**Comment by SteveJobzniak** [comment]
@mgp25 lol at `$i` (the standardized loop variable name). Old bad habits die hard? :P

@BaderAlmudarra That is because some parts are objects, others (like getRankedItems() are PHP native types like string, array, etc)! There's absolutely _nothing_ we can do about that. We can't magically make PHP's raw arrays capable of `->asJson()`.

And you certainly cannot do `json_encode($lazyObject)` because that would do something weird (most likely encode the objects as strings).

I guess the method suggested by mgp25 is your best choice. Unfortunately that one will recursively process the whole response into resolved objects and then convert the whole thing to JSON, just to be able to decode it again to get a small part as JSON. It would be faster to at least use `asStdClass()` to get raw objects (required for proper JSON encoding again) and not have to decode them from JSON first. So here's the fastest way to do just what you want (get a _specific_ part of the JSON data):

```php
$data = $ig->hashtag->getFeed('yourTag')->asStdClass();
$json = json_encode($data->ranked_items);
```

**Comment by mgp25** [comment]
@SteveJobzniak its not a bad habit if i choose other names for loop handlers and so xD. I know its not a good practice because it can confuse people, in particular in this project.

**Comment by SteveJobzniak** [comment]
@mgp25 It can also confuse code by killing the object as soon as anyone uses the most common loop variable in the world ;P

```php
$i = new Instagram();
for ($i = 0; $i < $len; ++$i) {
    $i->uh oh
}
```

We had some tickets because of that in the past. :P

**Comment by SteveJobzniak** [comment]
@BaderAlmudarra When I wrote the following to you:

> And you certainly cannot do json_encode($lazyObject) because that would do something weird (most likely encode the objects as strings).

I started thinking... "What would happen?". So I tried it. It creates a `{}` result (empty object). So I researched and discovered that PHP actually has an interface for controling what `json_encode()` will do with the object.

I'm working on implementing an update the LazyJsonMapper, which will let you do `json_encode($ig->hashtag->getFeed('yourTag')->getRankedItems())` which will encode it as a perfect array of JSON objects... :-)

Thanks for your question. Today I learned something new about PHP's JSON interface. ;-)

**Comment by SteveJobzniak** [comment]
@BaderAlmudarra I have now implemented the interface in LazyJsonMapper. Which means that PHP now knows what to do if it encounters LazyJsonMapper objects inside of other data (such as inside a PHP array).

You can read more about it here:

https://github.com/SteveJobzniak/LazyJsonMapper/releases

https://stevejobzniak.github.io/lazyjsonmapper-docs/classes/LazyJsonMapper.LazyJsonMapper.html#method_jsonSerialize

Simply update your project via `composer update -o` and you'll get the new version.

When you have the new version, you will be able to encode non-object values (such as the `getRankedItems()` array) as follows: `json_encode($ig->hashtag->getFeed('yourTag')->getRankedItems())`.

This new solution is by far the most efficient solution, and wastes zero time. It encodes the _exact_ objects from that exact branch of your main Response object. :-)

**Comment by SteveJobzniak** [comment]
@mgp25 @valga Pinging you two so that both of you are aware that `json_encode()` can now be used on arrays containing LazyJsonMapper objects. Can be useful if we need to encode such structures for sending to Instagram. :-)

**Comment by BaderAlmudarra** [comment]
Thank you so much @SteveJobzniak

**Comment by SteveJobzniak** [comment]
@BaderAlmudarra You're welcome. I am happy to hear that you like it! :-) Have fun!

**Comment by BaderAlmudarra** [comment]
@SteveJobzniak I am not sure what's the best way to let you know about a possible change in the implementation of search usernames function. Currently, `search($query)` in `Request\People.php` implements this functionality. I noticed that the request parameters in some recent version of instagram app as follows:
`https://i.instagram.com/api/v1/users/search/?timezone_offset=10800&q=[query]&count=30`
However, the current implementation uses different parameters, `ig_sig_key_version, is_typeahead, query and rank_token`. Can you please confirm this and make required change if needed?

**Comment by SteveJobzniak** [comment]
@BaderAlmudarra Is that new data from Android? Which app version?

**Comment by BaderAlmudarra** [comment]
@SteveJobzniak Yes android, version 22.0.0.3.68

**Comment by SteveJobzniak** [comment]
@BaderAlmudarra That's good. Many people report iPhone APIs, but those are expected to be different. But since you use Android, it means IG has indeed changed params.

Please make a new ticket with that info in it. :-)
