### ISSUE TITLE
Convert Gif to Video and upload to Instagram

### ISSUE THREAD

**Issue by AndiHamolli** [mgp25/Instagram-API#1694]
I was trying to do a test posting an image to my instagram account via this remarkable library, and I found out that it had this MediaAutoResizer.php class which made almost all images applicable for Instagram. 

The only one I could not find a solution for is uploading a GIF image to instagram, bc instagram seems not to be supporting gifs. I thought perhaps this library would allow me to convert it into video and then upload it to Instagram but I couldn't find any issue related to this. Does the library perform something like that? If not, can you please show me some workaround to achieve this?

I want to apologize if my question doesn't seem appropriate. Thank you in advance.

**Comment by mgp25** [comment]
Hello,

Instagram does not support gif, therefore we don't support gif either. `MediaAutoResizer` only works with images and videos.

It is okay to have questions, but when this type of questions happens, think about Instagram app, does it let you upload a gif? (in the device), it doesn't.

You have to convert your gif media to video.

Regards

**Comment by SteveJobzniak** [comment]
@AndiHamolli In `dev-master` (see README), the media classes have been renamed and expanded: https://github.com/mgp25/Instagram-API/issues/1645#issuecomment-341936984

We have a new `InstagramVideo()` class which is meant for video files, but can even take an image and create a video from it. Just be aware: 1. That was _NOT OUR INTENTION_, it is a side-effect of ffmpeg's ability to convert images to videos. 2. The video it creates may be too short to be legal on Instagram. Valga is going to implement video looping before v4.0 is released, to ensure that short videos reach the required length.

**Comment by AndiHamolli** [comment]
@SteveJobzniak can you please show me an example on how to achieve this. Like the ones inside the examples folder? Help is appreciated

**Comment by AndiHamolli** [comment]
@SteveJobzniak I just realised i was using an older version, which doesn't have media folder. how to achieve it from there?
