### ISSUE TITLE
possible change in users search function

### ISSUE THREAD

**Issue by BaderAlmudarra** [mgp25/Instagram-API#1697]
I noticed that the request parameters of people search in some recent version of real instagram Android app 22+ is requested by the following url:
`https://i.instagram.com/api/v1/users/search/?timezone_offset=10800&q=[query]&count=30`

However, the current implementation of `search($query) `in `Request\People.php` uses different parameters, **ig_sig_key_version, is_typeahead, query and rank_token**. 
Can you please confirm this and make required change if needed?

**Comment by SteveJobzniak** [comment]
Fixed in https://github.com/mgp25/Instagram-API/commit/41e20e01413d2a37cd2804220ef652faf31e7094 and https://github.com/mgp25/Instagram-API/commit/3c754200ed2c6c39f630c29b5fea0008629212b5
