### ISSUE TITLE
friendships/autocomplete_user_list API is obsolete

### ISSUE THREAD

**Issue by BaderAlmudarra** [mgp25/Instagram-API#1698]
Hi

It seems that the people->getAutoCompleteUserList() function is not in use any more. Currently it returns:

`{"message": "Please wait a few minutes before you try again.", "status": "fail"}`

Newer android versions of instagram app do not seem to be calling this API endpoint.

Bader

**Comment by SteveJobzniak** [comment]
No, it returns that message if you query it too fast. So your message means you have queried it recently (our login() function queries it during certain flows). That API takes several minutes for its cooldown.

But you may be right that newer apps no longer call it. @mgp25 ?

**Comment by SteveJobzniak** [comment]
@BaderAlmudarra Thanks for discovering this. Mgp has fixed it <3
