### ISSUE TITLE
How can use proxy

### ISSUE THREAD

**Issue by beljk** [mgp25/Instagram-API#17]
I want to use proxy , how do this ? @mgp25

**Comment by mgp25** [comment]
@beljk i don't think i'll add this to this API.

Regards

**Comment by sergey-tyan** [comment]
@beljk add 
    curl_setopt($ch, CURLOPT_PROXY, 'YOUR_PROXY_IP');
    curl_setopt($ch, CURLOPT_PROXYUSERPWD, 'USER:PASSWORD');
to request and uploadPhoto methods
