### ISSUE TITLE
Can I send direct message to my followers?

### ISSUE THREAD

**Issue by amauryleproux** [mgp25/Instagram-API#1700]
Hello, firstable thank you for your great work.

I've got a question, is it possible to send direct message to my followers?
If yes which is the file I have to use?

Thank you so much

**Comment by robdiberlin** [comment]
Request/Direct.php, sendText() f.e. but don't use it for spam... If you spam, IG is blocking you fast and this library as well 👯 ! :)

**Comment by amauryleproux** [comment]
Ok I see thanks anyway do you know until what number IG block the process? (it's for the start of a project so right now we just have 10 followers :D )

**Comment by robdiberlin** [comment]
Don't know... Trough app I can do around 60 per Day. Maybe more, maybe less. But I go in conversations and don't send the same text for example. Also it's a IG verified (blue badge) account... So tryout! IG is banning very fast on abusing DM Function! So be careful!

**Comment by amauryleproux** [comment]
So I try to send a message to my private account but I got an error message here is my code:

$userIds = '15996620';
$recipients = 
[
    'users' => $userIds
];

And the error message is 
"Something went wrong: "users" must be an array."

So I'm using the function badly but how I have to use it please?

**Comment by Alfredao** [comment]
@amauryleproux "users" must be an array :)

**Comment by amauryleproux** [comment]
Thanks @Alfredao ^^

So why there is this code in the wiki:

$recipients = 
[
    'users' => $userIds
];

**Comment by Alfredao** [comment]
Well man, I have never used this function before. I don't know if there in the wiki is wrong. But as the exception says, your code must be something like this

```php
$recipients = [ 
    'users' => [ $userIds ]
];`

**Comment by SteveJobzniak** [comment]
Wiki is right. It just doesn't show `$userIds = [...];`. Note the variable is named userIds, not userId. And 5he wiki says "provide 'users' as an array of user ids"

**Comment by SteveJobzniak** [comment]
PS: Instagra will ban or restrict your account very fast if you send the message to all your followers. Don't do it. They will not like you. You will get flagged as a spammer.
