### ISSUE TITLE
This action was disabled due to block from instagra, action [Like]- IPV6

### ISSUE THREAD

**Issue by henriqueandradesilva** [mgp25/Instagram-API#1701]
Has anyone found any solution for ipv6? every time I send any action I get this message "This action was disabled due to block from instagram!"
I've seen a staff saying that in ipv4 it's rolling normally, I'm thinking of using a rotating proxy

Does anyone else have another solution?

Thank you!

**Comment by SteveJobzniak** [comment]
This @henriqueandradesilva motherfucker isn't even using this library. The message looked strange, so I googled it and found another library.

What I posisbly hate even more than spammers, is idiots who ask for tech support here when using another library.
