### ISSUE TITLE
GetBroadcastID ?

### ISSUE THREAD

**Issue by atyachin** [mgp25/Instagram-API#1704]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hi,
I'm looking for a way to call `live->getInfo()` for a user that has already started broadcasting (not from my code).
Is there a way to retrieve a broadcast_id of a user who is currently broadcasting without calling first the `live->create()` method?
Possible scenarios:
1. User started live broadcasting via the real mobile app, and Id like to capture the stream details via code.
2. User is currently viewing other user's live broadcast, and I'd like to capture the stream details (mainly the RTMP URL).

Thanks!

**Comment by SteveJobzniak** [comment]
@atyachin Hi!

It's in one of these (I can see it but your exercise will be to read this list to find it too ;-)). This is how to find that kind of answer easily on your own. :-) I use the `ag` tool. You can use `grep` or similar.

```
instagram-php/src/Response$ ag getBroadcast

BroadcastInfoResponse.php
10: * @method mixed getBroadcastMessage()
11: * @method Model\User getBroadcastOwner()
12: * @method mixed getBroadcastStatus()

BroadcastHeartbeatAndViewerCountResponse.php
10: * @method mixed getBroadcastStatus()

CreateLiveResponse.php
12: * @method string getBroadcastId()
13: * @method mixed getBroadcasterUpdateFrequency()

DiscoverTopLiveResponse.php
11: * @method Model\Broadcast[] getBroadcasts()

Model/Broadcast.php
10: * @method mixed getBroadcastMessage()
11: * @method BroadcastOwner getBroadcastOwner()
12: * @method mixed getBroadcastStatus()

Model/BroadcastStatusItem.php
10: * @method mixed getBroadcastStatus()

Model/PostLiveItem.php
10: * @method Broadcast[] getBroadcasts()

Model/Reel.php
10: * @method Broadcast getBroadcast()

Model/ReelShare.php
10: * @method mixed getBroadcasts()

Model/TopLive.php
10: * @method BroadcastOwner[] getBroadcastOwners()

ReelsTrayFeedResponse.php
10: * @method Model\Broadcast[] getBroadcasts()

SuggestedBroadcastsResponse.php
10: * @method Model\Broadcast[] getBroadcasts()

TopLiveStatusResponse.php
10: * @method Model\BroadcastStatusItem[] getBroadcastStatusItems()

UserReelMediaFeedResponse.php
10: * @method Model\Broadcast getBroadcast()

UserStoryFeedResponse.php
10: * @method Model\Broadcast getBroadcast()
```

**Comment by atyachin** [comment]
Thanks SteveJobzniak!
Ok, that's a nice exercise  :)
In fact, what I'm trying to do is extracting the RTMP url while using the realtimeClient example.
So, i manage to get the broadcast_id on the 'live-started' event, however I'm a bit confused on which method to call in order to get the RTMP (it's not part of the \InstagramAPI\Realtime\Event\Payload\Live object).
There's a getRtmpPlaybackUrl() method that is part of Response/Model/Broadcast.php, however, I'm still struggling to find which method return this type of response...
I managed to call $resp = $ig->live->getInfo($live->getBroadcastId()), however the RTMP is only found in the response under:
$resp->*LazyJsonMapper\LazyJsonMapper*_objectData['rtmp_playback_url']
I'm sure there's more elegant way to do this :)
Any hints?

Thanks much!
Avital

**Comment by SteveJobzniak** [comment]
No problem! :)

As for the Realtime "Live" event, it basically only contains the ID. You must do the `getInfo()` call to get more details about it...

But the value you're looking for wasn't mapped to anything, because `BroadcastInfoResponse` was out of date and didn't have many of the new fields. I've now added all of those new values and overhauled Broadcast data, and linked `BroadcastInfoResponse` with `Model\Broadcast` so that all Broadcast-fields always exist in the `getInfo()` call.

See https://github.com/mgp25/Instagram-API/commit/e66186f14b9124cc82fe309c98f5acf2eba6104d.

```php
$resp = $ig->live->getInfo($live->getBroadcastId());
$resp->getRtmpPlaybackUrl();
```

Also note: When `broadcast_status` is `active`, meaning an ongoing broadcast, you can get the rtmp url. If it's `post_live` instead, you can only get `dash_manifest` (an XML field with playback info).

That's the new, elegant way to solve this. ;-P

**Comment by atyachin** [comment]
Hi SteveJobzniak,
This is amazing! thanks much for adding the Broadcast response.

I'm suspecting that there's an issue with the RTMP play URL. A typical response looks like:
rtmp://svelivestream007.16.ash1.facebook.com:16000/live-hd/17884846882182309

However, the above host fails to resolve..
sudo nmap -p 16000 svelivestream007.16.ash1.facebook.com
Starting Nmap 7.01 ( https://nmap.org ) at 2017-11-24 11:56 UTC
Failed to resolve "svelivestream007.16.ash1.facebook.com".

The Dash URL plays correctly:
https://instagram.fsdv1-1.fna.fbcdn.net/hvideo-ash1/v/rObn6J7QbxusjPhU6G0e2/live-dash/dash-hd/17884846882182309.mpd?_nc_rl=AfBxe_zp5IfUh7U0&oh=bb356c83bb93d6e2c6f6298d7a0565a1&oe=5A1A495D


I know that the RTMP upload stream goes to rtmp://live-upload.instagram.com:80/rtmp/[stream_id]

Did you ever manage to play the RTMP play URL that is returned in the Broadcast response?

Thanks again,
Avital

**Comment by atyachin** [comment]
Ok, after digging more and recording some sessions with Fiddler (have to play with it in order to bypass the SSL pinning), I found out that the rtmp_playback_url that is returned in the Broadcast response is correct, however it **doesn't seem to be operational**.

The Instagram app uses the **Dash** streams for the live playbacks in the app and not the RTMP.
(this is based on the iOS app, I assume that the Android app behaves similarly)

**Comment by SteveJobzniak** [comment]
@atyachin Hi. Glad you found the issue! Yeah, the official app uses DASH for all replays, so it makes sense that they use DASH for livestreams too.

I can confirm that the RTMP domain they provide in the API response is non-existent.

But DASH is a simpler format to download from anyway (it's just a folder of MPEG pieces), so you should be happy about that. ;-)

**Comment by ganego** [comment]
Sorry for OT.
Found this issue via google as I also try to dl an IG live stream. Problem is, with `ffmpeg -i "URL" file.mkv` the video is very laggy and stops every second or so for a moment (basically after each chunk or so I'd guess), the audio works fine though. Also tried -rtbufsize and -re but that does nothing. Downloading the stream with VLC works perfectly fine - but you cannot automate if then.  
@atyachin if you had success downloading the dash stream, how did you do it? Thank you.
