### ISSUE TITLE
Error when upload video

### ISSUE THREAD

**Issue by mohammad305** [mgp25/Instagram-API#1705]
Hi
I use this code for upload video but give error.

code:
`$ig->timeline->uploadVideo($videoFilename, ['caption' => $captionText]);`

error:

> You must have FFprobe to analyze video details.

I search on the internet but can't find answer.
How to fixed this error?

Thanks all

**Comment by mgp25** [comment]
Hello @mohammad305,

You haven't searched in internet. You need to install FFprobe as the error messages said.

Regards
