### ISSUE TITLE
Sessions to Redis

### ISSUE THREAD

**Issue by ilusha2012** [mgp25/Instagram-API#1708]
Hello! 
How can I configure sessions storage that to save it to Redis?

**Comment by SteveJobzniak** [comment]
Hi. That is explained here:

https://github.com/mgp25/Instagram-API/blob/master/examples/customSettings.php

If you program a good Redis storage, please share it. !-)

**Comment by ilusha2012** [comment]
Thank you!

**Comment by SteveJobzniak** [comment]
@ilusha2012 No problem. Oh and if you code a Redis storage class, be sure that you do it with `dev-master` (latest) code!

`composer require mgp25/instagram-php dev-master`

We changed the StorageInterface a little bit to change how cookies are handled. Some new functions, some changed functions. So don't waste time with the old ("v3 stable") version. Get the latest master code. ;-)
