### ISSUE TITLE
Instagram detect upload as spam

### ISSUE THREAD

**Issue by caioedut** [mgp25/Instagram-API#171]
Instagram detecting all posts as spam and deleting after upload.

**Comment by mgp25** [comment]
@caioedut maybe they detected some extrange behaviour in your activity. Try to logging in from zero or device. Anyway, not API issue

**Comment by jarnoh** [comment]
I think it is an issue with this API.  I have one account that gets it's photos removed after few seconds if posted with API, but photos stay if posted with official Instagram app.

**Comment by mgp25** [comment]
@jarnoh nope. That happens if Instagram has flagged your account/IP

**Comment by dene-** [comment]
His account or server/hosting IP I guess.

**Comment by jarnoh** [comment]
Guess you are right, this accounts official app's uploads now get removed as well.  Still, the last pics still seen are from the app uploads made after I noticed that API posts get removed.  Maybe the spam detection is triggered on a session first, then later applied on the whole account?
