### ISSUE TITLE
Wiki menu links are relative (and because of that, mostly broken)

### ISSUE THREAD

**Issue by WoLpH** [mgp25/Instagram-API#1712]
For example, take a look at this page: https://github.com/mgp25/Instagram-API/wiki/Technical-information

When you click on the "Getting started" link (or any other within "Instagram API Documentation" on the right nothing happens.

**Comment by mgp25** [comment]
Hello, ill fix that this afternnon. Im going to take care of that.

Thanks for reporting this. Will be fixed around 7pm in central europe time

Regards

**Comment by WoLpH** [comment]
Awesome! Thanks for the quick response and the great work on this lib :)

**Comment by mgp25** [comment]
Hello @WoLpH,

i fixed the links. Happy to see that people are using the wiki. Let me know if everything is okay now.

Regards

**Comment by WoLpH** [comment]
Looking great. Thanks for the quick fix!
