### ISSUE TITLE
How record live  stream to .mp4 

### ISSUE THREAD

**Issue by daulet140** [mgp25/Instagram-API#1713]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Hello
How can i record any user live stream on real time 
I used rtmp_playback_url. My ffmpeg command:
```php
ffmpeg  -v verbose -i "rtmp://svelivestream007.16.ash1.facebook.com:16000/live-hd/17909711284000230 -acodec copy -vcodec copy test.mp4
```
but received error
```php
Problem accessing the DNS. (addr: svelivestream007.16.ash1.facebook.com)
rtmp://svelivestream007.16.ash1.facebook.com:16000/live-hd/17897117905115300: Unknown error occurred
```
tnx

**Comment by solomax2014** [comment]
I used mpeg-dash thing for this purpose.

**Comment by SteveJobzniak** [comment]
Facebook/Instagram does not have RTMP.

They have only DASH.

See this: https://github.com/mgp25/Instagram-API/issues/1704
