### ISSUE TITLE
Support other language

### ISSUE THREAD

**Issue by mrb4hr4m** [mgp25/Instagram-API#1714]
- [ *] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ *] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ *] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ *] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ *] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ *] Question
- [ ] Other

---

Hi . the official version of instagram , support some other language  . any idea to change language in this api ?

**Comment by alexok** [comment]
You can extend the class

```php
class Instagram extends \InstagramAPI\Instagram
{
    public function request($url)
    {
        $request = parent::request($url);
        $request->setGuzzleOptions([
            'headers' => [
                'Accept-Language' => 'ru-RU',
            ]
        ]);
        return $request;
    }
}
```

**Comment by mgp25** [comment]
Or you can do a patch over `Constants.php`, changing locale and language.

Regards

**Comment by SteveJobzniak** [comment]
Best method: Patch Constants.php. That way you'll ensure we _always_ use your preferred language everywhere.

**Comment by alexok** [comment]
Constants.php is updated via the composer. The language is set by constants. If you change to static variables, then you can normally use

**Comment by SteveJobzniak** [comment]
@alexok You can patch Constants.php after composer update via this:

https://github.com/cweagans/composer-patches

(Make a patch that changes language, and tell composer-patches to install that patch after every update).

**Comment by mrb4hr4m** [comment]
thank thank thank :)

**Comment by mrb4hr4m** [comment]
Thank you very much :)
