### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by testforlite** [mgp25/Instagram-API#1717]
Why did I receive this error? `InstagramAPI\Exception\LoginRequiredException: User not logged in`. Please `call login()` and then try again. in `/var/www/apmcrm/vendor/mgp25/instagram-php/src/Request.php:635`

**Comment by Alfredao** [comment]
You received this error because the user was not logged in. You should call login() and then try again

**Comment by mgp25** [comment]
Hello @testforlite,

Please read the error, the solution is in it.
