### ISSUE TITLE
 Input/output error

### ISSUE THREAD

**Issue by masoudx** [mgp25/Instagram-API#1719]
Hello

I have a problem in live_broadcast.php

When I run ffmpeg stream command
I got this : 

rtmp://live-upload.instagram.com:80/rtmp/17896741633122925?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfbGl2ZWRhc2giOnsibGl2ZWRhc2hfbW9kZSI6InByaW1hcnkifSwiaWdfZmJsaXZlX3NlcnZZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOltdLCJpZ19saXZlX2VuYWJsZV9wb3BfcHJpbWluZyI6W119fQ%3D%3D&a=ATjuEwoqFE2Ml_a1: Input/output error

what is the problem here?

**Comment by mgp25** [comment]
Hello,

Not API related. For unrelated questions better search in google

Regards

**Comment by masoudx** [comment]
I searched in google but no success
Can you give me a little help plz?

**Comment by mgp25** [comment]
URL: http://lmgtfy.com/?q=Input%2Foutput+error+ffmpeg

Probably you are not providing a valid input/output folder/file.

**Comment by masoudx** [comment]
I checked another rtmp address (from another website) and it works perfectly
How can I make sure my instagram rtmp address is valid?
