### ISSUE TITLE
Exception 'ReflectionException' with message 'Class string does not exist'

### ISSUE THREAD

**Issue by zhito** [mgp25/Instagram-API#1720]
Does anybody know why?
**Exception 'ReflectionException' with message 'Class string does not exist'**

in `C:\a\www\sf\vendor\netresearch\jsonmapper\src\JsonMapper.php:556`

Stack trace:

`#0 C:\a\www\sf\vendor\netresearch\jsonmapper\src\JsonMapper.php(556): ReflectionClass->__construct('string')
#1 C:\a\www\sf\vendor\netresearch\jsonmapper\src\JsonMapper.php(384): JsonMapper->createInstance('string', false, Object(stdClass))
#2 C:\a\www\sf\vendor\netresearch\jsonmapper\src\JsonMapper.php(263): JsonMapper->mapArray(Array, Array, 'string')
#3 C:\a\www\sf\vendor\netresearch\jsonmapper\src\JsonMapper.php(278): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\Model\User))
#4 C:\a\www\sf\vendor\mgp25\instagram-php\src\Client.php(433): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\UserInfoResponse))
#5 C:\a\www\sf\vendor\mgp25\instagram-php\src\Request.php(105): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\UserInfoResponse), Object(stdClass), true, NULL)
#6 C:\a\www\sf\vendor\mgp25\instagram-php\src\Instagram.php(2295): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\UserInfoResponse))
#7 C:\a\www\sf\console\controllers\DuoController.php(385): InstagramAPI\Instagram->getUserInfoByName('psyxoff')
#8 [internal function]: console\controllers\DuoController->actionFollow()
#9 C:\a\www\sf\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#10 C:\a\www\sf\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 C:\a\www\sf\vendor\yiisoft\yii2\console\Controller.php(135): yii\base\Controller->runAction('follow', Array)
#12 C:\a\www\sf\vendor\yiisoft\yii2\base\Module.php(528): yii\console\Controller->runAction('follow', Array)
#13 C:\a\www\sf\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('duo/follow', Array)
#14 C:\a\www\sf\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('duo/follow', Array)
#15 C:\a\www\sf\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 C:\a\www\sf\yii(27): yii\base\Application->run()
#17 {main}`

**Comment by mgp25** [comment]
Hello @zhito,

when you open an issue, you need to post also the code you were using, so we can reproduce the error.

And as i can you are using an outdated function `getUserInfoByName()`. Please, use latest code from `dev-master` and see the examples and wiki for more information.

In the latest code, it would be:

```
$ig->people->getInfoByName($username);
```
