### ISSUE TITLE
"big_page" - endpoints returning > 200 results with no next_max_id

### ISSUE THREAD

**Issue by milsanore** [mgp25/Instagram-API#1721]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Hi,

I noticed the other day that when requesting a page of followers, I received a response with > 7 THOUSAND followers and no "next_max_id" field. So it's as if IG is returning one big page instead of many small pages. However the response does not contain _all_ of the user's followers and since it does not have the "next_max_id" field I cannot paginate.

This behaviour appears to be bound to an account, not a machine, so signing in elsewhere with the same account will cause the same behaviour, and it does not vary day to day.

I was just wondering if anyone else has come across this behaviour?

Thanks,

EDIT: also, when this scenario occurs, in the response: `{ big_page: false }`, whereas usually it's set to `true` (paradoxically).

**Comment by mgp25** [comment]
Hello @milsanore,

This is a normal behavior, and explained many times in other closed issues. The API is okay, Instagram server is the one that controls how many items can be loaded. Same behavior if you use the account on any device.

Regards

**Comment by milsanore** [comment]
Thanks @mgp25 , apologies for not finding it, I was searching for "big_page" instead of "big_list" 

For future travellers, it's discussed here:
https://github.com/mgp25/Instagram-API/issues/1340

**Comment by SteveJobzniak** [comment]
Apology accepted. `^_^`

It was an honest typo-mistake (I even thought `big_page` was a new official param since it osunded logicsl). Thanks for fixing the ticket title and even linking to the original ticket.
