### ISSUE TITLE
 I can not list live comments

### ISSUE THREAD

**Issue by JeanSauzem** [mgp25/Instagram-API#1725]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

to carry out the transmission I use obs.

code used:
```php
  set_time_limit(0);
        date_default_timezone_set('UTC');
        require __DIR__ . '/../../../../vendor/autoload.php';

        $ig        = new \InstagramAPI\Instagram(false, false);
        $messagesLives = [];
        try {
            $ig->login('username','password'));
        } catch (\Exception $e) {
            return false;
        }
        try {
            $messagesLives = $ig->live->getComments($id);
        
        } catch (\Exception $e) {
            $messagesLives = [];
        }
```

I make a comment and it does not appear when I update the page with the a code above

**Comment by Alfredao** [comment]
Please, tell us what happens. You got an error?

Maybe you forgot to print/dump the response?

**Comment by JeanSauzem** [comment]
There was no error, but it does not display comments in live, when it has a comment

**Comment by mgp25** [comment]
@JeanSauzem get used to post debug log when opening this kind of issues.

Regards

**Comment by SteveJobzniak** [comment]
@JeanSauzem Your code is wrong. The `getComments()` function does not return an array, but you seem to treat it as an array (you initialize the `$messagesLives` variable to an empty array). Perhaps that is the issue?

Look up what getComments returns (in our source code) and look at that `src/Response/*.php` file to see what functions ithas for actually getting the comments.

Also, post a debug log.

**Comment by JeanSauzem** [comment]
my friends are working, but I had not understood the logic in the comment of a live, it does not save the comment, but I have shown the comment the most recent

**Comment by JeanSauzem** [comment]
thank you
