### ISSUE TITLE
More media than 18 at a time

### ISSUE THREAD

**Issue by ilusha2012** [mgp25/Instagram-API#1726]
Hello!

Can I do get more than 18 media for once?

**Comment by SteveJobzniak** [comment]
First of all, the number is not 18.

The official website loads 12 media at a time. The official app (and our API which emulates the app) loads 12-19 (usually 18 (17-19) on impopular/personal accounts and 12 on hugely popular accounts).

We cannot change those server limits, they are controlled by Instagram. ;-)
