### ISSUE TITLE
How can i show results of vote?

### ISSUE THREAD

**Issue by learningwithyou** [mgp25/Instagram-API#1727]
Hello dear mgp25 and vazniak,

I need result of polls or statics, 

for example;

> 23 votes for "yes", 50 votes for "no".

i found **getStoryPollVoterInfos()** or **getStoryPolls()** in `Response/Model/Item.php` but ;
how can i use that , it's not working as `$ig->story->getStoryPollVoterInfos()`? 

Thank you for answers.

**Comment by mgp25** [comment]
Hello @learningwithyou,

`getStoryPollVoterInfos()` and `getStoryPolls()` are getters from the `Item` object. So if you have an instance of that, you can access its properties using any othe getters found in `Item` class.

`getStoryPollVoterInfos()` for example will return `story_poll_voter_infos` property. You can imagine the other property of the other getter.

I think, what you are looking for is:

```php
$ig->story->getStoryItemViewers($storyPk);
```

You should give it a shoot, check the response, and tell us if the response contains what you are looking for.

But! I see a big error in what you have posted:

`$ig->story->getStoryPollVoterInfos()` as you have said these functions are from `Item` class, so why you are trying to access the from `$ig->story`? 

All requests related to stories can be found in `/Request/Story.php`. So when doing this:

```php
$ig->story
```

You can access functions inside that class. Right?

Hope you can see things clearer after reading this.

Let me know if that helped you.

Regards

**Comment by learningwithyou** [comment]
Thank you a lot brother. You're awesome.
