### ISSUE TITLE
video caption

### ISSUE THREAD

**Issue by letreset** [mgp25/Instagram-API#173]
When i set caption to the uploading video, it doesn't set the caption. Here is debug log.

> POST /api/v1/upload/photo/ HTTP/1.1
Host: i.instagram.com
User-Agent: Instagram 7.19.1 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Cookie: csrftoken=4c0daac32f67c9f2b16e4e192af9da2e; ds_user=devopreactions; ds_user_id=3238503924; igfl=devopreactions; is_starred_enabled=yes; mid=VzcM3wABAAE9o60uBmjE9LCAwNAl; s_network=; sessionid=IGSC52e948da4bf50b022d3caed8cd0b6ecdc3a5521ba2f0c7418375312522982d60%3AZjvCLcCWtyqIqoSCx3jNNNLlcEOzBQYj%3A%7B%22_token_ver%22%3A2%2C%22_auth_user_id%22%3A3238503924%2C%22_token%22%3A%223238503924%3AckHaLCOne83e5DUR84uPuhTSxnQBYbyh%3A58fe126464a73f2254c398fdfee2698ea4aca0f7263be4063762627a106d388b%22%2C%22asns%22%3A%7B%22188.166.27.57%22%3A202018%2C%22time%22%3A1463225567%7D%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22last_refreshed%22%3A1463225567.66433%2C%22_platform%22%3A1%7D
Connection: close
Accept: */*
Content-type: multipart/form-data; boundary=3ab1c1c8-487f-4b30-bdc5-3b0130ce9504
Content-Length: 6709
Cookie2: $Version=1
Accept-Language: en-US
Accept-Encoding: gzip
Expect: 100-continue

< HTTP/1.1 100 Continue
< Date: Sat, 14 May 2016 11:45:59 GMT
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Server: nginx
< Date: Sat, 14 May 2016 11:45:59 GMT
< Content-Type: application/json
< Content-Language: en
< Expires: Sat, 01 Jan 2000 00:00:00 GMT
< Vary: Cookie, Accept-Language
< Pragma: no-cache
< Cache-Control: private, no-cache, no-store, must-revalidate
* Replaced cookie csrftoken="4c0daac32f67c9f2b16e4e192af9da2e" for domain i.instagram.com, path /, expire 1494675959
< Set-Cookie: csrftoken=4c0daac32f67c9f2b16e4e192af9da2e; expires=Sat, 13-May-2017 11:45:59 GMT; Max-Age=31449600; Path=/
* Replaced cookie ds_user_id="3238503924" for domain i.instagram.com, path /, expire 1471002359
< Set-Cookie: ds_user_id=3238503924; expires=Fri, 12-Aug-2016 11:45:59 GMT; Max-Age=7776000; Path=/
< Connection: close
< Content-Length: 46
<
* Closing connection 0
RESPONSE: {"status": "ok", "upload_id": "1463226355349"}

REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=785d56c2d1dbf244861354c3dd57dac114d08c8148b608f17f23fb9cc796eae0.{"upload_id":"1463226355349","camera_model":"HM1S","source_type":3,"date_time_original":"2016:05:14 07:45:59","camera_make":"XIAOMI","edits":{"crop_original_size":[null,null],"crop_zoom":1.3333334,"crop_center":[0,-0]},"extra":{"source_width":null,"source_height":null},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"4c0daac32f67c9f2b16e4e192af9da2e","_uuid":"3ab1c1c8-487f-4b30-bdc5-3b0130ce9504","_uid":"3238503924","caption":null}
RESPONSE: {"status": "ok", "media": {"taken_at": 1463226359, "pk": 1249955760142374534, "id": "1249955760142374534_3238503924", "device_timestamp": 1463226355349, "media_type": 2, "code": "BFYvCQsPVaG", "client_cache_key": "MTI0OTk1NTc2MDE0MjM3NDUzNA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent-ams3-1.cdninstagram.com/t51.2885-15/e35/13151173_561581097337244_2121137133_n.jpg?ig_cache_key=MTI0OTk1NTc2MDE0MjM3NDUzNA%3D%3D.2", "width": 320, "height": 320}, {"url": "http://scontent-ams3-1.cdninstagram.com/t51.2885-15/s240x240/e35/13151173_561581097337244_2121137133_n.jpg?ig_cache_key=MTI0OTk1NTc2MDE0MjM3NDUzNA%3D%3D.2", "width": 240, "height": 240}, {"url": "http://scontent-ams3-1.cdninstagram.com/t51.2885-15/s150x150/e35/13151173_561581097337244_2121137133_n.jpg?ig_cache_key=MTI0OTk1NTc2MDE0MjM3NDUzNA%3D%3D.2", "width": 150, "height": 150}]}, "original_width": 320, "original_height": 320, "view_count": 0.0, "user": {"username": "devopreactions", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent-ams3-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "Dev Ops Reactions", "pk": 3238503924, "is_private": false}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjE1NmMxOTE3MTkwZTQ5MDBhYTgxMWY3MzIxYjA2ODM5MTI0OTk1NTc2MDE0MjM3NDUzNCIsInNlcnZlcl90b2tlbiI6IjE0NjMyMjYzNjU3NjZ8MTI0OTk1NTc2MDE0MjM3NDUzNHwzMjM4NTAzOTI0fDJhMWM1ODA4MjZkYzM4YTBjNGRkZWNkM2ZjZTM2NGViOTMzZTk1ZWMwMmYzOGZiZjNlNzlhNWQ0ZjRiMWVjMjUifSwic2lnbmF0dXJlIjoiIn0=", "like_count": 0, "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 4, "comments": [], "comment_count": 0, "caption": null, "caption_is_edited": false, "photo_of_you": false, "video_versions": [{"url": "http://scontent-ams3-1.cdninstagram.com/t50.2886-16/13236416_1068366349904021_960909063_n.mp4", "width": 640, "type": 101, "height": 640}, {"url": "http://scontent-ams3-1.cdninstagram.com/t50.2886-16/13218639_1626245611030657_1595531880_s.mp4", "width": 480, "type": 102, "height": 480}, {"url": "http://scontent-ams3-1.cdninstagram.com/t50.2886-16/13218639_1626245611030657_1595531880_s.mp4", "width": 480, "type": 103, "height": 480}], "has_audio": false}, "upload_id": "1463226355349"}

REQUEST: qe/expose/
DATA: ig_sig_key_version=4&signed_body=7f87040098730cfc736b06845381887d8ee9551ddf2db5307ad0f3967aa40227.{"_uuid":"3ab1c1c8-487f-4b30-bdc5-3b0130ce9504","_uid":"3238503924","id":"3238503924","_csrftoken":"4c0daac32f67c9f2b16e4e192af9da2e","experiment":"ig_android_profile_contextual_feed"}
RESPONSE: {"status": "ok"}

REQUEST: media/configure/?video=1
DATA: ig_sig_key_version=4&signed_body=b2f72d7981c91bea50b3a630b6949d6a5e15f382e0e5dc542b47178945f7c8cf.{"upload_id":1463226355349,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":13,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"4c0daac32f67c9f2b16e4e192af9da2e","_uuid":"3ab1c1c8-487f-4b30-bdc5-3b0130ce9504","_uid":"3238503924","caption":"Starting an old legacy server"}
RESPONSE: {"status": "ok", "media": {"taken_at": 1463226359, "pk": 1249955760142374534, "id": "1249955760142374534_3238503924", "device_timestamp": 1463226355349, "media_type": 2, "code": "BFYvCQsPVaG", "client_cache_key": "MTI0OTk1NTc2MDE0MjM3NDUzNA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent-ams3-1.cdninstagram.com/t51.2885-15/e35/13151173_561581097337244_2121137133_n.jpg?ig_cache_key=MTI0OTk1NTc2MDE0MjM3NDUzNA%3D%3D.2", "width": 320, "height": 320}, {"url": "http://scontent-ams3-1.cdninstagram.com/t51.2885-15/s240x240/e35/13151173_561581097337244_2121137133_n.jpg?ig_cache_key=MTI0OTk1NTc2MDE0MjM3NDUzNA%3D%3D.2", "width": 240, "height": 240}, {"url": "http://scontent-ams3-1.cdninstagram.com/t51.2885-15/s150x150/e35/13151173_561581097337244_2121137133_n.jpg?ig_cache_key=MTI0OTk1NTc2MDE0MjM3NDUzNA%3D%3D.2", "width": 150, "height": 150}]}, "original_width": 320, "original_height": 320, "view_count": 0.0, "user": {"username": "devopreactions", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent-ams3-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "Dev Ops Reactions", "pk": 3238503924, "is_private": false}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImUxNDA4YmMyMWRiMTQyNzM5Yjc4OTBlMWJhNWFhYWQ1MTI0OTk1NTc2MDE0MjM3NDUzNCIsInNlcnZlcl90b2tlbiI6IjE0NjMyMjYzNjYyMjl8MTI0OTk1NTc2MDE0MjM3NDUzNHwzMjM4NTAzOTI0fDE3YmQyMjRlZGQ1ZTEzNzRlZDFjZTFlNDg4OWQ0OWQ1YjA0NzEzMjI4ODNmMTY5NTE2NjEzZWViNDkxYjc0OTUifSwic2lnbmF0dXJlIjoiIn0=", "like_count": 0, "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 4, "comments": [], "comment_count": 0, "caption": null, "caption_is_edited": false, "photo_of_you": false, "video_versions": [{"url": "http://scontent-ams3-1.cdninstagram.com/t50.2886-16/13236416_1068366349904021_960909063_n.mp4", "width": 640, "type": 101, "height": 640}, {"url": "http://scontent-ams3-1.cdninstagram.com/t50.2886-16/13218639_1626245611030657_1595531880_s.mp4", "width": 480, "type": 102, "height": 480}, {"url": "http://scontent-ams3-1.cdninstagram.com/t50.2886-16/13218639_1626245611030657_1595531880_s.mp4", "width": 480, "type": 103, "height": 480}], "has_audio": false}, "upload_id": 1463226355349}

REQUEST: qe/expose/
DATA: ig_sig_key_version=4&signed_body=7f87040098730cfc736b06845381887d8ee9551ddf2db5307ad0f3967aa40227.{"_uuid":"3ab1c1c8-487f-4b30-bdc5-3b0130ce9504","_uid":"3238503924","id":"3238503924","_csrftoken":"4c0daac32f67c9f2b16e4e192af9da2e","experiment":"ig_android_profile_contextual_feed"}
RESPONSE: {"status": "ok"}

**Comment by rooz121359** [comment]
Can you actually upload videos using this API ?

**Comment by letreset** [comment]
I've tried first time with the example video upload file and it's new account.

**Comment by rooz121359** [comment]
And did it work? what is the video format  and size you are using? does it have to be perfect square?

**Comment by MaximMikulich** [comment]
@letreset https://github.com/mgp25/Instagram-API/issues/167

**Comment by rooz121359** [comment]
in the 'Dependencies' section says it requires ffmpeg and GD! I don't have any of these on my VPS. But I can easily publish images onto Instagram using this API. the only thing I can't do is the video upload.
So, do i need the ffmpeg and GD for video upload?!

**Comment by letreset** [comment]
Thanks @MaximMikulich it works. @rooz121359 you need to install these.

**Comment by rooz121359** [comment]
Yes, @letreset ... I installed them and it worked like a charm mate. Excellent.. maybe put those requirements somewhere in the READ ME file ? I had to search and search for 2 days until I found out that I had to install those. cheers
