### ISSUE TITLE
get count followers in getFollowers()

### ISSUE THREAD

**Issue by designh2o** [mgp25/Instagram-API#1731]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->login('yourusername', 'yourpassword');
  $userId = $ig->people->getUserIdForName('someusername');

   $followers = $ig->people->getFollowers($userId);
   $users = $followers->getUsers();
  
    var_dump($users);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:
RESPONSE: 'follower_count' => null
```

---

### Describe your issue

We use the function getFollowers, this function returns an array "users", and the value of "follower_count" is null. As with the function getFollowers immediately to get "followers_count"?

**Comment by SteveJobzniak** [comment]
Hi. You can upgrade to `dev-master` (see README) to get v4.x in development, which uses [LazyJsonMapper](https://github.com/SteveJobzniak/LazyJsonMapper/). With that you can read `$followers->printJson()` to see all the data that really came from the server.

The answer is simple: The Instagram server does not give you any 'follower_count' in `getFollowers()`.

The right way to get those counts is `getInfoById()` which is like visiting their profile and seeing their info. That endpoint gives detailed User object info about the user, and shows its follower/following count etc.
