### ISSUE TITLE
API Reliability

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1733]
Hi,

I got a question, first of all I want to make clear I'm not using this API for any bot related stuff, I just want to make it possible for users to upload an image trough our app to their Instagram account. 

Now I was thinking, how reliable is this API? What are the chances of it being shutdown by Instagram/Instagram changing some encryption stuff in their API like Snapchat did back in the days?
Could anyone give me more information on this? (I understand there's always a chance they'll shut it down ;))

Thanks!

**Comment by SteveJobzniak** [comment]
Hi!

> possible for users to upload an image **trough our app**

You've been active in this repo and can't have missed the license. You mention an application and users. Which means that you must share your app's source code, or buy a commercial license, _or_ cease usage of this library in violation of the license:

https://github.com/mgp25/Instagram-API#license

**Comment by matthijsotterloo** [comment]
Yes I know that. The app is still in development and we’re testing possibilities on how to make this upload function work, as soon as this is really the way we’re gonna do it we’ll either open source or buy a license.

**Comment by mgp25** [comment]
<img src="https://i.imgur.com/8KTtscB.jpg" width=200>

By the way, Snapchat did not change their encryption, they just added other stuff that make it more difficult to do it, i lost interest and eventually stopped. But still there are ways (easy ones!) to get it working.

**Comment by matthijsotterloo** [comment]
@mgp25 Oh that's interesting!
