### ISSUE TITLE
Composer Require

### ISSUE THREAD

**Issue by kenkit** [mgp25/Instagram-API#1736]
Composer require installs an older version that doesn't have the photo post api.
Tested on both windows and linux.
I had to clone the repo manually and install some json library for it to work.
Otherwise, nice job Nothing could get any easier than this api

**Comment by mgp25** [comment]
It is explained in the readme:

```
composer require mgp25/instagram-php dev-master
```

Regards

**Comment by kenkit** [comment]
Thanks It's I mostly skim text may have missed the dev-master

**Comment by mgp25** [comment]
No problem @kenkit, you are welcome.

Regards
