### ISSUE TITLE
[Question] Get more than 1000 users who liked a media

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#1740]
---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
### Describe your issue

The function getLikers takes one mediaID and return all likers pk of that media at maximum of 1000 registers... it doesn`t return any pagination token.

Are there any way to get more users who liked some media?

**Comment by mgp25** [comment]
Duplicate issue. Please search in the closed issue.

Regards
