### ISSUE TITLE
User subscription

### ISSUE THREAD

**Issue by QQizi** [mgp25/Instagram-API#1745]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Is it possible to make a user subscription like so : https://www.instagram.com/developer/subscriptions

**Comment by valga** [comment]
Yes, it is possible. First you need to call `People::favorite()` on user you want to subscribe: you will receive push notifications about their new posts. Then use the Push client to receive `post` pushes, see `examples/pushReceiver.php` for usage.

It is obvious that you can't receive push notifications about your own posts, but you can always create a dummy account.
