### ISSUE TITLE
accessingValue example breaks

### ISSUE THREAD

**Issue by kriskras** [mgp25/Instagram-API#1749]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### 

I have been trying to run the accessingValues example. (located at https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php). For some reason I am not able to get it working as the methods printJson(); and printPropertyDescriptions(); do not seem to work. I have even added the line "use LazyJsonMapper\LazyJsonMapper;" but this does not make a difference.

Moreover the line $firstItem_username = $firstItem->getUser()->getUsername(); also breaks as "Call to a member function getUser() on null" is returned.

Thank you for looking into this. The library seems to offer a lot of options but I just need to get it working.

**Comment by mgp25** [comment]
Hello @kriskras,

The example is working great. Make sure you have `dev-master` code and have installed the library and its dependencies using composer as explained in the readme.

Regards
