### ISSUE TITLE
How to send a "security code" to email or SMS?

### ISSUE THREAD

**Issue by WilliamBlais** [mgp25/Instagram-API#1750]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Hi!

First of all, thank you for all the amazing work you've done.

I was wondering if, just after trying to login, there's a way to send a "security code" manually.
I'm not talking about a 2FA code, but a "code to confirm your identity".

The login would look like this:
-- Login using $username, $password
-- Login Exception (challenge required)
-- Send to the user a "security code"
-- Enter the security code
-- Login successful

Thanks,
William B

**Comment by mgp25** [comment]
Hello,

- You can use this function: [getSecurityInfo()](https://github.com/mgp25/Instagram-API/blob/a640aae361cb895c64234d453b416e5044c33ae7/src/Request/Account.php#L323) 

- The response properties: [AccountSecurityInfoResponse](https://github.com/mgp25/Instagram-API/blob/4060b47a5c1bcbcc51ef00e38c8f290ccaf964f7/src/Response/AccountSecurityInfoResponse.php)

You can save that value and send/store it. You can only get the `security_code` after a successful login. [1]

You can try using [twoFactorLogin.php](https://github.com/mgp25/Instagram-API/blob/master/examples/twoFactorLogin.php) as example. But if doesn't fit, you will need to implement this feature and send a PR. 

--- 
[1] What is a security code and how its used? - https://help.instagram.com/1006568999411025

**Comment by WilliamBlais** [comment]
@mgp25 Thank you for your help! I'm going to try it and send a PR if I manage to solve it.

**Comment by valga** [comment]
@WilliamBlais Sorry, but we will not accept any PRs, that are related to resolving login challenges. This library is intended for personal use, and login challenges do not appear when you are logging in from your home network. Moreover, in most cases login challenges are related with spam.

But we have `Instragram::request()` method that allows you to create custom requests, so you can implement challenge methods in your code without patching the library.
