### ISSUE TITLE
Post Live not found

### ISSUE THREAD

**Issue by JeanSauzem** [mgp25/Instagram-API#1751]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

After ending the transmission and perform the function to post the live already closed and does not appear in storie

Exemple code using:
```php
  set_time_limit(0);
        date_default_timezone_set('UTC');
        require __DIR__ . '/../../../../vendor/autoload.php';
        \InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
        $ig                                                         = new \InstagramAPI\Instagram(true, true);

        try {
            $ig->login('username', 'password');
        } catch (\Exception $e) {
            return false;
        }
        try {
            $status = $ig->live->addToPostLive(id);
        } catch (\Exception $e) {
           $status = '';
        }
         
        return $status;
```
 
**DEBUG:**

```
POST:  https://i.instagram.com/api/v1/live/17890270120134189/add_to_post_live/
DATA: signed_body=05dd7ddb662b1266123f24009620ea790df7b54cbb352402191e5fce0d8eec80.{"_csrftoken":"qTJp9Ia0xrTbIGG9IHL0vaAxQWVK81Ox","_uid":"610277892","_uuid":"f6d5a46a-0663-4a8b-9d4a-be21018a5489"}&ig_sig_key_version=4
← 400 	 33B

RESPONSE: {"message": "", "status": "fail"}
```

**Comment by valga** [comment]
@JeanSauzem I made a couple of tests with post lives:
1. Add non-existing live broadcast:
```
HTTP/1.1 500 Internal Server Error
Oops, an error occurred
```
2. Add live broadcast that was made by other user:
```
HTTP/1.1 400 Bad Request
{"message": "Broadcast is not available", "status": "fail"}
```
3. Add live broadcast that was already added and removed from post live:
```
HTTP/1.1 400 Bad Request
{"message": "", "status": "fail"}
```

Most likely your broadcast has been already removed from post live, so you can't add it again.
