### ISSUE TITLE
Login Problem !

### ISSUE THREAD

**Issue by mehrab-wj** [mgp25/Instagram-API#1752]
Hi,
im trying to use this library to create a new project
but i have some problem in login!
i using this code : 

```
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';
$username = 'spygram_app';
$password = '*******';


$ig = new \InstagramAPI\Instagram(true, true, [
	'storage'    => 'mysql',
	'dbhost'     => 'localhost',
	'dbname'     => 'marketem_spygram',
	'dbusername' => '*******',
	'dbpassword' => '******',
]);

try {
    $ig->login($username, $password,0);
    echo 'Success Login!';
} catch (\Exception $e) {
    echo '1.Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
```
but i get "**Invalid Parameters**" error !
and the other question : 
its needed to get instagram api key ?
thanks for help :heart:

**Comment by mgp25** [comment]
Hello @mehrab-wj,

Make sure you are using latest `dev-master` code. You can see [all examples](https://github.com/mgp25/Instagram-API/tree/master/examples) and [documentation](https://github.com/mgp25/Instagram-API/wiki).

You don't need any API key, it is the private lib from Instagram's app.

Also, remember to post debug log when opening an issue.

Happy Xmas.

**Comment by mehrab-wj** [comment]
for make sure , i registered and created new project in codenywhere.
then i cloned your project and use this command for composer :
```composer require mgp25/instagram-php dev-master```
i edited the [uploadPhoto.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php) and i put my instagram account username , password.
then i used this command : ```php uploadPhoto.php```
but again i got "**Invalid Parameters**" error!
Am I doing something wrong?
