### ISSUE TITLE
Follow not working but unfollow does

### ISSUE THREAD

**Issue by AndiHamolli** [mgp25/Instagram-API#1754]
i know you'd think i used it too often and that's why it's not working, but fact is, I only follow/unfollow about 12-13 people in 30 min. I also tested the code in two insta accounts and I get the same result. following doesn't work.

I even made a file for you to test it. This is the source code:

<?php

require '....../autoload.php';

$ig = new \InstagramAPI\Instagram(false, false);

$username = "************";
$pass = "********";

try {
    $ig->login($username, $pass);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

if (isset($_GET["id"]) || isset($_GET["username"])) {
	$id = ( isset($_GET["id"]) ) ? $_GET["id"] : $ig->people->getUserIdForName($_GET["username"]);
	print_r($ig->people->follow($id));
}

?>

so you can see the response for yourself.

you can call the file via
`andih.tk/eye_of_uchiha/instabot/andiacc/follow.php?username=instagram`. I tested it with public acc like @instagram and private accounts but none of them seems to work. It doesn't even show that `outgoing request =>1` for private acc.

Unfollow works actually. I use an older version of your library, but i looked at the source code inside People.php class and this `follow()` function was the same.

Pls help me solve the issue. :/

**Comment by AndiHamolli** [comment]
sorry for not showing code properly. Here is the source code:


	require '........../autoload.php';

	$ig = new \InstagramAPI\Instagram(false, false);

	$username = "***********";
	$pass = "*********";

	try {
	    $ig->login($username, $pass);
	} catch (\Exception $e) {
	    echo 'Something went wrong: '.$e->getMessage()."\n";
	    exit(0);
	}

	if (isset($_GET["id"]) || isset($_GET["username"])) {
		$id = ( isset($_GET["id"]) ) ? $_GET["id"] : $ig->people->getUserIdForName($_GET["username"]);
		print_r($ig->people->follow($id));
	}

**Comment by nemanjan00** [comment]
Are you sure ``$id`` is ok? 

Can you print it out to test?

**Comment by AndiHamolli** [comment]
@nemanjan00

test for yourself by trying the code on your acc. I had some code that would follow discovered people for my account but it didn't follow them.

**Comment by nemanjan00** [comment]
How about you just tell me if ``$id`` is ok?

**Comment by AndiHamolli** [comment]
@nemanjan00

in `?username=instagram` case the `$id = 25025320`. So yes, it's OKAY.

**Comment by nemanjan00** [comment]
Ok, then it sounds to me 2 things can be wrong. 

Either you are blocked from following or you are using old version of library. 

Can you confirm you can manually follow that person on your mobile phone? (important to be mobile, not web)

**Comment by AndiHamolli** [comment]
@nemanjan00 
i am just using a version that is before the current one added the media folder in the src. However I didn't see changes on the source code of People.php file where the `follow()` method is located. And it worked yesterday. Today noon it wasn't working anymore.

**Comment by AndiHamolli** [comment]
UPDATE:
NOW IT WORKS. DIDN'T CHANGE ANYTHING. WTF!!
MAYBE WAS SOME INSTAGRAM ISSUE

**Comment by AndiHamolli** [comment]
UPDATE 2:
IT AWKWARDLY DOESN'T WORK AGAIN. FOR FS. DON'T KNOW WHAT IS CAUSING THIS BEHAVIOR.

**Comment by nemanjan00** [comment]
You are probbably geting temporary block

**Comment by AndiHamolli** [comment]
@nemanjan00
probably, but it happens for both of my accounts at the same time. That can't be. Could you please test it yourself, with the code above, so i can be sure this is bc of some kind of block and not bc of some weird instagram issue.

And why would it block my account? I am following up to 12 and unfollowing up to 15 users in 30 min. Is that considered spam behaviour?

**Comment by valga** [comment]
@AndiHamolli Instagram has a very sophisticated anti-spam algorithm. So if you are blocked from using certain features, Instagram thinks that you are a spammer.
