### ISSUE TITLE
use `<pre>` tag for don't execution markdown.

### ISSUE THREAD

**Issue by NabiKAZ** [mgp25/Instagram-API#1757]
About this [wiki](https://github.com/mgp25/Instagram-API/wiki/How-to-write-correctly-in-Github).
You can use `<pre>` tag for don't execution markdown.
I see can not forke from wiki. so refer [this answer](https://stackoverflow.com/a/11481887/1407491).
I create this [temp project](https://github.com/NabiKAZ/Instagram-API-wiki/
) from your wiki. and change it and you can see [here ](https://github.com/NabiKAZ/Instagram-API-wiki/commit/a56bbabef987dfd1321736972da279b6677fcc3f
)my changes, and so can marge it on your wiki if you want.

**Comment by mgp25** [comment]
Hello @NabiKAZ,

Thanks! I just updated the wiki.

If you see anohter thing, just tell me.

Happy Xmas

Regards
