### ISSUE TITLE
Problem when livestreaming (getFFmpegWrapper)

### ISSUE THREAD

**Issue by draxpc** [mgp25/Instagram-API#1763]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
**Errror**

> ( ! ) Fatal error: Call to undefined method InstagramAPI\Utils::getFFmpegWrapper() in C:\wamp64\www\new.php on line 45

---
Example Code:

```php
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/vendor/autoload.php';


/////// CONFIG ///////
$username = 'user';
$password = 'pass';
$debug = true;
$truncatedDebug = false;
//////////////////////

/////// MEDIA ////////
$videoFilename = 'http://mywebsite.co/chris.mp4';
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
    
    $ffmpeg = \InstagramAPI\Utils::getFFmpegWrapper();

    // Tell Instagram that we want to perform a livestream.
    $stream = $ig->live->create();
    $ig->live->start($stream->getBroadcastId());

    // Switch from RTMPS to RTMP upload URL, since RTMPS doesn't work well.
    $streamUploadUrl = preg_replace(
        '#^rtmps://([^/]+?):443/#ui',
        'rtmp://\1:80/',
        $stream->getUploadUrl()
    );

    // Broadcast the entire video file.
    $ffmpeg->run(sprintf(
        '-rtbufsize 256M -re -i %s -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv %s',
        escapeshellarg($videoFilename),
        escapeshellarg($streamUploadUrl)
    ));

    $ig->live->end($stream->getBroadcastId());

    $ig->live->addToPostLive($stream->getBroadcastId());
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

Error Log/var_dump:

```php

> Fatal error: Call to undefined method InstagramAPI\Utils::getFFmpegWrapper() in C:\wamp64\www\new.php on line 45

```

---
### Describe your issue

Just trying to use this PHP to start a live stream. I apologize in advance if I'm not reading something correctly / being extremely stupid!

**Comment by rudemex** [comment]
@draxpc Hello, I see that fragment of code, and the first thing I see, these calling to the function run of the ffmpeg, and after the end of the live end, try putting a sleep in a lapse of time, so the video can be transmitted, think that the transmission is never immediate, there is always a delay, that's why you have to put the sleep.

Greetings

**Comment by draxpc** [comment]
@rudemex Thanks so much for the help. I have changed it to add sleep(268) AND I added a line that says:

`    InstagramAPI\Utils::$ffmpegBin = 'C:\Program Files (x86)\ffmpeg\bin';
`

It still won't work / reproduce the video, same error. 

> 

( ! ) Fatal error: Call to undefined method InstagramAPI\Utils::getFFmpegWrapper() in C:\wamp64\www\livestreamnow.php on line 45
--

**Current Code:**

`    InstagramAPI\Utils::$ffmpegBin = 'C:\Program Files (x86)\ffmpeg\bin';
    
    // Get FFmpeg handler and ensure that the application exists on this system.
    // NOTE: Look in `\InstagramAPI\Utils` if you want a custom ffmpeg path.
    $ffmpeg = \InstagramAPI\Utils::getFFmpegWrapper();

    // Tell Instagram that we want to perform a livestream.
    $stream = $ig->live->create();
    $ig->live->start($stream->getBroadcastId());

    // Switch from RTMPS to RTMP upload URL, since RTMPS doesn't work well.
    $streamUploadUrl = preg_replace(
        '#^rtmps://([^/]+?):443/#ui',
        'rtmp://\1:80/',
        $stream->getUploadUrl()
    );

    // Broadcast the entire video file.
    $ffmpeg->run(sprintf(
        '-rtbufsize 256M -re -i %s -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv %s',
        escapeshellarg($videoFilename),
        escapeshellarg($streamUploadUrl)
    ));


    sleep(268);
    // End the broadcast stream.
    // NOTE: Instagram will ALSO end the stream if your broadcasting software
    // itself sends a RTMP signal to end the stream. FFmpeg doesn't do that
    // (without patching), but OBS sends such a packet. So be aware of that.
    $ig->live->end($stream->getBroadcastId());
`

**Comment by rudemex** [comment]
Let's go to the obvious... do you have the ffmpeg and video and codec libraries installed in windows?

**Comment by draxpc** [comment]
@rudemex Yes, I have ffmpeg installed in windows.

C:\Program Files (x86)\ffmpeg\bin

and I also installed the php version via composer, the folder is called php-ffmpeg and resides in the vendor folder.

**Comment by rudemex** [comment]
Are you configuring ffmpeg correctly? Are you calling the exe correctly?

**Comment by draxpc** [comment]
@rudemex 

By the looks of things it seems as if getFFmpegWrapper() doesn't exist in my Utils.php, which it doesn't (just checked).

Also, say if I wanted to make it more simple, and stream with OBS, how would I go about doing this? There isn't any PHP example for OBS so it's super hard for me to code it.

**Comment by mgp25** [comment]
@draxpc you are not using latest dev-master code. Use the following:

Explained in the readme
`composer require mgp25/instagram-php dev-master`

Regards

**Comment by draxpc** [comment]
@mgp25 Thanks for the answer.

Is there any way to hide all the request output made by the PHP file?

**Comment by draxpc** [comment]
Also, I've succesfully streamed to my stream key + RTMP server, but when checking if the stream is live from another account, it doesn't appear as "live".

Thanks to everyone working on this project, fantastic job, thought I had to say this :+1:

**Comment by mgp25** [comment]
@draxpc 

> Is there any way to hide all the request output made by the PHP file?

Yes, that what we call `$debug`, it is set in the constructor. For more information, you can read the [wiki](https://github.com/mgp25/Instagram-API/wiki).

> Also, I've succesfully streamed to my stream key + RTMP server, but when checking if the stream is live from another account, it doesn't appear as "live".

Make sure you are doing everything correctly, and the script is working while streaming.

Regards
