### ISSUE TITLE
disable ssl verifier

### ISSUE THREAD

**Issue by saeedvaziry** [mgp25/Instagram-API#1764]
How can i set `CURLOPT_SSL_VERIFYPEER=false` ?

**Comment by mgp25** [comment]
Hello @saeedvaziry,

If you search the word `ssl` in the search bar at the top of the page, one of the results is the functions you are looking for.

Regards

**Comment by seva0812** [comment]
Instagram 75 version pinning ssl key signed
skype: webqart_1
