### ISSUE TITLE
Network: CURL error 27: SSL: couldn't create a context!

### ISSUE THREAD

**Issue by Changjinxing** [mgp25/Instagram-API#1765]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

```
Stack trace:
#0 ~/instagram/src/Client.php(700): InstagramAPI\Client->_guzzleRequest(Object(GuzzleHttp\Psr7\Request), Array)
#1 ~/instagram/src/Client.php(769): InstagramAPI\Client->_apiRequest(Object(GuzzleHttp\Psr7\Request), Array, Array)
#2 ~/instagram/src/Request.php(686): InstagramAPI\Client->api(Object(GuzzleHttp\Psr7\Request), Array)
#3 ~/instagram/src/Request.php(707): InstagramAPI\Request->getHttpResponse()
#4 ~/instagram/src/Request.php(763): InstagramAPI\Request->getRawResponse()
#5 ~/instagram/src/Request/Internal.php(972): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\MsisdnHeaderResponse))
#6  in ~/instagram/src/Client.php on line 637

```

Example Code:

```php
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../../../../vendor/autoload.php';

/////// CONFIG ///////
$username = 'aaaa';
$password = 'bbbb';
$debug = true;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->login($username, $password);
var_dump($ig);
exit();
```
### Describe your issue

When I excute 
`php vendor/mgp25/instagram-php/example/accessingValues.php`
I encountered the question before.
can anybody help me out. BTW, is this way to run example is correct?

**Comment by mgp25** [comment]
Hello @Changjinxing,

Not API issue.

Related info: https://curl.haxx.se/libcurl/c/libcurl-errors.html

Regards
