### ISSUE TITLE
syncFromAdressBook undefined!!

### ISSUE THREAD

**Issue by javansoft** [mgp25/Instagram-API#1766]
Hi friends,
I'm getting crazy with this problem, please help me For God's sake!!!!
this is my code :
```
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/vendor/autoload.php';

/////// CONFIG ///////
$username = '******';
$password = '******';
$debug = false;
$truncatedDebug = false;
//////////////////////
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {


    $contacts = array(
        array(
            'first_name' => 'whatever',
            'phone_numbers' => array('+625698715'),
            'email_addresses' => array('')
        )
    );

    $ig->syncFromAdressBook($contacts);

} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

and this is error :

> Fatal error: Uncaught Error: Call to undefined method InstagramAPI\Instagram::syncFromAdressBook() in D:\xampp\htdocs\insta\sample.php:35 Stack trace: #0 {main} thrown in D:\xampp\htdocs\insta\sample.php on line 35

**Comment by javansoft** [comment]
please dont block my account for post issues i am beginner

**Comment by charlie759** [comment]
I can't see that method anywhere in the `Instagram.php` file.  Where is it?

**Comment by mgp25** [comment]
Hello @javansoft,

1- Don't double post
2- **Search before opening an issue**

Function is in [People.php](https://github.com/mgp25/Instagram-API/blob/a640aae361cb895c64234d453b416e5044c33ae7/src/Request/People.php). `linkAddressBook()`

Regards
