### ISSUE TITLE
Livestream ends after a while (OBS)

### ISSUE THREAD

**Issue by draxpc** [mgp25/Instagram-API#1769]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---

### Describe your issue

OBS works for at least 30 minutes before the stream disconnects and I'm not sure why.

These are my current settings: https://imgur.com/n9GDojL

(Hope this image is fine as it is not code / errors)

I feel like this is to do with a setting that I have copied wrong or something like that, but if my mind doesn't fail me I read somewhere that the stream key does change every so often or something along those lines...

Thanks for the help, and again congrats for constructing such an amazing project.

**Comment by mgp25** [comment]
Hello @draxpc,

these settings has nothing to do with the disconnections.

If you were able to stream correctly, the settings you used are correct.

We dont have enough information about this. If you can collect more that, instagram responses or something, let me know and we'll investigate it.

Regards
