### ISSUE TITLE
Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.

### ISSUE THREAD

**Issue by janicheg** [mgp25/Instagram-API#177]
I have parsed new IG_SIG_KEY for 8.0.0, but logging doesn't work, the same problem for 7.19.1

@mgp25, does instagram developers changed auth algorithm?

**Comment by mgp25** [comment]
Maybe, maybe not, i don't know since i havent checked, but if you share info, its very possible that the community will help you

Regards

**Comment by RafaelAlbani** [comment]
Hi @janicheg, do you have the IG_SIG_KEY for 8.0.0 in some place to share with us?

Regards

**Comment by janicheg** [comment]
I'll share it, but later. I have some trouble with 8.0.0 app

**Comment by pseeker** [comment]
@RafaelAlbani  Instagram 8.0.0 Android
`9b3b9e55988c954e51477da115c58ae82dcae7ac01c735b4443a3c5923cb593a`

**Comment by RafaelAlbani** [comment]
Thanks @pseeker

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/commit/db5e5858f9e20301121e6d976659eca240c1ec68

**Comment by passion1989** [comment]
Thank you guys. I am using this API for my test project.
But with old and new constants, I can't login.
I am still getting the error "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram". Does this commit work for you?

**Comment by janicheg** [comment]
@passion1989  nope, still doesn't work

**Comment by mgp25** [comment]
It works perfectly, remove all .dat files, cookies etc, and retry again, use the latest commit with any modification

Regards

**Comment by borodulin** [comment]
Check that the version of the User Agent is exactly the same with the key version. Instagram 7.19.1 Android.. must be the same with IG_SIG_KEY for 7.19.1

**Comment by passion1989** [comment]
I am using new one "9b3b9e55988c954e51477da115c58ae82dcae7ac01c735b4443a3c5923cb593a"

**Comment by passion1989** [comment]
and new User agent and experiments too

**Comment by passion1989** [comment]
Okay, it works great. Thank you.

**Comment by LevPasha** [comment]
@pseeker @janicheg hi guys! Can you share 8.0.0+ IG_SIG_KEY. I have no android to get it myself.

On 8.0.0: `message=Please update your Instagram app to continue following.`
