### ISSUE TITLE
How can I get a direct pending in Realtime?

### ISSUE THREAD

**Issue by wolrd** [mgp25/Instagram-API#1771]
How can I get a direct pending in Realtime?

**Comment by nemanjan00** [comment]
I think you need to send request to check inbox.

**Comment by valga** [comment]
You can't do that with Realtime. Use the Push client for that: https://github.com/mgp25/Instagram-API/blob/c93458f7915fc1f5f7ec26a37646a3e8d5858ad8/src/Push.php#L82-L83

**Comment by amirpdlll** [comment]
> to

push can't  send pending messages !
