### ISSUE TITLE
reshare/repost video,photo,etc without ffmpeg,ffprobe

### ISSUE THREAD

**Issue by Mehrdad1991h** [mgp25/Instagram-API#1772]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Hello dear,
I try to reshare instagram video but as you said we need for `ffmpeg`, `ffprobe` and in many (95%) of shared host we don't have them, so my question is about reshare an existing post as a new post to new account, i want to know is it possible to get all requirement information from that existing post without using `ffmpeg `and `ffprobe`, also for `VideoThumbnail` can we use from existing photo (from our server/host/url/etc) or  existing photo in instagram, with correct aspect ratio if we can do this we don't need for `ffmpeg`, `ffprobe` for video detail and thumbnail.

thanks for your time.
kind regards,

**Comment by mgp25** [comment]
No, you need that requirements.

Regards

**Comment by aitte2** [comment]
I think you can download ffmpeg/ffprobe for linux binaries and put them in any folder on your shared server and set a custom path to those binaries for Instagram library. Search for closed tickets about that.
