### ISSUE TITLE
How do I generate a random signature (IG_SIG_KEY)?

### ISSUE THREAD

**Issue by kozintsev** [mgp25/Instagram-API#1778]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Is it technically possible to generate a random signature (IG_SIG_KEY)?
The article describes the way to get this data from the phone:
https://github.com/mgp25/Instagram-API/wiki/Technical-information

Is there any other way?

**Comment by mgp25** [comment]
@kozintsev it is not possible to generate a random signature, that is something unique for each version.

We provide a service via premium subscription, and you will be given always latest data about instagram. More info #1231 

Regards

**Comment by turktakipde** [comment]
Where do i create IG_SIG_KEY ?
