### ISSUE TITLE
how to set custom cover for video

### ISSUE THREAD

**Issue by Mehrdad1991h** [mgp25/Instagram-API#1780]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Question
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Other

---
after search and read i found [this issue](https://github.com/mgp25/Instagram-API/issues/384) 

I try to find function for set custom cover in current api but i can't !
is this function available in current version ?
old method :
`$video_id = $i->uploadVideo($video, $caption, $cover);`
I try to use from that with this code 
` $ig->timeline->uploadVideo`
but it have only 2 parameters (`$videoFilename`,`$externalMetadata`)
and `externalMetadata` only support : `caption`,`usertags`,`location`,`location_sticker`,`link`,`hashtags`,`story_mentions`,`story_polls`

So what happened for `custom cover`, how to set  `custom cover` in current version ?

kind regards

**Comment by mgp25** [comment]
Hello,

There is no way to set custom cover for a video. You can still do it on your own, but wont be implemented in the API, at least for now.

Regards

**Comment by aitte2** [comment]
Why was the custom cover removed? To stop fake covers?

**Comment by mgp25** [comment]
I honestly like the feature, but imagine im thinking more of the downsides that can make Instagram to really stop the API.

For example, imagine you are browsing Instagram, looking media and funny videos. Then you see a video with a cool cover, and you click it and it is something completly different, maybe even NSFW. And i think that Instagrams and users of the platform are against of it.

What are your thoughts @aitte2 ?

**Comment by Mehrdad1991h** [comment]
> imagine you are browsing Instagram, looking media and funny videos. Then you see a video with a cool cover, and you click it and it is something completly different, maybe even NSFW. And i think that Instagrams and users of the platform are against of it.

In current API 
we don't access to change cover at last with custom duration, 
or when want to reshare a post with exactly current existing cover, again we can't and we create new, 
also currently (at last me) didn't (or very very little) see fake cover/post, why ? 
(imagine after a week/month someone/page have 1K followers and send 1,2,..,10 fake posts so what happen ? many people leave,report,block that so finally banned account or at last lose followers)
so i don't say all but majority of people don't do that) ! 

So personally i think custom cover is an good idea for work,
Yes I think that is very good and useful method and we need for that 
**but** I can't ignore your talk, how can you trust all of us ? so really i don't know, 
also you have more experience (at last in this case) with that method in old version, 
maybe after add that method again in current API we see many fake post, also NSFW.

So finally personally i agree with you (@mgp25), if you said that is not good for public API or vice versa, i accept your chose !

**Comment by aitte2** [comment]
> For example, imagine you are browsing Instagram, looking media and funny videos. Then you see a video with a cool cover, and you click it and it is something completly different, maybe even NSFW. And i think that Instagrams and users of the platform are against of it.

@mgp25 Wow yeah the cover should match the video. Spammers and marketers could use fake covers. Instagram would not be happy about that. :P
