### ISSUE TITLE
Can't download any file from instagram and get 'URL signature expired'

### ISSUE THREAD

**Issue by Mehrdad1991h** [mgp25/Instagram-API#1782]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
here is my sample code 

```
                $post_Id = InstagramID::fromCode($post_Id);
                $mediaInfo = $i->media->getInfo($post_Id);
                $mediaInfo = $mediaInfo->getItems();
                $mediaInfo = $mediaInfo[0];
                $md_type = $mediaInfo->getMediaType();
                if ($md_type == 2) {
                    $imgInfo = $mediaInfo->getImageVersions2()->getCandidates()[0];
                    
                    $img_url = $imgInfo->getUrl();
                    $videoInfo = $mediaInfo->getVideoVersions()[0];
                    $video_url = $videoInfo->getUrl();

                    $save_img_name = basename($img_url);
                    $save_img_name = get_only_name($save_img_name);

                    $save_vid_name = basename($video_url);
                    $save_vid_name = get_only_name($save_vid_name);

                    download_file($video_url,$save_vid_name);
                    download_file($img_url,$save_img_name);
                }
function download_file($url,$filename)
{
    check_path();
    global $temp_folder;
    $saveto = $temp_folder . "/" . $filename;

//method 1 
//    $curl = new Curl();   //  https://github.com/php-curl-class/php-curl-class
//    $curl->setUserAgent('');
//    //('Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1');  //test with user agent 
//    $curl->setOpt(CURLOPT_SSL_VERIFYPEER, FALSE);
//    $curl->download($url, $saveto);
//
//    $curl->close();

//method 2 
//copy($url, $saveto);

//method 3
//file_put_contents($saveto, file_get_contents($url));

//method 4
//$newfname = $saveto;
//$file = fopen ($url, 'rb');
//if ($file) {
//    $newf = fopen ($newfname, 'wb');
//    if ($newf) {
//        while(!feof($file)) {
//            fwrite($newf, fread($file, 1024 * 8), 1024 * 8);
//        }
//    }
//}
//if ($file) {
//    fclose($file);
//}
//if ($newf) {
//    fclose($newf);
//}

//method 5
$resfile = $i->request($get_imgurl)
                        ->addPost('_uuid', $i->uuid)
                        ->addPost('_uid', $i->account_id)
                        ->addPost('_csrftoken', $i->client->getToken())
                        ->getHttpResponse();

// etc....
}
```

whats wrong ?
why i can load image in browser with that link but i can't save that in server and get '`403` `forbidden ` status from instagram' and with this body '`URL signature expired`' (without load in browser or after or etc ... all checked !)

**Comment by sarajh** [comment]
Me too, want to know ....

@mgp25 why you dont add download method from v 1 till now ?🤔

**Comment by mgp25** [comment]
It's working fine. Not API related.

Regards

**Comment by Mehrdad1991h** [comment]
@mgp25, thanks for your answer, can i know your test method ? (For video or image ?)

For download we need to set cookie and other headers or no ?
I cant download, is it for this :
CURLOPT_SSL_VERIFYPEER, FALSE

Is it possible to share your download method with us ? maybe my download method is wrong...

Thank you.
