### ISSUE TITLE
Cannot end live streaming

### ISSUE THREAD

**Issue by dabe93** [mgp25/Instagram-API#1784]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Example Code:

```php
try {
  $ig->live->end($stream->getBroadcastId());
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
```

Error Log/var_dump:

```php
Error: Call to undefined method InstagramAPI\Request\Live::end()
```

---

Hello,

I'm trying to live stream on instagram following the liveBroadcast.php example.
Everything works great except when I call the end function to stop the streaming that it throws me the undefined function error.

I am missing something?

I'm using version 3.1.

Thank you very much for your help!

**Comment by mgp25** [comment]
Hello @dabe93,

You are using an outdated release of the API.

You `dev-master` instead.

Regards
