### ISSUE TITLE
Checkpoint dismiss

### ISSUE THREAD

**Issue by MrLolthe1st** [mgp25/Instagram-API#1787]
Hello, im getting login response "{\"message\": \"challenge_required\", \"challenge\": {\"url\": \"https://i.instagram.com/challenge/1434639725/nyzuOB4EZj/\", \"api_path\": \"/challenge/1434639725/nyzuOB4EZj/\", \"hide_webview_header\": true, \"lock\": true, \"logout\": false, \"native_flow\": true}, \"status\": \"fail\", \"error_type\": \"checkpoint_challenge_required\"}", then accept challenge, retry request and get redirect to instagram://checkpoint/dismiss, what i need to do next?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/search?q=checkpoint&type=Issues&utf8=%E2%9C%93
