### ISSUE TITLE
Upload to instagram

### ISSUE THREAD

**Issue by alihesari** [mgp25/Instagram-API#1788]
According to my searches, I cannot post pictures to Instagram via the API. Instagram is now banning accounts and removing the images based on this method.
Please see [this link](https://stackoverflow.com/questions/18844706/how-to-post-pictures-to-instagram-using-api).
Does uploading an image or video using this library block our account?

**Comment by aitte2** [comment]
Your link is a may 2017 warning about some other person's code (which got people banned). It is not related to this library.

We have not heard about any bans for uploading images via this library.

**Comment by mgp25** [comment]
Hello @alihesari,

You can upload any type of media using this API, and you won't be blocked.

Regards

**Comment by ashishkumar-xx** [comment]
https://stackoverflow.com/search?q=post+pictures+to+Instagram
