### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by misterkek** [mgp25/Instagram-API#1789]
I Used that code

```
/////// CONFIG ///////
$username = "blabla";
$password = "blabla";
$debug = true;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
```

And recieved error "Something went wrong: Invalid Parameters"
Username and password are correct. What is the problem?

**Comment by mgp25** [comment]
Make sure you are using dev-master code.

Regards

**Comment by misterkek** [comment]
@mgp25 this helped! Thanks.
But now I recieving "Challenge required" every time I run a script. 
When I submit on instagram's site that that was me, it doesn't help... Next time I again recieving this message.

**Comment by mgp25** [comment]
Hello @misterkek, in the closed issues you will find a lot of information about checkpoint.

Regards
