### ISSUE TITLE
No caption text in instagram

### ISSUE THREAD

**Issue by Fesper** [mgp25/Instagram-API#1790]
Hello!

I'm trying to post an image with a caption.
But it doesn't work and instagram has not caption text.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:


set_time_limit(0);
date_default_timezone_set('UTC');
$path = __DIR__.'/vendor/autoload.php';
require $path;

/////// CONFIG ///////
$username = 'login';
$password = 'pwd';
$debug = true;
$truncatedDebug = true;

/////// MEDIA ////////
$photoFilename = "photo.jpg";
$captionText = 'Caption text';

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
    $ig->timeline->uploadPhoto($photoFilename, ['caption' => $captionText]);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

```

**POST:**  https://i.instagram.com/api/v1/media/configure/
**DATA:**
`signed_body=13044a1059dc12587b5a07a61ba1342881d50d049b600f114658069d34d111aa.{"device":{"manufacturer":"samsung","model":"SM-G935F","android_version":"23","android_release":"6.0.1"},"_csrftoken":"BkLAiPuBxWgDzUXckTZcm68BSSjs5ofg","media_folder":"Camera","source_type":"4","_uid":"6830403919","_uuid":"2198dc67-c002-414a-a167-ae0e2e29ce44","edits":{"crop_original_size":[500,500],"crop_zoom":1,"crop_center":[0,0]},"extra":{"source_width":500,"source_height":500},**"caption":"Caption text"**,"upload_id":"1516740494613"}&ig_sig_key_version=4`

**RESPONSE:** {"media": {"taken_at": 1516740495, "pk": 1698864863672866095, "id": "1698864863672866095_6830403919", "device_timestamp": 1516740494613, "media_type": 1, "code": "BeTlJewnRUv", "client_cache_key": "MTY5ODg2NDg2MzY3Mjg2NjA5NQ==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 500, "height": 500, "url": "https://scontent-frx5-1.cdninstagram.com/vp/d4cf0e27dff9ce4e6a98bb1552c15dd6/5AEA3F7C/t51.2885-15/e35/26224300_205527856663241_6949384177305255936_n.jpg?ig_cache_key=MTY5ODg2NDg2MzY3Mjg2NjA5NQ%3D%3D.2"}, {"width": 240, "height": 240, "url": "https://scontent-frx5-1.cdninstagram.com/vp/215501da6d54c56a75fbd69a4b9a3cab/5B03FF26/t51.2885-15/s240x240/e35/26224300_205527856663241_6949384177305255936_n.jpg?ig_cache_key=MTY5ODg2NDg2MzY3Mjg2NjA5NQ%3D%3D.2"}]}, "original_width": 500, "original_height": 500, "user": {"pk": 6830403919, "username": "login", "full_name": "Memt", "is_private": false, "profile_pic_url": "https://instagram.ffco1-1.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "has_anonymous_profile_picture": true, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "is_unpublished": false, "allowed_commenter_type": "any"}, **"caption": null**, "caption_is_edited": false, "comment_likes_enabled": false, "comment_threading_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "preview_comments": [], "comment_count": 0, "photo_of_you": false, "can_viewer_save": true, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImZjMjJiNDBkNDA5NzQ0MGJiODg1YzBjNjUzNGMyMTI4MTY5ODg2NDg2MzY3Mjg2NjA5NSIsInNlcnZlcl90b2tlbiI6IjE1MTY3NDA0OTYyNjJ8MTY5ODg2NDg2MzY3Mjg2NjA5NXw2ODMwNDAzOTE5fDBjMDE1MDJlMGMxNmM5MGE2YTBkZmE5Y2JjNGRlNjc2NjJmNGM0OWMwN2U3NmU1NDM1NDBmMWVjMTMwM2M1ZjcifSwic2lnbmF0dXJlIjoiIn0="}, "upload_id": "1516740494613", "status": "ok"}

---

**Comment by mgp25** [comment]
Hello @Fesper,

it is working fine. Make sure you are using latest code from `dev-master`

Regards

**Comment by Fesper** [comment]
No, I install
composer require mgp25/instagram-php

May be instagram has restrictions on the format of the text or encoding?

**Comment by Fesper** [comment]
@mgp25 , I tasted this code in other instagram accound and caption text was succesfully added...

**Comment by aitte2** [comment]
@Fesper Search closed tickets. I think caption can fail to apply for these reasons:

- Bad data (text must be in only UTF8 characters)
- Too many hashtags in caption. (insta will make it blank if you put too many)
- Shadowban (if your account is bad)

**Comment by Fesper** [comment]
@aitte2 Yes,i think it was a shadowban, because after 2 day i could post successfully
