### ISSUE TITLE
setting the useragent simply 

### ISSUE THREAD

**Issue by jiomai** [mgp25/Instagram-API#1791]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

It would be great to be able to customize the useragent when connecting to instagram (if it is already possible , please point me into the right direction) in a simple way, as setting useragent simply like login and password. 
I believe that using the same useragent as the original mobile device that is used with an account, results in less issues with functionality and bans.

**Comment by mgp25** [comment]
Hello @jiomai,

we use different valid user agents and we recommend to use them.

> I believe that using the same useragent as the original mobile device that is used with an account, results in less issues with functionality and bans.

That is unrelated. Instagram only bans if you do spam.

Regards
