### ISSUE TITLE
Best practice to use this library as a plugin for CMS

### ISSUE THREAD

**Issue by VAMPIIRE** [mgp25/Instagram-API#1796]
I noticed that this library is recommended to use it as a 24/7 web service. I want to use it as the plugin for classified CMS.  Can I use this lib?

**Comment by mgp25** [comment]
- Can you use the lib?
Yes.

- Can you use it as a 24/7?
No.

**Comment by aitte2** [comment]
setup a 24/7 web service as wiki faq says and connect to that service from another script. Read the faq.
