### ISSUE TITLE
Why do some images roll over?

### ISSUE THREAD

**Issue by wolrd** [mgp25/Instagram-API#1797]
Why do some images roll over?
From: https://ibb.co/gC7zjG
To: https://ibb.co/nkqPJb
```

$imgPath = $this->saveImageForSending($base64img);
$result = $api->direct->sendPhoto(['users' => [$to->service_id]], $imgPath );
private function saveImageForSending($base64img)
    {
        $fileName = 'image_'.time().uniqid(rand()) . '.jpg';
        $fullPath = public_path().'/path/'. $fileName;
        $fileResource = fopen($fullPath, 'wb');

        if (!$fileResource) {
            \Log::warning('Can\'t create an image', ['path' => $fullPath]);
            return false;
        }
        $data = explode(',', $base64img);

        if (fwrite($fileResource, base64_decode($data[1])) === false) {
            \Log::warning('Can\'t write data into the file', ['path' => $fullPath]);
            return false;
        }

        if (!fclose($fileResource)) { // clean up the file resource
            \Log::warning('Can\'t close the file', ['path' => $fullPath]);
            return false;
        }

        if($data[0] == "data:image/jpeg;base64")
        {
        	return $fullPath;
        }
        elseif($data[0] == "data:image/png;base64")
        {
        	$image = imagecreatefrompng($fullPath);
        	imagejpeg($image, $fullPath, 90);
        	imagedestroy($image);
        	return $fullPath;
        }

        \Log::warning('Can\'t convert file to jpg.', ['path' => $fullPathPng]);
        return false;
    }
```

**Comment by mgp25** [comment]
Hello @wolrd, you havent provided enough information for this issue:

- Are you using latest code?
- You need to post debug log
- Have you compared the input/output of all your functions (not the API ones)?
- Have you used the classes we provide to prepare media? There are examples for it.

Regards

**Comment by valga** [comment]
Also, Instagram ignores EXIF metadata, so make sure that your images already have proper orientation.

**Comment by wolrd** [comment]
I'm using the latest stable version (3.1).
The image is not roll overon my server but only in Instagram.
No. Media/Photo/InstagramPhoto.php - The file is not in version 3.1

**Comment by wolrd** [comment]
@valga The image is not roll over on my server but only in Instagram.

**Comment by valga** [comment]
@wolrd Upload the original image somewhere. For example, on Dropbox.

**Comment by aitte2** [comment]
I set a better title.

I think this is because your photos have EXIF rotation data. Instagram ignores all EXIF and uses the "real" rotation of the image. You must transform the actual image pixels to get the correct orientation.

@valga Isn't that what the InstagramPhoto class does?? If so then @wolrd must update to `dev-master` code.

**Comment by wolrd** [comment]
@valga https://www.dropbox.com/s/p0j10bt5dop78xo/image_15172297265907251515a6f169e07ad2.jpg?dl=1

**Comment by wolrd** [comment]
@aitte2 dev-master - not stable version.

**Comment by valga** [comment]
@wolrd 
```
$ identify image_15172297265907251515a6f169e07ad2.jpg
image_15172297265907251515a6f169e07ad2.jpg JPEG 1080x720 1080x720+0+0 8-bit DirectClass 93.2KB 0.000u 0:00.019
```
Your image actually has landscape orientation (1080x720), but it also has `Left bottom` EXIF orientation flag, so it displays as portrait one (720x1080). You can learn more about EXIF orientation [here](https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/).

Unfortunately, Instagram ignores EXIF orientation, so we made `MediaAutoResizer` class to fix that: https://github.com/mgp25/Instagram-API/blob/9996d447574938b8a117cf84ac58479b78fc76fa/src/MediaAutoResizer.php#L599-L622

**Comment by wolrd** [comment]
@valga thank you! Is there an example of using a class?

**Comment by valga** [comment]
@wolrd We have an example for stories: https://github.com/mgp25/Instagram-API/blob/e1d9b8528543bf0ccc958e234a595cdfb2efbfe9/examples/uploadStory.php#L84-L91

**Comment by wolrd** [comment]
@valga Thank you!

**Comment by wolrd** [comment]
@valga The class does not work for me.

It works for me:


`
$exif = @exif_read_data($fullPath);
        	if (!empty($exif['Orientation'])) {
	        	$image = imagecreatefromjpeg($fullPath);
		        switch ($exif['Orientation']) {
		            case 3:
		                $image = imagerotate($image, 180, 0);
		                break;

		            case 6:
		                $image = imagerotate($image, -90, 0);
		                break;

		            case 8:
		                $image = imagerotate($image, 90, 0);
		                break;
		        }
		        imagejpeg($image, $fullPath, 90);
		        return $fullPath;
		    }
`
https://stackoverflow.com/questions/7489742/php-read-exif-data-and-adjust-orientation
