### ISSUE TITLE
Question: RPL License

### ISSUE THREAD

**Issue by mercymainhere** [mgp25/Instagram-API#1800]
Hi. I have a problem with understanding this project license. I read some information on wiki, few other websites and I'm still not sure if I will break license with my project or not.

I'm currently running few accounts on Raspberry Pi but it's annoying when I need to change something in code or check status etc. so I planned to create web interface for this. I **will not change** anything in library code just create an web app (probably using Symfony) to control it.

In this case, do I have to share the code of this application or not?

**Comment by mgp25** [comment]
Hello @mercymainhere,

as long as its for personal usage, you are free to use it and you won't break any license. You don't need to share the code either.

Regards
