### ISSUE TITLE
call Graphql API like in web-version

### ISSUE THREAD

**Issue by bogusbd** [mgp25/Instagram-API#1801]
Hello everyone

Help me please, is it possible using this library to make a GET request for this API?

https://www.instagram.com/accounts/activity/?__a=1
this is from the web version and actually provides access to the last activity.

http://dl4.joxi.net/drive/2018/02/01/0026/1778/1763058/58/e27bf0a821.jpg 

If not, is it possible to obtain the same data in another way using this library?

Thank you for any help.

**Comment by mgp25** [comment]
Hello @bogusbd,

Yes, it is possible to obtain that data with the API. Almost all the data that is shown in the Instagram App, can be obtained using this API.

Regards

**Comment by bogusbd** [comment]
Hello @mgp25 , 
Can you please direct me to the right way or show a small example?
Because the API that I showed it used in the web version.  The mobile application doesn't have this functionality.  And I did not find any similar calls inside library code. 

It would really help me.
Thanks.

**Comment by aitte2** [comment]
https://github.com/mgp25/Instagram-API/blob/6939ba1aadcbddf7277b5a28a6d09715d5632c07/src/Request/People.php#L126

https://github.com/mgp25/Instagram-API/blob/6939ba1aadcbddf7277b5a28a6d09715d5632c07/src/Request/People.php#L144

**Comment by mehrdadmms** [comment]
hello 
correct me if i'm wrong but by this function i can get activity of the account i have logged in with.
is there any way I can get another's account activity (API, crawling, etc)

i have authorization from the target but i don't have it's username and password

for example i need data from this link with out having to log in with the target account 
https://www.instagram.com/accounts/activity/
