### ISSUE TITLE
examples/rankTokenUsage.php doesn't look to work

### ISSUE THREAD

**Issue by ShaunR** [mgp25/Instagram-API#1802]
I'm simply trying to get the feed for a hashtag which is what that example looks to do as well. The example returns nothing. When debug is enabled it does look like I can successfully login but the response from IG is always 0 results!  Did they change their API maybe?

```
GET:  https://i.instagram.com/api/v1/feed/tag/nature/?max_id=91efd894-f577-4f2a-a261-xxxxxxxxxxxx
â 0B
â 200    72B
RESPONSE: {"items": [], "num_results": 0, "more_available": false, "status": "ok"}
```

**Comment by CarlosTTRR** [comment]
Did you generate a random token like the example?

**Comment by ShaunR** [comment]
Yes, the same way the example did... The example itself does not work.

**Comment by aitte2** [comment]
https://github.com/mgp2https://github.com/mgp25/Instagram-API/blob/master/examples/README.md5/Instagram-API/tree/master/examples

--->

**Comment by ShaunR** [comment]
I'm not sure what your trying to say here?  I've installed this library using composer. Are you saying I need the development branch for this to work?  My own code as well as the example do not work.

**Comment by aitte2** [comment]
Hi. Yes, read the readme from the example folder. The "warning" section explains what's wrong here.

**Comment by ShaunR** [comment]
Thanks for your help.  I got it working using dev-master

**Comment by aitte2** [comment]
Fantastic :)
