### ISSUE TITLE
FFMPEG Error I/O error

### ISSUE THREAD

**Issue by msrahmanian** [mgp25/Instagram-API#1804]
Hello
I am using liveBroadcast.php but face this error with fffmpeg :

Something went wrong: FFmpeg Errors: ["rtmp://live-upload.instagram.com:80/rtmp/17898781387187753?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfbGl2ZWRhc2giOnsibGl2ZWRhc2hfbW9kZSI6InByaW1hcnkifSwiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6IjEifSwiaWdfbGl2ZV9lbmFibGVfcG9wX3ByaW1pbmciOnsiZW5hYmxlZCI6IjEifSwiaWdfbGl2ZV9pbmdlc3Rpb25fdXBkYXRlc190aHJpZnRfZW5hYmxlIjp7ImVuYWJsZWQiOiIxIn19fQ 3D 3D&a=ATgDryomyYFhVgsx: I/O error"], Command: "-rtbufsize 256M -re -i "a.mp4" -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv "rtmp://live-upload.instagram.com:80/rtmp/17898781387187753?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfbGl2ZWRhc2giOnsibGl2ZWRhc2hfbW9kZSI6InByaW1hcnkifSwiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6IjEifSwiaWdfbGl2ZV9lbmFibGVfcG9wX3ByaW1pbmciOnsiZW5hYmxlZCI6IjEifSwiaWdfbGl2ZV9pbmdlc3Rpb25fdXBkYXRlc190aHJpZnRfZW5hYmxlIjp7ImVuYWJsZWQiOiIxIn19fQ 3D 3D&a=ATgDryomyYFhVgsx"".

**Comment by aitte2** [comment]
# http://lmgtfy.com/?q=ffmpeg%20io%20error
