### ISSUE TITLE
Empty body in direct->getPresence()

### ISSUE THREAD

**Issue by mrb4hr4m** [mgp25/Instagram-API#1805]
### Purpose of your issue?
-  Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hi. when i want to getting presence in direct , i Empty response with error 

Log 

> GET:  https://i.instagram.com/api/v1/direct_v2/get_presence/
→ 0B
← 404 	 0B
RESPONSE: 

Error : Something went wrong: Requested resource does not exist.

Any idea to solve that ?

Update : also in 
`account->getPresenceStatus()` ,  `account->enablePresence();`  and `account->disablePresence()`

**Comment by mgp25** [comment]
Same as #1806 

Regards

**Comment by mrb4hr4m** [comment]
Thank you @mgp25  👍
