### ISSUE TITLE
Following hashtags not worked

### ISSUE THREAD

**Issue by mrb4hr4m** [mgp25/Instagram-API#1806]
### Purpose of your issue?
-   Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hi . `$ig->hashtag->follow('alone');` not worked with 404 error .

`POST:  https://i.instagram.com/api/v1/tags/follow/alone/`

**Comment by mgp25** [comment]
Hello @mrb4hr4m,

Code works perfectly, but it requires new version and signature keys, we won't update that data until all features are added to avoid possible side effects.

Regards

**Comment by mrb4hr4m** [comment]
Thank you .  @mgp25  . 

please add `address_book/acquire_owner_contacts/`  to getting all contact too . 

👍

**Comment by AmirHosseinKarimi** [comment]
Hi, there is not anyway to got this feature before update? any hack or hook or anything to fix this problem.

**Comment by aitte2** [comment]
@AmirHosseinKarimi Have you tried to follow a hashtag via the new release (version 4)? https://github.com/mgp25/Instagram-API/releases
