### ISSUE TITLE
Is there any EXE compilation release to use Instagram API as a CLI?

### ISSUE THREAD

**Issue by elpresti** [mgp25/Instagram-API#1809]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Hello! great job and congratulations for this helpful API!
My question: Is there any release with an EXE compilation of this Instagram API app? I need to use it as a CLI in a batch script in Windows 10, and I can't install there the PHP CLI and composer.

It could be very helpful to call it using something similar to:
_instagram-api.exe --username "myinstagramuser" --password "myinstagrampass" --video_to_push "C:/myvideo.mp4" --title "Title of my post" --description "Description of my post"_

Thanks in advance!

Regards!

**Comment by mgp25** [comment]
Hello @elpresti,

Sorry there is no 'exe'. You can still install php and run it on CLI, it will work with the specs you told.

Regards
