### ISSUE TITLE
Media shortcode

### ISSUE THREAD

**Issue by danilz** [mgp25/Instagram-API#181]
Hello!
Is there a method to get the media on the shortcode?
Example: https://www.instagram.com/developer/endpoints/media/#get_media_by_shortcode
Thank you.

**Comment by mgp25** [comment]
I guess, maybe in any response or any calculation in there.

I dont know

Regards

**Comment by RageBrahimi** [comment]
To be honest, you could just add `?__a=1` to the end of the URL

```
https://www.instagram.com/p/{shortcode}/?__a=1
```
