### ISSUE TITLE
Question: get posts of followed users

### ISSUE THREAD

**Issue by zezeljquantox** [mgp25/Instagram-API#1810]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question
- [ ] Other

Is it possible to get posts of followed users, something like homepage of logged in users? So far, i found methods for get feed of specific user, recent activities of followed users (getFollowingRecentActivity) , and getting recent stories from homepage. Also it will be great if i can get adverts and suggested posts.
Is it possible with this api or i need to create a web scraper?

**Comment by aitte2** [comment]
This is how you get the "homepage" (home timeline) with posts and advertisements from followed users:

https://github.com/mgp25/Instagram-API/blob/6939ba1aadcbddf7277b5a28a6d09715d5632c07/src/Request/Timeline.php#L180-L206

**Comment by zezeljquantox** [comment]
Thank you very much, i don't know how i missed that method.

**Comment by aitte2** [comment]
No problem :)
