### ISSUE TITLE
iOS Capturing the endpoints

### ISSUE THREAD

**Issue by GoldenEagle66** [mgp25/Instagram-API#1812]
I found the instruction in the wiki :

> You need to set up a Man-in-the-Middle (MITM) proxy, and tell your device to trust its certificate so that all HTTPS traffic flows through it.
> 
> I know for a fact Fiddle works instantly via iOS, but Instagram may use certificate pinning on Android in which case you need to hack the APK. Outside the scope of this project. Google it. Lots of guides exist.
> 
> For Android: http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForAndroid
> 
> For iOS: http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForiOS
> 
> And this project itself has some debugging options: Two debug flags in the constructor, and one special one for library developers, set via a public $i->apiDeveloperDebug = true; property.
> 
> With a proxy and those debugging options enabled, you can easily debug API traffic and contribute to this project!
> 
> Good luck.

Is it relevant now? Does it work?

**Comment by mgp25** [comment]
Remains the same, just disable certificate pinning.

Regards

**Comment by GoldenEagle66** [comment]
@mgp25 but how can I turn it off, could I say?

**Comment by GoldenEagle66** [comment]
![image](https://user-images.githubusercontent.com/17871694/36115875-72574a48-1045-11e8-840b-fafe1fd5a8b4.png)
https does not show
