### ISSUE TITLE
Phone and Email confirmation

### ISSUE THREAD

**Issue by mihey8800** [mgp25/Instagram-API#1813]
Hello. How to request sms code and email code with your api? When i start to use new account instagram requests confirmationg "It's me" and sms or email. If i confirm it with phone, it requests code again. I want to request the code with api and confirm with api too.

**Comment by mgp25** [comment]
Hello @mihey8800,

Please search before opening an issue. 

Issue: #1811

Regards

**Comment by zzet** [comment]
@mgp25 Sorry, I think he asked about the challenge confirmation

**Comment by kalaomer** [comment]
@mgp25 is there any function for login with sms code or email code?

**Comment by zzet** [comment]
@kalaomer as I understood (use search across issues) these function were removed and never will be added to this repository
