### ISSUE TITLE
Invalid megaphone type id. 

### ISSUE THREAD

**Issue by dark0n7** [mgp25/Instagram-API#1814]
After Feb 9 I got this error when I try to login.

{"message": "Invalid megaphone type id", "status": "fail"} Something went wrong: Invalid megaphone type id. 
This doesn't happen every time, but very often.

**Comment by mgp25** [comment]
@dark0n7 are you using latest release or dev-master code?

**Comment by Quequito** [comment]
Hi! 
Same here! 
I had an older version, so is just update to de latest release but im still getting this message...

Thanks!

**Comment by dark0n7** [comment]
@mgp25 Now I've upgraded for latest release and everything is working for now.

**Comment by dark0n7** [comment]
@Quequito Did you use composer to upgrade?

**Comment by Quequito** [comment]
@dark0n7 Yes... But i've upgrade it again, and after fixin my login code it works great! 

@mgp25 On more question, In this new version i have to download the photo from my "photo server" and then i can post it on instagram...
In previous version i used "http://..." as my photo...

Is there a new param to upload it directly from an url?

Thanks!

**Comment by mgp25** [comment]
@Quequito You need to download and then upload it.

Regards

**Comment by GMeb** [comment]
I have the same issue when I try to serialize a \InstagramAPI\Instagram object.
error: 
Something went wrong: InstagramAPI\Response\MegaphoneLogResponse: Invalid megaphone type id.

`class instaInstanceCommand extends Command
{
   

    protected function configure()
    {
        $this
            ->setName('insta:instance')
            ->setDescription('get instagram instance')
            ->addArgument('username', InputArgument::REQUIRED, 'Instagram Username')
            ->addArgument('password', InputArgument::REQUIRED, 'Instagram Password')
            ->addOption('only', null, InputOption::VALUE_REQUIRED);
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io= new SymfonyStyle($input, $output);
        $only = $input->getOption('only');
        return $this->getInstagramInstance($input->getArgument('username'), $input->getArgument('password'));

  
       
    }

    private function getInstagramInstance($username, $password)
    {
        /////// CONFIG ///////
        $debug          = false;
        $truncatedDebug = false;
        //////////////////////
        
        $encoders = [ new JsonEncoder()]; 
        $normalizer = new ObjectNormalizer();
        $normalizer->setCircularReferenceHandler(function ($object, string $format = null, array $context = []) {
            return $object;
        });
        $serializer = new Serializer([$normalizer], $encoders,[
            'enable_max_depth' => false
       ]);  
      

      
        $ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
        try {
            $ig->login($username, $password);
            $jsonContent = $serializer->serialize($ig, 'json');
            echo $jsonContent;
           
        } catch (\Exception $e) {
            throw new \Exception('Something went wrong: ' . $e->getMessage());
        }
    }

}`
