### ISSUE TITLE
Instagram API Platform Going To Depreciate 

### ISSUE THREAD

**Issue by ajaydesai** [mgp25/Instagram-API#1816]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

I am planing to developer the app using this instagram private api, I came to know that
Instagram going to remove their support for official apis, https://www.instagram.com/developer/
So Just want to know will that affect to this private api?

**Comment by mgp25** [comment]
Hello @ajaydesai,

That wont affect this API since its based on the phone app.

Remember that if you are using this API for commercial usagee, you need to see this: #1231 

Regards
