### ISSUE TITLE
Instagram Graph

### ISSUE THREAD

**Issue by myDevio** [mgp25/Instagram-API#1823]
Hi
As far as i know Instagram API will be Deprecated at 2018 and instagram Graph API will be lunch.
What will you do after this change (30 January 2018)?
Will this library continue to work after this date?
What is the situation? Continue with this library?
Thanks

**Comment by ibrunotome** [comment]
People just ignore the closed issues and ask again and again...

https://github.com/mgp25/Instagram-API/issues/1816
