### ISSUE TITLE
Usertag dont work

### ISSUE THREAD

**Issue by Daedra223** [mgp25/Instagram-API#1824]
I am getting the whole time the following error when trying to add usertags to an published picture:

> Something went wrong: Invalid user entry in usertags array. 

```
$userId1 = $ig->people->getUserIdForName($seiteToTag1);
$metadata2 =
    [
        'caption' => $bildBeschreibung,
        'usertags' =>
            [
                'removed' => [],
                'in'      =>
                    [
                        'position' =>
                            [
                                0.2, // x position
                                0.2  // y position
                            ],
                        'user_id'  =>
                            [
                                $userId1 
                            ]
                    ]
            ]
    ];

$ig->media->edit($item->getId(),"neue Bildbeschreibung" ,$metadata2);
```

I tried to casting the user_id and passing it with quotes but nothing worked :/ the media_ID is correct and the user_ID aswell ...

Is this maybe a bug?

Kind regards!

**Comment by Daedra223** [comment]
`Fatal error: Uncaught InvalidArgumentException: Invalid user entry in usertags array. in C:\xampp\htdocs\vendor\mgp25\instagram-php\src\Utils.php:694 Stack trace: #0 C:\xampp\htdocs\vendor\mgp25\instagram-php\src\Utils.php(673): InstagramAPI\Utils::throwIfInvalidUsertags(Array) #1 C:\xampp\htdocs\vendor\mgp25\instagram-php\src\Request\Media.php(100): InstagramAPI\Utils::throwIfInvalidUsertags(Array) #2 C:\xampp\htdocs\uploadPhoto.php(162): InstagramAPI\Request\Media->edit('172170281991989...', 'test', Array) #3 {main} thrown in C:\xampp\htdocs\vendor\mgp25\instagram-php\src\Utils.php on line 694`

**Comment by valga** [comment]
@Daedra223 Why do you have `user_id` as array? Check out the example: https://github.com/mgp25/Instagram-API/blob/715e69897ba05ac03b64399848c4b6dfdafbdc7d/examples/uploadAlbum.php#L33-L35

**Comment by Daedra223** [comment]
@valga Thank you for replying, I did read the example its as an array written in the WIKI:

[https://github.com/mgp25/Instagram-API/wiki#edit-media](url)
`$metadata = 
    [
        'usertags' => 
            [
                'removed' => [],
                'in'      => 
                    [
                        'position' => 
                            [
                                0.47097720202318, // x position
                                0.46537839732884  // y position
                            ],
                            'user_id'  => 
                                [
                                    $userId
                                ]
                    ]
            ]
    ];

$ig->media->edit($mediaId, $captionText, $metadata);`

And now I changed it to:

`$metadata = 
    [
        'usertags' => 
            [
                'removed' => [],
                'in'      => 
                    [
                        'position' => 
                            [
                                0.47097720202318, // x position
                                0.46537839732884  // y position
                            ],
                            'user_id'  => $userId,
                                
                    ]
            ]
    ];

$ig->media->edit($mediaId, $captionText, $metadata);`

And it still gives the same error message.

**Comment by alvinwiguna** [comment]
i am also getting the same errror
i am quite sure my pk is right, yet i keep getting the error
any idea why?

**Comment by iain-mildner** [comment]
I seem to have the same problem #1900 

@mgp25 does this functionality work in v4.0 ?
