### ISSUE TITLE
Fix windows escapeshellarg

### ISSUE THREAD

**Issue by BaderMudarra** [mgp25/Instagram-API#1825]
Hi guys

I was testing uploading video and it failed at `Request/Internal.php line # 2047`:
```
$ffMpegWrapper->run(sprintf(
                '-i %s -c:v copy -an -dn -sn -f segment -segment_time %d -segment_format mp4 %s',
                escapeshellarg($videoDetails->getFilename()),
                (int) $this->ig->getExperimentParam(
                    'ig_android_video_segmented_upload_universe',
                    'segment_duration_sec',
                    5
                ),
                escapeshellarg(sprintf(
                    '%s%s%s_0video.%%03d.mp4',
                    $outputDirectory,
                    DIRECTORY_SEPARATOR,
                    $prefix
                ))
            ));
```

I was trying to debug and find the cause of this issue and it was issuing the command with "  03d" instead of "%03d".

I tried to remove `escapeshellarg` from this part and it worked:

```
escapeshellarg(sprintf(
                    '%s%s%s_0video.%%03d.mp4',
                    $outputDirectory,
                    DIRECTORY_SEPARATOR,
                    $prefix
                ))
```

Can you please investigate and fix this issue.

**Comment by valga** [comment]
@BaderMudarra I decided to disable the segmented uploader on Windows, because `escapeshellarg()` does some really strange replacements there. It should fix your problem.

**Comment by aitte2** [comment]
@valga Is this right?

`     '%s%s%s_0video.%%03d.mp4',`

Sprintf parse `%%` as literal `%`, which is exported into shell as a percent... Is that intended? :)

**Comment by valga** [comment]
@aitte2 It is required by ffmpeg, see its [docs](https://www.ffmpeg.org/ffmpeg-formats.html#Examples-9).

`escapeshellarg()` on Windows does not escape, it just replaces "bad" chars with spaces. I would say it has destructive behavior. We certainly can do some workaround to fix that, but as far as we have another uploader to fall back, it is better to skip dirty things. 

Moreover, most people use Windows just for development, so this change will affect relatively small amount of video uploads.

**Comment by BaderMudarra** [comment]
@valga my production server is a windows VPS. will this update have any impact on uploading videos?

**Comment by valga** [comment]
@BaderMudarra We have 3 different video uploaders (just like the official app). I disabled just one of them on Windows. Other 2 will work just fine, because they doesn't require processing by ffmpeg.

**Comment by aitte2** [comment]
@valga oh I understand now :)

**Comment by Artclock** [comment]
Hi finaly i run insta live through OBS and ffmpeg , but i the instagram api wont work from my browser. 
i think its because of RTMP usrl . 
after `sprintf()` run  % char near the end of url  , replaced by space 

 `csx%3D&a=ATgn0jtYiTxCxfcp` 
 `csx  3D&a=ATgn0jtYiTxCxfcp`

OBS work but after live it cant save "post live"

**Comment by aitte2** [comment]
@Artclock sprintf does not replace `%` with space.

`echo sprintf('csx%3D&a=ATgn0jtYiTxCxfcp%s', 'hello')` result: PHP warning too few arguments.

`echo sprintf('%s', 'csx%3D&a=ATgn0jtYiTxCxfcp')` result: `csx%3D&a=ATgn0jtYiTxCxfcp`

Please be clear what you are talking about and what sprintf where and etc.

**Comment by valga** [comment]
@aitte2 I think it is `escapeshellarg()` on Windows again:
https://github.com/mgp25/Instagram-API/blob/b284efec194437d2504f8cb3b534ae797ce67ef6/examples/liveBroadcast.php#L57-L61

**Comment by Artclock** [comment]
You mean this code work for  linux user ?

**Comment by aitte2** [comment]
@valga Omg. Yes this is a escapeshellarg problem on Windows again :(

Maybe we can write our own utils::escapearg()

On windows it could try: surround all text with " and replace all " with \", and replace all % with ^% (see https://superuser.com/questions/683157/windows-command-line-imagemagick-percent-escapes)

On other os call phps own function.

I don't have windows to test if that works. I also suspect if that really worked php would have fixed their escapeshellarg years ago...

**Comment by valga** [comment]
@aitte2 It's a [known issue](https://bugs.php.net/bug.php?id=49446) since 2009. I guess nobody cares about that.

I found a [package](https://github.com/johnstevenson/winbox-args) that provides an alternative to `escapeshellarg()` on Windows, but I can't say whether it's safe to use it.

**Comment by aitte2** [comment]
@valga Nice! Looks like this package does exactly the thing I suggested. See the code https://github.com/johnstevenson/winbox-args/blob/master/src/Args.php

Can't test it on Ubuntu though. We need some windows user.
