### ISSUE TITLE
Stickers in Stories for Usertag

### ISSUE THREAD

**Issue by Daedra223** [mgp25/Instagram-API#1826]
Hello, 

is it possible with this API to generate usertag stickers in stories?  I saw that location stickers and hashtags and a link are possible to be integrated in a story. But is a usertag sticker also possible to use in stories? eg. "@instagram" and if you click on it, it leads you to the instagram page.

Kind regards!

**Comment by mgp25** [comment]
It is explained. Please search before opening an issue.

Regards

**Comment by Daedra223** [comment]
@mgp25 thank you for replying I read all examples and the whole wiki, but usertag stickers are not mentioned, would you please quote the lines?

Thank you and kind regards!

**Comment by mgp25** [comment]
In the wiki:

https://github.com/mgp25/Instagram-API/wiki#uploading-an-album

You can use ctrl+f (windows/linux) or cmd +f (mac).

Regards

**Comment by Daedra223** [comment]
@mgp25 thank you for replying!

I would recommand to add the following entry to the wiki:

```
'story_mentions' =>
[
	    'user_id'	       => '123456789',
  	    'x'                => 0.5, // Range: 0.0 - 1.0. Note that x = 0.5 and y = 0.5 is center of screen.
            'y'                => 0.5, // Also note that X/Y is setting the position of the CENTER of the clickable area.
            'width'            => 0.5661107, // Clickable area size, as percentage of image size: 0.0 - 1.0
            'height'           => 0.10647108, // ...
            'rotation'         => 0.0,
            'is_sticker'       => true, // Don't change this value.
],
```

**Comment by Daedra223** [comment]
I registered with a new skype name: waldi1193 or waldi1193@web.de what is your skype name?

Thanks and kind regards,
Waldemar
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 26.02.18, 11:28, mgp25 <notifications@github.com> schrieb:
In the wiki:
https://github.com/mgp25/Instagram-API/wiki#uploading-an-album
You can use ctrl+f (windows/linux) or cmd +f (mac).
Regards

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mgp25/Instagram-API","title":"mgp25/Instagram-API","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mgp25/Instagram-API"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mgp25 in #1826: In the wiki:\r\n\r\nhttps://github.com/mgp25/Instagram-API/wiki#uploading-an-album\r\n\r\nYou can use ctrl+f (windows/linux) or cmd +f (mac).\r\n\r\nRegards"}],"action":{"name":"View Issue","url":"https://github.com/mgp25/Instagram-API/issues/1826#issuecomment-368456250"}}}

**Comment by Daedra223** [comment]
I found the commit you made to make story mentions possible:
https://github.com/mgp25/Instagram-API/commit/5c1b43c52e97763fb323b995a18a73598962362f
