### ISSUE TITLE
how to get my photos?

### ISSUE THREAD

**Issue by popoff17** [mgp25/Instagram-API#1828]
I haven't found any way to get my photos in the library.
Could you please explain it to me?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/wiki#all-media-functions

Everything is documented in the source code as well!

**Comment by v03adk** [comment]
get your own feed
`$response = $ig->timeline->getUserFeed($ig->account_id, $maxId);`

see examples section https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php

**Comment by mgp25** [comment]
Hello @v03adk, next time let the user search for himself, otherwise he will keep opening invalid issues, and thats not the point.

Anyway the user will be thankful.

Regards

**Comment by v03adk** [comment]
@mgp25 yeah, sure! Just was doing the same thing, that's why shared it :)

**Comment by aitte2** [comment]
@v03adk there is an easier way: `$ig->timeline->getSelfUserFeed($maxId)`. :)
