### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: Unknown function getExternalId.

### ISSUE THREAD

**Issue by tolgatasci** [mgp25/Instagram-API#1829]
PHP Fatal error:  Uncaught Exception: Unknown function getExternalId.

php -v
```
PHP 7.1.11-0ubuntu0.17.10.1 (cli) (built: Nov  1 2017 16:30:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11-0ubuntu0.17.10.1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by aitte2** [comment]
You are trying to use new examples with older library version. Update to latest code `composer require mgp25/instagram-php dev-master`. Is a good idea anyway because the new code is better.
