### ISSUE TITLE
Getting owner's country?

### ISSUE THREAD

**Issue by atyachin** [mgp25/Instagram-API#1830]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

---

### Question:

Is there a way to retrieve the logged-in user's country?
I've noticed several address-related properties in the User model (city, street address, phone country code etc.), but they return NULL when trying to call $ig->account->getCurrentUser()->getUser();

(I'm assuming that each Instagram account is associated with specific country, regardless of the user's **current** location)

Thanks.

**Comment by aitte2** [comment]
There are only 2 func for getting user info:

`$ig->account->getCurrentUser()`
`$ig->people->getSelfInfo()` (same as `getInfoById()` with your own ID)

Search old tickets for getcurrentuser, to see if you can find more info

anyway I am sure of this: country, phone, etc, are only for BUSINES accounts :)
