### ISSUE TITLE
Any risk of the account being blocked using this API?

### ISSUE THREAD

**Issue by loVeno** [mgp25/Instagram-API#1832]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Is there any risk when we logging in an account or when we use an account in Instagram-PHP?
Like delete or lock account

**Comment by mgp25** [comment]
Hello @loVeno. As long as you don't spam and use it for personal usage, you won't have any problem.

Regards
