### ISSUE TITLE
Get Further information about a user

### ISSUE THREAD

**Issue by loVeno** [mgp25/Instagram-API#1833]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Hi.
How can i get Two Way Follower (Who has follow a user an user followed back) Count?
Is there any way?

**Comment by DRSDavidSoft** [comment]
@mgp25 Can you point me in the example which exposes `is_following_you`?

**Comment by DRSDavidSoft** [comment]
@mgp25 after digging into the library, it seems that instead of `is_following_you` one could simply do:

```
$userId = $ig->people->getUserIdForName('username');
$isFollowingMe = $ig->people->getFriendship($userId)->followed_by;

var_dump($isFollowingMe);
```

(Posted as a future note for myself)

**Comment by abbasjami** [comment]
i want get user all data when i search feeds
