### ISSUE TITLE
Any risk of the account being blocked using this API?

### ISSUE THREAD

**Issue by loVeno** [mgp25/Instagram-API#1834]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

In my past topic you send an answer without any help!
I meant: i would like to create a system with your API, that user can download private accounts's story With their own personal account.
So I want no risk for their account.

**Comment by aitte2** [comment]
For that kind of usage you will hurt their accounts. Instagram will see your ip connecting lots of users and will think they are all related spammers and will place account shadowbans and stuff on those accounts. Shadowbans will make your views/reach bad. They wont get many people who see your new posts etc when their accounts are shadowbanned.
