### ISSUE TITLE
Get story number and item

### ISSUE THREAD

**Issue by olaferarn** [mgp25/Instagram-API#1835]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Hello
I want to get list of story and show as json.
But when i use it:

>    $response = $ig->story->getUserStoryFeed("306800759")->getReel()->getItems()[0];
>    $firstItem = $response->printJson();
>    print_r($firstItem);

it use URL without urlencode(), and when i try to get json (from other servers) and json_decode it's not work.
The json_last_error() said: JSON_ERROR_SYNTAX

And this erorr for put url withour encodeing.
How can i access it?

**Comment by aitte2** [comment]
Wrong usage. Printjson puts text in terminal. Nothing else. You need `->asJson` or something like that (i cant remember)

**Comment by mgp25** [comment]
Please go to LazyJsonMapper repo for more information.

Examples: https://github.com/SteveJobzniak/LazyJsonMapper/blob/9066dc567b25784eac9ffe653fac92abb7c2115a/examples/basic_example.php

Regards
