### ISSUE TITLE
Live->getViewerList() throws exception 

### ISSUE THREAD

**Issue by atyachin** [mgp25/Instagram-API#1836]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

I'm trying to retrieve the current viewers list of a broadcast that is **not owned** by the signed it user.
The getViewerList() method is throwing an exception.

Example Code:

```php
try {
  $ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
  $ig->login($username, $password);
  $topLives = $ig->live->getDiscoverTopLive()->getBroadcasts();
  $broadcastId = $topLives[0]->getId();
  $viewers = $ig->live->getViewerList($broadcastId)->getUsers();
  echo "number of users in chat: ".sizeof($viewers);
} catch (\Exception $e) {
  echo $e->getMessage();
}
```

Output:

```php
"No response from server. Either a connection or configuration error."
```

The above code works fine when I'm passing broadcastId of a broadcast that was started by the logged-in user.

**Comment by aitte2** [comment]
Instagram sends empty replies (closes connection) when you do something very illegal with very unpermitted parameters. That is a good hint here, you can guess the rest ;)

**Comment by atyachin** [comment]
Thanks aitte2.
This is not very clear from the getViewerList() method description...
It would be great if one of the contributors could add some comment in the method description/docs. 
In case someone finds it useful, here's some code to check that the broadcast belongs to the signed-in user:
```PHP
if ($ig->account_id != $ig->live->getInfo($broadcastId)->getBroadcastOwner()->getPk()) {
  echo "$brodcastId doesn't belong to logged-in user"
  return;
}
```

**Comment by aitte2** [comment]
In many cases functions have ocmment slike that but I imagine most of the info is from research in actual use like yours. I will reopen this :) We should document it for sure.

**Comment by aitte2** [comment]
Fixed :) Thanks for report
