### ISSUE TITLE
Hashtag getRelated is ok but empty

### ISSUE THREAD

**Issue by wowDaiver** [mgp25/Instagram-API#1837]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

When I try send request with $ig->hashtag->getRelated('cats'); I get empty result.
Could you please clarify Is it instagram closed this functionality?

For example:
```
try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->login('yourusername', 'yourpassword');
    $result = $ig->hashtag->getRelated('cats');
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Answer is 
```
 GET: https://i.instagram.com/api/v1/tags/cats/related/?visited=%5B%7B%22id%22%3A%22cats%22%2C%22type%22%3A%22hashtag%22%7D%5D&related_types=%5B%22hashtag%22%5D → 0B ← 200 31B 
RESPONSE: {"related": [], "status": "ok"}
```

**Comment by aitte2** [comment]
I don't think they have closed that endpoint. It's just almost-useless. If you look at other `getRelated` such as `location->getRelated` they have the same problem:

https://github.com/mgp25/Instagram-API/blob/d1cd8b2dd140ddc9f36ed2c8389b46117f4132c6/src/Request/Location.php#L158-L162

In my experience the getRelated for locations sometimes has some data for locations in very large cities but is useless for anything else.

**Comment by wowDaiver** [comment]
I noticed this after Instagram made a subscription to the tags. also related tags work in the instagramapp.

**Comment by aitte2** [comment]
Interesting. @mgp25 maybe they changed this "get related hashtag" endpoint parameters if it works in appp but not here?

**Comment by mgp25** [comment]
This is due to a deprecate version of the API. Check latest commit from `dev-master`. After applying latest commit, the endpoint should be working again.

Regards

**Comment by aitte2** [comment]
Ohhh coool, we got a new version update. Thanks! :)
