### ISSUE TITLE
Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.

### ISSUE THREAD

**Issue by Bupyc** [mgp25/Instagram-API#1838]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** one
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hello, i install api, try to login - and get ( [message] => Your version of Instagram is out of date. Please upgrade your app to log in to Instagram. [status] => fail [error_type] => needs_upgrade ) 

In Wiki i see "If you get this message with this API, please open a new issue."

**Comment by mgp25** [comment]
Please use `dev-master` version

Regards

**Comment by Bupyc** [comment]
@mgp25 , i use dev-master  but i have same error.
