### ISSUE TITLE
Download all Messages from Chat

### ISSUE THREAD

**Issue by werthd** [mgp25/Instagram-API#1839]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hello, as you can see i searched everything in this project. I look almost everywhere i can think of to find a solution to download a whole chat. I would be nice to have all messages from the chat at one time.

Im sorry for my english and if this is a "dumb" question.

**Comment by aitte2** [comment]
You can do it :) Everything for direct chat messages is in here:

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php

I think you get the inbox, then find the thread id in your inbox, then request pages of that thread by `getThread()` with `$cursorId` used for requesting more and more pages.

**Comment by werthd** [comment]
Hi there again, I am slowly getting frustrated because im trying to install this under XAMPP/OSX and just so many things that I have to struggle with. The thing I can't seem to solve on my own ist a
```Warning: chmod(): Operation not permitted in /opt/lampp/htdocs/dashboard/vendor/mgp25/instagram-php/src/Utils.php on line 900 ```
I found the issues on this others had before but my knowledge seems to lack at this point. How can I solve this ? Thanks

**Comment by mgp25** [comment]
@werthd not API issue. Please use google.

Regards

**Comment by krismorte** [comment]
The `$cursorId` is in the inbox Object?
And the result URL will be like this

`direct_v2/inbox/persistentBadging=true&use_unified_inbox=true&cursor=`

**Comment by Limule** [comment]
Hi, is there an offset param to get more thread ?
