### ISSUE TITLE
Is this going to get affected by the deprecation of the whole Instagram API platform

### ISSUE THREAD

**Issue by anchetaWern** [mgp25/Instagram-API#1840]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

I just read that the whole Instagram API platform will get deprecated: https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/

this means no more endpoints for follower list, relationships and the like. 

Do you think this API will also get affected by these changes? Thanks in advanced!

**Comment by aitte2** [comment]
omg

https://github.com/mgp25/Instagram-API/issues/1823
https://github.com/mgp25/Instagram-API/issues/1816

**Comment by mgp25** [comment]
PLEASE, search in the closed issues!
