### ISSUE TITLE
 How can I reply with a story in Direct

### ISSUE THREAD

**Issue by mrb4hr4m** [mgp25/Instagram-API#1841]
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
-  [x] Question
- [ ] Other

---

Hi . I can share a  user story to other users .with `sendStory` in `direct.php`  . but i can't reply story to user . do you have any idea about this ?

thank you .

**Comment by mgp25** [comment]
First of all. Can this be done within the app?

**Comment by mrb4hr4m** [comment]
@mgp25 I know this is possible and we can done this with this app but i don't know how. i checked instagram android source but i cant't find a way .

Thanks .

**Comment by mgp25** [comment]
@mrb4hr4m then tell me how to do it in the app so i can check it

**Comment by mrb4hr4m** [comment]
@mgp25 You mean how we can replay story in  instagram official app ? opening story > write something inside EditText at the bottom of the page > click on send button .

**Comment by aitte2** [comment]
https://github.com/mgp25/Instagram-API/blob/796ca28a3ab7cbdf613f07aebecccec3f13a19bc/src/Request/Direct.php#L603-L630

https://github.com/mgp25/Instagram-API/blob/796ca28a3ab7cbdf613f07aebecccec3f13a19bc/src/Request/Direct.php#L697-L725

**Comment by mrb4hr4m** [comment]
@aitte2 "disappearing media" is uploading photo or video like story in direct inbox . i don't want it . when we replay any story , istagram showed story and wrote "You replied to their story" in direct . i don't want 'reshare' or 'send' or 'upload' story . i just want replay story in direct.
