### ISSUE TITLE
how to get most hot instagram's hashtag?

### ISSUE THREAD

**Issue by mhhg78** [mgp25/Instagram-API#1842]
how to get most hot instagram's hashtag?

**Comment by mgp25** [comment]
@mhhg78 I don't know if that can be done with Instagram. Keep in mind that if is not possible to do in the app, wont be possible in the API. So before opening this issue, you need to verify wether that option is available in the app.

And so far, i think we have implemented already all hashtag related functions... so...

1) Has the API that feature? (Y/N)
2) if N, then nothing more to do. If Y, send more information

Regards
