### ISSUE TITLE
2 factor dont work please help

### ISSUE THREAD

**Issue by ploitscom** [mgp25/Instagram-API#1844]
can someone test if the verification in two steps works please already try it and not

i try this:

```php
$loginResponse = $ig->login($username, $password);

if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()){

$twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();


$verificationCode = '910786';

$ver = $ig->finishTwoFactorLogin($username, $password, $twoFactorIdentifier, $verificationCode);



print_r($ver);
}

```
I get an error response. The SMS is sent correctly and received.✓

**Comment by mgp25** [comment]
Invalid issue.

You haven't posted any debug log, error shown or anything. I tried this recently and worked okay.

Regards
