### ISSUE TITLE
How do I verify a session without logging in?

### ISSUE THREAD

**Issue by mercymainhere** [mgp25/Instagram-API#1845]
I didn't found an answer so here I'am with this question: Is this possible to verify account session without logging in?

**What I do?**
My application is simple. When I write a post on my blog cron script on server creates a "sneak peek" and puts it on my Instagram account. I have another similar script for Twitter and it works exacly the same way.

**What is wrong?**
Sometimes there is a large time gap between blog posts and account session dies. Twitter script just send me an e-mail when this happens and I do re-login stuff but Instagram script forces to login. It would be good if I didn't have two factor verification. I'm not always write posts on my computer and it's kind of annoying when I add post from phone and after a while I receive SMS with Instagram code.

**What would be great?**
If `login` method could throw `LoginRequiredException` when session expired without forcing logging in. That would be awesome. 

I found that line but there is no possibility to disable this kind of behavior.

```
[...]
try {
    $this->timeline->getTimelineFeed(null, [
        'is_pull_to_refresh' => $isSessionExpired ? null : mt_rand(1, 3) < 3,
    ]);
} catch (\InstagramAPI\Exception\LoginRequiredException $e) {
    // If our session cookies are expired, we were now told to login,
    // so handle that by running a forced relogin in that case!
    return $this->_login($this->username, $this->password, true, $appRefreshInterval);
}
[...]
```

**Comment by aitte2** [comment]
A quick search found this related ticket: https://github.com/mgp25/Instagram-API/issues/1621

I don't think the class should change its autologin behavior... it is important that it takes care of login/resume automatically without needing to catch errors. It makes no sense to be able to make the login() function not do a login when it needs to.

You can privately do what you are after with some trick instead, something like this:

```php
class MercyMainHere extends \InstagramAPI\Instagram
{
    public function mySpecialLogin($username, $password)
     {
        if ($this->username !== $username || $this->password !== $password) {
            $this->_setUser($username, $password);
        }
        if (!$this->isMaybeLoggedIn) {
            return false; // Session is definitely dead or doesn't exist.
        }
        try {
            $this->timeline->getTimelineFeed(null, [
                'is_pull_to_refresh' => true,
            ]);
        } catch (\InstagramAPI\Exception\LoginRequiredException $e) {
            return false; // Do nothing if session is no longer valid.
        }
        return $this->login($username, $password);
    }
}
```

The concept is: set user, check the login-guess (isMaybeLoggedIn), then if it guesses you are logged in try a timeline refresh to know for sure. If that is all ok, do a real login call.

This is a hacky method but what you are asking for is very specific so rather use a hack than change the library for this very special requirement. ;)

Let me know if this works.

**Comment by mgp25** [comment]
Not API issue.

Regards

**Comment by MahdiPishguy** [comment]
@aitte2 hi, thanks 

i'm not sure this class is correct or not correct, but i get error
`"Call to a member function setActiveUser() on null"`

InstagramHelper.php:

```
use InstagramAPI\Exception\LoginRequiredException;
use InstagramAPI\Instagram;

class InstagramHelper extends Instagram
{
    public function __construct()
    {
        Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
    }

    public function mySpecialLogin($username, $password)
    {
        if ($this->username !== $username || $this->password !== $password) {
            $this->_setUser($username, $password);
        }
        if (!$this->isMaybeLoggedIn) {
            return false; // Session is definitely dead or doesn't exist.
        }
        try {
            $this->timeline->getTimelineFeed(null, [
                'is_pull_to_refresh' => true,
            ]);
        } catch (LoginRequiredException $e) {
            return false; // Do nothing if session is no longer valid.
        }
        return $this->login($username, $password); // You must call this too or Instagram may ban you.
    }
}
```

and using that in `InstagramController` class:

```
class InstagramController extends Controller
{
    public function check()
    {
        $username = 'insta__cheeta';
        $password = 'MahdiNarges123';

        $test = new InstagramHelper();

        dd($test->mySpecialLogin($username,$password));
    }
}
```

**Comment by aitte2** [comment]
@MahdiPishguy Hello :) Your bug is in your `__construct()` function. It doesn't call the original constructor.

Change yours to say this:

```php
    public function __construct()
    {
        Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
        parent::__construct();
    }
```

**Comment by MahdiPishguy** [comment]
@aitte2 Thanks , i fix that, in this sample

i want to check user has session if thats return true print `session found` otherwise print login
in this code i get `session not found` as i have data on session folder and after delete data i get not found again, could you help me please, Thanks in advance.

```
class InstagramController extends Controller
{
    public function __construct()
    {
        ini_set('max_execution_time', 300000);
    }

    public function check()
    {
        $username = 'insta__cheeta';
        $password = 'MahdiNarges123';

        $test = new InstagramHelper();

        $result = $test->mySpecialLogin($username, $password);

        if (!$result) { // USER NOT LOGGIN INTO ACCOUNT
            echo('user session not found');
            $ig = new Instagram();
            try {
                $ig->login($username, $password);
            } catch (\Exception $e) {
                echo 'Something went wrong: ' . $e->getMessage() . "\n";
                exit(0);
            }
        } else { // USER LOGIN SESSION FOUND UPLOAD PHOTO
            // ...
            echo('user session found');
        }
    }
}

```

**Comment by aitte2** [comment]
@MahdiPishguy Hi. Sorry no time... You will have to read the code in this comment (which you copied):

https://github.com/mgp25/Instagram-API/issues/1845#issuecomment-370248726

It's fully commented so you can see what every step does.

Look at those steps and change its behavior to fit your own requirements. Good luck.

**Comment by MahdiPishguy** [comment]
@aitte2 Thank you very much man, for end of your PS, yes i'm trying to do that like with GramEasy, i have another question as can i have your mail address? thanks in advance
