### ISSUE TITLE
Instagram has opened an alpha program for its Android app

### ISSUE THREAD

**Issue by aitte2** [mgp25/Instagram-API#1846]
@mgp https://www.androidpolice.com/2017/12/19/instagram-opened-alpha-program-android-app-heres-can-enroll/

Here's something new for your info, which you should know. because it's probably a bad idea to update constants to an alpha version signature :D Be sure you never grab keys from those versions!

**Comment by mgp25** [comment]
Hello @aitte2,

Yes, i am already aware of that. They introduced it (or at least i noticed it) 1 month ago more or less.

Regards
