### ISSUE TITLE
No Max ID for getLikers Response

### ISSUE THREAD

**Issue by koconder** [mgp25/Instagram-API#1849]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Trying to utilise the getLikers() function, unable to get more than 1,000 results for usernames that have liked a media item on instagram, removed a media ID but you can test with anything more than 1k from the explore feed.

`        $response = $ig->media->getLikers("(instagrammediaid)");
        $response_array = $response->getFullResponse();
        $response_array = json_decode(json_encode($response_array), true);
        print_r($response_array);`

I have analysed the request response headers to Instagram and no max_id request is sent and nothing in the response, I have tried to refactor the classes in Media.php for pushing through the max id:

`    /**
     * Get list of users who liked a media item.
     *
     * @param string $mediaId The media ID in Instagram's internal format (ie "3482384834_43294").
     * @param null|string $maxId Next "maximum ID", used for pagination.
     * @throws \InstagramAPI\Exception\InstagramException
     *
     * @return \InstagramAPI\Response\MediaLikersResponse
     */
    public function getLikers(
        $mediaId, $maxId = null)
    {
        $request = $this->ig->request("media/{$mediaId}/likers/");
        if ($maxId !== null) {
            $request->addParam('max_id', $maxId);
        }
        return $request->getResponse(new Response\MediaLikersResponse());
    }`

**Comment by mgp25** [comment]
Hello @koconder.

It is a duplicate issue:

https://github.com/mgp25/Instagram-API/search?utf8=%E2%9C%93&q=likers&type=Issues

Regards
