### ISSUE TITLE
Video upload

### ISSUE THREAD

**Issue by EXECUTOR-brandon** [mgp25/Instagram-API#185]
I have several short videos about 0.5mb in size and all .mp4 format.
Images with captions upload without problems but I've tried these videos and they seem to try to upload but do not actually post. I do not receive any errors maybe there are dimension limits just like images that must be jpg/jpeg and 400x400.  Any help would be greatly appreciated with this. Thank you
Here's my code:

<?php
require_once("Instagram/Instagram.php");
$username="**********";
$password="**********";
$debug=false;
$video="video.mp4";
$caption="My Video";
$i=new Instagram($username, $password, $debug);
try
{
$i->login();
}
catch(InstagramException $e)
{
$e->getMessage();
exit();
}
try
{
$i->uploadVideo($video, $caption);
}
catch(Exception $e)
{
echo $e->getMessage();
}
?>

**Comment by mgp25** [comment]
@EXECUTOR-brandon please paste debug log and install dependencies

Regards

**Comment by EXECUTOR-brandon** [comment]
Debug log states 2 errors when I search for the word "error" on the page:

Error 1:
 RESPONSE: RESPONSE: Oops, an error occurred. REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=bc351000818a47e148bc633d1e29cdf3069027c2f12802fa396953bbeedffe06.{"upload_id":null,"camera_model":"HM1S","source_type":3,"date_time_original":"2016:05:23 16:02:48","camera_make":"XIAOMI","edits":{"crop_original_size":[null,null],"crop_zoom":1.3333334,"crop_center":[0.0,-0.0]},"extra":{"source_width":null,"source_height":null},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"36529f4b117bdd1cae977fb8a7bcf7ce","_uuid":"f2f41e51-847d-449f-b460-a91a92e07829","_uid":3258530472,"caption":"My Video"} RESPONSE: {"status": "fail", "message": "upload_id is None"}

Error 2:
{"status": "fail", "message": "Other media configure error: gwcxKj2O6e"}

I noticed that my Upload ID is null/missing.
I also tried full path to video with same error.

**Comment by mgp25** [comment]
@EXECUTOR-brandon you havent installed dependencies

**Comment by EXECUTOR-brandon** [comment]
Oh ok I will look into that process thank you.

**Comment by EXECUTOR-brandon** [comment]
I was missing ffmpeg in my dependencies now I get this error:

{"status": "fail", "message": "Uploaded image isn't in the right format"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=003f8013177929dd859f92564286d4468c84d7953f895554dd928226dc5bc3e8.{"_uuid":"c5056c8e-eb77-4ba7-987c-2739f6576c62","_uid":"3258530472","id":"3258530472","_csrftoken":"HIDDEN","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} REQUEST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=eeb536b9f36967d218134895ca3f2b7e34e689c0c0dbc57114437a69255e45c9.{"upload_id":1464023341012,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":295,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"010663d0e70fcc067122147c7047f/506","_uuid":"c5056c8e-eb77-4ba7-987c-2739f6576c62","_uid":"3258530472","caption":"My Video"} RESPONSE: {"status": "fail", "message": "Other media configure error: yEmZkUpAj4"}

I am using:
$i->uploadVideo($video, $caption);

Video is 2 channel 30fps mp4 already posts to my instagram account via phone so no issue there.

**Comment by mgp25** [comment]
It says: Uploaded image isn't in the right format

Try with other mp4 encoding, and dimensions.

**Comment by EXECUTOR-brandon** [comment]
OK I will and update later thank you I know it's something with the video file itself according to the error.

**Comment by EXECUTOR-brandon** [comment]
After multiple videos, with different sizes and lengths all encoded properly and able to upload through my mobile device I still receive the exact same error for a VIDEO stating:
{"status": "fail", "message": "Uploaded image isn't in the right format"}
All is well with only JPG images haven't found a solution yet. Will keep this updated.

**Comment by EXECUTOR-brandon** [comment]
I was looking at the Instagram.php code trying to fix the video upload issue and noticed that line 494
says:   $this->uploadPhoto($video, $caption, $upload_id); 
Shouldn't that be:  $this->uploadVideo($video, $caption, $upload_id); ?

Also what about the:  public function uploadVideo($video, $caption = null) 
Shouldn't that be:  public function uploadVideo($video, $caption = null, $upload_id = null) ?

I'm NO EXPERT AT ALL but it looks like it may fix video issues.
After I did my own corrections
Now the problem I receive is a PHP error:
PHP Notice:  Undefined index: video_upload_urls /Instagram.php on line 348
Which loops until I run out of memory.

**Comment by EXECUTOR-brandon** [comment]
Now i'm encountering a new error and it doesn't think my video is an image anymore.
RESPONSE: {"status": "ok", "media": {"upload_id": 1464967671205}, "message": "media_needs_reupload", "error_title": "staged_position_not_found"}

Looked under issue #60 didn't find any solution unless I missed something. Other sources are stating to downgrade from 5.6 to 5.5.30 or lower to solve the issue but I doubt that could be the problem.

**Comment by rizkyred** [comment]
what is the mean of "installed dependencies" @mgp25
