### ISSUE TITLE
Challenge required every time I'm trying to login.

### ISSUE THREAD

**Issue by mashkovtsevlx** [mgp25/Instagram-API#1851]
Hello. I'm trying to log in.
Every time script throws me a message "Challenge required". Of course, I accept the challenge in the mobile app. 
Here's full exception text:
`InstagramAPI\Exception\ChallengeRequiredException: InstagramAPI\Response\LoginResponse: Challenge required. in /var/www/html/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:151
Stack trace:
#0 /var/www/html/vendor/mgp25/instagram-php/src/Client.php(570): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'Challenge requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/html/vendor/mgp25/instagram-php/src/Request.php(705): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\LoginResponse), Object(stdClass), Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/vendor/mgp25/instagram-php/src/Instagram.php(399): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /var/www/html/reciever.php(17): InstagramAPI\Instagram->login('user_here', 'pass_here')`

I migrated to the new server. Maybe here's a problem

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean
