### ISSUE TITLE
instead of Payload\ThreadActivity, an Event\Payload\Activity is given

### ISSUE THREAD

**Issue by DRSDavidSoft** [mgp25/Instagram-API#1855]
### Before submitting this issue, I've made sure that I have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of my issue:
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For this *bug report*, the *code* that will replicate the error, is:

**The exact example in:**
`/examples/realtimeClient.php`

**Executed via:**
`sudo php examples/realtimeClient.php` from `/var/www/html` (**CLI**, not web-server)

### ... and the *error log/traceback* is:

```
PHP Fatal error:

	Uncaught TypeError: Argument 2 passed to {closure}() must be an instance of InstagramAPI\Realtime\Payload\ThreadActivity,
	instance of InstagramAPI\Realtime\Event\Payload\Activity given,

	called in /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php on line 123

Stack trace:
#0 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}('340282366841710...', Object(InstagramAPI\Realtime\Event\Payload\Activity))
#1 /var/www/html/vendor/mgp25/instagram-php/src/Realtime/Event/Patch/Op.php(235): InstagramAPI\Realtime->emit('thread-activity', Array)
#2 /var/www/html/vendor/mgp25/instagram-php/src/Realtime/Event/Patch/Op.php(275): InstagramAPI\Realtime\Event\Patch\Op->_upsertThreadActivity()
#3 /var/www/html/vendor/mgp25/instagram-php/src/Realtime/Event/Patch/Op.php(551): InstagramAPI\Realtime\Event\Patch\Op->_handleAdd()
#4 /var/www/html/vendor/mgp25/instagram-php/src/Realtime/Event/Patch.php(42): InstagramAPI\Realtim in /var/www/html/index.php on line 136
```

---

### Describe your issue

I'm reading the Wiki and trying to execute each of the examples to get a better grasp at this (amazing) API. For now, I won't be modifying any of the examples.

This issue happened when I was trying the `realtimeClient.php` example. After setting up React and Instagram-API via `composer require`, I filled in the `$username` and `$password` variables, and ran the script from **CLI** using: `sudo php examples/realtimeClient.php`  – note that the examples were _cloned_ directly from git.

With `$debug` set to true, I got some messages regarding GMP on x86 (I assume for the MQTT protocol that Facebook Messenger uses for Instagram.) However, I was not on a x86 machine (nor was I using Windows), rather then testing the library on Raspbian OS on a Raspberry Pi.

So, I proceeded to `apt install php-gmp` and a `libgmp` which seemed to make the error go away.

The script appears to be stable, until I discovered it crashes on one odd behavior: If I try typing in a DM thread using _another_ account.

After more testing, I can confirm that the script won't crash If I don't repeat this. But as soon as I start typing from that _another_ account, the script ends with the PHP fatal error.

This doesn't seem to be an existing issue, either.

**Comment by mgp25** [comment]
Hello @DRSDavidSoft,

Are you using `dev-master` code? I just tried the code and it works perfectly. Latest stable release is VERY outdated.

**Comment by valga** [comment]
@DRSDavidSoft You are using an example from `dev-master` with stable release. There were massive refactoring around realtime code, so some things were renamed. Please browse [stable examples](https://github.com/mgp25/Instagram-API/tree/9996d447574938b8a117cf84ac58479b78fc76fa/examples) or update your composer requirements to `dev-master`.

**Comment by valga** [comment]
@mgp25 Hi. What about releasing new version?

**Comment by mgp25** [comment]
@valga im into that, but haven't got time lately to write a properly release note.

**Comment by DRSDavidSoft** [comment]
@mgp25 @valga Thanks for the quick reply, and I appreciate all the work you guys do for the open-source community.

I believe `composer require` defaults to the stable releases? If so, do I need to call something to change what branch of Instagram-API `composer` would use instead?

**Comment by mgp25** [comment]
Hello @DRSDavidSoft,

Yes, `composer require mgp25/instagram-php dev-master`

It was explained in the Readme.

Regards

**Comment by DRSDavidSoft** [comment]
@mgp25 I'm so sorry for not noticing that before. Sidenote: is `dev-master` considered stable enough to be used in production? I understand while refactoring, the logic should stay the same, if I'm not mistaken.

**Comment by mgp25** [comment]
@DRSDavidSoft No problem. Yes, actually is the most stable code we have at the moment. It is safe to be used in production. Keep in mind that some code could have changed and there are some breaks in the backwards compatibility. Overall, almost everything remains the same.

Regards

**Comment by DRSDavidSoft** [comment]
@mgp25 I really appreciate the time and energy you put into this project! :)

**Comment by mgp25** [comment]
@DRSDavidSoft Thanks. Our team did an outstanding work here @valga @SteveJobzniak @aitte2
