### ISSUE TITLE
Hashtag feed has been changed

### ISSUE THREAD

**Issue by BaderMudarra** [mgp25/Instagram-API#1858]
Hi guys

I am testing instagram app version 26.0.0.13.86 and the tag search is now showing two tabs: TOP and RECENT

The current library calls feed/tag/{$urlHashtag}/

However, the mobile is calling
tags/[TAG]/ranked/?..
and
tags/[TAG]/recent/?..

I think getFeed() function in Request\Hashtag.php need to be modified.

Thanks

**Comment by mgp25** [comment]
@BaderMudarra thanks. Im going to check it with actual API version in an hour or so.

Regards

**Comment by AlSalamFas** [comment]
Yes in hashtag search is 2 parts of result list: ”top” and ”recent”.

Put it in same function pls. GetFeed(tag, want recent or top)

**Comment by mgp25** [comment]
API version doesn't do that, in fact it has both recent and ranked items in the same response (also stories).

Regards

**Comment by BaderMudarra** [comment]
@mgp25 what do you mean by API version? 
I attached the requests log from the official app which shows two different APIs.

**Comment by jettero777** [comment]
> 
> API version doesn't do that, in fact it has both recent and ranked items in the same response (also stories).
> 
> Regards

Hi @mgp25 as I see the ranked items limited to 9 items only. Instagram web version also show 9 items only.
While the app show much more top items. Is it because endpoint was changed as was described in this issue?
