### ISSUE TITLE
anyone can login when session exist!

### ISSUE THREAD

**Issue by hossin277** [mgp25/Instagram-API#1859]
Hi . i use Instagram-API for android application!
but when somebody login and session created , if someone else login with that username with wrong password , will login to that account!
how can fix this issue?
tnx

**Comment by mgp25** [comment]
Hello @hossin277,

It is not an issue. You are using a valid session of an user, that exactly what Instagram App does. You can force a login, but it is not recommended. Any layer of security should be added on top of the API.

Regards

**Comment by Stiveknx** [comment]
@mgp25  And how do I force a re-login? 
In login functions, is hardcoded to "false".
https://github.com/mgp25/Instagram-API/blob/6939ba1aadcbddf7277b5a28a6d09715d5632c07/src/Instagram.php#L444

**Comment by aitte2** [comment]
@Stiveknx Hi, you're thinking about this problem the wrong way. :) The real app reuses permanent sessions, and has no login/logout behavior. It stays always logged in. This library matches that.

If you want to prevent users from doing logins to another users account, you need to add _your own_ secondary security. There's some old chats that talk about it: https://github.com/mgp25/Instagram-API/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+force+login (especially this: https://github.com/mgp25/Instagram-API/issues/1667)
