### ISSUE TITLE
editProfile method do not working

### ISSUE THREAD

**Issue by ratm92** [mgp25/Instagram-API#186]
Hello!

I found some problem with editProfile method, it does not working for me :(

`'full_name'     => $first_name,`
Should be changed to:
`'first_name'     => $first_name,`
 
Also there is additional field: 
`chaining_enabled`
 
`return $this->request('accounts/edit_profile/', $this->generateSignature($data))[1];`
And here I guess `edit_profile` have been changed to `edit`.

Thank you ;)

**Comment by mgp25** [comment]
Send a pull request when you have the working endpoint

Regards
