### ISSUE TITLE
.

### ISSUE THREAD

**Issue by nelsonjfpereira** [mgp25/Instagram-API#1863]

**Comment by nelsonjfpereira** [comment]
After some tests, I found that this is related to the account pf the user you follow being private or public. If it's private the reel result is null. Don't know if this is new or it was always like this.

Anyone knows a workaround since we're requesting information of someone we follow and after we've login?

**Comment by aitte2** [comment]
Don't know what your question is but `getUserStoryFeed` is the most correct function (real app uses it).
