### ISSUE TITLE
API help needed: Highlight item details from it's id highlight:179xyz.. (received from tray response).

### ISSUE THREAD

**Issue by wondersoftwares** [mgp25/Instagram-API#1865]
Hello!
I am getting highlight tray response from request("highlights/25025320/highlights_tray/"). But when looking into response when tray have multiple tray items(like Instagram account) and some of it's items doesn't have media items array included(Response shown at bottom).

As I've also noticed into Instagram, The same highlight story(with empty items) is loading on its click and then start playing. So there must be some api link from where we could get highlight details from its id given by tray. I've looked into our project files but couldn't find any hint.

So I wanted to get media items of it from its "id":"highlight:17912042755026444" and there's no method to do this.

By the way very well done for the whole api's and work!
Thanks a lot. It helped so much!

My Highlight tray Api Response for the Instagram:
```

{

    "tray":[
        {
            "id":"highlight:17883141376162110",
            "latest_reel_media":1513892613,
            "seen":null,
            "can_reply":false,
            "can_reshare":true,
            "reel_type":"highlight_reel",
            "cover_media":{...},
            "user":{...},
            "items":[....],
            "ranked_position":-1514391956,
            "title":"Talent Show",
            "seen_ranked_position":-1514391956,
            "prefetch_count":0
        },
        {...},
        {...},
        {...},
        {
            "id":"highlight:17912042755026444",
            "latest_reel_media":1512339240,
            "seen":null,
            "can_reply":false,
            "can_reshare":null,
            "reel_type":"highlight_reel",
            "cover_media":{...},
            "user":{...},
            "ranked_position":-1512439086,
            "title":"Art \ud83c\udfa8",
            "seen_ranked_position":-1512439086,
            "prefetch_count":0
        },
        {...}
    ],
    "show_empty_state":false,
    "status":"ok"

}
```

**Comment by mgp25** [comment]
```php
$highlights = $ig->highlight->getUserFeed($userId);

foreach ($highlights->getTray() as $tray) {
  if ($tray->getId() === 'highlight:17912042755026444') {
    $medias = $tray->getItems();
    break;
  }
```

Regards

**Comment by aitte2** [comment]
Mgp, he means that some things in the tray have no media items (null), so there must be some missing ”get items for highlight:28838383” endpoint.

**Comment by mgp25** [comment]
@aitte2 i just double check this, and i have the same conclusion as my previous comment. So far, there isn't other request to obtain all the items from a specific highlight. The only thing you can do is, is getting all of them together with `$highlights = $ig->highlight->getUserFeed($userId);`

You can check this in your device and there is no option to do that (I am using latest version).

**Comment by aitte2** [comment]
Good research!! :D I tried writing docs. Are these okay? https://github.com/mgp25/Instagram-API/commit/5fac0e1ca966e440b80c7937c9f19b7cb07cf2a1

**Comment by mgp25** [comment]
@aitte2 

<img src="https://sd.keepcalm-o-matic.co.uk/i-w600/this-is-purrfect.jpg" width=200>

**Comment by wondersoftwares** [comment]
Thank you guys for this updates but I am still unable to get highlight items. What I've tried and got responses showing below:

Request #1: 
url("https://i.instagram.com/api/v1/feed/reels_media/")
key("user_ids")
value("highlight:17883141376162110")
Response: {"message": "Invalid reel id list", "status": "fail"}

Request #2: 
url("https://i.instagram.com/api/v1/feed/reels_media/")
key("user_ids")
value(new String[]{"highlight:17883141376162110"})
Response: {"message": "Invalid reel id list", "status": "fail"}

Request #3: 
url("https://i.instagram.com/api/v1/feed/reels_media/")
key("user_ids")
value("17883141376162110")
Response: {"message": "Invalid reel id list", "status": "fail"}

Any solution?

**Comment by mgp25** [comment]
@wondersoftwares post debug log

**Comment by wondersoftwares** [comment]
Hi @mgp25, I'm using your lib support in Android and working fine with all other functions but in this feature I am getting this fail response so I need help in this.
Did you get the response by using this id 'highlight:11115084198240000' in the function getReelsMediaFeed?
Thanks!

**Comment by mgp25** [comment]
Can I see this android library you are talking about? (URL)

**Comment by wondersoftwares** [comment]
I am using this on my android app and it is incomplete so it isn't live and there's no url till now!
Is there any solution for this Response: {"message": "Invalid reel id list", "status": "fail"}
?
