### ISSUE TITLE
Is it possible to get most-liked / most-viewed posts for special user ?

### ISSUE THREAD

**Issue by Mehrdad1991h** [mgp25/Instagram-API#1867]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
after search and read wiki and issue just find [this issue](https://github.com/mgp25/Instagram-API/issues/850) 
But i don't have any special `hashtag`, and also want to get only most viewed and most liked post for `special user` so want to know have any solution ?
(I don't want to get all posts and check them for find most viewed/liked... looking for better solution.)

Thanks and kind regards.

**Comment by mgp25** [comment]
<img src="https://s10.postimg.org/ipg08bzh5/image.jpg" width=200>
