### ISSUE TITLE
Question regard to first media upload and link of profile

### ISSUE THREAD

**Issue by culturalmass** [mgp25/Instagram-API#1868]
[X] Question
Hi,
I am very happy to find this awesome code, to work with Instagram.
Thank you for the API!.
My question is the following, is inside the API?:
a function to call for the first upload media of a request username, or the link of the 
profile.
I looking to chain to my script to do such like , following liking. 
Taking the information of the function getRecentActivityInbox or getLikers.
and using printPropertyDescriptions to get username and tokenid.
but i am failing to get the upload media or the link to the profile.

Well i hope my question is clear and thank to the help in advance.
Salutes

**Comment by mgp25** [comment]
Yes, it is possible.

Check examples and wiki for more information.

Regards
