### ISSUE TITLE
Composer issue on Windows (master)

### ISSUE THREAD

**Issue by atyachin** [mgp25/Instagram-API#1870]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
The following command on Windows produces error:
`composer require mgp25/instagram-php dev-master`

Error:

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: lazyjsonmapper/lazyjsonmapper[v1.6.1, v1.5.1].
    - Can only install one of: lazyjsonmapper/lazyjsonmapper[v1.6.1, v1.5.1].
    - Can only install one of: lazyjsonmapper/lazyjsonmapper[v1.6.1, v1.5.1].
    - mgp25/instagram-php dev-master requires lazyjsonmapper/lazyjsonmapper ^1.6.1 -> satisfiable by lazyjsonmapper/lazyjsonmapper[v1.6.1].
    - Installation request for mgp25/instagram-php dev-master -> satisfiable by mgp25/instagram-php[dev-master].
    - Installation request for lazyjsonmapper/lazyjsonmapper (locked at v1.5.1) -> satisfiable by lazyjsonmapper/lazyjsonmapper[v1.5.1].

Installation failed, reverting ./composer.json to its original content.

This doesn't happen with the regular installation:
`composer require mgp25/instagram-php`

**Comment by atyachin** [comment]
Solved after running:
`composer require lazyjsonmapper/lazyjsonmapper`

And then running again:
`composer require mgp25/instagram-php dev-master`

**Comment by valga** [comment]
@atyachin It's a bug in composer itself: it doesn't treat dev- versions well.
