### ISSUE TITLE
How can get single collection's feed ?

### ISSUE THREAD

**Issue by JavaProgrammer1993** [mgp25/Instagram-API#1871]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
-  Question
- [ ] Other

---
Hi . we can get all saved media's in collection with `$ig->media->getSavedFeed()` . the question is how we can get special collection's feed ?

**Comment by mgp25** [comment]
Function added in latest commit: https://github.com/mgp25/Instagram-API/commit/afe3294cc814b39d735081b1b6b74b2d5099bf48

Regards
