### ISSUE TITLE
Unable to post caption (when using proxy)

### ISSUE THREAD

**Issue by vishal2647** [mgp25/Instagram-API#1872]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

Explanation of your issue goes here.

Almost all caption we provide works and shows on Instagram but few of them are not coming and photos get published with blank caption. For ex:
$caption = "Sunset in Huaihua. Huaihua is a small city in Hunan province. I was studying Chinese in Huaihua University during one year. The picture is from the main road in front of the University.";

If we try to publish an image with this caption, it will publsih with an empty caption. What might be causing this? 

One more thing: It is only happening when i am using a proxy. Without proxy, same caption is coming.

**Comment by mgp25** [comment]
I have not tried it, but it seems it is proxy issue.

Regards
