### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by mgp25** [mgp25/Instagram-API#1873]
@valga, @aitte2 - @SteveJobzniak 

One of the reasons many people are having issues is because using the latest stable release which is way too outdated. 

Lately i haven't as much time as i had before, so i couldn't write the release note. The aim of this issue is that everytime any of us has a little time on here, writes information for the release note. Since there was a lot of changes, i think we need to focus on big changes and backwards breaks.

_mgp25_

**Comment by SteveJobzniak** [comment]
Okay, I ran `git log --reverse 3.1..master > ~/Downloads/changes.txt` and started reading the changes to look for important ones...

---

- Examples: Most of the usage examples have been updated and extended to show various new features and abilities.
- Requests: Added new endpoints and updated old endpoints in many of the collections. Check your old code carefully after upgrading! There are **many backwards-compatibility breaking changes** to argument orders and argument usage! For example, _all pagination_ is now done via tokens, exactly like the real app (see the new examples for help with that).
- Models and Responses: Added lots of new properties to match Instagram's new API changes.
- The `MediaAutoResizer` class has been separated into `InstagramPhoto` and `InstagramVideo` classes instead.
- `InstagramVideo` is a new class which adds video processing support for the first time ever. You can now convert/validate your video files to ensure that they fit Instagram's requirements too!
- The `Push` system now automatically tracks, updates and re-registers your FBNS Push token (at login), exactly as intended by Instagram.

I am at `53e0423` and will continue this along the day and will update this post... but now it's time for breakfast :P
