### ISSUE TITLE
laravel problem

### ISSUE THREAD

**Issue by TechShankar** [mgp25/Instagram-API#1875]
i'm trying to upload photo returns this error "Class 'InstagramAPI\Media\Photo\InstagramPhoto' not found".

i found one solution from issue section this commend Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;. 

im set construct like this.

public function __construct()
    {
        Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
    }

this return this error. "Class 'App\Http\Controllers\Instagram\Instagram' not found".

please help how to solve this problem.

**Comment by mgp25** [comment]
Read the documentation+readme

Regards
