### ISSUE TITLE
MGP25 -- - reverse engineering

### ISSUE THREAD

**Issue by kwiiby** [mgp25/Instagram-API#1879]
@mgp25, you really enjoy this kind of stuff, right? =D
i imagine that it was a lot of work from you, hard work i mean..
i want to learn some things, can you explain me? ollydbg, packet sniffer, etc... i dont know if u use skype or whatsapp.. you are a very smart guy

i have thirsty of knowledge on this stuff, i have studied your api and i am amazed.

**Comment by kaykyr** [comment]
I'd like to know about that as well. Thanks.

**Comment by mgp25** [comment]
Hello, this is not the place to ask this kind of things. Remember that this is not a forum. This is just to solve issues related to the API, for any other stuff you can contact with me using my github email (github profile)

Regards
