### ISSUE TITLE
Edit from collections does not add medias

### ISSUE THREAD

**Issue by wowDaiver** [mgp25/Instagram-API#1883]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

I started using the collection and noticed the problem.

Endpoints:
media->save
collection->create (with media_id)
collection->getList
collection->removeMedia
it works fine

But looks like don't work $ig->collection->edit
Could you please check it?
```
try {
    $debug = true;
    \InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->login('yourusername', 'yourpassword');
    $result = $ig->collection->edit('...', array(
        'add_media' => ['...']
    ));
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```
Answer:
```
{
    "collection_id": "...",
    "collection_name": "Collection name",
    "status": "ok"
}
```
I no have any changes after that.

Note: Change collection name works fine

**Comment by wowDaiver** [comment]
Oh, I found the solve. I reserached code history and think so you need change $postData['add_media'] 
to $postData['added_media_ids']

![image](https://user-images.githubusercontent.com/5978067/38166223-e312b274-3528-11e8-904d-b59e38d93937.png)

**Comment by mgp25** [comment]
Hello @wowDaiver,

i have confirmed it.

Proof:

`{"module_name":"feed_saved_add_to_collection","added_media_ids":"[\"value\"]","_csrftoken":"token","_uid":"uid","_uuid":"uuid"}`


`URL: /api/v1/collections/id/edit/`

Thanks for reporting the bug! 😄 

Have a nice weekend

Regards

**Comment by mgp25** [comment]
Hello @wowDaiver,

i have confirmed it.

Proof:

`{"module_name":"feed_saved_add_to_collection","added_media_ids":"[\"value\"]","_csrftoken":"token","_uid":"uid","_uuid":"uuid"}`


`URL: /api/v1/collections/id/edit/`

Thanks for reporting the bug! 😄 

Have a nice weekend

Regards
