### ISSUE TITLE
Getting notification list

### ISSUE THREAD

**Issue by brunopiaui** [mgp25/Instagram-API#1885]
Hi,

I'm looking for a method to get the list of notifications about comments, likes...

Is there a method to return this list?

**Comment by mgp25** [comment]
Hello @brunopiaui,

make sure to search before opening a new issue.
https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php#L116

**Comment by brunopiaui** [comment]
I'm sorry, I've used the api and so far I've found everything I needed in the documentation and in the issues already open. I only opened this issue because I did not find it.

Thanks !!
