### ISSUE TITLE
pushReceiver.php doesn't work

### ISSUE THREAD

**Issue by arman4343** [mgp25/Instagram-API#1888]
Hello,

I run pushReceiver.php from cmd in windows 10.
When I use debug enable
`$debug = true;`
It's shows following error:
```
PHP Fatal error:  Class 'Monolog\Logger' not found in A:\xampp2\htdocs\instagram\pushReceiver.php on line 26

Fatal error: Class 'Monolog\Logger' not found in A:\xampp2\htdocs\instagram\pushReceiver.php on line 26
```
when debug is off
`$debug = false;`
It doesn't show any notification.

Any suggestion to solve this problem?

**Comment by mgp25** [comment]
Hello,

please read the Readme, it is explained how to install the API and its dependencies.

Regards

**Comment by aitte2** [comment]
@valga I think this ticket means some of the require-dev dependencies need to be moved to require?

https://github.com/mgp25/Instagram-API/blob/master/composer.json

**Comment by mgp25** [comment]
Good point @aitte2, i was using the dev stuff, and i thought it was a composer issue.

**Comment by aitte2** [comment]
I can test stable to see :)

**Comment by valga** [comment]
The library itself doesn't require `monolog/monolog`, but some examples do. We already have a warning about `react/http`, so I think it is better to make one for the logger.

**Comment by aitte2** [comment]
I checked. These are the only files that need Monolog or React\Http:

```
instagram-php/examples/pushReceiver.php
instagram-php/examples/realtimeClient.php
instagram-php/examples/realtimeHttp.php
```

Only one of them mentions needing react\http. The rest don't mention anything.

**Comment by arman4343** [comment]
It's work fine in Ubuntu but It doesn't work on Windows 10.
I'm looking for reason !

**Comment by valga** [comment]
@arman4343 `composer require monolog/monolog` will fix your problem. We are going to add that to the docs/examples.

**Comment by arman4343** [comment]
Thank you @valga .
I found my problem in windows.
I just need to enable GMP on PHP extension.

**Comment by valga** [comment]
Fixed in d8496fbef6b2e8b8a8e611e6734a8b6dd698182c.

**Comment by aitte2** [comment]
@valga Great :) Question:

- `vendor/valga/fbns-react/src/Thrift/Reader.php` and `vendor/valga/fbns-react/src/Thrift/Writer.php` are the vendor files that use gmp functions.
- `src/Realtime/Parser/GraphQlParser.php` and `src/Realtime/Parser/RegionHintParser.php` and `src/Realtime/Parser/SkywalkerParser.php` are the library files that use those gmp thrift things.

In https://github.com/mgp25/Instagram-API/commit/d8496fbef6b2e8b8a8e611e6734a8b6dd698182c you mention that the `Push` example needs gmp, but it seems like maybe the Push doesn't need it and only Realtime examples need it?

Just checking :)

**Comment by valga** [comment]
@aitte2 Nice catch. GMP is required for both Push (in my FBNS package) and Realtime. Will fix it.

**Comment by aitte2** [comment]
Okay great, glad I checked :) Will reopen until it's finished
