### ISSUE TITLE
Using Instagram API through Composer

### ISSUE THREAD

**Issue by HarryRowolt** [mgp25/Instagram-API#1889]
Ok, many may say I don't belong here and they are right. I am not a programer but sometimes I need some php or SQL. So now.... May be someone will give me a hint, can be considered social work. And in my field I help as well.....
I need to get the RTMP Key for livestreaming on Instagram with this API. I managed to install composer and PHP on my Windows PC (...) but I have no idea how to call the Script/API. 
If I try $ig = new \InstagramAPI\Instagram($debug, $truncatedDebug, $storageConfig = []);
I get "Command $ig is not defined".
Is there somebody who can point me in the right direction???? 
Thank you!!

**Comment by mgp25** [comment]
Hello @HarryRowolt,

Here you have some examples to start with and get familiarized with the API:

- [Examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

Also remember the installation steps explained in the readme:

`composer require mgp25/instagram-php`

Regards
