### ISSUE TITLE
How to get all media ids by hashtag?

### ISSUE THREAD

**Issue by dpavlovskiy** [mgp25/Instagram-API#1891]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---

How to get all media ids (list) for (by) hashtag?
This example gives only media_count:
```
$tag = 'specialhashtag';
$result = $ig->hashtag->search($tag);
$result->printJson();
	
{
    "results": [
        {
            "id": "17843124436038538",
            "name": "specialhashtag",
            "media_count": 498,
            "follow_status": null,
            "following": null,
            "allow_following": null,
            "allow_muting_story": null,
            "profile_pic_url": null,
            "non_violating": null,
            "related_tags": null,
            "debug_info": null
        },
    }
```

How to get 498 media ids?)
Thank you in advance!

**Comment by mgp25** [comment]
Please, search before opening an issue:

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Hashtag.php#L176

Regards

**Comment by dpavlovskiy** [comment]
Sorry & thank you so much!

**Comment by mgp25** [comment]
@dpavlovskiy no problem. You are wellcome. 

You can find examples here:

- [Examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

And documentation a FAQ here:

- [Wiki](https://github.com/mgp25/Instagram-API/wiki)

Regards
