### ISSUE TITLE
Requested resource does not exist

### ISSUE THREAD

**Issue by adminko-svk** [mgp25/Instagram-API#1892]
Hello, 
I get new error since yesterday when I try to add followers.

POST:  ```https://i.instagram.com/api/v1/friendships/create/3605779544/```
RESPONSE: page with title ```"Page Not Found &bull; Instagram"```

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

**Comment by mgp25** [comment]
Hello @adminko-svk,

user doesn't exist

Regards

**Comment by aitte2** [comment]
To add to this: IF you need to know when a user is missing, I am pretty sure you can catch that with https://github.com/mgp25/Instagram-API/blob/master/src/Exception/NotFoundException.php
