### ISSUE TITLE
Howto get the $MediaId for the image posted via  uploadPhoto() ?

### ISSUE THREAD

**Issue by iain-mildner** [mgp25/Instagram-API#1897]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
I have installed composer and the latest 4.0 codebase.

login() and uploadPhoto() to a profile works fine.

Now I want to start tagging users on the image I want to upload. After reading the docs I see that uploadPhotoAlbum() allows $usertags in the $metadata array BUT this does not seem to be available (yet?) in uploadPhoto()?

So I want to add the $UserTags info using  $IgObj->media->edit($MediaId, $CaptionText, $MetaData);

Todo that I need the $MediaId and thats whats driving me nuts!

QUESTION: what do i need todo code wise to get the media ID for the image posted via uploadPhoto() ?

Here is the code snippet I am using:

---
```php
set_time_limit(0);
date_default_timezone_set('Europe/Berlin');

require __DIR__.'/../vendor/autoload.php';

// login
try {
    $IgObj->login($Username, $Password);

} catch (\Exception $ErrObj) {
    echo 'Error: login($Username, $Password) - '.$ErrObj->getMessage()."\n";
    exit(0);
}
// uploadPhoto
try {
    // upload works OK
    $IgInfoObj = $IgObj->timeline->uploadPhoto($ImgFile, ['caption' => $MsgText]);

    // now I need the $MediaId from the posted image so look at data structures
    // dump data structure(s)
    $IgInfoObj->printJson();
    $IgInfoObj->printPropertyDescriptions();

    // now grab an array of items
    $IgItemList = $IgInfoObj->getItems();

    //  now grab the first [0] item of array
    $IgItem0 = $IgItemList[0]->getMedia();

    // dump data structure(s)
    $IgItem0->printJson();
    $IgItem0->printPropertyDescriptions();

    // and now grab the media id
    $MediaId = $IgItem0->getId(); 

    // with the $MediaId i can call the media->edit() function and tag the image!
    $IgObj->media->edit($MediaId, $CaptionText, $MetaData);

} catch (\Exception $ErrObj) {
    echo 'Error: uploadPhoto($ImgFile, ...) - '.$ErrObj->getMessage()."\n";
}

```php
// Please provide your error log/dump here, for example:

Error: uploadPhoto($ImgFile, ...) - Unknown function "getItems".

```

---

GET:  https://i.instagram.com/rupload_igphoto/1522954810442_0_-1252678344
→ 0B
← 200 	 12B
RESPONSE: {"offset":0}

POST:  https://i.instagram.com/rupload_igphoto/1522954810442_0_-1252678344
→ 166.93kB
← 200 	 69B
RESPONSE: {"upload_id": "1522954810442", "xsharing_nonces": {}, "status": "ok"}

POST:  https://i.instagram.com/api/v1/media/configure/
DATA: signed_body=4ddd8eb1c21ecf512e4f37279172ed4f5136d649ee8049cc378140b31bb27348.{"device":{"manufacturer":"samsung","model":"SM-G930F","android_version":"23","android_release":"6.0.1"},"_csrftoken":"RCQ9j1WoG0S1m9Ole3hDOL9LKhuuoFG3","media_folder":"Camera","source_type":"4","_uid":"4218889336","_uuid":"774ac689-4109-49f6-b20f-a3fb29bdd28f","edits":{"crop_original_size":[1024,1024],"crop_zoom":1,"crop_center":[0,0]},"extra":{"source_width":1024,"source_height":1024},"caption":"Reef V\n\nRetouch: @kiko.photodesign\nModel: @kiko.model\nPhoto: @lightaffaire\n\n#travel #spain #fuerteventura #asiangirl #nuvumagazine #cyranoshots #feetrica #scxnsor #vitacouture #unitedsedcards #oz_0 #foxyasiamagazine #bodymood #ngymn #shuttersteam #hottestgirlsontheplanet #frame_magazine #arsenicworldtour #sensual_dream #nude #fitnessmodel #fitchick #fitgirl #bodylanguage #body #loves_sensuality #sensual #nudeart #fineart #fineartphotography\n\n","upload_id":"1522954810442"}&ig_sig_key_version=4
← 200 	 1.46kB
RESPONSE: {"media": {"taken_at": 1522954811, "pk": 1750994329391287056, "id": "1750994329391287056_4218889336", "device_timestamp": 1522954810442, "media_type": 1, "code": "BhMyBC_F0sQCeqVxs5ryV5DfQkfrojpqNRdHoE0", "client_cache_key": "MTc1MDk5NDMyOTM5MTI4NzA1Ng==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 1024, "height": 1024, "url": "https://scontent-frt3-2.cdninstagram.com/vp/2864d1f9c39a0115906c71da4bde0022/5B6F9546/t51.2885-15/e35/29738980_2073655966244833_6082170850780381184_n.jpg?se=7\u0026ig_cache_key=MTc1MDk5NDMyOTM5MTI4NzA1Ng%3D%3D.2"}, {"width": 240, "height": 240, "url": "https://scontent-frt3-2.cdninstagram.com/vp/26af6bb25a8f1cd253824c1af23a9b57/5B570B85/t51.2885-15/s240x240/e35/29738980_2073655966244833_6082170850780381184_n.jpg?ig_cache_key=MTc1MDk5NDMyOTM5MTI4NzA1Ng%3D%3D.2"}]}, "original_width": 1024, "original_height": 1024, "user": {"pk": 4218889336, "username": "socialcli", "full_name": "socialtest", "is_private": true, "profile_pic_url": "https://sco...

RUN: $IgInfoObj->printJson()
{
    "media": {
        "taken_at": "1522954811",
        "pk": "1750994329391287056",
        "id": "1750994329391287056_4218889336",
        "device_timestamp": "1522954810442",
        "media_type": 1,
        "code": "BhMyBC_F0sQCeqVxs5ryV5DfQkfrojpqNRdHoE0",
        "client_cache_key": "MTc1MDk5NDMyOTM5MTI4NzA1Ng==.2",
        "filter_type": 0,
        "image_versions2": {
            "candidates": [
                {
                    "width": 1024,
                    "height": 1024,
                    "url": "https://scontent-frt3-2.cdninstagram.com/vp/2864d1f9c39a0115906c71da4bde0022/5B6F9546/t51.2885-15/e35/29738980_2073655966244833_6082170850780381184_n.jpg?se=7&ig_cache_key=MTc1MDk5NDMyOTM5MTI4NzA1Ng%3D%3D.2"
                },
                {
                    "width": 240,
                    "height": 240,
                    "url": "https://scontent-frt3-2.cdninstagram.com/vp/26af6bb25a8f1cd253824c1af23a9b57/5B570B85/t51.2885-15/s240x240/e35/29738980_2073655966244833_6082170850780381184_n.jpg?ig_cache_key=MTc1MDk5NDMyOTM5MTI4NzA1Ng%3D%3D.2"
                }
            ]
        },
        "original_width": 1024,
        "original_height": 1024,
        "user": {
            "pk": "4218889336",
            "username": "socialcli",
            "full_name": "socialtest",
            "is_private": true,
            "profile_pic_url": "https://scontent-frt3-2.cdninstagram.com/vp/4a4bde79842b0b273565e8089e7c4d0d/5B71C174/t51.2885-19/s150x150/14482822_204444896626045_4012101145022431232_a.jpg",
            "profile_pic_id": "1396300083418796698_4218889336",
            "has_anonymous_profile_picture": false,
            "can_boost_post": false,
            "can_see_organic_insights": false,
            "show_insights_terms": false,
            "is_unpublished": false,
            "allowed_commenter_type": "any"
        },
        "can_viewer_reshare": true,
        "caption": {
            "pk": "17930349736066050",
            "user_id": "4218889336",
            "text": "Reef V\n\nRetouch: @kiko.photodesign\nModel: @kiko.model\nPhoto: @lightaffaire\n\n#travel #spain #fuerteventura #asiangirl #nuvumagazine #cyranoshots #feetrica #scxnsor #vitacouture #unitedsedcards #oz_0 #foxyasiamagazine #bodymood #ngymn #shuttersteam #hottestgirlsontheplanet #frame_magazine #arsenicworldtour #sensual_dream #nude #fitnessmodel #fitchick #fitgirl #bodylanguage #body #loves_sensuality #sensual #nudeart #fineart #fineartphotography",
            "type": 1,
            "created_at": "1522954812",
            "created_at_utc": "1522954812",
            "content_type": "comment",
            "status": "Active",
            "bit_flags": 0,
            "user": {
                "pk": "4218889336",
                "username": "socialcli",
                "full_name": "socialtest",
                "is_private": true,
                "profile_pic_url": "https://scontent-frt3-2.cdninstagram.com/vp/4a4bde79842b0b273565e8089e7c4d0d/5B71C174/t51.2885-19/s150x150/14482822_204444896626045_4012101145022431232_a.jpg",
                "profile_pic_id": "1396300083418796698_4218889336",
                "has_anonymous_profile_picture": false,
                "can_boost_post": false,
                "can_see_organic_insights": false,
                "show_insights_terms": false,
                "is_unpublished": false,
                "allowed_commenter_type": "any"
            },
            "did_report_as_spam": false,
            "media_id": "1750994329391287056"
        },
        "caption_is_edited": false,
        "comment_likes_enabled": false,
        "comment_threading_enabled": false,
        "has_more_comments": false,
        "max_num_visible_preview_comments": 2,
        "preview_comments": [],
        "comment_count": 0,
        "photo_of_you": false,
        "can_viewer_save": true,
        "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjlkMTIwYzk1YWNlZjQyYjFhOGE1OTNiNDE1NjU3Mzk3MTc1MDk5NDMyOTM5MTI4NzA1NiIsInNlcnZlcl90b2tlbiI6IjE1MjI5NTQ4MTQxMjZ8MTc1MDk5NDMyOTM5MTI4NzA1Nnw0MjE4ODg5MzM2fDUwNDAxYjQ5MTBiYjIzM2JlM2QwNjY2ZjZkY2M1MjMwODU2ODZmNDdjZjMyZTE4ODM1Y2EzODQ2NWRjZWI2ZGQifSwic2lnbmF0dXJlIjoiIn0="
    },
    "upload_id": "1522954810442",
    "status": "ok"
}

RUN: $IgInfoObj->printPropertyDescriptions()
============================================================
> Class:    "\InstagramAPI\Response\ConfigureResponse"
  Supports: [X] Virtual Functions [ ] Virtual Properties
------------------------------------------------------------
  Show Functions: Yes.
  Allow Relative Types: No.
  Include Undefined Properties: No.
============================================================
  #01/07: "client_sidecar_id"
  * Type: "string" (Basic PHP type)
     has: bool hasClientSidecarId()
      is: bool isClientSidecarId()
     get: string getClientSidecarId()
     set: $this setClientSidecarId(string $value)
   unset: $this unsetClientSidecarId()
------------------------------------------------------------
  #02/07: "media"
  * Type: "\InstagramAPI\Response\Model\Item"
     has: bool hasMedia()
      is: bool isMedia()
     get: \InstagramAPI\Response\Model\Item getMedia()
     set: $this setMedia(\InstagramAPI\Response\Model\Item $value)
   unset: $this unsetMedia()
------------------------------------------------------------
  #03/07: "message"
  * Type: "mixed" (Basic PHP type)
     has: bool hasMessage()
      is: bool isMessage()
     get: mixed getMessage()
     set: $this setMessage(mixed $value)
   unset: $this unsetMessage()
------------------------------------------------------------
  #04/07: "message_metadata"
  * Type: "\InstagramAPI\Response\Model\DirectMessageMetadata[]"
     has: bool hasMessageMetadata()
      is: bool isMessageMetadata()
     get: \InstagramAPI\Response\Model\DirectMessageMetadata[] getMessageMetadata()
     set: $this setMessageMetadata(\InstagramAPI\Response\Model\DirectMessageMetadata[] $value)
   unset: $this unsetMessageMetadata()
------------------------------------------------------------
  #05/07: "status"
  * Type: "string" (Basic PHP type)
     has: bool hasStatus()
      is: bool isStatus()
     get: string getStatus()
     set: $this setStatus(string $value)
   unset: $this unsetStatus()
------------------------------------------------------------
  #06/07: "upload_id"
  * Type: "string" (Basic PHP type)
     has: bool hasUploadId()
      is: bool isUploadId()
     get: string getUploadId()
     set: $this setUploadId(string $value)
   unset: $this unsetUploadId()
------------------------------------------------------------
  #07/07: "_messages"
  * Type: "\InstagramAPI\Response\Model\_Message[]"
     has: bool has_Messages()
      is: bool is_Messages()
     get: \InstagramAPI\Response\Model\_Message[] get_Messages()
     set: $this set_Messages(\InstagramAPI\Response\Model\_Message[] $value)
   unset: $this unset_Messages()
============================================================

Error: uploadPhoto($ImgFile, ...) - Unknown function "getItems".

**Comment by mgp25** [comment]
`Media id` is property `id`.

You can know that `id` is the `Media id` because it is composed by the `pk` and your user id.

`mediaPk_yourUserId`

Hope your doubt is solved

Regards

**Comment by aitte2** [comment]
Your way of getting the uploaded ID is correct.

But I think you have only read the `examples/` folder, because if you read the actual code docs you will see that you **can* provide usertags in `uploadPhoto` (Begin by reading `src/Request/Timeline.php` at `uploadPhoto` function and follow the docs to its list of available metadata).

**Comment by RuPF** [comment]
> Unknown function "getItems".
Hello!
You have resolved the "Unknown function" getItems "." ? I faced the same problem. Thanks.
