### ISSUE TITLE
systemComments not store in timestamp

### ISSUE THREAD

**Issue by amirhododi** [mgp25/Instagram-API#1899]
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

Hi everyone

when use live example users comment was save but system comments like ****user joined not store in timestamp

**Comment by mgp25** [comment]
Yup. It is fixed as @aitte2 mentioned.

Commit: https://github.com/mgp25/Instagram-API/commit/5838b24cf3a94ef4af2d56ddc8ee276e04ec414d

Regards
