### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by capsload** [mgp25/Instagram-API#19]
Hello,

since 1-2 days, whenever i try to upload a Picture using the example uploadPhoto.php Script,
i get:

checkpoint_required

:<

**Comment by mgp25** [comment]
@capsload always post debug log..

**Comment by capsload** [comment]
Just saw that my Account got a CAPTCHA window, that causes the problem.

**Comment by rizkihape** [comment]
me too, how to fix this problom brad
