### ISSUE TITLE
Doubt Logout

### ISSUE THREAD

**Issue by Mamedov1985** [mgp25/Instagram-API#190]
If i logout the users after each execution can i be considered a bot by instagram?
My idea was to create some php scritps wich one returning a XML.
But if i do like that i should login and logout every time.
What do you guys thinks about that?

**Comment by mkanker** [comment]
why login/logout every time? save that login data and use it every time is better I guess

**Comment by mgp25** [comment]
Do what @mkanker say, thats the correct way to do it
