### ISSUE TITLE
Correct $metadata example in wiki#uploading-photos ? (and $usertags in uploadPhoto() and media-edit())

### ISSUE THREAD

**Issue by iain-mildner** [mgp25/Instagram-API#1900]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

While trying to add usertags to an already uploaded image done via uploadPhoto() I  built the correct $mediaId using $mediaPk_$userId as mentioned in a previous message (thanks for the answer).

SO I want to us media->code() so went and read the Wiki document concerning $metadata:

https://github.com/mgp25/Instagram-API/wiki#uploading-photos

$metadata example is listed as:

```php
$metadata = 
    [
        'usertags' => 
            [
                'removed' => [],
                'in'      => 
                    [
                        'position' => 
                            [
                                0.47097720202318, // x position
                                0.46537839732884  // y position
                            ],
                            'user_id'  => 
                                [
                                    $userId
                                ]
                    ]
            ]
    ];
```
Is that _CORRECT_  as 'user_id' seems to be defined as an array ??? (I am not php savvy but want to transistion to using this library from another library... above this lib I have our imageDB which we use in our photography business that does lots of cool stuff ie. selecting which image to post next, generating tags and usr tags based off the image contents nada nada nada...)

Anyway should'nt the example in the Wiki be as follows:
 
```php
$metadata = 
    [
        'usertags' => 
            [
                'removed' => [],
                'in'      => 
                    [
                        'position' => 
                            [
                                0.47097720202318, // x position
                                0.46537839732884  // y position
                            ],
                            'user_id'  => $userId
                    ]
            ]
    ];
```

So trying to use either verson of $metadata throws an error using a VALID $userId:

RUN: print_r($metadata) UserId=[316252630]
```php
Array
(
    [usertags] => Array
        (
            [removed] => Array
                (
                )

            [in] => Array
                (
                    [position] => Array
                        (
                            [0] => 0.47097720202318
                            [1] => 0.46537839732884
                        )

                    [user_id] => 316252630
                )

        )

)
```
GOT: print_r($metadata)

---

```php
//$mediaId correctly built further up in the code and media-edit() works ok if only $captionText is changed

$UserId = 316252630;

$metadata = 
    [
        'usertags' => 
            [
                'removed' => [],
                'in'      => 
                    [
                        'position' => 
                            [
                                0.47097720202318, // x position
                                0.46537839732884  // y position
                            ],
                        'user_id'  => $UserId
                    ]
            ]
    ];

echo "\n\nRUN: print_r(\$metadata) UserId=[$UserId]\n";
print_r($metadata);
echo "GOT: print_r(\$metadata)\n\n";

$IgRespObj = $IgObj->media->edit($mediaId, $captionText, $metadata);

Error: media->edit(1752026784390821344_4218889336, DESCRIPTION 004, ...) - Invalid user entry in usertags array.
```

Could a $usertags example be added to the examples directory?

Anyway any help you gurus could shed on this would be much appreciated?

I will be making a paypal contribution once I get this code + post 1st comment code working (not an idle promise).

Thanks

**Comment by aitte2** [comment]
Hi again :)

1. Actually the wiki is completely wrobg baout the usertags metadata values. Correct format is in the source code:
https://github.com/mgp25/Instagram-API/blob/5838b24cf3a94ef4af2d56ddc8ee276e04ec414d/src/Request/Internal.php#L201-L203

2. Did you not understand the reply I gave in the previous ticket? You should not call `edit()`, you can give the usertags to `uploadPhoto()`: https://github.com/mgp25/Instagram-API/issues/1897#issuecomment-379050968

**Comment by iain-mildner** [comment]
@aitte2 the forum and project etiquette seems to be that new/old users should read the docs, read the wiki, try the examples and study the code.

It is @mgp25 's code and you seem to be one of the core team so you guys get to make the rules BUT  if you keep saying "have you read the wiki?" and i add a X when posting a questions saying YES i have and then find out the code snippet is wrong it helps no-one.

Will the WIKI be updated to reflect the correct behaviour? 

If you say read the wiki then a normal person would expect it to reflect the truth. You see the problem?

2. yes I saw your answer in #1897 and for certain tasks that is the way i will use it (in uploadPhoto()) but if I want to retag or tag older and already online images then media-edit() is the solution?

So I take a look at the file you mentioned: Instagram-API/src/Request/Internal.php and see the following code snippet:

```php
 switch ($targetFeed) {
            case Constants::FEED_TIMELINE:
                $request
                    ->addPost('caption', $captionText)
                    ->addPost('source_type', '4')
                    ->addPost('media_folder', 'Camera')
                    ->addPost('upload_id', $uploadId);
                if ($usertags !== null) {
                    $usertags = ['in' => $usertags]; // Wrap in container array.
                    Utils::throwIfInvalidUsertags($usertags);
                    $request->addPost('usertags', json_encode($usertags));
                }
                break;
```

so $usertags are allowed. Great. 

My question from above concerning "Invalid user entry in usertags array" is not answered. Is the $metatag array defined correctly and what does/can "Invalid user entry in usertags array" mean as I know 100% that the $UserId of 316252630 (username: andiveromagazine) is correct.

Does media->edit(..., ..., $metatag) work?    or are 'usertags' array only allowed in uploadPhoto() in 4.0 ?

**Comment by iain-mildner** [comment]
```php

    // login code etc. deleted for brevity

    $UserId = 316252630;

    $metadata = 
    [
        'usertags' => 
            [
                'removed' => [],
                'in'      => 
                    [
                        'position' => 
                            [
                                0.47097720202318, // x position
                                0.46537839732884  // y position
                            ],
                        'user_id'  => $UserId
                    ]
            ]
    ];

    // WORKS!   $IgInfoObj = $IgObj->timeline->uploadPhoto($ImgFile, ['caption' => $MsgText]);
    //
    // DOES NOT WORK!
    $IgInfoObj = $IgObj->timeline->uploadPhoto($ImgFile, ['caption' => $MsgText, 'usertags' => $metadata]);
```

Error: uploadPhoto($ImgFile, ...) - Invalid user entry in usertags array.

**Comment by mgp25** [comment]
Hello @iain-mildner, I am sorry about the mismatch about the code and the wiki. Unfortunately we don't have time (at least taking about myself) to update everything. As @aitte2 said, all correct documentation can be found in the code.

Nevertheless, I'm going to review the wiki and update the parts that are wrong/outdated.

If you give me a little time, I'll answer your questions.

Regards

**Comment by iain-mildner** [comment]
@mgp25 thank you so much. Much appreciated and I know your time is better invested in coding than documentation.

My question here and also the same issue #1824 seem to point to 1. user misunderstanding or 2. bug in $usertags

Could that be clarified as well?

Thanx

**Comment by aitte2** [comment]
@mgp25 @iain-mildner Hi, In case you didn't see my edited message above (https://github.com/mgp25/Instagram-API/issues/1900#issuecomment-379435469) I said that I have edited the wiki already. :) Thanks for bringing it to our attention.

About `uploadPhoto()`: In that one, you should provide `'usertags' => ...` in the format I quoted here in point 1: https://github.com/mgp25/Instagram-API/issues/1900#issuecomment-379435469

About `edit()`: When you want to delete/add tags to existing media, you should use the format in the fixed wiki post: https://github.com/mgp25/Instagram-API/wiki#edit-media

**Comment by halixness** [comment]
> @iain-mildner
> 
> This example works:
> 
> ```
> $metadata = [
>         'caption' => 'test',
>         'usertags' =>
>         [
>             [
>             'position' =>
>                 [
>                     0.5, // x position
>                     0.5  // y position
>                 ],
>                 'user_id'  => $userId
>             ]
>     ]
> ];
> 
> $photoFilename = 'test.jpg';
> $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename, ['targetFeed' => \InstagramAPI\Constants::FEED_TIMELINE]);
> 
> $i->timeline->uploadPhoto($photo->getFile(), $metadata);
> ```
> 
> As @aitte2 told in one of his previous comments [#1900 (comment)](https://github.com/mgp25/Instagram-API/issues/1900#issuecomment-379435469):
> 
> The format is documented in the code:
> 
> [Instagram-API/src/Request/Internal.php](https://github.com/mgp25/Instagram-API/blob/5838b24cf3a94ef4af2d56ddc8ee276e04ec414d/src/Request/Internal.php#L201-L203)
> 
> Lines 201 to 203 in [5838b24](/mgp25/Instagram-API/commit/5838b24cf3a94ef4af2d56ddc8ee276e04ec414d)
> 
>          /** @var array|null Array of usertagging instructions, in the format 
>           * [['position'=>[0.5,0.5], 'user_id'=>'123'], ...]. ONLY FOR TIMELINE PHOTOS! */ 
>          $usertags = (isset($externalMetadata['usertags']) && $targetFeed == Constants::FEED_TIMELINE) ? $externalMetadata['usertags'] : null; 
> `in` and `remove` is only for media edit. So your question:
> 
> > 1. user misunderstanding or 2. bug in $usertags
> 
> It is an user misunderstanding. Hope now is everything clear.
> 
> For the editing media, check the following example in the wiki (it has been updated): https://github.com/mgp25/Instagram-API/wiki#edit-media
> 
> @aitte2 thanks for updating the wiki. I'll send you a piece of 🍰 later 😄

@mgp25 Unfortunately, this example seems not working for a single timeline photo. 
Once I fill all the metadata fields (checked userId and also tried to put it hardcoded), I always get the error:
`Invalid usertag at index "0": Missing keys "position", "user_id" for user tag array`
I looked for this error message in the previous issues, and I also quoted this post, but no way to fix it.
I tried the quote thing, same error. I guess something change in metadata structure.
Thanks in advance.

**Comment by thevisuales** [comment]
> > @iain-mildner
> > This example works:
> > ```
> > $metadata = [
> >         'caption' => 'test',
> >         'usertags' =>
> >         [
> >             [
> >             'position' =>
> >                 [
> >                     0.5, // x position
> >                     0.5  // y position
> >                 ],
> >                 'user_id'  => $userId
> >             ]
> >     ]
> > ];
> > 
> > $photoFilename = 'test.jpg';
> > $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename, ['targetFeed' => \InstagramAPI\Constants::FEED_TIMELINE]);
> > 
> > $i->timeline->uploadPhoto($photo->getFile(), $metadata);
> > ```
> > 
> > 
> > As @aitte2 told in one of his previous comments [#1900 (comment)](https://github.com/mgp25/Instagram-API/issues/1900#issuecomment-379435469):
> > The format is documented in the code:
> > [Instagram-API/src/Request/Internal.php](https://github.com/mgp25/Instagram-API/blob/5838b24cf3a94ef4af2d56ddc8ee276e04ec414d/src/Request/Internal.php#L201-L203)
> > Lines 201 to 203 in [5838b24](/mgp25/Instagram-API/commit/5838b24cf3a94ef4af2d56ddc8ee276e04ec414d)
> > ```
> >      /** @var array|null Array of usertagging instructions, in the format 
> >       * [['position'=>[0.5,0.5], 'user_id'=>'123'], ...]. ONLY FOR TIMELINE PHOTOS! */ 
> >      $usertags = (isset($externalMetadata['usertags']) && $targetFeed == Constants::FEED_TIMELINE) ? $externalMetadata['usertags'] : null; 
> > ```
> > 
> > 
> > `in` and `remove` is only for media edit. So your question:
> > > 1. user misunderstanding or 2. bug in $usertags
> > 
> > 
> > It is an user misunderstanding. Hope now is everything clear.
> > For the editing media, check the following example in the wiki (it has been updated): https://github.com/mgp25/Instagram-API/wiki#edit-media
> > @aitte2 thanks for updating the wiki. I'll send you a piece of 🍰 later 😄
> 
> @mgp25 Unfortunately, this example seems not working for a single timeline photo.
> Once I fill all the metadata fields (checked userId and also tried to put it hardcoded), I always get the error:
> `Invalid usertag at index "0": Missing keys "position", "user_id" for user tag array`
> I looked for this error message in the previous issues, and I also quoted this post, but no way to fix it.
> I tried adding single quotes but nothing, same error. I guess something changed in metadata structure.
> Thanks in advance.

Could you make it work?
