### ISSUE TITLE
List of missing endpoints/changes

### ISSUE THREAD

**Issue by aitte2** [mgp25/Instagram-API#1904]
I've noticed some missing features and it's getting hard to remember them all, so perhaps this ticket is a good idea to track them? But I know how busy everyone is so this isn't expected to be implemented. It's just to track them.

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php

- Is missing something like `getArchivedStoriesFeed()` (a name suggestion to match `Timeline::getArchivedMediaFeed()`). It's the new endpoint where Instagram provides a feed of all of your past stories. Stories are nowadays auto-archived by Instagram. Getting this feed is important since you need to be able to get those archived IDs to add those stories to story highlights to republish them (via the Highlight module). Also, this new endpoint probably needs a `max_id` param when many archived stories exist.

https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php

- In `getFollowingRecentActivity()` there's some weird tokens in each activity. The real app seems to send those tokens with the requests. Example: User A (someone you follow) started following _private_ user B (someone they follow). If you tap the private user B in the app, in the "started following" message, you will see their timeline even though they are private. The activity token (or something else in the activity feed) is clearly being used by the app for authenticating to fetch timeline of the private user... 

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Collection.php

- **EDIT:FIXED.** No way to paginate in `getList()`, and probably also in `getFeed()`. So if a person has more than 20-ish collections or items in a collection, there's no way to get the rest. I think it may just need `max_id` param, since the response contains `next_max_id` (we need to update the "collection list" responses too btw). See: https://github.com/mgp25/Instagram-API/issues/1903

**Comment by valga** [comment]
@aitte2 

> There's some weird tokens in each activity.

The app uses `pk` and `tuuid` to log actions (e.g. clicks) in the news feed via `news/log` endpoint.

> I think it may just need `max_id` param.

Yep.

**Comment by lilsecboi** [comment]
For business insights we have /insights/account_organic_insights and /insights/media_organic_insights .. but this only gives like/comments/savecount/impressions but does not give profile views etc. website clicks, actions etc. 

anyone have any idea what endpoint i should try? I tried media_insights etc. but didnt work.

gonna try to do some MITM endpoint sniffing later on

**Comment by mgp25** [comment]
@aitte2 ping me at my mail when you are available.

**Comment by mgp25** [comment]
aitte2 

- About the `getArchivedStoriesFeed()` see [Highlight.php#L13](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Highlight.php#L13)

Any other question regarding to this issue?

**Comment by valga** [comment]
@mgp25 Stories archive is `archive/reel/day_shells/`, we don't have it yet.

**Comment by mgp25** [comment]
@valga can you point me where in the app is that?

**Comment by valga** [comment]
@mgp25 https://help.instagram.com/2011873942380990?helpref=search&sr=3&query=stories%20archive

There is a dropdown that switches between Posts archive and Stories achive.

**Comment by mgp25** [comment]
@valga thanks, going to add it in a few minutes. By the way, remember what we talked about these headers

```
X-IG-Bandwidth-Speed-KBPS: -1.000
X-IG-Bandwidth-TotalBytes-B: 0
X-IG-Bandwidth-TotalTime-MS: 0
```
We should add the remaining logic to match the app.

**Comment by valga** [comment]
@mgp25 Strictly speaking we don't have a proper emulation even for `X-IG-Connection-Speed` header: https://github.com/mgp25/Instagram-API/blob/0bff0e48a7cf8d1702c9c7a8f9147126ccd4bcd6/src/Request.php#L381

The app uses this header to measure CDN speed by counting only `.jpg` requests, so it should be `-1` during pre- and post-login flows until timeline feed is requested (and we have some images downloaded). That said, I don't see a reason to implement new headers in a right way while keeping "bad" old header.

Also, considering latest commit, I don't like that you reused `UserFeedResponse` and `AymfItem` models. The app uses dedicated models for stories archive.

**Comment by mgp25** [comment]
@valga oks! Do you recommend to roll back and create a dedicate model for the archived story?

**Comment by valga** [comment]
@mgp25 You don't have to roll back: just add 2 new models (one for stories archive response and one for stories archive item) and change your response class, like I did in 5a9080ba1148216efb3ff77c982b2e3e255939bb with collections.

**Comment by mgp25** [comment]
@valga I changed the response and models to have a dedicated one. Now it looks better 😄 

I guess everything in this issue is already solved by now. In case I am missing something, feel free to open it and point what is missing.

Regards
