### ISSUE TITLE
Spam parameter in regular response

### ISSUE THREAD

**Issue by jiomai** [mgp25/Instagram-API#1908]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

---
I am aware that setting the debug parameter to true gives more details about the errors. Therefore it is possible to see if an action is marked as "Spam". I would like to examine the "spam" result further. In my believe I assume that it is happening with some proxies, even though not spamming. 

Request: is it possible to have the spam parameter returned in the regular response, without the debug parameter turned on?
---

**Comment by mgp25** [comment]
Hello @jiomai,

If you write here the response, we'll be able to add it. And as you are saying, you are right. Instagram doesn't like proxies, better avoid them.

Regards

**Comment by jiomai** [comment]
Thank you for the fast reply!

{"message":"feedback_required","spam":true,"feedback_title":"You\u2019re Temporarily Blocked","feedback_message":"It looks like you were misusing this feature by going too fast. You\u2019ve been blocked from using it.\n\nLearn more about blocks in the Help Center. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.","feedback_url":"WUT","feedback_appeal_label":"Report problem","feedback_ignore_label":"OK","feedback_action":"report_problem","status":"fail"}

**Comment by mgp25** [comment]
Hello again @jiomai,

from the response, it seems you are doing requests very fast (or a lot of them), maybe because of a shared IP, I don't know.

I don't think this response will be added, because it can help spammers, and we do not support them.

Regards

**Comment by aitte2** [comment]
@jiomai This kind of solution is mentioned in the release notes: https://github.com/mgp25/Instagram-API/tree/v4.0.0 (read about getFullResponse there). First do https://github.com/mgp25/Instagram-API/blob/master/examples/exceptionDetailsExample.php to get the response from the exception. Then check if the response has a spam field with `->hasSpam()` (to know if it is valid to call the getter) and then use `->getSpam()`. Same for all other unmapped data.
