### ISSUE TITLE
Your version of Instagram is out of date

### ISSUE THREAD

**Issue by lucasexe** [mgp25/Instagram-API#1909]
Hello guys, 
I already read the rules to post (avoid to duplicate issues) but this problem is different from the others once the fixes always will different :/

today i tried log in my account but the instagram returned:
`{"message": "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.", "status": "fail", "error_type": "needs_upgrade"}`

Did anyone else had this problem today?

Other infos:
`const IG_VERSION = '27.0.0.7.97';
const VERSION_CODE = '84433655';
const IG_SIG_KEY = '109513c04303341a7daf27bb41b268e633b30dcc65a3fe14503f743176113869';`

`User-Agent: Instagram 27.0.0.7.97 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; pt_BR)`

thank you.

**Comment by mgp25** [comment]
Hello,

It seems you are not using this API or running modifications. The version the API has is still working perfectly. I  just tried a clean login and worked perfectly.

For further help, you will need to post full debug log (The debug log this API provides).

Regards
