### ISSUE TITLE
Login Error when in production

### ISSUE THREAD

**Issue by marceloferraz** [mgp25/Instagram-API#1913]
Question:

I've recently added the API to my project, always avoiding spam and bot behavior (using sleep() and other measures). All my tests on development ended up fine.
As soon as I deployed in Amazon AWS, I was unable to login because of the "sentry_block" error. As I haven't even had the chance to use the API while in production, what may be the reason of a sentry_block error?

As @SteveJobzniak mentioned in a previous issue #1243 : 'Your server is probably part of a IP network/host that has had serious spammers on it. Instagram has blacklisted its network/IP. This is unfortunate.'

You think this may be the cause? 
How does instagram blacklist the network, so I may try to fix this issue.
You see any hope in this scenario?

Thanks in advance

**Comment by marceloferraz** [comment]
It looks like all the popular host service IP's are banned. Amazon, Azure, Google, Digitalocean etc...
You have any information about that?

**Comment by mgp25** [comment]
Hello @marceloferraz,

> You think this may be the cause?

Yes.

>  How does instagram blacklist the network, so I may try to fix this issue.

A lot of people using them for spamming purposes or other illicit activities.

>  You see any hope in this scenario?

Use a non flagged IP.

> It looks like all the popular host service IP's are banned. Amazon, Azure, Google, Digitalocean etc...
>You have any information about that?

Since a lot of people are using them. Instagram blocked them.

The information posted by @SteveJobzniak in #1243 is right.

**Solution?**

Use other IP or server.

Regards

**Comment by marceloferraz** [comment]
@mgp25 Thanks for the quick response.

I'll try that.

**Comment by akoweb** [comment]
When I get a ping server, I see the Instagram server, but when I define the account, I'm having trouble? How can I make sure my server is blocked?
