### ISSUE TITLE
Forced 2FA because of suspicious login location

### ISSUE THREAD

**Issue by PublicStaticVoid2014** [mgp25/Instagram-API#1914]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
<?php
set_time_limit(0);
require_once 'vendor/autoload.php';
$ig = new \InstagramAPI\Instagram(true, true, [
        'storage'    => 'mysql',
        'dbhost'     => 'localhost',
        'dbname'     => 'name',
        'dbusername' => 'user',
        'dbpassword' => 'pass',
]);
$ig->login($argv[1], $argv[2]);
?>
```

Error Log/var_dump:

```php
POST:  https://i.instagram.com/api/v1/accounts/login/              
DATA: signed_body=25ef66c2e9352e064e7e405c6c4b493907de69cf16b89eb2ded49d66c8131bc9.{"phone_id":"0e7c5ebd-1fc7-4428-beee-101b6c361ed5","_csrftoken":"nGi9FgD5YKwgaW71tCOiKMKpvXqYDxgA","username":"__171102__","adid":"4f86d44d-4f4e-46d5-a3e2-28c2d371ceac","guid":"b507550d-af15-459e-890f-49b0a6719941","device_id":"android-3bd8e524a46501fb","password":"nwza2552","login_attempt_count":"0"}&ig_sig_key_version=4
← 400    310B                    
RESPONSE: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/3980173210/G2u56yCoIn/", "api_path": "/challenge/3980173210/G2u56yCoIn/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}

PHP Fatal error:  Uncaught InstagramAPI\Exception\ChallengeRequiredException: InstagramAPI\Response\LoginResponse: Challenge required. in /var/www/ig-api/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:189
Stack trace:                     
#0 /var/www/ig-api/vendor/mgp25/instagram-php/src/Client.php(546): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/ig-api/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /var/www/ig-api/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /var/www/ig-api/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('__171102__', 'nwza2552', false, 1800)
#4 /var/www/ig-api/login.php(3): InstagramAPI\Instagram->login in /var/www/ig-api/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php on line 189
```

---
### Describe your issue

This is some kind of security mechanism that Instagram imposed to prevent strange login locations, and is a different kind of 2FA.
In the server response there is a "url" and "api_path" that will open a page and ask the user to send a security code and verify the login using the 6-digit code sent by email
Perhaps the library can also catch that response, request an email and validate the session using the code?
Thanks!

**Comment by ajaydesai** [comment]
@PublicStaticVoid2014 Facing the same issue from this morning

**Comment by ajaydesai** [comment]
@PublicStaticVoid2014 did you find any solution? facing the same issue.

**Comment by mgp25** [comment]
Hello,

It is not a second factor authentication. It is just a challenge to verify yourself for suspocious activities or IP related. It is exapleined in the FAQ: https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean

Regards
