### ISSUE TITLE
I AM BANNED THANKS

### ISSUE THREAD

**Issue by whatsappapi** [mgp25/Instagram-API#1915]
{
  "message" : "Sorry, there was a problem with your request.",
  "status" : "fail",
  "error_type" : "sentry_block"
}

I am not spammer. I am try to login my account 3 times challenge and after this response. Thanks for cause of ban.

**Comment by herrenail** [comment]
I am getting this message too.
Maybe there seems to be a problem with the login api.

**Comment by mgp25** [comment]
@whatsappapi We don't support people with your IQ.
