### ISSUE TITLE
How can I get a user profile in Realtime?

### ISSUE THREAD

**Issue by wolrd** [mgp25/Instagram-API#1917]
How can I get a user profile?
```
$rtc->on('thread-item-created', function ($threadId, $threadItemId, \InstagramAPI\Response\Model\DirectThreadItem $threadItem) {
    print_r(PROFILE);
});
```
I do not want to use 'getInfoById'.
`$response = $apiAccount->people->getInfoById($userId);
`
On version 3.0 I could get a user profile.

**Comment by valga** [comment]
@wolrd Well, we have no control over realtime payload, so if it doesn't have profile info, we can do nothing about that.

So you should use `People::getInfoById()` or `Direct::getThread()` to obtain profile info.

**Comment by wolrd** [comment]
@valga I use:
$threadItem->getProfile()
Profile is empty. Why?
