### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by cyberprosconsulting** [mgp25/Instagram-API#1919]
api is not installing directories are not created getting the following error

Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead. Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by aitte2** [comment]
That error is not related to this library. We do not use php-sdk-v4 or guzzle/guzzle.

https://github.com/mgp25/Instagram-API/blob/42460827d5fa802452e2e0f92d786686cdf6636a/composer.json#L41-L60

Try deleting your `composer.lock` file and running `composer update -o`. Either way, not our problem.
