### ISSUE TITLE
InstagramRegistration not work at all

### ISSUE THREAD

**Issue by BRAD-BIT** [mgp25/Instagram-API#192]
i tried to register using the following code
```php
<?php
require_once '../src/InstagramRegistration.php';
$debug = false;

$r = new InstagramRegistration($debug);
$username='BRAD_BIT9454';
$password='moha4422med';
$email='eng.moham@gmail.com';

$result = $r->createAccount($username, $password, $email);
print_r($result);
if (isset($result['account_created']) && ($result['account_created'] == true)) {
    echo 'Your account was successfully created! :)';
}
?>
```

without changing any thing in InstagramRegistration and make sure that BRAD_BIT9454 not taken but no thing happen 
any help please?

**Comment by mgp25** [comment]
@BRAD-BIT if you dont post any debug log, there is no support

Regards

**Comment by BRAD-BIT** [comment]
[logs.docx](https://github.com/mgp25/Instagram-API/files/287692/logs.docx)
 that is my bebug log files after run the above script on the localhost

**Comment by Taytus** [comment]
I can confirm that the registration is working perfectly.
