### ISSUE TITLE
Video post disappears after 1 second of upload 

### ISSUE THREAD

**Issue by Farzadpro** [mgp25/Instagram-API#1921]
Hi 
Im having a very weird problem with uploading a video, Ive used the example codes exactly but the problem is that after my video uploaded to page, after 1 seconds it disappears from my instagram page without any notice on page or error on response of script 
The script output is : 

  | POST:  https://i.instagram.com/api/v1/feed/timeline/
-- | --
  | DATA: is_prefetch=0&feed_view_info=&seen_posts=&phone_id=baad00e8-89cb-48d8-89e5-b20a5a93be1c&reason=pull_to_refresh&battery_level=100&timezone_offset=0&_csrftoken=iIo0vAvyRz7EMsXIef2B72QfQXEeLJLS&is_pull_to_refresh=1&_uuid=76d65032-450c-4f9e-bdc2-ad5ee96f79e5&is_on_screen=true&unseen_posts=&is_charging=1&is_async_ads_double_request=0&is_async_ads=0&will_sound_on=1&is_async_ads_rti=0
  | ← 200 	 249B
  | RESPONSE: {"num_results": 0, "more_available": false, "auto_load_more_enabled": true, "feed_items": [], "is_direct_v2_enabled": true, "next_max_id": null, "view_state_version": "1523965687776-3b3495ee7d9e4b56a85f48ebda5c6a5d", "client_feed_changelist_applied": false, "status": "ok", "_messages": [{"time": 1523965485.55, "key": "update_push_token"}]}
  |  
  | <br />
  | <b>Notice</b>:  Use of undefined constant PHP_WINDOWS_VERSION_MAJOR - assumed 'PHP_WINDOWS_VERSION_MAJOR' in <b>/home/admin/domains/mgp25/instagram-php/src/Request/Internal.php</b> on line <b>1842</b><br />
  | GET:  https://i.instagram.com/rupload_igvideo/1523965691968_0_-2127780076?target=ATN
  | → 0B
  | ← 200 	 12B
  | RESPONSE: {"offset":0}
  |  
  | POST:  https://i.instagram.com/rupload_igvideo/1523965691968_0_-2127780076?target=ATN
  | → 171.98kB
  | ← 200 	 39B
  | RESPONSE: {"xsharing_nonces": {}, "status": "ok"}
  |  
  | GET:  https://i.instagram.com/rupload_igphoto/1523965691968_0_1682324670
  | → 0B
  | ← 200 	 12B
  | RESPONSE: {"offset":0}
  |  
  | POST:  https://i.instagram.com/rupload_igphoto/1523965691968_0_1682324670
  | → 19.44kB
  | ← 200 	 69B
  | RESPONSE: {"upload_id": "1523965691968", "xsharing_nonces": {}, "status": "ok"}
  |  
  | POST:  https://i.instagram.com/api/v1/media/configure/?video=1
  | DATA: signed_body=4958ddf91ad23117117ac3701b70678cf6f95b2afa9d20e422e4069a8270398f.{"device":{"manufacturer":"samsung","model":"SM-G935F","android_version":"23","android_release":"6.0.1"},"length":"6.8","filter_type":"0","_csrftoken":"iIo0vAvyRz7EMsXIef2B72QfQXEeLJLS","source_type":"4","video_result":"","_uid":"6902632143","_uuid":"76d65032-450c-4f9e-bdc2-ad5ee96f79e5","extra":{"source_width":720,"source_height":720},"caption":"this is test for insta vid","audio_muted":"false","poster_frame_index":"0","upload_id":"1523965691968"}&ig_sig_key_version=4
  | ← 200 	 1.37kB
  | RESPONSE: {"media": {"taken_at": 1523965695, "pk": 1759474213130101216, "id": "1759474213130101216_6902632143", "device_timestamp": 1523965691968, "media_type": 2, "code": "Bhq6HmJFGHg", "client_cache_key": "MTc1OTQ3NDIxMzEzMDEwMTIxNg==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 720, "height": 720, "url": "https://scontent-lhr3-1.cdninstagram.com/vp/5c10010bfa2d75eac1b9d2a1b4c1624c/5AD86C72/t51.2885-15/e35/30079244_2058909787463775_1797423382216572928_n.jpg?ig_cache_key=MTc1OTQ3NDIxMzEzMDEwMTIxNg%3D%3D.2"}, {"width": 240, "height": 240, "url": "https://scontent-lhr3-1.cdninstagram.com/vp/8c95f3c6036732ff6b4217c63f30da9a/5AD82CB1/t51.2885-15/s240x240/e35/30079244_2058909787463775_1797423382216572928_n.jpg?ig_cache_key=MTc1OTQ3NDIxMzEzMDEwMTIxNg%3D%3D.2"}]}, "original_width": 720, "original_height": 720, "video_versions": [{"type": 101, "width": 640, "height": 640, "url": "https://scontent-lhr3-1.cdninstagram.com/vp/ab38424ba8a793f2418239fe5988a695/5AD87500/t50.2886-16/30720883_180504479428333_5897258373007856686_n.mp4", "id": "17920176346080524"}, {"type": 103, "width": 480, "height": 480, "url": "https://scontent-lhr3-1.cdninstagram.com/vp/4243fa533bd700aa22cf916dec7d38ed/5AD7E379/t50.2886-16/30522342_439765586482227_5001515793033694490_n.mp4", "id": "17925415849098789"}, {"type": 102, "width": 480, "height": 480, "url": "https://scontent-lhr3-1.cdninstagram.com/vp/4243fa533bd700aa22cf916dec7d38ed/5AD7E379/t50.2886-16/30522342_439765586482227_5001515793033694490_n.mp4", "id": "17925415849098789"}], "has_audio": true, "video_duration": 6.0, "user": {"pk": 6902632143, "username": "iranbestvideo", "full_name": "Video", "is_private": false, "profile_pic_url": "https://scontent-lhr3-1.cdninstagram.com/vp/f17e1275a70fc32e93cbf434ddc32bcd/5B6CCC7A/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "has_anonymous_profile_picture": true, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "is_unpublished": false, "allowed_commenter_type": "any"}, "can_viewer_reshare": true, "caption": {"pk": 17922783538121634, "user_id": 6902632143, "text": "this is test for insta vid", "type": 1, "created_at": 1523965696, "created_at_utc": 1523965696, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 6902632143, "username": "iranbestvideo", "full_name": "Video", "is_private": false, "profile_pic_url": "https://scontent-lhr3-1.cdninstagram.com/vp/f17e1275a70fc32e93cbf434ddc32bcd/5B6CCC7A/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "has_anonymous_profile_picture": true, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "is_unpublished": false, "allowed_commenter_type": "any"}, "did_report_as_spam": false, "media_id": 1759474213130101216}, "caption_is_edited": false, "comment_likes_enabled": false, "comment_threading_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "preview_comments": [], "comment_count": 0, "photo_of_you": false, "can_viewer_save": true, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImI0YzUwMzJjNzVjYTQ4ZGViNWYzYzM3ZWE5MDdiNjVmMTc1OTQ3NDIxMzEzMDEwMTIxNiIsInNlcnZlcl90b2tlbiI6IjE1MjM5NjU2OTY2NjN8MTc1OTQ3NDIxMzEzMDEwMTIxNnw2OTAyNjMyMTQzfDlmMjBlYzA2Y2ZiNzhkZjE3ZjRkMzRhN2JmODM2MjY3M2JjMTVkOTZiZWI4YWNkYmMxNDdmZGMyOTVkOTU5MzkifSwic2lnbmF0dXJlIjoiIn0="}, "upload_id": "1523965691968", "status": "ok"}
  |  
  |

**Comment by aitte2** [comment]
Instagram auto-deletes media a few seconds after upload in these cases:

1. New account which is posting media too fast.
2. A spammer.

**Comment by aitte2** [comment]
I also see you're running an old library release which is causing `Use of undefined constant PHP_WINDOWS_VERSION_MAJOR` in your log. Run `composer update -o` to fix that.
