### ISSUE TITLE
Where can I find "vendor/autoload.php" ?

### ISSUE THREAD

**Issue by tonixx** [mgp25/Instagram-API#1922]
Hi,

I've looked everywhere in the repository and I can't seem to find the required file "vendor/autoload.php". This file is used in all of the examples

Thx!

**Comment by tonixx** [comment]
Thx but this doesn't seem to solve it. In the post that you've suggested it says autoload.php can be replaced by init.php. I can't find init.php in the Instagram-API repository

**Comment by ibrunotome** [comment]
You will never find any file of vendor folder in any repository. Did you know how to use composer?

**Comment by aitte2** [comment]
https://github.com/mgp25/Instagram-API#installation

https://github.com/mgp25/Instagram-API#using-composer

https://github.com/mgp25/Instagram-API#i-dont-have-composer

https://github.com/mgp25/Instagram-API#warning-about-moving-data-to-a-different-server
