### ISSUE TITLE
Can't login via the API

### ISSUE THREAD

**Issue by tonixx** [mgp25/Instagram-API#1925]
Hi guys,

I've managed to install the API on my Linux server. I've entered my login details in examples/uploadPhoto.php and executed it via the command line. However, I get a login error:

← 400    108B
RESPONSE: {"message": "Sorry, there was a problem with your request.", "status": "fail", "error_type": "sentry_block"}
Something went wrong: InstagramAPI\Response\LoginResponse: Sorry, there was a problem with your request.

I mention that I've logged in via the browser using the same login details and it works fine.

Do you know how I can fix this?

Thx in advance!

**Comment by mgp25** [comment]
F.A.Q.: https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-sentry_block-error-mean

If you are able to log in using API in localhost, then the IP of your server is flagged.

Anyway, not API issue. Please search before opening an issue.

Regards

**Comment by andreescocard** [comment]
@Feelingly same question

**Comment by szokeptr** [comment]
Try deactivating the account, then reactivate after 3-4 hours and try logging in again. Your server must have a clean/trusted IP for this to work.
