### ISSUE TITLE
LoginResponse: Challenge required

### ISSUE THREAD

**Issue by saeideros** [mgp25/Instagram-API#1926]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---

Hi.
A few days ago I receive a "Suspicious Login Attempt" report and because that wasn't me I select "This Wasn't Me". After that I receive "Challenge required" when i try to login.
To confirm that this was me I try to login whit my server ip and confirm challenge manually. But it doesn't work.
I know you remove the future of challenge confirmation because of bad peoples who use this script to spamming. But would you be kind enough to help me to solve my problem, Please?

**Comment by mgp25** [comment]
Hello @saeideros,

It is explained in the F.A.Q.: https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean

Regards

**Comment by saeideros** [comment]
Thanks for comment.
I already try this ways but didn't help.

**Comment by mgp25** [comment]
If it keeps saying that using the API, it is IP issue. Not API issue.

Regards

**Comment by saeideros** [comment]
Woops
Yes. The problem was my ip. I changed it and every thing work like a charm.
Thanks again.
