### ISSUE TITLE
can be support instagram verification code?

### ISSUE THREAD

**Issue by MahdiPishguy** [mgp25/Instagram-API#1928]
Hi all. i have a question about get verify code by instagram on login to check user, this library can be get this options from instagram?

thanks

**Comment by mgp25** [comment]
Hello @MahdiPishguy,

We won't implement that functions in the API. It is explained in the F.A.Q.: https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean

Nevertheless, you can do your own implementation

Regards
