### ISSUE TITLE
Instagram Live - step between create and start

### ISSUE THREAD

**Issue by HarryRowolt** [mgp25/Instagram-API#1930]
Hey all.
In livebroadcast the 2 main calls are:
   // Tell Instagram that we want to perform a livestream.
    $stream = $ig->live->create();
    $broadcastId = $stream->getBroadcastId();
    $ig->live->start($broadcastId);

How can I get some time in between the ‘create’ and the ‘start’?
Usecase: I generate the RTMP and broadcast id and immediately the stream is live. But I need some moments to enter the broadcast Id in OBS e.g.  

I would love to have either 30-60 sec. or a stream start button. (Stop Button would be nice too...)
Any ideas? Thank you all.

**Comment by mgp25** [comment]
Hello,

Yes, it is possible to add some delay (I guess), but that is a programming issue not API one.

You can find PHP documentation here: https://secure.php.net/manual/en/index.php also google is your friend :)

Regards

**Comment by HarryRowolt** [comment]
Thanks, I used sleep() but it delayed the entire output no matter where I put it.

**Comment by coloop** [comment]
Hi Harry

Could you please help me about stream key ?

i got:

rtmps://live-upload.instagram.com:443/rtmp/17942106283057030?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfbGl2ZWRhc2giOnsibGl2ZWRhc2hfbW9kZSI6InByaW1hcnkifSwiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6IjEifSwiaWdfbGl2ZV9lbmFibGVfcG9wX3ByaW1pbmciOnsiZW5hYmxlZCI6IjEifSwiaWdfbGl2ZV9pbmdlc3Rpb25fdXBkYXRlc190aHJpZnRfZW5hYmxlIjp7ImVuYWJsZWQiOiIxIn19fQ%3D%3D\u0026a=AThbalbgmTGKYzj6

that i don't know which part is stream key for using in OBS.

tnx

**Comment by HarryRowolt** [comment]
all the stuff behind /rtmp/ 


Best Christian 



-----Original Message-----

**Comment by ttvd94** [comment]
Have you succeed @HarryRowolt ?
