### ISSUE TITLE
Is there another Instagram api update??

### ISSUE THREAD

**Issue by herrenail** [mgp25/Instagram-API#1933]
I have used ver. 4.1 Instagram-API ( updated 2 days ago )
​
I was using it well, but from about 10 hours ago my account suddenly started to lock up with checkpoints.(when I log in)
Could you check if there is another Instagram update?
​
Thanks.

**Comment by mgp25** [comment]
Hello,

Current version is okay. Checkpoint issue appears when you are log in to your account from a different location, or the IP is flagged.

You can read more information about the Checkpoint in the [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ):

- [What does "checkpoint_required" error mean?](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean)
