### ISSUE TITLE
ploblem login via fb

### ISSUE THREAD

**Issue by shadowc0de** [mgp25/Instagram-API#1935]
how to use format login parameter correctly?
Warning: mkdir(): Invalid path in C:\xampp\htdocs\mgp25\instagram-php\vendor\mgp25\instagram-php\src\Utils.php on line 899

Warning: chmod(): Invalid argument in C:\xampp\htdocs\mgp25\instagram-php\vendor\mgp25\instagram-php\src\Utils.php on line 900
Something went wrong: The "C:\xampp\htdocs\mgp25\instagram-php\vendor\mgp25\instagram-php\src/../sessions//EAABxxxZDZD/" folder is not writable.

**Comment by mgp25** [comment]
We don't support facebook login yey.

Regards
