### ISSUE TITLE
Respon json

### ISSUE THREAD

**Issue by azizul-hakim-x** [mgp25/Instagram-API#1936]
I tried to show the story user feed, and json's response did not show followed and followed, and I also asked how to display the user self feed, my question:

1. display json responses followed and following
2. displays the user's media feed response
3. how can i get access token from user already login

thank you

**Comment by mgp25** [comment]
Hello,

In order to get any property, make sure it is set. 

Here is an example that shows how to access values: [accesingValues.php](https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php)

- All responses can be found here: [/Response](https://github.com/mgp25/Instagram-API/tree/master/src/Response)


3. Can you explain what access token are you referring to?

**Comment by azizul-hakim-x** [comment]
thank you all it's been running well on localhost, but i have trouble when the fire is uploaded to the website and when login my account always get the challenge account information and some times like that result i can not enter my account through my domain I already use proxy but the result remains the same , "InstagramAPI\Response\LoginResponse: Sorry, there was a problem with your request."

**Comment by aitte2** [comment]
Try to copy `vendor/mgp25/instagram-php/sessions/` from your local machine to the same location on the server. That way you will reuse your working local session instead of making a new login attempt.

**Comment by azizul-hakim-x** [comment]
yes i've tried it and managed to login, but i need an online session so everyone can login his instagram account on my website

**Comment by mgp25** [comment]
@azizul-hakim-x what is the website you are using with the API?

**Comment by azizul-hakim-x** [comment]
i apologize, for not giving my website information, because my web is being exposed suspend for 1 month, this is my domain hcr-tech.com, i installed api instagram mgp25

but for the problem, the login I have solved is indeed because my private ip does not support for traffic to user login to instagram
