### ISSUE TITLE
Turn On Post Notification

### ISSUE THREAD

**Issue by BonsyBoing** [mgp25/Instagram-API#1939]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hello

I have been using the Push client created by @valga  and was wondering if it would be possible to implement the ability to turn on post notifications for a certain user?

![image](https://user-images.githubusercontent.com/18429405/39152260-10adb90a-4748-11e8-81f4-6be295aa3171.png)

**Comment by valga** [comment]
@BonsyBoing https://github.com/mgp25/Instagram-API/issues/1745#issuecomment-352365751
