### ISSUE TITLE
Delete Comment

### ISSUE THREAD

**Issue by Mamedov1985** [mgp25/Instagram-API#194]
How can i delete a comment that i did?
I'm using the command "comment($mediaId, $commentText)" to do the comment, but it did not return the commentId so i cannot use the command "deleteComment($mediaId, $captionText, $commentId)".

Where do i find the parameters $captionText and  $commentId ???

That's the result that i get in "comment($mediaId, $commentText)":

`<comment>
<status>Active</status>
<media_id>1.2610004326299E+18</media_id>
<text>OK</text>
<created_at>1464561980</created_at>
<user>...</user>
<content_type>comment</content_type>
<created_at_utc>1464590780</created_at_utc>
<pk>1.7856598879052E+16</pk>
<type>0</type>
</comment>`

Another doubt why some keys are coming with exponencial notation like the media_id ???

**Comment by mgp25** [comment]
Get info of the media and it will return the data of the comments too.

Regards

**Comment by Mamedov1985** [comment]
Same result did not return the $captionText and $commentId.

**Comment by mgp25** [comment]
There is a specific function for media comments

**Comment by Mamedov1985** [comment]
I'm really lost here.
I've tried the specific function too: getMediaComments($mediaId)
But still cant find this two parameters $captionText and $commentId

**Comment by Mamedov1985** [comment]
@mgp25 i found the error.
There an error in the function.

The right way is:
`  public function deleteComment($mediaId, $commentId)
  {
      $data = json_encode([
        '_uuid'          => $this->uuid,
        '_uid'           => $this->username_id,
        '_csrftoken'     => $this->token,
        'media_id'   	 => $mediaId,
    ]);

      return $this->request("media/$mediaId/comment/$commentId/delete/", $this->generateSignature($data))[1];
  }`

And another strange error is that all my arrays are returning exponential values in the ids like the exemple: [pk] => 1.7856601951051E+16
I have tried different server but still have the same result.
Do you have any idea how to solve that?

**Comment by thinhpc** [comment]
the private api comment almost return wrong comment pk.
It return pk like this: [pk] => 1.7856601951051E+16. And we can't get the exactly pk value. So sometime it true, sometime it wrong. This problem haven't has a solution

**Comment by mgp25** [comment]
Thats mostly because you are running it in a webserver or similar

**Comment by Mifody** [comment]
@thinhpc your php version less than 5.4
see links
http://stackoverflow.com/questions/2907806/handling-big-user-ids-returned-by-fql-in-php
https://gist.github.com/bcantoni/2162791

**Comment by thinhpc** [comment]
thanks  @Mifody !

It's fixed for me with the change:
find the precision value in your php.ini and change it to precision = 20.

My php version is 5.6 and this work like a charm.

Thanks you all!
