### ISSUE TITLE
 Something went wrong: You must have FFmpeg to process videos...

### ISSUE THREAD

**Issue by coloop** [mgp25/Instagram-API#1941]
hi
there is an error:

Something went wrong: You must have FFmpeg to process videos. Ensure that its binary-folder exists in your PATH environment variable, or manually set its full path via "\InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/home/exampleuser/ffmpeg/bin/ffmpeg';" at the start of your script. 

i use wamp64 and http://ffmpeg.zeranoe.com/builds/ installed!
also Environment variable set.

i can run ffmpeg command without any problem in CMD.

help please
tnx

**Comment by aitte2** [comment]
Hi. How did you fix it?

**Comment by coloop** [comment]
@aitte2 
hi
i have a mistake in defining Environment variable.

**Comment by aitte2** [comment]
@coloop Oh ok. Thanks for letting us know. :)
