### ISSUE TITLE
Improve uploadAlbum example to make all files valid before upload

### ISSUE THREAD

**Issue by dunky11** [mgp25/Instagram-API#1942]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Hello, ive used the below functions with great success, it validates your files to be in the correct format before uploading.

```php
    $ig->timeline->uploadPhoto( $photo->getFile(), ['caption' => $caption ]);             
    $ig->timeline->uploadVideo( $video->getFile(), ['caption' => $caption ]);
```

However i have trouble with the uploadVideo function like in the example:
```php
    $ig->timeline->uploadAlbum( $media, ['caption' => $caption ]);
```

it gives me errors, because the format of my files is not correct. Is there any way to format
the files in `$media` before uploading? Maybe call `getFile()` on each photo/video in the array?

Thanks for any answers in advance!

**Comment by aitte2** [comment]
I haven't read the details but I know this is in the project tracker:

https://github.com/mgp25/Instagram-API/projects/4

(See the Minor column, under "Update uploadAlbum example to describe how to give all files the same aspect ratio"). Looks like it never got done.

**Comment by dunky11** [comment]
thank you very much, got it working by making it like in the example

**Comment by aitte2** [comment]
That is good news. :) But I am reopening this to track discussion of a clean final solution to update the example file.

**Comment by SteveJobzniak** [comment]
@dunky11 The code you were linked to isn't complete. But the example has now been rewritten to the proper method. Download the latest `dev-master` code (or just get this exact file): https://github.com/mgp25/Instagram-API/blob/master/examples/uploadAlbum.php - it has the full code necessary to create correct albums where all media files are validated + become the same aspect ratio (that step is necessary for good looking albums without getting stretched images/videos in Instagram's web viewer).
