### ISSUE TITLE
Missing child comments from "getComments()"

### ISSUE THREAD

**Issue by forcemagic** [mgp25/Instagram-API#1943]
> **EDIT:** I'm very sorry for the inconvenience, I was using version 3.1 of this library which is clearly outdated. Sorry again!

# The Problem

My suspicion below was indeed correct. The `can_support_threading` is not sent to the server. This is my log with debug mode enabled:

```
GET:  https://i.instagram.com/api/v1/media/1553684049406923640_1244902698/comments/?ig_sig_key_version=4
→ 0B
← 200 	 1.66kB
RESPONSE: <very long json that is incomplete>
```

**Comment by aitte2** [comment]
No problem. Happy you solved it and updated the topic. :)
