### ISSUE TITLE
Posts You've Liked

### ISSUE THREAD

**Issue by instapost** [mgp25/Instagram-API#1944]
### Purpose of your issue?
- [x] Feature request (request for new functionality)

----

in instagram app can Access to last/recent  Posts(media) liked. [Instagram Help Center](https://help.instagram.com/367550509992787)

Screenshot on android:

<img src="http://uupload.ir/files/kd3t_photo_2018-04-24_11-03-32.jpg" width=200>

please add this.

and Is it possible to check a post as before i liked ? To show the heart icon in my App for a post ☺️ (That is, if I already liked a post,  return true(function))

**Comment by mgp25** [comment]
Please search before opening an issue. Next time we will close it directly.

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Media.php#L210

Regards

**Comment by instapost** [comment]
@mgp25  function getLikedFeed return all list users liked a post
but "Posts You've Liked" return all post me liked!!!
