### ISSUE TITLE
Report as spam or inappropriate

### ISSUE THREAD

**Issue by brunopiaui** [mgp25/Instagram-API#1947]
Hello,

Is there a method in the API to report a post or comment as spam or inappropriate?

I looked at git and the API code but did not find it. I only found one method to tell if a comment was reported as spam.

If it is not implemented, could you tell me how you could do it?

Thanks!!

**Comment by aitte2** [comment]
Go to the src/Request folder and run a search for "report".

Only functions I can find:
```
Discover.php
45:     * Report media in the Explore-feed.
52:     * @return \InstagramAPI\Response\ReportExploreMediaResponse
54:    public function reportExploreMedia(
58:        return $this->ig->request('discover/explore_report/')
62:            ->getResponse(new Response\ReportExploreMediaResponse());
```

Looks like other report functions are not available.

**Comment by mgp25** [comment]
Hello,

Report media as spam will be added in a couple minutes, nevertheless report media as inappropriate won't be added since it redirects to the Instagram web where they advise the user which option to select and why.

Regards

**Comment by aitte2** [comment]
@mgp25 Great! :D I think you missed the report comment feature he also asked? Swipe left on a comment and it has a report button with "Report as: 1. Spam or Scam. 2. Abusive Content"

**Comment by mgp25** [comment]
Hello,

Instagram takes "Spam or scam" both as `reason = 1`, that's why you will see I didn't add a `$reason` argument.

```
$ig->media->reportComment($mediaId, $commentId);
```

**Comment by siyavash4812** [comment]
@mgp25 Can you please also add the option to report a user as spam? thank you

**Comment by SteveJobzniak** [comment]
@siyavash4812 Good suggestion. `$ig->people->report($userPk)` would fit perfectly.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/commit/139e9b736ebca6196c438f217dec34c90945ec00

**Comment by aitte2** [comment]
Awesome work :D Hope you are happy @brunopiaui @siyavash4812

**Comment by brunopiaui** [comment]
It got better than expected!!

Thanks to all!!!!!!

🤘
