### ISSUE TITLE
pass data between php files!

### ISSUE THREAD

**Issue by ehsan1526** [mgp25/Instagram-API#1951]
Hi

I have a php file : 'live.php' that first logged in then started live broadcast!
And also i have a php file : 'comment.php' which task is comment on live video!

You know if we want to comment on live, must use comment() function that has to argument:

1.broadcast id***
2.comment text

In other side a broadcast id maked in first php file(live.php) and i needed in second php file (comment.php)
and any other arguments and parameters which needed to pass for other functions.

i'm using cmd not browser!
maybe my question is stupid but its my challenge.

if it was possible i could run it on browser but i don't have any idea for running on command!

thank you

**Comment by ehsan1526** [comment]
@mgp25 
Why my issue's closed without any answer ?!

**Comment by SteveJobzniak** [comment]
@ehsan1526 Because tickets are for about serious bugs/missing Instagram features, not about how to code stuff. :\
