### ISSUE TITLE
How to check if a post is already commented by me

### ISSUE THREAD

**Issue by sehgal10** [mgp25/Instagram-API#1952]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

How can I get if the post has already been commented by me or not. E.g. for a post like, we have has_liked attribute to do the work. Do we have anything like has_commented or any workaround?

**Comment by sehgal10** [comment]
@mgp25 I'll be happy to keep this closed or invalid. Can you please help me to know the reason for invalid. So I'll be careful to put up the correct question. Sorry if it is avoiding any of the post rules.

Thanks,
Sukhwinder

**Comment by mgp25** [comment]
Hello @sehgal10,

technically there is nothing wrong with this issue but the fact it is a programming issue and not an API one. If we allow people to ask programming issue, this issue tracker will be flooded with programming issues and we need to focus strictly in API issue.

About your question, you should get comments `getComments($mediaId)`, from the function in [Media.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Media.php), you will see that the response will be `MediaCommentsResponse`, which is the following class [MediaCommentsResponse](https://github.com/mgp25/Instagram-API/blob/master/src/Response/MediaCommentsResponse.php).

See `MediaCommentsResponse` and its properties, that is what you get from Instagram server, from this response you need to code the solution you want.

Regards

**Comment by sehgal10** [comment]
Thats a great help and guidance. Thanks a lot @mgp25 

Cheers!

**Comment by mgp25** [comment]
You are welcome. If you have any API issue feel free to open one. When we have some time we will make an extensive guide on how to use the API.

Regards

**Comment by aitte2** [comment]
@sehgal10 Just remember that a post can have 5000 comments and you would have to spend all day loading those. There is no official API way to check if you have commented. So I recommend making your own database with that info every time you send a comment, so you don't have to scan comments.

I just thought about something: I really hope this is not for some botting thing to scan to see if you have already spammed that guy :P
