### ISSUE TITLE
Strange code in Instagram.php

### ISSUE THREAD

**Issue by Zazo0** [mgp25/Instagram-API#1953]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

`in_array($this->experiments[$experiment][$param], ['enabled', 'true', '1'])`
Does response from Instagram may contain both as `enabled`, `true` and `1`? What about to convert these multiple values to any single value?

**Comment by mgp25** [comment]
Hello @Zazo0,

Yes, it can contain different values to tell if an experiment is enabled. 

> What about to convert these multiple values to any single value?

It is something we don't control. The response comes from Instagram server and we are simply checking wether the experiment is enabled by checking if it has any of those values (`['enabled', 'true', '1']`).

Regards
