### ISSUE TITLE
How to get new/lost followers of a user

### ISSUE THREAD

**Issue by miukal** [mgp25/Instagram-API#1954]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Some apps have the function like 'new/gained followers' or 'lost followers'.
Like there apps/web --
How did they do that?
I tried some methods:

1. get all followers list in different time, and compared them.
but it's very unreliable if there is too much followers, like 2 million or more.
You can't get all followers in a reasonable time.

2. get a users recent activities, there is 'who is just following you' in there. But it looks like the recent api have limit and you can't request next page of it? If so, you may also miss calculate with that.
And also, you don't know who is unfollowing you with that api.

Any one have suggestion on this?

**Comment by mgp25** [comment]
Hello @miukal,

This is a programming question not an API issue. Remember that this API is equivalent to the Instagram app (Android). Does the Instagram app allows you to see who has unfollowed you? Of course not, but you can go to your followers and see it right? The same happens with the API, you would need to follow that approach.

And yes, you can still paginate from your followers, I dont remember if it list them all after some pagination, but you can check that.

Regards

**Comment by aitte2** [comment]
@miukal Since the API doesn't have that feature (as mgp says) you can only do it by scanning. Get all followers (by pagination) into variable `$newFollowers` and then load previous scan's followers into `$oldFollowers`. Then use this code to check for what has been added and what has been removed:

```php
$added = array_diff($newFollowers, $oldFollowers);
$removed = array_diff($oldFollowers, $newFollowers);
```

This should be ok for small accounts (up to a few thousand followers) but you can forget about it for accounts with millions of followers because pagination scanning would either not work (most likely prevented by Instagram) or would take all day.

**Comment by miukal** [comment]
Thanks @mgp25 @aitte2 
Seems there is no better way to do this for now, especially on 'million followers' account.
I will try 'get all followers' method then.

**Comment by aitte2** [comment]
@miukal There is no better way. I don't think Instagram gives this "who exactly followed/unfollowed?" info even to the Business accounts with Instagram Insights analytics.

I suggest setting a limit and if a profile is below that limit, do scanning of individual follower changes. If above that limit just track the total number changes.

I was curious about testing `array_udiff` and came up with this example:

```php
function cmpUserLists1(array $a, array $b)
{
    // Do a string comparison of UserPK IDs. Doesn't detect username changes.
    return strcmp($a['pk'], $b['pk']);
}

function cmpUserLists2(array $a, array $b)
{
    // Do a string comparison of UserPK IDs. If equal, do a string comparison of
    // the usernames to check for any name-changes. Both are case-sensitive.
    $res = strcmp($a['pk'], $b['pk']);
    if ($res === 0) {
        $res = strcmp($a['username'], $b['username']);
    }

    return $res;
}

// example data:
$oldFollowers = [
    ['pk' => '100', 'username' => 'userA'],
    ['pk' => '101', 'username' => 'userB'],
    ['pk' => '102', 'username' => 'userC'],
    ['pk' => '103', 'username' => 'userD'],
];
$newFollowers = [
    ['pk' => '100', 'username' => 'userA_ChangedName'],
    ['pk' => '102', 'username' => 'userC'],
    ['pk' => '103', 'username' => 'userD'],
    ['pk' => '104', 'username' => 'userE'],
    ['pk' => '105', 'username' => 'userF'],
];

// comparison (ignore username changes):
$added = array_udiff($newFollowers, $oldFollowers, 'cmpUserLists1');
$removed = array_udiff($oldFollowers, $newFollowers, 'cmpUserLists1');

// result:
echo "-- ADDED (USERNAME CHANGES IGNORED):\n";
var_dump(count($added));
var_dump($added);
echo "-- REMOVED (USERNAME CHANGES IGNORED):\n";
var_dump(count($removed));
var_dump($removed);

// comparison (detect username changes):
$added = array_udiff($newFollowers, $oldFollowers, 'cmpUserLists2');
$removed = array_udiff($oldFollowers, $newFollowers, 'cmpUserLists2');

// result:
echo "-- ADDED (DETECT USERNAME CHANGES):\n";
var_dump(count($added));
var_dump($added);
echo "-- REMOVED (DETECT USERNAME CHANGES):\n";
var_dump(count($removed));
var_dump($removed);
```

Result:

```
-- ADDED (USERNAME CHANGES IGNORED):
int(2)
array(2) {
  [3]=>
  array(2) {
    ["pk"]=>
    string(3) "104"
    ["username"]=>
    string(5) "userE"
  }
  [4]=>
  array(2) {
    ["pk"]=>
    string(3) "105"
    ["username"]=>
    string(5) "userF"
  }
}
-- REMOVED (USERNAME CHANGES IGNORED):
int(1)
array(1) {
  [1]=>
  array(2) {
    ["pk"]=>
    string(3) "101"
    ["username"]=>
    string(5) "userB"
  }
}
-- ADDED (DETECT USERNAME CHANGES):
int(3)
array(3) {
  [0]=>
  array(2) {
    ["pk"]=>
    string(3) "100"
    ["username"]=>
    string(17) "userA_ChangedName"
  }
  [3]=>
  array(2) {
    ["pk"]=>
    string(3) "104"
    ["username"]=>
    string(5) "userE"
  }
  [4]=>
  array(2) {
    ["pk"]=>
    string(3) "105"
    ["username"]=>
    string(5) "userF"
  }
}
-- REMOVED (DETECT USERNAME CHANGES):
int(2)
array(2) {
  [0]=>
  array(2) {
    ["pk"]=>
    string(3) "100"
    ["username"]=>
    string(5) "userA"
  }
  [1]=>
  array(2) {
    ["pk"]=>
    string(3) "101"
    ["username"]=>
    string(5) "userB"
  }
}
```

You can use something like those algorithms. :)

**Comment by miukal** [comment]
Thanks @aitte2, those tips are really useful!
