### ISSUE TITLE
Report problem request

### ISSUE THREAD

**Issue by ivanyadeshko** [mgp25/Instagram-API#1955]
/**
     * @param string $problem 
     * one of instagram problem, for example: instagram_like_add
     * 
     * @return Response
     */
    public function reportProblem($problem)
    {
        if (!in_array($problem, ["instagram_like_add"])) {
            throw new RequestException('Invalid request options.');
        }

        $response = $this->request("repute/report_problem/{$problem}/")
            ->addPost('_csrftoken', $this->client->getToken())
            ->addPost('_uid', $this->account_id)
            ->addPost('_uuid', $this->uuid)
            ->getResponse(new Response());

        return $response;
    }

**Comment by ivanyadeshko** [comment]
Hi, guys.
Why my issue will be closed? I just wanted help.

**Comment by darkterminal** [comment]
@ivanyadeshko maybe you should read the wiki and documentation that is in this repository. Your issue is closed for violating the rules here.

Regards,
