### ISSUE TITLE
Comments to all posts of the user

### ISSUE THREAD

**Issue by 95panda** [mgp25/Instagram-API#1956]
Перейти на русскийFirst of all, I want to thank you for the great and incredibly long work. And also apologize for his own, well-deserved English.
I've been horrified for a long time using your libraries to work with direct message and everything is fine.
Now there was a need to develop some functional to search for comments to posts. But in the description of the project I do not find the necessary methods.
Please, tell me whether your project supports the work with comments to the user's posts? If supported, please orient where I can find out the details.
Thankful in advance for any help!

**Comment by mgp25** [comment]
Hello @95panda,

I really don't understand your question. If you are asking if it is possible to retrieve comments of a media, then yes, it is possible. See `Media::getComments()`

Regards
