### ISSUE TITLE
stevejobzniak's repositories are down - install fails

### ISSUE THREAD

**Issue by FloPMT** [mgp25/Instagram-API#1957]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

See title - installation currently fails. Error response:
[RuntimeException]                                                           
Failed to clone https://github.com/SteveJobzniak/LazyJsonMapper.git via https, ssh protocols, aborting.

**Comment by JackHamma** [comment]
Yes I'm having the same problem.

**Comment by mgp25** [comment]
LazyJsonMapper has recently moved to an organization, everything will be available soon.

Regards

**Comment by mgp25** [comment]
Everything should be okay now.

Regards
