### ISSUE TITLE
New functionality on Direct Message to mark conversations

### ISSUE THREAD

**Issue by brunopiaui** [mgp25/Instagram-API#1958]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

Hello,

The Instagram has provided a new feature to mark direct conversations with a star and a conversation query.

<img src="https://user-images.githubusercontent.com/728287/39544620-04453c86-4e25-11e8-91dd-f3aebf28244d.png" width=200>  <img src="https://user-images.githubusercontent.com/728287/39544664-278c3078-4e25-11e8-9162-c63e5759ed13.png" width=200>  <img src="https://user-images.githubusercontent.com/728287/39544695-3bf78d5a-4e25-11e8-8307-7b19167290b0.png" width=200>

Could they implement ??

I would like to know how you capture the instagram requests to implement in the API?

I think I could help in developing the API, but I do not know how to identify the new requests.

**Comment by mgp25** [comment]
Hello @brunopiaui,

That feature doesn't seem to be implemented in android yet. When it is available in the andorid platform we will implement it.

Regards
