### ISSUE TITLE
Logged in or not?

### ISSUE THREAD

**Issue by Fayozjon** [mgp25/Instagram-API#196]
Hi there!
Im trying to emplement authorization via Instagram.
I want to save credentials at session, is there any tips to create some login form via this api-> login() and save it to session.
Thank you for your comments

**Comment by mgp25** [comment]
The session is saved automatically. Please read the wiki

**Comment by aliebrash** [comment]
hi .. how can i save details of login ?
i want to login once and after each close program dont go to again login..how?
