### ISSUE TITLE
Need more wiki about module/pages for comments

### ISSUE THREAD

**Issue by sehgal10** [mgp25/Instagram-API#1961]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

Need a good wiki for the comments, just like we had for likes in the wiki page.
I'm not able to figure out what module/page value to use while adding a comment to a insta post. (https://github.com/mgp25/Instagram-API/blob/1699e99b8595a9ffc18fe8c26b26516ac4274bbc/src/Request/Media.php#L309)
I see the default it set to comments_feed_timeline. But what other values are possible?

Probably a method comments like https://github.com/mgp25/Instagram-API/blob/4ac3d4cda95f3a3a03787d9fce398e20b4d4308d/src/Request/People.php#L22  may also help. Any other guidance or reference if possible.

**Comment by mgp25** [comment]
Hello @sehgal10,

At the moment, this is something not critical and probably will be done in the future by me or other. For now, use the default values we have provided.

Regards
