### ISSUE TITLE
Cannot access media viewer info

### ISSUE THREAD

**Issue by gagginaspinnata** [mgp25/Instagram-API#1964]
My goal is to use the `getStoryItemViewers()` function to get the viewers of a story.

I'm retriving all my stories using the `getArchivedStoriesFeed()` . 
Lets say i get something like this:

> {  
         "timestamp":1525219300,
         "media_count":2,
         "id":"archiveDay:17881314865216446",
         "reel_type":"archive_day_reel",
         "latest_reel_media":1525285901
      },
      {  
         "timestamp":1524960100,
         "media_count":1,
         "id":"archiveDay:17867617315242142",
         "reel_type":"archive_day_reel",
         "latest_reel_media":1525025958
      },
      {  
         "timestamp":1524614500,
         "media_count":2,
         "id":"archiveDay:17910366304164315",
         "reel_type":"archive_day_reel",
         "latest_reel_media":1524678584
      },

Now,lets suppose I want to get the viewers of the story **"archiveDay:17867617315242142"**

When I use `$ig->story->getStoryItemViewers('17867617315242142');`

 I get the error 
> 
> RESPONSE: {"bundles": {}, "request_id": "40142e6edbb147f2973b09bc98634908", "status": "ok"}
> 
> GET:  https://i.instagram.com/api/v1/media/17881314865216446/list_reel_media_viewer/
> → 0B
> ← 400 	 64B
> RESPONSE: {"message": "Cannot access media viewer info", "status": "fail"}
> 
> Something went wrong: InstagramAPI\Response\ReelMediaViewerResponse: Cannot access media viewer info.

Where I went wrong? I tried to pass the parameter both as a string and as a number with no luck.

**Comment by mgp25** [comment]
Hello @gagginaspinnata,

You are doing it wrong. First you should use:

```php
$ig->story->getReelsMediaFeed($feedList);
```

Where `$feedList` is a list of numerical User Pk or Highlight or Archived IDs. In your example:

```php
$feedList = ['archiveDay:17867617315242142'];
```

`Story::getReelsMediaFeed()` will return the correct media pk used for the following request. So...

```php
$feedList = ['archiveDay:17867617315242142'];
$reelsMediaFeed = $ig->story->getReelsMediaFeed($feedList);

$mediaPk = $reelsMediaFeed->getReels()['archiveDay:17867617315242142']->getItems()[0]->getPk();

$ig->story->getStoryItemViewers($mediaPk);
```

Take it as an example, I haven't checked it, but it should be like this.

Regards

**Comment by gagginaspinnata** [comment]
thanks!
I was on the wrong way..I solved my issue, even if I could not use `getItems()[0].>getPk()` . It seems I'm not able to access the value inside the object.
I made a simple workaround
```
function get_story_data_from_id ($id_archiveday,$ig){
    $feedList = [$id_archiveday];
    $reelsMediaFeed = $ig->story->getReelsMediaFeed($feedList);

    $json = json_encode($reelsMediaFeed);
    preg_match("/pk\":(\d{19,19})/", $json, $output_array);    
    $pk =  $output_array[1];
    return  $ig->story->getStoryItemViewers($pk);
}
```

**Comment by bakill3** [comment]
What's the output array?
