### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Zazo0** [mgp25/Instagram-API#1966]
https://github.com/mgp25/Instagram-API/blob/67715b6d8baeb0e6bb51b31466ab4abaf3db34d7/CONTRIBUTING.md

`LazyJsonMapper` refers to SteveJobzniak's repo which doesn't exist

**Comment by mgp25** [comment]
Fixed: https://github.com/mgp25/Instagram-API/commit/3c6ec2f4f429aa00f0e4cdd3d99522eb46d9705d
