### ISSUE TITLE
Function timeline->uploadPhoto uploads photo, but without metadata (text)

### ISSUE THREAD

**Issue by adminko-svk** [mgp25/Instagram-API#1969]
Function `timeline->uploadPhoto` uploads only photo, without metadata (text).

Everything works great some days ago...

Can you check it please?

**Comment by mgp25** [comment]
If you dont post debug log and code, the issue will be considered as invalid and will be closed.

Regards

**Comment by mgp25** [comment]
Hello @adminko-svk,

Your request seems okay, and i just tried on my own and works, so probably your account is flagged or temporary banned.

Regards
