### ISSUE TITLE
Instagram has reset my password account

### ISSUE THREAD

**Issue by mkanker** [mgp25/Instagram-API#197]
Does anyone have yours password reset by Instagram? They send me an e-mail saying that was suspicion. I should re-login after some specific time or have you used the same cookie for long, long time?

**Comment by mgp25** [comment]
@mkanker if someone from other IP/Location tried to login to your account, Instagram does that to avoid people getting into your account. In that case use the same IP/location and thats it, better to use the same cookie

Regards
