### ISSUE TITLE
Logging in with cookies?

### ISSUE THREAD

**Issue by MrARM** [mgp25/Instagram-API#1972]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---

### Describe your issue
Hey, I have a script I made which I would like to use cookies because I can pull them from my client and into my server quickly. I tried making the data Files it uses and manually importing them, however when I tried to upload a photo I got a message telling me to call the Login function. Is there a function that allows me to import the session tokens instead of trying to stitch something that doesn't work right?

**Comment by mgp25** [comment]
Hello @MrARM,

You always should use `$ig->login()` in your script. That doesn't mean you are always logging in, in fact, once you are logged in, next time you call `login()` function it will use the existing session using the cookies stored in `session` folder.

 Probably you are wondering why the API sends requests then when calling `login()`. The answer is easy. We are trying to emulate as much as possible Instagram app behavior, and there are some requests that are sent to server even though you are already logged in.

So in resume, using `login()` function will use the existing session.

Regards

**Comment by zaxoavoki** [comment]
Hello @mgp25,
If I must always use `$ig->login()`, which arguments I need to put into this method? And one more question is why I do not have `session` folder in my project (I'm writing in Laravel 5.6)?
Thank you!

**Comment by Mehrdad1991h** [comment]
@zaxoavoki 
1-
$ig->login($username, $password);
2-
maybe your using from mysql for store data (if set mysql info in api so all data stored in mysql !)

**Comment by zaxoavoki** [comment]
@Mehrdad1991h, 
I'm not using mysql for saving session. In wiki says session folder must be created automatically, but it did not happen. And I don't want to save user's password and name BY my own hand 🍡. I do not have any ideas..

**Comment by zaxoavoki** [comment]
@mgp25 When I call `$ig->login('username', 'password')` I must use username and password again, why then this function use sessions?

**Comment by Mehrdad1991h** [comment]
@zaxoavoki I think you can get all your answer with search !
`login`  check your user, if sessions available try to use from that sessions ... Like Instagram  
Also You can read Wiki , FAQ, ...

------
https://github.com/mgp25/Instagram-API/wiki#login

**Comment by zaxoavoki** [comment]
@Mehrdad1991h I have an error. I dont know from which edge it is.. When I use `login()` function at first, session folder doesn't create in my Laravel project's folder.. So, I can't use session for this reason... How to fix?

**Comment by vkrzt** [comment]
@zaxoavoki session folder is usually created within vendor/mgp25/instagram-php folder. Please recheck.

**Comment by zaxoavoki** [comment]
@vkrzt OK, I see it. But how can I use this cookie `.dat` file?

**Comment by vkrzt** [comment]
You have nothing to do with that file (as per my understanding), library will automatically check this .dat file for session validity and use it or create a new one.

**Comment by zaxoavoki** [comment]
@vkrzt The library does not check this file. Every time when I need to use smth from Intsagram I need to use `$ig->login(username, pass)`, but how can I replace those datas from `.dat` file to username and pass?

**Comment by vkrzt** [comment]
@zaxoavoki, it does. please check documentation to the login() and support functions [here](https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php)

` /**
     * Login to Instagram or automatically resume and refresh previous session.
     *
     * Sets the active account for the class instance. You can call this
     * multiple times to switch between multiple Instagram accounts.
     *`

**Comment by zaxoavoki** [comment]
@vkrzt I don't understand how I must use `username-cookies.dat` via Laravel. Is there a user's password?

**Comment by zaxoavoki** [comment]
@vkrzt , Okay, thank you^^
