### ISSUE TITLE
Stream using OBS: Failed to connect

### ISSUE THREAD

**Issue by ttvd94** [mgp25/Instagram-API#1975]
I'm gonna use OBS for streaming.

I run a script which creates stream object and starts live-stream.
Then I copy `broadcast_id` and `upload_url` from the result to the OBS settings. I also change upload url to use RTMP.
**But** once I start streaming in OBS, I get the error "`Could not access to the specified channel or stream key, please double-check your stream key. If it is correct, there may be a problem connecting to the server.`"

What am I doing wrong?

**Comment by mgp25** [comment]
Hello @ttvd94,

This is a non API related issue. You should ask in an OBS forum.

You can't copy the url directly from the response. You need to do this:

```php
    // Tell Instagram that we want to perform a livestream.
    $stream = $ig->live->create();

    // Switch from RTMPS to RTMP upload URL, since RTMPS doesn't work well.
    $streamUploadUrl = preg_replace(
        '#^rtmps://([^/]+?):443/#ui',
        'rtmp://\1:80/',
        $stream->getUploadUrl()
    );

echo 'URL: '.$streamUploadUrl;
```

The rest of the steps are explained in the F.A.Q.: [How to broadcast using OBS?](https://github.com/mgp25/Instagram-API/wiki/FAQ#how-to-broadcast-using-obs)

More info: See [issue #1488-333365636](https://github.com/mgp25/Instagram-API/issues/1488#issuecomment-333365636)
