### ISSUE TITLE
Adding ability to pass Guzzle client options and custom middle-wares to Client.php

### ISSUE THREAD

**Issue by farsadf** [mgp25/Instagram-API#1976]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

### Describe your issue

As far as I've dug into the codebase, there are no ways to pass Guzzle client options to the library; for example, If you'd like to add a custom middleware to every request of your Guzzle client (which is available by pushing your middleware to handler stack), by the current implementation there are no ways to do that.

It's because of the hard-coded values for the handler and guzzle client configuration inside the ``Client.php`` file, lines 124 to 143.

My current proposal for this issue is changing ``Instagram::__construct`` signature (which is the only user of this method) to accept Guzzle client options as the fourth (optional) argument.

**Comment by mgp25** [comment]
And here is my question: Why do you want that?

It is hardcoded for a reason.

**Comment by farsadf** [comment]
Hello there,
It's only because of the ``connect_timeout`` option.
By developing locally It hurts a lot with my poor internet connection.
Thanks

**Comment by mgp25** [comment]
@valga @aitte2 @lazyjsonauthor What are your thought on this?

**Comment by mgp25** [comment]
@valga fantastic solution! Great catch.

Didn't know that, but going back to the source code:

```php
    /**
     * Create a custom API request.
     *
     * Used internally, but can also be used by end-users if they want
     * to create completely custom API queries without modifying this library.
     *
     * @param string $url
     *
     * @return \InstagramAPI\Request
     */
    public function request(
        $url)
    {
        return new Request($this, $url);
    }
```

Now I know why it was places there.

@lazyjsonauthor did it perfectly.

Today I learn something new 😄 

Thanks again @valga
