### ISSUE TITLE
upload PNG 

### ISSUE THREAD

**Issue by usamawaleed** [mgp25/Instagram-API#1978]
### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Dear Sir,
I want to know why I am unable to upload PNG image to my time line while instagram allow PNG image format.
Best Regards

**Comment by mgp25** [comment]
- [uploadPhoto.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php)
