### ISSUE TITLE
Login required

### ISSUE THREAD

**Issue by LoriKovari** [mgp25/Instagram-API#1979]
Hi,
I got from _uploadResumablePhoto function an 'login_required' exception.
I checked the credentials for the channel where the publish doesn't work and called the login method and everything is working fine but when it comes to publish a photo I got the 'login_required' exception.

Could you please help me with some ideas to fix that?

Here is the exception what I got:

InstagramAPI\\Exception\\LoginRequiredException: InstagramAPI\\Response\\ResumableOffsetResponse: Login required. 
in /home/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:189\nStack trace:\n#0 
/home/pi/mgp25/instagram-php/src/Client.php(546): 
InstagramAPI\\Exception\\ServerMessageThrower::autoThrow('InstagramAPI\\\\Re...', 'login_required', 
Object(InstagramAPI\\Response\\ResumableOffsetResponse), Object(GuzzleHttp\\Psr7\\Response))\n#1 
/home/pi/mgp25/instagram-php/src/Request.php(764): 
InstagramAPI\\Client->mapServerResponse(Object(InstagramAPI\\Response\\ResumableOffsetResponse), 
'{\"message\": \"lo...', Object(GuzzleHttp\\Psr7\\Response))\n#2 /home/mgp25/instagram-php/src/Request/Internal.php(1310): 
InstagramAPI\\Request->getResponse(Object(InstagramAPI\\Response\\ResumableOffsetResponse))\n#3 
/home/mgp25/instagram-php/src/Request/Internal.php(1421): 
InstagramAPI\\Request\\Internal->_uploadResumableMedia(Object(InstagramAPI\\Media\\Photo\\PhotoDetails), 
Object(InstagramAPI\\Request), Object(InstagramAPI\\Request))\n#4 
/home/mgp25/instagram-php/src/Request/Internal.php(133): 
InstagramAPI\\Request\\Internal->_uploadResumablePhoto(1, Object(InstagramAPI\\Request\\Metadata\\Internal))\n#5 
/home/mgp25/instagram-php/src/Request/Internal.php(98): 
InstagramAPI\\Request\\Internal->uploadPhotoData(1, Object(InstagramAPI\\Request\\Metadata\\Internal))\n#6 
/home/mgp25/instagram-php/src/Request/Timeline.php(38):

**Comment by mgp25** [comment]
When opening this kind of issues:

- Provide debug log
- Provide the code used
- Formatting your issue with markdown


- [/examples/uploadPhoto.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php)

Once you post debug log and the code you used, i'll answer.

Regards

**Comment by LoriKovari** [comment]
Hi, sorry for the incomplete informations:

### My code looks like:

```php
try {
    $filename = ".....";
    $caption = "some caption";
    if (!file_exists($filename)) 
        error('file not found');

    $metadata = [
        'caption' => $caption
    ];
    $result = $ig->timeline->uploadPhoto($filename, $metadata);
    response($result);
} catch (\Exception $e) {
    handleException($e);
}
```

### Error log

```json
 POST:  https://i.instagram.com/api/v1/feed/timeline/
DATA: feed_view_info=&phone_id=.....&is_pull_to_refresh=0&reason=cold_start_fetch&timezone_offset=0&_csrftoken=.....&is_async_ads_rti=0&will_sound_on=1&is_async_ads_double_request=0&battery_level=100&seen_posts=&is_charging=1&is_prefetch=0&is_async_ads=0&is_on_screen=true&_uuid=....&unseen_posts=
← 200    20.65kB
RESPONSE: {"num_results": 10, ... }

GET:  https://i.instagram.com/api/v1/scores/bootstrap/users/?surfaces=%5B%22coefficient_direct_recipients_ranking_variant_2%22%2C%22coefficient_direct_recipients_ranking%22%2C%22coefficient_ios_section_test_bootstrap_ranking%22%2C%22autocomplete_user_list%22%5D
→ 0B
← 200    52kB
RESPONSE: {"users": [...], "status": "ok"}

POST:  https://i.instagram.com/api/v1/feed/reels_tray/
DATA: _csrftoken=........&_uuid=.........
← 200    14.28kB
RESPONSE: {... "status": "ok"}

GET:  https://i.instagram.com/api/v1/direct_v2/ranked_recipients/?use_unified_inbox=true&mode=reshare&show_threads=true
→ 0B
← 200    3.32kB
RESPONSE: {... "status": "ok"}

GET:  https://i.instagram.com/api/v1/direct_v2/ranked_recipients/?use_unified_inbox=true&mode=raven&show_threads=true
→ 0B
← 200    3.33kB
RESPONSE: {... "status": "ok"}

GET:  https://i.instagram.com/api/v1/direct_v2/inbox/?persistentBadging=true&use_unified_inbox=true
→ 0B
← 200    929B
RESPONSE: {... "status": "ok"}

GET:  https://i.instagram.com/api/v1/news/inbox/
→ 0B
← 200    18.73kB
RESPONSE: {... "status": "ok"}

GET:  https://i.instagram.com/api/v1/users/profile_notice/
→ 0B
← 200    56B
RESPONSE: {"has_change_password_megaphone": false, "status": "ok"}

GET:  https://i.instagram.com/api/v1/discover/explore/?max_id=0&module=explore_popular&timezone_offset=0&is_from_promote=false&session_id=........&is_prefetch=false
→ 0B
← 200    35.47kB
RESPONSE: {... "status":"ok"}

GET:  https://i.instagram.com/rupload_igphoto/1526378630588_0_1034271622
→ 0B
← 403    47B
RESPONSE: {"message": "login_required", "status": "fail"}

PHP Fatal error:  Uncaught InstagramAPI\Exception\LoginRequiredException: InstagramAPI\Response\ResumableOffsetResponse: Login required. in /.../vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:189
Stack trace:
#0 /.../vendor/mgp25/instagram-php/src/Client.php(546): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'login_required', Object(InstagramAPI\Response\ResumableOffsetResponse), Object(GuzzleHttp\Psr7\Response))
#1 /.../vendor/mgp25/instagram-php/src/Request.php(764): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\ResumableOffsetResponse), '{"message": "lo...', Object(GuzzleHttp\Psr7\Response))
#2 /.../vendor/mgp25/instagram-php/src/Request/Internal.php(1310): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\ResumableOffsetResponse))
#3 /.../vendor/mgp25/instagram-php/src/Request/Internal in /.../vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php on line 189
```
### Mention: 
If I test it localy it is working fine everytime, but on the remote device where is the code running all the time I got the error. Could it be some session problem?

Thanks a lot.

**Comment by mgp25** [comment]
Hello @LoriKovari,

from my experience with other users it seems that although you have a valid session, you or probably one of your users has changed the password and therefore the script can't do certain requests.

My recomendation, delete your session from `/sessions` folder and try again.

**Comment by LoriKovari** [comment]
@mgp25  yes that really make sense.
Thanks a lot for your help and have a nice day
