### ISSUE TITLE
getSelfFollowing retuning old list of users when count is 0

### ISSUE THREAD

**Issue by sehgal10** [mgp25/Instagram-API#1981]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

getSelfFollowing API returning old list of users after unfollowing all the users (When Following count is 0). Though the list is suppose to change and getSelfInfo() is returning correct count.

Tried changing the proxy as well as deleting the session folder at vendor/mgp25/instagram-php/sessions

Still no luck. Is there something I have missed to delete or refresh the cache?

Thanks in Advance.

**Comment by NikitaSNS** [comment]
getSelfUserFeed, getUserFeed - alse works incorrectly

**Comment by mgp25** [comment]
@sehgal10 Works fine. Responses comes from Instagram server, so it is no API fault. For further support you have to post script code and debug log.

@NikitaSNS Again, it works great for me. Without giving a proper explanation about why it is "incorrectly" we can not do anything here.

Guys, when opening issues you need to provide as much info as you can. This includes script code and debug log.

I'll give an answer here when the information is posted. Make sure you are using `dev-master` version.

Regards
