### ISSUE TITLE
How to get user's last seen?

### ISSUE THREAD

**Issue by LloydBlv** [mgp25/Instagram-API#1982]
Is there anyway to find user's last online time?

**Comment by mgp25** [comment]
Hello @LloydBlv,

You can use [/examples/realtimeClient.php](https://github.com/mgp25/Instagram-API/blob/master/examples/realtimeClient.php#L89).

You can use the event `presence` to get such information:

```php
$rtc->on('presence', function (\InstagramAPI\Response\Model\UserPresence $presence) {
    $action = $presence->getIsActive() ? 'is now using' : 'just closed';
    printf('[RTC] User %s %s one of Instagram apps%s', $presence->getUserId(), $action, PHP_EOL);
});
```

Regards

**Comment by KipRaq** [comment]
Can I get this info without sending messages to that user?
