### ISSUE TITLE
Playing Live on RTMP Player?

### ISSUE THREAD

**Issue by ehsan1526** [mgp25/Instagram-API#1983]
Hi

Is there a solution for playing live video's in players by using any rtmp link (without using instagram app)?

thank you

**Comment by superoleg** [comment]
Use the method of
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Live.php
create() then start()
start() will return you  rtmp link. 
Example: rtmps://live-upload.instagram.com:443/rtmp/**17990264095190669?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfbGl2ZWRhc2giOnsibGl2ZWRhc2hfbW9kZSI6InByaW1hcnkifSwiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0mN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOltdLCJpZ19saXZlX2VuYWJsZV9wb3BfcHJpbWluZyI6eyJlbmFibGVkIjoiMSJ9LCJpZ19sRhdGVzX3RocmlmdF9lbmFibGUiOnsiZW5hYmxlZCI6IjEifX19&a=ATiiT-s-v-Sm16TW**

link: rtmp://live-upload.instagram.com:80/rtmp/
Password: **17990264095190669?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfbGl2ZWRhc2giOnsibGl2ZWRhc2hfbW9kZSI6InByaW1hcnkifSwiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0mN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOltdLCJpZ19saXZlX2VuYWJsZV9wb3BfcHJpbWluZyI6eyJlbmFibGVkIjoiMSJ9LCJpZ19sRhdGVzX3RocmlmdF9lbmFibGUiOnsiZW5hYmxlZCI6IjEifX19&a=ATiiT-s-v-Sm16TW**

**Comment by mgp25** [comment]
Probably there is something to view the transmissions, nevertheless, it is something we are not going to add.

Pull requests or information is always welcomed.

Regards
