### ISSUE TITLE
Cancel a Request follow

### ISSUE THREAD

**Issue by aiunc** [mgp25/Instagram-API#1984]
I've Requested follow for a private page. how i can cancel this?

<img src="http://uupload.ir/files/1xsy_456456453453453.png">

Function unfollow and removeFollower not work for this.

**Comment by mgp25** [comment]
Hello @aiunc,

It works, just tested. 

Regards

**Comment by aiunc** [comment]
@mgp25  thank you. i will test again.
a question other?!
how i can get list of users that i Requested follow?
in instagram web [this page](https://www.instagram.com/accounts/access_tool/current_follow_requests) show all it users

**Comment by mgp25** [comment]
@aiunc This API is based on the Android app. You would need to tell me where in the app I see this.

Regards
