### ISSUE TITLE
getReelsMediaFeed() returns no reels

### ISSUE THREAD

**Issue by r0xen** [mgp25/Instagram-API#1985]
As the title suggest. I tried this changing user performing the request. Something like

`$ig->story->getReelsMediaFeed($chunck)->getReelsMedia()`

where $chunck it's an arraylist of PKs, returns NULL - obvsly users have stories going on. Maybe an API change?

**Comment by r0xen** [comment]
Hello, this doesn't seems fixed to me. Same code, log:

`POST:  https://i.instagram.com/api/v1/feed/reels_media/
DATA: ig_sig_key_version=4&signed_body=db94747a46333eb617bf86c207dde49cf1f96fcc56d69245fde61084d737737a.{"supported_capabilities_new":"[{\"name\":\"SUPPORTED_SDK_VERSIONS\",\"value\":\"9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0\"},{\"name\":\"FACE_TRACKER_VERSION\",\"value\":\"9\"},{\"name\":\"segmentation\",\"value\":\"segmentation_enabled\"}]","_csrftoken":"SemjvkpaG15jkc2GOCzthSAsMz11k7Pu","user_ids":["chiaraferragni","fedez","edmondo.aloia"],"_uid":"REDACTED","_uuid":"REDACTED"}
← 200 	 29B
RESPONSE: {"reels": {}, "status": "ok"}

NULL`

**Comment by mgp25** [comment]
@r0xen man, look at your code you are not passing user IDs! you are passing usernames directly.

........

**Comment by r0xen** [comment]
Sorry that was a stupid mistake by me. Anyway seems like getReelsMediaFeed() does it's job but getReelsMedia() doesn't. Returns null even if instagram returns reels. Using getReels() instead of getReelsMedia() solves everything. Is this expected?

**Comment by mgp25** [comment]
Hello @r0xen,

Yes, they way you manipulate responses is related to the response itself. For example:

Response:
```json
{"reels": {}, "status": "ok"}
```

The way to work with this object would be like `->getReels()`

What about this response?

```json
{"reels": {"something": "value"}, "status": "ok"}
```

`->getReels()->getSomething()`

And what about this one:

```json
{"some_stuff": {"something": "value"}, "status": "ok"}
```

`->getSomeStuff()->getSomething()`


All this is explained in the [wiki](https://github.com/mgp25/Instagram-API/wiki):

- [Managing responses](https://github.com/mgp25/Instagram-API/wiki#managing-responses)

More information about how this is done can be found in [LazyJsonMapper](https://github.com/lazyjsonmapper/lazyjsonmapper) repository.


Regards
