### ISSUE TITLE
Do works faster!

### ISSUE THREAD

**Issue by testservices** [mgp25/Instagram-API#1986]
Hi
I want to follow or... 20 poeple, but it takes a long time to do it.
so I have to use pthread(for multi threading in php) and it's hard work to do it on host.

So is there any way to I do this work without multi threading?

**Comment by edtereza** [comment]
If you do it too fast, you will be shadow banned or worst...

Em seg, 21 de mai de 2018 08:36, testservices <notifications@github.com>
escreveu:
