### ISSUE TITLE
Live quality

### ISSUE THREAD

**Issue by DaveOff** [mgp25/Instagram-API#1987]
Is it possible to improve the quality of live streaming?

The quality of my video is 1080p, but it is still live is very poor quality And nothing is seen.

thanks.

```php
-rtbufsize 256M -re -i %s -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 480x240 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv %s

**Comment by valga** [comment]
@DaveOff `-s 480x240` means that your video is downscaled to 480x240; `-vb 400k -maxrate 1500k` means that average video bitrate is 400kbps with peaks up to 1500kbps.

If your source video is of high quality, you have to play with these params to preserve it. But take in mind that higher quality requires higher connection speed, etc.

**Comment by DaveOff** [comment]
@valga thanks for reply. my speed connection is high but can you help me with params and What parameters should I edit for maximum quality for 1080p video.

default -s is : 1080px720p but Nothing can be seen in live streaming
and i edit that to : 480x240 its better now but still not good...

**Comment by valga** [comment]
@DaveOff Try `-s 1080x720 -vb 3000k -maxrate 5000k`: higher resolution requires bigger bitrate. Also see https://stream.twitch.tv/encoding/ for recommendations.
