### ISSUE TITLE
Check Online Status

### ISSUE THREAD

**Issue by karopass** [mgp25/Instagram-API#1989]
---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

---
### Describe your issue
Hi!
Can we know user is online/offline at this time using this awesome library?
Thanks!

**Comment by mgp25** [comment]
Duplicate: https://github.com/mgp25/Instagram-API/issues/1982
