### ISSUE TITLE
Implementation of sending a heart (like) in Direct Messages

### ISSUE THREAD

**Issue by rushilsrivastava** [mgp25/Instagram-API#1992]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

This feature request was introduced in #853, but forgotten about. Will there ever be implementation of sending a heart (like) through direct messages?

**Comment by mgp25** [comment]
- [/Request/Direct.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php)
