### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by parsibox** [mgp25/Instagram-API#1993]
```
Something went wrong: Network: CURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
```
this is my code 

```
<?
set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'/vendor/autoload.php';

/////// CONFIG ///////
$username = 'ssssssssss';
$password = 'xxxxxxxx';
$debug = true;
$truncatedDebug = true;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
 
?>
```

**Comment by mgp25** [comment]
Read the wiki and FAQ.

**Comment by parsibox** [comment]
i add $options['verify'] = false; at  vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php line 329

**Comment by alissonpelizaro** [comment]
> i add $options['verify'] = false; at vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php line 329

This works for me, thanks!!

**Comment by szokeptr** [comment]
The correct solution would be `$ig->setVerifySSL(false)`. Never-ever mess with your `vendor` folder.

https://github.com/mgp25/Instagram-API/blob/d1159725aae5f4f61d1b3a4053dfc57a6c5f85a7/src/Instagram.php#L322-L336
