### ISSUE TITLE
how can I accept direct message request

### ISSUE THREAD

**Issue by DenisSouth** [mgp25/Instagram-API#1995]
If someone on instagram who doesn't follow me and whom I have not followed, send me direct message , i get a notification

Instagram-API can not read the message and answer on it
how can i accept this request
[pic of direct message request](http://www.tech-recipes.com/wp-content/uploads/2018/03/Instagram-Message-Requests.png)

**Comment by valga** [comment]
@DenisSouth Use `Direct::getPendingInbox()` to get a list of pending threads, and `Direct::approvePendingThreads()` to accept them.
