### ISSUE TITLE
getPopularFeed() version 2 match in version 4.1

### ISSUE THREAD

**Issue by plonknimbuzz** [mgp25/Instagram-API#1996]
### Purpose of your issue?
- [x] Question

---
where i can find getPopularFeed() match function in version 4.1?
i even try to find string using bash, 
`grep -r popular app/vendor/*`
and just find this line only
`endor/mgp25/instagram-php/src/Request/Discover.php:            $request->addParam('module', 'explore_popular');`
which is refers to `getExploreFeed()`

but i think that function is similar with `explore()` function not `getPopularFeed()`

**Comment by valga** [comment]
@plonknimbuzz Just think of 2.0 as an old Instagram app: there is no `getPopularFeed()` in the recent app anymore.

You should switch to `getExploreFeed()` or you can just continue to use 2.0, but its support will be discontinued by Instagram.
