### ISSUE TITLE
Problem with follow, unfollow, getUserFollowers, etc

### ISSUE THREAD

**Issue by yazhog** [mgp25/Instagram-API#2]
Hello. 
follow: http://clip2net.com/s/3r2Qgou
unfollow: http://clip2net.com/s/3r2R3cG
getUserFollowers: http://clip2net.com/s/3r2RwST

uploadPhoto (http://clip2net.com/s/3r2SWGO) and searchUsers (http://c2n.me/3r2TcLb) works good.
what am I doing wrong?

**Comment by mgp25** [comment]
@yazhog 
```php
  /**
  * Get user followers
  *
  * @param String $usernameId
  *   Username id
  *
  * @return array
  *   followers data
```

`username id` not `username`

Regards
