### ISSUE TITLE
REQUEST: comment

### ISSUE THREAD

**Issue by hadivip** [mgp25/Instagram-API#20]
is there any chance that you implement commenting in Instagram??

**Comment by mgp25** [comment]
Maybe some day, i don't know, i only did this API to upload my images to my account.

**Comment by aherlambang** [comment]
I'd also like to request this comment feature :)

**Comment by xteraflopx** [comment]
Can you tell us how you sniff the API endpoints? I would be willing to find out how to post comments and then report back here! I tried using Charles Proxy, but it only intercepts certain HTTP requests.

**Comment by hadivip** [comment]
decompiling the instageram app and using wireshark was what i do


با تشکر

هادی رنجبر






On Wed, Jan 6, 2016 at 9:50 PM -0800, "xteraflopx" <notifications@github.com> wrote:





Can you tell us how you sniff the API endpoints? I would be willing to find out how to post comments and then report back here! I tried using Charles Proxy, but it only intercepts certain HTTP requests.

---

**Comment by xteraflopx** [comment]
@hadivip using Wireshark is a pain in the butt, for some reason I think I was having trouble sorting out the HTTP requests because there was so much junk and TCP stuff... And I've decompiled the app into smali code but it seems obfuscated, and I don't know how anyone could find useful information with it! :(

**Comment by hadivip** [comment]
well you should filter wireshark out put using http tag. the original code is most definitely obfuscated but still they can not hide certain things like endpoints. Whit some luck you will get there




On Wed, Jan 6, 2016 at 9:57 PM -0800, "xteraflopx" <notifications@github.com> wrote:





@hadivip using Wireshark is a pain in the butt, for some reason I think I was having trouble sorting out the HTTP requests because there was so much junk and TCP stuff... And I've decompiled the app into smali code but it seems obfuscated, and I don't know how anyone could find useful information with it! :(

---

**Comment by xteraflopx** [comment]
@hadivip I just opened Wireshark for a test and I think it's useless... The only HTTP requests are from downloading pictures. Every request is over SSL so you can't even see which URL's the requests are going to... :(

**Comment by hadivip** [comment]
Ok buddy i will give it try myself and report back when i got some free time :)

**Comment by RageBrahimi** [comment]
Add the following to '../src/Instagram.php'

Add the following to 

  /**
  * Comment media
  *
  * @param String $mediaId
  *   Media id
  *
  * @param String $commentText
  *   Comment Text
  *
  public function comment($mediaId, $commentText = "")
  {
    if (!$this->isLoggedIn)
    {
      throw new InstagramException("Not logged in\n");
      return;
    }

    $data = json_encode(array(
        '_uuid'  => $this->uuid,
        '_uid'   => $this->username_id,
        '_csrftoken' => $this->token,
        'comment_text'   => $commentText
    ));

    return $this->request("media/$mediaId/comment/", $this->generateSignature($data))[1];
  }


Then use:

try {
  $i->comment($mediaId, $commentText = "");
} catch (Exception $e)
{
  echo $e->getMessage();
}

**Comment by hadivip** [comment]
dude that's awesome I can't wait to give it a try :)




On Fri, Jan 8, 2016 at 5:21 AM -0800, "Rage Brahimi" <notifications@github.com> wrote:





Add the following to '../src/Instagram.php'

Add the following to

  /**
  * Comment media
  *
  * @param String $mediaId
  *   Media id
  *
  * @param String $commentText
  *   Comment Text
  *
  public function comment($mediaId, $commentText = "")
  {
    if (!$this->isLoggedIn)
    {
      throw new InstagramException("Not logged in\n");
      return;
    }

    $data = json_encode(array(
        '_uuid'  => $this->uuid,
        '_uid'   => $this->username_id,
        '_csrftoken' => $this->token,
        'comment_text'   => $commentText
    ));

    return $this->request("media/$mediaId/comment/", $this->generateSignature($data))[1];
  }


Then use:

try {
  $i->comment($mediaId, $commentText = "");
} catch (Exception $e)
{
  echo $e->getMessage();
}

---

**Comment by mgp25** [comment]
Let me know if this works, and i'll add it :smile: 

Regards

**Comment by xteraflopx** [comment]
It seems like @mgp25 didn't want to reveal how he found the API endpoints. Well guess what! I've accomplished it myself! I decompiled the Instagram APP, modified the SMALI code, and all requests are automatically written to the Log... I'm now able to find every single API endpoint. Hopefully I will be able to additionally log all the POST data and such... Example of the output I get:

https://i.instagram.com/api/v1/feed/u
https://i.instagram.com/api/v1/users/
https://i.instagram.com/api/v1/feed/user/2465627079/
https://i.instagram.com/api/v1/users/2465627079/info/
https://i.instagram.com/api/v1/friendships/show/2465627079/
https://i.instagram.com/api/v1/friendships/2465627079/following/
https://i.instagram.com/api/v1/friendships/show_many/
https://i.instagram.com/api/v1/discover/popular/
https://i.instagram.com/api/v1/discover/popular/
https://i.instagram.com/api/v1/accounts/logout/
http://i.instagram.com/api/v1/users/check_email/
https://i.instagram.com/api/v1/accounts/username_suggestions/
https://i.instagram.com/api/v1/si/fetch_headers/
https://i.instagram.com/api/v1/users/check_username/
https://i.instagram.com/api/v1/accounts/create/
https://i.instagram.com/api/v1/accounts/create/

**Comment by xteraflopx** [comment]
By the way, I tested the commenting endpoint and I can confirm that it works :+1:

**Comment by miladghiravani** [comment]
Use this: `$ig->media->comment($mediaId , "Nice")`
