### ISSUE TITLE
Get all followings

### ISSUE THREAD

**Issue by wangdan0527** [mgp25/Instagram-API#200]
I got only 175 results but I have a thousand.
I think there is a pagination but how to use it?
Please help me.

Thanks

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/wiki#get-followings--followers

**Comment by mgp25** [comment]
@wangdan0527 add the `max_id` attrib

**Comment by wangdan0527** [comment]
Is that max count?

**Comment by wangdan0527** [comment]
$follows = $user -> getUserFollowings('1401749255', 400);
	print_r($follows);
This is my code
Array
(
    [status] => ok
    [big_list] => 
    [users] => Array
        (
        )

    [page_size] => 200
)

This is the result
Please check and help me
Thanks

**Comment by HayashiShintaro** [comment]
I have same trouble in getting total number of followers and followings.

How can I get total number of followers and followings?

**Comment by HayashiShintaro** [comment]
@mgp25 I faced same problem in getting total number of followers and followings.
Is there any api for getting total number of followers and followings?
If so, please let me know.
PS: getProfileData() doesn't give me the info.

**Comment by RageBrahimi** [comment]
Use `getUsernameInfo()`

**Comment by HayashiShintaro** [comment]
@RageBrahimi Thank you

**Comment by RageBrahimi** [comment]
@wangdan0527 You're using `$maxid` incorrectly.

So when you run `$i->getUserFollowings($usernameId);` similar JSON below is returned (truncated)

```javascript
  {
  	"status": "ok",
  	"big_list": true,
  	"users": [{
  		"username": "asl.mert",
  		"has_anonymous_profile_picture": true,
  		"profile_pic_url": "http://scontent-lhr3-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg",
  		"full_name": "Asl\u0131 Mert",
  		"pk": 3294959691,
  		"is_verified": false,
  		"is_private": false
  	},{
  		"username": "ali_mashaikhi",
  		"has_anonymous_profile_picture": false,
  		"profile_pic_url": "http://scontent-lhr3-1.cdninstagram.com/t51.2885-19/s150x150/13116539_277661979235903_421638637_a.jpg",
  		"full_name": "~\u00b0\u25cf( \u0639\u0644\u064a \u0622\u0625\u0644\u0645\u0640\u2665\u0328\u0325\u032c\u0329\u0634\u0622\u0625\u064a\u062e\u064a )\u25cf\u00b0~",
  		"pk": 1269703933,
  		"is_verified": false,
  		"is_private": false
  	}],
  	"page_size": 200,
  	"next_max_id": "AQDoABpB7cRzDcTsdQeb7JDFAw-v_muGDyD7ljq72ujH6-ejagHcg4wdtQvx2hUs9by4NIxcV_i8kMRy1mfScjvh18axrt12ww8QIdQCCt7sba21LUsBdKh2vUX4bZhO700"
  }
```
You must use the node `next_max_id` for `$maxid`

**Comment by Arei15** [comment]
GetUsernameInfo() with attrib max_id don't have return full
