### ISSUE TITLE
Error with Two Factor Login

### ISSUE THREAD

**Issue by brunopiaui** [mgp25/Instagram-API#2002]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hi,

I'm trying to test a login (Two Factor), but sending the sms code returns an error.

I've searched a lot before opening this issue, but I have tested multiple logins successfully, and only this type, with the sample code, does not work.

I'm using **mgp25/Instagram-API dev-master**

Code:

```php
<?php
set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'./vendor/autoload.php';
/////// CONFIG ///////
$username = 'xxxxx@gmail.com';
$password = 'xxxxxxxxx';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->setVerifySSL(false);
try {
    $loginResponse = $ig->login($username, $password);
    if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()) {
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();
        // The "STDIN" lets you paste the code via terminal for testing.
        // You should replace this line with the logic you want.
        // The verification code will be sent by Instagram via SMS.
        $verificationCode = trim(fgets(STDIN));
        $ig->finishTwoFactorLogin($username, $password, $twoFactorIdentifier, $verificationCode);
        $feed = $ig->discover->getExploreFeed();
    }
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

Result:

```
POST:  https://i.instagram.com/api/v1/accounts/login/

DATA: signed_body=e996418bbb74d87b5f9e5bc854ec1d816e171c063c8fd04cdb3c91d9cfbf81f3.{"phone_id":"0e60312e-9dae-4e53-aaf8-8a913a8be865","_csrftoken":"SCSI0x94qQEMTHz5yTQl4Kl
HzTU3DAol","username":"xxxxx@gmail.com","adid":"cb722642-efc9-4179-97ec-cb2417760376","guid":"f8ff58d7-9fb7-4bbf-8fbb-db5914d1aabb","device_id":"android-4075c4ad4dcf
2428","password":"xxxxxxxxx","login_attempt_count":"0"}&ig_sig_key_version=4
← 400     524B
RESPONSE: {"message": "", "two_factor_required": true, "two_factor_info": {"username": "xxxxx", "obfuscated_phone_number": "5357", "two_factor_identifier": "OrQ
cz0Asyf", "show_messenger_code_option": false, "phone_verification_settings": {"max_sms_count": 2, "resend_sms_delay_sec": 60, "robocall_after_max_sms": true, "robocall_count_down_ti
me_sec": 30}}, "phone_verification_settings": {"max_sms_count": 2, "resend_sms_delay_sec": 60, "robocall_after_max_sms": true, "robocall_count_down_time_sec": 30}, "status": "fail"}


POST:  https://i.instagram.com/api/v1/accounts/two_factor_login/
DATA: signed_body=bec6ad08d30c9cb617fd0480fbf544ad27d2605a2c96efa5694f664633abb4e4.{"verification_code":"821604","_csrftoken":"SCSI0x94qQEMTHz5yTQl4KlHzTU3DAol","two_facto
r_identifier":"OrQcz0Asyf","username":"xxxxx@gmail.com","device_id":"android-4075c4ad4dcf2428","password":"xxxxxxxxx"}&ig_sig_key_version=4
← 400     87B
RESPONSE: {"message": "Invalid Parameters", "status": "fail", "error_type": "invalid_parameters"}`
```

`Something went wrong: InstagramAPI\Response\LoginResponse: Invalid Parameters.`

**Comment by brunopiaui** [comment]
Hi @mgp25 
I used the example that is here in github and I passed as much information about the problem as possible. If the issue was marked invalid, could you tell me what I did wrong?
Thanks..

**Comment by mgp25** [comment]
I dont see anything wrong at first sight, maybe the function has been updated

**Comment by brunopiaui** [comment]
I'm using the latest version of the API

**Comment by mgp25** [comment]
@brunopiaui If you send me an email with the account that (or any dummy account with 2FA), I'll check if something has changed.

**Comment by brunopiaui** [comment]
Done... Thanks!!

**Comment by mgp25** [comment]
It requires to use the username and not the email. This can easily be updated passing the login response to `finishTwoFactorLogin()` and taking the real username (not email) as the `username` POST param.
