### ISSUE TITLE
InstagramAPI\Response\DirectRankedRecipientsResponse

### ISSUE THREAD

**Issue by iwolfmarketing** [mgp25/Instagram-API#2004]

**Comment by Ademking** [comment]
Same error 😢

**Comment by iwolfmarketing** [comment]
@Ademking Instagram has recently updated their API. This mgp25 API is using Instagram Android v10.x  and the last version of Instagram app on Android is v45.x.

**Comment by Ademking** [comment]
@iwolfmarketing : so how can we fix it ? did you found a solution ? 😃
