### ISSUE TITLE
setBiography 404

### ISSUE THREAD

**Issue by phenoengine** [mgp25/Instagram-API#2005]
Hello. Got 404 while calling $ig->account->setBiography('asdasd');

`POST: https://i.instagram.com/api/v1/accounts/set_biography/ DATA: signed_body=77e0077c51f985bb556a647025ee5f00d7d2ccfd7e91754e79b7d29da34f0d82.{"_csrftoken":"FhXkNnqJ25TidQlpBEZPogPSQOslFo5r","_uid":"7874677761","_uuid":"b1f2f820-e757-460d-826e-2dcc294e9811","raw_text":"asdasd"}&ig_sig_key_version=4 ← 404 26.29kB RESPONSE: here is html with 404 error`

`Fatal error: Uncaught InstagramAPI\Exception\NotFoundException: Requested resource does not exist. in /var/www/instaconsole/vendor/mgp25/instagram-php/src/Client.php:467 Stack trace: #0 /var/www/instaconsole/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\UserInfoResponse), '<!DOCTYPE html>...', Object(GuzzleHttp\Psr7\Response)) #1 /var/www/instaconsole/vendor/mgp25/instagram-php/src/Request/Account.php(68): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\UserInfoResponse)) #2 /var/www/instaconsole/parser/functions.php(237): InstagramAPI\Request\Account->setBiography('asdasd') #3 /var/www/instaconsole/parser/client-daemon.php(65): processTask(Array) #4 {main} thrown in /var/www/instaconsole/vendor/mgp25/instagram-php/src/Client.php on line 467`

Also have a question. What is the point to use `setBiography()` function and then `editProfile()` like docs says if we can directly using `editProfile()` with all included parameters?

Thanks in advance :)

**Comment by mgp25** [comment]
Hello @phenoengine,

They are not independent one from the other. This means you need to do one, in order to set the other one.

You would need to do:

```php
$bio = 'asdasd';

$ig->account->getCurrentUser();
$ig->account->setBiography($bio);
$ig->account->editProfile($url, $phone, $name, $bio, $email, $gender);
```

Instagram did this in order to verify mentions and hashtags that are going to be included in the bio.

Regards

**Comment by mgp25** [comment]
This requires a newer version (Constants), in order to work. You will have to wait until we release new keys.

Regards
