### ISSUE TITLE
setUser after successful login

### ISSUE THREAD

**Issue by MahdiPishguy** [mgp25/Instagram-API#2009]
after successful login into Instagram account i'm trying to use exiting data with `_setUser` by this code:

    public function check()
    {
        $username = 'XXXX';
        $password = 'XXXX';
        $ig = new Instagram($debug, $truncatedDebug);
        try {
            $ig->_setUser($username, $password);

            //or this code:
            //$ig::_setUser($username, $password);
        } catch (\Exception $e) {
            echo 'Something went wrong: '.$e->getMessage()."\n";
            exit(0);
        }
    }

unfortunately i get this error:

`"Call to protected method InstagramAPI\Instagram::_setUser() from context 'App\Http\Controllers\InstagramController'"`

**Comment by aitte2** [comment]
https://github.com/mgp25/Instagram-API/issues/1845
