### ISSUE TITLE
checkpoint_required + user-agent value?

### ISSUE THREAD

**Issue by Zazo0** [mgp25/Instagram-API#2010]
Linked with this one:
https://github.com/mgp25/Instagram-API/issues/1512

The problem is you provide android user-agents only but the user can login for example on iOS or PC/Mac:
https://pics.me.me/suspicious-login-attempt-grabtsevo-krutitsy-belaya-kaptevka-odnogo-chestva-android-25382532.png

**Comment by mgp25** [comment]
### [F.A.Q. - What does "checkpoint_required" error mean?](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean)

- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!

**Comment by Zazo0** [comment]
@mgp25 thanks for explanation
