### ISSUE TITLE
How to check for bad password exception?

### ISSUE THREAD

**Issue by dunky11** [mgp25/Instagram-API#2012]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Hello, i have the following code:

```php
$ig = new \InstagramAPI\Instagram( true, false );
 
try {
     $ig->login( "my_correct_email@email.de", "my_wrong_password" );
 } catch (\InstagramAPI\Exception\InstagramException $e ) {
     echo 'Something went wrong: ' . $e->getMessage()."\n";
 }
```

I want to check if the password was correct. Logging in with the wrong email throws an exception, so does without a password. But when i enter the wrong password i don't get an exception, how can i check that the password was correct?

thanks for any help in advance!

**Comment by mgp25** [comment]
Hello @dunky11,

It is explained in the login documentation in the source code. But testing it takes about 20 seconds. It returns `InstagramAPI\Response\LoginResponse`. Thats how you can check it

Regards
