### ISSUE TITLE
No session cookie was found

### ISSUE THREAD

**Issue by aleks63** [mgp25/Instagram-API#2013]
`Fatal error: Uncaught RuntimeException: No session cookie was found. in /vendor/mgp25/instagram-php/src/Realtime/Mqtt/Auth.php:54`

**Comment by mgp25** [comment]
You should post what code did you use and so. As the error says, `No session cookie was found`. Check your folder permissions and so.

Regards

**Comment by szokeptr** [comment]
This is indeed a real issue. The InstagramAPI\Realtime\Mqtt\Auth::getPassword() method, should now also check for the sessionid cookie on the .instagram.com domain too, not only i.instagram.com.
