### ISSUE TITLE
Capture instagram publications and comment

### ISSUE THREAD

**Issue by GuilhermeHumberto** [mgp25/Instagram-API#2014]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Firstly, I would like to congratulate those responsible for the dedication in updating the code and keeping it working.

I wonder if there is any updated way to capture the latest posts from an instagram and comment on a specific photo.

Tks for listening.

**Comment by mgp25** [comment]
Yes, it is possible.

Regards

**Comment by GuilhermeHumberto** [comment]
could you help me? You scored as a duplicate but did not find a topic similar to my question.

**Comment by mgp25** [comment]
It is explained in the [wiki](https://github.com/mgp25/Instagram-API/wiki)

Regards
