### ISSUE TITLE
how can i check password after successful login if that changed?

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2015]
### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

After successful login into account, i change my password and when i try to login again i don't get password is incorrect, i'm using database as storage and i truncate all tables which i stored data into them, before trying to login with incorrect password, for example:

function to login:

    public function check()
    {
        $username = 'my-acount';
        $password = 'sss'; // wrong password after successful login and try login-resume again

        $ig = new InstagramHelper();

        try {
            $output = $ig->loginIntoInstagram($username, $password, '');
            dd($output);
        } catch (\Exception $e) {
            echo 'Something went wrong: ' . $e->getMessage() . "\n";
            exit(0);
        }
    }

and class helper to use your library:

```
use InstagramAPI\Instagram;
class InstagramHelper extends Instagram
{
    protected $ig;

    public function __construct()
    {
        set_time_limit(0);
        date_default_timezone_set('UTC');

        Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

        $this->ig = new Instagram(false, false, [
            'storage' => 'mysql',
            'dbhost' => env('DB_HOST'),
            'dbname' => env('DB_DATABASE'),
            'dbusername' => env('DB_USERNAME'),
            'dbpassword' => env('DB_PASSWORD'),
            'dbtablename' => env('INSTAGRAM_DATA')
        ]);
        parent::__construct();
    }

    public function loginIntoInstagram($username, $password, $proxy = '')
    {
        $ig = $this->_loginIntoInstagram($username, $password, $proxy);

        // if instagram can't login to account and return error
        if (is_array($ig) && isset($ig['state'])) {
            return [
                "text" => $ig['text'],
                "state" => "error",
            ];
        }

        $info = $ig->people->getSelfInfo();

        if ($info->getStatus() != "ok") { // if username or password is not valid
            ...
        } else { // can be login into instagram account
            ...
        }
    }

    public function _loginIntoInstagram($username, $password, $proxy = '')
    {
        try {
            $ig = $this->loader($username, $password, $proxy);
            $ig->login($username, $password);

            $currentUser = InstagramAccount::whereUsername($username)->first();
            if ($currentUser != null) {
                $currentUser->checkpoint = 1;
                $currentUser->save();
            }

            return $ig;
        } catch (\Exception $e) {
            return [
                "text" => $this->getInstagramMessage($e->getMessage()),
                "state" => "error",
            ];
        }
    }

    public function loader($username, $password, $proxy = "")
    {
        $this->ig->_setUser($username, $password);

        $this->setVerifySSL(false);

        if ($proxy != "") {
            $this->setProxy($proxy);
        }
        return $this;
    }
}
```

**Comment by mgp25** [comment]
Does Instagram app lets you know if the password is wrong when you have already an existing session? It doesn't, right? The same happens here.

It is true, that certain requests such as uploading media will throw an error if it requires a relogin in order to authenticate in case that the password has changed.

Best way to check if password has changed, is loging in.

Regards

**Comment by Mrp12** [comment]
@mgp25 your mean is this session created by instagram that's right?
