### ISSUE TITLE
get badge notifications count from BadgeNotificationsResponse

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2016]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---

in this part of library from [this link](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Account.php#L627) we have `getBadgeNotifications` function

now after successful login i have this result and i want to get count of badge notifications, but i cant do that, where is this count and how can i get that?

```
BadgeNotificationsResponse {#2593 ▼
  +httpResponse: Response {#2689 ▶}
  -_compiledPropertyMapLink: & array:4 [▼
    "status" => PropertyDefinition {#1078 ▶}
    "message" => PropertyDefinition {#1079 ▼
      +arrayDepth: 0
      +propType: null
      +isObjectType: false
    }
    "_messages" => PropertyDefinition {#1080 ▼
      +arrayDepth: 1
      +propType: "InstagramAPI\Response\Model\_Message"
      +isObjectType: true
    }
    "badge_payload" => PropertyDefinition {#2607 ▼
      +arrayDepth: 0
      +propType: "InstagramAPI\Response\Model\UnpredictableKeys\CoreUnpredictableContainer"
      +isObjectType: true
    }
  ]
  -_objectData: array:1 [▼
    "status" => "ok"
  ]
}
```

my code is:

```
$acc = new Account($ig);
dd($acc->getBadgeNotifications()));
```

**Comment by mgp25** [comment]
Without posting debug log, this issue is considered invalid.

**Comment by Mrp12** [comment]
@mgp25 i'm sorry, which debug is your mean? my code to test that is very basic, login and try to get count of badge

**Comment by Mrp12** [comment]
@mgp25 debug log link:

https://pastebin.com/sTUS7bA7

**Comment by mgp25** [comment]
Fixed in latest commit: https://github.com/mgp25/Instagram-API/commit/422b6fa49dec9dd616f890b2a3c95191be303248

Regards
