### ISSUE TITLE
Using setBiography from Account class

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2017]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
 in Account class i'm trying to setBiography with this codes, but for all i get error

```
$ig = $this->login($username, $password);  // return successful login

$acc = new Account($ig);
dd($acc->setBiography('TESTING setBiography '));  // solution 1

dd(\InstagramAPI\Request\Account($ig)::setBiography('TESTING setBiography ')); // solution 2

dd(Account($ig)::setBiography('TESTING setBiography ')); // solution 3
```

**Comment by mgp25** [comment]
Please, read wiki, examples and closed issues before opening a new one.

**Comment by Mrp12** [comment]
@mgp25 ok i read again your library wiki and i know i should be call that with this format:


```
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
    $ig->account->setBiography("change biography from instagram api");
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
```

unfortunately i get this error:
`Something went wrong: Requested resource does not exist. `
