### ISSUE TITLE
Whats exactly $extradata parameter in Media->like() method?

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2019]
in this link of this function: https://github.com/mgp25/Instagram-API/blob/fbbceaa5299844adc94f0648abe20d1b80693099/src/Request/Media.php#L142

you say `$extraData (optional) Depending on the module name` whats exactly this parameter and how can i found more information about that?

**Comment by mgp25** [comment]
Depending where and how you did the like, the request changes a bit, see `_parseLikeParameters`
