### ISSUE TITLE
Re-login after message "login_required" returned in the first login

### ISSUE THREAD

**Issue by mkanker** [mgp25/Instagram-API#202]
Hi,
I was checking about the code, I guess this part could make a loop, or not?
In which situation they ask the cookie in the login? Because the goal here is to send the cookie in the second attempt, right?

`if(isset($check['message']) && $check['message'] == 'login_required')
{
     $this->login(true);
}`

**Comment by mgp25** [comment]
@mkanker if you have a cookie and you are try to logging but receive as response `login_required` que force a login replacing your cookies and session with a new ones

Regards
