### ISSUE TITLE
Get specific media comments on paginate userFeed

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2020]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other
---

in one of my post in instagram i have some commets which user posted for my post, now i'm trying to get this list with paginating `getUserFeed`

i can find two issue like with my problem, but they aren't helpful for me

1) https://github.com/mgp25/Instagram-API/issues/1956
2) https://github.com/mgp25/Instagram-API/issues/684

and this part of `Media` class:

https://github.com/mgp25/Instagram-API/blob/fbbceaa5299844adc94f0648abe20d1b80693099/src/Request/Media.php#L368

now after read all of them i can't get this list of media comments

```php
$userId = $ig->people->getUserIdForName('MY_PAGE');
$maxId = null;
do {
    $response = $ig->timeline->getUserFeed($userId, $maxId);
    foreach ($response->getItems() as $item) {
        //print_r(  $item->getComments($item->getId())  );
        //print_r(  $item->getComments()  );
        //print_r(  $item->media->getComments($item->getId())  );
        //print_r(  $item->getMedia()->getComments($item->getId())  );
    }
    $maxId = $response->getNextMaxId();
    echo "Sleeping for 5s...\n";
    sleep(5);
} while ($maxId !== null); 
```

**Comment by mgp25** [comment]
To get and paginate comments you need to use `Media::getComments()` function. This function needs the `media_id` and additionally you can pass:

```php
     * @param array  $options An associative array of optional parameters, including:
     *                        "max_id" - next "maximum ID" (get older comments, before this ID), used for backwards pagination;
     *                        "min_id" - next "minimum ID" (get newer comments, after this ID), used for forwards pagination;
     *                        "target_comment_id" - used by comment Push notifications to retrieve the page with the specific comment.
     *
```

And as your code shows, here is a lack of understanding how PHP and even the API works. You are calling `media` or `getComments()` from an object that has no relation to the class or function itself, and that doesn't make any sense.

`$ig->media->getComments($mediaId);` is the proper way to do it.

I would recommend you looking these examples before continuing with the API:

- [Examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
