### ISSUE TITLE
Private post shortcodes produce a non suitable media_id with InstagramID::fromCode

### ISSUE THREAD

**Issue by koso00** [mgp25/Instagram-API#2022]
While i was using the api i encountered this problem.
If i feed a private post shortcode, that looks like this : Bjt2qFJnxspZiO1ISO5JKDE_BQi1xgK8EofetY0
The instagramID::fromCode respond with a long media id, not working

**Comment by mgp25** [comment]
@koso00 post code

**Comment by koso00** [comment]
This is the media_id that the InstagramID produces
672087672314592236660760677360602325100217528396177323779164603078196

**Comment by mgp25** [comment]
@koso00 I am asking about the code you used, not the output.

**Comment by koso00** [comment]
```
$code = "Bjt2qFJnxspZiO1ISO5JKDE_BQi1xgK8EofetY0";
$id = new \InstagramAPI\InstagramID();
$r =  $id->fromCode($code);
echo $r;
```

**Comment by mgp25** [comment]
If I remember well, private posts have a different shortcode. The real one should be just the last part:

```php
$code = "BQi1xgK8EofetY0";
$id = new \InstagramAPI\InstagramID();
$r =  $id->fromCode($code);
echo $r;
```

`Instagram id: 24343044635147206808753716`.

You will need to verify this, since I am not sure.

**Comment by koso00** [comment]
I love you man, checking right now

**Comment by koso00** [comment]
If i try to send it with Direct->sendPost it throws
`{"status":500,"error":"\"24343044635147206808753716\" is not a valid media ID."}`

**Comment by mgp25** [comment]
Remember that media id is composed by the media id and user id

**Comment by koso00** [comment]
Ok no, the real shortcode are the first 11 chars of the private shortcode, tested and working
