### ISSUE TITLE
How to specify "cursorId" for getPendingInbox() method?

### ISSUE THREAD

**Issue by ta4** [mgp25/Instagram-API#2023]
https://github.com/mgp25/Instagram-API/blob/fbbceaa5299844adc94f0648abe20d1b80693099/src/Request/Direct.php#L73

**Comment by koso00** [comment]
If i remember you will get the cursor calling getPendingInbox() the first time, then you can pass it as the attribute of the function.
Every time you call the function you will get the cursor for the pagination

**Comment by mgp25** [comment]
I don't know if `getPendingInbox()` is still used (I don't know). Nevertheless, the function has no argument to pass a `cursorId`. If you want, send debug log and I'll check it. You can also send debug log to my email.

Maybe you are looking for `getInbox()` instead?

Regards
