### ISSUE TITLE
get "DirectRankedRecipientsResponse" error when using login function

### ISSUE THREAD

**Issue by idanneeman** [mgp25/Instagram-API#2024]
Hi,
```php
$ig->login($username, $password); 
```
throw for me this error:
`InstagramAPI\Response\DirectRankedRecipientsResponse`
how to solve it?
thank you

**Comment by mgp25** [comment]
If you dont post debug log, this issue will be considered as invalid and will be closed.

**Comment by mgp25** [comment]
It works perfectly. Make sure you are using latest release or latest source from `dev-master`

Regards
