### ISSUE TITLE
Manually set full path via "\InstagramAPI\Media\Video\FFmpeg::$defaultBinary" doesn't work

### ISSUE THREAD

**Issue by Kolyanus** [mgp25/Instagram-API#2027]
I get that error in windows:
You must have FFmpeg to process videos. Ensure that its binary-folder exists in your PATH environment variable, or manually set its full path via `\InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/home/exampleuser/ffmpeg/bin/ffmpeg';` at the start of your script.

Before, when it was `\InstagramAPI\Utils::$ffmpegBin` - everything worked perfectly.

Now I  set path to `ffmpeg.exe` in  `\InstagramAPI\Media\Video\FFmpeg::$defaultBinary` and it shows this error. I tried to set path, path with/without `ffmpeg.exe`, different slashes, but no luck.

Is there a way without setting PATH environment variable?

**Comment by mgp25** [comment]
Hello,

There are many guides that explain how to add bins to the PATH enviroment. Simply add this `;c:\ffmpeg\bin`. Or follow one of those guides.

Make sure you are using the correct path if adding it manually.

**Comment by Kolyanus** [comment]
Thanks, yes, I know how to add it to the PATH enviroment. But I want to write it in my script, not to enviroment. And I do it how it says - I add this string before: \InstagramAPI\Media\Video\FFmpeg::$defaultBinary = 'c:\ffmpeg\bin' and I get that error. I checked path  - it's correct, but this string doesn't work. String for mpeg probe works (has different answer - error, when I change it to the wrong path, for example), but this one for some reason doesn't.

**Comment by valga** [comment]
@Kolyanus It works just fine for me:
```php
\InstagramAPI\Media\Video\FFmpeg::$defaultBinary = 'D:\Programs\ffmpeg\ffmpeg-20180413-23e994c-win64-static\bin\ffmpeg.exe';
var_dump(\InstagramAPI\Media\Video\FFmpeg::factory()->version());
```
```
string(80) "ffmpeg version N-90704-g23e994ca49 Copyright (c) 2000-2018 the FFmpeg developers"
```

```

**Comment by Kolyanus** [comment]
As I see you have mistaken path, with ffmpeg.exe at the end,  but it has to be just path to folder, without ffmpeg.exe. I think it works for you because you have also PATH in enviroment variable. And it was set  when you installed FFmpeg.

**Comment by valga** [comment]
@Kolyanus Full path to ffmpeg is required. It means that `ffmpeg.exe` is required at the end of path.

Also, I did not install ffmpeg, I just unpacked some nightly build, so I don't have ffmpeg path in my `%PATH%` variable. But it works for me, so double check your path.

**Comment by Kolyanus** [comment]
Then I absolutely don't have idea what is wrong. I know, my path is 100% correct, I checked it 100 times, for example like this:
echo shell_exec('F:\ffmpeg.exe -h');
it get output from ffmpeg.exe.

**Comment by Kolyanus** [comment]
Eventually I've added path  to environment variable, and it still getting that error... I updated ffmpeg - and nothing. Why it worked before, and doesn't now?

**Comment by Kolyanus** [comment]
Thanks

**Comment by pulluramazan** [comment]
how do we run it on php server?
