### ISSUE TITLE
 Friendship Status not showing up

### ISSUE THREAD

**Issue by bisht-sanjeet** [mgp25/Instagram-API#2028]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

 I was playing around with this and found that response is missing very important thing when getting userinfo. 

I entered one of my friend pk id and in response I get all the details except for the friendship that was working on older version maybe on API version 2 or 3 haven't used it for a while. 
I see a new thing called 'is_bestie' can someone explain me what is this? 

Anyways tried with some friends id and non friends id but friendship is not showing up in response. 

I'm using this `$ig->people->getInfoById($user_pk)->getUser();`

Response is something like this and he is my friend 
```
         [_objectData:LazyJsonMapper\LazyJsonMapper:private] => Array
        (
            [pk] => 12313131233
            [username] => asdasdasd
            [full_name] => asdasdasdasd
            [is_private] => 
            [profile_pic_url] => https://scontent-lhr3-1.cdninstagram.com/vp/ca955a53fb7ac276a2522a87cb6adbbe/5BB6AEFF/t51.2885-19/s150x150/32587086_152410702282727_778590640626728960_n.jpg
            [profile_pic_id] => 1790882721678863606_123123123123
            [is_verified] => 
            [has_anonymous_profile_picture] => 
            [media_count] => 382
            [geo_media_count] => 0
            [follower_count] => 762
            [following_count] => 655
            [following_tag_count] => 0
            [biography] => Love with all your heart someday the love will find its way back to you and stay forever 💕❣️
            [external_url] => 
            [reel_auto_archive] => on
            [usertags_count] => 92
            [is_favorite] => 
            [has_chaining] => 1
            [hd_profile_pic_versions] => Array
                (
                    [0] => Array
                        (
                            [width] => 320
                            [height] => 320
                            [url] => https://scontent-lhr3-1.cdninstagram.com/vp/8008d4b407c3f8af4617a9f159538ffc/5BB579F2/t51.2885-19/s320x320/32587086_152410702282727_778590640626728960_n.jpg
                        )

                    [1] => Array
                        (
                            [width] => 640
                            [height] => 640
                            [url] => https://scontent-lhr3-1.cdninstagram.com/vp/1011b0ad89322245bdf9c215aba47af7/5BABFD9F/t51.2885-19/s640x640/32587086_152410702282727_778590640626728960_n.jpg
                        )

                )

            [hd_profile_pic_url_info] => Array
                (
                    [url] => https://scontent-lhr3-1.cdninstagram.com/vp/f1785110e2181e59f01da576c92f3937/5BC0214B/t51.2885-19/32587086_152410702282727_778590640626728960_n.jpg
                    [width] => 1046
                    [height] => 1046
                )

            [has_highlight_reels] => 1
            [include_direct_blacklist_status] => 1
            [school] => Array
                (
                )

            [is_bestie] => 
            [has_unseen_besties_media] => 
            [auto_expand_chaining] => 
        )
```

Can someone please help me with this? 

Thanks,
Sanjeet Bisht

**Comment by mgp25** [comment]
Hello, 

Use proper function to get friendship status.

See [/Request/People.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php)

Regards
