### ISSUE TITLE
 Help me find the right parameters for the instagram poll API

### ISSUE THREAD

**Issue by craftalpian** [mgp25/Instagram-API#2030]
hello mgp25, i am asking for your help in the poll feature in instagram story. when trying to decompile the latest instagram app, i found api 

> media/%s/%s/story_poll_vote/

 (not in php language). The full code like this:

`paramc = paramc.a("media/%s/%s/story_poll_vote/", new Object[] { paramString1, paramString2 });

    paramc.a.a("vote", String.valueOf(paramInt));

    paramc.a.a("radio_type", paramString3);

    paramc.o = new com.instagram.common.p.a.j(l.class);

    paramc.c = true;`

and I tried to send with code like the following:

`curl_setopt($ch, CURLOPT_URL, "https://i.instagram.com/api/v1/media/1797611407823568682/2/story_poll_vote/");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, 'ig_sig_key_version=4&signed_body=b38feca661cb65b7899814b215289b42da19b043b75a9ba9cae4e465866d7531.%7B%22vote%22%3A%222%22%2C%22radio_type%22%3A%22wifi-none%22%7D');
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');`

but the result is like this:

> {"message": "Invalid vote", "status": "fail"}

I believe that the first "%s" contains the media_id and the second "%s" contains the votes (between 1 and 2) as in the push.php file. (media/%s/%s/story_poll_vote/)

can you help me?
best regards, Alfian

**Comment by mgp25** [comment]
I recommend you checking API's debug log
