### ISSUE TITLE
Instagram only accepts non-rotated media. Your file "a.jpg" is either rotated or flipped or both.

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2035]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

What exactaly this error mean? that the photo was edited after taken and fliped or rotated? I never got an error like this on instagram app and i always rotate photos there...

I'm trying to upload a simple story and getting this error...

The image is 1080x1920 was never edited in any image editor (the only thing i did was to resize the original file to reduce the size) and i can normally upload the image through instagram app

I dont understand why i am getting this error on api can you provide more information

the code is simple as:

```
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

    $ig->login($username, $password);

	$ig->story->uploadPhoto('/home/rafa/Desktop/a.jpg');

```

**Comment by mgp25** [comment]
Hello @bolds07,

make sure to read the wiki and check the examples before opening an issue since all this is explained already.

Use this to prepare your media for story:

```php
    $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename, ['targetFeed' => \InstagramAPI\Constants::FEED_STORY]);
    $ig->story->uploadPhoto($photo->getFile(), $metadata);
```

Regards

**Comment by valga** [comment]
@bolds07 Your photo is either rotated or flipped with EXIF tag. Instagram ignores EXIF tags, so your photo might change its orientation after upload. See #1797 for an example.

We have a class that normalizes photo orientation automatically, so your photo will look exactly the same after upload.
