### ISSUE TITLE
TimelineFeedResponse

### ISSUE THREAD

**Issue by herrenail** [mgp25/Instagram-API#2036]
This message appears during login.
InstagramAPI\Response\TimelineFeedResponse: Checkpoint required.

If I log in again, I can log in.

Is it related to the acceptance of the Instagram New Terms? ( 6/11 IG update )

**Comment by mgp25** [comment]
[F.A.Q. - What does "checkpoint_required" error mean?](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean)
