### ISSUE TITLE
Videos prepared by the package doesn't get accepted by Instagram (too long)

### ISSUE THREAD

**Issue by x-yuri** [mgp25/Instagram-API#2037]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

I take your [example][example], pass it a long video. It cuts it to 1 min 0 s 27 ms (as reported by `mediainfo --fullscan`), and Instagram says:

[example]: https://github.com/mgp25/Instagram-API/blob/v4.1.0/examples/uploadVideo.php

> Failed to get photo details: Instagram only accepts timeline videos that are between 3.000 and 60.000 seconds long. Your video "INSTAVID_5AERz6" is 60.027 seconds long.

Well, I can see you passing `-t 60` to `ffmpeg`, but for some reason, I get extra milliseconds.

If you need the video file, can you recommend a way to provide it?

When I do

```
$ ffmpeg -i input.mp4 -ss 00:01:16 -c:v copy -c:a copy -t 60 output.mp4
```

I get only 1 extra ms.

**Comment by devdudeNL** [comment]
Have you tried `-t 59.999`?

**Comment by x-yuri** [comment]
`-t 59.999` gives same `1 min 0 s 27 ms`.

```
59.99  -> 1 min 0 s 1 ms
59.927 -> 59 s 960 ms
59.926 -> 59 s 931 ms
59.9   -> 59 s 927 ms
```

I believe it has something to do with keyframes.
