### ISSUE TITLE
Getting null on some fields when i search tag

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2038]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---
After reading all sample codes, wiki and issues i can't find any solution about this problem

when i try to search some tags like with this code:

`$ig->hashtag->search('cats');`

i get this result:

    "results" => array:30 [▼
      0 => array:11 [▼
        "id" => "17843930926043558"
        "name" => "cats"
        "media_count" => 66000236
        "follow_status" => null
        "following" => null
        "allow_following" => null
        "allow_muting_story" => null
        "profile_pic_url" => null
        "non_violating" => null
        "related_tags" => null
        "debug_info" => null
      ]

how can i get `profile_pic_url`, `follow_status`, `following`, `allow_following` from that?

BTW `getInfo()` return null too and don't have some method to get this items
Thanks in advance

**Comment by mgp25** [comment]
Hello @Mrp12,

these properties will be added in the 42 pull request (https://github.com/mgp25/Instagram-API/pull/2006) (probably will be added soon). You should always provide debug log when opening an issue. Instagram's response although contains these properties, their values are not set.

Regards

**Comment by Mrp12** [comment]
after updating Tag classes from your commit, searching tag using this url:

https://i.instagram.com/api/v1/tags/search/?timezone_offset=0&q=cats&count=30

after testing this `url` on browser i return `null` for some fields
