### ISSUE TITLE
cant run livestream on vps (centos) 

### ISSUE THREAD

**Issue by iranilord** [mgp25/Instagram-API#2039]
hi
after i use default livestream on example folder and set my login information
when i run it i get this error
-----------------------
Something went wrong: You must have FFmpeg to process videos. Ensure that its binary-folder exists in your PATH environment variable, or manually set its full path via "\InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/home/exampleuser/ffmpeg/bin/ffmpeg';" at the start of your script.
--------------------
i installed ffmpeg by epels on my vps 
/usr/bin/ffmpeg 
so i set 
---------
$ffmpeg = \InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/usr/bin/ffmpeg' ;
--------
after this i run script again now i get this error
----------
PHP Fatal error:  Call to a member function runAsync() on string in /root/examples/......
-----------
now i don't know what to do !!
sorry for my english :)

**Comment by mgp25** [comment]
Well, you are doing this:

```php
$ffmpeg = \InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/usr/bin/ffmpeg';

    $broadcastProcess = $ffmpeg->runAsync(sprintf(
        '-rtbufsize 256M -re -i %s -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv %s',
        \Winbox\Args::escape($videoFilename),
        \Winbox\Args::escape($streamUploadUrl)
    ));
```

And the error is exactly what you are doing. Trying to call `runAsync()` on a string, because the value of `$ffmpeg` is not an object like is supposed to, and instead is a string.

Instead use the example we provide with a valid path to the bin:

```php
    // Get FFmpeg handler and ensure that the application exists on this system.
    // NOTE: You can supply custom path to the ffmpeg binary, or just leave NULL
    // to autodetect it.
    $ffmpegPath = null;
    $ffmpeg = \InstagramAPI\Media\Video\FFmpeg::factory($ffmpegPath);
```

Regards

**Comment by iranilord** [comment]
@mgp25 
tnx for your answer 
now i remove this 
$ffmpeg = \InstagramAPI\Media\Video\FFmpeg::factory($ffmpegPath);
and replaced with this 
    $ffmpegPath = null;
    InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/usr/bin/ffmpeg';
but now iget erorr
PHP Notice:  Undefined variable: ffmpeg in /root/examples/liveBroadcast.php on line 59
PHP Fatal error:  Call to a member function runAsync() on null in /root/examples/liveBroadcast.php on line 59

sry im very amatur :)

**Comment by mgp25** [comment]
Maybe you got me wrong.

Use the script as it is without any modification and add your ffmpeg bin path to `$ffmpegPath`.  Your questions are PHP related not API.

Or the same script without modification but adding:
```php
InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/home/exampleuser/ffmpeg/bin/ffmpeg';
```
Regards

**Comment by iranilord** [comment]
ommm add ffmpeg bin path to $ffmpegPath
 $ffmpegPath = '/usr/bin/ffmpeg' ;
    $ffmpeg = \InstagramAPI\Media\Video\FFmpeg::factory($ffmpegPath);
now i get new error
Something went wrong: It seems that the path to ffmpeg binary is invalid. Please check your path to ensure that it is correct.
but path in true !!
