### ISSUE TITLE
Can't start PushReceiver through proxy

### ISSUE THREAD

**Issue by nobilik** [mgp25/Instagram-API#2043]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

$username = '';
$password = '';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

 $ig->setProxy("https://login:pass@host:port");
$loop = \React\EventLoop\Factory::create();
if ($debug) {
    $logger = new \Monolog\Logger('push');
    $logger->pushHandler(new \Monolog\Handler\StreamHandler('php://stdout', \Monolog\Logger::INFO));
} else {
    $logger = null;
}
$push = new \InstagramAPI\Push($loop, $ig, $logger);
$push->on('incoming', function (\InstagramAPI\Push\Notification $push) {
    printf('%s%s', $push->getMessage(), PHP_EOL);
});
$push->on('like', function (\InstagramAPI\Push\Notification $push) {
    printf('Media ID: %s%s', $push->getActionParam('id'), PHP_EOL);
});
$push->on('comment', function (\InstagramAPI\Push\Notification $push) {
    switch ($push->getActionPath()) {
        case 'comments_v2':
            $mediaId = $push->getActionParam('media_id');
            $commentId = $push->getActionParam('target_comment_id');
            break;
        case 'media':
        default:
            $mediaId = $push->getActionParam('id');
            $commentId = $push->getActionParam('forced_preview_comment_id');
    }
    printf(
        'Media ID: %s. Comment ID: %s.%s',
        $mediaId,
        $commentId,
        PHP_EOL
    );
});
$push->on('direct_v2_message', function (\InstagramAPI\Push\Notification $push) {
    printf(
        'Thread ID: %s. Thread item ID: %s.%s',
        $push->getActionParam('id'),
        $push->getActionParam('x'),
        PHP_EOL
    );
});
$push->on('error', function (\Exception $e) use ($push, $loop) {
    printf('[!!!] Got fatal error from FBNS: %s%s', $e->getMessage(), PHP_EOL);
    $push->stop();
    $loop->stop();
});
$push->start();
$loop->run();
```

Error Log/var_dump:

```php
[2018-06-19 14:52:33] push.INFO: Starting FBNS client... [] []
[2018-06-19 14:52:33] push.INFO: Setting up reconnect timer to 1 seconds. [] []
php > $loop->run();
[2018-06-19 14:52:40] push.INFO: Connecting to mqtt-mini.facebook.com:443... [] []
[2018-06-19 14:52:45] push.ERROR: Connection timed out after 5 seconds. [] []
[2018-06-19 14:52:45] push.INFO: Setting up reconnect timer to 2 seconds. [] []
[2018-06-19 14:52:47] push.INFO: Connecting to mqtt-mini.facebook.com:443... [] []
[2018-06-19 14:52:52] push.ERROR: Connection timed out after 5 seconds. [] []
[2018-06-19 14:52:52] push.INFO: Setting up reconnect timer to 4 seconds. [] []
[2018-06-19 14:52:56] push.INFO: Connecting to mqtt-mini.facebook.com:443... [] []
[2018-06-19 14:53:01] push.ERROR: Connection timed out after 5 seconds. [] []
[2018-06-19 14:53:01] push.INFO: Setting up reconnect timer to 8 seconds. [] []

....etc
```

### Describe your issue
Hi! 
I'm trying to start Push Receiver through proxy, but it can't connect to mqtt-mini.facebook.com:443. Without proxy all works well. I tried 10 different proxies, but result is the same. Other actions works with these proxies (I can send direct messages). Thanks!

**Comment by valga** [comment]
@nobilik Quite unfortunately you can't use HTTPS proxy with Realtime and FBNS clients, because PHP doesn't allow nested SSL encryption for its streams. We can't do anything with that, so you should switch to HTTP or SOCKS proxy.
