### ISSUE TITLE
Item-Caption Issue

### ISSUE THREAD

**Issue by nhalstead** [mgp25/Instagram-API#2046]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) - Found here back from Oct 2017 #1612
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ) - 
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki) - Does not Include section for `$ig->timeline->getUserFeed($uid)->getItems()[0]->getCaption()->getText()`
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples) - Nothing Relayed
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation) - "mgp25/instagram-php": "^4.1"

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Example Code:

```php
function getUserPosts($username){
  global $ig;
  $mediaFiles = array(); // Reset queue.
  $maxId = null;

  //$f = getUserFeed($username);
  $uid = getUserId($username);// Converts from Username to UserId
  $timeline = $ig->timeline->getUserFeed($uid);

  //print_r($timeline);

  /**
   * Each Item is an Item Class Instance
   * @link https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php#L416
   * @see https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/Item.php
   */
   //print_r($f->items);
  foreach ($timeline->getItems() as $item) {
    $itemDate = date('Y-m-d \a\t H.i.s O', $item->getTakenAt());
    if ($item->getMediaType() == InstagramAPI\Response\Model\Item::ALBUM) {
        // Albums contain multiple items which must all be queued.
        // NOTE: We won't name them by their subitem's getIds, since
        // those Ids have no meaning outside of the album and they
        // would just mean that the album content is spread out with
        // wildly varying filenames. Instead, we will name all album
        // items after their album's Id, with a position offset in
        // their filename to show their position within the album.
        $subPosition = 0;
        foreach ($item->getCarouselMedia() as $subItem) {
            ++$subPosition;
            if ($subItem->getMediaType() == InstagramAPI\Response\Model\CarouselMedia::PHOTO) {
                $mediaUrl = $subItem->getImageVersions2()->getCandidates()[0]->getUrl();
            } else {
                $mediaUrl = $subItem->getVideoVersions()[0]->getUrl();
            }
            $subItemId = sprintf('%s [%s-%02d]', $itemDate, $item->getId(), $subPosition);
            $mediaFiles[$subItemId] = [
                'taken_at' => $item->getTakenAt(),
                'url'      => $mediaUrl,
            ];
        }
    } else {
        if ($item->getMediaType() == InstagramAPI\Response\Model\Item::PHOTO) {
            $mediaUrl = $item->getImageVersions2()->getCandidates()[0]->getUrl();
        } else {
            $mediaUrl = $item->getVideoVersions()[0]->getUrl();
        }
        $itemId = sprintf('%s [%s]', $itemDate, $item->getId());
        $mediaFiles[$itemId] = [
          'caption' => $item->getCaption()->getText(),
          'taken_at' => $item->getTakenAt(),
          'comments_count' => $item->getCommentCount(),
          'url'      => $mediaUrl,
        ];
    }
  }
```

Error Log/var_dump:
```php
Fatal error: Uncaught Error: Call to a member function getText() on null in C:\Users\~~\src\download.php:129 Stack trace: #0 C:\Users\~~\src\download.php(153): getUserPosts('xyzusername') #1 {main} thrown in C:\Users\nhalstead\~~\src\download.php on line 129
```

---

### Describe your issue

The problem I am getting I am unable to access the captions text data. Now when I can print_r it I can see the raw data is being taken in by the lazyJsonMapper but the method getText() is not working.

I am currently running with composer set to `"mgp25/instagram-php": "^4.1"` so I am not running the dev branch.

> ### print_r($item->getCaption())
> ![image](https://user-images.githubusercontent.com/5577816/41638969-00c953b4-742a-11e8-8a05-109c3f4cbefe.png)

**Comment by mgp25** [comment]
Post debug log

**Comment by nhalstead** [comment]
The Only Error I receive is the following
```php 
Fatal error:  Uncaught Error: Call to a member function getText() on null in C:\Users\~~\src\download.php:130
  Stack trace:
  #0 C:\Users\~~\src\download.php(154): getUserPosts('noah0h')
  #1 {main}
  thrown in C:\Users\~~\src\download.php on line 130


```
If you want the server, it will be the same issue
```php
[Wed Jun 20 13:57:53.304594 2018] [php7:error] [pid 10748:tid 1332] [client 127.0.0.1:16009] PHP Fatal error:  Uncaught Error: Call to a member function getText() on null in C:\\Users\\nhalstead\\Documents\\GitHub\\Instagram_Scraper\\src\\download.php:130\nStack trace:\n#0 C:\\Users\\nhalstead\\Documents\\GitHub\\Instagram_Scraper\\src\\download.php(154): getUserPosts('noah0h')\n#1 {main}\n  thrown in C:\\Users\\nhalstead\\Documents\\GitHub\\Instagram_Scraper\\src\\download.php on line 130
```
Then the code stops.

**Comment by mgp25** [comment]
Not all media items have set the `caption` field. One of the items has `'caption':null` and therefore when you are doing:

```php
$item->getCaption()->getText(),
```

You are trying to call `getText()` on a `null` value. Instead you can do something like:


```php
          'caption' => ($item->getCaption()->getText() === null) ? null : $item->getCaption()->getText(),
```

**Comment by nhalstead** [comment]
Thanks. I'll have to remember that when I run into an issue with this library.

The code that you have send me above does not work as expected as it still throws an error and halts but expanding off of what you are doing I did write a function to handle it and get the caption by matching the class type.
```php
/**
 * Get the Caption if the Instance matches as a Caption
 *
 * @link https://github.com/mgp25/Instagram-API/issues/2046
 * @param InstagramAPI\Response\Model\Caption Post to Pull from
 * @return String The Caption
 */
function tryCaption($i){
  if(@get_class($i) == "InstagramAPI\Response\Model\Caption"){
    return $i->getText();
  }
  else{
    return "";
  }
}
``` 
> **NOTE**: The @ symbol is suppressing the error from `get_class` when `null` is passed to it via $i.

I believe to make your code work the way intended it would be the following (below), as `->getCaption()` would be `null` since `->getText` throws an error for not existing despite being a method from `InstagramAPI\Response\Model\Caption`.
```php
'caption' => ($item->getCaption() === null) ? null : $item->getCaption()->getText(),
```

**Comment by mgp25** [comment]
Yes, that was what I meant 😄 Hope you caught the idea.

Regards
