### ISSUE TITLE
/feed/tag/ how to pagination?

### ISSUE THREAD

**Issue by Bupyc** [mgp25/Instagram-API#205]
/feed/tag/ - max_id
I have next_max_id but, if i send it in max_id - instagram get me same page.
If i send to instagram max_id (PK or 1 or id from id_userid) instagram dont get me data.

How pagination it? I try send id_userid but isnt work too.

**Comment by RageBrahimi** [comment]
Use `getHashtagFeed($hashtagString, $maxid = null)` instead. Input the value of `next_max_id` in `$maxid`
