### ISSUE TITLE
[Critical] Bug found. SetProxy does not set proxies

### ISSUE THREAD

**Issue by emarudee** [mgp25/Instagram-API#2052]
I am using latest dev-master version.

Test this code
You will see that 
```php
$ig->setProxy($proxy_bad);
$res = $ig->request($url)->setNeedsAuth(false)->getResponse($reps);
```
Will not throw any error and will use `$proxy_ok` variable.

```php
<?php

require_once "vendor/autoload.php";


class R extends \InstagramAPI\Response {
    public function isOk() {
        return true;
    }
}


$proxy_ok = 'user187:Oxrh5Rf5@92.222.181.232:10187'; // working proxy
$proxy_bad = 'user651447:AsCHLtEL@51.255.171.653:11447'; //wrong ip proxy

$url = 'https://api.myip.com';

$ig = new \InstagramAPI\Instagram();
$ig->settings->setActiveUser('test');

$reps = new R();



var_dump('Test proxy via mgp25:' , $ig->getProxy());
$ig->setProxy($proxy_ok);
$res = $ig->request($url)->setNeedsAuth(false)->getResponse($reps);
var_dump('Result:', $res->asArray());


var_dump('Test proxy via mgp25:' , $ig->getProxy());
$ig->setProxy($proxy_bad);
$res = $ig->request($url)->setNeedsAuth(false)->getResponse($reps);
var_dump('Result:', $res->asArray());



$ig = new \InstagramAPI\Instagram();
$ig->settings->setActiveUser('test');

var_dump('Test 2 proxy via mgp25:' , $ig->getProxy());
$ig->setProxy($proxy_bad);
$res = $ig->request($url)->setNeedsAuth(false)->getResponse($reps);
var_dump('Result:', $res->asArray());




var_dump('Test proxy via guzzle:' , $proxy_ok);
$client = new \GuzzleHttp\Client();
$res = $client->request('GET', $url, ['proxy' => $proxy_ok]);
var_dump('Result:', $res->getBody());


var_dump('Test proxy via guzzle:' , $proxy_bad);
$client = new \GuzzleHttp\Client();
$res = $client->request('GET', $url, ['proxy' => $proxy_bad]);
var_dump('Result:', $res->getBody());



var_dump('Test 2 proxy via guzzle:' , $proxy_bad);
$client = new \GuzzleHttp\Client();
$client->request('GET', $url, ['proxy' => $proxy_ok]);
$res = $client->request('GET', $url, ['proxy' => $proxy_bad]);
var_dump('Result:', $res->getBody());





$conf = [
    10036 => 'GET',
    10002 => $url,
    10004 => $proxy_ok
];

$handle = curl_init();

curl_setopt_array($handle, $conf);

var_dump('Test proxy via curl:' ,$proxy_ok);
var_dump('Result:', curl_exec($handle) );



$conf[10004] = $proxy_bad;

$handle = curl_init();

curl_setopt_array($handle, $conf);

var_dump('Test proxy via curl:' ,$proxy_bad);
var_dump('Result:', curl_exec($handle) );
```

**Comment by emarudee** [comment]
I am using your latest master-dev version. However tried on stable - the same thing.
It seems setProxy take effect only after request call made.


$ig->setProxy($proxy_bad);
$res = $ig->request('http://127.0.0.1')->setNeedsAuth(false)->getResponse($reps); // uses previous $proxy_ok
$res = $ig->request($url)->setNeedsAuth(false)->getResponse($reps); // uses $proxy_bad and throws error

This way it changes proxy on my request. 



This was my installation:
```
wget https://raw.githubusercontent.com/mgp25/Instagram-API/master/Dockerfile
sed -i -e "s/RUN composer install --prefer-source --no-interaction/#RUN composer install --prefer-source --no-interaction/" Dockerfile
docker build -t mgp25 .
docker run -it mgp25 bash
composer require mgp25/instagram-php dev-master
```

**Comment by emarudee** [comment]
I have pretty old version too. Its working fine there. This bug is not present in this version.
The bug appears only in latest dev-master and stable versions.

"name": "mgp25/instagram-php",

            "version": "dev-master",

            "source": {

                "type": "git",

                "url": "https://github.com/mgp25/Instagram-API.git",

                "reference": "efdbc694a0e3d401ea1fe90ada7e159ea4d32cd1"

            },

            "dist": {

                "type": "zip",

                "url": "https://api.github.com/repos/mgp25/Instagram-API/zipball/efdbc694a0e3d401ea1fe90ada7e159ea4d32cd1",

                "reference": "efdbc694a0e3d401ea1fe90ada7e159ea4d32cd1",

                "shasum": ""

            },

**Comment by valga** [comment]
@emarudee That's the way how cURL works:

```php
$conf = [
    10036 => 'GET',
    10002 => $url,
    10004 => $proxy_ok
];

$handle = curl_init();

curl_setopt_array($handle, $conf);

var_dump('Test proxy via curl:' ,$proxy_ok);
var_dump('Result:', curl_exec($handle) );

$conf[10004] = $proxy_bad;

curl_reset($handle);

curl_setopt_array($handle, $conf);

var_dump('Test proxy via curl:' ,$proxy_bad);
var_dump('Result:', curl_exec($handle) );
```

It reuses already opened connection with proxy even when the proxy is changed. Just create a new `Instagram` object every time you want to change a proxy, like you did with Guzzle and curl handle in your code.

**Comment by Stiveknx** [comment]
@valga 

After https://github.com/mgp25/Instagram-API/commit/fa6057c16d7ab646abf2a943254edcce4ef3c04d
I still need to create a new instagram object when I try to change some proxy?

**Comment by valga** [comment]
@Stiveknx You can safely change proxies after that commit, but I would not recommend reusing the same `Instagram` object for different accounts.
