### ISSUE TITLE
Question: follow response

### ISSUE THREAD

**Issue by phenoengine** [mgp25/Instagram-API#2056]
Hello again!
Got issue with following users. Call `$friendship = $ig->people->follow($some_id_here)`, but follow counter in instagram account doesnt increase. Checked `$friendship->getStatus()` - it is okay, `$friendship->getMessage()` is also empty. No exceptions or smth strange.
Any ideas why follow function doesnt work as expected?

Thanks in advance! Response below.

**POST:  https://i.instagram.com/api/v1/friendships/create/7792990817/
DATA: signed_body=2b9634b3e6329ec69d956f144048c95e8ea43c7766cea8e15ca45c271848bb38.{"_csrftoken":"FhXkNnqJ25TidQlpBEZPogPSQOslFo5r","user_id":"7792990817","radio_type":"wifi-none","_uid":"7874677761","_uuid":"b1f2f820-e757-460d-826e-2dcc294e9811"}&ig_sig_key_version=4
← 200 	 130B
RESPONSE: {"friendship_status": {"following": false, "followed_by": false, "blocking": false, "muting": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "status": "ok"}**

**Comment by mgp25** [comment]
Probably detected as a spammer/bot or flagged IP. I can confirm this works.

Regards
