### ISSUE TITLE
About the checkpoint_required error.

### ISSUE THREAD

**Issue by torv** [mgp25/Instagram-API#2059]
Dear Mr. Manager.

I have read the FAQ about checkpoint error. It's IP problem and re-login by official app will be fix.
But I still want to fix by api, and I know we should send a confirm email to user and then enter a confirm code. should fix this.
But I check your commit history, you had ever make some code for checkpoint and sendConfirmEmail, then remove the code later. Is it not work well?

**Comment by mgp25** [comment]
Hello @torv,

We don't give support for that anymore. Legit API users don't need checkpoint thing at all as explained in the F.A.Q.

Regards
