### ISSUE TITLE
Not getting Album Push Notification

### ISSUE THREAD

**Issue by gmacdev** [mgp25/Instagram-API#2061]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Example Code:

```php
       //get Post Notifications(Follow the user 1st)
            $receiverID = $ig->people->getUserIdForName($receiverUsername);
            $ig->people->follow($receiverID);
            // make a receiver fav so you get it's post notification
            $ig->people->favorite($receiverID);

            $loop = \React\EventLoop\Factory::create();
            if ($debug) {
                $logger = new \Monolog\Logger('push');
                $logger->pushHandler(new \Monolog\Handler\StreamHandler('php://stdout', \Monolog\Logger::INFO));
            } 
            else {
              $logger = null;
          }

          $push = new \InstagramAPI\Push($loop, $ig, $logger);

          $push->on('post', function (\InstagramAPI\Push\Notification $push) {
            $messageRes = $push->getMessage();
            var_dump($messageRes);
            $mediaID = $push->getActionParam('id');
            var_dump($mediaID);
        });


          $push->on('error', function (\Exception $e) use ($push, $loop) {
            printf('[!!!] Got fatal error from FBNS: %s%s', $e->getMessage(), PHP_EOL);
            $push->stop();
            $loop->stop();
        });
          $push->start();
          $loop->run();
```

### Describe your issue

Is it possible to get push(post) notifications of an album(multiple images and/or videos) upload? 
I've been successful in getting the image & video push notification but when I upload an album I didn't get any log realted to the album upload in command line using the above code.
Is there any other way possible to get to know when a user post an album? (incoming or post event doesn't give any logs)
Ps: Thanks for making this amazing library.

**Comment by valga** [comment]
@gmacdev Can you receive a notification about new albums on your phone with the real Instagram app?

**Comment by valga** [comment]
@gmacdev Well, our library is basically a copy of the real app. So if you can't receive a notification about new album with the real app, you can't do that with our library.

But good thing is you can [report the problem to Instagram](https://help.instagram.com/381579045265733?helpref=page_content) and they might help you with it. I mean the problem with the app, not with our library.
