### ISSUE TITLE
[Question] from instagram web url to MediaId

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2063]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

I want to run checks on specific posts based on user input, so i need somehow let the user input the post he wants to be checked.

Instagram App does not provide (as long as i know) any way to user get media_id and foward this information... so in order to let user select one specific post to run my script i would need to implement a whole client (not really a good solution)

the plan B is to work with the instagram weburl ex: https://www.instagram.com/p/BkEXqsVA79F/

Instagram browser version allow users to access its media using alphanumeric indexes as `BkEXqsVA79F`

Is there any way to convert `BkEXqsVA79F` to the media_id so i can use inside the api?

**Comment by Alfredao** [comment]
Theres a hack for this. It is not the best way but it could help you

```php
<?php
$data   = file_get_contents('https://www.instagram.com/p/BkEXqsVA79F/');
$split1 = explode("window._sharedData =", $data);
$split2 = explode(";</script>", $split1[1]);

$result = json_decode(html_entity_decode($split2[0]), true);
$media  = $result['entry_data']['PostPage'][0]['graphql']['shortcode_media'];

var_dump($media['shortcode'], $media['id']);
```

So you'll have this as output

/mnt/c/p21/sistemas/web/apache/localhost/www/sharedData.php:9:string 'BkEXqsVA79F' (length=11)
/mnt/c/p21/sistemas/web/apache/localhost/www/sharedData.php:9:string '1802669839740026693' (length=19)

**Comment by Alfredao** [comment]
Theres a hack for this. It is not the best way but it could help you

```php
<?php
$data   = file_get_contents('https://www.instagram.com/p/BkEXqsVA79F/');
$split1 = explode("window._sharedData =", $data);
$split2 = explode(";</script>", $split1[1]);

$result = json_decode(html_entity_decode($split2[0]), true);
$media  = $result['entry_data']['PostPage'][0]['graphql']['shortcode_media'];

var_dump($media['shortcode'], $media['id']);
```

So you'll have this as output

/mnt/c/web/apache/localhost/www/sharedData.php:9:string 'BkEXqsVA79F' (length=11)
/mnt/c/web/apache/localhost/www/sharedData.php:9:string '1802669839740026693' (length=19)

**Comment by mgp25** [comment]
Use this class we provide: https://github.com/mgp25/Instagram-API/blob/master/src/InstagramID.php

Regards

**Comment by bolds07** [comment]
Thanks for the information...

I've never made a real contribution to this repository, here is my small sip

At this file you recomended me you could avoid define `base2to10`  and `base10to2` functions by simple using php standard radix converter `base_convert`

http://php.net/manual/en/function.base-convert.php

`string base_convert ( string $number , int $frombase , int $tobase )`

It just accepts between 2 and 36 [so you can't replace the whole class] but it would avoid redefining those functions

**Comment by bolds07** [comment]
@mgp25 Sorry for reaching you again about this issue...

Apparently I made a very wrong assumption..., after you gave that answer i made some tests and proceed to developing my system...

now i'm just about to finish and i realize that all `media` requests are based on instagram mediaID format, something like `giantnumber_userid`  and the base64 conversion only gives me `giantnumber`

is there any way to reach a media without knowing from which user it belongs?

I really didn't want to do like the other user suggested and parse the instagram web html

**Comment by bolds07** [comment]
@mgp25 i've managed to do it... 

But it took longer because this example and the official documentation doesn't say is that is possible to get media info using only the media `pk` (that was i was stucked)


```
/**
     * Get detailed media information.
     * @param string $mediaId The media ID in Instagram's internal format (ie "3482384834_43294").
     * @throws \InstagramAPI\Exception\InstagramException
     * @return \InstagramAPI\Response\MediaInfoResponse
     *
/
    public function getInfo($mediaId)

```
So after I found the example I spend a lot of time thinking how to get the `userID` to be able to construct the instagram mediaID format `mediapk_userpk`
But this information is **_wrong_**, is possible to use `getInfo` only with the pk
