### ISSUE TITLE
PHP Fatal error exception LazyJsonMapper

### ISSUE THREAD

**Issue by tonyrbt** [mgp25/Instagram-API#2067]
i got error after i try get user timeline

`PHP Fatal error:  Uncaught exception 'LazyJsonMapper\Exception\LazyUserOptionException' with message 'Virtual property access is disabled for class "\InstagramAPI\Response\UserFeedResponse".' in /home/public_html/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php:2336`

this example code

```php
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

$ig = new \InstagramAPI\Instagram();
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}



$userID = $ig->people->getUserIdForName($otherPage);
$feed = $ig->timeline->getUserFeed($userID);




//print_r($feed);

```

**Comment by mgp25** [comment]
Duplicate: https://github.com/mgp25/Instagram-API/search?q=%27Virtual+property+access+is+disabled+for+class&type=Issues
