### ISSUE TITLE
Cant get the number of posts 'num_result' in hashtag info when getting the feed.

### ISSUE THREAD

**Issue by ugurcanb** [mgp25/Instagram-API#2069]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation) but cant update to latest  because I made little changes in direct class. I am a novice at composer or in general. (i have the source from a month ago or so)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors) <from instagram's side maybe?>
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hi I am trying to get all the post that tagged with some hashtag but when I get the hashtag info via InstagramAPI\Request\Hashtag getInfo() function, the response contains a field 'num_results' saying it has 9k results but when I use getFeed() paginate and reach the null max_id for pagination the number of posts Instagram have sent to me is way less than the number I get from hashtag info. Something like 1800 posts. 

I am sure that I am using the pagination the right. I used the rankToken example as a starting point.  I am using the same rank token for all the pagination, getting the next max_id from the response and doing a do while(max_id == null). Giving 6 seconds breaks via sleep between each pagination request and not doing any request in each cycle of do..while except requesting for next page via getFeed function with the parameter next max_id from the response.

I also tried to continue with the previous of last page's max_id and also get a null max_id for next page meaning it is the last page. Also, different hashtags have a different rate between num_results and actual post count reachable via getFeed(). For example, I tried a 16k num_result hashtag and got 11k of posts.

I also used [https://github.com/postaddictme/instagram-php-scraper](https://github.com/postaddictme/instagram-php-scraper) this package to try a different approach and it is the same.  I cant get the all posts Instagram saying it has.

Is it possible that the number of result Instagram saying doesn't match the number of posts Instagram giving? Is anybody having the same issue as me?  

-I didn't put any code as I didn't think it is relevant to code if you need I can put some. Thank you in advance. And thank you for this package.

**Comment by valga** [comment]
@ugurcanb The number of search results is always approximate, because counting every single result is very expensive. Also, there are such things as private accounts, hidden posts, etc. No one will bother to count just for you how many posts you will be able to see.

It's like getting 100K results in Google, but stopping at 10th page, because no more results are available.
