### ISSUE TITLE
parameters for get reels story id and taken at 

### ISSUE THREAD

**Issue by nuzulr24** [mgp25/Instagram-API#2074]
how to get reels story id and taket at on story instagram?

**Comment by mgp25** [comment]
Hello @nuzulr24,

please read the wiki and search in the code before opening a new issue.

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php#L71

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php#L96
