### ISSUE TITLE
Count the number of stories in a certain place

### ISSUE THREAD

**Issue by geroale** [mgp25/Instagram-API#2075]
Hello guys and thank you for this awesome API. I was wondering if there was the possibity to count the number of stories in a certain location because I wanted to build some statistics about how a place is full of people or not.
With the API to get stories from a location I get only 18 stories at a time (and if I refresh I get a fewer number of the remaining (less than 18)), I think that instagram has coded these limit in their API, but is there a way to bypass it?

I mean, I only need ther number of the stories published in that location and I wondered if it is possibile.

Thank you,
Alessandro

**Comment by mgp25** [comment]
Hello @geroale,

Yes, it is possible. You will get the same response as you will get in your phone. The response should be the same. By checking the location feed, you should be able to see and count all story items.

Regards
