### ISSUE TITLE
Unable to find the necessary "rur" cookie for uploading video

### ISSUE THREAD

**Issue by brianholle** [mgp25/Instagram-API#2076]
### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---
### Describe your issue
I have been having issues with posting videos. Both to my story and through standard posting. The error message I receive is below:

     Something went wrong: Upload of "Tmpfile.mp4" failed: Unable to find the necessary "rur" cookie for uploading video.

I have tried to trace down the cause of this issue through src/Request/Internal.php and src/Client.php without much luck. I have not seen it mentioned in any closed issues or the wiki.

What causes the lack of a "rur" cookie and how can i obtain one to resolve this issue. I get this issue every time I attempt to post a video to my story and I get it on occasion for standard video posts.

Thanks for your help. Your repo has been a MASSIVE help to me. I appreciate your hard work.

**Comment by mgp25** [comment]
@brianholle Are you using latest release or `dev-master`?

**Comment by brianholle** [comment]
I believe this has fixed my problem. I was in dev-master. Thank you for the help!
