### ISSUE TITLE
Move x-fb-http-engine header from Client::api() to Request::_addDefaultHeaders()

### ISSUE THREAD

**Issue by 4n70w4** [mgp25/Instagram-API#2077]
I need disable `x-fb-http-engine` header for some requests. I use `setAddDefaultHeaders(false)` for disable instagram headers. I think need to move `x-fb-http-engine header`.

see https://github.com/4n70w4/Instagram-API/commit/8edc15ad2893d633e8c9d2e2344799c515ed0277

**Comment by valga** [comment]
@mgp25 As far as I remember every request made by app goes through liger library, that adds this header. So why would remove it?

**Comment by mgp25** [comment]
@valga I wouldn't remove it. I agree with you and you are right about this. We shouldn't mess with that. If any wants to do changes they can always do it locally. We must follow requests done using by Liger as we know.
