### ISSUE TITLE
Instagram Users Have problem to watch Live BroadCast 

### ISSUE THREAD

**Issue by payanthe** [mgp25/Instagram-API#2079]
after launching [liveBroadcast.php](https://github.com/mgp25/Instagram-API/blob/master/examples/liveBroadcast.php) users have this problem:

`we're having trouble loading this live video, please try again later.`

**Comment by mgp25** [comment]
Hello,

Just tried, and it is working fine. Make sure ffmpeg is transmitting and you have a good connection for streaming. If you have any other issue, remember to post debug log.

Regards

**Comment by bramversteeg** [comment]
I have the same issue. This is the output i'm getting.

https://pastebin.com/XeDSWT6a

I am using mac osx. All the other services work perfect! I'm using an .mp4 file of 22mb (which should be no problem for my internet connection).

My ffmpeg:

ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100


I have no clue how i can fix this.
