### ISSUE TITLE
Registration Script Doesn't Work Anymore

### ISSUE THREAD

**Issue by irnicolass** [mgp25/Instagram-API#208]
Why the registration script doesn't work? it always declared that the username isn't available. where is the mistakes in it? though I never modify the original script contents ..

there is the code:

```php
<?php

set_time_limit(0);
error_reporting(0);

require_once '../src/InstagramRegistration.php';

$debug = true;
$r = new InstagramRegistration($debug);

$first_name = "Nicolass";

echo "\n\nUsername: ";
$username = "klomukasurya";

echo "\nPassword: ";
$password = "badguyss";

echo "\nEmail: ";
$email = "testercreate@gmail.com";
$email = filter_var($email, FILTER_SANITIZE_EMAIL);

if(filter_var($email, FILTER_VALIDATE_EMAIL) === false){
	echo json_encode(array('result' => 0, 'status' => 'error', 'content' => '<i class="fa fa-remove"></i> '.$email.' is not a valid email address, please check your email again!'));
} else {
    $check = $r->checkUsername($username);
	var_dump($check);
	if($check['available'] == false){
		echo json_encode(array('result' => 0, 'status' => 'error', 'content' => '<i class="fa fa-remove"></i> Sorry, username '.$username.' is taken, please try with another one'));
	} else {
		$result = $r->createAccount($username, $password, $email, $first_name);
var_dump($result);
		if(isset($result['account_created']) && ($result['account_created'] == true)){
			echo json_encode(array('result' => 1, 'status' => 'success', 'content' => '<i class="fa fa-check"></i> Congratulations! Your Instagram account was successfully created! :)'));
		}
	}
}
?>
```

please resolve it dude ;)

**Comment by RageBrahimi** [comment]
Please post the response (debug) that you get so we can know what to look for.

**Comment by irnicolass** [comment]
there is debug i get:
Username: Password: Email: REQUEST: users/check_username/ DATA: ig_sig_key_version=4&signed_body=fc99e74161909bf0e982380d924ad7661bb18b166d7c73f1bb55cc031a664479.%7B%22_uuid%22%3A%226179f0a7-4ebf-4fd8-a4ae-cce8df4185df%22%2C%22username%22%3A%22klomukasurya%22%2C%22_csrftoken%22%3A%22missing%22%7D RESPONSE: {"result":0,"status":"error","content":"<\/i> Sorry, username klomukasurya is taken, please try with another one"}

**Comment by mgp25** [comment]
@irnicolass read the response....

**Comment by irnicolass** [comment]
yes, but i check it on instagram is Available, no one user use that username :3
