### ISSUE TITLE
How to check isFollowing by Instagram ID

### ISSUE THREAD

**Issue by barisyild** [mgp25/Instagram-API#2083]
$FriendshipStatus = $ig->people->approveFriendship($InstaID)->getFriendshipStatus();
if($FriendshipStatus->isFollowing() || $FriendshipStatus->isOutgoingRequest())
{
               return self::ALREDY_FOLLOWING;
}
$ig->people->follow($InstaID);
$FriendshipStatus = $ig->people->getFriendship($InstaID);
if($FriendshipStatus->isFollowing() || $FriendshipStatus->isOutgoingRequest())
{
                return self::SUCCESS;
}

Instagram marking as spamming this code.
Is this use wrong?

**Comment by barisyild** [comment]
FeedbackRequiredException: stdClass Object
(
    [message] => feedback_required
    [spam] => 1
    [feedback_title] => Action Blocked
    [feedback_message] => This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.
    [feedback_url] => repute/report_problem/instagram_follow_users/
    [feedback_appeal_label] => Report problem
    [feedback_ignore_label] => OK
    [feedback_action] => report_problem
    [status] => fail
)

**Comment by Stiveknx** [comment]
About spam:

Or you are really doing spam.
Or you're making requests too fast (run some sleep() between each request)
