### ISSUE TITLE
is any exception to manage limitaion of send like,comment?

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2087]
when i send like, comment or following other pages, i would like to manage this actions is limited, for example instagram blocked sending like or limited that for some days, i can't find any exception to helper class and methods in source of this library, could you help me or give me some information? thanks

**Comment by mgp25** [comment]
Hello @Mrp12,

If the request wasn't successful you will be able to get the status of the response `fail` or any other property that defines the error itself. You can do it in the same way as normal requests. If you want to manage responses in exception see this: https://github.com/mgp25/Instagram-API/blob/master/examples/exceptionDetailsExample.php

Regards
