### ISSUE TITLE
Challenge required in loop

### ISSUE THREAD

**Issue by DarkSaTla** [mgp25/Instagram-API#2090]
Hey,
i put the scripts to the my server, my account location is israel, i trying to login everytime but i got loop in the challenge requied, i tried to use proxy from israel or change the proxy to other location in israel but nothing work, everytime i got challenge requied, how can i fix it?

~~ and more one question, There is a limit up to a certain amount How many accounts can I add?
Thanks you!!

**Comment by mgp25** [comment]
F.A.Q.: [What does "checkpoint_required" error mean?](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean)

Use browser or mobile client to verify your account.

> There is a limit up to a certain amount How many accounts can I add?

There is not a concrete limit on the amount of accounts you can add, but the API was meant to be used for personal usage only. If you use it for any other thing, you are the only responsible for the consecuences of it. As long as you use it as a legit use, you should not face any problem.

Regards

**Comment by lastwall** [comment]
I want to bypass this with phone or email verification..
is there any way in new API version?
it seems it doesn't work in new version? I searched it out but nothing found
any help will be appreciated..
