### ISSUE TITLE
Mentions/Feedstory

### ISSUE THREAD

**Issue by clouddev-elias** [mgp25/Instagram-API#2094]
### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ x] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
  $metadata = [
            'story_mentions' =>
            [
                'user_id' => $userId, // Must be a numerical UserPK ID.
                'x' => 0.5, // Range: 0.0 - 1.0. Note that x = 0.5 and y = 0.5 is center of screen.
                'y' => 0.5, // Also note that X/Y is setting the position of the CENTER of the clickable area.
                'width' => 1, // Clickable area size, as percentage of image size: 0.0 - 1.0
                'height' => 1, // ...
                'rotation' => 0.0,
                'is_sticker' => true, // Don't change this value.
            ]
        ];
```

My questions is whenever Story mentions is still working for feeds? Currently only hashtags was working, usermentions was NOT working for me. I have read previous issues, and samples etc.

**Comment by mgp25** [comment]
Hello @clouddev-elias,

Here is an example:

```php
$metadata = [
        'caption' => 'Hello @test',
	'story_mentions' =>
        [
	      [
                 'user_id'          => $userId, //user id of @test
                 'x'                => 0.5,
                 'y'                => 0.5,
                 'width'            => 0.5661107,
                'height'           => 0.10647108,
                'rotation'         => 0.0,
	     ],
	]
];
```

Regards
