### ISSUE TITLE
how to join  live ??

### ISSUE THREAD

**Issue by milad74yari** [mgp25/Instagram-API#2095]
Hello
I am using this request to enter Live
where is the problem from ?

`
C2548i a = c2548i.m7789a("live/%s/join/", str);

		a.f10382a.m9638a("encoded_server_data_info", 1);

		a.f10382a.m9638a("device_id", str3);

		a.f10382a.m9638a("sdp_offer", 1);
`

When the live is over

`
{"message": "Broadcast cannot be seen", "status": "fail"}
`

**Comment by mgp25** [comment]
Duplicate: #1690
