### ISSUE TITLE
Warning about suspicious activity

### ISSUE THREAD

**Issue by andreybashtovoy** [mgp25/Instagram-API#2097]
Hello! My hosting told me to delete the file that works with api, because Google gave them a warning about suspicious activity. What could have caused this problem? Can I somehow fix this?

**Comment by mgp25** [comment]
Hello, 

The API has nothing to do with google. If you tried using an account from your server, you probably have received an email saying that `there was a suspicious activity` and they want you to verify if the login was legit or not.

Probably something similar to this: https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean

Regards
