### ISSUE TITLE
getGender() method always return NULL.

### ISSUE THREAD

**Issue by megghross** [mgp25/Instagram-API#2098]
## Issue
- I tried to get gender of User using method getGender() in User class, but it alwasy return null.
- Here is code snippet

```
 $selfInfo = $Instagram->people->getInfoByName('someusername');
 print_var($selfInfo->getUser()->getGender());
```

Please let me know how to overcome this issue, I've tried many username and other technique as well, as Getting user account from timeline feeds and searching direct by name and id as well.

**Comment by szokeptr** [comment]
There is not even a single trace of a profile's gender in the Android app (except your own profile settings), so this will never work.

**Comment by mgp25** [comment]
@megghross You can't get user's gender. Furthermore, you should look at the response shown in the debug log. It will help you while coding and understanding how the API works.

Regards
