### ISSUE TITLE
Upload Photo Doesnt work

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#21]
Uploading Photo doesnt work.
Please Repair this !

**Comment by mgp25** [comment]
If you dont provide any code or debug log, this issue is inavalid

Regards

**Comment by doctorbinsibar** [comment]
i just can give you debug info here: 

REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=f1faf55a8226cce78ccd255fb6f382b9dd3ac65b906b9b456f036d9b9fba442f.%7B%22caption%22%3A%22welcome+47256%22%2C%22upload_id%22%3Anull%2C%22source_type%22%3A4%2C%22edits%22%3A%7B%22crop_zoom%22%3A1%2C%22crop_center%22%3A%5B0%2C0%5D%2C%22crop_original_size%22%3A%5B150%2C150%5D%2C%22black_pixels_ratio%22%3A0%7D%2C%22device%22%3A%7B%22manufacturer%22%3A%22asus%22%2C%22model%22%3A%22Nexus+7%22%2C%22android_version%22%3A22%2C%22android_release%22%3A%225.1%22%7D%2C%22_csrftoken%22%3A%220c564d7fa300e8719f643dff8668d4bb%22%2C%22_uuid%22%3A%229228c783-1afd-4ef9-a667-283a879a9cf7%22%2C%22_uid%22%3A%222334008827%22%7D RESPONSE: Oops, an error occurred.
