### ISSUE TITLE
Your version of Instagram is out of date

### ISSUE THREAD

**Issue by jpmoney5065** [mgp25/Instagram-API#210]
`REQUEST: si/fetch_headers/?challenge_type=signup&guid=b26de3b3d2f442e290de7a2372188423 `

`RESPONSE: {"status": "ok", "shift": 18, "header": "tTqB3689wyDlckhpYANEe4gW52PbOurG", "edges": 100, "iterations": 10, "size": 42} `

`REQUEST: accounts/login/ DATA: ig_sig_key_version=4&signed_body=adbd53fe8b0eae976a7d87c5e077cbb719549b9e2a44f073f0982e203558aec7.{"phone_id":"ab06f78a-0dbd-48e9-a198-7c8b2bb02596","_csrftoken":"Set-Cookie: csrftoken=c8c08d89b625c19329d5f5f403bb4a38","username":"*removed","guid":"c73e3ceb-42e0-4c6b-80ee-c53ff31e1eed","device_id":"android-4e5dd35dcf24753e","password":"*removed","login_attempt_count":"0"} `

`RESPONSE: {"status": "fail", "message": "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram."}`

**Comment by Mifody** [comment]
> "_csrftoken":"Set-Cookie: csrftoken=c8c08d89b625c19329d5f5f403bb4a38"

what??? Oo

**Comment by mkanker** [comment]
@Mifody lol why Oo?

**Comment by mgp25** [comment]
It works fine, make sure you are using latest source code, and just in case remove all your `.dat` files inside the `data` folder

Regards
