### ISSUE TITLE
Address Book link is not working

### ISSUE THREAD

**Issue by shkumbinhasani** [mgp25/Instagram-API#2100]
Hi ,
Recently i started trying this class and i like your work but i had one issue when i tried the Link Adress Book it gets a bad response like "Oops, an error occurred."

```
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
try {
	$contacts[] = "+386XXXXXX";
    $userId = $ig->people->unlinkAddressBook();
	$userId = $ig->people->linkAddressBook($contacts);
    print_r($userId);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

And here is the response 

> [1;34mPOST:  [0mhttps://i.instagram.com/api/v1/address_book/link/?include=extra_display_name,thumbnails
> [1;33mDATA: [0mcontacts=%5B%22386XXXXXX%22%5D&_uuid=10010bfd-b95d-439b-ac88-f65c85597922&_csrftoken=2t8ybSNgyzTAzgfG2URA2CMgWVPar8EE
> [0;32m← 500     25B[0m
> [0;36mRESPONSE: [0mOops, an error occurred.

**Comment by mgp25** [comment]
Read closed  issues before opening new ones

```php

    $contacts = array(
        array(
            'first_name' => 'whatever',
            'phone_numbers' => array('+625698715'),
            'email_addresses' => array('')
        )
    );
```

Regards

**Comment by kelvionald** [comment]
`try {
  // $contacts = [
  //   [
  //     'first_name' => 'Vlad',
  //     'phone_numbers' => ['+79615306818'],
  //     'email_addresses' => []
  //   ],
  //   [
  //     'first_name' => 'Yana',
  //     'phone_numbers' => ['+79648625071'],
  //     'email_addresses' => []
  //   ]
  // ];
  $contacts = array(
      array(
          'first_name' => 'Contact1',
          'phone_numbers' => array('+625698715'),
          'email_addresses' => array('')
      )
  );
  $userId = $ig->people->unlinkAddressBook();
  $userId = $ig->people->linkAddressBook($contacts);
  print_r($userId);
} catch (\Exception $e) {
  echo 'Something went wrong: '.$e->getMessage()."\n";
}`
Its not work for me, why?
`POST:  https://i.instagram.com/api/v1/address_book/unlink/
DATA: signed_body=dc8d14a61bd88d6b000ac83e3f3156100ccfaa26bb1df7141cb89384bf01fe4d.{"_csrftoken":"7sTKoDVEAHD2jqmnPazt6R2S3LsmPNig","_uid":"13349992672","_uuid":"7679731d-93fb-4a1b-bd75-9d3a56046d32"}&ig_sig_key_version=4
← 200    16B
RESPONSE: {"status": "ok"}

POST:  https://i.instagram.com/api/v1/address_book/link/
DATA:
← 400    50B
RESPONSE: {"message": "Invalid arguments", "status": "fail"}

Something went wrong: InstagramAPI\Response\LinkAddressBookResponse: Invalid arguments.`
