### ISSUE TITLE
Information 2

### ISSUE THREAD

**Issue by projectbot2018** [mgp25/Instagram-API#2101]
will these Api also work after the July 31 changes? 
and successively after the other limitations that instagram’ll impose on 31 December and in earlier 2020 

This is what instagram publish : 
Instagram API Platform: Deprecation
We will be deprecating the older Instagram API Platform in three phases with complete deprecation occurring in early 2020.

The following will be available until July 31, 2018:

Follower List - to read the list of followers and followed-by users
Relationships - to follow and unfollow accounts on a user’s behalf
Commenting on Public Content - to post and delete comments on a user’s behalf on public media
The following will be available until December 11, 2018:

Commenting - to post and delete comments on a user’s behalf on owned media
Public Content - to read any public profile info and media on a user’s behalf
Likes - to like and unlike media on a user’s behalf
Subscriptions - to receive notifications when media is posted
The following will be available until early 2020:

Basic - to read a user’s profile info and media

**Comment by mgp25** [comment]
Duplicate Issue.

This API is based on the Android app. None of the changes Instagram does will affect this API.

Regards
