### ISSUE TITLE
Dealing with new format of IG links

### ISSUE THREAD

**Issue by samdonato** [mgp25/Instagram-API#2103]
### Purpose of your issue?

- [X] Question

### Describe your issue

Short question: How can i get the media id for the new format link?

Recently I've noticed that when I get a link to media in the IG app, it is returning a new format which looks like this https://ig.me/1HE2gvdo8iqmyjo. That string on the end does not seem to be our typical "Short Code". If you put the ig.me link in a browser, it will redirect to the standard https://www.instagram.com/p/Bld_j7HF5Vp, so we can see the real short code for 1HE2gvdo8iqmyjo is Bld_j7HF5Vp. The example shortcodeConverter.php doesn't handle this new shortcode. How do I deal with this new URL?

**Comment by M47H3W** [comment]
The URL looks like a simple short link. When you visit the page, you are presented with a 302 redirection. All that you need to do is execute a cURL request and check the `Location` header

The following code will should get you the correct URL:


```
<?php

echo ShortURLtoCode("https://ig.me/1HE2gvdo8iqmyjo");


function ShortURLtoCode($url){

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
	curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
	curl_setopt($ch, CURLOPT_HEADER, 1);

	$headers = array();
	$headers[] = "Host: ig.me";
	$headers[] = "Upgrade-Insecure-Requests: 1";
	$headers[] = "User-Agent: Mozilla/5.0 (Windows NT 6.2; rv:20.0) Gecko/20121202 Firefox/20.0";
	$headers[] = "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8";
	$headers[] = "Accept-Language: en-US,en;q=0.9,da;q=0.8,mt;q=0.7,la;q=0.6";
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
    	echo 'Error:' . curl_error($ch);
	}

	$headers = get_headers_from_curl_response($result);



	return $headers["Location"];

}


function get_headers_from_curl_response($response)
{
    $headers = array();

    $header_text = substr($response, 0, strpos($response, "\r\n\r\n"));

    foreach (explode("\r\n", $header_text) as $i => $line)
        if ($i === 0)
            $headers['http_code'] = $line;
        else
        {
            list ($key, $value) = explode(': ', $line);

            $headers[$key] = $value;
        }

    return $headers;
}

```

**Comment by samdonato** [comment]
M47H3W's answer was great. Closing.
