### ISSUE TITLE
How can I get all comments to the media?

### ISSUE THREAD

**Issue by roman22275** [mgp25/Instagram-API#2105]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

My code doesnt work
```php
$forFullPath = __DIR__ . DIRECTORY_SEPARATOR; 
require_once $forFullPath.'vendor/autoload.php'; 
$ig = new \InstagramAPI\Instagram(); 
try { 
$ig->login('login', 'pass'); 
} 
catch(Exception $e) { 
echo $e->getMessage(); 
} 

$userId = $ig->people->getUserIdForName('user'); 
$res= $ig->timeline->getUserFeed($userId); 
$res = json_decode(json_encode($res)); 



$mediaId = $res->items[0]->id; 

    $comment_helper = null;
      $comments = [];
 
      do {
          if (is_null($comment_helper)) {
              $comment_helper = $ig->media->getComments($mediaId);
          } else {
          	
             $comment_helper = $ig->media->getComments($mediaId, $comment_helper->getNextMaxId());
         }
         $comments = array_merge($comments, $comment_helper->getComments());
         sleep(5);
         echo " max id ". $comment_helper->getNextMaxId() ." ";
     } while (!is_null($comment_helper->getNextMaxId()));
 
   // print_r($comments);
```

**Comment by darkterminal** [comment]
Please read [**Wiki**](https://github.com/mgp25/Instagram-API/wiki)

**Comment by mgp25** [comment]
Have a look at this pagination example: https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php

Regards

**Comment by kozintsev** [comment]
$comment_helper->getNextMaxId()
The method causes an error.

Fatal error: Uncaught LazyJsonMapper\Exception\LazyJsonMapperException: Unknown function "getNextMaxId". in \vendor\lazyjsonmapper\lazyjsonmapper\src\LazyJsonMapper.php on line 2156

LazyJsonMapper\Exception\LazyJsonMapperException: Unknown function "getNextMaxId". in \vendor\lazyjsonmapper\lazyjsonmapper\src\LazyJsonMapper.php on line 2156
