### ISSUE TITLE
Set exception codes properly

### ISSUE THREAD

**Issue by mbande** [mgp25/Instagram-API#2107]
it seems that Exception codes are not handled properly. e.g. a NotFoundException code is 0!

**Comment by valga** [comment]
@mbande Exception codes are useful when you have only one generic exception for all errors. In that case you can distinguish between different errors with the help of exception code. In our case `NotFoundException` is already specific.

But you can do something like this:
```php
$code = $error->getCode();
$response = $error->getResponse();
if ($response !== null) {
    $code = $response->getHttpResponse()->getStatusCode();
}
```
