### ISSUE TITLE
Can't login instagram account / Challenge required

### ISSUE THREAD

**Issue by sexavet94** [mgp25/Instagram-API#2111]
I test it on my local server. Without proxy usage. With the same IP i can login from my android device and chrome browser normally. When i try login with API i get warning on my mobile device. And i accept this challenge, clicking 'This Was Me' button. But it doesn't help. When i refresh API, now shown challenge required error. I try change my account password, add two factor authentication, disable two factor authentication and nothing help.
With the same local server i can login other my fake account normally. But with my real account can't login with API.

Debug log:

POST:  https://i.instagram.com/api/v1/accounts/read_msisdn_header/
DATA: signed_body=815c8898bdf2ebd837d909e6f1e0dbbbcfac8acb70de1290520b4a982e6814f7.{"_csrftoken":"OhHMSnRKS63UvrYGVGeSJZYSA13QVff6","device_id":"674fd883-3ac4-442c-a5e0-e69d88ab0019"}&ig_sig_key_version=4
← 200 	 16B
RESPONSE: {"status": "ok"}

POST:  https://i.instagram.com/api/v1/qe/sync/
DATA: signed_body=b650d037ba758db3130e123f773f3f3728b1321010406a7e12c1480b0a73f528.{"id":"674fd883-3ac4-442c-a5e0-e69d88ab0019","experiments":"ig_android_updated_copy_user_lookup_failed,ig_android_hsite_prefill_new_carrier,ig_android_me_profile_prefill_in_reg,ig_android_allow_phone_reg_selectable,ig_android_gmail_oauth_in_reg,ig_android_run_account_nux_on_server_cue_device,ig_android_universal_instagram_deep_links_universe,ig_android_make_sure_next_button_is_visible_in_reg,ig_android_report_nux_completed_device,ig_android_sim_info_upload,ig_android_reg_omnibox,ig_android_background_phone_confirmation_v2,ig_android_background_voice_phone_confirmation,ig_android_password_toggle_on_login_universe_v2,ig_android_skip_signup_from_one_tap_if_no_fb_sso,ig_android_refresh_onetap_nonce,ig_android_multi_tap_login,ig_android_onetaplogin_login_upsell,ig_android_jp_sms_code_extraction_fix, ig_challenge_kill_switch,ig_android_modularized_nux_universe_device,ig_android_run_device_verification,ig_android_remove_sms_password_reset_deep_link,ig_android_phone_id_email_prefill_in_reg,ig_android_typeahead_bug_fixes_universe,ig_restore_focus_on_reg_textbox_universe,ig_android_abandoned_reg_flow,ig_android_phoneid_sync_interval,ig_android_2fac_auto_fill_sms_universe,ig_android_family_apps_user_values_provider_universe,ig_android_security_intent_switchoff,ig_android_enter_to_login,ig_android_show_password_in_reg_universe,ig_android_access_redesign,ig_android_remove_icons_in_reg_v2,ig_android_ui_cleanup_in_reg_v2,ig_android_login_bad_password_autologin_universe,ig_android_editable_username_in_reg"}&ig_sig_key_version=4
← 200 	 1kB
RESPONSE: {"experiments": [{"name": "ig_android_me_profile_prefill_in_reg", "group": "control_0829", "additional_params": [], "params": [{"name": "prefill_enabled", "value": "false"}], "expired": true}, {"name": "ig_android_allow_phone_reg_selectable", "group": "test_0731", "additional_params": [], "params": [{"name": "phone_reg_selection_enabled", "value": "true"}], "expired": true}, {"name": "ig_android_gmail_oauth_in_reg", "group": "rollout_1201", "additional_params": [], "params": [{"name": "try_background_confirm", "value": "true"}], "expired": true}, {"name": "ig_android_run_account_nux_on_server_cue_device", "group": "control_1016_v2", "additional_params": [], "params": [{"name": "show_account_nux", "value": "false"}], "expired": true}, {"name": "ig_android_sim_info_upload", "group": "test", "additional_params": [], "params": [{"name": "enable_upload", "value": "true"}], "expired": true}, {"name": "ig_android_background_phone_confirmation_v2", "group": "test_background_confirm_only_1119", "additional_params": [], "params": [{"name": "background_phone_confirm_enabled", "value": "true"}, {"name": "move_confirmation_screen_to_end_of_phone_flow", "value": "false"}], "expired": true}, {"name": "ig_android_jp_sms_code_extraction_fix", "group": "control_1122", "additional_params": [], "params": [{"name": "apply_fix", "value": "true"}], "expired": true}, {"name": "ig_android_modularized_nux_universe_device", "group": "roll_out_dynamic_onboarding_0612", "additional_params": [], "params": [{"name": "increment_following_count", "value": "true"}, {"name": "request_from_server", "value": "true"}, {"name": "run_from_plugin", "value": "true"}], "logging_id": "ig_android_modularized_nux_universe_device$ig_android_modularized_nux_from_server_device_v6$roll_out_dynamic_onboarding_0612", "expired": false}, {"name": "ig_android_run_device_verification", "group": "test_both", "additional_params": [], "params": [{"name": "run_device_verification", "value": "verification_run_check"}], "expired": true}, {"name": "ig_android_remove_sms_password_reset_deep_link", "group": "test_0904", "additional_params": [], "params": [{"name": "remove_deep_link", "value": "true"}], "expired": true}, {"name": "ig_android_phone_id_email_prefill_in_reg", "group": "prefill_enabled_0130", "additional_params": [], "params": [{"name": "prefill_enabled", "value": "true"}], "expired": true}, {"name": "ig_android_typeahead_bug_fixes_universe", "group": "rollout_0302", "additional_params": [], "params": [{"name": "show_profile_pic", "value": "false"}], "expired": true}, {"name": "ig_android_phoneid_sync_interval", "group": "test_6_hours", "additional_params": [], "params": [{"name": "fully_synced", "value": "604800"}, {"name": "partially_synced", "value": "21600"}], "expired": true}, {"name": "ig_android_family_apps_user_values_provider_universe", "group": "test", "additional_params": [], "params": [{"name": "should_provide_user_values", "value": "true"}], "expired": true}, {"name": "ig_android_security_intent_switchoff", "group": "allusers", "additional_params": [], "params": [{"name": "switch_offs", "value": ""}], "expired": true}, {"name": "ig_android_enter_to_login", "group": "test_1127", "additional_params": [], "params": [{"name": "enter_to_login", "value": "true"}], "expired": true}, {"name": "ig_android_access_redesign", "group": "test2_1120_rollout", "additional_params": [], "params": [{"name": "lookup_by_phone", "value": "false"}, {"name": "send_direct_sms", "value": "true"}, {"name": "show_redesigned_lookup", "value": "false"}], "expired": true}, {"name": "ig_android_remove_icons_in_reg_v2", "group": "launch_1012", "additional_params": [], "params": [{"name": "remove_icons_on_name_and_pwd", "value": "remove_icon_and_decrease_top_margin_weight"}, {"name": "remove_icons_on_phone_conf", "value": "remove_icon_and_decrease_top_margin_weight"}, {"name": "remove_icons_on_two_fac", "value": "remove_icon_and_decrease_top_margin_weight"}, {"name": "remove_icons_on_username", "value": "remove_icon_and_decrease_top_margin_weight"}], "expired": true}, {"name": "ig_android_ui_cleanup_in_reg_v2", "group": "test_with_tertiary_ci_opt_out_with_tertiary_style_test_0213", "additional_params": [], "params": [{"name": "next_button_disable_style", "value": "filled_blue_when_disabled"}, {"name": "secondary_text_link_style_fix", "value": "test_with_tertiary_ci_opt_out"}, {"name": "secondary_text_link_style_fix_expose", "value": "true"}, {"name": "tertiary_text_link_style_fix", "value": "test"}], "expired": true}, {"name": "ig_android_login_bad_password_autologin_universe", "group": "control_0824", "additional_params": [], "params": [{"name": "attempt_threshold", "value": "1"}, {"name": "is_enabled", "value": "true"}], "expired": true}], "status": "ok"}

GET:  https://i.instagram.com/api/v1/zr/token/result/?token_hash=
→ 0B
← 200 	 189B
RESPONSE: {"token": {"carrier_name": "", "carrier_id": 0, "ttl": 72000, "features": [], "request_time": 1532410310, "token_hash": "", "rewrite_rules": [], "enabled_wallet_defs_keys": [], "deadline": "", "zero_cms_fetch_interval_seconds": 86400}, "status": "ok"}

POST:  https://i.instagram.com/api/v1/attribution/log_attribution/
DATA: signed_body=c60558caee811cb6a9df33d2846f392ea99025dc42efdf9ab95fe96bb9a02649.{"adid":"906ca48b-733a-4c33-840b-85169f9786d0"}&ig_sig_key_version=4
← 200 	 16B
RESPONSE: {"status": "ok"}

POST:  https://i.instagram.com/api/v1/accounts/contact_point_prefill/
DATA: signed_body=1826a28ff3b788e2abeb35bfef0b4a117fd4d03ca8eda04618afcaaaf632a3b9.{"phone_id":"de68faab-a978-408d-a7ea-d2b77ccc377a","_csrftoken":"OhHMSnRKS63UvrYGVGeSJZYSA13QVff6","usage":"prefill"}&ig_sig_key_version=4
← 200 	 16B
RESPONSE: {"status": "ok"}

POST:  https://i.instagram.com/api/v1/accounts/login/
DATA: signed_body=6ec44575e96ca939d84df6a5dd54ee727fb581366c756bb00e82a028201a80de.{"phone_id":"de68faab-a978-408d-a7ea-d2b77ccc377a","_csrftoken":"OhHMSnRKS63UvrYGVGeSJZYSA13QVff6","username":"xxxx","adid":"906ca48b-733a-4c33-840b-85169f9786d0","guid":"674fd883-3ac4-442c-a5e0-e69d88ab0019","device_id":"android-e9e3ec19878855ef","password":"xxxx","login_attempt_count":"0"}&ig_sig_key_version=4
← 400 	 310B
RESPONSE: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/4049541685/7iTGcAj3sM/", "api_path": "/challenge/4049541685/7iTGcAj3sM/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}

Something went wrong: InstagramAPI\Response\LoginResponse: Challenge required.

**Comment by mgp25** [comment]
F.A.Q.: [What does "checkpoint_required" error mean?](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean)

**Comment by DavidCLuna** [comment]
@mgp25 All the people ask the same question, but in reality the information on the wiki, does not answer this problem, says that is what happens, but the solution to accept that I was the one who made the login, does not work .
please tell me how I can solve it, it will not take too much time, I've been in this for several days
