### ISSUE TITLE
Add custom csrftoken cookie

### ISSUE THREAD

**Issue by sexavet94** [mgp25/Instagram-API#2113]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
I want to add cookies custom. Because when i try to login with API i get 'challenge required' message, and i can't pass this challenge.
I normally login to instagram from chrome. After i copy all cookies and write to the cookie file in API cookie storage file. When call the 'login' method, again i get 'challenge required' message, and the cookie file changed automatically. But when i use this cookies in my PHP script, which this script i use CURL , and i send request to instagram.com with cookie , i don't receive any challenge, and all is work normally.

**Comment by mgp25** [comment]
Not something we plan to add. You can manually change them in `.dat` files.

Regards
