### ISSUE TITLE
Highlighted Feed

### ISSUE THREAD

**Issue by clouddev-elias** [mgp25/Instagram-API#2114]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Example Code:

```php
$photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename, ['targetFeed' => \InstagramAPI\Constants::FEED_STORY]);
$ig->story->uploadPhoto($photo->getFile(), $metadata);
```

---
### Describe your issue

I'm looking for a way to add story feed photo into "Highlights" Story section. So far i have not found any way todo so. The code above add it currently to the story feed.  I have checked the constants, but i am not sure. Thanks

**Comment by szokeptr** [comment]
See 
https://github.com/mgp25/Instagram-API/blob/36a92c944ac5b3117331a85a71b40a8220f6d349/src/Request/Highlight.php#L65-L69
and 
https://github.com/mgp25/Instagram-API/blob/36a92c944ac5b3117331a85a71b40a8220f6d349/src/Request/Highlight.php#L112-L115

**Comment by clouddev-elias** [comment]
Ok, thanks. I will review the code.

**Comment by clouddev-elias** [comment]
I will have to **request example** for usage with photo or media file, so this can be closed correctly. Otherwise thus must be done manually, thanks.

**Comment by szokeptr** [comment]
Can you add photo or media file to highlights directly in the Android app? 
Highlights are created from stories, you must first publish a story, then you can add it to a highlight.

**Comment by clouddev-elias** [comment]
I am new to the API and still exploring great potential this API has. 

So far ive posted the Feed Story media, then my **approach** would be:
1. Create/Edit HighlightId and Get element mediaId from the feed story (Not sure, if there is a return while uploading)
2. Create/Edit existing Highlight, then add mediaId to the highlited section.

If the approach is correct, i would investigate it in some time. If you could post sample, that would be much appreciated.

**Comment by szokeptr** [comment]
You are on the right path, just take your time to explore the API. It's one of the most well documented projects I've ever seen, just make sure you read the code. 
Good luck.

**Comment by clouddev-elias** [comment]
👍
