### ISSUE TITLE
Instagram connection works better with proxy with IP authentication?

### ISSUE THREAD

**Issue by nadpel** [mgp25/Instagram-API#2116]
Instagram connection works better with proxy with IP authentication?
I asked it because my proxies provider said it, but I would like to know if someone tried it already with IP authentication?

**Comment by mgp25** [comment]
Someone is trying to scam you.

**Comment by nadpel** [comment]
you sure? coz he don't tried to sell me something.. I paid for proxies from him already but he told me this: 

"Most of the bots are work better with IP authentication and not with username and password authentication.
If you use it from bot, my advice is to use IP Authentication. You must add your real IP in our control panel. Or if you are using a VPS, you must add the IP of the VPS on our panel
We recommend using IP Authentication, check the IP authentication option."

is not true what's he said?
I must to know coz I too much hard to change all the system to use IP Authentication... :/
