### ISSUE TITLE
How can I publish a story with the question sticker? Thank you

### ISSUE THREAD

**Issue by EphramDoyle** [mgp25/Instagram-API#2117]
How can I publish a story with the question sticker? Thank you

**Comment by mgp25** [comment]
@EphramDoyle This API doesn't provide stickers, you need to manually draw it on top of the image.

Regards

**Comment by EphramDoyle** [comment]
Ohh, thanks.

And do you have a recent APK modified todo read request SSL?

By chance do you have a modified app that allows you to read the requests?
I haven't managed to patch any APK that includes the question sticker.

Regards and thanks again!
Ephram
