### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by hanncreator** [mgp25/Instagram-API#2119]
PHP Notice:  Undefined variable: statusCode in /home2/postgram/public_html/app/vendor/mgp25/instagram-php/src/Utils.php on line 361

**Comment by Alfredao** [comment]
ffprobe is installed in your server?
Have you set the correct ffprobe location?

```php
\InstagramAPI\Utils::$ffprobeBin = '/home/exampleuser/ffmpeg/bin/ffprobe';
```

**Comment by mgp25** [comment]
Feel free to open if the issue persists. But it seems to be an issue at your end. Make sure everything is configured correctly and double check the binary paths are right.

Regards
