### ISSUE TITLE
Instagram-API Warning!

### ISSUE THREAD

**Issue by rohollahsaberi** [mgp25/Instagram-API#2120]
i use this library in localhost web page.
but i get this error:

> Can I run this library via a website?
No. Don't do it. You cannot safely use this or any other 3rd party Instagram libraries directly via a website!
This library (and all other 3rd party reverse engineered Instagram libraries), is made for command line usage in a terminal by running the script like a program (such as php yourscript.php). We do not recommend running this library via a web browser! Because browsers will terminate the PHP process as soon as the user closes their connection to the page (closes the tab, or presses "Stop loading page"), which means that your script can terminate at any moment. This library is not a webpage! It is an Instagram for Android application emulator. It emulates an application. Not a webpage. You cannot just randomly kill this library in the middle of work!...

why?
how can i use this library?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/36a92c944ac5b3117331a85a71b40a8220f6d349/src/Instagram.php#L79

Regards

**Comment by rohollahsaberi** [comment]
i solve the problem, but i can't login 

myCode:
> <?php
include '/vendor/autoload.php';
/////// CONFIG ///////
$username = 'ra.sad';
$password = '************'; 

try {
    echo "Hello";
    $ig = new \InstagramAPI\Instagram(false, false, [
        'storage'    => 'mysql',
        'dbhost'     => 'localhost',
        'dbname'     => 'ins',
        'dbusername' => 'root',
        'dbpassword' => '',
    ]);
$login = $ig->login($username,$password);
    $userId = $ig->people->getUserIdForName('ra.sad');
    echo $userId;

    print_r($userId);
} catch (\Exception $e) {
   echo 'Something went wrong in login: '.$e->getMessage()."\n";
}
?>

error:
> Human-Readable Response: { "token": { "carrier_name": "", "carrier_id": 0, "ttl": 72000, "features": [], "request_time": 1533018114, "token_hash": "", "rewrite_rules": [], "enabled_wallet_defs_keys": [], "deadline": "", "zero_cms_fetch_interval_seconds": 86400 }, "status": "ok" } Something went wrong in login: Missing JSON property definitions in "InstagramAPI\Response\Model\Token": ("zero_cms_fetch_interval_seconds").

**Comment by mgp25** [comment]
`$ig->apiDeveloperDebug = false;`
