### ISSUE TITLE
Other some details (like bio) from many followers

### ISSUE THREAD

**Issue by leandromatos** [mgp25/Instagram-API#2121]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

I'm using getFollowers to get all followers from a user, however I need some other details from followers like the bio.

Considering a user with 118,000 followers, what would be the best way to get all user data with getInfoById?

What is the limit of instagram for requests with getInfoById per hour?

**Comment by mgp25** [comment]
> Considering a user with 118,000 followers, what would be the best way to get all user data with getInfoById?

Getting the information as you were using the mobile app. Tap in the follower and then request its info.

Regards

**Comment by leandromatos** [comment]
@mgp25 The question is not how, but rather the best practice.

Anyway, I'll try to get jobs with redis.
