### ISSUE TITLE
Can't get business account statistics

### ISSUE THREAD

**Issue by DmitriyPanov1** [mgp25/Instagram-API#2123]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

My code
```php
require __DIR__ . '/../vendor/autoload.php';

$username = 'login';
$password = 'password';

$ig = new \InstagramAPI\Instagram();

try {
   $ig->login($username, $password);
   $isBusiness  = $ig->people->getSelfInfo()->getUser()->getIsBusiness();
  
 if ($isBusiness) {
      $statistics = $ig->business->getStatistics();
  }
} catch (\Exception $e) {
   echo 'error : '.$e->getMessage();
}

```

I get message error:

```php
error : InstagramAPI\Response\GraphqlBatchResponse: There was an error while fetching account statistics. Try again later.
```

**Comment by NikitaTSB** [comment]
business->getInsights() too, maybe it is Instagram side troubles

**Comment by saiger** [comment]
+1
It doesn't work for me too

**Comment by berrymore** [comment]
Have the same problem. getStatistics method returns 404 error page in body response

**Comment by valga** [comment]
@mgp25 I remember you had some business account at your hands, so please check what happened.

**Comment by pasitrinkimane** [comment]
Yeap, It still doesnt work.

**Comment by mgp25** [comment]
If anyone has a business account that can be shared with me via email, I'll update these requests as soon as I get one account for testing.

**Comment by mgp25** [comment]
Updated and fixed in latest commit. If you want to collaborate, you can add the missing models.

Regards
