### ISSUE TITLE
can i login use session information without call $ig->login() ?

### ISSUE THREAD

**Issue by JKwang00** [mgp25/Instagram-API#2124]
Hi.
I got logged info after finished verify Challenge via email code on my server.(use other API)

but i can't login use $ig->login();

return "Challenge required."

how can i login in "mgp25/Instagram-API" that use logged info?

{"loggedInUser":{"pk":"5839904"},"cookies":{"csrftoken":"OhnBnMzsfuW0GEM8PBv0TzjzwxP5drNr","rur":"ATN","mid":"W2KaaAABAAHe7RdGYHK3Uw9YNCVI","mcd":"3","shbid":"10016","shbts":"1533189165.6000543","ds_user_id":"5839904","sessionid":"IGSC1e24f6e69ab987ffb36e5f0068b328fe5c21d540c3ad23d3ef9f38ebf711eb99%3AVMQFCuW3E5GlnKkfcodfXnRk9YaVUCMo%3A%7B%22_auth_user_id%22%3A5839904%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22_auth_user_hash%22%3A%22%22%2C%22_platform%22%3A4%2C%22_token_ver%22%3A2%2C%22_token%22%3A%225839904%3APhkCtmSe4MxeyAypwP3GJ9oVI7GQdGCa%3Aca47e1a902c3a623f96422dd33174ebc25d515f698778a24079ac2b2ec9c1485%22%2C%22last_refreshed%22%3A1533189165.6006352901%7D"},"csrfToken":"OhnBnMzsfuW0GEM8PBv0TzjzwxP5drNr","rankToken":"690df8f8-72ba-4eec-8330-4d89e293c3ea","phoneId":"f00f1495-87ef-4711-9ba4-ed1fa6dc285a","deviceId":"android-1179a73deabbddfe","guid":"7623e9a3-56a1-4203-a42b-27c536987c00","uuid":"7623e9a3-56a1-4203-a42b-27c536987c00","googleAdId":"59a240bc-fa93-432f-bb61-615ccdf1e848"}

i'm so sorry that i'm not good at english.

**Comment by mgp25** [comment]
Copy your user folder from `\sessions` folder to your new enviroment. It is not a good practice tho.

Regards
