### ISSUE TITLE
Request for implementation of share to Facebook on post, like in app

### ISSUE THREAD

**Issue by XantiumNZ** [mgp25/Instagram-API#2125]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

Some sort of way to do [instant Facebook sharing](https://b.catgirlsare.sexy/kwO5.png) with this API would be fantastic, as well as Twitter and Tumblr for other people to be able to use if necessary.

**Comment by mgp25** [comment]
This is something we wont do. Nevertheless, feel free to open a pull request if you add that part.

Regards
