### ISSUE TITLE
timeline update for user with 2-factor login

### ISSUE THREAD

**Issue by scarface10x** [mgp25/Instagram-API#2127]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ x] Question
- [ ] Other

---

Hi, I have often problems updating the timeline of users that use 2-factor login. I checked what application send in the POST request using a proxy, but I can see only strange characters. 
If I sniff the timeline request with a normal user (without 2-factor login), I can see parameters similar of the ones in your code. Can you help me understand what happens? It's like the content is encrypted for users with 2-factor login

**Comment by mgp25** [comment]
That doesn't make any sense. Please provide debug log.

**Comment by scarface10x** [comment]
I have burp requests, not the log.

This is the user without 2 factors login
![image](https://user-images.githubusercontent.com/42026964/43641673-dc0288a2-9724-11e8-89a9-bc18c84d6980.png)

And this is the one with the 2-factor login
![image](https://user-images.githubusercontent.com/42026964/43641781-3b82c65c-9725-11e8-8042-c4fa62d4ff1e.png)
