### ISSUE TITLE
Wrong count of following and can't get user id

### ISSUE THREAD

**Issue by drag0nman** [mgp25/Instagram-API#2129]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Implementation for get following user:

```php
    $rankToken = \InstagramAPI\Signatures::generateUUID();
    $maxId = null;
    do {
        $response = $ig->people->getFollowing($userId , $rankToken,null,$maxId);
        $users = $response->getUsers();
        foreach ($users as $key =>  $user)
        {
            echo "\n $key:".$user->getUsername();
        }
        $maxId = $response->getNextMaxId();
        echo "Sleeping for 5s...\n";
        sleep(5);
        echo "\nCount: ".count($users);
    } while ($maxId !== null); 

```

### Describe your issue

By Instagram real app the user has for instance 7500 following user but the  $user array has only 7359 elements. I got the array of user without pagination. Why can't get total of users following?

Thank you

**Comment by mgp25** [comment]
Hello, it is normal behavior, same occurs in the apps. In many occasions you won't be able to get the full list.

Regards

**Comment by drag0nman** [comment]
Hello

the result is always the same.
I supposed that if it was normal behavior the number should be different every time.


________________________________
Da: mgp25 <notifications@github.com>
Inviato: giovedì 2 agosto 2018 23:03
A: mgp25/Instagram-API
Cc: Giuseppe; Author
Oggetto: Re: [mgp25/Instagram-API] Wrong count of following and can't get user id (#2129)


Hello, it is normal behavior, same occurs in the apps. In many occasions you won't be able to get the full list.

Regards
