### ISSUE TITLE
Login_required (sometimes error)

### ISSUE THREAD

**Issue by polamoros** [mgp25/Instagram-API#213]
I'm having this error sometimes. I have a server managing 4 accounts.

**Comment by mgp25** [comment]
Force login

**Comment by borodulin** [comment]
Have the same issue with new created account (younger month). Old account works fine.

**Comment by polamoros** [comment]
@mgp25  Thanks!

**Comment by jbrabec** [comment]
Even if i try force login, there is still this error. Some accounts are fine, some not. Any ideas somebody?

**Comment by LoriKovari** [comment]
I got the "Login_required" stuff too but the login works fine for all accounts.The problem is that when i try to publish some accounts doesn't working due the "Login_required" error. Do u have any idea?
