### ISSUE TITLE
LoginResponse: Challenge required. Getting the URL.

### ISSUE THREAD

**Issue by Lars-** [mgp25/Instagram-API#2130]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ x ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

Okay, so you probably think "Oh, another Challenge required issue, he probably didn't look at others or at the faq." But I did :)
Problem is, your example doesn't work.

In the TwoFactorLogin, this code:
```
try {
    $loginResponse = $ig->login($username, $password);
    if ($loginResponse !== null ....
```
will fail if a challenge is required, because login() fails if a challenge is required. I need the URL of the challenge. How do I get it? I can see it if I enable debug, but not if I don't. I tried several things, but it always returns a fatal error which triggers the catch.

**Comment by Write** [comment]
Same problem here and can't find a solution inside the others tickets locked

**Comment by marciocamello** [comment]
Don't use over http, use with command php -f file.php, and use a proxy to solve challenge problems.

**Comment by Lars-** [comment]
That still throws a fatal error

**Comment by Stiveknx** [comment]
```
try {
$ig->login(); ...
} catch (\Exception $ex) {
	if(preg_match('/Challenge/', $ex->getMessage())) {
		if($ex->getResponse() && $ex->getResponse()->getChallenge()) {
			$challenge = $ex->getResponse()->getChallenge();
			if(is_array($challenge)) {
				var_dump($challenge);; // I still didn't figure it out, why this is an array, let me know. I think in this case, URL is in $challenge['challenge_url'];
			} else {
		                $url = $challenge->getUrl();
			}
		        echo "Challenge URL: " . $url;
		} 
	}
}

**Comment by mgp25** [comment]
- `LoginResponse` -> https://github.com/mgp25/Instagram-API/blob/master/src/Response/LoginResponse.php#L155

- `Model\Challenge` -> https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/Challenge.php

Plus, we don't support things related to the Challenge thing.

Regards
