### ISSUE TITLE
How can I send specific cookies

### ISSUE THREAD

**Issue by apirahim** [mgp25/Instagram-API#2132]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I am trying to preform some actions that it is not supported in this library using Instagram::request
My problem is this library when sending requests it doesn't include all the cookies specifically "mid" cookies ( which is critical for my request )

When I open the cookies.dat file, I see them there along with all other cookies
`[{"Name":"rur","Value":"FRC","Domain":".instagram.com","Path":"\/","Max-Age":null,"Expires":null,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"mcd","Value":"3","Domain":".instagram.com","Path":"\/","Max-Age":null,"Expires":false,"Secure":false,"Discard":false,"HttpOnly":false},{"Name":"csrftoken","Value":"VjKGMA2gneZlc5Kg5EHupTyZQaXP5mTS","Domain":".instagram.com","Path":"\/","Max-Age":"31449600","Expires":1564704367,"Secure":true,"Discard":false,"HttpOnly":false},{"Name":"mid","Value":"W2OcbwABAAF2Ktvuhr8LBPHcqKPS","Domain":".instagram.com","Path":"\/","Max-Age":"630720000","Expires":false,"Secure":false,"Discard":false,"HttpOnly":false}]`

But when the library send requests it only send "csrftoken" and "rur" in the cookies field, even that Instagram is setting the mid cookies over and over 

How can I fix it and force mid cookies to be sent along with all other cookies

**Comment by apirahim** [comment]
I think I found the problem, it is in the way guzzle store cookies 
https://github.com/guzzle/guzzle/blob/master/src/Cookie/SetCookie.php starting from line 72

as you see the max age for mid cookies is 630720000 + expires is set 20 years from now from instagram server, so somehow when guzzle calculate the expires he set it as false, then when a request is made, all the cookies with a false expires date are not used, which is causing this bug and who else know what 

anyway, I am going to try to make a small fix by myself, if I was correct can anyone be kind enough to report this to guzzle

**Comment by valga** [comment]
@apirahim It seems that you are using a x86 PHP build. Consider switching to a x64 one.

```
# x86
$ php -r "var_dump(strtotime('Thu, 29 Jul 2038 19:22:17 GMT'));"
bool(false)

# x64
$ php -r "var_dump(strtotime('Thu, 29 Jul 2038 19:22:17 GMT'));"
int(2164044137)
```
