### ISSUE TITLE
i want to request my own url use new Reqeust();

### ISSUE THREAD

**Issue by JKwang00** [mgp25/Instagram-API#2134]
Hi. good day.
i try to call reqeust my own url.

$url = "https://i.instagram.com/challenge/5839904/scnWulwi0A/";
$method = 1;

i putted my function in Instagram.php 
public function sendcode($url, $method) {
    $response = $this->request($url)
                    ->setNeedsAuth(false)
                    ->addPost('_uuid', $this->uuid)
                    ->addPost('_uid', $this->account_id)
                    ->addPost('choice', $method)
                    ->getResponse(new Response);
}

and i called this code after $ig->login();

$ig->sendcode($url, $method);

but i got this message

"This page could not be loaded. If you have cookies disabled in your browser, or you are browsing in Private Mode, please try enabling cookies or turning off Private Mode, and then retrying your action."

what did i make mistake??

thanks a lot.

**Comment by apirahim** [comment]
are you calling the login() with empty parameters ? or with $username and $password ?

**Comment by mercymainhere** [comment]
@JKwang00 Provided value is bad. Method "request" requires path, not a full url.

For example
`$this->request('challenge/5839904/scnWulwi0A/');`

**Comment by apirahim** [comment]
yes, you need to use Api path returned by your login request, also Important , you are going to need to remove the first slash (/) 
`$Api_Path= substr($Api_Path, 1);`
to become like this challenge/5839904/scnWulwi0A/

**Comment by JKwang00** [comment]
@mercymainhere , @apirahim 
it's so wonderful, thanks a lot guys!
