### ISSUE TITLE
help me for mgp25 project

### ISSUE THREAD

**Issue by saeedkarimi71** [mgp25/Instagram-API#2135]
how to solve this:
Warning: require(/storage/ssd4/813/3170813/public_html/ins/../vendor/autoload.php): failed to open stream: No such file or directory in /storage/ssd4/813/3170813/public_html/ins/ins.php on line 3

Fatal error: require(): Failed opening required '/storage/ssd4/813/3170813/public_html/ins/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd4/813/3170813/public_html/ins/ins.php on line 3

**Comment by valga** [comment]
@saeedkarimi71 https://getcomposer.org/
