### ISSUE TITLE
Trying to getUsers() of a Media throw Virtual property access is disabled for class "\InstagramAPI\Response\Model\User"

### ISSUE THREAD

**Issue by Write** [mgp25/Instagram-API#2137]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```
	try {

	    $userId = $ig->people->getUserIdForName('xxx');
	    $maxId = null;
	    $response = $ig->timeline->getUserFeed($userId, $maxId);
	    foreach ($response->getItems() as $item) {
		    $response = $ig->media->getLikers($item->getId())->getUsers();
	   		foreach ($response as $key => $user)
	        {
	            if ($user->getIsPrivate())
	        		echo $item->getId().'User : ' . $user->getUsername . ' is private ! '. '<br>';
	        	else 
	            	echo $item->getId().'User : ' . $user->getUsername . ' is private ! '. '<br>';
	        }
	        
	    }
	} 
```

Error Log/var_dump:

```php
Virtual property access is disabled for class "\InstagramAPI\Response\Model\User"
```

### Describe your issue

I'm trying to get access to users who liked posts but when i do that it throws Virtual property access is disabled for class "\InstagramAPI\Response\Model\User" How can i fix this ? Basically what i try to do is to get Object User from getLikers. 

Thanks !

**Comment by mgp25** [comment]
Hello @Write,

It seems you have missed this guide: [Wiki - Managing Responses](https://github.com/mgp25/Instagram-API/wiki#managing-responses)

Regards
