### ISSUE TITLE
Something Problem in Registering Account

### ISSUE THREAD

**Issue by tyfopart** [mgp25/Instagram-API#214]
The registration script runs fine, after I edit a bit in some parts.

but, why my registered account, thus not available on instagram? but the script had already been declared the successful result, this [account_created] = > 1 & [status] => ok

Result showed that the registration process was successful, but why when i looking for the account on Instagram thus not available?

Please help me to solve this problem.

this the json result:

`Array ( [username] => brownwolf814 [password] => testingaccountx [email] => brownwolf814@gmail.com [first_name] => Carter [device_id] => a2e070e3-794b-4e02-9e62-7ae70f282df6 [_uuid] => a2e070e3-794b-4e02-9e62-7ae70f282df6 [csrftoken] => missing ) Array ( [status] => ok [created_user] => Array ( [username] => brownwolf814 [has_anonymous_profile_picture] => 1 [nux_private_first_page] => [profile_pic_url] => http://scontent-sit4-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg [full_name] => Carter [pk] => 3402093033 [hd_profile_pic_url_info] => Array ( [url] => http://scontent-sit4-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg [width] => 150 [height] => 150 ) [nux_private_enabled] => [is_private] => ) [account_created] => 1)`

thankyou team!

**Comment by mgp25** [comment]
Sometimes because of the IP or because of multiple registration, Instagram don't create the account in order to avoid spam or bulk requests.

I just tested the registration script, and so fat it works well.

Regards

**Comment by tyfopart** [comment]
can you update InstagramRegistration script?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/examples/registrationTool.php
