### ISSUE TITLE
hot can i get 'instance of /Model/Location' using findPlaces?

### ISSUE THREAD

**Issue by woodam00** [mgp25/Instagram-API#2142]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

HI. everyone.

I searched location use findPlaces. this is my code

$response = $ig->location->findPlaces($q);
foreach ($response->getItems() as $item) {
        $location = $item->getLocation();
        // i must use location->search->getVenues()[0] to use get 'instance of /Model/Location class' in here?

}

$metadata = [
        'caption' => 'My awesome caption',
        'location' => $location, // $location must be an instance of /Model/Location class
];
            
$ig->timeline->uploadPhoto($outputFile, $metadata);

but i got message :
Fatal error: Uncaught InvalidArgumentException: You are not allowed to use Location model objects from the Facebook-based location search functions. They are not valid media locations!

help me please.
Thank you and Take care.

**Comment by valga** [comment]
@woodam00 The documentation for `findPlaces()` method clearly says that you can't use it for uploads: https://github.com/mgp25/Instagram-API/blob/a640aae361cb895c64234d453b416e5044c33ae7/src/Request/Location.php#L53-L54
