### ISSUE TITLE
Challenge required

### ISSUE THREAD

**Issue by Lars-** [mgp25/Instagram-API#2143]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hello again,

Another problem with challenge required. Well, I get this message on some accounts. I tried enabling 2FA, I tried other IPs and of course I tried to do the challenge. Nothing works. The weird part is that I can login (with the same IP) on the ig website and app. 

What am I doing wrong?

**Comment by mercymainhere** [comment]
It is very easy. You can login with the same IP becasue you already confirmed device (PC or phone) in Instagram. Challenge required verifies that you are a human not a machine. If you pass this once, it's gone.

My solution for this problem was creating request for **challenge required**. Just catch exception and get data from request that is in that exception. There is everything you need to create request.

I am currently at work, but when I return home, I will try to find my code and post it here.

**Comment by Lars-** [comment]
Well, if I do the challenge (go to the URL and verify by text or email), I still get the challenge required message. That's kind of the problem.

Thank you for your answer anyway and I still am curious about your code :)

**Comment by afedkina1024** [comment]
I have the same problem.

**Comment by yatsenkolesh** [comment]
I have the same problem.

**Comment by mercymainhere** [comment]
@Lars- sorry I didn't post this yesterday. This is code that I use:
```
try {
    $loginResponse = $Instagram->login($accountObject->getUsername(), $accountObject->getRawPassword());
    $accountObject->setInstagramId($Instagram->account_id);

    if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()) {
        $accountObject->setTwoFactorIdentifier($loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier());
    }

    if ($loginResponse instanceof LoginResponse || $loginResponse === null) {
        //Other stuff.
    }
} catch (Exception $Exception) {
    if ($Exception instanceof ChallengeRequiredException) {
        sleep(5);
        
        $customResponse = $Instagram->request(substr($Exception->getResponse()->getChallenge()->getApiPath(), 1))->setNeedsAuth(false)->addPost("choice", 0)->getDecodedResponse();

        if (is_array($customResponse)) {
            $accountObject->setInstagramId($customResponse['user_id']);
            $accountObject->setChallengeIdentifier($customResponse['nonce_code']);

            //Other stuff.
        } else {
            //Other stuff.
        }
    } else {
        //Other stuff.
    }
}
```
As you can see if **ChallengeRequiredException** is thrown I send request to url received from response. This request contains **choice** field which tells Instagram what method you want to use to verify that you are a human (0 is for SMS and, if I remember correctly, 1 is for E-Mail).

After that Instagram sends a code (by E-Mail or SMS, depends what you choose) and I use this to complete verification process:

```
try {
    $Instagram->changeUser($accountObject->getUsername(), $accountObject->getRawPassword());
    $customResponse = $Instagram->request("challenge/".$accountObject->getInstagramId()."/".$accountObject->getChallengeIdentifier()."/")->setNeedsAuth(false)->addPost("security_code", $Code)->getDecodedResponse();

    if (!is_array($customResponse)) {
        //Other stuff.
    }

    if ($customResponse['status'] == "ok" && (int)$customResponse['logged_in_user']['pk'] === (int)$accountObject->getInstagramId()) {
        //Other stuff.
    }
} catch (Exception $Exception) {
    //Other stuff.
}
```

Of course **security_code** is a received code. I hope script is simple enough to understand.
_//Other stuff._ is just database stuff or error displaying stuff.
`changeUser` method is `_setUser` method but public.

I used this code only two times for my account (second time was when I changed proxy) and for now I don't have any challenge required problems.

**Comment by yatsenkolesh** [comment]
@Lars- just to to change account for auth. It's working for me. You are need to create new account and use it.

**Comment by Lars-** [comment]
@yatsenkolesh thank you for your answer, but creating a new account is not an option since this account has 18k followers.

**Comment by Lars-** [comment]
@bas321 you should change the code in quite some ways to get it to work. First of all `$AccountObject` is something @mercymainhere implemented somewhere else, so you should get rid of that. And you should also create a public function `changeUser` which calls `_setUser` (this has to happen in the package itself (other option is to make `_setUser` public. Then you need to add some echos/var-dumps to know what numbers you need to enter where.

The first part is to create a challenge identifier and send the code. The second part is to validate the user with this validation code (the six digits).

**Comment by galanx** [comment]
@mercymainhere @Lars- 

I wonder how it worked for you guys, but for me when trying to validate with received code I get the "failed" response:

`array:2 [▼
  "message" => "This field is required."
  "status" => "fail"
]`

This is the code I use which sends the SMS but can't confirm it:

```
    $ig = new Instagram();
    $ig->setUser($channel->username, $channel->password);
    //dd($ig->client);
    // $customResponse = $ig->request($challengeUrl."/")
    // ->setNeedsAuth(false)
    // ->addPost("choice", 0)
    // ->getRawResponse();

    $customResponse = $ig->request($challengeUrl."/")
    ->setNeedsAuth(false)
    ->addPost("security_code", "321689")
    ->getRawResponse();
```

Thanks for your input by the way, very useful. :)

**Comment by Lars-** [comment]
@galanx I had the same problem. Trick is to delete all cookies first (in vendor/mgp25/instagram-php/sessions or in your database (depending on what you configured)). Then execute the first part of @mercymainhere s code. Then you'll receive a challenge identifier and a user ID. Enter that information in the second part and replace $Code with a string of the 6-digit code and execute the second part. I expect that you ensured that both parts work first (no syntax errors and such).

**Comment by galanx** [comment]
@Lars-

Isn't the user id and the challenge identifier part of the challenge url that you get from the exception api path? I have it set up to the point where i get the code via SMS
Then I comment that part and execute the other part as you saw above with the code I received, which resulted on "this field is required". I have no syntax errors whatsoever. I have also extended the main Instagram class and made a setUser public function as required.

**Comment by szokeptr** [comment]
You need to send additional parameters with that request (uuid if I remember correctly). You need to check what the Android app does and build the same request.

**Comment by Lars-** [comment]
@galanx You should execute the following code:
```php
$username = '';
$password = '';
$user_id = '123';
$challenge_id = 'sjsfnf';
$Code = 'Code you received by SMS';
try {
    $Instagram->changeUser($username, $password);
    $customResponse = $Instagram->request("challenge/".$user_id."/".$challenge_id."/")->setNeedsAuth(false)->addPost("security_code", $Code)->getDecodedResponse();

    if (!is_array($customResponse)) {
        //Other stuff.
    }

    if ($customResponse['status'] == "ok" && (int)$customResponse['logged_in_user']['pk'] === (int)$accountObject->getInstagramId()) {
        echo 'Finished!';
    }
} catch (Exception $Exception) {
    //Other stuff.
}
```

Be sure to *first* remove all sessions related to this user as I mentioned above. Otherwise, Instagram will think that you are trying to try again which result in the error you describe.

**Comment by Lars-** [comment]
@galanx I will make a full example for you based on @mercymainhere s code

**Comment by Lars-** [comment]
@galanx try this. Haven't tested it completely, but I think it works as it should :)
```php
<?php

use InstagramAPI\Exception\ChallengeRequiredException;
use InstagramAPI\Instagram;
use InstagramAPI\Response\LoginResponse;

require __DIR__ . '/vendor/autoload.php';

//Enter these options
$username            = 'insta_dm.it';
$password            = '18Donuts';
$verification_method = 0; //0 = SMS, 1 = Email

//Leave these
$user_id      = '';
$challenge_id = '';

class ExtendedInstagram extends Instagram {
	public function changeUser( $username, $password ) {
		$this->_setUser( $username, $password );
	}
}

function readln( $prompt ) {
	if ( PHP_OS === 'WINNT' ) {
		echo "$prompt ";

		return trim( (string) stream_get_line( STDIN, 1024, PHP_EOL ) );
	}

	return trim( (string) readline( "$prompt " ) );
}

$instagram = new ExtendedInstagram();

try {
	$loginResponse = $instagram->login( $username, $password );
	$user_id       = $instagram->account_id;

	if ( $loginResponse !== null && $loginResponse->isTwoFactorRequired() ) {
		echo '2FA not supported in this example';
		exit;
	}

	if ( $loginResponse instanceof LoginResponse || $loginResponse === null ) {
		echo "Not a challenge required exception...\n";
	}

	echo 'Logged in!';
} catch ( Exception $exception ) {
	/** @var LoginResponse $response */
	if ( ! method_exists( $exception, 'getResponse' ) ) {
		echo $exception->getMessage();
		exit;
	}
	$response = $exception->getResponse();

	if ( $exception instanceof ChallengeRequiredException ) {
		sleep( 5 );

		$customResponse = $instagram->request( substr( $response->getChallenge()->getApiPath(), 1 ) )->setNeedsAuth( false )->addPost( 'choice', $verification_method )->getDecodedResponse();

		if ( is_array( $customResponse ) ) {
			$user_id      = $customResponse['user_id'];
			$challenge_id = $customResponse['nonce_code'];
		} else {
			echo "Weird response from challenge request...\n";
			var_dump( $customResponse );
			exit;
		}
	} else {
		echo "Not a challenge required exception...\n";

		var_dump( $response );
		exit;
	}

	try {
		$code = readln( 'Code that you received via ' . ( $verification_method ? 'email' : 'sms' ) . ':' );
		$instagram->changeUser( $username, $password );
		$customResponse = $Instagram->request( "challenge/$user_id/$challenge_id/" )->setNeedsAuth( false )->addPost( 'security_code', $code )->getDecodedResponse();

		if ( ! is_array( $customResponse ) ) {
			echo "Weird response from challenge validation...\n";
			var_dump( $customResponse );
			exit;
		}

		if ( $customResponse['status'] === 'ok' && (int) $customResponse['logged_in_user']['pk'] === (int) $user_id ) {
			echo 'Finished, logged in successfully! Run this file again to validate that it works.';
		}
	} catch ( Exception $Exception ) {
		//Other stuff.
	}
}
```

**Comment by Alabahala** [comment]
@Lars- I just tried your code and when i submit the code IG reponds with

**Comment by Lars-** [comment]
@Alabahala run the code again

**Comment by Alabahala** [comment]
@Lars- it asks for the challenge again :| 
Maybe is because I have 2FA?

**Comment by Lars-** [comment]
@Alabahala the example does not support 2FA

**Comment by Alabahala** [comment]
@Lars- I know that this example does not support 2FA, but the console didn't print the echo "2FA not supported in this example" so I assume the login response isn't  asking for 2FA

**Comment by Lars-** [comment]
@Alabahala Absolutely true. I don't know why it's happening... Maybe an enter in the $code or something?

**Comment by Alabahala** [comment]
@Lars- I disabled 2FA and it worked, but I need 2FA enabled :S

**Comment by Lars-** [comment]
@Alabahala Nice 😄 If you need 2FA, I suggest you upgrade my code and share your result with us

**Comment by galanx** [comment]
@Lars- 

Thanks for trying to help me out! I implemented your code 100% as is (of course gave in my username and password), I execute it via command line and I get the code via sms. When I submit it, it still keeps telling me "This field is required". I always delete the cookies and settings folder before executing the challenge script, but no luck. I am really curious as to why it works with you guys . I am using proxy as well btw, however tried without proxy and no luck there either.

**Comment by szokeptr** [comment]
@galanx see my previous comment.

**Comment by Lars-** [comment]
@galanx Very weird :s @szokeptr why don't I need the UUID?

**Comment by Lars-** [comment]
@szokeptr I don't agree. If I try the challenge with a browser, I even get the "This field is required" error sometimes. Mostly when I'm using the e-mail verification. And I'm using the latest version 😉 Please share your code so that we can learn from it.

@galanx It works for me without the UUID and stuff.

**Comment by galanx** [comment]
@Lars-  @szokeptr 

I have a working version that is separate from the mgp25 library. I manage to verify it but I am then unable to resume the same login via this library, that's my only issue. As per additional parameters, there seems to be an additional parameter called "csrfmiddlewaretoken" that I am sending with the code as a post param, without that, I seem to get the same error there too. However, I am not sure how to get this "csrfmiddlewaretoken" with your implementation. 

I am really wondering why it works with you guys, I am doing everything the same 100%.

**Comment by szokeptr** [comment]
@Lars- did you even inspect the traffic of the Android app?

@galanx I just checked, the request needs security_code, _csrftoken, guid (this is the UUID) and device_id as post params. I don't have code sample because I don't have this implemented as I don't need this functionality.

**Comment by Lars-** [comment]
@szokeptr Nope, but it works for me

**Comment by szokeptr** [comment]
@Lars- @galanx  this is the actual request sent by the app: https://imgur.com/a/dKc8R66

**Comment by szokeptr** [comment]
Remove the ->setSignedPost() as this will set it to null, and the params are not signed.
This API has nothing to do with the web API and you should never mix the two.

**Comment by galanx** [comment]
@szokeptr 
Yes, same result sadly. If the challenge url wasn't correct, it wouldn't show "Field is required" message I guess. :/

**Comment by jackottowa** [comment]
Can anyone get this fully working? Experiencing the same issue as @galanx

**Comment by skayerok** [comment]
I can separately login by entering challenge verification code, using code examples from this thread, or by entering verification code from 2FA.
But if I need to do both at the same time I get: 
`{u'action': u'close', u'status': u'ok'}`
after I enter code from challenge.

Does anyone know how to solve this?

**Comment by Lars-** [comment]
That probably means that it’s okay and you’ve logged in.

 

Van: Pavel <notifications@github.com> 
Verzonden: vrijdag 10 augustus 2018 17:05
Aan: mgp25/Instagram-API <Instagram-API@noreply.github.com>
CC: Lars Jansen <jansenco101@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mgp25/Instagram-API] Challenge required (#2143)

 

I can separately login by entering challenge verification code, using code examples from this thread, or by entering verification code from 2FA.
But if I need to do both at the same time I get:
{u'action': u'close', u'status': u'ok'}
after I enter code from challenge.

Does anyone know how to solve this?

**Comment by farhanansari** [comment]
I"m getting the same result "This field is required" after entering the code.  Definitely some parameter is missing when submitting the code.  

@skayerok What version of this API are you using to test this code?

**Comment by farhanansari** [comment]
I do have a challenge_required script working from older version of this api.  If anyone of you need to see the code you can email me. I wouldn't mind sharing.  I just can't get it to work for 3.1 or 4x version of this api.  My email is in my bio.

**Comment by galanx** [comment]
@farhanansari 

The version of @Lars- is working now for some mysterious reasons. Just be sure to clear the cookies before sending the choice option and after verifying you have to call updateLoginState and sendLoginFlow with true boolean to refresh the timeline to simulate real user behavior (See 2 factor login example). 

Very weird, since I did the same before and was getting the same error. I am curious about your working version and as to why it doesn't work with latest one, will contact you via email.

Another weird behavior I saw is it verifies every user, however with some users, after calling the login method, it throws challenge required exception again. I noticed the cookie "expires" value is being set to negative value for some attributes where it was marked "false" before.

**Comment by farhanansari** [comment]
Yes, you are correct.  I do get error sometimes but then sometimes I don't.  Sometimes it says "Finished.  logged in successfully...." but when I run it again I get challenge again.  It must be due to not calling updateLoginState and sendLoginFlow.  So I added following:

`class ExtendedInstagram extends Instagram {
   public function changeUser( $username, $password ) {
      $this->_setUser( $username, $password );
   }

   public function finishChallange($response, $appRefreshInterval) {
        $this->_updateLoginState($response);
        $this->_sendLoginFlow(true, $appRefreshInterval);
   }

}` 

My issue is that when I call $instagram->finishChallange($customResponse, 1800); I get error 

"Argument 1 passed to InstagramAPI\Instagram::_updateLoginState() must be an instance of InstagramAPI\Response\LoginResponse,"  

Above is correct as line:       $customResponse = $instagram->request( substr( $response->getChallenge()->getApiPath(), 1 ) )->setNeedsAuth( false )->addPost( 'choice', $verification_method )->getDecodedResponse(); does not return LoginResponse.

What am I missing?

**Comment by galanx** [comment]
@farhanansari 
You need to import Login response in your extended class and expect that response from the challenge request instead of getDecodedResponse. Check 2f auth as example.

**Comment by 1vanov** [comment]
Hi guys! I just used @Lars- code and every time I get 500 server error here:

$customResponse = $instagram->request(substr($response->getChallenge()->getApiPath(), 1))->setNeedsAuth(false)->addPost('choice', $verification_method)->getDecodedResponse();

I tried without "getDecodedResponse()", inspected $customResponse and get this:

["_httpResponse":protected]=>
  NULL

What's a problem with request?

**Comment by noobikz0r** [comment]
@1vanov
1) Did you check `challenge` object? Sometimes it's array instead of object.
2) You can enable debug for the `Instagram` instance and check requests/responses:
```php
$client = new Instagram(true); // The first parameter is debug flag
```

**Comment by sololance** [comment]
Hi guys, having same issue with "This field is required".

Can somebody share code that works?

Thank you in advance.

**Comment by galanx** [comment]
@sololance and whoever is getting "This field is required", the solution is as follows. 

You have 2 requests, the first one is when you send the choice, and the second one where you send the code that you receive.

Make sure that you delete the cookies and settings before the 1st request, and make sure that the cookies exist (are created by the 1st request) for the code request. Deleting the cookies before sending the code will result in that error.

**Comment by mgp25** [comment]
I just did some changes to fit requests from the device. The rest is up to you guys

```php
<?php

require __DIR__ . '/vendor/autoload.php';

//Enter these options
$username            = '';
$password            = '';
$verification_method = 0; 	//0 = SMS, 1 = Email


class ExtendedInstagram extends Instagram {
	public function changeUser( $username, $password ) {
		$this->_setUser( $username, $password );
	}
}

function readln( $prompt ) {
	if ( PHP_OS === 'WINNT' ) {
		echo "$prompt ";

		return trim( (string) stream_get_line( STDIN, 6, "\n" ) );
	}

	return trim( (string) readline( "$prompt " ) );
}

$ig = new ExtendedInstagram();

try {
	$loginResponse = $ig->login( $username, $password );
	echo 'Logged in!';
} catch ( Exception $exception ) {

	$response = $exception->getResponse();

	if ($exception instanceof ChallengeRequiredException
	&& $response->getErrorType() === 'checkpoint_challenge_required') {

		sleep(3);

		$checkApiPath = substr( $response->getChallenge()->getApiPath(), 1);
		$customResponse = $ig->request($checkApiPath)
									->setNeedsAuth(false)
									->addPost('choice', $verification_method)
									->addPost('_uuid', $ig->uuid)
									->addPost('guid', $ig->uuid)
									->addPost('device_id', $ig->device_id)
									->addPost('_uid', $ig->account_id)
									->addPost('_csrftoken', $ig->client->getToken())
									->getDecodedResponse();

	} else {
		echo "Not a challenge required exception...\n";
		exit;
	}

	try {

		if ($customResponse['status'] === 'ok' && $customResponse['action'] === 'close') {
			echo 'Checkpoint bypassed';
		}

		$code = readln( 'Code that you received via ' . ( $verification_method ? 'email' : 'sms' ) . ':' );
		$ig->changeUser( $username, $password );
		$customResponse = $ig->request($checkApiPath)
									->setNeedsAuth(false)
									->addPost('security_code', $code)
									->addPost('_uuid', $ig->uuid)
									->addPost('guid', $ig->uuid)
									->addPost('device_id', $ig->device_id)
									->addPost('_uid', $ig->account_id)
									->addPost('_csrftoken', $ig->client->getToken())
									->getDecodedResponse();

		if ($customResponse['status'] === 'ok' && (int) $customResponse['logged_in_user']['pk'] === (int) $user_id ) {
			echo 'Finished, logged in successfully! Run this file again to validate that it works.';
		} else {
			echo "Probably finished...\n";
			var_dump( $customResponse );
		}
	} catch ( Exception $ex ) {
		echo $ex->getMessage();
	}
}
```

**Comment by jay-webmavens** [comment]
@mgp25 
When i add your code first few hours i get "challenge required" Error after some time when i run code repeatedly then i got below response instead of   "challenge required" Please help me 
[message] => checkpoint_required
[checkpoint_url] => https://i.instagram.com/integrity/checkpoint/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss
[lock] => 1
[status] => fail
[error_type] => checkpoint_logged_out

**Comment by farhanansari** [comment]
Can't seem to get rid of checkpoint_required.  Same issue here...

**Comment by luisfavila** [comment]
I still get "This field is required" with that code @mgp25

**Comment by bolds07** [comment]
I'm having problem trying to use this code (as many people reported)
when I do...

```
$customResponse = $ig->request($checkApiPath)
									->setNeedsAuth(false)
									->addPost('choice', $verification_method)
									->addPost('_uuid', $ig->uuid)
									->addPost('guid', $ig->uuid)
									->addPost('device_id', $ig->device_id)
									->addPost('_uid', $ig->account_id)
									->addPost('_csrftoken', $ig->client->getToken())
									->getDecodedResponse();
```

the response always is: ` {"action": "close", "status": "ok"}`, no e-mail nor sms are sent and i still get the challenge if try to login again...

but if for this same account, same ip i try to login over web they show me the challenge page and when i click on i do receive the email... (Im just trying to emphasize that the problem is not ip or account)

**Comment by bolds07** [comment]
there is something more happening which I personally dont understand.

using the lastest @mgp25 code:

a) if i remove `$ig->changeUser( $username, $password );` it returns `logged_in_user": {bla bla bla}` but any next request asks for a new challenge

b) if I use the code as is I get code 400 `{"message": "This field is required.", "status": "fail"}` as many others reported

**Comment by mihey8800** [comment]
@bolds07 have u found the solution?

 in @mgp25 code 

$customResponse = $ig->request($checkApiPath)
									->setNeedsAuth(false)
									->addPost('choice', $verification_method)
									->addPost('_uuid', $ig->uuid)
									->addPost('guid', $ig->uuid)
									->addPost('device_id', $ig->device_id)
									->addPost('_uid', **$ig->account_id**)
									->addPost('_csrftoken', $ig->client->getToken())
									->getDecodedResponse();

**$ig->account_id** is always null.  I tryied to send $user_id = explode("/",$checkApiPath)[1]; instead $ig->account_id. Error is same. What field is needed? I can't parse instagram traffic from phone(

**Comment by hoemon** [comment]
looking for a solution as well..
