### ISSUE TITLE
Transcode error: Video file does not contain duration

### ISSUE THREAD

**Issue by taha** [mgp25/Instagram-API#2145]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [x] Other

---

Hi,

I'm using the Timeline::uploadVideo method as described in the example. However, Instagram rejects ~50% of the videos I've tested with (the error below). My code is literally identical to the example's (also using `\InstagramAPI\Media\Video\InstagramVideo` for video processing).

I've tried converting the failed videos with various tools (e.g. HandBrake on macOS), even tried to manually set the duration for the video in ffmpeg (using `-t` argument) with no luck.

Any idea how to work around this issue?

**EDIT:** I forgot to mention that the same rejected videos by Timeline::uploadVideo work fine when fed to Timeline::uploadAlbum

**Code**
```php
$video = new \InstagramAPI\Media\Video\InstagramVideo($videoFilename);
$ig->timeline->uploadVideo($video->getFile(), ['caption' => $captionText]);
```

**Error Response**
```
400 	 86B
RESPONSE: {"message": "Transcode error: Video file does not contain duration", "status": "fail"}
RuntimeException: All configuration retries have failed.
```

**Comment by mgp25** [comment]
Try this:

```php
$video = new \InstagramAPI\Media\Video\InstagramVideo($videoFilename, ['targetFeed' => \InstagramAPI\Constants::FEED_TIMELINE]);
```

You can change the target feed to fit your requirements. Let me know if that worked.

**Comment by valga** [comment]
@taha Please share the video file you have problems with.

**Comment by taha** [comment]
@mgp25 that didn't work :/

@valga [test.mp4.zip](https://github.com/mgp25/Instagram-API/files/2272097/test.mp4.zip) (A video I grabbed of an Instagram video post)

**Comment by valga** [comment]
@taha Your video works for me with all 3 video uploaders. Are you sure it is failing for you?

By the way, do you use latest dev-master version?

**Comment by taha** [comment]
I just tried it again now and it still fails with the dev-master version (same error). Would you mind sharing your code @valga? Perhaps I can test with it to make sure?

If it continues failing then it could be my environment. I'm installing ffpmeg on the official PHP docker image (Alpine 3.7)

**Comment by mgp25** [comment]
Works for me as well.

```php
$video = new \InstagramAPI\Media\Video\InstagramVideo('test.mp4', ['targetFeed' => \InstagramAPI\Constants::FEED_TIMELINE]);
$i->timeline->uploadVideo($video->getFile());
```

Regards
