### ISSUE TITLE
If Session Exist Login with Session

### ISSUE THREAD

**Issue by burakbuylu** [mgp25/Instagram-API#2146]
Hello,

I want to login with session but every refresh its login with username and password. The performance can be killing with this.

If Session Exist Login with Cookie another login with username and password How can we do this ?

Thanks.

**Comment by mrladeia** [comment]
https://github.com/mgp25/Instagram-API/issues/1845

**Comment by mgp25** [comment]
If the session exists the API will reuse the session. If it has an invalid session it will login from zero.

You can find more information:

- `login()` https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L399
- `_setUser()` https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L747

Regards
