### ISSUE TITLE
Once use  $ig->login in php

### ISSUE THREAD

**Issue by milad7091** [mgp25/Instagram-API#2148]
hello.
i use instagram/api for php.
I just want to use one of the $ig->logins($username, $password).
And then I can use the "$userId = $ig->people->getUserIdForName('instagram');" on other pages of my site. Without having to re-enter the login command at the beginning of each page.

Please use the $ig->logins($username, $password) command in one page and use  $ig->people->getUserIdForName('instagram'); command on the other page.

Tanks.

**Comment by mgp25** [comment]
Then don't destroy the object and maintain the session or modify the code to fit your requirements.
