### ISSUE TITLE
My system is very slow

### ISSUE THREAD

**Issue by muhammet205** [mgp25/Instagram-API#2149]
Hi, my system is very slow. Example

Login user -> follow user  (15 second - 1 follower)
I want to fast system. Example (15 second - 100 followers)

What should I do ? Please help me

**Comment by muhammet205** [comment]
My code

Try{
$login = $ig->login($username,$password);
$follow = $ig->people->follow($user_id);
} catch(Exception $e){
.......

1 follower lasts 15 seconds. I want to 100 followers 15 second

**Comment by takemore** [comment]
Hi, 
In this case your account will be blocked, because spam. You need to simulate like a real user.
