### ISSUE TITLE
Highlight: EmptyResponseException

### ISSUE THREAD

**Issue by clouddev-elias** [mgp25/Instagram-API#2153]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
$this->highlight->create($mediaIds, $title = 'Highlights', null, $module = 'self_profile');
```

Error Log/var_dump:

```php
InstagramAPI\Exception\EmptyResponseException: No response from server. Either a connection or configuration error.
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
POST:  https://i.instagram.com/api/v1/highlights/create_reel/
DATA: signed_body=a06c13f51494cc5d452f7d4d6354b0911d3865599b82547ee50f67e1f5a4d7fe.{"source":"self_profile","_csrftoken":"Uo2ik914G3i94V69UMbNMIy4lCcZbhVg","_uid":"7761726375","_uuid":"9e8fae04-50db-4388-a92a-bf0667e8d746","cover":"{\"media_id\":\"***ID_MANUALLY_REMOVED***\",\"crop_rect\":\"[0.0, 0.19543147, 1.0, 0.8045685]\"}","title":"Highlights","media_ids":"[\"***ID_MANUALLY_REMOVED***\"]"}&ig_sig_key_version=4
← 500    25B
```

Response:

```http
RESPONSE: Oops, an error occurred.
```
---

### Describe your issue

By testing. I am trying to create a simple Highlight with a simple Image/mediaId. I have removed the mediaId from the post request. 

What did i miss here?

**Comment by clouddev-elias** [comment]
It seems to create the highlight, however the response is still the same.

**Comment by clouddev-elias** [comment]
Posting edit to Highlight, throws exceptions aswell
`POST:  https://i.instagram.com/api/v1/highlights/highlight:17943085948093659/edit_reel/`

`RESPONSE: {"message": "Failed to edit reel.", "status": "fail"}`

This is propably outdated aswell
https://github.com/mgp25/Instagram-API/blob/887dca6afb905a12ce63cb604d73d7afb6c72763/src/Request/Highlight.php#L117

**Comment by clouddev-elias** [comment]
Hello, this one still returns Exception after updating

**Comment by mgp25** [comment]
@clouddev-elias provide more details, info, debug log...

**Comment by clouddev-elias** [comment]
```php
$this->highlight->edit($highLightId, $params = ['add_media' => $addMedia, 'remove_media' => $items, "cover_media_id" => $addMedia[0]], $module = 'self_profile');
````
```php
InstagramAPI\Exception\EndpointException: InstagramAPI\Response\HighlightFeedResponse: Failed to edit reel.

**\vendor\mgp25\instagram-php\src\Exception\ServerMessageThrower.php:190
**\vendor\mgp25\instagram-php\src\Client.php:579
**\vendor\mgp25\instagram-php\src\Request.php:793
**\vendor\mgp25\instagram-php\src\Request\Highlight.php:148
```
RESPONSE: `{"message": "Failed to edit reel.", "status": "fail"}`


If you need more info, let me know.

**Comment by clouddev-elias** [comment]
1) Tests\Feature\InstaHighLightTest::testExample
InstagramAPI\Exception\EmptyResponseException: No response from server. Either a connection or configuration error.

**\vendor\mgp25\instagram-php\src\Client.php:493
**\vendor\mgp25\instagram-php\src\Request.php:793
**\vendor\mgp25\instagram-php\src\Request\Highlight.php:99
