### ISSUE TITLE
socks5 proxy through IPv6 problem

### ISSUE THREAD

**Issue by nobilik** [mgp25/Instagram-API#2156]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');
require_once(__DIR__ . '/vendor/autoload.php');

 
const DEBUG = true;
const TRANCATED_DEBUG = false;


$client = new React\HttpClient\Client($loop);

if (DEBUG) {
    $logger = new \Monolog\Logger('push');
    $logger->pushHandler(new \Monolog\Handler\StreamHandler('php://stdout', \Monolog\Logger::INFO));
} else {
    $logger = null;
}
$ig = new \InstagramAPI\Instagram(DEBUG, TRANCATED_DEBUG, []);

// Below are two ways to set proxy. Let it be first and second.
$ig->setProxy(['proxy' => ['https' => 'http://proxy_params', 'http' => 'http://proxy_params']]); //first
$ig->setProxy('socks5://proxy_params'); //second

$loginResponse = $ig->login("login", "password");

$loop = \React\EventLoop\Factory::create();

$push = new \InstagramAPI\Push($loop, $ig, $logger);
$push->on('incoming', function (\InstagramAPI\Push\Notification $push) {
        printf('%s%s', $push->getMessage(), PHP_EOL);
 });

$push->start();
$loop->run();
```

Error Log/var_dump:
With first way (proxy params are an array)
```php

[2018-08-13 05:09:18] push.ERROR: No proxy with CONNECT method found. [] []
[2018-08-13 05:09:18] push.INFO: Existing reconnect timer has been canceled. [] []
[2018-08-13 05:09:18] push.INFO: Setting up reconnect timer to 2 seconds. [] []
[2018-08-13 05:09:20] push.INFO: Connecting to mqtt-mini.facebook.com:443... [] []
[2018-08-13 05:09:20] push.ERROR: No proxy with CONNECT method found. [] []
[2018-08-13 05:09:20] push.INFO: Existing reconnect timer has been canceled. [] 

```
With second (proxy params are string)
```php

PHP Warning:  Uncaught InstagramAPI\Exception\NetworkException: Network: CURL error 7: Can't complete SOCKS5 connection to ipv6_address. (5) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html). in /vendor/mgp25/instagram-php/src/Client.php:646
Stack trace:
#0 /vendor/mgp25/instagram-php/src/Client.php(709): InstagramAPI\Client->_guzzleRequest(Object(GuzzleHttp\Psr7\Request), Array)
#1 /vendor/mgp25/instagram-php/src/Client.php(778): InstagramAPI\Client->_apiRequest(Object(GuzzleHttp\Psr7\Request), Array, Array)
#2 /vendor/mgp25/instagram-php/src/Request.php(715): InstagramAPI\Client->api(Object(GuzzleHttp\Psr7\Request), Array)
#3 /vendor/mgp25/instagram-php/src/Request.php(736): InstagramAPI\Request->getHttpResponse()
#4 /vendor/mgp25/instagram-php/src/Request.php(792): InstagramAPI\Request->getRawResponse()
#5 /vendor/mgp25/instagr in /vendor/mgp25/instagram-php/src/Client.php on line 646

```
Hi! I have a problem with socks5 proxy through IPv6. When I try to pass proxy params as string it can't login. For IPv4 (all schemes) and for IPv6 (http proxy) it works perfect.

If I pass an array as proxy params than I can login with every scheme through both v4 and v6. But there is a problem with push receiver. It throws exception with every given proxy.

Thanks!

**Comment by mgp25** [comment]
It seems a proxy issue. According to the exception you have posted and the url you have included it says it all:

```
CURLE_COULDNT_CONNECT (7)

Failed to connect() to host or proxy. 
```

Regards

**Comment by nobilik** [comment]
Sorry, maybe I wasn't clear enough. I do it in two different ways with same proxy, and when I pass options as an array it connects and the IG account can login through it, but Push client can't.

**Comment by mgp25** [comment]
Maybe @valga can tell you something about that, but it seems to be proxy related. When @valga has some free time to come around here, he probably will give you an accurate answer about this.

**Comment by valga** [comment]
@nobilik 

```php
$ig->setProxy([
    'https' => 'http://proxy_params', 
    'http' => 'http://proxy_params',
]);
```
or just `$ig->setProxy('http://proxy_params');`, because Instagram doesn't use plain HTTP.

**Comment by moosbat** [comment]
> @valga, maybe I didn't understand your answer... Below I show all proxy settings' ways with results. It's all for socks5 via IPv6.
> 
> If I use
> 
> ```
> $ig->setProxy([
>     'https' => 'http://proxy_params', 
>     'http' => 'http://proxy_params',
> ]);
> ```
> When I try to log in I got
> `PHP Warning: Uncaught InstagramAPI\Exception\NetworkException: Network: CURL error 56: Received HTTP code 502 from proxy after CONNECT (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).`
> 
> If I use
> `$ig->setProxy('http://proxy_params')`
> When I try to log in I got
> 
> `PHP Warning: Uncaught InstagramAPI\Exception\NetworkException: Network: CURL error 7: Can't complete SOCKS5 connection to ____. (5) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).`
> 
> And when I use
> `$ig->setProxy(['proxy' => ['https' => ''http://proxy_params', 'http' => 'http://'http://proxy_params']]);`
> 
> I can log in with IG accounts BUT the code (Push receiver)
> 
> ```
> $loop = \React\EventLoop\Factory::create();
> $push = new \InstagramAPI\Push($loop, $ig, $logger);
> $push->on('incoming', function (\InstagramAPI\Push\Notification $push) {
>         printf('%s%s', $push->getMessage(), PHP_EOL);
> });
> $push->start();
> $loop->run();
> ```
> Gives me endless reconnect
> 
> ```
> 
> [2018-08-13 05:09:18] push.ERROR: No proxy with CONNECT method found. [] []
> [2018-08-13 05:09:18] push.INFO: Existing reconnect timer has been canceled. [] []
> [2018-08-13 05:09:18] push.INFO: Setting up reconnect timer to 2 seconds. [] []
> [2018-08-13 05:09:20] push.INFO: Connecting to mqtt-mini.facebook.com:443... [] []
> [2018-08-13 05:09:20] push.ERROR: No proxy with CONNECT method found. [] []
> [2018-08-13 05:09:20] push.INFO: Existing reconnect timer has been canceled. [] 
> ```

Any update on this?

**Comment by moosbat** [comment]
@nobilik 
Any update on this?
I'm facing the same problem
I can login/like/send-direct with SOCKS5/HTTP proxy but when i use that same proxy for push it just gives me the same errors

**Comment by nobilik** [comment]
@moosbat Hi. no news. I've stopped to try. Http works well

**Comment by moosbat** [comment]
@nobilik thanks for replying. Same here . @valga I think the push client have problems with socks4&socks5 proxies. HTTP proxies work totally fine tho
