### ISSUE TITLE
Two Factor Login Invalid Parameter

### ISSUE THREAD

**Issue by evelynkh** [mgp25/Instagram-API#2157]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

When the two factor login is activated in the instagram account, user will be asked to enter verification code every time they attempt to login. I have just installed the api using composer and try to run the twoFactorLogin.php in the examples folder with terminal after filling the username and password fields (Have yet to make any changes in the code except for the username and password variable).

---

Example Code:

```php
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

/////// CONFIG ///////
$username = 'xxxxxx@xxxxx.com';
$password = 'xxxxxxxxxxx';
$debug = true;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $loginResponse = $ig->login($username, $password);

    if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()) {
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();

        // The "STDIN" lets you paste the code via terminal for testing.
        // You should replace this line with the logic you want.
        // The verification code will be sent by Instagram via SMS.
        $verificationCode = trim(fgets(STDIN));
        $ig->finishTwoFactorLogin($username, $password, $twoFactorIdentifier, $verificationCode);
    }
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

```
Error Log/var_dump:

```
POST:  https://i.instagram.com/api/v1/accounts/login/
DATA: signed_body=fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1.{"phone_id":"c20eab00-0bf3-4d51-a55b-16d6409de652","_csrftoken":null,"username":"xxxxx@xxxxxx.com","adid":"d3aa631d-c036-4f4d-bdfa-5f55ea5ee8bf","guid":"950e4ad9-bbf0-425c-90de-9d065d9a639e","device_id":"android-9a6ad6392d47bc5c","password":"xxxxxxxxx","login_attempt_count":"0"}&ig_sig_key_version=4

RESPONSE: {"message": "", "two_factor_required": true, "two_factor_info": {"username": "xxxxxxxx", "sms_two_factor_on": true, "totp_two_factor_on": false, "obfuscated_phone_number": "5537", "two_factor_identifier": "xxxxxxxx", "show_messenger_code_option": false, "show_new_login_screen": false, "phone_verification_settings": {"max_sms_count": 2, "resend_sms_delay_sec": 60, "robocall_after_max_sms": true, "robocall_count_down_time_sec": 30}}, "phone_verification_settings": {"max_sms_count": 2, "resend_sms_delay_sec": 60, "robocall_after_max_sms": true, "robocall_count_down_time_sec": 30}, "status": "fail"}

>>STDIN -> verification_code

POST:  https://i.instagram.com/api/v1/accounts/two_factor_login/
DATA: signed_body=1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8.{"verification_code":"123456","_csrftoken":null,"two_factor_identifier":"xxxxxxx","username":"xxxxx@xxxxxx.com","device_id":"android-9a6ad6392d47bc5c","password":"xxxxxxxx"}&ig_sig_key_version=4

RESPONSE: {"message": "Invalid Parameters", "status": "fail", "error_type": "invalid_parameters"}

Something went wrong: InstagramAPI\Response\LoginResponse: Invalid Parameters.

```
Keep getting invalid_param response for finishTwoFactorLogin function

**Comment by valga** [comment]
@evelynkh Please check whether 425d015 fixes it for you.

**Comment by evelynkh** [comment]
@valga thank you for your response. But it doesn't fix my issue.

Still with the same response:
RESPONSE: {"message": "Invalid Parameters", "status": "fail", "error_type": "invalid_parameters"}

Something went wrong: InstagramAPI\Response\LoginResponse: Invalid Parameters.

![invalid param 2](https://user-images.githubusercontent.com/42338968/44316481-18803c00-a456-11e8-95ac-add3bc290515.png)

**Comment by mgp25** [comment]
@evelynkh have you checked your write permissions? In the debug log you have attached, we can see that `_csrftoken` is `null`. I haven't checked myself, but it could be a reason of you having this issue.

**Comment by evelynkh** [comment]
@mgp25 I still get the same response even after I provided the csrftoken

![invalid param 3](https://user-images.githubusercontent.com/42338968/44505240-787f1880-a6ca-11e8-97b2-5305bda6e823.PNG)

**Comment by chiliad** [comment]
I have the exact same issue, tried the fix didn't worked.
I'm loging using e-mail adress.

**Comment by mgp25** [comment]
I can check it, but I would need an account with 2FA enabled. If any has one, and dont mind to share it with me (via email only). I'll check this and try to give a solution for this.

**Comment by chiliad** [comment]
I sent you an account

**Comment by chiliad** [comment]
That's weird because this account worked fine until i changed the storage (i'm in early development around your API), i switched to default storage but no effect

**Comment by chiliad** [comment]
@mgp25 do you happen to have a workaround waiting for a fix?

**Comment by mgp25** [comment]
@chiliad Commit pushed to `dev-master`. Let me know if that worked.

Regards

**Comment by evelynkh** [comment]
@mgp25 I tried Commit: https://github.com/mgp25/Instagram-API/commit/19c757d84b14cd11f9432f989b2e1fd1e7191e2e but it didn't fixed the issue

**Comment by mgp25** [comment]
Can you post debug log?

**Comment by evelynkh** [comment]
@mgp25 I retried using username instead of email and it's working now.
Thank you very much for the response

Best Regards,

**Comment by chiliad** [comment]
@evelynkh After the commit?

**Comment by mgp25** [comment]
@evelynkh take a close look at your request you are mixing both `verification_code` and `two_factor_identifier` identifier values. 😉

**Comment by chiliad** [comment]
@mgp25 any ideas for my issue?
Thanks for your time.

**Comment by mgp25** [comment]
@chiliad the previous comment was for you, by mistake I mentioned the other user, but it was for you:

ake a close look at your request, you are mixing verification_code and two_factor_identifier values. 😉

And please, use only username, email is not supported.

**Comment by chiliad** [comment]
Everything is working fine now thank you!

In what case should we use username? Never?
Thank you :)
