### ISSUE TITLE
get data for 4 account

### ISSUE THREAD

**Issue by milad7091** [mgp25/Instagram-API#2159]
I have 4 accounts.
I use the following code to login.
I have a problem for manage two account. To use any account, I have to log in again.
How should I use the information stored in each database for each account, without use login again?

```
$username = 'user';
$password = 'pass';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug,[
'storage'    => 'mysql',
        'dbhost'     => 'localhost',
        'dbname'     => 'sessions',
        'dbusername' => 'root',
        'dbpassword' => '',
    ]);

    if ($ig->settings->hasUser('user')=='1')
    {
        $ig->settings->setActiveUser('user');
        $userId = $ig->people->getUserIdForName('instagram');
    }
```

`Something went wrong: User not logged in. Please call login() and then try again.`

Tanks.

**Comment by mgp25** [comment]
Please read the documentation and source code. `login()` functions does the login part when the session doesn't exist, but when it does it simply does required requests. We are emulating device requests.

So, yeah, you need to use `login()` always and the function will do the rest.

Regards
