### ISSUE TITLE
Question about the usage of this private Api as a webservice.

### ISSUE THREAD

**Issue by marcelinhovt** [mgp25/Instagram-API#2160]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hi, first of all, thank you.

1) After read your FAQ about "Can I run this library via a website?" i still having a doubt. I have a App that was using the Instagram Api. After all the recently changes, the app is not working anymore. 
Now, I need to use a private instagram Api like this one. My question is:
Can I use this Api as a webservice and call the service to login and send Likes, by example, from a iOS and Android app ?

Another question: The enterprise that hired me, need to do this fastly. Do you offer this type of service and support to help. They can pay or donate if it needs.

Thanks for the support and attention.

**Comment by mgp25** [comment]
1. Yes, you can use this API, but keep in mind that any spammy activity will be limited by Instagram, and this is something we don't allow too.

About the support, you can look this: https://github.com/mgp25/Instagram-API/issues/1231#issue-227060777

Regards

**Comment by marcelinhovt** [comment]
Is not for spammy ! Its a app that user put some friends of instagram and other social medias. And the user can like the last photos from some of them.

About the licence: If I get the subscription plan, you put the service in a address and I just connect with the Api, like the official Instagram Api ? Or do you give a support to do it ?
