### ISSUE TITLE
Unclear error on log in

### ISSUE THREAD

**Issue by eugenecooper** [mgp25/Instagram-API#2163]
_HI,_

Lately every time I'm trying to log in (using multiple accounts and IPs) I'm getting the same exception (in ServerMessageThrower.php line 88).
In debug mode I found out that there is one last line of response that is likely causing the exception.
`GET: direct_v2/ranked_recipients?show_threads=true ← 400 33B RESPONSE: {"message": "", "status": "fail"}`
So if I'm just catching the exception and proceeding with posting it actually works. I'm assuming the error is related to direct v2 API and can be ignored if you just want to make a post but could you please explain why that could be happening or give a suggestion where I can disable that particular response check.

_Thanks_

**Comment by mgp25** [comment]
Hello @eugenecooper,

It seems you are running an outdated version of the API. Please make sure to update to latest dev-master code.

Regards

**Comment by eugenecooper** [comment]
Sorry, I didn't realize I was stuck at ^2 so I thought everything was up to date on composer update.
