### ISSUE TITLE
Only 8 photos in the timeline feed

### ISSUE THREAD

**Issue by vladimrirwapev** [mgp25/Instagram-API#2164]
I am trying to view photos from the timeline but the function retutns only 8 items

My code:

set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'/vendor/autoload.php';
use InstagramAPI\InstagramID;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
 
$username = 'myusername';
$password = 'password';
$debug = true;
$truncatedDebug = false;
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
$feed = $ig->timeline->getTimelineFeed(15);//15 is maxID
$items = $feed->getFeedItems();
echo sizeof($items);
 
The $items array always contains only 8 items even if I set different maxID parameter. Is there a way to get more? Am I doing anything wrong?

**Comment by mgp25** [comment]
Example: https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php

**Comment by vladimrirwapev** [comment]
It works this way. Thanks a lot for your help!

**Comment by evantoday** [comment]
> 
> 
> It works this way. Thanks a lot for your help!

how you write the code bro ? i got same issue
