### ISSUE TITLE
How to get self Following

### ISSUE THREAD

**Issue by alfazck** [mgp25/Instagram-API#2165]
Hello Sir,
How do i get list of self following which do not accept request (follow request) from there id's.
i tried selffollowing, getfollowing functions but didnt get pending following request of me.
please give me solution. i am giving screenshot which i want require.
![current_follow_requests](https://user-images.githubusercontent.com/42431937/44193770-94763d80-a151-11e8-9dbb-13a4f3dc3ccb.png)

**Comment by valga** [comment]
@alfazck https://github.com/mgp25/Instagram-API/blob/78055c700a7e60dc77ba637cf50c64580b15b276/src/Request/People.php#L225-L232
