### ISSUE TITLE
[Wiki] Comments modules list

### ISSUE THREAD

**Issue by mercymainhere** [mgp25/Instagram-API#2168]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---

I needed comment feature but there is no Wiki with listed modules so I got them on my own.
I didn't noticed any additional parameters in request content  / header.
I used apk from apkmirror with version that is in `Constants::IG_VERSION`.

### Modules
**`comments_v2_feed_timeline`**
Post from timeline

**`comments_v2_feed_contextual_hashtag`**
Post from hashtag search tab.

**`comments_v2_photo_view_profile`**
Post from user profile with photo.

**`comments_v2_video_view_profile`**
Post from user profile with video.

**`comments_v2_media_view_profile`**
Post from user profile with slideshow.

**`comments_v2_feed_contextual_location`**
Post from location search tab.

**Comment by valga** [comment]
@mercymainhere Please file a PR with the info, as it should be documented in the code, like I did with user info here https://github.com/mgp25/Instagram-API/blob/4191b00b0aab5858be70a9fbe5769061dd8e26c5/src/Request/People.php#L22-L24 and here https://github.com/mgp25/Instagram-API/blob/4191b00b0aab5858be70a9fbe5769061dd8e26c5/src/Request/People.php#L65
