### ISSUE TITLE
Could you please add more examples?

### ISSUE THREAD

**Issue by coolnickname** [mgp25/Instagram-API#217]
I'm having a hard time getting information from Instagram and think it would be easier if there were some more complicated examples that would for example, get all posts from a certain user and like them automatically.

**Comment by polamoros** [comment]
This is not a issue... To get all posts from an user you have to use 'getUserFeed'. Then, you will get media and the 'maxid' that you will have to use with the next query. Once you stored all media (maxid not set on the response) you can do like to picture using 'like(mediaId)' with the media_id collected before.
