### ISSUE TITLE
 The problem of input parameters is join live

### ISSUE THREAD

**Issue by milad74yari** [mgp25/Instagram-API#2170]
Request:

```http

POST /api/v1/live/"&broadcast_id&"/join/ HTTP/1.1
Host: i.instagram.com
Connection: keep-alive
Accept-Language: en-US
Cookie: . . . . .
Cookie: csrftoken=g79dofABCDEFGII3LI7YdHei1234567; mid=WFI52QABAAGrbKL-ABCDEFGHIJK
User-Agent: Instagram 42.0.0.19.95 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)
```

parameter:

```http

  
{"encoded_server_data_info":" ","device_id":" ","sdp_offer":" "}

```
**Hello friends
I do not know the encoded_server_data_info and sdp_offer parameters in this request. If anyone knows to tell me**

**Comment by JRoy** [comment]
If I recall they will not support this to avoid bot viewers

**Comment by mgp25** [comment]
That request is not yet implemented in the API.

Regards

**Comment by milad74yari** [comment]
@mgp25 would be very good. This api was launched. Because my users need to log in to Live and they are waiting for that

**Comment by mgp25** [comment]
@milad74yari if you have users as you are cliaming, you should get a premium license according to ours. This way you are also supporting this whole project which is completly free and it doesn't code and moderate itself.

Regards
