### ISSUE TITLE
instagram-API-master/examples/uploadPhoto.php showing This page isn’t working HTTP ERROR 500

### ISSUE THREAD

**Issue by Oguntoye** [mgp25/Instagram-API#2173]
### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->login('yourusername', 'yourpassword');
    $result = $ig->media->comment('14123451234567890_1234567890', 'Hello World');
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```
RESPONSE: {"status": "fail", "message": "Sorry, the comment data may have been corrupted."}

InstagramAPI\Response\CommentResponse: Sorry, the comment data may have been corrupted.
```

**Comment by mgp25** [comment]
Provide debug log or this issue will be considered as invalid and closed. Error 500 is not API fault.

**Comment by Oguntoye** [comment]
How can I get the debug log?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-the-500-http-error-code-mean

**Comment by Oguntoye** [comment]
could it be that am not configuring it well. have tried composer for the
installation. it seems is not working so i downloaded the complete zip file
and posted in to a live server then fill in an instagram username and
password with a sample picture then the same message continues. will be
glad if you can help with some installation steps.
Thanks in advance.
Best Regards..

**Comment by mgp25** [comment]
Installation guide can be found in: https://github.com/mgp25/Instagram-API#installation

Composer is the path to go.

**Comment by Oguntoye** [comment]
Thanks for swift response.. What do i do next after running this:

composer require mgp25/instagram-php

**Comment by mgp25** [comment]
Once is installed, you can start building whatever you want. See this as a reference: https://github.com/mgp25/Instagram-API/tree/master/examples

**Comment by Oguntoye** [comment]
Okay. Thanks.. am still in the process of using composer to install.. but
is like is taking longer time.. is that how it takes time.?
[image: Screen Shot 2018-08-23 at 2.42.37 PM.png]

**Comment by Oguntoye** [comment]
Have install it on my local machine and i dont know what to do next. can
you please help?

**Comment by Oguntoye** [comment]
i got it work but i got this error message VIA my terminal:

Something went wrong: Input file "http

This is a great work man.. u really deserve some accolades.. How can i fix
this error:


Something went wrong: Input file "
https://i0.wp.com/thefreshimages.com/wp-content/uploads/2017/07/Love-Images-3.jpg"
doesn't exist.

meanwhile the image exists
