### ISSUE TITLE
Age Confirmation

### ISSUE THREAD

**Issue by fueldroids** [mgp25/Instagram-API#2174]
The new Instagram app imposes Age verification to access certain profiles, mostly alchool.

(try to open this with an account that is not connected via FB) 

[https://www.instagram.com/skol/](https://www.instagram.com/skol/)

Please see an example from the App

![2018-08-24 14 20 57](https://user-images.githubusercontent.com/29915661/44568532-d9315280-a7a9-11e8-8bb1-54a51f94bf79.png)

Are you able to provide an interface for this choice?

**Comment by mgp25** [comment]
Hello @fueldroids. Im not able to replicate this behavior with my account. If you send me your account via email, I can check this request.

**Comment by fueldroids** [comment]
Sent, many thanks for the quick follow-up.

**Comment by mgp25** [comment]
@fueldroids Should be working fine in the last commit from `dev-master`.

```php
$ig->people->markUserOverage($userId);
```

Commit: https://github.com/mgp25/Instagram-API/commit/4191b00b0aab5858be70a9fbe5769061dd8e26c5

Regards
