### ISSUE TITLE
Question: What to do on Challenge Required?

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2177]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Recently very often Instagram is throwing challenges to users when they login with a new device

`{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/8274888690/kl06heov5i/", "api_path": "/challenge/8274888690/kl06heov5i/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"} `

This happens even with instagram app so it's tottally not an API issue, but i would like to know the right way to deal with it

What shall be the next steps when getting this exception? 
Actually I'm redirecting the user to the challenge URL and letting him deal with it, but sometimes even when he clicks on "was me" when i try to re-login the challenge is threw again

**Comment by mgp25** [comment]
F.A.Q.: [Checkpoint required](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean)

https://github.com/mgp25/Instagram-API/issues/2143

Regards

**Comment by mohammadyacn314** [comment]
@mgp25  Challenge not checkpoint . please help.i created full php code but for some accounts i have this problem in a loop.by seting socks5 proxy it will solve ???
TNX
