### ISSUE TITLE
Using last login cookies

### ISSUE THREAD

**Issue by miladcoder** [mgp25/Instagram-API#2178]
Dear guys
am using this library on laravel-project
everythings is ok but i have question
for first time i have to login and this is ok 
but when i want to use another methods,i dont need call login method again so i need using last login cookies.
please help me

**Comment by mgp25** [comment]
Duplicate issue. Search for already answered questions and look for documentation in the code.

Read this: https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L399
