### ISSUE TITLE
InstagramAPI\Response\DirectSendItemResponse: Feedback required.

### ISSUE THREAD

**Issue by alibaraneser** [mgp25/Instagram-API#2179]
Hi guys,

In closed issues you have explained how this error happened, but I want to ask you a few questions.

1) after receiving a message to a specific person I get this error although I use sleep function. Moreover, according to what you wrote, the instagram perceives me as spam, but then when I try again I can send it back.
2) How companies using this system for advertising promotions are not perceived as spam? As far as I understand, this warning comes up when I post a message to random people, but I am wondering exactly what this company is doing.

**Comment by mgp25** [comment]
We dont support this kind of stuff

Regards
