### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by polamoros** [mgp25/Instagram-API#218]
I have problems with do follow. The query return status "ok" but the 'friendship_status'['following'] return false. Can be a aproblem with the rate limits? I do this query 15/hour.

**Comment by mkanker** [comment]
Isn't cause the friend didn't accept the request yet?

**Comment by polamoros** [comment]
@mkanker It could be that the problem was for that... Anyway, wich are the rate limits that you are using?

Thanks for response;)
