### ISSUE TITLE
How to get only popular results with getFeed()

### ISSUE THREAD

**Issue by chiliad** [mgp25/Instagram-API#2182]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

$feed = $this->instagram->hashtag->getFeed('hashtagToSearch', Signatures::generateUUID(), $maxId);


```

---

### Describe your issue

I am currently trying to get popular results from the getFeed() function but it seems mixed, can someone think about something to get only those results without scanning all of them?

Thank you very much

**Comment by chiliad** [comment]
Nevermind, it seems that the I should use $feed->getRankedItems instead of $feed->getItems, correct me if i'm wrong?

getRankedItems does not have the users_like array tho, that's too bad

**Comment by mgp25** [comment]
You are correct.

Regards

**Comment by chiliad** [comment]
@mgp25 It seems that the results from getRankedItems are frozen in time. since the day I opened the issue, the results are totally the same, instagram app has of course fresh results.

I'm digging into this but can't find the problem
