### ISSUE TITLE
How Can I get User Profile Image (NON LOGIN)

### ISSUE THREAD

**Issue by burakbuylu** [mgp25/Instagram-API#2183]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hello how can I get user profile image with non login user? Or how can I check is user has have profile image ?

---

**Comment by mgp25** [comment]
You need to be logged in in order to make any request. Can you see any friend profile in the android or iOS app without login? This is the same as the app.

Regards

**Comment by bolds07** [comment]
Actually `getInfo` with the userID works without authentication

**Comment by mgp25** [comment]
@bolds07 you shouldn't use requests in a way that they weren't meant to, but as always using the API safely is up to the users.
