### ISSUE TITLE
getRankedItems only has 9 items

### ISSUE THREAD

**Issue by chiliad** [mgp25/Instagram-API#2187]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

I am currently trying to get popular results from the `getFeed()`.
getFeed()->getItems() returns all items as expected but this is fresh posts.
getFeed()->getRankedItems() returns 9 items (popular one, those i'm looking for) but they seem to need update and I can't get more than 9.

Thank you very much

**Comment by mgp25** [comment]
@chiliad have you tried looking in the phone? Because popular feed returns exactly 9 items (check it in the phone), and they are updated by Instagram.

Regards

**Comment by chiliad** [comment]
Well @mgp25 the next ones are still popular so the question is, how to get them?

I searched for a long time but couldn't find a solution

**Comment by mgp25** [comment]
@chiliad Popular are the ranked items.

**Comment by chiliad** [comment]
@mgp25 Well I was checking on iPhone it's entirely different my bad the API is working as expected.
Do you have any guidance in how I could achieve what i'm trying to do?

**Comment by mgp25** [comment]
@chiliad what are you trying to do?

**Comment by chiliad** [comment]
Gathering the top feeds by hashtag but it seems that It's not there on Android.
On iPhone, we have a choice to see the hashtag and then, click to sort on "Recent" "Top" etc..

**Comment by zNoobs** [comment]
Hi,
On the Android app you have more than 9 results, it's like you said on iPhone now.
But the API still send 9 results and these results are not even the top 9 on the "Top" tab on the app.
How to get more results like on the app? And how to get the results in the same order as the app?
