### ISSUE TITLE
composer - Failed to download lazyjsonmapper/lazyjsonmapper from dist

### ISSUE THREAD

**Issue by xdevmas** [mgp25/Instagram-API#2188]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
I'm installing the library via composer, the new version have some problem and can't be downloaded with composer.

The composer log : 

```
Package operations: 5 installs, 0 updates, 0 removals
- Installing lazyjsonmapper/lazyjsonmapper (v1.6.1): Downloading (failed)   
Failed to download lazyjsonmapper/lazyjsonmapper from dist: 
The "https://api.github.com/repos/SteveJobzniak/LazyJsonMapper/zipball/f30b4d0b3f416631e3411d66962a55f586d04809" 
file could not be downloaded (HTTP/1.1 404 Not Found)

```
The dependecy library can not be found! 

What is wrong ?

I've tried it many times but there is something wrong

**Comment by mgp25** [comment]
Please you `dev-master`. Instructions on the Readme

Regards

**Comment by mgp25** [comment]
@xdevmas have you done as mentioned:

`composer require mgp25/instagram-php dev-master`?

**Comment by xdevmas** [comment]
yes exactly 

    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.

**Comment by mgp25** [comment]
@xdevmas more info: https://github.com/anouarabdsslm/laravel-fpdf/issues/16#issuecomment-159543626
