### ISSUE TITLE
Please update your Instagram app to continue liking photos

### ISSUE THREAD

**Issue by chanoc-b** [mgp25/Instagram-API#219]
First of all, thanks for sharing your project... you are Great! You are very able and your work is very helpfull, If I'll have the possibility/ability I would love to collaborate on this project!

Issue
I've encountered an issue using v8.2.0 code:
If I try to like a media, ig reply with the following message:
"{"status":"fail","message":"Please update your Instagram app to continue liking photos"}"

I've sniffed v8.2.0 traffic, actually the request to like a media (finded after an hashtag-search) have the same endpoint, but the data contained in the request is something like
{
	"module_name":"feed_contextual_hashtag",
	"media_id":"",
	"_csrftoken":"",
	"_uid":"",
	"_uuid":"",
	"hashtag":""
}

so I've updated the data in the _function like($mediaId){...}_ but I still have that reply...am I the only one having this "issue"?

**Comment by polamoros** [comment]
I'dont have this issue.

**Comment by chanoc-b** [comment]
Really? After reading your reply I've done a test: I've tried to run some of my others accounts.
Result: some works very well, some dont works.. It's really strange because the code they are based-on is the same... I don't know what to think, what's your opinion?

**Comment by mgp25** [comment]
It works perfectly

Regards
