### ISSUE TITLE
How to decode timestamp?

### ISSUE THREAD

**Issue by ivgreskiv** [mgp25/Instagram-API#2191]
Hello, i can't find needed info in issues so here is question.
`"items": [
          {
            "item_id": "28328977397009730269065415030210560",
            "user_id": "282295683",
            "timestamp": 1535716941906535,
            "item_type": "text",
            "text": "Check"
          }
        ]`
How i can decode timestamp?

**Comment by mgp25** [comment]
@ivgreskiv What do you mean by "decode"?
