### ISSUE TITLE
exceeded the timeout of 60 seconds

### ISSUE THREAD

**Issue by shkumbinhasani** [mgp25/Instagram-API#2196]
Hi sorry for the unproffesional writting and noob question when i am trying to upload video on IGTV it shows me this i dont know where to change that 

Failed to run the ffmpeg binary: The process "ffmpeg.exe -v error -y -i video.mp4 -vf crop=w=405:h=720:x=437:y=0,scale=w=480:h=854,pad=w=480:h=854:x=0:y=0:color=0xFFFFFF -metadata:s:v rotate="" -f mp4 -c:v libx264 -preset fast -crf 24 -c:a copy C:\Users\XXXX\AppData\Local\Temp\INSCE21.tmp" exceeded the timeout of 60 seconds.

**Comment by mgp25** [comment]
`Failed to run the ffmpeg binary` and `exceeded the timeout of 60 seconds`. Since the code works, I would recommend you to debug what happens with the ffmpeg. You can always increase the timeout. If you still face the issue, provide ffmpeg verbose log.

Regards

**Comment by Niek** [comment]
FYI: what helped for me is adding a a timeout option here:
https://github.com/mgp25/Instagram-API/blob/742cb8d50f360ac52faff4065d4c171e14ce2ec8/src/Media/Video/FFmpeg.php#L120-L121
For example:
```php
$process->setTimeout(3600);
```
It would be nice if this would be an option to the ``InstagramVideo()`` constructor.
