### ISSUE TITLE
getMedia ALL

### ISSUE THREAD

**Issue by burakbuylu** [mgp25/Instagram-API#2199]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---
Hello again,

I can't get all media details. How can I get all details?

```
            $feed = $this->discover->getExploreFeed();
            $items = [];
            foreach($feed->getItems() AS $item){
                //dd($item->getMedia());
                $media = $item->getMedia();
                $media = $media->getResponse(); //its not work ->getUser are work but I want all
                dd($media,true);

            }
```

Or how can I founds available methods for getMedia ? 

Regards

**Comment by mgp25** [comment]
You can see how the request is mapped here: https://github.com/mgp25/Instagram-API/blob/master/src/Response/ExploreResponse.php

Regards
