### ISSUE TITLE
Cant Post Photos

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#22]
there is an issue something new on instagram now i cant post pictures !

**Comment by doctorbinsibar** [comment]
i cant post this doesnt seems to work !

**Comment by doctorbinsibar** [comment]
Calling this URL seems to report a problem:
https://i.instagram.com/api/v1/upload/photo/


HTTP/1.1 100 Continue
Date: Mon, 04 Jan 2016 00:43:50 GMT

HTTP/1.1 500 INTERNAL SERVER ERROR
Server: nginx
Date: Mon, 04 Jan 2016 00:43:50 GMT
Content-Type: text/html; charset=utf-8
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
X-Instagram-Ssl-Everywhere: True
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Set-Cookie: csrftoken=0c564d7fa300e8719f643dff8668d4bb; expires=Mon, 02-Jan-2017 00:43:50 GMT; Max-Age=31449600; Path=/
Connection: keep-alive
Content-Length: 25

Oops, an error occurred.

**Comment by mgp25** [comment]
@doctorbinsibar remove all the auth files, login again and try again, it should work try also with a different photo

Regards
