### ISSUE TITLE
how to get list waiting friend requests and auto-accept them?

### ISSUE THREAD

**Issue by DesDeRe** [mgp25/Instagram-API#2200]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

Is there a way for me to list waiting friend requests and auto-accept them?

**Comment by mgp25** [comment]
Hello, 

please, search before opening an issue: https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php#L232

**Comment by DesDeRe** [comment]
can you show a sample code snippet please?

How do I use this function?

Help me please

**Comment by DesDeRe** [comment]
hello. help me please. I was wait 3 week for this
