### ISSUE TITLE
Instagram-API: Caption text does not exist

### ISSUE THREAD

**Issue by amensum** [mgp25/Instagram-API#2202]
I try: 

```php
$ig->timeline->uploadPhoto($photo->getFile(), ["caption" => "Hello world!"]); 
```

Request completed, image successfully uploaded, but caption is empty :( When i run the example [uploadPhoto.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php), the image is also loaded without a title.

**Comment by mgp25** [comment]
Make sure you are using `dev-master`. If you are in `dev-master` probably your account/IP is flagged. Remember to post also debug log.

Regards
