### ISSUE TITLE
Login in to instagram throw User not logged in. Please call login() and then try again.

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2203]
hi, when i try to login into instagram account with `login` function of this api i get `User not logged in. Please call login() and then try again` error, i think my implementation is ok because i check more samples about that, but unfortunately i'm not sure what's the problem

my `InstagramHelper` class:

BTW this method is for using multiple login account

I'm using `InstagramHelper` class as an Ajax request and response, it work fine when i use that classic mode not using via Ajax
```php
class InstagramHelper extends Instagram
{
    public $ig;
    public function __construct()
    {
        set_time_limit(0);
        Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
        parent::__construct();
    }
    public function loader($username, $password, $proxy = "")
    {
        $this->ig = new Instagram(false, false, [
            'storage' => 'mysql',
            'dbhost' => env('DB_HOST'),
            'dbname' => env('DB_DATABASE'),
            'dbusername' => env('DB_USERNAME'),
            'dbpassword' => env('DB_PASSWORD'),
            'dbtablename' => env('INSTAGRAM_DATA')
        ]);
        $loginResponse = $this->ig->login($username, $password);
        $this->_setUser($username, $password);
        $this->setVerifySSL(false);
        return $this->ig;
    }
}
```

simplified function to use that via Ajax to login into instagram account:
```php
public function loginIn($username, $password){
    $ig = new InstagramHelper();
    try {
        $ig->loader($username, $password);
        $data = $ig->people->search("instagram")->getUsers();
    } catch (\Exception $e) {
        return response()->json(['state' => false, 'message' => $ig->getInstagramErrorText($e->getMessage())]);
    }
}
```

**Comment by mgp25** [comment]
Hello @Mrp12,

First of all, make sure you are using `dev-master`. In current `dev-master` you don't call `_setUser()`! You should call `$this->setVerifySSL(false);` before any request is made, in other words, before `login()`.

That said, I don't see any other thing. And as the error says: `User not logged in. Please call login() and then try again` happens when you try to do any request before calling `login()`.

**Comment by Mrp12** [comment]
@mgp25 Thanks i found where cause of problem
