### ISSUE TITLE
Throttled by Instagram because of too many API requests. 

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2204]
I'm trying to know which action or timeout cause of this problem and how can i manage requests to fix this problem. i get this error on following users, Thanks in advance

**Comment by mgp25** [comment]
@Mrp12 you are doing many requests in a short period of time, you should add backoff times to your requests.

**Comment by desatir7316** [comment]
do i have to add sleep() between each request? its a little weird !
if want to get followers and get userId for each of them.
