### ISSUE TITLE
Not able to get following of a userId

### ISSUE THREAD

**Issue by revanthrr** [mgp25/Instagram-API#2205]
**i get this following error when i try to get someone's following list**

here is my code

```
<?php
set_time_limit(0);
date_default_timezone_set('UTC');
require 'C:\xampp\htdocs\vendor\autoload.php';
/////// CONFIG ///////
$username = 'my username'; 
$password = 'my pass';
$debug = true;
$truncatedDebug = false;

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
try {
	$userId = $ig->people->getUserIdForName('yaboyjake.d');
	$ig->people->getFollowers($userId);
	var_dump($ig);
}
 catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
						}
 
 ?>
```

**THIS IS THE ERROR**

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function InstagramAPI\Request\People::getFollowers(), 1 passed in C:\xampp\htdocs\scripts\test.php on line 22 and at least 2 expected in C:\xampp\htdocs\vendor\mgp25\instagram-php\src\Request\People.php:355
Stack trace:
#0 C:\xampp\htdocs\scripts\test.php(22): InstagramAPI\Request\People->getFollowers('5806594608')
#1 {main}
  thrown in C:\xampp\htdocs\vendor\mgp25\instagram-php\src\Request\People.php on line 355

Fatal error: Uncaught ArgumentCountError: Too few arguments to function InstagramAPI\Request\People::getFollowers(), 1 passed in C:\xampp\htdocs\scripts\test.php on line 22 and at least 2 expected in C:\xampp\htdocs\vendor\mgp25\instagram-php\src\Request\People.php:355
Stack trace:
#0 C:\xampp\htdocs\scripts\test.php(22): InstagramAPI\Request\People->getFollowers('5806594608')
#1 {main}
  thrown in C:\xampp\htdocs\vendor\mgp25\instagram-php\src\Request\People.php on line 355

**Comment by invasioncredible** [comment]
@revanthrr Hey man. The problem you get here is caused by not passing $rankToken as a second argument to the getFollowers method.
