### ISSUE TITLE
Get an error `challenge_required` when try to upload story

### ISSUE THREAD

**Issue by ducnguyenhuy** [mgp25/Instagram-API#2206]
Here are responses I have got:
`{"message": "challenge_required",  "status": "fail", "error_type": "checkpoint_challenge_required"}`

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean

**Comment by ducnguyenhuy** [comment]
@mgp25 I'm running your API on local. So I think IP don't cause that. Any suggestions? Thanks a lot!

**Comment by mgp25** [comment]
@ducnguyenhuy Verify your account via web browser.

**Comment by ducnguyenhuy** [comment]
@mgp25 You mean I need to prove I'm human? If yes, I did that.

Could you tell me how to verify account? I did not get any prompt about that.

**Comment by mgp25** [comment]
@ducnguyenhuy login in Instagram web and go to your profile, it should appear a page to verify yourself.

**Comment by ducnguyenhuy** [comment]
@mgp25 I don't see it. But seem It's fixed if one of things below happens:
1. Switch to Business Account (I don't know your API will work with type of this account)
2. Submit a new post to my profile.
