### ISSUE TITLE
Challenge Required Loop

### ISSUE THREAD

**Issue by halixness** [mgp25/Instagram-API#2209]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'/../vendor/autoload.php';
/////// CONFIG ///////
$username = 'MYACCOUNT';
$password = 'MYPASS';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
```

Error Log/var_dump:

```
RESPONSE: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/CODE1/CODE2/", "api_path": "/challenge/CODE1/CODE2/", "hide_webview_header": true, "lock": true, "logout": fal
se, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}
Something went wrong: InstagramAPI\Response\LoginResponse: Challenge required.
```

---

### Describe your issue

I'm trying to log with this account, which has been used in Italy. I moved my server with Google Cloud Platform to Mountain View and got a challenge. Fine, so I completed the challenge by putting the given code multiple times from google chrome on that server, with that static ip.
Everytime I try to log I get a challenge. I even moved my VM to Europe to see if something would have changed.
Any advice? Thanks.

**Comment by mgp25** [comment]
Use the same IP for the script and to verify yourself. Remove your session from `/sessions` folder and try it. There is a closed issue with some tips.

Regards
