### ISSUE TITLE
endpoint for search photo on map

### ISSUE THREAD

**Issue by yazhog** [mgp25/Instagram-API#221]
Hello.
In Open API instagram:
 /media/search - Search for recent media in a given area.
Its helps to find photo on map by Latitude and Longitude of the center search coordinate. 

Is there a similar endpoint in private api?
searchLocation($query) - other functionality

**Comment by RageBrahimi** [comment]
Please read the [Wiki](https://github.com/mgp25/Instagram-API/wiki).
Use `getLocationFeed($locationId, $maxid = null)`.

**Comment by yazhog** [comment]
searchLocation($query) and getLocationFeed($locationId, $maxid = null) can not provide pictures of the coordinates of the point on the map
