### ISSUE TITLE
Get search results of username search or hashtag and location

### ISSUE THREAD

**Issue by xdevmas** [mgp25/Instagram-API#2210]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hi thanks for this great library, 

Is there any way to get top result of search result?
i mean the result that is accessible when we search a username or location or hashtag in instagram app search tab.
Is there any way to get those result list with this api ?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Hashtag.php

Regards

**Comment by xdevmas** [comment]
Thanks 
Can u please give me an example code to use that class?
