### ISSUE TITLE
Problem with uploadStory.php

### ISSUE THREAD

**Issue by Osman071** [mgp25/Instagram-API#2211]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Dear Ladies and Gentleman,

I hope that you can help me with my problem. I downloaded the **composer** and installed mgp25 through it:

`composer require mgp25/instagram-php`

After that I downloaded the mgp25 folder from **github**:

[https://github.com/mgp25/Instagram-API](url)

After that I copied the `uploadStory.php` to my `/var/www/html` folder in order to upload stories on my Instagram account (I have a business account and >10k followers). That's my code:

```php
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

$username = '';
$password = ''; //I typed in the right username and password
$debug = true;
$truncatedDebug = false;

$photoFilename = '/home/user/Downloads/story.jpg';

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
    $ig->story->uploadPhoto($photo->getFile());
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
?>
```

It's basically just the login and the upload without any location or metadata. When I restart apache2 and go to `localhost/uploadStory.php` I get the `HTTP Error 500`. I don't believe that it's because of a syntax error, I think that I have some permissions error or maybe I also use this API wrong (never worked before with composer). Does anyone had the same problem like me? I would be thankful for every answer that I get. Please do not hesitate to contact me if you need any further information.

Best Regards

**Comment by burakbuylu** [comment]
I think this problem coming your web server. Can you share latest apache error logs with us ?

And whats your PHP version?

**Comment by mgp25** [comment]
Hello @Osman071,

 first of all, the script is wrong. There is no `$photo` anywhere in the script, so you should check the [example](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStory.php) again to add exactly that.

And about the 500 HTTP error code, it is explained in the F.A.Q.:

F.A.Q.: [What does the 500 HTTP error code mean?](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-the-500-http-error-code-mean)

Make sure you read the F.A.Q. and wiki before opening an issue.

Regards
