### ISSUE TITLE
Upload photo to FEED_TIMELINE got an error

### ISSUE THREAD

**Issue by ducnguyenhuy** [mgp25/Instagram-API#2213]
Thanks for your APIs!

I got an error as followings: Something went wrong: Failed to get photo details: Instagram only accepts story media with aspect ratios between 0.560 and 0.670. Your file "INSTAIMG_598eak" has a 0.8000 aspect ratio

I'm using a photo with size 162 x 270. So aspect ratios is 0.6. But I got an error as above. Please give me advise. Thanks.

**Comment by mgp25** [comment]
Please use the examples: https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php

It will prepare your media so it can be uploaded to Instagram
