### ISSUE TITLE
Instagram response: Update Your App to Use Direct!

### ISSUE THREAD

**Issue by javansoft** [mgp25/Instagram-API#2217]
hi
`
$res=$ig->direct->getInbox();
echo $res;
`

output:

> {
> "pending_requests_total": null,
> "seq_id": null,
> "pending_requests_users": null,
> "inbox": {
> "unseen_count": null,
> "has_older": null,
> "oldest_cursor": null,
> "unseen_count_ts": null,
> "threads": null
> },
> "megaphone": {
> "generic_megaphone": {
> "type": "deprecate_raven_tray",
> "title": "Update Your App to Use Direct",
> "message": "Your Instagram app is out of date. Update it now to use Direct.",
> "dismissible": false,
> "icon": null,
> "buttons": [
> {
> "text": "Update",
> "url": "https://play.google.com/store/apps/details?id=com.instagram.android",
> "action": null,
> "background_color": null,
> "border_color": null,
> "text_color": null,
> "action_info": null
> }
> ],
> "megaphone_version": "v1",
> "button_layout": "vertical",
> "action_info": {},
> "button_location": "bottom",
> "background_color": null,
> "title_color": null,
> "message_color": null,
> "uuid": "7451a4f3af2a438a830cf444cc3983b2"
> }
> },
> "status": "ok",
> "message": null,
> "_messages": null,
> "fullResponse": {
> "inbox": {},
> "megaphone": {
> "generic_megaphone": {
> "type": "deprecate_raven_tray",
> "title": "Update Your App to Use Direct",
> "message": "Your Instagram app is out of date. Update it now to use Direct.",
> "dismissible": false,
> "icon": null,
> "buttons": [
> {
> "text": "Update",
> "style": "confirm",
> "url": "https://play.google.com/store/apps/details?id=com.instagram.android"
> }
> ],
> "megaphone_version": "v1",
> "button_layout": "vertical",
> "action_info": {},
> "button_location": "bottom",
> "uuid": "7451a4f3af2a438a830cf434cc3983b2"
> }
> },
> "status": "ok"
> },
> "httpResponse": {}
> }
> 

how i can solve it?
thanks

**Comment by javansoft** [comment]
> hi
> `$res=$ig->direct->getInbox(); echo $res;`
> 
> output:
> 
> > {
> > "pending_requests_total": null,
> > "seq_id": null,
> > "pending_requests_users": null,
> > "inbox": {
> > "unseen_count": null,
> > "has_older": null,
> > "oldest_cursor": null,
> > "unseen_count_ts": null,
> > "threads": null
> > },
> > "megaphone": {
> > "generic_megaphone": {
> > "type": "deprecate_raven_tray",
> > "title": "Update Your App to Use Direct",
> > "message": "Your Instagram app is out of date. Update it now to use Direct.",
> > "dismissible": false,
> > "icon": null,
> > "buttons": [
> > {
> > "text": "Update",
> > "url": "https://play.google.com/store/apps/details?id=com.instagram.android",
> > "action": null,
> > "background_color": null,
> > "border_color": null,
> > "text_color": null,
> > "action_info": null
> > }
> > ],
> > "megaphone_version": "v1",
> > "button_layout": "vertical",
> > "action_info": {},
> > "button_location": "bottom",
> > "background_color": null,
> > "title_color": null,
> > "message_color": null,
> > "uuid": "7451a4f3af2a438a830cf444cc3983b2"
> > }
> > },
> > "status": "ok",
> > "message": null,
> > "_messages": null,
> > "fullResponse": {
> > "inbox": {},
> > "megaphone": {
> > "generic_megaphone": {
> > "type": "deprecate_raven_tray",
> > "title": "Update Your App to Use Direct",
> > "message": "Your Instagram app is out of date. Update it now to use Direct.",
> > "dismissible": false,
> > "icon": null,
> > "buttons": [
> > {
> > "text": "Update",
> > "style": "confirm",
> > "url": "https://play.google.com/store/apps/details?id=com.instagram.android"
> > }
> > ],
> > "megaphone_version": "v1",
> > "button_layout": "vertical",
> > "action_info": {},
> > "button_location": "bottom",
> > "uuid": "7451a4f3af2a438a830cf434cc3983b2"
> > }
> > },
> > "status": "ok"
> > },
> > "httpResponse": {}
> > }
> 
> how i can solve it?
> thanks

**Comment by javansoft** [comment]
solved!

change:

> const IG_VERSION = '10.33.0';

in Constans.php

to:

> const IG_VERSION = '13.33.0';

**Comment by mgp25** [comment]
@javansoft that is not a good solution, in fact it is a terrible fix since you are ignoring a lot of information related to the version and that will lead to multiple issues. You need to use `dev-master` version.

Regards
