### ISSUE TITLE
how do i use getFollowers correctly?

### ISSUE THREAD

**Issue by wsribeiro5** [mgp25/Instagram-API#2219]
I want do get all my followers using getSelfFollowers or getFollowers.

$ig = new \InstagramAPI\Instagram();

$login = $ig->login('wellyngtonsampaio_', 'xxxxxx'); //800396494

// Generate a random rank token.
    $rankToken = \InstagramAPI\Signatures::generateUUID();
    
	$maxId = null;
    for ($i=0; $i < 50; $i++) { 

    	$response = $ig->people->getFollowers(800396494, $rankToken, $maxId);

		foreach ($response->getUsers() as $item) {
        	
        	printf("%s - %s \n",$item->getPk(), $item->getFullName());
        }
        $maxId = $i;
        sleep(2);
    }

Someone can help me?

With this code i got 193 followers but i have 1142.

Regards

**Comment by mgp25** [comment]
Use pagination.

Example: [/examples/paginationExample.php](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php)

Regards
