### ISSUE TITLE
Transcode error

### ISSUE THREAD

**Issue by DaveOff** [mgp25/Instagram-API#2221]
I'm trying to upload the video but this is response

**POST:** `https://i.instagram.com/api/v1/media/configure/?video=1`

**DATA:**
```json
signed_body=1ebf2369b25b7c2bfccef9975526d7014f440219cdf6d3e4764079860a6590ca.
{"device":
    {
       "manufacturer":"OnePlus",
       "model":"ONEPLUS A3010",
        "android_version":"24",
        "android_release":"7.0"
    },
"length":"50.1",
"filter_type":"0",
"_csrftoken":"7BBTgmwfJegt6STL5nuZxHG15w0PjTUa",
"source_type":"4",
"video_result":"",
"_uid":"3312789242",
"_uuid":"ff1d6ebb-1965-4216-b359-c2204b00d628",
"extra": {
     "source_width":480,
     "source_height":480
},
"caption":"v",
"audio_muted":"false",
"poster_frame_index":"0",
"upload_id":"1537000965855"
}&ig_sig_key_version=4
```

**← 400 63B RESPONSE:**
```json
 {"message": "Transcode error: b'yrQ7DYF595'", "status": "fail"}
```

Someone can help me?

**Comment by mgp25** [comment]
@DaveOff 

- What version of the API are you using? Are you using `dev-master? If not, update and try again.
- What media are you trying to upload? Can you attach it here?
- Post the code you used too.

The more info you give, the easier is to help you.

**Comment by mgp25** [comment]
Closed because of lack of information was provided. Feel free to open when you post the related information.

Regards
