### ISSUE TITLE
[] Timeout Pagination

### ISSUE THREAD

**Issue by burakbuylu** [mgp25/Instagram-API#2222]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hello Everyone,

I'm using your system with my helper class; the best one is ;
```php
    public function getTagMedia($tag,$maxId=null){
        $ig = $this->instagram;
        $uuid = $this->getUUID();
        $items=[];
        do {
            $result = $this->hashtag;
            $response = $result->getRecent($tag, $uuid);

            foreach($response->getItems() AS $item){
                $item['media_type'] = \InstagramAPI\Utils::checkMediaType($item['media_type']);
                $item['filter'] = \InstagramAPI\Utils::getFilterCode($item['filter_type']);
                $items[] = $item;
            }

            if($response->isMoreAvailable()) {
                $this->nextMaxId = $response->getNextMaxId();
            }else{
                $response->unsetNextMaxId();
                unset($this->nextMaxId);
            }
            sleep(5);

            //return $response->getItems();
        } while ($maxId !== null); // Must use "!==" for comparison instead of "!=".
        return $items;
    }
```

This one, This is work correctly. Like this
`InstaHelper::getTagMedia('Ronaldinho');`

But if I get maxId and use with max id like this;

`InstaHelper::getTagMedia('Ronaldinho',Insta::getNextMaxId());`

All is correct but script exceed the max timeout input time(300 sec) for us.. What the problem?

Best Regards.

**Comment by mgp25** [comment]
Hello @burakbuylu,

It seems there is something wrong in your implementation. Not API issue.

For more information about pagination:

- [/examples/paginationExample.php](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php)

Regards

**Comment by burakbuylu** [comment]
@mgp25 Thanks for reply, I tried 5-6 times but I got same error? But I wondered; is hashtag->getRelated() function are not accept the maxId?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Hashtag.php#L198

Regards

**Comment by burakbuylu** [comment]
@mgp25 Okay I found problem. I created new function end send nextId to code :/ Just work;

Like this;
<?php
    public function getRecent(
        $hashtag,
        $maxId = null)
    {
        Utils::throwIfInvalidHashtag($hashtag);
        $urlHashtag = urlencode($hashtag); // Necessary for non-English chars.
        $getRecentFeed = $this->ig->request("tags/{$urlHashtag}/recent/")
            ->addParam('visited', '[{"id":"'.$hashtag.'","type":"hashtag"}]')
            ->addParam('related_types', '["hashtag"]');
        if ($maxId !== null) {
            $getRecentFeed->addParam('max_id', $maxId);
        }
        return $getRecentFeed->getResponse(new Response\TagRelatedResponse());
    }
?>

**Comment by mgp25** [comment]
@burakbuylu have you tried `getSection()`?

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Hashtag.php#L49

**Comment by burakbuylu** [comment]
@mgp25 You're best ♥ but im blind 😋
