### ISSUE TITLE
use proxy

### ISSUE THREAD

**Issue by hasanitman** [mgp25/Instagram-API#2223]
hello
can u tell me if i want use proxy where should i put this line ?
$ig->setProxy('http://user:pass@iporhost:port');

thank you

**Comment by hasanitman** [comment]
Why no answer?
Where u answe this question
Plz help me
Thank you

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/search?q=proxy&type=Issues

Regards
