### ISSUE TITLE
How to List All Direct Message ?

### ISSUE THREAD

**Issue by msarac61** [mgp25/Instagram-API#2224]
Hello everyone,

I have little information about this section, I've extracted files in my php file, I'm requesting help below, but I don't know how to list the data in the file.

Sorry for bad english

```php
include __DIR__.'/vendor/autoload.php';
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

/////// CONFIG ///////
$username = 'xxxx';
$password = 'xxxx';
$debug = true;
$truncatedDebug = false;
$text = 'deneme';
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
	try {
		$loginResponse = $ig->login($username, $password);
		$direct = $ig->direct->getInbox();
		$threads = $direct->inbox->threads;
	} catch (\Exception $e) {
		echo 'Something went wrong: '.$e->getMessage()."\n";
	}
```

**Comment by mgp25** [comment]
First of all, you need to use propper getters as explained in the wiki in "[Managing responses](https://github.com/mgp25/Instagram-API/wiki#managing-responses)", make sure to have a look at it bebore continue reading.

Json returned from Instagram are mapped into responses and models. If you have documentated you will already know this. 

Basically these are the responses and models that  [Direct::getInbox()](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php#L34) uses.

- Function info: [Direct::getInbox()](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php#L34)


- Response: [/Response/DirectInboxResponse.php](https://github.com/mgp25/Instagram-API/blob/master/src/Response/DirectInboxResponse.php)
- Model: [/Response/Model/DirectInbox.php](https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/DirectInbox.php)
- Model: [/Response/Model/DirectThread.php](https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/DirectThread.php)
- Model: [/Response/Model/DirectThreadItem.php](https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/DirectThreadItem.php)

According to these models, the code should be the following one:

```php
$direct = $ig->direct->getInbox();
$threads = $direct->getInbox()->getThreads();

foreach($threads as $thread) {
     $threadItems = $threads->getItems();
     foreach($threadItems as $threadItem) {
          if ($threadItem->getText() !== null) {
               echo $threadItem->getText() . "\n";
          }
     }
}
```

**Comment by msarac61** [comment]
but I'm $ig->login(); to avoid all json data together, how am I supposed to go? thank you very much for your help and attention
