### ISSUE TITLE
DM - Profile Photo And List All Message

### ISSUE THREAD

**Issue by msarac61** [mgp25/Instagram-API#2225]
Hello,

The codes I use in my mgp25 instagram dm application are as follows, but there is a situation where I want to add the profile picture and user name, and if I wrote the last message, it seems my usage step. what I want is; let me always see my friend's username and profile picture. my sample images and codes are below, but my codes are not enough for this layout.

```
$direct = $ig->direct->getInbox();
$threads = $direct->getInbox()->getThreads();
foreach($threads as $thread) {
    $threadItems = $thread->getItems();
     foreach($threadItems as $threadItem) {
        if ($threadItem->getText() !== null) {
				$userId = $threadItem->getUserId();
				echo $profil_photo; // I need
				$info = $ig->people->getInfoById($userId);
				$kullanici_adi = $info->getUser()->getUsername();
				echo 'Last Message : '.' '.$kullanici_adi;
				echo 'My Friend Username : '.' '.$friend_username; // I need
				echo $threadItem->getText() . "\n";
				echo '<a href="?id='.$userId.'" data-id="'.$userId.'">Reply</a>';
				echo '<br />';
          }
     }
}
 
```
![adsiz](https://user-images.githubusercontent.com/16395566/45673399-3e6f2e00-bb33-11e8-9c19-bd41ac1589f2.png)

In addition, I would like to list all the correspondence I made with my friend. Thank you.

Thank you very much for being helpful. 🧡

**Comment by mgp25** [comment]
Take the user id and use another request to get user info. You can find all requests here: https://github.com/mgp25/Instagram-API/tree/master/src/Request

Keep in mind this is NOT a support forum, this is an issue tracker. And this is not an issue.

Regards

**Comment by msarac61** [comment]
I understand you, thank you for replying, but I think that I can't fully understand what you're saying and I can't. can you share a very very simple coding for me because I'm having difficulty interpreting the inside of the loop?

**Comment by msarac61** [comment]
> Take the user id and use another request to get user info. You can find all requests here: https://github.com/mgp25/Instagram-API/tree/master/src/Request
> 
> Keep in mind this is NOT a support forum, this is an issue tracker, and this is not an issue.
> 
> Regards

I understand you, thank you for replying, but I think that I can't fully understand what you're saying and I can't. can you share a very very simple coding for me because I'm having difficulty interpreting the inside of the loop?
