### ISSUE TITLE
uploadVideo is showing the logs on browser

### ISSUE THREAD

**Issue by ducnguyenhuy** [mgp25/Instagram-API#2226]
When I try to call uploadVideo after user submit video, API works but I saw the output on browser as below:

> POST: https://i.instagram.com/api/v1/feed/timeline/ DATA: is_prefetch=0&feed_view_info=&seen_posts=&phone_id=decaa573-0f23-4a04-9799-ed7054d4c3ff&reason=pull_to_refresh&battery_level=100&timezone_offset=0&_csrftoken=ykcX73tKFM22pvZdBuIPCjOcWWym1jz5&is_pull_to_refresh=1&_uuid=5720f72a-3ac8-4108-ae93-0975570465dc&is_on_screen=true&unseen_posts=&is_charging=1&is_async_ads_double_request=0&is_async_ads=0&will_sound_on=1&is_async_ads_rti=0 ← 200 9.58kB RESPONSE: {"num_results": 6, "more_available": true, "auto_load_more_enabled": true, "feed_items": [{"media_or_ad": {"taken_at": 1537259343, "pk": 1870989330256958640, "id": "1870989330256958640_197164598", "device_timestamp": 1537259330418, "media_type": 2, "code": "Bn3FuIIgxSw", "client_cache_key": "MTg3MDk4OTMzMDI1Njk1ODY0MA...

How can I remove them?

Thanks for your help.

**Comment by mgp25** [comment]
@ducnguyenhuy Have you read the wiki?

https://github.com/mgp25/Instagram-API/wiki#constructor

**Comment by ducnguyenhuy** [comment]
@mgp25 Yes. I have. Could you point me the line that you want to read again?

Thanks.

**Comment by mgp25** [comment]
` $debug: Boolean. Debug mode (Optional)`

**Comment by ducnguyenhuy** [comment]
It worked! Thanks a lot.
