### ISSUE TITLE
Get more information about users in the subscribers of the user

### ISSUE THREAD

**Issue by maksam07** [mgp25/Instagram-API#2228]
### Before submitting an issue make sure you have:
+ [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
+ [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
+ [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
+ [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
+ [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
+ [x] Question

---

### Describe your issue
We have the code:
```php
$userId = $ig->people->getUserIdForName( 'username' );
$response = $ig->people->getFollowers( $userId, $token, null, $maxId );
foreach ( $response->getUsers() as $item ){
	$FollowerCount = $item->getFollowerCount();
	...
}
```
I can not get the number of subscribers
And I can not get a lot of other information
But...
```php
$userId = $ig->people->getUserIdForName( 'username' );
$response = $ig->people->getFollowers( $userId, $token, null, $maxId );
foreach ( $response->getUsers() as $item ){
	$uI = $ig->people->getInfoById( $item->getPk() )->getUser();
	$FollowerCount = $uI->getFollowerCount();
	...
}
```
After this, there is a lot of information about the user
But if you perform this function in a loop, the instagram starts to swear on a large number of queries
And if you put a timer, it will take a very long time

**I can immediately get complete information about the user?**

**Comment by mgp25** [comment]
@maksam07 

`People::getFollowers()` only returns the followers. This happens the same in the mobile app. Go to any user and check the followers. In no time it will show you the number of followers, just a list of followers (users).

This piece of code is correct:

```php
$userId = $ig->people->getUserIdForName( 'username' );
$response = $ig->people->getFollowers( $userId, $token, null, $maxId );
foreach ( $response->getUsers() as $item ){
	$uI = $ig->people->getInfoById( $item->getPk() )->getUser();
	$FollowerCount = $uI->getFollowerCount();
	...
}
```

The way you are doing it is the right way. Make it more natural. Take your mobile devices, open Instagram app and time yourself how much does it take to you to iterate every user.

Regards
