### ISSUE TITLE
Reply all pending

### ISSUE THREAD

**Issue by vhrut** [mgp25/Instagram-API#2229]
So I'm trying to reply every new message with like Customer services message...
any way this is the code... can't understand what's wrong

(`$Instagram` - Logging details works with other things so the problem not here)

```php
$inbox = $Instagram->direct->getPendingInbox();
$threads = $inbox->getInbox()->getThreads();
$approve = $Instagram->direct->approvePendingThreads($threads); // To approve the messages im going reply 
```
```php
foreach($threads as $thread) 
{
	$userid = $thread['pk'];
	$resp = $Instagram->direct->sendText($userid, $comment);
}
```

**Comment by mgp25** [comment]
You haven't posted what is wrong, any error or debug log response.

**Comment by mgp25** [comment]
Feel free to open again this issue when you provide the required information.

Regards

**Comment by beshoo** [comment]
`$userid = $thread->getInviter()->getPk();` NOT `$userid = $thread['pk'];`
