### ISSUE TITLE
Does someone take the "auth_user_hash" in the end of the sessionid?

### ISSUE THREAD

**Issue by mkanker** [mgp25/Instagram-API#223]
I've taken this parameter in the end of the session id and I couldn't get the news feed for theses account.

**Comment by mkanker** [comment]
I've taken http error (429) that means too many requests together in a computer and network I've used nothing before. Can be any configuration?
friendships/autocomplete_user_list/

**Comment by RageBrahimi** [comment]
Could you be a bit more collaborative and explain your issue.
Where are you finding `auth_user_hash`, also why us `friendships/autocomplete_user_list/` randomly listed.

**Comment by mkanker** [comment]
In my session_id, they're putting they've been included something new in the end:
"...d%23%3A123272139.691219%2C%32_platform%22%3A1%2C%22_auth_user_hash%22%3A%22%22%7D"

it's this part:
"auth_user_hash%22%3A%22%22%7D"

**Comment by RageBrahimi** [comment]
I just tried this, and I cannot see `auth_user_hash`
