### ISSUE TITLE
Is this library using the latest version of Instagram ?

### ISSUE THREAD

**Issue by delmotte** [mgp25/Instagram-API#2230]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

I just saw that the latest version of Instagram is 63.0.0.17.94 whereas this library is using 42.0.0.19.95 from 2018-04-18 (source = https://mobile.softpedia.com/apk/instagram/42.0.0.19.95/).

I would like to know if it was normal that there was a gap between current version of Instagram and the version of this library ? Is there any reason ?

**Comment by mgp25** [comment]
@delmotte whats the point of updating the version if the other features are not yet implemented? Thats the main reason. Nevertheless, we are soon updating the version since most of the features are implemented.

Regards
