### ISSUE TITLE
How to fetch users list whom i sended request to Private account.

### ISSUE THREAD

**Issue by alfazck** [mgp25/Instagram-API#2231]
Hello Sir,
I want to get list of users whom i had followed but they don't accept my request. so i can unfollow them, 
i has asked this question before but you said try **getPendingFriendships()**, But sir this function is to get our pending request, i don't want our pending request, i want the user's list whom i send request but they do not accept in case of private account.
This is the Link where you find this users list on instagram:
**https://www.instagram.com/accounts/access_tool/current_follow_requests**
Sir please give me solution for this. Thank you in Advance.
regards,
Alfaz
![current_follow_requests](https://user-images.githubusercontent.com/42431937/45755509-44046b00-bc3c-11e8-9fc9-ffb1e85a28d2.png)

**Comment by mgp25** [comment]
The question was recently asked. Please search in the closed issues.

Regards

**Comment by alfazck** [comment]
Sir i had searched but i cant find please share me a link or give me some proper information please.. waiting for your positive reply.

**Comment by mgp25** [comment]
@alfazck this API is based on the android app. If you find a way to get the list of following requests on the app, write to me and I'll do it, until then this issue will be closed

Regards

**Comment by alfazck** [comment]
Yes sir we get list of Current follow requests, we have to go to Settings -> Account Data -> (Connections Section)  Current follow requests (View All),
To get List we have to click on view all, then the list will be displayed on screen.
But sir now a days we can't open Account data because there is a bug in App. if it is solved by Instagram then we can access. and if you follow this step while opening in desktop then we can access live. Please try once.
Thank you sir for giving positive Reply.

Regards

**Comment by mgp25** [comment]
@alfazck After looking closely at the request which seems to be the same as the web, I am not going to implement it inside the API. That doesn't mean you can't implement the function on your own, something like:

```php
    public function getPendingFollowingRequests()
    {
        return $this->ig->request("https://www.instagram.com/accounts/access_tool/current_follow_requests")
            ->getResponse(new Response\GenericResponse());
    }
```

The response is an HTML page, and the information you are looking from is inside this tag: `<script type="text/javascript">window._sharedData = `, which comes in JSON.

Hope this helped you, in case you need anything else, let me know.

Regards

**Comment by alfazck** [comment]
Thank you so much sir, i will surely try this. 
You are Excellent sir. :+1:

**Comment by fredm12** [comment]
Hello mgp25, 

I don't see how to reach the final list of pending followings from the json you talked about. Could you drive me to the way please?

Here is an example of json I see : 
``{
	"config": {
		"csrf_token": "V9MsWm2QTNzLvmGa5fcBtFfFgsAwdoWN",
		"viewer": null,
		"viewerId": null
	},
	"supports_es6": false,
	"country_code": "FR",
	"language_code": "en",
	"locale": "en_US",
	"entry_data": {
		"LoginAndSignupPage": [{
				"captcha": {
					"enabled": false,
					"key": ""
				},
				"gdpr_required": true,
				"tos_version": "eu",
				"username_hint": ""
			}
		]
	},
	"gatekeepers": {
		"cb": true,
		"seo": true,
		"seoht": true,
		"phone_qp": true,
		"nt": true,
		"rp": true,
		"daid": true,
		"frx": true,
		"hpi": true
	},
	"knobs": {
		"acct:ntb": 0,
		"cb": 0,
		"captcha": 0,
		"fr": 0
	},
	"qe": {
		"fsu_count": {
			"g": "",
			"p": {}
		},
		"iab": {
			"g": "",
			"p": {}
		},
		"app_upsell": {
			"g": "",
			"p": {}
		},
		"profile_header_name": {
			"g": "",
			"p": {}
		},
		"bc3l": {
			"g": "",
			"p": {}
		},
		"direct_conversation_reporting": {
			"g": "",
			"p": {}
		},
		"frx_reporting": {
			"g": "",
			"p": {}
		},
		"general_reporting": {
			"g": "",
			"p": {}
		},
		"reporting": {
			"g": "",
			"p": {}
		},
		"acc_recovery_link": {
			"g": "",
			"p": {}
		},
		"notif": {
			"g": "",
			"p": {}
		},
		"mobile_stories_doodling": {
			"g": "",
			"p": {}
		},
		"show_copy_link": {
			"g": "",
			"p": {}
		},
		"p_edit": {
			"g": "",
			"p": {}
		},
		"404_as_react": {
			"g": "",
			"p": {}
		},
		"acc_recovery": {
			"g": "",
			"p": {}
		},
		"collections": {
			"g": "",
			"p": {}
		},
		"comment_ta": {
			"g": "",
			"p": {}
		},
		"su": {
			"g": "",
			"p": {}
		},
		"ebd_ul": {
			"g": "control_no_universal",
			"p": {
				"is_enabled": "false"
			}
		},
		"ebdsim_li": {
			"g": "",
			"p": {}
		},
		"ebdsim_lo": {
			"g": "",
			"p": {}
		},
		"empty_feed": {
			"g": "",
			"p": {}
		},
		"appsell": {
			"g": "",
			"p": {}
		},
		"heart_tab": {
			"g": "",
			"p": {}
		},
		"follow_button": {
			"g": "",
			"p": {}
		},
		"log_cont": {
			"g": "test_intent_m",
			"p": {
				"has_contextual_m": "true"
			}
		},
		"msisdn": {
			"g": "",
			"p": {}
		},
		"onetaplogin": {
			"g": "",
			"p": {}
		},
		"profile_tabs": {
			"g": "",
			"p": {}
		},
		"em_sig": {
			"g": "test_w_sug_d",
			"p": {
				"has_multi_step_email_suggestion": "false",
				"has_signup_email_suggestion": "true"
			}
		},
		"multireg_iter": {
			"g": "test_11_29",
			"p": {
				"has_prioritized_phone": "true"
			}
		},
		"reg_vp": {
			"g": "",
			"p": {}
		},
		"report_media": {
			"g": "",
			"p": {}
		},
		"report_profile": {
			"g": "",
			"p": {}
		},
		"sidecar_swipe": {
			"g": "",
			"p": {}
		},
		"su_universe": {
			"g": "",
			"p": {}
		},
		"stale": {
			"g": "",
			"p": {}
		},
		"tp_pblshr": {
			"g": "",
			"p": {}
		},
		"video": {
			"g": "",
			"p": {}
		},
		"felix": {
			"g": "",
			"p": {}
		},
		"felix_clear_fb_cookie": {
			"g": "",
			"p": {}
		},
		"felix_creation_duration_limits": {
			"g": "",
			"p": {}
		},
		"felix_creation_enabled": {
			"g": "",
			"p": {}
		},
		"felix_creation_fb_crossposting": {
			"g": "",
			"p": {}
		},
		"felix_creation_fb_crossposting_v2": {
			"g": "",
			"p": {}
		},
		"felix_creation_validation": {
			"g": "",
			"p": {}
		},
		"felix_creation_video_upload": {
			"g": "",
			"p": {}
		},
		"felix_early_onboarding": {
			"g": "",
			"p": {}
		},
		"unfollow_confirm": {
			"g": "",
			"p": {}
		},
		"profile_enhance_li": {
			"g": "",
			"p": {}
		},
		"profile_enhance_lo": {
			"g": "",
			"p": {}
		},
		"comment_enhance": {
			"g": "",
			"p": {}
		},
		"mweb_topical_explore": {
			"g": "",
			"p": {}
		},
		"follow_all_fb": {
			"g": "",
			"p": {}
		},
		"lite_direct_upsell": {
			"g": "",
			"p": {}
		},
		"web_loggedout_noop": {
			"g": "",
			"p": {}
		},
		"a2hs_heuristic_uc": {
			"g": "",
			"p": {}
		},
		"a2hs_heuristic_non_uc": {
			"g": "",
			"p": {}
		},
		"web_hashtag": {
			"g": "",
			"p": {}
		},
		"web_hashtag_logged_out": {
			"g": "",
			"p": {}
		},
		"header_scroll": {
			"g": "",
			"p": {}
		},
		"rout": {
			"g": "",
			"p": {}
		},
		"web_lo_follow": {
			"g": "",
			"p": {}
		},
		"web_share": {
			"g": "",
			"p": {}
		},
		"lite_rating": {
			"g": "",
			"p": {}
		},
		"web_embeds_share": {
			"g": "",
			"p": {}
		},
		"web_share_lo": {
			"g": "",
			"p": {}
		},
		"web_embeds_logged_out": {
			"g": "",
			"p": {}
		},
		"web_datasaver_mode": {
			"g": "",
			"p": {}
		},
		"lite_datasaver_mode": {
			"g": "",
			"p": {}
		},
		"lite_video_upload": {
			"g": "",
			"p": {}
		},
		"ig_aat": {
			"g": "",
			"p": {}
		},
		"post_options": {
			"g": "",
			"p": {}
		},
		"igtv_public_viewing": {
			"g": "",
			"p": {}
		},
		"caching": {
			"g": "",
			"p": {}
		},
		"nux": {
			"g": "",
			"p": {}
		},
		"hpi": {
			"g": "",
			"p": {}
		},
		"iglmsr": {
			"g": "multi_reg",
			"p": {
				"has_multi_step_registration": "true",
				"has_prefill": "false"
			}
		},
		"igwsvl": {
			"g": "",
			"p": {}
		},
		"iglcp": {
			"g": "has_prefill",
			"p": {
				"has_login_prefill": "false"
			}
		},
		"lite_story_video_upload": {
			"g": "",
			"p": {}
		},
		"iglscioi": {
			"g": "",
			"p": {}
		},
		"ws2": {
			"g": "",
			"p": {}
		},
		"wpn": {
			"g": "",
			"p": {}
		}
	},
	"hostname": "www.instagram.com",
	"deployment_stage": "c2",
	"platform": "web",
	"rhx_gis": "126f51664497f4388019f5bf2d3a74ab",
	"nonce": "GlM5OGo2zYZfloKlL1wGBw==",
	"mid_pct": 81.26324,
	"server_checks": {},
	"zero_data": {},
	"rollout_hash": "4ff2dd661008",
	"bundle_variant": "metro",
	"probably_has_app": false
}
``

**Comment by alfazck** [comment]
I also didn't reach buddy,  if you get any solution about this share with me also.

**Comment by fredm12** [comment]
No luck, alfazck. This json structure is certainly used in the framework of a cascade of javascript functions (starting with "window.__initialDataLoaded(window._sharedData)"), but I don't succeed to find the point to produce the final call/request that will return/display the list.

**Comment by alfazck** [comment]
@mgp25 Admin Please help us to solve this point, please.

**Comment by sukhcha-in** [comment]
@alfazck Thanks for this issue, i am also looking for solution to this.

**Comment by alfazck** [comment]
@sukhcha-in Anytime bro, Admin will help us to solve this issue.

**Comment by fredm12** [comment]
Not sure mgp25 will be able to solve this case. It would require something like selenium and phantomjs to engage the javascript parts and not sure mgp25 will be OK to go this way for this single feature. What's your opinion, mgp25?

**Comment by alfazck** [comment]
@fredm12 I am using this way only. but it's not the right way, mgp25 says to me if you can access it from the application then it can be accessed from this API also. there can be another way to fetch all pending together so we can cancel our request.

**Comment by alfazck** [comment]
@fredm12 , Bro its Available Check it plz
Open Instagram App > Setting > Account Data > Connection = Current Follow Request

**Comment by fredm12** [comment]
Effectivelly, my mobile app is in French, but I found it (the only difference is that it's not "Connection" at the end, but directly "Current Follow Request"; the "Connection" entry is about my own connections to the Instagram service). Well, so, since this is the case, mgp25 should re-open this thread as per his own message there : https://github.com/mgp25/Instagram-API/issues/2231#issuecomment-423149637

**Comment by fredm12** [comment]
@mgp25, what do you think?
