### ISSUE TITLE
Setting your account status as online/active now

### ISSUE THREAD

**Issue by staz0x** [mgp25/Instagram-API#2232]
Is there a function in the lib for setting your account status to online. I know it will be realtime but is there a link to the api or something? Will be really helpful ~thanks!

**Comment by mgp25** [comment]
Yes, there is a function to enable or disable that

Regards

**Comment by staz0x** [comment]
Can you give me a source or sth?

**Comment by ange007** [comment]
I think the question of the possibility of maintaining an account online. 
I could not add any features to the display status account online.

`/accounts/set_presence_disabled/` it's not that.
