### ISSUE TITLE
Can't follow anymore on API, or iPhone, but can on Instagram.com

### ISSUE THREAD

**Issue by chiliad** [mgp25/Instagram-API#2233]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

```php
$this->ig->people->follow($userId)
```

Error Log/var_dump:

```php
POST:  https://i.instagram.com/api/v1/friendships/create/466694367/
DATA: signed_body=778562c77b6a084fb8693b649cbb085798c353a745fb74b39a7e55bf4b99e481.{"_csrftoken":"kqP6xI25mqGFyV219FbJCBlA0852i8na","user_id":"466694367","radio_type":"wifi-none","_uid":"8286249280","_uuid":"3da7571f-1944-4b09-823f-efda74c47777"}&ig_sig_key_version=4
← 200    130B
RESPONSE: {"friendship_status": {"following": false, "followed_by": false, "blocking": false, "muting": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "status": "ok"}
```

After some followings and unfollowing I can no longer follow with the API 
or my iPhone during my tests, but I can from the website which is 
weird if it is a follow block i guess, any ideas?

PS: I try every 20 to 40min to see if it's gone but nope, it's been 8 hours like that

Thank you very much

**Comment by mgp25** [comment]
You have been shadowbanned. You should wait until Instagram lets you perform some actions. Why have you been shadownbanned? Probably because of spammy or suspicious activities.

As you can see, it is not an API issue since you can't on your phone as well. 

Regards

**Comment by chiliad** [comment]
There was not any spammy activities, there code performed human-like actions and i think is not a shadowban since my posts are not shelved (if i'm correct), I'm pretty sure it is not a api issue, but it "could" be linked to the API and propagated to my phone (pardon the terms) since it's properly working on the website.

I was just asking for advices and thoughts
