### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by maksam07** [mgp25/Instagram-API#2235]
Why can not I use a proxy?

Error: 
`
Network: CURL error 7: Can't complete SOCKS5 connection to 2a0b:1584:5edd:2c06:b4bd:91b2:ef45:f0c3:51127. (5) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
`
I use so:
```php
$ig->setProxy( 'socks5://login:pass@ip:port' );
```

OR
Error:
`
Network: CURL error 35: error:1408F10B:SSL routines:ssl3 get record:wrong version number (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
`
I use so: 
```php
$ig->setProxy( 'https://login:pass@ip:port' );
```

https proxy is available and I can surf the page in the browser

**Comment by maksam07** [comment]
for https the replacement on http helped

**Comment by mgp25** [comment]
Hello @maksam07,

It is not API issue, your errors are explained in the following URL: https://curl.haxx.se/libcurl/c/libcurl-errors.html

- **cURL error 7:** Failed to connect() to host or proxy. 
- **cURL error 35:** A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others. 

For more information, I recommend you to use Google.

Regards
