### ISSUE TITLE
Сreate requests and confirm SMS

### ISSUE THREAD

**Issue by maksam07** [mgp25/Instagram-API#2236]
I apologize for the incorrect question, but nowhere can I find the answer
I want to learn how to create queries, but I do not know how you get URLs and data that you need to send to it.
I have an android, but I did not find a program to track traffic
I want to create a request to send SMS when I sign in to confirm that it's me
Tried to use this function: https://github.com/mgp25/Instagram-API/issues/2143#issuecomment-412613011
But there is no variable checkpoint_challenge_required
And the answer looks like this:
`
RESPONSE: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
`

That's what it looks like when I go with a browser
<img src="https://user-images.githubusercontent.com/24889043/45837476-18ef4980-bd18-11e8-9d89-e7c68fb0092b.png" width="400">
Proposes adding a phone number
How can I confirm the phone number (or enter another) without logging in through the browser?

**Comment by mgp25** [comment]
Hello @maksam07,

If you want to learn how to create your own function to make requests I recommend you better searching in Google. This is not a support forum, is an issue tracker. We would like to help everybody but it is not possible. This kind of question has been answered many times and recently we provided a simple sketch to do this with the API.

You can find related answered issues here (contains what you are looking for): https://github.com/mgp25/Instagram-API/search?q=checkpoint&type=Issues

Also you broke one of the rules we made to open an issue:

> Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!

Regards
