### ISSUE TITLE
Session Folder

### ISSUE THREAD

**Issue by daylaborers** [mgp25/Instagram-API#2237]
Hi there,

is it possible to change the session folder? I use the API in a Laravel Application and i have an `mkdir(): Permission denied` Error. So mayby i can set the session folder in an accessable part of the app

Cheers
Ralf

**Comment by mgp25** [comment]
Hello @daylaborers,

Yes, it is possible:

```php
$ig = new Instagram($debug, $truncatedDebug, [
	'storage'    => 'file',
	'basefolder' => 'Your_Path'
]);
```

Regards

**Comment by daylaborers** [comment]
Thank you, it works
