### ISSUE TITLE
Custom Thumbnail for videos

### ISSUE THREAD

**Issue by Spielie** [mgp25/Instagram-API#2239]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue
Is there any way to set a custom preview image / thumbnail for videos in the timeline? I've seen an older issue (ID: [1114](https://github.com/mgp25/Instagram-API/issues/1114)) simular to this one. It got declined because Instagram haven't had a function like this, but it got added for Android devices about one year ago.
Is there currently any way to do this or is there an featured planed?

**Comment by mgp25** [comment]
Hello @Spielie,

As far as I remember, it is already implemented. You only need to specify the thumbnail timestamp in the external metadata array. This is passed with the key `thumbnailTimestamp`.

For more information, you can look at the following class:
https://github.com/mgp25/Instagram-API/blob/master/src/Media/Video/InstagramThumbnail.php

Regards
