### ISSUE TITLE
Unfollow not working for 100%

### ISSUE THREAD

**Issue by mkanker** [mgp25/Instagram-API#224]
Hi guys,

Have you had any issue with the unfollow?
I've done some unfollows, I got the status = "ok", but It keep following. What can be?

**Comment by mgp25** [comment]
I dont know, it works to me, you can debug it better, post more information...

**Comment by miladcoder** [comment]
hey dude . 
unfollow not working . 

im using this code for unfollow :
$ig->people->unfollow('user_pk');

this is response on debug mode : 
{"friendship_status": {"following": false, "followed_by": true, "blocking": false, "muting": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "status": "ok"}

please help me @mgp25

**Comment by miladcoder** [comment]
block and unblock working ... but unfollow not working....
