### ISSUE TITLE
Using as WebApp and Managing multiple accounts in same time

### ISSUE THREAD

**Issue by alihasanzaade** [mgp25/Instagram-API#2240]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
### Describe your issue

Thank you for your amazing library, I appreciate your efforts, I have read this library documentation and i have some question about this library.

1 - Using as WebApp

- You said we should never use this library as WebApp and we should run this library as php daemon, Because of i want to manage accounts with WebApp, I decided to run library as daemon as i communicate with daemon via RPC or Sockets,  In this way script is always running until process closed, Is this pattern OK?

- You said we cannot use this app as web app, so why in Dockerfile you are used apache?
 As i know apache will terminate sessions/process when user closes the page(as you explained in documentation), And in each request your library instance will be created from scratch.even we should use it internally in localhost
 Please tell me if i'm wrong, Can we use apache?

2 - Using multiple accounts

- As you explained in documentation , This library is same as android application and in android application we cannot manage multiple accounts in same time, we should switch accounts, But i want to manage accounts in same time, Use cannot wait for other accounts jobs, Can i manage multiple accounts in same time when i running a single daemon and communicate with this via RPC or Socket?
I think i should run a separated daemon for each account, Please tell me what is the solution?

3 - What is the realtimeHttp.php?
- Please explain realtime feature and this file, i cannot understand the usage of this file and no any documentation thats related it

 

Thanks

**Comment by JRoy** [comment]
@alihasanzaade This sounds like help you'd get with a subscription. Learn more here: #1231
