### ISSUE TITLE
Session Convert to dat Style

### ISSUE THREAD

**Issue by burakbuylu** [mgp25/Instagram-API#2241]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hello there,

I have many sessions from my old script. How can I convert to mgp25 session style?

As this class has have any function for convert? Or we must be wright helper?

An example sessions like this;

`csrftoken=sfLFdoxxBR43FkPbFeVxxx4nExMA3H98; sessionid=IGSC4a025408df39xxxxca139bb33af874535b53610d2d564204f7bd536e29d83cd%3A4HXgvBNmxvH1xasdfa3432H9jY8mvqWkh%3A%7B%22_auth_user_id%22%3A7883458413%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22_auth_user_hash%22%3A%22%22%2C%22_platform%22%3A1%2C%22_token_ver%22%3A2%2C%22_token%22%3A%227889458213%3AOyTcGxyhuzkjzxHA56apiqHPTvA7c3M9%3A7ae1ebe2eagf3447643cd05aaa1a7168d5e2edef00aceb6de9a090d0b979e139%22%2C%22last_refreshed%22%3A1536774148.9463334084%7D; urlgen="{}:1g099o:rf1riRH4teUJkVy4a_BhyaMy-pw"; ds_user_id=7889458213; rur=FTW; shbts=1536714148.9439695; shbid=2734; ds_user=testuser;
`

**Comment by mgp25** [comment]
@burakbuylu that is only the cookie from a session, It would be recommended to do a new login.
