### ISSUE TITLE
Feature request: get link for IGTV video

### ISSUE THREAD

**Issue by Zazo0** [mgp25/Instagram-API#2243]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

You have already added some functionality for IGTV but both iOS and Android apps also allow to get a link for web browser. Link example:
https://www.instagram.com/tv/BoBgGBOnpu8/

Approximate steps on android:
1)on screen with video press `...` near icons like, comment, share
2)select in menu `copy link`

**Comment by mgp25** [comment]
Added: https://github.com/mgp25/Instagram-API/commit/9d20c73eb8d55249bd596c5007a496a9944defe3

Regards
