### ISSUE TITLE
Video Uploading issue

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2245]
Hello, please, explain me whats wrong?

`FFprobe failed to analyze your video file "/Users/hellenmicky/www/insta/storage/app/uploads/tmp/IMG_6591.MOV".`

**Comment by mgp25** [comment]
Hello @AndManowar,

You might find the answer here: https://github.com/mgp25/Instagram-API/issues/1880

Also remember to always post your script code.

Regards
