### ISSUE TITLE
How check user is logged in or not?

### ISSUE THREAD

**Issue by SiddheshShah** [mgp25/Instagram-API#2246]
Here is my code :- 
$username = 'username';
$password = 'password';
$debug = false;
$truncatedDebug = false;
InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
try {
	\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
	$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
        $ig->login($username,$password);
} catch (\Exception $e) {
	 echo 'Something went wrong: '.$e->getMessage()."\n";
}
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->login($username,$password);

If i change $debug = true then i can show my response.
Can you please tell me how to check user is logged in or not..?

**Comment by mgp25** [comment]
Hello @SiddheshShah,

This question has been answered before, please have a look at: https://github.com/mgp25/Instagram-API/search?q=How+check+user+is+logged+in+or+not%3F&type=Issues

Regards
