### ISSUE TITLE
Class 'InstagramAPI\Instagram' not found

### ISSUE THREAD

**Issue by Bestfastfire** [mgp25/Instagram-API#2247]
```
<?php
	
	require 'vendor/autoload.php';
	$ig = new \InstagramAPI\Instagram();


	$login = $ig->login('id', 'pass');
	print_r($login);
```

In my code above it always gives error, I can not access the class, I have already used the **mgp25/instagram-php**, **mgp25/instagram-api** and **mgp25/instagram-php dev-master** and none worked, always the same error.

In the examples the problem is the same.

Erros: 
Fatal error: Uncaught Error: Class 'InstagramAPI\Instagram' not found
Error: Class 'InstagramAPI\Instagram' not found

**Comment by agentleo** [comment]
same issue, i'm on 'dev-master'.
any help would be appreciated, thanks.
