### ISSUE TITLE
How to use the Push API?

### ISSUE THREAD

**Issue by GyanendroKh** [mgp25/Instagram-API#2248]
I have found in the examples, [Push Receiver](https://github.com/mgp25/Instagram-API/blob/master/examples/pushReceiver.php) but not the [InstagramAPI\Request\Push](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Push.php) class example.   
I have gone throught the code of [InstagramAPI\Request\Push](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Push.php) but in the `register($pushChannel, $token)` method, I have no idea what to use for the token.

**Comment by mgp25** [comment]
Hello @GyanendroKh,

- [pushReceiver.php](https://github.com/mgp25/Instagram-API/blob/master/examples/pushReceiver.php) uses an [InstagramAPI\Request\Push](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Push.php) object, see [line 40](https://github.com/mgp25/Instagram-API/blob/master/examples/pushReceiver.php#L40)

- [Line 210](https://github.com/mgp25/Instagram-API/blob/fa6057c16d7ab646abf2a943254edcce4ef3c04d/src/Push.php#L210) of [InstagramAPI\Request\Push](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Push.php) uses a function called `_getFbns()` and you can see that it calls:

```php
$this->_instagram->push->register('mqtt', $token);
```

So there you have the class getting the token. You shouldn't manipulate that function if you don't know what the token is.

Regards
