### ISSUE TITLE
Login Problem Help Please

### ISSUE THREAD

**Issue by alihansarigit** [mgp25/Instagram-API#2249]
Hello there,

The first account login password is taken into account, the second account entry password is ignored. The solution to this is to clean the session folder or logout. If I do this, the application is running slow and the new device is added to the user "new device input" warning goes.

In summary
What should I do to make sure that the api is fast and that the password is always checked?

**Comment by alihansarigit** [comment]
> Hello there,
> 
> The first account login password is taken into account, the second account entry password is ignored. The solution to this is to clean the session folder or logout. If I do this, the application is running slow and the new device is added to the user "new device input" warning goes.
> 
> In summary
> What should I do to make sure that the api is fast and that the password is always checked?

edit : 
I need to log in when logging or logout. What's the difference?

**Comment by mgp25** [comment]
Hello @alihansarigit,

It is explained in the functions documentation both `login` and `logout`

Regards
