### ISSUE TITLE
password check when login

### ISSUE THREAD

**Issue by Keremturker** [mgp25/Instagram-API#2252]
Hello, how can i do password check when every login ?

I want do because , if once correct entered username and password, later even if an incorrect  password is entered response is be successful.
Maybe solution is a delete  session folder or call logout function. This time if is logged on different device  and if call anything function response is be ' Login Required'.

So, how can i check  password  when try login?

**Comment by mgp25** [comment]
Hello @Keremturker,

Once you hace logged in successfully, the API will be reusing the existing valid session, and this is how it is supposed to be (think the same as the mobile app). The app doesn't check your password everytime you use it and neither the API.

You can logout, that will delete your existing session, so you can process the password again, but this is NOT a good practice, and this is something you don't want to do in your app.

Additionally, if you don't have any session, you can catch an exception if the password is invalid.

Regards

**Comment by mgp25** [comment]
@Keremturker calling the function `login()` doesn't mean you always authenticate to the server. If you have already a valid session you will skip that part and only do some requests to mimic app behavior.

I recommend you reading both functions documentation, it is everything explained there and in the F.A.Q.

Regards

**Comment by miller1702** [comment]
How can I check for new password?
