### ISSUE TITLE
Remove Follower 

### ISSUE THREAD

**Issue by zertex** [mgp25/Instagram-API#2254]
```
removeFollower except error:
https://i.instagram.com/api/v1/friendships/remove_follower/FName/
Page Not Found
```

`FName` exist in followed

**Comment by mgp25** [comment]
@zertex can you post debug log, please?

**Comment by zertex** [comment]
Sorry... My error... Need UserId, I paste Username...
Now all ok, but user keep in followers :(
May be I do something wrong... Thanks
