### ISSUE TITLE
Requesting Login attempt dialog for user 

### ISSUE THREAD

**Issue by logaro** [mgp25/Instagram-API#2257]
### Purpose of your issue
- [x] Feature request (request for new functionality)
---
Hi 
when i login with other device or other web based API's i get this message in my mobile 

> (we detected an login attempt .....+ map location + button to select THIS WAS ME) 

like this image:
https://image.ibb.co/eWNHGz/login.png

**When i use this API i don't receive that question message.**

I think getting that message on device and user selecting "this was me" make the bot less risky for normal usage and some websites are using this feature already. 

**How can i change the login to work like that?** 

i want the user accept it , and instagram understand that this is him requesting this access.

**Comment by mgp25** [comment]
Hello @logaro,

This is something I dont plan to support, but if you are intested in adding that feature, you are welcome to send pull requests.

Regards
