### ISSUE TITLE
cookie file is not writable

### ISSUE THREAD

**Issue by shayanzd20** [mgp25/Instagram-API#2258]
hi mgp25
thanks for your great API.
please help me with below error. I oppose sometimes in some API

### here is error
`Something went wrong: The "/home/???????/domains/?????/public_html/instagram/Instagram-API/sessions/instagramaccountsherin.ema-cookies.dat" cookie file is not writable.`
### end

**Comment by mgp25** [comment]
This has nothing to do with the API. Check the folder permissions.

Regards
