### ISSUE TITLE
getHashFeed['items] Empty

### ISSUE THREAD

**Issue by FarhadF** [mgp25/Instagram-API#226]
Hi guys,

First of all Awesome job!
since 3-4 days ago I noticed I cant get items of popular tags like 'selfie', 'instagood' and etc. only ranked_items array is populated but items array is Null. any work around? 

                    [caption_is_edited] => 
                    [usertags] => Array
                        (
                            [in] => Array
                                (
                                )

                        )

                    [photo_of_you] => 
                )

        )

    [status] => ok
    [num_results] => 0
    [auto_load_more_enabled] => 1
    [items] => Array
        (
        )

    [more_available] => 
)

thanks in advance.
Farhad

**Comment by FarhadF** [comment]
After more research I got that instagram Hides popular tags recent posts from time to time. Selfie and instagood are currently hidden. So not an issue, Just information :)

Thanks
Farhad

**Comment by mgp25** [comment]
@FarhadF thanks! i'll add this info in the wiki

Regards
