### ISSUE TITLE
Issue while fetching Hashtags info

### ISSUE THREAD

**Issue by angelocala94** [mgp25/Instagram-API#2263]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

#### Issue while fetching Hashtags info

I'm using the search function of Hashtag class.
My code works but I need name, media count and profile_pic_url, but the IG APIs returns only name and media count, the other params are null.

This is not a problem caused by this library, because the Instagram endpoint does not return these informations. 

(https://i.instagram.com/api/v1/tags/search/?timezone_offset=0&q=cats&count=5 for example).

The Instagram app shows these pictures while searching, maybe this endpoint is wrong or there is another endpoint to fetch these informations.

I tried also getInfo() that refers to this endpoint (https://i.instagram.com/api/v1/tags/cats/info/) but nothing, profile_pic_url is always null.

Anyone could help me?

**Comment by mgp25** [comment]
@angelocala94 please, provide debug log

**Comment by angelocala94** [comment]
As I sad, I think that is not a library related issue, because Instagram endpoint `/tags/search` returns "null" for profile_pic_url param.
My question is: is there another endpoint used by the official Instagram app? 
Btw, this is the code and output.

#### Code:
```
try {
     $response = $this->ig->hashtag->search($query);
     foreach ($response->getResults() as $hashtag) {
        echo "hashtag dump:\n";
        var_dump($hashtag);
        echo "profile_pic_url dump:\n";
        var_dump($hashtag->getProfilePicUrl());
    }
} catch (\Exception $e) {
     \Log::info('INSTAGRAM: '.$e->getMessage());
}
```
#### Output
```
hashtag dump:
object(InstagramAPI\Response\Model\Tag)#1533 (2) {
  ["_compiledPropertyMapLink":"LazyJsonMapper\LazyJsonMapper":private]=>
  &array(3) {
    ["media_count"]=>
    object(LazyJsonMapper\Property\PropertyDefinition)#1183 (3) {
      ["arrayDepth"]=>
      int(0)
      ["propType"]=>
      string(3) "int"
      ["isObjectType"]=>
      bool(false)
    }
    ["name"]=>
    object(LazyJsonMapper\Property\PropertyDefinition)#1545 (3) {
      ["arrayDepth"]=>
      int(0)
      ["propType"]=>
      string(6) "string"
      ["isObjectType"]=>
      bool(false)
    }
    ["id"]=>
    object(LazyJsonMapper\Property\PropertyDefinition)#1182 (3) {
      ["arrayDepth"]=>
      int(0)
      ["propType"]=>
      string(6) "string"
      ["isObjectType"]=>
      bool(false)
    }
  }
  ["_objectData":"LazyJsonMapper\LazyJsonMapper":private]=>
  array(17) {
    ["id"]=>
    int(17841563647117066)
    ["name"]=>
    string(12) "foodbloggers"
    ["media_count"]=>
    int(1630166)
    ["follow_status"]=>
    NULL
    ["following"]=>
    NULL
    ["allow_following"]=>
    NULL
    ["allow_muting_story"]=>
    NULL
    ["profile_pic_url"]=>
    NULL
    ["non_violating"]=>
    NULL
    ["related_tags"]=>
    NULL
    ["subtitle"]=>
    NULL
    ["social_context"]=>
    NULL
    ["social_context_profile_links"]=>
    NULL
    ["follow_button_text"]=>
    NULL
    ["show_follow_drop_down"]=>
    NULL
    ["debug_info"]=>
    NULL
    ["search_result_subtitle"]=>
    string(10) "1.6m posts"
  }
}
profile_pic_url dump:
NULL
```

**Comment by mgp25** [comment]
@angelocala94 Just checked latest requests from apk. Everything is okay, and the responses you are getting are okay as well.

You can get stories that are related to tag doing a GET request to: `https://i.instagram.com/api/v1/tags/cats/story/`

I think this concrete request is not implemented, but let me know if it works and can be added before publishing a new release of the code.

Regards

**Comment by angelocala94** [comment]
So, Instagram app makes more than one GET request to retrieve tags info while searching?
Instagram shows me an image, the tag name and the "search_result_subtitle" params.
I thought the image showing in the Instagram app was inside the profile_pic_url property.

![img_2416](https://user-images.githubusercontent.com/6445721/46620812-123d4080-cb26-11e8-9d1a-0e58dd489637.jpg)

At the moment I'm using an alternative way to get these images on client side, to not slow down the APIs.

I'm getting asynchronously these images querying this endpoint: https://www.instagram.com/explore/tags/cats/?__a=1

**Comment by mgp25** [comment]
@angelocala94 will be fixed in the next commit.

Regards

**Comment by angelocala94** [comment]
Thanks @mgp25, awesome!
