### ISSUE TITLE
Cant get profile media/followers/followings statistics anymore

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2264]
Hi, Im trying to get mediaCount/followers and followings count like this 

    var_dump($activeAccount->getInstagramAccount()->getUser()->getMediaCount()), but it returns null.
A few days ago it worked, but now - not.
Has instagram changed something in their API?

    $activeAccount->getInstagramAccount()->getUser()->asArray() 
returns 

    Array
    (
    [has_persistent_profile_school] => 
    [can_boost_post] => 
    [has_biography_translation] => 1
    [profile_pic_url] => https://instagram.fiev15-1.fna.fbcdn.net/vp/16e5d3b5767a831c6b0af4db2192a4d9/5C44A083/t51.2885-19/s150x150/42080442_2187664541455458_5888612944085778432_n.jpg
    [persistent_profile_school_entry_point_type] => none
    [school] => Array
        (
        )

    [show_insights_terms] => 
    [is_eligible_for_school] => 
    [has_placed_orders] => 
    [can_see_organic_insights] => 
    [is_private] => 
    [biography] => Только самые интересные новости и факты со всего мира. Подписывайся )
    [allowed_commenter_type] => any
    [username] => vse__znay
    [profile_pic_id] => 1883366837956110198_8540444136
    [hd_profile_pic_versions] => Array
        (
            [0] => Array
                (
                    [height] => 320
                    [url] => https://instagram.fiev15-1.fna.fbcdn.net/vp/c5f69890fd6c6c024f45fc68c5fbde90/5C53DFFB/t51.2885-19/s320x320/42080442_2187664541455458_5888612944085778432_n.jpg
                    [width] => 320
                )

        )

    [reel_auto_archive] => unset
    [is_verified] => 
    [show_conversion_edit_entry] => 1
    [full_name] => Интересные Новости
    [pk] => 8540444136
    [has_anonymous_profile_picture] => 
    [hd_profile_pic_url_info] => Array
        (
            [height] => 329
            [url] => https://instagram.fiev15-1.fna.fbcdn.net/vp/4b5cba24af042d93e6397b366a023849/5C58BEFB/t51.2885-19/42080442_2187664541455458_5888612944085778432_n.jpg
            [width] => 329
        )

    [external_url] => 
    [birthday] => 
    [phone_number] => +380732064276
    [country_code] => 380
    [national_number] => 732064276
    [gender] => 3
    [email] => manowartop97@gmail.com
    [needs_email_confirm] => 1
    [can_link_entities_in_bio] => 
    )

**Comment by mgp25** [comment]
Use the appropiate function. Can be found here: https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php

Regards

**Comment by Tridenn** [comment]
@mgp25 Hey. I'm sorry for interrupting. Question. When posting multiple photos, the instaram responds that all is well. Everything is as usual. But the post does not appear, when placing individual photos, everything is fine. There is nothing unusual in the response to the ingram. Could you try to make a post from several photos, whether it will be published with you or not.

**Comment by mgp25** [comment]
@Tridenn I think you have commented in the wrong issue maybe?

**Comment by Tridenn** [comment]
@mgp25. I did not want to create a whole issue. By this I asked here. The ability to post a few photos has already returned. Apparently it was a bug on the side of instagram. Thank you.
