### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by amirkhh** [mgp25/Instagram-API#2265]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
// Please provide your own code here, for example:

public function actionLogin2($username, $password, $verificationCode)
    {
        try{
            $this->ig = new Insta(true, false);

            $loginResponse = $this->ig->login($username, $password);
            
            if($loginResponse !== null && $loginResponse->isTwoFactorRequired())
            {
                $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();
                // The "STDIN" lets you paste the code via terminal for testing.
                // You should replace this line with the logic you want.
                // The verification code will be sent by Instagram via SMS.
                //$verificationCode = '264779';//trim(fgets(STDIN));
                $this->ig->finishTwoFactorLogin($username, $password, $twoFactorIdentifier, $verificationCode);
            }
        }
        catch(IncorrectPasswordException $e)
        {
            echo 'Something went wrong (InstagramException): '.$e->getMessage()."\n";
        }
        catch (InstagramException $e) {
            echo 'Something went wrong (InstagramException): '.$e->getMessage()."\n";
        }
    }
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

RESPONSE: {"message": "Update your app to log in with two-factor authentication.", "status": "fail", "error_type": "needs_upgrade"}

Something went wrong (InstagramException): InstagramAPI\Response\LoginResponse: Update your app to log in with two-factor authentication.
```

---

### For a new endpoint *feature request*, you should include the *capture of the request and response*.

Request:

```http
# Please provide your capture below, for example:

POST:  https://i.instagram.com/api/v1/accounts/login/
DATA: signed_body=234a1ab6a0e3cb959032539a7e6682fb0bb20da272832395280fbec4a2d4b25a.{"phone_id":"7ab845a3-a363-4c6c-9996-9e529ae82900","_csrftoken":"HorWkvOpAljnEUzxpa6hi4GwOnR6rZNG","username":"amir_mooz","adid":"3b4f1478-ca74-4090-a89d-7c765c723e91","guid":"62978894-4e6f-44f0-9abc-eb4a0715d62e","device_id":"android-f18777f5054c49f1","password":"123456789a","login_attempt_count":"0"}&ig_sig_key_version=4
â†گ 400          121B

```

Response:

```http
# Please provide your capture below, for example:

RESPONSE: {"message": "Update your app to log in with two-factor authentication.", "status": "fail", "error_type": "needs_upgrade"}
```
---

### Describe your issue

Hi, I want to use two factor authentication and I've used your example.

I didn't get verification code by sms, I get it by Google Authenticator but I have below error:

"Update your app to log in with two-factor authentication."

what's the problem ? my code has wrong ?

**Comment by mgp25** [comment]
@amirkhh ar you using `dev-master`?

**Comment by mgp25** [comment]
@amirkhh will be fixed in the next commit.

Regards
