### ISSUE TITLE
Upload album

### ISSUE THREAD

**Issue by Tridenn** [mgp25/Instagram-API#2266]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones 
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ) 
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki) 
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples) 
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation) 

### Purpose of your issue? 
- [ ] Bug report (encountered problems/errors) 
- [ ] Feature request (request for new functionality) 
- [x] Question 
- [ ] Other 

The last few days with the loading of albums going on something strange. The first response to instagram is that everything is fine, but the recording is not published. If you do a lot of attempts, then the post begins to be published. Added a configureWithRetries request to the code again and it gives an error, although the first one says ok. I cited below: Other media configure error: b'1z4HvICOon. But! After some time, the error disappears and starts to be placed normally. No one came across this? Maybe I'm doing something wrong? Photo upload, copied from example. I tried several versions of the library.

POST: https://i.instagram.com/api/v1/feed/timeline/ 
DATA: "status": "ok" 

POST: https://i.instagram.com/api/v1/upload/photo/ 
→ 22.34kB 
← 200 115B 
RESPONSE: {"upload_id": "1539036552144", "media_id": "1885897753750586866_3102583937", "xsharing_nonces": {}, "status": "ok"} 

POST: https://i.instagram.com/api/v1/upload/photo/ 
→ 21.21kB 
← 200 115B 
RESPONSE: {"upload_id": "1539036552309", "media_id": "1885897762508171048_3102583937", "xsharing_nonces": {}, "status": "ok"} 

POST: https://i.instagram.com/api/v1/media/configure_sidecar/ 
DATA: signed_body=90a344c646539e9b49894a793c5163c977930e93dc1e90f21bce56982ff198b3.{"_csrftoken":"JWxZb3rRPMPcMxJB7j6phAWex8sWDWAq","_uid":"3102583937","_uuid":"9527b7fa-ea8c-42b8-a5ba-7779b6d667e9","caption":"!!","children_metadata":[{"date_time_original":"2018:10:09 01:09:14","scene_type":1,"disable_comments":false,"upload_id":"1539036552144","source_type":0,"scene_capture_type":"standard","date_time_digitized":"2018:10:09 01:09:14","geotag_enabled":false,"camera_position":"back","edits":{"filter_strength":1,"filter_name":"IGNormalFilter"}},{"date_time_original":"2018:10:09 01:09:14","scene_type":1,"disable_comments":false,"upload_id":"1539036552309","source_type":0,"scene_capture_type":"standard","date_time_digitized":"2018:10:09 01:09:14","geotag_enabled":false,"camera_position":"back","edits":{"filter_strength":1,"filter_name":"IGNormalFilter"}}],"client_sidecar_id":"1539036554979"}&ig_sig_key_version=4 
← 200 1.46kB 
RESPONSE: {"client_sidecar_id": "1539036554979", "media": {"taken_at": 1539036555, "pk": 1885897771266818175, "id": "1885897771266818175_3102583937", "device_timestamp": 1539036554979, "media_type": 8, "code": "BosDgfzD0B_", "client_cache_key": "MTg4NTg5Nzc3MTI2NjgxODE3NQ==.2", "filter_type": 0, "comment_likes_enabled": false, "comment_threading_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "preview_comments": [], "can_view_more_preview_comments": false, "comment_count": 0, "carousel_media_count": 2, "carousel_media": [{"id": "1885897753750586866_3102583937", "media_type": 1, "image_versions2": {"candidates": [{"width": 600, "height": 600, "url": "https://instagram.fhel6-1.fna.fbcdn.net/vp/331496a536f00e01df4e10719add5cc1/5C4899F5/t51.2885-15/e35/42986887_249054962621351_8175341300883448188_n.jpg?ig_cache_key=MTg4NTg5Nzc1Mzc1MDU4Njg2Ng%3D%3D.2"}, {"width": 240, "height": 240, "url": "https://instagram.fhel6-1.fna.fbcdn.net/vp/b8e87c6c30c66eac24a677877a8f7cb1/5C4A98FD/t51.2885-15/e35/s240x240/42986887_249054962621351_8175341300883448188_n.jpg?ig_cache_key=MTg4NTg5Nzc1Mzc1MDU4Njg2Ng%3D%3D.2"}]}, "original_width": 600, "original_height": 600, "pk": 1885897753750586866, "carousel_parent_id": "1885897771266818175_3102583937", "fb_user_tags": {"in": []}}, {"id": "1885897762508171048_3102583937", "media_type": 1, "image_versions2": {"candidates": [{"width": 600, "height": 600, "url": "https://instagram.fhel6-1.fna.fbcdn.net/vp/532002d6a4b8fafafe6581a0312081a4/5C62C964/t51.2885-15/e35/42611084_1886621668099549_4907155856702819952_n.jpg?ig_cache_key=MTg4NTg5Nzc2MjUwODE3MTA0OA%3D%3D.2"}, {"width": 240, "height": 240, "url": "https://instagram.fhel6-1.fna.fbcdn.net/vp/3b19303648902d5d94d5a686eaa1bdbf/5C61215D/t51.2885-15/e35/s240x240/42611084_1886621668099549_4907155856702819952_n.jpg?ig_cache_key=MTg4NTg5Nzc2MjUwODE3MTA0OA%3D%3D.2"}]}, "original_width": 600, "original_height": 600, "pk": 1885897762508171048, "carousel_parent_id": "1885897771266818175_3102583937", "fb_user_tags": {"in": []}}], "user": {"pk": 3102583937, "username": "denis_tr333", "full_name": "\u0414\u0435\u043d\u0438\u0441 \u0422\u0440\u0438\u0444\u0430\u043d\u043e\u0432", "is_private": false, "profile_pic_url": "https://instagram.fhel6-1.fna.fbcdn.net/vp/4ac223e3c4c19bd6020baef893619787/5C5AEF2B/t51.2885-19/s150x150/41823348_1170613403092770_5476867395924525056_n.jpg", "profile_pic_id": "1735644102367414432_3102583937", "has_anonymous_profile_picture": false, "can_boost_post": true, "can_see_organic_insights": true, "show_insights_terms": false, "reel_auto_archive": "on", "is_unpublished": false, "allowed_commenter_type": "any"}, "can_viewer_reshare": true, "caption": {"pk": 17981200615069329, "user_id": 3102583937, "text": "!!", "type": 1, "created_at": 1539036555, "created_at_utc": 1539036555, "content_type": "comment", "status": "Active", "bit_flags": 0, "user": {"pk": 3102583937, "username": "denis_tr333", "full_name": "\u0414\u0435\u043d\u0438\u0441 \u0422\u0440\u0438\u0444\u0430\u043d\u043e\u0432", "is_private": false, "profile_pic_url": "https://instagram.fhel6-1.fna.fbcdn.net/vp/4ac223e3c4c19bd6020baef893619787/5C5AEF2B/t51.2885-19/s150x150/41823348_1170613403092770_5476867395924525056_n.jpg", "profile_pic_id": "1735644102367414432_3102583937", "has_anonymous_profile_picture": false, "can_boost_post": true, "can_see_organic_insights": true, "show_insights_terms": false, "reel_auto_archive": "on", "is_unpublished": false, "allowed_commenter_type": "any"}, "did_report_as_spam": false, "media_id": 1885897771266818175}, "caption_is_edited": false, "boosted_status": "not_boosted", "photo_of_you": false, "fb_user_tags": {"in": []}, "can_viewer_save": true, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZGY1ZmRmMjI2YzgwNDNkOWI1ZjJmMWJjYjliYjcwZTYxODg1ODk3NzcxMjY2ODE4MTc1Iiwic2VydmVyX3Rva2VuIjoiMTUzOTAzNjU1NzI3NXwxODg1ODk3NzcxMjY2ODE4MTc1fDMxMDI1ODM5Mzd8NjQ5OGYzNWNmMTg3MjYzNGRhODJjY2Y2MGQ3ZGY3NzljYjUwNGY4ZjhlMWJhZDc2ODNhNzIwNjdkZjAwMTBhNCJ9LCJzaWduYXR1cmUiOiIifQ=="}, "status": "ok"} 

POST: https://i.instagram.com/api/v1/media/configure_sidecar/ 
DATA: signed_body=254d3f3e3e977626ab5ae61ced6df43fe5b217f5b9dda11bb2e88bd38297951c.{"_csrftoken":"JWxZb3rRPMPcMxJB7j6phAWex8sWDWAq","_uid":"3102583937","_uuid":"9527b7fa-ea8c-42b8-a5ba-7779b6d667e9","caption":"!!","children_metadata":[{"date_time_original":"2018:10:09 01:09:22","scene_type":1,"disable_comments":false,"upload_id":"1539036552144","source_type":0,"scene_capture_type":"standard","date_time_digitized":"2018:10:09 01:09:22","geotag_enabled":false,"camera_position":"back","edits":{"filter_strength":1,"filter_name":"IGNormalFilter"}},{"date_time_original":"2018:10:09 01:09:22","scene_type":1,"disable_comments":false,"upload_id":"1539036552309","source_type":0,"scene_capture_type":"standard","date_time_digitized":"2018:10:09 01:09:22","geotag_enabled":false,"camera_position":"back","edits":{"filter_strength":1,"filter_name":"IGNormalFilter"}}],"client_sidecar_id":"1539036554979"}&ig_sig_key_version=4 
← 500 75B 
RESPONSE: {"message": "Other media configure error: b'1z4HvICOon'", "status": "fail"}

**Comment by Tridenn** [comment]
I think this is due to the latest instagram updates that happened just a few days ago. One picture is normally placed. I think this is because through the web, you can publish one picture and there does not process the photo on the client. The album can be poured only from the phone, perhaps they began to add their own exif or vice versa to check the absence, but I tried to clean it additionally for everyone.

**Comment by mgp25** [comment]
I can't tell what your issue is, probably because a misconfigured media. And just tested on my side, and works perfectly for me.

Regards

**Comment by Tridenn** [comment]
@mgp25 used  \InstagramAPI\Media\Photo\InstagramPhoto?

**Comment by mgp25** [comment]
I used the `uploadAlbum` example

**Comment by frmeran** [comment]
I'm having that issue also

**Comment by mehrdadmms** [comment]
@mgp25 
Hello I have an issue with uploading videos in album 
I get this error from Instagram server 
`{'message': 'In migration.', 'status': 'fail'}`
have you ever seen such error ? 

please answer :((
