### ISSUE TITLE
getFollowedBy() return no value but getFriendship() okay...

### ISSUE THREAD

**Issue by xavdep** [mgp25/Instagram-API#2267]
Hi all,

```php
echo($ig->people->getFriendship("3622434838"))
```
 return 

`{"following":false,"followed_by":false,"blocking":false,"muting":false,"is_private":false,"incoming_request":false,"outgoing_request":false,"is_blocking_reel":false,"is_muti
ng_reel":false,"is_bestie":false,"status":"ok"}`

but 

```php
echo($ig->people->getFriendship("3622434838")->getFollowedBy()) 
```
return no value, like a blank value. Same for getFollowing or getIsPrivate... blank value

What a mess I don't understand. It's a bug? A troubleshoot with symfony 3.4 and JSON Parsing and PHP 7?

Thanks

**Comment by mgp25** [comment]
Hello @xavdep,

It is not an API issue or either a bug. You have to get more experience with PHP and make sure about the things before posting them.

You can go to php interactive mode in the Terminal by doing `php -a`. Try doing this:

```
mgp25$ php -a
Interactive shell

php > echo false

```

As you can see above boolean values can't be echoed. You can actually do other things such as `var_dump()`:

```
mgp25$ php -a
Interactive shell

php > var_dump(false);
bool(false)
```

You can try other functions like `is_bool()`, etc.

You have to differentiate between the response and the values inside the response, when you are doing:

```php
$response = $ig->people->getFriendship("3622434838");

echo $response->asJson();
```

This is the response:

`{"following":false,"followed_by":false,"blocking":false,"muting":false,"is_private":false,"incoming_request":false,"outgoing_request":false,"is_blocking_reel":false,"is_muti ng_reel":false,"is_bestie":false,"status":"ok"}`

When you are doing:

```php
$response = $ig->people->getFriendship("3622434838");

$followedBy = $response->getFollowedBy(); // Here you are getting the value of `followed_by`
```

You are returning the value of the key `followed_by` which is `false` (boolean).

Hope you have undertood what was going here. And I encourage you to keep learning and keep trying new things. But remember to always search before posting anything, most of the times the answer is the obvious one 😉 

Regards

**Comment by xavdep** [comment]
Yes, three steps:

- The interactive php console
- Function vardump
- The things with the boolean can't echoed. (I try to write them in a database, but same effect, blank value and not a false or 0 written...)
- Difference with response and one component of response

Does I miss something ?

Thanks

**Comment by mgp25** [comment]
@xavdep Make sure you are storing the values correctly and that the field has its propper type set, but since it is a database thing, this is no longer the repository to ask.

If you are storing everything as a string, it might be useful for you looking at the example I posted to you:

```php
$response = $ig->people->getFriendship("3622434838");

$followedBy = $response->getFollowedBy();

if ( $followedBy === true ) {
    echo 'true';
} elseif ( $followedBy === false ) {
   echo 'false';
}
```

or the short form:

```php
echo $followedBy ? 'true' : 'false';
```

**Comment by xavdep** [comment]
Ok maybe I need to sleep... So in PHP when you treat booleans, it's nothing/blank for false and 1 for true when we take values? Why PHP do that to us ? We are just humans haha

Thanks to you I think I have understand the trick. You're the man !

**Comment by mgp25** [comment]
@xavdep 

```
mgp25$ php -a
Interactive shell

php > echo false;
php > echo true;
1
php > echo (int) false;
0
php > echo (int) true;
1
php > echo "true";
true
php > echo "false";
false
```

**Comment by xavdep** [comment]
All is understood commander @mgp25 , mission can resume !!
