### ISSUE TITLE
Story without items

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2268]
Hey, how can I display story, if it doesnt have any items. 
e.g.:

    [2] => Array
                (
                    [id] => tag:cat:1539065726244
                    [latest_reel_media] => 1539065726
                    [expiring_at] => 1539152126
                    [seen] => 0
                    [can_reply] => 
                    [can_reshare] => 
                    [reel_type] => mas_reel
                    [owner] => Array
                        (
                            [type] => tag
                            [pk] => cat
                            [name] => #cat
                            [profile_pic_url] => https://instagram.fiev15-1.fna.fbcdn.net/vp/ef18efaf8b1d14647ccd71fdf51d3d88/5C47DFD0/t51.2885-15/e35/42122586_1034908683346819_4910025465349083950_n.jpg?se=7&ig_cache_key=MTg4NTY3MTk1NDgyMTA3OTk2OQ%3D%3D.2
                            [profile_pic_username] => nala_cat
                        )

                    [items] => Array
                        (
                        )

                    [prefetch_count] => 0
                    [unique_integer_reel_id] => 1886109148350066555
                    [muted] => 
                    [ranked_position] => 3
                    [seen_ranked_position] => 3
                )

        )

**Comment by mgp25** [comment]
Hello @AndManowar,

You need to use: https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php#L148

```php
$ig->story->getReelsMediaFeed('tag:cat:1539065726244');
```

Let me know if that worked.
