### ISSUE TITLE
Error running linkAddressBook and unlinkAddressBook

### ISSUE THREAD

**Issue by Shamim1977** [mgp25/Instagram-API#2269]
```php
<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require 'autoload.php';

/////// CONFIG ///////
$username = 'myigusername'
$password = 'myigpass'
$debug = true;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
 

    $ig->unlinkAddressBook();
    
    $contacts = array(
        array(
            'first_name' => 'Contact1',
            'phone_numbers' => array('+123455566'),
            'email_addresses' => array('')
        )
    );

    //$res = new \InstagramAPI\Request\People\linkAddressBook($contacts);
    $res = $ig->linkAddressBook($contacts);
    echo $res;
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

```
...the above piece is saved in a file named crow.php where autoload.php is situated. login goes successful. It gives a lot of usernames which I am following but not linking addressbook, but saying-

`Fatal error: Uncaught Error: Call to undefined method InstagramAPI\Instagram::linkAddressBook() in /Users/shamimhossain/vendor/crow.php:38
Stack trace:
#0 {main}
  thrown in /Users/shamimhossain/vendor/crow.php on line 38`

btw, same thing happens with `unlinkAddressBook`.

Note: I am running this locally on a Mac.

Please save me.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/search?q=unlinkAddressBook&unscoped_q=unlinkAddressBook
