### ISSUE TITLE
Please update your Instagram app to continue following...

### ISSUE THREAD

**Issue by LevPasha** [mgp25/Instagram-API#227]
Hi! I use 8.2 sig key, but follow return {"status": "fail", "message": "Please update your Instagram app to continue following."}. What's wrong?

**Comment by mgp25** [comment]
@LevPasha force a login and it will work

Regards

**Comment by LevPasha** [comment]
@mgp25 hi! The problem is in something different. I clean all saved data, and if I catch request header there is: "User-Agent: Instagram 8.2.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)".

Like and login work fine...
