### ISSUE TITLE
How to change v1 to find_v2

### ISSUE THREAD

**Issue by Shamim1977** [mgp25/Instagram-API#2270]
RESPONSE: {"users": [], "warning": "This endpont is deprecated, please use find_v2", "status": "ok"}

I am getting the above message while using addressbook to link/unlink. 
Can you please tell me which file I should go to change "v1" to "find_v2"?

I will be obliged.

**Comment by mgp25** [comment]
Hello @Shamim1977,

This feature is something I don't pretend to give support anymore. Still, if you are interested, you can research it and send a PR we will gladly accept.

Regards
