### ISSUE TITLE
Insights response empty

### ISSUE THREAD

**Issue by iagoqueiroz** [mgp25/Instagram-API#2272]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hi, i'm using a web (http) application using this api and i'm having some issues on the response of the insights. Is returning a empty node, and dont know why, but some days ago are still working correctly

```php
        if ($this->login($account->username, $account->password)) {
            return $this->getResponseJson(
                $this->ig->business->getInsights()
            );
        }
```

The response:
```json
{
    "instagram_user": {
        "instagram_insights": {
            "nodes": []
        }
    },
    "status": "ok"
}
```

**Comment by mgp25** [comment]
@iagoqueiroz What release of the API are you using?

**Comment by iagoqueiroz** [comment]
I updated yesterday on morning to the latest one, dev-master.

**Comment by mgp25** [comment]
@iagoqueiroz I can research it but I would need a business account, if any could send me the credentials of a business account (via email) I'll research it.

**Comment by Daenyl** [comment]
If u need a business account to get gender insights or best time to post and blabal...i'll can send u my profile if u need yet

**Comment by mgp25** [comment]
@Daenyl It would be great!

**Comment by mgp25** [comment]
Funtion updated. Related commit: https://github.com/mgp25/Instagram-API/commit/c3e57d5c7fb41a9a2c29f90c6f2511884d4043b8

Regards
