### ISSUE TITLE
Improvement of log in 

### ISSUE THREAD

**Issue by solcre-at** [mgp25/Instagram-API#2275]
Such API should allow us to generate a client id and by means of a Instagram log in (or a custom external log in by you) get an access token to be able to do requests about this API without having to storage the user's credentials.

Otherwise we need to storage the user's credentials to use them each time that we do a request about such API.

**Comment by mgp25** [comment]
Hello @solcre-at,

Maybe you haven't understood the nature of this API. It is based on the android app (That's why it's called "Instagram private API"). We can't do such thing.

**Comment by solcre-at** [comment]
I understood properly how it works but I think that such improvement could improve the API usage.

It's a weak point to improve.
