### ISSUE TITLE
Real data for device_id, phone_id, uuid

### ISSUE THREAD

**Issue by dakiesse** [mgp25/Instagram-API#2277]
Hey! Where can I find the data on real device? I mean from Android API

      this.settings.set('device_id', Signatures.generateDeviceId())
      this.settings.set('phone_id', Signatures.generateUUID(true))
      this.settings.set('uuid', Signatures.generateUUID(true))

**Comment by mgp25** [comment]
It might be stored somewhere in the private folders of the API in your system device. These values are generated inside the application.

Not API issue.

Regards
