### ISSUE TITLE
How to request a security code via SMS or email?

### ISSUE THREAD

**Issue by wolrd** [mgp25/Instagram-API#2281]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Intagram requests to send a code to an email or SMS. 
How to request a security code via SMS or email?
![instagram - google chrome 2018-10-15 23 17 19](https://user-images.githubusercontent.com/35338702/46976624-ac772880-d0d2-11e8-807c-0d70da3c3b6f.png)

**Comment by mgp25** [comment]
We haven't implemented the checkpoint function and we won't implemented either.

Regards

**Comment by wolrd** [comment]
@mgp25 thanks!
