### ISSUE TITLE
Push notifications issue

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2282]
Hi. Im trying to setup push notifications in two ways.
First way is to run them from console script, but Im getting an error like 
      
    Type error: Argument 4 passed to InstagramAPI\Push\Fbns::__construct() must be an instance of 
    InstagramAPI\Devices\DeviceInterface, null given

Another way is to run them in web, and, of course, Im getting an error 

    Uncaught InvalidArgumentException: Recursion detected in /Users/hellenmicky/www/insta/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71

Code:

    class PushService
    {
    /**
     * Имя логгера
     *
     * @const
     */
    const LOGGER_NAME = 'push';

    /**
     * @var ExtEventLoop|LibEventLoop|LibEvLoop|StreamSelectLoop
     */
    private $loop;

    /**
     * @var Push
     */
    private $push;

    /**
     * PushService constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->loop = Factory::create();
    }

    /**
     * @param Instagram $client
     * @param bool $debug
     * @return PushService
     * @throws \Exception
     */
    public function createPushInstance(Instagram $client, bool $debug): self
    {
        $this->push = new Push($this->loop, $client, $this->getLogger($debug));
        return $this;
    }

    /**
     * Запуск ивентов
     *
     * @return void
     */
    public function startEvents(): void
    {
        $this->push->start();
        $this->loop->run();
    }

    /**
     * Остановка ивентов
     *
     * @return void
     */
    public function stopEvents(): void
    {
        $this->push->stop();
        $this->loop->stop();
    }

    /**
     * Отлов входящих ивентов
     *
     * @return PushService
     */
    public function setOnIncomingEvent(): self
    {
        $this->push->on('incoming', function (Notification $push) {
            printf('%s%s', $push->getMessage(), PHP_EOL);
        });

        return $this;
    }
    ... // Other events

Call:

    (new PushService())
            ->createPushInstance($this, true)
            ->setOnIncomingEvent()
            ->setOnLikeEvent()
            ->setOnCommentEvent()
            ->setOnDirectEvent()
            ->setOnErrorEvent()
            ->startEvents();

Can you explain please how to setup pushes?

**Comment by valga** [comment]
@AndManowar We already have a fully working push example - https://github.com/mgp25/Instagram-API/blob/2519c5f41b46fb980b3e3bd02e585a2fb8fb3e4f/examples/pushReceiver.php
