### ISSUE TITLE
how to get full_name from profile?

### ISSUE THREAD

**Issue by miller1702** [mgp25/Instagram-API#2288]
how to get full_name or other data from profile
$ig->account->getCurrentUser()->full_name doesn't works

**Comment by Tridenn** [comment]
If you make var_dump ($ ig-> account-> getCurrentUser ()), you will notice that the object is returned to you.
$i->account->getCurrentUser()->getUser()->getFullName()

**Comment by miller1702** [comment]
it works thnx
