### ISSUE TITLE
Debug as JSON

### ISSUE THREAD

**Issue by derjrjr** [mgp25/Instagram-API#229]
Hello,
Would it be possible to use the debug as JSON to parse arrays?
I tried using the debug option as JSON but it doesnt work, could you say how to do this or possibly add it in? I want to be able to parameters such as sucess etc to see if what ever I was trying to do worked without going through whole JSON debug response and make more user friendly.

Regards

**Comment by RageBrahimi** [comment]
Could you define 'it doesnt work', because the debug is returned as a JSON. 

```javascript

        if ($this->debug) {
            echo "REQUEST: $endpoint\n";
            if (!is_null($post)) {
                if (!is_array($post)) {
                    echo 'DATA: '.urldecode($post)."\n";
                }
            }
            echo "RESPONSE: $body\n\n";
        }
```

**Comment by derjrjr** [comment]
Yes, I know it is returned as JSON but I am unable to define the debug option as a variable to work with and parse

`
require '../src/Instagram.php';
/////// CONFIG ///////
$username = 'exms7ysq2s';
$password = 'UeALADNI';
$debug = "true";

$photo = 'https://scontent.cdninstagram.com/t51.2885-15/s150x150/e35/c181.0.718.718/13108697_965936313505138_565178000_n.jpg';     // path to the photo
$caption = 'caption!';     // caption
//////////////////////
$i = new Instagram($username, $password, $debug);

try {
    $i->login();
} catch (InstagramException $e) {
    $e->getMessage();
    exit();
}

try {
    $i->uploadPhoto($photo, $caption);
} catch (Exception $e) {
    echo $e->getMessage();
}
`

You cannot parse the $debug as when it is equal to true it just displays and cannot parse, to what I found.

Reegards

**Comment by RageBrahimi** [comment]
Then make what you're doing a variable.

```javascript
try {
    $imageUpload = $i->uploadPhoto($photo, $caption);
} catch (Exception $e) {
    echo $e->getMessage();
}
```
Then use `$imageUpload['status']` for example to get status.
