### ISSUE TITLE
How to get following user list from activity?

### ISSUE THREAD

**Issue by n-eliseev** [mgp25/Instagram-API#2290]
Hello!

How can I get a list of user who following to me:
![](http://nelis.ru/screen/2018-10-19_144314.png)

If I create request:
```php
$res=$ig->people->getRecentActivityInbox();
print_r($res);
```

Responce contain only last following user and text:
![](http://nelis.ru/screen/2018-10-19_145347.png)

**Comment by mgp25** [comment]
The API is based on the Android app, so only references and features from Android will be valid. In this case you are posting something from Instagram Web, and that info is not relevant.

Regards

**Comment by n-eliseev** [comment]
This list is in the mobile application. I can't figure out what request to see it.
![](https://e.apk.plus/screenshots/3/d/8/com.goldenstone.instapics_7.png)

**Comment by n-eliseev** [comment]
> 
> 
> The API is based on the Android app, so only references and features from Android will be valid. In this case you are posting something from Instagram Web, and that info is not relevant.
> 
> Regards

This list is in the mobile application. I can't figure out what request to see it.
![](https://e.apk.plus/screenshots/3/d/8/com.goldenstone.instapics_7.png)
