### ISSUE TITLE
CURL error 61

### ISSUE THREAD

**Issue by xavdep** [mgp25/Instagram-API#2292]
Hi all,

When I try to login (may be I have try  with to login too many times with too much user/password  combination) I get this error:

> Something went wrong: Network: CURL error 61: Error while processing content unencoding: Unknown failure within decompression software. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

Have some ideas of the origin of problem? May be so many try of login ?

Thanks

**Comment by Tridenn** [comment]
Hello, use you proxy?

**Comment by xavdep** [comment]
No proxy, may be I should?

**Comment by xavdep** [comment]
I think it's insta server problem, I close issue
