### ISSUE TITLE
How to avoid "consent_required"

### ISSUE THREAD

**Issue by AtCliffUnderline** [mgp25/Instagram-API#2293]
I'm so sorry, i'm really bad in English, so I haven't found anything in FAQ or closed issues. 
When I tested this API from mac OS terminal on my home mac it is easily posting photos, but when i uploaded everything on my hosting and run the same script, it throws "consent_required" like:
`RESPONSE: {"message": "consent_required", "consent_data": {"headline": "Updates to Our Terms and Data Policy", "content": "We've updated our Terms and made some changes to our Data Policy. Please take a moment to review these changes and let us know that you agree to them.\n\nYou need to finish reviewing this information before you can use Instagram.", "button_text": "Review Now"}, "status": "fail"}`

What should I do to avoid that? Thanks a lot for patience.

**Comment by mgp25** [comment]
Login with your device, accept new terms and select that you are over 18. After that, this message will be gone.

Regards

**Comment by AtCliffUnderline** [comment]
I have logged in via both desktop and phone app, nothing appeared :(

**Comment by AtCliffUnderline** [comment]
> Login with your device, accept new terms and select that you are over 18. After that, this message will be gone.
> 
> Regards

I have logged in via both desktop and phone app, nothing appeared :(

**Comment by Tridenn** [comment]
@AtCliffUnderline, you have not solved the problem?

**Comment by igorbelikov** [comment]
+1
