### ISSUE TITLE
What is it zero rating?

### ISSUE THREAD

**Issue by rostyslav-matushkin** [mgp25/Instagram-API#2297]
What is meant zero rating? What does it affect? How and when I should use it?
What is happening in the class ZeroRating in "reset" and "rewrite" functions?
I write a library on Java and try to understand php syntax :)

**Comment by zzet** [comment]
You need the zero rating (if you don't want to have any problems with login flow and some requests). What about the `zero rating` term - you can `google` them for the understanding of a idea :)

**Comment by zzet** [comment]
@mgp25 `A gift from heaven` sounds well :)
