### ISSUE TITLE
returned a result with an error set.

### ISSUE THREAD

**Issue by Tridenn** [mgp25/Instagram-API#2298]
<built-in method cancelled of  asyncio.Future object at 0x7f5a478be208> returned a result with an error set.

Hello, who else faced this question? It happens rarely and the logs I did not manage to track down, returns from here:
Exception / ServerMessageThrower.php
Tell me what it can be connected with, I'll try to fix it myself, in version 4 this was not.

**Comment by mgp25** [comment]
We can't do anything without any debug log or reproduce steps. Open a new issue when you can documentate this
