### ISSUE TITLE
does story emoji work?

### ISSUE THREAD

**Issue by GoldenEagle66** [mgp25/Instagram-API#2299]
Hello, I am wondering if your library supports story interactions?
![image](https://user-images.githubusercontent.com/17871694/47446621-4c643e80-d7c4-11e8-855b-7ad65c0a16b1.png)
If so, how does it work? And where to look

**Comment by mgp25** [comment]
You need to manually draw them into the image.

Regards

**Comment by GoldenEagle66** [comment]
> You need to manually draw them into the image.
> 
> Regards

No, I want to send an emotion to another user in his story

**Comment by GoldenEagle66** [comment]
> You need to manually draw them into the image.
> 
> Regards

when I watch someone else's story and click on the screen, they appear
![image](https://user-images.githubusercontent.com/17871694/47447054-4de23680-d7c5-11e8-8ccd-13d93a0cdb26.png)
user sees it like this
