### ISSUE TITLE
Can't upload videos

### ISSUE THREAD

**Issue by CreaDEV** [mgp25/Instagram-API#23]
Hi,

with the app I'm able to upload videos.I tried to upload a video with uploadPhoto() but it fails with the message: 
RESPONSE: {"status":"fail","message":"Uploaded image isn't in the right format"}

Ca you implement an uploadVideo method?

**Comment by mgp25** [comment]
@CreaDEV why are you trying to upload a video using `uploadPhoto` ? the function name is explicit enough i guess.

I dont know if i'll ever add this feature, maybe some day or maybe not. I did this API for myself, just to upload my photos, so i dont know.
