### ISSUE TITLE
Get mediaId to send media using Instagram Direct

### ISSUE THREAD

**Issue by hydefus** [mgp25/Instagram-API#2300]
Hi, I was wondering if this api has a mechanism to upload to Instagram a HTTP hosted image and automatically get the mediaId to use:

$ig->direct->sendPost($recipients, $mediaId);

If not, Does this api have a method to get the mediaID using an image from a byte array ?

Thanks

**Comment by mgp25** [comment]
Hello,

Yes, you can get the `mediaId` in the upload's response. You can't upload images from urls, you will need to have the file

Regards
