### ISSUE TITLE
How i get all replies from all comments?

### ISSUE THREAD

**Issue by sinhoshow** [mgp25/Instagram-API#2305]
I need to get all comments, including comment replies. If possible, a code example to explain better. I saw the getCommentReplies() method, but i don't know how use it.

**Comment by rishabhdugar** [comment]
hi @sinhoshow , i need some help setting this up in hostgator, can you help me , i am getting this issue Warning: require(/home4/nyisoethet/public_html/instagram-test/api/examples/../vendor/autoload.php): failed to open stream: No such file or directory in /home4/nyisoethet/public_html/instagram-test/api/examples/twoFactorLogin.php on line 6
