### ISSUE TITLE
FFmpeg Errors

### ISSUE THREAD

**Issue by akula22** [mgp25/Instagram-API#2309]
["Unrecognized option 'preset'."], ["Error splitting the argument list: Option not found"], Command: "-y  -i .....
-vf 'crop=w=136:h=170:x=0:y=0,scale=w=480:h=600,pad=w=480:h=600:x=0:y=0:color=0xFFFFFF' -metadata:s:v rotate="" -f mp4 -c:v libx264 -preset fast -crf 24 -c:a copy '/tmp/INSTAVID_nazqZP'

**Comment by mgp25** [comment]
Hello @akula22,

Not API issue, check your ffmpeg

Regards
