### ISSUE TITLE
getting the next "page" at searchUsers($query)

### ISSUE THREAD

**Issue by mkanker** [mgp25/Instagram-API#231]
Does anyone know how to get the second part of this result? Because sometimes we got a result with the node saying: "has_more = true", but it doesn't have the nextMaxId or something like it.

**Comment by RageBrahimi** [comment]
Try this
```javascript
  /**
   * Search users.
   *
   * @param string $query
   *
   * @return array
   *   query data
   */
  public function searchUsers($query, $maxid = null)
  {
      if (is_null($maxid)) {
          $endpoint = $this->request('users/search/?ig_sig_key_version='.Constants::SIG_KEY_VERSION."&is_typeahead=true&query=$query&rank_token=$this->rank_token")[1];
      } else {
          $endpoint = $this->request('users/search/?max_id=".$maxid."&ig_sig_key_version='.Constants::SIG_KEY_VERSION."&is_typeahead=true&query=$query&rank_token=$this->rank_token")[1];
      }

      $query = $this->request($endpoint)[1];
      if ($query['status'] != 'ok') {
          throw new InstagramException($query['message']."\n");
          return;
      }
      return $query;

  }
```

FYI `$maxid` is something like `next_max_id`, or similar! I don't know precisely as I haven't run the endpoint before. [Here](https://github.com/mgp25/Instagram-API/issues/200) is more info

**Comment by mkanker** [comment]
@RageBrahimi this return didn't send a next_max_id as the others request, that's the issue.

**Comment by RageBrahimi** [comment]
@mkanker Okay, unfortunately, that's not something that we can fix. It seems the `num_results` is defaulted to 51 and there is no `next_max_id`.
```javascript
 {
  	"has_more": true,
  	"status": "ok",
  	"num_results": 51,
}
```

**Comment by mkanker** [comment]
I'm sorry, @RageBrahimi.
Actually, I was checking in the Instagram and even Instagram doesn't work like that. It shows only the 51 results too, so for me it's good enough, it's not our fault ;)
