### ISSUE TITLE
Error when storageConfig is passed to API

### ISSUE THREAD

**Issue by joshuachinemezu** [mgp25/Instagram-API#2310]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Example Code:

```<?php

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__ . '/../vendor/autoload.php';

/////// CONFIG ///////
$username = 'myusername';
$password = 'mypassword';
$debug = true;
$truncatedDebug = false;
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug,[
    'storage'    => 'mysql',
    'dbhost'     => 'localhost',
    'dbname'     => 'mydb',
    'dbusername' => 'root',
    'dbpassword' => '',
]);

try {
    $loginResponse = $ig->login($username, $password);

    if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()) {
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();

        // The "STDIN" lets you paste the code via terminal for testing.
        // You should replace this line with the logic you want.
        // The verification code will be sent by Instagram via SMS.
        $verificationCode = trim(fgets(STDIN));
        $ig->finishTwoFactorLogin($username, $password, $twoFactorIdentifier, $verificationCode);
    }
} catch (\Exception $e) {
    echo 'Something went wrong: ' . $e->getMessage() . "\n";
}

```

Error Log/var_dump:

```php
PHP Fatal error:  Uncaught InstagramAPI\Exception\SettingsException: MySQL Connection Failed: SQLSTATE[HY000] [2002] No such file or directory in /home/myname/web/project/vendor/mgp25/instagram-php/src/Settings/Storage/Components/PDOStorage.php:75
Stack trace:
#0 /home/myname/web/project/vendor/mgp25/instagram-php/src/Settings/StorageHandler.php(142): InstagramAPI\Settings\Storage\Components\PDOStorage->openLocation(Array)
#1 /home/myname/web/project/vendor/mgp25/instagram-php/src/Settings/Factory.php(202): InstagramAPI\Settings\StorageHandler->__construct(Object(InstagramAPI\Settings\Storage\MySQL), Array, Array)
#2 /home/myname/web/project/vendor/mgp25/instagram-php/src/Instagram.php(308): InstagramAPI\Settings\Factory::createHandler(Array, Array)
#3 /home/myname/web/project/public/twoFactorLogin.1.php(16): InstagramAPI\Instagram->__construct(true, false, Array)
#4 {main}
  thrown in /home/myname/web/project/vendor/mgp25/instagram-php/src/Settings/Storage/Components/PDOStorage.php on line 75
.
```

I passed my storage configuration to the API and I ran the file from the commandline but it is giving me the error below

PHP Fatal error:  Uncaught InstagramAPI\Exception\SettingsException: MySQL Connection Failed: SQLSTATE[HY000] [2002] No such file or directory in /home/myname/web/project/vendor/mgp25/instagram-php/src/Settings/Storage/Components/PDOStorage.php:75

Please help

**Comment by mgp25** [comment]
@joshuachinemezu the data passed to storage config could be wrong. As the error says: ` MySQL Connection Failed: SQLSTATE[HY000] [2002] No such file or directory`

Regards
