### ISSUE TITLE
Expose timeout option for ffmpeg process

### ISSUE THREAD

**Issue by olee** [mgp25/Instagram-API#2312]
Feature request:
Expost the timeout option of the started FFMPEG process to allow for more than the default 60 seconds of processing time for video files.

---
Description:
The current code creates a default `Process` instance which uses a default timeout of 60 seconds.
When processing high resolution videos on hardware like a Raspberry Pi, the time to process the video is often not enough and the process fails.

This was already reported as a bug in #2196 together with a solution, however the solution requires adjusting the source code of this library for that because there is no way to extend/configure it externally to use the adjusted timeout.
This is why I propose adding a configuration option to InstagramVideo (or somewhere else) to allow setting a timeout.

**Comment by mgp25** [comment]
@olee Is this happening to you only when doing broadcasting? Because I am thinking we could modify [FFMPEG.php](https://github.com/mgp25/Instagram-API/blob/master/src/Media/Video/FFmpeg.php) in concrete the [runAsync()](https://github.com/mgp25/Instagram-API/blob/master/src/Media/Video/FFmpeg.php#L115) function with an extra argument that could be: `$timeout`

```php
   /**
     * Run a command asynchronously.
     *
     * @param string $command
     *
     * @return Process
     */
    public function runAsync(
        $command
        $timeout = null)
    {
        $fullCommand = sprintf('%s -v error %s', Args::escape($this->_ffmpegBinary), $command);
        $process = new Process($fullCommand);
        if ($timeout !== null && $timeout > 60) {
            $process->setTimeout($timeout);
        }
        $process->start();
        return $process;
    }
```

Could you try this?

**Comment by mgp25** [comment]
Anyone who ever face this error, please feel free to open this issue again. Try the code I provided above, and if it solves the issue, I will add this code to the repository.

Regards

**Comment by olee** [comment]
Hi, sorry for not replying.
This code in itself looks nice, however the issue is that I would have to patch this into the files in the vendor directory which I'd rather not do (actually this is my current workaround).
This is why I asked if this could be included as an option to pass the library somewhere so it can be properly configured and does not get reverted again when updating the library.
