### ISSUE TITLE
How to get my media?

### ISSUE THREAD

**Issue by Rux77** [mgp25/Instagram-API#2314]
Is there a way get my account's photos ?

I tried

```
$feed = $ig->highlight->getSelfUserFeed();
$items = $feed->getItems();
```
the response from instgram servers are working fine..
but why there is no items? it returns `null`

* I didn't use my account for a long time, maybe thats the problem? cuz my photos not getting highlighted?

**Comment by khanof89** [comment]
Did you try 
$ig->timeline->getSelfUserFeed();

?

**Comment by Rux77** [comment]
Yes, it works. 
sorry didn't see that.. 

thanks @mgp25 .. for this great work!
