### ISSUE TITLE
Direct

### ISSUE THREAD

**Issue by vvvrum** [mgp25/Instagram-API#2316]
Does everyone have direct requests?

**Comment by Hattshire** [comment]
Apparently Instagram's direct_v2 api was changed, the response of the request is an empty 404 from both PHP api and from Python api 😿

**Comment by Hattshire** [comment]
Now works on python side, it was only the instagram user-agent version, apparently now versions < 10.34.# are banned (it still works with _Instagram X Android..._ though)

However mgp25/Instagram-API uses IG as _64.0.0.14.96_ so there would be something I'm missing there (I've not tested yet on PHP)
```
>>> a.USER_AGENT = 'Instagram 10.33.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)'
>>> a.SendRequest("direct_v2/inbox/")
Request return 404 error!
None
False
>>> a.USER_AGENT = 'Instagram 10.34.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)'
>>> a.SendRequest("direct_v2/inbox/")
True
```

**Comment by arsalanTra** [comment]
how can i capture instagram direct requests from my instagram windows 10 app or android app who now how can i capture this things? Fiddler dose not show me these requests :( plz help me
