### ISSUE TITLE
Login to instagram do not work anymore

### ISSUE THREAD

**Issue by Ohabiballah** [mgp25/Instagram-API#2317]
Error in loging to instagram, it was all working fine until yesterday the login stop working with no exception showen it's reurn empty exception, please can someone help me or just tell me way 

**The code :** 
/////// CONFIG ///////
$username = $settings->username;
$password = $settings->password;
 			
$debug = false;
$photo = $img ;
$info  = new Info(Auth::id(), Request::get('v_id'));
$caption = $msg.' - to view more details go to '.$info->getDomain() . "/inventory/view/" .Request::get('v_id');    
$i = new Instagram($username, $password, $debug);
//Login
try {
 $i->login();
} catch (\Exception $e) {
 $output['success'] = false;
 $output['result']  = [];
 $output['message']  = $e->getMessage();
 return Response::json($output);
}

**Debug/log:**
{success: false, result: [], message: "↵"}
message: "↵"
result: []
success: false

Thank you,

**Comment by mgp25** [comment]
@Ohabiballah You haven't followed the issue template:

1) You haven't provided proper debug log
2) You are not using latest release
3) You are not formatting the issue properly with markdown
