### ISSUE TITLE
[REQUEST] Delete settings and cookies for accounts with old  last_login

### ISSUE THREAD

**Issue by 4n70w4** [mgp25/Instagram-API#2318]
It will be very useful to have the ability to delete old data from storage, for example, that were not used during the month or any desired period. Perhaps value of the last_login from the settings is suitable for a cutoff.

**Comment by mgp25** [comment]
@4n70w4 all cookies and settings are updated when logging in (if required). If any value is outdated it will be updated.

Regards

**Comment by 4n70w4** [comment]
@mgp25 you did not understand again. I need to clean the system of trash data.
I don’t want to use part of my accounts and I need to free the storage.
Why do you often close a request with an irrelevant answer?
