### ISSUE TITLE
Please help me take more comments

### ISSUE THREAD

**Issue by OdinChuvak** [mgp25/Instagram-API#2319]
Instagram-API/src/Request/Media.php in this file there is a function getComments()

public function getComments(
        $mediaId,
        array $options = [])
    {
        $request = $this->ig->request("media/{$mediaId}/comments/")
            ->addParam('can_support_threading', true);

        // Pagination.
        if (isset($options['min_id']) && isset($options['max_id'])) {
            throw new \InvalidArgumentException('You can use either "min_id" or "max_id", but not both at the same time.');
        }
        if (isset($options['min_id'])) {
            $request->addParam('min_id', $options['min_id']);
        }
        if (isset($options['max_id'])) {
            $request->addParam('max_id', $options['max_id']);
        }

        // Request specific comment (does NOT work together with pagination!).
        // NOTE: If you try pagination params together with this param, then the
        // server will reject the request completely and give nothing back!
        if (isset($options['target_comment_id'])) {
            if (isset($options['min_id']) || isset($options['max_id'])) {
                throw new \InvalidArgumentException('You cannot use the "target_comment_id" parameter together with the "min_id" or "max_id" parameters.');
            }
            $request->addParam('target_comment_id', $options['target_comment_id']);
        }

        return $request->getResponse(new Response\MediaCommentsResponse());
    }

Who can tell you how to get more than 20 comments. I don't understand how to use the next_max_id parameter that comes along with the first 20 comments.

Please, help me get all the comments.

**Comment by OdinChuvak** [comment]
the next_max_id parameter contains {"server_cursor": "QVFBOWN1a1ozTkNfLU5aaHhUd283N2YxVnNLRXN6NjRsQjJVamJidS1qUGliYlRxNTNNdTRyc19zejdLbmJfbmNRUmNuNEpFT0txUUlxaTY3d1NwaENpcWFfMTBGVlQ1ZnV6WjdYQmRzTHRiOHc=", "is_server_cursor_inverse": false}

what to do?

**Comment by RainGrid** [comment]
@OdinChuvak https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php

**Comment by OdinChuvak** [comment]
> @OdinChuvak https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php

Oh, thanks a lot. Helped!

**Comment by mgp25** [comment]
@OdinChuvak Please read wiki and examples before opening a new issue.

Regards

**Comment by RainGrid** [comment]
@mgp25 is it possible to add an example that retrieves all comments from a post (inc. replies) ?

**Comment by askingokyildiz** [comment]
Please, help me get all the comments.

**Comment by bloolight** [comment]
> the `next_max_id` parameter contains
> 
> ```json
> {"server_cursor": "QVFBOWN1a1ozTkNfLU5aaHhUd283N2YxVnNLRXN6NjRsQjJVamJidS1qUGliYlRxNTNNdTRyc19zejdLbmJfbmNRUmNuNEpFT0txUUlxaTY3d1NwaENpcWFfMTBGVlQ1ZnV6WjdYQmRzTHRiOHc=", "is_server_cursor_inverse": false}
> ```
> 
> what to do?


Hi @OdinChuvak , seems like you've figured out this issue.

But, I am getting same response when call `$maxId = $response->getNextMaxId();`
In your case, the "server_cursor" was just the $maxId?

Thanks.

**Comment by RainGrid** [comment]
@bloolight all comments except replies. $this->ig is Instagram object
`public function getMediaComments($link, &$error = NULL)
    {
        $comments = array();
	if($link[strlen($link) - 1] != '/')
		$link .= '/';
		
	if(!preg_match("/\/p\/.*\//i", $link, $match)) {
		return false;
	}
	$match[0] = substr($match[0], 3, strlen($match[0]) - 4);
	$shortcode = $match[0];
		
        $id = InstagramID::fromCode($shortcode);

        try {
            $maxId = null;
            $minId = null;
            $comments = array();

            $response = $this->ig->media->getComments($id, array());
            $comments = array_merge($comments, $response->getComments());
            $maxId = $response->getNextMaxId();
            $minId = $response->getNextMinId();
            while($maxId != null) {
                $options = array();
                $options['max_id'] = $maxId;
                $response = $this->ig->media->getComments($id, $options);
                $comments = array_merge($comments, $response->getComments());
                $maxId = $response->getNextMaxId();
                sleep(1);
            }
            while($minId != null) {
                $options = array();
                $options['min_id'] = $minId;
                $response = $this->ig->media->getComments($id, $options);
                $comments = array_merge($comments, $response->getComments());
                $minId = $response->getNextMinId();
                sleep(1);
            }
        } catch (\Exception $e) {
        }
        return $comments;
    }`

@bloolight replies
`public function getApiMediaCommentReplies($media_id, $comment_id, $options = array())
    {
        $comments = array();
        try {
            $parentCommentResponse = $this->ig->media->getComments($media_id, ['target_comment_id' => $comment_id]);
            sleep(1);
            $parentComments = $parentCommentResponse->getComments();
            $parentComment = null;
            foreach ($parentComments as $curComment) {
                if ($curComment->getPk() == $comment_id) {
                    $parentComment = $curComment;
                    break;
                }
            }
            if ($parentComment) {
                $previewComments = $parentComment->getPreviewChildComments();
                $commentsCount = $parentComment->getChildCommentCount();
                if ($commentsCount > 0) {
                    $comments = $previewComments;
                    if ($commentsCount > count($previewComments)) {
                        $maxId = $parentComment->getNextMaxChildCursor();
                        $minId = $parentComment->getNextMinChildCursor();
                        while($maxId != null) {
                            $options = array();
                            $options['max_id'] = $maxId;
                            $repliesResponse = $this->ig->media->getCommentReplies($media_id, $comment_id, $options);
                            $comments = array_merge($comments, $repliesResponse->getChildComments());
                            $maxId = $repliesResponse->getNextMaxChildCursor();
                            sleep(1);
                        }
                        while($minId != null) {
                            $options = array();
                            $options['min_id'] = $minId;
                            $repliesResponse = $this->ig->media->getCommentReplies($media_id, $comment_id, $options);
                            $comments = array_merge($comments, $repliesResponse->getChildComments());
                            $minId = $repliesResponse->getNextMinChildCursor();
                            sleep(1);
                        }
                    }
                }
            }
            
        } catch (\Exception $e) {
            return $comments;
        }
        sleep(1);
        return $comments;
    }`

**Comment by RainGrid** [comment]
@bloolight replies
`public function getApiMediaCommentReplies($media_id, $comment_id, $options = array())
    {
        $comments = array();
        try {
            $parentCommentResponse = $this->ig->media->getComments($media_id, ['target_comment_id' => $comment_id]);
            sleep(1);
            $parentComments = $parentCommentResponse->getComments();
            $parentComment = null;
            foreach ($parentComments as $curComment) {
                if ($curComment->getPk() == $comment_id) {
                    $parentComment = $curComment;
                    break;
                }
            }
            if ($parentComment) {
                $previewComments = $parentComment->getPreviewChildComments();
                $commentsCount = $parentComment->getChildCommentCount();
                if ($commentsCount > 0) {
                    $comments = $previewComments;
                    if ($commentsCount > count($previewComments)) {
                        $maxId = $parentComment->getNextMaxChildCursor();
                        $minId = $parentComment->getNextMinChildCursor();
                        while($maxId != null) {
                            $options = array();
                            $options['max_id'] = $maxId;
                            $repliesResponse = $this->ig->media->getCommentReplies($media_id, $comment_id, $options);
                            $comments = array_merge($comments, $repliesResponse->getChildComments());
                            $maxId = $repliesResponse->getNextMaxChildCursor();
                            sleep(1);
                        }
                        while($minId != null) {
                            $options = array();
                            $options['min_id'] = $minId;
                            $repliesResponse = $this->ig->media->getCommentReplies($media_id, $comment_id, $options);
                            $comments = array_merge($comments, $repliesResponse->getChildComments());
                            $minId = $repliesResponse->getNextMinChildCursor();
                            sleep(1);
                        }
                    }
                }
            }
            
        } catch (\Exception $e) {
            return $comments;
        }
        sleep(1);
        return $comments;
    }`

**Comment by bloolight** [comment]
@RainGrid Thanks for your response on my question. Really appreciate it.

I believe the above code samples are great for me and another developers who is going to get all comments and replies. That's perfect, actually. 💯 

Here is one more problem I'd like to figure out in getting comments, and would love to hear your thoughts if possible.

So, when I try to get the $maxId, I am getting some array value very rarely.  Tbh, I expected to get a string as a $maxId value, but I got the following value in my previous try.

```PHP
{
 "server_cursor":"QVFCakZPc2xKRVZQYzJyVHRfdnFuNG1KU3NBd1FPbUxfS241M0xIZnV6UG9SeVNtbEM4bHpNOVNCdURZY2JKeGlGLTN3MGE1eEl5T0djLVFES0FCTk53TQ==", 
 "is_server_cursor_inverse": false
}
```

So I was wondering if this is some kinds of new exception or else.
I know this might not happened on your side yet, but please let me know if you have any clue on this issue.

Regards!

**Comment by RainGrid** [comment]
@bloolight I've never seen this before. Is this a correct id?

**Comment by bloolight** [comment]
Yes, right.

**Comment by RainGrid** [comment]
@bloolight looks like IG exception. We can just check the type of the variable for now.

**Comment by RainGrid** [comment]
@bloolight Can you tell me which type has this value?

> {
"server_cursor":"QVFCakZPc2xKRVZQYzJyVHRfdnFuNG1KU3NBd1FPbUxfS241M0xIZnV6UG9SeVNtbEM4bHpNOVNCdURZY2JKeGlGLTN3MGE1eEl5T0djLVFES0FCTk53TQ==", 
 "is_server_cursor_inverse": false
}
