### ISSUE TITLE
How do I check if a user or post exists by their user_id or media_id?

### ISSUE THREAD

**Issue by OdinChuvak** [mgp25/Instagram-API#2323]
Hi. I save to the database user_id of users and media_id of posts to use them in the future. However, if a user deletes their account or post, instagram api requests do not work for deleted objects.

How can I pre-check if there is an account or post by user_id or media_id?

**Comment by OdinChuvak** [comment]
Hi. I save to the database user_id of users and media_id of posts to use them in the future. However, if a user deletes their account or post, instagram api requests do not work for deleted objects.

How can I pre-check if there is an account or post by user_id or media_id?

**Comment by bolds07** [comment]
load user info by id and media info by id and see if it returns error

your post is tottally out of standard here, you didn't read the wiki... it is going to be closed

**Comment by mgp25** [comment]
Use the search function to check wether the user exists or not. Once then you can iterate on the user feed to check if the stored mediaID is the same.

Please, follow issue templates.

Regards
