### ISSUE TITLE
Help please.. InstagramAPI\Response\TimelineFeedResponse: Consent required

### ISSUE THREAD

**Issue by testing1912** [mgp25/Instagram-API#2327]
I am getting an error in the mgp25 Instagram API. When I run the application on localhost, there is no problem, but when I get to the paid host, I get the following error.:

`InstagramAPI\Response\TimelineFeedResponse: Consent required`

**Comment by testing1912** [comment]
@mgp25

**Comment by mgp25** [comment]
You should verify and agree terms using your mobile device. But just to avoid similar questions, I'll post the code to do this with the API.

```php
 public function agreeConsentFirstStep()
    {
        return $this->ig->request('consent/existing_user_flow/')
            ->setNeedsAuth(false)
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_uuid', $this->ig->uuid)
            ->getResponse(new Response\GenericResponse());
    }

    public function agreeConsentSecondStep()
    {
        return $this->ig->request('consent/existing_user_flow/')
            ->setNeedsAuth(false)
            ->addPost('current_screen_key', 'qp_intro')
            ->addPost('updates', ['existing_user_intro_state' => '2'])
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_uuid', $this->ig->uuid)
            ->getResponse(new Response\GenericResponse());
    }

    public function agreeConsentThirdStep()
    {
        return $this->ig->request('consent/existing_user_flow/')
            ->setNeedsAuth(false)
            ->addPost('current_screen_key', 'tos_and_two_age_button')
            ->addPost('updates', ['age_consent_state' => '2', 'tos_data_policy_consent_state' => '2'])
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_uuid', $this->ig->uuid)
            ->getResponse(new Response\GenericResponse());
    }
```

**Comment by Tridenn** [comment]
@mgp25 
Do they need to be performed in turn?

**Comment by mgp25** [comment]
@Tridenn yes

**Comment by testing1912** [comment]
> @Tridenn yes

Do we need to define these methods in the TimelineFeedResponse class?

**Comment by testing1912** [comment]
> @mgp25
> Do they need to be performed in turn?
Hey bro, Do we need to define these methods in the TimelineFeedResponse class?

**Comment by amirwwe619** [comment]
> 
> 
> You should verify and agree terms using your mobile device. But just to avoid similar questions, I'll post the code to do this with the API.
> 
> ```
>  public function agreeConsentFirstStep()
>     {
>         return $this->ig->request('consent/existing_user_flow/')
>             ->setNeedsAuth(false)
>             ->addPost('_csrftoken', $this->ig->client->getToken())
>             ->addPost('_uid', $this->ig->account_id)
>             ->addPost('_uuid', $this->ig->uuid)
>             ->getResponse(new Response\GenericResponse());
>     }
> 
>     public function agreeConsentSecondStep()
>     {
>         return $this->ig->request('consent/existing_user_flow/')
>             ->setNeedsAuth(false)
>             ->addPost('current_screen_key', 'qp_intro')
>             ->addPost('updates', ['existing_user_intro_state' => '2'])
>             ->addPost('_csrftoken', $this->ig->client->getToken())
>             ->addPost('_uid', $this->ig->account_id)
>             ->addPost('_uuid', $this->ig->uuid)
>             ->getResponse(new Response\GenericResponse());
>     }
> 
>     public function agreeConsentThirdStep()
>     {
>         return $this->ig->request('consent/existing_user_flow/')
>             ->setNeedsAuth(false)
>             ->addPost('current_screen_key', 'tos_and_two_age_button')
>             ->addPost('updates', ['age_consent_state' => '2', 'tos_data_policy_consent_state' => '2'])
>             ->addPost('_csrftoken', $this->ig->client->getToken())
>             ->addPost('_uid', $this->ig->account_id)
>             ->addPost('_uuid', $this->ig->uuid)
>             ->getResponse(new Response\GenericResponse());
>     }
> ```

Hey, Where should we call this functions?

**Comment by tcz** [comment]
Unfortunately this is not working anymore.

```
public function create() : Instagram
    {
        $this->ig = new Instagram();

        try {
            $this->ig->login($this->username, $this->password);
        } catch (ConsentRequiredException $e) {
            sleep(1);
            $this->agreeConsentFirstStep();

            sleep(1);
            $this->agreeConsentSecondStep();

            sleep(1);
            $this->agreeConsentThirdStep();

            sleep(1);
            $this->ig->login($this->username, $this->password);
        }

        return $this->ig;
    }

    public function agreeConsentFirstStep()
    {
        $response = new Response\GenericResponse();
        $this->ig->request('consent/existing_user_flow/')
            ->setNeedsAuth(false)
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_uuid', $this->ig->uuid)
            ->getResponse($response);
    }

    public function agreeConsentSecondStep()
    {
        return $this->ig->request('consent/existing_user_flow/')
            ->setNeedsAuth(false)
            ->addPost('current_screen_key', 'qp_intro')
            ->addPost('updates', ['existing_user_intro_state' => '1'])
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_uuid', $this->ig->uuid)
            ->getResponse(new Response\GenericResponse());
    }

    public function agreeConsentThirdStep()
    {
        return $this->ig->request('consent/existing_user_flow/')
            ->setNeedsAuth(false)
            ->addPost('current_screen_key', 'tos_and_two_age_button')
            ->addPost('updates', ['age_consent_state' => '2', 'tos_data_policy_consent_state' => '2'])
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_uuid', $this->ig->uuid)
            ->getResponse(new Response\GenericResponse());
    }
```

Getting the following exception:


```
In ServerMessageThrower.php line 190:
                                                          
  [InstagramAPI\Exception\BadRequestException]            
  InstagramAPI\Response\GenericResponse: Request failed.  
                                                          

Exception trace:
 InstagramAPI\Exception\ServerMessageThrower::autoThrow() at /web/vendor/mgp25/instagram-php/src/Client.php:579
 InstagramAPI\Client->mapServerResponse() at /web/vendor/mgp25/instagram-php/src/Request.php:832
 InstagramAPI\Request->getResponse() at /web/src/AppBundle/Service/SocialMedia/InstagramFactory.php:70
 AppBundle\Service\SocialMedia\InstagramFactory->agreeConsentSecondStep() at /web/src/AppBundle/Service/SocialMedia/InstagramFactory.php:36
 AppBundle\Service\SocialMedia\InstagramFactory->create() at /web/var/cache/dev/ContainerX6mqyht/getUls_InstagramService.php:8
 require() at /web/var/cache/dev/ContainerX6mqyht/appDevDebugProjectContainer.php:2010
 ContainerX6mqyht\appDevDebugProjectContainer->load() at /web/var/cache/dev/ContainerX6mqyht/getUls_InstagramFollowerCountUpdaterService.php:8
 require() at /web/var/cache/dev/ContainerX6mqyht/appDevDebugProjectContainer.php:2010
 ContainerX6mqyht\appDevDebugProjectContainer->load() at /web/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:304
 Symfony\Component\DependencyInjection\Container->get() at /web/src/AppBundle/Command/InstagramFollowerCountUpdaterCommand.php:23
 AppBundle\Command\InstagramFollowerCountUpdaterCommand->execute() at /web/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /web/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at /web/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /web/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /web/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /web/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /web/bin/console:27
```

**Comment by Pezhvak** [comment]
> Unfortunately this is not working anymore.
> 
> ```
> public function create() : Instagram
>     {
>         $this->ig = new Instagram();
> 
>         try {
>             $this->ig->login($this->username, $this->password);
>         } catch (ConsentRequiredException $e) {
>             sleep(1);
>             $this->agreeConsentFirstStep();
> 
>             sleep(1);
>             $this->agreeConsentSecondStep();
> 
>             sleep(1);
>             $this->agreeConsentThirdStep();
> 
>             sleep(1);
>             $this->ig->login($this->username, $this->password);
>         }
> 
>         return $this->ig;
>     }
> 
>     public function agreeConsentFirstStep()
>     {
>         $response = new Response\GenericResponse();
>         $this->ig->request('consent/existing_user_flow/')
>             ->setNeedsAuth(false)
>             ->addPost('_csrftoken', $this->ig->client->getToken())
>             ->addPost('_uid', $this->ig->account_id)
>             ->addPost('_uuid', $this->ig->uuid)
>             ->getResponse($response);
>     }
> 
>     public function agreeConsentSecondStep()
>     {
>         return $this->ig->request('consent/existing_user_flow/')
>             ->setNeedsAuth(false)
>             ->addPost('current_screen_key', 'qp_intro')
>             ->addPost('updates', ['existing_user_intro_state' => '1'])
>             ->addPost('_csrftoken', $this->ig->client->getToken())
>             ->addPost('_uid', $this->ig->account_id)
>             ->addPost('_uuid', $this->ig->uuid)
>             ->getResponse(new Response\GenericResponse());
>     }
> 
>     public function agreeConsentThirdStep()
>     {
>         return $this->ig->request('consent/existing_user_flow/')
>             ->setNeedsAuth(false)
>             ->addPost('current_screen_key', 'tos_and_two_age_button')
>             ->addPost('updates', ['age_consent_state' => '2', 'tos_data_policy_consent_state' => '2'])
>             ->addPost('_csrftoken', $this->ig->client->getToken())
>             ->addPost('_uid', $this->ig->account_id)
>             ->addPost('_uuid', $this->ig->uuid)
>             ->getResponse(new Response\GenericResponse());
>     }
> ```
> 
> Getting the following exception:
> 
> ```
> In ServerMessageThrower.php line 190:
>                                                           
>   [InstagramAPI\Exception\BadRequestException]            
>   InstagramAPI\Response\GenericResponse: Request failed.  
>                                                           
> 
> Exception trace:
>  InstagramAPI\Exception\ServerMessageThrower::autoThrow() at /web/vendor/mgp25/instagram-php/src/Client.php:579
>  InstagramAPI\Client->mapServerResponse() at /web/vendor/mgp25/instagram-php/src/Request.php:832
>  InstagramAPI\Request->getResponse() at /web/src/AppBundle/Service/SocialMedia/InstagramFactory.php:70
>  AppBundle\Service\SocialMedia\InstagramFactory->agreeConsentSecondStep() at /web/src/AppBundle/Service/SocialMedia/InstagramFactory.php:36
>  AppBundle\Service\SocialMedia\InstagramFactory->create() at /web/var/cache/dev/ContainerX6mqyht/getUls_InstagramService.php:8
>  require() at /web/var/cache/dev/ContainerX6mqyht/appDevDebugProjectContainer.php:2010
>  ContainerX6mqyht\appDevDebugProjectContainer->load() at /web/var/cache/dev/ContainerX6mqyht/getUls_InstagramFollowerCountUpdaterService.php:8
>  require() at /web/var/cache/dev/ContainerX6mqyht/appDevDebugProjectContainer.php:2010
>  ContainerX6mqyht\appDevDebugProjectContainer->load() at /web/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:304
>  Symfony\Component\DependencyInjection\Container->get() at /web/src/AppBundle/Command/InstagramFollowerCountUpdaterCommand.php:23
>  AppBundle\Command\InstagramFollowerCountUpdaterCommand->execute() at /web/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:251
>  Symfony\Component\Console\Command\Command->run() at /web/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:964
>  Symfony\Component\Console\Application->doRunCommand() at /web/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /web/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:248
>  Symfony\Component\Console\Application->doRun() at /web/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /web/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
>  Symfony\Component\Console\Application->run() at /web/bin/console:27
> ```

try this (tested with instagram v100.0.0.17.129)

```
public function agreeConsentFirstStep()
    {
        $this->ig->request('consent/existing_user_flow/')
            ->setNeedsAuth(false)
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_uuid', $this->ig->uuid)
            ->getRawResponse();
    }

    public function agreeConsentSecondStep()
    {
        return $this->ig->request('consent/existing_user_flow/')
            ->setNeedsAuth(false)
            ->addPost('current_screen_key', 'dob')
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('day', 5)
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('day', 1994)
            ->addPost('_uuid', $this->ig->uuid)
            ->addPost('month', 7)
            ->getRawResponse();
    }
```

i will investigate more on this, but it might worth checking the response of the agreeConsentFirstStep() method. what i get is:
`{"screen_key": "dob", "contents": {"dob": {"consent_key": "dob", "content_type": "text", "headline": "Enter Your Date of Birth", "paragraphs": [{"text": "Your age affects the resources we offer and the way we use your data for ads.", "style": "paragraph"}], "optional_paragraphs": [], "age": 25, "today": "2019-07-05"}}, "primary_button_text": "Submit", "status": "ok"}`

as you can see the screen_key is 'dob' (date of birth). meh, maybe they require something else (which i don't know what that might be), in that case you should send those two steps that @mgp25 gave you. or even chaining the responses, as you can see in my case after the second step i get this:

`{"screen_key": "finished", "status": "ok"}`

it might be possible that screen_key gives you another step to go through.
and also keep in mind that this happens when you use a virgin proxy or even changing the device.
