### ISSUE TITLE
Get Media Messages (Image)

### ISSUE THREAD

**Issue by edilson-silva** [mgp25/Instagram-API#2328]
How can i get media messages received (Image)?
I'm trying to get them but I receive a null message.

**Comment by mgp25** [comment]
@edilson-silva can you please elabotate your question? What do you mean by media messages? Comments?

**Comment by edilson-silva** [comment]
I saw that it is entirely possible to get text messages from Instagram Direct.
I'm wondering if it's possible to get media messages (Images) from Instagram Direct.

**Comment by mgp25** [comment]
Yes, I guess so. Have you tried `getInbox()`?

**Comment by mgp25** [comment]
@edilson-silva Just tried a couple minutes ago, and yes, It is possible.

Regards

**Comment by semspanhaak** [comment]
I'am excatly looking for this, currently using this code but is isn't showing all images
`try {
        
        $maxid = null;

        do{
            $response = $ig->direct->getInbox($maxId);
            $threads = $response->getInbox()->getThreads();
            foreach($threads as $thread) {
                $threadItems = $thread->getItems();
                
                foreach($threadItems as $threadItem) {
                    //print_r($threadItem->getMedia());
                    //print_r(get_class_methods($threadItem));
                    if ($threadItem->getMedia() !== null) {
                        //echo $threadItem->getMedia() . "<br/>";
                        $image = $threadItem->getMedia()->getImageVersions2()->getCandidates()[0]->getUrl();
                        echo '<img src="'.$image.'" alt="Smiley face" height="250">';
                    }
                }
            }

            $maxId = $response->getNexttCursor();
            echo $maxid;

            echo "Sleeping for 5s...\n";
            sleep(5);
        }while ($maxId !== null);

        
    } catch (\Throwable $e) {
        echo 'Something went wrong: '.$e->getMessage()."\n";
    }`
