### ISSUE TITLE
Find Unfollowed Peopel !

### ISSUE THREAD

**Issue by enghelab** [mgp25/Instagram-API#2329]
Can I find unfollowed people by using this library ?
(Assuming we have a username and password)

**Comment by bolds07** [comment]
no api will provide you that, you must build your own program for this purpose

**Comment by mgp25** [comment]
Adding to what @bolds07, we must think about the Instagram app since the API is based on it. Does the app include a function to get unfollowed people? No as far as I know.

Regards
