### ISSUE TITLE
clear white screen!

### ISSUE THREAD

**Issue by colotoon** [mgp25/Instagram-API#2330]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
its not working, every time i just got nothing(at the web browser - clean page) at the shell - no out, clean too.
if i enable debug mode - its shows me hundreds lines of json, with everything like historys, posts etc.
BUT, i just want to share 1 photo, and its not working, photo not uploading at my instagram account, no new post!

i try to use php5.6 and 7.0 - no results
composer instaled last version and its not help!
i just used last version of photoupload.php

So, how i can upload photo???

**Comment by bolds07** [comment]
you are not going to get answers if you are not providing a code to replicate your problem... there are very smart people here, but none of them are mind readers to guess what are you doing in your code while getting this error

BTW there is a pretty straight foward example of how to upload a photo in this repository

**Comment by colotoon** [comment]
lol, yep im very smarty, read again what i am told:
i just used last version of photoupload.php

read this again if u not understand where is sample of code what i use
and read again where im told about latest version im use, xD

ppl dont wanna read, u right lol

**Comment by colotoon** [comment]
this is code if u still not understand:

`<?php

include __DIR__.'/../vendor/autoload.php';
require __DIR__.'/../src/Instagram.php';

/////// CONFIG ///////
$username = 'mylogin';
$password = 'mypassword';
$debug = false;

$photo = __DIR__.'/../media/6RHR8zlV2bk.jpg';     // path to the photo
$caption = 'test';     // caption

//////////////////////

$i = new \InstagramAPI\Instagram($username, $password, $debug);

try {
    $res=$i->login();
	var_dump($res);
} catch (Exception $e) {
    $e->getMessage();
    exit();
}

try {
    $res=$i->uploadPhoto($photo, $caption);
	var_dump($res);
} catch (Exception $e) {
    echo $e->getMessage();
}
`

**Comment by mgp25** [comment]
Issue doesn't follow the proper format. Therefore is considered as invalid. This is not an API issue. Please use examples.

Regards

**Comment by colotoon** [comment]
realy??? its api issue!!!!
ur API not working!!!
and im use ur fucking examples - its not working!!!
u stupid or what????
make working api or delete this shit from GIT!!!
will be reported about u and ur project, and about useless support too!

**Comment by mgp25** [comment]
@colotoon you clearly haven't used any example. Anyway, we don't tolerate such behaviors. If you don't respect people, you won't have place here. I am sorry, but I am going to block you.

Recommendation: Read
