### ISSUE TITLE
uploadPhoto.php error

### ISSUE THREAD

**Issue by instacounter** [mgp25/Instagram-API#2332]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

![issue](https://user-images.githubusercontent.com/44951539/48317836-63929100-e5f8-11e8-89c2-4c92e7006bd7.png)

### Describe your issue

Hi, I'm using the uploadPhoto.php example, but I can not make it work.
I get the following error:

```
Notice: Undefined index: following in C:\xampp\htdocs\instagram\vendor\mgp25\instagram-php\src\http\Response\Objects\FriendshipStatus.php on line 18

Notice: Undefined index: following in C:\xampp\htdocs\instagram\vendor\mgp25\instagram-php\src\http\Response\Objects\FriendshipStatus.php on line 18
```

**Comment by mgp25** [comment]
Are you using latest source code/release? If so, can you post the debug log provided by the API?

**Comment by mgp25** [comment]
Please, you the examples we provided.

Regards

**Comment by instacounter** [comment]
Por favor, de verdad que lo he intentado y me he leído todo, pero es que no me funciona.
Me salta siempre el mismo error:
Notice: Undefined index: following in C:\xampp\htdocs\instagram\vendor\mgp25\instagram-php\src\http\Response\Objects\FriendshipStatus.php on line 18

Notice: Undefined index: following in C:\xampp\htdocs\instagram\vendor\mgp25\instagram-php\src\http\Response\Objects\FriendshipStatus.php on line 18
Something went wrong:
