### ISSUE TITLE
Send Image via Instagram Direct.

### ISSUE THREAD

**Issue by edilson-silva** [mgp25/Instagram-API#2333]
How to send image via direct?

I've already tried the sendPostToDirect() method from Realtime,
however I'm getting 500 (Internal Server Error).

**Comment by mgp25** [comment]
Issue doesn't follow the proper format. Therefore is considered as invalid.

Related: https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-the-500-http-error-code-mean

Regards
