### ISSUE TITLE
How can I get Media created time?

### ISSUE THREAD

**Issue by lolka02** [mgp25/Instagram-API#2334]
How can I get Media created time?  
```
$ig->media->getInfo($id);
echo  $mediaInfo->getItems()[0]->getCaption()->getCreatedAt();//return if it have a caption. 
```
But how can I get if its havent caption ?

**Comment by mgp25** [comment]
Issue doesn't follow the proper format. Therefore is considered as invalid.

Regards

**Comment by mahedimaruf** [comment]
but this is really a issue
