### ISSUE TITLE
latest_story_pk + media id: ignored.

### ISSUE THREAD

**Issue by TCB13** [mgp25/Instagram-API#2339]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

So I'm trying to get all the timeline "posts" that happened after a certain media id until some date. For this I've this while loop:

```````
do {
	$instagramTimeline = $instagramConnection->timeline->getTimelineFeed(null, ["latest_story_pk" => $lastItem->id]);

	$instagramFactory = new InstagramItemFactory($instagramTimeline);
	$items            = $instagramFactory->getItems();
	array_push($timelineItems, ...$items);
	$lastItem = end($timelineItems);

	sleep($sleep);
} while ($lastItem->timestamp >= $oldest_date);
```````

The problem: looks like instagram doesn't care about the value I suppy in `latest_story_pk` (the id of the last media item on the last iteration) and just gives me the latest 8 items.

Why? What am I doing wrong? Yes, I've read the examples and I'm aware that usually one can call `getNextMaxId()` to get tha max_id to use in the next query. Shouldn't `latest_story_pk` with the ID of the last media also work?

Another way to put it: is it possible to do pagination using the ID of some media instead of the `getNextMaxId()` value? If not, can I get `getNextMaxId()` from the media ID whenever I want?

Thank you.

**Comment by bolds07** [comment]
As far as I know instagram feed isn't chronological since long time ago...
so if you want to paginate you really need to use `max_id`

**Comment by TCB13** [comment]
@bolds07 that would explain the issue. Maybe the parameter should be then removed from the code?

**Comment by moosbat** [comment]
_latest_story_pk_, _seen_posts_, _unseen_posts_, _feed_view_info_ are used by Instagram to detect real app users and they have nothing to do with pagination. When you run instagram for the first time, _latest_story_pk_ is empty but after that it should contain timeline latest media id

**Comment by TCB13** [comment]
@moosbat thank you for the feedback.
