### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by turanmahmudov** [mgp25/Instagram-API#234]
I receive this response on login:
{"status": "fail", "message": "Sorry, there was a problem with your request."}

**Comment by RageBrahimi** [comment]
Delete generated .dat files in `../src/data` - If that doesn't work, attempt logging in on another server or localhost.

**Comment by turanmahmudov** [comment]
I deleted .dat files but same. Is it a IP problem?

**Comment by RageBrahimi** [comment]
@turanmahmudov Potentially. As I recommended, try localhost or another server (avoid free hosting)

**Comment by turanmahmudov** [comment]
@RageBrahimi I will try

**Comment by turanmahmudov** [comment]
@RageBrahimi yes, it worked. thanks a lot.

**Comment by RageBrahimi** [comment]
@turanmahmudov You're welcome :+1:

**Comment by fatgue** [comment]
Someone know that exactly caused this problem. On my localhost every test user can login. But on my server some user got an error. 

{"status": "ok", "shift": 18, "header": "**************************", "edges": 100, "iterations": 10, "size": 42}DATA: ig_sig_key_version=4&signed_body=**************************.{"phone_id":"**************************","_csrftoken":"Set-Cookie: csrftoken=**************************","username":"**************************","guid":"**************************","device_id":"android-7168b51738f95a47","password":"**************************","login_attempt_count":"0"} {"status": "fail", "message": "Sorry, there was a problem with your request."}

**Comment by MMrR0b0TT** [comment]
Maybe, spam.
