### ISSUE TITLE
Cookie file is not writable problem

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2340]
Hi, Im doing likes and subscribes, and sometimes Im getting as exception : 

    The "/home/tcrtsayi/public_html/vendor/mgp25/instagram-php/sessions/inked.hub/inked.hub- 
    cookies.dat" cookie file is not writable.

How can it be solved?

**Comment by Tridenn** [comment]
Hello, maybe the file is damaged or you do not have rights to read it?

**Comment by AndManowar** [comment]
This errors occurs just sometimes and i dont know the reason

**Comment by mgp25** [comment]
Check file permissions. Not API issue.

Regards
