### ISSUE TITLE
Instagram's Signature Key

### ISSUE THREAD

**Issue by instacounter** [mgp25/Instagram-API#2341]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [] Bug report (encountered problems/errors)
- [] Feature request (request for new functionality)
- [x ] Question
- [] Other

---

### Describe your issue

Hello, I have read the documentation many times but I do not understand the subject of the instagram signature key so that the api works

const IG_SIG_KEY = 'c1c7d84501d2f0df05c378f5efb9120909ecfb39dff5494aa361ec0deadb509a';
const SIG_KEY_VERSION = '4';

What would you put in place to make it work?
In the case that you extract the signature, where do I enter it? In what document

**Comment by mgp25** [comment]
It is similar to what it is explained here: https://www.instagram.com/developer/secure-api-requests/

Regards

**Comment by amarvaran** [comment]
Selling
Instagram 75, 76,77 version pinning ssl key signed
skype: amarvaran
