### ISSUE TITLE
how do i get the photo id

### ISSUE THREAD

**Issue by yusufakgunn** [mgp25/Instagram-API#2345]
- [ x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ x] Question
- [ ] Other

Hello, how do i get the photo id from photo url

**Comment by imorteza** [comment]
Get HTML source of URL and find "al:ios:url" meta parameter.

<meta property="al:ios:url" content="instagram://media?id=XXXXXXXXXXXXXXXXXX" />

**Comment by mgp25** [comment]
Check this: https://github.com/mgp25/Instagram-API/blob/master/src/InstagramID.php

Regards
