### ISSUE TITLE
Challenge Required

### ISSUE THREAD

**Issue by holden321** [mgp25/Instagram-API#2351]
Hello!
There is a lot of questions and a lot of answers about this issue but still there is no real solution.
Can you just add some working code as an example to the wiki so that no one ask the question again?

**Comment by mgp25** [comment]
The solution is simple. Verify your account via web browser or device. By the way, I don't know if you have read the issue template at all:

- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!

Happy weekend.

**Comment by holden321** [comment]
I read the issue template and also the wiki.
There is no solution in wiki at all, just a string about checkpoint_required.

We (and I believe most of real users of this API) have a lot of users that want to post to Instagram by this api.
So it is really headache for users and us to do it by hand from our servers or devices.

It would be much better if there was such a flow:
1. check login by api -> challenge required
2. tell instagram to send the code by api
3. suggest user to enter the received code on a web interface
4. send the code to instagram by api

Why don't write two methods like
$instagram->tellInstagramSendCode($bySMS = true)
$instagram->sendCode($code)

If the second method needs some params we can save them somewhere after the first method.

I think this is not difficult for you at all because you are experienced with Instagram.
This is difficult for others like me because it is hard to reproduce such a situation and it is no good to use some user's account to test.

**Comment by mgp25** [comment]
@holden321 there is already an issue where proposed code was discussed. Have you tried searching in the closed issues? If not, I would recommend you looking at them

**Comment by holden321** [comment]
Yes, I have searched and found some solutions but the problem is that I don't know whether it is right solution. Right now I have such a code https://pastebin.com/XvP1tPXe (is it your code actually) but I don't know whether it will work.  I will try it on a real users tomorrow no Monday when managers of my company and our clients are in their offices and ready to contact. If it is working code then why not to make it good looking, place it in methods inside api and write the solution in wiki?

**Comment by mgp25** [comment]
I wont give support for that for some specific reasons that were discussed many times, and by the way, If you have your "users" and using the API commercially, you are using it violating the license...

**Comment by DavidCLuna** [comment]
@holden321 pudiste solucionarlo?, muchas de nosotros tenemos este error y siempre se dice lo mismo, que está en la WIKI, pero allá no hay solución para ello!.
@holden321 puedes decirme cómo lo solucionaste?

**Comment by DavidCLuna** [comment]
@mgp25 At least tell me where I can find the solution to this problem, I've been doing this for several days, locally it works well, I'm running the php directly, but when I upload it to an amazon server that problem occurs to me.

**Comment by DavidCLuna** [comment]
@mgp25 Please help me

**Comment by mgp25** [comment]
@DavidCLuna extracted from the wiki:

> If you get checkpoint_required, it means that Instagram wants you to prove that you are human and that you are the owner of the account. It can easily get triggered if you put your script on a server which is in a country that you don't normally log in from, for example. Simply login to your account via the official website or your mobile device - that should fix it. If you still get the error again, it means Instagram dislikes your server's IP and that you must login to your account via Instagram's website and your server's IP to prove to them that your server's IP is a human.

**Comment by DavidCLuna** [comment]
@mgp25 In the official instagram application I press that it was me, when mea aprece the message that the login is suspicious.
But I rerun the script and the same error continues to occur.
How do I do this? "If you still get the error again, it means Instagram dislikes your server's IP and that you must login to your account via Instagram's website and your server's IP to prove to them that your server's IP is a human."

**Comment by beshoo** [comment]
@DavidCLuna checkpoint loop. you need to use residential Ip Address.
Checkpoint it is very easy to pass, the problem is you have to clear your cookies, use a clean ip address, that is all.

**Comment by tompiccarreda** [comment]
I coded a working solution for the challenge endpoint, send me an email I'd be happy to help.

**Comment by ttvd94** [comment]
@beshoo As you may know using a clean IP address is not as easy as you say. One cannot keep changing servers hoping the new server has not a black-listed IP.
