### ISSUE TITLE
Can some give an example of using IGTV?

### ISSUE THREAD

**Issue by 8lbiasian** [mgp25/Instagram-API#2359]
---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

I am trying to upload video to IGTV feature 

and as i understand from the code i should call it like this

```$resp = $Instagram->tv->uploadVideo($file_path, $data);```

where $file_path is for video path

now what i should include in $data exactly 

as i saw from instagram IGTV its ask for title and description 
but is it same what i will include in $data?? 

for example like this 

```
$data['title'] = "My New IGTV Video";
$data['description'] = "Please give me your feedback about this video"; 
```
please guide me for this if my way is not correct and if so please tell me and close this issue ^^ 

thanks in advance.

**Comment by mgp25** [comment]
@8lbiasian 

`$externalMetadata` for IGTV:

- `title`: Title of the IGTV video
- `caption`: Description of the IGTV video

Regards
