### ISSUE TITLE
failed when login

### ISSUE THREAD

**Issue by mieburungdara** [mgp25/Instagram-API#236]
RESPONSE: {"status": "fail", "message": "Sorry, there was a problem with your request."}

**Comment by mgp25** [comment]
@mieburungdara have you tried relogin with `$force = true`? by they way, when opening an issue paste also the request

**Comment by mieburungdara** [comment]
i try to force login, public function login($force = true), but still fail to login...

and this my config:


<?php
require "Instagram.php";

$username = "blablabla";
$password = "blablabla";
$debug    = "true";

$i = new Instagram($username, $password, $debug);

try{
  $i->login();
} catch (InstagramException $e)
{
  $e->getMessage();
  exit();
}

?>

**Comment by fatgue** [comment]
Hi,

do you have found any solution for your problem. I have exact the same problem . I also deleted the files in the data folder...
