### ISSUE TITLE
Location->Feed isnt gettings newest Items

### ISSUE THREAD

**Issue by uriafranko** [mgp25/Instagram-API#2365]
Hey,
Really tried to deep in the API
but I couldn't find a good reason for that...
When I get a location feed Example:
$feed = $ig->location->getFeed($location->location_id,$rank_token);
Im getting every thing but some times its misses the newest items that I can see from the Actual IG app

So its like isn't refreshing the results or IDK really tried to figure that out...
Please help :)

** Again the results are fine I'm getting anything but some times the first Item is like the second or so within the IG application

**Comment by szokeptr** [comment]
You might be routed to a different server, Instagram’s cache is not always consistent.

**Comment by mgp25** [comment]
If it is just sometimes, then it is not API issue, and that is actually the real response from Instagram server.

Regards

**Comment by uriafranko** [comment]
@mgp25 Hey
Its not that some times it will give the newest and some times it won't 
I meant sometimes it just not refreshing for couple of hours so you won't get the new feed as it supposed to be

**Comment by super-ienien** [comment]
Same issue for me :(
