### ISSUE TITLE
Strategy Parse Response from Server

### ISSUE THREAD

**Issue by phoenixvk** [mgp25/Instagram-API#2368]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
### Describe your issue

Explanation of your issue goes here.
I am getting response like below : 

```
POST:  https://i.instagram.com/api/v1/feed/timeline/
DATA: is_prefetch=0&feed_view_info=&seen_posts=&phone_id=4c14088a-94b7-49c3-bec3-12caad443c50&reason=pull_to_refresh&battery_level=100
← 200    15.19kB
RESPONSE: {"response": "Random Json Response"}
```
I want value of response key from here. Can anyone tell me strategy to parse it? or is this a special kind of Software Architecture style like SOAP or REST?

how to parse this data? Cant I have only response key here?

Thanks :+1:

**Comment by mgp25** [comment]
It is explained in the wiki.

Regards
