### ISSUE TITLE
Audio in Instagram Direct

### ISSUE THREAD

**Issue by hydefus** [mgp25/Instagram-API#2372]
When receive an audio (new feature at Dec 10, 2018) via Instagram Direct I am getting:

{"item_id": "28490479403077995238334226648530944", "user_id": 4459933742, "timestamp": 1544471983198534, "item_type": "placeholder", "placeholder": {"is_linked": false, "title": "Update App", "message": "Update your app to see this message", "seen_user_ids": [], "view_mode": "permanent", "seen_count": 0, "replay_expiring_at_us": null}}

**Comment by JRoy** [comment]
Yeah, this api doesn't implement that feature yet. Since this api is sending a version number that is older than this feature was released in, Instagram is prompting to "update" the "app"

**Comment by mgp25** [comment]
Updated to 76.0.0.15.395 constants in: https://github.com/mgp25/Instagram-API/commit/b6cae398c3a067a6f614711cca58f827187a6eaf

Regards
