### ISSUE TITLE
Does the API affect the activity or no?

### ISSUE THREAD

**Issue by 8lbiasian** [mgp25/Instagram-API#2377]
As some people see in their mobile app they can find ( Your Activity )
which is show the Time on Instagram and the daily average spent on the app. 

so the question is does posting/likes etc.. reflect as activity and do it same as the app? 

and does this will affect my account when i do most things automation, for example, i do scheduling post for next 2 3 weeks and i leave the account without open the app does this mean i do 0 activity and my account will be flagged by IG? 

- [X ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X ] Question
- [ ] Other

---

**Comment by llang9** [comment]
I believe from my testing that activity is determined by connection to Realtime, as that's used by the app whenever it's in the foreground. I imagine that if you're accessing the API frequently without ever connecting to Realtime it would be a flag. Please note that is all conjecture and I don't know in all that much detail.

**Comment by mgp25** [comment]
I personally don't know, that is something someone would need to check and documentate.

Regards

**Comment by hadikmsh** [comment]
hi.
is there any api to get our activity or it saved locally?
