### ISSUE TITLE
Caption missing when upload

### ISSUE THREAD

**Issue by sevekim** [mgp25/Instagram-API#2378]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
**Set up : (Using latest dev-master version as of December 13, 2018)**

First of all, thank you for an awesome api.

I made 4 Instagram accounts for test purpose. With identical photo and caption, I noticed sometimes that caption won't be uploaded to the post.

I think I read through most of questions available online regarding missing caption, but couldn't find a clear answer that works.

I've also gone through `internal.php` and checked through debug file, but no clear explanation.

**Below is the debug:**

    `	POST:https://i.instagram.com/api/v1/feed/timeline/ DATA:is_prefetch=0&feed_view_info=&seen_posts=&phone_id=0d2e2693-6a0c-4e07-9e49-56ef70d6f7e0&reason=warm_start_fetch&battery_level=100&timezone_offset=0&_csrftoken=VW8YupcvHVHdWRJJ5RRIP0DIsxGAKp6p&client_session_id=02cb127e-5fd0-4f97-894c-cdc436fc4e38&device_id=08c52284-6eb4-4f60-ba62-2c194f663e57&is_pull_to_refresh=0&_uuid=08c52284-6eb4-4f60-ba62-2c194f663e57&is_on_screen=true&unseen_posts=&is_charging=1&rti_delivery_backend=0&is_async_ads_double_request=0&is_async_ads=0&will_sound_on=1&is_async_ads_rti=0 ← 200 8.4kB RESPONSE:{  
	   "num_results":5,
	   "more_available":false,
	   "auto_load_more_enabled":true,
	   "feed_items":[  
		  {//Other posts }
	   ],
	   "is_direct_v2_enabled":true,
	   "next_max_id":null,
	   "pagination_info":{  
		  "source":null,
		  "group_id":null
	   },
	   "view_state_version":"1544688338618-bec1c48646a5487eb19c94f5142a23a6",
	   "client_feed_changelist_applied":false,
	   "client_session_id":"02cb127e-5fd0-4f97-894c-cdc436fc4e38",
	   "client_gap_enforcer_matrix":[  
		  {  
			 "list":[  
				3,
				2
			 ]
		  },
		  {  
			 "list":[  
				2,
				3
			 ]
		  }
	   ],
	   "status":"ok"
	}GET:https://i.instagram.com/rupload_igphoto/288339294327053_0_-424138514 → 0B ← 200 12B RESPONSE:{  
	   "offset":0
	}POST:https://i.instagram.com/rupload_igphoto/288339294327053_0_-424138514 → 95.69kB ← 200 71B RESPONSE:{  
	   "upload_id":"288339294327053",
	   "xsharing_nonces":{  

	   },
	   "status":"ok"
	}POST:https://i.instagram.com/api/v1/media/configure/?timezone_offset=0 DATA:signed_body=47f09f05770a0ece98722af051dc2ec053e7d292aa20cb4af3e864e530ec7857.{  
	   "device":{  
		  "manufacturer":"samsung",
		  "model":"SM-G935F",
		  "android_version":"23",
		  "android_release":"6.0.1"
	   },
	   "date_time_digitalized":"2018:12:13 08:05:39",
	   "_csrftoken":"VW8YupcvHVHdWRJJ5RRIP0DIsxGAKp6p",
	   "media_folder":"Camera",
	   "source_type":"4",
	   "_uid":"9256309405",
	   "_uuid":"08c52284-6eb4-4f60-ba62-2c194f663e57",
	   "edits":{  
		  "crop_original_size":[  
			 640,
			 704
		  ],
		  "crop_zoom":1,
		  "crop_center":[  
			 0,
			 -0
		  ]
	   },
	   "extra":{  
		  "source_width":640,
		  "source_height":704
	   },
	   "caption":"This is a sample",
	   "date_time_original":"2018:12:13 08:05:39",
	   "upload_id":"288339294327053"
	}&ig_sig_key_version=4 ← 200 1.13kB RESPONSE:{  
	   "media":{  
		  "taken_at":1544688339,
		  "pk":1933308376951912249,
		  "id":"1933308376951912249_9256309405",
		  "device_timestamp":288339294327053,
		  "media_type":1,
		  "code":"BrUfbnJgXc5",
		  "client_cache_key":"MTkzMzMwODM3Njk1MTkxMjI0OQ==.2",
		  "filter_type":0,
		  "comment_likes_enabled":false,
		  "comment_threading_enabled":false,
		  "has_more_comments":false,
		  "max_num_visible_preview_comments":2,
		  "preview_comments":[  

		  ],
		  "can_view_more_preview_comments":false,
		  "comment_count":0,
		  "image_versions2":{  
			 "candidates":[  
				{  
				   "width":640,
				   "height":704,
				   "url":"https://scontent-ort2-1.cdninstagram.com/vp/c63bc45314f78b1ed00367eb7a2398da/5CAEE9F9/t51.2885-15/e35/45607211_555261058271252_4221033376496833404_n.jpg?_nc_ht=scontent-ort2-1.cdninstagram.com\u0026ig_cache_key=MTkzMzMwODM3Njk1MTkxMjI0OQ%3D%3D.2"
				},
				{  
				   "width":480,
				   "height":528,
				   "url":"https://scontent-ort2-1.cdninstagram.com/vp/72b3c5cf6b51a400ff0d066c899d723b/5C9EFE02/t51.2885-15/e35/p480x480/45607211_555261058271252_4221033376496833404_n.jpg?_nc_ht=scontent-ort2-1.cdninstagram.com\u0026ig_cache_key=MTkzMzMwODM3Njk1MTkxMjI0OQ%3D%3D.2"
				}
			 ]
		  },
		  "original_width":640,
		  "original_height":704,
		  "user":{  
			 "pk":9256309405,
			 "username":"Some ID",
			 "full_name":"Some ID",
			 "is_private":false,
			 "profile_pic_url":"https://scontent-ort2-1.cdninstagram.com/vp/110f282e3a7222f4d4a3298765210499/5C95FDF6/t51.2885-19/s150x150/45448580_509019206174732_2423591500433588224_n.jpg?_nc_ht=scontent-ort2-1.cdninstagram.com",
			 "profile_pic_id":"1923803922902586705_9256309405",
			 "has_anonymous_profile_picture":false,
			 "can_boost_post":false,
			 "can_see_organic_insights":false,
			 "show_insights_terms":false,
			 "reel_auto_archive":"unset",
			 "is_unpublished":false,
			 "allowed_commenter_type":"any"
		  },
		  "can_viewer_reshare":true,
		  "caption":null,
		  "caption_is_edited":false,
		  "photo_of_you":false,
		  "fb_user_tags":{  
			 "in":[  

			 ]
		  },
		  "can_viewer_save":true,
		  "organic_tracking_token":"eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjhjZGEzYTgxZjEzZTQ1M2E4ODdmMzU5NTE0NjgzMjI1MTkzMzMwODM3Njk1MTkxMjI0OSIsInNlcnZlcl90b2tlbiI6IjE1NDQ2ODgzNDEyODl8MTkzMzMwODM3Njk1MTkxMjI0OXw5MjU2MzA5NDA1fDg0MjUxZTg1NTMyN2M4MjIwODU4YzdhODY0MTgzMWY2YmQzYzkwYTk1MDVjMjdkYmEwNjNkZjRjYjZhMjA1MzUifSwic2lnbmF0dXJlIjoiIn0="
	   },
	   "upload_id":"288339294327053",
	   "status":"ok"
	}`

The `caption` is null for some reason.

Would you be able to give me a hand and figure out why the caption won't be added?

Thank you for help and any advice will be much appreciated!

**Comment by mgp25** [comment]
You haven't posted the expected debug log, you should have posted `/configure` request.

Regards

**Comment by fballiano** [comment]
I get the same type of error, this is the "configure" request/response:

```
POST:  https://i.instagram.com/api/v1/media/configure/?timezone_offset=3600
DATA: signed_body=270a60dad194f220a0edef5203a273f4881faee6f9330409b974c1fab814d4ba.{"device":{"manufacturer":"LGE","model":"RS988","android_version":"23","android_release":"6.0.1"},"date_time_digitalized":"2019:01:20 11:52:31","_csrftoken":"F84iBv7b7UHfQc6uQkNUoUyhq3LWRetv","media_folder":"Camera","source_type":"4","_uid":"10597234741","_uuid":"0a473566-8901-42bd-85e7-031fadab21c2","edits":{"crop_original_size":[1080,720],"crop_zoom":1,"crop_center":[0,-0]},"extra":{"source_width":1080,"source_height":720},"caption":"Your #happy #picoftheday by rawpixel.com.\n\n#happiness #happy #photooftheday #love #loveyourself #asmileaday #motivation #man #and #woman #doing #five.","date_time_original":"2019:01:20 11:52:31","upload_id":"561150468955594"}&ig_sig_key_version=4
← 200 	 1.14kB
RESPONSE: {"media": {"taken_at": 1547981551, "pk": 1960933839854822195, "id": "1960933839854822195_10597234741", "device_timestamp": 561150468955594, "media_type": 1, "code": "Bs2ovAYluMz", "client_cache_key": "MTk2MDkzMzgzOTg1NDgyMjE5NQ==.2", "filter_type": 0, "comment_likes_enabled": false, "comment_threading_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "preview_comments": [], "can_view_more_preview_comments": false, "comment_count": 0, "image_versions2": {"candidates": [{"width": 1080, "height": 720, "url": "https://scontent-mxp1-1.cdninstagram.com/vp/84d86ba58ce9a52004f67c23457710e6/5D00690E/t51.2885-15/e35/49325808_381792675711833_7794034079332251189_n.jpg?_nc_ht=scontent-mxp1-1.cdninstagram.com\u0026se=7\u0026ig_cache_key=MTk2MDkzMzgzOTg1NDgyMjE5NQ%3D%3D.2"}, {"width": 240, "height": 160, "url": "https://scontent-mxp1-1.cdninstagram.com/vp/7f276bd1e7f46eaeb5286fb63328620d/5CBFCC06/t51.2885-15/e35/s240x240/49325808_381792675711833_7794034079332251189_n.jpg?_nc_ht=scontent-mxp1-1.cdninstagram.com\u0026ig_cache_key=MTk2MDkzMzgzOTg1NDgyMjE5NQ%3D%3D.2"}]}, "original_width": 1080, "original_height": 720, "user": {"pk": 10597234741, "username": "yourdailyhappypic", "full_name": "Your #daily #happy pic", "is_private": false, "profile_pic_url": "https://scontent-mxp1-1.cdninstagram.com/vp/4671733524fc629e63a0da931d1d0033/5CC97F31/t51.2885-19/s150x150/49848987_572100476597015_3282611511121412096_n.jpg?_nc_ht=scontent-mxp1-1.cdninstagram.com", "profile_pic_id": "1960331079311341175_10597234741", "has_anonymous_profile_picture": false, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "reel_auto_archive": "unset", "is_unpublished": false, "allowed_commenter_type": "any"}, "can_viewer_reshare": true, "caption": null, "caption_is_edited": false, "photo_of_you": false, "fb_user_tags": {"in": []}, "can_viewer_save": true, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjE4NmM4NTRhYjQ5YjRhYmM4NmI4NmI3NjIyMzQ4NTVlMTk2MDkzMzgzOTg1NDgyMjE5NSIsInNlcnZlcl90b2tlbiI6IjE1NDc5ODE1NTI2NDd8MTk2MDkzMzgzOTg1NDgyMjE5NXwxMDU5NzIzNDc0MXwxYjFlZDgwODU0YWQwMzc2MTU1YTBiNjVhN2JjYjgyOWI5YTIxNjE3N2Y1NjE4MTM3MTk1N2RmNTEzYWYwNmI4In0sInNpZ25hdHVyZSI6IiJ9"}, "upload_id": "561150468955594", "status": "ok"}
```

**Comment by gurenovich** [comment]
I have same problem...

**Comment by selene-y** [comment]
same here...
