### ISSUE TITLE
Signup  account Error

### ISSUE THREAD

**Issue by tottilin** [mgp25/Instagram-API#238]
{"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_action": "open_request_form", "feedback_url": "http://help.instagram.com/contact/540011792739811?additional_content=AejiXm_tAjOIZoZiv50tbon3lCO2S0SrhSqPHFjzP9oH4fdalu6eh3qv4TN5_KMVebO1e_9-OWQ-XBDqIFLW0pB5UHu7t1jtbzebBgTEVkvFCW2JWnaU2mSBfGDVg1sHFt-r1CHCo9GN3dHwcuz0SZQ2VNQ16kPjx6dznadJgp6crLZyDqROphTWHcPZLrTXj6NunJqhZwtGeaWuMlX7AQp9airAgbDIHxqL9thBStyBPcU3455406wBZuSTqh8gLwcboIvjMboX1x50EImZ2ieqrjkiseROvcuPezTTqVOKKlYmf2RjciEYo2TijJ2_hzsadx705ZmEK8IP5xjJaLnFFYErOkSKWin2k7fXlEPh1Tzfv52AEPLgmt1F-pY2696Ctx-1Ozk7CFZev6GEpgX6yEvWFKRuxXYSBoIAfAkPpqQ6EtFT1O-o6csycP16KQrYhsV6u3lMnlLF_iJ_4E2rnt_4iqsnCwUhrfI3UPrsYaMW2UzBprzO_7Q5d5Zv928GfUTGtzLSPj4Rc_wgbXpyOG6GLCYI_FiPaPKF0VKl5cMAE_3TiouKuVoXGSGOPyQ\u0026locale=en_US", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Tell us"}

**Comment by RageBrahimi** [comment]
```javascript 
"feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.",
"spam": true
```
Basically, your I.P, or at least your attempt was marked as SPAM `"spam": true`. 
It wasn't an error as far as the script is concerned otherwise it wouldn't have gone through.

**Comment by tottilin** [comment]
I know this is not a problem of your program, I do not know you have not encountered this problem, how to deal with

**Comment by tottilin** [comment]
Change UA and proxy it is valid
