### ISSUE TITLE
Using Realtime vs Push for Direct events

### ISSUE THREAD

**Issue by llang9** [mgp25/Instagram-API#2380]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hi, I've created a script that runs Realtime and Push in the same script - however, I had a read of (https://github.com/mgp25/Instagram-API/wiki/FAQ#is-it-possible-to-run-the-realtime-and-push-clients-in-a-single-script) and it says that it doesn't recommend running them at the same time as the Instagram Client only runs one or the other. 

The reason why I'm using Realtime is to be able to get the event `thread-item-created` and be able to execute some code, let's call it `X`, on that `ThreadItem`. 

The reason why I'm using Push is to be able to get the event `direct_v2_message` and more specifically, when there is a DM request that is sent to the pending inbox. There I want to approve the thread and then execute the same code `X` on the `ThreadItem` within the received `Thread` ID. 

I realise that it's possible to move the code from Realtime to Push and just check there for `thread-item-created` type event too in the `direct_v2_message` event.

I preferred using Realtime because it provided the `ThreadItem` that is relevant directly to the callback and which is why I started with it. I only added Push after I realised I needed to also approve pending requests and there was no such event in Realtime, only in Push.

My question is whether this approach is fine? Would you recommend to instead move everything over to Push? Or alternatively, some way to get the event for a pending `Thread` in Realtime? Alternatively, is it even a good idea to have Realtime constantly running because a user would not be in-app all the time? I'm also currently using 4.1.0 as I had read an issue that Realtime is no longer working in the latest releases due to some updates to the API. For additional reference, the goal is to only run on one account to basically receive DMs - if that is something relevant to seeming like a normal user.

Follow-up to that, what is a good way to ensure that Realtime or Push is able to constantly run? Is one more "stable" than the other when it comes to leaving it running for a long time. I imagine that Push is better designed for this? Should we be de-registering a push token on end of script?

Oh and not directly relevant to this issue but decided to not open another. Are there recommendations on handling sessions? For example, is it an issue if I end up clearing the `sessions/` folder and log in many times, each time a different device? Would it be preferable to use the same device at least each time? I got a bunch of emails, logging in from a new device whilst testing where sometimes I reinstalled dependancies and so lost the sessions.

**Comment by mpt212** [comment]
@llang9 hi, could  you resolve your problem?

**Comment by llang9** [comment]
@mpt212 No? I asked for recommendation on best approach and no one else has commented yet haha? 

I suspect the most qualified to answer it would be @ghost or @valga from what I’ve seen.

**Comment by valga** [comment]
@llang9 Although you can run Realtime 24/7, the best way is to act as a human: always run Push receiver and react to pushes by starting Realtime (and stopping it after some time of inactivity). They finally released Iris in app version 60 or so, making you able to receive offline messages after re-connecting Realtime. But Iris is broken in our code, so you can't receive direct messages in our latest release at all.

After using Push and Realtime for about 2 years, I can only say that both of them are unreliable. You must run HTTP requests periodically to cover everything at 100%.

And there is no way to get pending threads with Realtime. De-registering push token is not required.

Also you should use some reliable sessions storage like MySQL (via out PDO adapter) to preserve device IDs.

**Comment by llang9** [comment]
@valga with Push, I've noticed that once I leave it running for a while it ends up not getting notifications. Is that something you've noticed? Do you have any strategies on combatting this to make sure it continues to run? From the logs it looks it continues to reconnect (or whatever it does with the loop/time stuff) but it doesn't seem to get new notifications.
