### ISSUE TITLE
Constraints for sendVideo in Direct are wrong

### ISSUE THREAD

**Issue by llang9** [mgp25/Instagram-API#2383]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---

### Describe your issue

When sending a video as a DM the library will not allow you to send a video that is in the format of a story as it uses the TimelineConstraint which sets minimum aspect ratio to too high for a story. In Instagram, it's very much possible to send videos (from gallery roll) that are of a story aspect ratio and when I changed the `min_aspect_ratio` of TimelineConstraint I was able to send without any issues.

I'm not sure how to best confirm what the exact constraints are nor how to best modify the constraints to fit in with the style of the package so I'm just leaving this here as a not to the devs.

**Comment by JRoy** [comment]
@llang9 When sending a video in a dm, let's say a screen recording for example: when you open the video, will it fill the whole screen?

**Comment by mgp25** [comment]
Closed since there was no feedback in the issue and no steps to reproduce or more details. Please feel free to open when there is more information about this.

Regards

**Comment by dardo82** [comment]
I’ve been able to send videos in DMs up to 1 minute long using my gist…
https://gist.github.com/dardo82/0f127b170a890ab93078f2eb061700ce
For it to work you obiously need to change the `MAX_DURATION` to `60` in
https://github.com/mgp25/Instagram-API/blob/master/src/Media/Constraints/DirectConstraints.php

Also there is no need for `threadId`, you can just use `userId` instead…
