### ISSUE TITLE
Add support for story slider polls

### ISSUE THREAD

**Issue by jasoniangreen** [mgp25/Instagram-API#2387]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

I see that polls are supported and working such as in [this example](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStoryPoll.php). But I can see no example of the slider polls frequently found in stories. Is this indeed not yet implemented? If not, it would be a great feature to have.

**Comment by mgp25** [comment]
Added in latest commit: https://github.com/mgp25/Instagram-API/commit/1965569b2e746e0d7d97ac86613343a918654e57

Example: [/examples/uploadStorySlider.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStorySlider.php)

**Comment by AlexBlokh** [comment]
hey @mgp25

Is there any way to fetch `slider votes` result. Current methods to fetch stories does not provide those. Polls are ok, but can't find the slider results
