### ISSUE TITLE
uploadAlbum not work for me when use some image 

### ISSUE THREAD

**Issue by aminmohammadmazreali** [mgp25/Instagram-API#2394]
```php
$image = new \InstagramAPI\Media\Video\InstagramVideo("image_address", [
            'targetFeed' => \InstagramAPI\Constants::FEED_TIMELINE_ALBUM
        ]);
$image=$image->getFile();
```

response for me : 

**/tmp/INSTAIMG_Q2iSZa**

when send this to uploadAlbum _**not work**_ 

**or**

response for me : 

**/media/amin/96E484F5E484D8BF1/MyProject/BackEnd/iranito/public/uploads/image/2018/12/1544348048-E9AidUkplvbbtAqG.jpg**

when send this to uploadAlbum **_work_**

> i think because when image is big not work

**Comment by mgp25** [comment]
Invalid issue. Not following issue template and debug log is missing. Please provide all the information in order to get a response.

Regards
