### ISSUE TITLE
Decrease audio quality after uploaded to ig

### ISSUE THREAD

**Issue by ALYREZA** [mgp25/Instagram-API#2397]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Question
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Other

### Describe your issue

I create video from 1 jpeg  + 1 mp3 whith this config  
```
"ffmpeg -hide_banner -loglevel panic -loop 1 -i ./file.jpeg -itsoffset 2 -i ./file.mp3 -ac 2 -c:v libx264 -preset veryslow -c:a copy -shortest -movflags +faststart ./file.mp4";
```
 when I check the quality of file everything is OK  
but when video uploaded to Instagram audio quality decreases dramatically.
How can I prevent this to happen ?

**Comment by bolds07** [comment]
I didn't face this issue but you could try to mime instagram settings

Video Format: MP4 | Video Codec: H.264 | Audio Codec: AAC | Video Resolution: Maximum width 1080 pixels | Frame Rate: Max 30fps | Bit Rate: Up to 7500 kbps |Video File Size: Lower than 4GB | Aspect Ratio: 1.91:1 (max), 4:5 (minimum)

**Comment by mgp25** [comment]
I haven't either. Check what @bolds07 posted.

@bolds07 are you interested in becoming a collaborator/moderator of the repository?

Regards

**Comment by bolds07** [comment]
@mgp25, i feel honored by the invitation i do follow this repository for like 2 years and i feel i know a lot about the api itself, but my reverse engineering skill are super basic so i cant contribute so much for the expansion of api's coverage, the best i can do is help the people to find answers at repository wiki or things like this...

if that is ok to you i do accept
