### ISSUE TITLE
You must have FFmpeg to process videos.

### ISSUE THREAD

**Issue by sametaras** [mgp25/Instagram-API#2398]
Hello there,

I have problem about ffmpeg and ffprobe, two of them are installed i can access with exec or shell_exec but i when i send video to instagram i receive RuntimeException with message You must have FFmpeg to process videos...

\InstagramAPI\Media\Video\FFmpeg::$defaultBinary = 'ffmpeg';
var_dump(\InstagramAPI\Media\Video\FFmpeg::factory()->version());

it is not working 

but its works:
var_dump(shell_exec('ffmpeg -version'));

Can you help me about this?

**Comment by CodeRefract** [comment]
Hello, how did you install ffmpeg? In what directory is this file located?

**Comment by mgp25** [comment]
Hello @sametaras,

We have different issues related to this exact issue, please have a look to the following issues: https://github.com/mgp25/Instagram-API/search?q=FFmpeg+to+process+videos&type=Issues

I am sure you will find the solution there.

Regards

**Comment by sametaras** [comment]
thank you all, you are very helpful. Its because of version of the php, so progress library of smyfony, not working on my hosting... i upgraded to php 7

**Comment by mgp25** [comment]
So everything working fine now, right?

**Comment by sametaras** [comment]
yes everything is working fine now thank you all

**Comment by mgp25** [comment]
Awesome 😄 👍
