### ISSUE TITLE
Headers getting printed in response.

### ISSUE THREAD

**Issue by infigickrutik** [mgp25/Instagram-API#2402]
GET: https://i.instagram.com/api/v1/users/infigic6/usernameinfo/ → 0B ← 200 831B RESPONSE: {"user": {"pk": 9763141966, "username": "infigic6", "full_name": "infigic", "is_private": false, "profile_pic_url": "https://instagram.fdel5-1.fna.fbcdn.net/vp/5fece44ed32cfc802b57d7a92b3f0c62/5CD62C18/t51.2885-19/s150x150/47691244_2008092279488799_6762379935437815808_n.jpg?_nc_ht=instagram.fdel5-1.fna.fbcdn.net", "profile_pic_id": "1943453213496446775_9763141966", "is_verified": false, "has_anonymous_profile_picture": false, "media_count": 0, "follower_count": 4, "following_count": 4, "following_tag_count": 0, "biography": "", "can_link_entities_in_bio": true, "biography_with_entities": {"raw_text": "", "entities": []}, "external_url": "", "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "can_convert_to_business": true, "can_create_sponsor_tags": false, "can_be_tagged_as_sponsor": false, "reel_auto_archive": "unset", "usertags_count": 0, "usertag_review_enabled": false, "has_chaining": false, "hd_profile_pic_versions": [{"width": 320, "height": 320, "url": "https://instagram.fdel5-1.fna.fbcdn.net/vp/171ccb848cff0b956ca83c2578415494/5CC79F60/t51.2885-19/s320x320/47691244_2008092279488799_6762379935437815808_n.jpg?_nc_ht=instagram.fdel5-1.fna.fbcdn.net"}, {"width": 640, "height": 640, "url": "https://instagram.fdel5-1.fna.fbcdn.net/vp/268466d2bd280e5939521f64b65ace09/5CC8E3DB/t51.2885-19/s640x640/47691244_2008092279488799_6762379935437815808_n.jpg?_nc_ht=instagram.fdel5-1.fna.fbcdn.net"}], "hd_profile_pic_url_info": {"url": "https://instagram.fdel5-1.fna.fbcdn.net/vp/083ebc15fd33cecb9b72486bc751a683/5CCBF860/t51.2885-19/47691244_2008092279488799_6762379935437815808_n.jpg?_nc_ht=instagram.fdel5-1.fna.fbcdn.net", "width": 1080, "height": 1080}, "has_placed_orders": false, "show_conversion_edit_entry": true, "allowed_commenter_type": "any", "is_video_creator": false, "has_profile_video_feed": false, "school": {}, "is_eligible_for_school": false, "has_persistent_profile_school": false, "persistent_profile_school_entry_point_type": "none", "is_business": false, "is_call_to_action_enabled": null, "account_type": 1}, "status": "ok"} GET: https://i.instagram.com/api/v1/friendships/9763141966/following/?rank_token=096d3c32-c8a5-420c-a495-37f33d540986 → 0B ← 200 701B RESPONSE: {"users": [{"pk": 25025320, "username": "instagram", "full_name": "Instagram", "is_private": false, "profile_pic_url": "https://instagram.fdel5-1.fna.fbcdn.net/vp/d596fbf6242e8f30045a19fb16aef2ed/5CB33E5B/t51.2885-19/s150x150/14719833_310540259320655_1605122788543168512_a.jpg?_nc_ht=instagram.fdel5-1.fna.fbcdn.net", "profile_pic_id": "1360316971354486387_25025320", "is_verified": true, "has_anonymous_profile_picture": false, "reel_auto_archive": "on", "latest_reel_media": 1546543094, "is_favorite": false}, {"pk": 5713198279, "username": "em_stylish_princess", "full_name": "em_stylish_princess", "is_private": false, "profile_pic_url": "https://instagram.fdel5-1.fna.fbcdn.net/vp/e7fe2a3eb084f2d1446c5cb29a914a90/5CC345F1/t51.2885-19/s150x150/45884178_1940993935999053_4710908267000233984_n.jpg?_nc_ht=instagram.fdel5-1.fna.fbcdn.net", "profile_pic_id": "1929977268424567318_5713198279", "is_verified": false, "has_anonymous_profile_picture": false, "reel_auto_archive": "off", "is_favorite": false}, {"pk": 25054624, "username": "gustavorochaa", "full_name": "Gustavo Rocha", "is_private": false, "profile_pic_url": "https://instagram.fdel5-1.fna.fbcdn.net/vp/e3df7afc67f680befe915b949c8082b1/5CB40989/t51.2885-19/s150x150/47452651_1889170137796894_4287561131704188928_n.jpg?_nc_ht=instagram.fdel5-1.fna.fbcdn.net", "profile_pic_id": "1939636820220810342_25054624", "is_verified": true, "has_anonymous_profile_picture": false, "reel_auto_archive": "on", "latest_reel_media": 1546565489, "is_favorite": false}, {"pk": 218943210, "username": "camerondallas", "full_name": "Cameron Dallas", "is_private": false, "profile_pic_url": "https://instagram.fdel5-1.fna.fbcdn.net/vp/7eaaaf2434d51bea06ce68bc2286a298/5CB47530/t51.2885-19/s150x150/43315608_579062975890667_2158398723267231744_n.jpg?_nc_ht=instagram.fdel5-1.fna.fbcdn.net", "profile_pic_id": "1896743425577279646_218943210", "is_verified": true, "has_anonymous_profile_picture": false, "reel_auto_archive": "on", "latest_reel_media": 1546555524, "is_favorite": false}], "big_list": false, "page_size": 200, "status": "ok"}

![image](https://user-images.githubusercontent.com/42574767/50675393-e1c94d80-1013-11e9-9b1f-fbd4eb7ff825.png)

**Comment by mgp25** [comment]
Hello @infigickrutik,

That are not any headers, what you are getting is the actual response from the server (json format) and it is printed using a debug function. If you don't want debug log, you can disable it.

You can find more information about this in the [wiki](https://github.com/mgp25/Instagram-API/wiki).

Regards
