### ISSUE TITLE
Login error: built-in method cancelled of asyncio.Future object...

### ISSUE THREAD

**Issue by artcad** [mgp25/Instagram-API#2406]
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Code:

```php

set_time_limit(0);
date_default_timezone_set('Europe/Paris');
require __DIR__.'/vendor/autoload.php';
$username = 'myusername';
$password = 'mypassword';
$debug = true;
$truncatedDebug = false;
$ig = new \InstagramAPI\Instagram();

try {
  $ig->login($username, $password);
}
catch (Exception $e) {
  echo "Login problem : ".$e->getMessage()."\n";
}
```

Log:

```
Fatal error: Uncaught InstagramAPI\Exception\BadRequestException: InstagramAPI\Response\BootstrapUsersResponse: <built-in method cancelled of  asyncio.Future object at 0x7f761c212208> returned a result with an error set. in /.../vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:190
Stack trace:
#0 /.../vendor/mgp25/instagram-php/src/Client.php(579): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', '<built-in metho...', Object(InstagramAPI\Response\BootstrapUsersResponse), Object(GuzzleHttp\Psr7\Response))
#1 /.../vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\BootstrapUsersResponse), '{"message": "\\u...', Object(GuzzleHttp\Psr7\Response))
#2 /.../vendor/mgp25/instagram-php/src/Request/People.php(179): InstagramAPI\Request->getResponse(Object(InstagramAPI\Resp in /.../vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php on line 190
```

When I start or restart my script and I login to the account, sometimes I got this error. If I try to restart the script sometimes for unknown reasons, it's working well and the script runs correctly.

Thank you for your time.

**Comment by mgp25** [comment]
@artcad Can you send credentials of the account (via email) or set a dummy account so I can reproduce it on my side and be able to make a fix for it.

Regards

**Comment by plonknimbuzz** [comment]
i want to elaborate but its difficult to reproduce the bug. because it just happen **sometimes** only.  TS [2406](https://github.com/mgp25/Instagram-API/issues/2406) and TS in [2298](https://github.com/mgp25/Instagram-API/issues/2298) say same problem `happens only sometimes`. When i refresh/do it again, action just success (as expected). 

In this month i face this issue 10 times only while i active developing for my private apps.

Any idea to log this debug while i using it in web GUI? or may i just send account credential and proxy only?

**Comment by valga** [comment]
It's just an internal server error, that happens on Instagram side. Don't know why they let its message pass through to us though.
