### ISSUE TITLE
Direct: cannot send text

### ISSUE THREAD

**Issue by rostyslav-matushkin** [mgp25/Instagram-API#2409]
> ### Before submitting an issue make sure you have:
> * [x]  [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
> * [x]  [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
> * [x]  [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
> * [x]  [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
> * [x]  [Installed the api using `composer`](https://github.com/mgp25/Instagram-API#installation)
> * [x]  [Using latest API release](https://github.com/mgp25/Instagram-API/releases)
> 
> ### Purpose of your issue?
> * [ ]  Bug report (encountered problems/errors)
> * [ ]  Feature request (request for new functionality)
> * [x]  Question
> * [ ]  Other
> 
> ### Describe your issue
> I want to send some text to existed thread but I always get error `Need to specify thread ID or recipient users`.
> json is `{"text": "Hi","action": "send_item","thread_ids": [340282366841710300949128185861508494266],"client_context": "4817c700-1439-11e9-a315-a0481c8e17d4","_uuid": "0efb9a30-138c-11e9-85c9-a0481c8e17d4","_csrftoken": "Fq7h1v8wtvLpkPxmnU0fZ2w4Le1FqHiE",}`
> `thread id` I get from a response of inbox, value is correct.
> `thread_ids` value is correctly filled?

**Comment by mgp25** [comment]
@rostyslav-matushkin can you post debug log and the code you used to send the direct?

Regards

**Comment by elvislakota** [comment]
Try 
{"text": "Hi","action": "send_item","thread_ids": ["340282366841710300949128185861508494266"],"client_context": "4817c700-1439-11e9-a315-a0481c8e17d4","_uuid": "0efb9a30-138c-11e9-85c9-a0481c8e17d4","_csrftoken": "Fq7h1v8wtvLpkPxmnU0fZ2w4Le1FqHiE"}

**Comment by elvislakota** [comment]
Try 
{"text": "Hi","action": "send_item","thread_ids": ["340282366841710300949128185861508494266"],"client_context": "4817c700-1439-11e9-a315-a0481c8e17d4","_uuid": "0efb9a30-138c-11e9-85c9-a0481c8e17d4","_csrftoken": "Fq7h1v8wtvLpkPxmnU0fZ2w4Le1FqHiE"}

**Comment by rostyslav-matushkin** [comment]
> @rostyslav-matushkin can you post debug log and the code you used to send the direct?
> 
> Regards

I wrote own Java library and don't use this implementation. Thus I cannot provide any logs what u asked.

**Comment by rostyslav-matushkin** [comment]
> Try
> `{"text": "Hi","action": "send_item","thread_ids": ["340282366841710300949128185861508494266"],"client_context": "4817c700-1439-11e9-a315-a0481c8e17d4","_uuid": "0efb9a30-138c-11e9-85c9-a0481c8e17d4","_csrftoken": "Fq7h1v8wtvLpkPxmnU0fZ2w4Le1FqHiE"} `

It didn't help me. Thanks!

**Comment by rostyslav-matushkin** [comment]
I have an update, how to successfully send this action.
body is byte array and became like this:

> --0efb9a30-138c-11e9-85c9-a0481c8e17d4
> Content-Disposition: form-data; name="client_context"
> 
> 57235340-14c0-11e9-8993-a0481c8e17d4
> --0efb9a30-138c-11e9-85c9-a0481c8e17d4
> Content-Disposition: form-data; name="thread_ids"
> 
> [340282366841710300949128185861508494266]
> --0efb9a30-138c-11e9-85c9-a0481c8e17d4
> Content-Disposition: form-data; name="text"
> 
> Hello, world!
> --0efb9a30-138c-11e9-85c9-a0481c8e17d4--

And headers should contain `multipart/form-data; boundary= + uuid`

Why is that happening?

**Comment by elvislakota** [comment]
[Check this file](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php)

@param array  **$recipients An array with "users" or "thread" keys.
                       To start a new thread, provide "users" as an array
                           of numerical UserPK IDs. To use an existing thread
                        instead, provide "thread" with the thread ID**.

     @param string $text       Text message.

      @param array  $options    An associative array of optional parameters, including:
                                "client_context" - predefined UUID used to prevent double-posting.

`

Are you sure the Thread key is valid, or better try with a numerical UserPK ID

**Comment by rostyslav-matushkin** [comment]
> [Check this file](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php)
> 
> @param array **$recipients An array with "users" or "thread" keys. To start a new thread, provide "users" as an array of numerical UserPK IDs. To use an existing thread instead, provide "thread" with the thread ID**.
> 
> ```
>  @param string $text       Text message.
> 
>   @param array  $options    An associative array of optional parameters, including:
>                             "client_context" - predefined UUID used to prevent double-posting.
> ```
> `
> 
> Are you sure the Thread key is valid, or better try with a numerical UserPK ID

I use valid threads id because I got them from the inbox response only.
I don't want to use users id.

**Comment by mgp25** [comment]
@rostyslav-matushkin if you did an port of this API in java you must open source it becase of the License this API has.

By the way, the solution of this questions is answered in the wiki: https://github.com/mgp25/Instagram-API/wiki

Regards
