### ISSUE TITLE
Getting user public posts/timeline using his or her username only 

### ISSUE THREAD

**Issue by Biggo6** [mgp25/Instagram-API#241]
Hello!

i would like to know if the API can provide the functionality of getting user public posts/timeline using his or username only without login into the app

Regards

**Comment by mgp25** [comment]
You need to be logged in in orther to use the api

Regards

**Comment by RageBrahimi** [comment]
If their profile is public, do the following:
```javascript
$i->searchUsername($usernameName);
```
Get the usernames ID, assign it as `$usernameId` then run
```javascript
 $i->getUserFeed($usernameId, $maxid = null, $count = null)
```

**Comment by Biggo6** [comment]
Hello i dont see where is usernameId is,


{"status":"ok","user":{"username":"kim","usertags_count":32,"has_anonymous_profile_picture":false,"media_count":472,"following_count":382,"is_business":false,"auto_expand_chaining":false,"has_chaining":true,"geo_media_count":317,"profile_pic_url":"http:\/\/scontent-lhr3-1.cdninstagram.com\/t51.2885-19\/11351651_745713102203770_1270930496_a.jpg","is_favorite":false,"biography":"","full_name":"Kim
Swanson","follower_count":23321,"pk":61,"hd_profile_pic_url_info":{"url":"http:\/\/scontent-lhr3-1.cdninstagram.com\/t51.2885-19\/11351651_745713102203770_1270930496_a.jpg","width":150,"height":150},"is_private":false,"external_url":""}}


Joram Kimata
Izweb Technologies
CEO &Founder
P.O Box 8445, DSM

**Comment by azureatlas** [comment]
It's the "pk" attribute
