### ISSUE TITLE
How to catch exceptions for InstagramID::fromCode($id)

### ISSUE THREAD

**Issue by sukhcha-in** [mgp25/Instagram-API#2410]
### Before submitting an issue i have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Example Code:

```php
try {
    $id = InstagramID::fromCode($id);
} catch (\Exception  $e) {
    sendError($e);
}
```

Error Log/var_dump:

```php
InstagramAPI\Response\MediaCommentsResponse: Media is unavailable.
```

---

### Describe your issue

I am trying to get media ID from Instagram web URL. 
Is there any proper way to catch exceptions?

**Comment by mgp25** [comment]
Hello @sukhcha-in,

You are already catching exception of `InstagramID::fromCode()`. The exception you are getting is from `Media::getComments()` function.

Regards

**Comment by sukhcha-in** [comment]
@mgp25 Sir i am trying to use this API in Laravel app, So whole app crashes and gives this error instead of returning exception response:

```
InstagramAPI\Response\MediaCommentsResponse: Media is unavailable.
```
Here is the screenshot: [https://imgur.com/ef9Vg9R](https://imgur.com/ef9Vg9R)
I didn't understand your answer can you please clarify little bit?
