### ISSUE TITLE
How can I resend verification code?

### ISSUE THREAD

**Issue by akhur02** [mgp25/Instagram-API#2411]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
```php
$ig = new Instagram();
$challengePath = 'challenge/' . $iUserId . '/' . $nonceCode . '/';
$choiceType = 0;
$ig->changeUser($login, $password);
$response = $ig->request($challengePath)
    ->setNeedsAuth(false)
    ->addPost("choice", $choiceType)
    ->addPost('_uuid', $ig->uuid)
    ->addPost('guid', $ig->uuid)
    ->addPost('device_id', $ig->device_id)
    ->addPost('_uid', $ig->account_id)
    ->getDecodedResponse();

```

Error Log/var_dump:

```php

RESPONSE: {"status": "fail", "message": "This field is required."}
```
Can I resend code?

**Comment by mgp25** [comment]
Hello, we dont support checkpoint/challenge related issues

Regards

**Comment by sukhcha-in** [comment]
Hello,
Do you got solution about "This field is required." Error?
