### ISSUE TITLE
Product tags info

### ISSUE THREAD

**Issue by yspb** [mgp25/Instagram-API#2412]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hello guys, i don't understand how to get products, their prices and direct links from media.
I read release notes, but found that only setting this data is available and for instagram business accounts only.
There was similar question at april 2018 ( https://github.com/mgp25/Instagram-API/issues/1894 ), do you have any plans to implement this feature?
Can this be done with a premium sub?

Thanks for your attention

**Comment by mgp25** [comment]
Hello @yspb,

Here is an example:

```php
foreach ($userMedia->getItems() as $item) {
    if ($item->getProductTags() !== null) {
        $productTags = $item->getProductTags()->getIn();
        foreach ($productTags as $productTag) {
            $product = $productTag->getProduct();
            $productName = $product->getName();
            $price = $product->getPrice();
            $currentPrice = $product->getCurrentPrice();
            $productId = $product->getProductId();
            $mainImage = $product->getMainImage()->getImageVersions2()->getCandidates(); // Array with IMAGE (url) in diff. resolutions
            $externalUrl = $product->getExternalUrl();
            $merchant = $product->getMerchant()->getUsername();
        }
    }
}
```

Regards
