### ISSUE TITLE
Conflict between API and Instagram application.

### ISSUE THREAD

**Issue by edilson-silva** [mgp25/Instagram-API#2413]
I am using the API at one time for testing and noticed that sometimes API conflict occurs with the Instagram application and security alerts are shown.

Is it possible to change the requisitions so that they are made from a specific country or region?

If yes, what part of the API code do I need to make this change?

**Comment by adeilsoncs** [comment]
@edilson-silva 

use a proxy server in your home and the problem is resolved...
