### ISSUE TITLE
Adding Product Tags to Media

### ISSUE THREAD

**Issue by kiwired** [mgp25/Instagram-API#2414]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hi!

I wonder, if it's possible to add Product Tags to Media at the moment? 
I can provide test accounts, where Instagram Shopping enabled.

Thanks in advance

**Comment by mgp25** [comment]
Hello @kiwired,

That feature is not implemented yet, and it is not a priority for us at the moment. However, we will welcome any contributions to the project. If you implement this feature, you can send a pull request. We will review it, and if everything is correct, we will merge with the code.

Best regards
