### ISSUE TITLE
User getUserId() function always return null

### ISSUE THREAD

**Issue by Splinteer** [mgp25/Instagram-API#2415]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hello,
I'm getting every followers for my account with getFollowers() and an array of Users.
But when I try to getUserId() this function always return null but I can use every other function from User class.
I know I can get user id like that but there is too much API call getting it like that:
`$response = $ig->people->getInfoById($userId);`

Here is my code

```php
do {
  $res = $this->_ig->people->getFollowers($this->getAccountId(), $this->getUuid(), null, $maxId);
  foreach($res->getUsers() as $oUser){
    $flw_userid = $oUser->getUserId();
    if (!in_array($flw_userid, $aOldFollowerId)) {
      $stmt->bindParam(':flw_userid', $flw_userid);
      $stmt->execute();

      $nbNewFollower++;
    }
    $aFollower[] = array(
      'id' => $oUser->getId(),
      'username' => $oUser->getUsername(),
      'fullname' => $oUser->getFullName(),
      'profilePicUrl' => $oUser->getProfilePicUrl()
    );
  }
  $maxId = $res->getNextMaxId();
  sleep(10);
} while ($maxId !== null);
```

**Comment by mgp25** [comment]
Hello @Splinteer,

You must always check if the attribute is found in the response. If it exists you will be able to get it, otherwise you will get `null`. You can enable debug log in order to see responses.

Regards
