### ISSUE TITLE
How to get older feed than certain feed? Max_id

### ISSUE THREAD

**Issue by SongHyok** [mgp25/Instagram-API#242]
Hello

I tried to use feed pagination so I have looked closed issue and I had found solution so till now, I have used it but now it is not working.

I have modified getTimeline function like this.
```php
public function getTimeline($max_id = NULL)
  {
      
      if($max_id==null){
          $timeline = $this->request("feed/timeline/?rank_token=$this->rank_token&ranked_content=true")[1];
      } else {
          $timeline = $this->request("feed/timeline/?rank_token=$this->rank_token&ranked_content=true&max_id=$max_id")[1];
      }
      
      if ($timeline['status'] != 'ok')
      {
        throw new InstagramException($timeline['message'] . "\n");
        return;
      }

      return $timeline;
  }
```

It was working perfectly but now it is malfunctioned.

**Comment by RageBrahimi** [comment]
Explain what you mean by `malfunctioned` - include a debug too.

**Comment by SongHyok** [comment]
i mean when I execute this function, the result is from the latest one even I input max_id(feed_id like 125676543290). It worked very well. But now, they are not working.

**Comment by RageBrahimi** [comment]
```javascript
"next_max_id": "1282337634308293325_25025320"
```
So `$max_id` should be `1282337634308293325_25025320`
