### ISSUE TITLE
How do I get all the comments

### ISSUE THREAD

**Issue by kugimomerfaruk** [mgp25/Instagram-API#2420]
Hi, I'm new to this. I tried so hard, but I couldn't. How can I get all the comments of a post. I used the example below.

```php
$my_i=0;
$maxId = null;
do {
    $feed = $ig->media->getComments($mediaID, array('max_id'=>$maxId ));
    print 'getCommentCount->'.$feed->getCommentCount();
    $maxId = $feed->getNextMaxId();
    $ambil = $feed->getComments();
    foreach($ambil as $data){
        echo "<br>";
        echo "====== \n";
        print $data->getText();
        $my_i++;
    }
} while (!is_null($maxId));
```

**Comment by mgp25** [comment]
Hello @kugimomerfaruk,

When you open a new issue, make sure you give full details of what question or issues are you having. In the context of this issue, I am not sure what error are you facing. 

Also make sure you have looked to the pagination example:

- [/examples/paginationExample.php](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php)

Regards
