### ISSUE TITLE
react/event-loop outdated

### ISSUE THREAD

**Issue by blue-eyed-devil** [mgp25/Instagram-API#2423]
Would it be possible to update dependency of react/event-loop to the latest (1.0.0)?
composer won't install INstagram-php because i already have react/event-loop 1.0.0 installed and I keep getting message:
![capture](https://user-images.githubusercontent.com/19608742/51262993-87fb5700-1a07-11e9-8214-0907b5e8c4c4.PNG)

**Comment by mgp25** [comment]
Hello,

You can modify the composer.json and try if everything goes well, but since we haven't checked dependencies, changes and so, I would recommend you to downgrade to the version the API uses.

Regards
