### ISSUE TITLE
No response from server. Either a connection or configuration error.

### ISSUE THREAD

**Issue by igorbelikov** [mgp25/Instagram-API#2425]
```php
$ig->media->getInfo(...)
```

Exception: No response from server. Either a connection or configuration error.

Another methods works good.

**Comment by igorbelikov** [comment]
vendor/mgp25/instagram-php/src/Request/Media.php:29
```php
return $this->ig->request("media/{$mediaId}/info/")
```

Have error **Http response Method Not Allowed 405**. 😞

**Comment by mgp25** [comment]
Will review this tomorrow

**Comment by xiCO2k** [comment]
Thanks

**Comment by mgp25** [comment]
Does this happen only with stories?

**Comment by xiCO2k** [comment]
This is the Id returned from:
`$ig->people->getRecentActivityInbox()->getNewStories()`

And that is the getInfo:
`$ig->media->getInfo('1715536040856253967_5537473138');`

I also exploded this id and tried with just '1715536040856253967' but no luck

**Comment by mizbani** [comment]
From today, the API path of receiving media information does not need to send POST data and available on the GET method
please change method to this :
`public function getInfo($mediaId)
    {
        return $this->ig->request("media/{$mediaId}/info/")
            ->getResponse(new Response\MediaInfoResponse());
    }`

**Comment by aliforever** [comment]
It happens only for posts, I guess they have changed the post request.

**Comment by aliforever** [comment]
> From today, the API path of receiving media information does not need to send POST data and available on the GET method
> please change method to this :
> `public function getInfo($mediaId) { return $this->ig->request("media/{$mediaId}/info/") ->getResponse(new Response\MediaInfoResponse()); }`

It works. thanks

**Comment by xiCO2k** [comment]
Awesome, just checked and works.

**Comment by mgp25** [comment]
I just verified this behavior with the current Instagram app. Pushing a fix in a minute.

**Comment by mgp25** [comment]
Fixed in: https://github.com/mgp25/Instagram-API/commit/b7f1d9812d4dbca5a3eee8f5c45cfcd1c8240775

**Comment by comical-interactive** [comment]
Hello.. this issue is occuring again.. can you take a look? i think instagram changed their API.. because i got
 "No response from server. Either a connection or configuration error"
