### ISSUE TITLE
What is autoCompleteUserList()? Why it gaves error always?

### ISSUE THREAD

**Issue by ihsangulumser** [mgp25/Instagram-API#243]
What is autoCompleteUserList function?

and why it gaves error everytime i try to login?

```
REQUEST: friendships/autocomplete_user_list/
RESPONSE: {"status":"fail","message":"Sorry, too many requests. Please try again later."}
```

**Comment by mgp25** [comment]
I dont remeber what the functions does, but i guess the response is evident. Also, reuse session, avoid login in multiple times
