### ISSUE TITLE
Bug in src/Push.php

### ISSUE THREAD

**Issue by reznikartem** [mgp25/Instagram-API#2433]
Hello. Found bug in src/Push.php , line 251

```php
$this->emit('error', $e);
```

$e is object, but method emit accepts only array.

P.S. thanks you for your work.

**Comment by mgp25** [comment]
@RageBrahimi Did it throw any error? Can you post any evidence/report?

Regards

**Comment by reznikartem** [comment]
> **PLEASE**, follow issue template!

I`m so sorry :( Post this issue in the middle of hard work, my fault. 

> Did it throw any error?

Yep:

Uncaught TypeError: Argument 2 passed to InstagramAPI\\Push::emit() must be of the type array, object given, called in /usr/local/www/Core/vendor/mgp25/instagram-php/src/Push.php on line 251 and defined in /usr/local/www/Core/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:115
Stack trace:
#0 /usr/local/www/Core/vendor/mgp25/instagram-php/src/Push.php(251): InstagramAPI\\Push->emit('error', Object(InstagramAPI\\Exception\
etworkException))
#1 /usr/local/www/Core/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): InstagramAPI\\Push->InstagramAPI\\{closure}('{\"k\":\"eyJwbiI6I...')
#2 /usr/local/www/Core/vendor/mgp25/instagram-php/src/Push/Fbns.php(121): InstagramAPI\\Push\\Fbns->emit('fbns_token', Array)
#3 /usr/local/www/Core/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): InstagramAPI\\Push\\Fbns->InstagramAPI\\Push\\{closure}(Object(Fbns\\Client\\Message\\Register))
#4 /usr/local/www/Core/vendor/valga/fbns-react/src/Lite.php(179): Fbns\\Client\\Lite->emit('register', Array)
#5 /usr/local/www/Core/vendor/valga/fbns-react/src/Lite.php(218): Fbns\\Client\\Lite->onRegister('{\"pkg_name\":\"co...')
#6 /usr/local/www/Core/vendor/valga/fbns-react/src/Lite.php(126): Fbns\\Client\\Lite->onMessage(Object(BinSoul\
et\\Mqtt\\DefaultMessage))
#7 /usr/local/www/Core/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Fbns\\Client\\Lite->Fbns\\Client\\{closure}(Object(BinSoul\
et\\Mqtt\\DefaultMessage), Object(Fbns\\Client\\Lite\\ReactMqttClient))
#8 /usr/local/www/Core/vendor/valga/fbns-react/src/Lite/ReactMqttClient.php(668): Evenement\\EventEmitter->emit('message', Array)
#9 /usr/local/www/Core/vendor/valga/fbns-react/src/Lite/ReactMqttClient.php(547): Fbns\\Client\\Lite\\ReactMqttClient->finishFlow(Object(Fbns\\Client\\Lite\\ReactFlow))

**Comment by valga** [comment]
@reznikartem Thanks for the report.
