### ISSUE TITLE
Network: CURL error 18: transfer closed

### ISSUE THREAD

**Issue by xiCO2k** [mgp25/Instagram-API#2436]
Hey,

Sometimes I get this error getting the `$ig->media->getInfo()`, normally on the next run it works great, should I catch this case and ignore?

`Fatal error: Uncaught InstagramAPI\Exception\NetworkException: Network: CURL error 18: transfer closed with 59283 bytes remaining to read (see http://curl.haxx.se/libcurl/c/libcurl-errors.html). in /var/www/html/vendor/mgp25/instagram-php/src/Client.php:646`

Thanks.

**Comment by mgp25** [comment]
Hello @xiCO2k,

Please, use issue template. Next time the issue will be closed directly if not followed.

From https://curl.haxx.se/libcurl/c/libcurl-errors.html:

```
CURLE_PARTIAL_FILE (18)

A file transfer was shorter or larger than expected. This happens when the server first reports an expected transfer size, and then delivers data that doesn't match the previously given size. 
```

Make sure you are using latest code from `dev-master` and your proxy is okay.

Regards

**Comment by ryandiamond23** [comment]
@mgp25 I am seeing this issue as well using the latest release on master via composer -- any ideas? I am trying to pull comments in from a post.

**Comment by mgp25** [comment]
@ryandiamond23 Not API issue… read my comment above https://github.com/mgp25/Instagram-API/issues/2436#issuecomment-456128043

Regards

**Comment by ryandiamond23** [comment]
Got it -- was of course my own doing and not an API issue as mentioned. Appreciate the quick response as well.
