### ISSUE TITLE
Is it possible to get Item by URL/hash?

### ISSUE THREAD

**Issue by youmee** [mgp25/Instagram-API#2437]
Can't figure out how to retrieve Item object by URL. Is it possible?
URL like: `https://www.instagram.com/p/Bstvi1nhR5m/`

**Comment by mgp25** [comment]
Hello @youmee,

This issue doesn't follow the issue template, next time your issue will be closed directly if you dont follow the template.

Yes, it is possible and it is a duplicate issue. Anyway, here is the reference: https://github.com/mgp25/Instagram-API/blob/master/src/InstagramID.php

Regards

**Comment by mgp25** [comment]
@youmee no problem. Did you find the solution?

**Comment by youmee** [comment]
@mgp25 yeah! Thank you! Really nice lib.
