### ISSUE TITLE
Endpoint for search specific username in Likes/Followers/Following lists

### ISSUE THREAD

**Issue by 350d** [mgp25/Instagram-API#2438]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Anyone with SSL sniffer available (with ssl pinning) please help me to find endpoint needed for search specific usernames in media likes list and account followers/following lists.
This feature available in mobile app when you viewing any of these lists on very top in search bar.
Thank you!

<img src="https://user-images.githubusercontent.com/429208/51567421-29016c00-1e65-11e9-8ffb-6a0cf0e657e9.jpeg" width=400>

**Comment by mgp25** [comment]
Hello @350d,

Unfortunately, these requests doesn't appear to be in the Android version of Instagram. This API is based on Instagram for Android, so all request must appear in there. If you see that these are enabled in the Android app, let me know and I'll add them.

Regards!

**Comment by pashmak73** [comment]
Hi, it's exists in android!

Also it's exists in your api too! Search query parameters in `getFollowers` or `getFollowing` is the answer, if you set an query, it will returns followings/followers list based on search query.

Good luck.

**Comment by 350d** [comment]
@mgp25 Hello! This functionality available on Android too, so, please, reopen this request if possible.
@pashmak73 `query` parameter works just like a filter in current implementation and existing method can only download all likes/followers/following and search in these lists. This is not what I'm looking for. I need single request method and it will be a huge optimization for existing methods.

**Comment by mgp25** [comment]
Hello @350d,

That feature is already implemented (https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php#L376). AS you can see there is already a `$searchQuery` param.

Regards

**Comment by 350d** [comment]
@mgp25 Yes, thank you for your answer, but it's partly correct. Method with `$searchQuery` available only for followers/following lists but not for likes. I've tried to simply add this query parameter to likes method - doesn't work.

**Comment by JRoy** [comment]
@350d,

This behavior is not present in the Android app. Therefore we cannot emulate it.

Regards
