### ISSUE TITLE
next_max_id for getStoryItemViewers returning invalid value 

### ISSUE THREAD

**Issue by leyoav** [mgp25/Instagram-API#2440]
### Purpose of your issue?
- [X] Bug report (encountered problems/errors)

When trying to get next block of results for list of story viewers (getStoryItemViewers API),
the `next_max_id field` `[ ($maxId = $response->getNextMaxId(); ]` contains invalid value (got value = "23" instead of in a standard format) 

![image](https://user-images.githubusercontent.com/13105516/51630493-fd5caf80-1f52-11e9-90b9-02022c39ad0f.png)

Then eventually next retrieval command fails 
`[ $response = $instagram->story->getStoryItemViewers($mediaPk,  $maxId); ]`

Does that value originally return from Instagram (i.e, pagination is NOT available for this function) or is it a mishandling of this field by the base code ?

**Comment by mgp25** [comment]
@leyoav we do not manipulate any response from Instagram, so yes that it is the original value that instagram assigned.

What is the response when it fails? Please provide more details and debug log

**Comment by leyoav** [comment]
Oops - Now it seems that next_max_id = 23 did the work (even if looks not in the right format) and I did get the next result block (although updated_media sub-structure is missing, and that's what confused me).

![image](https://user-images.githubusercontent.com/13105516/51637045-677d5080-1f63-11e9-8e64-3175739fd9d2.png)

Great - thank you for your quick response. You really did a great work !
