### ISSUE TITLE
How works getFollowers ?

### ISSUE THREAD

**Issue by DeLuca92** [mgp25/Instagram-API#2441]
Hello,  I will try get all Followers by a user, but I can not do this :/
Only return a 200users, but the account have 111k
In the wiki show to put only echo `$ig->people->getFollowers($userId)`, but this not works I search here and found this alternative.

```php
<?php

error_reporting(E_ALL);
ini_set('display_errors',1);
set_time_limit(0);
ini_get('curl.cainfo');

require 'autoload.php';

\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

$username = 'user';
$password = 'user';

$ig = new \InstagramAPI\Instagram();
 $rankToken = \InstagramAPI\Signatures::generateUUID();
try{
	$ig->login($username, $password);
} catch (\Exception $e){
		echo $e->getMessage();
}

	//echo $ig->account->getCurrentUser();
	$userId = $ig->people->getUserIdForName('vivalatino');
	
	echo $ig->people->getFollowers($userId,$rankToken);
		
?>
```

**Comment by DeLuca92** [comment]
Okay, I will try, can i post my future code here?

**Comment by mgp25** [comment]
@DeLuca92 Sure!

**Comment by JRoy** [comment]
For your use case the 1st parameter should  be the user id, 2nd the rankToken, 3rd is null, and the 4th is your max id.

Also, I'm not accusing you of this or anything but I'd like to point out that this API is not for spam. That violates not only the terms of the API but Instagram's as well

**Comment by DeLuca92** [comment]
I know.

Only to do a test not send msg.
To check all Followers

**Comment by uchihaarfan28** [comment]
i received duplicated result, anyone have same problem like me ?
