### ISSUE TITLE
Is it safe to use free proxies with this library?

### ISSUE THREAD

**Issue by logaro** [mgp25/Instagram-API#2444]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)
### Purpose of your issue?
- [x] Question

Hi, I am aware that i can send all my request with proxies like socks,
But the important question is that, If i use a free proxy (they are easy to find on websites), 

1- The proxy provider can see my session information that i send to instagram?

2- Can they redirect me to a fake instagram api and steal my password or session information? (they can be _man in middle_ and send my data to themselves)

**Comment by beshoo** [comment]
Not related...
Instagram will limits / block your activity. 

Regards

**Comment by logaro** [comment]
@beshoo  Hi Are u ok? Did you read my question or just wanted to say something?! 
-
I know instagram limits requests, 
My question is that if the proxy provider want to sniff my data, Can they still my session or not? very simple!

**Comment by 8lbiasian** [comment]
> @beshoo
> Hi Are u ok? Did you read my question or just wanted to say something?!
> 
> I know instagram limits requests,
> My question is that if the proxy provider want to sniff my data, Can they still my session or not? very simple!

the proxy issues are not related to the API, but as an answer, even private have issues with proxy so imagen using a free one.

**Comment by szokeptr** [comment]
Since Instagram uses only HTTPS for their API communcation you should be fine, unpess you disable SSL verification.
