### ISSUE TITLE
Any body know? How to get json about subscribings page?

### ISSUE THREAD

**Issue by BaturitskiyDenis** [mgp25/Instagram-API#2445]
<img src="https://user-images.githubusercontent.com/45892893/51675465-cfc04680-1fe4-11e9-8677-dfb788dd728a.jpg" width=200>

**Comment by mgp25** [comment]
Please search before opening an issue: https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php

**Comment by BaturitskiyDenis** [comment]
> Please search before opening an issue: https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php

Thx!
