### ISSUE TITLE
Story seen notification

### ISSUE THREAD

**Issue by lintangtimur** [mgp25/Instagram-API#2447]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue
When i create story, i want if people X seen my story i get notification. This is posible to get X username is in the list of seen story?

**Comment by JRoy** [comment]
This is possible by using the getStoryItemViewers function in the [Story Class](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php) with pagination. 

To see an example of how pagination works: [paginationExample.php](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php)

Hope this helps

**Comment by lintangtimur** [comment]
ok, thanks. How to implement into realtime?
so I only need to run once, and wait for the results
