### ISSUE TITLE
getUserIdForName time by request

### ISSUE THREAD

**Issue by DeLuca92** [mgp25/Instagram-API#2448]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- 

 [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other
-----------------------------------------------------------------------------------------------------
Hello,
I tried to get 300 ids by my user (I have a list of usernames), but API or Instagram, but API or Instagram are locking
And sent this msg: Something went wrong: Throttled by Instagram because of too many API requests.
I put a `sleep (5)`;, but the same error occurs.

I think this is normal beacuse API or Insgram think this is spam: /

Is there a way to solve this?

**Comment by mgp25** [comment]
Hello @DeLuca92,

This is normal. You are doing too many requests in a short amount of time, and Instagram prevents you by refusing your requests. Add a delay and wait a couple minutes until you get a valid response

Regards

**Comment by bisht-sanjeet** [comment]
> @mgp25 , Okay I will search :)
> What is the recommended `sleep `to use this?
> Regards

@DeLuca92 
https://github.com/mgp25/Instagram-API/issues/1710#issuecomment-347415959
according to this comment it should be 5 or more seconds. 
And I personally using sleep between 5-8 if required.

**Comment by DeLuca92** [comment]
@bisht-sanjeet , okay thx.
I think the error is in getUserIdForName because it do the requests and instagram block this requests :/
But I will try put a 8 seg of  sleep and a cont when the cont arrive in 150 Ids stop by 1 hour and start again until end of list.
