### ISSUE TITLE
 REQUEST:  accounts/create/, RESPONSE:  HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by meta1001** [mgp25/Instagram-API#245]
REQUEST:  accounts/create/
DATA:  ig_sig_key_version=4&signed_body=f9661e508e9e85509399a2c40cf714829b8d9a3bf0ce35c0e2c8cb1d439d4e1f.%7B%22username%22%3A%20%22totolink_regtO%22%2C%20%22first_name%22%3A%20%22LogI%20love%22%2C%20%22password%22%3A%20%22lby851222%22%2C%20%22qs_stamp%22%3A%20%22%22%2C%20%22force_sign_up_code%22%3A%20%22%22%2C%20%22guid%22%3A%20%2224666135-f925-43e4-b2f6-aa7b071e6958%22%2C%20%22phone_id%22%3A%20%2224666135-f925-43e4-b2f6-aa7b071e6958%22%2C%20%22email%22%3A%20%22linbayu312%40163.com%22%2C%20%22_csrftoken%22%3A%20%22missing%22%2C%20%22device_id%22%3A%20%22da60b579faebe684e2a2bf90d4e50c8297d98119%22%7D 

RESPONSE:  HTTP/1.1 400 Bad Request
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Fri, 01 Jul 2016 03:23:51 GMT
Content-Type: application/json
Set-Cookie: csrftoken=3f39d1f929f14a5d712b55ae01823d5d; expires=Fri, 30-Jun-2017 03:23:51 GMT; Max-Age=31449600; Path=/
Set-Cookie: s_network=; expires=Fri, 01-Jul-2016 04:23:51 GMT; Max-Age=3600; Path=/
Set-Cookie: sessionid=IGSCfbe5417ce1077798172666f4f88a6d66cf956b058d5802f5d75146b9b6074a5e%3AyTIiRw9qRWORQMRpA5dSJrgDDyXFdooA%3A%7B%22_token_ver%22%3A2%2C%22_auth_user_id%22%3A3487114756%2C%22_token%22%3A%223487114756%3AvxqAQuXhLRc4kL5ccpeqkhpARH2mpmxx%3A9a26242a5beb8c704224a181a791278bdcbba50b1bf9edb0d0d0443214c1a65d%22%2C%22asns%22%3A%7B%2245.32.52.253%22%3A20473%2C%22time%22%3A1467343431%7D%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22last_refreshed%22%3A1467343431.573864%2C%22_platform%22%3A1%7D; expires=Thu, 29-Sep-2016 03:23:51 GMT; httponly; Max-Age=7776000; Path=/
Set-Cookie: mid=V3XiRgABAAF-n5FESUf6iizACEYk; expires=Thu, 26-Jun-2036 03:23:51 GMT; Max-Age=630720000; Path=/
Connection: close
Content-Length: 477

{"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_action": "report_problem", "feedback_url": "repute/report_problem/instagram_signup/", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Report problem"}

**Comment by mgp25** [comment]
"spam": true
