### ISSUE TITLE
Updating X_IG_Capabilities to latest version

### ISSUE THREAD

**Issue by pashmak73** [mgp25/Instagram-API#2457]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

It's not an issue, but you didn't update `X_IG_Capabilities` constants in this https://github.com/mgp25/Instagram-API/commit/b6cae398c3a067a6f614711cca58f827187a6eaf

Is it OK or not?

**Comment by mgp25** [comment]
Yes, it is okay. That value is not updated very often.

Regards
