### ISSUE TITLE
[REQUEST] Add account data endpoint

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2460]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

### Describe your issue

I would like to request the creation of the account data endpoint.

It is acessible through instagram app from settings -> Account Data
it shows ingo like date the person joined instagram, former usernames at all....
https://ibb.co/Qbk5XQD

There is also a similar endpoint [possible the same] which anyone can query for business profiles
https://ibb.co/YNpPsrG

**Comment by bolds07** [comment]
Can you point me which address the webview is getting? i may try to mock and use in my personal project...

I actually have a project based in this repository and i'm trying to enforce that profiles using it are not fakes or just made for that purpose... so check how old the profile is a good metric for me

**Comment by JRoy** [comment]
@bolds07 I'm unable to find the address it's using as well as their authentication methods as well

**Comment by agustinjch** [comment]
As @JRoy said, is a webview and no a standard api call.

So, my guess is that the endpoint will be something like in the site `https://www.instagram.com/accounts/access_tool/` , but I don't think the app cookie will work.

**Comment by amarvaran** [comment]
Selling
Instagram 75, 76,77 version pinning ssl key signed
skype: webqart_1

**Comment by JRoy** [comment]
Added in 3669f43

Regards

**Comment by bolds07** [comment]
@Jroy, for bussiness accounts is also possible to see the "join date" did you find any endpoint related to that?
