### ISSUE TITLE
Share post in Story 

### ISSUE THREAD

**Issue by 8lbiasian** [mgp25/Instagram-API#2464]
### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x ] Feature request (request for new functionality)
- [x ] Question

---

### Describe your issue

Is it possible to add the ability to share a post in the story? 

not sharing as Photo but as a post so ppl can click on it and navigate to post 

sorry i am not expert in debugging to get the endpoint etc..

**Comment by 8lbiasian** [comment]
@mgp25 brother is this doing what I ask for?? and does it work with video posts? or only photos! 

https://github.com/mgp25/Instagram-API/blob/master/examples/sharePhotoToStoryFeed.php

**Comment by JRoy** [comment]
@8lbiasian you're not entitled to anything and we will do this on our own time. mgp is very busy and I'm working on adding other features. Don't ask us to drop everything we are doing just to solve your thing.

**Comment by 8lbiasian** [comment]
@JRoy bro i know how this is hard and really appreciate it and thankful for your work ofc, so i didnt say that i need the things immediately its just a question then i found some code which i am trying to implement, if it's same what i want thats ok and if its not just say no
I didn't rush and didn't bother u guys for hurry in answering me

**Comment by JRoy** [comment]
Yes, to add the clickable text area you use this example: https://github.com/mgp25/Instagram-API/blob/master/examples/sharePhotoToStoryFeed.php 
As for drawing it, that's up to you.
