### ISSUE TITLE
Video unavailable when live broadcasting

### ISSUE THREAD

**Issue by manuelgu** [mgp25/Instagram-API#2465]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Example Code:
To be found here https://github.com/mgp25/Instagram-API/blob/master/examples/liveBroadcast.php

### Describe your issue

I have tried to run the liveBroadcast.php example, providing an mp4 file with a length of 2:34m. The script runs fine, Instagram reports back that the broadcast is "active". The check whether the broadcast is running or not also returns true, returning in the do-while loop to continuously fetch the status. However, I am unable to watch the actual live stream on a device. It appears as if the account was streaming, however tapping the icon results in a loading wheel and eventually a generic error message by Instagram that the broadcast cannot be played.

What could be the reason?

**Comment by bolds07** [comment]
Very stupid question but... are you trying to watch with a different account?
you cant watch your own instagram live, so you must use a different acount to test it

**Comment by manuelgu** [comment]
Yes, I am trying to watch with a different account than the one livestreaming

**Comment by manuelgu** [comment]
I was able to reproduce this issue several times over the course of a couple of days.

**Comment by JRoy** [comment]
I've dealt with this problem many times on some of my personal projects and the issue usually comes down to one of two things:

1) You're streaming content in an odd aspect ratio that the Instagram Client can/will not process.
2) Instagram is not happy with your account (you've been spamming, you're a *newer* account using this API, etc).

Regards
