### ISSUE TITLE
InstagramRegistration Tool

### ISSUE THREAD

**Issue by muhammeddilaver** [mgp25/Instagram-API#247]
Always RESPONSE: {"status": "ok", "errors": {"device_id": ["Too many users have been registered on this device."]}, "account_created": false}

how can i make?
Thanks.

**Comment by mgp25** [comment]
Change device id, obvious right?

**Comment by muhammeddilaver** [comment]
'android-'.str_split(md5(mt_rand(1000, 9999)), 17)[mt_rand(0, 1)]

It is not random?

**Comment by mgp25** [comment]
it doesnt matter, it can coincide with an existing one.

If i say you one number randomly, in rare situations ill coincide with you
