### ISSUE TITLE
Bug two accounts with same information.

### ISSUE THREAD

**Issue by akhur02** [mgp25/Instagram-API#2470]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
I have two instagram accounts akhur02 and jango.rules. akhur02 password1, and jango.rules passwowrd2
I tried to login with akhur02 with password jango.rules. 

```php
$login = $ig->login('akhur02', 'password2'); //
```
Login success by jango.rules. Why, if login is akhur02? in truth, I should have received an error that the password is not correct

And when I tried to login with jango.rules and password1 - akhur02. 

```php
$login = $ig->login('jango.rules', 'password1'); 
```
I get error password is not correct

**Comment by mgp25** [comment]
Duplicate issue. Because you were already logged in, and when it exists a valid session, you dont need to authenticate again, it will get all the required information from the store data in `/sessions/`

Regards

**Comment by akhur02** [comment]
@mgp25 why duplicate. there is two instagram accounts and problem is not in sessions. I'm trying to login as akhur02 but I’m logging on  instagram as jango.rules.
