### ISSUE TITLE
unlinkAddressBook does not work anymore

### ISSUE THREAD

**Issue by plankes-projects** [mgp25/Instagram-API#2484]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

            "name": "mgp25/instagram-php",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/mgp25/Instagram-API.git",
                "reference": "6492fabc4baea5672712885448bcf579c0b9cab9"
            },

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Example Code:

```php
$instagramApi = new Instagram(true, false, [
	'storage'     => 'mysql',
	'pdo'         => $pdo,
	'dbtablename' => 'instagram'
]);

$instagramApi->setProxy($proxy);
$instagramApi->login($username, $password);

$selfInfoUser = $instagramapi->people->getSelfInfo()->getUser();
$username = $selfInfoUser->getUsername();

$instagramapi->people->unlinkAddressBook(); //throws exception
```

Error Log/var_dump:

```php
Debug of unlinkAddressBook:

POST:  https://i.instagram.com/api/v1/address_book/unlink/
DATA: signed_body=XXX.{"_csrftoken":"XXX","_uid":"XXX","_uuid":"XXX"}&ig_sig_key_version=4
← 500 	 25B
RESPONSE: Oops, an error occurred.

Exception message: 
No response from server. Either a connection or configuration error.
```
### Describe your issue

Issue is present since last week. Other requests work as expected. Even linkAddressBook instead of unlinkAddressBook would work at this location.

**Comment by JRoy** [comment]
Will look into this

**Comment by plankes-projects** [comment]
Seem like it was a temporary error on instagram side. requests works again.
