### ISSUE TITLE
Show Question Endpoints are incorrect

### ISSUE THREAD

**Issue by JRoy** [mgp25/Instagram-API#2486]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

The show question endpoint probably got new parameters when we updated the constants. Live#getQuestions() is still working however just Live#showQuestion() isn't as the server doesn't give a response...

**Comment by myhrmans** [comment]
Gets stuck in a while-loop of tries trying to make the request. Unable to stop after command is executed. Stream needs to be restarted.

**Comment by JRoy** [comment]
This has been fixed in 098bfa3.
