### ISSUE TITLE
Proxy Issues

### ISSUE THREAD

**Issue by xosad** [mgp25/Instagram-API#2487]
I've checked the other issues but couldn't make my code work, 

```
$ig = new \InstagramAPI\Instagram();
try {
    $ig->setUser($username, $password);
    $ig->setProxy('154.28.353.454:25742');
    $ig->login();

```

is there anything wrong with this code?

**Comment by mgp25** [comment]
Invalid issue.

You haven't:

- Followed issue template
- Provided debug log

Regards
