### ISSUE TITLE
deleteComment Issue

### ISSUE THREAD

**Issue by evil0angel** [mgp25/Instagram-API#249]
**你好～我发现了一个错误。Instagram.php里的deleteComment方法应该修改成**
```
public function deleteComment($mediaId, $commentId)
{
    $data = json_encode([
        '_uuid' => $this->uuid,
        '_uid' => $this->username_id,
        '_csrftoken' => $this->token,
        'comment_ids_to_delete' => $commentId,
    ]);

    return $this->request("media/$mediaId/comment/bulk_delete/", $this->generateSignature($data))[1];
}

```

**Comment by RageBrahimi** [comment]
You've altered the `deleteComment` from single to bulk (which we currently do not have the function for) therefore this isn't an issue.

I will add Bulk Comments at a later date.

**Comment by evil0angel** [comment]
When I use the `deleteCommen`, the response is 'oops an error occured'。

This is the request that I grabbed from the app to the request of the delete comment.

> POST /api/v1/media/1271770890049974143_3235271818/comment/bulk_delete/ HTTP/1.1
