### ISSUE TITLE
Getting error "Invalid Parameters" back, response 400 from Instagram.

### ISSUE THREAD

**Issue by SoufianAkh** [mgp25/Instagram-API#2490]
### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Example Code:
```php
<pre>
<?php
require 'instagram/vendor/autoload.php';
$debug = true;
$truncatedDebug = false;

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login("myusername", "mypass");

} catch (InstagramException $e) {
	echo "Error";
    print_r($e->getMessage());
    exit();
}
?>
```

Error Log/var_dump:
```php
Fatal error:  Uncaught exception 'InstagramAPI\InstagramException' with message 'Invalid Parameters' in /home/admin/web/xx.nl/public_html/xx/instagramuploader/instagram/vendor/mgp25/instagram-php/src/Instagram.php:185
Stack trace:
#0 /home/admin/web/xx.nl/public_html/xx/instagramuploader/test_login.php(11): InstagramAPI\Instagram->login('myusername', 'mypass')
#1 {main}
  thrown in /home/admin/web/xx.nl/public_html/xx/instagramuploader/instagram/vendor/mgp25/instagram-php/src/Instagram.php on line 185

```

Response:
```http
# Please provide your capture below, for example:
Array
(
    [0] => HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Vary: Accept-Language, Cookie
Content-Language: en
Date: Thu, 07 Feb 2019 01:56:04 GMT
Strict-Transport-Security: max-age=604800
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd; worker-src 'self' https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Set-Cookie: rur=PRN; Domain=.instagram.com; HttpOnly; Path=/; Secure
Set-Cookie: csrftoken=CvM1jezLQtl51pPCdxKmYc5GypTz55Un; Domain=.instagram.com; expires=Thu, 06-Feb-2020 01:56:04 GMT; Max-Age=31449600; Path=/; Secure
Connection: close
Content-Length: 87

    [1] => Array
        (
            [message] => Invalid Parameters
            [status] => fail
            [error_type] => missing_parameters
        )

)
```
---

### Describe your issue

Hello guys,

I've been using this library for a while until it stopped working back in October 2018, since then I didn't have time to catch up and update it.

I've just installed this entire library over again using composer, but once I try to login, it throws me an error talking about "invalid parameters". 
After throwing a print_r statement in the Instagram.php file, it became clear to me that this error is coming from Instagram with a 400 code response.

Do you know if this is occuring for more people, and what the possible solution might be?

I'd really appreciate it if anyone could take a look into this!

**Comment by JRoy** [comment]
Hello, are you using the `dev-master` version from composer?

**Comment by SoufianAkh** [comment]
No I'm using the normal version. Installed through the following command:

> composer require mgp25/instagram-php

**Comment by JRoy** [comment]
@SoufianAkh Try using `composer require mgp25/instagram-php dev-master` and try again.

Let me know if you have your problem after that.

**Comment by SoufianAkh** [comment]
>  [InvalidArgumentException]
>  Package mgp25/instagram-php at version dev-master has a PHP requirement inc
>  ompatible with your PHP version (5.5.38)

Seems that I have to upgrade my PHP first. The current version if Instagram-PHP doesn't require a newer PHP version, the dev-master version does.

Right now it's mid-night, I don't want to start upgrading PHP on my server to prevent issues this late.
I will upgrade my PHP tomorrow and report back to you.

What's the minimum PHP version for dev-master anyway?

Thanks for your quick responses!

**Comment by JRoy** [comment]
@SoufianAkh You probably need php7. Parts of the api will work on php5 but it's highly recommended that you upgrade to php7 for future proofing.

Good luck getting it working tomorrow!

**Comment by SoufianAkh** [comment]
Just upgraded PHP on my server to 7.2 and installed the dev-master version.
Problem seems to be solved and it works flawless!

Still not sure yet if the problem with the normal version had something to do with the PHP version or if the dev-master has fixed the specific issue.

Thanks for your time JRoy :+1:
