### ISSUE TITLE
markMediaSeen() - All story items must be instances of \InstagramAPI\Response\Model\Item.

### ISSUE THREAD

**Issue by Vakiyt** [mgp25/Instagram-API#2494]
I use `markMediaSeen` to mark seen to all posts first, anyway i get next error: `Something went wrong: All story items must be instances of \InstagramAPI\Response\Model\Item. `

I use this code:
```php
	$ig->login($username, $password);
	$userID = _$ig->people->getUserIdForName(_REDACTED_);
	$feed = $ig->story->getUserStoryFeed($userID);
	$feed = json_decode($feed, true);
	$itemsnew = $feed['reel']['items'];
	print_r($itemsnew);
	$ig->story->markMediaSeen($itemsnew, null);
	echo count($feed['reel']['items']);
	print_r($feed['reel']);
```

**Comment by mgp25** [comment]
Hello @Vakiyt,

You need to do it like this:

```php
	$ig->login($username, $password);
	$userID = $ig->people->getUserIdForName(_REDACTED_);
	$feed = $ig->story->getUserStoryFeed($userID);
	$itemsnew = $feed->getReel()->getItems();
	$ig->story->markMediaSeen($itemsnew, null);
	echo count($itemsnew);
```

Please, next time follow issue template or your issue will be closed directly.

I also recommend you reading the wiki and checking the examples for learning how to use the API properly.

Regards

**Comment by Vakiyt** [comment]
Ok thank you, i will.
