### ISSUE TITLE
Get Highlight Video URL

### ISSUE THREAD

**Issue by chiliad** [mgp25/Instagram-API#2495]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hello there! 
I was wondering after playing a bit with getUserFeed if there is any way to get highlighted stories video URL ? Only thing I can for now is pictures.

Thanks !

**Comment by mgp25** [comment]
Hello @chiliad,

Use [Story::getReelsMediaFeed()](https://github.com/mgp25/Instagram-API/blob/f44bcda037e06c83ce951575645dfe5b8e02b4e1/src/Request/Story.php#L201) and send the media id i the `user_ids` param.

Regards

**Comment by tawfek** [comment]
can i know how to user this function getReelsMediaFeed()
thank you for your time
