### ISSUE TITLE
How can I use searchTags?

### ISSUE THREAD

**Issue by wangkaihong** [mgp25/Instagram-API#2496]
I am using pagination example, I want to:

1) I want to search posts by tag
2) I saw you are suggesting searchTags function in git issues but I am not sure how to use it for example in pagination example. 
3) Is there a searchTags function in the code? When I search in github I cannot find it.

**Comment by JRoy** [comment]
Please follow the issue template! Next time you don't, your issue will be ignored.

The function you're looking for is: https://github.com/mgp25/Instagram-API/blob/22eb362bf60d3c1fc3191bee45e3c9cbeae5686c/src/Request/Hashtag.php#L136-L166
