### ISSUE TITLE
How to get location story

### ISSUE THREAD

**Issue by uriafranko** [mgp25/Instagram-API#2498]
Hey 
The updated Location getFeed isn't returning stories as its already gettings the sections...
I would recommend adding this function

>
    /**
     * Get the Story feed for a location.
     *
     * Note that if your location is a "group" (such as a city), the feed will
     * include stories from multiple locations within that area. But if your
     * location is a very specific place such as a specific night club, it will
     * usually only include stories from that exact location.
     *
     * @param string      $locationId The internal ID of a location (from a field
     *                                such as "pk", "external_id" or "facebook_places_id").
     * @param string      $rankToken  The feed UUID. Use must use the same value for all pages of the feed.
     * @param null|string $maxId      Next "maximum ID", used for pagination.
     *
     * @throws \InvalidArgumentException
     * @throws \InstagramAPI\Exception\InstagramException
     *
     * @return \InstagramAPI\Response\LocationFeedResponse
     *
     * @see Signatures::generateUUID() To create a UUID.
     * @see examples/rankTokenUsage.php For an example.
     */
    public function getFeedStory(
        $locationId,
        $rankToken,
        $maxId = null)
    {
        Utils::throwIfInvalidRankToken($rankToken);
        $locationFeed = $this->ig->request("feed/location/{$locationId}/")
            ->addParam('rank_token', $rankToken);
        if ($maxId !== null) {
            $locationFeed->addParam('max_id', $maxId);
        }
        return $locationFeed->getResponse(new Response\LocationFeedResponse())->getStory();
    }

And Adding 
`'story'                  => 'Model\StoryTray',`
To the location Feed response

**Comment by dsidious1** [comment]
@uriafranko Hi! How did you work with the cursor? It's not work for me.. I create issue in this thread but it was deleted.( Can you post any example from sniffer?

**Comment by mgp25** [comment]
Added in commit: https://github.com/mgp25/Instagram-API/commit/a1bb67840cf1513b792a84b7726a101f807d075c

**Comment by mgp25** [comment]
@JRoy could you rename the function I just pushed to `getStoryFeed()` since it makes more sense

Regards

**Comment by JRoy** [comment]
@mgp25 sure thing
