### ISSUE TITLE
[Question] the generation process of some instagram app tokens

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2501]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other
-
---
 
### Describe your issue

This question a bit out of the purpose of this api, but if someone had dig enough to know the answer for sure the person is in this group

I would like to know a bit more about: "phone_id", "uuid" , "device_id"

I know for this api purposes they are randomly generated on first login of every account... but how it works for real instagram app?

everytime i reinstall the app on the SAME PHONE will it generate a new "phone_id" and "device_id" ? or  will it read some hardware info to generate the values and then they will keep the same across several reinstalations?

Do multiple accounts on same phone share any of these values?

Is there any side effect if I keep the same values forever in my app?

**Comment by JRoy** [comment]
Hi, sorry for the late response. Your answer is here: https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L792-L821

All of these are just standard uuids that either get saved to local storage or generated at random on login.
