### ISSUE TITLE
approve

### ISSUE THREAD

**Issue by paolowu62** [mgp25/Instagram-API#2503]
Something went wrong: Requested resource does not exist.
<?php 
set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'/vendor/autoload.php';

/////// CONFIG ///////
$username = '';
$password = '';
$debug = true;
$truncatedDebug = false;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
$n = 1;
    $var = $ig->people->getPendingFriendships();
  $var->printPropertyDescriptions();
foreach($var->getUsers() as $rip){
echo json_encode($rip->getId(),JSON_PRETTY_PRINT);
echo $rip->getUsername().'accepted #'.$n;
$n = $n++;
echo "\n";
sleep(01);
$ig->people->approveFriendship($pending);
}
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

the method approveFriendship not work

**Comment by JRoy** [comment]
Please follow the issue template
