### ISSUE TITLE
[Question] is using new device list with old sig key can affect the api?

### ISSUE THREAD

**Issue by 8lbiasian** [mgp25/Instagram-API#2504]
### Purpose of your issue?

- [x ] Question

-------------------

I am not asking about how to get these values. 

now in GoodDevices.php 

I did add a new device for example 

    '27/8.1.0; 480dpi; 1080x2150; HUAWEI/HONOR; COL-L29; HWCOL; kirin970;',

and 

IG_VERSION = '76.0.0.15.395';

so if I go and use it does it make an issue with IG that I am using a new device with an old version of IG?? 

i read the comment about changing the devices list, so i am only updating to test around for my own so i hope this is not an issue for you.

**Comment by JRoy** [comment]
Changing the IG_VERSION constant is not recommend at all as it can lead to requests not working or requests not returning their intended response. As for modifying devices, support will not be given for that and it's at your own risk.

Regards
