### ISSUE TITLE
Bug with videos and story slider

### ISSUE THREAD

**Issue by tobiasmanroth** [mgp25/Instagram-API#2506]
### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)

I just noticed that the example code to post a story with a "story slider" does not work when using a video. I used exactly the same metadata but the slider does not show up in the story. When using the metadata with another API endpoint, I'm able to post a video story with a slider so it looks like this might be a bug in this API.

Cheers, Tobias

**Comment by JRoy** [comment]
What other endpoint are you using that's making this work?

**Comment by tobiasmanroth** [comment]
Instagram offers the functionality to post images from the web browser to the story. However this endpoint also works with videos and additional metadata if you post the right data.

**Comment by JRoy** [comment]
This api is emulating the android app, not the web client

**Comment by tobiasmanroth** [comment]
I just added this as an example. I used the latest dev-master of mgp25/Instagram-API to post a video to my story containing a slider question but it was not visible.

**Comment by JRoy** [comment]
oh sorry for the misunderstanding

**Comment by tobiasmanroth** [comment]
See: https://github.com/mgp25/Instagram-API/pull/2519

**Comment by JRoy** [comment]
Fixed in 460bceb

Cheers!
