### ISSUE TITLE
Remove/Disable Proxy when it is already set?

### ISSUE THREAD

**Issue by sukhcha-in** [mgp25/Instagram-API#2507]
### I have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of my issue:
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [x] Other

---

### My issue:

Hello,
Is there any way to remove proxy settings at a certain point once it is already set?
I want to retrieve user profile data without using proxy because proxy makes my app really slow.
Thanks.

**Comment by JRoy** [comment]
No, it's not a good idea to switch ip addresses while making requests under the same session. Especially when using a 3rd party api.

**Comment by sukhcha-in** [comment]
If someone is looking for a solution to this, you can implement like this way:

Inside `mgp25/instagram-php/src/Instagram.php` add this function:
```
/**
  * Unset proxy for requests.
  *
  */
public function unsetProxy()
{
    $this->client->unsetProxy();
}
```
and inside `mgp25/instagram-php/src/Client.php` add this function:
````
/**
 * Unset proxy for requests.
 *
 */
public function unsetProxy()
{
    $this->_proxy = null;
    $this->_resetConnection = true;
}
````
That's it, now you can use it like this after setting a proxy: `$ig->unsetProxy();`
