### ISSUE TITLE
How to take more result in suggested user

### ISSUE THREAD

**Issue by Nasirinejad** [mgp25/Instagram-API#2508]
Hi I want to take more suggestion in one request.
I tried these requests:
`fbsearch/suggested_searches/?type=users&user_num=60`
`fbsearch/suggested_searches/?type=users&count=60`
`fbsearch/suggested_searches/?type=users`
but all response same result with 4 suggested users!
what i should to do?

**Comment by JRoy** [comment]
**Please** follow the issue template! Future issues that don't follow the template will be ignored!

Anyway, the request you're looking for is `People#getSuggestedUsersBadge()`
