### ISSUE TITLE
LIke - Action blocked

### ISSUE THREAD

**Issue by ptakptakptak** [mgp25/Instagram-API#2510]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X ] Question
- [ ] Other

---

### Describe your issue

- I have installed clean version of new InstagramAPI via composer
- First I had problems with logging in to my account (checkpoint_required) but managed to solve it using code from #2143 
- I tried to like first photo - Success
- I tried to like second photo and I get "Action blocked" ("Based on previous use of this feature, your account has been temporarily blocked from taking this action. This block will expire on 2019-02-15. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.")
- Manually liking stopped working as well now
- Commenting/Following via API works normally. Only liking does not

That looks strange, as:
- i have used an account which has never been connected via API
- i didn't manually like more than about 20 photos a day
- i have used clean IP

Guys, do you have any suggestion why it does not work?

THanks for your help

**Comment by JRoy** [comment]
Instagram's almighty AI is unpredictable. It's possible you're preforming unusually than you normally do, but it's impossible to know for sure
