### ISSUE TITLE
[Feature Request] Edit Video/Album Thumbnails

### ISSUE THREAD

**Issue by claude-wishnote** [mgp25/Instagram-API#2521]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
I posted some single videos and video albums. now, I want to update's some videos's thumbnail.
But how to update a posted video's thumbnail.
`$ig->media->edit($id,'update the captionText',$metadata,'VIDEO');`

**Comment by JRoy** [comment]
This feature is not present on the Android App therefore it cannot be added to the api.

Cheers.

**Comment by claude-wishnote** [comment]
> This feature is not present on the Android App therefore it cannot be added to the api.
> 
> Cheers.

thank you very much~
