### ISSUE TITLE
get saved lives from special user with userId

### ISSUE THREAD

**Issue by farzad119** [mgp25/Instagram-API#2522]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Hello there
i want to get saved lives from special user with userId
i try request to ```feed/user/{$userId}/story/``` but it only return stories that profile.
how can i do this?

**Comment by JRoy** [comment]
[`Story#getReelsTrayFeed`](https://github.com/mgp25/Instagram-API/blob/f44bcda037e06c83ce951575645dfe5b8e02b4e1/src/Request/Story.php#L124) has the getPostLive() function that has data for all accounts you follow. As for one specific user, I don't think we have that data as of yet. I'll look into this more tomorrow.

**Comment by JRoy** [comment]
Hello, I've done some research and I found that this data indeed is in the API, you can get it by doing [`Story#getUserStoryFeed($userId)`](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php#L175) and using getPostLiveItem() from the response.

Regards
