### ISSUE TITLE
get Unknown Server Error when $ig->story->uploadPhoto

### ISSUE THREAD

**Issue by danielcardoso** [mgp25/Instagram-API#2524]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ X [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
// uploadStory.php example file

set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

/////// CONFIG ///////
$username = '';
$password = '';
$debug = true;
$truncatedDebug = false;
//////////////////////

/////// MEDIA ////////
$photoFilename = '';
//////////////////////

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

// You don't have to provide hashtags or locations for your story. It is
// optional! But we will show you how to do both...

// NOTE: This code will make the hashtag area 'clickable', but YOU need to
// manually draw the hashtag or a sticker-image on top of your image yourself
// before uploading, if you want the tag to actually be visible on-screen!

// NOTE: The same thing happens when a location sticker is added. And the
// "location_sticker" WILL ONLY work if you also add the "location" as shown
// below.

// NOTE: And "caption" will NOT be visible either! Like all the other story
// metadata described above, YOU must manually draw the caption on your image.

// If we want to attach a location, we must find a valid Location object first:
try {
    $location = $ig->location->search('40.7439862', '-73.998511')->getVenues()[0];
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

// Now create the metadata array:
$metadata = [
    // (optional) Captions can always be used, like this:
    'caption'  => '#test This is a great API!',

    // (optional) To add a hashtag, do this:
    'hashtags' => [
        // Note that you can add more than one hashtag in this array.
        [
            'tag_name'         => 'test', // Hashtag WITHOUT the '#'! NOTE: This hashtag MUST appear in the caption.
            'x'                => 0.5, // Range: 0.0 - 1.0. Note that x = 0.5 and y = 0.5 is center of screen.
            'y'                => 0.5, // Also note that X/Y is setting the position of the CENTER of the clickable area.
            'width'            => 0.24305555, // Clickable area size, as percentage of image size: 0.0 - 1.0
            'height'           => 0.07347973, // ...
            'rotation'         => 0.0,
            'is_sticker'       => false, // Don't change this value.
            'use_custom_title' => false, // Don't change this value.
        ],
        // ...
    ],

    // (optional) To add a location, do BOTH of these:
    'location_sticker' => [
        'width'         => 0.89333333333333331,
        'height'        => 0.071281859070464776,
        'x'             => 0.5,
        'y'             => 0.2,
        'rotation'      => 0.0,
        'is_sticker'    => true,
        'location_id'   => $location->getExternalId(),
    ],
    'location' => $location,

    // (optional) You can use story links ONLY if you have a business account with >= 10k followers.
    // 'link' => 'https://github.com/mgp25/Instagram-API',
];

try {
    // This example will upload the image via our automatic photo processing
    // class. It will ensure that the story file matches the ~9:16 (portrait)
    // aspect ratio needed by Instagram stories. You have nothing to worry
    // about, since the class uses temporary files if the input needs
    // processing, and it never overwrites your original file.
    //
    // Also note that it has lots of options, so read its class documentation!
    $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename, ['targetFeed' => \InstagramAPI\Constants::FEED_STORY]);
    $ig->story->uploadPhoto($photo->getFile(), $metadata);

    // NOTE: Providing metadata for story uploads is OPTIONAL. If you just want
    // to upload it without any tags/location/caption, simply do the following:
    // $ig->story->uploadPhoto($photo->getFile());
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

```

{"message": "Unknown Server Error.", "status": "fail"}

---

### Describe your issue

I was trying to post a story.

**Comment by make-it-git** [comment]
Same issues for me. Carousel posting works fine with exactly same photos.

**Comment by tobiasmanroth** [comment]
I'm facing the same issue but from time to time the story image post is successful.
Story videos seem to succeed everytime though.

**Comment by mgp25** [comment]
@danielcardoso can you provide full debug log?

**Comment by make-it-git** [comment]
@tobiasmanroth I can confirm this, from time to time timeline image is posted.
But most times it returns an error

POST: https://i.instagram.com/api/v1/media/configure/?timezone_offset=10800 DATA: signed_body=ad661e913ffaa7285a8c1d80550c11883d1613317d10113caa3a93ba1c92401d.{"device":{"manufacturer":"HUAWEI","model":"LON-L29","android_version":"24","android_release":"7.0"},"date_time_digitalized":"2019:02:20 19:29:33","_csrftoken":"CENSORED","media_folder":"Camera","source_type":"4","_uid":"CENSORED","_uuid":"CENSORED","edits":{"crop_original_size":[1080,1080],"crop_zoom":1,"crop_center":[0,-0]},"extra":{"source_width":1080,"source_height":1080},"caption":"","date_time_original":"2019:02:20 19:29:33","upload_id":"242968089702393"}&ig_sig_key_version=4 ← 500 54B RESPONSE: {"message": "Unknown Server Error.", "status": "fail"}

I was able to "fix" this by resizing image to lower size (let's say, 500x500 pixels) and it is posted successfully every time.

**Comment by tobiasmanroth** [comment]
I think I've got a hint on that: When I reduce the filesize by reducing the jpeg quality, it succeeds more often (or everytime? Needs to be checked).

**Comment by danielcardoso** [comment]
**Update**!
I am closing this issue because it looks like it's an Instagram issue.
I reduced the file size and it worked... Also just a note for other developers, instead of uploading a PNG image I am uploading a JPEG @ 80%, because it reduces a lot the file size.

For me it's working at this moment.

Thanks for the support :)

**Comment by holden321** [comment]
I started to use the api in autumn 2018 and never face this error. But today after updating the api to the latest version, I started to face the error in 60% of all posts. So it is obviously something changed in the api that make the error appear more often than before. It is not only instagram issue.

$photo = new \InstagramAPI\Media\Photo\InstagramPhoto($data['photo']);
$tmpFilenameProcessed = $photo->getFile();
$response = $this->_instagramAPI->timeline->uploadPhoto($tmpFilenameProcessed, $metaData);

**Comment by mgp25** [comment]
@holden321 this will be fixed soon, I have already identified the issue

Regards

**Comment by holden321** [comment]
@mgp25 I am really sorry for such a question but when to expect the fix?

**Comment by sergeykomlev** [comment]
@holden321 this issue fixed yet?

Image reducing and resizing help me fix this "Unknown Server Error" in most times, but sometimes it's happened again.

**Comment by mgp25** [comment]
#2665
