### ISSUE TITLE
Copyright live feature block

### ISSUE THREAD

**Issue by yoosef** [mgp25/Instagram-API#2526]
Hi
when I am sending live to instagram, there is an error message which cause to stop live. I tried to restart the sending live process, but the error is preventing from sending live. After a while the error is ignored and everything came to normal state.
How can I prevent from occurring this error message ?
I have long continues live event about 6 hours in a day.

Error While Creating Livestream: InstagramAPI\Response\StartLiveResponse: Copyright live feature block.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.1
InstagramLive-PHP Flavor: stable
Operating System: Linux
PHP Version: 7.2.15-0ubuntu0.18.04.1
PHP Runtime: cli
PHP Binary: /usr/bin/php7.2
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
Exception: InstagramAPI\Response\StartLiveResponse: Copyright live feature block.
============END DUMP============

**Comment by JRoy** [comment]
Follow the issue template next time, and this is due to you playing copyright music or content on a Livestream.
