### ISSUE TITLE
Getting Signed Post Request for Login

### ISSUE THREAD

**Issue by engine22** [mgp25/Instagram-API#2528]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ x] Question
- [ ] Other

---

Hi, 

I was wondering if anyone knew a way how I can get the signed POST requests for login without actually submitting the CURL request for logging in?

When i try the following:
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->login($username, $password);

It goes for the login. I'd like to find a way where I can read the POST request's body and headers without actually sending it to Instagram.

**Comment by JRoy** [comment]
Look at the source code
