### ISSUE TITLE
Add gif to story image

### ISSUE THREAD

**Issue by hebbars** [mgp25/Instagram-API#2529]
### Describe your issue

Hey, can we have the feature to embed gif on top of the story image? Refer the screenshot for more info

![fullsizerender](https://user-images.githubusercontent.com/13349299/53278965-f64adc00-3760-11e9-98b7-9c0059df03e3.jpeg)

**Comment by JRoy** [comment]
GIFs are taken directly from the giphy api, not Instagram. Additionally, they are placed onto the image client side. You'll need to do this yourself.

Cheers.
