### ISSUE TITLE
How can i get twoFactorIdentifier after passing challenge?

### ISSUE THREAD

**Issue by sukhcha-in** [mgp25/Instagram-API#2533]
### Before submitting an issue i have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [x] Other

---

### Example from mgp25: [#issuecomment-412613011](https://github.com/mgp25/Instagram-API/issues/2143#issuecomment-412613011)

```php

//this is the custom response we get after submitting challenge
$customResponse = $ig->request($checkApiPath)
		     ->setNeedsAuth(false)
		     ->addPost('choice', $verification_method)
		     ->addPost('_uuid', $ig->uuid)
		     ->addPost('guid', $ig->uuid)
		     ->addPost('device_id', $ig->device_id)
		     ->addPost('_uid', $ig->account_id)
		     ->addPost('_csrftoken', $ig->client->getToken())
		     ->getDecodedResponse();
```

---

### Response:

```json
{
  "action" => "close",
  "status" => "ok"
}
```
---

### Describe your issue

I am testing challenge required from long time and I have turned on two-factor authentication on my account as well.
So when I submit challenge and when it verifies successfully it gives me `response` as stated above.
Alongside it also sends me two factor authentication code even without requesting it.
How can i identify if two-factor is on after submitting a challenge?
How can i get `getTwoFactorIdentifier()` so that i can submit two-factor code?

If i try to pass login() function again after challenge is completed, it sends me new two-factor code on my phone. Now i receive two text messages instead of one.

**Comment by sukhcha-in** [comment]
@mgp25 thanks for this great API, but is my question not valid?
I know you're not supporting login questions anymore but there is no info about this problem.
Am i doing something wrong or there is no way of checking two factor after passing challenge?

**Comment by mgp25** [comment]
Hello @sukhcha-in,

This question has been answered multiple times, that is why the issue was closed directly. Also we don't give support about challenge or related issues.

We recommend searching in closed issues, reading wiki and checking examples before opening a new issue:

- [/examples/twoFactorLogin.php](https://github.com/mgp25/Instagram-API/blob/master/examples/twoFactorLogin.php)

Regards

**Comment by sukhcha-in** [comment]
@mgp25 thanks, will try to figure out.

**Comment by AndreyPesotskiy** [comment]
Hey @sukhcha-in ,
Did you find a solution to the problem?

**Comment by sukhcha-in** [comment]
@AndreyPesotskiy No, i still receive two messages for twofactor.
