### ISSUE TITLE
How many times we must generate ranktoken?

### ISSUE THREAD

**Issue by majidrajabi** [mgp25/Instagram-API#2534]
We generate a ranktoken for calling some functions. Is it permitted to use of that same generated ranktoken for rest of the requests which we send?
How many time we can generate ranktoken?

**Comment by JRoy** [comment]
Please refer to the examples before opening issues, as well as follow the issue template!

Relevant Example:
[rankTokenUsage.php](https://github.com/mgp25/Instagram-API/blob/master/examples/rankTokenUsage.php)
