### ISSUE TITLE
gzip some endpoints

### ISSUE THREAD

**Issue by ivanyadeshko** [mgp25/Instagram-API#2540]
*improvement*
Hi, to every one!
I'm detecting strange Instagram behavior on feed/timeline endpoint.
On my phone i see many pagination requests, an see pagination requests, But POST body encripted O_o ... and cannot be read.

In Instagram-API script, POST body send on Instagram not cripted. I think, next time will cause considerable problems.

APP: 76.0.0.15.395
Device: Nexus 5

**Comment by ivanyadeshko** [comment]
And i am dont see pagination point on instagram response
http://joxi.ru/12MWx9OhlgLyWr
but in my phone over 100 medias in timeline feed

**Comment by JRoy** [comment]
Will look into this

**Comment by valga** [comment]
@ivanyadeshko It's not encrypted. It's just compressed with gzip. 

@JRoy This behavior is controlled with `ig_android_request_compression_universe` experiment. It has following params:
* `use_for_feed` - `feed/timeline/` endpoint;
* `use_for_qe` - `qe/sync/` endpoint;
* `use_for_stories` - ??

When enabled, POST body must be compressed with gzip, and headers must contain `Content-Encoding: gzip` one.

**Comment by JRoy** [comment]
@valga I just tested those experiments and they appear to not be present in the account I know to be using gzipped content. Maybe in v82, gzip is the norm?

**Comment by valga** [comment]
@JRoy This experiment has been changed in 82. Now it's called `ig_android_request_compression_launcher` and has only 2 params:
* `use_for_feed`;
* `use_for_stories`.

Also gzip compression is now always enabled for `address_book/link/` endpoint and some ads-related one.
