### ISSUE TITLE
Question & Help - Upload video to stories

### ISSUE THREAD

**Issue by hebbars** [mgp25/Instagram-API#2541]
First of all thanks for this wonderful API. I was able to use it for my page. Having said that I am new to PHP and struggling to upload videos to Stories. I am able to upload photos to stories though.

I am getting the aspect ratio error for my *.mp4 videos. Note that these videos are generated from image magick software by merging a photo and gif. I was able to upload the same video directly via Insta APP but not with this PHP API. 

I have gone through your examples and your issues, but I could not get any lead. I request you to help me and point me to rite directions about this issue? Also is there any PHP class which can convert to the required instagram aspect ratio? Please help for the same.

**Comment by JRoy** [comment]
The app automatically changes the aspect ratio for you, we don't. You'll have to alter these yourself.

Regards.

**Comment by hebbars** [comment]
Thanks for the reply. Any particular PHP module if you can refer me to begin with. It will be great help

**Comment by JRoy** [comment]
If you had a 16:9 video (for example in 1920x1080 to an 9:16 ratio (stories requirement) you could do this in ffmpeg: `ffmpeg -i video.mp4 -vf scale=1080:1920 video_story.mp4 -hide_banner`

**Comment by hebbars** [comment]
I tried with the above syntax, still getting the same aspect ratio error. no luck. In addition, I downloaded the video uploaded by the Instagram app and then tried to upload the same video via PHP API, it complains about the same issue. Looks like a potential bug?

**Comment by mgp25** [comment]
```php
    $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename, ['targetFeed' => \InstagramAPI\Constants::FEED_STORY]);
    $ig->story->uploadPhoto($photo->getFile(), $metadata);
```
