### ISSUE TITLE
Can't follow on the person

### ISSUE THREAD

**Issue by AlexUlianets** [mgp25/Instagram-API#2543]
One of my account sometimes can't follow on any account. No errors in the response:

$ig->people->follow($pk)->asArray()

Response:

status=ok
following=false
outgoing_request=false

I tried to change proxy and waited for two days, but nothing. Also from my account through the instagram app, i don't have any problems with following.

It is very strange, because if errors exist, API gives response, but here all is ok.

I CAN give you my account credentials, you can check that no errors it doesn't have

**Comment by JRoy** [comment]
Please follow the issue template, next time you don't your issue will be closed without warning.

As for this, please enable debug mode and send the debug logs of when you do this request

**Comment by mgp25** [comment]
Hello @AlexUlianets ,

Your IP is flagged, try using different one.

Regards

**Comment by AlexUlianets** [comment]
I tried to change different proxy, but nothing, my debug is enabled:)

**Comment by AlexUlianets** [comment]
@JRoy ok no problem, no logs:((

**Comment by AlexUlianets** [comment]
If i wait some hours it works, but sometimes no((
