### ISSUE TITLE
media->getInfo() error

### ISSUE THREAD

**Issue by lewbor** [mgp25/Instagram-API#2544]
There is a error while executing 
```php
$mediaId = '1772128724164452834';
$mediaInfo = $ig->media->getInfo($mediaId);
```

$mediaId value taken from examples/sharePhotoToStoryFeed.php, but other ids also does not working.
Debug log is 
`
POST:  https://i.instagram.com/api/v1/media/1772128724164452834/info/
DATA: signed_body=f9a27de73a4325d3efb453845a2908e6c4a582b3b8d54284ef6968ef46ad52bf.{"media_id":"1772128724164452834","_csrftoken":"pUlCTBZPvajnROBNrlNiZe2NK8Aki01Q","_uid":"10969244114","_uuid":"e498e4f9-eb0e-4c5f-9923-4ab48d327183"}&ig_sig_key_version=4

← 405    0B
RESPONSE: 
`
Exception is: No response from server. Either a connection or configuration error. 
$ig using socks5 proxy. login() with credentials and followers search before call media->getInfo() works fine.

**Comment by lewbor** [comment]
Probably error is that request using POST method (need GET). Changes in https://github.com/mgp25/Instagram-API/commit/b7f1d9812d4dbca5a3eee8f5c45cfcd1c8240775#diff-d8d5c3f8c67f59dbc95eded8c6ed5b20
After commenting addPost() calls getInfo() work fine..

**Comment by JRoy** [comment]
I'll look into this

**Comment by mgp25** [comment]
@JRoy discord

**Comment by mgp25** [comment]
@lewbor Make sure you are using dev-master. This was commented in another issue and updated:

```php
    public function getInfo(
        $mediaId)
    {
        return $this->ig->request("media/{$mediaId}/info/")
            ->getResponse(new Response\MediaInfoResponse());
    }
```

Request tested and working fine.

Regards
