### ISSUE TITLE
Upload photo in timeline returns ok but Instagram not posted it

### ISSUE THREAD

**Issue by luanecomp** [mgp25/Instagram-API#2545]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
### Describe your issue

Hello, I uploaded an image to the instagram timeline, it returns OK but the image was not posted to the timeline.
The post in the stories works normally.

The instagram return is:

{ "media": { "taken_at": "1551450242", "pk": "1990031324127579737", "id": "1990031324127579737_6097709197", "device_timestamp": "386641252565009", "media_type": 1, "code": "BueAvIWhk5Z", "client_cache_key": "MTk5MDAzMTMyNDEyNzU3OTczNw==.2", "filter_type": 0, "comment_likes_enabled": false, "comment_threading_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "preview_comments": [], "can_view_more_preview_comments": false, "comment_count": 0, "image_versions2": { "candidates": [ { "width": 630, "height": 354, "url": "https:\/\/scontent-lga3-1.cdninstagram.com\/vp\/5148b2bca87e2b5935599458a90c6f3e\/5D162CD8\/t51.2885-15\/e35\/51683089_1181324392037070_7444481099070441518_n.jpg?_nc_ht=scontent-lga3-1.cdninstagram.com&ig_cache_key=MTk5MDAzMTMyNDEyNzU3OTczNw%3D%3D.2" }, { "width": 240, "height": 134, "url": "https:\/\/scontent-lga3-1.cdninstagram.com\/vp\/f1997ef17ff9ee38c57ce40d26fcfd27\/5D0B36E1\/t51.2885-15\/e35\/s240x240\/51683089_1181324392037070_7444481099070441518_n.jpg?_nc_ht=scontent-lga3-1.cdninstagram.com&ig_cache_key=MTk5MDAzMTMyNDEyNzU3OTczNw%3D%3D.2" } ] }, "original_width": 630, "original_height": 354, "user": { "pk": "xxxxxxx", "username": "xxxxxx", "full_name": "xxxxx", "is_private": false, "profile_pic_url": "https:\/\/scontent-lga3-1.cdninstagram.com\/vp\/df822503d2bde4f965c45bcf4aa49759\/5D1729EA\/t51.2885-19\/s150x150\/43621836_2048598708532994_3554115540865777664_n.jpg?_nc_ht=scontent-lga3-1.cdninstagram.com", "profile_pic_id": "1611769216578686258_6097709197", "has_anonymous_profile_picture": false, "can_boost_post": false, "can_see_organic_insights": false, "show_insights_terms": false, "reel_auto_archive": "unset", "is_unpublished": false, "allowed_commenter_type": "any" }, "can_viewer_reshare": true, "caption": null, "caption_is_edited": false, "photo_of_you": false, "fb_user_tags": { "in": [] }, "can_viewer_save": true, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjIwOGU3ZDJjYTQ0YTRkNjdhMGU5ODY2YTc1NzA3M2RjMTk5MDAzMTMyNDEyNzU3OTczNyIsInNlcnZlcl90b2tlbiI6IjE1NTE0NTAyNDQxOTJ8MTk5MDAzMTMyNDEyNzU3OTczN3w2MDk3NzA5MTk3fDc3ODcyOGRlYmVlMGQ5YWExOGJlZDVlMzBhODg0ZmI1M2Q2YzdkYmZmMWRhNjg4YWIwMTFmOTY2MDY3MWVlZTYifSwic2lnbmF0dXJlIjoiIn0=" }, "upload_id": "386641252565009", "status": "ok" }

**Comment by mgp25** [comment]
Hello @luanecomp,

Your IP is flagged, try using different one.

Regards

**Comment by luanecomp** [comment]
It's weird for me. Stories work pretty well.
Well, thanks so much anyway.
