### ISSUE TITLE
using with instagramm app

### ISSUE THREAD

**Issue by brbear** [mgp25/Instagram-API#2562]
---

### Before submitting an issue make sure you have:
- [+] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [+] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [+] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [+] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [+] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [+] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [+] Question
- [ ] Other

---

### Describe your issue

Hello,

I want to use your api in my new service and I want to know something. I can't find answers in f.a.q. This service will get some money, it is commercial using.

Tell me please, can I use it with Instagram official api? 

2) Instargram api need approving from Instagram - can I use your api without approving? Is it legal for commercial using?

3) In my service will be approximately 10-000 people, will your api work correct?

**Comment by JRoy** [comment]
For both of your questions: https://github.com/mgp25/Instagram-API/blob/master/LICENSE and #1231 should be good things to look over.

Regards.
