### ISSUE TITLE
Story Question Responses?

### ISSUE THREAD

**Issue by humet** [mgp25/Instagram-API#2571]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hi,

I've been having a look through the API and I'm wanting to know if it's possible to fetch responses to story questions? I don't think I can see it anywhere currently.

Thanks

**Comment by JRoy** [comment]
When you fetch your story feed, they are in the response.

Cheers.

**Comment by humet** [comment]
When I've fetched a story feed using getUserStoryFeed(), all I can see is who has seen the story, not the question responses. Is there a different function for getting the logged in story feed?

**Comment by JRoy** [comment]
If you look at my commit that added this functionality (https://github.com/mgp25/Instagram-API/commit/f44bcda037e06c83ce951575645dfe5b8e02b4e1) You'd see that you can use the getStoryQuestions() function on an Item model to get the info.

Cheers.
