### ISSUE TITLE
Question about fields in Business Account getAccountInsightsUnit() response 

### ISSUE THREAD

**Issue by 8lbiasian** [mgp25/Instagram-API#2575]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Question

### Describe your issue

I am trying to build Graph similar to what we have in IG App
so I am trying to get all functions and fields 

but I saw some fields when I call this 

$Business->getData()->getUser()->getBusinessManager()->getAccountInsightsUnit()

I got an array having a list of functions or endpoints whatever its called 
I found this 

```
aymt_instagram_account_insights_channel: {
    tips: { },
    id: "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    channel_id: "1111111111111111"
},
```
so my question is what is this, or i dont need it.

also i have this 

```
graph: {
   nodes: {
           0: {
               delta: ""
           }
   }
},
metric_graph: {
   nodes: {
           0: {
               total: "0",
               graph_name: "FOLLOWERS",
               data_points: { }
           },
           1: {
              total: "0",
              graph_name: "UNFOLLOWERS",
              data_points: { }
          }
   }
}

```

so i dono why this graph for exactly as it have zero information and in metric_graph its have followers and unfollowers but again with zero things so i dono what it should have either in app i dont saw something similar to this 

sorry if my question is not that much clear i hope someone understand me and answer me. if its not related then close it

**Comment by mgp25** [comment]
Hello @8lbiasian, documentation for properties and responses are missing and we will be filling the missing information as we know which properties/values are those.

I am sorry I can't provide you more details about this, but it requires some time verifying and researching every value.

Regards
