### ISSUE TITLE
 story highlight backup 

### ISSUE THREAD

**Issue by bisht-sanjeet** [mgp25/Instagram-API#2578]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

hello, 
I'm using this API from a long time. 
Recently I used backup and saw backup function is not creating story highlight backup 
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php#L423
Nor its in new version 
https://github.com/mgp25/Instagram-API/blob/v82-changes/src/Request/Timeline.php#L423

Can you please add story highlights in it? :D 
It will be awesome :) 

Thanks :)

**Comment by mgp25** [comment]
Hello @bisht-sanjeet,

We will eventually add this, but this is not our top priority at the moment. If you add this feature, send a PR and we will be happy to review it and merge it.

Regards
