### ISSUE TITLE
Upload media with Location

### ISSUE THREAD

**Issue by ivanyadeshko** [mgp25/Instagram-API#2579]
Hi guys!
I'm debbuging uploading photo to user feed, and see facebook_places_id, But this param generate InvalidArgumentException. Its old code ? =)

Intercepted request from my real phone:
Endpoint: https://i.instagram.com/api/v1/media/configure/
POST: signed_body=19c84e2ef838b9cb5cf48dd6bc04d47c1fe139aca906363d75991308ac6975a7.{
	"timezone_offset":"10800",
	"_csrftoken":"SOsYpjQjs8ePwVqY5zAny84T6XYnYPuU",
	"media_folder":"Download",
	"source_type":"4",
	"_uid":"11233412175",
	"_uuid":"34a8817e-0663-480a-b688-03d2da096457",
	"caption":"",
	"upload_id":"375108331316234",
	"location":"{
		\"name\":\"Sochi,+Russia\",
		\"address\":\"Sochi\",
		\"lat\":43.5853,
		\"lng\":39.7203,
		\"external_source\":\"facebook_places\",
		\"facebook_places_id\":\"116273651719563\"
	}",
	"suggested_venue_position":-1,
	"device":{"manufacturer":"LGE","model":"Nexus+5","android_version":23,"android_release":"6.0.1"},
	"edits":{
		"crop_original_size":[640.0,640.0],
		"crop_center":[0.0,-0.0],"crop_zoom":1.0
	},
	"extra":{"source_width":640,"source_height":640},
	"is_suggested_venue":false
}&ig_sig_key_version=4

Nexus 5
App: 76.0.0.15.395

**Comment by ivanyadeshko** [comment]
Now, after some upload tests,  i'm shure. Ig dont displaying location without facebook_places_id.
Its Bug!

**Comment by zabidok** [comment]
If I rigth - you can use ONLY facebook_places_id param, withoout name, lat, etc

**Comment by mgp25** [comment]
No code was provided. Will open this with code is published along with the response and API version

Regards

**Comment by ivanyadeshko** [comment]
If i using IG(mgp25) emulate code from master brunch, app sending request without facebook_places_id in location container. Result: media successful uploaded, but without Place.
If i'm change your(mgp25) code (add facebook_places_id to configure request), when media published with Place point.
For all configure requets, i'm receive standart ig response

For debug i'm using Android App: 76.0.0.15.395 and says it upper

What other data you need to show, don't know ?
