### ISSUE TITLE
ffmpeg crop bug

### ISSUE THREAD

**Issue by claude-wishnote** [mgp25/Instagram-API#2580]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
![image](https://user-images.githubusercontent.com/7498634/54907379-54b1d880-4f20-11e9-88f0-40a1f0b14599.png)

My source videos are 1920*1080 videos, but sometimes ffmpeg cropped to "w=1915:h=1080".

and i print the cmd:
ffmpeg' -v error -y  -i '/home/ubuntu/tmp/0350afd90b113a39e674fa6ba1f299de_59_71.mp4' -vf 'crop=w=1915:h=1080:x=2:y=0,scale=w=720:h=406,pad=w=720:h=406:x=0:y=0:color=0x000000' -metadata:s:v rotate="" -f mp4 -c:v libx264 -preset fast -crf 24 -c:a copy '/tmp/INSTAVID_WFJuBD'

**Comment by JRoy** [comment]
We aren't ffmpeg. Please don't ask for help nor support about ffmpeg on this repo.
