### ISSUE TITLE
Deleting media with type: CAROUSEL

### ISSUE THREAD

**Issue by ivanyadeshko** [mgp25/Instagram-API#2584]
I am checking deleting media files, and dont see type **ALBUM**
IG change type **ALBUM** to **CAROUSEL**

_Need change code in: Utils::checkMediaType()_

Device: Nexus 5
App: 76.0.0.15.395

**Comment by mgp25** [comment]
Updated in latest commit: https://github.com/mgp25/Instagram-API/commit/4c18d7f2c4f17a0d9c1cfe5d7c6fa0c9b0ff754b
