### ISSUE TITLE
Is it possible change accept language? 

### ISSUE THREAD

**Issue by jmakuf** [mgp25/Instagram-API#2585]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---
Is it possible change accept language. 

---

In the file 
mgp25/instagram-php/src/Constants.php seting english language

```php
    const ACCEPT_LANGUAGE = 'en-US'; // "language-COUNTRY".
```
How can I change this language to ru-RU?

**Comment by valga** [comment]
@jmakuf You can change it in your project with [composer-patches](https://github.com/vaimo/composer-patches) plugin.

But take in mind that we use error messages to detect critical errors: https://github.com/mgp25/Instagram-API/blob/05676aa616a3071396618e5f799f813507cf2532/src/Exception/ServerMessageThrower.php#L58-L86
