### ISSUE TITLE
Parsing comments issue

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2586]
I have an issue with collecting comments.
After some time - instagram returns nextMinId = null, and I am unable to get other post comments.

Code sample: 
         
     protected function collectCommentsByPaginationKey(string $mediaId, string $key = 
     'min_id'): array
    {
        $collectedComments = [];
        $paginationKeyValue = null;
        do {
            try {
                $comments = InstagramProvider::get()->media->getComments($mediaId, [$key => $paginationKeyValue]);
                echo "Comments by {$key}" . PHP_EOL;
                if (!$comments->getComments()) {
                    echo '!comments->getComments() ' . $mediaId . PHP_EOL;
                }

                foreach ($comments->getComments() as $comment) {
                    $collectedComments[$comment->getPk()] = [
                        'comment_id'          => $comment->getPk(),
                        'username'            => $comment->getUser()->getUsername(),
                        'user_id'             => $comment->getUser()->getPk(),
                        'comment'             => $comment->getText(),
                        'time'                => $comment->getCreatedAt(),
                        'comment_likes_count' => $comment->getCommentLikeCount() ?: 0
                    ];
       
                $paginationKeyValue = $key === 'min_id' ? $comments->getNextMinId() : $comments->getNextMaxId();
            } catch (Throwable $exception) {
                echo 'Error while collecting comments: ' . $exception->getMessage() . PHP_EOL;
            }
        } while ($paginationKeyValue !== null);

        return $collectedComments;
    }

And my logs 

    [2019-03-27 09:05:27] gameDebug12.INFO: 1562 Comments Collected in: 323.4 sec  
    [2019-03-27 09:11:28] gameDebug12.INFO: 1999 Comments Collected in: 324.22 sec 
    [2019-03-27 09:37:51] gameDebug12.INFO: 1624 Comments Collected in: 347.17 sec  
    [2019-03-27 07:19:35] gameDebug12.INFO: 1393 Comments Collected in: 271.39 sec 

But post has 5000 comments

**Comment by valga** [comment]
@AndManowar You have to walk through the threads.

https://github.com/mgp25/Instagram-API/blob/05676aa616a3071396618e5f799f813507cf2532/src/Response/Model/Comment.php#L160-L189

https://github.com/mgp25/Instagram-API/blob/05676aa616a3071396618e5f799f813507cf2532/src/Request/Media.php#L395-L418
