### ISSUE TITLE
Something went wrong: InstagramAPI\Response\ConfigureResponse: Upload id is None

### ISSUE THREAD

**Issue by fabiofns** [mgp25/Instagram-API#2587]
Hi guys, some one can help me, this message show every time i try post. but was working fine a few days ago,. i don't no whats happened.
<img width="1622" alt="Captura de Tela 2019-03-27 às 08 08 09" src="https://user-images.githubusercontent.com/44261916/55071477-79fd2e80-5067-11e9-9475-908b017e4bdc.png">

**Comment by ivanyadeshko** [comment]
Hmmm... can you show you requets data for method:
Timeline::uploadPhoto() or Timeline::uploadVideo() or Timeline::uploadAlbum()
?

**Comment by JRoy** [comment]
The action was blocked most likely.
