### ISSUE TITLE
How do you send an image in a DM that is not posted to instagram?

### ISSUE THREAD

**Issue by hackerjacks** [mgp25/Instagram-API#259]
I want to send someone a DM with a picture I have stored locally. Is this possible?

**Comment by techinpark** [comment]
Check it.
[https://github.com/mgp25/Instagram-API/wiki#direct-share-media-to-a-friend](Wiki)

**Comment by hackerjacks** [comment]
You check it. That method only allows you to share media that has been uploaded, thus the "media_id" parameter.
