### ISSUE TITLE
Confirm use for scheduling

### ISSUE THREAD

**Issue by vaishnavmhetre** [mgp25/Instagram-API#2591]
I have read about the legal terms for the repository usage. Be noted that I'm going to build my project for personal use and not going to redistribute it. I had to confirm creating *Personal Post Scheduler* is legal yet keeping my code closed source for privacy concerns.

**Comment by mgp25** [comment]
Hello @vaishnavmhetre,

If its just for private and personal usage, feel free to use the API. 

Regards
