### ISSUE TITLE
Have Live Broadcast Id But On instagram application does not start live 

### ISSUE THREAD

**Issue by mjpournassari** [mgp25/Instagram-API#2598]
```
$stream = $ig->live->create();
		sleep(2);
        $ig->live->start($stream->getBroadcastId());
```
I  have a broadcast id and push video with obs or ffmpeg without any error.
`/18035784199101195?s_efg=eyJxZV9ncm91cHMiOnsiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xpdmVfZW5hYmxlX2xpdmVkYXNoIjp7ImxpdmVkYXNoX21vZGUiOiJwcmltYXJ5In0sImlnX2xpdmVfZW5hYmxlX3BvcF9wcmltaW5nIjp7ImVuYWJsZWQiOiJ0cnVlIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6InRydWUifX19&s_vt=ig&a=Abz1tAnznaPCOPpY`

**But on instagram app There is no live status .**
if i call `$ig->live->addToPostLive($stream->getBroadcastId());`
App says your video will be available soon,but nothing happen after hour.

Thank You

**Comment by JRoy** [comment]
Please check the following example before opening any issues:

*[liveBroadcast.php](https://github.com/mgp25/Instagram-API/blob/master/examples/liveBroadcast.php)
