### ISSUE TITLE
Get following MAX_ID

### ISSUE THREAD

**Issue by ironbeasty** [mgp25/Instagram-API#260]
I want to get the next page of user's following

I need to extract the "next_max_id", but it's not working.

> $test = $i->getUsernameInfo($id);
> echo $test['next_max_id'];

Returns nothing. Any ideas?

**Comment by techinpark** [comment]
@ironbeasty 

 `getUsernameInfo()` not is function of users followings. 

Try this. 
`$i->getUserFollowings($usernameId, $maxid);`
