### ISSUE TITLE
IGTV video upload query

### ISSUE THREAD

**Issue by hebbars** [mgp25/Instagram-API#2600]
Hi There, Firstly thanks a lot for this wonderful tool.

I am using it for several purpose for my channel. Lately I started exploring the IGTV option with this PHP tool. I am able to upload the videos with this tool, however my videos are getting zoomed after the upload. Basically I am ensuring the my videos have the 9:16 aspect ratio (720x1280), but still the videos get zoomed. After the upload, I was able to download the video to inspect the aspect ratio and I could see it was 640x800. It proves clearly there was a change to resolution. So my question is what am I missing here? why this resolution gets changed. any help or pointer would help. 

I am using the '23/6.0.1; 640dpi; 1440x2560; ZTE; ZTE A2017U; ailsa_ii; qcom', following device config with the PHP script.

Just to let you know, that I was able to upload the same video via IGTV portal and there were no issues.

**Comment by mgp25** [comment]
Hello @hebbars,

You need to follow issue template, and you need to provide as well the code you have used for uploading the media since there are many options to do it.

I will open this issue again when there is enough information.

Regards
