### ISSUE TITLE
Check if media deleted

### ISSUE THREAD

**Issue by thesite1** [mgp25/Instagram-API#2603]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hello, 

I'm using the getFeed function to get medias from a hashtag.
The problem is when I do a foreach, if a media is deleted my script end as error.
I try to check before if the media is still available but I didn't succeed.

I tried something like : 
```php
if ($ig->media->getInfo('2013106954429071158_7398468602')->isItems() === NULL)
```
But I get the message : 
```http
[1;34mPOST:  [0mhttps://i.instagram.com/api/v1/media/2013106954429071158_7398468602/info/
[1;33mDATA: [0msigned_body=f1e1635e2241e2f25a9b85f8e560a1ca3f2f890f7663930b52dbae88062f344d.{"media_id":"2013106954429071158_7398468602","_csrftoken":"okvGBkTuaAVa3UgiJZKeE4dhMAYtpyVS","_uid":"12092131027","_uuid":"9bab70f3-4510-4062-8b87-20ba7b0ae9ba"}&ig_sig_key_version=4
[0;32mâ†? 405 	 0B[0m
[0;36mRESPONSE: [0m

Something went wrong: No response from server. Either a connection or configuration error.
```

Could you help me to know which is the correct solution ?

Thanks!

**Comment by mgp25** [comment]
Catching the exception

Regards
