### ISSUE TITLE
uploadPhoto not working

### ISSUE THREAD

**Issue by damianolivier** [mgp25/Instagram-API#2604]
Hi, I'm using uploadStory.php code properly with no issues.

But when I try to use uploadPhoto.php it shows me a fail message.

I hope log could be useful for you to help me:

> 
GET:  https://i.instagram.com/rupload_igphoto/166197779677525_0_-345608249
→ 0B
← 200 	 12B
RESPONSE: {"offset":0}

POST:  https://i.instagram.com/rupload_igphoto/166197779677525_0_-345608249
→ 602.6kB
← 200 	 71B
RESPONSE: {"upload_id": "166197779677525", "xsharing_nonces": {}, "status": "ok"}

POST:  https://i.instagram.com/api/v1/media/configure/
DATA: signed_body=bd59a007db919e73b357352c0eaacc1aa11dc8da7f9c4b4b294ad5c63dcf50c0.{"supported_capabilities_new":"[{\"name\":\"SUPPORTED_SDK_VERSIONS\",\"value\":\"9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0\"},{\"name\":\"FACE_TRACKER_VERSION\",\"value\":\"10\"},{\"name\":\"segmentation\",\"value\":\"segmentation_enabled\"},{\"name\":\"WORLD_TRACKER\",\"value\":\"WORLD_TRACKER_ENABLED\"}]","device":{"manufacturer":"LGE","model":"RS988","android_version":"23","android_release":"6.0.1"},"_csrftoken":"6dOOoo3RPHfh8QUX6hcLLcS2b5iSPDdO","media_folder":"Camera","source_type":"4","_uid":"4305608682","_uuid":"432fd1f4-0054-41ee-8552-1d2abc1c05d1","edits":{"crop_original_size":[1024,768],"crop_zoom":1,"crop_center":[0,-0]},"extra":{"source_width":1024,"source_height":768},"caption":"","upload_id":"166197779677525"}&ig_sig_key_version=4
← 500 	 54B
RESPONSE: {"message": "Unknown Server Error.", "status": "fail"}
>

**Comment by beshoo** [comment]
Try to use different proxy

**Comment by damianolivier** [comment]
I'm not using any proxy at all... or what do you mean? 
Thanks
