### ISSUE TITLE
Get the last comments page

### ISSUE THREAD

**Issue by zeiflonte** [mgp25/Instagram-API#2606]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Example Code:

```$comMinId = $saved_value;
$commentList = $this->ig->media->getComments($post->media_id, ['min_id' => $comMinId]);
```

---

### Describe your issue

I need to get only the last comments.
I'd like to either begin from the end of comments (and go backwards) or save min_id cursor of the last page in order to quickly proceed to the last saved page (and go downwards).
I can save the last min_id, but I'm not sure if it's reliable as long as it consists of different inner fields.
Is there a good option to do it?

**Comment by mgp25** [comment]
Hello @zeiflonte,

The best way to do it, is by pagination. We should reproduce the same behavior as the app, so it is the only method I recommend. I am not sure if saving the `max_id` value will work, but you can try it.

Regards
