### ISSUE TITLE
getPendingFriendships() returns max 200 users

### ISSUE THREAD

**Issue by ankitgaurish** [mgp25/Instagram-API#2607]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

$response = $ig->people->getPendingFriendships();

returns max 200 users. I have more than 1k Pending requests.

How to get all the pending requests?

P.S: I also tried fetching next_max_id, but it always returns null.

**Comment by aadityatamrakar** [comment]
I think this is Instagram's limit. You can see in-app and web also. You can only see pending request up to 200 in web and 1k in the app.

**Comment by JRoy** [comment]
This request doesn't appear to have any active pagination as said above.

Regards

**Comment by kapil3790** [comment]
@JRoy I am trying to find out how many active pending follow requests are there in my account at a given point of time but I am unable to do that. Is there an alternate way to do that as the pagination 
is not there?
I don't know how but there are a few people around who are able to get this through.

Thanks
