### ISSUE TITLE
Add link to story

### ISSUE THREAD

**Issue by damianolivier** [mgp25/Instagram-API#2609]
Hi, I want to add a link to a story upload.

I see the documentation says the following:
// (optional) You can use story links ONLY if you have a business account with >= 10k followers.

I do have a business account with 18k followers

I send the link parameter but nothing happens. Is it not supported yet? Do you know when will it be ?

Thanks!

**Comment by mgp25** [comment]
Maybe account needs to be verified or something more but the feature works.

**Comment by JRoy** [comment]
@mgp25 unverified users have this feature, most likely the parameters have changed.

**Comment by JRoy** [comment]
Changed the `story_cta` parameter in 94784cc

Will merge to master with #2569, when ready.

Cheers.

**Comment by damianolivier** [comment]
I already tried locally but the fix didn't work, maybe I'm missing something

Thanks

**Comment by mgp25** [comment]
It has been added in https://github.com/mgp25/Instagram-API/commit/0a9d2b911203c55e3262bab0b8e9466feba7d5e0

Regards

**Comment by damianolivier** [comment]
Sorry, it doesn't work

**Comment by JRoy** [comment]
@damianolivier is the email ok your GitHub profile active? I can email you to take additional steps

**Comment by damianolivier** [comment]
Yes it is, thanks a lot!

**Comment by damianolivier** [comment]
This was never fixed :(
