### ISSUE TITLE
Regarding the last IG Update - Impressions sent with likes concern

### ISSUE THREAD

**Issue by spooksie** [mgp25/Instagram-API#2610]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### I've noticed Instagram was hit recently regarding users getting temp like blocked. I've spoken to many developers regarding this. The suspect is impressions when issuing likes. 

My question: Is it possible to send impressions with liking on posts?

I don't know if to connect to the post page via Guzzle to achieve the result. Any ideas?

Appreciate your hard work. 

---

**Comment by JRoy** [comment]
Any impressions would be likely be sent to Instagram via the graph api, of which we don't support/implement due to the massive amount of work that would entail and the possibility that it could be used for spam.

Regards.
