### ISSUE TITLE
Is webview sessionid equals login sessionid?

### ISSUE THREAD

**Issue by ibrahimdevs** [mgp25/Instagram-API#2612]
Hi,
Thanks for great work. I developed an mobile app. User firstly login Instagram via webview (browser) and I'm getting sessionid from webview cookies. Then I'm using this api's endpoint urls. For getting media or follower it works. But for follow or unfollow an user doesn't work.

Do you any idea why is like that? Your login function result can be different from Instagram web page's login form result?

** I know that my question is not directly about this project. I spend too much time and had to ask you here, because I think if there is an answer to my question, it should be in here.

Thanks,

**Comment by JRoy** [comment]
This library is an emulation of the Android app, not the website. We will not issue support to this.

Regards.
