### ISSUE TITLE
proc_open(): CreateProccess Failed

### ISSUE THREAD

**Issue by siikuder** [mgp25/Instagram-API#2620]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Issue : 
I installed Instagram-API with composer on Windows 10 | PHP 7.3.2, use code this :

```sh
composer require mgp25/instagram-php dev-master
```

but i get error like this
`[ErrorException]                                   
proc_open(): CreateProcess failed, error code - 5`

**Comment by mgp25** [comment]
Hello,

This is not an API issue. Please contact composer team instead.

Regards
