### ISSUE TITLE
Follow User don't work on one account

### ISSUE THREAD

**Issue by dpmika** [mgp25/Instagram-API#2621]
Hi everyone,
I'm using this library on two different accounts with the same code.

In the first account I have no problem, I can follow and not follow without problems.

In the second one, I can only do not follow. When I try the rate of the ads following an account does not work. The account does not start following the user.

This is the answer that gave me a distant following

{"friendship_status": {"following": false, "followed_by": false, "blocking": false, "muting": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "status": "ok"}

If I try to follow from app or from instagram.com, I have no problem, so I guess it's not a ban.

Excuse my English :)

Thank's

**Comment by mgp25** [comment]
Account flagged. Not API issue.

Regards
