### ISSUE TITLE
Follow and Unfollow return 404

### ISSUE THREAD

**Issue by frfmmdreza** [mgp25/Instagram-API#2623]
Hi, i'm using follow and unfollow methods (from people class) but i get 404 page not found error.
I test with diffrent user id (not username) but the results are the sanme.
How can i solve that?
Thanks

**Comment by frfmmdreza** [comment]
Why this issue is closed?
This problem asked earlier but nobody answer that

**Comment by bolds07** [comment]
@frfmmdreza 
do you want to be even considered? 
FOLLOW THE ISSUE TEMPLATE

you come here to ask someone to spend his time to help you for free and you are not even considerate enough to read and follow the process?
