### ISSUE TITLE
Trying to get all viewers [getStoryItemViewers] [PAGINATION] 

### ISSUE THREAD

**Issue by bakill3** [mgp25/Instagram-API#2627]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---
### Describe your issue

Hello, I am having trouble getting all the viewers for Stories. I only get 20 viewers. I've tried to paginate with max_id and it doesn't work (I even used the example as a reference).

I tried getting the information from getStoryItemViewers and also called getNextMaxId(), didn't work.

Thanks for your support!
PS: If I missed something I'm sorry.

**Comment by bisht-sanjeet** [comment]
I'm not sure if it will help you or not. I get around 3-4k plus views on my stories but if I try to paginate on Instagram app it won't ever load 200 viewers inspite loading it on official app.
I don't know its a bug or they do it deliberately.
So it must be happening same in api end also.

**Comment by bakill3** [comment]
I only get 20. If I at least got 200 i would be satisfied. I just wanted to see a working example of the Pagination of Story Viewers

**Comment by bakill3** [comment]
I managed to get it working, thanks @mgp25 for making this awesome API
