### ISSUE TITLE
New composer version

### ISSUE THREAD

**Issue by xasor** [mgp25/Instagram-API#2628]
Hello,

I would like to ask if there is any plan to release a new composer version. I am "scared" to say the least to require "dev-master".

Thanks!

**Comment by JRoy** [comment]
After the new pigeon headers are added and #2435 is addressed maybe it would be time for a new release due to the new constants version being outdated in the current version. 

What do you think @mgp25?

**Comment by mgp25** [comment]
As soon as we write the release note, checking if there were code breaks (backwards compatibility), fixes and features, we will add a new release. It will be soon (I will try to have for the next days). Nevertheless, `dev-master` is safe to use.

Regards

**Comment by xasor** [comment]
Thanks for the replies.

Indeed, it is working fine, although yesterday I had an error because an object changed name ( album to carousel ).

I will keep an eye when the new release is out.

**Comment by mgp25** [comment]
@xasor release note is finished. If everything is okay the new release will be pushed today or tomorrow morning

Regards
