### ISSUE TITLE
Upload a video

### ISSUE THREAD

**Issue by tomansell** [mgp25/Instagram-API#2629]
## Prerequisites
I'm pretty new to PHP, I have been using Instagram-private-API NPM library.

- Can I pass user session from Node to PHP API?
- Is there any way to get the session of the user i.e user session by passing User Instagram ID, Do I need to pass username & password every time I need to upload a video.
`
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    // echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

try {
    $video = new \InstagramAPI\Media\Video\InstagramVideo($videoFilename);
    $ig->timeline->uploadVideo($video->getFile(), ['caption' => $captionText]);
    print_r($video);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
} `

**Comment by mgp25** [comment]
Hello,

- I guess
- Yes

Please, read wiki and check examples before opening a new issue.

Regards
