### ISSUE TITLE
Feature Request: Add share IGTV to Timeline

### ISSUE THREAD

**Issue by codebyzen** [mgp25/Instagram-API#2631]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

I see some posts with "Watch the rest of the video on IGTV" Button on bottom of video. I want to do the same. At first i try to use
```php
$options = ['caption'=>"Test\nCaption\n#infovideo"];
$ig_media_object = new \InstagramAPI\Media\Video\InstagramVideo($videoFilename, ['targetFeed' => \InstagramAPI\Constants::FEED_TV]);
$responce = $ig->timeline->uploadVideo($ig_media_object->getFile(), $options);
```

but it cause error

```http
Fatal error: Uncaught InvalidArgumentException: Instagram only accepts timeline media with aspect ratios between 0.800 and 1.910.
```

I go to Instagram-API/src/Request/TV.php and make:

```php
$ig_media_object = new \InstagramAPI\Request\TV($ig);
$responce = $ig_media_object->uploadVideo($videoFilename, ['title'=>'Test\nTitle\n#infovideo']); // post to IGTV
```

It upload my video to IGTV successfully but only to IGTV, not in simple post to timeline.

How can I make post in timeline with button (Watch the rest of the video on IGTV) on bottom?

**Comment by codebyzen** [comment]
In native client it's sounds like "Post preview" (only for videos more than 1 minute length)

**Comment by c00ler123** [comment]
@JRoy, do you have any changes of that topic ? Still actual

**Comment by JRoy** [comment]
Added in 198e1a97d55948144145d2c542b3baea61c9c5c2

Regards.
CC: @codebyzen @c00ler123
