### ISSUE TITLE
External link not allowed anymore

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2635]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Example Code:

```
/////// CONFIG ///////
$username = '';
$password = '';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
//works fine

	$ig->follow(12345);
	//error
	$ig->account->editProfile("","","","","","");
	//same error
```

 
 

### Describe your issue

It seems that instagram is removing the external url feature from profiles... all profiles i get with url are being blocked from doing some stuff and i'm not being able to edit the profile to remove the url through the api (i can do in instagram app)

so lets say i've a profile X with any external url (really any, i'm getting this error even if the url is http://www.google.com), after it login if i try to follow anyone i get the error:

`{"message": "feedback_required", "spam": true, "feedback_title": "Link not allowed", "feedback_message": "It looks like your profile contains a link that is not allowed. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_profile_edit/", "feedback_appeal_label": "Tell us", "feedback_ignore_label": "OK", "feedback_action": "report_problem", "status": "fail"}`

so this is not an api issue... BUT, if i try to edit the profile with the api `editProfile` and set the url to "" i get the same error

**Comment by JRoy** [comment]
This is a  `feedback_required` issue, of which is not supported due to its extensive answering on the wiki and issue tracker.

Regards.

**Comment by bolds07** [comment]
Well, i was getting this problem in my personal account which i dont even use to test with the api
Also getting with tons of accounts do use my service through the api  

I do use home base IP and i'm currently at a hotel so i dont think it was an "bad ip" issue since it would affect all the guests here

But anyway, without any interference it got solved 72h later
