### ISSUE TITLE
Any one have instagram api in php not in framework

### ISSUE THREAD

**Issue by umeshdepale** [mgp25/Instagram-API#2637]

**Comment by mgp25** [comment]
What...?

**Comment by umeshdepale** [comment]
I want Instagram hashtag search API in PHP

**Comment by mgp25** [comment]
That is already implemented in the API. Please read the wiki before opening an issue

**Comment by umeshdepale** [comment]
but help can you give me search hashtag API in CURL

**Comment by bolds07** [comment]
@mgp25 i dont understand why you waste your time to answer people that are clearly in some "introduction to programming" class =b
