### ISSUE TITLE
LauncherSyncResponse: No configs given.

### ISSUE THREAD

**Issue by j3fdev** [mgp25/Instagram-API#2639]
I'm trying to log in but I can not seem to get this error:

```
"InstagramAPI\Response\LauncherSyncResponse: No configs given."
```

I tried to use the configs that are in src/Request/Internal.php on line 1064 but without success

```
src/Request/Internal.php line 1064 
->addPost('configs', 'ig_android_felix_release_players,ig_user_mismatch_soft_error,ig_android_os_version_blocking_config,ig_android_carrier_signals_killswitch,fizz_ig_android,ig_mi_block_expired_events,ig_android_killswitch_perm_direct_ssim,ig_fbns_blocked');

class LauncherSyncResponse extends Response
{
    const JSON_PROPERTY_MAP = [
        'configs' => 'ig_android_felix_release_players,ig_user_mismatch_soft_error,ig_android_os_version_blocking_config,ig_android_carrier_signals_killswitch,fizz_ig_android,ig_mi_block_expired_events,ig_android_killswitch_perm_direct_ssim,ig_fbns_blocked',
    ];
}
```

I'm using code like this and on the web

```
<?php

require 'vendor/autoload.php';

use InstagramAPI\Exception\InstagramException;
use InstagramAPI\Instagram;

Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

    try{
        $ig = new Instagram();
        $ig->login('username', 'password');
        print_r($ig->account_id);
    }catch (InstagramException $exception){
        print_r($exception->getMessage());
    }
```

Can someone help me?

Thanks

**Comment by JRoy** [comment]
First of all: We do not support web usage but you must also share a full debug log

**Comment by beshoo** [comment]
Please kindly update your api to the latest version.

Use the dev one

**Comment by blizzardsolution** [comment]
I'm building back-end API using mgp25.
This is not a actual web page, only end-point, but it asks me to use the following setting to continue as web page.

Anyway, I've set this. 
Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

And when I try to login,
I also have the same error.

Please help me on this.
Thanks in advance.

**Comment by beshoo** [comment]
@blizzardsolution Download Latest Dev Master

**Comment by blizzardsolution** [comment]
@beshoo Thanks, but I've installed it using composer 3 hrs ago. What should I do now ?

**Comment by beshoo** [comment]
@blizzardsolution at least please copy and paste the logs so i can understand the problem

**Comment by blizzardsolution** [comment]
I've built back-end api for direct messaging action using mgp25. And I used this setting.
Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

Method : POST
API: localhost:8080/api/direct-message

And I tested it using postman. But on the login(), error occured. 

**Debug log**
`POST:  https://b.i.instagram.com/api/v1/accounts/read_msisdn_header/
DATA: signed_body=c003e49a70ff6a957b6345b3c489976df33e6eed2eb470dea60958dded77f532.{"mobile_subno_usage":"ig_select_app","device_id":"d4377948-05cc-46cf-b05e-d3b64df66e65"}&ig_sig_key_version=4
← 200 	 16B
RESPONSE: {"status": "ok"}

POST:  https://b.i.instagram.com/api/v1/qe/sync/
DATA: signed_body=c4273fae3367bddbcbfeea0e36482a33642ef3a722a3b6e93bf5a1b8ab0e31de.{"id":"d4377948-05cc-46cf-b05e-d3b64df66e65","experiments":"ig_growth_android_profile_pic_prefill_with_fb_pic_2,ig_android_react_updater_universe,ig_android_autosubmit_password_recovery_u **.... .... ....** ig_android_restore_focus_on_textbox_reg_universe"}&ig_sig_key_version=4
← 200 	 1.13kB
RESPONSE: {"experiments": [{"name": "ig_android_background_voice_phone_confirmation_prefilled_phone_number_only", "group": "test", "additional_params": [], "params": [{"name": "enabled", "value": "true"}]}, {"name": "ig_android_report_nux_completed_device",  **... ...** "params": [{"name": "is_enabled", "value": "true"}]}], "status": "ok"}

POST:  https://b.i.instagram.com/api/v1/launcher/sync/
DATA: signed_body=70de09ca9c4b11e6762cc38b947f27f6024dbdeec173e09b649a1a2b12b632a1.{"_csrftoken":"KK6SUMu3dnFhh0k6v21tXw4QqIdrXJJ3","id":"d4377948-05cc-46cf-b05e-d3b64df66e65","configs":""}&ig_sig_key_version=4
← 400 	 49B
RESPONSE: {"message": "No configs given", "status": "fail"}`

**Comment by beshoo** [comment]
Whare is the PHP code you are using !

**Comment by blizzardsolution** [comment]
`
Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
$this->ig = new Instagram(true, false);
$this->ig->login('anonymous', 'password');
`

**Comment by blizzardsolution** [comment]
I'd appreciate your help, if this setting below
`Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;`
is really necessary for my specification. I'm building back-end api, not a webpage.
Thanks.

**Comment by beshoo** [comment]
```
Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
require __DIR__.'/../vendor/autoload.php';
/////// CONFIG ///////
$username = '';
$password = '';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

```

**Comment by blizzardsolution** [comment]
@beshoo That's actually the same as mine.

**Comment by beshoo** [comment]
First of all, delete the cookies, then reloading and show me the full log

**Comment by blizzardsolution** [comment]
> @blizzardsolution Download Latest Dev Master

Can you give me detailed instruction about how to do this ? Thanks.

**Comment by beshoo** [comment]
@blizzardsolution  

`composer require mgp25/instagram-php dev-master
`

**Comment by beshoo** [comment]
Remove the lib, then download it again

**Comment by blizzardsolution** [comment]
@beshoo Sure. I'll try that, and then let you know.

**Comment by blizzardsolution** [comment]
@beshoo Super !
Dev master works now.
But, one more please.
Should I have this setting indeed ?

`Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;`

**Comment by beshoo** [comment]
Yes

**Comment by blizzardsolution** [comment]
@beshoo  Thanks.

**Comment by Octolus** [comment]
I am getting same problem.

**Comment by mgp25** [comment]
# Solution 

**Update to latest release or dev-master code**

**Comment by d46** [comment]
If you get composer content length mismatch go with this

```
composer config -g repo.packagist composer https://packagist.org
composer config -g github-protocols https ssh
```
