### ISSUE TITLE
Feature Request: Quiz Responses

### ISSUE THREAD

**Issue by humet** [mgp25/Instagram-API#2642]
Hi,

There is a new quiz feature Instagram launched a few days ago. Could I request this be added, please? I'd like to be able to get the answers for each user if possible?

Or is this already possible? 

Thanks

**Comment by JRoy** [comment]
I will add this when we update the constants as quizes are not in v85.

Regards.

**Comment by lastwall** [comment]
@JRoy May I ask how often do you update constant?

**Comment by JRoy** [comment]
This feature is now exclude to our private repository. See #2655 for more information.
