### ISSUE TITLE
Comment Count Of Medias Always 0

### ISSUE THREAD

**Issue by merteroglu01** [mgp25/Instagram-API#2643]
Error in response while catching the media informations.

It always return 'comment_count' as 0.
When fetching information about all of my photos, in every response comment_count is 0.
And checked account is the correct account in $insta-login($username,$password). 

Sample response from server:
"taken_at": "1551356415",
        "pk": "1989244253435663920",
        "id": "1989244253435663920_10705923723",
        "device_timestamp": "15513564138992",
        "media_type": 1,
        "filter_type": 0,
        "comment_likes_enabled": true,
        "comment_threading_enabled": true,
        "has_more_comments": false,
        "max_num_visible_preview_comments": 2,
        "can_view_more_preview_comments": false,
        "comment_count": 0,

**Comment by ttvd94** [comment]
same problem here

**Comment by alexok** [comment]
@merteroglu01 
First, you need to correctly issue a question.
secondly, I have already asked about this, and it seems like this is the correct answer in new versions. I use old commits for now. As an option, you can write your method with the old parameters

**Comment by mbnl** [comment]
@merteroglu01 
Timeline.php'de getUserFeed fonksiyonunda şöyle bir satır var;

->addParam('exclude_comment', true)

buradaki true'yu false'a çevirmen gerekli bu şekilde yaparsan yorumlar gelir

->addParam('exclude_comment', false)

**Comment by strabsquad** [comment]
Thank you @mbnl , it solved the problem for me !
