### ISSUE TITLE
Some videos incorrectly rotated through InstagramVideo class

### ISSUE THREAD

**Issue by RonSv** [mgp25/Instagram-API#2644]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)

--- 

Hello! 

Some videos incorrectly rotated through InstagramVideo class. In media players source.mp4 is played correctly.

As far as I understand, the problem is in the function **_getRotationFilters** of InstagramVideo class. It returns ['transpose=clock']. Or the problem is somewhere further. Please help, thanks in advance.

**Example Code:**
```php
$video = new \InstagramAPI\Media\Video\InstagramVideo('source.mp4');
File::copy($video->getFile(), 'result.mp4');
```

**Files:**
[source.mp4](https://drive.google.com/open?id=1dgmy-fHkOcoXDDdWDzDOy2_1ZIYcMo-4) → [result.mp4](https://drive.google.com/open?id=1xirZe9rT5JHMivoo6K0HPQPa0oT7AUhD)
![screenshot](https://user-images.githubusercontent.com/12168423/57096503-1dec9080-6d1e-11e9-905e-da142b2701b8.png)

**ffmpeg -i source.mp4**
```http
ffmpeg version 4.1.3-static Copyright (c) 2000-2019 the FFmpeg developers

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'source.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-04-29T09:44:20.000000Z
    com.android.version: 9
  Duration: 00:00:08.26, start: 0.000000, bitrate: 19483 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, smpte170m), 1920x1080, 19787 kb/s, SAR 1:1 DAR 16:9, 29.90 fps, 30.01 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2019-04-29T09:44:20.000000Z
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2019-04-29T09:44:20.000000Z
      handler_name    : SoundHandle`
```

**Comment by Valew17** [comment]
Same problem.
ffmpeg version 4.1.3-static.

Did someone find a solution?

**Comment by bolds07** [comment]
I believe nobody here is ffmpeg specialist, would be easier send an inquiry to ffmpeg support 

I know that most phones do record always at horizontal and use some metadata to tell the players to rotate videos to vertical, so the rotation is done at playtime,  but it is made if the player consider the metadata... Some players don't and I'm not sure if to instagram is a must you reenconde the video with the rotated version or you can just add this metadata to work

**Comment by valga** [comment]
@RonSv It's a [bug](https://trac.ffmpeg.org/ticket/6370) in ffmpeg itself.

I tried to work around it in 832525ed1839699d12199b76418a2d8645ce30a6, it should be fixed now.
