### ISSUE TITLE
How to parse push response?

### ISSUE THREAD

**Issue by kimia000** [mgp25/Instagram-API#2647]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Describe your issue

I tried to get the recent activities on my account such as likes and comments. I used the example given but the response is way too complicated. I tried to simply get the basic items (user_id, media_id, comment) from
`$push = new \InstagramAPI\Push($loop, $ig, $logger);
`but the returning object is too complicated and I have no idea how to get the items.

I understand this is not an actual issue of the program, but could you please give me a hint how I can get a minimal output of the push?

**Comment by JRoy** [comment]
Please actually review the examples. The one you're looking for is [pushReceiver.php](https://github.com/mgp25/Instagram-API/blob/master/examples/pushReceiver.php).

Cheers.
