### ISSUE TITLE
Get all user followers and followings without max_id

### ISSUE THREAD

**Issue by MrProrper** [mgp25/Instagram-API#265]
Hi,
I need to get all user followers and followings without max_id. so I've create a function to do this BUT this is SLOW, is there any function to do it faster?

`function GetAllSelfUserFollowing($i){
	$t = 0;
	$followings = '';
	while (true) {
		if ($t == 0) {
			$followings[] = $i->getSelfUserFollowing();
		}
		if ( (isset($followings[$t]['next_max_id']) && !empty($followings[$t]['next_max_id'])) ) {
			$nextid = $followings[$t]['next_max_id'];
			$followings[] = $i->getSelfUserFollowing($nextid);
		}else{
			break;
		}
		$t += 1;
	}
	$a = array();
	foreach ($followings as $key => $value) {
		$a = array_merge($a, $value['users']);
	}
	$res['status'] = $followings[0]['status'];
	$res['users'] = $a;
	return $res;
}`

**Comment by mgp25** [comment]
Sorry, there isnt.

Regards
