### ISSUE TITLE
I can't access some accounts viewers

### ISSUE THREAD

**Issue by bakill3** [mgp25/Instagram-API#2651]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

### Describe your issue

Hello, I've been using the api to see my story viewers (on my main account and on my business accounts) for the past 2 weeks. Yesterday I created a 'Landscapes account', and I added it to see the viewers (login loop) but it wasn't working.. And it's strange because after that I created another account and it worked on that one but on the Landscape never worked..

**Comment by beshoo** [comment]
Log?
