### ISSUE TITLE
How get nickname by phonenumber

### ISSUE THREAD

**Issue by ahvahsky2008** [mgp25/Instagram-API#2657]
### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [ x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question
- [ ] Other

How get insta nickname by phone number?

**Comment by JRoy** [comment]
You'd need to link your address book

**Comment by alexok** [comment]
By the way, this question is also interesting. You can have more information on the method in which format to transmit numbers

**Comment by alexok** [comment]
> You'd need to link your address book

Old address book format not work
https://github.com/mgp25/Instagram-API/issues/2100#issuecomment-492394304
