### ISSUE TITLE
How to send direct message ?

### ISSUE THREAD

**Issue by Noido** [mgp25/Instagram-API#2658]
Hi i have a list of users and i want send them direct message how i can do that ? 

Thanks

**Comment by mgp25** [comment]
Hello,

There is already documentation about this. Feel free to check the following documentation:

- [Wiki](https://github.com/mgp25/Instagram-API/wiki)
- [Examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

Regards

**Comment by josuelmm** [comment]
In the examples is not the file of how send direct message or get messages
