### ISSUE TITLE
Explore Feed nextMaxId not working

### ISSUE THREAD

**Issue by AdriaCarrera** [mgp25/Instagram-API#2659]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hello, I am new using this repo so maybe it's my issue, so many apologies if is that the case.

When I am using discover -> exploreFeed() functionality, I am unable to pass to other page using maxId and nextMaxId.

Here is the relevant part of the code:

```php

try {
            $response = $this->ig->discover->getExploreFeed();
            $maxId = $response->getMaxId();
            $searches = 0;
            while($maxId && $searches < $maxSearches){
                echo 'Max id: '.$maxId."\n";
                
                //Do stuff with $items

                $searches++;
                $maxId = $response->getNextMaxId();
                sleep(10);
            }

        } catch (Exception $e) {
            echo 'Exploring falied: '.$e->getMessage()."\n";
        }

```

And the output of the echo is always: 

Max id: 1

By the way, thank you very much for sharing this awesome project. The code is very clean and very well structured.

You are awesome guys!

**Comment by JRoy** [comment]
This is the improper use of pagination. Please look at the relevant examples:
* [paginationExample.php](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php)

By glacing at your code, it appears you're not actually doing a new request with your max id.

Cheers.
