### ISSUE TITLE
ig->timeline->getTimelineFeed method pagination.

### ISSUE THREAD

**Issue by IORoot** [mgp25/Instagram-API#2662]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I just can't get pagination working with this particular method. The "home screen" feed (`ig->timeline->getTimelineFeed`) won't return a second (or more) page of results for me. I can do it with other methods, but not this one.

I've tried to break it down to the simplest form I could, which is:
```
$ig = new \InstagramAPI\Instagram();
$ig->login($user, $pass);

//Get feed.
$maxId = null;
$response = $ig->timeline->getTimelineFeed($maxId);
$items = $response->getFeedItems();
var_dump($items); 	// Totally fine. Can retrieve the results.

$NextMaxId = $response->getNextMaxId();    // Works - string retrieved.

$response_b = $ig->timeline->getTimelineFeed($NextMaxId);	
// Does *not* retrieve next set of results? Returns the same, first 7-8 again?

$items_b = $response_b->getFeedItems();
var_dump($items_b);	 // Basically the same as the first dump.
```

The second var_dump has differences, tokens, comments, counts, etc... But the item results are the same. 
I believe I'm doing the right thing by supplying the $NextMaxId into the method for the next set of results, no?
Just to cover my bases, I've searched and read ALL the issues for 'getTimelineFeed', 'pagination', 'timeline', 'maxId', and 'home page'. I've run the wiki example for pagination, which is fine and works, just not on this method. 

The only similar issue posted is issue #2618, but that has been marked as 'invalid' for some reason. 

I've also used the `$response->printPropertyDescriptions();` method to see what other things may need setting and can see a couple of related virtual functions for:
- auto_load_more_enabled
- pagination_info

But I'm afraid I don't know what they do, how they relate or if they need some action on them.

I'm sorry, I'm probably doing something wrong, but I can't for the life of me find any related issues (closed or open), wiki entries, comments or even google searches that help. It would also seem that this method would be heavily used in your API by other developers, so I'm confused as to why no one else has mentioned this. Therefore, I'm assuming I've messed up somewhere. Any pointers or links to guide me?

**Comment by JRoy** [comment]
#2618 was marked as invalid due to their code being invalid and the numerous examples of how you're supposed to use it.

As for you: Can you please make sure you're on the latest commit of `dev-master` and try again.

**Comment by IORoot** [comment]
@JRoy, thank you. That's the stupid thing I hadn't done. Apologies. When I composer installed, I just assumed that the version I was using only had code in it that was working. 
I also assumed that I was already on the master branch. But alas, I was not. I can see now that the wiki does actually say that exact thing on the 'dependencies' page. 

Anyway, that works now. Thanks.

**Comment by mafanikio** [comment]
> @JRoy, thank you. That's the stupid thing I hadn't done. Apologies. When I composer installed, I just assumed that the version I was using only had code in it that was working.
> I also assumed that I was already on the master branch. But alas, I was not. I can see now that the wiki does actually say that exact thing on the 'dependencies' page.
> 
> Anyway, that works now. Thanks.

Can you explain what was the difference, please?
I'm using the same lib but rewritten on python and I met 100% the same problem as you. All paginations work but TImeLineFeed is not. I'd spent few days to solve it and still nothing.

**Comment by JRoy** [comment]
Don't ask for support for libraries that is not this one.
