### ISSUE TITLE
The entry process is very slow. How can I be constantly open?

### ISSUE THREAD

**Issue by pulluramazan** [mgp25/Instagram-API#2663]
Hi
The user is forced to log in to different pages. therefore the transition between pages is very slow. How can I solve this?
My code
page 1
```php
/////// CONFIG ///////
$username = 'usr';
$password = 'pass';
$debug = false;
$truncatedDebug = false;
//////////////////////
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->login($username, $password);
echo $ig->people->getSelfFollowing(\InstagramAPI\Signatures::generateUUID());
```
Page 2
```php
/////// CONFIG ///////
$username = 'usr';
$password = 'pass';
$debug = false;
$truncatedDebug = false;
//////////////////////
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->login($username, $password);
echo $ig->people->getSelfFollowing(\InstagramAPI\Signatures::generateUUID());
```

**Comment by mgp25** [comment]
Hello,

Once you have logged in, a session will be created. The API will reuse this session for the next requests. You need to manage how you handle the user's sessions

Regards

**Comment by pulluramazan** [comment]
> Hello,
> 
> Once you have logged in, a session will be created. The API will reuse this session for the next requests. You need to manage how you handle the user's sessions
> 
> Regards

how can I do it. do you have sample code
