### ISSUE TITLE
Live broadcast 

### ISSUE THREAD

**Issue by peter1parker** [mgp25/Instagram-API#2666]
I've updated latest changes to live and its example . but video not streaming anymore .  you can try it yourself . i used video that i've test before instagram api changes .
also there is no error on log to share for you. video stopped streamming using ffmpeg and nothing displayed as error on debug .
also on instagram application this message is showing :   " Your video will be available soon " !!

 debug and truncatedDebug :
> POST: https://i.instagram.com/api/v1/feed/timeline/ DATA: is_prefetch=0&feed_view_info=&seen_posts=&phone_id=174d5801-ff88-467b-ba98-f21c3ce330ab&reason=pull_to_refresh&battery_level=97&timezone_offset=0&_csrftoken=U9y93umhJ0CHSOJOy5vDXz0Ws3q752x5&client_session_id=34deeafa-35ae-4672-b869-44ce57fe46b2&device_id=640a9cb7-3efd-4a28-b6be-d6ad1a60840a&is_pull_to_refresh=1&_uuid=640a9cb7-3efd-4a28-b6be-d6ad1a60840a&is_on_screen=true&unseen_posts=&is_charging=0&is_async_ads_in_headload_enabled=0&rti_delivery_backend=0&is_async_ads_double_request=0&will_sound_on=1&is_async_ads_rti=0 ← 200 52.36kB RESPONSE: {"num_results": 0, "more_available": false, "auto_load_more_enabled": true, "feed_items": [], "is_direct_v2_enabled": true, "next_max_id": null, "pagination_info": {"source": null, "group_id": null}, "view_state_version": "1558126996335-7bd65dee49c644428d43878ea4afe437", "client_feed_changelist_applied": false, "client_session_id": "34deeafa-35ae-4672-b869-44ce57fe46b2", "suggested_users": {"title": "Suggested for You", "style": "with_content_thumbnail", "suggestion_cards": [{"user_card": {"user": {"pk": "787132", "username": "natgeo", "full_name": "National Geographic", "is_private": false, "profile_pic_url": "https://instagram.fevn1-2.fna.fbcdn.net/vp/2cdb200a633081263c312a549f29c637/5D730DE8/t51.2885-19/s150x150/13597791_261499887553333_1855531912_a.jpg?_nc_ht=instagram.fevn1-2.fna.fbcdn.net", "profile_pic_id": "1288575635841480803_787132", "is_verified": true, "has_anonymous_profile_picture": false}, "algorithm": "ig_regional_interests_algorithm", "social_context": "Popular", "icon... POST: https://i.instagram.com/api/v1/live/create/ DATA: _csrftoken=U9y93umhJ0CHSOJOy5vDXz0Ws3q752x5&preview_height=1184&_uuid=640a9cb7-3efd-4a28-b6be-d6ad1a60840a&broadcast_type=RTMP_SWAP_ENABLED&broadcast_message=&preview_width=720&internal_only=0 ← 200 1.31kB RESPONSE: {"broadcast_id": 17955693208278014, "upload_url": "rtmps://live-upload.instagram.com:443/rtmp/17955693208278014?s_efg=eyJxZV9ncm91cHMiOnsiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xpdmVfZW5hYmxlX2xpdmVkYXNoIjp7ImxpdmVkYXNoX21vZGUiOiJwcmltYXJ5In0sImlnX2xpdmVfZW5hYmxlX3BvcF9wcmltaW5nIjp7ImVuYWJsZWQiOiJ0cnVlIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6InRydWUifX19\u0026s_vt=ig\u0026a=Aby9ff6NFXgag_bl", "fbvp_tcp_upload_url": "fblive://live-vp-upload.instagram.com:443/rtmp/17955693208278014?s_efg=eyJxZV9ncm91cHMiOnsiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xpdmVfZW5hYmxlX2xpdmVkYXNoIjp7ImxpdmVkYXNoX21vZGUiOiJwcmltYXJ5In0sImlnX2xpdmVfZW5hYmxlX3BvcF9wcmltaW5nIjp7ImVuYWJsZWQiOiJ0cnVlIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6InRydWUifX19\u0026s_f=1\u0026s_vt=ig\u0026a=Abwp3joSljilDXYV", "fbvp_quic_upload_url": "fblive://live-vp-upload.instagram.com:443/rtmp/1795569320827801... POST: https://i.instagram.com/api/v1/live/17955693208278014/start/ DATA: _csrftoken=U9y93umhJ0CHSOJOy5vDXz0Ws3q752x5&_uuid=640a9cb7-3efd-4a28-b6be-d6ad1a60840a ← 200 63B RESPONSE: {"media_id": "2046040020667419375_12293956348", "status": "ok"} POST: https://i.instagram.com/api/v1/live/17955693208278014/question_status/ DATA: _csrftoken=U9y93umhJ0CHSOJOy5vDXz0Ws3q752x5&_uuid=640a9cb7-3efd-4a28-b6be-d6ad1a60840a&allow_question_submission=true ← 200 56B RESPONSE: {"is_question_submission_allowed": true, "status": "ok"} GET: https://i.instagram.com/api/v1/live/17955693208278014/get_comment/?last_comment_ts=0&num_comments_requested=3 → 0B ← 200 207B RESPONSE: {"comment_likes_enabled": false, "comments": [], "comment_count": 0, "caption": null, "caption_is_edited": false, "has_more_comments": false, "has_more_headload_comments": false, "media_header_display": "none", "can_view_more_preview_comments": false, "live_seconds_per_comment": 2, "is_first_fetch": "True", "system_comments": null, "comment_muted": 0, "status": "ok"} POST: https://i.instagram.com/api/v1/live/17955693208278014/heartbeat_and_get_viewer_count/ DATA: _csrftoken=U9y93umhJ0CHSOJOy5vDXz0Ws3q752x5&_uuid=640a9cb7-3efd-4a28-b6be-d6ad1a60840a&offset_to_video_start=0 ← 200 179B RESPONSE: {"viewer_count": 0.0, "broadcast_status": "active", "cobroadcaster_ids": [], "offset_to_video_start": 0, "total_unique_viewer_count": 0, "is_top_live_eligible": 0, "status": "ok"} GET: https://i.instagram.com/api/v1/live/17955693208278014/get_like_count/?like_ts=0 → 0B ← 200 83B RESPONSE: {"likes": 0, "likers": [], "like_ts": 1558127022, "burst_likes": 0, "status": "ok"} GET: https://i.instagram.com/api/v1/live/17955693208278014/get_join_request_counts/?last_total_count=0&last_seen_ts=0&last_fetch_ts=0 → 0B ← 304 0B RESPONSE: GET: https://i.instagram.com/api/v1/live/17955693208278014/get_final_viewer_list/ → 0B ← 200 61B RESPONSE: {"users": [], "total_unique_viewer_count": 0, "status": "ok"} POST: https://i.instagram.com/api/v1/live/17955693208278014/end_broadcast/ DATA: signed_body=327c68b14f81dca8a5357fbc3cc8eba0b2a9b0f73e817111b1280d27f8c1d242.{"_csrftoken":"U9y93umhJ0CHSOJOy5vDXz0Ws3q752x5","_uid":"12293956348","_uuid":"640a9cb7-3efd-4a28-b6be-d6ad1a60840a","end_after_copyright_warning":"false"}&ig_sig_key_version=4 ← 200 16B RESPONSE: {"status": "ok"} POST: https://i.instagram.com/api/v1/live/17955693208278014/add_to_post_live/ DATA: signed_body=d916123dbe7fef4126dff6c71ad64fbf7d2f28a709771b86828c2fafc122d715.{"_csrftoken":"U9y93umhJ0CHSOJOy5vDXz0Ws3q752x5","_uid":"12293956348","_uuid":"640a9cb7-3efd-4a28-b6be-d6ad1a60840a"}&ig_sig_key_version=4 ← 200 923B RESPONSE: {"pk": "post_live_12293956348", "user": {"pk": 12293956348, "username": "ymz.test", "full_name": "YMZ.test", "is_private": false, "profile_pic_url": "https://scontent-lhr3-1.cdninstagram.com/vp/c13d8bc691a6fb3b4e225329707e8c40/5D7C0DF1/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=scontent-lhr3-1.cdninstagram.com", "is_verified": false}, "broadcasts": [{"id": 18067710016063596, "broadcast_status": "post_live_posting", "broadcast_owner": {"pk": 12293956348, "username": "ymz.test", "full_name": "YMZ.test", "is_private": false, "profile_pic_url": "https://scontent-lhr3-1.cdninstagram.com/vp/c13d8bc691a6fb3b4e225329707e8c40/5D7C0DF1/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=scontent-lhr3-1.cdninstagram.com", "friendship_status": {"following": false, "followed_by": false, "blocking": false, "muting": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false, "is_restricted": false}, "is_verified":...

**Comment by ahmadd110** [comment]
same problem! 
I think ffmpeg not send to new port (443)

**Comment by JRoy** [comment]
Appears to be a ffmpeg bug from what I'm seeing here: https://trac.ffmpeg.org/ticket/6471

Nothing we can currently do to fix this besides wait for ffmpeg. But I would add that streaming via OBS or other 3rd party encoders that support RTMPS does work.

Regards.

**Comment by peter1parker** [comment]
Did you find any other open source encoders ?
