### ISSUE TITLE
Story mention tags not working on app, but working on web

### ISSUE THREAD

**Issue by Biscuri** [mgp25/Instagram-API#2669]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

$usuario = "amigojoaosilva";
$produto = "https://static.careers360.mobi/media/article_images/2018/05/26/GATE_Mock-Test.jpg";
$perfil = "https://assets.pernod-ricard.com/nz/media_images/test.jpg?hUV74FvXQrWUBk1P2.fBvzoBUmjZ1wct";

$image = new \claviska\SimpleImage();
$image
    ->fromFile($produto);

//Crop image to fit 9:16 aspect ratio

$ratio = $image->getAspectRatio();
$ratioAlvo = 0.5625; // 9:16

if ($ratio != $ratioAlvo){ //If ratio is 9:16 do nothing
    $altura = $image->getHeight();
    $largura = $image->getWidth();
    
    if ($ratio >= $ratioAlvo) { //If wider
        $larguraAlvo = $altura * $ratioAlvo;
        $corte = ($largura - $larguraAlvo) / 2;
        $image->crop($corte, 0, $largura - $corte, $altura);
    } else { // If higher
        $alturaAlvo = $largura / $ratioAlvo;
        $corte = ($altura - $alturaAlvo) / 2;
        $image->crop(0, $corte, $largura, $altura - $corte);
    }
}

$altura = $image->getHeight();
$largura = $image->getWidth();

$alturaBg = $altura * 0.18; //18% of image height
$backgroundTexto = new \claviska\SimpleImage();
$backgroundTexto
    ->fromFile(__DIR__ .'/background-selo.png')
    ->resize(null, $alturaBg);

$larguraBg = $backgroundTexto->getWidth(); //Proportional width to resized height

$alturaPerfil =  $alturaBg * 0.375; // Fit the profile to a transparent hole behind the sticker
$imagePerfil = new \claviska\SimpleImage();
$imagePerfil
    ->fromFile($perfil)
    ->resize(null, $alturaPerfil);

//This is the sticker, overlaing the profile image so I have a round canvas over the square instagram profile image

$image 
    ->overlay($imagePerfil, 'top right', 1, -(($larguraBg - $alturaPerfil) / 2), $altura/10 + $alturaBg * 0.11)
    ->overlay($backgroundTexto, 'top right', 1, 0, $altura/10);

// Positioning the mention centered on the sticker, based on sticker size and position proportional to image
$mention = [
    'x'         => 1.0 - (($larguraBg / 2) / $largura), // Range: 0.0 - 1.0. Note that x = 0.5 and y = 0.5 is center of screen.
    'y'         => (($alturaBg/2) + ($altura/10)) / $altura, // Also note that X/Y is setting the position of the CENTER of the clickable area.
    'width'     => $larguraBg / $largura, // Clickable area size, as percentage of image size: 0.0 - 1.0
    'height'    => $alturaBg / $altura,
    'rotation'  => 0.0
];

\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true; //I run it on a cron service, so I need it to accept be run on a browser

$ig = new \InstagramAPI\Instagram(false, false);

//Credentials
try {
    $ig->login("mylogin", "mypass");
} catch (\Exception $e) {
    echo json_encode(["success" => false, "message" => 'An error has occurred: '.$e->getMessage()."\n"]);
    exit(0);
}

// Get userId for mentioning
$userId = $ig->people->getUserIdForName($usuario);

$mention['user_id'] = $userId;

$metadata = [
    'caption' => '@loja', //Just here because the mention doesn't show otherwise (this should be better documented, btw)

    'story_mentions' => [$mention],
    
];

try {
    
    $caminho = $usuario.time().'.jpg';
    $image->toFile($caminho); //Generating product image with sticker over it

    $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($caminho, ['targetFeed' => \InstagramAPI\Constants::FEED_STORY]);
    $ig->story->uploadPhoto($photo->getFile(), $metadata); //Uploading photo

    unlink($caminho); //Removing temp image with sticker

    echo json_encode(["success" => true, "message" => 'Story successfully uploaded.']);
} catch (\Exception $e) {
    echo json_encode(["success" => false, "message" => 'An error has occurred: '.$e->getMessage()."\n"]);
}

```

Error Log/var_dump:

The story media is successfully uploaded, no error. But, the tag is perfectly positioned on web view, while on mobile view it's messy, on some images, it's small and bad positioned, on others it doesn't even show.

Example web view well fit: https://i.imgur.com/BbXUB8A.png
My test insta, you can check the stories on mobile (I'm constantly uploading more via cronjob right now): https://www.instagram.com/stories/amigojoaosilva/

---

---

### Describe your issue

The library works well and upload the story photos successfully, but the mentions are well positioned when I see them on desktop, while on instagram app they appear displaced or don't even appear at all.

I made the calculations of position and size all based on percentages of total image width and height, and positioning of the sticker, so the tag area is exactly centered on the sticker with the same size. I printed all the values, they match, and on desktop you can see the sticker and mention areas coincide perfectly. Why is that only in the mobile app the mention area is messed up?

Examples of well positioned mentions on web (covering the entire sticker):

![image](https://user-images.githubusercontent.com/7120806/58056823-e9a80b00-7b38-11e9-8952-21b4d8a1321e.png)

![image](https://user-images.githubusercontent.com/7120806/58056832-f2004600-7b38-11e9-929e-5b6bc13cb262.png)

Bad positioned mention on mobile (the tag appear to be on the same place, but the area is only the upper left quarter of the sticker):

![image](https://user-images.githubusercontent.com/7120806/58056946-6aff9d80-7b39-11e9-8395-5fb79202d388.png)

**Comment by JRoy** [comment]
This doesn't look different, I don't get your problem. Additionally, we don't support the web as this is an app emulation not a webapp.

Regards.

**Comment by mgp25** [comment]
+ It is being used for commercial purposes without having in mind the [License](https://github.com/mgp25/Instagram-API#license)
