### ISSUE TITLE
[REQUEST] Browser based instagram features

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2670]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other
 
### Describe your issue
Some of instagram's offical app features runs in a webview (for example `challenge_required`, `report`, some of the account data is also shown into a webview) a webview do emulate a basic browser so all this code should be able to run in an external browser...
When running this functions instagram's doesn't ask the user to login again, so the app is somehow re-using the cookie to the webview...
I've been trying to reverse engineer how do they do that, but my skill in this field are pretty limitated and i wasn't sucessfull, as far as i got the webview the reversed code seemed to use isn't pretty much special they just adjust the `user-agent` and few other settings not much special... but there is one method that all the reverse engineer framework i tried do not generate
so i believe that this method do the magic trick to convert the api's cookie into a browser usable cookie to the webview

is it possible to someone with more expertise in this area to add the method to "export browser useable cookies" to this api?

**Comment by JRoy** [comment]
Requests which tend to be done via a webview, are usually requests which usually are easy to abuse and I personally don't feel it's worth to add. 

We may consider this as part of #2655's private code repository if it's wanted that bad.

Cheers.

**Comment by bolds07** [comment]
@JRoy , dont you think you are to much authoritary?
many of instagrams requests are done via webview...

if you want to disable e-mail notifications - webview
if you want to know when was the account created - webview
challenge_required - webview

that is okay you personally don't feel worth to add, but this is a public repository right? it shouldn't be your personal decision, maybe someone else has the same problem, maybe someone else think it worth adding, maybe someone else have done and can share the code...

the way you work seems you are getting money for each closed issue

**Comment by JRoy** [comment]
The webview would take time a fair bit of time to implement for not worth while nor vital features (like I've described in multiple other issues). I'm not saying we won't add these features ever, just not our priority. I was saying that if you wanted/needed it badly, you could consider a subscription and we'd work on it faster.

If anyone would like to add this feature they may but nagging us and demanding features won't get them added any faster. Reverse engineering takes time: More necessary features and ones that take less time will be added to the repository faster.

Regards.
