### ISSUE TITLE
Challenge required is totally changed

### ISSUE THREAD

**Issue by jeudesprits** [mgp25/Instagram-API#2677]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:
```php
<?php
set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'/../vendor/autoload.php';
/////// CONFIG ///////
$username = '';
$password = '';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $loginResponse = $ig->login($username, $password);
    if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()) {
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();
        // The "STDIN" lets you paste the code via terminal for testing.
        // You should replace this line with the logic you want.
        // The verification code will be sent by Instagram via SMS.
        $verificationCode = trim(fgets(STDIN));
        $ig->finishTwoFactorLogin($username, $password, $twoFactorIdentifier, $verificationCode);
    }
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
PHP Fatal error:  Uncaught InstagramAPI\Exception\ChallengeRequiredException: InstagramAPI\Response\LoginResponse: Challenge required. in /home/ubuntu/dev/ig/php_service/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:190
```

---

Request:

```http
POST:  https://i.instagram.com/api/v1/accounts/login/
DATA: signed_body=d06ed410e8931ce4777592894fc163b80fb3a8e94e7439f5a4376bc42c0dec1f.{"country_codes":"[{\"country_code\":\"1\",\"source\":[\"default\",\"sim\"]}]","phone_id":"39446815-e5e4-4bbb-b294-b72f46559657","_csrftoken":"4i5Xl9GRp0yNcvKNSrGwLxgs9C09GrTK","username":"...","adid":"10da892f-071d-4b6f-b461-b07ffec426fb","guid":"0d87f369-1931-4c15-a671-36121ac830d1","device_id":"android-dd7196d171463c9d","google_tokens":"[]","password":"...","login_attempt_count":"0"}&ig_sig_key_version=4
```

Response:

```http
← 400 	 308B
RESPONSE: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/364451761/1IVcENFOuC/", "api_path": "/challenge/364451761/1IVcENFOuC/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}
```
---

### Describe your issue

Just use _twoFactorLogin.php_ example, but it throws. I think this is because the server response code has changed and the structure of the response has changed as well. I do not see where to get _twoFactorIdentifier_.

**Comment by JRoy** [comment]
This isn't a two-factor-authentication issue, this is a login checkpoint (to make sure it's really you logging into the account. 

We do not support checkpoint issues as stated in the header of the issue template:
```
`challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
```

Regards.

**Comment by notcammy** [comment]
@JRoy I do believe the login/checkpoint handling has been changed on Instagram's end one way or another. Following the instructions stated in the [Wiki](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean) does not work and recently a bunch of users of my own projects have been getting the same errors when trying to renew their login cookie.
Using one of the examples such as [uploadPhoto.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php) results the same error response, so I really doubt this is because of user error. 

Any suggestions?

**Comment by phpjoker** [comment]
when login and challenge required occur, my response exception:
{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}

url and api_path has no pk or hash such as : 364451761/1IVcENFOuC/
whats happend or why?
