### ISSUE TITLE
Models: felix_deep_link in StoryCta model 

### ISSUE THREAD

**Issue by Maxim-Mazurok** [mgp25/Instagram-API#2679]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I've posted a story and linked IGTV CTA (swipe up action).
When I'm getting it using `getUserReelMediaFeed`, I can see in the debugger new property in the `story_cta` object: `felix_deep_link`:
```js
{
  story_cta: {
    links: {
      linkType: 1,
      webUri: "https://www.instagram.com/tv/XXXXXXXXXXXX/?src=swipe_up",
      deeplinkUri: "",
      // ... other as usual (empty or null)
    },
    felix_deep_link: "tv_viewer?id=1234567891234567891" // <-- this is new
  }
}
```

I think it's a deep link to view IGTV. And it's confusing because I would expect it to be in the `deeplinkUri` inside the link.

So, my question is: can we create a method for getting it? Like `$story->getStoryCta()[0]->getFelixDeepLink()`?

**Comment by JRoy** [comment]
Should be added in 3923a44ae46cd5981e3e23a01fcae6184b73e1b2

Regards.
