### ISSUE TITLE
$bodies array 

### ISSUE THREAD

**Issue by hackerjacks** [mgp25/Instagram-API#268]
How do you determine the entries in the $bodies array in functions like changeProfilePicture, uploadPhoto. uploadVideo, and direct_share? Sorry if this question is not too clear. I'm referring to the first argument to the buildBodies function.

**Comment by RageBrahimi** [comment]
Not really API related, more basic PHP help - read the general PHP docs.

**Comment by hackerjacks** [comment]
Has nothing to do with PHP, I was asking about the values in the bodies array
