### ISSUE TITLE
Blurred border

### ISSUE THREAD

**Issue by stek29** [mgp25/Instagram-API#2684]
I'm not sure that template can be used for this type of issue, so I've ignored it.

From what I see, it currently uses solid `bgColor` both for expand (for border) and for crop (for background?).

I'd be glad to implement this, but I'm not that familiar with this project -- so I'd love to hear your suggestions on how to add this properly. Should new option be created? Maybe some special value for `bgColor` can be used? Should it use some magic value for the bgColor?

Here's type of border I'm talking about:
![blurry border image](https://user-images.githubusercontent.com/11808223/58839796-f1ed6380-866b-11e9-9bd0-a4019e2e2e56.png)

Algorithm doesn't seem difficult:
- Calculate dimensions for expanded photo (`InstagramMedia::_process`)
- Following happens in `_createOutputFile->_processResource` and is media type specific:
  - Resize image to those dimensions while cropping it (not sure how to explain this one better)
  - Apply `IMG_FILTER_GAUSSIAN_BLUR` in rounds (40 seems good enough, might want to scale image down for performance reasons and scale it back. `IMG_FILTER_SMOOTH` might work too)
  - Copy that to the `$output`, and then copy `$source` over it

I'm not sure if this can be applied to CROP, but having blurred border for EXPAND would be quite useful. I also haven't looked into video handling yet.

**Comment by JRoy** [comment]
Hey @stek29, if you would like to pull request this, the implementation should be:
* New field in the `InstagramMedia` class
  * Set it in the constructor with an `$options` value.

**Comment by RainGrid** [comment]
@JRoy I'm working on this PR. Should I pass the needed for bg rectangle to _createOutputFile function or calculate and use in _processResource function directly? I've created $_bgBlurred field, calculation function and image filter. The algorithm works.

**Comment by JRoy** [comment]
@RainGrid You should do it directly in the `_processResource` function

**Comment by RainGrid** [comment]
@JRoy I also need to add constant (possibly minimum) dimensions for the small image that I'm using to apply filters. Should I place them in InstagramPhoto class?

**Comment by JRoy** [comment]
@RainGrid Yes

**Comment by JRoy** [comment]
This has been added in a18e48f94179e171ffce20533de565fc4484ae16.

Cheers

**Comment by hoemon** [comment]
Any examples of how to use this please?
I'm having trouble finding any examples on cropped/expanded image posting as well.

**Comment by RainGrid** [comment]
@hoemon https://github.com/mgp25/Instagram-API/pull/2715#issuecomment-504108249
