### ISSUE TITLE
Models: Add story_app_attribution to reel model

### ISSUE THREAD

**Issue by Maxim-Mazurok** [mgp25/Instagram-API#2688]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I've found a story with Spotify music embedded into it.
When I'm getting it using `getUserReelMediaFeed`, I can see in the debugger new property in the root of the `Story` object: `story_app_attribution`:
```php
[
  ...,
  'story_app_attribution' => 
    array (
      'app_action_text' => 'Play on Spotify',
      'app_icon_url' => 'https://instagram.fods1-1.fna.fbcdn.net/v/t51.12442-15/29740079_2048812088668836_4134550447078189559_n.png?_nc_ht=instagram.fods1-1.fna.fbcdn.net&oh=3612f453da310ce260391499e1d0ab88&oe=5D95B149',
      'content_url' => 'https://open.spotify.com/track/7DcvwMAiqKJQD1rrdfxSDx?si=f_J0wbVHQCmqC6bIZvArvA&utm_source=instagram&utm_medium=ig_stories',
      'id' => 174829003346,
      'link' => 'com.spotify.music',
      'name' => 'Spotify',
    ),
  ...
]
```

Is there any way I can get it currently? When doing `$story['story_app_attribution'];` it says "error evaluating code".
Also, can we add this model to the API?

**Comment by JRoy** [comment]
Should be added in a9457d7ba93e2b6b8c6ad0f463b87d7e8d948d68

Regards.
