### ISSUE TITLE
https://github.com/mgp25/Instagram-API

### ISSUE THREAD

**Issue by tetrahydra** [mgp25/Instagram-API#269]
I am getting this warning

```
file_get_contents(http://www.passportmalaysia.com/image.php?t=in&amp;f=1000-Page-0-%26-Page-1.jpg&amp;c=MP-53): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
 in /home/exonicom/public_html/passportmalaysia.com/library/instagram/Instagram.php on line 208
```

For the variable, I have been using

`$instagram_photo = htmlspecialchars_decode("http://www.passportmalaysia.com/image.php?t=in&f=$filename&c=" . $collection_cuid);`

But still can't work.

**Comment by RageBrahimi** [comment]
Basic PHP error, your `file_get_contents` isn't working.

**Comment by tetrahydra** [comment]
Other requests are working well, except if filename contains symbol.
