### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by bisht-sanjeet** [mgp25/Instagram-API#2691]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---
https://github.com/mgp25/Instagram-API/wiki#instagram-direct
This section has outdated information 

`$ig->direct->sendPost($recipients, $mediaId);`

Instagram needs compulsory 3 parameters. Third parameter is missing. 
3rd one is called options 
```

$options = [

	'media_type' => 'video', //compulsory, it doesn't care photo can also be sent as video and it will sent normally
	'text' => 'wow 22', // optional, if you want to send some message with media.

];

```
`$ig->direct->sendPost($recipients, $mediaId, $options);`

**Comment by dawidmierzwa95** [comment]
How can I create story photo with stickers layer (e.g. gif)?

**Comment by JRoy** [comment]
Added :)
