### ISSUE TITLE
Can't add $biography string with cyrrilic symbols to setBiography()

### ISSUE THREAD

**Issue by sergeykomlev** [mgp25/Instagram-API#2692]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Code from /src/Request/Account.php

```
public function setBiography(
    $biography)
{
    if (!is_string($biography) || strlen($biography) > 150) {
        throw new \InvalidArgumentException('Please provide a 0 to 150 character string as biography.');
    }

    return $this->ig->request('accounts/set_biography/')
        ->addPost('raw_text', $biography)
        ->addPost('_uuid', $this->ig->uuid)
        ->addPost('_uid', $this->ig->account_id)
        ->addPost('device_id', $this->ig->device_id)
        ->addPost('_csrftoken', $this->ig->client->getToken())
        ->getResponse(new Response\UserInfoResponse());
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

RESPONSE: {"result":0,"msg":" Your bio must be 150 characters or fewer.","title":"\u041e\u0439, \u0432\u0441\u0451..."

InstagramAPI\Response\UserInfoResponse: Your bio must be 150 characters or fewer.
```

---

### Describe your issue

I'm trying to set $biography with Cyrillic symbols, but I can't when this string is set in /src/Request/Account.php in setBiography() function:

```
if (!is_string($biography) || strlen($biography) > 150) {
   throw new \InvalidArgumentException('Please provide a 0 to 150 character string as biography.');
}
```
The length of $biography string is correct. No more than 150.

- When I use only Latin symbols - I can set only Latin $biography;
- When I set USER_AGENT_LOCALE to 'ru_RU'; in /src/Constants.php - I can set also Cyrillic $biography;
- When I comment this line, I can set both Cyrillic and Latin $biography's without any problem.

**Comment by JRoy** [comment]
Should be fixed with https://github.com/mgp25/Instagram-API/commit/d32c072e6c10a69c0a1882f7ac976b663f126b5b

Regards.
