### ISSUE TITLE
User functions are now returning null like getBiography() and getFollowerCount()

### ISSUE THREAD

**Issue by Splinteer** [mgp25/Instagram-API#2694]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Model\User functions now return null.
Everything was working days ago but I think Instragram updated their API since all of these functions are returning null now:
getBiography()
getFollowerCount()
getFollowingCount()
getMediaCount()

I think there is more functions returning null now but these are the only one I am using

By the way I still can use theses functions:
getPk()
getUsername()
getFullName()
getProfilePicUrl()

---

**Comment by beshoo** [comment]
I believe it is your account has been suspended

**Comment by Splinteer** [comment]
@beshoo I don't think because I still can use theses functions:
getPk()
getUsername()
getFullName()
getProfilePicUrl()

**Comment by szokeptr** [comment]
@Splinteer from where do you get the model instance? Probably the endpoint you are using is not returning those values for the User model, so they'll be null.

**Comment by beshoo** [comment]
No, it is your account am 100% sure.

http://instagram.com/currentmoodclothing
array (
  'user_name' => 'currentmoodclothing',
  'getFollowersCount' => 235861,
)

**Comment by Splinteer** [comment]
@szokeptr were right I forgot that every endpoint don't get same infos.
I could not get it with the comment endpoint.
Thanks add to get it with getInfoById() when I can't get those infos

Thank you
