### ISSUE TITLE
Web URL for the story item changed

### ISSUE THREAD

**Issue by sergeykomlev** [mgp25/Instagram-API#2696]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

Old link system for stories not working. New links look like https://www.instagram.com/stories/username/pk-code/

**Comment by JRoy** [comment]
This isn't supported on the android app, as there is no way to share a story link.

Regards.

**Comment by sergeykomlev** [comment]
> This isn't supported on the android app, as there is no way to share a story link.
> 
> Regards.

Thanks. But this links works perfect on iOS.

Story feed - https://www.instagram.com/stories/instagram/

Story item - https://www.instagram.com/stories/instagram/pk-code

**Comment by JRoy** [comment]
@sergeykomlev, this library is an emulation of the Android app. Therefore it will only support features on the Android app version.

Regards.
