### ISSUE TITLE
Request: editProfile

### ISSUE THREAD

**Issue by DrDefine** [mgp25/Instagram-API#27]
Hello. I get status "ok" from query "accounts/edit_profile/" but my profile didnt change.
code:
```php
$profileObj = $instagramObj->editProfile("http://correcturl.com", "", "somefirstname", "", "mycurmail@gmail.com", 1, false);
```
```
REQUEST: accounts/edit_profile/
DATA: ig_sig_key_version=4&signed_body=870f1c9347035af21d1da7676293b3f7e308e16b50f29fefb3137157003b21fb.%7B%22_uuid%22%3A%22cf736436-b069-4874-9345-31632aaa2b91%22%2C%22_uid%22%3A%22728485321%22%2C%22_csrftoken%22%3A%224b0204c5ac79568a959e1b33d95765ad%22%2C%22external_url%22%3A%22correcturl.com%22%2C%22phone_number%22%3A%22%22%2C%22first_name%22%3A%22somefirstname%22%2C%22biography%22%3A%22%22%2C%22email%22%3A%22mycurmail%40gmail.com%22%2C%22gender%22%3A1%2C%22is_private%22%3Afalse%7D
RESPONSE: {"status":"ok", ....
```

what am I doing wrong?

**Comment by d4mk0** [comment]
+1 me too have this problem.

**Comment by xteraflopx** [comment]
@d4mk0 @DrDefine instead of complaining about code not working, how bout you go ahead and try to solve the problem yourself. I reverse engineered the Android APK and found every single endpoint myself. I'm able to edit my account, and I'm even able to create new accounts. You can't expect someone else to do all the work for you.

**Comment by geoffroymorel** [comment]
Same issue, the changes are not taken into account even though the API response status is "ok"... I've sniffed the request on Instagram iOS : `accounts/edit_profile/` does not take the `is_private` parameter. I've tried removing it with no success.

Anyone have found a solution ? @xteraflopx maybe ?

**Comment by mgp25** [comment]
@DrDefine its working fine here

Regards
