### ISSUE TITLE
pagination in getFollowers return repeat value

### ISSUE THREAD

**Issue by uchihaarfan28** [mgp25/Instagram-API#2702]
i try to get all of followers a instagram user account, i use getFollowers but, i am received repeat value from my pagination.
do {
        try{
            
            $getFollowers = $Instagram->people->getFollowers($target->id, $rank_token, null, $next_max_id);
              
              foreach ($getFollowers->getUsers() as $followers) {
              echo $followers->getUsername() ."<br>";    
              }
                 $next_max_id =  $getFollowers->getNextMaxId();
        }catch (\Exception $e) {
           echo $e;
                
 
       
        }

       
    }while ($next_max_id !== null);

**Comment by miladrajabi2002** [comment]
I also have this problem
