### ISSUE TITLE
I can't set more then 100 reels in getReelsMediaFeed method

### ISSUE THREAD

**Issue by AlexandrDolzhikov** [mgp25/Instagram-API#2704]
Hey guys! Sorry for my English, I use google translator =)

I try to put 500 PK id's in the getReelsMediaFeed method. But I receive this error:
`InstagramAPI\Response\ReelsMediaResponse: Too many reels requested.`

After that, I put 100 PK id's, and it works is fine for me! I don't understand why does it happen? Maybe Instagram limited count reels?
Please, help me, guys! How can I put 500 PK id's, and more?

**Comment by sergeykomlev** [comment]
@AlexandrDolzhikov you fixed this problem?

**Comment by AlexandrDolzhikov** [comment]
No, I didn't fix it! I can't put more than 20 reels to this function... I can't understand it is problem with Instagram or with this library)

**Comment by sergeykomlev** [comment]
@AlexandrDolzhikov I think it's a new limits from Instagram.

**Comment by grig191** [comment]
@sergeykomlev @AlexandrDolzhikov have you managed to work around this limit for mass story watching?
