### ISSUE TITLE
Missing csfrtoken

### ISSUE THREAD

**Issue by x12x24** [mgp25/Instagram-API#2705]
Fatal error: Uncaught exception 'InstagramAPI\InstagramException' with message 'Missing csfrtoken' in /public_html/image/vendor/mgp25/instagram-php/src/Instagram.php:170

My code:
require 'vendor/autoload.php';

			/////// CONFIG ///////
			$username = '****';
			$password = '****';
			$debug = true;
			$truncatedDebug = true;
			//////////////////////
			/////// MEDIA ////////
			$photoFilename = 'image1.jpg';
			$captionText = '11';
			//////////////////////
			$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

			$ig->login($username, $password);

			try {
			    $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename);
			    $ig->timeline->uploadPhoto($photo->getFile(), ['caption' => $captionText]);
			} catch (\Exception $e) {
			    echo 'Something went wrong: '.$e->getMessage()."\n";
			}

**Comment by JRoy** [comment]
Please use the issue template, as we cannot help you if you do not. Additionally, by the looks of your file path, you're attempting to use this API from a website, which is not supported.

Regards.
