### ISSUE TITLE
Feature Request: Login Activity

### ISSUE THREAD

**Issue by kaykyr** [mgp25/Instagram-API#2707]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

### Describe your issue

Hello!

I think that "Login Activity" could be a great feature to manage devices connected to Instagram Account and logout them.

I refer it to this feature on the Instagram App: "Settings > Security > Login Activity"

**Comment by JRoy** [comment]
This feature isn't present in the Android version of the app so therefore we can not add it.

Regards.
