### ISSUE TITLE
Story sticker not working

### ISSUE THREAD

**Issue by aliazizi** [mgp25/Instagram-API#2711]
## Prerequisites

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

I'm trying to add hashtag sticker, I use example of uploadstory for this, but it's not working
The story upload but there is no hashtag in it

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->login('yourusername', 'yourpassword');


$metadata['caption'] = '#test 123 ';
	$metadata['hashtags'] = [
	// Note that you can add more than one hashtag in this array.
		[
		'tag_name' => 'test',
		'x' => 0.55132717,
		'y' => 0.24060743,
		'width' => 0.22407408,
		'height' => 0.099777035,
		'rotation' => 0.0,
		'is_sticker' => false,
		'use_custom_title' => false,
		],
	];
  $img = $imagePath;
   $ig->story->uploadPhoto($img, $metaData);
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
// Please provide your error log/dump here, for example:

POST:  https://i.instagram.com/api/v1/upload/photo/
→ 137.55kB
← 200 	 71B
RESPONSE: {"upload_id": "208584995778224", "xsharing_nonces": {}, "status": "ok"}

POST:  https://i.instagram.com/api/v1/media/configure_to_story/
DATA: signed_body=babae8054cbe41c38e9ba911159252f807d2553b8f7f500cc2f323c50a9b76e7.{"device":{"manufacturer":"OnePlus","model":"ONEPLUS A3010","android_version":"24","android_release":"7.0"},"story_hashtags":"[{\"tag_name\":\"test\",\"x\":0.55132717,\"y\":0.24060743,\"width\":0.22407408,\"height\":0.099777035,\"rotation\":0,\"is_sticker\":false,\"use_custom_title\":false}]","_csrftoken":"IisvMs2JPyf0yUwWhCthCoVcspBQI3wY","client_shared_at":"1560938185","configure_mode":"1","source_type":"3","_uid":"13681353236","_uuid":"fc4beb16-3124-4da4-a3b6-71226ed2efa3","edits":{"crop_original_size":[800,1422],"crop_zoom":1,"crop_center":[0,-0]},"extra":{"source_width":800,"source_height":1422},"caption":"#test 123 ","mas_opt_in":"NOT_PROMPTED","upload_id":"208584995778224","client_timestamp":"1560938175"}&ig_sig_key_version=4
← 200 	 1.68kB
RESPONSE: {"media": {"taken_at": 1560938185, "pk": 2069622072438740183, "id": "2069622072438740183_13681353236", "device_timestamp": 208584995778224, "media_type": 1, "code": "By4xk8_BNTX", "client_cache_key": "MjA2OTYyMjA3MjQzODc0MDE4Mw==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 800, "height": 1422, "url": "https://scontent-frx5-1.cdninstagram.com/vp/39615c2ba35fcc4c08d75df501531a8d/5D0CC3E4/t51.12442-15/e35/62204078_2297754910270600_4135097043181230132_n.jpg?_nc_ht=scontent-frx5-1.cdninstagram.com\u0026ig_cache_key=MjA2OTYyMjA3MjQzODc0MDE4Mw%3D%3D.2", "estimated_scans_sizes": [15858, 31716, 47574, 63432, 79290, 95704, 115857, 129026, 142723]}, {"width": 240, "height": 426, "url": "https://scontent-frx5-1.cdninstagram.com/vp/c808c3f5bbd2c365af80e8157c04dc79/5D0C84ED/t51.12442-15/e35/p240x240/62204078_2297754910270600_4135097043181230132_n.jpg?_nc_ht=scontent-frx5-1.cdninstagram.com\u0026ig_cache_key=MjA2OTYyMjA3MjQzODc0MDE4Mw%3D%3D.2", "estimated_scans_sizes": [2997, 5...

GET:  https://i.instagram.com/api/v1/media/2069622072438740183_13681353236/info/
→ 0B
← 200 	 1.54kB
RESPONSE: {"items": [{"taken_at": 1560938185, "pk": 2069622072438740183, "id": "2069622072438740183_13681353236", "device_timestamp": 208584995778224, "media_type": 1, "code": "By4xk8_BNTX", "client_cache_key": "MjA2OTYyMjA3MjQzODc0MDE4Mw==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 800, "height": 1422, "url": "https://scontent-frx5-1.cdninstagram.com/vp/39615c2ba35fcc4c08d75df501531a8d/5D0CC3E4/t51.12442-15/e35/62204078_2297754910270600_4135097043181230132_n.jpg?_nc_ht=scontent-frx5-1.cdninstagram.com\u0026ig_cache_key=MjA2OTYyMjA3MjQzODc0MDE4Mw%3D%3D.2", "estimated_scans_sizes": [15858, 31716, 47574, 63432, 79290, 95704, 115857, 129026, 142723]}, {"width": 240, "height": 426, "url": "https://scontent-frx5-1.cdninstagram.com/vp/c808c3f5bbd2c365af80e8157c04dc79/5D0C84ED/t51.12442-15/e35/p240x240/62204078_2297754910270600_4135097043181230132_n.jpg?_nc_ht=scontent-frx5-1.cdninstagram.com\u0026ig_cache_key=MjA2OTYyMjA3MjQzODc0MDE4Mw%3D%3D.2", "estimated_scans_sizes": [2997, ...

```

---
---

### Describe your issue

I see the tag in request and the request sent successfully, Also in instagram story exist, but there is no hashtag in it

**Comment by aliazizi** [comment]
I also try location, mention sticker but I get same result.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStory.php#L31

**Comment by aliazizi** [comment]
@mgp25 I use example of uploadstory for this, I also copy exactly your code but it's not working

**Comment by aliazizi** [comment]
@mgp25 I see all issue and wiki and example, I using this library for more than on year and I read most of the codes.
Also in request you can see my request body is ok.
But it's not working
you should check this first and reopen the issue

**Comment by aliazizi** [comment]
@mgp25 thanks I didn't the note

**Comment by FrankTheDevop** [comment]
@aliazizi mgp25 linked to the comment in the example. If you read it carefully it is explained that the Android App for Instagram does 2 things:
1. Create a data structure for the configuration where the clickable area of the sticker should be
2. Draws a the sticker as a picture onto the original picture.

This library does only do the Step 1. You are responsible to do Step 2 (drawing on the picture) yourself. You have to add this functionally on your stack!

Best Regards,
Frank
