### ISSUE TITLE
Obtaining ads in timeline feed

### ISSUE THREAD

**Issue by YogSotot** [mgp25/Instagram-API#2717]
Some time ago I started to use Instagram API v4 for collecting ads from timeline feed, and recently switched to the version 5.
I'm checking, whether the post is an advert or not, using method FeedItem::isAdAction().
But I found, that new version of Instagram API is collecting significally less ads on the same account.
When i switched library back from v5 and v4, I noticed that old library obtains more ads.

While experimenting with request headers, I found, that disabling Gzip compression in request  solved the problem, and  ads are appearing in the feed again (like in old version).

Is it possible to distinguish more ads, using methods of library ?

It it possible to get back ads in Instagram API v5 without modifying request headers?

**Comment by JRoy** [comment]
First of all, I highly recommend you don't mess with the request details, they are emulating the app and modifying them can lead to an account shadowban. I will look into ad detection however.

**Comment by JRoy** [comment]
After some research, the correct way to detect ads is by doing:
```php
if ($feedItem->isMediaOrAd()) {
  if ($feedItem->getMediaOrAd()->isAd()) {
    echo "It's an Ad!"
  } else {
    echo "It's not an ad!"
  }
```

Cheers.
