### ISSUE TITLE
Friendship function

### ISSUE THREAD

**Issue by MMrR0b0TT** [mgp25/Instagram-API#272]
Hi all,

Does anyone know how to check if an user is blocking me?
I've checked the endpoint: "friendships/show" and I could see that the blocking info is about me, if I block the user, there isn't nothing about he blocking me.

https://github.com/mgp25/Instagram-API/pull/195

**Comment by RageBrahimi** [comment]
I don't think there is a way of checking if you've been blocked natively either currently, so this cannot be supported at the minute.
