### ISSUE TITLE
How to set up multi-account activity?

### ISSUE THREAD

**Issue by cosinus90** [mgp25/Instagram-API#2725]
Hi, 
As I figured out the switching between account is made by login() function. 

But, in WEB usage prevent message it was told that frequent logging-in for every operation can cause a ban. Logically, there should be an option to keep cookie and may be other specific data and use it for next operation.

Actually I'd like to watch the stats of few accounts (for example - every 10 minutes). But if I will log into accounts every 10 minutes - I'll get the ban. 

Probably, login() function is the function I asking for? I.e. it don't login but use the data of current login connection?

Then, how do I login time-to-time as it written in the WEB prevention? (You must also be sure that your permanent process periodically calls login() inside your 24/7 PHP process, to emulate the Instagram for Android application being closed/opened and refreshing itself)

So, is there a possibility to execute operations within multiple accounts without re-login?

And next question - is it OK to start command line processes for different accounts in the same time?

**Comment by JRoy** [comment]
This behavior is not supported.

Additionally, please follow the issue template next time.
