### ISSUE TITLE
Feature Request: Add cover photo for IGTV

### ISSUE THREAD

**Issue by geek2200** [mgp25/Instagram-API#2728]
Hi,

If it possible add IGTV cover photo and set meta data for TV class or add thumbnail timestamp for cover photo in IGTV. 
Also, when set share to feed=true in TV meta data, can set thumbnail timestamp for timeline feed preview. 

Thanks a lot.

**Comment by furlanleandro** [comment]
Hello, add the code in Internal.php in uploadVideoThumbnail,

`if ($externalMetadata['thumbnail_image'] != ''){
              $videoThumbnail = new \InstagramAPI\Media\Photo\InstagramPhoto($externalMetadata['thumbnail_image'],
                  $options
              );
            }else{
              $videoThumbnail = new InstagramThumbnail(
                  $internalMetadata->getVideoDetails()->getFilename(),
                  $options
              );
            }`

When create object for IG TV, use 
`$ig->tv->uploadVideo($video->getFile(), ['share_to_feed' => true,'title' => $captionText, 'caption' => 'Teste Description','thumbnail_image' => '1920_1080.jpg']);`

**Comment by JRoy** [comment]
This feature is now exclude to our private repository. See #2655 for more information.

**Comment by JRoy** [comment]
This feature is now exclude to our private repository. See #2655 for more information.
