### ISSUE TITLE
Your version of Instagram is out of date - VB.NET

### ISSUE THREAD

**Issue by n0s3c** [mgp25/Instagram-API#273]
hey everyone
i'm trying to make a vb.net login version for this code but everytime i send login request i get a 400
please help !

my web request code : 

Public Function postreq(ByVal url As String, ByVal post As String) As String
        RQ = CType(HttpWebRequest.Create(url), HttpWebRequest)
        RQ.Method = "POST"
        RQ.UserAgent = "Instagram 8.4.0 Android (23/6.0.1; 420dpi; 1080x1794; LGE/google; Nexus 5X; bullhead; bullhead; en_US)"
        RQ.Accept = "*/*"
        RQ.ContentType = "application/x-www-form-urlencoded; charset=UTF-8"
        RQ.Headers.Add("Cookie2", "$Version=1")
        RQ.Headers.Add("Accept-Language", "en-US")

        Dim byteArr() As Byte = Encoding.Default.GetBytes(post)
        RQ.ContentLength = byteArr.Length
        Try
            Dim dataStream As Stream = RQ.GetRequestStream()
            dataStream.Write(byteArr, 0, byteArr.Length)
            rp = CType(RQ.GetResponse(), HttpWebResponse)
            Return New StreamReader(rp.GetResponseStream()).ReadToEnd()
        Catch ex As System.Net.WebException
            Return ex.Message
        End Try
        Return Nothing
    End Function

-------------------------------------------------------------------
POST https://i.instagram.com/api/v1/accounts/login/ HTTP/1.1
User-Agent: Instagram 8.4.0 Android (23/6.0.1; 420dpi; 1080x1794; LGE/google; Nexus 5X; bullhead; bullhead; en_US)
Accept: */*
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie2: $Version=1
Accept-Language: en-US
Host: i.instagram.com
Content-Length: 346
Expect: 100-continue
Connection: Keep-Alive

requestbody :

ig_sig_key_version=4&signed_body=063ede55959cea28936bc97d0f3455149f15420771c23589dd3e07fff47582f7.{"phone_id":"498cbdb6-dbf8-49e6-9c00-ae042e718f01","_csrftoken":"Zui3v4KaMIGDE7N7nRrnzft8ALVnt6Bl","username":"test","guid":"7bc028e6-a611-4a68-b2c2-f4e59a59b905","device_id":"android-eedded8cd384ce63",password":"example","login_attempt_count":"0"}
---------------------------------------------------------------------------------------------
HTTP/1.1 400 Bad Request
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Thu, 14 Jul 2016 05:13:59 GMT
Content-Type: application/json
Set-Cookie: csrftoken=GZEF2KwUmUiMSSKu4MzJ61i4vKHeDVGG; expires=Thu, 13-Jul-2017 05:13:59 GMT; Max-Age=31449600; Path=/
Set-Cookie: mid=V4cflwABAAHycd_-lGRN9D6bhAg9; expires=Wed, 09-Jul-2036 05:13:59 GMT; Max-Age=630720000; Path=/
Connection: keep-alive
Content-Length: 122

responsebody :

{"status": "fail", "message": "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram."}

**Comment by n0s3c** [comment]
why you closed my issue ? :L

**Comment by stdu00** [comment]
Hi,
I'm also working on a .net version 
Here is my code for the login, it is working fine/
I just have problem with the uploadphoto (error 415) maybe you will have a solution.
Maybe this would help.
Stdu00@gmail.com

        Public Function GetLogin(ByVal p_url As String, ByVal p_param As String, ByRef p_token As String) As String
            Dim ls_url As String = "https://i.instagram.com/api/v1/" + p_url
            Dim Req As HttpWebRequest = DirectCast(WebRequest.Create(ls_url), HttpWebRequest)

            Dim boundary As String = Guid
            'Req.Headers.Add("Connection: close")
            If gb_proxy Then
                Req.Proxy = myProxy
            End If
            Req.KeepAlive = False
            Req.Accept = "*/*"
            Req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8"
            Req.Headers.Add("Cookie2: $Version=1")
            Req.Headers.Add("Accept-Language: en-US")
            'Req.CookieContainer = New CookieContainer
            Req.CookieContainer = gCookieContainer
            Req.UserAgent = USER_AGENT
            Req.Method = "POST"


            ' Encode the parameters as form data:
            Dim encoding As New UTF8Encoding
            Dim formData As Byte() = encoding.GetBytes(p_param)
            Req.ContentLength = formData.Length

            Dim post As Stream = Req.GetRequestStream()
            post.Write(formData, 0, formData.Length)

            Dim Resp As HttpWebResponse = Req.GetResponse()
            Dim str As New System.IO.StreamReader(Resp.GetResponseStream())
            Dim ls_result As String = str.ReadToEnd()
            str.Close()

            gCookieContainer = New CookieContainer
            gCookieContainer.Add(Resp.Cookies)

            For Each cookie As Cookie In Resp.Cookies
                If cookie.Name = "csrftoken" Then
                    p_token = cookie.Value
                End If
            Next

            Return ls_result
        End Function

**Comment by n0s3c** [comment]
thanks @stdu00 , Check your email :)
