### ISSUE TITLE
Create thread with single user id

### ISSUE THREAD

**Issue by soliify** [mgp25/Instagram-API#2740]
Hello, i am trying to create a new thread with a single user. I know that in `https://i.instagram.com/api/v1/direct_v2/threads/broadcast/text/` you can send a message with an existing threadid, but i want to send a message with a non existing threadid. I have searched all your message wiki and still cannot find it, i was hoping you can help, thanks.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php#L479
