### ISSUE TITLE
Expected behavior on Media  getComments

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2743]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

  
### Describe your issue
I'm trying to load all comments from a specific media. 
 According to the comments in the Media file

> "By default, if no
>      * parameter is provided, Instagram gives you the latest page of comments
>      * and then paginates backwards via the "max_id" parameter (and the correct
>      * value for it is the "next_max_id" in the response)."

but if i do call $ig->getComments("somemedia with thousand comments") i do get on the log:

```
https://i.instagram.com/api/v1/media/2069014819832072764/comments/?can_support_threading=true

{
   "comment_likes_enabled":true,
   "comments":[
       //lots of comments here
       
   ],
   "comment_count":4582,
   
   "has_more_comments":false,
   "has_more_headload_comments":true,
   "threading_enabled":true,
   "media_header_display":"none",
   "initiate_at_top":true,
   "insert_new_comment_to_top":true,
   
   "can_view_more_preview_comments":true,
   "next_min_id":"{\"cached_comments_cursor\": \"17844065359496240\", \"bifilter_token\": \"KIABARIA0ABoAEgAOAAoABAAEAAIAAgAX3nf_ff-frn-7p3LO8LRZbZezjvdB2nq9mH7atBLQ7gVJ8dE92w7wAKvSUjP_wg97zr6Z7TAr_-3o9d3nc7v99f_fT_b7_eOr_ez__1f1d__b_ffTho823C_0ohTNKKmgMqQpWHPmYkxBQIA\"}",
   "status":"ok"
}
```

note that default answer of instagram was **next_min_id** and not next_max_id as said in doc, and it seams to match the instagram app behavior

when i do look any media in the feed the first comments to load are those with "high" popularity (usually the older, but not necessaraly chronological)

the point is: if i manually remove from the code the line:
`->addParam('can_support_threading', true);`

then the same request gets like: GET 
```
https://i.instagram.com/api/v1/media/2069014819832072764/comments/

{
   "comment_likes_enabled":true,
   "comments":[
      
   ],
   "comment_count":4582,
  
   "has_more_comments":true,
   "has_more_headload_comments":false,
   "media_header_display":"none",
   "display_realtime_typing_indicator":true,
   
    
   "can_view_more_preview_comments":true,
   "next_max_id":"{\"server_cursor\": \"QVFEcHRQWXQtb2ZneWJXUHF3ZmlKUWM4V2dCMUMtSnlUanFvRmxJQTBUU2RnR3BUaHJvZG9JWUJRS3ZYcC1ZLXdpeEItRjR4OFVUN2ZkcHVyMGNHc2VMdQ==\", \"is_server_cursor_inverse\": false}",
   "status":"ok"
}
```

then this way the instagram return **next_max_id**

 if i do use the api's original way with `->addParam('can_support_threading', true);` i'm not even able to paginate 30% of the 4000 comments without the param i get around 90% of the comments

so what is the right way?
am i missing something?

**Comment by JRoy** [comment]
I'll look into the requests sent from the app but I don't recommend tinkering with the API.

**Comment by bolds07** [comment]
> tinkering

I don't change the apis behavior, i did it just because the doc and the actual usage where like oposite and as i follow this repository for a very long time i do remeber in the past there wasn't that parameter so i removed to see what i would get

**Comment by mgp25** [comment]
Valga explained this very well in another thread

**Comment by bolds07** [comment]
@mgp25 ,  can you point me out this thread? i've read all threads about comments of 2019 and no real answer

#2601 #2450 #2319 #2147

https://www.instagram.com/p/BzjpAR9H3Ye/ this post has 43k comments, most of them comments to the media not replies

i'm not being able to get even 1k comments
