### ISSUE TITLE
Access archived story of user

### ISSUE THREAD

**Issue by etmatrix** [mgp25/Instagram-API#2746]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

For story I can get my archived story with getArchivedStoriesFeed, but not archived story of users. Could you implement it?

**Comment by JRoy** [comment]
You can't do that? If you mean highlights, check the highlight class.
