### ISSUE TITLE
Username info is possibly deprecated

### ISSUE THREAD

**Issue by LouenLeoncoeur** [mgp25/Instagram-API#2757]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->login(username, password);
    $result= $ig->people->getInfoByName('anatoliy.kuzmin1999');
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```

Error Log/var_dump:

```php
RESPONSE: Oops, an error occurred. no response from server
```

Throughout few last days I noticed that I get 'no response' error on some specific accounts few times in a row and then it works. today some specific accounts such as 'levickaya_s', 'anatoliy.kuzmin1999', '_nssssssssn_' are unavailable with 'no response' constantly. And it seems number of those accounts is growing daily.
Opening those profiles with website works okay, in the app - works but has a red label saying an error occured

**Comment by michelmelo** [comment]
Hello, this is a problem of php itself (CURL or GET) that can not connect to the instagram server. This is usually a problem on your server that must have failed communications with other servers.

**Comment by LouenLeoncoeur** [comment]
Hey, thanks for the response!
Yes, what you described happens sometimes, but this is not the case. Profiles I mentioned earlier are loading with an error in official IG app on newer versions and show blank page on older versions. The library gives 'no response from server' for them no matter what server or how many times I try. I guess it's IG problem but newer versions of app give data despite the error whereas the lib gives nothing, so the current lib version could be old enough to not support basic IG functions soon

**Comment by JRoy** [comment]
Hi, michelmelo is wrong, there is a response from the server but the response was marked as failed. You can enable debug mode to see the response.

Cheers.

**Comment by LouenLeoncoeur** [comment]
JRoy, I'm sorry to write to closed issue but as you can see in the code, debug mode is enabled and the entire response I see is 
`GET: https://i.instagram.com/api/v1/users/parus.88/usernameinfo/ → 0B ← 500 25B RESPONSE: Oops, an error occurred. no response from server`
Current version of library is not loading anything from a number of IG profiles, I found at least 20. 
Could you upgrade IG version used in the library?

**Comment by JRoy** [comment]
I'm sure this doesn't have to do with constants, rather the volatility of this endpoint. This endpoint was used to get the information of a user from a comment mention, however now the user ID is sent along with the mention, deprecating this endpoint, I'll see what I find after I get off holiday.

Issue reopened.

**Comment by bolds07** [comment]
@JRoy  

> This endpoint was used to get the information of a user from a comment mention

If this endpoint is used to get the data only on mention what is the endpoint used to get info when the user goes to explorar and click on search for profiles?

**Comment by JRoy** [comment]
@bolds07 See `Discover#search()` that will return a user's id

**Comment by LouenLeoncoeur** [comment]
Instagram has fixed the problem, now `People#getInfoByName` is working fine with all accounts

**Comment by JRoy** [comment]
94acd75b8db47d5ada5f86614dc4735d742960fa should fix this

Regards.
