### ISSUE TITLE
Any option how to change user status to active?

### ISSUE THREAD

**Issue by mihaelartz** [mgp25/Instagram-API#2759]
Every time I login, I send messages via direct, I simply do some activity, all my followers see me the status that was the last one when i was login over the phone, the better I was reconnected i was offline.

Sorry for my bad English. Thanks! 🙂

**Comment by JRoy** [comment]
See `Account::getPresenceStatus()`, `Account::enablePresence()`, and `Account::disablePresence()`

Also, please follow the issue template as we will answer you in the future if you do not follow it.

Cheers.
