### ISSUE TITLE
STDIN not sorking

### ISSUE THREAD

**Issue by edward-joseph** [mgp25/Instagram-API#2761]
## STDIN
Unfortunately, after many attempts I failed to use the following code:
```php
$ig = new \InstagramAPI\Instagram(false,false);
try {
    $loginResponse = $ig->login('**********','**********');
    if ($loginResponse !== null && $loginResponse->isTwoFactorRequired()) {
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();
        $verificationCode = trim(fgets(STDIN));
        $ig->finishTwoFactorLogin($this->usermail,$this->password,$twoFactorIdentifier,$verificationCode);
    }
} catch (Exception $e)
    $this->errorType = $e->getMessage();
}
```
<b> Warning: fgets() expects parameter 1 to be resource, string given in /home/edwardjo/public_html/Instagram-API/index.php on line 16</b>

and

<b> You must provide a verification code and two-factor identifier to finishTwoFactorLogin().</b>

<i>Please help me out how to fix this</i>

**Comment by mgp25** [comment]
So... you are trying to run a CLI script in a webserver... right...

Answering to your question:
> Please help me out how to fix this

Use CLI or change the way to insert data. Not API issue
