### ISSUE TITLE
Please unblock account

### ISSUE THREAD

**Issue by borutkovacic345** [mgp25/Instagram-API#2763]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.
---

### Describe your issue

I have been blocked from this repo, probably because i asked something about direct inbox feature. I have read the terms of use, and i am aware that i must not use this software to spam others. I can prove that i am not. Looks like it was misunderstanding; We are working on webhook service and we are only sending replies (we dont send messages first) based on keywords.

We want to help. I already contributed to the project and i am planning to do more.

I currently use my second account.

**Comment by JRoy** [comment]
Asking to be unblocked just gives us more ground for you to be blocked again. How are we supposed to know what account you're referring to when you didn't mention it and you're posting the issue from a secondary account (Secondary accounts are also against GitHub's terms of service).

Basically, please don't asked to be unblocked on the issue tracker. If you'd like to continue contributing, do so from this account. But note, spam of the issue tracker or any other sort will result in another block.

Regards.
