### ISSUE TITLE
Get list of all threads in direct inbox

### ISSUE THREAD

**Issue by borutkovacic345** [mgp25/Instagram-API#2764]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

**Just to clarify, i am not using this to spam others!** We are working on webhook service that will send replies only to some threads.

Hello, i am trying to use pagination with direct inbox. I read the wiki. I also saw [similar issue](https://github.com/mgp25/Instagram-API/issues/1535) on this, but i am trying to use maxID(as described in wiki). This is my code: 

```
      $maxId = null;
      $threads = array();
      do {
        $direct = $this->ig->direct->getInbox($maxId);
        $threads = array_merge($threads, $direct->getInbox()->getThreads());
        //$this->logger->log("Unread count".$direct->getInbox()->getUnseenCount());
        $maxId = $direct->getNextMaxId();
      } while ($maxId !== null);
```

It is returning me this error: 

> PHP Fatal error:  Uncaught LazyJsonMapper\Exception\LazyJsonMapperException: Unknown function "getNextMaxId"

I also tried: 

```
      do {
        $direct = $this->ig->direct->getInbox($maxId);
        $threads = array_merge($threads, $direct->getInbox()->getThreads());
        //$this->logger->log("Unread count".$direct->getInbox()->getUnseenCount());
        $maxId = $direct->getOldestCursor();
      } while ($maxId !== null);
```

This also returns: 

> PHP Fatal error:  Uncaught LazyJsonMapper\Exception\LazyJsonMapperException: Unknown function "getOldestCursor"

Am i doing something wrong? Is it possible to get all direct inbox threads? Or if not, is it possible to get all unread items?

**Comment by szokeptr** [comment]
The cursor is not in the `DirectInboxResponse`, but the `DirectInbox` model, so you need to call `$direct->getInbox()->getOldestCursor()` to get the cursor. 

I’d strongly recommend you to take a look at all the responses and models because they are all easy to read and you will know how to access each property.

**Comment by JRoy** [comment]
@szokeptr explained this, as I would've, closing.

**Comment by borutkovacic345** [comment]
So first i call `$maxId = $direct->getInbox()->getOldestCursor()` and then `$direct = $this->ig->direct->getInbox($maxId);` for pagination? Yes i have read response model. I also saw that this is a property of `DirectInbox`. 

But i tried the following code and it is still returning me errors: 

```
      do {
        $maxId = $this->ig->direct->getInbox()->getOldestCursor();
        var_dump($maxId);
        $direct = $this->ig->direct->getInbox($maxId);
        $threads = array_merge($threads, $direct->getInbox()->getThreads());
        //$this->logger->log("Unread count".$direct->getInbox()->getUnseenCount());
        //$maxId = $direct->getInbox()->getOldestCursor();
      } while ($maxId !== null);
```

> Unknown function "getOldestCursor"
(in second line where $maxId is defined)

**Comment by borutkovacic345** [comment]
oh nevermind, i fixed it
