### ISSUE TITLE
uploadPhoto not working

### ISSUE THREAD

**Issue by edward-joseph** [mgp25/Instagram-API#2766]
## Input file "..." doesn't exist.
To upload a photo from the uploadPhoto function:
```php
    $ig = new \InstagramAPI\Instagram(false,false);
    try {
        $ig->login('*****','*****');
    } catch(Exception $e) {
        echo $e->getMessage();
        exit(0);
    }
    try {
        $photo = new \InstagramAPI\Media\Photo\InstagramPhoto('https://edwardjoseph.ir/Instagram-API/image.jpg');
        $ig->timeline->uploadPhoto($photo->getFile(), ['caption' => 'IS TEST']);
    } catch (\Exception $e) {
        echo $e->getMessage();
    }
```
Unfortunately, every time I try, I will go through the following error (File exists): **Input file https://edwardjoseph.ir/Instagram-API/image.jpg" doesn't exist.**

If you have a solution, please help :(

**Comment by mgp25** [comment]
I think you haven't searched enough in the repository. Remote files are not allowed, only local ones

Regards
