### ISSUE TITLE
cant use uploadVideo

### ISSUE THREAD

**Issue by edward-joseph** [mgp25/Instagram-API#2767]
## Undefined variable: statusCode
Unfortunately, I encountered an error while using the `uploadVideo` function!
My code:
```php
public function uploadVideo($videoAddres,$videoCaption=null,$videoLocation=null) {
    try {
        if ($videoLocation != null) {
            $videoLocation = $this->setLocation($videoLocation[0],$videoLocation[1]);
        }
        $video = new \InstagramAPI\Media\Video\InstagramVideo($videoAddres);
        $ig->timeline->uploadVideo($video->getFile(), ['caption' => $videoCaption,'location'=>$videoLocation]);
    } catch (Exception $e) {
        $this->getException($e);
    }
}

$IG->uploadVideo('video.mp4','I AM DEVELOPER #DEV #MEDIA_TARFAND',['35.6962217','50.9660343']);
```
The mistakes I encountered:

**` Notice: Undefined variable: statusCode in /home/edwardjo/public_html/Instagram-API/vendor/mgp25/instagram-php/src/Utils.php on line 361`**

_and_

**`You must have FFprobe to analyze video details. Ensure that its binary-folder exists in your PATH environment variable, or manually set its full path via "\InstagramAPI\Utils::$ffprobeBin = '/home/exampleuser/ffmpeg/bin/ffprobe';" at the start of your script.`**

**please help**

**Comment by JRoy** [comment]
Your first error seems unrelated to the  code you've show. As for the second error, you have to install ffmpeg and ffprobe and set the path to it like described in many other issues

Cheers.

**Comment by edward-joseph** [comment]
I'm currently using a purchased hosting site, how to install two ffmpeg and ffprobe add-ons in my host?

**Comment by JRoy** [comment]
This API is not for web usage

**Comment by edward-joseph** [comment]
Do you know a library that uses the Instagram API and can be used on the web? (Because I'm designing a website and I need a library to connect with the Instagram API)

**Comment by edward-joseph** [comment]
> 
> 
> This API is not for web usage

Do you know a library that uses the Instagram API and can be used on the web? (Because I'm designing a website and I need a library to connect with the Instagram API)
