### ISSUE TITLE
Questions about Constants

### ISSUE THREAD

**Issue by yaniferhaoui** [mgp25/Instagram-API#2768]
Hello, I would like to customize Constants configuration to appear different from other Bots which use this API.

But I don't really understand what are const variables : EXPERIMENTS, LOGIN_EXPERIMENTS and LAUNCHER_CONFIGS ?

If they are related to a typical phone, can I find them in my personnal phone ? 
How can I customize/change them without appear suspicious for Instagram platform ?

If someone could explain or has infos about that?

Thanks for your time :)

**Comment by JRoy** [comment]
I **highly** recommend you leave the constants as is. The constants are safe from the get-go. As long as you are not spamming, you have no need to worry.

Cheers

**Comment by yaniferhaoui** [comment]
ok thanks, one more thing, I have extract the IG_SIG_KEY from the instagram apk version 98.0.0.15.119.
What could go wrong if I change the current IG_SIG_KEY with the new?
