### ISSUE TITLE
setCloseFriends() not work

### ISSUE THREAD

**Issue by walterjrp** [mgp25/Instagram-API#2771]
# Bug Report

---

Hello
I'm trying to use the setCloseFriends () function but I did not succeed.
I always get the following return:

```php
Something went wrong: No response from server. Either a connection or configuration error.
```

--

My PHP code:

```php
<?php

set_time_limit(0);

require 'vendor/autoload.php';

$username = 'xx';
$password = 'xx';
$debug = false;
$truncatedDebug = false;

\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {

    $ig->login($username, $password);

    $people = new \InstagramAPI\Request\People($ig);
    $people->setCloseFriends(['juninhochr']);

} catch (\Exception $e) {
    echo 'Something went wrong: ' . $e->getMessage() . "\n";
    exit(0);
}
```

How can I solve this problem?

**Comment by SHELA** [comment]
IG Down

**Comment by szokeptr** [comment]
Instagram is [down](https://downdetector.com/status/instagram) at the moment.

**Comment by JRoy** [comment]
As mentioned in the above posts, parts of Instagram's servers are not responding to all requests at the moment. This is not an API problem.

Regards.

**Comment by walterjrp** [comment]
@JRoy I've been trying to do this for a week.

**Comment by walterjrp** [comment]
Guys, this is not a problem right now.
I've been trying to use functionality for days.

**Comment by JRoy** [comment]
I'll try this request later, and if it doesn't work I'll fix it

**Comment by walterjrp** [comment]
Ok, thank you!
I tried to fix it myself but I did not succeed.

**Comment by walterjrp** [comment]
Hi @JRoy, any news?

**Comment by JRoy** [comment]
Hello @walterjrp, I've just tested this request and it works for me. Here is the code I used:
```php
$ig->people->setCloseFriends(['25025320'], []);
```

Make sure you read the documentation for the function.

**Comment by walterjrp** [comment]
@JRoy Sorry. I was passing the username.
What you were going through would be a kind of ID? How can I get the user ID?

**Comment by mgp25** [comment]
How about reading the wiki and examples?
