### ISSUE TITLE
Want to get user follower_count and following_count

### ISSUE THREAD

**Issue by abbasjami** [mgp25/Instagram-API#2775]
When i try search feeds based on tags and it returns me all feeds with all data and also it has user object (Modal/User) but it did not have all necessary information i wanted (e.g followers_count/followings_count) etc 
for getting these followers_count and followings _count i need to make getUserInfoById 
that causing an error 
"Throttled by Instagram because of too many API requests."
please suggest me what i have to do 
i want to get all information for user when i getfeeds() searched by hashtag.
then easily i can implement user followers and followings filters

**Comment by mgp25** [comment]
Issue doesn't follow the proper format. Therefore is considered as invalid.

Regards

**Comment by abbasjami** [comment]
how i have to create issue ???

**Comment by abbasjami** [comment]
what is proper format ???
