### ISSUE TITLE
How can I prevent the scrypt be stoped when the username does not exist?

### ISSUE THREAD

**Issue by Tivixo** [mgp25/Instagram-API#2777]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

__INSERT YOUR DESCRIPTION HERE__

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
INSERT YOUR CODE HERE
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
INSERT YOUR DEBUG LOG HERE
```

**Comment by Tivixo** [comment]
Hi,

I want get info from some usernames, when they are exist everything is ok, but if one of them are not all script stopped and don't check other username.
how can I fix this? I want if I get 404 response, ignore the username go for next username, not being stopped.
my code:
`$userId = $ig->people->getUserIdForName($firstusername);`

response:
`PHP Fatal error:  Uncaught InstagramAPI\Exception\NotFoundException: Requested resource does not exist. in /var/www/ig/vendor/mgp25/instagram-php/src/Client.php:491
Stack trace:
#0 /var/www/ig/vendor/mgp25/instagram-php/src/Request.php(832): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\UserInfoResponse), '<!DOCTYPE html>...', Object(GuzzleHttp\Psr7\Response))
#1 /var/www/ig/vendor/mgp25/instagram-php/src/Request/People.php(76): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\UserInfoResponse))
#2 /var/www/ig/vendor/mgp25/instagram-php/src/Request/People.php(96): InstagramAPI\Request\People->getInfoByName('jhcxfhcjdhvjxfk...')
#3 /var/www/ig/geters/gettargetinfo.php(39): InstagramAPI\Request\People->getUserIdForName('jhcxfhcjdhvjxfk...')
#4 {main}
  thrown in /var/www/ig/vendor/mgp25/instagram-php/src/Client.php on line 491`

**Comment by mgp25** [comment]
1. try catch
2. verify wether the user exists or not

regards
