### ISSUE TITLE
How can I process an array of stories in markMediaSeen ()?

### ISSUE THREAD

**Issue by thevisuales** [mgp25/Instagram-API#2778]
Well the title maybe the somewhat confusing but I will explain myself better.

I have created a function that collects the stories of 2 users and stores them in a .json file

```php
$reels = $stories_reels->getReels()->getData();
                        foreach ($reels as $r) {
                            $items = [];
                            $stories_loop = [];
                            $items = $r->getItems();

                            foreach ($items as $item) {
                                if (!$item->getId()) {
                                    // Item is not valid
                                }
                                $stories_loop[] = $item;
                            }

                            if (empty($stories)) {
                                $stories = $stories_loop;
                            } else {
                                $stories = array_merge($stories, $stories_loop);
                            }
                        }

$fp = fopen('storypack.json', 'w');
fwrite($fp, json_encode($stories));
fclose($fp);
```

So far so good, all the data collected from the stories is stored.
The problem is when trying to use it later to mark them as seen with markMediaSeen ().
It turns out that I am recovering the information like this:

```php
$data_storypack = file_get_contents('storypack.json');
$array_storypack = json_decode($data_storypack, true);

if(!empty($array_storypack) && is_array($array_storypack) ){
                    $ig->story->markMediaSeen($array_storypack);
}
```

But when executing it it shows me this error:
**All story items must be instances of \InstagramAPI\Response\Model\Item.**

Obviously in this case it does not come from getItem, since I got it from getItem before saving it to the json.

Could you tell me how I should treat the information to validate it? I do not understand what difference can exist, both arrays are equal before and after the json.

Thank you very much for your time!

**Comment by mgp25** [comment]
An array is not the same as an object. You should serialize the object. Not related to the API.
