### ISSUE TITLE
How to post specials chars in the caption ?

### ISSUE THREAD

**Issue by stdu00** [mgp25/Instagram-API#278]
Hi,
I try to upload a photo using a caption like this : 
```php
$caption = 'test © test';     // caption
```
But the configure fonction seems fail : 
```
REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=6c51071c2a3045a71efdb707a7407be724002eee19cdd8f397bee1c1ae3315b9.
```
```json
RESPONSE: {"status": "fail", "message": "Please update your Instagram app to continue posting photos"}
```

If I remove the copyright from the caption eveything is ok.
Someone know how to post this ?
Thanks
Stdu

**Comment by mgp25** [comment]
@stdu00 it seems there is some data mising in the request, check it or post the full request

**Comment by stdu00** [comment]
Hi,
Here is the full log, seems the configure request missed some data
 
REQUEST: si/fetch_headers/?challenge_type=signup&guid=3a909f2f1ceb468fb372473234e754b4
RESPONSE: {"status": "ok", "shift": 18, "header": "O9c8D7SNXiuwHpRYJ42lUM6g3VkanZBt", "edges": 100, "iterations": 10, "size": 42}

REQUEST: accounts/login/
DATA: ig_sig_key_version=4&signed_body=f5a1162cd499d950ba4c052126e0f05e526401c218dc1a79aecb1c216631531b.{"phone_id":"9ba2365d-58bb-4134-b6d8-b3867174ea44","_csrftoken":"Set-Cookie: csrftoken=Cmu1NBKeTWROCS296omrel7x9qSzT7BH","username":"xxx","guid":"b55b858c-fb24-458f-bd33-79ba17cdc5b4","device_id":"android-8408de3662e4ef73","password":"xxxx","login_attempt_count":"0"}
RESPONSE: {"logged_in_user": {"username": "xxx", "has_anonymous_profile_picture": true, "profile_pic_url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "xxx", "pk": 3195927469, "is_private": true}, "status": "ok"}

REQUEST: qe/sync/
DATA: ig_sig_key_version=4&signed_body=45478c703f547f5931c1cd12d3fbb19dbda15826fb3e01bf8f2068b5fb7fe745.{"_uuid":"b55b858c-fb24-458f-bd33-79ba17cdc5b4","_uid":3195927469,"id":3195927469,"_csrftoken":"ldDbjZi221CZgqCQsG10CrqSJVV5NGAa","experiments":"ig_android_progressive_jpeg,ig_creation_growth_holdout,ig_android_report_and_hide,ig_android_new_browser,ig_android_enable_share_to_whatsapp,ig_android_direct_drawing_in_quick_cam_universe,ig_android_huawei_app_badging,ig_android_universe_video_production,ig_android_asus_app_badging,ig_android_direct_plus_button,ig_android_ads_heatmap_overlay_universe,ig_android_http_stack_experiment_2016,ig_android_infinite_scrolling,ig_fbns_blocked,ig_android_white_out_universe,ig_android_full_people_card_in_user_list,ig_android_post_auto_retry_v7_21,ig_fbns_push,ig_android_feed_pill,ig_android_profile_link_iab,ig_explore_v3_us_holdout,ig_android_histogram_reporter,ig_android_anrwatchdog,ig_android_search_client_matching,ig_android_high_res_upload_2,ig_android_new_browser_pre_kitkat,ig_android_2fac,ig_android_grid_video_icon,ig_android_white_camera_universe,ig_android_disable_chroma_subsampling,ig_android_share_spinner,ig_android_explore_people_feed_icon,ig_explore_v3_android_universe,ig_android_media_favorites,ig_android_nux_holdout,ig_android_search_null_state,ig_android_react_native_notification_setting,ig_android_ads_indicator_change_universe,ig_android_video_loading_behavior,ig_android_black_camera_tab,liger_instagram_android_univ,ig_explore_v3_internal,ig_android_direct_emoji_picker,ig_android_prefetch_explore_delay_time,ig_android_business_insights_qe,ig_android_direct_media_size,ig_android_enable_client_share,ig_android_promoted_posts,ig_android_app_badging_holdout,ig_android_ads_cta_universe,ig_android_mini_inbox_2,ig_android_feed_reshare_button_nux,ig_android_boomerang_feed_attribution,ig_android_fbinvite_qe,ig_fbns_shared,ig_android_direct_full_width_media,ig_android_hscroll_profile_chaining,ig_android_feed_unit_footer,ig_android_media_tighten_space,ig_android_private_follow_request,ig_android_inline_gallery_backoff_hours_universe,ig_android_direct_thread_ui_rewrite,ig_android_rendering_controls,ig_android_ads_full_width_cta_universe,ig_video_max_duration_qe_preuniverse,ig_android_prefetch_explore_expire_time,ig_timestamp_public_test,ig_android_profile,ig_android_dv2_consistent_http_realtime_response,ig_android_enable_share_to_messenger,ig_explore_v3,ig_ranking_following,ig_android_pending_request_search_bar,ig_android_feed_ufi_redesign,ig_android_video_pause_logging_fix,ig_android_default_folder_to_camera,ig_android_video_stitching_7_23,ig_android_profanity_filter,ig_android_business_profile_qe,ig_android_search,ig_android_boomerang_entry,ig_android_inline_gallery_universe,ig_android_ads_overlay_design_universe,ig_android_options_app_invite,ig_android_view_count_decouple_likes_universe,ig_android_periodic_analytics_upload_v2,ig_android_feed_unit_hscroll_auto_advance,ig_peek_profile_photo_universe,ig_android_ads_holdout_universe,ig_android_prefetch_explore,ig_android_direct_bubble_icon,ig_video_use_sve_universe,ig_android_inline_gallery_no_backoff_on_launch_universe,ig_android_image_cache_multi_queue,ig_android_camera_nux,ig_android_immersive_viewer,ig_android_dense_feed_unit_cards,ig_android_sqlite_dev,ig_android_exoplayer,ig_android_add_to_last_post,ig_android_direct_public_threads,ig_android_prefetch_venue_in_composer,ig_android_bigger_share_button,ig_android_dv2_realtime_private_share,ig_android_non_square_first,ig_android_video_interleaved_v2,ig_android_follow_search_bar,ig_android_last_edits,ig_android_video_download_logging,ig_android_ads_loop_count_universe,ig_android_swipeable_filters_blacklist,ig_android_boomerang_layout_white_out_universe,ig_android_ads_carousel_multi_row_universe,ig_android_mentions_invite_v2,ig_android_direct_mention_qe,ig_android_following_follower_social_context"}
RESPONSE: {"ig_android_report_and_hide": {"is_enabled": "enabled"}, "status": "ok", "ig_android_boomerang_entry": {"is_enabled": "enabled"}, "ig_ranking_following": {"followers_list_use_model": "true", "search_request_params": "{\"ranking_experiment_name\":\"nullstate_model\"}", "followers_list_should_rank_randomize": "true"}, "ig_fbns_shared": {"enable_shared_process": "-1"}, "ig_android_dv2_consistent_http_realtime_response": {"is_enabled": "1"}, "ig_timestamp_public_test": {"is_seamless_holdout": "false", "behavior": "test", "timestamp_style": "text_row_under", "is_feed_ui_holdout": "false", "experiment_flavor": "timestamp_below_comments_with_explore_attribution"}, "ig_android_histogram_reporter": {"report_rate": "1"}, "ig_android_prefetch_explore_delay_time": {"delay_time_ms": "1000"}, "ig_android_explore_people_feed_icon": {"show_icon": "1"}, "ig_android_ads_cta_universe": {"cta_in_profile": "1", "overlay_on_like": "1"}, "ig_android_boomerang_layout_white_out_universe": {"is_enabled": "true"}, "ig_android_inline_gallery_backoff_hours_universe": {}, "ig_android_video_loading_behavior": {"longer_video_timer": "1"}, "ig_android_video_stitching_7_23": {"stitching_ads": "enabled", "stitching_all": "enabled"}, "ig_android_periodic_analytics_upload_v2": {"is_enabled": "1", "upload_interval_seconds": "120"}, "ig_android_enable_client_share": {"is_enabled": "0"}, "ig_android_disable_chroma_subsampling": {}, "ig_android_ads_holdout_universe": {"behavior": "test"}, "ig_android_anrwatchdog": {"is_enabled": "1"}, "ig_android_ads_loop_count_universe": {"is_enabled": "1"}, "ig_android_ads_overlay_design_universe": {"design": "3"}, "ig_android_progressive_jpeg": {"min_scan": "0", "peek_media": "enabled"}, "ig_video_use_sve_universe": {"is_enabled": "enabled"}, "ig_android_react_native_notification_setting": {"is_enabled": "disabled"}, "ig_android_fbinvite_qe": {"ig_invite_page_size": "50", "ig_invite_show_new_fb_invite": "1", "ig_invite_section_on_top": "1", "ig_separate_invite_section": "1", "ig_invite_show_old_invites": "1"}, "ig_android_video_download_logging": {"is_enabled": "enabled"}, "ig_android_post_auto_retry_v7_21": {"auto_retry_fast": "true", "auto_retry_mode": "auto"}, "ig_android_ads_full_width_cta_universe": {"full_width": "1", "enable_overlay": "1", "move_indicator": "1"}, "ig_android_app_badging_holdout": {"behavior": "pass"}, "ig_android_infinite_scrolling": {}, "ig_android_high_res_upload_2": {"size_small": "200", "quality_large": "70", "size_large": "1080", "quality_small": "95"}, "ig_android_options_app_invite": {"is_enabled": "1"}, "ig_android_inline_gallery_no_backoff_on_launch_universe": {"ig_android_inline_gallery_no_backoff_on_launch": "disabled"}, "ig_android_share_spinner": {"is_enabled": "disabled"}, "ig_android_new_browser": {"is_enabled": "enabled"}, "ig_fbns_push": {"is_enabled": "enabled", "user_present": "enabled", "boot": "enabled", "network": "enabled", "svc_ping": "disabled"}, "ig_android_direct_mention_qe": {"is_enabled": "1", "active_dismisser_min_action_count": "5", "active_dismisser_ratio": "3"}, "ig_creation_growth_holdout": {"behavior": "pass"}, "ig_android_mentions_invite_v2": {"is_enabled": "0"}, "ig_android_feed_unit_footer": {"feed_unit_footer": "1"}, "ig_android_prefetch_venue_in_composer": {"is_enabled": "enabled"}, "ig_android_camera_nux": {"camera_nux": "1"}, "ig_android_direct_plus_button": {"is_enabled": "0"}, "ig_android_inline_gallery_universe": {"ig_android_inline_gallery_enabled": "enabled"}, "ig_android_feed_reshare_button_nux": {"is_enabled": "1", "minimum_nux_reshow_interval_seconds": "43200", "maximum_nux_quota": "3"}, "ig_android_boomerang_feed_attribution": {"is_enabled": "enabled"}, "ig_android_prefetch_explore_expire_time": {"expire_time_in_min": "180"}, "ig_android_feed_unit_hscroll_auto_advance": {"auto_advance": "1"}, "ig_android_enable_share_to_messenger": {"is_enabled": "1"}, "ig_android_search_null_state": {"number_of_search_history_item": "3", "experiment_flavor": "search_null_state_with_hide_item"}, "ig_android_universe_video_production": {"upload_per_pixel_bit_rate_16by9": "9.7222", "upload_width_max_low": "540", "upload_width_max_mid": "640", "screen_width_low": "500", "total_memory_low": "520", "upload_per_pixel_bit_rate_9by16": "7", "cpu_cores_low": "1", "upload_per_pixel_bit_rate_square": "7", "total_memory_mid": "1000", "cpu_cores_mid": "1", "upload_width_max_high": "720", "screen_width_mid": "700", "upload_width_min": "480"}, "ig_android_new_browser_pre_kitkat": {"is_enabled": "enabled"}, "ig_android_rendering_controls": {"high_quality_downsample_enabled": "false"}, "ig_android_hscroll_profile_chaining": {"is_enabled": "1", "auto_advance": "1"}, "ig_video_max_duration_qe_preuniverse": {"max_duration_sec": "60"}, "ig_android_profile_link_iab": {"is_enabled": "enabled"}, "ig_android_huawei_app_badging": {"is_enabled": "1"}, "ig_android_media_favorites": {"is_enabled": "1"}, "ig_android_business_profile_qe": {"is_enabled": "disabled"}, "ig_android_mini_inbox_2": {"enable_actionbar_pinning": "true"}, "ig_android_2fac": {"is_enabled": "disabled"}, "ig_android_asus_app_badging": {"is_enabled": "1"}, "ig_explore_v3": {"is_explore_v3_enabled": "enabled"}}

REQUEST: friendships/autocomplete_user_list/
RESPONSE: {"status": "fail", "message": "Sorry, too many requests. Please try again later."}

REQUEST: feed/timeline/
RESPONSE: {"status": "ok", "num_results": 1, "is_direct_v2_enabled": true, "auto_load_more_enabled": true, "items": [{"taken_at": 1468831962, "pk": 1296978964287596462, "id": "1296978964287596462_3195927469", "device_timestamp": 1468831980, "media_type": 1, "code": "BH_y38PhCeuFqjgz_cgE1RsN0BcH_mMQatXQaQ0", "client_cache_key": "MTI5Njk3ODk2NDI4NzU5NjQ2Mg==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s1080x1080/e15/fr/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 1080, "height": 720}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 750, "height": 500}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 640, "height": 426}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s480x480/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 480, "height": 320}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s320x320/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 320, "height": 213}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s240x240/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 240, "height": 160}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s150x150/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 150, "height": 100}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s640x640/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 640, "height": 640}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s480x480/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 480, "height": 480}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s320x320/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 320, "height": 320}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s240x240/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 240, "height": 240}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s150x150/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 150, "height": 150}]}, "original_width": 1080, "original_height": 720, "user": {"username": "xxx", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "xxx", "pk": 3195927469, "is_verified": false, "is_private": true}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjUwMTJjZWVhZDg2NDQzMWRhZWMxM2MwOTIxYjk3ZTc4MTI5Njk3ODk2NDI4NzU5NjQ2MiIsInNlcnZlcl90b2tlbiI6IjE0Njg4MzI2MzU1NzV8MTI5Njk3ODk2NDI4NzU5NjQ2MnwzMTk1OTI3NDY5fDQwZjc5ZTZiODM0MDVmZTBmNzZjNzJjNjc4MTVmZWM5ZGQ5YmI5OWJiMjE1ODJiNjM1YjQ4N2I5N2NmZmIzNTIifSwic2lnbmF0dXJlIjoiIn0=", "like_count": 0, "likers": [], "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 2, "comments": [], "comment_count": 0, "caption": {"status": "Active", "user_id": 3195927469, "created_at_utc": 1468831963, "created_at": 1468831963, "bit_flags": 0, "user": {"username": "xxx", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "xxx", "pk": 3195927469, "is_verified": false, "is_private": true}, "content_type": "comment", "text": "Tour de France 2016 - Stage 15 - CULOZ, FRANCE - JULY 17 : PANTANO GOMEZ Jarlinson (COL) Rider of IAM CYCLING and MAJKA Rafal (POL) Rider of TINKOFF in action during stage 15 of the 2016 Tour de France a 160 km stage between Bourg-en-Bresse and Culoz, on July 17, 2016 in Culoz, France , 17/07/2016 ( Photo by Nico Vereecken / Photonews", "media_id": 1296978964287596462, "pk": 17849574181100472, "type": 1}, "caption_is_edited": false, "photo_of_you": false}], "more_available": false, "next_max_id": null}

REQUEST: direct_v2/inbox/?
RESPONSE: {"status": "ok", "seq_id": 0, "pending_requests_total": 0, "inbox": {"unseen_count": 0, "has_older": false, "unseen_count_ts": 1468832636385117, "threads": [{"named": false, "users": [{"username": "vkalut", "has_anonymous_profile_picture": false, "friendship_status": {"following": false, "incoming_request": false, "outgoing_request": false, "blocking": false, "is_private": false}, "profile_pic_url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-19/11116877_463824250437803_216223101_a.jpg", "full_name": "Vincent Kalut \ud83c\udde7\ud83c\uddea", "pk": 17640627, "is_private": false}], "has_newer": false, "thread_id": "340282366841710300949128128637858286849", "image_versions2": {"candidates": [{"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s1080x1080/e15/fr/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 1080, "height": 720}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 750, "height": 500}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 640, "height": 426}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s480x480/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 480, "height": 320}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s320x320/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 320, "height": 213}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s240x240/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 240, "height": 160}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s150x150/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 150, "height": 100}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s640x640/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 640, "height": 640}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s480x480/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 480, "height": 480}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s320x320/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 320, "height": 320}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s240x240/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 240, "height": 240}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s150x150/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 150, "height": 150}]}, "last_activity_at": 1468831992512095, "newest_cursor": "27095167853147480935982391906795520", "is_spam": false, "has_older": true, "oldest_cursor": "27095167853147480935982391906795520", "left_users": [], "muted": false, "items": [{"user_id": 3195927469, "timestamp": 1468831992512095, "item_type": "media_share", "media_share": {"taken_at": 1468831962, "pk": 1296978964287596462, "id": "1296978964287596462_3195927469", "device_timestamp": 1468831980, "media_type": 1, "code": "BH_y38PhCeuFqjgz_cgE1RsN0BcH_mMQatXQaQ0", "client_cache_key": "MTI5Njk3ODk2NDI4NzU5NjQ2Mg==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s1080x1080/e15/fr/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 1080, "height": 720}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 750, "height": 500}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 640, "height": 426}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s480x480/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 480, "height": 320}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s320x320/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 320, "height": 213}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s240x240/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 240, "height": 160}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s150x150/e15/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2", "width": 150, "height": 100}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s640x640/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 640, "height": 640}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s480x480/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 480, "height": 480}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s320x320/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 320, "height": 320}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s240x240/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 240, "height": 240}, {"url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-15/s150x150/e15/c180.0.720.720/13696456_1563001390662220_444664459_n.jpg?ig_cache_key=MTI5Njk3ODk2NDI4NzU5NjQ2Mg%3D%3D.2.c", "width": 150, "height": 150}]}, "original_width": 1080, "original_height": 720, "user": {"username": "xxx", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "xxx", "pk": 3195927469, "is_private": true}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImVhZTdhMjNmZGExODRkZDRiM2JiMTUwMTE3ZTA1OTQxMTI5Njk3ODk2NDI4NzU5NjQ2MiIsInNlcnZlcl90b2tlbiI6IjE0Njg4MzI2MzYzODl8MTI5Njk3ODk2NDI4NzU5NjQ2MnwzMTk1OTI3NDY5fDdlYTg5NmIyMDRhZjM3ZGE0NmMyODU0YTA0YmEyZWI1YjQzYzVhN2Y4ZGExNjE1MmE4NTkwYTcwZGM1NjcxNjQifSwic2lnbmF0dXJlIjoiIn0=", "like_count": 0, "likers": [], "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 3, "comments": [], "comment_count": 0, "caption": {"status": "Active", "user_id": 3195927469, "created_at_utc": 1468831963, "created_at": 1468831963, "bit_flags": 0, "user": {"username": "xxx", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "xxx", "pk": 3195927469, "is_private": true}, "content_type": "comment", "text": "Tour de France 2016 - Stage 15 - CULOZ, FRANCE - JULY 17 : PANTANO GOMEZ Jarlinson (COL) Rider of IAM CYCLING and MAJKA Rafal (POL) Rider of TINKOFF in action during stage 15 of the 2016 Tour de France a 160 km stage between Bourg-en-Bresse and Culoz, on July 17, 2016 in Culoz, France , 17/07/2016 ( Photo by Nico Vereecken / Photonews", "media_id": 1296978964287596462, "pk": 17849574181100472, "type": 1}, "caption_is_edited": false, "photo_of_you": false}, "item_id": "27095167853147480935982391906795520", "client_context": "2219f7db-cb98-482c-a171-5920fe20baf0"}], "thread_type": "private", "thread_title": "", "last_seen_at": {"3195927469": {"item_id": "27095167853147480935982391906795520", "timestamp": "1468831992512095"}}, "canonical": true, "inviter": {"username": "xxx", "has_anonymous_profile_picture": true, "profile_pic_url": "http://scontent-bru2-1.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "xxx", "pk": 3195927469, "is_private": true}, "pending": false}]}, "pending_requests_users": []}

REQUEST: news/inbox/?
RESPONSE: {"status": "ok", "new_stories": [], "old_stories": [], "continuation_token": 0, "friend_request_stories": [], "counts": {"relationships": 0, "requests": 0, "photos_of_you": 0}, "subscription": null}

RESPONSE: {"status": "ok", "upload_id": "1468832637156"}

REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=6c51071c2a3045a71efdb707a7407be724002eee19cdd8f397bee1c1ae3315b9.
RESPONSE: {"status": "fail", "message": "Please update your Instagram app to continue posting photos"}

REQUEST: qe/expose/
DATA: ig_sig_key_version=4&signed_body=a0b3be38bfe2ed7f40693f1d956dc3c94bc43906e7c5b90fdb830c2e7dfe7f7d.{"_uuid":"b55b858c-fb24-458f-bd33-79ba17cdc5b4","_uid":3195927469,"id":3195927469,"_csrftoken":"ldDbjZi221CZgqCQsG10CrqSJVV5NGAa","experiment":"ig_android_profile_contextual_feed"}
RESPONSE: {"status": "ok"}

**Comment by mgp25** [comment]
@stdu00 i dont know if you are using my code or what, but the configure request is messed up

**Comment by stdu00** [comment]
this extract is done using your code (download latest version this morning)
Seems the $post is empty

**Comment by stdu00** [comment]
Found : need to encode the array before calling the json_encode
	protected function utf8ize($d) {
	    if (is_array($d)) {
	        foreach ($d as $k => $v) {
	            $d[$k] = $this->utf8ize($v);
	        }
	    } else if (is_string ($d)) {
	        return utf8_encode($d);
	    }
	    return $d;
	}

    protected function configure($upload_id, $photo, $caption = '')
    {
        $size = getimagesize($photo)[0];

        $post = json_encode($this->utf8ize([
        'upload_id'          => $upload_id,
        'camera_model'       => 'HM1S',
        'source_type'        => 3,
        'date_time_original' => date('Y:m:d H:i:s'),
        'camera_make'        => 'XIAOMI',
        'edits'              => [
          'crop_original_size' => [$size, $size],
          'crop_zoom'          => 1.3333334,
          'crop_center'        => [0.0, -0.0],
        ],
        'extra' => [
          'source_width'  => $size,
          'source_height' => $size,
        ],
        'device' => [
          'manufacturer'    => 'Xiaomi',
          'model'           => 'HM 1SW',
          'android_version' => 18,
          'android_release' => '4.3',
        ],
        '_csrftoken'  => $this->token,
        '_uuid'       => $this->uuid,
        '_uid'        => $this->username_id,
        'caption'     => $caption,
     ]));
        $post = str_replace('"crop_center":[0,0]', '"crop_center":[0.0,-0.0]', $post);

        return $this->request('media/configure/', $this->generateSignature($post))[1];
    }

**Comment by mgp25** [comment]
You can make php to have utf8 enabled by default

Regards
