### ISSUE TITLE
Is it possible to fetch the same information as you would see in the Following tab?

### ISSUE THREAD

**Issue by camero2734** [mgp25/Instagram-API#2781]
From what I've been finding, I believe that in the Android apk this is referred to as `newsfeed_following`. In the app itself, it is the following tab where it says `XXX liked/commented on YYY's post`. 

Is it possible to access this? I believe #2138 explains how you can get push notifications for it, but how do I just "view" the feed like in the app?

**Comment by JRoy** [comment]
Yeah, you're looking for `People#getRecentActivityInbox`

https://github.com/mgp25/Instagram-API/blob/d1159725aae5f4f61d1b3a4053dfc57a6c5f85a7/src/Request/People.php#L123-L127
