### ISSUE TITLE
InstagramAPI\Response\FriendshipResponse: Feedback required.

### ISSUE THREAD

**Issue by cassiohuber** [mgp25/Instagram-API#2783]
# Bug Report

---

### Notes:
We will close your issue, sometimes without answering, if any of the following are met:
* You have not included your code or your debug log
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your issue:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar issues including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your issue below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

Yesterday I started getting this warning, doing a search on it I found no article about the problem, what can this be?

### Debug Log
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
[Fri Jul 26 01:35:04.603517 2019] [:error] [pid 19107] [client xxx] PHP Fatal error:  Uncaught LazyJsonMapper\\Exception\\LazyJsonMapperException: Unknown function "getItems". in /var/www/html/app/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php:2156\nStack trace:\n#0 /var/www/html/inc/plugins/auto-like/cron.php(342): LazyJsonMapper\\LazyJsonMapper->__call('getItems', Array)\n#1 /var/www/html/inc/plugins/auto-like/cron.php(223): Plugins\\AutoLike\\_like_from_target(Object(Plugins\\AutoLike\\ScheduleModel), Object(InstagramAPI\\Instagram))\n#2 /var/www/html/app/core/Event.php(40): Plugins\\AutoLike\\addCronTask()\n#3 /var/www/html/app/controllers/CronController.php(16): Event::trigger('cron.add')\n#4 /var/www/html/app/core/App.php(524): CronController->process()\n#5 /var/www/html/index.php(67): App->process()\n#6 {main}\n  thrown in /var/www/html/app/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php on line 2156
```

**Comment by JRoy** [comment]
> You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and countless closed tickets in the past!

Literally in the header of the issue template.

**Comment by mgp25** [comment]
Apart from that, look at the path `var/www/html/inc/plugins/auto-like/cron.php(342)` this is a no no to me.
