### ISSUE TITLE
Does _csrftoken ever expires

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2787]
# Question
 
### Description

I was performing some tests in my system and then i got the classical: 
`{"message": "feedback_required", "comment_error_key": "comment_si_blocked", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_comment/", "feedback_appeal_label": "Report problem", "feedback_ignore_label": "OK", "feedback_action": "report_problem", "status": "fail"} `

I'm used to this so and ignored a while, but 48hours after that, even me not using instgram to anything else i was still getting this error unabling me to do a single comment, follow or like photos. So i found it odd and start doing some research.

at very same time i was getting this error with the api i was fine commeting using instagram app
So i started messing up with the api params to see where i could get (i know people here hate this, but i do on my own risk) and then i noticed that after a full login i was able again to comment without problems (by full login i mean delete  cookies and crsfToken but keep all phoneId guid deviceId stuff)

then i forced the api to use the old  crsfToken  and cookie and the error returned.

I do know instagram is not stupid enough to block spam related behavior by simple locking  the crsfToken because anyone could simple relogin and solve it... so my question is:

Does `crsfToken`  has an expiration date?

@JRoy i know you dont like to answer `feedback_required` questions but if i simpled asked my question without putting the context would be more complicated to understand

**Comment by JRoy** [comment]
Yes csrftokens expire

**Comment by etaxi341** [comment]
@bolds07 how did you solve the problem? Do you make the account relogin every 48 hours? Or how do you solve this? I have the same problem. I am not spamming but after 48 hours spam is true.

**Comment by bolds07** [comment]
I didn't solve the problem so far... although @JRoy  answered the token expires he closed the issue so fast (as always) that nobody could add extra info
when they expires?
how to know if they are expired?

i guess instagram doesn't do a full fresh login  every 48 hours... so this might work,,, but is not the solution i would like tu put in my system since i've 6k daily users
