### ISSUE TITLE
Is there a way to retrieve `accessibility_caption` field from Media like in the Web API?

### ISSUE THREAD

**Issue by fuzzybro** [mgp25/Instagram-API#2788]
Web API (and web version of Instagram) has accessibility_caption field as `alt_text` for most media images. Would be awesome to have the same thing for the MGP25-Instagram library. I presume this could be enabled via different set of `ig_experiments`. Please let me know.

Cheers!

**Comment by JRoy** [comment]
Hello,

I was not able to find `accessibility_caption`, `alt_text`, or anything similar in media responses; nor was I able to find a corresponding experiment. It is likely that accessibility captions are not supported on Android (yet).

Cheers.

**Comment by fuzzybro** [comment]
@JRoy I think one should enable accessibility in Android system settings (like in the iOS). This would set a different set of android-experiments but I'm not entirely sure. Maybe you're right and android version doesn't support that yet.
