### ISSUE TITLE
IG_SIG_KEY for version 8.5.2

### ISSUE THREAD

**Issue by kdekooter** [mgp25/Instagram-API#279]
I noticed the latest version of the app is 8.5.2. I have been studying the wiki, juggling with ADB and APKTools. But extrating the key seems to be beyond me. Has anyone been able to get it?

**Comment by huttarichard** [comment]
@mgp25 @kdekooter who is going to make s pull request? new keys are in 
https://github.com/huttarichard/instagram-private-api -> client/v1/constants.js

**Comment by huttarichard** [comment]
@mgp25 :smile: :smile: :smile:

**Comment by huttarichard** [comment]
so no advertising and no new keys I guess @mgp25
