### ISSUE TITLE
How does Instagram define device_id, phone_id and 

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2792]
### Description
This is a quetions I always had and I've tryed to decompile instagram to get to the bottom of this many times but i'm never got the answer:

How does instagram generate these ids: `uuid`, `phone_id`, `device_id`?

please help me to fill the questions in this scenario 
**Question 1**
let's say I have 1 phone and 2 users  t1 and t2

phone  is used by  t1 with uuid_t1, phone_id_t1 and device_id_t1... then  add a second account to instagram app t2... 

```
is device_id_t1 == device_id_t2?
is phone_id_t1 == phone_id_t2?
```

**Question 2**
 let's say I have 1 phone and 1 user with uuid_t1, phone_id_t1 and device_id_t1... then the user unninstall and reinstall the instagram app. after the second instalation does any of the values remain the original?

```
is is device_id_t1 == new_device_id_t1?
is phone_id_t1 == new_phone_id_t1?
is uuid_t1 == new_uuid_t1?
```

**Comment by JRoy** [comment]
This really isn't something we support or answer on the bug tracker for what I hope are obvious reasons.

**Comment by bolds07** [comment]
@JRoy , it isn't an obvious reason to me... you dont answer because you dont know or because im a free user of the repository?

since this repository intent to mock instagrams behavior would be reasonable disclose this information... note that i'm not asking for the algoritm itself only the politic of generation... and the reason is obvious to me

if one user adds 2 or more accounts to my system i would like it to behave as two accounts in the same phone

as well if the user remove and then add the same account back, i would like it to behave properly... 

if i do use "as is" by api standards will generate new ids ALWAYS and may get to a point where the same user will be the owner of a dozen devices (at instagram servers perspective)  

@mgp25 BTW, this kind of "not willing to help" behavior is the main reason why i dont consider paying a subscription or suporting this repository somehow

i've been following this repository for the past 3 years and i dont use a single line of code from here, since all my projects are java i come here, read, ask,, learn and translate to java its a lot of pain but still this is the best source of knowledge about instagram on the internet.

but this politics of "10 seconds to close an issue"  like an opened issue somehow hurts or "not going to answer because i dont see the point on answering" really keep me away of being more envolved or sponsoring
