### ISSUE TITLE
Solution: Challenge Required (Remote Server)

### ISSUE THREAD

**Issue by hoemon** [mgp25/Instagram-API#2793]
I've been dealing with challenge required errors for my account for the last few days. I was unable to post any content, or, pass that error, as, none of the solutions provided here worked for me. I was basically stuck at the challenge required state, with or without two factor authentication.

Then I realized, it could be an IP issue. However, my server ip is static, so I can't change that.

Here is what I did:

1. Login to instagram (bot) account from your actual mobile device.
2. Make a post - check if it succeeds.
3. As now, the mobile phone IP address is "safe" for instagram (successful login & post) - share your mobile connection (mobile hotspot)
4. on your machine, through the instagram-api php files, run the login php - or make a post. This time as you're doing the login process over the same safe ip, you should have a successfull login attemp and finally you will have your Session file.
5. transfer your session file to your remote server.
6. login using the instagram-api on your remote server. As the session file is there, it should work.

I'm sorry that the post is out of the format for this repo, but, please accept this as a working solution. I struggled with this for many days, and I was about to give up - so maybe this helps to someone who is in my condition.

Good luck!

**Comment by JRoy** [comment]
As stated in the issue template, we don't give support with challenge required errors.

Regards.
