### ISSUE TITLE
Doesn't post a comment

### ISSUE THREAD

**Issue by babuzinga** [mgp25/Instagram-API#2795]
# Description
A few days ago, the code that posts the photo on Instagram and makes a comment (if the description text did not fit) stopped working, uploads the photo, and the cat doesn’t have a comment, began to return an Instagram error "InstagramAPI\Response\CommentResponse: Feedback required." account login is no problem

### Code
```
try {
  $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($media['image']);
  $response = $ig->timeline->uploadPhoto($photo->getFile(), ['caption' => $media['text']]);
  $response = json_decode($response);
  $mediaId = $response->media->id;
  $ig->media->comment($mediaId, $media['comment']);
  $error_message = '';
} catch (Exception $e) {
  $error_message = $e->getMessage();
}
``` 

### Debug Log
```php
[debug.log](https://github.com/mgp25/Instagram-API/files/3456419/debug.log)
```

**Comment by mgp25** [comment]
It is not a bug, it is detected as spam.

Regards
