### ISSUE TITLE
Mgp25 Verification  Code After RESPONSE Closed

### ISSUE THREAD

**Issue by deepaksharma1232** [mgp25/Instagram-API#2796]
Hello! I was running an account about 1 year on this API: {Redacted}
So, yesterday I had login again and I get this response after following challenge URL:

RESPONSE: {"action": "close", "status": "ok"}
So, what this mean?

Thank you!

**Comment by deepaksharma1232** [comment]
Code Is Here 
   $Instagram->changeUser($username,$password);
        $customResponse = $Instagram->request("challenge/".$user_id ."/".$challenge_id."/")->setNeedsAuth(false)->addPost("security_code", $Code)->getDecodedResponse();
    
print_r($customResponse );
RESPONSE: {"action": "close", "status": "ok"}

**Comment by JRoy** [comment]
We don't give support in challenge solving.

Regards.

**Comment by deepaksharma1232** [comment]
Please Let me know What is issue ??
This response are coming every Time All Ig Account 
RESPONSE: {"action": "close", "status": "ok"}

**Comment by deepaksharma1232** [comment]
> We don't give support in challenge solving.
> 
> Regards.

Please Let me know What is issue ??
This response are coming every Time All Ig Account
RESPONSE: {"action": "close", "status": "ok"}
