### ISSUE TITLE
Viewing only unseen threads

### ISSUE THREAD

**Issue by GuilhermeHumberto** [mgp25/Instagram-API#2797]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description

I searched all issues and got no response. The issue that comes closest to my question is #755 but has not been answered.

I would just like to get direct messages that I didn't mark as read.

```$ig->direct->markItemSeen();```

Suppose my service has been stopped for a while, instagram will keep getting messages in direct, so when i activate my service, i would like to get the old unread messages to save in my database, but i didn't find any parameter that tells me whether that thread is read or not.

Can someone help me?

**Comment by webds** [comment]
I think this will help you.
 $ig->direct->getPendingInbox();

**Comment by amirpdlll** [comment]
$ig->direct->getPendingInbox();  is getting just pending messages , is there a way to get unseen messages from inbox ?

**Comment by GuilhermeHumberto** [comment]
> $ig->direct->getPendingInbox(); is getting just pending messages , is there a way to get unseen messages from inbox ?

Exactly

**Comment by webds** [comment]
Okay, so will push not help you? At startup, all messages arrive that you have not seen.

**Comment by amirpdlll** [comment]
> Okay, so will push not help you? At startup, all messages arrive that you have not seen.

Unfortunately I didn't understand what you meant ,

can you please mention the code or a source ?



this is my code now 
`$direct = $ig->direct->getInbox();
$threads = $direct->getInbox()->getThreads();
foreach($threads as $thread) {
    $threadItems = $thread->getItems();
    foreach($threadItems as $threadItem) {
        $threadItem->getText();
    }
}`

I am getting all messages such as unseen or seen so what should I do to see just unseen messages ?

**Comment by amirpdlll** [comment]
> > $ig->direct->getPendingInbox(); is getting just pending messages , is there a way to get unseen messages from inbox ?
> 
> Exactly

Hey

I found it ;)

check read_state to see if it is unseen or seen

**Comment by webds** [comment]
> > > $ig->direct->getPendingInbox(); is getting just pending messages , is there a way to get unseen messages from inbox ?
> > 
> > 
> > Exactly
> 
> Hey
> 
> I found it ;)
> 
> check read_state to see if it is unseen or seen
Example please. 

So in any case, do you need to read all the messages? I think it is a bad idea. I had the idea of receiving messages from PUSH. But, it is not clear how to get the sender ID of the message. My vorpus were closed.

**Comment by amirpdlll** [comment]
If there is a way to get just unseen messages I really want to know that !

is there a method for that?
can you provide a code?

**Comment by JRoy** [comment]
Instagram doesn't just send unseen messages, it sends a number of threads and sorts them client sifr

**Comment by webds** [comment]
Why not receive messages from PUSH?
The only thing I noticed is when to send a message, then delete it then it will come to PUSH all the time.
@amirpdlll   write an example of how you were able to filter.

@JRoy How to get the user id of the one who sent the message to PUSH?

https://github.com/mgp25/Instagram-API/issues/2819

**Comment by amirpdlll** [comment]
this is my code to filter seen and unseen
`$direct = $Instagram->direct->getInbox();
//$direct = $ig->direct->getPendingInbox();
//print_r($direct);
$threads = $direct->getInbox()->getThreads();
foreach($threads as $thread) {
    $threadItems = $thread->getItems();
    $read_state=$thread->getRead_state();
   

    if($read_state==0){
//this message is seen
    }
elseif($read_state==0){
//this message is unseen
}

}
`


I know nothing about PUSH can you please tell me what is and how to use it ?

**Comment by webds** [comment]
Example Instagram-API/examples/pushReceiver.php
[https://github.com/mgp25/Instagram-API/blob/master/examples/pushReceiver.php](url)
PUSH are notifications that come to the phone when the application is closed.
They are also implemented in this library. But JRoy wrote that they require updating, and they don’t have time for this.
Although I checked, they work.
As soon as someone writes, you immediately receive this message.

**Comment by amirpdlll** [comment]
> Example Instagram-API/examples/pushReceiver.php
> [https://github.com/mgp25/Instagram-API/blob/master/examples/pushReceiver.php](url)
> PUSH are notifications that come to the phone when the application is closed.
> They are also implemented in this library. But @JRoy wrote that they require updating, and they don’t have time for this.
> Although I checked, they work.
> As soon as someone writes, you immediately receive this message.


hello , thanks bro , this is a cool feature I hope they work on it ...

I think you were looking for it to get user_id in push so you can get it using thread_id

**Comment by amirpdlll** [comment]
@webds  hello ,
I have faced a problem when i'm using PUSH !

every thing is ok but push can't get pending messages !!!

have you any suggestion to get pending messages using PUSH ?

thanks
