### ISSUE TITLE
Vertical pictures : Uploaded image isn't in an allowed aspect ratio"

### ISSUE THREAD

**Issue by stdu00** [mgp25/Instagram-API#280]
Hi mgp, seems to be a problem with vertical pictures.
Here is the config request.
Any idea ?
Thx
Stdu00

REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=5b898d3be8fa708b5368978ffed00636c3a023e02c04e9d0472d29b186de8f4b.{"upload_id":"1468852591747","camera_model":"HM1S","source_type":3,"date_time_original":"2016:07:18 14:36:33","camera_make":"XIAOMI","edits":{"crop_original_size":[426,426],"crop_zoom":1.3333334,"crop_center":[0,-0]},"extra":{"source_width":426,"source_height":426},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"Q1H95OuC43rXEsGWhxnaWYJnGPrGWW9A","_uuid":"9f68a106-69a2-43ac-a259-7a053d86ace8","_uid":3195927469,"caption":""}
RESPONSE: {"status": "fail", "message": "Uploaded image isn't in an allowed aspect ratio"}

**Comment by mgp25** [comment]
Read the response `Uploaded image isn't in an allowed aspect ratio`, change the ratio
