### ISSUE TITLE
Like don't work

### ISSUE THREAD

**Issue by engnaguib** [mgp25/Instagram-API#2800]
i user the api with laravel
when i use like function it's back with 
Something went wrong: InstagramAPI\Response\GenericResponse: Feedback required. 
also where can i find the log with laravel?

**Comment by JRoy** [comment]
This isn't a laravel support page and we don't support web usage. Additionally if you would have followed the issue template, you would have seen that we don't support "Feedback Required" errors.

Regards.

**Comment by engnaguib** [comment]
it's already working with laravel ,i finished all project just the like action :)
