### ISSUE TITLE
Not a feedback question, something different. 

### ISSUE THREAD

**Issue by bisht-sanjeet** [mgp25/Instagram-API#2810]
# Question

Hello, I have been using this API for many years on my personal account and my other page. 

Now the issue is that in some case it shows feedback error which I know occurs when doing some action too fast or spamming according to Instagram. But what I do is totally valid and legal. Some time back it stopped caption being posted and for the first time I used it for commenting and it started showing feedback error. I will repeat for the first time I used it for commenting and on the first time, it started showing feedback error. Whereas on another account no error was coming. Now the thing is I have searched a lot about this found out on some older posts that when this happens open Instagram in the browser and do the challenge or click on It was me.
I have done this number of time. My account works fine when I do these things with a real app but shows feedback when doing it via API. Sometimes when changing API IP address it shows 'it was me' error whenever I use API. Every time I have to do 'it was me'. 

I know you won't help in this case but if you could can you please help me. I'm not using this to spam anyone or do any illegal work. Just simple things to make my life easy. 

Please help me how to tackle this and how to do it was me on API or do feedback challenge. 

Please help me. 
_Also please don't report this issue as spam. Otherwise, I won't be able to comment in future in this repo._ 

**Thanks a lot for the API even if you are not able to help. :) 
It has saved a lot of time of mine. :) 

Great work team. :)** 

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

__INSERT YOUR DESCRIPTION HERE__

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
INSERT YOUR CODE HERE
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
INSERT YOUR DEBUG LOG HERE
```

**Comment by JRoy** [comment]
Hello,
We don't just say we can't help with feedback errors, it's because we can't help. We don't have any control over Instagram marking your account as feedback required. That being said, you could try our premium subscription which has a more up to date codebase and that might work: See #2655
