### ISSUE TITLE
Why 1080p devices are required?

### ISSUE THREAD

**Issue by Stiveknx** [mgp25/Instagram-API#2811]
# Question

I'm wondering why only devices with 1080p are required in GoodDevices list.

The only reason for it, is get the HD videos?

Well, I have my own device list (on my own fork of the project), I would like to add more devices, but these devices, doesn't have high resolution. 

My main question is:
I'm not interested on how the video quality is going to be, my actions doesn't even relate with video streaming. Is safe for me to remove this requirement in my fork? Besides the low video quality, I'll have more issues ? 

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

__INSERT YOUR DESCRIPTION HERE__

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
INSERT YOUR CODE HERE
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
INSERT YOUR DEBUG LOG HERE
```

**Comment by JRoy** [comment]
Instagram (sometimes) only sends over higher quality images/streams if the phone can handle it, hence the reason for the devices bring 1080p. If you want to remove that, it's up to you and no support will be given for it as it has no been tested.

Cheers.
