### ISSUE TITLE
Just getting 12 Media Items

### ISSUE THREAD

**Issue by phibershinigami** [mgp25/Instagram-API#2812]
#Bug Report
### Description
Trying to pull all photos from any insta account.
I m using this code : 
### Code
Please post your code relevant to the bug in the section below:
```php
$userId = $ig->people->getUserIdForName('galatasaray');
$feed = $ig->timeline->getUserFeed($userId);

$items = $feed->getItems();
echo count($items);
``` 

### Debug Log
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
INSERT YOUR DEBUG LOG HERE
```

### Output
Output : 12.
It must be too much

**Comment by mgp25** [comment]
@phibershinigami https://github.com/mgp25/Instagram-API/wiki

**Comment by phibershinigami** [comment]
> @phibershinigami https://github.com/mgp25/Instagram-API/wiki

Dude i m  a new coder for this hard projects.
Can u explain me? Is my question an issue?
What i need to add my codes for all medias? - not 12 items - .

**Comment by mgp25** [comment]
Listen, if you don't take the time to read the wiki, documentation and examples we provide, we won't bother on explain anything further. No, your question is not an issue, it is something that has been explained several times and you can find enough information for this. If you are new for the project, I recommend you checking the wiki and the examples before opening an issue.

Regards

**Comment by bvanhou** [comment]
I am leaving a note here to clarify if anyone needs this in the future. Even though you are passing in null value you will still need to treat this as pagination. Within the wiki there is a simple example you can follow.

https://github.com/mgp25/Instagram-API/wiki#pagination


```
$maxId = null;
$_media = [];
do {
    $response = $ig->timeline->getSelfUserFeed($maxId);
    $_media = array_merge($_media, $response->getItems());
    $maxId = $response->getNextMaxId();
} while ($maxId !== null);

echo count($_media);
```
