### ISSUE TITLE
Challenge Required { action : close, status : ok }

### ISSUE THREAD

**Issue by jajosheni** [mgp25/Instagram-API#2813]
I am sorry @mgp25 for asking a question about challenge_required again. I read that my question was to be closed immediately if I do ask about challenge_required. I apologize but I have mailed you twice and no answer.

Now the issue is that I am developing a simple API in Java and this issue has helped me a lot : https://github.com/mgp25/Instagram-API/issues/2143#event-1821788429

I make it past the challenge and get a positive message.
Still after I get `{ action : close, status : ok }` I get a message " You have been logged out " the moment I try to make another request.

I want to ask what is that you are doing in this API that doesn't get you logged out.
Any help would be very much appreciated.

And one more time, sorry for going against the rules.

**Comment by JRoy** [comment]
A) You just admitted to violating our license as (unless the code is somewhere else) I don't see the repo on your profile. 
B) We don't support those requests for a reason, just because you acknowledge that we don't support them doesn't mean we'll help you.

Regards

**Comment by jajosheni** [comment]
It is a private repo. And I think the answer mustn't be that hard to give. You could just tell me the next action i need to do after getting the above message and it would be of great help. I am asking for a solution you already know. I dont need no source code.

**Comment by JRoy** [comment]
You're still violating the license by your repository being private.

Issue Locked.
