### ISSUE TITLE
timeline service throw exception

### ISSUE THREAD

**Issue by gurkankesgin** [mgp25/Instagram-API#2817]
`https://github.com/mgp25/Instagram-API/blob/94acd75b8db47d5ada5f86614dc4735d742960fa/src/Request/Timeline.php`

`getTimelineFeed()` method

I use same request param and body but I receive code below. Could someone please help me with this problem?

```
{
    "message": "login_required",
    "error_title": "You've Been Logged Out",
    "error_body": "Please log back in.",
    "logout_reason": 7,
    "status": "fail"
}
```

**Comment by mgp25** [comment]
1) The issue is not following the issue template
2) The response says it all
