### ISSUE TITLE
Add Comment on IGTV posts

### ISSUE THREAD

**Issue by aliforever** [mgp25/Instagram-API#2823]
# Feature Request
---
### Description
Using comment() from media, only works for normal posts, unlike instagram web. 
Also getInfo() from media has the same behavior, only works for normal posts, not IGTVs. 
I'm guessing there are different endpoints for IGTVs.

**Comment by JRoy** [comment]
IGTV uses the same endpoint as Media#comment. You can use that.

Regards.

**Comment by aliforever** [comment]
The problem was that getTimelineFeed didn't return IGTVs, because of the app version. That got me confused. Thanks
