### ISSUE TITLE
Async Feature

### ISSUE THREAD

**Issue by usegitlab** [mgp25/Instagram-API#2825]
Is very cool use lib in async🤤
![FACC764B-8C44-4666-962A-0D14BB2792C1](https://user-images.githubusercontent.com/40073967/63606975-a777e500-c5d1-11e9-9b65-384c8d24755f.jpeg)

**Comment by JRoy** [comment]
PHP has no native (& cross platform) async or promise support. Most requests (especially login ones) are dangerous to run async anyway
