### ISSUE TITLE
get all messages from direct

### ISSUE THREAD

**Issue by amirpdlll** [mgp25/Instagram-API#2826]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description

I have read all related issues  but I didn't find a soloution ,
I want to get all messages from inbox 
I think I should pass last cursor id to inbox , this is my code
```

$direct = $Instagram->direct->getInbox(28898275610028568598146750424809472);
$threads = $direct->getInbox()->getThreads();
```

but when I use this , I got this error

BadRequestException: Invalid request options. 

how should I get all messages ?

**Comment by wowDaiver** [comment]
```
$cursor = null;
do {
    $inbox = $ig->direct->getInbox($cursor);
    $threads = $inbox->getInbox()->getThreads();
    echo count($threads) . PHP_EOL; // 20
    $cursor = $inbox->getInbox()->getOldestCursor();
    echo $cursor . PHP_EOL; // for remember
} while ($inbox->getInbox()->getHasOlder());
```

**Comment by webds** [comment]
Привет @wowDaiver Подскажи, пожалуйста, как Вы получаете новые сообщения, которые приходят в директ, те которые еще не прочитаны?

**Comment by wowDaiver** [comment]
Запоминаю список тредов с последним стампом времени. Если отличается, считаю новые сообщения, которые новее указанного времени
