### ISSUE TITLE
Real-Time on presence is never triggered

### ISSUE THREAD

**Issue by m5ome** [mgp25/Instagram-API#2837]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

```php
<?php

require_once 'vendor/autoload.php';

$ig = new \InstagramAPI\Instagram(true);
$ig->login(
    'username', 'password'
);

$rtc = new \InstagramAPI\Realtime(
    $ig, $loop = \React\EventLoop\Factory::create()
);

$rtc->on('presence', function (\InstagramAPI\Response\Model\UserPresence $presence) {
    $action = $presence->getIsActive() ? 'is now using' : 'just closed';
    printf('[RTC] User %s %s one of Instagram apps%s', $presence->getUserId(), $action, PHP_EOL);
});

$rtc->start();
$loop->run();

```

**Comment by JRoy** [comment]
Likely related to #2287
