### ISSUE TITLE
Composer / namespaces error

### ISSUE THREAD

**Issue by EXECUTOR-brandon** [mgp25/Instagram-API#284]
`PHP Fatal error:  Class 'InstagramAPI\Constants' not found in`

**Comment by EXECUTOR-brandon** [comment]
Ever since update with namespace line 1662 on Instagram.php has error
[19-Jul-2016 12:33:05 UTC] PHP Fatal error:  Class 'InstagramAPI\Constants' not found in

**Comment by mgp25** [comment]
Use `composer update`, and add this to your script project: 

```
include __DIR__.'/Instagram-API/vendor/autoload.php';
```

**Comment by EXECUTOR-brandon** [comment]
That fixed Fatal Error now back to Video Upload error:

.{"upload_id":"1468943009772","camera_model":"HM1S","source_type":3,"date_time_original":"2016:07:19 15:43:33","camera_make":"XIAOMI","edits":{"crop_original_size":[null,null],"crop_zoom":1.3333334,"crop_center":[0.0,-0.0]},"extra":{"source_width":null,"source_height":null},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"MLlV2ZKpeuNSWo8hHnEzoxeB1QbnQ9zL","_uuid":"4063f724-ebd6-46e0-9588-95822fc9a498","_uid":"3258530472","caption":"SUCCESS"} **RESPONSE: {"status": "fail", "message": "Uploaded image isn't in the right format"}** REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=c5b2e1cf00ee2a3562bee5b72e0a06431a72ec7ab48a44b7e25c8c4184db06ac.{"_uuid":"4063f724-ebd6-46e0-9588-95822fc9a498","_uid":"3258530472","id":"3258530472","_csrftoken":"MLlV2ZKpeuNSWo8hHnEzoxeB1QbnQ9zL","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} REQUEST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=b594320dc989f59e3bd96f83b7dcb739583d5431a9a4220afa78ec7cc00a3b8c.{"upload_id":1468943009772,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":265,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"MLlV2ZKpeuNSWo8hHnEzoxeB1QbnQ9zL","_uuid":"4063f724-ebd6-46e0-9588-95822fc9a498","_uid":"3258530472","caption":"SUCCESS"} **RESPONSE: {"status": "fail", "message": "Other media configure error: yEmZkUpAj4"}** REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=c5b2e1cf00ee2a3562bee5b72e0a06431a72ec7ab48a44b7e25c8c4184db06ac.{"_uuid":"4063f724-ebd6-46e0-9588-95822fc9a498","_uid":"3258530472","id":"3258530472","_csrftoken":"MLlV2ZKpeuNSWo8hHnEzoxeB1QbnQ9zL","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"}

**Comment by EXECUTOR-brandon** [comment]
It's an MP4 file video not an image confused???

**Comment by mgp25** [comment]
mp4 its a video format +  that is a diff issue

Regards
