### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by 1vanov** [mgp25/Instagram-API#2842]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description

Hi. I'd like to buy a Premium version of this api. How can I do this?

**Comment by JRoy** [comment]
Thanks for your interest with the Premium API, please send an email to me@mgp25.com regarding your interest.

Cheers

**Comment by 1vanov** [comment]
> Thanks for your interest with the Premium API, please send an email to [me@mgp25.com](mailto:me@mgp25.com) regarding your interest.
> 
> Cheers

Thanks for the answer. I sent an email a few days ago, but have not yet received a response.
