### ISSUE TITLE
Call to undefined method finishChallengeLogin()

### ISSUE THREAD

**Issue by MavenStack** [mgp25/Instagram-API#2844]
After entering challenge code, trying to finish login, i get the below error.

Please help.

Fatal error: Call to undefined method InstagramAPI\Instagram::finishChallengeLogin()

**Comment by JRoy** [comment]
That isn't a function nor do we support challenges.

**Comment by MavenStack** [comment]
Okay, but previous versions of this library had challenge code handling functionalities.

So how do i handle challenges.
