### ISSUE TITLE
How can I get the last 1000 followers of any account?

### ISSUE THREAD

**Issue by mrtplt024** [mgp25/Instagram-API#2846]
# Question

I want to get the last 1000 followers of any account. I did research and tried to pagination but I could not. My code is getting so many followers of account. I just want to last 1000 followers. I did not understand the maxId logic.

* I [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* I [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* I [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* I [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* I [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* I [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description

I want to get the last 1000 followers of any account. I did research and tried to pagination but I could not. My code is getting so many followers of account. I just want to last 1000 followers. I did not understand the maxId logic.

### Code
```php
try {

	$userId = $ig->people->getUserIdForName('natgeo');
	$maxId = null; 
	$lastfollowers = $ig->people->getFollowers($userId,$rankToken,null,$maxId);
	$obj = json_decode($lastfollowers, TRUE);

} catch (\Exception $e){
	echo $e->getMessage();
}

**Comment by JRoy** [comment]
Please view the pagination example

**Comment by mrtplt024** [comment]
> Please view the pagination example

I already read pagination example. I can get all followers but I can not limit the number. Is here any example of my need? Limit the numbers of data.
