### ISSUE TITLE
Video MP4 Image Format Error

### ISSUE THREAD

**Issue by EXECUTOR-brandon** [mgp25/Instagram-API#285]
Tried with multiple MP4 video files, works through the Instagram App can't get to work through this API.

{"upload_id":"1468943009772","camera_model":"HM1S","source_type":3,"date_time_original":"2016:07:19 15:43:33","camera_make":"XIAOMI","edits":{"crop_original_size":[null,null],"crop_zoom":1.3333334,"crop_center":[0.0,-0.0]},"extra":{"source_width":null,"source_height":null},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"MLlV2ZKpeuNSWo8hHnEzoxeB1QbnQ9zL","_uuid":"4063f724-ebd6-46e0-9588-95822fc9a498","_uid":"3258530472","caption":"SUCCESS"} RESPONSE: {"status": "fail", "message": "Uploaded image isn't in the right format"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=c5b2e1cf00ee2a3562bee5b72e0a06431a72ec7ab48a44b7e25c8c4184db06ac.{"_uuid":"4063f724-ebd6-46e0-9588-95822fc9a498","_uid":"3258530472","id":"3258530472","_csrftoken":"MLlV2ZKpeuNSWo8hHnEzoxeB1QbnQ9zL","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} REQUEST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=b594320dc989f59e3bd96f83b7dcb739583d5431a9a4220afa78ec7cc00a3b8c.{"upload_id":1468943009772,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":265,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"MLlV2ZKpeuNSWo8hHnEzoxeB1QbnQ9zL","_uuid":"4063f724-ebd6-46e0-9588-95822fc9a498","_uid":"3258530472","caption":"SUCCESS"} RESPONSE: {"status": "fail", "message": "Other media configure error: yEmZkUpAj4"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=c5b2e1cf00ee2a3562bee5b72e0a06431a72ec7ab48a44b7e25c8c4184db06ac.{"_uuid":"4063f724-ebd6-46e0-9588-95822fc9a498","_uid":"3258530472","id":"3258530472","_csrftoken":"MLlV2ZKpeuNSWo8hHnEzoxeB1QbnQ9zL","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"}

**Comment by mgp25** [comment]
`Uploaded image isn't in the right format`

**Comment by EXECUTOR-brandon** [comment]
Video

**Comment by mgp25** [comment]
@EXECUTOR-brandon im not saying it, Instagram said it, look at the response you have posted:
```json 
RESPONSE: {"status": "fail", "message": "Uploaded image isn't in the right format"} 
```

The video could be corrupted or overpasses the size or the video ratio, maybe the mimytype of the video is wrong. I just checked all those functions and work perfectly. Also make sure to have all dependencies installed and make sure the video file is okay

Regards

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/
