### ISSUE TITLE
How to call examples/x.php endpoints in docker

### ISSUE THREAD

**Issue by tayfunyasar** [mgp25/Instagram-API#2850]
I already ran wrapper in docker container using commands below.

```
docker build -t instagram_api . --no-cache
docker run instagram_api
```

But i dont know how to make a call to example functions.

Can anyone share how to send requests for any action like 
POST "http://localhost:8080/examples/uploadStory.php".
body: {....}

After one single call, i will be learning coding php ^_^

I already checked https://github.com/mgp25/Instagram-API/wiki

**Comment by mgp25** [comment]
```
php script.php
```
