### ISSUE TITLE
No thumbnail for uploaded video

### ISSUE THREAD

**Issue by Kurill** [mgp25/Instagram-API#286]
The problem is that each time you upload a video (of various sizes) is placed in the tape Instagram, but no picture preview. Instead just a black screen, [screenshot](http://de-v.net/img/2016-07-19_19-47-15.png). However, if you press the "PLAY" button, the video plays and all is well.

**Comment by mgp25** [comment]
@Kurill it works, there is a function that creates the preview (thumbnail), maybe it took a black frame, anyway, check it: https://github.com/mgp25/Instagram-API/blob/master/src/Utils/Utils.php#L59

**Comment by mgp25** [comment]
I just tried it and worked perfectly to me, so i dont know. Im changing the code right now and im testing every function, and so far it works pretty good

**Comment by Kurill** [comment]
Can you provide an example video for upload which You have going without problems?

**Comment by mgp25** [comment]
Sure: https://www.google.es/search?q=mp4+test+files&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=ymSOV8WON4ax8wfr14DwDg#q=mp4+test+files&tbm=vid

**Comment by Kurill** [comment]
I'll try [this video](https://archive.org/download/Pbtestfilemp4videotestmp4/video_test.mp4) and get (new for me) error
> Transcode error: Not a single valid video stream
But why..?!

**Comment by mgp25** [comment]
The mp4 sample you have chosen is corrupt, try with other one... double check things first

**Comment by Kurill** [comment]
At this time i'm try [this video](https://archive.org/download/Testvideomp4/testipodandyoutube.mp4) and nothing change with thumbnail - black, black, black =|

**Comment by mgp25** [comment]
change the preview settings, api doesnt do everything, you can customize it if you want

**Comment by molny** [comment]
@mgp25 I found out what the problem is at @Kurill
The problem really is, she reproduces by me and my friends.

If change temp path [on this string](https://github.com/mgp25/Instagram-API/blob/b419308f3874a41782a154417afaefdfbdd30eaa/src/Utils/Utils.php#L65) everything working okay.

There are suspicions that it had something to do with the rights to a. jpg file. But the problem really is and I think it is better to change the location of TEMP folder

**Comment by mgp25** [comment]
@molny send a PR

**Comment by molny** [comment]
@mgp25 PR? What is that mean?

**Comment by mgp25** [comment]
@molny pull request
