### ISSUE TITLE
Auto post to associated FB page (business account)

### ISSUE THREAD

**Issue by bryanbassett** [mgp25/Instagram-API#2862]
Wondering if there is a way to have the post also check the post to Facebook box as well? Or the cross post to story box?

**Comment by mgp25** [comment]
@bryanbassett 

Please read issue template, if not used, it will be considered as invalid. You also need to provide as much information and details as possible.

**Comment by bryanbassett** [comment]
Will do. Don’t see how any more information is necessary but will do.
