### ISSUE TITLE
This field is required

### ISSUE THREAD

**Issue by aslero** [mgp25/Instagram-API#2863]
# Question

Tell me please, where was the mistake?

gives out

```
Undefined index: user_id

var_dump($customResponse);  ===  { ["message"]=> string(23) "This field is required." ["status"]=> string(4) "fail" }
```

My code
```
$debug = false;
        $truncatedDebug = false;
        $user_id = '';
        $challenge_id = '';

        $verification_method = 0; //0 = SMS, 1 = Email

        function readln($prompt) {
            if ( PHP_OS === 'WINNT' ) {
                echo $prompt;

                return trim( (string) stream_get_line( STDIN, 6, "\n" ) );
            }

            return trim(readline("$prompt"));
        }


        Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

        $ig  = new Instagram($debug, $truncatedDebug);

        try{
            $loginResponse = $ig->login($request->login, $request->password);
            $user_id = $ig->account_id;

            if ( $loginResponse !== null && $loginResponse->isTwoFactorRequired() ) {
                return '2FA not supported in this example';
            }

            if ( $loginResponse instanceof LoginResponse || $loginResponse === null ) {
                return "Not a challenge required exception...\n";
            }

            return 'Logged in!';
        }catch (\Exception $e) {
            if ( ! method_exists( $e, 'getResponse' ) ) {
                echo $e->getMessage();
                exit;
            }
            $response = $e->getResponse();
            var_dump($response);

            if ($e instanceof ChallengeRequiredException) {
            sleep(5);

            $customResponse = $ig->request(substr($e->getResponse()->getChallenge()->getApiPath(), 1))->setNeedsAuth(false)->addPost("choice", 0)->getDecodedResponse();
            var_dump($customResponse);
            if (is_array($customResponse)) {
                $user_id = $customResponse['user_id'];
                $challenge_id  = $customResponse['nonce_code'];
            } else {
                //Other stuff.
            }
                try {
                    $code = readln( 'Code that you received via ' . ( $verification_method ? 'email' : 'sms' ) . ':' );
                    $customResponse = $ig->request( "challenge/$user_id/$challenge_id/" )->setNeedsAuth( false )->addPost( 'security_code', $code )->getDecodedResponse();

                    if ( ! is_array( $customResponse ) ) {
                        echo "Weird response from challenge validation...\n";
                        //var_dump( $customResponse );
                        exit;
                    }

                    if ( $customResponse['status'] === 'ok' && (int) $customResponse['logged_in_user']['pk'] === (int) $user_id ) {
                        echo 'Finished, logged in successfully! Run this file again to validate that it works.';
                    } else {
                        echo "Probably finished...\n";
                       //var_dump( $customResponse );
                    }
                } catch ( Exception $ex ) {
                    echo $ex->getMessage();
                }
        } else {
                //Other stuff.
            }
            return 'Something went wrong: '.$e->getMessage()."\n";
        }
```

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

__INSERT YOUR DESCRIPTION HERE__

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
INSERT YOUR CODE HERE
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
INSERT YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Hello @aslero,

As the repository guidelines specifies, we are not giving support to any kind of issues related to checkpoint. You can already find some information about this in the repository.

Best regards.
