### ISSUE TITLE
How to change User-Agent?

### ISSUE THREAD

**Issue by Asteur** [mgp25/Instagram-API#2865]
# Question

Thanks for your work. Could you suggest me how to change user-agent to your own device?

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

I checked the code and it is always using Android. If I want to use iOS, and also log in, as seems this is my device, how can I do it. 

I've tried such experiments:
user-agent =  'Instagram 19.0.0.27.91 (iPhone6,1; iPhone OS 9_3_1; en_US; en; scale=2.00; gamut=normal; 640x1136) AppleWebKit/420+' 
and it seems Instagram believe I am in iOS, but in Android, you have such constants (VERSION_CODE, IG_SIG_KEY, EXPERIMENTS and etc.). Will I find them if I reverse engineer app on my device? or it's something different?

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
INSERT YOUR CODE HERE
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
INSERT YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
No, that is completely wrong and will cause a lot of issues, we can't support that.

Best regards

**Comment by Asteur** [comment]
Thank you for the quick response, but I do not ask you to implement it, I am simply interested in proposals for its implementation on my own. So if you have any notes or ideas, feel free to share.
