### ISSUE TITLE
How do I specify counts for hash tag search posts

### ISSUE THREAD

**Issue by nishantsharmajecrc** [mgp25/Instagram-API#288]
I'm trying to find a way to get multiple posts for a hashtag by using current implementation it only returns first 15 posts. I see there is one option for max_id in the Instagram.PHP, I m just wondering will that be helpful if yes how do I use it ? Any pointers will be appreciated.

**Comment by RageBrahimi** [comment]
Use similar concept as [this](https://github.com/mgp25/Instagram-API/issues/242#issuecomment-229896060).

**Comment by nishantsharmajecrc** [comment]
thanks!
