### ISSUE TITLE
Popular Feeds and Users

### ISSUE THREAD

**Issue by phibershinigami** [mgp25/Instagram-API#2888]
# Question
## Description

I'm trying to get the most followed accounts/ most liked medias in the world, no matter how much I move between the Response and Request folders, I can't find them. Can u help me?

## Main Question
How do I use 'Response / PopularFeedResponse.php'?

**Comment by JRoy** [comment]
The popular feed has been gone for a long time, therefore this Response is just old.

Regards.

**Comment by phibershinigami** [comment]
Hmm .. thank you for your answer. So, is there anything you can guide me about?
