### ISSUE TITLE
sendPhoto challenge required

### ISSUE THREAD

**Issue by tavangar79** [mgp25/Instagram-API#2891]
# Question

challenge required in sendPhoto

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:+ You have not included context about your question
+ You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
+ You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
+ You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
+ You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
+ You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
+ You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
+ You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
+ You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description

hey guys im using latest Api and i do success login to instagram. when i want sendPhoto in direct messages i get error chanllenge requiered this issues happen just in sendPhoto and other api works fine. please help me about this and how to pass challen.
i think i need send this challeng to app and pass it from app.

### Debug Log (Optional)

```php
"message" => "challenge_required"
  "challenge" => array:6 [▼
    "url" => "https://i.instagram.com/challenge/?challenge_node_id=17842698202689740"
    "api_path" => "/challenge/?challenge_node_id=17842698202689740"
    "hide_webview_header" => true
    "lock" => true
    "logout" => false
    "native_flow" => true
  ]
  "status" => "fail"
```

**Comment by mgp25** [comment]
This is fixed in the private subscription. https://github.com/mgp25/Instagram-API/issues/2655

Best regards
