### ISSUE TITLE
New parameter feedPosition

### ISSUE THREAD

**Issue by pavlovskiycode** [mgp25/Instagram-API#2892]
# Question
How to use new required parameter $**feedPosition** in media->like action?

**Comment by AmirHosseinKarimi** [comment]
Hi, Why this question is invalid? I have this problem too, I have searched about this in repository and source but do not found any document about this.
Is there someone help us?

**Comment by usamaejaz** [comment]
There is no hint about this.

**Comment by jmworks** [comment]
I'm also having trouble with what kind of value should I pass as the $feedPosition

**Comment by michelmelo** [comment]
@AmirHosseinKarimi and @usamaejaz  and @jmworks  feedPosition
is the position of the post in the feed. in my case I started to send the position I receive in the items,
ex: 
$ig->like('444_3333',3);

**Comment by AmirHosseinKarimi** [comment]
@michelmelo is this important for Instagram for analyze and detect fake request/clients?
I pass this parameter with this: Response array index * Page number in timeline or explore....
Is okay?

**Comment by michelmelo** [comment]
@AmirHosseinKarimi it should be, but as I do not use the likes much, I send to be the position I receive.
