### ISSUE TITLE
Direct realtime update 

### ISSUE THREAD

**Issue by costapombo1997** [mgp25/Instagram-API#2893]
* ✅[Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* ✅ [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* ✅ [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* ✅ [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* ✅ [Installed the API using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* ✅[Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Is it possible to get my own messages ? The code bellow is supposed to run on my computer and I would like to send from my phone. The event is triggered when i get a message from someone else but I need it to be triggered when I send a message too. 

### Code
```php
        $rtc->on('thread-item-created', function ($threadId, $threadItemId, \InstagramAPI\Response\Model\DirectThreadItem $threadItem) use($ig, $myUserId, $rtc, $loop) {
            echo "msg created";
        });
```

**Comment by JRoy** [comment]
Instagram doesn't send notifications to you when you send a message. Therefore we cannot make that happen.

Regards.

**Comment by costapombo1997** [comment]
> Instagram doesn't send notifications to you when you send a message. Therefore we cannot make that happen.
> 
> Regards.

When I open instagram on my browser it updates in real time
