### ISSUE TITLE
Please provide at least one recepient 

### ISSUE THREAD

**Issue by mahmoudBens** [mgp25/Instagram-API#2895]
# Legacy Issue Template

## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Understand that we will *CLOSE* (without answering) *all* issues related to `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [X ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X ] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X ] Question
- [ ] Other

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
try{
$toSend =['6903555338', '20519095905', '1904229952', '4720613356', '4164651082', '7291652295', '18578377911', '17349848371', '11885997512', '3462908722', '4087096643', '20203874287', '12023235739', '19056876712', '9143383806', '18520549816', '2199241310', '4134151392', '3991100292', '13460278274', '5754436532', '3665518644', '8432017020', '14698144838', '5389985021', '5616804721', '444314724', '8715081901', '5726864505', '8505490728', '3053539606', '10035027899', '15462144755', '2438705609', '3663823716', '3230001353', '2208455104', '8399422368', '3783968714', '7062783921', '11566269069', '9487415735', '8208838489', '5910834068', '4436771257', '6354513916', '1347850618', '3611490738', '11425521185', '10639980542', '2203198688', '11907111785', '12001736128', '7917549583', '3099649923', '6004934312', '1951899544', '10476177130', '7005877455', '7973390943', '1979540511', '3513608280', '10487772130', '10609904079', '3866947283', '2885738408', '9721053969', '8427983052', '8309685230', '10196753128', '2237597618', '1609066534', '5788490955', '10107673735', '2221283562', '6992726151', '9551313034', '1711164463', '4924825102', '9211477455', '3682581382', '1904747904', '8475491108', '8302935252', '8502580339', '8169643567', '3119074950', '8224325143', '4244633494', '5342396797', '8542469431', '7750979983', '7864926739', '8760407175', '7009068275', '9194563921', '9055092855', '5809381238', '8582984185', '8368231713', '9023798129', '8611861904', '4399481503', '9049998333', '629959750', '8717540672', '421961137', '9170977612', '9012029030', '5480167286', '8631967912', '8261110944', '8901919220', '8912061640', '9049853872', '3927013882', '7107837402', '8667549770', '8654044016', '8525135062', '8619581778', '8521828510', '9126617119', '8314974297', '8974668385', '7903560086', '6589705711', '8362739637', '6257812282', '8697378875', '8562193788', '8108287631', '1596973963', '8932093283', '8555875370', '8579359537', '8563194229', '8645149733', '8442397105', '8649028610', '8750561323', '1912232803', '8005710929', '8372424623', '9034237269', '2168854790', '2881952093', '6982326143', '6763718133', '8426322499', '8023232424', '8615921643', '8613218047', '2041484961', '8561263197', '4270655556', '6067243941', '4244990304', '7329405471', '8518385843', '3738205885', '3714020756', '8501168154', '8063889470', '8439682936', '5842248206', '1707972120', '4315444583', '8296864150', '8391888761', '7183648445', '6942624088', '8229341965', '1438880719', '6120561541', '8351633667', '8102423246', '8428353303', '6093219891', '8429011673', '5180852437', '8425797767', '7905132729', '7218721581', '2987531862', '8402778390', '8414581852', '3094303438', '4681483940', '3576553673', '8360228603', '7620904457', '8308784356', '7703394665', '8265420606', '8155659071', '8022657982', '5387220353', '4768298009', '8026069252', '7838224262', '7997944978', '4263528898', '7164504150', '5876156985', '6219656027', '5787709027', '3683573946', '7846520725', '7277382501', '3811579254', '7370062538', '6637257276', '7110384333', '6723857703', '1553103830', '5787892510', '6657306140', '1454384699', '7446259816', '1917169356', '7320125985', '5769804049', '1416061164', '5575364295', '4722357794', '6625019000', '7158549372', '6074350923', '3237158274', '7139893915', '3428691829', '6839187164', '7010983922', '3080598982', '6965763703', '5904586260', '3135271377', '5720276440', '5815634136', '6910854258', '6867835464', '6836136664', '4950907455', '3666411934', '6278109542', '3280349736', '6094423461', '1909808472', '642770470', '6710281752', '3551077565', '1728172116', '6301284252', '6194986745', '5852517242', '5676934465', '5860878707', '3069058977', '6199011056', '6269420963', '1579029806', '5480377248', '4294792665', '1554560933', '5463644575', '5717328369', '4714658418', '5732977114', '3542921619', '3506125722', '5715904627', '3089084667', '5717220405', '5717666415', '3027419027', '4465916365', '2321541600', '3025911082', '5681363122', '5661725695', '5636905018', '5628257361', '4589323469', '5550728528', '5548176216', '5545712576', '4930295423', '3517774083', '5483545398', '3264090006', '5384549562', '4726784404', '3791279376', '3679493291', '3749044448', '2368403664', '5318639742', '4946206382', '5056914449', '4473194737', '4204199921', '4859025374', '2252169289', '4246965901', '3644777569', '2149476365', '4872294141', '4848060543', '1220381054', '4836333849', '4828278051', '3422985154', '3573647991', '2727321665', '3868992585', '3409546986', '3045047722', '2063792612', '2222971681', '4196060662', '3936885996', '2304758037', '2893525632', '3531256866', '3561463644', '3548341475', '3969988237', '2377782564', '2308448800', '3410203678', '3299271628', '4198305507', '3090653869', '3572508299', '3066431461', '3433330953', '3883328462', '1424638255', '3264270232', '2959325904', '4515044002', '4764080436', '3503199884', '2368283846', '3168940749', '3284300477', '4174312258', '4457717540', '4361754995', '4126420662', '3860950558', '4600654496', '1324631167', '3302916675', '4299311081', '3156966120', '2931486543', '1759226640', '4142304740', '3485782360', '4218732644', '1905803610', '3939138042', '4685314920', '3306306254', '2220037096', '4350838266', '2213477219', '1816908479', '2066739642', '3413454456', '2256719707', '3209900733', '4488012907', '4094131960', '3074459821', '3461709508', '4130557709', '3489453310', '2316737591', '2219341402', '3999103292', '4583617866', '1903375534', '2349031270', '1987429850', '3979639883', '3112008190', '4652343294', '3615368391', '1121511553', '3542073904', '1376564364', '3040892527', '1649849356', '3530938870', '2374526240', '2189509683', '3480149680', '1955006705', '1500250564', '1330274330', '3283348625', '4035323019', '3606942510', '4646810332', '1816755842', '3312071841', '3561383256', '1958239147', '4070069022', '2990802597', '1359031738', '1622922909', '2351541837'];
	// $option = array();
	$recepeint = array($toSend)	;
  $res=$ig->direct->sendText($recepeint,$msg);
  } catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}

Error : 
POST: https://i.instagram.com/api/v1/feed/timeline/ DATA: �  ← 200 18.31kB RESPONSE: {"num_results": 9, "more_available": true, "auto_load_more_enabled": true, "feed_items": [{"media_or_ad": {"taken_at": 1569344624, "pk": 2140140282167178291, "id": "2140140282167178291_321320796", "device_timestamp": 1569344571124837, "media_type": 1, "code": "B2zTj9oFDQz", "client_cache_key": "MjE0MDE0MDI4MjE2NzE3ODI5MQ==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 959, "height": 1199, "url": "https://scontent-mrs2-1.cdninstagram.com/v/t51.2885-15/e35/70773817_755389614889643_4170859938100306017_n.jpg?_nc_ht=scontent-mrs2-1.cdninstagram.com\u0026_nc_cat=1\u0026se=8\u0026oh=4dba62a164d1276a752e24f009166616\u0026oe=5E1E41C5\u0026ig_cache_key=MjE0MDE0MDI4MjE2NzE3ODI5MQ%3D%3D.2", "estimated_scans_sizes": [16669, 33339, 50009, 66679, 83348, 93267, 118686, 134892, 150028]}, {"width": 480, "height": 600, "url": "https://scontent-mrs2-1.cdninstagram.com/v/t51.2885-15/e35/p480x480/70773817_755389614889643_4170859938100306017_n.jpg?_nc_ht=scontent-mrs2-1.cdninstagram.com\... Something went wrong: Please provide at least one recipient.

Note : I read one comment in the same case , but i didn't get it .
I'm new on php i'm just learning that language, i've a problem with Thread of numerical ID for users 
in the documentation is written that users must be an array like i've done. I dunno why execution is showing please provide at least one receipent

**Comment by JRoy** [comment]
Considering you're not using the latest version, and that you appear to be using it for spam; Support will not be given.
