### ISSUE TITLE
Error on switching personal account to business account

### ISSUE THREAD

**Issue by lolamv** [mgp25/Instagram-API#2897]
I tried to switch personal account to business account

```
$respFirst = $ig->account->switchToBusinessProfile();
if ($respFirst->getStatus() == 'ok') {
    $resp = $ig->account->setBusinessInfo(
        $phone,
        $email,
        $categoryID
    );
    if ($resp->getStatus() == 'ok') {
          .....
    }
}
```

---
function $ig->account->setBusinessInfo() gets error

>
name | Exception
message | No response from server. Either a connection or configuration error.
code | 0
type | InstagramAPI\Exception\EmptyResponseException
file | /home/jango/projects/instmania/vendor/mgp25/instagram-php/src/Client.php
line | 493

**Comment by JRoy** [comment]
This is no longer supported on the public version of the API, please view issue #2655 to learn more on how to join the private code subscription.

Cheers.
