### ISSUE TITLE
How can I get user's media without logging in

### ISSUE THREAD

**Issue by developerfromjokela** [mgp25/Instagram-API#2899]
Hello,

I successfully got user details without logging in via userLookup.

How can I get that user's posts? I can't find any requests for it.

**Comment by JRoy** [comment]
You don't.

**Comment by developerfromjokela** [comment]
But why? This is possible, even found request for it in inspector.

**Comment by developerfromjokela** [comment]
There is an JSON request to server, which then returns media.
