### ISSUE TITLE
Upload photo but not working URL

### ISSUE THREAD

**Issue by sominus** [mgp25/Instagram-API#290]
I have response

["status"]=>
  string(2) "ok"
  ["media"]=>
  array(21) {
    ["taken_at"]=>
    int(1468994352)
    ["pk"]=>
    int(1298341189031915705)
    ["id"]=>
    string(30) "1298341189031915705_3559486486"
    ["device_timestamp"]=>
    int(1468994413754)
    ["media_type"]=>
    int(1)
    ["code"]=>
    string(11) "BIEom65gXC5"
    ["client_cache_key"]=>
    string(30) "MTI5ODM0MTE4OTAzMTkxNTcwNQ==.2"
    ["filter_type"]=>
    int(0)
    ["image_versions2"]=>
    array(1) {
      ["candidates"]=>
      array(15) {
        [0]=>
        array(3) {
          ["url"]=>
          string(150) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/e35/13743360_272484926450768_1271547035_n.jpg?se=7&ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2"
          ["width"]=>
          int(4608)
          ["height"]=>
          int(3456)
        }
        [1]=>
        array(3) {
          ["url"]=>
          string(156) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s1080x1080/e35/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2"
          ["width"]=>
          int(1080)
          ["height"]=>
          int(810)
        }
        [2]=>
        array(3) {
          ["url"]=>
          string(161) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2"
          ["width"]=>
          int(750)
          ["height"]=>
          int(562)
        }
        [3]=>
        array(3) {
          ["url"]=>
          string(161) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2"
          ["width"]=>
          int(640)
          ["height"]=>
          int(480)
        }
        [4]=>
        array(3) {
          ["url"]=>
          string(154) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s480x480/e35/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2"
          ["width"]=>
          int(480)
          ["height"]=>
          int(360)
        }
        [5]=>
        array(3) {
          ["url"]=>
          string(154) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s320x320/e35/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2"
          ["width"]=>
          int(320)
          ["height"]=>
          int(240)
        }
        [6]=>
        array(3) {
          ["url"]=>
          string(154) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s240x240/e35/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2"
          ["width"]=>
          int(240)
          ["height"]=>
          int(180)
        }
        [7]=>
        array(3) {
          ["url"]=>
          string(154) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s150x150/e35/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2"
          ["width"]=>
          int(150)
          ["height"]=>
          int(112)
        }
        [8]=>
        array(3) {
          ["url"]=>
          string(175) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s1080x1080/e35/c576.0.3456.3456/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2.c"
          ["width"]=>
          int(1080)
          ["height"]=>
          int(1080)
        }
        [9]=>
        array(3) {
          ["url"]=>
          string(180) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/c576.0.3456.3456/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2.c"
          ["width"]=>
          int(750)
          ["height"]=>
          int(750)
        }
        [10]=>
        array(3) {
          ["url"]=>
          string(180) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c576.0.3456.3456/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2.c"
          ["width"]=>
          int(640)
          ["height"]=>
          int(640)
        }
        [11]=>
        array(3) {
          ["url"]=>
          string(173) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s480x480/e35/c576.0.3456.3456/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2.c"
          ["width"]=>
          int(480)
          ["height"]=>
          int(480)
        }
        [12]=>
        array(3) {
          ["url"]=>
          string(173) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s320x320/e35/c576.0.3456.3456/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2.c"
          ["width"]=>
          int(320)
          ["height"]=>
          int(320)
        }
        [13]=>
        array(3) {
          ["url"]=>
          string(173) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s240x240/e35/c576.0.3456.3456/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2.c"
          ["width"]=>
          int(240)
          ["height"]=>
          int(240)
        }
        [14]=>
        array(3) {
          ["url"]=>
          string(173) "http://scontent-arn2-1.cdninstagram.com/t51.2885-15/s150x150/e35/c576.0.3456.3456/13743360_272484926450768_1271547035_n.jpg?ig_cache_key=MTI5ODM0MTE4OTAzMTkxNTcwNQ%3D%3D.2.c"
          ["width"]=>
          int(150)
          ["height"]=>
          int(150)
        }
      }
    }
    ["original_width"]=>
    int(4608)
    ["original_height"]=>
    int(3456)
    ["user"]=>
    array(8) {
      ["username"]=>
      string(12) "sominus_demo"
      ["has_anonymous_profile_picture"]=>
      bool(false)
      ["is_unpublished"]=>
      bool(false)
      ["profile_pic_url"]=>
      string(93) "http://scontent-arn2-1.cdninstagram.com/t51.2885-19/13745095_681955275295263_1044968308_a.jpg"
      ["profile_pic_id"]=>
      string(30) "1297627253185770913_3559486486"
      ["full_name"]=>
      string(7) "Sominus"
      ["pk"]=>
      int(3559486486)
      ["is_private"]=>
      bool(false)
    }
    ["organic_tracking_token"]=>
    string(344) "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImRlMjRjMDg1Nzc3OTRmMzdiMTFjODNhNGY5OGMxMzU3MTI5ODM0MTE4OTAzMTkxNTcwNSIsInNlcnZlcl90b2tlbiI6IjE0Njg5OTQzNTQ3NDF8MTI5ODM0MTE4OTAzMTkxNTcwNXwzNTU5NDg2NDg2fDZmZWQ1YjMzYzAzY2M4NGQyOGE4NjIxNmVlYmM2NjdlMWUyOGZmMzNjYjNkNThmNGJlZjhhODU0NTRjOGVhYjQifSwic2lnbmF0dXJlIjoiIn0="
    ["has_liked"]=>
    bool(false)
    ["has_more_comments"]=>
    bool(false)
    ["max_num_visible_preview_comments"]=>
    int(4)
    ["comments"]=>
    array(0) {
    }
    ["comment_count"]=>
    int(0)
    ["caption"]=>
    array(11) {
      ["status"]=>
      string(6) "Active"
      ["user_id"]=>
      int(3559486486)
      ["created_at_utc"]=>
      int(1468994354)
      ["created_at"]=>
      int(1468994354)
      ["bit_flags"]=>
      int(0)
      ["user"]=>
      array(8) {
        ["username"]=>
        string(12) "sominus_demo"
        ["has_anonymous_profile_picture"]=>
        bool(false)
        ["is_unpublished"]=>
        bool(false)
        ["profile_pic_url"]=>
        string(93) "http://scontent-arn2-1.cdninstagram.com/t51.2885-19/13745095_681955275295263_1044968308_a.jpg"
        ["profile_pic_id"]=>
        string(30) "1297627253185770913_3559486486"
        ["full_name"]=>
        string(7) "Sominus"
        ["pk"]=>
        int(3559486486)
        ["is_private"]=>
        bool(false)
      }
      ["content_type"]=>
      string(7) "comment"
      ["text"]=>
      string(63) "Netureal beauty
http://instagram.sominus.net/?p=202
sun is up"
      ["media_id"]=>
      int(1298341189031915705)
      ["pk"]=>
      int(17859002656036426)
      ["type"]=>
      int(1)
    }
    ["caption_is_edited"]=>
    bool(false)
    ["photo_of_you"]=>
    bool(false)
  }
  ["upload_id"]=>
  string(13) "1468994413754"
}

and URL https://www.instagram.com/p/BIEom65gXC5/ but url not workig, why?

**Comment by RageBrahimi** [comment]
Well, this suggest the script is obviously working, but your account is probably flagged up as spam. I'd suggest waiting a few hours (probably 24 hours) before you post again.
