### ISSUE TITLE
[Feature Request] Muted Reels

### ISSUE THREAD

**Issue by ckrl** [mgp25/Instagram-API#2900]
# Question

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

There is an endpoint "friendships/muted_reels" that shows list of friends with muted stories.
I found it just similar to "friendships/blocked_reels/"
Is there are an endpoint to get friends with muted posts?

Thanks.

**Comment by ckrl** [comment]
And muted posts, pls, if possible.

**Comment by JRoy** [comment]
Completed in the private API
