### ISSUE TITLE
getNextMaxId limit 200 results

### ISSUE THREAD

**Issue by alviseelvis87** [mgp25/Instagram-API#2906]
Dear,
sorry for disturb, i'm new and i'm sorry if i wrong something.
I 'm doing this piece of script:

$data[$key]['max_id'] = $followers->getNextMaxId();

                        $followers_ids = null;
                        unset($followers_ids);
                        $followers_ids = [];
                        foreach ($followers->getUsers() as $follower) {
                            $followers_ids[] = $follower->getPk();
                        }

So my problem is that the results give me all time only 200 users.
How can i fix it for get more results?
Thank you in advance.

Best regards.

**Comment by mgp25** [comment]
Hello,

You are not using the issue template, next time the issue will be closed directly. This has been answered multiple times and it is a normal behavior, you can check this within the device. In case you don't know how to paginate, please have a look at the examples and the wiki.

Regards
