### ISSUE TITLE
is Api crashed?

### ISSUE THREAD

**Issue by phibershinigami** [mgp25/Instagram-API#2908]
# Question
is Api crashed? I know what this error means, but even if I never use it for half an hour, it makes it even in the smallest request.
### Exception
Uncaught InstagramAPI\Exception\ThrottledException: Throttled by Instagram because of too many API requests.

**Comment by mgp25** [comment]
Duplicate: https://github.com/mgp25/Instagram-API/search?q=ThrottledException&type=Issues
