### ISSUE TITLE
Registration is not working

### ISSUE THREAD

**Issue by bidlocode** [mgp25/Instagram-API#291]
It seems like post-request is lacking proper **'waterfall_id', 'qs_stamp'** parameters. 
Answer is always the same 
``{"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_action": "report_problem", "feedback_url": "repute/report_problem/instagram_signup/", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Report problem"}``

**Comment by mgp25** [comment]
It doesnt require those params, i just tried and it works, maybe you are using it too often

Reards

**Comment by Dev-Aryan** [comment]
> {"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", **"spam": true,** "feedback_action": "report_problem", "feedback_url": "repute/report_problem/instagram_signup/", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Report problem"}


Probably you are spamming their server.
Please try again in sometime
