### ISSUE TITLE
Remove final Request/Metadata/Internal class

### ISSUE THREAD

**Issue by aliazizi** [mgp25/Instagram-API#2913]
# Feature Request

---

### Notes:
We will close your feature request, sometimes without answering, if any of the following are met:
* You requested a endpoint/function for `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block` errors. These are decidedly unsupported, and will not be added
* You requested a endpoint/function for an iOS feature. This API emulates the Android API, therefore we cannot, *safely*, add endpoints/functions which are not in the Android app.
* You are using the wrong issue template

Please make sure you have done the following before submitting your feature request:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for the same feature request
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)

---

### Description
Please include a well-worded description of your feature request. Please make sure to include where on the app this feature is acceptable so we can reproduce it. Additionally, it would make our lives easier if you are able to post the endpoint, its associated parameters, and response.

I extends core class and make few changes to create thumbnail without ffmpeg ( i cant install it ), But there is a problem with `Metadata/Internal` class, It's final and I cant extends this class,

Is there any chance to change this class to no final?

**Comment by mgp25** [comment]
Issue doesn't follow a valid format. Therefore is considered as invalid.

Regards

**Comment by aliazizi** [comment]
@mgp25 This is a question not an issue, Can you at least answer it ?

**Comment by mgp25** [comment]
@aliazizi you haven't filled or written anything in the issue template. Issue template can be a error/issue report, request, bug report or whatever, but if you don't fill the template I won't check it, because it is useless and won't help anyone if there is no details about it at all. You need to explain what happens, why your request, what it fixes and so on.

Please, have a look at the template and feel free to open a new issue with all the details we ask for

Best regards

**Comment by aliazizi** [comment]
@mgp25 I think you dont see my text, I add my question in template I add my content in `__INSERT DESCRIPTION HERE__` section. Here it is.

> I extends core class and make few changes to create thumbnail without ffmpeg ( i cant install it ), But there is a problem with Metadata/Internal class, It's final and I cant extends this class,
> 
> Is there any chance to change this class to no final?

**Comment by mgp25** [comment]
You are totally right, my fault. However, can you provide more details?

**Comment by aliazizi** [comment]
Thanks,
I cant install ffmpeg, So I change few line to get thumbnail from image in disk ( not create it from video ) 
I'm successfully do that but there is a problem with `Request\Metadata\Internal` I cant extends ( I can create whole new class but it's not likely ) 

The problem is that in this class I want to override `setVideoDetails` method to create an instance from my own `VideoDetail` class ( to get duration ratio and ... from input not from ffmpeg )

Is there a change to remove `final` keyword from this class?

**Comment by aliazizi** [comment]
Here is the line I'm talking about
https://github.com/mgp25/Instagram-API/blob/eb00ad82979dc454d60439972262d76c52f4e720/src/Request/Metadata/Internal.php#L15

**Comment by JRoy** [comment]
This is something that can be done, @mgp25, do you think this would have any side effects?

**Comment by JRoy** [comment]
Fixed in 9e3bcdcf7dc8796d72af0852bdc952c38e7ba9b4

**Comment by aliazizi** [comment]
Thank you
