### ISSUE TITLE
[Feature Request] Remove Story Question Answer

### ISSUE THREAD

**Issue by jordanmiguel** [mgp25/Instagram-API#2927]
# Feature Request

---

### Notes:
We will close your feature request, sometimes without answering, if any of the following are met:
* You requested a endpoint/function for `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block` errors. These are decidedly unsupported, and will not be added
* You requested a endpoint/function for an iOS feature. This API emulates the Android API, therefore we cannot, *safely*, add endpoints/functions which are not in the Android app.
* You are using the wrong issue template

Please make sure you have done the following before submitting your feature request:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for the same feature request
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)

---

### Description

Guys, is there a way to remove an Story Question answer AND/OR answer the story question answer? Can you provide an endpoint or some way to do it? On the phone, you can go to the Story Question answers, click on the question, click Remove Answer and confirm it.

**Comment by JRoy** [comment]
Completed in the private code subscription!

Please see #2655 for information on how to subscribe to the private code subscription!

Regards.

**Comment by jordanmiguel** [comment]
Sure! 100eur/m is 500 BRL which is half of our minimum wage salary, not that your work is not awesome, but the pricing is absurd.
