### ISSUE TITLE
Uploading Image: "Other media configure error: Wiz9ibexcf"

### ISSUE THREAD

**Issue by fagenorn** [mgp25/Instagram-API#293]
Keep getting error: {"status":"fail","message":"Other media configure error: Wiz9ibexcf"} 
when upload image.

Request:

`POST /api/v1/upload/photo/ HTTP/1.1
Accept-Language: en-US
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=8d3b1f79772e690
Accept: */*
User-Agent: Instagram 8.5.1 Android (23/6.0.1; 120dpi; 1280x720; Samsung; trhplte; SM-N910U; bacon; en_US)
Host: i.instagram.com
Cookie: REDACTED
Content-Length: 5368
Expect: 100-continue

--8d3b1f79772e690
Content-Disposition: form-data; name="upload_id"

8d3b1f79772e690
--8d3b1f79772e690
Content-Disposition: form-data; name="_uuid"

baed792d-db4f-4975-be50-ec7b803b7dc5
--8d3b1f79772e690
Content-Disposition: form-data; name="_csrftoken"

benDY6Wp0iyJFW2BnzllEkZdnBtdMc1s
--8d3b1f79772e690
Content-Disposition: form-data; name="image_compression"

{"lib_name":"jt","lib_version":"1.3.0","quality":"70"}
--8d3b1f79772e690
Content-Disposition: form-data; name="photo"; filename="pending_media_8146842.jpg"
Content-Transfer-Encoding: binary
Content-type: application/octet-stream

����
--8d3b1f79772e690--
`

Response:
`
{
	"status": "ok",
	"upload_id": "8d3b1f79772e690"
}
`

Request:

`
signed_body=10c74e09146f83c6a40fd03f3592a889b7b0a30e8ec12d013b46ba73503bbd53.{"upload_id":"8d3b1f79772e690","media_folder":null,"date_time_digitalized":null,"camera_model":"SM-N910U","source_type":"3","date_time_original":"2016-07-22 06:15:38","camera_make":"Samsung","edits":{"crop_original_size":[138,138],"crop_zoom":1.3333334,"crop_center":[0.0,-0.0]},"extra":{"source_width":138,"source_height":138},"device":{"manufacturer":"Samsung","model":"SM-N910U","android_version":23,"android_release":"6.0.1"},"_csrftoken":"REDACTED","_uuid":"baed792d-db4f-4975-be50-ec7b803b7dc5","_uid":"3562151576","caption":":)"}&ig_sig_key_version=4
`

Response:

`
{
	"status": "fail",
	"message": "Other media configure error: Wiz9ibexcf"
}
`

Have been trying to solve this issue for a few days, hope someone can help me out.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/issues/286#issuecomment-234264177

Regards

**Comment by tahelromero** [comment]
The error it´s the codification of the message

**Comment by andrewostroumov** [comment]
You need to remove metadata from image. For example by ImageMagick strip option. https://www.imagemagick.org/script/command-line-options.php#strip
