### ISSUE TITLE
Uncaught InstagramAPI\Exception\ConsentRequiredException: on line 190

### ISSUE THREAD

**Issue by elvin111-php** [mgp25/Instagram-API#2931]
Hello my api don't work.
My index.php 
![изображение](https://user-images.githubusercontent.com/54534688/66713507-dbdf7480-edbc-11e9-9e9c-99788030e399.png)

My problem
![изображение](https://user-images.githubusercontent.com/54534688/66713520-ed288100-edbc-11e9-9b02-490f71a051bf.png)

Where is the mistake?

**Comment by elvin111-php** [comment]
please help me

**Comment by JRoy** [comment]
Don't use this api on the web
