### ISSUE TITLE
Media not found or unavailable for Media Requests

### ISSUE THREAD

**Issue by UXandre** [mgp25/Instagram-API#2933]
# Question

Description
I am trying to send requests to get the basic info of a piece of media but keep failing it. The media id is gained through the official Instagram Graph API so I suppose is correct.

### Code that I'm using to request

```php
$ig->media->getInfo($mediaId);
```

### Debug Log
```php
GET: https://i.instagram.com/api/v1/media/18001724395052205/info/ → 0B ← 400 63B RESPONSE: {"message": "Media not found or unavailable", "status": "fail"} Something went wrong: InstagramAPI\Response\MediaInfoResponse: Media not found or unavailable.
```

Would appreciate it if anyone can help. I would also really appreciate if the admin could allow the question stays open for a bit longer than it usually does before closing it. Completely understand you admins are great and busy dealing with a lots of questions. I have to aks questions as my deadline of project is approaching and I've done the reading of your docs/wiki. Just can't find the answers. Thank you again.

**Comment by mgp25** [comment]
Hello @UXandre,

Can you provide more info about the media? Also, `media_id` is not in the correct format it should be: `mediaId_userId`.

Regards

**Comment by UXandre** [comment]
Hi @mgp25,

Sure! Thanks so much for getting back to me! And yes for sure. The media is [a piece of content on my own feed](https://www.instagram.com/p/BqfMyTEFuzY/).

My initial intent was to post comments on other people's comment with the function:
```php
$ig->media->comment()
```

But had an error with the log like this.
```
"comment_error_key": "comment_media_does_not_exist"
```

So I thought it would be because of the media ID. In order to test if it's the media ID's issue, I tried the basic method
```php 
$ig->media->getInfo($mediaId);
```

I appended my Instagram UID to the media id returned by the official Instagram Graph API like this 
```
18001724395052205_595150521
```

But still get the same log as below

```php
GET: https://i.instagram.com/api/v1/media/18001724395052205_595150521/info/ → 0B ← 400 63B RESPONSE: {"message": "Media not found or unavailable", "status": "fail"} Something went wrong: InstagramAPI\Response\MediaInfoResponse: Media not found or unavailable.
```

I'm on Laravel. After reading your other response, I understand that the package isn't built for website use and needed the code below to be added to the construct function in the controller, which I've done too.

```php
Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
```

Would it because the way I got the mediaId was wrong in the first place? 

Thanks so much again!

**Comment by mgp25** [comment]
Hello @UXandre,

I am not sure how you obtained your media ID, but it is definitely wrong. Looking at the response of:

```php
$mediaId = '595150521':
$ig->timeline->getUserFeed($mediaId);
```

The media you are looking for is the 7th element from the Items array, and it has the following media ID: `1918308199284796632_595150521` and this works perfectly.

You can even convert the short code (obtained from the media URL) to the media ID:

```php
// From Shortcode to Media ID.
$code = 'BqfMyTEFuzY';
$id = InstagramID::fromCode($code);
echo "Instagram code({$code}) -> id({$id})\n\n";
```

```
Instagram code(BqfMyTEFuzY) -> id(1918308199284796632)
```

Please make sure to use correct methods and read documentation and examples where most of the things are explained.

Best regards

**Comment by UXandre** [comment]
@mgp25 THANKS SO MUCH FOR THIS. With your help I managed to get the right Media ID and the info. Just tried the comment method and it works like a charm, too.

Just in case somebody stumbles upon the thread and have some issues as I had:

1) If you are mixing the use of official Facebook/Instagram Graph API, be careful not using the media ID you got from the official API. Get the media id just as above suggested by @mgp25.

2) Just tried the media id gained from the shortcode conversion as suggested above.

```php
// From Shortcode to Media ID.
$code = 'BqfMyTEFuzY';
$id = InstagramID::fromCode($code);
echo "Instagram code({$code}) -> id({$id})\n\n";
```

Even without appending the user_id, the media id works for posting comments, too.

Happy coding and a BIG THANK YOU to @mgp25 again. You are my hero.
