### ISSUE TITLE
create story with "@user"

### ISSUE THREAD

**Issue by werzila** [mgp25/Instagram-API#2935]
Hi @mgp25. How do i create story with "@user", and set position and color? 
Thank)

**Comment by Juan-de-Costa-Rica** [comment]
There are external metadata parameters listed in the comments of `configureSinglePhoto()` method. I'm not sure you can set usertags on a story photo, but this info may help you!


https://github.com/mgp25/Instagram-API/blob/502a89aceed92595514d5c381e36176985abb977/src/Request/Internal.php#L206-L208

https://github.com/mgp25/Instagram-API/blob/502a89aceed92595514d5c381e36176985abb977/src/Request/Internal.php#L217-L218

**Comment by mgp25** [comment]
There are examples explaining this.

Best regards
