### ISSUE TITLE
How to use socks proxy with authentication?

### ISSUE THREAD

**Issue by cosinus90** [mgp25/Instagram-API#2943]
# Question
I cant use authenticated socks proxies.
---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
I cant't use authenticated socks proxy. Below are my attempts

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
$ig->setProxy('tcp://user:pass@1.2.3.4:15098');
$ig->setProxy('socks5://user:pass@1.2.3.4:15098');
$ig->setProxy('socks5h://user:pass@1.2.3.4:15098');

$ig->setProxy([
	'proxytype' => CURLPROXY_SOCKS5, 'proxy'=>"1.2.3.4:15098", 'proxyuserpwd'=>'user:pass'
]); 
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
 Network: CURL error 56: Proxy CONNECT aborted (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

```

In the same time curl_mod request with options 
```
['proxytype' => CURLPROXY_SOCKS5, 'proxy'=>"1.2.3.4:15098", 'proxyuserpwd'=>'user:pass']
```
works fine.

**Comment by Juan-de-Costa-Rica** [comment]
You need to use guzzle format for proxies.

```
// SOCKS5 Proxy needing authentication:
$ig->setProxy('socks5://user:pass@iporhost:port');
```

**Comment by cosinus90** [comment]
Oops, sorry.. I missed another function where I assign the proxy too and there was remained http://
It would be better to delete this tread.
