### ISSUE TITLE
no access to getFelixShare

### ISSUE THREAD

**Issue by alipishevar** [mgp25/Instagram-API#2946]
# Bug Report

---

### Description
Please include a well-worded description of your issue below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

Making a direct->getThread($threadId)->getThread()->getItems()[0]->getFelixShare() request on direct messages can lead to LazyJsonMapperException error.

### Code

```php
$messages = $this->instagram()->direct->getThread($threadId)->getThread()->getItems();
$messages[0]->getFelixShare()
``` 

### Debug Log
```php
"message": "Unable to convert data to stdClass: Bad JSON property definitions in \"InstagramAPI\\Response\\Model\\FelixShare\": (['Unexpected non-numeric array key (\"taken_at\") for array-property \"video\" at array-depth 0 of 1.']).",
    "exception": "LazyJsonMapper\\Exception\\LazyJsonMapperException",
    "file": "/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php",
    "line": 1174,
```

**Comment by JRoy** [comment]
We can't control what Instagram sends back.

Regards.

**Comment by mgp25** [comment]
@alipishevar post debug log

**Comment by koso00** [comment]
> We can't control what Instagram sends back.
> 
> Regards.

you must wrap, no control what instagram sends back, this bug happens sometimes when in a chat is present a shared post containing a video
