### ISSUE TITLE
story not marked as seen

### ISSUE THREAD

**Issue by Farzadyz** [mgp25/Instagram-API#2948]
hi in when i send a request for see story in api all its good and show this log
`"debug":{"mark_seen_resp":"ok","getReelsMediaFeed":4,"markMediaSeen":1,"delay":43,"info":"markMediaSeen() at 200","memory_get_usage":10249224,"memory_get_peak_usage":10901848},"pid":"14043"`
but in instagram app story not marked as seen

**Comment by itsrehanijaz** [comment]
> hi in when i send a request for see story in api all its good and show this log
> `"debug":{"mark_seen_resp":"ok","getReelsMediaFeed":4,"markMediaSeen":1,"delay":43,"info":"markMediaSeen() at 200","memory_get_usage":10249224,"memory_get_peak_usage":10901848},"pid":"14043"`
> but in instagram app story not marked as seen

You must have ->setVersion(2) in src/Requests/internal.php under function markStoryMediaSeen(). If your version of script is calling Version 1, it is deprecated endpoint.
