### ISSUE TITLE
File autoload.php Not found

### ISSUE THREAD

**Issue by ocbocb** [mgp25/Instagram-API#295]
Hi, 
Thanks for you work on this API. However, I noticed that autoload.php is not included. However it is required in the Registration Tool. Please advise.

**Comment by mgp25** [comment]
@ocbocb in the readme is explained, you need composer and then do this: composer require mgp25/instagram-php

Regards

**Comment by ocbocb** [comment]
OK, Thank you.

**Comment by AndiHamolli** [comment]
Is there some way to use the library without composer?
