### ISSUE TITLE
Unfollow Error

### ISSUE THREAD

**Issue by ataliweb** [mgp25/Instagram-API#2950]
Hello,

I get an error this way:

code : $ig->people->unfollow($user);
error : 
`Fatal error: Uncaught InstagramAPI\Exception\FeedbackRequiredException: InstagramAPI\Response\FriendshipResponse: Feedback required. in /var/www/vhosts/adnkonline.com/httpdocs/ataliweb/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:190 Stack trace: #0 /var/www/vhosts/adnkonline.com/httpdocs/ataliweb/vendor/mgp25/instagram-php/src/Client.php(579): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'feedback_requir...', Object(InstagramAPI\Response\FriendshipResponse), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/vhosts/adnkonline.com/httpdocs/ataliweb/vendor/mgp25/instagram-php/src/Request.php(832): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\FriendshipResponse), '{"message": "fe...', Object(GuzzleHttp\Psr7\Response)) #2 /var/www/vhosts/adnkonline.com/httpdocs/ataliweb/vendor/mgp25/instagram-php/src/Request/People.php(807): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\FriendshipResponse)) #3 /var/www/vhosts/adnkonline.com/httpdocs/dene in /var/www/vhosts/adnkonline.com/httpdocs/ataliweb/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php on line 190`

**Comment by erencandamaroglu** [comment]
There is no solution on the page you are given only to that page but you do not offer a solution.
