### ISSUE TITLE
LoginFlow process in version 6.1.0 Better than 7.1.0

### ISSUE THREAD

**Issue by moosavimaleki** [mgp25/Instagram-API#2951]
when login with Instagram-API:7.1.0 the ThrottledException occurred (with some instagram accounts, not all them)
but when use Instagram-API:6.1.0 for those accounts it works very good

I have tested this item several times (with delete session files)

I don't need the 7.1.0 version
I just sent this issue for reporting to contributors team

**Comment by moosavimaleki** [comment]
the different are in ```_sendLoginFlow``` function

**Comment by JRoy** [comment]
Duplicate of #2941
