### ISSUE TITLE
Account Compromised Challenge.

### ISSUE THREAD

**Issue by itsrehanijaz** [mgp25/Instagram-API#2954]
#2713 Feature Request

---

### Notes:
We will close your feature request, sometimes without answering, if any of the following are met:
* You requested a endpoint/function for `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block` errors. These are decidedly unsupported, and will not be added
* You requested a endpoint/function for an iOS feature. This API emulates the Android API, therefore we cannot, *safely*, add endpoints/functions which are not in the Android app.
* You are using the wrong issue template

Please make sure you have done the following before submitting your feature request:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for the same feature request
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)

---

### Description
Please include a well-worded description of your feature request. Please make sure to include where on the app this feature is acceptable so we can reproduce it. Additionally, it would make our lives easier if you are able to post the endpoint, its associated parameters, and response.

Recently Instagram started forcing users to change their passwords while watching stories (after 10K stories). Update is required for story endpoints.
![Capture](https://user-images.githubusercontent.com/22751063/67539725-7e242400-f6fc-11e9-9354-031e607f023f.PNG)

`{
"message": "checkpoint_required",
"checkpoint_url": "https://i.instagram.com/challenge/?challenge_node_id=18067271881160731",
"lock": true,
"status": "fail"
}`

**Comment by JRoy** [comment]
Not spamming should prevent this. 

Additionally, we do not support `checkpoint_required` errors as stated on the issue template.

Regards.
