### ISSUE TITLE
Sort by date followed

### ISSUE THREAD

**Issue by 0xmahdi** [mgp25/Instagram-API#2955]
# Feature Request

---

Please add this feature in `getSelfFollowing()`  just like Instagram app.

<img src="https://user-images.githubusercontent.com/53916487/67567747-57371380-f737-11e9-97e7-354ec1699e28.jpg" width=300>

**Comment by mgp25** [comment]
Self note. Added in private repo.

**Comment by JRoy** [comment]
This has been added on the private api, please see #2655 for information on how to subscribe.

Cheers.
