### ISSUE TITLE
Media Like Doesn't work any more in this a few days

### ISSUE THREAD

**Issue by Ebrahimjz** [mgp25/Instagram-API#2957]
i have use media like to auto like my timeline posts its worked fine for a week and now there is some days its not working and gave me FeedBackRequestException in log what should i do to make it work again?

**Comment by Ebrahimjz** [comment]
i send my error here to see what happened i can take results from server but cannot like any media from library

> PHP Fatal error:  Uncaught InstagramAPI\Exception\FeedbackRequiredException: InstagramAPI\Response\GenericResponse: Feedback required. in C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25
\instagram-php\src\Exception\ServerMessageThrower.php:190
Stack trace:
#0 C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\instagram-php\src\Client.php(576): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'feedback_requir...',
 Object(InstagramAPI\Response\GenericResponse), Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\instagram-php\src\Request.php(832): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\GenericResponse), '{"message":
 "fe...', Object(GuzzleHttp\Psr7\Response))
#2 C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\instagram-php\src\Request\Media.php(164): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\GenericResponse))
#3 C:\xampp\htdocs\InstagramAPIGit\autoLike.php(56): InstagramAPI\Request\Media->like('216346583034889...')
#4 {main}
  thrown in C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\instagram-php\src\Exception\ServerMessageThrower.php on line 190

Fatal error: Uncaught InstagramAPI\Exception\FeedbackRequiredException: InstagramAPI\Response\GenericResponse: Feedback required. in C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\inst
agram-php\src\Exception\ServerMessageThrower.php:190
Stack trace:
#0 C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\instagram-php\src\Client.php(576): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'feedback_requir...',
 Object(InstagramAPI\Response\GenericResponse), Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\instagram-php\src\Request.php(832): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\GenericResponse), '{"message":
 "fe...', Object(GuzzleHttp\Psr7\Response))
#2 C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\instagram-php\src\Request\Media.php(164): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\GenericResponse))
#3 C:\xampp\htdocs\InstagramAPIGit\autoLike.php(56): InstagramAPI\Request\Media->like('216346583034889...')
#4 {main}
  thrown in C:\xampp\htdocs\InstagramAPIGit\vendor\mgp25\instagram-php\src\Exception\ServerMessageThrower.php on line 190

**Comment by JRoy** [comment]
We don't support feedback required

**Comment by jorgemudry** [comment]
@Ebrahimjz it seems that you need to re-authorize your account against Instagram (or Instagram does not like you to do that (like a media) using the library.

btw, this "issue" is probably going to be closed because you didn't follow the issue template 😝
