### ISSUE TITLE
Media like returns empty response

### ISSUE THREAD

**Issue by everdrone** [mgp25/Instagram-API#2958]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* [x] You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* [x] You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* [x] You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* [x] You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* [x] You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* [x] You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

Cannot like any media (from any account).
My profile isn't flagged as a bot, I do not spam likes or content and I am able to upload photos via this API so it's not an ip ban or anything like that.

Do i need to update the signature that ships with this repo?
I'm having an hard time trying to figure out what's missing

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
<?php
set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'/../../../vendor/autoload.php';
/////// CONFIG ///////
$username = 'REDACTED';
$password = 'REDACTED';
$debug = true;
$truncatedDebug = false;
//////////////////////
/////// MEDIA ////////
use InstagramAPI\InstagramID;

$ig = new \InstagramAPI\Instagram(true);
try {
  // print "logged in using $username\n";
  $ig->login($username, $password);
} catch (\Exception $e) {
  echo 'Something went wrong: '.$e->getMessage()."\n";
  exit(0);
}

$shortcode = "B4Adl5MnEs3";

try {
  $mediaId = InstagramID::fromCode($shortcode);
  // print "media id for $shortcode is $mediaId\n";
  $response = $ig->media->getInfo($mediaId);
  $media_username = $response->getItems()[0]->getUser()->getUsername();
  $media_userid = $response->getItems()[0]->getUser()->getUserId();
  $module = 'feed_timeline';
  $extraData = ['username' => $media_username, 'user_id' => $media_userid];
  $response = $ig->media->like($mediaId, $module);
  // print "liked $shortcode\n";
} catch(\Exception $e) {
  echo 'Something went wrong: '.$e->getMessage()."\n";
}
?>
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
POST:  https://i.instagram.com/api/v1/media/2161857968522152759/like/
DATA: signed_body=c51014417fb163e68b9235832bc46dd38123c2cc35afec612cb6ca42163cbafd.{"media_id":"2161857968522152759","_csrftoken":"bJsRnvAIuCUDnpSo4Za7AxJCvKAOUf0M","radio_type":"wifi-none","_uid":"1602963060","device_id":"android-a8a5c0caf507d7fd","_uuid":"91464dee-1a1c-419d-b9db-b6010207b659","is_carousel_bumped_post":"false","container_module":"feed_timeline","feed_position":"feed_timeline"}&ig_sig_key_version=4&d=0
← 500 	 25B
RESPONSE: Oops, an error occurred.
```

**Comment by Juan-de-Costa-Rica** [comment]
This works:

```php
try {
    $mediaId = InstagramID::fromCode($shortcode);
    // print "media id for $shortcode is $mediaId\n";
    $response = $ig->media->getInfo($mediaId);
    $media_username = $response->getItems()[0]->getUser()->getUsername();
    $media_userid = $response->getItems()[0]->getUser()->getPk();

    $module = 'feed_timeline';
    $extraData = ['username' => $media_username, 'user_id' => $media_userid];
    $response = $ig->media->like($mediaId, 0, $module);
    // print "liked $shortcode\n";
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

Gotta change `->getUserId()` to `->getPk()` and  put the feed position into the `like()` method!

**Comment by everdrone** [comment]
Yes! Thank you!
