### ISSUE TITLE
stats increase

### ISSUE THREAD

**Issue by iccunha** [mgp25/Instagram-API#296]
hello, it would be possible to get a profile of increase statistical report on instagram between dates?
example: between 22.06.2016 to 07.22.2016 +1000 followers and -100 followers and even have a list of people who left to follow and on what date

![screenshot_1](https://cloud.githubusercontent.com/assets/20159214/17075097/aec6a5ac-505f-11e6-88a9-55441daca3ad.jpg)

**Comment by RageBrahimi** [comment]
Maybe, when Instagram open up analytics for everyone.
