### ISSUE TITLE
$response->getRankToken() result string is not a valid rank token.

### ISSUE THREAD

**Issue by nJuraev** [mgp25/Instagram-API#2963]
# Bug Report

### Description
Please include a well-worded description of your issue below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

Something went wrong while fetching people: `1572258398139|8cee6301001a9d9d570d1c183e676d2888f9c5614428d38c3e85c36ceb1588e2` is not a valid rank token.
This error appears when i search for people, hashtags and locations . When i use permanent rank token from `$rankToken = \InstagramAPI\Signatures::generateUUID();` response return same 30 items many times

### Code
Please post your code relevant to the bug in the section below:

```php
       $result = array();
        $excludeList = [];
        $rankToken = null;
        try {
            do {
                $response = $this->ig->people->search($query,$excludeList,$rankToken);
                foreach ($response->getUsers() as $user) {
                    $excludeList[] = $user->getPk();
                    $result[] = $user->asArray();
                   //Log::info($user);
                }
                Log::info($excludeList);

                Log::info('has more^ ' . $response->getHasMore());
                $rankToken = $response->getRankToken();
                Log::info( "Sleeping for 3s...");
                sleep(3);
            } while ($response->getHasMore());

            Log::info("users found " . count($result));
        } catch (\Exception $e) {
            Log::error('Something went wrong while fetching people: ' . $e->getMessage());
        } 
```

**Comment by Juan-de-Costa-Rica** [comment]
You can't keep keep changing the exclude list.
Remove or comment that part out and it works.

```
       $result = array();
        $excludeList = [];
        $rankToken = null;
        try {
            do {
                $response = $this->ig->people->search($query,$excludeList,$rankToken);
                foreach ($response->getUsers() as $user) {
                    //$excludeList[] = $user->getPk();
                    $result[] = $user->asArray();
                   //Log::info($user);
                }
                Log::info($excludeList);

                Log::info('has more^ ' . $response->getHasMore());
                $rankToken = $response->getRankToken();
                Log::info( "Sleeping for 3s...");
                sleep(3);
            } while ($response->getHasMore());

            Log::info("users found " . count($result));
        } catch (\Exception $e) {
            Log::error('Something went wrong while fetching people: ' . $e->getMessage());
        } 
```

**Comment by nJuraev** [comment]
> Remove or comment that part out and it works
your advice not good. these edits led to endless loop? and your answer in not answer for main problem
1572258398139|8cee6301001a9d9d570d1c183e676d2888f9c5614428d38c3e85c36ceb1588e2 is not a valid rank token.

**Comment by Juan-de-Costa-Rica** [comment]
Your problem was that you weren't getting a valid rank token because you were using the exclude list incorrectly. 

Not changing the exclude list every loop gets you a valid rank token and fixes the problem associated with this library. 

A basic php tutorial can show you how to exit a loop when you are ready to.

**Comment by nJuraev** [comment]
Shouldn't i use the excludeList at all? i have tried this way and the result was endless loop because $response->getHasMore() always return true

**Comment by Juan-de-Costa-Rica** [comment]
Exclude list should be set before your do while loop, and you shouldn't change it.

**Comment by nJuraev** [comment]
I want to describe what I understand from your answers
For solving problem with rank token I need do not change exclude List on while loop? Okay I tried this way and rankToken error dissapeared but the result was infinite loop because $response->getHasMore always returns true and the response->getUsers() always returns the same 30 records. RankToken on each response changes but it does not effect to returned data and pagination
What can you say about this example Pagination with exclusion
In this example exlude List changes in each loop and there rank token changes to.
I ask you to help me with this little problem and if you can get working example of searching users
