### ISSUE TITLE
My script doesnt add captions to posts

### ISSUE THREAD

**Issue by Quiec** [mgp25/Instagram-API#2964]
# Bug Report

---

### Description
Bot does not add captions to posts. It happens once or twice a week (like now), and then it goes back to normal. But why is it happening? 

### Code
fotoat.php: `

<?php 
include "Config.php";

$photo8 = __DIR__ . '/abbas.jpg';
         $metadata8 = [
    'caption' => 'afadsfas |adfasfd tarafından gönderildi | r/tamamahbapengelli Hot #1'
];

$photo8 = new \InstagramAPI\Media\Photo\InstagramPhoto($photo8);
 $ig->timeline->uploadPhoto($photo8->getFile(), $metadata8);
` 
config.php: `
<?php
require __DIR__ . '/vendor/autoload.php';
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

$username = 'turkeyjerky0';
$password = '';

$debug = true;
$truncatedDebug =true;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->login($username, $password);
`

### Debug Log

`root@archi-sunucu:~/yusuf/www# php fotoat.php
POST:  https://i.instagram.com/api/v1/upload/photo/
→ 22.95kB
← 200    71B
RESPONSE: {"upload_id": "645003345106647", "xsharing_nonces": {}, "status": "ok"}

POST:  https://i.instagram.com/api/v1/media/configure/?timezone_offset=0
DATA: signed_body=3f17309a677f8b5ff3290bc2404470aeadc39ee3ee1272fd55f06fbb01b58bf1.{"device":{"manufacturer":"samsung","model":"SM-G935F","android_version":"23","android_release":"6.0.1"},"date_time_digitalized":"2019:10:28 11:10:04","_csrftoken":"mCQFw1KLKnWdnFaRmqXMMWICg1KGubxQ","media_folder":"Camera","source_type":"4","_uid":"6276469501","_uuid":"e0351a04-b2ac-4c4c-aeb7-e3b5604dc4fb","edits":{"crop_original_size":[320,320],"crop_zoom":1,"crop_center":[0,-0]},"extra":{"source_width":320,"source_height":320},"caption":"afadsfas |adfasfd taraf\u0131ndan g\u00f6nderildi | r\/tamamahbapengelli Hot #1","date_time_original":"2019:10:28 11:10:04","upload_id":"645003345106647"}&ig_sig_key_version=4
← 200    1.31kB
RESPONSE: {"media": {"taken_at": 1572261005, "pk": 2164604658266168330, "id": "2164604658266168330_6276469501", "device_timestamp": 645003345106647, "media_type": 1, "code": "B4KOHfXHFwK", "client_cache_key": "MjE2NDYwNDY1ODI2NjE2ODMzMA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"width": 320, "height": 320, "url": "https://scontent-fco1-1.cdninstagram.com/vp/9ec6c902856080c6f9390956983328dc/5E613221/t51.2885-15/e35/74936907_784482435355110_3226708366901895652_n.jpg?_nc_ht=scontent-fco1-1.cdninstagram.com\u0026_nc_cat=106\u0026ig_cache_key=MjE2NDYwNDY1ODI2NjE2ODMzMA%3D%3D.2", "estimated_scans_sizes": [2135, 4270, 6406, 8541, 10676, 13328, 172133, 19218, 19218]}, {"width": 480, "height": 480, "url": "https://scontent-fco1-1.cdninstagram.com/vp/9ec6c902856080c6f9390956983328dc/5E613221/t51.2885-15/e35/74936907_784482435355110_3226708366901895652_n.jpg?_nc_ht=scontent-fco1-1.cdninstagram.com\u0026_nc_cat=106\u0026ig_cache_key=MjE2NDYwNDY1ODI2NjE2ODMzMA%3D%3D.2", "estimated_scans_siz...`

**Comment by mgp25** [comment]
Not a bug, probably because you are spamming or either your IP or account is flagged. 

Regards

**Comment by rob-z** [comment]
Hi, I'm facing the same issue. How do I check that my IP or account is flagged? When I run the Instagram-API script in debug mode, everything seems fine (just as with the starter of this topic).  I get a response that the image was posted. The image is posted, but without a caption. 

When I manually post an image through the Instagram app, I have no trouble adding a caption.
