### ISSUE TITLE
getUserFeed return "Throttled by Instagram because of too many API requests"

### ISSUE THREAD

**Issue by nicolass2002** [mgp25/Instagram-API#2965]
# Question
Hi,
few days ago all work ok...and without any change in code I got 
"Throttled by Instagram because of too many API requests" in error log.

I inspect and see that getUserFeed function from Requests/Timeline not work and return that error.

I get stories, and higlights, tags...etc...Only when I try to get posts by user I got that error. 

Any suggestion?

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

__INSERT YOUR DESCRIPTION HERE__

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
INSERT YOUR CODE HERE
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
INSERT YOUR DEBUG LOG HERE
```

**Comment by Aassifh** [comment]
I am having the same issue, waiting for help if there is any ? Thanks..

**Comment by LouenLeoncoeur** [comment]
Same here

**Comment by JRoy** [comment]
This is likely because you're being detected for spam.

Regards.

**Comment by LouenLeoncoeur** [comment]
@JRoy I'm not spamming any requests from my account, but three days ago I noticed that exception though nothing changed. I removed timeline->getUserFeed request and tried to load some profiles, no exceptions. Could you please check it?

**Comment by laccielchourdin** [comment]
I’ve faced with same issue as described above.

**Comment by laccielchourdin** [comment]
And it’s started after recent IG October updates.

**Comment by bobbonew** [comment]
Instagram now enforces users to be logged in to view public profiles. Just saw this news on HN:


https://thenextweb.com/socialmedia/2019/10/28/instagram-now-forces-people-to-sign-in-to-view-public-profiles/

This must be why this error has cropped up.

**Comment by LouenLeoncoeur** [comment]
Why is it related?

**Comment by bobbonew** [comment]
You’re getting a throttle error when trying to grab public feeds. 

Public feeds are no longer available. You must be logged in.

**Comment by LouenLeoncoeur** [comment]
but in order to use this library you have to be logged in and my account was logged in when I got this exception

**Comment by laccielchourdin** [comment]
> This is likely because you're being detected for spam.
> 
> Regards.

Based on this information, there should be much more exceptions and troubles with other functions caused by that. I have colleagues, that are using this API and other private APIs as well, most of them are getting the same problems with getting posts by user. Something has changed on IG's side from the last October update. There are some thoughts, that IG is flagging UserAgents from now ( not an IP ban or temp account limitation). It seems to be global issue for all private APIs. This one is not an exception.

**Comment by Aassifh** [comment]
I think this issue should be reopened because its not working, is it possible ? Thank you

**Comment by nicolass2002** [comment]
Reopen issue.

**Comment by kakilang1982** [comment]
Is this issue reopen?
