### ISSUE TITLE
uploadPhoto does not work anymore

### ISSUE THREAD

**Issue by pussbb** [mgp25/Instagram-API#2967]
Even with example script uploadPhoto I get 
```plain
POST:  https://i.instagram.com/api/v1/upload/photo/
→ 62.1kB
← 400    58B
RESPONSE: Something is wrong. Please check your input and try again.
```

Any glues why it happens, yersterday everything was working?

```plain
[2019-10-29 08:45:21] request.ERROR: InstagramAPI\Exception\BadRequestException: Invalid request options. in /vendor/mgp25/instagram-php/src/Client.php:489
Stack trace:
#0 /vendor/mgp25/instagram-php/src/Request.php(832): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\UploadPhotoResponse), 'Something is wr...', Object(GuzzleHttp\Psr7\Response))
#1 /vendor/mgp25/instagram-php/src/Request/Internal.php(1740): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\UploadPhotoResponse))
#2 /vendor/mgp25/instagram-php/src/Request/Internal.php(139): InstagramAPI\Request\Internal->_uploadPhotoInOnePiece(1, Object(InstagramAPI\Request\Metadata\Internal))
#3 /vendor/mgp25/instagram-php/src/Request/Internal.php(101): InstagramAPI\Request\Internal->uploadPhotoData(1, Object(InstagramAPI\Request\Metadata\Internal))
#4 /vendor/mgp25/instagram-php/src/Request/Timeline.php(38): InstagramAPI\Request\Internal->uploadSinglePhoto(1, '/tmp/INSTAIMG_Z...', Object(InstagramAPI\Request\Metadata\Internal), Array)

```

**Comment by Tridenn** [comment]
Hi, the bug problem got worse yesterday. #2665

**Comment by usamaejaz** [comment]
Same here. Photo, album, and even video upload is not working. #2665

**Comment by hoemon** [comment]
Same here for me. Updated to the latest version, login works, but the uploads do not work.

**Comment by hoemon** [comment]
`Something went wrong (photo upload): Invalid request options.`

**Comment by hoemon** [comment]
For story uploads, it's very similar
`Something went wrong (videostory upload): Upload of "videotoupload" failed: Instagram's server returned HTTP status "400".`

**Comment by vostlerts** [comment]
![image](https://user-images.githubusercontent.com/42810338/67745700-f872e200-fa35-11e9-917c-181bfc9f2888.png)
Upload Story: Something is wrong. Please check your input and try again.

**Comment by messilao** [comment]
Same here for me. Updated to the latest version, login works, but the uploads do not work.

**Comment by bepossitive** [comment]
All the same, looks like Instagram changed their API methods

**Comment by hoemon** [comment]
I hope this resolves quickly :/

**Comment by hoemon** [comment]
(in the meantime, if there are any quick fixes until an official update is here, please share <3)

**Comment by hoemon** [comment]
quick test update: other (non-php) private instagram api's still work. Some of them are updated months ago. Therefore I believe the error may be unrelated to instagram's api change. (unless other libraries somehow implemented the change beforehand?)

**Comment by Ejara1986** [comment]
now upload image is work for me

**Comment by bepossitive** [comment]
Looks like working now

**Comment by pussbb** [comment]
For me its also working. Lets say temprorary issues at Instagram side
