### ISSUE TITLE
Something is wrong. Please check your input and try again.

### ISSUE THREAD

**Issue by holden321** [mgp25/Instagram-API#2971]
All of a sudden, Instagram starts to response with "Something is wrong. Please check your input and try again." when photos are uploading.

POST: https://i.instagram.com/api/v1/upload/photo/ → 212.52kB ← 400 58B RESPONSE: Something is wrong. Please check your input and try again.

**Comment by RonSv** [comment]
Same problem.

In the first I saw an error about 12 hours ago, then it went away by itself. And such errors started again about 2 hours ago.

**Comment by aislandener** [comment]
+1

**Comment by omv58** [comment]
Same problem.

**Comment by taangarm** [comment]
+1

**Comment by mewlabs** [comment]
same problem

**Comment by JRoy** [comment]
Due to multiple people experiencing this, I'll ignore your lack of following the issue template but please follow it next time  :)

As for this, let's hope it's Instagram being funny again but I'll keep this open for monitoring...
