### ISSUE TITLE
Challenge Required

### ISSUE THREAD

**Issue by chrischance67** [mgp25/Instagram-API#2981]
# Question

---

### Notes:

Hello, 
I have a problem with the package, as I commented. A few months ago, I integrated this package into a personal website, everything worked very well, in fact, I had problems integrating the Challenge, but it finally worked. The point is that for a short time now, it is not working, the API only returns "Challenge Required". And I really need this integration

**Comment by elpresti** [comment]
The same to me right now.
I: 27/01/2020 22:44:53: [0;36mRESPONSE: [0m{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/4398118760/VBDr2F6ISt/", "api_path": "/challenge/4398118760/VBDr2F6ISt/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}

Any help? I already have tried this, but without success:
https://www.techjunkie.com/instagram-error-challenge_required-what-to-do/

I'll appreciate your help.
Thanks!
