### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by CamiloManrique** [mgp25/Instagram-API#299]
@mgp25  I'm trying to login using the following code:

<?php

include __DIR__.'/../vendor/autoload.php';
require '../src/Instagram.php';

/////// CONFIG ///////
$username = 'camilomanriquec';
$password = 'c31353135';
$debug = true;
//////////////////////

$i = new \InstagramAPI\Instagram($username, $password, $debug);

try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}

?>

However in the response i get the following lines:

REQUEST: friendships/autocomplete_user_list/
RESPONSE: {"status": "fail", "message": "login_required"}

REQUEST: feed/timeline/
RESPONSE: {"status": "fail", "message": "login_required"}

REQUEST: direct_v2/inbox/?
RESPONSE: {"status": "fail", "message": "login_required"}

I don't know what I'm doing wrong. Thanks in advance.

**Comment by MrProrper** [comment]
Make sure your `data` folder privileges/permission is `read and write` and try again.
if its already done and not working try `$i->login(true);`

Regards.
