### ISSUE TITLE
getUserStoryFeed return always caption null

### ISSUE THREAD

**Issue by marcovieira17** [mgp25/Instagram-API#2993]
Caption is returning null when call getUserStoryFeed() but when call media->getInfo($storyID) is returning caption.

Any solution?

Best regards.

**Comment by mgp25** [comment]
Please make sure to search before opening a new issue since this has been already answered.

It is not an issue and not a bug, that is how Instagram works now, caption is only been returned when calling `getInfo()`.

Best regards
