### ISSUE TITLE
 Hashtag ranked posts feed uses outdated endpoint, it provides only 9 ranked items

### ISSUE THREAD

**Issue by jettero777** [mgp25/Instagram-API#2996]
# Feature Request

---

### Notes:
We will close your feature request, sometimes without answering, if any of the following are met:
* You requested a endpoint/function for `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block` errors. These are decidedly unsupported, and will not be added
* You requested a endpoint/function for an iOS feature. This API emulates the Android API, therefore we cannot, *safely*, add endpoints/functions which are not in the Android app.
* You are using the wrong issue template

Please make sure you have done the following before submitting your feature request:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for the same feature request
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)

---

### Description
Please include a well-worded description of your feature request. Please make sure to include where on the app this feature is acceptable so we can reproduce it. Additionally, it would make our lives easier if you are able to post the endpoint, its associated parameters, and response.

Current API uses `feed/tag/[TAG]/` endpoint for hashtag feed.
But seems it is outdated as it provides only 9 items as ranked posts, though there are hundreds ranked posts in the app (TOP tab in tag feed).
It is not matter of pagination, it is 9 ranked posts in total, no more.

As was reported in #1858 since app ver 26.0.0.13.86 the endpoints for hashtag feed were changed to `tags/[TAG]/ranked/` and `tags/[TAG]/recent/`
I did tests with `tags/[TAG]/ranked/` and I'm getting full list of ranked posts with it, same as is in the app.

**Comment by JRoy** [comment]
I don't know why `Hashtag::getFeed()` was in there for so long, as they've been replaced by `Hashtag::getSection()`

Anyways, I've deprecated `Hashtag::getFeed()` in ea95726f817b8b2e89069d042cbcaec4699cb48d. Now it's just a wrapper for `Hashtag::gtSection()`. It will be removed down the road all together, so please start using `Hashtag::gtSection()`.

Cheers.
