### ISSUE TITLE
Misspelled variable

### ISSUE THREAD

**Issue by dsentker** [mgp25/Instagram-API#300]
Notice from my IDE.

Instagram.php, Line 441: $recimient_users should be $recipeint_users (as defined in line 428=

`$recipeint_users = implode(',', $string);

        $endpoint = Constants::API_URL.'direct_v2/threads/broadcast/media_share/?media_type=photo';
        $boundary = $this->uuid;
        $bodies = [
            [
                'type' => 'form-data',
                'name' => 'media_id',
                'data' => $media_id,
            ],
            [
                'type' => 'form-data',
                'name' => 'recipient_users',
                'data' => "[[$recimient_users]]", // <--
            ],
[...]
`

Good API anyway, thank you for your work!

**Comment by RageBrahimi** [comment]
Pull request already [made](https://github.com/mgp25/Instagram-API/pull/244).

**Comment by dsentker** [comment]
Oh, i did not notice that this was already fixed. I got this (outdated?) version from packagist / composer.
