### ISSUE TITLE
userFrienship endpoint returning 405 response.

### ISSUE THREAD

**Issue by pabloVoorvaart** [mgp25/Instagram-API#3006]
Hello, 

currently the userFriendship endpoint is returning 405 responses. This has been happenning for a while now? Any ideas why this could be hapenning? Is the endpoint depriciated?

Cheers, Pablo.

**Comment by JRoy** [comment]
Can you share the function you're using as well as a debug log

**Comment by JRoy** [comment]
Closing due to no response from the op.

**Comment by frame888** [comment]
I have the same issue with the python InstagramAPI (The developer said it is a port of the PHP version) and I encountered the same problem. I found that the `userFriendship` endpoint no longer accepts POST requests. Changing the request method from POST to GET solved the problem. The POST parameters `ig_sig_key_version` and `signed_body` are no longer required.
