### ISSUE TITLE
Media likes search api

### ISSUE THREAD

**Issue by lewbor** [mgp25/Instagram-API#3008]
# Feature Request

---

### Notes:
We will close your feature request, sometimes without answering, if any of the following are met:
* You requested a endpoint/function for `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block` errors. These are decidedly unsupported, and will not be added
* You requested a endpoint/function for an iOS feature. This API emulates the Android API, therefore we cannot, *safely*, add endpoints/functions which are not in the Android app.
* You are using the wrong issue template

Please make sure you have done the following before submitting your feature request:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for the same feature request
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)

---

### Description

Recently Instagram added a likes search functionality (similar to subscribes search). When you get a list of media likes, you can also a search for a specific person. Can it be implemented?
Thanks for you great work!

**Comment by JRoy** [comment]
After looking into this, it appears the app itself is searching the list of people from the `likers` request and no alternate request is being sent to filter the list. So you will need to do this in your code.

Cheers.
