### ISSUE TITLE
After I using `getSections()` I have trouble, maybe tab argument is required?

### ISSUE THREAD

**Issue by igorbelikov** [mgp25/Instagram-API#3013]
# Question
After I using `getSections()` I have trouble, maybe tab argument is required?

### Description
After I use the getSections tag search method in my Instagram account, I’m asked to change my password as if I’m doing something forbidden, is it possible to pass $tab in the getSections method?

### Code
```php
// ...

// check count
$api->hashtag->getInfo($taskTagPrepared)->getMediaCount()

// process response
$response = $api->hashtag->getSection($hashtag, \InstagramAPI\Signatures::generateUUID(), null, $nextIds, $maxId);

// process medias
foreach ($response->getSections() as $section) {
    $responseItems = $section->getLayoutContent()->getMedias();
    foreach ($responseItems as $item) {
        $currentItems[] = $item->getMedia();
    }
}

// ...
```

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Hashtag.php#L55

**Comment by igorbelikov** [comment]
@mgp25 yes, I have seen that, but in your souce you have this:
```
if ($tab !== null) {
            if ($tab !== 'top' && $tab !== 'recent' && $tab !== 'places' && $tab !== 'discover') {
                throw new \InvalidArgumentException('Tab section must be \'top\', \'recent\', \'places\' or \'discover\'.');
            }
            $request->addPost('tab', $tab);
        } else {
            // ?
            $request->addPost('supported_tabs', '["top","recent","places","discover"]');
        }
```

and if I use, for example, 'top', then within 5 minutes I also get a request to change the password

even for fun, I used your example about searching by tags:
https://github.com/mgp25/Instagram-API/blob/master/examples/rankTokenUsage.php
