### ISSUE TITLE
Post (photo, video, story) not working any more AGAIN.

### ISSUE THREAD

**Issue by zhelinskyy** [mgp25/Instagram-API#3014]
# Bug Report
I worked with your library for several days without any problems, but now it has stopped working
---

### Notes:
POST: https://i.instagram.com/api/v1/upload/photo/ → 38.2kB ← 400 58B RESPONSE: Something is wrong. Please check your input and try again. Something went wrong: Invalid request options.

I worked with your library for several days without any problems, but now it has stopped working

**Comment by meysam1366** [comment]
hi
I have the same problem
please help me
