### ISSUE TITLE
API - Upload Photo not working any more.

### ISSUE THREAD

**Issue by 55utd55** [mgp25/Instagram-API#3021]
When I run the following code, I get "_Invalid request options._" error. Where's the problem? I am using the latest version of the API.

```
<?php
set_time_limit(0);
date_default_timezone_set('UTC');
require './vendor/autoload.php';
/////// CONFIG ///////
$username = 'username';
$password = 'password';
$debug = false;
$truncatedDebug = false;
//////////////////////
/////// MEDIA ////////
$photoFilename = './image.jpg';
$captionText = 'text';
//////////////////////
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->login($username, $password);
$photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename);
$ig->timeline->uploadPhoto($photo->getFile(), ['caption' => $captionText]);
```

**Comment by daptanque** [comment]
Yeah, there has been a post yesterday about it too but got deleted... I personally have that issue only on uploading albums... but as far as I know version 4.1.0  of mgp25 is continuing to work... Anyway I tried to downgrade but had problems with other packages... 

check this too #2972

**Comment by Blokerok** [comment]
Is there a chance to restore posting photos and albums?

**Comment by 55utd55** [comment]
I use 4.1.0, it is run. Thank you!
