### ISSUE TITLE
{"message": "useragent mismatch", "status": "fail"}

### ISSUE THREAD

**Issue by Jpark99** [mgp25/Instagram-API#3024]
# Bug Report

---

### Notes:
We will close your issue, sometimes without answering, if any of the following are met:
* You have not included your code or your debug log
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your issue:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar issues including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your issue below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

When I try to get FBLocationResponse from valid coordinates, it gives me an error. I follow the link given(https://i.instagram.com/api/v1/fbsearch/places/?timezone_offset=0&lat=-1.57085&lng=36.6&count=50), it says {"message": "useragent mismatch", "status": "fail"}. I'm guessing this is an issue with the android device for some reason? Any idea why this might happen? Thank you.

### Code
Please post your code relevant to the bug in the section below:
```php
$response = $ig->location->findPlacesNearby($y,$z,null,$exclude_list,$rankToken);
``` 

### Debug Log
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`. Additionally, you can do `\InstagramAPI\Debug::$debugLog = true;` for the debug log to be saved to a file:
```php
GET:  https://i.instagram.com/api/v1/fbsearch/places/?timezone_offset=0&lat=-1.57085&lng=36.6&count=50
→ 0B
← 400    396B
RESPONSE: {"message": "[{\"message\":\"Errors while executing operation \\\"IGLocationTaggingQuery\\\": At Query.checkin_search_query:CheckinSearchQuery.place_results:CheckinSearchPlaceResultsConnection.edges: Field implementation threw an exception. Check your server logs for more information.\",\"severity\":\"ERROR\",\"path\":[\"checkin_search_query\",\"place_results\",\"edges\"]}]", "status": "fail"
```

**Comment by JRoy** [comment]
Should be fixed in a26331fec7a333cd34baae99a07ce0873793a404

Cheers.
