### ISSUE TITLE
Can I get recent activity?

### ISSUE THREAD

**Issue by vadimTovstik** [mgp25/Instagram-API#3027]
Need to get account activity like comments, likes, who start follow you. From here https://www.instagram.com/accounts/activity/?__a=1 but using this library. How I can do it?

Note: getRecentActivityInbox() this is not what me need. It's little bit different. It's fetch "what's new" 'news/inbox', not last activity 'accounts/activity'.

**Comment by JRoy** [comment]
That endpoint was shutdown by Instagram and will be removed shortly
