### ISSUE TITLE
Code doesn't correspont to the commit

### ISSUE THREAD

**Issue by cosinus90** [mgp25/Instagram-API#3029]
OK, I don't know much about processes at Github, recently I downloaded the latest version and got an error. The search for the solution brought me to this commit
https://github.com/mgp25/Instagram-API/commit/fd035b3c0750c1d58212375093485ae1952348ef
by Aug 2018. I thought that this fix should present in current state of the file. But currently there isn't this fix
https://github.com/mgp25/Instagram-API/blob/master/src/Response/InsightsResponse.php

OK, may be it was deleted later? But looking the history one can see that that there were not any commits afterwards
https://github.com/mgp25/Instagram-API/commits/master/src/Response/InsightsResponse.php

What's going on here?

**Comment by JRoy** [comment]
Sorry I'm confused, what are you talking about because I can see that commit in that file

**Comment by cosinus90** [comment]
Oh, sorry, I just thought that commit's gist is ADDING brackets, not removing. I felt that something wrong on my side...
