### ISSUE TITLE
getUserFeed problem

### ISSUE THREAD

**Issue by snapmaster** [mgp25/Instagram-API#303]
Recently after trying to get info about user I got `"message": "checkpoint_required"`. Before I never had such a problem. Do not have android device to check is enpoint still works the same way. Any help, guys? Ty :)

```

REQUEST: feed/user/XXXXXXXX/?rank_token=3591841712_7e356b99-23b8-447b-aa7b-42b0f2818435&ranked_content=true
RESPONSE: {"status": "fail", "lock": true, "message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/challenge/?rank_token=3591841712_7e356b99-23b8-447b-aa7b-42b0f2818435\u0026ranked_content=true"}


REQUEST: users/XXXXXX/info/
RESPONSE: {"status": "fail", "lock": true, "message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/challenge/"}


**But this request works perfectly** 
REQUEST: users/USERNAME/usernameinfo/

```

**Comment by GuilhermeFM** [comment]
This happens when instagram ask for a "authenticity confirmation". In order to solve this problem you need to manually login into the account used to make the request and answer the verification

**Comment by snapmaster** [comment]
@GuilhermeFM so I guess  endpoints are the same but insta keep asking for phone verification after second request I am doing through API... Hm

**Comment by GuilhermeFM** [comment]
@snapmaster For me the api asked for this only once

**Comment by mgp25** [comment]
Verify it again and it should work

Regards
