### ISSUE TITLE
Something is wrong. Please check your input and try again.

### ISSUE THREAD

**Issue by michelmelo** [mgp25/Instagram-API#3030]
Hello, I have this error in one of my accounts,
My test account is working and my personal is not, the same code, the difference is only where is the username and password.
 response with "Something is wrong. Please check your input and try again." when photos are uploading.

POST: https://i.instagram.com/api/v1/upload/photo/ → 212.52kB ← 400 58B RESPONSE: Something is wrong. Please check your input and try again.

**Comment by JRoy** [comment]
Instagram and Facebook are experiencing worldwide outages right now, therefore I'm confident this isn't an api issue.

The reason your test account is working is likely due to a saved session because not *all* endpoints are down.

Regards.
