### ISSUE TITLE
 Authorization stopped working

### ISSUE THREAD

**Issue by Blok76** [mgp25/Instagram-API#3031]
# Question

Today, authorization in the API has stopped working. v. 4.1.0. Pleas Help.
 
 \InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
    $ig = new \InstagramAPI\Instagram(true, false);    
  try {
      $ig->login($config['instagram']['username'], $config['instagram']['password']);
  } catch (\Exception $e) {
    $info .= 'Instagram login error: '.$e->getMessage()."\n";
    echo $info;
  } 
The exception returns the following message: No response from server. Either a connection or configuration error. 
The username and password are correct and valid.

Logs: 

POST:  https://i.instagram.com/api/v1/accounts/login/
DATA: signed_body=38eddb96f300c2b1fefce424ccb1a4f448f569d755494bd2e454dce93ca1908d.{"phone_id":"70dccab2-b5d4-41b0-9049-34716a438b55","_csrftoken":null,"username":"may_user","adid":"88fa19aa-ae73-4b41-9744-bf04316fdca1","guid":"2bd0c3ba-a183-4d16-8ad3-07ab861899cf","device_id":"android-9f7470d224471b4f","password":"hear_my_pass","login_attempt_count":"0"}&ig_sig_key_version=4
← 500 	 25B
RESPONSE: Oops, an error occurred.

**Comment by JRoy** [comment]
Instagram and Facebook are experiencing worldwide outages right now, therefore I'm confident this isn't an api issue.

Regards.
