### ISSUE TITLE
Solving photo upload error

### ISSUE THREAD

**Issue by shokerplz** [mgp25/Instagram-API#3037]
# Photo upload issue solver

---

### Description
Lot's of people faced an issue when trying to post photo (may be this issue also exists when posting video and stories). API returns "Invalid request options" or Bad Request. From some time this issue became permanent for me. So if you are facing the same issue, I think I found a way to bypass it.
When we are trying to post photo with `$ig->timeline->uploadPhoto()` it calls `$this->ig->internal->uploadSinglePhoto()` and `uploadPhotoData()`. So our exception is rasing from `uploadPhotoData()`, when we are using `_uploadPhotoInOnePiece()` we are sending request to `upload/photo/` which is not working (for now at least), and the solution is to use `_uploadResumablePhoto()` which sends request to `https://i.instagram.com/rupload_igphoto/` which is perfectly working.

### Ready to use solution
I made an simple class that rewrites uploadPhotoData function, I think you can use it in your projects if you are facing the same issue. Btw it is temporary solution, I think there is much better way to solve this problem, but if you need to post photos from code you can go with that.
```
use InstagramAPI\Client;
use InstagramAPI\Constants;
use InstagramAPI\Request\Metadata\Internal as InternalMetadata;
use InstagramAPI\Utils;
date_default_timezone_set('UTC');
require __DIR__.'/vendor/autoload.php';
$username            = $argv[1];
$password            = $argv[2];
$photoFilename   = $argv[3];
$debug = true;
$truncatedDebug = false;
$captionText = implode(" " ,array_slice($argv, 4));
class ExtInternal extends \InstagramAPI\Request\Internal {
    public function uploadPhotoData(
        $targetFeed,
        InternalMetadata $internalMetadata)
    {
        if ($targetFeed === Constants::FEED_DIRECT) {
            throw new \InvalidArgumentException(sprintf('Bad target feed "%s".', $targetFeed));
        }
        if ($internalMetadata->getPhotoDetails() === null) {
            throw new \InvalidArgumentException('Photo details are missing from the internal metadata.');
        }
        try {
            $this->_uploadResumablePhoto($targetFeed, $internalMetadata);
        } catch (InstagramException $e) {
            throw $e;
        } catch (\Exception $e) {
            throw new UploadFailedException(
                sprintf(
                    'Upload of "%s" failed: %s',
                    $internalMetadata->getPhotoDetails()->getBasename(),
                    $e->getMessage()
                ),
                $e->getCode(),
                $e
            );
        }
    }
}
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
    $internal = new ExtInternal($ig);
} catch (\Exception $e) {
    echo 'LOGIN EXCEPTION: '.$e->getMessage()."\n";
    exit(0);
}
try {
    $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename);
    $internalMetadata = new InternalMetadata(Utils::generateUploadId(true));
    $targetFeed = Constants::FEED_TIMELINE;
    try {
        if ($internalMetadata->getPhotoDetails() === null) {
            $internalMetadata->setPhotoDetails($targetFeed, $photoFilename);
        }
    } catch (\Exception $e) {
        throw new \InvalidArgumentException(
            sprintf('Failed to get photo details: %s', $e->getMessage()),
            $e->getCode(),
            $e
        );
    }
    $internal->uploadPhotoData($targetFeed, $internalMetadata);
    $configure = $internal->configureSinglePhoto($targetFeed, $internalMetadata, ['caption' => $captionText]);
    return $configure;
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

**Comment by JRoy** [comment]
While we appreciate your effort to help the repository this is unfortunately not a proper fix for the issue. While it may work, I strongly advise not using this untill a proper fix is issued. Until this is done however, I suggest people who depend on this look at investing in the private code subscription (see #2655) where we've already fixed this issue and continue to place new features and constants updates before the public repo.

Cheers.
