### ISSUE TITLE
Does Exclude List work anymore with Location::FindPlacesNearby() ?

### ISSUE THREAD

**Issue by Jpark99** [mgp25/Instagram-API#3040]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

**When I run the paginateWithExclusion.php under the Example directory, I get Invalid rank token. When I get rid of the exclude list though, the error goes away, but obviously it would not be so efficient. Just to be clear, does exclude list still work in FindPlaces() or FindPlacesNearby() ?**  

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
try {
    // Let's list locations that match "milan".
    $query = 'milan';
    // Initialize the state.
    $rankToken = null;
    $excludeList = [];
    do {
        // Request the page.
        $response = $ig->location->findPlaces($query, $excludeList, $rankToken);
        // In this example we're simply printing the IDs of this page's items.
        foreach ($response->getItems() as $item) {
            $location = $item->getLocation();
            // Add the item ID to the exclusion list, to tell Instagram's server
            // to skip that item on the next pagination request.
            $excludeList[] = $location->getFacebookPlacesId();
            // Let's print some details about the item.
            printf("%s (%.3f, %.3f)\n", $item->getTitle(), $location->getLat(), $location->getLng());
        }
        // Now we must update the rankToken variable.
        $rankToken = $response->getRankToken();
        // Sleep for 5 seconds before requesting the next page. This is just an
        // example of an okay sleep time. It is very important that your scripts
        // always pause between requests that may run very rapidly, otherwise
        // Instagram will throttle you temporarily for abusing their API!
        echo "Sleeping for 5s...\n";
        sleep(5);
    } while ($response->getHasMore());
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
``` 

### Debug Log (Optional)
Please post your debug log in the section below; You can enable the debug log by using `new Instagram(true)` instead of `new Instagram()`:
```php
Something went wrong: "1575324414222|939d7fcca6cc01f2ec40e88d36002772d0a8055180ec21bfa10b29de8baa7a66" is not a valid rank token.
```

**Comment by JRoy** [comment]
They have been removed from the app correct. It will likely be removed from the API too shortly

**Comment by Jpark99** [comment]
Is there an alternative way to achieve the similar goal by any chance?

Thank you for your quick response.

**Comment by JRoy** [comment]
You could do it client side by looking through the list. Instagram isn't allowing searching or pagination of this request anymore basically
