### ISSUE TITLE
How to simply like a post

### ISSUE THREAD

**Issue by apyredev** [mgp25/Instagram-API#3044]
Hello, 

I've looked at a lot of examples but I can't seem to be able to do what I want: I simply need to like a media from a user, how can I do that?

`$response = $ig->timeline->getUserFeed($userId);
 $mediaId =$response[0]->getMedia();
$extraData = ['user_id' => $userId];
$ig->media->like($mediaId, $module, $extraData);`

This is what I could come up to, but It's worthless..
Thanks!

**Comment by JRoy** [comment]
Read the source code and make sure you're using the latest version of the api
