### ISSUE TITLE
Getting followerCount of my followers

### ISSUE THREAD

**Issue by brunopiaui** [mgp25/Instagram-API#3047]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
Please include a well-worded description of your question below; We will close your issue if we have to guess what you're talking about, please be as specific as possible:

Hi everyone,

1 - This code fetches a user's followers;
2 - Then takes the total followers of each follower;

Executing code without sleep returns a request limit error.

With sleep, the code executes perfectly, but it takes a long time. A user with 30,000 followers, for example, takes approximately 2 days to complete.

Is there a better way to perform this task without taking so much time ???

### Code (Optional)
Please post your code relevant to the question in the section below:
```php
<?php
set_time_limit(0);
date_default_timezone_set('UTC');
require __DIR__.'/vendor/autoload.php';

/////// CONFIG ///////
$debug = false;
$truncatedDebug = false;
//////////////////////

\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;

$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug, [
    'storage'    => 'file',
    'basefolder' => './',
]);

try {
  $ig->login('username', 'xxxx');
  $id = 6543769;
  $rankToken = \InstagramAPI\Signatures::generateUUID();
  $maxId = null;
  $num = 1;
  do {
    $followers = $ig->people->getFollowers($id, $rankToken, null, $maxId);
    foreach ($followers->getUsers() as $user) {
      sleep(5);
      $friend = $ig->people->getInfoById($user->getPk());
      $totalFollowers = $friend->getUser()->getFollowerCount();
      echo $num . ' - ' . $user->getFullName() . '  - Total followers: ' . $totalFollowers . "\n";
      $num++;
    }
    $maxId = $followers->getNextMaxId();
    sleep(5);
  } while ($maxId !== null);
} catch (\Exception $e) {
  echo 'Something went wrong: '.$e->getMessage()."\n";
  exit(0);
}
```

**Comment by JRoy** [comment]
You can reduce the sleep to 1 or 2 and still be safe but otherwise you're out of luck

**Comment by brunopiaui** [comment]
But would that be the right way to do it ?? Isn't there a method that returns a user's followers already with this total followers?

**Comment by brunopiaui** [comment]
> You can reduce the sleep to 1 or 2 and still be safe but otherwise you're out of luck

But would that be the right way to do it ?? Isn't there a method that returns a user's followers already with this total followers?

**Comment by JRoy** [comment]
Nope

**Comment by brunopiaui** [comment]
Ok, thanks..
