### ISSUE TITLE
Port configuration for Postgres/My SQL

### ISSUE THREAD

**Issue by e1sep0** [mgp25/Instagram-API#3055]
Hi, you`ve forgot about **dbport** in postgres connection in Factory(
![image](https://user-images.githubusercontent.com/5094299/70635966-d4fea200-1c45-11ea-953d-c940b53c68f5.png)
![image](https://user-images.githubusercontent.com/5094299/70636898-60c4fe00-1c47-11ea-906f-f07864f58c5b.png)

**Comment by fanatov37** [comment]
hm. I will check it and resolve

**Comment by JRoy** [comment]
Resolved in 8552c995476b804c56475922b8220799c7012b08 thanks to #3066 

Cheers!
