### ISSUE TITLE
Question abount notifications

### ISSUE THREAD

**Issue by stepan-neretin7** [mgp25/Instagram-API#3056]
# Question

When users comment on my publications, I receive a notification on my phone
Is it possible (not in real time) to receive these notifications and read them?

**Comment by JRoy** [comment]
See the [realtimeClient](https://github.com/mgp25/Instagram-API/blob/master/examples/realtimeClient.php) example.

Cheers.

**Comment by stepan-neretin7** [comment]
Sorry .. Apparently you misunderstood me
I do not want to receive real-time notifications
Only when I want to run the script mysel

**Comment by stepan-neretin7** [comment]
@JRoy May be some other way ?
