### ISSUE TITLE
Enhacements and features

### ISSUE THREAD

**Issue by mgp25** [mgp25/Instagram-API#307]
I open this issue to know which features do you want to see in the API and i'll be doing and adding them.

Regards

**To Do:**

- [x] Proxy support
- [x] Verify checkpoint
- [x] Facebook login (Not going to implement this)
- [x] Registration fix (to lazy to do this, just add the waterfall id, easy to do, just spent some time looking to the code)

**Comment by jpmoney5065** [comment]
I would love a way to send the verify email if I get a checkpoint! Thanks

**Comment by GuilhermeFM** [comment]
Login with a facebook account if possible.

**Comment by MaximMikulich** [comment]
1. send messages in Direct without photos
2. send photo in Direct
3. Send messages and photo in Direct

**Comment by polamoros** [comment]
Any type of rate limit control

**Comment by beshoo1** [comment]
if i search for a Tag , API will display all photos including photo i already like , comment
is there a way to filter out the already  (liked , commented) photo ?
Some one may say , you can loop over and discard (liked , commented) photo  , but this will cost time . so is there a way to discard already  (liked , commented) photo ?

**Comment by zarulizham** [comment]
Send messages in Direct without mediaid would be great :)

**Comment by mgp25** [comment]
I dont think ill ever implement messages in direct, too much spam

**Comment by mgp25** [comment]
Proxy suport added

**Comment by MaximMikulich** [comment]
@mgp25 You were talking about Proxy the same thing :)

**Comment by beshoo1** [comment]
@mgp25 how to use proxy support,  nothing in wiki about it

**Comment by mgp25** [comment]
See the commit and see the functions

**Comment by snapmaster** [comment]
How about to Verify checkpoint on my mobile phone function?

**Comment by doctorbinsibar** [comment]
RegistrationTool.php gets Captcha Challenge

Maybve possible to use deathbycaptcha api to solve the captchas ?!

> Array
(
    [0] => HTTP/1.1 400 Bad Request
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Accept-Language, Cookie
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Sat, 30 Jul 2016 14:37:52 GMT
Content-Type: application/json
Connection: keep-alive
Content-Length: 122


    [1] => Array
        (
            [status] => fail
            [lock] => 1
            [message] => checkpoint_required
            [checkpoint_url] => https://i.instagram.com/challenge/
        )

)

**Comment by snapmaster** [comment]
my profile was deleted because I could not enter my mobile phone when checkpoint_required appeared.. So vote for function to  pass checkpoint

**Comment by MrProrper** [comment]
I think if it have a Error Manager or Error Center or something like that to do a specific reaction on a specific error that Instagram returns, would be great. 
For example :
<pre><code>
$Errors = array(
	"not_allowed_aspect_ratio"=> "Uploaded image isn't in an allowed aspect ratio",
	"login_required" => "login_required",
	"checkpoint_required" => "login_required",
	"too_many_users_registered"=> "too many users have been registered on this device"
	// .
	// and other errors
	// .
	// .
	// .
	 );
if ($response == $Errors['not_allowed_aspect_ratio']) {
	// do something...
}else if($response == $Errors['login_required']){
	// do something else...
}
</pre></code>

**Comment by beshoo1** [comment]
i add +1 for checkpoint , kindly is there any ETA

**Comment by mgp25** [comment]
I dont need +1 post, if someone already told it, then there is no sense in repeat it, and if you read the first comment of mine, is already added.

There is no ETA, ill code eventually and when i have free time, it could be tomorrow or next year

Regards

**Comment by beshoo1** [comment]
Dear mgp25 , i like to thank you for your kindly replay , but please note i thought you need voting for that.  you can see some of user talked about checkpoint ! 
@snapmaster @jpmoney5065 @snapmaster , so that is why i thoughted you are looking for voting.

I am sorry if that bother you.

**Comment by fatgue** [comment]
Rate limit control would be a feature

**Comment by ascepanovic** [comment]
Ability to send private message to user and ability to read messages as well

**Comment by doctorbinsibar** [comment]
Please make possible to call URLS with Instagram Logged in. 
I want to confirm Emails with the Script.
Maybe Call_URL($url) 
And then the Registred Instagram Account is confirming email.

The Email I get from my Catchall Email Address, but i need a way to call this Email Address.

**Comment by doctorbinsibar** [comment]
A Phone Number Registration if its possible. That would be great :+1:

**Comment by polamoros** [comment]
Something with the New Instagram Stories (Snapchat copy).

**Comment by mands72** [comment]
Hi @mgp25,
would be nice if you could implement the new Stories feature (/api/v1/feed/reels_media/)
Tried to get it working by myself because it first seemed to be something easy but just gave up on it after getting always 403 Forbidden's back...

**Comment by ngandhy** [comment]
first, thanks @mgp25 for the library!

Feature Requests:
1) set location
2) user tags

thx!

**Comment by CaliAlec** [comment]
@mands72 I thought it would be straightforward as well. I looked at the request body which looks something like:

`1c2ab1b2ab131c33b13a12a2c122c1a33213cba2ab333a3cac112b.{
  "_csrftoken": "token",
  "_uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "_uid": "1234567",
  "user_ids": [
    "7654321"
  ]
}`

and I tried to generate the HMAC-SHA256 signature of the JSON using the updated key, but it doesn't match the hash that was sent in the request, so the server rejects it. Not sure how this request is any different than any of the other ones.

**Comment by ascepanovic** [comment]
Any chance that we can read whole thread in inbox ?
With current inbox function I get only last message of sender in thread.

**Comment by biohan** [comment]
Registration does not work. phone_id and guid always random

` [1] => Array                                                                                
     (                                                                                       
         [status] => ok                                                                      
         [errors] => Array                                                                   
             (                                                                               
                 [device_id] => Array                                                        
                     (                                                                       
                         [0] => Too many users have been registered on this device.          
                     )                                                                       
                                                                                             
             )                                                                               
                                                                                             
         [account_created] =>                                                                
     )                                                                                       `

**Comment by gergo2007** [comment]
Support for uploading landscape and portrait pictures please.

Thanks!

**Comment by mgp25** [comment]
@ngandhy that is done in the configure request, someone can capture it and add it easily
@gergo2007 that is easily to add it, use a proxy and capture the request

Not going to add any rate limit

@biohan thats the `device_id` you can always change it

@polamoros im not going to implement that feature, if someone wants to send a pull request, then perfect

**Comment by gergo2007** [comment]
@mgp25 can you please elaborate?

**Comment by mgp25** [comment]
@gergo2007 You can use a proxy to capture the request, then compare the request done in your device and the one done in the API, add the changes to the code, send a pull request and ill merge it

**Comment by gergo2007** [comment]
@mgp25 Oh ok, will do it soon! :) Thanks!

**Comment by beshoo1** [comment]
*Checkpoint.php* has no proxy connection function in the curl request .

**Comment by mgp25** [comment]
Im going to close this issue, if you want to add something, send a pull request and ill merge it

Regards
