### ISSUE TITLE
linkAddressBook() always return empty LinkAddressBookResponse

### ISSUE THREAD

**Issue by emanf** [mgp25/Instagram-API#3075]
first, thanks for your awesome work.

i just want to link new contacts and get info of my contacts but the function always returns empty.
`RESPONSE: {"items": [], "users": [], "status": "ok"}`

if you just create an account in instagram without syncing your contacts, you can't use linkAddressBook() and you will get error.(yes, i tested it with calling unlinkAddressBook() first)

is there someway to get only my contacts IG informations?

**Comment by JRoy** [comment]
I believe Instagram shut down this endpoint due to media pushback after it was reported that is was possible to find millions of Instagram accounts with this endpoint. Anyways, it's nothing we can fix

Cheers.

**Comment by emanf** [comment]
ok that's make sense, but how to sync contacts? so i can see my contacts in discover area after, i use instagram and sync my contacts and see ppl but when i use linkAddressBook() nothing happen.

**Comment by JRoy** [comment]
Instagram made it so there was no way to do this as of now.

**Comment by emanf** [comment]
so why sync contacts works on app but not in this script? did they change any parameter or something? does sync contacts work in your premium script?

**Comment by JRoy** [comment]
I do believe it has been fixed in the premium api.
