### ISSUE TITLE
IOS, Android Versioning and Signature Key Correlation

### ISSUE THREAD

**Issue by denizaydemir** [mgp25/Instagram-API#3078]
I don't have any questions about extracting endpoints or signature keys. I wondered the correlation among Instagram API, Android, IOS versioning and signature keys(v4). 
(114.0.0.38.120 or any other version number is used only for demonstration purposes)

**1.** Assume that a new version of Android app released, let's say 114.0.0.38.120, also IOS version of app released(Android, IOS updates simultaneously). Will the IOS version also have the version code same as Android (114.0.0.38.120)? We know that IOS version code definitely starts with 114.0

**2.** Considering the previously given conditions, new signature key(s?) also generated. Then which of the following hapens:
	

- **2.1.** New signature keys generated for each platform(IOS, Android), both of these keys are unique.

	

- **2.2.** A new API signature key generated for the version 114.0.0.38.120, both platforms uses the same key.

	
**3.** Having signature key Android 114.0.0.38.120, which of the following assumptions are true:
(Knowing that User-Agent: "Instagram 114.0.0.38.120 Android (23/6.0; 515dpi; 1440x2416; huawei/google; Nexus 6P; angler; angler; en_US)" definitely works)
	

- **3.1.** Signed requests having User-Agent: "Instagram 114.0.0.38.120 (iPhone8,1; iOS 11_4; en_US; en_US; scale=2.00; gamut=normal; 750x1334) AppleWebKit/420+" will be accepted by API.

	

- **3.2.** Signed requests having User-Agent: "Instagram 76.0.0.15.395 Android (23/6.0; 515dpi; 1440x2416; huawei/google; Nexus 6P; angler; angler; en_US)" will be accepted by API.

	

- **3.3.** Signed requests having User-Agent: "Instagram 50.0.0.52.188 (iPhone8,1; iOS 11_4; en_US; en_US; scale=2.00; gamut=normal; 750x1334) AppleWebKit/420+" will be accepted by API.

**Comment by JRoy** [comment]
Thanks for your question, let me try and answer is for you:

1. Yes the two apps generally have synced version names (114.0) but their version codes (126373) can tend to go out of sync.
2. A different signature key is generated for each platform
3. I don't really know what you mean by this question but you need to use an iPhone's user agent if you were emulating the iOS API

Speaking of the iOS API however, if that's something that interests you, we have added that in the private api subscription! Learn more here: #2655

**Comment by denizaydemir** [comment]
Actually my 3. question is crucial. Let me explain in depth:
Some POST requests require signed body with the signature key as everyone here knows. I always matched the User-Agent Instagram version with the Android app version of the signature key extracted.
See:
"Instagram **114.0.0.38.120** Android (23/6.0; 515dpi; 1440x2416; huawei/google; Nexus 6P; angler; angler; en_US)"
IG_SIG_KEY: cee21c6e65240ce3a7f414a171fa1d0f04f6eb68e062e76c3b3935cXXXXXXXXX

However, I wondered what happens if we use a different User-Agent Instagram version? Additionally, what happens when changing User-Agent to iOS and using the same signature key? Will the Instagram API reject these requests?

**Comment by mgp25** [comment]
@denizaydemir signature is based on the apk (build version), and UA is built using device data, signature should be the same if you use the same apk file. If you use a different UA version it won't work.

> Additionally, what happens when changing User-Agent to iOS and using the same signature key? Will the Instagram API reject these requests?

While the request is sent and you got a response, this is totally wrong and will make it easily to have restrictions. iOS and Android signatures are different, and by different I mean the signature key.
