### ISSUE TITLE
Request\Direct::getInbox returns empty response since 7.0.0

### ISSUE THREAD

**Issue by EligiusSantori** [mgp25/Instagram-API#3079]
# Bug Report
Cannot receive direct messages since v7.0.0 till dev-master (c095702ce3661cf61a9560798f013cac7db28ce3).

### Description
Tried 3 different pages. Tried API storage clearing.
RTC isn't working also.

### Code
```php
$api = app(\InstagramAPI\Instagram::class);
$api->login('...', '...');
dump($api->direct->getInbox()->asArray());
``` 
```
=> [
     "pending_requests_total" => 0,
     "has_pending_top_requests" => false,
     "status" => "ok",
   ]
```

**Comment by JRoy** [comment]
You keep the cursorId null but make the limit 20. So your code would be changed to:
```php
$api = app(\InstagramAPI\Instagram::class);
$api->login('...', '...');
dump($api->direct->getInbox(null, 20)->asArray());
```

Regards.
