### ISSUE TITLE
data settings problem

### ISSUE THREAD

**Issue by jpmoney5065** [mgp25/Instagram-API#308]
After clearing data folder and running:

```
$i = new \InstagramAPI\Instagram($user1, $pass1);
$i->login();
echo $i->username_id;        // 1st run displays id from user1, 2nd run displays id form user2 

$i->setUser($user2,$pass2);
echo $i->username_id;        // 1st run displays id from user1, 2nd run displays id form user2 

$i->login();
echo $i->username_id;        //1st run displays id from user2, 2nd run displays id form user2 
```

data structure looks like this:

> data/user1/settings-user1.dat
> data/user1/user1-cookies.dat
> data/user1/user2-cookies.dat

Where username_id inside settings-user1.dat has the value of user2's id

Is it intended that you must run a new instance for every user before you can use setUser()?

**Comment by jpmoney5065** [comment]
Even with the correct data structure set up first

> data/user1/settings-user1.dat
> data/user1/user1-cookies.dat
> 
> data/user2/settings-user2.dat
> data/user2/user2-cookies.dat

I get the same results; a user2-cookies.dat inside the user1 folder and settings-user1.dat having an incorrect value for username_id

**Comment by mgp25** [comment]
@jpmoney5065 ill add a fix tomorrow night or saturday

**Comment by mgp25** [comment]
@jpmoney5065 check it, it should work now
