### ISSUE TITLE
The settings key "public_key" is not a valid persistent key name.

### ISSUE THREAD

**Issue by ssdbroker** [mgp25/Instagram-API#3091]
[_response:InstagramAPI\Exception\InstagramException:private] => 
    [message:protected] => The settings key "public_key" is not a valid persistent key name.
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => C:\xampp\htdocs\tests\vendor\mgp25\instagram-php\src\Settings\StorageHandler.php
    [line:protected] => 395

**Comment by mgp25** [comment]
@ssdbroker Fixed in https://github.com/mgp25/Instagram-API/commit/c8b18ee61a7537da59eeebea5dfa44cbebf6c3f4
