### ISSUE TITLE
PHP Fatal error when run "php pushReceiver.php"

### ISSUE THREAD

**Issue by cong88nv** [mgp25/Instagram-API#3098]
php .\pushReceiver.php
PHP Fatal error:  Declaration of Fbns\Client\Lite\StreamParser::onError($callback) must be compatible with BinSoul\Net\Mqtt\StreamParser::onError(callable $callback): void in C:\xampp 7.4 htdco\htdocs\instagram private api new\vendor\valga\fbns-react\src\Lite\StreamParser.php on line 23

i'm using PHP in XAMP 7.1 , window 10 latest please fix. thank u

**Comment by JRoy** [comment]
Use the latest dev-master

**Comment by cong88nv** [comment]
i curent use lastest dev-master
