### ISSUE TITLE
Paginating getUserFollowers

### ISSUE THREAD

**Issue by FFServices** [mgp25/Instagram-API#31]
Hi there,

Can somebody tell me, how to pass next_max_id to the query?
If the list is larger than 200 user, only the first 200 will be listed at once, and I want to get the full list.

**Comment by mgp25** [comment]
@FFServices get a proxy, capture the request, send it to me, and ill implement it.

Right now im busy, but if you prefer to wait, i'll look at it by the end of the month, or you can send me the request.

Regards

**Comment by mgp25** [comment]
PR merged. https://github.com/mgp25/Instagram-API/commit/34829a338a0d0af04108663a02f5e27f4eb659f3

Regards
