### ISSUE TITLE
getInfoByName($user) return Null when user start with "#" character

### ISSUE THREAD

**Issue by Amin-Hosseini** [mgp25/Instagram-API#3109]
# Bug Report

### Description
If user start with "#" character, getInfoByName($user) return Null and don't throw any Exception.

### Code
```php
$user = "#abc"
$info = $ig->people->getInfoByName($user)->getUser();
dump($info);
// null
``` 

### Debug Log
```php
null
```

**Comment by mgp25** [comment]
There is no user with `#`.

**Comment by Amin-Hosseini** [comment]
Yes, but I checked with another character like "! @ $ %" and throw Exception.
Thank you anyway.
