### ISSUE TITLE
ThrottledException on getLikers method

### ISSUE THREAD

**Issue by o-sys** [mgp25/Instagram-API#3110]
# Bug Report

---

### Notes:
We will close your issue, sometimes without answering, if any of the following are met:
* You have not included your code or your debug log
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your issue:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar issues including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
This problem appeared a few hours ago. Profiles that were repeatedly collecting likes and comments started to throw ThrottledException after attempt to get likers. I try to wait for some hours to repeat later, but the result is the same.
Everything was fine for weeks before. Likes via a website are not hidden. If I add a new profile, it collects likes finely (not sure if they won't be throttled soon).
Are there any known limits for calling getLikers method?

### Code
Please post your code relevant to the bug in the section below:
```php
        try {
            $likers = $this->ig->media->getLikers($post->media_id);
            if ($likers != null) {
                foreach ($likers->getUsers() as $h) {
                        // save user name
                         // save like
                    }
                }
            }
        // triggered if the post was removed
        } catch (\InstagramAPI\Exception\BadRequestException $e) {
        } finally {
            // process exception
        }
``` 

### Debug Log
```php
[stacktrace]
#0 /var/www/insta-it/vendor/mgp25/instagram-php/src/Client.php(737): InstagramAPI\\Client->_guzzleRequest(Object(GuzzleHttp\\Psr7\\Request), Array)
#1 /var/www/insta-it/vendor/mgp25/instagram-php/src/Client.php(805): InstagramAPI\\Client->_apiRequest(Object(GuzzleHttp\\Psr7\\Request), Array, Array)
#2 /var/www/insta-it/vendor/mgp25/instagram-php/src/Request.php(754): InstagramAPI\\Client->api(Object(GuzzleHttp\\Psr7\\Request), Array)
#3 /var/www/insta-it/vendor/mgp25/instagram-php/src/Request.php(775): InstagramAPI\\Request->getHttpResponse()
#4 /var/www/insta-it/vendor/mgp25/instagram-php/src/Request.php(831): InstagramAPI\\Request->getRawResponse()
#5 /var/www/insta-it/vendor/mgp25/instagram-php/src/Request/Media.php(242): InstagramAPI\\Request->getResponse(Object(InstagramAPI\\Response\\MediaLikersResponse))
#6 /var/www/insta-it/app/Models/CronModels/Instagram.php(263): InstagramAPI\\Request\\Media->getLikers('222533793124468...')
#7 /var/www/insta-it/app/Models/CronModels/Instagram.php(245): App\\Models\\CronModels\\Instagram->loadLikes(Object(App\\Models\\Post))
#8 /var/www/insta-it/app/Models/CronModels/Instagram.php(195): App\\Models\\CronModels\\Instagram->loadPage(Object(InstagramAPI\\Response\\UserFeedResponse))
#9 /var/www/insta-it/app/Models/CronModels/Instagram.php(131): App\\Models\\CronModels\\Instagram->loadProfile()
#10 /var/www/insta-it/app/Jobs/ProcessAccount.php(146): App\\Models\\CronModels\\Instagram->process()
```

**Comment by pavlovskiycode** [comment]
+ 1

**Comment by mgp25** [comment]
Not a bug, you just exceeded Instagram's request limits.
