### ISSUE TITLE
i have this eror You must have FFmpeg to process videos.

### ISSUE THREAD

**Issue by immiri** [mgp25/Instagram-API#3112]
Something went wrong: You must have FFmpeg to process videos. Ensure that its binary-folder exists in your PATH environment variable, or manually set its full path via "\InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/home/exampleuser/ffmpeg/bin/ffmpeg';" at the start of your script.

what i should to do

---

**Comment by mgp25** [comment]
Exatly this: 

`Ensure that its binary-folder exists in your PATH environment variable, or manually set its full path via "\InstagramAPI\Media\Video\FFmpeg::$defaultBinary = '/home/exampleuser/ffmpeg/bin/ffmpeg';" at the start of your script.`

Regards

**Comment by immiri** [comment]
i have ffmpeg but not work   can you tell me wher i can change default dir  and then can i fid the correct place      sorry   im nob  and i need stream on instagram     and my mother language is not english
