### ISSUE TITLE
Dot in username

### ISSUE THREAD

**Issue by amirpdlll** [mgp25/Instagram-API#3113]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description

When I insert usernames that contain dot (.) like test.com I will face error below :
"The username you entered doesn't appear to belong to an account. Please check your username and try again."

but username is correct so what's the problem ?

### Code (Optional)
Please post your code relevant to the question in the section below:
```php

$username = 'example.com';
$password = '*******';
$debug = false;
$truncatedDebug = false;

//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
$loop = \React\EventLoop\Factory::create();
if ($debug) {
    $logger = new \Monolog\Logger('rtc');
    $logger->pushHandler(new \Monolog\Handler\StreamHandler('php://stdout', \Monolog\Logger::INFO));
} else {
    $logger = null;
}
$rtc = new \InstagramAPI\Realtime($ig, $loop, $logger);
``` 

### Debug Log (Optional)

```php
← 400    165B
RESPONSE: {"message": "The username you entered doesn't appear to belong to an account. Please check your username and try again.", "status": "fail", "error_type": "ip_block"}

Something went wrong: InstagramAPI\Response\LoginResponse: The username you entered doesn't appear to belong to an account. Please check your username and try again.

```

**Comment by mgp25** [comment]
Please, whenever you open a new issue, post enough details (debug log, code and so) otherwise we will consider this issue as invalid

**Comment by amirpdlll** [comment]
> Please, whenever you open a new issue, post enough details (debug log, code and so) otherwise we will consider this issue as invalid

I'm sorry , now I have updated my question, my problem is when I want to login with a username that there is dot (.) in it , I face that error , what can I do ?

thanks

**Comment by mgp25** [comment]
User `example.com` doesn't exists. 

Regards

**Comment by amirpdlll** [comment]
> User `example.com` doesn't exists.
> 
> Regards

example.com was just an example , try this one ketabjour.ir this username exist but I face error

**Comment by mgp25** [comment]
Try a simple login and try again, post debug log, however, from the IG response you can see:

```json
"error_type": "ip_block"
```

**Comment by amirpdlll** [comment]
this is error log image

**Comment by amirpdlll** [comment]
> Try a simple login and try again, post debug log, however, from the IG response you can see:
> 
> ```json
> "error_type": "ip_block"
> ```

in error log I can see "error_type": "ip_block" , so now what is wrong ? how can I fi it ? 
thanks

**Comment by amirpdlll** [comment]
this is error log

> 
> POST:  https://i.instagram.com/api/v1/accounts/login/
> DATA: signed_body=****.{"country_codes":"[{\"country_code\":\"1\",\"source\":[\"default\",\"sim\"]}]","phone_id":"****","_csrftoken":"*****","username":"ketabjour.ir","adid":"****","guid":"*****","device_id":"android-***","google_tokens":"[]","password":"***","login_attempt_count":"0"}&ig_sig_key_version=*
> ← 400    165B
> RESPONSE: {"message": "The username you entered doesn't appear to belong to an account. Please check your username and try again.", "status": "fail", "error_type": "ip_block"}

There is "error_type": "ip_block" , so now what can I do to fix? 
thanks

**Comment by amirpdlll** [comment]
why ip_block happened? and how can I prevent it to happen ?

**Comment by amirpdlll** [comment]
there is no help ?
