### ISSUE TITLE
Using two factor login on different pages

### ISSUE THREAD

**Issue by amirpdlll** [mgp25/Instagram-API#3116]
# Question

---

### Notes:
We will close your question, sometimes without answering, if any of the following are met:
* You have not included context about your question
* You are asking about `challenge_required`, `checkpoint_required`, `feedback_required` or `sentry_block`. They've already been answered in the Wiki and *countless* closed tickets in the past!
* You have used the wrong issue template
* You are posting screenshots, which are too painful to help you with 

Please make sure you have done the following before submitting your question:
* You have [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bug-tracker for similar questions including **closed** ones
* You have [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
* You have [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
* You have [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
* You have [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
* You are [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

---

### Description
I want to login using two factor authorization but I want to send SMS (code ) in one page and the other page should continue login to instagram, so I grab $twoFactorIdentifier and $verificationCode and insert it to second page but I see error 

`PHP Fatal error:  Uncaught Error: Call to undefined method InstagramAPI\Instagram::twoFactorLogin() in /home/ahpit/inst2/php/test5.php:42`

### Code (Optional)
First page to send SMS (code)
```php
    $loginResponse = $ig->login($username, $password);

    if (!is_null($loginResponse) && $loginResponse->getTwoFactorRequired()) {
        $twoFactorIdentifier = $loginResponse->getTwoFactorInfo()->getTwoFactorIdentifier();

        // I added this line so i could write in the code in CLI.
        // You can replace this line with the logic you want.
        // Verification code will be received via SMS.
        print" \n identifire : $twoFactorIdentifier \n";
       // $verificationCode = trim(fgets(STDIN));

       // $ig->twoFactorLogin($verificationCode, $twoFactorIdentifier);
    }
``` 

Second page for just login
```php
       $loginResponse = $ig->login($username, $password);
        $twoFactorIdentifier='******';
        $verificationCode='*****';
        $ig->twoFactorLogin($verificationCode, $twoFactorIdentifier);
``` 

### Debug Log (Optional)

```php

PHP Fatal error:  Uncaught Error: Call to undefined method InstagramAPI\Instagram::twoFactorLogin() in /home/ahpit/inst2/php/test5.php
```

**Comment by mgp25** [comment]
Please, search before opening a new issue: https://github.com/mgp25/Instagram-API/blob/master/examples/twoFactorLogin.php

Next time issue will ne closed directly.

Regards
