### ISSUE TITLE
use new Arrays

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#312]
Hello,
how to use this kind of arrays ? 
I want to safe the media ID but cant use them as array 

> InstagramAPI\ConfigureResponse Object
(
    [upload_id:protected] => 1469902012363
    [media_id:protected] => 1305955259525132925_3265658963
    [image_url:protected] => http://scontent.cdninstagram.com/t51.2885-15/e35/13736909_1250847814947743_1636039636_n.jpg?ig_cache_key=MTMwNTk1NTI1OTUyNTEzMjkyNQ%3D%3D.2
    [status:protected] => ok
    [message:protected] => 
)

**The Error Text**
Fatal error: Cannot use object of type InstagramAPI\ConfigureResponse as array in

**Comment by mgp25** [comment]
Check this: https://github.com/mgp25/Instagram-API/blob/master/src/http/Response/ConfigureResponse.php

It's an object, you can call: `->getUploadId()` ... check file for more functions

Regards

**Comment by mustafababil** [comment]
I cannot utilize returned ConfigureResponse object.

```
function uploadImage($imgPath, $caption){
  //Logins the insta
  $this->i->login();    
  
  //Upload the image and get ConfigureResponse Object
  $uploadResult = $this->i->uploadPhoto($imgPath, $caption);    
  
  //Get the media_id of uploaded image
  return $uploadResult->getMediaId();
}
```

I saw following

> Method 'getMediaId' not found in class array


My full wrapper class is here.
http://pastebin.com/tj9yV18m

**Comment by mgp25** [comment]
@mustafababil https://github.com/mgp25/Instagram-API/blob/master/src/http/Response/ConfigureResponse.php

+ make sure you have latest code
