### ISSUE TITLE
setUser() still not working properly and other data issues

### ISSUE THREAD

**Issue by jpmoney5065** [mgp25/Instagram-API#315]
The same problem remains with setUser and login()

IGDataPath does not change when you use setUser()

So you are checking:
`file_exists($this->IGDataPath."$this->username-cookies.dat")`
so..

> /data/USER-1-PATH/USER-2-coockies.dat

Where IGDataPath is still the data path for the user you started the instance with, not the user use switched to.

Also the http request uses the the IGDataPath to make a cookie file which is in the wrong user folder

and inside of login() there is this line:
`$this->settings->set('username_id', $this->username_id);`
which uses the incorrect IGDataPath again

**Comment by mgp25** [comment]
You can also test and send a pull request if you find something

Regards
