### ISSUE TITLE
How do you get signature key and user agent?

### ISSUE THREAD

**Issue by fragiledream** [mgp25/Instagram-API#316]
Can you please tell me how you get the signature key and user agents? I would like to use my own private constants since the current ones are constantly showing "too many accounts registered using this device".

**Comment by mgp25** [comment]
Thats because of the device id, not IG signature. Explained in the wiki btw

Regards

**Comment by fragiledream** [comment]
Could you please tell me how to solve this issue? I couldn't find answers on the wiki.

**Comment by mgp25** [comment]
Change the device id

**Comment by fragiledream** [comment]
I mean should I generate a random device ID?

**Comment by derjrjr** [comment]
The device ID consists of "android-" and a string with 16 characters and digits.
For example: android-TJVAM2NU764BYED3, android-IXO6JGB94K81UFDN, android-OFZ29UBCSVIQNGHK.

I am not much of a developer in .NET but I generated them with a PHP script and tested them with an account and they worked fine with no errors. Here is the PHP script:
`
<?php
function generateID($length = 16) {
    return substr(str_shuffle(str_repeat($x='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil($length/strlen($x)) )),1,$length);
}

echo  "android-".generateID(); 
?>

`
This code randomly selects 16 letters/numbers from the input and adds the "android-" part where the ID is being displayed (echo), please note the letters must be CAPITAL !

Hope this helped :)
