### ISSUE TITLE
How do I output all usernames that posted using a specified hashtag?

### ISSUE THREAD

**Issue by ConstantinSchreiber** [mgp25/Instagram-API#319]
I wrote a web app that outputs n usernames that posted using a specific hashtag. It accesses the public_content scope of the "official" Instagram API. Since they restricted access to sandbox mode in november last year it doesn't work anymore.

Is it possible to do the same thing using this API? If so I would be grateful for any hints to the right direction.

**Comment by mgp25** [comment]
Yes, it is possible, you can get all function from here: https://github.com/mgp25/Instagram-API/wiki

Regards
