### ISSUE TITLE
I have some errors

### ISSUE THREAD

**Issue by honeydewkorea** [mgp25/Instagram-API#321]
I installed root directory of my website by composer.
And i have written some code.

Such as, 

```
<?php

include '../vendor/autoload.php';
require '../vendor/mgp25/instagram-php/src/Instagram.php';

/////// CONFIG ///////
$username = 'honeydewkorea';
$password = 'Blah~~~';
$debug = true;

$photo = 'http://mydomain/image/logo.png';     // path to the photo
$caption = 'null';     // caption
//////////////////////

$i = new \InstagramAPI\Instagram($username, $password, $debug);

try {
    $i->login(true);
} catch (Exception $e) {
    $e->getMessage();
    exit();
}

try {
    $i->uploadPhoto($photo, $caption);
} catch (Exception $e) {
    echo $e->getMessage();
}
```
But, it has some errors, such as "msg:login_required" and 'doesn't upload function'.

This is my full return code:

> `REQUEST: si/fetch_headers/?challenge_type=signup&guid=c679665670064f4a988e78dff974fd45 RESPONSE: {"status": "ok"} REQUEST: accounts/login/ DATA: ig_sig_key_version=4&signed_body=ba09500980717f289eedd1de87e8336c1116b005d38cc0b4a6e156b027dadeed.{"phone_id":"37823cc0-3db8-41dc-87a5-05e3539a5eb6","_csrftoken":"Set-Cookie: csrftoken=Q5FKiFqUFbvbBIhrBaFkaLj5RjwdvcqI","username":"honeydewkorea","guid":"7f66e0ac-32d4-4779-a208-8bc4bce17bac","device_id":"android-4052bd29d84f0768","password":"Blah~~~","login_attempt_count":"0"} RESPONSE: {"logged_in_user": {"username": "honeydewkorea", "has_anonymous_profile_picture": true, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "(\uc8fc)\ud5c8\ub2c8\ub4c0", "pk": 3580741174, "is_private": false}, "status": "ok"} REQUEST: qe/sync/ DATA: ig_sig_key_version=4&signed_body=b6719cbc2c7d53fcf7d939bb4264e0119f17b2a615023bb7ffaf141ef420d48c.{"_uuid":"7f66e0ac-32d4-4779-a208-8bc4bce17bac","_uid":3580741174,"id":3580741174,"_csrftoken":"DM4aWprF6BiLiGXTyzSgmhVsxZckD7s8","experiments":"ig_android_progressive_jpeg,ig_creation_growth_holdout,ig_android_report_and_hide,ig_android_new_browser,ig_android_enable_share_to_whatsapp,ig_android_direct_drawing_in_quick_cam_universe,ig_android_huawei_app_badging,ig_android_universe_video_production,ig_android_asus_app_badging,ig_android_direct_plus_button,ig_android_ads_heatmap_overlay_universe,ig_android_http_stack_experiment_2016,ig_android_infinite_scrolling,ig_fbns_blocked,ig_android_white_out_universe,ig_android_full_people_card_in_user_list,ig_android_post_auto_retry_v7_21,ig_fbns_push,ig_android_feed_pill,ig_android_profile_link_iab,ig_explore_v3_us_holdout,ig_android_histogram_reporter,ig_android_anrwatchdog,ig_android_search_client_matching,ig_android_high_res_upload_2,ig_android_new_browser_pre_kitkat,ig_android_2fac,ig_android_grid_video_icon,ig_android_white_camera_universe,ig_android_disable_chroma_subsampling,ig_android_share_spinner,ig_android_explore_people_feed_icon,ig_explore_v3_android_universe,ig_android_media_favorites,ig_android_nux_holdout,ig_android_search_null_state,ig_android_react_native_notification_setting,ig_android_ads_indicator_change_universe,ig_android_video_loading_behavior,ig_android_black_camera_tab,liger_instagram_android_univ,ig_explore_v3_internal,ig_android_direct_emoji_picker,ig_android_prefetch_explore_delay_time,ig_android_business_insights_qe,ig_android_direct_media_size,ig_android_enable_client_share,ig_android_promoted_posts,ig_android_app_badging_holdout,ig_android_ads_cta_universe,ig_android_mini_inbox_2,ig_android_feed_reshare_button_nux,ig_android_boomerang_feed_attribution,ig_android_fbinvite_qe,ig_fbns_shared,ig_android_direct_full_width_media,ig_android_hscroll_profile_chaining,ig_android_feed_unit_footer,ig_android_media_tighten_space,ig_android_private_follow_request,ig_android_inline_gallery_backoff_hours_universe,ig_android_direct_thread_ui_rewrite,ig_android_rendering_controls,ig_android_ads_full_width_cta_universe,ig_video_max_duration_qe_preuniverse,ig_android_prefetch_explore_expire_time,ig_timestamp_public_test,ig_android_profile,ig_android_dv2_consistent_http_realtime_response,ig_android_enable_share_to_messenger,ig_explore_v3,ig_ranking_following,ig_android_pending_request_search_bar,ig_android_feed_ufi_redesign,ig_android_video_pause_logging_fix,ig_android_default_folder_to_camera,ig_android_video_stitching_7_23,ig_android_profanity_filter,ig_android_business_profile_qe,ig_android_search,ig_android_boomerang_entry,ig_android_inline_gallery_universe,ig_android_ads_overlay_design_universe,ig_android_options_app_invite,ig_android_view_count_decouple_likes_universe,ig_android_periodic_analytics_upload_v2,ig_android_feed_unit_hscroll_auto_advance,ig_peek_profile_photo_universe,ig_android_ads_holdout_universe,ig_android_prefetch_explore,ig_android_direct_bubble_icon,ig_video_use_sve_universe,ig_android_inline_gallery_no_backoff_on_launch_universe,ig_android_image_cache_multi_queue,ig_android_camera_nux,ig_android_immersive_viewer,ig_android_dense_feed_unit_cards,ig_android_sqlite_dev,ig_android_exoplayer,ig_android_add_to_last_post,ig_android_direct_public_threads,ig_android_prefetch_venue_in_composer,ig_android_bigger_share_button,ig_android_dv2_realtime_private_share,ig_android_non_square_first,ig_android_video_interleaved_v2,ig_android_follow_search_bar,ig_android_last_edits,ig_android_video_download_logging,ig_android_ads_loop_count_universe,ig_android_swipeable_filters_blacklist,ig_android_boomerang_layout_white_out_universe,ig_android_ads_carousel_multi_row_universe,ig_android_mentions_invite_v2,ig_android_direct_mention_qe,ig_android_following_follower_social_context"} RESPONSE: {"ig_android_report_and_hide": {"is_enabled": "enabled"}, "status": "ok", "ig_android_boomerang_entry": {"is_enabled": "enabled"}, "ig_android_ads_loop_count_universe": {"is_enabled": "1"}, "ig_timestamp_public_test": {"is_seamless_holdout": "false", "behavior": "test", "timestamp_style": "text_row_under", "is_feed_ui_holdout": "false", "experiment_flavor": "timestamp_below_comments_with_explore_attribution"}, "ig_android_histogram_reporter": {"report_rate": "1"}, "ig_android_prefetch_explore_delay_time": {"delay_time_ms": "1000"}, "ig_android_ads_cta_universe": {"cta_in_profile": "1", "overlay_on_like": "1"}, "ig_android_boomerang_layout_white_out_universe": {"is_enabled": "true"}, "ig_android_inline_gallery_backoff_hours_universe": {}, "ig_android_video_loading_behavior": {"longer_video_timer": "1"}, "ig_android_video_stitching_7_23": {"stitching_ads": "enabled", "stitching_all": "enabled"}, "ig_android_periodic_analytics_upload_v2": {"is_enabled": "1", "upload_interval_seconds": "120"}, "ig_android_enable_client_share": {"is_enabled": "0"}, "ig_android_disable_chroma_subsampling": {}, "ig_android_ads_holdout_universe": {"behavior": "test"}, "ig_android_non_square_first": {"is_non_square": "enabled"}, "ig_android_profile": {"follow_button_in_single_media": "true"}, "ig_android_anrwatchdog": {"is_enabled": "1"}, "ig_android_ads_overlay_design_universe": {"design": "3"}, "ig_android_progressive_jpeg": {"feed": "enabled", "min_scan": "0", "peek_media": "enabled"}, "ig_video_use_sve_universe": {"is_enabled": "enabled"}, "ig_android_react_native_notification_setting": {"is_enabled": "enabled"}, "ig_ranking_following": {"followers_list_should_rank_all": "true", "followers_list_use_model": "true", "search_request_params": "{\"ranking_experiment_name\":\"nullstate_model\"}"}, "ig_android_video_download_logging": {"is_enabled": "enabled"}, "ig_android_post_auto_retry_v7_21": {"auto_retry_fast": "false", "auto_retry_mode": "last"}, "ig_android_ads_full_width_cta_universe": {"full_width": "1", "enable_overlay": "1", "move_indicator": "1"}, "ig_android_app_badging_holdout": {"behavior": "pass"}, "ig_android_infinite_scrolling": {"is_enabled": "enabled", "num_results": "20"}, "ig_android_high_res_upload_2": {"size_small": "200", "quality_large": "70", "size_large": "1080", "quality_small": "95"}, "ig_android_options_app_invite": {"is_enabled": "0"}, "ig_android_inline_gallery_no_backoff_on_launch_universe": {"ig_android_inline_gallery_no_backoff_on_launch": "disabled"}, "ig_android_new_browser": {"is_enabled": "enabled"}, "ig_fbns_push": {"is_enabled": "enabled", "user_present": "enabled", "boot": "enabled", "network": "enabled", "svc_ping": "disabled"}, "ig_android_direct_mention_qe": {"is_enabled": "1", "active_dismisser_min_action_count": "5", "active_dismisser_ratio": "3"}, "ig_creation_growth_holdout": {"behavior": "pass"}, "ig_android_mentions_invite_v2": {"is_enabled": "0"}, "ig_android_feed_unit_footer": {"feed_unit_footer": "0"}, "ig_android_prefetch_venue_in_composer": {"is_enabled": "enabled"}, "ig_android_camera_nux": {"camera_nux": "1"}, "ig_android_direct_plus_button": {"is_enabled": "0"}, "ig_android_inline_gallery_universe": {"ig_android_inline_gallery_enabled": "enabled"}, "ig_android_feed_reshare_button_nux": {"is_enabled": "1", "minimum_nux_reshow_interval_seconds": "43200", "maximum_nux_quota": "3"}, "ig_android_boomerang_feed_attribution": {"is_enabled": "enabled"}, "ig_android_prefetch_explore_expire_time": {"expire_time_in_min": "180"}, "ig_android_feed_unit_hscroll_auto_advance": {"auto_advance": "0"}, "ig_android_enable_share_to_messenger": {"is_enabled": "1"}, "ig_android_search_null_state": {"number_of_search_history_item": "3", "experiment_flavor": "search_null_state_with_hide_item"}, "ig_android_universe_video_production": {"upload_per_pixel_bit_rate_16by9": "9.7222", "upload_width_max_low": "540", "upload_width_max_mid": "640", "screen_width_low": "500", "total_memory_low": "520", "upload_per_pixel_bit_rate_9by16": "7", "cpu_cores_low": "1", "upload_per_pixel_bit_rate_square": "7", "total_memory_mid": "1000", "cpu_cores_mid": "1", "upload_width_max_high": "720", "screen_width_mid": "700", "upload_width_min": "480"}, "ig_android_new_browser_pre_kitkat": {"is_enabled": "enabled"}, "ig_android_rendering_controls": {}, "ig_android_hscroll_profile_chaining": {"is_enabled": "1", "auto_advance": "1"}, "ig_android_full_people_card_in_user_list": {"is_enabled": "disabled"}, "ig_video_max_duration_qe_preuniverse": {"max_duration_sec": "60"}, "ig_android_prefetch_explore": {"use_prefetch_cache": "true", "experiment_flavor": "prefetch_explore_with_delay", "disable_prefetch": "false"}, "ig_android_profile_link_iab": {}, "ig_android_huawei_app_badging": {"is_enabled": "1"}, "ig_android_media_favorites": {"is_enabled": "1"}, "ig_android_business_profile_qe": {"is_enabled": "disabled"}, "ig_android_mini_inbox_2": {"enable_actionbar_pinning": "true"}, "ig_android_2fac": {"is_enabled": "disabled"}, "ig_android_asus_app_badging": {"is_enabled": "1"}, "ig_explore_v3": {"is_explore_v3_enabled": "enabled"}} REQUEST: friendships/autocomplete_user_list/ RESPONSE: {"status": "fail", "message": "login_required"} REQUEST: feed/timeline/ RESPONSE: {"status": "fail", "message": "login_required"} REQUEST: direct_v2/inbox/? RESPONSE: {"status": "fail", "message": "login_required"}`

Why these problems occur to me? Should i set up a special work? Such as, 'set a secret code of insta public api or get a user's access_token'

**Comment by mgp25** [comment]
Make sure you have write privileges set in the `data` folder, force a login or remove the data and it will work

Regards

**Comment by honeydewkorea** [comment]
I already granted write privileges, but it isn't still working.

> drwxrwsrwx 3 ubuntu www  4096 Aug  1 15:57 data

**Comment by mgp25** [comment]
@honeydewkorea remove user contents from inside `data` folder

**Comment by honeydewkorea** [comment]
It is working now, Thank you very much!
