### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by derjrjr** [mgp25/Instagram-API#323]
Thank you for adding proxy support! 
But how do you use it?
I looked through the examples but am not sure how to use it..
Thanks

**Comment by jpmoney5065** [comment]
```
$i = new \InstagramAPI\Instagram($username, $password);                 
$i->setProxy($proxy);
$i->login();
```

**Comment by chadpriddle** [comment]
I'm using the dev-master. If I use this: $proxy = 'user:pass@ipaddress:port' it immediately fails with: 

`Fatal error: Uncaught exception 'InstagramAPI\InstagramException' with message 'Proxy host error. Please check ip address and port of proxy.' in /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/Instagram.php:142 Stack trace: #0 /home/devphox/public_html/instagram/index.php(17): InstagramAPI\Instagram->setProxy('ch??????:2p...') #1 {main} thrown in /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/Instagram.php on line 142`

If I use a proxy where I use IP authentication then execute it hangs about 60 seconds then gives me this error:

`REQUEST: feed/timeline/ RESPONSE: REQUEST: direct_v2/inbox/? RESPONSE: 
Fatal error: Uncaught exception 'InstagramAPI\InstagramException' with message ' ' in /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/Instagram.php:706 Stack trace: #0 /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/Instagram.php(212): InstagramAPI\Instagram->getv2Inbox() #1 /home/devphox/public_html/instagram/index.php(19): InstagramAPI\Instagram->login() #2 {main} thrown in /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/Instagram.php on line 706`

I'm not sure why it's calling the getv2Inbox() function. My code:

`$i = new \InstagramAPI\Instagram($username, $password, $debug);
$i->setProxy($proxy);
$i->login();`

If I remove the setProxy function everything works as it should but I'm wanting to use a proxy so my IP doesn't get banned.

Great script btw

**Comment by derjrjr** [comment]
You declare them seperately.
```
$proxy = '192.168.1.1';
$port = '8080';
$username = 'username';
$password = 'password';
$i = new \InstagramAPI\Instagram($username, $password, $debug);
$i -> setProxy($proxy, $port, $username, $password);
 $i->login();
```
Hope this helps :)

**Comment by chadpriddle** [comment]
I have tried that as well with the same results. The new setProxy function in dev-master splits out the ip, port, username and password as well.

**Comment by derjrjr** [comment]
What do you mean? 
I havent been able to use the API yet but I have looked at the source.
In "src/instagram.php" for setting proxy settings it says:
```
 public function setProxy($proxy, $port = null, $username = null, $password = null)
```
so you just send the 4 parameters.

**Comment by chadpriddle** [comment]
I have tried that with the same results. I have purchased 5 proxies from one source and purchased 5 from another source and I can't get any to work with the setProxy function :/

**Comment by derjrjr** [comment]
What provider is it? You are generally given 2 options, IP authentication and username and password authentication.
I usually use IP authentication as it is much easier than setting up the username and password.
If you are using this API on a server, add the servers IP also as that needs authorization.
It is always a good idea to test with free proxies before buying them just to make sure you can make it work although 5 proxies costs only about 5$.

**Comment by chadpriddle** [comment]
I have tried both the username/password and also the ip auth. I put in my servers IP address and my local IP address that is executing the script in their system. Read my original post with the errors. 

I've tried: 
highproxies.com
sslprivateproxy.com

**Comment by derjrjr** [comment]
hmm im not too sure, try redownloading the whole package and try again, I will be using it soon and can see if I have the same problem as you
