### ISSUE TITLE
Problem using "registrationTool.php"

### ISSUE THREAD

**Issue by yaghmaie** [mgp25/Instagram-API#325]
Hello,
I can not get "success" message  using "registrationTool.php". I use an email that is not registered with any account. Script can successfully check account availability but it fails with registration. I also changed my IP address but there was no luck.

Thanks

**Comment by imaraz** [comment]
hi,
i have same issue. is this api still working?

**Comment by mgp25** [comment]
Yes, API is working, i dont know if registration, but the rest works good

Regards

**Comment by baimurzin** [comment]
I have the same issue, and here is what i found when registrationTool.php:
`"errors": {"device_id": ["Too many users have been registered on this device."]}`

Can I somehow change the device?

**Comment by mgp25** [comment]
You can change your device id by changed the `settings` file inside your username folder in `data` folder

Regards

**Comment by baimurzin** [comment]
how can I point to the my data folder in the constructor of Setting class? (is there example of setting file)
Could I create this folder anywhere?
Or that folder already exist and I should use it?

Thanks a lot!!
