### ISSUE TITLE
upload Photo

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#327]
InstagramAPI\ConfigureResponse Object
(
    [upload_id:protected] => 
    [media_id:protected] => 
    [image_url:protected] => 
    [status:protected] => fail
    [message:protected] => Please update your Instagram app to continue posting photos
)

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/commit/add6531e98665ea34496112cccb9cf8880cf2bd9

**Comment by doctorbinsibar** [comment]
problem still exists, cant upload photos and if i want to upload video is the same because it needs to upload photo before uploading video !

**Comment by mgp25** [comment]
It works
