### ISSUE TITLE
Login if account using Two factor identification

### ISSUE THREAD

**Issue by iqsites** [mgp25/Instagram-API#328]
Some accounts secured by Two factor identifier
In this case I have the answer:

```json
{
    message = "";
    "phone_verification_settings" =     {
        "max_sms_count" = 2;
        "resend_sms_delay_sec" = 60;
        "robocall_after_max_sms" = 1;
        "robocall_count_down_time_sec" = 30;
    };
    status = fail;
    "two_factor_info" =     {
        "obfuscated_phone_number" = 1234;
        "phone_verification_settings" =         {
            "max_sms_count" = 2;
            "resend_sms_delay_sec" = 60;
            "robocall_after_max_sms" = 1;
            "robocall_count_down_time_sec" = 30;
        };
        "two_factor_identifier" = xxxxxxxxxx;
        username = "xxxxxxxxxxxx";
    };
    "two_factor_required" = 1;
}
```
So, we have a text to phone number with the last 4 numbers: `obfuscated_phone_number` for username with a identifier of the request `two_factor_identifier`.

What I need to send (I getting text and know the text key) for login?

**Comment by mgp25** [comment]
Im not going to implement this, at least for the moment. Anyway, if you do it, you can send a pull request and i will merge it

Regards

**Comment by iqsites** [comment]
So sad ((( because I have no idea how intercept request from the legal app :((((
