### ISSUE TITLE
Get more result on popular feed

### ISSUE THREAD

**Issue by webfreaks** [mgp25/Instagram-API#330]
Hallo,

Is there any chance to get more popular feed result?
Can we use ```"next_max_id"``` on ```$i->getPopularFeed()``` for get more result?
Like this reference : [https://github.com/mgp25/Instagram-API/issues/200](https://github.com/mgp25/Instagram-API/issues/200#issuecomment-223379603)

Thank you.

**Comment by mgp25** [comment]
Yes, it will work i guess, you can try it and send a pull request if it works

Regards
