### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by Ebrahim-Elsawy** [mgp25/Instagram-API#332]
when i am trying to install via composer i got this error can any one help me on that 

Could not find package mgp25/instagram-php at any version matching your PHP version 5.5.34.0

**Comment by wehmoen** [comment]
PHP >= 5.6 is required

**Comment by chadpriddle** [comment]
Update your PHP to 5.6. I read through closed issues that it can work on 5.5 but I couldn't figure out how to manually install the package without using composer
