### ISSUE TITLE
Story

### ISSUE THREAD

**Issue by imton** [mgp25/Instagram-API#334]
Hey, has anybody have the chance to play with the new story API?
It seems to 
```POST /api/v1/media/configure_to_reel/```
With ````{"waterfall_id":"???????","camera_position":"front","_uuid":"XXXX","_uid":"XXXX","upload_id":XXXX,"edits":{},"source_type":1,"_csrftoken":"XXXX"}````

I am getting 403 forbidden at the moment. 
Any idea what ````waterfall_id````  is?  Has anyone been able to POST on this endpoint?

Thank you

**Comment by gaston23** [comment]
Hi @mgp25 , would you mind explaining me why you closed this issue? was this by error? 

I think my Story endpoints research would help here too, still can't get around the 403 error.

Thank you

**Comment by 83lipe** [comment]
how to post on story?

**Comment by SteveJobzniak** [comment]
@83lipe https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php
