### ISSUE TITLE
Cant Post Photos and Videos

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#336]
`RESPONSE: 825306-1100410/1100411 RESPONSE: {"status": "ok", "upload_id": "1470492632753"} REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=8f9f14bcc560ec74bbdf5e932a384de0ea9adad928febc22c36c20da86408755. RESPONSE: {"status": "fail", "message": "Please update your Instagram app to continue posting photos"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=4fb81836f2c84d2db44ff77290427c04f1dd2b2218a3e9597ce50658b4012390.{"_uuid":"7f270168-1bd9-419a-ad6e-bc0b506194a5","_uid":"3631784377","id":"3631784377","_csrftoken":"nkS8OVnzX1Kyh6ELOgkPBcFKWwaQ8NNA","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} REQUEST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=8f9f14bcc560ec74bbdf5e932a384de0ea9adad928febc22c36c20da86408755. RESPONSE: {"status": "fail", "message": "Please update your Instagram app to continue posting photos"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=4fb81836f2c84d2db44ff77290427c04f1dd2b2218a3e9597ce50658b4012390.{"_uuid":"7f270168-1bd9-419a-ad6e-bc0b506194a5","_uid":"3631784377","id":"3631784377","_csrftoken":"nkS8OVnzX1Kyh6ELOgkPBcFKWwaQ8NNA","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} `

**Please update your Instagram app to continue posting photos**
is the error message

**Comment by mgp25** [comment]
Have you updated your code before opening this issue?

Regards

**Comment by doctorbinsibar** [comment]
i have tried to update via composer, get message that newest version on server.
Then i downloaded from Github and uploded to server.
'This is the latest version.

i dont know why i get this error sience past week.

**Comment by mgp25** [comment]
@doctorbinsibar delete your data inside the `data` folder

**Comment by doctorbinsibar** [comment]
i will thank you :100:  Woks great !

**Comment by doctorbinsibar** [comment]
`RESPONSE: 825306-1100410/1100411 RESPONSEs: {"status": "ok", "upload_id": "1470506588866"} REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=8f9f14bcc560ec74bbdf5e932a384de0ea9adad928febc22c36c20da86408755. RESPONSE: {"status": "fail", "message": "Please update your Instagram app to continue posting photos"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=dc2e7d629a6858cd6f65067879f988c8935f164f483841981528c4e60be22eff.{"_uuid":"7fbc006c-bc93-4666-9788-3ab822e07c46","_uid":"3631784377","id":"3631784377","_csrftoken":"aA6ev109ksh7ehK0wJ6qRizYWNyiE7QA","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} REQUEST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=8f9f14bcc560ec74bbdf5e932a384de0ea9adad928febc22c36c20da86408755. RESPONSE: {"status": "fail", "message": "Please update your Instagram app to continue posting photos"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=dc2e7d629a6858cd6f65067879f988c8935f164f483841981528c4e60be22eff.{"_uuid":"7fbc006c-bc93-4666-9788-3ab822e07c46","_uid":"3631784377","id":"3631784377","_csrftoken":"aA6ev109ksh7ehK0wJ6qRizYWNyiE7QA","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} `

**Comment by doctorbinsibar** [comment]
It was my Fault,
next time this happens also check your hashtags and your caption text.
Mostly its because of blocked hashtags..

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/
