### ISSUE TITLE
Increase Video View

### ISSUE THREAD

**Issue by ferhadkonar** [mgp25/Instagram-API#337]
hi mgp25, and hope you are well

Really thanks for this complete API code,

I have one question,Is there a way to increase video view? I think that have private endpoint, that add view count, whit use users data such as cookie, IP ,etc.

Please help me .....

Best Regard.

**Comment by mgp25** [comment]
Yes, there is a way, but im not going to do it

Regards

**Comment by ferhadkonar** [comment]
hi, and thanks for speed answer, 
how can i speak private whit you? I really need that way...
Please help me
