### ISSUE TITLE
Transcode timeout

### ISSUE THREAD

**Issue by samdonato** [mgp25/Instagram-API#338]
My first try at running this.  In the examples, I am running uploadVideo.  Added the path to local mp4, user, password and caption.  I turned debug on and here is the data after the login.  The first "Fail" I ran across is "Transcode timeout".  I am running this on my Amazon ec2 instance "Amazon Linux AMI 2016.03"  ffmpeg and gd are installed

RESPONSE: 3252519-4336692/4336693 RESPONSE: {"status": "ok", "upload_id": "1470584149670"} REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=b1e673fc8ed6fe101aafb2f75fb790ac1b24975799cc916f740945ecb84a0e3b.{"upload_id":"1470584149670","camera_model":"LG-D370","source_type":3,"date_time_original":"2016:08:07 10:35:54","camera_make":"LGE","edits":{"crop_original_size":[null,null],"crop_zoom":1.3333334,"crop_center":[0.0,-0.0]},"extra":{"source_width":null,"source_height":null},"device":{"manufacturer":"LGE","model":"LG-D370","android_version":18,"android_release":"4.3"},"_csrftoken":"rWmvKjyED89hkZvik666Doaovz7Fx6iE","_uuid":"4233d4b2-0596-4000-9e2f-96d9e62a12e9","_uid":"3410257178","caption":"asdfasdf"} RESPONSE: {"status": "fail", "message": "Transcode timeout"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=332d834fa35ff988dfd78933f92997db38223f284f01a92760cb42ad29d5afad.{"_uuid":"4233d4b2-0596-4000-9e2f-96d9e62a12e9","_uid":"3410257178","id":"3410257178","_csrftoken":"rWmvKjyED89hkZvik666Doaovz7Fx6iE","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} REQUEST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=1fa35a17dc07c19addadf8511ffcc4289eba3c1685b412bf794e8251fa2d028d.{"upload_id":1470584149670,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":60,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"LGE","model":"LG-D370","android_version":18,"android_release":"4.3"},"_csrftoken":"rWmvKjyED89hkZvik666Doaovz7Fx6iE","_uuid":"4233d4b2-0596-4000-9e2f-96d9e62a12e9","_uid":"3410257178","caption":"asdfasdf"} RESPONSE: {"status": "fail", "message": "Other media configure error: yEmZkUpAj4"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=332d834fa35ff988dfd78933f92997db38223f284f01a92760cb42ad29d5afad.{"_uuid":"4233d4b2-0596-4000-9e2f-96d9e62a12e9","_uid":"3410257178","id":"3410257178","_csrftoken":"rWmvKjyED89hkZvik666Doaovz7Fx6iE","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"}

**Comment by RiTu1337** [comment]
You have to pause and retry the same request on transcode timeout.

**Comment by samdonato** [comment]
Thank you.  Just for the example, I did:

```
try {
    $i->uploadVideo($video, $caption);
    echo 'upload worked';
} catch (Exception $e) {
    echo $e->getMessage();
    sleep(10);
    $i->uploadVideo($video, $caption);
}
```

It worked
