### ISSUE TITLE
Delete comment

### ISSUE THREAD

**Issue by turanmahmudov** [mgp25/Instagram-API#339]
Hi,
When I want to delete user comment from my profile I use:
`deleteComment('1287309876859394261_47299627', '17849216731108348', 'Test')`
Response:
`{"status": "ok"}`.
Comment is not deleted. 

When I want to delete my comment from my profile:
Response:
`Oops, an error occurred.`
Comment is not deleted. 

When I want to delete my comment from other user's profile:
Response:
`{"status": "ok"}`.
Comment is deleted.

What am I doing wrong?

**Comment by derjrjr** [comment]
You may need a different function like deleteCommentself('1287309876859394261_47299627', '17849216731108348', 'Test'). I checked the src/instagram.php and found no such function, MGP25 will have to add it unless you can :)

**Comment by mgp25** [comment]
@turanmahmudov 

fixed in latests commits

**Comment by turanmahmudov** [comment]
Now:
I can't delete my comment from other users' posts;
I can't delete my comment from my post;
I can delete others' comments from my post.

**Comment by glazkovan** [comment]
I can't delete others' comments from my post.
