### ISSUE TITLE
Add location to posts

### ISSUE THREAD

**Issue by RageBrahimi** [mgp25/Instagram-API#34]
######  **How do you add a location to uploadPhoto.php**

I'm aware it's something on the lines of the code below, but how do we add it to 'Instagram.php', but I'm not entirely sure how.

```
     device_timestamp = 0,
     caption = xxx,
     location = {“
          name”: ”xxx”,
          ”lng”: 0,
          ”lat”: 0,
          ”external_id”: 0,
          “address”: ”xxx”,
          ”external_source”: ”foursquare”
     },
     source_type = 0,
     filter_type = 15
```

Something of the lines of this I assume? (below doesn't work):

```
      'caption'     => $caption,
      'upload_id'   => $upload_id,
      'source_type' => 3,
      'location'       =>
       array(
          'name'          => $name,
          'lng'        => $lng,
          'lat'        => $lat,
          'black_pixels_ratio' => 0
       ),
       ...
```

**Comment by mgp25** [comment]
@RageBrahimi send me the http request with the location to my mail, and i'll add this to the API

Regards

**Comment by MaximMikulich** [comment]
@mgp25 I send, but you don't add this to the API, why?)

**Comment by RageBrahimi** [comment]
@MaximMikulich Just add it here for now so everyone can use it, and when @mgp25 is ready, he'll add it to the source.

**Comment by MaximMikulich** [comment]
@RageBrahimi @mgp25 
`$location = 
array(
'external_source' => 'facebook_places',
'city' => '',
'name' => '24-7 NYC Realty',
'facebook_places_id' => 541394132625167,
'foursquare_v2_id' => NULL,
'state' => '',
'address' => '275 Central Park W, New York',
'lat' => 40.786541,
'pk' => 1021639683,
'lng' => -73.9689178,
'external_id' => NULL,
);
$location = json_encode($location);


$data = (object)array(
'device_id' => $device_id,
'guid' => $guid,
'usertags' => $usertags,
'lng' => -73.9689178,
'media_id' => $media_id,
'caption' => trim($caption),
'location' => $location,
'lat' => 40.786541,
'device_timestamp' => time(),
'filter_type' => '114',
'source_type' => 3,
'extra' => '{}',
'Content-Type' => 'application/x-www-form-urlencoded; charset=UTF-8',
);
$data = json_encode($data);
$sig = GenerateSignature($data);
$new_data = 'signed_body=' . $sig . '.' . urlencode($data) . '&ig_sig_key_version=4';
$conf = SendRequest('media/configure/', true, $new_data, $agent, true);`

This is all done on the example [](http://lancenewman.me/posting-a-photo-to-instagram-without-a-phone/)

**Comment by MaximMikulich** [comment]
@RageBrahimi And I find how add usertags, but when I transfer the settings on the server is transmitted Instagram emptiness: "in": []

```
$usertags = array (
'in' => 
array (
0 => 
array (
'position' => 
array (
0 => 0.10000000000000001,
1 => 0.14999999999999999,
),
'user' => 
array (
'username' => 'scandimax',
'pk' => 518659795,
'profile_pic_url' => 'http://scontent.cdninstagram.com/t51.2885-19/11348160_881962661883493_1767921066_a.jpg',
'is_private' => false,
'full_name' => 'Maxim',
),
),
),
);
$usertags = json_encode($usertags);
```

**Comment by RageBrahimi** [comment]
And you've tried, and these have both worked successfully?

**Comment by MaximMikulich** [comment]
@RageBrahimi location worked, usertag not

**Comment by klawdyo** [comment]
@MaximMikulich @RageBrahimi @mgp25 
Hi, guys! Having progress in adding location?
```PHP
Array
(
    [upload_id] => 1460918151271
    [camera_model] => HM1S
    [source_type] => 3
    [date_time_original] => 2016:04:17 15:35:53
    [camera_make] => XIAOMI
    [edits] => ...
    [extra] => ...
    [device] => ...
    [_csrftoken] => f0a9c3a98b0d4dc72a925248595d3452
    [_uuid] => 04f0269b-ec00-4457-8860-b722f387aca0
    [_uid] => 2175898438
    [caption] => tests1
    [location] => Array
        (
            [external_source] => facebook_places
            [city] => 
            [name] => 24-7 NYC Realty
            [facebook_places_id] => 5.4139413262517E+14
            [foursquare_v2_id] => 
            [state] => 
            [address] => 275 Central Park W, New York
            [lat] => 40.786541
            [pk] => 1021639683
            [lng] => -73.9689178
            [external_id] => 
        )
    [lat] => 40.786541
    [lng] => -73.9689178
)
```

Where am I going wrong?

**Comment by RageBrahimi** [comment]
@klawdyo From just an overview, your **facebook_places_id** is not valid. Find a valid ID and it should work.

**Comment by klawdyo** [comment]
@RageBrahimi facebook_places_id was changed by php because is long. I put quotes to fix it.
```
            'location' => [
                'external_source' => 'facebook_places',
                'city' => '',
                'name' => 'Assu',
                'facebook_places_id' => '114542481892365',
                'foursquare_v2_id' => NULL,
                'state' => '',
                'address' => '',
                'pk' => 236984630,
                'lat' => -5.576944444,
                'lng' => -36.908888889,
                'external_id' => NULL,
            ],
            'lat' => -5.576944444,
            'lng' => -36.908888889,
      
```
returns
`{"status":"fail","message":"Other media configure error: E3v4zLVnwi"}`

When I remove the 'location', 'lat' and 'lng' keys from array, the upload works fine.
Where am I going wrong?

**Comment by klawdyo** [comment]
OK. Fixed. facebook_places_id can not be string.

**Comment by MaximMikulich** [comment]
@klawdyo 
```
'lat' => -5.576944444,
'lng' => -36.908888889,
```
it can be removed

**Comment by MaximMikulich** [comment]
@klawdyo information about the location of this feature I'm looking for `searchLocation($query);`

**Comment by RageBrahimi** [comment]
@klawdyo It'd be good if you posted the code that works for others future reference.

**Comment by MaximMikulich** [comment]
@RageBrahimi I can post.
here?

**Comment by MaximMikulich** [comment]
@RageBrahimi but can you help me on #135 ?

**Comment by klawdyo** [comment]
@MaximMikulich The only required key is 'facebook_places_id'.

@RageBrahimi  Inside "configure()", after $post, my code is:

```PHP
            $location = [
                'facebook_places_id' => '114542481892365', //inside quotes to avoid int32 problems
            ] ;

            //converting to json
            $location = [ 'location' => json_encode( $location ) ];

            //Removing quotes from json. 
            //'facebook_places_id' needs to be an integer
            $pattern = '/"facebook_places_id":"([0-9]+)"/';
            $location['location'] = preg_replace( $pattern, '"facebook_places_id":\1', $location['location'] );

            //Merge location
            $post = array_merge( $post, $location );
```

**Comment by MaximMikulich** [comment]
@klawdyo I understood) but I did with the function `searchLocation($query);`
works good)
