### ISSUE TITLE
How to get a media_id with upload a media?

### ISSUE THREAD

**Issue by honeydewkorea** [mgp25/Instagram-API#340]
Hi.

I want to get a media_id when i upload a media.

I asked upload function such as :
`$insta_info = $i->uploadPhoto($photo, $caption);`

And i tried read a data for the method:
```
// Parse 
$insta_info[status];
```
But I couldn't read a data. How to read a data in multiple array? 

The upload function's return is ; (I modified the retrun data such as my private informations)

> RESPONSE: {"status": "ok", "upload_id": "1470656961417"} REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=8df8a4f341eec8222a619ed1038921faeb5e11d8c0c43f24a1a7ff3313e3b70f.{"upload_id":"1470656961417","camera_model":"LT700","source_type":3,"date_time_original":"2016:08:08 20:49:23","camera_make":"QMobile","edits":{"crop_original_size":[800,800],"crop_zoom":1.3333334,"crop_center":[0,-0]},"extra":{"source_width":800,"source_height":800},"device":{"manufacturer":"QMobile","model":"LT700","android_version":18,"android_release":"4.3"},"_csrftoken":"PPCNVi1T52s388fh4PL4LY7INaXv0ymP","_uuid":"86cbb97c-3ac7-4155-944e-e6d4e57fe818","_uid":"&numeric_id&","caption":"1350\ud64d\ucf69\uc73c\ub85c \ub5a0\ub098\uc694!#\uae40\uc815\ud0dc"} **RESPONSE: {"status": "ok", "media": {"taken_at": 1470656968, "pk": 1312288220351853001, "id": "1312288220351853001_&numeric_id&", "device_timestamp": 1470656961417, "media_type": 1, "code": "BI2Ly8BAHHJ", "client_cache_key": "MTMxMjI4ODIyMDM1MTg1MzAwMQ==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://scontent.cdninstagram.com/t51.2885-15/e35/13767635_1744567942448329_1159474735_n.jpg?se=8\u0026ig_cache_key=MTMxMjI4ODIyMDM1MTg1MzAwMQ%3D%3D.2", "width": 800, "height": 800}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13767635_1744567942448329_1159474735_n.jpg?ig_cache_key=MTMxMjI4ODIyMDM1MTg1MzAwMQ%3D%3D.2", "width": 640, "height": 640}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s480x480/e35/13767635_1744567942448329_1159474735_n.jpg?ig_cache_key=MTMxMjI4ODIyMDM1MTg1MzAwMQ%3D%3D.2", "width": 480, "height": 480}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s320x320/e35/13767635_1744567942448329_1159474735_n.jpg?ig_cache_key=MTMxMjI4ODIyMDM1MTg1MzAwMQ%3D%3D.2", "width": 320, "height": 320}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e35/13767635_1744567942448329_1159474735_n.jpg?ig_cache_key=MTMxMjI4ODIyMDM1MTg1MzAwMQ%3D%3D.2", "width": 240, "height": 240}, {"url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e35/13767635_1744567942448329_1159474735_n.jpg?ig_cache_key=MTMxMjI4ODIyMDM1MTg1MzAwMQ%3D%3D.2", "width": 150, "height": 150}]}, "original_width": 800, "original_height": 800, "user": {"username": "instaname", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "(\uc8fc)\ud5c8\ub2c8\ub4c0", "pk": &numeric_id&, "is_private": false}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjY2MjJhMzZlODNkMjQxMWU5OWY2MTQzN2JmMjgwYjRjMTMxMjI4ODIyMDM1MTg1MzAwMSIsInNlcnZlcl90b2tlbiI6IjE0NzA2NTY5Njg0NzV8MTMxMjI4ODIyMDM1MTg1MzAwMXwzNTgwNzQxMTc0fGFhODNhZGFlMzdjZWVhOTMxNDlkNDg1MzdlYzk0MTUzNzgzMDRhYmI2NmFmM2ZhN2Q4Y2M5ZmE4YmE2ZmQyMGQifSwic2lnbmF0dXJlIjoiIn0=", "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 4, "comments": [], "comment_count": 0, "caption": {"status": "Active", "user_id": &numeric_id&, "created_at_utc": 1470656968, "created_at": 1470656968, "bit_flags": 0, "user": {"username": "instaname", "has_anonymous_profile_picture": true, "is_unpublished": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "full_name": "(\uc8fc)\ud5c8\ub2c8\ub4c0", "pk": &numeric_id&, "is_private": false}, "content_type": "comment", "text": "1350\ud64d\ucf69\uc73c\ub85c \ub5a0\ub098\uc694!#\uae40\uc815\ud0dc", "media_id": 1312288220351853001, "pk": 17859838195057307, "type": 1}, "caption_is_edited": false, "photo_of_you": false}, "upload_id": "1470656961417"}** REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=225a365df7c36723e56e744eee415c2daf800fd4e7d6716e285554c07cd4746c.{"_uuid":"86cbb97c-3ac7-4155-944e-e6d4e57fe818","_uid":"&numeric_id&","id":"&numeric_id&","_csrftoken":"PPCNVi1T52s388fh4PL4LY7INaXv0ymP","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"}

**Comment by mgp25** [comment]
`$insta_info->getMediaId()`

Reference: https://github.com/mgp25/Instagram-API/blob/master/src/http/Response/ConfigureResponse.php#L28

**Comment by honeydewkorea** [comment]
I solved the problem, thank you so much!!

**Comment by acondura** [comment]
$photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename);
$ret = $ig->timeline->uploadPhoto($photo->getFile(), ['caption' => $captionText]);

The above works great, the post is successfully sent to Instagram however, when I try to get the media id with:
$ret->getMediaId();
nothing happens, no returned ID. What's going on?
