### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#342]
Hello,
please fix Registration

> HTTP/1.1 400 Bad Request
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Tue, 09 Aug 2016 18:52:47 GMT
Content-Type: application/json
Set-Cookie: csrftoken=8Y55iUmceF5mukowTqQo8FQ9KnrdYUdB; expires=Tue, 08-Aug-2017 18:52:47 GMT; Max-Age=31449600; Path=/; secure
Set-Cookie: s_network=; expires=Tue, 09-Aug-2016 19:52:47 GMT; Max-Age=3600; Path=/
Set-Cookie: sessionid=IGSC23fbab2e917554bbf252fc0e19b166c2bdc4ba0bbeb075031cf5cf226bd47f51%3AmO1LAoBBtYpmkwyyg8fWXC2e1JOV8khp%3A%7B%22_token_ver%22%3A2%2C%22_auth_user_id%22%3A3645126677%2C%22_token%22%3A%223645126677%3AOoxVGe0WQZKxJkRuqKQJXFeSqrUHFvGp%3A7c2b5be54b912800865857e49e8ec2189eebd71ed7975c1b376a239ff35528e9%22%2C%22asns%22%3A%7B%22104.227.107.7%22%3A55286%2C%22time%22%3A1470768767%7D%2C%22_auth_user_backend%22%3A%22accounts.backends.CaseInsensitiveModelBackend%22%2C%22last_refreshed%22%3A1470768767.307041%2C%22_platform%22%3A1%2C%22_auth_user_hash%22%3A%22%22%7D; expires=Mon, 07-Nov-2016 18:52:47 GMT; httponly; Max-Age=7776000; Path=/; secure
Set-Cookie: mid=V6omfgABAAFpsx2ZYfJ7mZkGDgxX; expires=Mon, 04-Aug-2036 18:52:47 GMT; Max-Age=630720000; Path=/
Connection: keep-alive
Content-Length: 477

    [1] => Array
        (
            [status] => fail
            [feedback_title] => Signup Error
            [feedback_message] => Sorry! There’s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.
            [spam] => 1
            [feedback_action] => report_problem
            [feedback_url] => repute/report_problem/instagram_signup/
            [feedback_ignore_label] => OK
            [message] => feedback_required
            [feedback_appeal_label] => Report problem
        )

)

**Comment by mgp25** [comment]
`[spam] => 1`

register manually from your device
