### ISSUE TITLE
Video Upload

### ISSUE THREAD

**Issue by chadpriddle** [mgp25/Instagram-API#343]
Using dev-master

I can easily upload photos no problem. When I switch to the upload video script the video doesn't post. When I use debug true I don't get no errors other than it's pulling feed info but nothing about the video error. 

I have curl and php gd installed. Here is my ffmpeg version info:
`root@server [~]# ffmpeg -version
ffmpeg version N-81308-g369ed11 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-17)
configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/root/bin --extra-libs=-ldl --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libfreetype --enable-libspeex --enable-libtheora
libavutil      55. 28.100 / 55. 28.100
libavcodec     57. 51.100 / 57. 51.100
libavformat    57. 46.100 / 57. 46.100
libavdevice    57.  0.102 / 57.  0.102
libavfilter     6. 50.100 /  6. 50.100
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  1.100 /  2.  1.100
libpostproc    54.  0.100 / 54.  0.100`

If I turn debug to false and run this:
`try {
    $i->uploadVideo($filename, $comment);
} catch (Exception $e) {
    echo $e->getMessage();
}`
I get no errors.

If I run this without the try and catch:
`$i->uploadVideo($filename, $comment);`

I get this error:
`Fatal error: Uncaught exception 'InstagramAPI\InstagramException' in /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/http/HttpInterface.php:169 Stack trace: #0 /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/Instagram.php(287): InstagramAPI\HttpInterface->uploadPhoto('uploads/1R9Kizl...', 'Test', 1.47078717379E+12) #1 /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/Instagram.php(313): InstagramAPI\Instagram->uploadPhoto('uploads/1R9Kizl...', 'Test', 1.47078717379E+12) #2 /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/http/HttpInterface.php(310): InstagramAPI\Instagram->configureVideo(1.47078717379E+12, 'uploads/1R9Kizl...', 'Test') #3 /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/Instagram.php(303): InstagramAPI\HttpInterface->uploadVideo('uploads/1R9Kizl...', 'Test') #4 /home/devphox/public_html/instagram/test2.php(21): InstagramAPI\Instagram->uploadVideo('uploads/1R9Kizl...', 'Test') #5 {main} thrown in /home/devphox/public_html/instagram/vendor/mgp25/instagram-php/src/http/HttpInterface.php on line 169`

When I navigate to line 169 of HttpInterface.php it is within the uploadPhoto function. Should it be??

Also the mp4 I am uploading was originally downloaded from an Instagram feed so it should work. Any thoughts? Is there another error log I should be looking at? It seems like I am not getting typical error responses like others in the closed issues. 
Thanks!

**Comment by chadpriddle** [comment]
Line 387 in Instagram.php:
`$this->uploadPhoto($video, $caption, $upload_id);`

Should it be:
`$this->uploadVideo($video, $caption, $upload_id);`

I tried it and I no longer get a fatal error but still no other responses or errors. At all of my debugs I just see "Response: " at the bottom of my page

**Comment by mgp25** [comment]
@chadpriddle code is okay, you can try using a clear code from zero.

Regards

**Comment by chadpriddle** [comment]
"clear code from zero"? Can you elaborate please. Is this a form of debugging with your code?

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/
