### ISSUE TITLE
Please update your Instagram app to continue commenting Error

### ISSUE THREAD

**Issue by GitDov** [mgp25/Instagram-API#344]
I'm getting this error message when i try to comment. I usually do 1 to 3 comments and then i receive this message: 

message => Please update your Instagram app to continue commenting
status => fail

But when i use another service like instagress or by the cellphone its not blocked.
I changed the IP, Logoff and Login again, and still did not work.

Any suggestions?

**Comment by GuilhermeFM** [comment]
This usually happens when you signed the post data with the wrong key/algorithm. Check if other post calls are working.

This could also be caused if you have special characters on the comment. Example if you try to send a comment with 'ç' or 'á' you need to scape those characters.

**Comment by GitDov** [comment]
@GuilhermeFM I need to encode the string or escape the spaces??? Its strange because i can comment sometimes before its locked.
In case of wrong key it should lock in the first attemp.

**Comment by GuilhermeFM** [comment]
@GitDov I'm not certain, i was getting the same problem as you when i was messing with hashtags feeds, everything was correct the key and the algorithm used to sign and the behavior was the same as you got, it worked for some and for other not, then i realised that i only got this message when the string had special character then i decided to encoded only the words with special characters

**Comment by mgp25** [comment]
Sometimes its due a anti-bot detection

Regards

**Comment by chrisbrennanphoto** [comment]
I was getting this as a result of having special characters in the Caption or Title in metadata. Removing or stripping questionable characters from the images resolved the issue.

**Comment by SteveJobzniak** [comment]
@chrisbrennanphoto Interesting... that's strange. I would have expected them to just say "invalid request". Not "please update"...

I think Instagram allows any UTF-8 character. But you must be sure that your data is UTF-8. For example, let's say your website is in Russian and has a CP1259 codeset, then you must convert all form data to UTF8 via http://php.net/manual/en/function.mb-convert-encoding.php before sending to Instagram.
