### ISSUE TITLE
login response empty

### ISSUE THREAD

**Issue by SaeedSoltoon** [mgp25/Instagram-API#346]
hi @mgp25  , when im runing the exmple of photo upload , i want to get the response from login method but it is empty. 
here is code, just a print_r added!
----
```
$i = new \InstagramAPI\Instagram($username, $password, $debug);
try {
    $res = $i->login();
   print_r($res);
} catch (Exception $e) {
    $e->getMessage();
}

try {
    $res = $i->uploadPhoto($photo, $caption);
    echo "<br>========<br><pre>";
    	print_r($res);
    echo "</pre>";
} catch (Exception $e) {
    echo $e->getMessage();
}
```
but response of the photo upload is works, what should i do? is there anything wrong?!

**Comment by mgp25** [comment]
You can access to its values using the functions of the object, like:

```php
$res = $i->login();
$usernameId = $res->getUsernameId();
```

Reference: https://github.com/mgp25/Instagram-API/blob/master/src/http/Response/LoginResponse.php

**Comment by SaeedSoltoon** [comment]
@mgp25 thanks for your response, i do the same , but there is an error fatal error.
`PHP Fatal error:  Call to a member function getUsernameId() on null`
what should i do now? 
the image response works properly and login process is ok, what's the issue?

**Comment by mgp25** [comment]
post debug log when error occurs

**Comment by SaeedSoltoon** [comment]
@mgp25 thank you. here is the debug log
[14-Aug-2016 23:10:13 Asia/Tehran] PHP Fatal error:  Call to a member function getUsernameId() on null in /home/temphaa/public_html/phpins/vendor/mgp25/instagram-php/examples/uploadPhoto.php on line 21

**Comment by SaeedSoltoon** [comment]
just added this to your example code
```
$res = $i->login();
$usernameId = $res->getUsernameId();
```
just it. i dont know what's the issue.
