### ISSUE TITLE
Proxy question

### ISSUE THREAD

**Issue by pavle93** [mgp25/Instagram-API#347]
Hello, thanks for the great API. I have one question about proxies. I've grabbed a proxy from here
https://proxy-list.org/english/index.php

And in code did something like this

` $r->setProxy('http://210.129.22.168',3128);
$result = $r->createAccount($username, $password, $email) ;`

However Instagram still keeps blocking me. And it shouldn't since I proxied the request. Do you have any advice about what to do ? :)

**Comment by mgp25** [comment]
Nope

**Comment by derjrjr** [comment]
Problem most likely with the proxy, most public proxies on them sites say they are active even when they arent and even if they are active, not all have SSL or work with Instagram..
I would advise to buy a private proxy and try
