### ISSUE TITLE
Checkpoint not working

### ISSUE THREAD

**Issue by gergo2007** [mgp25/Instagram-API#348]
Hi

I have requested a checkpoint but i get redirected to instagram page with the error message:
Error
Could not refresh this page. If you do not have cookies enabled in your browser or if you're browsing in private mode, try to enable or disable cookies privately and then try again.

**Comment by gergo2007** [comment]
* About to connect() to i.instagram.com port 443 (#0)
*   Trying 31.13.66.52... * connected
* Connected to i.instagram.com (31.13.66.52) port 443 (#0)
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.instagram.com,O=Instagram LLC,L=Menlo Park,ST=CA,C=US
* 	start date: Apr 08 00:00:00 2015 GMT
* 	expire date: Dec 30 12:00:00 2016 GMT
* 	common name: *.instagram.com
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> POST /integrity/checkpoint/checkpoint_logged_out_main/408312141/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss HTTP/1.1
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G34 Instagram 8.5.2 (iPhone5,2; iPhone OS 9_3_3; es_ES; es-ES; scale=2.00; 640x1136)
Host: i.instagram.com
Cookie: is_starred_enabled=yes; ds_user=gergo; mid=V6eIOgABAAHUuCrxcH3C4WcT4MVQ; csrftoken=r1BBDUxfyVffARZAnnkAqZ8UFRjp1Tan
Origin: https://i.instagram.com
Connection: keep-alive
Proxy-Connection: keep-alive
Accept-Language: es-es
Referer: https://i.instagram.com/integrity/checkpoint/checkpoint_logged_out_main/408312141/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Content-Length: 93
Content-Type: application/x-www-form-urlencoded

< HTTP/1.1 200 OK
< Content-Language: es
< Expires: Sat, 01 Jan 2000 00:00:00 GMT
< Vary: Cookie, Accept-Language
< Pragma: no-cache
< Cache-Control: private, no-cache, no-store, must-revalidate
< Date: Sun, 14 Aug 2016 20:59:50 GMT
< X-Frame-Options: SAMEORIGIN
< Content-Type: text/html
* Replaced cookie csrftoken="r1BBDUxfyVffARZAnnkAqZ8UFRjp1Tan" for domain i.instagram.com, path /, expire 1502657972
< Set-Cookie: csrftoken=r1BBDUxfyVffARZAnnkAqZ8UFRjp1Tan; expires=Sun, 13-Aug-2017 20:59:50 GMT; Max-Age=31449600; Path=/; secure
* Replaced cookie checkpoint_step="" for domain i.instagram.com, path /, expire 1471208372
< Set-Cookie: checkpoint_step=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
< Connection: keep-alive
< Content-Length: 7* About to connect() to i.instagram.com port 443 (#0)
*   Trying 157.240.3.52... * connected
* Connected to i.instagram.com (157.240.3.52) port 443 (#0)
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.instagram.com,O=Instagram LLC,L=Menlo Park,ST=CA,C=US
* 	start date: Apr 08 00:00:00 2015 GMT
* 	expire date: Dec 30 12:00:00 2016 GMT
* 	common name: *.instagram.com
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /integrity/checkpoint/checkpoint_logged_out_main/408312141/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss HTTP/1.1
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G34 Instagram 8.5.2 (iPhone5,2; iPhone OS 9_3_3; es_ES; es-ES; scale=2.00; 640x1136)
Host: i.instagram.com
Accept: */*
Cookie: is_starred_enabled=yes; ds_user=gergo; mid=V6eIOgABAAHUuCrxcH3C4WcT4MVQ; csrftoken=r1BBDUxfyVffARZAnnkAqZ8UFRjp1Tan

< HTTP/1.1 200 OK
< Content-Language: en
< Expires: Sat, 01 Jan 2000 00:00:00 GMT
< Vary: Cookie, Accept-Language
< Pragma: no-cache
< Cache-Control: private, no-cache, no-store, must-revalidate
< Date: Sun, 14 Aug 2016 21:02:10 GMT
< X-Frame-Options: SAMEORIGIN
< Content-Type: text/html
* Replaced cookie csrftoken="r1BBDUxfyVffARZAnnkAqZ8UFRjp1Tan" for domain i.instagram.com, path /, expire 1502658112
< Set-Cookie: csrftoken=r1BBDUxfyVffARZAnnkAqZ8UFRjp1Tan; expires=Sun, 13-Aug-2017 21:02:10 GMT; Max-Age=31449600; Path=/; secure
* Replaced cookie checkpoint_step="" for domain i.instagram.com, path /, expire 1471208512
< Set-Cookie: checkpoint_step=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
< Connection: keep-alive
< Content-Length: 77
< 
* Connection #0 to host i.instagram.com left intact
* Closing connection #0

**Comment by mgp25** [comment]
It works for me

Regards

**Comment by gergo2007** [comment]
For code im getting an empty string (  $code = trim(fgets(STDIN)); ) 
Maybe thats the problem?

**Comment by mgp25** [comment]
@gergo2007 it could be, test it and send a pull request

**Comment by gergo2007** [comment]
@mgp25 can you please explain how and from where should i be getting a code?
i have tested it yesterday and STDIN returns this:


Chat Conversation Start
MON 6:36PM
lmao
https://github.com/mgp25/Instagram-API/issues/348
Checkpoint not working · Issue #348 · mgp25/Instagram-API
Hi I have requested a checkpoint but i get redirected to instagram page with the error message: Error Could not refresh this page. If you do not have cookies enabled in your browser or if you're b...
github.com
MON 11:13PM
hallod
ez szted mit csinal?
$code = trim(fgets(STDIN));

le trimeli amit kapsz a filebol?
de mien filebol?
:))

nemtom XD
ense
erdekes

irasd ki STDIN
masik valasza meg works for me
fucking pric
k
XD

:))
stream resource @11 ▼
  timed_out: false
  blocked: true
  eof: true
  wrapper_type: "PHP"
  stream_type: "STDIO"
  mode: "r"
  unread_bytes: 0
  seekable: true
  uri: "php://stdin"
  options: []
}

fgets(STDIN) returns false and after trimming it the code is empty.

Thank you
