### ISSUE TITLE
Curl error:SSL: CA certificate set, but certificate verification is disabled

### ISSUE THREAD

**Issue by thmsystem** [mgp25/Instagram-API#351]
When I try to login I get this error from Curl.

So I changed curl options to:
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);

and now it's work.

I have this error in OS X El Capitan 10.11.6
Curl version: 7.47.1

**Comment by dtgdev** [comment]
It works! Thanks! I struggled with the same issue for two days.You really saved my day.
