### ISSUE TITLE
Undefined offset: 0 when logging in

### ISSUE THREAD

**Issue by gergo2007** [mgp25/Instagram-API#353]
#message: "Undefined offset: 0"
  #code: 0
  #file: "/var/www/html/vendor/mgp25/instagram-php/src/Instagram.php"
  #line: 179
  #severity: E_NOTICE
  -trace: {▼
    71. Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() ==> new ErrorException(): {▼
      src: {▼
        /var/www/html/vendor/mgp25/instagram-php/src/Instagram.php:179: """
          'phone_id'            => SignatureUtils::generateUUID(true),\n
          '_csrftoken'          => $token[0],\n
          'username'            => $this->username,\n
          """
      }
    }

Token is empty, array(0) { }
Fetch is:
array:2 [▼
  0 => false
  1 => null
]

Seems like im getting this error with a proxy.

**Comment by gergo2007** [comment]
Token is empty, array(0) { }

**Comment by gergo2007** [comment]
Fetch is:
array:2 [▼
  0 => false
  1 => null
]

**Comment by mgp25** [comment]
Then is proxy error and post debug log!
