### ISSUE TITLE
[SOLVED] How to deal with API REQUEST/RESPONSE

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#354]
Dear All , I am new to this API so please be patient with me :)

When we use this API , we can not know how things gos if debug is false.
If debug is true , a huge amount of debug information is returned as TEXT

php TestLogin.php
REQUEST: si/fetch_headers/?challenge_type=signup&guid=bdc8fef891234155a772afb6cbd36512
RESPONSE: {"status": "ok"}

REQUEST: accounts/login/
DATA: ig_sig_key_version=4&signed_body=bb1952d7cbe7f12650625f81e354f68f54aa93eac282b3ffe6a3ca3439226e96.{"phone_id":"39b9a789-5f13-45e2-ab1d-c23fac7b144a","_csrftoken":"Set-Cookie: csrftoken=yFRB3O2Vp7EEi7J6z6ywKEQ4Hww4jP4N","username":"sabo.al.walid","guid":"dd0dabd6-2e2b-4891-ab3f-c2422f8c7616","device_id":"android-dbfebd268db48687","password":"3310065+-6669448","login_attempt_count":"0"}
RESPONSE: {"buttons": [{"action": "dismiss", "title": "Try Again"}], "status": "fail", "message": "The username you entered doesn't appear to belong to an account. Please check your username and try again.", "invalid_credentials": true, "error_title": "Incorrect Username"}

do i have to search the returned text to match "Incorrect Username" string ?

and  all other function return same RESPONSE format.

other eg: 
$i->searchLocation('usa');

it return a very long text with a lot of REQUEST/RESPONSE , how can i catch RESPONSE.

i know there is a RESPONSE scripts Instagram-API/src/http/Response
but it dos not cover error RESPONSES .  like what if username and password is not correct ?. or the uploaded image is not in a correct format 

i did search , and i did not find answer , i am sure there is a way but i dont know how , so please gide me .

**Comment by GuilhermeFM** [comment]
Almost all response that come from instagram are in json format even the response from request that fail except for 404 response in that case a web page is returned. So you could use some kind of json tool to convert the json string into object and then read the object properties

If you want to know more about how instagram works through their API, you can install a web proxy (fiddler or other) and point your device or emulator to pass through fiddler proxy. All requests/response will be there for you to analise.

**Comment by beshoo1** [comment]
Dear @GuilhermeFM thank you for your kindly reply , i know that 
RESPONSE: {"buttons": [{"action": "dismiss", "title": "Try Again"}], "status": "fail", "message": "The username you entered doesn't appear to belong to an account. Please check your username and try again.", "invalid_credentials": true, "error_title": "Incorrect Username"}
is a JSON , but it came with a lot of TEXT . and we have a lot of JSON response.

how can i only print JSON without other stuff !

**Comment by derjrjr** [comment]
Do something like this
``
$i = new \InstagramAPI\Instagram($username, $password, $debug);
try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}
try {
**$data =**    $i->uploadPhoto($photo, $caption);
} catch (Exception $e) {
    echo $e->getMessage();
}

if($data['status'] == 'fail'){
echo "Fail";
else{
echo "Success";
}

``

**Comment by beshoo1** [comment]
@derjrjr thank you very much , and i found this right Now :)  

 $message =  $i->uploadPhoto($photo, $caption);
   print $message->getMessage();

Thanks to Instagram-API/src/http/Response/Response.php
