### ISSUE TITLE
Question about Requests!

### ISSUE THREAD

**Issue by manugildev** [mgp25/Instagram-API#355]
What do you use to analyze the android requests that instagram app uses??
I'm trying to port your API to other languages but I need to know how to do this reverse engineering trick to view what http requests are being made! 

Thanks!

**Comment by GuilhermeFM** [comment]
The easy way is to use web proxy. I like to use fiddler but there are others. Once you install a web proxy just configure the device/emulator to go through the proxy

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/wiki
