### ISSUE TITLE
User information on mediaInfo

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#358]
Hi!

I am trying to show media with all it's information (date, filter, caption, etc) as well as information about the media author (user who took the photo/video). I don't see a way to access the user info from mediaInfo request, how can this be done with just one request?

Thanks!

**Comment by iimnd** [comment]
maybe this help : 
you must create a function to get the response first on http/Response/MediaInfoResponse.php, then if you want to access them, you just access the function.

**Comment by mgp25** [comment]
@joseflorido you can add the functions to the response as @iimnd said

Regards
