### ISSUE TITLE
Can't upload video

### ISSUE THREAD

**Issue by torlakfaruk** [mgp25/Instagram-API#361]
Hi i try to upload video with your example code. The code is running but nothing happened on account. Why nothing happened. What should i do for it?

**Comment by mgp25** [comment]
@torlakfaruk debug log?

**Comment by torlakfaruk** [comment]
Try it now. It give:

RESPONSE: {"status": "fail", "message": "Uploaded image isn't in the right format"}
RESPONSE: {"status": "fail", "message": "Other media configure error: yEmZkUpAj4"}

The video which i try to upload is downloaded from instagram.

**Comment by mgp25** [comment]
@torlakfaruk try using other format (extension, dimmensions, etc) or similar: `Uploaded image isn't in the right format`

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/
