### ISSUE TITLE
Video uploads not working

### ISSUE THREAD

**Issue by ronnie173** [mgp25/Instagram-API#366]
Is anybody having issues with the video not being uploaded to instagram?

**Comment by iimnd** [comment]
i'm failed too. get error log  "duplicate update id".

**Comment by mgp25** [comment]
@iimnd post full response

**Comment by mgp25** [comment]
Video upload works, for further support post debug log

Regards

**Comment by iimnd** [comment]
hi sir @mgp25 here is my response when i uploaded a video :

> Array ( [photo_result] => InstagramAPI\ConfigureVideoResponse Object ( [upload_id:protected] => [media_id:protected] => [image_url:protected] => [video_version:protected] => [status:protected] => fail [message:protected] => Server got a conflicting upload id ) )

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/

**Comment by summy1991** [comment]
Hii

**Comment by summy1991** [comment]
Hii

**Comment by summy1991** [comment]
Hii, I am try post using your API but error came "Server got a conflicting upload id". and post some video only upload images not video.
