### ISSUE TITLE
Get followers capped at 200 users

### ISSUE THREAD

**Issue by hancux** [mgp25/Instagram-API#372]
Hi,

Great work for the API! 
I am planning to use this API to get the whole list of some username followers.
However, when I call this command :

> $i->getUserFollowers($usernameToSearch);

I only able to get the first 200 followers.

I tried using it with :

> $i->getUserFollowers($usernameToSearch, 1000);

and I get an empty result.

Any ideas?

Thanks! =)

**Comment by hancux** [comment]
sorry found the solution. i am using max id incorrectly. thanks!

**Comment by entezarlifedesign** [comment]
hello

max_id is null @hancux and show only 1000 user

What should we do?

Thank you
