### ISSUE TITLE
App Implementation

### ISSUE THREAD

**Issue by MasonBurdette** [mgp25/Instagram-API#374]
Hello!

I am very new to programming, so sorry if this isn't an issue, I just need some help making it.

I am currently working on developing an app, where users follow/like other users/post for coins.  Then those coins are used for more follows/likes.  Basically a promotion service for Instagram. 

So my main question is how would I use this repo in a Swift app?  Once again, I'm a beginner, so don't hate on me for being a noob.

Thanks.

**Comment by stpnov** [comment]
You can send the request to the backend, backend has to fulfill the request.

**Comment by MasonBurdette** [comment]
@stpnov Ok I was just being dumb.. Thanks 👍 !
