### ISSUE TITLE
getMediaComments empty comments array

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#375]
Hi, very frequently I am getting an empty comments array (for medias with `comment_count >0`) when I do a `getMediaComments` request. Other requests I make for the same `mediaId` on the same script, like `getMediaLikers`, work fine.

Has someone else had this issue? Any possible work around?

Thanks!

**Comment by joseflorido** [comment]
This is working fine now. Looks like it was a temporary problem from Instagram API itself.

**Comment by simsekanil** [comment]
Hi, I use another repo, but when I query media comments quickly, Instagram starts to send empty arrays. I think Instagram detects inhuman behaviour and applies some kind of a soft ban. After sometime it works fine again. Does anyone know how to get over this problem? It is really annoying...
