### ISSUE TITLE
Can not register success.

### ISSUE THREAD

**Issue by c3887518** [mgp25/Instagram-API#378]
{"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There's a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_action": "report_problem", "feedback_url": "repute/report_problem/instagram_signup/", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Report problem"} Error during registration.

**Comment by mgp25** [comment]
`"spam": true`

**Comment by adiumin** [comment]
From any ip, any country include ipv6 only i get 'spam": true'
