### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by ItsASmallWorld** [mgp25/Instagram-API#379]
I get the following error when trying to login:

RESPONSE: {"status": "fail", "lock": true, "message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/integrity/checkpoint/checkpoint_logged_out_main/44851781/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss"}

ERROR: checkpoint_required

My code is below:

```
`$instagram = new \InstagramAPI\Instagram($username, $password, $debug);

try {
        $instagram->login();

} catch (Exception $e) {

        echo 'ERROR: ';
        echo $e->getMessage();
        exit();

}
`
```

**Comment by jpmoney5065** [comment]
It looks like the login failed, I think that you account may be locked and could require a checkpoint.

**Comment by ItsASmallWorld** [comment]
Thanks.  How do I use a checkpoint in code using the API?

**Comment by jpmoney5065** [comment]
[checkpoint.php](https://github.com/mgp25/Instagram-API/blob/master/src/Checkpoint.php)
[example](https://github.com/mgp25/Instagram-API/blob/master/examples/checkpoint.php)

**Comment by ItsASmallWorld** [comment]
Thanks!

**Comment by h-2-0** [comment]
@jpmoney5065 , @ItsASmallWorld 

Is Checkpoint.php still working? I'm not a PHP guy but 'll attempt to translate it into Python. Thanks!

**Comment by mangledbottles** [comment]
@h-2-0 yes, last time I checked it was working, you need to run it CLI though

**Comment by h-2-0** [comment]
@mangledbottles

Thanks! Since I don't know PHP at all I will try to port it and run it via [https://github.com/LevPasha/Instagram-API-python/](https://github.com/LevPasha/Instagram-API-python/).
