### ISSUE TITLE
Error while posting Photo

### ISSUE THREAD

**Issue by replay42** [mgp25/Instagram-API#385]
I get the response "Please update your Instagram app to continue posting photos" when I try to post a photo via the API.

Using basically the following script:
`$i = new \InstagramAPI\Instagram('username', 'password', false);`
`$i->login(); `
`$caption = "Caption"; `
`$imageurl = "http://url.com/image.jpg"; `
`$i->uploadPhoto($imageurl, $caption); `

Has someone else the same issue?

**Comment by replay42** [comment]
The format of the image was not accepted by Instagram, so the image could not be posted.
Kind of wrong error message but that's not the fault of the author of this script.
Thanks a lot for this one, works just great!
-- CLOSE --

**Comment by ezmanboy** [comment]
Are You understand the image format? There is an understanding supported by the proportions?

**Comment by replay42** [comment]
Just noticed it wasn't even the size / format of the image, what caused the problem.
It was the Caption I used.
In it, I used the letter " é ", which seems to cause a problem when using the api.

Using a different caption didn't cause the problem anymore, even using the first image I tried.

@ezmanboy, what do you mean with "understanding the image format"?

**Comment by ezmanboy** [comment]
There is a portrait image and landscape image. For example, if you use a portrait image with a height of 1080 px and a width of 600 px, the image will not boot due to incorrect proportions.
