### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#387]
Hello
İnstagram has 4 kınd of Checkpoınts
1. Phone Verıfy
2. Emaıl Checkpoınt (You get an emaıl and add the Code)
3. Captcha Challenge (Add Captcha to contınue)
4. Fırst tıme usıng thıs Scrıpt Challenge (You was logged ın from other place ) .-> Yes that was me

I want to get Response whıch Checkpoint the Account is. The scrıpt just gıves me checkpoınt_required response on any Checkpoınt.

**Comment by mgp25** [comment]
@doctorbinsibar post full response and i'll do it eventually

Regards

**Comment by doctorbinsibar** [comment]
`InstagramAPI\InstagramException Object
(
    [message:protected] => checkpoint_required

    [string:Exception:private] => exception 'InstagramAPI\InstagramException' with message 'checkpoint_required
' in /public_html/vendor/mgp25/instagram-php/src/Instagram.php:836
Stack trace:
#0 /public_html/vendor/mgp25/instagram-php/src/Instagram.php(203): InstagramAPI\Instagram->getv2Inbox()
#1 /public_html/auto_liker.php(91): InstagramAPI\Instagram->login()
#2 {main}
    [code:protected] => 0
    [file:protected] => /public_html/vendor/mgp25/instagram-php/src/Instagram.php
    [line:protected] => 836
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => public_html/vendor/mgp25/instagram-php/src/Instagram.php
                    [line] => 203
                    [function] => getv2Inbox
                    [class] => InstagramAPI\Instagram
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [1] => Array
                (
                    [file] => public_html/insta_liker.php
                    [line] => 91
                    [function] => login
                    [class] => InstagramAPI\Instagram
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

        )

    [previous:Exception:private] => 
)`

**Comment by mgp25** [comment]
@doctorbinsibar no, i meant response, you need to capture the request and response so i can implement everything

**Comment by doctorbinsibar** [comment]
at this point you even cant see if account is deleted maybe.
just 'checkpoint_required' maybe because it saves the cookies. But when i try to login manually the account seems to be deleted.

`REQUEST: si/fetch_headers/?challenge_type=signup&guid=07d6ce0458224f1e9ed7da40c65cb952 RESPONSE: {"status": "ok"} REQUEST: accounts/login/ DATA: ig_sig_key_version=4&signed_body=ccee6e474d387b1ec8f699128d4241049888f913bad79a244ad091db20e96a24.{"phone_id":"6ebedbf2-32f6-4dee-acaf-2f6ab6acd427","_csrftoken":"Set-Cookie: csrftoken=oCUV87DCfnpplr8o90M1BHtSnJu9ESoS","username":"midorofeeva55447","guid":"24ffe8b2-58cf-4bd3-b610-f46284b65efc","device_id":"android-7239f808da00fd80","password":"m0uDy8Np","login_attempt_count":"0"} RESPONSE: {"status": "fail", "lock": true, "message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/challenge/3570107860/"} `


If you can tell me how to capture the endpoints of İnstagram App, i can try to make a checkpoint APİ whıch actually mıght work solving Checkpoints.

**Comment by doctorbinsibar** [comment]
`REQUEST: si/fetch_headers/?challenge_type=signup&guid=c62392ab4b5a4f989b4d4b350cd57a95 RESPONSE: {"status": "ok"} REQUEST: accounts/login/ DATA: ig_sig_key_version=4&signed_body=e64c49f567967eeb60fe0ce5fc2596fe57b0143c6b3ed41633fcdea2c34355d3.{"phone_id":"8de825e4-363e-4355-bdec-99b48986e5bf","_csrftoken":"Set-Cookie: csrftoken=ctioQaC325zWvG1KeyGWdfZ69P9Fnj39","username":"dostepanova52061","guid":"740c26d9-6f92-4cf4-8b4f-f9901ebfaba6","device_id":"android-dc4f48290ff78b01","password":"CkgjAXge","login_attempt_count":"0"} RESPONSE: {"status": "fail", "lock": true, "message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/integrity/checkpoint/checkpoint_logged_out_main/3554374395/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss"} `


This Response shows me the Email Verifıcation Checkpoint
see here: http://imgur.com/a/z2gmJ

**Comment by mgp25** [comment]
Use the checkpoint example

Regards

**Comment by doctorbinsibar** [comment]
`REQUEST: si/fetch_headers/?challenge_type=signup&guid=aa74c46a8039465eb11664f703f9849b RESPONSE: {"status": "ok"} REQUEST: accounts/login/ DATA: ig_sig_key_version=4&signed_body=2a80869b3106c0d396749e2a27bffc56ad1a86926279272faa741fad13c8f798.{"phone_id":"4e8ff0c2-c74c-4f0e-b773-5bd3a8722289","_csrftoken":"Set-Cookie: csrftoken=2baKnkGDlqU80e9Nnswuhi9DUtzeXC0t","username":"teshiryaeva36288","guid":"865681be-8346-4e3a-9be4-ad3508e00248","device_id":"android-dfa15d60afe816f7","password":"mxVOEOaF","login_attempt_count":"0"} RESPONSE: {"status": "fail", "lock": true, "message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/challenge/3554640371/"} `


This Response is from Phone Verify
http://imgur.com/a/sk7gZ

**Comment by doctorbinsibar** [comment]
your checkpoint example doesnt work for me.
İ didnt get any email and if Debug ıt shows me full instagram error page.
There ıs somethıng wrong there ıs even no $token

**Comment by doctorbinsibar** [comment]
you solve other checkpoints too or the email checkpoınt only ?
Thıs would be good feature request.
Solving other Checkpoınts :8ball:
