### ISSUE TITLE
Error On Install

### ISSUE THREAD

**Issue by apriady** [mgp25/Instagram-API#388]
Hi,
when i try to run this code : 
`composer require mgp25/instagram-api master`
it will give me error like this
![screen shot 2016-08-26 at 22 43 34](https://cloud.githubusercontent.com/assets/1451429/18011475/950d8720-6bdf-11e6-8eaf-ce89f41ae811.png)
what is the problem? is it a typo in package name, or something else?
what command should i use when i want to use master branch?
`composer require mgp25/instagram-api master`
or
`composer require mgp25/instagram-php master`

ps: sorry for my bad english

**Comment by mgp25** [comment]
`composer require mgp25/instagram-php master`

It was a typo in the readme, fixed

Regards
