### ISSUE TITLE
Phone Verify Checkpoint

### ISSUE THREAD

**Issue by derjrjr** [mgp25/Instagram-API#389]
Hello,
Could you add the phone verify checkpoint?
There are 2 actions;
1) Requesting the SMS code be send to a number
2)Inputting the SMS code to verify

Here are the iOS API request URLs with parameters:

1)
URL:
https://i.instagram.com/api/v1/accounts/send_sms_code/
Parameters:
_csrftoken, _uuid, _uid, device_id, phone_number

2)
URL:
https://i.instagram.com/api/v1/accounts/verify_sms_code/
Paramters:
_csrftoken, _uuid, _uid, device_id, phone_number, verification_code

Thanks

**Comment by mgp25** [comment]
@derjrjr post full header and body if possible and i code the request. You can send it to my mail if you prefer it

Regards

**Comment by c3887518** [comment]
without full header...
