### ISSUE TITLE
login failed 

### ISSUE THREAD

**Issue by beljk** [mgp25/Instagram-API#39]
@mgp25  I can't login

accounts/login/ DATA: ig_sig_key_version=4&signed_body=6348d634e3fccd60e1c11d9e32c359a71628fc8164bf966397e68e32307c2e89.%7B%22device_id%22%3A%22android-e68a83370faacfab%22%2C%22guid%22%3A%22ae19c151-0d8b-45f6-adc3-74631fcab6f3%22%2C%22username%22%3A%22bexxxxxx%22%2C%22password%22%3A%22Ahxxxxxxxxxxxxxxxx%22%2C%22csrftoken%22%3Anull%2C%22login_attempt_count%22%3A%220%22%7D RESPONSE

**Comment by mgp25** [comment]
@beljk its working perfectly, delete auth files and retry again, if required, login first with a device and then with the api

Regards

**Comment by beljk** [comment]
I have the same issue and tested in another so what's wrong ?? I am newer in php and I only setup xampp and run apache @mgp25
