### ISSUE TITLE
Oops error occured at data configure

### ISSUE THREAD

**Issue by karankundre** [mgp25/Instagram-API#4]
in uploadphoto()

string(588) "HTTP/1.1 100 Continue Date: Sat, 05 Dec 2015 08:11:38 GMT HTTP/1.1 500 INTERNAL SERVER ERROR Server: nginx Date: Sat, 05 Dec 2015 08:11:39 GMT Content-Type: text/html; charset=utf-8 Content-Language: en Expires: Sat, 01 Jan 2000 00:00:00 GMT Vary: Cookie, Accept-Language X-Instagram-Ssl-Everywhere: True Pragma: no-cache Cache-Control: private, no-cache, no-store, must-revalidate Set-Cookie: csrftoken=62b92b571b7473e1d39f3bf72be7018e; expires=Sat, 03-Dec-2016 08:11:39 GMT; Max-Age=31449600; Path=/ Connection: keep-alive Content-Length: 25 Oops, an error occurred. "

REQUEST: media/configure/ DATA: 
RESPONSE: Oops, an error occurred. object(Instagram)#1 (9) 

failed to configure

**Comment by mgp25** [comment]
@karankundre it seems its an error at your side not API issue.

Regards

**Comment by pseeker** [comment]
Hi)
I had a similar problem.
line 145 (Instagram.php):
'data' => round(microtime(true)*1000)

My hosting generates: 1.44931326721E+12
Need: 1449313267213

I have corrected: 'data' => round(microtime(true)*100)

hosting generates: 144931326721

Now upload photo working, but instagram does not index these photos. Search this photo on the hashtag does not work.

I figured there must be thirteen digits: round(microtime(true)*1000).

**Comment by mgp25** [comment]
@pseeker please quote things properly.

In the API the upload id is set to `round(microtime(true)*1000)` which is 13 digits. It's working pretty fine to me.

Regards

**Comment by mgp25** [comment]
@pseeker send a pull request

**Comment by aliguzz** [comment]
This is  the great solution! Thanks @pseeker thank you very much for your answer it worked.

**Comment by ericmuigai** [comment]
@pseeker thanks for the help. Worked for me.
