### ISSUE TITLE
syncFromAdressBook issue

### ISSUE THREAD

**Issue by beljk** [mgp25/Instagram-API#40]
@mgp25  address_book/link/?include=extra_display_name,thumbnails RESPONSE: Oops, an error occurred. is a must to search one by one ? I searched one and works fine but if I search with multiple I got this issue

$Contacts = array(
	array(
    'first_name' => 'whatever',
    'phone_numbers' => array('20101043xxx','+20100105xxx', '+201000967xxx','+201000409xxx'),
    'email_addresses' => array('whatever@gmail.com','whatever@gmail.com','whatever@gmail.com','whatever@gmail.com')
  )

**Comment by mgp25** [comment]
Post full debug, post verbose of the request, if you don't know how to do it, search in google, with that i can't know the issue
