### ISSUE TITLE
How to get all inbox data? ( getv2Inbox only get the last conversation )

### ISSUE THREAD

**Issue by nanangkoesharwanto** [mgp25/Instagram-API#400]
**SOLVED**.

get all inbox data by using `directThread($threadId)`

**Comment by SachinPendse** [comment]
@nanangkoesharwanto How did you get a list of all of the threadids in the Inbox?

**Comment by c0d3n1nj4** [comment]
$inbox = $i->getv2Inbox();
$tIdArr = array();
foreach ($inbox->getInbox()->getThreads() as $threads) {
  $tIdArr[] = $threads->thread_id; // do whatever you want to the thread_id
}
