### ISSUE TITLE
Uncaught Error: Class 'InstagramAPI\SignatureUtils' not found

### ISSUE THREAD

**Issue by rizkihape** [mgp25/Instagram-API#402]
Hi,
This is my first code and i don't know how to fix this problem

thank you :)

**Comment by nanangkoesharwanto** [comment]
on what function did u find this error?

**Comment by rizkihape** [comment]
Instagram.php Line 40

 this function : 

$this->device_id = SignatureUtils::generateDeviceId(md5($username.$password));

**Comment by nanangkoesharwanto** [comment]
I have no idea, may be try to download again the Instagram-API will fix it.

**Comment by rizkihape** [comment]
oke makasih :)

**Comment by nanangkoesharwanto** [comment]
try to dump-autoload proccess. sometimes the class is not recognized yet.

**Comment by mgp25** [comment]
@rizkihape use composer

Regards
