### ISSUE TITLE
No next_max_id on getUserFollowers and getUserFollowing

### ISSUE THREAD

**Issue by ismailcaakir** [mgp25/Instagram-API#411]
Merhaba, ( Türkçe yazıyorum durumu açıklamak için google translate ile çevirebilirsiniz )

Ben kullanıcımın takipçilerini ve takip ettiklerini veri olarak çekmek istiyorum fakat bana next_max_id değerini vermiyor.

**Comment by mgp25** [comment]
@ismailcaakir i dont understand your language, write it in English so everyone can understand you. Dont post all the requests only the one you are refering too.

You can add it and send it in a Pull Request

Regards

**Comment by polyskalov** [comment]
@ismailcaakir can you try with `getUserFollowers->getNextMaxId()` method?
Other reason — not so many users in answer.

**Comment by ismailcaakir** [comment]
Master ( Geliştirilen ) sürüme güncelledim. Problem çözüldü teşekkür ederim ilgilendiğiniz için.
