### ISSUE TITLE
Is instagram actually returning gzipped responses?

### ISSUE THREAD

**Issue by maddo7** [mgp25/Instagram-API#412]
I've seen some requests have an added Accept-Encoding: gzip header but does Instagram return gezipped responses? I've only seen non-encoded responses so far.

**Comment by mgp25** [comment]
You can check it capturing device requests

Regards

**Comment by maddo7** [comment]
I have done that and never seen gzipped responses that was why I asked here. I couldn't believe such a big company like facebook is wasting so much traffic.
