### ISSUE TITLE
Is this script (instagram API) support «create_many» method?

### ISSUE THREAD

**Issue by polyskalov** [mgp25/Instagram-API#413]
In some old script i seen requests to API like `friendships/create_many/async/` and `friendships/show_many/?user_ids=`.

I try to request this method, and instagram says «Invalid parameters».
Is this method not supported anymore by instagram API or i do something wrong?

**Comment by mgp25** [comment]
@polyskalov i dont know, it seems you are mixing public api stuff with private api stuff

As i said before im not sure.

Regards
