### ISSUE TITLE
create account failed

### ISSUE THREAD

**Issue by beljk** [mgp25/Instagram-API#42]
the username is available 

Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\Instagram-API-master\examples\registrationTool.php on line 21

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\Instagram-API-master\examples\registrationTool.php on line 21
 REQUEST: users/check_username/ DATA: ig_sig_key_version=4&signed_body=3232f2a93bb529db8f18f2daaa8d54cd0164e815e187d59e60af76cfe030ecee.%7B%22_uuid%22%3A%22beec3f3d-5eb4-49cb-80f8-d98855273f49%22%2C%22username%22%3A%22%22%2C%22_csrftoken%22%3A%22missing%22%7D RESPONSE: Username not available, try with another one Username: 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\Instagram-API-master\examples\registrationTool.php on line 21

**Comment by mgp25** [comment]
@beljk im glad you like my API but this issue tracker is for API issues not PHP ones, you are using a CLI script, CLI = Command Line Interface

Regards

**Comment by beljk** [comment]
I follow you and interesting in your projects , I hope to be like you ;) 
can you describe what do you mean ? and tell me how to fix it ?

Best Regards

**Comment by mgp25** [comment]
Is not something you can fix, i think you should search some guides, learn programming and once then, come back here. Its a CLI script which means is supposed to be executed in a terminal or command line
