### ISSUE TITLE
Registration with phone do not work anymore

### ISSUE THREAD

**Issue by hypertech** [mgp25/Instagram-API#422]
Hello, I found earlier that phone registration was on endpoint : "accounts/send_signup_sms_code/", but yesterday this stop to work and start to return "invalid request". Anybody found new endpoint or new list of the params ?

**Comment by jpmoney5065** [comment]
No part of this API uses that endpoint.

**Comment by hypertech** [comment]
So you do not want to do some research about this ?

**Comment by jpmoney5065** [comment]
You can code a function and make a pull request.

Or  at least post full header and body.
