### ISSUE TITLE
how to get comment_id for deleteComment function?

### ISSUE THREAD

**Issue by nanangkoesharwanto** [mgp25/Instagram-API#423]
I need helps about how to get comment id.

I did using **mediaInfo($mediaId)**.
the function return:
```
MediaInfoResponse {#883 ▼
  +taken_at: 1472570120
  +image_url: "http://instagram.fcgk5-1.fna.fbcdn.net/t51.2885-15/e35/14134871_1243786265666679_1951058561_n.jpg?ig_cache_key=MTMyODMzNjkwNzY1MDE1NTIzMg%3D%3D.2"
  +like_count: 1
  +likers: array:1 [▶]
  +comments: array:4 [▼
    0 => Comment {#885 ▼
      +status: "Active"
      +username_id: 230866XXX.0
      +created_at_utc: 1473219957
      +created_at: 1473219957
      +bit_flags: null
      +user: User {#882 ▶}
      +comment: "9th"
      +pk: 17862408649053XXX.0
      +type: null
      +media_id: 1328336907650155XXX.0
    }....
```

I also use function **getMediaComments($mediaId)**, it return:

```
array:6 [▼
  "status" => "ok"
  "caption_is_edited" => false
  "has_more_comments" => false
  "comments" => array:12 [▼
    0 => array:10 [▼
      "status" => "Active"
      "user_id" => 2308661XXX.0
      "created_at_utc" => 1473208105
      "created_at" => 1473208105
      "bit_flags" => 0
      "user" => array:6 [▶]
      "content_type" => "comment"
      "text" => "first comment"
      "pk" => 17862400573053XXX.0
      "type" => 0
    ]...
```

then I use 'pk' in 'comments' fields as comment id in function **deleteComment($mediaId, $commentId)**.
the function return:

```
array:1 [
    "status" => "ok"
]	
```		

when I check in my Instagram account, the comment is still, not deleted.

I tried using **deleteCommentsBulk($mediaId, $commentIds)**, but it return:
```
array:2 [
  "status" => "fail"
  "message" => "You cannot delete these comments"
]
```

any advice please...

**Comment by mgp25** [comment]
@nanangkoesharwanto it works fine, just tested it. Your php config if gicing you a decimal value `17862400573053XXX.0` and instead it should be an integer value `17862400573053XXX`

If you change config or do this `intval($res->getCommentId())` or `intval('17862400573053XXX.0')`

Regards
