### ISSUE TITLE
Fiddler

### ISSUE THREAD

**Issue by MMrR0b0TT** [mgp25/Instagram-API#427]
I've tried to get the endpoints as I did in the past, but I couldn't.
What do you use? I've used Fiddler in the past, but now I'm getting this message:

"HTTP/1.1 Request was missing the required HOST header."

**Comment by mgp25** [comment]
I dont use any software to capture traffic, i have my own ways. anyway, there are a lot of alternatives out there and remember to disable cert pinning.

Regards

**Comment by beshoo1** [comment]
>> i have my own ways
It will be kindness from you if you share that !
