### ISSUE TITLE
No return search by hashtags

### ISSUE THREAD

**Issue by secretcau** [mgp25/Instagram-API#430]
Hi.

My problem is Searching issue in instagram app and web page.
I couldn't search using for every tags, when i posted pictrue from this api.

(I could find that the number of posts, but I couldn't see any post on the return list)

But i remember that i could search using hashtags, before several weeks.

What is a solution? Is there any my mistake such as writing banned hashtags?

**Comment by mgp25** [comment]
Sometimes works sometimes not, i dont know if its Instagram or API issue, but its not very important at the moment. If you want, capture the request and send a pull request.

Regards

**Comment by secretcau** [comment]
It always doesn't work these days. I think maybe instagram has changed their system. But i hope that my opinion isn't truth. The problem is very inportant my app. I really wish to solve.

**Comment by mgp25** [comment]
If you really wish to solve this so bad, start researching would be a good option instead of waiting for a solution from other/s, what do you think?

**Comment by secretcau** [comment]
Thanks, I already start researching by myself. But i couldn't find a solution. Din't even works i upload with a picture and only one hashtag. HaHa.... I wonder if this API's other users have a same problem.
