### ISSUE TITLE
Set location when uploading a photo/video

### ISSUE THREAD

**Issue by jonatanfroes** [mgp25/Instagram-API#431]
Hi!

I'd like to get and set the picuture location when uploading a photo or video. Is it possible?

**Comment by mgp25** [comment]
I'll be adding it tonight

Regards

**Comment by mgp25** [comment]
@jonatanfroes you can add now a location while uploading a photo.

You need to use  `searchLocation`, use `getVenues()` function to see all location, when you find the one you want to set, just pass that object, for example `getVenues()[2]` in the last param of `uploadPhoto`

Regards

**Comment by jonatanfroes** [comment]
Thanks! @mgp25

**Comment by SubodhDahal** [comment]
I get an `Call to undefined method stdClass::getExternalIdSource()` error while passing `getVenues()[2]` as the last parameter to `uploadPhoto`. Following is the code I used:

    ...
    $locations = $i->searchLocation($input['location']['latitude'], $input['location']['longitude']);
    $i->uploadPhoto($photo, $caption, null, null, $locations->getVenues()[2]);

The method `$locations->getVenues()[2]` does contain a valid `stdClass` object.
