### ISSUE TITLE
getUserFollowers 404 Not found

### ISSUE THREAD

**Issue by wehmoen** [mgp25/Instagram-API#432]
Hi,

i tried to get the user followers but the Response is always null.
I used `var_dump` on 
```php
$this->http->request("friendships/$usernameId/followers/?max_id=$maxid&ig_sig_key_version=" . Constants::SIG_KEY_VERSION . "&rank_token=$this->rank_token"));
```

and the result was:
```
object(InstagramAPI\http\Response\FollowerResponse)#24 (5) {
  ["followers":protected]=>
  NULL
  ["next_max_id":protected]=>
  NULL
  ["status":protected]=>
  NULL
  ["message":protected]=>
  NULL
  ["fullResponse":protected]=>
  NULL
}
```

Is there a new Endpoint for this request?

**Comment by mgp25** [comment]
@wehmoen i just tested it and it works great. Make sure you are passing the correct `username_id`. If you request users too often, you wont get any response by the server.

Regards
