### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by hypertech** [mgp25/Instagram-API#433]
Hello guys. I get something new when try to upload image. My acc is verified with phone, but i get 
{"status": "fail", "lock": true, "message": "checkpoint_required", "checkpoint_url":"https://i.instagram.com/challenge/", "_messages": [{"key": "update_push_token", "time": 1473353051.84}]}

What is it up to ?
Thanks

**Comment by hypertech** [comment]
It happen not on uploading, it happen on second login to acc.

**Comment by mgp25** [comment]
Duplicated
