### ISSUE TITLE
Undefined index: feed_aysf

### ISSUE THREAD

**Issue by ismailcaakir** [mgp25/Instagram-API#436]
Ben giriş yaparken sorun yaşıyorum.

ErrorException in TimelineFeedResponse.php line 40:
Undefined index: feed_aysf

[http://prntscr.com/cfr6i2](http://prntscr.com/cfr6i2)

This Line:
`            $this->megaphone = (isset($response['megaphone'])) ? new FeedAysf($response['megaphone']['feed_aysf']) : null;
`

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/commit/45d32b23c0ff3b222d394865e688939d619fddc2
