### ISSUE TITLE
Sorry, too many requests. Please try again later error

### ISSUE THREAD

**Issue by snapmaster** [mgp25/Instagram-API#438]
Hello!

Each time I login I get this error:
```
REQUEST: friendships/autocomplete_user_list/
RESPONSE: {"status": "fail", "message": "Sorry, too many requests. Please try again later."}
```

**Comment by jpmoney5065** [comment]
Not a problem with the API.

Check how many requests are going from your server to instagram.

Make less requests.

**Comment by RiTu1337** [comment]
It's not a rate limit issue, this request always gets that error.

**Comment by mgp25** [comment]
@RiTu1337 normal behaviour
