### ISSUE TITLE
Pagination for getting user followings is not working

### ISSUE THREAD

**Issue by MarkoSulamagi** [mgp25/Instagram-API#441]
Getting user followers pagination is working properly, but for followings it's not.
If I use pagination key I get from query then I still get the same results (accounts) as without pagination key.

**Comment by mgp25** [comment]
Send a pull request and ill merge it

Regards

**Comment by h-2-0** [comment]
@MarkoSulamagi 

Can you still paginate user's followers? I was able to do it last week but not any more (although I'm using a Python based port).

**Comment by MarkoSulamagi** [comment]
Yes, I can still paginate followers. I tested multiple Python and PHP libraries. Followers pagination works fine.

Followings pagination is still not working and I don't know how to make it work. I decompiled the latest Android Instagram APK to see how they were using the followings API in their code. It seemed to be doing the same thing as this library does so I hit a dead end. 
I don't really know how to debug this thing.

**Comment by mgp25** [comment]
Fixed in latest commit

**Comment by MarkoSulamagi** [comment]
Thank you!

**Comment by h-2-0** [comment]
Thank you, both @MarkoSulamagi  and @mgp25 !!!
