### ISSUE TITLE
hashtag search doesn't work

### ISSUE THREAD

**Issue by secretcau** [mgp25/Instagram-API#443]
Hi. I couldn't find a solution for #430, yet.

I have updated this api and using only one hashtag. But i can't get a result of searching with hashtag.

**Comment by jd440** [comment]
same for me!

**Comment by secretcau** [comment]
Really? I saw another person having same problem. #435 
We can try to find a solution! And I wish API's admin help to us.

**Comment by mgp25** [comment]
Oks, research about it, its as simple as capturing the request, once you have it send a pull request.

If you have any programming issue, there is a lot of documentation in google, also check wiki for any extra information.

Regards

**Comment by jpmoney5065** [comment]
This is a Instagram anti spam thing that happened earlier this week. It's not this API's problem. Happening with other Instagram API/software.

**Comment by secretcau** [comment]
Thanks. I send a email with some capture file.

@jpmoney5065 Really? Uhm... But I only use this api. If it caused anti spam issue, what is a solution?

**Comment by jd440** [comment]
@mgp25 thanks
thanks. what do you use to caputuring request? "charles-proxy"?

**Comment by jd440** [comment]
I'm surprised, I capture request with "charles-proxy" when I'm posting pic with tag.
And I noticed app made different request:
- upload/photo
- tag/search
- media/configure

But it seems even if we choose one tag from returning list of RESPONSE to the tag/search REQUEST, the media/configure/ REQUEST doesn't change or doesn't include any id?

what did i missed something?

**Comment by jpmoney5065** [comment]
@secretcau stop following so many people

**Comment by jd440** [comment]
But the hashtag isn't new as mention by @jpmoney5065

When I tried with code developped from the article of @lancenewman and @mokhdzanifaeq  las t year I had the same problem.

**Comment by jpmoney5065** [comment]
Instagram has you/your accounts/your ip addresses marked as spam because you follow too many people/send too many direct messages/post duplicate photos and comments/act generally in a non-human fashion. 

You are banned from using hashtags.
If you have a solution as to how to avoid this post it or make a pull request.
