### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by derjrjr** [mgp25/Instagram-API#444]
Hello,
Im having an issue using proxies with the API.
I was using the API and came across this:
when I just try to log in without a proxy I get normal response etc but when I try to log in with a proxy, debug returns this-
```[1;34mGET: [0mfeed/timeline/ [0;32m← 0 0B[0m [0;36mRESPONSE: [0m [1;34mGET: [0mfriendships/autocomplete_user_list/?version=2 [0;32m← 0 0B[0m [0;36mRESPONSE: [0m [1;34mGET: [0mfeed/reels_tray/ [0;32m← 0 0B[0m [0;36mRESPONSE: [0m```

*Github does not support all the unicode so some letters dont show, so here is a screenshot: http://prntscr.com/cgjeda *

I am using a private proxy that does work so that is not the problem, is it that the proxy timed out or something as I do not understand that API response...

Thanks :)

**Comment by mgp25** [comment]
It's proxy issue, not API, try with other one

Regards

**Comment by jpmoney5065** [comment]
Proxies through the API are working fine.

Instagram doesn't like you proxy or your server is configured incorrectly.

**Comment by derjrjr** [comment]
Im using the same proxy through a program called FollowLiker and it is working fine.. could you atleast explain that response?
Thanks

**Comment by mgp25** [comment]
@derjrjr what response? there is none, that chars are for formating strings with colours, it seems you are running it in webserver and not CLI.

**Comment by derjrjr** [comment]
yea, Im trying to build a webserver application
what can I do to try and fix this? The proxy seems to be working fine in other programs, maybe im using it wrong in this script?

**Comment by mgp25** [comment]
@derjrjr maybe you have configured in a wrong way, or just simply Instagram doesnt like the proxy and refuse connection, in any of the cases, is not an API issue

Regards

**Comment by derjrjr** [comment]
Ok I will test around with it
Can I email you the SMS checkpoint headers like you asked in a issue before?
