### ISSUE TITLE
getMediaLikers returns empty

### ISSUE THREAD

**Issue by mahmoud015** [mgp25/Instagram-API#445]
hi,

i use this code to getMediaLikers but it always get empty

`try {
    $i->getMediaLikers($mediaId);
} catch (Exception $e) {
    echo $e->getMessage();
}`

not getMediaLikers only but any get request get empty

please give me the correct code to get the array

thank you.

**Comment by mgp25** [comment]
Works fine, make sure you passed as param a correct `media_id`

Regards

**Comment by mahmoud015** [comment]
i think media_id is not the problem because the same code works fine with other requested like Like/unlike a video or photo and Upload Photo and video 

is there any code i have to add because i use the example uploadPhoto.php to do all of request

**Comment by mahmoud015** [comment]
should i make $debug = true; ?
