### ISSUE TITLE
hashtag search doesn't work #2

### ISSUE THREAD

**Issue by Mifody** [mgp25/Instagram-API#448]
не могу ответить в "hashtag search doesn't work #443"
my little research:

photo created on a computer
1. https://www.instagram.com/p/BKOMaYfATZm/ posted with my phone and searched by hashtag
2. https://www.instagram.com/p/BKLNiAvg0rf/ posted with my computer and NOT searched by hashtag

photo created on a phone
1. https://www.instagram.com/p/BKLNLEIAjJh/  posted with my phone and searched by hashtag
2. https://www.instagram.com/p/BKLQS8jglbI/ posted with my computer and NOT searched by hashtag

all posts posted with one IP & account
any ideas? 

P.S. sorry for my very bad english :))

**Comment by mgp25** [comment]
Not valid.

Regards

**Comment by jpmoney5065** [comment]
Same problem as everybody is having. 
Not just this API, affecting other API's as well.
