### ISSUE TITLE
Error during registration.

### ISSUE THREAD

**Issue by iStorry** [mgp25/Instagram-API#450]
###########################
#                         #
# Instagram Register Tool #
#                         #
###########################

Username: abc
Username abc is available

Password: abc

Email: abc@gmail.com

Name (Optional): 
Error during registration.

InstagramAPI\AccountCreationResponse Object ( [username:protected] => [has_anonymous_profile_picture:protected] => [allow_contacts_sync:protected] => [nux_private_first_page:protected] => [profile_pic_url:protected] => [full_name:protected] => [pk:protected] => [hd_profile_pic_url_info:protected] => [nux_private_enabled:protected] => [is_private:protected] => [account_created:protected] => [feedback_title:protected] => Signup Error [feedback_message:protected] => Sorry! Thereâ€™s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake. [spam:protected] => 1 [feedback_action:protected] => report_problem [feedback_url:protected] => repute/report_problem/instagram_signup/ [errors:protected] => [status:protected] => fail [message:protected] => feedback_required [fullResponse:protected] => ) Error during registration.

**Comment by mgp25** [comment]
Instead of dumping the variable, set `true` to `$debug`  there is a built-in debug log.

Instagram has detected you as spam

Regards
