### ISSUE TITLE
Uploading video issue

### ISSUE THREAD

**Issue by honeydewkorea** [mgp25/Instagram-API#451]
I built a system uploading photo, before.
Now, i am making a logic related to upload a video.
However, it just returns error messages.

I tried to use direct uploading mp4 file from my server and from insta server pre-uploaded URL.

What's wrong? Did i have a mistake?

> RESPONSE: {"status": "ok", "upload_id": "1473694396801"} REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=de7773e9055922019755c4495ffebee8904c76e4afcd0c277b3836d8454e39c8.{"upload_id":"1473694396801","camera_model":"KITE","source_type":3,"date_time_original":"2016:09:13 00:33:22","camera_make":"Wiko","edits":{"crop_original_size":[null,null],"crop_zoom":1.3333334,"crop_center":[0,-0]},"extra":{"source_width":null,"source_height":null},"device":{"manufacturer":"Wiko","model":"KITE","android_version":18,"android_release":"4.3"},"_csrftoken":"AMFUl1giSx12OexBR3yTcWjtWk1F4hpG","_uuid":"744e7e62-bfb3-4efd-9128-2185d1bb0036","_uid":3022105762,"caption":"#secretcau"} RESPONSE: {"status": "ok", "media": {"upload_id": "1473694396801"}, "message": "**media_needs_reupload**", "error_title": "**staged_media_missing**"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=ca883c0427f75cbb639e072c378b5ef0ccaf9aed1c800f074fc737465a385c75.{"_uuid":"744e7e62-bfb3-4efd-9128-2185d1bb0036","_uid":3022105762,"id":3022105762,"_csrftoken":"AMFUl1giSx12OexBR3yTcWjtWk1F4hpG","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"} REQUEST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=b6643da4c83b007723c2a5580f816fb9e71786c09c79f468caa5fd10ca5aee1e.{"upload_id":1473694396801,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":124,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"Wiko","model":"KITE","android_version":18,"android_release":"4.3"},"_csrftoken":"AMFUl1giSx12OexBR3yTcWjtWk1F4hpG","_uuid":"744e7e62-bfb3-4efd-9128-2185d1bb0036","_uid":3022105762,"caption":"#caption"} RESPONSE: {"status": "fail", "message": "**Other media configure error: yEmZkUpAj4**"} REQUEST: qe/expose/ DATA: ig_sig_key_version=4&signed_body=ca883c0427f75cbb639e072c378b5ef0ccaf9aed1c800f074fc737465a385c75.{"_uuid":"744e7e62-bfb3-4efd-9128-2185d1bb0036","_uid":3022105762,"id":3022105762,"_csrftoken":"AMFUl1giSx12OexBR3yTcWjtWk1F4hpG","experiment":"ig_android_profile_contextual_feed"} RESPONSE: {"status": "ok"}

**Comment by mgp25** [comment]
@honeydewkorea make sure you are using latest version of the code. Also keep in mind that not all videos fit in the upload. 

Try uploading from localhost and it should work

Regards

**Comment by honeydewkorea** [comment]
Thanks. I use 1.4 release, do i need an update to 1.4.2 version for uploading video?

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/
