### ISSUE TITLE
Uploading video issue #2

### ISSUE THREAD

**Issue by honeydewkorea** [mgp25/Instagram-API#458]
Thanks. The #451 is caused from my wrong code.

However, i see a different error msg, now.

> Uploaded image isn't in the right format

I know that the right format is mp4, 1x1 ratio, running time, file size. so i made suitable for the format.
But, i couldn't solve.

For second, i found video on instagram, and i downloaded my web server.
(https://scontent.cdninstagram.com/t50.2886-16/14207521_1675012109492522_273224933_n.mp4)

However, i can't upload a video. what's wrong?

**Comment by RiTu1337** [comment]
Try to change the video profile to baseline.

**Comment by mgp25** [comment]
Its video issue. Recommendation: record a video of 5 sec duration from your mobile device or try other .mp4 files until you get a working video you can use as base

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/
