### ISSUE TITLE
Can I update profile picture ?

### ISSUE THREAD

**Issue by vkill** [mgp25/Instagram-API#460]
Hi

[editProfile](https://github.com/mgp25/Instagram-API/blob/v1.4.2/src/Instagram.php#L913) can update Website, Bio, Email, Phone Number, Gender and Username, but cannot update Profile Picture.
So, can I update it ?

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L871

Please, try searching before opening a new issue.

Regards

**Comment by vkill** [comment]
oh, sorry, I used wrong search keyword.

**Comment by r00oobin** [comment]
Im sorry but I cant find the function
can you please help me?
there is a https://github.com/mgp25/Instagram-API/blob/c615a810812e4e7bcc66856f395e6eebfe1a0072/src/Instagram.php#L823
changeProfilePicture function but I think in an old version. Or I dont know
Can you may help me?
Greeting

Robin
