### ISSUE TITLE
Getting Oops, an error occurred.

### ISSUE THREAD

**Issue by iarcxxi** [mgp25/Instagram-API#462]
Hi
i wanna send direct message to a user with this api but i get: Oops, an error occurred.
i echo out $data , $header and $resp = curl_exec($ch); 
this is the log:

$data
`8d7780dd-0aee-4338-80a1-40735704acca Content-Disposition: form-data; name="recipient_users" [["myusername"]] --8d7780dd-0aee-4338-80a1-40735704acca Content-Disposition: form-data; name="client_context" 8d7780dd-0aee-4338-80a1-40735704acca --8d7780dd-0aee-4338-80a1-40735704acca Content-Disposition: form-data; name="thread_ids" ["0"] --8d7780dd-0aee-4338-80a1-40735704acca Content-Disposition: form-data; name="text" This is a Sample Text Sended From api! :) --8d7780dd-0aee-4338-80a1-40735704acca--`

------------------------
$header:

`Array ( [0] => Proxy-Connection: keep-alive [1] => Connection: keep-alive [2] => Accept: */* [3] => Content-type: multipart/form-data; boundary=8d7780dd-0aee-4338-80a1-40735704acca [4] => Accept-Language: en-en )`

------------------------
curl_exec($ch) : 

`HTTP/1.1 500 Internal Server Error Content-Language: en Expires: Sat, 01 Jan 2000 00:00:00 GMT Vary: Cookie, Accept-Language Pragma: no-cache Cache-Control: private, no-cache, no-store, must-revalidate Date: Tue, 13 Sep 2016 09:50:54 GMT Content-Type: text/html; charset=utf-8 Set-Cookie: csrftoken=uY9sy62LcND0S6LEPdVv69cE3xRDJLIT; expires=Tue, 12-Sep-2017 09:50:54 GMT; Max-Age=31449600; Path=/; secure Connection: keep-alive Content-Length: 25 Oops, an error occurred.`

and i am sure credentials are correct. ( setPrivateAccount() and setPublicAccount() works fine.)
Can you help me find out and fix issue? 

Thanks.

**Comment by mgp25** [comment]
It's not API issue: `500 Internal Server Error`
