### ISSUE TITLE
Login with facebook

### ISSUE THREAD

**Issue by sparkleappz** [mgp25/Instagram-API#463]
Hello Mate,

How we can implement login with facebook ? please provide the instructions.

Thanks
Surya

**Comment by mgp25** [comment]
You need to code it first, then send a pull request. If you dont know how to start read wiki or google

**Comment by sparkleappz** [comment]
is it possible to add to login with facebook with your private api ?

i am confused with your reply, can you please explain

**Comment by mgp25** [comment]
Yes, its possible to login with facebook using this API, but you need to code the function first

**Comment by sparkleappz** [comment]
can you please provide me hint .. how to code that or any link please

**Comment by mgp25** [comment]
of course: https://google.com and https://github.com/mgp25/Instagram-API/wiki

**Comment by sparkleappz** [comment]
mate you are not providing proper answer ... seriously it is possible ?
