### ISSUE TITLE
Set Proxy Error

### ISSUE THREAD

**Issue by PaulElM** [mgp25/Instagram-API#464]
I tried to use the setProxy function..
`$debug = true;

$r = new \InstagramAPI\InstagramRegistration($debug);
$ip = "211.63.185.211";
$port = "8080";
$r->setProxy($ip,$port);`
and hereis the error

`PHP Fatal error:  Uncaught exception 'InstagramAPI\InstagramException' with message 'Proxy host error. Please check ip
 address and port of proxy.' in /var/www/html/insta/vendor/mgp25/instagram-php/src/InstagramRegistration.php:71
Stack trace:
#0 /var/www/html/insta/index.php(12): InstagramAPI\InstagramRegistration->setProxy('211.63.185.211', '8080')
#1 {main}
  thrown in /var/www/html/insta/vendor/mgp25/instagram-php/src/InstagramRegistration.php on line 71`

**Comment by PaulElM** [comment]
I checked if the proxy ip and port is working on http://www.ip-adress.com/Proxy_Checker/ and it is "This Proxy from  	Korea, Republic of is working."
So what is the problem?

**Comment by mgp25** [comment]
Because Instagram doesnt like all proxies. If not, it will refuse to connect.

Not API issue

Regards

**Comment by jpmoney5065** [comment]
Change to:

```
$r = new \InstagramAPI\InstagramRegistration($debug);
$ip = "http://211.63.185.211";
$port = "8080";
$r->setProxy($ip,$port);
```

or

```
$r = new \InstagramAPI\InstagramRegistration($debug);
$ip = "http://211.63.185.211:8080";
$r->setProxy($ip);
```

**Comment by mahmoud015** [comment]
@jpmoney5065 thanks man adding http:// solve the problem :+1:

**Comment by mahmoud015** [comment]
i use the proxy like that and works fine 

`$i = new \InstagramAPI\Instagram($username3, $password2, $debug);

try {
    $i->setProxy($proxy);
} catch (Exception $e) {
    $e->getMessage();
    /*exit();*/
}
      
try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    /*exit();*/
}

try {
    $i->comment($mediaId, $commentText);
} catch (Exception $e) {
   echo $e->getMessage();
   
}

but dont forget http:// before the proxy`
