### ISSUE TITLE
comment id not found

### ISSUE THREAD

**Issue by kevinjon27** [mgp25/Instagram-API#466]
sir, I am using getMediaComments(), in comments array I dont get comment id, only PK. when I wanna delete comment using deleteComment($mediaId, $commentId); in $commentId I cannot put comment PK on that variable. how I can fix this? Thank you

**Comment by mgp25** [comment]
Use `deleteCommentsBulk` function instead

Regards

**Comment by kevinjon27** [comment]
sorry sir, my comment PK is 1.7851833718094E+16, so how I can convert to commentID.

**Comment by kevinjon27** [comment]
It's work now!
just add in php.ini precision = 20 and pk will return exactly what I need. Thanks anyway sir!
