### ISSUE TITLE
Getting one issue while pulling following list

### ISSUE THREAD

**Issue by sumandey121** [mgp25/Instagram-API#467]
Hello @mgp25 , Thanks for your great work first. 

I have started testing this script, since now everything looks good, but I stuck on a point and can not resolve.  I am trying to pull the "following" list of an user and I am getting first 200 of them in one request and then I have taken the next max ID from the first response to call the next 200, but I am getting always first 200 as results never the next 200 and so far. Not sure what is wrong, because the request getting everything necessary. Here is my code:
```
$nextMaxID = $users->getNextMaxId();
return $this->getUserTotalFollowings($usernameId, $nextMaxID);
```
$users has the result of first 200 and next max ID.

Please help me!!

Regards

**Comment by mgp25** [comment]
@sumandey121 

```php
$a = null;
do{
   if(is_null($a))
         $a = $this->getUserTotalFollowings($usernameId);
   else 
         $a =  $this->getUserTotalFollowings($usernameId, $a->getNextMaxId());
} while(!is_null($a->getNextMaxId()));
```
