### ISSUE TITLE
Account creation error? Is it IP Ban? 

### ISSUE THREAD

**Issue by d3vilsn0w** [mgp25/Instagram-API#468]
REQUEST: accounts/create/
DATA: ig_sig_key_version=4&signed_body=13219b7de1848eb95843900bd059c36a5ea5178014faccd188f9d8c02bc491d0.%7B%22allow_contacts_sync%22%3A%22true%22%2C%22phone_id%22%3A%22b7ea14c1-7bd6-4aeb-b53b-9441442d6fb4%22%2C%22_csrftoken%22%3A%22EY7eRV1GqHYnbRACbbRBVAlebksR4x09%22%2C%22username%22%3A%22lsadsad9123%22%2C%22first_name%22%3A%22%22%2C%22guid%22%3A%22b7ea14c1-7bd6-4aeb-b53b-9441442d6fb4%22%2C%22device_id%22%3A%22android-13f0ec2ad5f0910b%22%2C%22email%22%3A%22futhootteam%2Bsad%40gmail.com%22%2C%22force_sign_up_code%22%3A%22%22%2C%22waterfall_id%22%3A%22e96e7579-5f98-4512-9185-284f79843e3d%22%2C%22qs_stamp%22%3A%22%22%2C%22password%22%3A%22lasdasd123%22%7D
RESPONSE: {"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_action": "report_problem", "feedback_url": "repute/report_problem/instagram_signup/", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Report problem"}

I tried using a Proxy as well but no luck. 

        curl_setopt($ch, CURLOPT_PROXY, "PROXY:PORT");

**Comment by jpmoney5065** [comment]
API works.

You are flagged as spam

`"spam": true,`
