### ISSUE TITLE
hashtag

### ISSUE THREAD

**Issue by oratiostuff** [mgp25/Instagram-API#469]
This system can post a hashtag
**removed**

What I noticed take about 60 Seconds To post a picture

Please Let OS users do git hub, try to solve the topic and not close

**Comment by jpmoney5065** [comment]
We all know hashtags aren't searchable. Do you have any insight into the problem?

**Comment by oratiostuff** [comment]
no, we are working on a solution .

we find that this system above ( https://en.instamizer.com ) can post the hastags correctly.

ps . they use only login and password ( without official instagram api )

**Comment by mgp25** [comment]
There is nothing to research, posting and configure calls are done via HTTP, so its easy to get them and easy to know what happens.

Send a pull request

**Comment by mgp25** [comment]
See how easy? Now its working: https://github.com/mgp25/Instagram-API/commit/561536352604d87c0160c3406393a378820afb43

Took me 2 minutes. Is not that hard...

**Comment by jd440** [comment]
thanks @mgp25 but it doesn't same to fix it

**Comment by mgp25** [comment]
#470
