### ISSUE TITLE
Publications and hastags

### ISSUE THREAD

**Issue by weeh89** [mgp25/Instagram-API#470]
Hi, I make the publication by this script.
There are about two weeks hashtags publications are not public lists
_Example: https://www.instagram.com/explore/tags/HASHTAG/_

**If you are logged in with the same account that published, or is not logged in to any account the image appears correctly in the hashtag list.

If you are logged in with another user the image does not appear to him in the hashtag list**

Is there any way for this fix to this problem?

**Comment by mgp25** [comment]
True, i just tested it.

Yes, there is a way to fix it. When someone or i is in the mood to work on that we'll send a pull request, meanwhile do not open more issues, we know the thing and thats it.

- Is there any way for this fix to this problem?

Yes, research, compare, try and error until success

Regards

**Comment by oratiostuff** [comment]
we are working to fix

also already for more than 14 days I'm trying to get this setting

**Comment by honeydewkorea** [comment]
@weeh89 Hello. i have a issue that yours.
Did you solve the problem? Could you help me?
