### ISSUE TITLE
Bad request when uploading photo

### ISSUE THREAD

**Issue by Svoka** [mgp25/Instagram-API#471]
Hey!
When I try to upload photo I getting bad request error.

Login - ok
Update profile pricture - ok
Upload photo - bad request

Any thoughts what it can be?

StackTrace:

Array
(
    [0] => Array
        (
            [file] => /home/www/aproori/backend/classes/Instagram-API/src/Instagram.php
            [line] => 461
            [function] => uploadPhoto
            [class] => InstagramAPI\HttpInterface
            [type] => ->
            [args] => Array
                (
                    [0] => /home/www/aproori/test/wall.jpeg
                    [1] => Message
                    [2] => 
                    [3] => 
                    [4] => 
                    [5] => 
                )

        )

    [1] => Array
        (
            [file] => /home/www/aproori/test/pub-insta.php
            [line] => 29
            [function] => uploadPhoto
            [class] => InstagramAPI\Instagram
            [type] => ->
            [args] => Array
                (
                    [0] => /home/www/aproori/test/wall.jpeg
                    [1] => Эгегей
                )

        )

)

**Comment by jpmoney5065** [comment]
No debug

**Comment by Svoka** [comment]
I tried your example file, but removed debug as you suggested.
Still the same.
Any special requirments for photo size?


$username = 'mylogin';
$password = 'mypass';
//$debug = false;

$photo = $_SERVER["DOCUMENT_ROOT"].'/test/wall.jpeg';     // path to the photo
//////////////////////

$i = new \InstagramAPI\Instagram($username, $password);

try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}

try {
    $i->uploadPhoto($photo, $caption);
} catch (Exception $e) {
    echo $e->getMessage();
}
