### ISSUE TITLE
Proxy Setting Error

### ISSUE THREAD

**Issue by derjrjr** [mgp25/Instagram-API#472]
Hello,
I am trying to set a proxy, just to login and getting an exeption error:
``
Fatal error: Uncaught exception 'InstagramAPI\InstagramException' with message 'Proxy host error. Please check ip address and port of proxy.' in /home/insttuoc/public_html/tests/insta_api/src/Instagram.php:151 Stack trace: #0 /home/insttuoc/public_html/tests/insta_api/examples/login.php(10): InstagramAPI\Instagram->setProxy('http://173.208....', '3128') #1 {main} thrown in /home/insttuoc/public_html/tests/insta_api/src/Instagram.php on line 151
``

Im using this code:
``
include __DIR__.'/../vendor/autoload.php';
require '../src/Instagram.php';
$username = 'usename';
$password = 'password';
$debug = true;
$ip = "http://173.208.91.4";
$port = "3128";
$i = new \InstagramAPI\Instagram($username, $password, $debug);
$i->setProxy($ip, $port);
try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
}
``

Thanks !

**Comment by jpmoney5065** [comment]
```
if (!empty($proxy['host']) && isset($proxy['port']) && is_int($proxy['port'])) {
            $this->proxyHost = $proxy['host'].':'.$proxy['port'];
        } else {
            throw new InstagramException('Proxy host error. Please check ip address and port of proxy.');
        }
```

port need to be an int

**Comment by derjrjr** [comment]
ok, I made appropriate fixes but have this problem now:

``
[1;34mPOST: [0mqe/sync/ DATA: ig_sig_key_version=4&signed_body=600f3a20d0b2f8c7ccac5b4fc0cc2faa28a2d69a92b2a746597eab04aa97289d.{"id":"079af97e-e4a8-4751-aa4e-1065dcb2aca1","experiments":"ig_android_reg_login_btn_active_state,ig_android_ci_opt_in_at_reg,ig_android_one_click_in_old_flow,ig_android_merge_fb_and_ci_friends_page,ig_android_non_fb_sso,ig_android_mandatory_full_name,ig_android_reg_enable_login_password_btn,ig_android_reg_phone_email_active_state,ig_android_analytics_data_loss,ig_fbns_blocked,ig_android_contact_point_triage,ig_android_reg_next_btn_active_state,ig_android_prefill_phone_number,ig_android_show_fb_social_context_in_nux,ig_android_one_tap_login_upsell,ig_fbns_push,ig_android_phoneid_sync_interval"} [0;32m← 0 0B[0m [0;36mRESPONSE: [0m [1;34mGET: [0msi/fetch_headers/?challenge_type=signup&guid=d1d89e3334164d40825a6565d26a2dcd [0;32m← 0 0B[0m [0;36mRESPONSE: [0m Couldn't get challenge, check your connection
``
Thanks :)

**Comment by jpmoney5065** [comment]
Not a problem with the API
Something is wrong with your connection

**Comment by mgp25** [comment]
Duplicate #473
