### ISSUE TITLE
Proxy Setting Error UPDATE

### ISSUE THREAD

**Issue by derjrjr** [mgp25/Instagram-API#473]
When I dont use a proxy, its fine but when I do theres a problem..
Could there be a problem with the proxy connection code?
I am using private proxies, that work with instagram program..

**Comment by jpmoney5065** [comment]
Nope. It's not a problem with this API. 
Did you test your proxy running from your server independently of this API?

**Comment by derjrjr** [comment]
yes, they are working, I am using them with FollowLiker.com and its fine.. thats why im confused..
Thanks :)

**Comment by jpmoney5065** [comment]
Did you test your proxy **_`running from your server`_** independently of this API?

**Comment by derjrjr** [comment]
Yes, the proxy works with the registrationTool.php but not with the other ones for me..
I noticed that the registationTool uses a different class ($r = new \InstagramAPI\InstagramRegistration($debug);)
This class seems to work with the proxies for me but the other one doesnt?
Thanks

**Comment by mgp25** [comment]
@derjrjr the API works fine with proxy, maybe you should look at your code/enviroment/proxy and for that purposes its better to search in google, although we are here to help people, we focus on API issue, and this is not

Regards

**Comment by derjrjr** [comment]
ok, thanks
Ill keep testing around for the moment
