### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by irshad9998** [mgp25/Instagram-API#474]
when i want to login, then checkpoint_required msg debug

How to bypass checkpoint_required and login or i want to manually verify account

What can i do??

Sorry for my bad english.

**Comment by jpmoney5065** [comment]
https://github.com/mgp25/Instagram-API/blob/master/examples/checkpoint.php

**Comment by irshad9998** [comment]
Hello i am not understand what want to say checkpoint.php.

It's not run

**Comment by derjrjr** [comment]
The checkpoint.php is for email verification.
You most likely need phone verification which is not currently covered by this API.
Hope this helps :)

**Comment by irshad9998** [comment]
i am new to php when i run checkpoint.php then it's not work 

can you explain me what is trim(fgets(STDIN)) and what is stdin

**Comment by jpmoney5065** [comment]
http://php.net/manual/en/features.commandline.php
