### ISSUE TITLE
HTTP ERRORR 500

### ISSUE THREAD

**Issue by johnraypaulin14** [mgp25/Instagram-API#477]
I followed the instructions and tried to run the example for pagination but it's not working. What could be the problem? 

I'm thinking this line is causing the error but I'm not sure. Tried to echo something before this line, it displayed but after this line no display..

$i = new InstagramAPI\Instagram($username, $password, $debug);

**Comment by mgp25** [comment]
@johnraypaulin14 Do you know php? Thats the first requirement if you are planing to use this API. That line is instantiating the main class, so you can call function with `$i`. 

`Server 500 error` its because connection issue. Not API issue

Regards
