### ISSUE TITLE
Регистрация не работает

### ISSUE THREAD

**Issue by Martyn911** [mgp25/Instagram-API#478]
Совсем не работает регистрация.
Пробовал использовать прокси но результат тот же.
Ответ сервера:
`REQUEST: accounts/create/
DATA: ig_sig_key_version=4&signed_body=0d8aeef3a8d877a55bc37d4c16960a568b402adaf0a62e0a1eefd5689ab8681e.%7B%22allow_contacts_sync%22%3A%22true%22%2C%22phone_id%22%3A%22d236d050-015d-46ad-9dbe-4764629e0648%22%2C%22_csrftoken%22%3A%22ic29PJuqxqelZxTmE7WFJvdqIPnpvCKN%22%2C%22username%22%3A%22jsdfhsdf234%22%2C%22first_name%22%3A%22%5Cu041d%5Cu0438%5Cu043a%5Cu0438%5Cu0442%5Cu0430%22%2C%22guid%22%3A%22d236d050-015d-46ad-9dbe-4764629e0648%22%2C%22device_id%22%3A%22android-ee1389674e6b80f7%22%2C%22email%22%3A%22djhsfsvdsd%40gmail.com%22%2C%22force_sign_up_code%22%3A%22%22%2C%22waterfall_id%22%3A%22a95a8d37-0c44-4bdd-b39f-1e46c82d185d%22%2C%22qs_stamp%22%3A%22%22%2C%22password%22%3A%22jsdfhj234xg%22%7D
RESPONSE: {"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_action": "report_problem", "feedback_url": "repute/report_problem/instagram_signup/", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Report problem"}`

как обойти фильтры инстаграма и заставить работать? постоянно "spam": true

**Comment by sp4nky** [comment]
Hello

The Instagram-API request was performed correctly but you've marked as spam! 
Instagram spam detection algorithms is little bit sophisticated. It's really (fuzzy) to note their detection factors.
At least make sure your proxy IP is not blacklisted nor not located in heavily flagged IP range! Also check if the proxy is not leaking headers that may identify it self as a proxy such (Proxy-Connection: Keep-Alive, ... etc)!

Don't try to make multiple accounts using the same IP, (this doesn't make sense)

Residential IP (dynamic) ranges will look more legit.

Regards

**Comment by mgp25** [comment]
@Martyn911 english!
