### ISSUE TITLE
Upload photo Issue

### ISSUE THREAD

**Issue by beljk** [mgp25/Instagram-API#48]
REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=4cb754746a509aa5be8a9a34284068f5b0bdb34abec75ef6bf82ab10b05e8f65.%7B%22caption%22%3A%22good%22%2C%22upload_id%22%3Anull%2C%22source_type%22%3A3%2C%22edits%22%3A%7B%22crop_zoom%22%3A1%2C%22crop_center%22%3A%5B0%2C0%5D%2C%22crop_original_size%22%3A%5B150%2C150%5D%2C%22black_pixels_ratio%22%3A0%7D%2C%22device%22%3A%7B%22manufacturer%22%3A%22lg%22%2C%22model%22%3A%22Nexus+5%22%2C%22android_version%22%3A23%2C%22android_release%22%3A%226.0.1%22%7D%2C%22_csrftoken%22%3A%22668054251f413ad12ba83ec764321c57%22%2C%22_uuid%22%3A%22ca9de15d-7b14-4f5c-b51d-de3846665713%22%2C%22_uid%22%3A%222272589366%22%7D RESPONSE: Oops, an error occurred.

**Comment by modsfabio** [comment]
Try #46
