### ISSUE TITLE
searchLocation() query

### ISSUE THREAD

**Issue by amr-dallin** [mgp25/Instagram-API#480]
Hi, guys! No description provided. 

In Instagram.php:
`public function searchLocation($latitude, $longitude, $query = null)`

I do:
`$i = new \InstagramAPI\Instagram(...);`
`$i->login();`

`print_r($i->searchLocation('Tashkent'));`
or
`print_r($i->searchLocation(null, null, 'Tashkent'));`

Result: 5xx Server Error

How?

Thanks!

**Comment by jpmoney5065** [comment]
1)
5xx error is your server/failed coding
check your error logs

2)
searchLocation() requieres 2 variables

**Comment by mgp25** [comment]
F.A.Q: https://github.com/mgp25/Instagram-API/wiki/FAQ#im-getting-error-500
