### ISSUE TITLE
Error : Call to a member function getUser() on null

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#481]
I have this php code :

	$tag = 'sport';
	try {
		$helper = null;
		$media = [];
		do {
			if(is_null($helper)) {
				$helper = $instagram->tagFeed($tag);
			} else {
				$helper = $instagram->tagFeed($tag,$helper->getNextMaxId());
			}
		$loop++;	
		$media = array_merge($media, $helper->getItems());
		}while(!is_null($helper->getNextMaxId()) and $loop <= 1);
		
		if(count($media) > 0){ 
			foreach ($media as $item)
				{
					$array[] = $item->getCaption()->getUser()->getFullName();
						
				}
				return $array;
			}		
	} catch (Exception $e) {
	  echo $e->getMessage();
	}
	
it return "Call to a member function getUser() on Null , 
so this line :
$item->getCaption()->getUser()->getFullName();
or even this one : 
$item->getCaption()->getText();

return same error !
but on other hand , i can see  "Caption Object" in item reply!

debug output is huge but here is a link to it:

http://beshoo.com/text.txt

please have a look to the print_r($item) :

`
[0] => InstagramAPI\Item Object
        (
            [taken_at:protected] => 1474349271
            [pk:protected] => 1343261508641787564
            [id:protected] => 1343261508641787564_2281890447
            [device_timestamp:protected] => 1474349256302
            [media_type:protected] => 1
            [code:protected] => BKkOTmnDI6s
            [client_cache_key:protected] => MTM0MzI2MTUwODY0MTc4NzU2NA==.2
            [filter_type:protected] => 0
            [image_versions2:protected] => Array
                (
                    [0] => InstagramAPI\HdProfilePicUrlInfo Object
                        (
                            [url:protected] => http://scontent.cdninstagram.com/t51.2885-15/e35/14369235_335615250120225_150636878_n.jpg?ig_cache_key=MTM0MzI2MTUwODY0MTc4NzU2NA%3D%3D.2
                            [width:protected] => 720
                            [height:protected] => 720
                        )

                    [1] => InstagramAPI\HdProfilePicUrlInfo Object
                        (
                            [url:protected] => http://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/14369235_335615250120225_150636878_n.jpg?ig_cache_key=MTM0MzI2MTUwODY0MTc4NzU2NA%3D%3D.2
                            [width:protected] => 640
                            [height:protected] => 640
                        )

                    [2] => InstagramAPI\HdProfilePicUrlInfo Object
                        (
                            [url:protected] => http://scontent.cdninstagram.com/t51.2885-15/s480x480/e35/14369235_335615250120225_150636878_n.jpg?ig_cache_key=MTM0MzI2MTUwODY0MTc4NzU2NA%3D%3D.2
                            [width:protected] => 480
                            [height:protected] => 480
                        )

                    [3] => InstagramAPI\HdProfilePicUrlInfo Object
                        (
                            [url:protected] => http://scontent.cdninstagram.com/t51.2885-15/s320x320/e35/14369235_335615250120225_150636878_n.jpg?ig_cache_key=MTM0MzI2MTUwODY0MTc4NzU2NA%3D%3D.2
                            [width:protected] => 320
                            [height:protected] => 320
                        )

                    [4] => InstagramAPI\HdProfilePicUrlInfo Object
                        (
                            [url:protected] => http://scontent.cdninstagram.com/t51.2885-15/s240x240/e35/14369235_335615250120225_150636878_n.jpg?ig_cache_key=MTM0MzI2MTUwODY0MTc4NzU2NA%3D%3D.2
                            [width:protected] => 240
                            [height:protected] => 240
                        )

                    [5] => InstagramAPI\HdProfilePicUrlInfo Object
                        (
                            [url:protected] => http://scontent.cdninstagram.com/t51.2885-15/s150x150/e35/14369235_335615250120225_150636878_n.jpg?ig_cache_key=MTM0MzI2MTUwODY0MTc4NzU2NA%3D%3D.2
                            [width:protected] => 150
                            [height:protected] => 150
                        )

                )

            [original_width:protected] => 720
            [original_height:protected] => 720
            [view_count:protected] => 0
            [organic_tracking_token:protected] => eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImY1ZDEzNDZiYTdmYTQ4YzNhMTAxZjJhY2NlZDE0MDMwMTM0MzI2MTUwODY0MTc4NzU2NCIsInNlcnZlcl90b2tlbiI6IjE0NzQzNDkyOTg2ODR8MTM0MzI2MTUwODY0MTc4NzU2NHwzMDIyMjM1NDg5fDYwZjNkYjNmMTZlYzE1M2NlZTg3MGFjZTIzNDNhYzMzOTdjYzA3NjYxYWI3OGIzNDMxZDI5ZDUxOGZlOTEwY2YifSwic2lnbmF0dXJlIjoiIn0=
            [has_more_comments:protected] => 
            [max_num_visible_preview_comments:protected] => 2
            [comments:protected] => Array
                (
                )

            [comment_count:protected] => 0
            [caption:protected] => InstagramAPI\Caption Object
                (
                    [status:protected] => Active
                    [user_id:protected] => 2281890447
                    [created_at_utc:protected] => 1474349272
                    [created_at:protected] => 1474349272
                    [bit_flags:protected] => 0
                    [user:protected] => InstagramAPI\User Object
                        (
                            [username:protected] => arab_christians
                            [has_anonymous_profile_picture:protected] => 
                            [is_favorite:protected] => 
                            [profile_pic_url:protected] => http://scontent.cdninstagram.com/t51.2885-19/s150x150/12716734_442668805925278_877611457_a.jpg
                            [full_name:protected] => SPORT_MASTER
                            [pk:protected] => 2281890447
                            [is_verified:protected] => 
                            [is_private:protected] => 
                            [coeff_weight:protected] => 0
                            [friendship_status:protected] => InstagramAPI\FriendshipStatus Object
                                (
                                    [following:protected] => 
                                    [incoming_request:protected] => 
                                    [outgoing_request:protected] => 
                                    [is_private:protected] => 
                                )

                        )

                    [content_type:protected] => comment
                    [text:protected] => I love all
                    [media_id:protected] => 1343261508641787564
                    [pk:protected] => 17842474162190493
                    [type:protected] => 1
                )

            [caption_is_edited:protected] => 
            [photo_of_you:protected] => 
            [video_versions:protected] => 
            [has_audio:protected] => 
            [video_duration:protected] => 
            [user:protected] => InstagramAPI\User Object
                (
                    [username:protected] => arab_christians
                    [has_anonymous_profile_picture:protected] => 
                    [is_favorite:protected] => 
                    [profile_pic_url:protected] => http://scontent.cdninstagram.com/t51.2885-19/s150x150/12716734_442668805925278_877611457_a.jpg
                    [full_name:protected] => Arab_Christians
                    [pk:protected] => 2281890447
                    [is_verified:protected] => 
                    [is_private:protected] => 
                    [coeff_weight:protected] => 0
                    [friendship_status:protected] => InstagramAPI\FriendshipStatus Object
                        (
                            [following:protected] => 
                            [incoming_request:protected] => 
                            [outgoing_request:protected] => 
                            [is_private:protected] => 
                        )

                )

            [likers:protected] => Array
                (
                    [0] => InstagramAPI\User Object
                        (
                            [username:protected] => sambergen
                            [has_anonymous_profile_picture:protected] => 
                            [is_favorite:protected] => 
                            [profile_pic_url:protected] => http://scontent.cdninstagram.com/t51.2885-19/11820636_443984519122807_759361177_a.jpg
                            [full_name:protected] => Sam Bergen
                            [pk:protected] => 537634
                            [is_verified:protected] => 
                            [is_private:protected] => 
                            [coeff_weight:protected] => 0
                            [friendship_status:protected] => 
                        )

                )

            [like_count:protected] => 1
            [preview:protected] => 
            [has_liked:protected] => 
            [explore_context:protected] => 
            [explore_source_token:protected] => 
            [explore:protected] => 
            [impression_token:protected] => 
            [usertags:protected] => InstagramAPI\Usertag Object
                (
                    [in:protected] => Array
                        (
                            [0] => InstagramAPI\In Object
                                (
                                    [position:protected] => InstagramAPI\Position Object
                                        (
                                            [pos1:protected] => 0.41049102
                                            [pos2:protected] => 0.45981058
                                        )

                                    [user:protected] => InstagramAPI\User Object
                                        (
                                            [username:protected] => basem.gerges._
                                            [has_anonymous_profile_picture:protected] => 
                                            [is_favorite:protected] => 
                                            [profile_pic_url:protected] => http://scontent.cdninstagram.com/t51.2885-19/s150x150/13827265_1120527081334557_866840175_a.jpg
                                            [full_name:protected] => Basem Gerges
                                            [pk:protected] => 1817935387
                                            [is_verified:protected] => 
                                            [is_private:protected] => 
                                            [coeff_weight:protected] => 0
                                            [friendship_status:protected] => 
                                        )

                                )

                        )

                    [photo_of_you:protected] => 
                )

        )
`

**Comment by beshoo1** [comment]
Well i found it :) it is "taken_at"
getTakenAt()

i told you , we are in 2016 :)

**Comment by mgp25** [comment]
```php
$array[] = $item->getCaption()->getUser()->getUsername();
```

is not an API issue, its a programming issue!

**Comment by beshoo1** [comment]
I dont understand , i line it as you did your kindly reply !
$item->getCaption()->getUser()->getUsername();

PS: some times it works , some times it is not !

**Comment by mgp25** [comment]
Not all items have captions. You need to think what you are doing

**Comment by jpmoney5065** [comment]
Just use an if statement man
```
 if($caption = $item->getCaption()){
    //Do stuff with caption
}
```
