### ISSUE TITLE
getHashtagFeed missing "Response" in Instagram.php

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#483]
Instagram.php On line 1470 

        $hashtagFeed = $this->http->request($endpoint)[1];

        if ($hashtagFeed['status'] != 'ok') {
            throw new InstagramException($hashtagFeed['message']."\n");
            return;
        }

it has no Response!

i trid some thing like : 
     
```
   $hashtagFeed =   new TagFeedResponse($this->http->request($endpoint)[1]);
        if (!$hashtagFeed->isOk()) {         
            throw new InstagramException($hashtagFeed['message']."\n");
            return;
        }  
```

but i stock with 
Warning: Invalid argument supplied for foreach() in ./vendor/mgp25/instagram-php/src/http/Response/TagFeedResponse.php on line 19

**Comment by jpmoney5065** [comment]
Your search is failing, probably because you are adding a # at the beginning of your search. Instagram is not sending an error message, but a blank response.

Try removing the #

**Comment by beshoo1** [comment]
first of all , you did not read my post carefully  
second , please dont close the post before solving the problem , i am sure about what i am talking about.

No it is not i am not adding # , 
$instagram->getHashtagFeed('sport',$helper->getNextMaxId());
it return data , no problem with that .. but there is no methods to catch data ! 
and there is no file in ./vendor/mgp25/instagram-php/src/http/Response/ to handle getHashtagFeed

**Comment by jpmoney5065** [comment]
OK, so it's not an issue with the API.. code a method and send a pull request!

**Comment by jakeingit** [comment]
I'd love to help code an additional method for getting a response for hashtag posts but I'm new at PHP.

**Comment by jakeingit** [comment]
If you've written something that works, please send a pull request! (:

**Comment by jpmoney5065** [comment]
Here, look at this, practice your PHP, code it up properly, test it, send a pull request.

If you have questions send an email, don't make an issue for something that isn't an issue.
jon @ website in my profile

```
    public function getHashtagFeed($hashtagString, $maxid = null)
    {
        if (is_null($maxid)) {
            //$endpoint = "feed/tag/$hashtagString/?rank_token=$this->rank_token&ranked_content=true&";
            $hashtagFeed = new TagFeedResponse($this->http->request("feed/tag/$hashtagString/?rank_token=$this->rank_token&ranked_content=true&")[1]);
        } else {
            //$endpoint = "feed/tag/$hashtagString/?max_id=".$maxid."&rank_token=$this->rank_token&ranked_content=true&";
            $hashtagFeed = new TagFeedResponse($this->http->request("feed/tag/$hashtagString/?max_id=".$maxid."&rank_token=$this->rank_token&ranked_content=true&")[1]);
        }

        //$hashtagFeed = $this->http->request($endpoint)[1];

        /*
        if ($hashtagFeed['status'] != 'ok') {
            throw new InstagramException($hashtagFeed['message']."\n");

            return;
        }

        return $hashtagFeed;
        */

        if (!$hashtagFeed->isOk()) {
            throw new InstagramException("Hey status didn't come back OK and Instagram doesn't send an error message for failed searches! \n");
        }

        return $hashtagFeed;
    }
```
