### ISSUE TITLE
Continue) A hashtag searching problem

### ISSUE THREAD

**Issue by secretcau** [mgp25/Instagram-API#485]
Hi. I wrote a hashtag searching problem before.
And then, i have researched the problem.

Now, i am facing a problem related the hashtag searching problem.

> I can search when i logged-in for uploaded photo's owner account to instagram.
> However, I couldn't find if i logged-in for other account.  

Now, i posted the issue to instagram cs team. But i'm not expect a solution from their.

Sorry to my poor English.

**Comment by jpmoney5065** [comment]
No solution right now. Someone will get to it when they get to it.

**Comment by secretcau** [comment]
Uhm... Isn't it my mistake? Your means 'Current searching problem is normality at now although i set by the standard using this API'. Is it right?

**Comment by secretcau** [comment]
@jpmoney5065 I found definite difference.
I could get it **without** log-in on instagram web-page.
But, I couldn't get it **with** log-in instagram web.

Is there a clue?

**Comment by mgp25** [comment]
#470
