### ISSUE TITLE
Empty response form video chunk upload processes

### ISSUE THREAD

**Issue by haiduong87** [mgp25/Instagram-API#486]
I can't upload video with this API.
Here's the log: (debug = true)
[uploadVideo.txt](https://github.com/mgp25/Instagram-API/files/484108/uploadVideo.txt)
I'm using easy php server for windows
Please take a look

**Comment by mgp25** [comment]
```json
{"status": "fail", "message": "Server got a conflicting 
```

**Comment by haiduong87** [comment]
Hi,
I know that error, but I haven't edit anything.
And I also use your test video too.
Please help.

As far as I know, the upload video progess splited into 3 step:
 - Chunk uploading video pieces (4 in your api)
 - Upload a preview picture
 - Configure the api

But, I don't see any chunk video upload response, then the APi continue to upload preview image (this step is ok and it uses the upload_id, and instagram think it's a single photo), then the 3rd step will get that "conflict.." error.

After I run that sample, my test accout will display a new photo (the preview photo).

**Comment by mgp25** [comment]
You can enable cURL verbose editing `HttpInterface.php`

Regards

**Comment by haiduong87** [comment]
Hi,
I have figured what's the problem, it's about the SSL
Have to add "curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);" before uploading chunk video pieces.
Now  I'm getting another error:
[another log.txt](https://github.com/mgp25/Instagram-API/files/495239/another.log.txt)
POST: media/configure/? DATA: ig_sig_key_version=4&signed_body=932f2fdf9f64163b8f651d01baba7a08a0c1730b643e9d14d4166599b5aa7a41.{"_csrftoken":"bgpmMRQWA5N9rChLLWuadpZbZ2MsfRDp","media_folder":"Instagram","source_type":4,"_uid":"3886886850","_uuid":"099970fb-5ae7-4a29-b803-a77bf973c9e9","caption":"testnao","upload_id":"1474972783739","device":{"manufacturer":"Samsung","model":"SM-G935T","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[560.0,560.0],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":560,"source_height":560}} ← 200 131B RESPONSE: {"status": "ok", "media": {"upload_id": "1474972783739"}, "message": "media_needs_reupload", "error_title": "staged_media_missing"}
I used http://techslides.com/demos/sample-videos/small.mp4
and I have to generated a preview myself (I can't install ffmpeg right now, and I use ffmpeg of windows to create that preview)
![small](https://cloud.githubusercontent.com/assets/22165935/18870212/d5319d88-84d9-11e6-8027-d2ee1d75ed93.jpg)

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/
