### ISSUE TITLE
Followers/Following fetching

### ISSUE THREAD

**Issue by cutzenfreund** [mgp25/Instagram-API#489]
Hi, first of all, thank you for this great API.

I am working on a follower analysis tool and want to analyze every Xth follower or every Xth page so I don't have to get ALL the followers of users with followers >100.000 for example.

Is this possible?

**Comment by mgp25** [comment]
Maybe, but that is not an API issue

Regards

**Comment by cutzenfreund** [comment]
Sorry, I didn't know where to ask.
Would you mind to give me a hint how to achieve this with your API?

Am 21.09.2016 12:40 nachm. schrieb "mgp25" <notifications@github.com>:

**Comment by mgp25** [comment]
You can ask those kind of questions in a programming forum, im sure they will help you there.

Because of the little time i have and the ammount of issues are opened in github, i have to focus only in API issues.

Regards
