### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by mgp25** [mgp25/Instagram-API#49]
Im doing a lot of changes and i figured out lot of information, anyway i need some testers with an android device and with SSL trust killer installed in other words, to capture app traffic.

Interested ones contact with me via mail (in my girhub's profile page)

Regards

**Comment by cloudever** [comment]
Hi. Few weeks ago I was interested with priv API of Instagram.
First time I tried to capture network traffic with fiddler2, but it was hidden. I guess that it works with own http(s) stack. Then I make a decompile apk and found ch.boye library for custom http(s) stack. Also I found necessary config file, changed one value to true (it's obfuscated, in real I think name of variable is DEBUG). After that I compiled it to apk, signed, installed and wow.. fiddler shows all https queries from instapp.

I tried to make it with v6.x android app. Versions 7.x are crashe after 5 seconds, but I have time to make login request.

Can you tell me how did you sniff https on 7th version. Did you do those changes in apk?
