### ISSUE TITLE
methods in login()

### ISSUE THREAD

**Issue by Brownizzz** [mgp25/Instagram-API#491]
Hi! if the user is logged in, what to call these methods?
-autoCompleteUserList();
-getReelsTrayFeed();
-getRankedRecipients();
-getRecentRecipients();
-megaphoneLog();
-getv2Inbox();
-getRecentActivity();
-explore();

**Comment by mgp25** [comment]
Thats how app behaves

Regards

**Comment by Brownizzz** [comment]
thanks for the answer

**Comment by ususus12** [comment]
any idea what the megaphoneLog is used for?
