### ISSUE TITLE
Function searchLocation and Wiki description 

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#492]
in WIKI 
`$i->searchLocation($input) 
`, which is one input is required , string of country name.
But in mgp25/instagram-php/src/Instagram.php
it seem there is an update ! and i dont know how it hase to be don without updating wiki : 
Line 1233
` function searchLocation($latitude, $longitude, $query = null) .
`

and even if i pass it like this : 
`print_r(searchLocation($latitude = null, $longitude = null,'USA'))
`
it print this error;

```
Fatal error: Uncaught InstagramAPI\InstagramException: 
 in ./vendor/mgp25/instagram-php/src/Instagram.php:1249
Stack trace:
#0 ./action.php(22): InstagramAPI\Instagram->searchLocation(NULL, NULL, 'usa')
#1 {main}
  thrown in ./vendor/mgp25/instagram-php/src/Instagram.php on line 1249

```

mr @jpmoney5065  saide in one of his comments
2)
searchLocation() requieres 2 variables

But in past i can pass the name of the country and it will return array of matched !
What is the problem ?

**Comment by mgp25** [comment]
Capture request, compare and send a pull request. 

and by the way, the error you have its because you are passing null to values that shoudnt be null. I dont know if you can send only the query, but that is easy to test, remove the other params in `instagram.php` test, and if you find any difference, send a pull request.

Regards

**Comment by beshoo1** [comment]
Dear @mgp25 , thank you very much for your kindly reply , glad to be one of who try to help.
I did test what you side befor posting , and it did not works , we have to pass lat lng , but what i am pointing to , why in the WIKI no info about that , users like to follow instruction , and by that mistake thy may open an issues which will wasted your time , and there time by debugging and searching.

I am ready any time to send PL , as you can see i am doing my best :)
