### ISSUE TITLE
[Question] What the different between getHashtagFeed and tagFeed?

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#493]
Dear all , this is not an issue , but a question to community.
As i can see we have two methds to Search  by Tag , (getHashtagFeed and tagFeed ) 

but if you look to the code you may see that thy have same endpoint !
getHashtagFeed
 "feed/tag/$hashtagString/";
tagFeed
"feed/tag/$tag/"

other Question in same subject 
(getHashtagFeed and tagFeed ) return a top new feed for giving tag , of course you can go back by pagination.

But what if i want to get an old taged media , let's say 5 days old , this needs me to make a lot of  pagination.

is there a way to target a specific date ?

can we get a all list of NextId without looping throw all pages , then we chose which NextId wana use ?

Regards,

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/commit/93c0c929046e174aa3563e82478a0e57297b4a85

**Comment by beshoo1** [comment]
Thank you very much for clearing the duplication , now it`s more robust :)

> i think there is an offset param you can set. But check it yourself to be sure
Well its seem there is no way , other service online use paid instagram API version to offer this service.

but i am not sure , it`s just my search over google, in app there is nothing about sorting by date ! is it ?
 
Yours
