### ISSUE TITLE
[Question] getFriendshipStatus() is this method ever return something ?

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#494]
Dear all , Please enlighten me, i tried all situation , this method dos not return a value ! not even ones , 
`$user->getFriendshipStatus()->getFollowing();`

each time it return NULL . i am sure the API is working but the problem i dont know when this method has to be caled .

**Comment by mgp25** [comment]
Sometimes there is `friendship_status` sometimes not, depending on each user. You should read the code before opening an issue:

https://github.com/mgp25/Instagram-API/blob/master/src/http/Response/Objects/User.php#L37

**Comment by beshoo1** [comment]
i did read the code carefully , but if i am following and he do the same , it has to show some thing ! correct   . 
i show time line of one of my friends, null return !

**Comment by mgp25** [comment]
@beshoo1 do a `var_dump` of `$user` and paste it here

**Comment by jpmoney5065** [comment]
@beshoo1 it depends on how you are getting the `$user` object.
Instagram doesn't return full results for every call.
Get the users pk and call the `userFriendship()` method to test for friendship status

**Comment by jpmoney5065** [comment]
```
$i = new \InstagramAPI\Instagram(USER,PASS); // USE YOUR OWN USERNAME AND PASSWORD

$userPK = // USE ANY WAY YOU WANT TO GET THE PK

$friendStatus = $i->userFriendship($userPK);

if(!empty($friendStatus['following']) echo 'Yay we are friends! Horray!';
if(!empty($friendStatus['outgoing_request']) echo 'User is private, but request sent!';
if(!empty($friendStatus['incoming_request']) echo 'Someone wants to be my friend, but I am private';
if(!empty($friendStatus['followed_by']) echo 'Someone is following me';
if(!empty($friendStatus['blocking']) echo 'oh no! blocked again!';
if(!empty($friendStatus['is_private']) echo 'this users account is private';
```
Can you figure it out from here??

**Comment by beshoo1** [comment]
Dear Mr @jpmoney5065, Thank you for this code , yes it solve the problem .
and you point me to how in future i can use each method alone .

Thank you.

**Comment by mgp25** [comment]
This is not API issue
