### ISSUE TITLE
Feed error

### ISSUE THREAD

**Issue by aryanbaghi** [mgp25/Instagram-API#495]
getUserFeed throw this exception: `'InstagramAPI\InstagramException' with message '`. This began to happen today and not fixed until now

**Comment by jpmoney5065** [comment]
It is working normally.

**Comment by beshoo1** [comment]
@aryanbaghi show us your code please.

**Comment by jpmoney5065** [comment]
```
$i = new \InstagramAPI\Instagram(USER,PASS);
$userfeed = $i->getUserFeed('330592117');
print_r($userfeed);
```
