### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by maximseshuk** [mgp25/Instagram-API#496]
```
$helper = $i->getSelfUserFollowers();
print_r($helper);
$helper2 = $i->getSelfUserFollowers($helper->getNextMaxId());
print_r($helper2);
```

$helper and $helper2 both print the first page, and analogous to this example (https://github.com/mgp25/Instagram-API/blob/master/examples/PaginationExample.php
), it runs endlessly and outputs first page

What is the problem? Sry for bad English

**Comment by jpmoney5065** [comment]
**Not an API issue.**
Look at the code, `getSelfUserFollowers()` does't accept any variables! 

Use:
```
$nextMaxId = null;
do{
    $userFeed = $i->getUserFollowers($i->username_id,$nextMaxId);
    // DO STUFF
}while($nextMaxId=$userFeed->getNextMaxId());
```
or change the method to:
```
public function getSelfUserFollowers($nextMaxId=null)
{
    return $this->getUserFollowers($this->username_id,$nextMaxId);
}
```

Go to a program forum for programming advice.

**Comment by maximseshuk** [comment]
```
    public function getSelfUserFollowers($max_id = null)
    {
        return $this->getUserFollowers($this->username_id, $max_id);
    }
```
https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php
