### ISSUE TITLE
Instagram.php

### ISSUE THREAD

**Issue by k41ed** [mgp25/Instagram-API#5]
REQUEST: si/fetch_headers/?challenge_type=signup&guid=0f80c304f2344decabd4732b20cc6e2c RESPONSE: Array ( )
Notice: Undefined offset: 1 in C:\xampp\htdocs\insta2\insta\src\Instagram.php on line 73

**Comment by mgp25** [comment]
@k41ed do you have all dependencies installed? `var_dump` the result, its working pretty fine here
