### ISSUE TITLE
Create new account ?

### ISSUE THREAD

**Issue by SolomoneKane** [mgp25/Instagram-API#50]
Hi,

I tried to create a new account with the RegistrationTool.php file but it seems like it doesn't work. It says that the username is unvailable but he's available. When I'm trying to print_r the result of the curl post, it returns an empty array.

Username: sfjnhsj354k
REQUEST: users/check_username/
DATA: ig_sig_key_version=4&signed_body=6c2f4316246fec921fe631aee1f3d183e6573c01c
5d36a94bbfcdddc6a74ba91.%7B%22_uuid%22%3A%227aef2a8e-cf7f-49e1-84f7-b1f443ac45b5
%22%2C%22username%22%3A%22sfjnhsj354k%22%2C%22_csrftoken%22%3A%22missing%22%7D
RESPONSE:

Username sfjnhsj354k not available, try with another one

Thanks ! :)

**Comment by mgp25** [comment]
User is not available, that means the user already exists. Do a `var_dump` instead

Regards
