### ISSUE TITLE
error

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#501]
How about to check if updateds working ?
Im running on Centos PHP 7 
Previous Versions working fine and everytime you make an update i have to edit the whole code :-1: 

Fatal error: Uncaught Error: Class 'InstagramAPI\AdaptImage'

**Comment by mgp25** [comment]
@doctorbinsibar learn php instead of complaining!

```
composer update
```

Im getting tired of this 💩
