### ISSUE TITLE
Problem upload video 

### ISSUE THREAD

**Issue by rizkyred** [mgp25/Instagram-API#504]
Hi i tried to upload video but failed. is that function can work correctly ?

Thanks

**Comment by mgp25** [comment]
Works fine

**Comment by rizkyred** [comment]
can you give me, example code ? i tried upload photo it works, but didnt works with upload video

**Comment by EXECUTOR-brandon** [comment]
Read Video Rules.  http://www.premiumbeat.com/blog/how-to-edit-and-encode-videos-for-instagram/
Or here. 
http://hisdesignonline.com/add-edited-video-instagram/
