### ISSUE TITLE
Class SignatureUtils not Found

### ISSUE THREAD

**Issue by rizkihape** [mgp25/Instagram-API#505]
Hello
how ti fix this problem?
I Try install with composer, but it's still error 
This code is 

`
Fatal error: Uncaught Error: Class 'InstagramAPI\SignatureUtils' not found in /home/u878633572/public_html/Instagram/src/Instagram.php:42 Stack trace: #0 /home/u878633572/public_html/Instagram/index.php(5): InstagramAPI\Instagram->__construct('username', 'password...', false) #1 {main} thrown in /home/u878633572/public_html/Instagram/src/Instagram.php on line 42`

Sorry my english bad :)
Thanks

**Comment by mgp25** [comment]
Not API issue. Check installation

Regards
