### ISSUE TITLE
Trouble with signature.

### ISSUE THREAD

**Issue by JohnMKC** [mgp25/Instagram-API#506]
Respected Sir,

I have installed Instagram on Bluestack because I was not able to root My Nexus 6P properly since got Nougat update. I have rooted bluestack and did manual method to extract signature. I was able to do all the steps till "Break using F2" but then after I have to press F9 to run app. It seems even after pressing F9 nothing happening. I have been following this tutorial : https://mokhdzanifaeq.github.io/extracting-instagram-signature-key-2/
 
Link : http://image.prntscr.com/image/e0289a631484452085e160f7a80f69d2.png

I'm using windows 10 by the way..

Thank You!

**Comment by mgp25** [comment]
@JohnMKC is not an API issue. Remember to do i while executing it, research a little and you will get it, you are almost there.

Regards

**Comment by JohnMKC** [comment]
It is keep saying failed to dump memory at address xyz.
