### ISSUE TITLE
[Not an issue ][Question] Dos Instagram accept respectable automation  ?

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#507]
Dear all , All we hate SPAM , will , i do !
But i note a message Instagram reply to user without blocking IP Address. which it
"To many request please try again"

will , in this case there is a foreach loop to collect a list of images. No one can scroll down as fast as foreach .

i mean , Dos Instagram accept some kind of respectable automation  ? 
You can see in facebook there is a lot of automation  tools , yes there is a recaptcha in some point "which is ckeck_point" in instagram , but user can do some thing regarding it , but if you look to whatsapp . there is no way you can automate any thing , there is no Please message ,,,just a BLOCK ..

I know Instagram TOS say to use the app in a correct way , dont spam bla bla bla
but in real world , they know this is not a human been , we all know about human pattern detection algorithm , come on this is facebook who know every methods your hand may use...

even thy provide api , once api available so automation is on the surface.
so my target of this post , how can we define SPAM , while  automation  is kind of spam, and is the respectable automation is accepted by instagram or not!

Regards
 
@mgp25 , i know it is not an API issue , but it is some thing community my like to talk about!

**Comment by GuilhermeFM** [comment]
Yes they provide API but you you need to get through a world of pain to get permission to use it and when you acquire the permission you need to keep in mind theirs limits.

There are no common rule of how instagram flags you as spam, if you make a observational study about the the API behavior you will see that each user will be flagged as spam differently Ex.: a user with less than 5k followers start to 18follow / 18unfollows per hour get blocked easily while one with more than 300k does not.

In some cases instagram will not flag you as spam, they will simply block you access to the endpoint. The friendship endpoint may not flag you as spam instead it will not execute the action and the return of the request will be 200 and no fails status on json. If you manage to get to that point you can check this behavior by going into your phone instagram app and trying to follow someone you will see that the follow button will turn green and then will be back to white as if you are not following the person.

There other types of blocking like json response with messages like "feedback_required" that indicate that you maybe abusing one endpoint specifically.

Thus to conclude there are no pattern in their blocking system if you ask my opnion i could speculate that they use some kind of fuzzy logic to filter their requests.
