### ISSUE TITLE
Notice and Warning errors since the last update

### ISSUE THREAD

**Issue by Alexsisukin** [mgp25/Instagram-API#509]
After the upgrade, there were mistakes, is this normal?

> Notice: Undefined index: media in site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/Objects/Args.php on line 17

>Call Stack:
 >   0.0023     287080   1. {main}() site.net/public_html/cron/cron_strategy_1_new.php:0
  >  0.0566     725064   2. new_get_all_spam_account() site.net/public_html/cron/cron_strategy_1_new.php:22
  > 35.5141    1807440   3. InstagramAPI\Instagram->login() site.net/public_html/inc/helpers/helper.php:1150
   >47.2206    1862008   4. InstagramAPI\Instagram->getRecentActivity() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/Instagram.php:223
  > 48.1606    1887704   5. InstagramAPI\ActivityNewsResponse->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/Instagram.php:1068
   >48.1664    1893240   6. InstagramAPI\Story->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/ActivityNewsResponse.php:23
   >48.1664    1893536   7. InstagramAPI\Args->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/Objects/Story.php:16

>Warning: Invalid argument supplied for foreach() in site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/Objects/Args.php on line 17

>Call Stack:
  >  0.0023     287080   1. {main}() site.net/public_html/cron/cron_strategy_1_new.php:0
   > 0.0566     725064   2. new_get_all_spam_account() site.net/public_html/cron/cron_strategy_1_new.php:22
   >35.5141    1807440   3. InstagramAPI\Instagram->login() site.net/public_html/inc/helpers/helper.php:1150
   >47.2206    1862008   4. InstagramAPI\Instagram->getRecentActivity() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/Instagram.php:223
   >48.1606    1887704   5. InstagramAPI\ActivityNewsResponse->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/Instagram.php:1068
   >48.1664    1893240   6. InstagramAPI\Story->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/ActivityNewsResponse.php:23
   >48.1664    1893536   7. InstagramAPI\Args->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/Objects/Story.php:16

>Notice: Undefined index: media in site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/Objects/Args.php on line 17

>Call Stack:
  >  0.0023     287080   1. {main}() site.net/public_html/cron/cron_strategy_1_new.php:0
   > 0.0566     725064   2. new_get_all_spam_account() site.net/public_html/cron/cron_strategy_1_new.php:22
   >68.5713    1860992   3. InstagramAPI\Instagram->login() site.net/public_html/inc/helpers/helper.php:1150
   >80.3681    1869712   4. InstagramAPI\Instagram->getRecentActivity() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/Instagram.php:223
   >81.2852    1876928   5. InstagramAPI\ActivityNewsResponse->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/Instagram.php:1068
   >81.2853    1877344   6. InstagramAPI\Story->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/ActivityNewsResponse.php:23
   >81.2853    1877640   7. InstagramAPI\Args->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/Objects/Story.php:16

>Warning: Invalid argument supplied for foreach() in site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/Objects/Args.php on line 17

>Call Stack:
  >  0.0023     287080   1. {main}() site.net/public_html/cron/cron_strategy_1_new.php:0
    >0.0566     725064   2. new_get_all_spam_account() site.net/public_html/cron/cron_strategy_1_new.php:22
   >68.5713    1860992   3. InstagramAPI\Instagram->login() site.net/public_html/inc/helpers/helper.php:1150
   >80.3681    1869712   4. InstagramAPI\Instagram->getRecentActivity() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/Instagram.php:223
   >81.2852    1876928   5. InstagramAPI\ActivityNewsResponse->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/Instagram.php:1068
   >81.2853    1877344   6. InstagramAPI\Story->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/ActivityNewsResponse.php:23
   >81.2853    1877640   7. InstagramAPI\Args->__construct() site.net/public_html/inc/helpers/vendor/mgp25/instagram-php/src/http/Response/Objects/Story.php:16

**Comment by mgp25** [comment]
@Alexsisukin Fixed. Please, check code before opening issue, i mean, sometimes is just adding a check if tha var isnt set or it doesnt exist.

Anyway, now its fixed

Regards

**Comment by Alexsisukin** [comment]
Thank you!
