### ISSUE TITLE
not working my localhost

### ISSUE THREAD

**Issue by sefaiyi** [mgp25/Instagram-API#51]
```php
require '../src/Instagram.php';

/////// CONFIG ///////
$username = 'user';
$password = 'pass';
$debug    = true;

$photo    = '1.jpg';     // path to the photo
$caption  = '#deneme';   // caption
//////////////////////

$i = new Instagram($username, $password, $debug);

try{
  $i->login();
} catch (InstagramException $e)
{
  $e->getMessage();
  exit();
}

try {
  $attimi = $i->uploadPhoto($photo, $caption);
  var_dump($attimi);
} catch (Exception $e)
{
  echo $e->getMessage();
}
```
// OUTPUT

`REQUEST: media/configure/ DATA: ig_sig_key_version=4&signed_body=74cc08beff43dab5fd9db85dae801c4ba63b730c20364e3e915c2c9cd9582f6c.%7B%22caption%22%3A%22%23deneme%22%2C%22upload_id%22%3Anull%2C%22source_type%22%3A3%2C%22edits%22%3A%7B%22crop_zoom%22%3A1%2C%22crop_center%22%3A%5B0%2C0%5D%2C%22crop_original_size%22%3A%5B640%2C640%5D%2C%22black_pixels_ratio%22%3A0%7D%2C%22device%22%3A%7B%22manufacturer%22%3A%22lg%22%2C%22model%22%3A%22Nexus+5%22%2C%22android_version%22%3A23%2C%22android_release%22%3A%226.0.1%22%7D%2C%22_csrftoken%22%3A%22d3ff8d81d8ab9a16b885f5704afba899%22%2C%22_uuid%22%3A%22cc198e8e-74c6-426d-8580-adc2a281edd0%22%2C%22_uid%22%3A%221651967972%22%7D RESPONSE: Oops, an error occurred. NULL`

**Comment by mgp25** [comment]
@sefaiyi first of all, make sure you are logged in, and if there is an error uploading a photo, just try again and it will work

Regards
