### ISSUE TITLE
likeCount and commentCount always 0 in getHashtagFeed and issue in getComments and getMedia Likers

### ISSUE THREAD

**Issue by webfreaks** [mgp25/Instagram-API#514]
After version 1.5, `comment_count` and `like_count` always 0 in `getHashTagFeed()` method.

Then,
when I call `getComments()` or `getMediaLikers()`, some media return error message:
```
Sorry, this photo has been deleted.
```

But, in fact, this media not deleted.

**Comment by mgp25** [comment]
Works perfectly just tested it
