### ISSUE TITLE
upload video, only upload a custom preview

### ISSUE THREAD

**Issue by ofernandoleite** [mgp25/Instagram-API#515]
Hello,

I'm having a problem sending video to instagram.

It is only sending the custom preview, someone knows what can be?

Error:

RESPONSE: {"status": "fail", "message": "Server got a conflicting upload id"}

Thank you!

Update:
Ps: Windows Hosting

**Comment by ofernandoleite** [comment]
Ps: Windows Hosting

**Comment by mgp25** [comment]
@ofernandoleite check latest commits

**Comment by ofernandoleite** [comment]
@mgp25 

I just upgraded to the latest version.

Still with the same problem!


Thank You!
