### ISSUE TITLE
upload video, only upload a custom preview [3]

### ISSUE THREAD

**Issue by ofernandoleite** [mgp25/Instagram-API#518]
The solution I sent ( #516 ) is about FFmpeg, but it has nothing to do with the problem I am in conflict id upload.

I'm still the problem below:

```json
RESPONSE: {"status": "fail", "message": "Server got a conflicting upload id"}
```
Sorry to open Several issues

Thank you!

**Comment by haiduong87** [comment]
Try disable ssl on function httpinterface.uploadVideo()
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
at the first exec

**Comment by ofernandoleite** [comment]
@haiduong87 

← 200 131B RESPONSE: {"status": "ok", "media": {"upload_id": "1475029789373"}, "message": "media_needs_reupload", "error_title": "staged_media_missing"} 
Notice: Undefined index: upload_id in E:\Programas\xampp\htdocs\colanosapo\src\http\Response\ConfigureResponse.php on line 15

Notice: Undefined index: id in E:\Programas\xampp\htdocs\colanosapo\src\http\Response\ConfigureResponse.php on line 16

Notice: Undefined index: image_versions2 in E:\Programas\xampp\htdocs\colanosapo\src\http\Response\ConfigureResponse.php on line 17

Notice: Undefined index: code in E:\Programas\xampp\htdocs\colanosapo\src\http\Response\ConfigureResponse.php on line 18
POST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=fab12299f58ebd967b218e1128d461222d0bf3ee364e343dde28ee79527906fa.{"upload_id":1475029789373,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":15,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"Samsung","model":"SM-G3606","android_version":18,"android_release":"4.3"},"_csrftoken":"W3pgUtVQ7mUN0sSPsswWXWbvsyNjGKxJ","_uuid":"7d24ef74-8e12-4a39-af85-051077233e30","_uid":"3972590530","caption":":D"} ← 500 72B RESPONSE: {"status": "fail", "message": "Other media configure error: yEmZkUpAj4"}

**Comment by haiduong87** [comment]
Yeah, I'm going to ask about this.
Yesterday I found out the SSL prolem, made some changes and I got that new error too :D
The problem now moves to configure the preview photo

**Comment by ofernandoleite** [comment]
If you find out let me know. Thank you

**Comment by aliebrash** [comment]
hi... tnx for your Practical project..
i want to ask that In your opinion can i change this project to java?

**Comment by sp4nky** [comment]
@aliebrash check this [https://www.npmjs.com/package/instagram-private-api](url)

**Comment by mgp25** [comment]
Try again with latest commit from master, if still not working try with another video and make sure you have installed ffmpeg.

If you still face issue, send me an email with full debug log

Regards

**Comment by haiduong87** [comment]
Hi,
@ofernandoleite enable ssl in chunk media upload proccess too
Thanks @mgp25, I can upload video now.

**Comment by juicejams** [comment]
Where do I enable ssl ? I tried setting true and false for verify peer and verify host but still get the same error.

**Comment by webfreaks** [comment]
What "Try disable ssl" means?
I don't clearly understand with this statement.

Thank you.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/issues/518#issuecomment-250054920
