### ISSUE TITLE
Line break in caption.

### ISSUE THREAD

**Issue by JohnMKC** [mgp25/Instagram-API#520]
Hello,

I have tried \r\n and \n to break line in caption. But didn't work. Also tried some PHP built in function but nothing worked for me. Any method to break line ?

Thanks!

**Comment by mgp25** [comment]
Not API issue + i dont think Instagram lets line break

Regards

**Comment by sefidary** [comment]
Instagram allow linebreak in app

**Comment by sefidary** [comment]
use pack('H*', '0a')  or pack('H*', '0d') (UTf-8 character for line break)

**Comment by gonzalon** [comment]
@sefidary I try out what you mention, but only seeing some weird characters. How did you manage to make it work? Could you post a snippet of your code? Thanks!

**Comment by rizkyred** [comment]
Hi @sefidary what do you mean by use pack('H_', '0a') or pack('H_', '0d') (UTf-8 character for line break) ?
