### ISSUE TITLE
How to display all posts of users?

### ISSUE THREAD

**Issue by sdr34** [mgp25/Instagram-API#522]
How to display all posts of users? photo width 240 height 153 please tell me
```php
$media = $i->getSelfUserFeed($max_id = null)->getItems();
                          
 if(count($media) > 0){ 
            foreach ($media as $item)
                {
                
               }
```

**Comment by mgp25** [comment]
@sdr34 check this [example](https://github.com/mgp25/Instagram-API/blob/master/examples/PaginationExample.php) to see how pagination works.

For each response you can get items and iterate its values. If you dont know how to do this, you can search in google or php.net: https://secure.php.net/manual/en/control-structures.foreach.php

Regards
