### ISSUE TITLE
Creating API

### ISSUE THREAD

**Issue by JohnMKC** [mgp25/Instagram-API#527]
Hello,

This is not an Issue but I need a help regarding creating API. Recently I downloaded Charles and created proxy and then connected my phone to the proxy. I'm trying to create Hike Messenger API. I was able to see the traffic of sending verification SMS to phone and registering the account in HTTPS request because installed certificate on phone. But then I send a message to my friend and I couldn't see the message in HTTP(S) request. Why ? It doesn't use HTTP(S) protocol ? Which protocol it uses ? and how can I know about it ? And which tool do you suggest to use while doing this ? Short answer will be fine.

Thanks!

**Comment by mgp25** [comment]
Please, this is not a discussion forum. You will find more information by searching in google than opening an issue here.

Regards
