### ISSUE TITLE
Direct message endpoint changed / broken?

### ISSUE THREAD

**Issue by frrakn** [mgp25/Instagram-API#530]
I'm getting
```
HTTP/1.1 500 Internal Server Error
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Cookie, Accept-Language
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Thu, 29 Sep 2016 20:15:47 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Content-Length: 25

Oops, an error occurred.
```

When I'm using the direct message endpoint. Any chance the most recent Instagram update killed it?

**Comment by mgp25** [comment]
Works perfectly.

Look at your error: `HTTP/1.1 500 Internal Server ErrorHTTP/1.1 500 Internal Server Error`
https://github.com/mgp25/Instagram-API/wiki/FAQ#im-getting-error-500
