### ISSUE TITLE
Sorting search result

### ISSUE THREAD

**Issue by webfreaks** [mgp25/Instagram-API#534]
Hi, Is there possible to sort search result(getUserFeed, getHashtagFeed, searchUsers) like sorting by follower_count, media_count or something else?

**Comment by mgp25** [comment]
@webfreaks yes it is possible, but that is something that the user should code bythemseves

Regards

**Comment by beshoo1** [comment]
Dear @mgp25 , i think @webfreaks  want to ask instagram to return a ready sorted results . not fill it in array and play with it !
i think we can not do such thing as along as you can not do it on the real app !
