### ISSUE TITLE
upload Photo

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#537]
When you upload an image, it compresses the sides. Ugly. Can this be fixed? Should the photo on the background of the square obtained? I do not speak English well.

**Comment by mgp25** [comment]
Yes, you can modify the code to adapt your requirements

Regards

**Comment by Triden** [comment]
image 2560*1707 load bad. image 1280 * 720 load good. the first image gets the newheight ~ 720px, but they become instagrame 1080px. whether it can be a bug?

**Comment by Triden** [comment]
I found a solution.) Just I commented out
  / * Elseif ($ this-> height> 1080) {
                     $ This-> newHeight = 1080;
                 } * /
Thank you.

**Comment by beshoo1** [comment]
We have to do this resize in order to meet instagram photo ratio
