### ISSUE TITLE
Count Followers?

### ISSUE THREAD

**Issue by Thuran** [mgp25/Instagram-API#540]

**Comment by beshoo1** [comment]
Man ! JUST SEARCH !!!!!

**Comment by mgp25** [comment]
@Thuran read the wiki and example codes.

**Comment by Thuran** [comment]
I can thank you;

Att,
Thuran Eduardo Crespi
[https://outlook.live.com/owa/?path=/mail/inbox/rp&retryCount=3]


________________________________
De: mgp25 <notifications@github.com>
Enviado: segunda-feira, 3 de outubro de 2016 19:31
Para: mgp25/Instagram-API
Cc: Thuran; Mention
Assunto: Re: [mgp25/Instagram-API] Count Followers? (#540)


@Thuran<https://github.com/Thuran> read the wiki and example codes.

-
