### ISSUE TITLE
Registration Not Work

### ISSUE THREAD

**Issue by putraxor** [mgp25/Instagram-API#55]
Registration won't work, it always say the username is unavailable all the time.
this is my code:

`
<?php
if(isset($_POST['username'])) {
require_once '../src/InstagramRegistration.php';
$r = new InstagramRegistration(true);

$debug = true;
echo "<pre>";

  $check = $r->checkUsername($username);
  var_dump($check);
  if ($check['available'] == false)
    echo "Username $username not available, try with another one\n\n";

//echo "Username $username is available\n\n";
$username = trim($_POST['username']);
$password = trim($_POST['password']);
$email = trim($_POST['email']);
$first_name = trim($_POST['first_name']);
echo "\n\nUsername: $username";
echo "\nPassword: $password";
echo "\nEmail: $email\n";

$result = $r->createAccount($first_name, $username, $password, $email);
var_dump($result);
if (isset($result['account_created']) && ($result['account_created'] == true))
{
  echo "Your account was successfully created! :)";
}
echo "</pre>";
}`
> Username: REQUEST: users/check_username/
> DATA: ig_sig_key_version=4&signed_body=7eaaf544d2a4a14df74650e0d5e4be16b9b849e309ac220d9953a43db71b3a01.%7B%22_uuid%22%3A%221b2a26c1-ae0c-4560-ac48-859b26baffe0%22%2C%22username%22%3A%22rezdongan1992%22%2C%22_csrftoken%22%3A%22missing%22%7D
> RESPONSE: 
> 
> Username rezdongan1992 not available, try with another one

**Comment by mgp25** [comment]
Works
