### ISSUE TITLE
work in localhost, not in hosting

### ISSUE THREAD

**Issue by nanangkoesharwanto** [mgp25/Instagram-API#554]
I don't know why it's happens. All functions work nicely in localhost. but do nothing in hosting. even I made the permission of mgp25 folder and all folder in it into 777.
In hosting, all functions start from new Instagram, does not work.
**this is the script**
```php
			$username = $data->username;
			$password = $data->token;
			$username_id = $data->ins_id;
			$debug = false;
			
			$instagram = new Instagram($username, $password, $debug);
			dd($instagram);	
```		
**result in localhost**
```
Instagram {#872 ▼
  +username: "abcdefgh"
  +password: "1234567890"
  +debug: false
  +truncatedDebug: false
  +uuid: "3c02751b-1549-4075-9e9c-230954b51234"
  +device_id: "android-b596a2fc6f01c66f"
  +username_id: "2308661123"
  +token: "dWe8IVYjNIzLmN8gB8yM0J1Bq3Cd1234"
  +isLoggedIn: true
  +rank_token: "2308661123_3c02751b-1549-4075-9e9c-230954b51234"
  +IGDataPath: "C:\xampp\htdocs\ibridge\vendor\mgp25\Instagram-php\src\data\abcdefgh\"
  +customPath: false
  +http: HttpInterface {#877 ▶}
  +settings: Settings {#878 ▶}
  +proxy: null
  +proxyHost: null
  +proxyAuth: null
}
```
while in hosting, it just a white blank screen.
no return at all, even I made the `$debug = true`.
Any suggestions would be really help me.
thanks.

**Comment by onlyongunz** [comment]
Have you make sure all of required environment are good to go? i mean, the php version, required depencies, and etc...

**Comment by mgp25** [comment]
@nanangkoesharwanto in `HttpInterface.php`, make cURL verbose `true`. And you will check whats happening with the request. Maybe Instagram is blocking your server requests

Regards

**Comment by nanangkoesharwanto** [comment]
@mgp25 , I change all verbose in `HttpInterface.php` to `true`, but still no return at all, just a white blank screen.
```
$instagram = new Instagram($username, $password, $debug);
dd($instagram);
```

**Comment by haiduong87** [comment]
Please check the SSL setting
I'm a windows user and I need to enable ssl of the uploadvideo to make it work. (easyphpserver lastest version)

**Comment by nanangkoesharwanto** [comment]
another error comes. after the white blank screen disappeared.
```
ErrorException in /home/admin/web/ibridgeapp.com/public_html/vendor/composer/ClassLoader.php
line 412:

include(/home/admin/web/ibridgeapp.com/public_html/vendor/composer/../mgp25/instagram-php/src/Instagram.php):
failed to open stream: No such file or directory
```
I think, I have to see a doctor for my headache.
