### ISSUE TITLE
upload photo with usertags

### ISSUE THREAD

**Issue by MositerZ** [mgp25/Instagram-API#555]
Hello
Did can i upload photo with tag one user ?
I dont see any method talk about this featuer

**Comment by haiduong87** [comment]
Tag is a part of your caption.

**Comment by MositerZ** [comment]
how?
$i->uploadPhoto($url, $caption,**$user)**;
is that correct?

**Comment by haiduong87** [comment]
hmm...
$caption = '[yourCaptionGoesHere] [#hash1] [#hash2] [@user1] [@user2]';
$i->uploadPhoto($url, $caption);

**Comment by MositerZ** [comment]
@haiduong87

hehehe im so sorry i have mistake with **title issue**
i know every thing about $caption and it work good
**BUT**
mistake = upload photo with tag
**correct = upload photo with usertags**

**Comment by mgp25** [comment]
Not implemented yet, although you can capture request and do its implementation

Regards

**Comment by David-Kurniawan** [comment]
in 2017...

how i can do that?
upload single photo with usertags

**Comment by mgp25** [comment]
@David-Kurniawan please read the code, everything is documented

**Comment by David-Kurniawan** [comment]
@mgp25  sorry, this is my mistake, i cannot find anywhere, i try like this:
```$metadata = [
              'caption' => 'My awesome caption',
	      'usertags' => [
                 'position' => [
                                  0.74315617510662,
                                  0.52898550724638
                               ],
                 'user_id'  => [
                                  29559807
                               ]
	        ]```

but not work for me? please give me link how i can do that :smiley:

**Comment by SteveJobzniak** [comment]
@David-Kurniawan You can see all supported metadata in src/Request/Internal.php, in configureSinglePhoto and configureSingleVideo. As you see, we have no usertags support.
