### ISSUE TITLE
Class not found after update. Understanding of namespace and require, just to be clear

### ISSUE THREAD

**Issue by Stepkaa** [mgp25/Instagram-API#556]
Hi, today updated to the recent version of API. And again, good old problems with importing classes. I updated via Composer. So, I can solve this by adding millions of `require_once 'SignatureUtils.php';` and etc., but can you please explain once and for all, how it should be done in a right way? So many people run into this problem, I just want to make everyone understand this to avoid such problems in the future and not open a ton of same issues. Thanks.

**Comment by mgp25** [comment]
@Stepkaa The legend says that there is a website, where you can write your question and find the answer, that web is called google. Use it. Being lazy and not look for things is very easy. Solving things by yourself takes time, but you learn more.

```
 mgp25$ cd Instagram-API/
 mgp25$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by Stepkaa** [comment]
Thanks for quick reply. Yup, I searched. I can even predict answer to all "class not found" issues :) 

But, what i think, people try to use an API from directories other then composer's /vendor/... . Such as myself. After scrolling through issues, i found `require("../vendor/autoload.php");`, and from vendor directory it works nicely. But when it comes to working from other, here I have problems. Sorry for not mentioning it :(

**Comment by mgp25** [comment]
_sigh..._

Create a script anywhere you want, this is clear right?

Inside the script:

```
<?php

include 'PATH_TO_AUTOLOAD.php';

//And here all your instagram code...
```

Where `PATH_TO_AUTOLOAD.php` is the path where you have the `autoload.php`. Is that clear too? 

Im not explaning anything different from what google says, its just basic PHP, requiring a file, right?
