### ISSUE TITLE
Instagram checkpoint update

### ISSUE THREAD

**Issue by emildayan** [mgp25/Instagram-API#559]
Seems like IG has a checkpoint update (only tried email).

New format seems to be:

/checkpoint_logged_out_main/{account_id}/{new_code}?next=%2F

7-letter az09 code, that's pretty much all I know.

Cheers and hope you have an amazing weekend @mgp25!

**Comment by mgp25** [comment]
@emildayan ill check eventually, not very interested in Instagram at the moment

Regards
