### ISSUE TITLE
How can we post image in Instagram via API - PHP

### ISSUE THREAD

**Issue by helloarpitgshah** [mgp25/Instagram-API#56]
Hey,

How can we post an image into instagram with Instagram PHP API?

Can you please help me?

Thanks,

**Comment by mgp25** [comment]
See the examples

Regards

**Comment by helloarpitgshah** [comment]
Thanks for your quick response.

Can We able to make the Oauth Login with instagram and Post both for this example?

**Comment by mgp25** [comment]
@helloarpitgshah we dont use OAuth with this API, we use device authentication system. Both login and upload photo is in the same example script

Regards
