### ISSUE TITLE
Please explain the meaning of such message

### ISSUE THREAD

**Issue by himor** [mgp25/Instagram-API#560]
REQUEST: friendships/autocomplete_user_list/
RESPONSE: {"status": "fail", "message": "Sorry, too many requests. Please try again later."}

Everything works fine, though - the client logs in and able to perform different actions. 

Quick question: how ofter would you recommend to log in? Let's say script is running for days. Should I just log in once and use that client until the script ends? Or would it be a good practice to log in more often?

**Comment by GuilhermeFM** [comment]
Login once and not anymore, the cookies returned by instagram has a very long expire date.
