### ISSUE TITLE
Can I read direct now?

### ISSUE THREAD

**Issue by baimurzin** [mgp25/Instagram-API#561]
I found this library, and I tried to read direct message with it, Is it implemented already?

Tanks a lot for an answer!

**Comment by snapmaster** [comment]
1. Errors (Ошибки in russian):
I found this library, and I've tried to read direct messages with it. Does it already implemented?
Thanks a lot for the answer!

2. Too lazy to check the code?? (Ахуели совсем)

**Comment by baimurzin** [comment]
@snapmaster Я смотрел код, точнее даже запускал его но сообщения из директа так и не получил..
Может тогда подскажите, за что отвечают эти методы:
`
getPendingInbox()
directThread($threadId)
getv2Inbox()
getDirectShare()
`

**Comment by mgp25** [comment]
@snapmaster if you want to comment, do it in English, so everybody can understand

**Comment by baimurzin** [comment]
I tried this methods 
`
getPendingInbox()
directThread($threadId)
getv2Inbox()
getDirectShare()
`

But no one helps me. No result always null or arrays with zero length. when I var_dump it

**Comment by mgp25** [comment]
@baimurzin compare the function with the requests Instagram does, maybe is not implemented.

**Comment by michelmelo** [comment]
Is there any solution for this case? I was looking for this and I did not find it.
