### ISSUE TITLE
FriendshipStatus doesn't expose all returned fields

### ISSUE THREAD

**Issue by azureatlas** [mgp25/Instagram-API#564]
A request like

`friendships/show/123456789`

returns:
```json
{
   "status":"ok",
   "incoming_request":false,
   "is_blocking_reel":false,
   "followed_by":false,
   "is_muting_reel":false,
   "outgoing_request":true,
   "following":false,
   "blocking":false,
   "is_private":true
}
```
1) However only some fields are exposed by the FriendshipStatus class. Specifically, we need to add:

```
is_blocking_reel
followed_by
is_muting_reel
blocking
```

2) Also, the current code is expecting "source_token" in the response, when there are pending requests, but the response doesn't contain it. The response above was for a private user, towards which there is a pending follow request, as you can see, but no source_token was present.

**Comment by mgp25** [comment]
Merged https://github.com/mgp25/Instagram-API/commit/2d7db73cbd22f7ddca23a629130474ef591d7664

Regards
