### ISSUE TITLE
Uploaded image isn't in the right format

### ISSUE THREAD

**Issue by detho** [mgp25/Instagram-API#567]
cant upload video

this result
> 2[1;34mPOST:  [0mupload/video/
[1;33mΓåÆ 0B[0m
[0;32mΓåÉ 0     0B[0m
[0;36mRESPONSE: [0m

[1;34mPOST:  [0mupload/photo/
[1;33mΓåÆ 0B[0m
[0;32mΓåÉ 0     0B[0m
[0;36mRESPONSE: [0m

[1;34mPOST:  [0mupload/photo/
[1;33mΓåÆ 765B[0m
[0;32mΓåÉ 200   46B[0m
[0;36mRESPONSE: [0m{"status": "ok", "upload_id": "1476160243557"}

[1;34mPOST:  [0mmedia/configure/?
[1;33mDATA: [0mig_sig_key_version=4&signed_body=cbbb68a853530def34b1893555a16508ce4e42a4e7fcb07ed386233184ee4058.{"_csrftoken":"usTiWkUvBQCM25jjcQBT8euhnM2PgVeM","media_folder":"Instagram","source_type":4,"_uid":"4008818448","_uuid":"b580dccb-2223-470a-ac2e-c0be852875c4","caption":"test","upload_id":"1476160243557","device":{"manufacturer":"ZTE","model":"NX511J","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":null,"source_height":null}}
[0;32mΓåÉ 400   73B[0m
[0;36mRESPONSE: [0m{"status": "fail", "message": "Uploaded image isn't in the right format"}

**Comment by mgp25** [comment]
@detho use latest commit (master branch). Debug from CLI please.

Regards

**Comment by detho** [comment]
@mgp25 my problem in this latest commit.. how fix this?

**Comment by mgp25** [comment]
@detho first post a clean debug log from CLI

**Comment by detho** [comment]
same?

POST: upload/video/ → 496B ← 200 2.44kB
 
RESPONSE: {"status": "ok", "upload_id": "1476193903816", "video_upload_urls": [{"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c22\u0026vx_token=307", "job": "AQC05CXzxCALH7o1NCNCLK6WDOd6ky2Hq9vDVLQ2bUZOA3BADeMGkgEuCoAtsY8sKyHhMkUkF0byAHGmGLeRxpJtNT1MdjjRfCRvIdBnWsoS-z69YcMD-d0HOCJi_3vt-7wlhqwqrwsDYP59Emxrwlntvl2K9vC4eEYQ-wCYDIEuxE1uRQMvqGXLtSvctCkIWOZ2o6vySgHLlT4pGW_7BlR2HLpIqpuNFABPnfhWqLVyd2g7qJcWlFuX36ik74q3Aj6OT-tzt2LCy6xgFMKiY7VqcATzx53VS_96oeQTGgb7IgzPLwGuUv4tIVg3VEQ-ull5ufySc-MsvFSeJvI6UF9b1B1qoB5vVrlYcukPIaTNdIA69RCcp_N7rHB5om4WZIE6V3427tHhT72rEldoU_G_79SwOpZKquOxNNSgoxFv2SvFKxNMGQ_DvVqu0NNE3H0uxyr3AbV5aaMJzppGDP-A", "expires": 1791553904.389187}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c27\u0026vx_token=100", "job": "AQCKDd5dcHZmABfsSxj3jdhb83lsGtSG2pYro_xJbETOnbDkrPA0_NxTc693L56qsuIo-tmVfIJzmwOkwfFPYr9klwow9dG_EcNFQsBHqBNQUcT6q5EmRvDBAaxObCeTAhUcLpdeQnO9IHZQy0E7U4J7NQcVk9hTT5T4JC4bPqPfGe2A6K3C6OTz_dyP8f--2TRDf-IayyTGlY_SntJgb50XwbGFBWc7xCg1-subteu6h5l7HvmkgwAGrVrW9DOvQRQCk9PZqUeSV_1H-uxKv5YJnUtWuu-vqNwUzuX-xjk1pqPxnR9pF5hmDfh2wtWsjHdyIzRxiA0QWCbwHG7rDrzmVu-k_Nnod-lxyX8vHaD4WAlTlIS0i64xHW8oFLzuQ4OgdkKJ6o-g0tdmwJUJ1zdHkR8SY7FQ_FW0dEXiYXFrOXNnNeJUHtYzYfwAxhugzGKsBhvUlfz1qj1itwePLlUR", "expires": 1791553904.389891}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c22\u0026vx_token=105", "job": "AQBMVacMmFfv4-YOZKMGukHOdk8VA6LZKHLTyCEWjdXnxQAERM_bgWG73VI4vljw9UZhHM638ufqGrgAW8DUoDgy5XsrPmeK6GRtIrzjypcDODioNX5rI4ACdyDH3v0PFlQDVM0N4mIeN5H747-aJaz7QKBaF5vlEPU-FcRKrDV7vRc_ldgH3QjTU9KN6IKbK5sxRqQp3JuPycmZKpDLaFl7rJ1Fov7cW6UvtOWkcH1vpaUvInxAwZTruSoDT0KdiZkBp3SNEhzz8z4ZASQRmEFDPbIGUiiQLRrg7PQ1CQDyghEdvSU6cjk9UQh8Nhg2gtdWEEkfDnUipzH-8bLbFUDTHltDn3mMgYPkqCUsCRIE_hkCHvxAqOXu0S0-YYd5CZLVwdXWwuJ4xvk4-PZeJlQCAL3FZbuUj9zZg3sgj1vfn7fsXANWj0dKcNuHVE_mRTVAf0w1PGjZ0HGdUl623dM1", "expires": 1791553904.390609}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c22\u0026vx_token=300", "job": "AQDpDOKB9BQ_5MSR4gToT5GzePzb4C5kYmu481dc0Gl8o626t5HJ5yxDkS2LyhymMhhhlhqt8fKLN4XGAEdhK8Qy2TxgR2LOO6aAkdzp4_kq7Kny_TKIBLpLBSHHgX8tuCnl7BY3GX_HY6xUhBQIxDsYe3ZJ6V50OElmlG9WEeC8a9hxoRhB3QIvA8XnLHVM9MvKVe2sicrtVPmKSPBbiA-oqscrJGtdAOsLYMmyivlzu_FnMHxjJ02cKZe0n1_jlVbuO6wlfME9V7VLStvNQqSS8BOoLCAMUZbKlHAb3s-eNIWY_dWd-g_uGmOVYOYJH3kUUDTDNIXjjj47ki5zXxTxk2U0kf408F3dGfJt7h3Nybg4ziH7-SGVy-GrBP8pLfk10rbf6aZ1Sbq9QundVQOqp_SytTjfm7lSuwFjXTsp7aZ3BdiKgJ7gZbukXh5t8cFrjXLzlMZ6I4cwToS9PhsJ", "expires": 1791553904.39131}]} 

POST: upload/photo/ → 60.13kB ← 201 20B 

RESPONSE: 184719-246291/246292 

POST: upload/photo/ → 765B ← 200 46B RESPONSE: {"status": "ok", "upload_id": "1476193903816"} 

POST: media/configure/? DATA: ig_sig_key_version=4&signed_body=18fb400b677f6b7aa5425df7ccd2b22844fcced4235ccf179598c8f2b42d9ae8.{"_csrftoken":"usTiWkUvBQCM25jjcQBT8euhnM2PgVeM","media_folder":"Instagram","source_type":4,"_uid":"4008818448","_uuid":"96c108c4-d023-4d81-91ad-0036c1e7f9aa","caption":"hanya test upload","upload_id":"1476193903816","device":{"manufacturer":"ZTE","model":"NX511J","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":null,"source_height":null}} ← 400 73B 

RESPONSE: {"status": "fail", "message": "Uploaded image isn't in the right format"}

**Comment by detho** [comment]
@mgp25 
i got new problem :(

Server got a conflicting upload id

`POST: upload/video/ → 0B ← 0 0B 
RESPONSE: POST: upload/photo/ → 0B ← 0 0B 
RESPONSE: POST: upload/photo/ → 8.59kB ← 200 46B 
RESPONSE: {"status": "ok", "upload_id": "1476762742844"} 
POST: media/configure/? DATA: ig_sig_key_version=4&signed_body=6747a1ef334def17959c9822ca4598505ef19278ef152aaac46486cd3a457671.{"_csrftoken":"usTiWkUvBQCM25jjcQBT8euhnM2PgVeM","media_folder":"Instagram","source_type":4,"_uid":"4008818448","_uuid":"951664d0-ff8a-457a-bb9e-a445bb5d903b","caption":"tes","upload_id":"1476762742844","device":{"manufacturer":"ZTE","model":"NX511J","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":null,"source_height":null}} ← 200 2.48kB 
RESPONSE: {"status": "ok", "media": {"taken_at": 1476762773, "pk": 1363507431355058228, "id": "1363507431355058228_4008818448", "device_timestamp": 1476762742844, "media_type": 1, "code": "BLsJsjehgg0", "client_cache_key": "MTM2MzUwNzQzMTM1NTA1ODIyOA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "xxSensorxx", "width": 320, "height": 320}, {"url": "xxSensorxx", "width": 240, "height": 240}, {"url": "xxSensorxx", "width": 150, "height": 150}]}, "original_width": 320, "original_height": 320, "user": {"username": "diginstacom", "has_anonymous_profile_picture": false, "is_unpublished": false, "profile_pic_url": "xxSensorxx", "profile_pic_id": "xxx", "can_boost_post": true, "full_name": "xxxx", "pk": xxx, "is_private": false}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiMDA3NTg3Nzg4OTE1NDc1ZWEwNDA0NTI5ZDNiZjcyOGIxMzYzNTA3NDMxMzU1MDU4MjI4Iiwic2VydmVyX3Rva2VuIjoiMTQ3Njc2Mjc3NTUwMnwxMzYzNTA3NDMxMzU1MDU4MjI4fDQwMDg4MTg0NDh8ZDI4M2RjM2IwODU0NDBlNTQ2YzJlMTU4MTE5MDM1MTQ3ZTFmMDg3MmUxMzc0YzM1ZTkxN2UwNGJmYjg3NmRiMyJ9LCJzaWduYXR1cmUiOiIifQ==", "has_liked": false, "has_more_comments": false, "max_num_visible_preview_comments": 4, "preview_comments": [], "comment_count": 0, "caption": {"status": "Active", "user_id": , "created_at_utc": 1476762774, "created_at": 1476762774, "bit_flags": 0, "user": {"username": "xxx", "has_anonymous_profile_picture": false, "is_unpublished": false, "profile_pic_url": "xxx", "profile_pic_id": "1360114975158708866_4008818448", "can_boost_post": true, "full_name": "xxx", "pk": xxx, "is_private": false}, "content_type": "comment", "text": "tes", "media_id": xxxx, "pk": 17843346073154568, "type": 1}, "caption_is_edited": false, "photo_of_you": false}, "upload_id": "1476762742844"} 
POST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=9dbb4861b2a7e44913f7578d9d7f08c3f19438f74e63b5ae6d9eed91644d1ab1.{"upload_id":1476762742844,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":14,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"ZTE","model":"NX511J","android_version":18,"android_release":"4.3"},"_csrftoken":"usTiWkUvBQCM25jjcQBT8euhnM2PgVeM","_uuid":"951664d0-ff8a-457a-bb9e-a445bb5d903b","_uid":"4008818448","caption":"tes"} ← 400 67B RESPONSE: {"status": "fail", "message": "Server got a conflicting upload id"}`

**Comment by mgp25** [comment]
@detho if you see debug log, no bytes are sent during video upload

**Comment by detho** [comment]
@mgp25 
function uploadVideo in HttpInterface.php $bodies no data file??

```json
    $bodies = [
          [
              'type' => 'form-data',
              'name' => 'upload_id',
              'data' => $upload_id,
          ],
          [
              'type' => 'form-data',
              'name' => '_csrftoken',
              'data' => $this->parent->token,
          ],
          [
              'type'   => 'form-data',
              'name'   => 'media_type',
              'data'   => '2',
          ],
          [
              'type' => 'form-data',
              'name' => '_uuid',
              'data' => $this->parent->uuid,
          ],
      ];
```
this line i debug var_dump($resp);
result is null 
I am confused.

**Comment by detho** [comment]
problem solved.
I added SSL_VERIFYPEER..

thx @mgp25

**Comment by mgp25** [comment]
@detho there is a function...

```php
    public function verifyPeer($enable)
    {
        $this->http->verifyPeer($enable);
    }

    public function verifyHost($enable)
    {
        $this->http->verifyHost($enable);
    }
```

**Comment by detho** [comment]
@mgp25 i update a script, i got response in upload video "Please update your instagram app to continue posting photo"

why?
