### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by dcman** [mgp25/Instagram-API#57]
```
REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=1939d9479deaf28e04bc05ba37185ddadfa5577bc3e766e1d6c02efd6a21fd32.%7B%22caption%22%3A%22sdfsdf+%5Cud83d%5Cude0d+%5Cud83d%5Cude18%22%2C%22upload_id%22%3A%221455607149788%22%2C%22source_type%22%3A3%2C%22edits%22%3A%7B%22crop_zoom%22%3A1%2C%22crop_center%22%3A%5B0%2C0%5D%2C%22crop_original_size%22%3A%5Bnull%2Cnull%5D%2C%22black_pixels_ratio%22%3A0%7D%2C%22device%22%3A%7B%22manufacturer%22%3A%22lg%22%2C%22model%22%3A%22Nexus+5%22%2C%22android_version%22%3A23%2C%22android_release%22%3A%226.0.1%22%7D%2C%22_csrftoken%22%3A%2288e5a58390b2cd0595069c02424054b5%22%2C%22_uuid%22%3A%228706f53d-4929-4b47-bb5c-5b026b6f79f1%22%2C%22_uid%22%3A%222940862585%22%7D
RESPONSE: {"status":"fail","message":"Uploaded image isn't in the right format"}
```
![14266](https://cloud.githubusercontent.com/assets/436284/13069653/2f7847d8-d43b-11e5-8651-3afe294a638f.jpg)

**Comment by mgp25** [comment]
Read the response, image is not in the right format, make sure is jpg and has right W x H. Try with different dimensions and formats.

By the way, nice photo

Regards

**Comment by dcman** [comment]
All the photos in the set are in the same format. They were all made with
imagemagic 500X500 and jpg. Uploading worked a few days ago. After the
first few failed uploads I tried with an image that had worked before and
got the same failed response.

Any suggestions on other formats and sizes to try?

Thanks for your time.

**Comment by mgp25** [comment]
@dcman i dont know since i dont upload photos, but keep trying, it should work

Regards
