### ISSUE TITLE
How to unprotected object?

### ISSUE THREAD

**Issue by dyaskur** [mgp25/Instagram-API#572]
How to unprotected object? the result is 
InstagramAPI\FollowingResponse Object ( [followings:protected]

i cant use object of followings cause it's protected, so i must use getFollowings() but it's too uncomfortable for me. 

the old version(8.5) i could use array, but in latest version i couldn’t?

**Comment by mgp25** [comment]
Its easier to call a function that returns everything you want instead of messing with arrays. `getFollowings()` will return all followings in an array.

Regards

**Comment by dyaskur** [comment]
but why so ambiguous??
example $i->getTimeline is given result array, and no function to show/return the result, but    $i->getSelfUsersFollowing() given result object and must call a function to show/return result?

**Comment by mgp25** [comment]
@dyaskur check latest commit. Because im not a machine and im slowly making objects to each response. There is a `timelineFeed` function that returns an object.

**Comment by dyaskur** [comment]
okay thanks, i just asked cause i am not usual with object.
but i hope the object is not protected, so i can call it without a function.

gracias, ur code is very useful.
