### ISSUE TITLE
Loop getting the following list

### ISSUE THREAD

**Issue by MMrR0b0TT** [mgp25/Instagram-API#573]
Is someone having any loop during reading the following list? Even using the nextMaxId I'm gotting this. I've reconnect the user, I restart the nextMaxId too but it keeps happening. Does someone have any suggetion?

**Comment by sander3** [comment]
I actually am. I'm getting 20394 results of someone who follows 374 users...

**Comment by jpmoney5065** [comment]
Check your loops boys, it's working fine
