### ISSUE TITLE
solving captcha feature

### ISSUE THREAD

**Issue by ratm92** [mgp25/Instagram-API#574]
Hi, mgp25 🌊 

How about to add solving captcha feature to your api? 
About a month ago I've sent you my sniff results. 

Also I guess I can do it by myself.. Can you give me some tips via email.

Thank you!

**Comment by MMrR0b0TT** [comment]
Where do you need captcha? Is there any situation that Instagram is asking for?

**Comment by jpmoney5065** [comment]
It will come when it comes(maybe it won't), In the meantime feel free to do it yourself and make a pull request.

I don;t want to speak for mgp25, but I believe he is busy with other things right now.

You can email me with any progress you have and will help if I can. ` jon @ the-website-in-my-profile`
