### ISSUE TITLE
media post issue 

### ISSUE THREAD

**Issue by sumandey121** [mgp25/Instagram-API#580]
Uncaught exception 'InstagramAPI\InstagramException' with message 'Uploaded image isn't in an allowed aspect ratio' in /var/www/html/app/src/http/HttpInterface.php:211

**Comment by mgp25** [comment]
@sumandey121 have you read the exception?

**Comment by beshoo1** [comment]
stange , there is a class made for this to fix each photo to meate instagram aspect ratio
