### ISSUE TITLE
not get followings

### ISSUE THREAD

**Issue by alejandrononemo** [mgp25/Instagram-API#583]
do {
			if (is_null($helper)) {
				$helper = $instagram->getSelfUsersFollowing();
			} else {
				$helper = $instagram->getSelfUsersFollowing($helper->getNextMaxId());
			}
			$followings = array_merge($followings, $helper->getFollowings());
		} while (!is_null($helper->getNextMaxId()));
var_dump($helper);var_dump($followings);die;

object(InstagramAPI\FollowingResponse)#293 (5) { ["followings":protected]=> NULL ["next_max_id":protected]=> NULL ["status":protected]=> NULL ["message":protected]=> NULL ["fullResponse":protected]=> NULL } 
NULL

http://tbeauty.ru/test.php
response in debug mode: ok
What is trouble? Why followings is null?

**Comment by mgp25** [comment]
1) Post debug log

**Comment by dyaskur** [comment]
i think it's just for some accounts, because it's happened to me to, some of my accounts is give null result even if use official app. example:
https://www.instagram.com/adindabarbara/

**Comment by MMrR0b0TT** [comment]
It's happens to me too and I'm using a net version of this api.

**Comment by alejandrononemo** [comment]
http://tbeauty.ru/test.php

post debug log is very very big
