### ISSUE TITLE
LocationFeedResponse.php has some unused code

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#586]
Dear all , im not sure if this is correct , please help me to find out.
in LocationFeedResponse.php we have 2 methods getRankedItems , and getItems
getItems is not working , there is nothing related to it.

is this correct ?

```
  public function getRankedItems()
    {
        return $this->ranked_items;
    }
```
```
    public function getItems()
    {
        return $this->items;
    }
```

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/commit/9628c773d77d9c17e20278379841c03d234c1c6f
