### ISSUE TITLE
[Question] How can i know if Photo is liked/comment by UserId

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#588]
Dear all , 
if you want to know if userId is comment on a photo , you have to get Loop all commenters to know if this UserId is comment on this Pic . That i can do.
but is there any other way ? to avoid Loop ?

No for like. all we know Instagram return 999 liker . what if the userId is the 1001 :)
how can i know if this userId like this photo or not ?
and is there any way to avoid Loop ?

Regards

**Comment by mgp25** [comment]
@beshoo1 not API issue. For programming questions better use google

```php
if (in_array('test', $users)) {
    echo 'test is in $users';
}
```

**Comment by beshoo1** [comment]
@mgp25 , i am a programmer since 10 years ! and i know how to use google.
Please kindly , can you reread the post !

**Comment by mgp25** [comment]
Avoid a loop in your code
--
```php
if (in_array('test', $users)) {
    echo 'test is in $users';
}
```

Likers in Instagram
--
If in the Instagram app (in device), it shows only 999 likers, and you are the 1001, Instagram app will still show the same likers. So... if this API and Instagram app does the same... then you can only return first 999 likers and this mean you can return liker 1001. Sometimes its better to compare behavior of the API with the app, so you can understand better the functionality

**Comment by beshoo1** [comment]
Dear @mgp25
Thank you for your kind replay .

Now if i did like a photo , a small red heart will appear in the app and the web .telling me that i already like this photo .
even if the likers  more than 1000.

Will dos our API provide such thing , an indicator true/flase if the Loged User Like this photo or not  .

Regarding " Avoid"  a loop and "in_array" , i think if you want to get all commenters you need to go through getMediaComments  -> nextMaxId to collect all commenters names/Id , here there is a loop then we fill names in array , then we do 

```
if (in_array('test', $users)) {
    echo 'test is in $users';
}
```

correct me if i am wrong . i am not sure if my english is clear , sorry since my mother language is not english.

Thank you and best regards

**Comment by beshoo1** [comment]
@mgp25 for your attention
