### ISSUE TITLE
Signup Error

### ISSUE THREAD

**Issue by Nikturab** [mgp25/Instagram-API#589]
I tried to sign up with different IPs, user agents and proxies, but i always get this error:

> {"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_action": "report_problem", "feedback_url": "repute/report_problem/instagram_signup/", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Report problem"}

Does Sign Up not working or I do something incorrectly? ( I use code from registration example)

**Comment by mgp25** [comment]
I havent checked it in a while, i guess it works, if not, create an account manually
