### ISSUE TITLE
Video Issue

### ISSUE THREAD

**Issue by honeydewkorea** [mgp25/Instagram-API#593]
Hello.

I am making a uploading video script.
But i failed.

I fit the format '640x640', 'mp4', 'H.264', '29.97 frame rates', etc.
However, i have received a message related 'format'.

How to solve the error?

[](https://www.dropbox.com/s/p9hr1ricc6cj5kw/test_2.mp4?dl=0)
This is a link uploaded the dropbox.

----------------------
Second, Can you give a hint for solve the #485?
I couldn't find a solution, yet.

**Comment by RiTu1337** [comment]
Make sure to convert it to a baseline profile.

**Comment by mgp25** [comment]
@honeydewkorea there are many guides (searching in google) to adapt videos to Instagram format

Regards

**Comment by honeydewkorea** [comment]
@mgp25 I know that and i already modified some parameters.
But the error couldn't solved.

[https://www.dropbox.com/s/i59lablos9z7ymg/test_1_1.mp4?dl=0](url)

> POST: upload/video/ → 496B ← 200 2.44kB RESPONSE: {"status": "ok", "upload_id": "1477021670235", "video_upload_urls": [{"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash1c16\u0026vx_token=103", "job": "AQDmndOZrCuU_FGOSCIbUmmMkLedbV5MWkN6m6ckTW9ffnBPV5q-AggSaEO_JDwSPrEUjTBdQ-ekGEhIuA-owfwAHtFsvSsWK6EBzHBCqJHb0Iv7_REFP_U518oP142tMiSMEflY-6y-XPlYznb92BEsJij9_Xio6HX-8k0xw3QMnH1xBBP18laXJd-wThbUWal_2macYks7NdZ5XMD508YvV0FxTTGldBeWbqJl8mGYMnUGPDv0R149l_6EmJ-onVHtv4kyN6k6fy3tWdQoKo18dhZXAd7NH27C0kMyfsx4p04rkVdFyQasKvBLPpSfe6SPAAYkJkV6a-I22FuLnGWrSUOFEuPpQ1tb-BYT0l7vLXP2bbLtbQJL83gvVBIajbGetMRH83jA74SPfaR_PdJ7O48c6jZPQ3VbSYg2N8nS3-BX8tcqxVNkqsxKMOxVuhXIwlsCMYq1CXSFSU6KNwI7", "expires": 1792381676.180511}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c08\u0026vx_token=306", "job": "AQBeCkU4dVeHJS8dK9QWEBO4fO3cRECsetR7KHD2_uTICPiPR26i6MyVTKl37gGtUzg_L5UiQK7dekd2AEfron9WWDxM6AUJA0Z-F_4o3srm1aoNOHhzF33X7eA-YFspPYZQ0eSGLhLyuQN-xBR8jYx4tzprV3Zr2SdsJFJTY7j1mNh4miie3b1DheM9o1ulMSbIh9roqzktB31fbrPzOdBhVnp2r3TwTFti2NuYiKi_h3R6gXemgrCaeVMzQP_U62yR6mXyLttizEUGHYjHiB4QY0w7Jz4iVU336aezRnqUqYKYVz2Ms2FzvUAJiOBcnt99fWPXyOlREspPkTzMKwU3tA6Bx8KKRlavU7dhzhwdYDoyyxFi-Op2gPxkujso_pxsVZwqn9VUGlopRd8_ouE-XwYRD7t8eTz2F0FXzHi0FEdjIunGlLvFkMUNPVHU9VGEj-R0IQVOqtVj7per9394", "expires": 1792381676.181216}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c06\u0026vx_token=301", "job": "AQBEoNOSxnAMRzWVuZMAsLTdoudu95DcRVBb3Ar1PTv43nez3FGN2d1gqevViP6An_b8sMy7ek2wDAdIZXFnaL9Fg0DfgghH6iDgpvBi4TG6RBXlV4PVXqO87rQsePIvJZ_pGDS98B5AGmYLeT-oZuiXRDrCU6NHpOrDtrBeaGDdfmvmnIqJF8ftsGMkdvxzxIw2_Hu6vwoOWbaS7I4NxMnvZfavVxiLaMIfM_KVyo0mQZtpZ5rn2Anu54Rma5yWxK6tgCgFCuRs9tgqffPjVcR7OLYWyj9xdfGaDmESlbWEvMPAQ35G80tqtOXXaUQ2K4sh0FJJr4YdmshMn3pJo6vcfOlRyF2rTGLdswsZlp019bEB9K16qFoQizPi94QzKNgi_6GD0N-GX5p2rZ4ktHQ1GRCsaEOAR-O1K8eHSjJ9CijRNeQNWPX7_bVWVGNStxX7LLYyINaqKA0rnFH9osZp", "expires": 1792381676.181932}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c06\u0026vx_token=300", "job": "AQCbf-zFjc7kqawDi_4XlWxRVr8ijAT4EQzXDgtFkhN7jtCq0I4V56_-pNtyTIt8b9w7vMAEYeZDhuLvVeJx6CHuQef6_xhAGtuhBi4RP6LzwEGpr1QXhlsSK-JAbFYYjEh05_IDsenOt37Yipkh8yCjNfQrHuYH_vxeOhYqmJUcMZwuM-P0ubfAl5HMywHJ_CTNdbZJZiTGfsJEGb0B8UqXqJr0pxD6yku2NnYTH6LmxTg4evKnMT6KD3NXQXPe2uRoEjM-Eh6YZ_min0xBVzUVVViI6u1gZdPkhUcczyrx_QDecfJZEQsS1T2ULCy-J9i-5HmIYLAKiS1IZCqDCPPN9-Hklkl1LbQPA3-mktF5HFtMiPPmWL-sh-KdB4_iGBsoxa4TTGEowzBJlmNbOlfY_t0hd7m5T1pTy16aiqm0DeEvbyYibcnTdIdAIkPbgqvXj-pEp0q7WHKQsWpnUCyz", "expires": 1792381676.182654}]} POST: upload/photo/ → 156.73kB ← 201 20B RESPONSE: 481476-641967/641968 POST: upload/photo/ → 765B ← 200 46B RESPONSE: {"status": "ok", "upload_id": "1477021670235"} POST: media/configure/? DATA: ig_sig_key_version=4&signed_body=5d07b2bb27ab15e40608e70311d0d27ac676075932edc33ab441f0aeb2a38dc2.{"_csrftoken":"iVnr0GvF4NnU64rObJdEnNAerCHiNNTA","media_folder":"Instagram","source_type":4,"_uid":"4033912453","_uuid":"e3fcd6ed-13c4-48ee-8af0-c6fed9f5e7f1","caption":"#\uce90\uc2dc\ud0dc\uadf8 \ud14c\uc2a4\ud2b8","upload_id":"1477021670235","device":{"manufacturer":"Samsung","model":"GT-I9152P","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":null,"source_height":null}} ← 400 73B RESPONSE: {"status": "fail", "message": "Uploaded image isn't in the right format"} Uploaded image isn't in the right format

**Comment by GuilhermeFM** [comment]
@honeydewkorea Try making the video mp4 container, h264 encode 30FPS with ACC audio format and with aspect ratio between 0.8 and 1.91. Almost any resolution will work as long you keep the aspect ratio between 0.8 and 1.91.

PS: I was forgetting to mention video must be 1 min long or less

**Comment by honeydewkorea** [comment]
@GuilhermeFM  Thanks. But i already made the video that mp4, 600x600(1.0ratio), 29.97fps, progressive, 00:00:14:28, CBR(also i tried VBR), 0.19 Mbps, AAC, 160kbps, 44 kHz, Mono.

But i can't uploading this file. While I could upload the video file on the instagram public application.

What is wrong? Is it a AWS server problem? or PHP version? I don't know the solution

**Comment by haiduong87** [comment]
Try make a preview photo manually and use the optional $preview parameter.
