### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by Stim777** [mgp25/Instagram-API#595]
"Checkpoint_required" error occurs. Request Checkpoint.php script does not send mail code, and the other error in the url, not in the script: https://i.instagram.com/integrity/checkpoint/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss. Show you how to overcome?

**Comment by mgp25** [comment]
I havent checked the `checkpoint.php` in a while, and probably i wont anymore, but you can login in your device to verify it and then go back to the API and it will work

Regards

**Comment by Stim777** [comment]
на устройстве никаких запросов не возникает. На другом аккаунте вопрос появился, подтвердил. А на первом аккаунте не появляется на устройстве запрос.
 
no requests on the device does not occur. In another account, the question appeared confirmed. And on the first account does not appear on the device request.

**Comment by abesmon** [comment]
same problem: no requests on device does not occured :C hope if someone can explain how to bypass such challenge

**Comment by Stim777** [comment]
It helps relogin from iOs app

**Comment by abesmon** [comment]
No, seems not working to me :( code still says `{u'status': u'fail', u'lock': True, u'message': u'checkpoint_required', u'error_type': u'checkpoint_logged_out', u'checkpoint_url': u'https://i.instagram.com/integrity/checkpoint/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss'}`

and no any requests on the device
