### ISSUE TITLE
How to use with composer?

### ISSUE THREAD

**Issue by UnitedComet** [mgp25/Instagram-API#596]
Hello, I need help , I dont know how to lunch RegistrationTool.php i tried a lot of ways but still nothing. I have spended all day on fixing it an have no result. Please give me a tutorial how to do that or what I have to install and how to start. 
Thank you very much,

**Comment by mgp25** [comment]
https://www.google.es/search?q=how+to+install+composer&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=1gsNWKjWBdPEaJXyoZAF

Regards

**Comment by UnitedComet** [comment]
Hi, I have installed composer but I dont know how to run the registerTool.php , can you give me a tip how to do that please? I'll be very grateful

**Comment by mgp25** [comment]
`php registerTool.php`

**Comment by UnitedComet** [comment]
I have tried 
"C:\xampp\php\php.exe" -f registrationTool.php
pause

But i recieve a lot of errors in cmd

and  with php registerTool.php :

User@WZTMWZT-8T2S5SH MINGW64 /c/xampp/htdocs/a
$ php registerTool.php
Could not open input file: registerTool.php

User@WZTMWZT-8T2S5SH MINGW64 /c/xampp/htdocs/a
$

User@WZTMWZT-8T2S5SH MINGW64 /c/xampp/htdocs/a
$ php C:\xampp\htdocs\a\vendor\mgp25\instagram-php\examples\RegisterTool.php
Could not open input file: C:xampphtdocsavendormgp25instagram-phpexamplesRegisterTool.php

User@WZTMWZT-8T2S5SH MINGW64 /c/xampp/htdocs/a
$

**Comment by UnitedComet** [comment]
Update:
C:\xampp\htdocs\a\examples>php registrationTool.php

Fatal error: Uncaught Error: Class 'InstagramAPI\SignatureUtils' not found in C:\xampp\htdocs\a\src\InstagramRegistration.php:22
Stack trace:
#0 C:\xampp\htdocs\a\examples\registrationTool.php(10): InstagramAPI\InstagramRegistration->__construct(false)
#1 {main}
  thrown in C:\xampp\htdocs\a\src\InstagramRegistration.php on line 22

C:\xampp\htdocs\a\examples>pause
Press any key to continue . . .

**Comment by mgp25** [comment]
Did you even read the readme? .........

https://github.com/mgp25/Instagram-API#composer

**Comment by UnitedComet** [comment]
Sorry for such stupid questions, I am not familiar with composer and php. Im programing in another language

```

User@WZTMWZT-8T2S5SH MINGW64 ~/Desktop/MyProject
$ composer require mgp25/instagram-php
Using version v1.5.0.1 for mgp25/instagram-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mgp25/instagram-php (v1.5.0.1)
    Loading from cache

Writing lock file
Generating autoload files

User@WZTMWZT-8T2S5SH MINGW64 ~/Desktop/MyProject
$

```

[User@WZTMWZT-8T2S5SH MINGW64 ~/Desktop/MyProject/vendor/mgp25/instagram-php/exam                                                                                      ples
$ php registrationTool.php

Warning: include(C:\Users\User\Desktop\MyProject\vendor\mgp25\instagram-php\exam
ples/../vendor/autoload.php): failed to open stream: No such file or directory i
n C:\Users\User\Desktop\MyProject\vendor\mgp25\instagram-php\examples\registrati
onTool.php on line 3

Warning: include(): Failed opening 'C:\Users\User\Desktop\MyProject\vendor\mgp25
\instagram-php\examples/../vendor/autoload.php' for inclusion (include_path='.;C
:\php\pear') in C:\Users\User\Desktop\MyProject\vendor\mgp25\instagram-php\examp
les\registrationTool.php on line 3

Fatal error: Uncaught Error: Class 'InstagramAPI\SignatureUtils' not found in C:
\Users\User\Desktop\MyProject\vendor\mgp25\instagram-php\src\InstagramRegistrati
on.php:22
Stack trace:
#0 C:\Users\User\Desktop\MyProject\vendor\mgp25\instagram-php\examples\registrat
ionTool.php(10): InstagramAPI\InstagramRegistration->__construct(false)
#1 {main}
  thrown in C:\Users\User\Desktop\MyProject\vendor\mgp25\instagram-php\src\Insta
gramRegistration.php on line 22

User@WZTMWZT-8T2S5SH MINGW](url)64 ~/Desktop/MyProject/vendor/mgp25/instagram-php/exam                                                                                      ples

**Comment by UnitedComet** [comment]
Update:
Oh , finally I got it. But all the time it says that Username  not available, try with another one
and no request is sended to the server

**Comment by UnitedComet** [comment]
UP. Someone know why registration not working?

**Comment by ankitatejani84** [comment]
hello I need help

PNG image does not upload display ERROR: 
POST: upload/photo/ → 96.2kB ← 200 46B RESPONSE: {"upload_id": "1497962096849", "status": "ok"} POST: media/configure/ DATA: ig_sig_key_version=4&signed_body=10c3659aaf30ab0c8070b52fbf495de78866768b6c85a64068b215490b367b98.{"_csrftoken":"kyuGtg51YM95NTIhQCSDy0mJypR58Zu4","_uid":"5625410436","_uuid":"77a8c579-328a-4ffc-a533-06f35ae1681b","edits":{"crop_original_size":[500,400],"crop_zoom":1,"crop_center":[0,0]},"device":{"manufacturer":"samsung","model":"SM-G930F","android_version":"23","android_release":"6.0.1"},"extra":{"source_width":500,"source_height":400},"caption":"I am using Daily Romantic Love Quotes & I Love it! It's the best way to be motivated through out the day. Get it from Play Store : http:\/\/play.google.com\/store\/apps\/details?id=com.optimumbrewlab.drlq","source_type":4,"media_folder":"Camera","upload_id":"1497962096849"} ← 400 73B RESPONSE: {"message": "Uploaded image isn't in the right format", "status": "fail"} Something went wrong: Uploaded image isn't in the right format.

why png image not upload in instagram?
I'm using https://github.com/mgp25/Instagram-API#composer

thank you
