### ISSUE TITLE
pagination example doesn't always work

### ISSUE THREAD

**Issue by aragonthebest** [mgp25/Instagram-API#600]
Hey, does anybody else have the issue, that sometimes the download of the follower data doesn't work probably, but there is no error, only 2 warnings. 1 because of this line:
`$followers = array_merge($followers, $helper->getFollowers());`
produces the "error": 

> Warning: array_merge(): Argument #2 is not an array

and than 2, because of this line:
`foreach ($followers as $follower) {...}`
produces the "error":
> Warning: Invalid argument supplied for foreach()

yes its a warning, but the result is, that the program doesn't abort, and gives unusable datas.
its not only in the pagination example, it could happen everywhere where pagination is naccessary

**Comment by mgp25** [comment]
@aragonthebest there are cases and cases, since the API return objects, the users have to managed those objects and from there taking it to one or other action.

Regards
