### ISSUE TITLE
getUserFollowings API pagination not working

### ISSUE THREAD

**Issue by MarkoSulamagi** [mgp25/Instagram-API#602]
Hi,

User followings API pagination is not working. Noticed it first yesterday. Tried, but I don't know how to fix it. 

**Request 1:**
`friendships/3445522349/following/?rank_token=3648779790_e005f8cd-fb13-431f-bfe5-ab6dfdb73907`
**Recieved next max id:** AQCETu1f9h2_1wK-P5XrGHfLOV4xNWbB958dsVWNexjGsNH81HplC_VeC-QD_ZLxtKDa76ah7ECcb9twM_Kw96DiQIPyhkqPp5-3KdmTzRyNt_fINZ7oWp7Is-BBM_GqsVE
**200 results:** greatrapsongs, programmers_life, cheekypooh, rayo..., 

**Request 2 with pagination key:**
`friendships/3445522349/following/?rank_token=3648779790_e005f8cd-fb13-431f-bfe5-ab6dfdb73907&max_id=AQCETu1f9h2_1wK-P5XrGHfLOV4xNWbB958dsVWNexjGsNH81HplC_VeC-QD_ZLxtKDa76ah7ECcb9twM_Kw96DiQIPyhkqPp5-3KdmTzRyNt_fINZ7oWp7Is-BBM_GqsVE`
**Recieved next max id:** AQCs4fHRUkqdFDFW86TD6IfZWsUiO6UXRANE-KaaO_FUrS1GDoFedHWitYAu2Bqf5554ZNBkWAC5vOWYrFGRtzPfUKuPGeIkndqkGjuzphBEXha6Rtr2pe9dvVe4TiJj92o
**200 results:** greatrapsongs, programmers_life, cheekypooh, rayofl...

**Comment by mgp25** [comment]
@MarkoSulamagi if you are checking other user frienships, the result is limited to the last/first 200. No matter if you use `max_id`, result is always limited (in this case). 

If you check APP behaviour (alwaus compare API behaviour to the APP), you will see only 200 will be shown

Regards

**Comment by MMrR0b0TT** [comment]
@mgp25 are you saying that I can't get the full following lst from an user?

**Comment by MMrR0b0TT** [comment]
I have the same issue and them I got a infinite loop trying to get the nextMaxId null when I'm trying to read the complete list of the following list of my users.

**Comment by MarkoSulamagi** [comment]
I tested on Sony Xperia L with latest Instagram update and following pagination is working fine. Can anybody else check it?

**Comment by mgp25** [comment]
Count them manually, only 200 will be shown. Maybe im wrong, test it and tell me the result

**Comment by MMrR0b0TT** [comment]
This occurs only for in some situation and the same ocurrs in the App official too. I guess it's not a bug our, but it's a situation. When you're scrolling-down in the app and the users repeat, it's the same situation in here. I coudln't fix it yet.

**Comment by MarkoSulamagi** [comment]
@mgp25 It loads 200 and after I get to bottom it loaded more. I got over 300, before I stopped counting.

**Comment by mgp25** [comment]
@MarkoSulamagi then capture requests, check if there is any differ, and send a pull request if there is any

**Comment by MarkoSulamagi** [comment]
@mgp25 I checked for non-friend user followings and it's also working. That's good news, because it means it's possible to make it work. 

I'll see if I can capture the requests. Might take some time, because I don't have much experience with it.

**Comment by danleyb2** [comment]
@MarkoSulamagi Did you get a fix for this? 

@mgp25 
`getUserFollowings` pagination doesn't seem to work for some user ids like `2200927400`
the response is repeated for all later requests, tested on `dev-master`

**Comment by MarkoSulamagi** [comment]
@danleyb2 Nope, didn't find a fix

**Comment by danleyb2** [comment]
@MarkoSulamagi Too bad, 
Looks like its true from what @mgp25 said, for some accounts, the app (both ios and android) will keep repeating the initial responses

you can test with the above userid, the username is `praguetoday`

and i also noted that this happens for accounts where the `next_max_id` returned is a long string that cannot be cast into an integer

**Comment by berkayk** [comment]
I am having a similar problem where `next_max_id` is always returning **200**. It's impossible to get the next page with this behaviour.
