### ISSUE TITLE
comment post error 

### ISSUE THREAD

**Issue by sumandey121** [mgp25/Instagram-API#603]
```
InstagramAPI\CommentResponse Object
(
    [comment:protected] => 
    [status:protected] => fail
    [message:protected] => feedback_required
    [fullResponse:protected] => 
)
```

**Comment by mgp25** [comment]
Requires feedback

**Comment by prappo** [comment]
@mgp25 what is "feedback" here ?

**Comment by mangledbottles** [comment]
Spam detection

**Comment by prappo** [comment]
@mangledbottles what is the solution?

**Comment by mgp25** [comment]
@prappo not spam

**Comment by Taytus** [comment]
@prappo I was doing some testings (not spamming) but just posting the same comment and triggering the same error. I changed the comment and it worked for me.

**Comment by prappo** [comment]
@Taytus I was also testing not spamming 😂
