### ISSUE TITLE
How get media URL from timelineFeed ?

### ISSUE THREAD

**Issue by chocomage** [mgp25/Instagram-API#605]
Hello,

I just started with this amazing API, I'm a little disappointed with somes functions...

What is the best / simply way to get the media URL from a Item Object  (In this case created from timelineFeed) ?

Thanks by advance.

**Comment by mgp25** [comment]
Every object has its own getter functions. For example: [TimelineFeedResponse.php](https://github.com/mgp25/Instagram-API/blob/master/src/http/Response/TimelineFeedResponse.php)

You can use, `getFeedItems()`, that will return an `Item` object, and you can use the getter function from it, and so...
