### ISSUE TITLE
Suggested users?

### ISSUE THREAD

**Issue by djstanley** [mgp25/Instagram-API#61]
Hi, when you follow a user on IG you get a list of similar users returned, 'suggested users'.

I'm sure this is a simple call with the outgoing parameter as the user's username, could either somebody tell me this endpoint url, or @mgp25 could you add support for this? getSuggested("usernameHere")

Thanks guys!

**Comment by mgp25** [comment]
When you follow someone using this API, the response contains the suggested users, check it.

Regards
