### ISSUE TITLE
App for Windows 10 use "ig_sig_key_version" == 5 and new variables

### ISSUE THREAD

**Issue by skvoshiz** [mgp25/Instagram-API#610]
![screenshot_4](https://cloud.githubusercontent.com/assets/15720360/19775742/0d8aa294-9c7a-11e6-8d3f-58df6ec81ff9.png)
Do you know it?

**Comment by mgp25** [comment]
Yes, and iOS too. Android 4

Not related

**Comment by aliforever** [comment]
Hey, there are some features available on windows 10 instagram that are not available on Android.
But I can't capture traffic with mitm, or charles. They seem to have problems with universal windows apps
Do you know what is the program @skvoshiz is using?

**Comment by RowanFazio** [comment]
@mgp25 @aliforever 
What is the name of this app that @skvoshiz used it?
