### ISSUE TITLE
Indicating The   (Small red heart)  when you like media

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#611]
We all know that we can grep all MediaLikers , but this mean we have to loop through NextMaxId , and only 1000 Name is return.
 
Now if i did like a photo , a small red heart will appear in the app and the web .telling me that i already like this photo .
even if the likers more than 1000.

Will dos our API provide such thing , an indicator true/flase if the Loged User Like this photo or not .

**Comment by mgp25** [comment]
Yes

**Comment by beshoo1** [comment]
Please may you tell me how ? 
i will be thankful

**Comment by beshoo1** [comment]
Any Advice ?
