### ISSUE TITLE
[Question] Is there any endpoint to report a user?

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#612]
Sorry for using this channel to ask a question but i didn't find any other way....

I'm using your api in a project to create a 'virtual cop', it's part of an academic project of AI and I would to be able to report spammy accounts (as is possible in the mobile app) those are discovered by my classifier...

[a brieft about the project]
I've a crawler gathering data from instagram accounts then i use a classifier to determine which of them are fake spammer accounts and report them to instagram community, this project is part of a AI discipline in my university and I want to use real data as validation to my project, so if after some days instagram block or remove that account i reported i can get this return as a right classification and measure the % accurace of my classifier

thanks for your help

**Comment by mgp25** [comment]
Does the Instagram has that feature? If it has it, then there is and endpoint. You can capture the traffic in order to get the request.
