### ISSUE TITLE
Sorry, too many requests. Please try again later

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#614]
/////// CONFIG ///////
$username = 'MYUSER';
$password = 'MYPASS';
$debug = true;
//////////////////////
$i = new \InstagramAPI\Instagram($username, $password, $debug);
try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}
print $i->getSelfUsernameInfo()->getUsernameId();

Logs Attached
[logs.txt](https://github.com/mgp25/Instagram-API/files/560285/logs.txt)

**Comment by beshoo1** [comment]
Since API already knows The account ID
GET:  users/**3022235489**/info/
Why we have to reask API to send one more request !

**Comment by mgp25** [comment]
Post debug log (truncated one)
