### ISSUE TITLE
user mark on a photo

### ISSUE THREAD

**Issue by GoldenEagle66** [mgp25/Instagram-API#615]
Whether it is possible to note the user in the photo, I received a request from the application to see that the request goes to the
`https://i.instagram.com/api/v1/media/$IDMEDIA/edit_media/`
with parameters :
`{"caption_text":"photo test333","_csrftoken":"Kadlma9lX8ybXPVUtdQ48IyGblll3aRj","usertags":"{\"in\":[{\"user_id\":1450877332,\"position\":[0.96666664,0.9916667]}]}","_uid":"3961772133","_uuid":"1bccc9e1-e663-4214-b326-1acc4d1f5e18","location":"{}"}`
but when I send a request
`{"status": "fail", "message": "invalid request"}`
whether it is possible through your library user note in the photo?

**Comment by mgp25** [comment]
It's possible to add a user tag. If you have already captured the request, you only need to code it, and things will work. If you receive `invalid request`, something in the code you did is wrong

Regards

**Comment by baimurzin** [comment]
How can I capture request and after I captured request what should I do to add it to this library?
