### ISSUE TITLE
oembed deleted?

### ISSUE THREAD

**Issue by Stim777** [mgp25/Instagram-API#616]
function oembed is deleted? Why?
Why get mediaId from link?

**Comment by mgp25** [comment]
oembed function? Your questions isnt clear. But i but think its API issue, nevertheless if you post any reference, etc ill answer you

Regards

**Comment by Stim777** [comment]
https://github.com/mgp25/Instagram-API/issues/184

this code not found now

**Comment by mgp25** [comment]
That function wasn never added

**Comment by Stim777** [comment]
without it to get a list of all the photos on the locations added to my photos?

**Comment by mgp25** [comment]
Took me 1 seconds searching......... https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1146

**Comment by Stim777** [comment]
not!

http://www.image123.net/xylacw0h5s3bpic.html
http://www.image123.net/c8uk3ey741wipic.html

from photo to view photos other users in this location

**Comment by mgp25** [comment]
I dont know if that function is coded, but you can code it and send  pull requests. You will need to capture the traffic requests from your device

Regards
