### ISSUE TITLE
Posting video problem

### ISSUE THREAD

**Issue by webfreaks** [mgp25/Instagram-API#618]
Hi,

I have installed FFMPEG to my server. But, I still can't post a video. The error log said:

```
POST:  upload/video/
→ 500B
← 500 	 25B
RESPONSE: Oops, an error occurred.


POST:  upload/photo/
→ 0B
← 0 	 0B
RESPONSE: 

POST:  upload/photo/
→ 8.9kB
← 500 	 25B
RESPONSE: Oops, an error occurred.
```

did I miss something?

Thank you.

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/issues/518#issuecomment-250054920

Check in closed issues before opening a new one

Regards

**Comment by EXECUTOR-brandon** [comment]
Yes I encountered the same issue:

POST: upload/video/ → 500B ← 500 25B RESPONSE: Oops, an error occurred. POST: → 0B ← 0 0B RESPONSE: POST: → 0B ← 0 0B RESPONSE: POST: → 0B ← 0 0B RESPONSE: POST: → 0B ← 0 0B RESPONSE: POST: upload/video/ ← 0 0B RESPONSE: POST: upload/photo/ → 8.04kB ← 500 25B RESPONSE: Oops, an error occurred. 

Is it possible I have wrong ffmpeg version? Here is a screenshot of what I have:

![ffmpegversion](https://cloud.githubusercontent.com/assets/19518737/20433137/4fbd1ba4-ad70-11e6-941b-aca867a7214a.jpg)

Also I have looked at https://github.com/mgp25/Instagram-API/issues/518#issuecomment-250054920  and made the following edits without success:

In the file src/Instagram.php

Edited:

    public function verifyPeer($enable)
    {
        $this->http->verifyPeer($enable);
    }

    public function verifyHost($enable)
    {
        $this->http->verifyHost($enable);
    }


To:

    public function verifyPeer($disable)
    {
        $this->http->verifyPeer($disable);
    }

    public function verifyHost($disable)
    {
        $this->http->verifyHost($disable);
    }

In the file http/HttpInterface.php

Edited:

    public function verifyPeer($enable)
    {
        $this->http->verifyPeer($enable);
    }

    public function verifyHost($enable)
    {
        $this->http->verifyHost($enable);
    }


To:

    public function verifyPeer($disable)
    {
        $this->http->verifyPeer($disable);
    }

    public function verifyHost($disable)
    {
        $this->http->verifyHost($disable);
    }

I have been bouncing around this SSL problem and yes I have a dedicated HostGator server with SSL (https) and it has messed with my PHPMailer program and had to bypass SSL validation to get that to work again after I acquired my SSL certificate.  I'll keep testing and maybe get an answer.

**Comment by mgp25** [comment]
@EXECUTOR-brandon my eyes are bleeding. Do you know that you havent done anything in those functions right? You are just changing the name of the var........

Do you know php? Because thats not the way you should set a value through a function

**Comment by Lastwisher** [comment]
@EXECUTOR-brandon keep hard working did you try 
```
public function verifyPeer($true)
{
    $this->http->verifyPeer($true);
}
```
or 
```
public function verifyPeer($false)
{
    $this->http->verifyPeer($false);
}
```
maybe 

```
public function verifyPeer($variableNamesDosentChangeValues)
{
    $this->http->verifyPeer($variableNamesDosentChangeValues);
}
```

**Comment by mgp25** [comment]
I recommend you this: https://secure.php.net/manual/en/language.references.pass.php

**Comment by EXECUTOR-brandon** [comment]
Actually my problem was not SSL related at all.  The problem was always FFMPEG.  For those who have installed FFMPEG to "/root/bin/ffmpeg", you will NOT have permissions to access the library, hence your terminal commands will work yet php executions will not.  Just remove FFMPEG first, then use this guide: https://s3bubble.com/installing-ffmpeg-on-centos-6-6-in-usrlocalbin/ to install FFMPEG to "/usr/bin/ffmpeg" and everything will work fine since the Instagram API now has access/permissions for execution, as it is working 100% for me now.  Happy Holidays!!!

P.S. To remove the already installed FFMPEG from "/root/bin/ffmpeg" go here and follow the Revert Changes section at the bottom:
http://trac.ffmpeg.org/wiki/CompilationGuide/Centos
