### ISSUE TITLE
get followers not working

### ISSUE THREAD

**Issue by tobsn** [mgp25/Instagram-API#619]
Code:
```
	try {
		$helper = null;
		$followers = [];
		do {
			if( is_null( $helper ) ) {
				$helper = $i->getUserFollowings( $usernameId );
			}
			else {
				$helper = $i->getUserFollowings( $usernameId, $helper->getNextMaxId() );
			}
			$followers = array_merge( $followers, $helper->getFollowers() );
		} while( !is_null( $helper->getNextMaxId() ) );

		echo "My followers: \n";
		foreach( $followers as $follower ) {
			echo '- '.$follower->getUsername()."\n";
		}
	} catch (Exception $e) {
		echo $e->getMessage();
	}
```

Error:
`PHP Fatal error:  Call to undefined method InstagramAPI\FollowingResponse::getFollowers() in test.php on line 32`

Line 32 is the array_merge line. Login works.

**Comment by tobsn** [comment]
Never mind - followers vs followings... mix up!

**Comment by Mifody** [comment]
$helper = $i->**getUserFollowings**( $usernameId );

  $followers = array_merge( $followers, $helper->**getFollowers**() )
maybe
 $helper = $i->**getUserFollowers**( $usernameId );

?

**Comment by tobsn** [comment]
There is still something wrong though...
```
		$helper = null;
		$followers = [];
		do {
			if( is_null( $helper ) ) {
				$helper = $i->getUserFollowings( $usernameId );
			}
			else {
				$helper = $i->getUserFollowings( $usernameId, $helper->getNextMaxId() );
			}
			$gf = $helper->getFollowings();
			if( is_array( $gf ) ) {
				$followers = array_merge( $followers, $gf );
			}
		} while( !is_null( $helper->getNextMaxId() ) );
```

instagram shows for that user 362 followers and the followers array is 13,134...

**Comment by mgp25** [comment]
Duplicate issue. Instagram shows only limited follower/followings. Compare request with the device. You will find aditional info in closed issues with the same topic

Regards

**Comment by tobsn** [comment]
I just compared it with the web view and the web view works just fine... i'll check the code and the requests and see what the difference is.
