### ISSUE TITLE
Problem upload video

### ISSUE THREAD

**Issue by ofernandoleite** [mgp25/Instagram-API#621]
Hello, I'm using your system. Very good!

But has some accounts instagram I can not upload videos and some I can.

I believe the problem is not in the system, as I can upload video of some accounts.

Is it something on Instagram? Something has gone through this and can help me?

_The logs below use the same system, just change the username and password to send the video. (same mp4)_

I was doing the tests, and found that the error occurs in the **uploadVideo() function**.

_**I added a `print_r in "for ($ a = 0; $ a <= 3; ++ $ a)`**_

```php
$result = curl_exec($ch);			
$header_len = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
$body = substr($result, $header_len);
$array[] = [$body];		
print_r($array); //new line add (test uploadVideo)
```

I had an interesting point, see:

**ERROR ACCOUNT UPLOAD VIDEO:**
_
Array ( [0] => Array ( [0] => 0-1359262/5437055 ) ) 
_
Array ( [0] => Array ( [0] => 0-1359262/5437055 ) [1] => Array ( [0] => ) ) 
_
Array ( [0] => Array ( [0] => 0-1359262/5437055 ) [1] => Array ( [0] => ) [2] => Array ( [0] => ) ) 
_
Array ( [0] => Array ( [0] => 0-1359262/5437055 ) [1] => Array ( [0] => ) [2] => Array ( [0] => ) **[3] => Array ( [0] => 4077789-5437054/5437055 )** ) 
_
___
**SUCCESS ACCOUNT UPLOAD VIDEO:**
_
Array ( [0] => Array ( [0] => 0-1359262/5437055 ) ) 
_
Array ( [0] => Array ( [0] => 0-1359262/5437055 ) [1] => Array ( [0] => ) ) 
_
Array ( [0] => Array ( [0] => 0-1359262/5437055 ) [1] => Array ( [0] => ) [2] => Array ( [0] => ) ) 
_
Array ( [0] => Array ( [0] => 0-1359262/5437055 ) [1] => Array ( [0] => ) [2] => Array ( [0] => ) **[3] => Array ( [0] => {"status": "ok", "result": "deprecated", "configure_delay_ms": "6500"} )** ) 
_

**Comment by mgp25** [comment]
@ofernandoleite do you know that there is a built-in debug mode right? From the debug log you will see everything more clear. I don't think it's an Instagram issue, neither the API. If you are using a server, that may be the issue.

If for some reason, you find it is an Instagram API issue, let me know and ill fix it.

Regards
