### ISSUE TITLE
How do you do it?

### ISSUE THREAD

**Issue by sminav** [mgp25/Instagram-API#622]
I wonder how you have disassembled Instagram protocol. You decompile the application or use MIT attack?

**Comment by Mifody** [comment]
Декомпилить ничего не надо, просто отснифать андроид и все :)

**Comment by mgp25** [comment]
@Mifody rush b

write in English, everyone should be able to understand what you are writing

@sminav you will find info in google

Regards

**Comment by beshoo1** [comment]
Easy , setup a proxy :)
