### ISSUE TITLE
{"status": "fail", "message": "Invalid megaphone type id"}

### ISSUE THREAD

**Issue by MMrR0b0TT** [mgp25/Instagram-API#625]
Is normal I receive this message from megaphone or can be something wrong in my code?

**Comment by mgp25** [comment]
@MMrR0b0TT there is something wrong, probably in your code. When logging in, a megaphone request is done, at least for me, works perfectly:

```json
POST:  megaphone/log/
DATA: type=feed_aysf&action=seen&reason=&_uuid=UUID&device_id=DEVICE_ID&_csrftoken=TOKEN
← 200 	 33B
RESPONSE: {"status": "ok", "success": true}
```

@MMrR0b0TT shouldn't you be hacking E corp?
