### ISSUE TITLE
Old Signature Key?

### ISSUE THREAD

**Issue by xCreez** [mgp25/Instagram-API#63]
I think the old Signature Key isn't working anymore...

**Comment by mgp25** [comment]
Works perfectly to me, if you open an issue, you need to provide data, debug log etc.

If your error persists send me an email with all details

Regards

**Comment by xCreez** [comment]
I get this error during login:
{"status":"fail","message":"Your version of Instagram is out of date. Please upgrade your app to log in to Instagram."}
