### ISSUE TITLE
registrationTool.php code is not working 

### ISSUE THREAD

**Issue by mouser53** [mgp25/Instagram-API#631]
Hello,

When I try to use registrationTool.php page for new account create, I have got a lot of error.

* Application cant find settins.dat file ("......\settings-esradenizim045.dat"). Error sceen is as follows.
![image](https://cloud.githubusercontent.com/assets/14909059/19964806/8b4f7be4-a1cc-11e6-9e09-14c75030776a.png)

* Application cant find cookies.dat file

I am also attaching code file.

[ex_registrationTool.txt](https://github.com/mgp25/Instagram-API/files/568871/ex_registrationTool.txt)

Regards.

**Comment by mgp25** [comment]
@mouser53 change the code to check is the path is writable, otherwise settings file wont be created

Regards

**Comment by mouser53** [comment]
I have made it writable, but it did not changed. 

I have created directory. When it has failed, I restored code as original. 

Could you run it?

Regards.

**Comment by mgp25** [comment]
@mouser53 check latest commit, You should do a little research before opening an issue.

Regards
