### ISSUE TITLE
New Instagram Block

### ISSUE THREAD

**Issue by francnuec** [mgp25/Instagram-API#632]
So using the gikdbg.art tool, I couldn't get the sig_key in the latest instagram app. It seems like the app actively checks for attached processes to the app (or if there's a trace) before proceeding. If it finds that there's an attachment, it does not proceed with login, which now makes it hard to get the key.

Please, how can I get around this? Or have you been able to get key yourself?

P.S. I tried using previous keys with corresponding version, but the api returns a "needs_upgrade" error, basically telling me my version is old.

**Comment by MMrR0b0TT** [comment]
How did you tried that?

**Comment by mgp25** [comment]
You can also inject a hook to the app. All Instagram/WhatsApp/Facebook etc does, is always reversible, and there is always a way to get to the data. 

By the way, this issue is not related.

Regards

**Comment by francnuec** [comment]
@mgp25 Can you please give more info on that? It's kinda related here (for one, I got the tutorial from here). I also tried the values in the Constants.php file, still didn't work. My app is down. Please help.

@MMrR0b0TT You should find what you're looking for here: https://github.com/mgp25/Instagram-API/wiki/Technical-information

**Comment by GuilhermeFM** [comment]
if the last version you tried is 9.6.7, i was able to get the key without problem using gikgdb. In case anyone want it 

"0696caff093352eef061e662ac92c784b1fb1efc217b3781f80466ea346ee135"

**Comment by GuilhermeFM** [comment]
@francnuec 9.7.0 - "2f6dcdf76deb0d3fd008886d032162a79b88052b5f50538c1ee93c4fe7d02e60". You must be doing somethink wrong with gkdbg

**Comment by francnuec** [comment]
@GuilhermeFM Thanks for the keys.

I guess I must be doing something wrong then. Although, I used this same technique in the past with no issues till I updated my Instagram app.

Can you walk me through how you do yours? Just to check if I missed anything.

**Comment by GuilhermeFM** [comment]
@francnuec just follow up the old way, find the place where to put the break point as you usually do, then hit F9 until you hit the break point. You could experience some kind of freeze in the app on phone if that is the case just hit F9 again until it unfreeze the app.
