### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by shuk007** [mgp25/Instagram-API#634]
How to add a new line into the caption of the photo/video?
thx!

**Comment by shuk007** [comment]
How to add a new line into the caption of the photo/video?
thx!

**Comment by mgp25** [comment]
@shuk007 https://www.google.es/search?q=new+line+php

**Comment by shuk007** [comment]
I know, \r\n not work

**Comment by MrLuit** [comment]
You need to use "\n" (make sure to use double quotes).
