### ISSUE TITLE
using another vendor package in instagram.php

### ISSUE THREAD

**Issue by mustaqim313** [mgp25/Instagram-API#635]
Yeah this is offtopic. Still hope for an assist.

Let says,I wanna load another class from another vendor and use it in instagram.php. How should I do it?

**Comment by mgp25** [comment]
Import it to the project, add it to the same name namespace, idk, you can also search in google

Regards

**Comment by mustaqim313** [comment]
Thanks it is working. But using a difference namespace and included in autoload_namespaces & autoload_static
