### ISSUE TITLE
Transcode Timeout

### ISSUE THREAD

**Issue by samdonato** [mgp25/Instagram-API#637]
I had opened a similar ticket awhile back.  I get a "Transcode Timeout" error when posting a video.  The recommendation was to retry it once it failed.  I am finding now that most videos fail now and it doesn't matter how many times you retry the same one.  It used to be 1 in 10, now it is 8 out of 10 that give an error.  Would you take a look at this error and let me know if you spot anything?

POST: upload/video/ → 496B ← 200 2.44kB RESPONSE: {"status": "ok", "upload_id": "1478466705789", "video_upload_urls": [{"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c06\u0026vx_token=312", "job": "AQAUskKUhQI8HHJeOqDxdq0MILE1DG6ABOAYCVRFbIyy9wBme10_Bea8rQrQd93Ughm5DanjXkNGEOsVxQhvnPY_9Lp5oS-9OCp1MjQKTWQJ1WEDnvTSCiac9D2Hkof9U9kF2Ih8KJZ2Drdub7Zmkd-XGf-fgXuH1PzSFYWnX0H0Ikup-V13I2G3fXIs8wgx8BhEvTLhPj95m67PYfGVonMSDqIPaSNN5MLLAlUeJgl3cwBFDcOLM0rMXglz2I6LJiL7_edXgk6r79PQs81NMI4VWjMSDIKDcj4YrVdnWOauTiPyKMtbu5HmFnGyBDLGtPxFQLVjAxIwYm4rTPLFH3EwlGVCfKs0wHFSTDL0hkwQd8aO2f6JzHV3oItqSz_pZDE7oONKvBzWikVKhXccZjUxJXx5TV3oPJbGviakldeCYNT2DM5sGro6REbLlp_XFliuZXuX-d8iASs_H7aD7x5w", "expires": 1793826706.077221}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c06\u0026vx_token=300", "job": "AQAvMn90kaYF-jZvFD_0eHiB2CPC6v-JhNuKY-hcWZ_2rj7K1WnJVmo8OgcPIYKP00FtsfPxCaOa4WjcGf8bHsYlLnXSJ0a1hNws2m45H1rtQ1woBugNVa3Mbt_TQV9-2IaqXjbYvBNtoIIOSPG0bxnQRU5Xq23AJYHQd9Hu8bISLFd2OY2hTiH5T20KvIKo5DqVeJXH_T6TzOHnL3Z1G5K6_Y5wlnET6_s6x5gtSII186PI4_jIVhVklDTNPVlz3mcMDbuC6vJ2F5cLRwmrs6-XY44V30kbnZjt2hZ771WTW34ntM7HKyk7PWR-qukGEvDpwwOoq8OUX99ZFXB9q4_2aIUPMxNkUZNXvHpQqDkjd4etYJyt3JPGpxO_b-61RDSejmjJPAvC5T0zctU_n5oJWa70q3BAY9gElrj7xnXAT4eD51TDx0bEMa3lX0OZkmI0IcMzDsUtbg2PEg7DtDwo", "expires": 1793826706.078036}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash3c07\u0026vx_token=102", "job": "AQCxQsv7rLnPsXYkGUNqmqP0FYMbz07iQRGNnYK1De_D5T8xK_t9wHSMblSDr40aJj4X3oR9Z2eyVc9UVErLjpZmrx6EWUn5h3nwbTl2hk7t-Qa3f54AVaIuL5-iHsag835W00TTjWedOEm5lpwlj-Gz9rm-gC7as7PL6ne9QQseHf1ntWvoqZWiIofoDEFUYVeOwBLmYqx5UM8smlFesYL3Su3hirt-gOgu9L-bjqhbhQW_xU_S3YF5l0mPXOsQgw4fsIPyvJD24VYQY_EIlG1Fkz7oP8cJL7du5zzpQ5BMOVOlHEFbAAgneRSZc9sYvSqzwWxE50SLpN0QoXVnsel1tPpgpQ0IN-Hx0v_Y4eOIbplvnhJdHKHX6xiYn_SP-mcX7SasArHz2_zlunIO5GkoRJ3WaDUoQuUtFqkcVznTBDshHxekYdFaHyJ1ZEhujN3s_nIn25hT9ePRegZF7_ok", "expires": 1793826706.078888}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c07\u0026vx_token=304", "job": "AQDSG9eNJV28LYyvuVdFFnU4Yl2YQdv1XAAVAiUWiiisSircca1kZNlh6KfWhoD5E4oo20yipRE44-6IXG12DNuI1C9OyBlqw9_Z0HZoY573HlPdl0JRnzsobY_2jCsrfx0BK7XCY1XBfcagKoao-b3CxZoROKhncSRpQIHxFH4WSyant0HhIQXmixGIOjH761JMqpKQqKCg2Tbts-DnkmoKUav3ty3I8ozclbAR7uzRML7flZ4j6LsrS1SesWUktE5RqyfTsDWea2CPqlZWb12QDDt7dEySu4eWAoisq3SfXOASwpkToJFDFrSiglzochBnVwOmSee52J01J4-piEI3BbM93DAKmvHpiJGeNOCWOcY-hPuRYb0Q7XL-cK58ZjhES_FSeSnKoMWbh5m5D70fNSmfpM7TpghX7A9PLd0cmwotAs4M3UA6PR4SIZ15MO8K0SnFNB3HBY-M1vl9nNz9", "expires": 1793826706.079669}]} POST: https://upload.instagram.com/api/v1/stage/video/?target=ash2c07&vx_token=304 → 1.14mB ← 201 17B RESPONSE: 0-1195402/4781615 POST: https://upload.instagram.com/api/v1/stage/video/?target=ash2c07&vx_token=304 → 2.28mB ← 201 17B RESPONSE: 0-2390805/4781615 POST: https://upload.instagram.com/api/v1/stage/video/?target=ash2c07&vx_token=304 → 2.28mB ← 201 17B RESPONSE: 0-3586208/4781615 POST: https://upload.instagram.com/api/v1/stage/video/?target=ash2c07&vx_token=304 → 1.14mB ← 200 70B RESPONSE: {"status": "ok", "result": "deprecated", "configure_delay_ms": "6500"} POST: upload/video/ ← 201 23B RESPONSE: 3586209-4781614/4781615 POST: upload/photo/ → 53.08kB ← 200 46B RESPONSE: {"status": "ok", "upload_id": "1478466705789"} POST: media/configure/? DATA: ig_sig_key_version=4&signed_body=0b191277bcb99e1ce9cffac7a79071ecae78e09edfacaf6fdc0669f79525e293.{"_csrftoken":"YboS9XFbJdzEelKrpnjO1FNR9nivMDIz","media_folder":"Instagram","source_type":4,"_uid":"3210405428","_uuid":"0cf23392-cb96-4cb7-85e5-e2a62b776377","caption":"\ud83c\udfc6  ","upload_id":"1478466705789","device":{"manufacturer":"Huawei","model":"Orinoquia Auyantepui Y210","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":null,"source_height":null}} ← 202 50B RESPONSE: {"status": "fail", "message": "Transcode timeout"} Transcode timeoutPOST: upload/video/ → 496B ← 200 2.44kB RESPONSE: {"status": "ok", "upload_id": "1478466729950", "video_upload_urls": [{"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c06\u0026vx_token=305", "job": "AQClvtsYpVyBINrMAoTZu46aMP_Z6KfFpx9oDqZjFc9kdJ2B_QLIXLCEPgOJirXNEQ_Xj9Ht6JdXx4-A73fQfAxo9TIIaPyKVaCfOl8h7ehQCbiUPrkNXGHeGPBFtwf4VkvtzIgwbUv5MH--fNsJwCZ0eWmQgE81OmHR_sfpnddCC_VbLMiLHx-NBb3JM7FtY5AYTvPsQiT2OGKpUtbjJnUPt-OlasPFnc2eOg3gF7om-qVXOkAqo9Riuhd4K7Tn9VKC6bMWvrE66moLonhxIS7L-aZpH59BnfpQWlO5woM-zovKcbBFKvT6Q8ypPaCFYUq5D2OYhJ8fECPcn-ptJ93EK3khO0CxJlu3dmj1s87t3EvSYxsga82VJJkDQys4GGa0G73gUhTmys5IuVHZt4jK8j5UxYSnK376zGnlPHqebCTdWkgnG3OhE4Prw5LL98xiRKyu5mefDd1j2dRZIssG", "expires": 1793826730.239146}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c06\u0026vx_token=308", "job": "AQADHZwcuyyKAuU7uvuXDwp5CoFl-IGjIhVo42ASUDx5sOkM9G9Vqu8od_Crx9iEWGi0PFDXJAYwkc8QnPOJOro5vs5nBGWXrfAH-BxgEqYgnNnjyFzgo6_EEIgYfeqbiHfumSkxyq1KYHa7Vw97Ld0ZLJZ6InmN52E71qdzc4LoGjUY-68kQ3cgWNTcc_2PdmulseT06U5JrXCdjiPs7mzL4MzSinNvYiD-z_AM8lFt6TgrXvKmb5TWuqADZqsdeuiz89ZXhCq8FavR-E3bEgz9eeAksfDvBZ8pY8vtkcirtupze3vUi_AjRg8LHtfmAyygcYjifZf7PMZMLuGj147xviHnIzpvKktEFhKm41DBxkaw9JY8UalN22u4fRibBUVv8ZhXwFZKv-pnrM7Qbht8VRydBfNZafdPYSraBZKoI_5i8Dn3-LBrwFRyOIb8UdLNHLmEXh8SImPzp6BIz48l", "expires": 1793826730.239956}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c07\u0026vx_token=303", "job": "AQA4aX_4bUApCoYkD40m5VTl7IVbHQEWrHG_w0t9fnSReFpdL6ee_hg3nBES9l-1kn3lF6DmJNNN7Ozvclz49Hv_tnfEbmO9JHNE58DHhmlHP7X413jrIY6ZVVETYjPR0Q7R5qugSa0M7mY13-h97crGMQwRpfVj2Nt0VkG3XxFIqSA2zOnvR7U-vPe2ZENt3gLnuIuBl4FWHp7ZpO61GciKa2oxrsmDTL9xs0XlMNkIrOGEM_YlN84i4YsmitXrUTnPR8WxzfJnqtGuWqBTdNJpr9LJE-4FiZqUhc2vedIVuC5s-0QtOztg90xWFnngD7VP-2mJIMpihnh0NA1w8zN7WLOa5wXFI6lvsP4ndiaedA_-C3f6z1KH15cWFkxdnuZztpPh0rg4J-laldV3-hVTcAC60Hk9yPf2exx2GHmXEhBk35OBGPKLOVtlh4dUOvq6bIrlSS5Brju8yO4SS0WD", "expires": 1793826730.241335}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash1c16\u0026vx_token=105", "job": "AQD9inikLDABpbhDiPBC7WT4Y9KM3Vb26AK9RiBLHv4_zOUwb5UZg4w1saMIpUKMuzCmxh0nZxxVZnZS8TrXvCARn9vivFyYNohzXmdxnpJpmDl_4PU09qDzt3HxVDx84NXl5HNATf67XptSRuj_PNIPDAb2rUye4bs0S5_ytnND4-9GMjLhOisaWQb5cKfOHKB0OxVA6As1IrrZ0GWWUwljcdugGKPqwhH0lGu7A-qeDCcJDcZDmJwmHWErtfovD3asipQBt3IGge4Lsd73lBicydXhuC9aGaJ0J3bvn8LccCWX_egushii0VFruEQdlY4zsko6hHJJdpqy-lAtQQzkhO4A9AJMGT30KC_wsjr7ZXj6MFbVy4_VIb65jkf-fgC-2Dl3JmWjFjoiO9xCENZDN4INnsArhia71EH_-2Alzycga3ChQZA8SOKtrn40lvNiN9UBHrSlWnvHthP8Kkgx", "expires": 1793826730.242121}]} POST: https://upload.instagram.com/api/v1/stage/video/?target=ash1c16&vx_token=105 → 1.14mB ← 201 17B RESPONSE: 0-1195402/4781615 POST: https://upload.instagram.com/api/v1/stage/video/?target=ash1c16&vx_token=105 → 2.28mB ← 201 17B RESPONSE: 0-2390805/4781615 POST: https://upload.instagram.com/api/v1/stage/video/?target=ash1c16&vx_token=105 → 2.28mB ← 201 17B RESPONSE: 0-3586208/4781615 POST: https://upload.instagram.com/api/v1/stage/video/?target=ash1c16&vx_token=105 → 1.14mB ← 200 70B RESPONSE: {"status": "ok", "result": "deprecated", "configure_delay_ms": "6500"} POST: upload/video/ ← 201 23B RESPONSE: 3586209-4781614/4781615 POST: upload/photo/ → 53.08kB ← 200 46B RESPONSE: {"status": "ok", "upload_id": "1478466729950"} POST: media/configure/? DATA: ig_sig_key_version=4&signed_body=b2fedf12f326bd65a8032af34c5862b09b3277a39c202887b4ac4a84baa4d49f.{"_csrftoken":"YboS9XFbJdzEelKrpnjO1FNR9nivMDIz","media_folder":"Instagram","source_type":4,"_uid":"3210405428","_uuid":"0cf23392-cb96-4cb7-85e5-e2a62b776377","caption":"\ud83c\udfc6 ","upload_id":"1478466729950","device":{"manufacturer":"Huawei","model":"Orinoquia Auyantepui Y210","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":null,"source_height":null}} ← 202 50B RESPONSE: {"status": "fail", "message": "Transcode timeout"}

**Comment by haiduong87** [comment]
I don't see configure video in your log. Have you tried with newest code?

**Comment by samdonato** [comment]
I just downloaded the latest code and same result.  It is only certain videos... I am trying to repost videos.  here is one that never works.  https://www.instagram.com/p/BMWAPMUj3kL/.  I wget the mp4 locally (https://scontent.cdninstagram.com/t50.2886-16/14977952_939879119452195_3176064006846676992_n.mp4) and then try to post.  What else can I do to debug?

**Comment by haiduong87** [comment]
@samdonato add something like this to your code
function: public function uploadPhoto
{
//added code
$retry = -1;
doConfigure:
$retry++;
//end added code
if ($reel_flag) // go find this line in uploadPhoto function
... 
if (!$configure->isOk()) {
                       //added code
			if($configure->getMessage() == 'Transcode timeout'' && $retry < 3)
			{
				sleep(100);
				goto doConfigure;
			}
                       //end added code
            throw new InstagramException($configure->getMessage());
        }
}
This work for me.
https://www.instagram.com/p/BMiRtHWB4is/ (please ignore the preview picture, I can't install ffmgp (or whatever) on IIS, just use a random picture)
@mgp25 please considering to put it in the api. Sorry, I can't make a pr, seen I'm not working with php much (c#/.Net dev)

**Comment by samdonato** [comment]
@haiduong87,  So you just retry if you get a transcode timeout? I have a retry, but I don't wait as long as you.  I also don't set a preview picture at all
```
try {
        $i->uploadVideo($fileName, $caption);
    } catch (Exception $e) {
        sleep(10);
        try{
            $i->uploadVideo($fileName, $caption);
        }catch (Exception $e) {
                      echo "<br/><br/>TRIED TO POST TWICE AND FAILED"  ;
        }
    }
```

What would you suggest?

**Comment by haiduong87** [comment]
Hi @samdonato,
You should read https://github.com/mgp25/Instagram-API/issues/60 carefully.
In your bug log, I see that the "uploadVideo" process has failed at the "configure preview photo" process, so I just retry that step but not the whole process.
And again... please read https://github.com/mgp25/Instagram-API/issues/60 to know more clearly about the upload process.
And try my suggestion above.

**Comment by mgp25** [comment]
@haiduong87 i will.

@samdonato dont reupload already upload media. Try with other media and compare both requests. There are also guides in internet to prepare videos for video upload.

Regards
