### ISSUE TITLE
uploadPhoto in example does not work for me

### ISSUE THREAD

**Issue by rpw98** [mgp25/Instagram-API#64]
I just tried the new code. Login was fine. But uploadPhoto did not work. The call to uploadPhoto returns nothing, resulting in a null upload_id.

**Comment by mgp25** [comment]
@rpw98 it works perfectly. If you want to open an issue, provide data and debug log, otherwise this issue is invalid

Regards

**Comment by rpw98** [comment]
Thanks for quick response. I turned on debug. but like I said, uploadPhoto
does not return anything. RESPONSE prints nothing. I also tried printing
out after this line:

$resp       = curl_exec($ch);
echo "-----------------------upload response------------------";
print_r($resp);

It prints out nothing, really weird.
