### ISSUE TITLE
One issue with photo upload

### ISSUE THREAD

**Issue by rajenpal033** [mgp25/Instagram-API#640]
Hello,
I know there are three types photo types supported by Instagram as follows:
Square Image: 1080px in width by 1080px in height
Vertical Image:  1080px in width by 1350px in height
Horizontal Image: 1080px in width by 566px in height
I can convert the images in any of this format, but while uploading using uploadPhoto method, how do I mention the type?

Thanks.

**Comment by haiduong87** [comment]
Check:
https://github.com/mgp25/Instagram-API/issues/568
Try it yourself.

**Comment by mgp25** [comment]
As @haiduong87 pointed, check `AdaptImage.php`

Regards
