### ISSUE TITLE
Direct Message Thread ID

### ISSUE THREAD

**Issue by Mamedov1985** [mgp25/Instagram-API#643]
I sent a direct message and it worked fine the first time.
But when i tried to send the second message i received an Status OK but the message was not received.

So i got the result and i saw a Tread ID number "thread_id": "340282366841710300949128126314748338735"
I tried to replace the ["0"] 
'type' => 'form-data',
'name' => 'thread_ids',
'data' => '["0"]',

I received a Status OK again but the message was not received again.

Any ideias how to solve that?

**Comment by maximTartachnik** [comment]
Hi 
How you did resole this issue?

**Comment by MAXVELL2010** [comment]
very interesting me
