### ISSUE TITLE
Server got a conflicting upload id

### ISSUE THREAD

**Issue by summy1991** [mgp25/Instagram-API#645]
Hello,  

I try to post video using mpg25/instagram API but error come "Server got a conflicting upload id". and some case its only post images not video.  Please help

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/search?utf8=%E2%9C%93&q=Server+got+a+conflicting+upload+id&type=Issues

**Comment by uditkhullar** [comment]
@mgp25  do we have a pull request to fix this issue :)

**Comment by uditkhullar** [comment]
Is this issue fixed now :)

**Comment by uditkhullar** [comment]
@summy1991 please tell me how you fixed this issue ?

**Comment by summy1991** [comment]
No, I try to fix this. I try to upload video but i got same error. if you
fix that please told me.

Thanks
