### ISSUE TITLE
Signature Key

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#646]
Please tell us. signature key. It is a unique or different on each device? If one key is used a lot of accounts, it will lead to the ban? If yes, how to make the ability to work with multiple accounts?

**Comment by saeid10260** [comment]
hi dear.
i think  it is unique .

**Comment by mgp25** [comment]
@Triden the best thing you could to is reversing the function that handles instagram signature string. And you will see there if it is static data or random runtime data

Regards
