### ISSUE TITLE
Mention on Comment

### ISSUE THREAD

**Issue by pentatonicfunk** [mgp25/Instagram-API#649]
whenever use comment() method but with `@blabalbal` it was success with response something like this :
```php
object(stdClass)#81 (2) {
  ["comment"]=>
  object(stdClass)#82 (9) {
    ["status"]=>
    string(6) "Active"
    ["media_id"]=>
    int(.......)
    ["text"]=>
    string(10) "@blabalbal"
    ["created_at"]=>
    float(1478792436)
    ["user"]=>
    object(stdClass)#85 (8) {
      ["username"]=>
      string(11) "........."
      ["has_anonymous_profile_picture"]=>
      bool(false)
      ["profile_pic_url"]=>
      string(111) .............
      ["profile_pic_id"]=>
      string(30) "..........."
      ["full_name"]=>
      string(9) "......."
      ["pk"]=>
      int(........)
      ["is_verified"]=>
      bool(false)
      ["is_private"]=>
      bool(false)
    }
    ["content_type"]=>
    string(7) "comment"
    ["created_at_utc"]=>
    int(1478821236)
    ["pk"]=>
    int(.......)
    ["type"]=>
    int(0)
  }
  ["status"]=>
  string(2) "ok"
}
```

but when checked on the instagram, there is no comment containing `@blabalbal`

but when comment() with text no mention such as "nice", "good" etc, it success and showed up on instagram, any clue ?

**Comment by mgp25** [comment]
@pentatonicfunk that depends if you account is flagged or not. I can post comments (also containing mentions). Havent tested in a while, but seems an antispam measure. Im not saying that you spam. Maybe Instagram is trying to avoid influence of API users in their platform. 

A good way to test this, would be to compare all incoming/outgoing requests and try to make an exact replica of it. Understanding Instagram code always helps.

Regards

**Comment by pentatonicfunk** [comment]
the problem is : i tested same account, using this API, ad using Instagram on my android phone with same version, 
Comment `@mention` on the same picture, it works on my android phone, but not work on the API, 

on the picture say there is lets say 5 comments, but when i check it, it just show only comment that done by android phone, and other comments that i made with API not showing.

Could you please test it ?
