### ISSUE TITLE
Typo in function 'direct_share'

### ISSUE THREAD

**Issue by RageBrahimi** [mgp25/Instagram-API#65]
You've a typo in your function 'direct_share'

```
			[
  				'type' => 'form-data',
  				'name' => 'recipient_users',
  				'data' => "[[$recimient_users]]"
  			],
```

[[$recimient_users]] should be **[[$recimient_users]]**

Can you also tell us how this works, I'm trying it, but the only receipt is myself? Do we have to use the ID of the user or the username?

**Comment by mgp25** [comment]
@RageBrahimi there is a typo but it works, i tested everything before doing the commit.

Regards

**Comment by RageBrahimi** [comment]
Could you give me quick help as to what '$recipients' should be, as I'm the only recipient when I try it

**Comment by MaximMikulich** [comment]
@RageBrahimi You understand? They need array(id)?
