### ISSUE TITLE
Server got a conflicting upload id

### ISSUE THREAD

**Issue by uditkhullar** [mgp25/Instagram-API#651]
Hi,

Please help I am getting this issue "Server got a conflicting upload id"  when I try to upload a video.

**Comment by mgp25** [comment]
Did you read closed issues?

**Comment by uditkhullar** [comment]
I read but I am not able to find a solution. Please help !!

**Comment by uditkhullar** [comment]
Is it fixed ? Or not ?

**Comment by uditkhullar** [comment]
Please let me know how to fix it ?

**Comment by summy1991** [comment]
Can we post video in Instagram ??? because i try to post video its show error "Server got a conflicting upload id"

**Comment by mgp25** [comment]
Debug and read closed issues, it is answered there. Make sure all dependencies are installed and working fine

Regards
