### ISSUE TITLE
Response is NULL by proxy regestration but user was created

### ISSUE THREAD

**Issue by DenisSokoloff** [mgp25/Instagram-API#652]
```
try
    {
        $result     = $r->createAccount($username, $password, $email, $name);
        if ($result->isAccountCreated())
        {
            echo "Your account was successfully created! :)\n";
        }
        else
        {
            echo "Error during registration.\n";
            if ($result->isSpam())
            {
                echo "Bad Proxy.\n";
            }
        }
        var_dump($result);

    }
    catch(Exception $e)
    {
        echo 'Caught exception: ',  $e->getMessage(), "\n";
    }
```

I got error 

_REQUEST: si/fetch_headers/ RESPONSE: {"status": "ok"} 

REQUEST: accounts/create/ DATA: ig_sig_key_version=4&signed_body=be5afcc616900e2403f63d56eb02f5951a0d4ba80020fa07098c73454b437c23.%7B%22allow_contacts_sync%22%3A%22true%22%2C%22phone_id%22%3A%22182cfb37-df6f-4a34-91ad-2341d6c1d40f%22%2C%22_csrftoken%22%3A%22xHfG7m4WSefwVD3K3u8nH04p6AMeU9g6%22%2C%22username%22%3A%22ad.ad.ad.ad_123417%22%2C%22first_name%22%3A%22+It+Is+Me.%22%2C%22guid%22%3A%22182cfb37-df6f-4a34-91ad-2341d6c1d40f%22%2C%22device_id%22%3A%22android-3d29ed85aaf848d4%22%2C%22email%22%3A%22ad.ad.ad.ad.da17%40gmail.com%22%2C%22force_sign_up_code%22%3A%22%22%2C%22waterfall_id%22%3A%22b9346d71-de91-44c2-9ac2-bf8ffd5307eb%22%2C%22qs_stamp%22%3A%22%22%2C%22password%22%3A%22A1234%21123q17%22%7D_

RESPONSE: Oops, an error occurred.

_Warning: array_key_exists() expects parameter 2 to be array, null given in E:\phpStormProjects\addmefollowers.com\vendor\mgp25\instagram-php\src\http\Response\AccountCreationResponse.php on line 41

Warning: array_key_exists() expects parameter 2 to be array, null given in E:\phpStormProjects\addmefollowers.com\vendor\mgp25\instagram-php\src\http\Response\AccountCreationResponse.php on line 44_

`var_dump($result);`

**object(InstagramAPI\AccountCreationResponse)#2 (20) { 
["username":protected]=> NULL ["has_anonymous_profile_picture":protected]=> NULL ["allow_contacts_sync":protected]=> NULL ["nux_private_first_page":protected]=> NULL ["profile_pic_url":protected]=> NULL ["full_name":protected]=> NULL ["pk":protected]=> NULL ["hd_profile_pic_url_info":protected]=> NULL ["nux_private_enabled":protected]=> NULL ["is_private":protected]=> NULL ["account_created":protected]=> bool(false) ["feedback_title":protected]=> NULL ["feedback_message":protected]=> NULL ["spam":protected]=> NULL ["feedback_action":protected]=> NULL ["feedback_url":protected]=> NULL ["errors":protected]=> NULL ["status":protected]=> NULL ["message":protected]=> NULL ["fullResponse":protected]=> NULL }** 

But user was created

**Comment by mgp25** [comment]
@DenisSokoloff probably spam flagged due proxy

Regards
