### ISSUE TITLE
Instagram version is out of date

### ISSUE THREAD

**Issue by Alex-Bogdanov** [mgp25/Instagram-API#654]
Hi, could you elaborate it a little bit please. I changed the `VERSION` constant in _Constants.php_ to **'9.7.5'** and now when login the app throws:
`Uncaught exception 'InstagramAPI\InstagramException' with message 'Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.'`
What's wrong here? I can't understand. I just forced the _PHP_ app to pretend like I'm an IG mobile client with the latest version.

P.S. Recently, I've just analyzed some intercepted IG mobile app traffic to have a look for some changes in the mobile API. And still no difference in initial _https://i.instagram.com/api/v1/qe/sync/_ request, which expects form-urlencoded value like:
`ig_sig_key_version=4&signed_body=987508607d1b481be24c689a6b223a624675c3d119b4d168a5370bf20feaac95.%7B%22experiments%22%3A%22ig_android_reg_login_btn_active_state%2Cig_android_ci_opt_in_at_reg%2Cig_android_one_click_in_old_flow%2Cig_android_merge_fb_and_ci_friends_page%2Cig_android_non_fb_sso%2Cig_android_mandatory_full_name%2Cig_android_reg_enable_login_password_btn%2Cig_android_reg_phone_email_active_state%2Cig_android_analytics_data_loss%2Cig_fbns_blocked%2Cig_android_contact_point_triage%2Cig_android_reg_next_btn_active_state%2Cig_android_prefill_phone_number%2Cig_android_show_fb_social_context_in_nux%2Cig_android_one_tap_login_upsell%2Cig_fbns_push%2Cig_android_phoneid_sync_interval%22%2C%22id%22%3A%22bba38b57-949f-472d-90d8-dfb2b67f171c%22%7D`

But the server responds with HTTP 400 `{"status": "fail", "message": "invalid request"}`

**Comment by mgp25** [comment]
@Alex-Bogdanov did you also updated the `ig_sig_key`. Please see `Constants.php`

Regards

**Comment by Alex-Bogdanov** [comment]
@mgp25 it's static variable, how can I get the updated version of `const IG_SIG_KEY = '2f6dcdf76deb0d3fd008886d032162a79b88052b5f50538c1ee93c4fe7d02e60';`?

As I understand this is a secret shared key used in _sha256_ encryption algorithm to sign the body of initial sync request

**Comment by lucassimao** [comment]
https://github.com/mgp25/Instagram-API/wiki/Technical-information

**Comment by Alex-Bogdanov** [comment]
@lucassimao thanks!

**Comment by lucassimao** [comment]
@mgp25 seems like the tutorial at https://mokhdzanifaeq.github.io/extracting-instagram-signature-key-2/ isn't available any more. Do you have any copy?

**Comment by mgp25** [comment]
@lucassimao wiki updated with full info.

Regards
