### ISSUE TITLE
Get media_id from url

### ISSUE THREAD

**Issue by ArashFarahani** [mgp25/Instagram-API#655]
Hello . Thank you for your great tool ! Im new to php so accept my apologies if my question is simple . 
How can i get mediaId from url like https://instagram.com/p/BMxEvLBDYZ2/ . Because all the functions require media Id. Except that i know i can get it from user -> user medias -> ..... . I was searching for a simple solution
Thanks

**Comment by mgp25** [comment]
@ArashFarahani search for the user, check the user feed, and from the feed i guess there is a function named `getMediaUrl`

Regards

**Comment by ArashFarahani** [comment]
Thanks . So there is no direct way for getting a post comments for example from instagram url . Do you have any plans for making a functions like this ? 
by the way what is the media_id ? I mean how do you generate it so maybe i can generate it my self .
@mgp25

**Comment by mgp25** [comment]
@ArashFarahani `media_id` its generated by Instagram in server side. You can get post comments by knowing the media id, or searching for the user feed, its the same behaviour as Instagram app. 

If you want to take info directly from a given url you are looking for a scrapper. Anyway, i think its better to use the API, since if the page changes you wont be able to retrieve the data

Regards

**Comment by ArashFarahani** [comment]
Great got it .

**Comment by joseflorido** [comment]
If you have the media shortCode (i.e: BMxEvLBDYZ2), you can convert it to the mediaId (and viceversa), check this function: https://github.com/postaddictme/instagram-php-scraper/blob/8d474a9227984d5437c18804e75d9d46f4d729db/src/InstagramScraper/Model/Media.php#L160

**Comment by mangledbottles** [comment]
```
<?php
function linktomediaid($url);
//$url = 'https://www.instagram.com/p/BM2DRebjTwU/?taken-by=bitchedhoe';
	$urlexplode = explode('/', $url);
	$code = $urlexplode[4];
        $alphabet = [
            '-' => 62, '1' => 53, '0' => 52, '3' => 55, '2' => 54, '5' => 57, '4' => 56, '7' => 59, '6' => 58, '9' => 61,
            '8' => 60, 'A' => 0, 'C' => 2, 'B' => 1, 'E' => 4, 'D' => 3, 'G' => 6, 'F' => 5, 'I' => 8, 'H' => 7,
            'K' => 10, 'J' => 9, 'M' => 12, 'L' => 11, 'O' => 14, 'N' => 13, 'Q' => 16, 'P' => 15, 'S' => 18, 'R' => 17,
            'U' => 20, 'T' => 19, 'W' => 22, 'V' => 21, 'Y' => 24, 'X' => 23, 'Z' => 25, '_' => 63, 'a' => 26, 'c' => 28,
            'b' => 27, 'e' => 30, 'd' => 29, 'g' => 32, 'f' => 31, 'i' => 34, 'h' => 33, 'k' => 36, 'j' => 35, 'm' => 38,
            'l' => 37, 'o' => 40, 'n' => 39, 'q' => 42, 'p' => 41, 's' => 44, 'r' => 43, 'u' => 46, 't' => 45, 'w' => 48,
            'v' => 47, 'y' => 50, 'x' => 49, 'z' => 51
        ];
        $n = 0;
        for ($i = 0; $i < strlen($code); $i++) {
            $c = $code[$i];
            $n = $n * 64 + $alphabet[$c];
        }
        echo $n;


?>
```
