### ISSUE TITLE
Photo configure function

### ISSUE THREAD

**Issue by haiduong87** [mgp25/Instagram-API#656]
Hi @mgp25,  
This is not an issue, I just want to correct some code and I can't make a PR
Please check:
https://github.com/mgp25/Instagram-API/blob/master/src/http/HttpInterface.php
Line 213,
Please add an if/else to configure photo with the $customPreview 
Thanks alot.

**Comment by mgp25** [comment]
@haiduong87 that would be an extra feature. I think its better to avoid fake previews

Regards
