### ISSUE TITLE
help wanted: '/feed/location/$locationId/?max_id=$maxId'

### ISSUE THREAD

**Issue by Alex-Bogdanov** [mgp25/Instagram-API#658]
Hi!
Anybody knows is there any possibility to get location feed by passing location coordinates _(lat, lng)_ instead of _locationId_, which is expected to be found in user profile media.

P.S. My willing is just to get location feed without uploading photo and setting location tag manually and only after that getting _locationId_ from my media feed

**Comment by beshoo1** [comment]
actually you have to get location id by searching for this location pass coordinates (lat, lng) 

`i->searchLocation($_GET['lat'], $_GET['lng'], 'LOCATION NAME');`
it will show you an JSON array with location name and IDs ,
Then you pass the Id , i am sure you know how !

**Comment by Alex-Bogdanov** [comment]
@beshoo1 Yep, thanks. I've already resolved it. It is called `external_id`, which is exactly the same as `facebook_location_id`, which also could be passed to `getFeedLocation` method as `$locationId` parameter
