### ISSUE TITLE
About get all followings

### ISSUE THREAD

**Issue by dleviathan** [mgp25/Instagram-API#660]
Hi, I have problem when get all list following from non-friends user.

		$followingResponse = null;
		$totalFollowingReceived = 0;

		do{
			try {
				if (is_null($followingResponse)) {
					$followingResponse = $instagram->getUserFollowings($idUser);
				} else {
					$followingResponse = $instagram->getUserFollowings($idUser, $followingResponse->getNextMaxId());
				}
			} catch (Exception $ex) {
				var_dump("[" . __FILE__ . " >> " . __FUNCTION__ . " >> " . __LINE__ . "]ERROR GET FOLLOWING: " . $ex->getMessage());
			}
			/** @var array() $listFollowers */
			$listFollowing = $followingResponse->getFollowings();
			if (is_array($listFollowing) && count($listFollowing) > 0) {
				$totalFollowingReceived += count($listFollowing);
				echo("TOTAL FOLLOWING TOTAL: " . $totalFollowingReceived . "\n");
				echo("TOTAL FOLLOWING GET IN REQUEST: " . count($listFollowing) . "\n");
				echo('MAX_ID FOR NEXT REQUEST: ' . $followingResponse->getNextMaxId() . "\n");
			}
		}while(!is_null($followingResponse->getNextMaxId()) || $totalFollowingReceived < $followingCount);

when I run I have result in file:
[resultGetFollowing.txt](https://github.com/mgp25/Instagram-API/files/593712/resultGetFollowing.txt)

It's infinity loops and I always get 1 list user (with 195 users) although `next_max_id` changed every request.

 May be is duplicated at here [https://github.com/mgp25/Instagram-API/issues/619](url) or [https://github.com/mgp25/Instagram-API/issues/602](url) but i still get exactly ** how to fix it?**. 

P/s: when get all followers,  it still working successful not limited.

**Comment by jpmoney5065** [comment]
API is working. 

Here is code I use to get the PK's of a users followings, pretty much the same thing and just tested:

```
$nextMaxId = null;
$following_list = array();
do{
    $userFeed = $i->getUserFollowings('4035945769',$nextMaxId);
    $followings = $userFeed->getFollowings();
    foreach($followings as $user) {
        $following_list[] = $user->getUsernameId();
    }
}while($nextMaxId=$userFeed->getNextMaxId());

echo count($following_list);
```

**Comment by dleviathan** [comment]
Still fail. You must try with userId: 305743277. user only have 222 following

**Comment by aragonthebest** [comment]
@dleviathan , @jpmoney5065  This works:

$helper = $i->getSelfUsersFollowing();
$fullResponse = $helper->getFullResponse();

$following = $fullResponse->users[0];
var_dump(following);




> object(stdClass)#153 (10) {
  ["username"]=>
  string(12) "tuulavintage"
  ["has_anonymous_profile_picture"]=>
  bool(false)
  ["is_favorite"]=>
  bool(false)
  ["has_chaining"]=>
  bool(true)
  ["profile_pic_url"]=>
  string(102) "http://scontent-frt3-1.cdninstagram.com/t51.2885-19/s150x150/13402347_102672053494707_1203077374_a.jpg"
  ["profile_pic_id"]=>
  string(27) "1271667359302254517_7522782"
  ["full_name"]=>
  string(13) "Jessica Stein"
  ["pk"]=>
  int(7522782)
  ["is_verified"]=>
  bool(false)
  ["is_private"]=>
  bool(false)
}

$usernameId = $following->pk;
$username = $following->username;
$full_name = $following->full_name;
$ProfilPicUrl = $following->profile_pic_url;
$is_private = $following->is_private;`
