### ISSUE TITLE
like issue

### ISSUE THREAD

**Issue by arminbiz** [mgp25/Instagram-API#661]
Hello,
I have a problem with this error message when i like media, can you help me with this problem?
this is the error message:

{"status": "fail", "feedback_title": "Can't like post.", "feedback_message": "This post can't be liked right now. Try again in a minute or tell us if you think we made a mistake. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_action": "open_request_form", "feedback_url": "http://help.instagram.com/contact/540011792739811?additional_content=Aehnr2fKPRgkXW9U2SF074YjHj4oWYmTAPbkyfgDjhtWLqLhWqtbDIsHrlhnO5pQtxUZ1XSXZOllG4wq1EXSoOvg5uiagX75NPwBibj9RTnK4gRgGV4nMAVZWENHXuZjUiILPPtjxvKrRkq4lzTck4ffXYs205evt3c8bxD5P8AoZCsIbXBAthJTqKBOEJh_D49McyjAT3M_XL-u5VbFeJPxdLrXYvqEXMGcWKXaGHo1L9FDjj4lQflJtwy2DHBp-vmZuFyHcuofVNF22IwhftXaEcf6w7x397wZpJG6RO9lC9c6V7iyNtmmAopjTkRUbOw4PmmrJyOQXmspNSGwm491Z57Ojt5JALgzFhH-ZCeFWIc8R5lS_vEgQAkGBR4sa3NqkVbb4HOylwTTwwsgRkU8ix1L8JPvhT4Y1JljBKfmR_3VZEiPVrzAIXzZbHum3ArlwJYw85z3RyfzUqQPAAlY2ejaS42RP0Jt8nXhipoxvqtzBLNjOgoDZMhNXEf0jGL-oMz4rg5nuA0rtBYUf_kg_sK9oJo0CiFz2gJZC9f-NdHCeLh0_02xFy2BNmBoFAh9gC9r1mPfw5QJc-_XRyAQzveraS4r6TX8ZEcEE_6-MihiDKWVIA1FQvGE402ti5TO2P1dfjb69rFktRX-rCwevZvvC0d0GP4q_JsDEmPqsjh_tjp1xGxPbZgjEr9KoskjHg-tgbOO6zjtANomPzGzAZBDjB2I59xvS2KvG3NGabMup_uONiz5rCBLBMIJpvpDNMSrBQlCLJnrhXr2FRx-t0eKAPhe-hL9fRZZE7gqF2wYH_V_lsASgYub-9EFIZU\u0026locale=en_US", "feedback_ignore_label": "OK", "message": "feedback_required", "feedback_appeal_label": "Tell us"}

**Comment by jpmoney5065** [comment]
Your account is making too many actions per hour or your account has too much spam activity on it.
