### ISSUE TITLE
Will batch GET post requests be supported (e.g. pass list of ids to media endpoint)?

### ISSUE THREAD

**Issue by edm-ar** [mgp25/Instagram-API#662]
Don't know if I missed something in the documentation, but there doesn't seem to be any support for requesting multiple media ids in the public API.

**Comment by Lastwisher** [comment]
As far as i know if you want to get information about spesifc media id you have to get them one by one. 
Becouse api support that way, if you think api support batch request please send a link.

**Comment by mgp25** [comment]
@edm-ar app does not do this

Regards
