### ISSUE TITLE
Photo Not Posting to Instagram

### ISSUE THREAD

**Issue by MichaelFriedberg** [mgp25/Instagram-API#668]
Ran uploadPhoto.php and it did not upload photo.

**Comment by lucassimao** [comment]
please, run in debug mode and post the log. will be helpful

**Comment by MichaelFriedberg** [comment]
One thing I should mention was the getPK() function  in Instagram-API/src/Instagram.php (LINE 162) was not working. 

So I manually overwrote with the pk value from the JSON blob that was returned. I got a success message. 

`//$this->username_id =  $response->getLoggedInUser()->getPK();`
TO
`$this->username_id = 12345678; `
(Thats not really my username_id)



`POST:  upload/photo/
→ 84.87kB
← 200 	 46B
RESPONSE: {"status": "ok", "upload_id": "1479451134750"}`
But no upload.

**Comment by MichaelFriedberg** [comment]
BTW where is the error log file?

**Comment by MichaelFriedberg** [comment]
Okay Guys and Gals
by changing 
`$this->username_id = $response->getLoggedInUser()->getPK();`

TO 

`$this->username_id = $response->getLoggedInUser()->getUsernameId();`

you can get rid of that getPK() function does not exist error. But still no upload to insta.

**Comment by mgp25** [comment]
@MichaelFriedberg everything is explained + i thing you are confusing name getters with its values. If not uploaded, probably account flagged

Regards

**Comment by mgp25** [comment]
@MichaelFriedberg there is a bug in latest code, will be fixed within the next hours

Sorry

Regards

**Comment by MichaelFriedberg** [comment]
@mgp25  Dude let me help you out.

**Comment by Lastwisher** [comment]
Tomorrow i will hopefully fix this issue, so far what i can say is getPk() is correct function on most of cases
