### ISSUE TITLE
Bad image resize in AdaptImage

### ISSUE THREAD

**Issue by Aerox1** [mgp25/Instagram-API#670]
Hi . i have a picture with size of 1246 * 1280 and i check it with AdaptImage class . but still the photo isnt in the right format . and its different from when i upload it manually through the app . And the image format IS jpg . 

this is the original file :
![photo_2016-11-18_12-16-18](https://cloud.githubusercontent.com/assets/7089492/20434506/4c08a080-adbd-11e6-9133-ea64f6d57ba9.jpg)

And this is how it is uploaded :
![photo_2016-11-18_18-28-04](https://cloud.githubusercontent.com/assets/7089492/20434534/69202990-adbd-11e6-810a-c36cec6c3867.jpg)

Thanks for your help

**Comment by jpmoney5065** [comment]
Using `adaptImage` almost always gives me bad results, I have totally bypassed it in my code. Instagram will accept most image dimensions these days, from my experience.

**Comment by Aerox1** [comment]
So you dont do any resize ? If you do can you give me some hints please .. @jpmoney5065

**Comment by mgp25** [comment]
@Aerox1 adatImage will be skipped in the next commit

Regards
