### ISSUE TITLE
Is there a way for get next iterations of timelineFeed ?

### ISSUE THREAD

**Issue by chocomage** [mgp25/Instagram-API#671]
Hello,

I have seen in many functions like getSelfUserFollowers there is a parameter for maxId, so we can iterate and have the next results, but with $account->timelineFeed() there is no function parameter like with getSelfUserFollowers.
There is no way for have the next iterations of timelineFeed items ? 

Thanks by advance.

**Comment by Lastwisher** [comment]
If we do that and someone use it for 10m follower its will take forever this is why we left that to developers.
