### ISSUE TITLE
Follower request to profile

### ISSUE THREAD

**Issue by PhilipOnline** [mgp25/Instagram-API#673]
Please, help me to get that users (usernames) who have done follow request to my profile.
As a result, we have only сount of users, which have sent follow request to me.

'counts' : {
	'requests' : 81,
	'relationships' : 0,
	'photos_of_you' : 0
	
but don't have usernames of followers.

**Comment by lucassimao** [comment]
Give a look at the PaginationExample.php file in the examples source folder of the project repository

**Comment by PhilipOnline** [comment]
as result of this file we have followers, but i want now usernames people who done request to my private profile

**Comment by mgp25** [comment]
@PhilipOnline i dont remember the object response but, if you dump it `var_dump()`, you will see all information about the object. Accesing to its values:

if field is `media_id`, getter will be `getMediaId()`

If you have any doubt, post your code and we'll help you.

Regards

**Comment by Mamedov1985** [comment]
After get the Follower request user what command do u use to accept them ???
Thanks.
