### ISSUE TITLE
uploading photo

### ISSUE THREAD

**Issue by moralesf1** [mgp25/Instagram-API#674]
i just try to upload a photo and i get this error, Instagram Exception in Http Interface.php line 238
What does it mean?
this is the data that i sendding 
$instagram->uploadPhoto('C:/xampp/htdocs/tesis/public/uploads/imagen7.jpg','instagram nuevo');

**Comment by MZK91** [comment]
I'm having the same issue. I just updated from the last version and i now i can't upload any photo.

**Comment by mgp25** [comment]
There is a bug in latest version. Will be fixed within the next hours / tomorrow morning

Regards

**Comment by moralesf1** [comment]
Ok, i'll waiting for it, thanks.

**Comment by MZK91** [comment]
@mgp25 Thanks, you are doing a great job !

**Comment by mgp25** [comment]
Fixed in latest commits

Regards
