### ISSUE TITLE
Issues on video upload

### ISSUE THREAD

**Issue by MZK91** [mgp25/Instagram-API#676]
Hello, since the newest version i'm having issues with the video upload.

Here it is the error message : 

`Wrong function getVideoUploadUrl `

Thanks.

**Comment by mgp25** [comment]
@MZK91 are you using latest commits? there were come changes

**Comment by MZK91** [comment]
Yes, i'm using the version 1.6.0.1, i'm updated a few hours ago.

**Comment by mgp25** [comment]
@MZK91 will be fixed in the next minutes

Regards!

**Comment by MZK91** [comment]
Thanks @mgp25 U r the best, tell me if you need help ?
It'll be a pleasure if i can help u !

**Comment by mgp25** [comment]
@MZK91 fixed in latest commit

Regards
