### ISSUE TITLE
When we update Lib we have to respect the old working flow 

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#677]
Dear Devs.

Thank you for the new Lib update , but all our hard work was disrespected by updating the way you deal with functions and Responders .

Wrong function getFollowers...
and a lot of things is not working , so as i know there is some thing called , know-how to upgrade to the new version with changed functions names and how to use the new way,

now i am searching arround my code and seeking the repo. to find how-to ,,,

even 
  public function getNextMaxId()

is not available.

i am sure this new repo is not ready!

```
PHP 5.6.28 (cli) (built: Nov 20 2016 02:41:28)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Suhosin v0.9.38, Copyright (c) 2007-2015, by SektionEins GmbH

 
```

**Comment by mgp25** [comment]
We are improving the code, and if you dont like it, then do things your own. If you get used to things and never improve them, then shitty things will appear eventually.

+ it has backwards compatibility, if you bother a little searching the code you will see it was a typo what caused that, but it is always better to complain in the issues section 

You told me once you were developer with 10 year experience. You should know what im saying

It will be fixed in the minutes

**Comment by mgp25** [comment]
In the response class there is a var named `$users` then the function will be `getUsers()`, the same happens with all the classes and vars.

In the case of followers is just changing `getFollowers()` to `getUsers()`, this way mapping values will be easier with Instagram server

**Comment by beshoo1** [comment]
the problem i note,  you assume that i did not search. but honestly i did.

it will be nice if there is a change log about renamed functions so dev can
replace them.

dev make methods,  test them, its works,  then he forgot them since it
works fine.

by updating the functions names,  this will break things out.  you know
that.

again,  you assume that i don't like the new code.

infact i love it.  the chain classes, i love it.

so please take it easy.

good work and please be patient with me.

i note,  there is responses when calling unavailable function.
it will be nice if the response some thing like :

this function N has been changed to X.

this will help other to upgrade.... our as i said,  a change log will be
fine.

i am sure we are in the same side,  but with different glasses,  please
take my glass and see what i sow.

Thank you for your your reply.
