### ISSUE TITLE
What is nextMaxId exactly ?

### ISSUE THREAD

**Issue by Aerox1** [mgp25/Instagram-API#678]
Hello . Do you generate nextMaxId yourself or you get it from Instagram ? Because i had a wired experience . I was getting one media comments and in the middle accidentally switch to another media with the same nextMaxId and it was still giving me the results . 
I wanted to know what exactly nextMaxId is and how it generated .

Regards

**Comment by mgp25** [comment]
@Aerox1 generated by the server, it is used for pagination. When you are in the app, and want to load for items, photos etc while scrolling down, `max_id` is passed as a value to get the next items.

Here is one example: https://github.com/mgp25/Instagram-API/blob/master/examples/PaginationExample.php

Wiki documentation: https://github.com/mgp25/Instagram-API/wiki#pagination

Regards
