### ISSUE TITLE
Registration does not work

### ISSUE THREAD

**Issue by sekon-am** [mgp25/Instagram-API#68]
When I'll run 

php registrationTool.php

script logged

REQUEST: accounts/create/
DATA: ig_sig_key_version=4&signed_body=edbcd298b1680ca8cb62f30fa13839021f16d74a83fbce02aea00c5d83b83bca.%7B%22phone_id%22%3A%2262d9ef40-a488-4005-a2a0-8245e9ab660e%22%2C%22_csrftoken%22%3A%22missing%22%2C%22username%22%3A%22cat_john01%22%2C%22first_name%22%3A%22%22%2C%22guid%22%3A%2262d9ef40-a488-4005-a2a0-8245e9ab660e%22%2C%22device_id%22%3A%22android-a012869311d64a44b%22%2C%22email%22%3A%22cat_john_01%40mail.ru%22%2C%22force_sign_up_code%22%3A%22%22%2C%22qs_stamp%22%3A%22%22%2C%22password%22%3A%22somepass%22%7D
RESPONSE: {"status": "fail", "feedback_title": "Signup Error", "feedback_message": "Sorry! There\u2019s a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "spam": true, "feedback_ignore_label": "Ignore", "message": "feedback_required", "feedback_appeal_label": "Tell us", "feedback_url": "http://help.instagram.com/contact/540011792739811?additional_content=AehCnkC7rgev6tZdeelWAVJKLYgxjD1tQuMx7BwrgC1BsBzpXoJ9gkStMycsOogCTwIfx-XAtnL2Cd58d8N11DxO7xXGkXb1C-o3FFDmsPWV7TyNxv_eYjiVqdQbVwRt13BD7hKMe8LrAc0tBjuF5C0O_-5TO13jIyTnGnioen9aB1X8t1L9ZWFQ1_n6t-XgBwKe4rVaqHwyH-E5A0jiI6BENvyJYhAlpk_twjoxRCOQMZqRSmV4SFdE--mKBtskR76gljLtibW8EG1zOQdvb4Xuqn_JDaItVyKOf6VjFMF6yMEMZ81PuKVb1sMTrUTDKYYlSR0HgbyEExqEgSP2jpdKgoyBBO96B0v2x_JpBbazt8Xx7qb_zcASZhmP1PEclWQ5VxJTwf7eLmgAvFR227pKGiyANpMuhfH43nPCHZRG9oyI2jHDWIfGeiZcUSjbHMepqFY2WixR_Hvz6vw3ihJ2zZmuUiUGRvxldRGOTcvMdZRLSjOJz3y6MFriuCzzPq08AZFb1ECiWNvpjs-q6xzJHjCX3VvsuwIEXhDiS0etZQ\u0026locale=en_US"}

**Comment by mgp25** [comment]
@sekon-am retry again, look at the response: `Sorry! Theres a problem signing you up right now. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.`

I just tried and it works perfectly.

Regards

**Comment by sinnus** [comment]
Looks like IP is banned by instagram
