### ISSUE TITLE
Proxy Error - Register account

### ISSUE THREAD

**Issue by mangledbottles** [mgp25/Instagram-API#681]
Hello mgp25,
When I try to register an account using proxy I get error
`Fatal error: Uncaught exception 'InstagramAPI\InstagramException' with message 'Couldn't get challenge, check your connection' in /home/instetzy/public_html/test821/beta/src/InstagramRegistration.php:174 Stack trace: #0 /home/instetzy/public_html/test821/beta/src/InstagramRegistration.php(137): InstagramAPI\InstagramRegistration->getCsfrtoken() #1 /home/instetzy/public_html/test821/beta/examples/registrationTool.php(50): InstagramAPI\InstagramRegistration->createAccount('burmysdh87s45', 'admfinas1122', 'adminburhan@gma...') #2 {main} thrown in /home/instetzy/public_html/test821/beta/src/InstagramRegistration.php on line 174`

I'm using a private proxy and it works when being used to just log in. I believe there is an issue?

Thanks :) 👍

**Comment by mgp25** [comment]
@mangledbottles it seems Instagram is refusing your connection

Regards

**Comment by mangledbottles** [comment]
It happens with all proxies for me when registering but not when logging in with proxy, can you check it works for you :) 
Thanks
