### ISSUE TITLE
getFollowerCount returning null always 

### ISSUE THREAD

**Issue by vishal2947** [mgp25/Instagram-API#682]
I am using pagination example and trying to get follower count of my follower using:

`    foreach ($followers as $follower) {
        //var_dump($follower);
        echo "<br><br>";
        echo '- '.$follower->getFollowerCount()."\n";
    }`

but it is always returning empty. Any suggestions what i am doing wrong?

**Comment by mgp25** [comment]
@vishal2947 it is working. Make sure you have latest commits

Regards

**Comment by saeedvaziry** [comment]
Not working for me too
