### ISSUE TITLE
Changes on DM Api

### ISSUE THREAD

**Issue by eduardoboca** [mgp25/Instagram-API#685]
Along with the new features announced by Instagram yesterday (disappearing photos and videos for groups and friends in Instagram Direct), has the Api tha sends DM changed?

**Comment by lucassimao** [comment]
why? any error?

**Comment by eduardoboca** [comment]
Yes, since yesterday I've been receiving a "Bad Request" response...

I'll double check my code, just wanted to see if anyone out there had the same problem.

Is your code still working fine?

**Comment by lucassimao** [comment]
Just checked my bot store instagram's bot and it's working fine, sending direct messages without problems. Do you have the updated version of the library?

**Comment by eduardoboca** [comment]
Ok, I'll close the issue and review my code then. Thank you very much for the quick response!
