### ISSUE TITLE
Transcode timeout 

### ISSUE THREAD

**Issue by MZK91** [mgp25/Instagram-API#687]
Hello,
With the newest version i'm having the "Transcode timeout" even with the error catching and the "sleep()".
Here it is my code : 
```
try {
            $this->instagram->uploadVideo($filePath, $caption);
        } catch (Exception $e) {
            echo $e->getMessage();
            sleep(10);
            $this->instagram->uploadVideo($filePath, $caption);
        }
```

**Comment by RiTu1337** [comment]
@MZK91 https://github.com/mgp25/Instagram-API/issues/637

**Comment by MZK91** [comment]
I don't see whats wrong, here it is the debug results : 

POST: upload/video/ → 496B ← 200 2.52kB RESPONSE: {"status": "ok", "upload_id": "1479855321966", "video_upload_urls": [{"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c08\u0026vx_token=313\u0026staging_in_tao=0", "job": "AQDVex_QeVcQo5x2rXnKxqCvaKffY7_7nDYeqoAT39iz3H3kFn6BZHKfRf7s_DIv3fB6sZnS0YH4cK3tJlG87zBOk9rj9Up_sO2faXjBNIvTgTmTo5iX0TJvdxoXElhrAjDJWmRQV-dvY21ySItkz7ZjL3QQX9WYVipgbvuQuRwfGO7e4VxxTdnqPFEiuYt6WV2M_y5WM6hBdwdoHQGv0F4nJ4nTXskzu47oc1efn6ZiNdzElmcbUArTZVwBi1os0hpDwZtVgXo-bAXjYzacW5xvP3EBXUipgIzZDtjOW2UyAu6hy3jclD4rKxHQjKQAJHrg2G-aFiwi6O80PpLX723zeY1FM61CP5QBPnlqNBzL_41FoIjVNBBa5FgqTcbVRnPCCghtslbmQu1CXvfRCYAzvh1XmlvrTsLIH7A8bWauf3IgJMbde9ssPY3RlZ6tkvUC9y0-ocOM1d0RwdCvEo5Q", "expires": 1795215646.378157}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c07\u0026vx_token=304\u0026staging_in_tao=0", "job": "AQAg9AtnmFgQaA8dEkJX_xKS3iqRzVnprF57XUkRZBnX8CmeeONRHJ3A9NYcITTLM_qzJbkJOkIvRajBxYvayQvtcpT5fCRWJajprSur5fympFosDfSiRvR9ScogO18P05_dPVwW8R1PCdO4u4yqWguS8Sa7pB8m3p8Dk84fYeuKguhv9xfZEaYHAZ_XkzMvez5ry9zTfPqlAY6t8Q4zyc2bTKsyYCLQm6km4LERTjWxfnZtGcWHmKS68A33GhE5xNhm8-CmfddWLiEkz0AxuAkiT1XbJiDnwOs-JwcF9ePWiv5neenwj-JW3pLtakhGeUOz8WfaADoRhVJviySaNqRQqqXUXL03zU9zd_N-RmjrfEQqKOKAtEXu_lnPYN_eOOoZjjm1Y5fEwd79M9WdEBX74ftljjfXXTnVHOPHeyTLBUWjeSILP2g7jMs1sOkUorMlGmA-GLnKCZwqbfedKuNG", "expires": 1795215646.378892}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c08\u0026vx_token=306\u0026staging_in_tao=0", "job": "AQBpSsadmx5yVoUwI5c0yXh71urkhVNHJI8Oia7mD71irzDL42jhPJY8JljPxmShixeMDVXMJsMowREFVAoyPehIztpV22Uc_3JA9hyh7L9vlS5nQtdNj_rmN2DIGo99tABzNzXwPsf9nfv5swXsfvd8fHfHdaYkUVYzlT-wIUwVtQ3wiAg8MwAlL4OoCtNr4SNG9gZ2KwbSsl59z376ufSZDJvU4zezv0EnWGidGsu0j9CJbazNrqcP-TcyClwDRiCldcfbBouUtj5zbIzII2ApHD-KH0VQuUKGpuSzPQXkyO0SyOIYIRokSPtNpqkI1Rjonknaz78K_5giNfjl61pXOWJ9jY-AD_kQemI23Lo8BGxSoPIwros1kQRV3TPKCpjF_FxHr_SFwk6Og1zxAS35E5RyJ7NwlJCMJ7o3WfzPqy93y3JMbsZ8PK0WyqNXmDKmbqbR6QJYX7c94DV9AIoO", "expires": 1795215646.379599}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=ash2c07\u0026vx_token=106\u0026staging_in_tao=0", "job": "AQDBqirlftugnN0hGwWqIH4RoBEhc8V8sB7SkmJLUMe-wyOMk2GsfjPnIWWwtwRz581PVprElmPGMCNe2meBOnPfEqLDNuHLzrECMvnQTVg5-2wXlRXuYmmSFb1YnUvW-bvnDma7F3iLwqsp_NfAcxDrD3CpNYERxGFfMpejxbgd1l0rYeuiVGKfWJUQidpTPcKgoCIYL-5MQjQzBZYH9KH5Hktjf-NA8cIWK-vysgY5S8MBDYBZKIKmi52XDQjuVyHioOcueozj5Pq3cs714nBHGDG39sLzZIWv99EgISlKrW0rm_PDLE660Essb4F7lF7ErStvn1Ol6uwkVLkimtpTINuuQdfAjHl5dc2fl0qDTBVgo0zZ6Cy0fUib3AN9zfVv2kljoHZl1oNGHftsGdZuSiBbB2Rmzkb4sIykue2Xtdlqlho5-KySYbmC6dzvm0KHa77hWANea4dxMN74u8Wn", "expires": 1795215646.380291}]} POST: https://upload.instagram.com/api/v1/stage/video/?target=ash2c07&vx_token=106&staging_in_tao=0 → 1.32mB ← 201 17B RESPONSE: 0-1383389/5533563 POST: https://upload.instagram.com/api/v1/stage/video/?target=ash2c07&vx_token=106&staging_in_tao=0 → 2.3mB ← 201 17B RESPONSE: POST: https://upload.instagram.com/api/v1/stage/video/?target=ash2c07&vx_token=106&staging_in_tao=0 → 2.3mB ← 201 17B RESPONSE: POST: https://upload.instagram.com/api/v1/stage/video/?target=ash2c07&vx_token=106&staging_in_tao=0 → 1.32mB ← 200 70B RESPONSE: {"status": "ok", "result": "deprecated", "configure_delay_ms": "6500"} POST: upload/video/ ← 201 23B RESPONSE: 4150170-5533562/5533563 POST: upload/photo/ → 15.83kB ← 200 46B RESPONSE: {"status": "ok", "upload_id": "1479855321966"} POST: media/configure/ DATA: ig_sig_key_version=4&signed_body=e68dfa8bfa39e6a96c9e5b3b19ec0e8bc586608d7463145a3b14671cc670e459.{"_csrftoken":"KTPwaZjsDkdAEKMDSWssmsOWJqFAQKUQ","media_folder":"Instagram","source_type":4,"_uid":"53509776","_uuid":"493f0b6b-563b-4ed4-b0ee-074636da2608","caption":"Freestyle \u00e0 l'ancienne d'Ademo de PNL ! * * * #Ademo #PNL #ThrowBack #Freestyle #QLf","upload_id":"1479855321966","device":{"manufacturer":"TCT (Alcatel)","model":"6016A","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0,0],"crop_zoom":1},"extra":{"source_width":null,"source_height":null}} ← 202 50B RESPONSE: {"status": "fail", "message": "Transcode timeout"}

**Comment by mgp25** [comment]
Make sure you have installed `ffmpeg`. If you have it installed, make sure the preview photo is generate correctly. If you see the latest request in the debug log you have posted, you will notice this:

```
crop_original_size":[null,null]
```

The line is:

```           
 'crop_original_size' => [$size, $size],
```

The value is taken from `$size = getimagesize($photo)[0];`

And `$photo` is the preview photo generated by ffmpeg, so check if its generated correctly and why its failing your ffmpeg.

You can also hardcode the size of the preview if you want to check, but i highly recommend debugging why ffmpeg didnt generated correctly the preview or why ` getimagesize($photo)[0]` returns `null`

Regards
