### ISSUE TITLE
unable to send direct_share

### ISSUE THREAD

**Issue by spidersanghvi** [mgp25/Instagram-API#694]
<?php

	include '../../../../vendor/autoload.php';
	require '../src/Instagram.php';

	/////// CONFIG ///////
	$username = '';
	$dm = [];
	$password = '';
	$debug = true;
	//////////////////////

	$i = new \InstagramAPI\Instagram($debug);
	$i->setUser($username, $password);

	try {
		$i->login();
	} catch (Exception $e) {
		echo 'something went wrong '.$e->getMessage()."\n";
		exit(0);
	}
	$ids = [];
	//foreach($dm as $user){
	//	$a = $i->getUsernameId($user);
	//	array_push($ids, $a);
	//}
	$a = $i->uploadPhoto('image.jpg');
	$i->direct_share($a, $dm);

This code gets this error:
Catchable fatal error: Object of class InstagramAPI\ConfigureResponse could not be converted to string in C:\xampp\htdocs\vendor\mgp25\instagram-php\src\http\HttpInterface.php on line 801

http://pastebin.com/r8rgpYmG

**Comment by mgp25** [comment]
@spidersanghvi you are passing an object not a string. Check the values passed to `direct_share` and read the function documentation
