### ISSUE TITLE
failed login on v1.6+

### ISSUE THREAD

**Issue by juicytuna** [mgp25/Instagram-API#696]
When trying to log in, it slowly tries to go through each endpoint specified in login method before eventually failing at an arbitrary endpoint with the message:

JsonMapper::map() requires first argument to be an object, NULL given.

This happens with 1.6, 1.6.0.1, 1.6.0.2 and dev-master. Tried with centos 6 64 bit, centos 7 64bit  with php 5.4, 5.5, 5.6 and 7.0.

I would have blamed it on network, but on the same machine v1.5.1 logs in fine. ( just the getPk() issue I raised earlier)

**Comment by frrakn** [comment]
Where was a big API change from `1.5.1` to `1.6`. Login usage is different now.

```
$instagram = new \InstagramAPI\Instagram("username", "password");
$instagram->login();
```

is now 

```
$instagram = new \InstagramAPI\Instagram();
$instagram->setUser("username", "password");
$instagram->login();
```

**Comment by juicytuna** [comment]
I am doing the new way

**Comment by frrakn** [comment]
Please paste full error stack

**Comment by jpmoney5065** [comment]
Also `setProxy()` function will not work as before. 

Make sure host ip user and pass is set individually now

**Comment by juicytuna** [comment]
Same thing with or without proxy. Debug log:


> POST:  qe/sync/
> DATA: ig_sig_key_version=4&signed_body=f3c34d5096e4e331f12f9c1ec3f608c673dc086591b96c5f9e61cd3dde1160de.{"id":"2467041d-b9cf-40f3-810f-989e80d510d0","experiments":"ig_android_reg_login_btn_active_state,ig_android_ci_opt_in_at_reg,ig_android_one_click_in_old_flow,ig_android_merge_fb_and_ci_friends_page,ig_android_non_fb_sso,ig_android_mandatory_full_name,ig_android_reg_enable_login_password_btn,ig_android_reg_phone_email_active_state,ig_android_analytics_data_loss,ig_fbns_blocked,ig_android_contact_point_triage,ig_android_reg_next_btn_active_state,ig_android_prefill_phone_number,ig_android_show_fb_social_context_in_nux,ig_android_one_tap_login_upsell,ig_fbns_push,ig_android_phoneid_sync_interval"}
> ← 200    1.38kB
> RESPONSE: {"status": "ok", "experiments": [{"params": [{"name": "button_filled", "value": "false"}, {"name": "outline_opaque", "value": "false"}, {"name": "button_filled_fade_in", "value": "false"}], "group": "control_20160830", "name": "ig_android_reg_login_btn_active_state"}, {"params": [{"name": "opt_in_at_username_page", "value": "2"}], "group": "test_button_at_username_20161116", "name": "ig_android_ci_opt_in_at_reg"}, {"params": [{"name": "support_non_fb_sso", "value": "true"}], "group": "test_20160629", "name": "ig_android_non_fb_sso"}, {"params": [{"name": "is_enabled", "value": "enabled"}, {"name": "phone_first", "value": "enabled"}], "group": "test_with_phone_first_20160322", "name": "ig_android_contact_point_triage"}, {"params": [{"name": "button_filled", "value": "false"}, {"name": "outline_opaque", "value": "false"}, {"name": "button_filled_fade_in", "value": "true"}], "group": "filled_fade_in_20160830", "name": "ig_android_reg_next_btn_active_state"}, {"params": [{"name": "prefill_...
> 
> GET:  si/fetch_headers?challenge_type=signup&guid=4c3fb0565866454d89f5325f3140bba8
> ← 200    16B
> RESPONSE: {"status": "ok"}
> 
> POST:  accounts/login/
> DATA: ig_sig_key_version=4&signed_body=217372c1134d6ed2a92a34cea3a8b4d3154302e950f8558f96ff473434208f6a.{"phone_id":"fabdaa38-dea8-40e6-9491-ffb7eed11614","_csrftoken":"Set-Cookie: csrftoken=oLWfyKpr4GNxlxsMsQzhQowlEa5ydRL2","username":"get_pokecoinz_n0w","guid":"fdb768a4-a39b-44ff-88cf-24dd43dbe631","device_id":"android-b2e76e23f1f9c363","password":"azerty159","login_attempt_count":0}
> ← 200    467B
> RESPONSE: {"logged_in_user": {"username": "get_pokecoinz_n0w", "has_anonymous_profile_picture": false, "allow_contacts_sync": false, "show_feed_biz_conversion_icon": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/15048188_1443973445617065_6218988374024257536_n.jpg", "profile_pic_id": "1302427849316036960_2902588560", "full_name": "Get your free Pokecoins today!", "pk": 2902588560, "is_verified": false, "is_private": false}, "status": "ok"}
> 
> POST:  qe/sync/
> DATA: ig_sig_key_version=4&signed_body=6c564cbb35ec28d60a0aac20479b0d86cbfeac56f1f5c04da804f3add8755597.{"_uuid":"fdb768a4-a39b-44ff-88cf-24dd43dbe631","_uid":2902588560,"_csrftoken":"xdfOxzjf6edqdqxPrTPe9Bew1HesopRG","id":2902588560,"experiments":"ig_android_ad_holdout_16m5_universe,ig_android_progressive_jpeg,ig_creation_growth_holdout,ig_android_oppo_app_badging,ig_android_ad_remove_username_from_caption_universe,ig_android_enable_share_to_whatsapp,ig_android_direct_drawing_in_quick_cam_universe,ig_android_ad_always_send_ad_attribution_id_universe,ig_android_universe_video_production,ig_android_direct_plus_button,ig_android_ads_heatmap_overlay_universe,ig_android_http_stack_experiment_2016,ig_android_infinite_scrolling,ig_fbns_blocked,ig_android_post_auto_retry_v7_21,ig_fbns_push,ig_android_video_playback_bandwidth_threshold,ig_android_direct_link_preview,ig_android_direct_typing_indicator,ig_android_preview_capture,ig_android_feed_pill,ig_android_profile_link_iab,ig_android_story_caption,ig_android_network_cancellation,ig_android_histogram_reporter,ig_android_anrwatchdog,ig_android_search_client_matching,ig_android_follow_request_text_buttons,ig_android_feed_zoom,ig_android_drafts_universe,ig_android_disable_comment,ig_android_user_detail_endpoint,ig_android_os_version_blocking,ig_android_blocked_list,ig_android_event_creation,ig_android_high_res_upload_2,ig_android_2fac,ig_android_mark_reel_seen_on_Swipe_forward,ig_android_comment_redesign,ig_android_ad_sponsored_label_universe,ig_android_mentions_dismiss_rule,ig_android_disable_chroma_subsampling,ig_android_share_spinner,ig_android_video_reuse_surface,ig_explore_v3_android_universe,ig_android_media_favorites,ig_android_nux_holdout,ig_android_insta_video_universe,ig_android_search_null_state,ig_android_universe_reel_video_production,liger_instagram_android_univ,ig_android_direct_emoji_picker,ig_feed_holdout_universe,ig_android_direct_send_auto_retry_universe,ig_android_samsung_app_badging,ig_android_disk_usage,ig_android_business_promotion,ig_android_direct_swipe_to_inbox,ig_android_feed_reshare_button_nux,ig_android_react_native_boost_post,ig_android_boomerang_feed_attribution,ig_fbns_shared,ig_fbns_dump_ids,ig_android_react_native_universe,ig_show_promote_button_in_feed,ig_android_ad_metadata_behavior_universe,ig_android_video_loopcount_int,ig_android_inline_gallery_backoff_hours_universe,ig_android_rendering_controls,ig_android_profile_photo_as_media,ig_android_async_stack_image_cache,ig_video_max_duration_qe_preuniverse,ig_video_copyright_whitelist,ig_android_render_stories_with_content_override,ig_android_ad_intent_to_highlight_universe,ig_android_swipe_navigation_x_angle_universe,ig_android_disable_comment_public_test,ig_android_profile,ig_android_direct_blue_tab,ig_android_enable_share_to_messenger,ig_android_fetch_reel_tray_on_resume_universe,ig_android_promote_again,ig_feed_event_landing_page_channel,ig_ranking_following,ig_android_pending_request_search_bar,ig_android_feed_ufi_redesign,ig_android_pending_edits_dialog_universe,ig_android_business_conversion_flow_universe,ig_android_show_your_story_when_empty_universe,ig_android_ad_drop_cookie_early,ig_android_app_start_config,ig_android_fix_ise_two_phase,ig_android_ppage_toggle_universe,ig_android_pbia_normal_weight_universe,ig_android_profanity_filter,ig_ios_su_activity_feed,ig_android_search,ig_android_boomerang_entry,ig_android_mute_story,ig_android_inline_gallery_universe,ig_android_ad_remove_one_tap_indicator_universe,ig_android_view_count_decouple_likes_universe,ig_android_contact_button_redesign_v2,ig_android_periodic_analytics_upload_v2,ig_android_send_direct_typing_indicator,ig_android_ad_holdout_16h2m1_universe,ig_android_react_native_comment_moderation_settings,ig_video_use_sve_universe,ig_android_inline_gallery_no_backoff_on_launch_universe,ig_android_immersive_viewer,ig_android_discover_people_icon,ig_android_profile_follow_back_button,is_android_feed_seen_state,ig_android_dense_feed_unit_cards,ig_android_drafts_video_universe,ig_android_exoplayer,ig_android_add_to_last_post,ig_android_ad_remove_cta_chevron_universe,ig_android_ad_comment_cta_universe,ig_android_search_event_icon,ig_android_channels_home,ig_android_feed,ig_android_dv2_realtime_private_share,ig_android_non_square_first,ig_android_video_interleaved_v2,ig_android_video_cache_policy,ig_android_react_native_universe_kill_switch,ig_android_video_captions_universe,ig_android_follow_search_bar,ig_android_last_edits,ig_android_two_step_capture_flow,ig_android_video_download_logging,ig_android_share_link_to_whatsapp,ig_android_facebook_twitter_profile_photos,ig_android_swipeable_filters_blacklist,ig_android_ad_pbia_profile_tap_universe,ig_android_use_software_layer_for_kc_drawing_universe,ig_android_react_native_ota,ig_android_direct_mutually_exclusive_experiment_universe,ig_android_following_follower_social_context"}
> ← 200    10.86kB
> RESPONSE: {"status": "ok", "experiments": [{"params": [{"name": "behavior", "value": "pass"}], "group": "pass", "name": "ig_android_ad_holdout_16m5_universe"}, {"params": [{"name": "min_scan", "value": "0"}, {"name": "peek_media", "value": "enabled"}], "group": "control_20160602", "name": "ig_android_progressive_jpeg"}, {"params": [{"name": "behavior", "value": "pass"}], "group": "everyone_else", "name": "ig_creation_growth_holdout"}, {"params": [{"name": "enable_badging", "value": "1"}], "group": "control", "name": "ig_android_oppo_app_badging"}, {"params": [{"name": "upload_per_pixel_bit_rate_16by9", "value": "9.7222"}, {"name": "upload_width_max_low", "value": "540"}, {"name": "upload_width_max_mid", "value": "640"}, {"name": "screen_width_low", "value": "500"}, {"name": "total_memory_low", "value": "520"}, {"name": "upload_per_pixel_bit_rate_9by16", "value": "7"}, {"name": "cpu_cores_low", "value": "1"}, {"name": "upload_per_pixel_bit_rate_square", "value": "7"}, {"name": "total_memory_mid",...
> 
> GET:  friendships/autocomplete_user_list/?version=2
> ← 429    82B
> RESPONSE: {"status": "fail", "message": "Sorry, too many requests. Please try again later."}
> 
> GET:  feed/timeline?rank_token=2902588560_fdb768a4-a39b-44ff-88cf-24dd43dbe631&ranked_content=true
> ← 200    51.56kB
> RESPONSE: {"status": "ok", "megaphone": {"generic_megaphone": {"title_color": "262626", "dismissible": false, "type": "android_upgrade", "title": "Update Instagram", "uuid": "653c108dec274b97a232b587f6bb50da", "buttons": [{"url": "https://play.google.com/store/apps/details?id=com.instagram.android", "text": "Update Now", "border_color": "70C050", "text_color": "FFFFFF", "action_info": {}, "action": "clicked", "background_color": "70C050"}, {"url": null, "text": "Not Now", "border_color": "EFEFEF", "text_color": "262626", "action_info": {}, "action": "dismiss", "background_color": "EFEFEF"}], "button_location": "bottom", "action_info": {}, "button_layout": "vertical", "megaphone_version": "v2", "message_color": "737373", "message": "get_pokecoinz_n0w, we're always working to improve your Instagram experience. You're currently using an old version of the app. Use the latest version to get new features and improvements. We hope you enjoy it!", "background_color": "EFEFEF", "icon": null}}, "num_resu...
> 
> GET:  direct_v2/ranked_recipients?show_threads=true
> ← 200    10.7kB
> RESPONSE: {"status": "ok", "filtered": true, "expires": 7200, "ranked_recipients": [{"user": {"username": "nichtlustig2.0", "has_anonymous_profile_picture": false, "coeff_weight": 0.0, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/12070685_856836917759056_1884726509_a.jpg", "full_name": "Dominik", "pk": 2267100998, "is_verified": false, "is_private": true}}, {"user": {"username": "jasmin_salvador_", "has_anonymous_profile_picture": false, "coeff_weight": 0.0, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/14693957_1801574600084457_3983506914918006784_a.jpg", "profile_pic_id": "1374641306878190858_2283045111", "full_name": "Jasyyy\ud83d\udc95\ud83c\udf43", "pk": 2283045111, "is_verified": false, "is_private": true}}, {"user": {"username": "alan___21", "has_anonymous_profile_picture": false, "coeff_weight": 0.0, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/13694699_1748846915397401_376670189_a.jpg", "profile_pic_id...
> 
> GET:  direct_share/recent_recipients/
> ← 0      0B
> RESPONSE:
> 
> something went wrong JsonMapper::map() requires first argument to be an object, NULL given.
>

**Comment by mgp25** [comment]
@juicytuna post your code

**Comment by juicytuna** [comment]
```php

<?php

require __DIR__ . '/vendor/autoload.php';

$debug = true;
$truncatedDebug = true;

$username = "user";
$password = "pass";
$ip = "http://185.xxx.xxx.207";
$port = "24399";


$i = new \InstagramAPI\Instagram($debug, $truncatedDebug);

//set proxy
$i->setProxy($ip,$port);

//log in
$i->setUser($username, $password);

try {
    $i->login();
} catch (Exception $e) {
    echo 'something went wrong '.$e->getMessage()."\n";
    exit(0);
}


?>

```

**Comment by juicytuna** [comment]
issue occurs with or without proxy. Thanks.

**Comment by mgp25** [comment]
@juicytuna you didnt posted the full code, if the debug log i see above, login was success

**Comment by jpmoney5065** [comment]
From debug above:

```
GET: friendships/autocomplete_user_list/?version=2
← 429 82B
RESPONSE: {"status": "fail", "message": "Sorry, too many requests. Please try again later."}
```

**Comment by juicytuna** [comment]
From my understanding that should't cause log in to fail. Every time I run it  it fails after a different endpoint request. 
To add some context, the above log in attempt took about 3 minutes before eventually failing.

**Comment by juicytuna** [comment]
@mgp25 log in was a success, but the login method failed. The login method does more than just log in.

**Comment by juicytuna** [comment]
Just spun up a vps with a different provider and it's working fine there. Must've been an issue with the other provider (OVH). Sorry to waste your time guys. Thanks
