### ISSUE TITLE
Call to undefined method stdClass::request()

### ISSUE THREAD

**Issue by rizkyred** [mgp25/Instagram-API#697]
FatalErrorException in Instagram.php line 1769:
Call to undefined method stdClass::request()

have you test it ? after composer update i got this error

**Comment by David-Kurniawan** [comment]
Me too
`Call to a member function request()`

**Comment by mgp25** [comment]
Are you using php >= 5.6?

**Comment by rizkyred** [comment]
Yes i am using PHP Version 5.6.19. can you make it works on php >=5.6 please

**Comment by mgp25** [comment]
@rizkyred you are already running in php >= 5.6. Have you tried downloading the code again?

**Comment by rizkyred** [comment]
Yeah already composer update a couple min ago, and still error. 

FatalErrorException in Instagram.php line 1769:
Call to a member function request() on null

**Comment by mgp25** [comment]
@rizkyred can you try `dev-master` ?

**Comment by joseflorido** [comment]
I think the problem is that you are using the old constructor, doing
something like this:
$i = new \InstagramAPI\Instagram($username, $pass, $debug, $IGDataPath);

Instead, try doing this:
$i = new \InstagramAPI\Instagram($debug);
$i->setUser($username, $pass);

**Comment by David-Kurniawan** [comment]
@joseflorido Thank you so much... work perfect!

**Comment by Lastwisher** [comment]
At instagram.php you will see settings on top you can make from there.

**Comment by rizkyred** [comment]
@Lastwisher @joseflorido can you give me with full example code how to use with IGDataPath (cookie) ?
is that just : 
$i = new \InstagramAPI\Instagram($debug);
$i->setUser($username, $pass);
$i->settingsAdopter["type"] = "file";
$i->settingsAdopter["path"] = "some/path";

?
