### ISSUE TITLE
DM spam error

### ISSUE THREAD

**Issue by dvdiegoviana** [mgp25/Instagram-API#698]
Over the last threee days, I'm facing problems to send Instagram DM. I'm receiving the following response message:
{
	"status": "fail", 
	"feedback_title": "Message Failed", 
	"feedback_message": "This message contains content that has been blocked by our security systems. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", 
	"spam": true, "feedback_action": "report_problem", "feedback_url": "repute/report_problem/instagram_direct_v2_thread_create/", 
	"feedback_ignore_label": "OK", 
	"message": "feedback_required", "feedback_appeal_label": "Report problem"
}
Is this a known issue? 
My application has been running for approximately 4 months and I've never had this problem.

**Comment by mgp25** [comment]
Instagram has detected you as spam

Regards

**Comment by dvdiegoviana** [comment]
But do you know if there is a reason for that? Is it because of the message content for instance? Or is it forbidden at all to send DM for those who follow me?

**Comment by lucassimao** [comment]
It's not forbidden, instagram  only wants to keep their users far from spamers. If you send the same DM to several followers, it's easy to detect you and flag you as spam. Even the official API has this limitations. As a clue, try to behave as a "real user"

**Comment by dvdiegoviana** [comment]
I see. Thank you!
