### ISSUE TITLE
Jsonmapper crash

### ISSUE THREAD

**Issue by lkp111138** [mgp25/Instagram-API#699]
When the request received an invalid response, the script crashes. please fix!
Also I am not spamming (about 1 request per 2 seconds at most)

Debug log: 
```GET:  direct_v2/inbox/
← 503    105B
RESPONSE: <html>
<head>
<title>5xx Server Error</title>
</head>

<body>
<h1>5xx Server Error</h1>
</body>

</html>


PHP Warning:  Invalid argument supplied for foreach() in /var/www/lib/instagram-api/vendor/netresearch/jsonmapper/src/JsonMapper.php on line 142
InstagramAPI\V2InboxResponse :```

**Comment by mgp25** [comment]
@lkp111138 that error is not due jsonmapper but your server

Regards

**Comment by lkp111138** [comment]
The 5xx server error is returned by Instagram, not my servers.
I am wondering about what can I do if Instagram returned something non-json, as the error occured while doing ```switchUser()``` and ```login()```
