### ISSUE TITLE
IG_SIG_KEY issue

### ISSUE THREAD

**Issue by hadivip** [mgp25/Instagram-API#7]
hi,
I'm having some question about `IG_SIG_KEY`. i would very much be appreciate if you can answer. 
1) is `IG_SIG_KEY` unique and different on every device or it is only a string in Instagram APK file based on every release of ?
2) I've tried your code with current `IG_SIG_KEY` and I've got an exception saying your account has been block. however it doesn't!!! i tried for the second time and it did work. i just deleted the cookie file.
3) i'm having windows 10. i installed Payton and excute test.py. i got an error instead. what is the make file in github repository. how can i get `IG_SIG_KEY` using this tool? i tried `gikdbg.art` but my device is not rooted so this is not my way to go.

thanks for your time

**Comment by mgp25** [comment]
@hadivip i suppose its version related, i've done this based on one version. You can extract it easily from apk.

Regards
