### ISSUE TITLE
Is there any way I can get List of Users that i follow them but thy dont follow me back.

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#700]
Dear all , i know there is a function to get getUserFollowings , which return users i do Follow them .
But if one of them does not Follow me back , it will be in the list to.

I know , i can get the getUserFollower and make compare between two lists . but what if the list 838383888 user , long time and resources will be involved.  

i now , i can send userFriendship to know the status of the user Friendship , but my target to limit down instagram request .

Please Advice

**Comment by Lastwisher** [comment]
you can use user**s**Friendship() for multiple requests.

**Comment by beshoo1** [comment]
i know that but if i have 1000 user , then i need to loop over all users ! correct ?
That what i  dont want to do it , so i am asking if there is a way around
