### ISSUE TITLE
How to check if user is loggedIn?

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#701]
Hi!

I am trying to get UsernameInfoResponse. If I do login() the script takes much longer, seems that it does the login request in any case. Is there a way I can check if user is loggedIn and if not, do force login(1)?

Also, a strange thing happening is that I frequently get login_required but according to cookies the session should last months. Any ideas about that?

Thanks!

**Comment by jpmoney5065** [comment]
```
if($i->isLoggedIn()) {
    //do stuff
}else {
    //do login
}
```

**Comment by joseflorido** [comment]
Thanks. I did try that, but:
Fatal error: Call to undefined method InstagramAPI\Instagram::isLoggedIn()

**Comment by jpmoney5065** [comment]
Aw sorry looks like it was moved/changed in the new update! (still rocking previous build here)

Looks like you should be able to check for `$i->isLoggedIn `
The method looks like it has been renamed & moved to settings so: `$i->settings->islogged()`

**Comment by jpmoney5065** [comment]
> Also, a strange thing happening is that I frequently get login_required but according to cookies the session should last months. Any ideas about that?

I don't think that is an API issue

**Comment by joseflorido** [comment]
Thanks!

**Comment by joseflorido** [comment]
Sorry I'm reopening this, but I am seeing:
echo $i->settings->islogged();  => 1
But still getting: InstagramAPI\UsernameInfoResponse : login_required

Any ideas why?

**Comment by jpmoney5065** [comment]
maybe post a debug log

**Comment by jpmoney5065** [comment]
also check that you have permissions to write on your data folder

**Comment by joseflorido** [comment]
Thanks!

I am quite sure that data folder is writable, the script works most of the time but fails sometimes and I just the path and it has 0777 permissions.

My code is something like:

require("vendor/autoload.php");
$i = new \InstagramAPI\Instagram($debug);
$i->setUser($igUserName, $igPass);

if(!$i->settings->islogged()) {
  $i->login(1);
}

try {
  $user = $i->searchUsername("nike");
} catch (Exception $e) {
  echo $e->getMessage();
}

Debug log:
GET:  users/nike/usernameinfo/
← 400 	 47B
RESPONSE: {"status": "fail", "message": "login_required"}
InstagramAPI\UsernameInfoResponse : login_required

Thanks a lot for your help!

**Comment by joseflorido** [comment]
I found the solution, the correct way to check of user is logged in is:
if($i->settings->isLoggedIn) {
  // do stuff
} else {
  $i->login(1);
}
