### ISSUE TITLE
Switching users

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#704]
Hi,

How would you go about switch users? Does the API offer some method to switch between multiple accounts? Do I need to do logout() before doing setUser() and login() with a different account? Is there a limit to the number of accounts you can use? I am thinking about using several accounts to avoid "too many requests", is that the right strategy or are proxies more important?

Thanks!

**Comment by mgp25** [comment]
@joseflorido it's explained in the wiki. The bahaviour is the same as the Instagram app.
