### ISSUE TITLE
How can I change IGDataPath?

### ISSUE THREAD

**Issue by makm** [mgp25/Instagram-API#706]
Hello. we has new bugs )
https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L48

**Comment by rizkyred** [comment]
Yeah i need this too for now

**Comment by makm** [comment]
You can use:
$i = new \InstagramAPI\Instagram(false);
$i->settingsAdopter = [
            'type' => 'file',
            'path' => ini_get('upload_tmp_dir'), //or other directory
        ];
 $i->setUser('login', 'pass');

**Comment by rizkyred** [comment]
I got an error JsonMapper::map() requires first argument to be an object, NULL given. Do you have clue? @makm

**Comment by rizkyred** [comment]
Ok solved. its because setProxy() changed. i think it should not bother the code for any updates
