### ISSUE TITLE
login_required to login()

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#707]
Hi, I keep having issues with login...

This is a very simple test code:
```
<?
require("vendor/autoload.php");
$i = new \InstagramAPI\Instagram(true, true);
$i->setUser('xxx', 'yyy');

try {
  $i->login();
} catch (Exception $e) {
  echo $e->getMessage();
}
?>
```
My data path is writable and I can see that there are two files in it: $username-cookies.dat  and settings-$username.dat

And my debug log:
```
GET:  feed/timeline?rank_token=4187990858_d459d685-5157-4b03-b76d-bba0d67729d4&ranked_content=true
← 400 	 47B
RESPONSE: {"status": "fail", "message": "login_required"}

InstagramAPI\TimelineFeedResponse : login_required
```

Looks like for some reason login() is returning a TimeLineFeedResponse, is that expected?
Any idea how to avoid this problem?

Thanks!

**Comment by mgp25** [comment]
@joseflorido use login function with `$force = true` once

Regards

**Comment by thanhsonnguyen4796** [comment]
@mgp25  sorry, Can you say more clearly.

`<?php

include 'autoload.php';
require 'Instagram.php';

/////// CONFIG ///////
$username = 'XXX';
$password = 'YYY';
$photo = 'D:/featured.jpg';    // path to the photo
$caption = 'Test';     // caption
//////////////////////

$i = new \InstagramAPI\Instagram(true, true);

$i->setUser($username, $password);

try {
    $i->login($force = true);
} catch (Exception $e) {
	$e->getMessage();
    echo $e;
    exit();
}

try {
    $i->uploadPhoto($photo, $caption);
} catch (Exception $e) {
    echo $e->getMessage();
}`

This is my code. I used "$force = true" but i got this error

`GET: feed/timeline?rank_token=3966830430_173fbd99-20f9-4a6c-9b64-b28b85eb7fd6&ranked_content=true ← 400 47B RESPONSE: {"status": "fail", "message": "login_required"}`

:(
