### ISSUE TITLE
Why mgp25\instagram-php\src\http\Response\ProfileResponse.php have no function ?

### ISSUE THREAD

**Issue by rizkyred** [mgp25/Instagram-API#708]
Why mgp25\instagram-php\src\http\Response\ProfileResponse.php have no function ? (in latest version)
there are some function i used in this class, i need like getProfilePicUrl() function.

**Comment by rizkyred** [comment]
why everything on \instagram-php\src\http\Response\ folder there are no function on that class ? just a public variable,

**Comment by mgp25** [comment]
@rizkyred if the name of the variable is, `url`, to get that value you just do this, `getUrl()`. The same happens with the rest of the vars
