### ISSUE TITLE
Values returned as NULL for getUserFollowers

### ISSUE THREAD

**Issue by GeraldHost** [mgp25/Instagram-API#710]
following_count, friendshipstatus, media_count and others returning as NULL when I do this: 

 ` $target_id = '889664020';`
 ` $u = $i->getUserFollowers($target_id, $maxid = null)->getFollowers();`
  `var_dump($u);`

Any ideas?

Thanks in advance :-)

**Comment by mgp25** [comment]
@GeraldHost duplicate, you should check closed issues first:

```php
$target_id = '889664020';
$u = $i->getUserFollowers($target_id, $maxid = null)->getUsers();
```

**Comment by GeraldHost** [comment]
Thanks for your response. When I run getUsers(); I get a fatal error 'Call to undefined method...' Can't seem to find the answer in any other issue threads.

**Comment by mgp25** [comment]
@GeraldHost are you using latest source?

**Comment by GeraldHost** [comment]
Yes, I'm using the latest source and also tried a fresh install. Not sure what's going wrong.

**Comment by mgp25** [comment]
@GeraldHost are you using `dev-master`  and have you installed it using `composer` ?

**Comment by GeraldHost** [comment]
@mgp25 I'm not using dev-master but I have installed using composer. I'll see if I can get that example working, if not must be a problem my end.

**Comment by mgp25** [comment]
@GeraldHost if the issue persists, send me an email and ill help you

Regards

**Comment by GeraldHost** [comment]
@mgp25 thank you :-)

**Comment by mgp25** [comment]
@GeraldHost everything is okay. The function `getUserFollowers` only returns this values:

```json
	"username": "",
		"has_anonymous_profile_picture": false,
		"profile_pic_url": "",
		"is_favorite": false,
		"full_name": "",
		"pk": ,
		"is_verified": false,
		"is_private": true
```

(I have removed the values). If you want to check more info about the user, you should use other functions.

Regards

**Comment by GeraldHost** [comment]
@mgp25 Ahh I understand now. Thank you!! :-) Awesome work BTW!
