### ISSUE TITLE
Login issue with Null given for map()

### ISSUE THREAD

**Issue by kiralore** [mgp25/Instagram-API#711]
There is a issue "something went wrong JsonMapper::map() requires first argument to be an object, NULL given." when I run the PaginationExample.php. Closed previous issue showed changing vps could help but it not works for me. Any solution?

**Comment by mgp25** [comment]
@kiralore post debug log + code

**Comment by kiralore** [comment]
Not with my PC so i will post debug log later, but I only set my username and password in the PaginationExample.php without other changes. It stops at the login function as it caught the error "something went wrong" and the message.

**Comment by ginviz** [comment]
I have the same problem as in Kiralore.
`<?php
include 'C:/OpenServer/domains/localhost/vendor/autoload.php';
require '../src/Instagram.php';

$username = '******';
$password = '******';
$debug = false;

$i = new \InstagramAPI\Instagram($debug);
$i->setUser($username, $password);
try {
    $i->login();
} catch (Exception $e) {
    echo 'something went wrong '.$e->getMessage()."\n";
    exit(0);
}
$target_id = '1111111';
$u = $i->getUserFollowers($target_id, $maxid = null)->getUsers();
print_r ($u);`

Error logs:

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'JsonMapper::map() requires first argument to be an object, NULL given.' in C:\OpenServer\domains\localhost\vendor\netresearch\jsonmapper\src\JsonMapper.php:126
Stack trace:
#0 C:\OpenServer\domains\localhost\vendor\mgp25\instagram-php\src\Instagram.php(1776): JsonMapper->map(NULL, Object(InstagramAPI\FollowerResponse))
#1 C:\OpenServer\domains\localhost\vendor\mgp25\instagram-php\src\Instagram.php(1324): InstagramAPI\Request->getResponse(Object(InstagramAPI\FollowerResponse))
#2 C:\OpenServer\domains\localhost\vendor\mgp25\instagram-php\examples\PaginationExample.php(27): InstagramAPI\Instagram->getUserFollowers('1111111', NULL)
#3 {main}
thrown in C:\OpenServer\domains\localhost\vendor\netresearch\jsonmapper\src\JsonMapper.php on line 126

**Comment by mgp25** [comment]
Instagram is refusing the connection from your VPS. As told by other users, try other one. Im not sure how Instagram decides which one to accept. 

Regards
