### ISSUE TITLE
Checkpoint.php

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#713]
In Checkpoint.php not use a proxy for request.

**Comment by Triden** [comment]
And Undefined offset: 1 to 'csrfmiddlewaretoken' => $token[1].
Instagram no request token.

**Comment by mgp25** [comment]
@Triden Instagram refuses connection. If you have any issue, you can always log in manually with your device

Regards

**Comment by Triden** [comment]
And the proof is not held in the mail. I just clicked on a site that's me. Whether it is possible to automate it?

**Comment by Triden** [comment]
As far as I understand. Instagram told me that this page does not exist.

**Comment by Triden** [comment]
Maybe you add at least a proxy please?

**Comment by mgp25** [comment]
Is not a priority, you can add it your own if you need it

Regards
