### ISSUE TITLE
Get 400 error from server

### ISSUE THREAD

**Issue by torv** [mgp25/Instagram-API#716]
I have try to login by Android code

But always get 400 error code from server.
Can you help me check the code ?
Thanks very much.

**Comment by mgp25** [comment]
Hello, this is not API issue.

I recommend you to try only with login request. Compare this one with the one of yours. Make sure both signatures are generated the same way. And do a http traffic debug to check if you have the same result as this API

Keep debugging!

Regards

**Comment by torv** [comment]
@mgp25  This is the project 
https://github.com/torv/Private-Api
I only try login by now. I have make sure the signature no problem, compare to this one.
Is there any other key point I should take care? user-agent or sth?
Thanks very much.

**Comment by torv** [comment]
@mgp25 the detail error is 
{"status": "fail", "message": "Your version of Instagram is out of date. Please upgrade your app to log in to Instagram.", "error_type": "needs_upgrade"}

**Comment by mgp25** [comment]
@torv request, user agent, signature or token, is not okay/updated

**Comment by torv** [comment]
@mgp25 
1. request? Can you tell in detail?
2. User-Agent = "Instagram 9.8.0 Android (23/6.0.1; 640dpi; 1440x2560; samsung; SM-G9200; zerofltechn; samsungexynos7420; zh_CN)"
3. token I just take from "Set-Cookies: csrftoken=cUMaMn01KYOPvguRe8OkS23w24PY1v8G; expires=Wed, 29-Nov-2017 15:02:51 GMT; Max-Age=31449600; Path=/; secure"
then token = "cUMaMn01KYOPvguRe8OkS23w24PY1v8G". right?
4. signature I just follow your logic, sign the params and key with hmac. I compared the result with yours, it's same.
