### ISSUE TITLE
Data folder on wrong account

### ISSUE THREAD

**Issue by jcoulaud** [mgp25/Instagram-API#717]
Hello !

First of all, thx for this great API, I have been using it for 1 year now and it's save me so much time...

I have a question.
Is there a way to **NOT** create a username folder (data/username/*.dat) when adding a **wrong** Instagram account (_Actually, if I got a string error with_ `$i->setUser($username, $password);` )? Because if I put something wrong with my IDs like a fake account / password, it still creates a folder with the 2 .dat files in it.

Best, Julien

**Comment by jpmoney5065** [comment]
can create a function.. something like:
```
function deleteSomeUsersInstagramAPIData($username){
    $datapath = INSTAGRAM_API_PATH."data".DIRECTORY_SEPARATOR.$username;
    array_map('unlink', glob("$datapath/*.*"));
    rmdir($datapath);
}
```

**Comment by jcoulaud** [comment]
Thank you @jpmoney5065 :)
