### ISSUE TITLE
Direct Message

### ISSUE THREAD

**Issue by putraxor** [mgp25/Instagram-API#72]
When direct message sending API will be available?

**Comment by mgp25** [comment]
@putraxor i don't know. Maybe soon, maybe never.

If want that feature, i recommend you to capture the request and code it yourself, that way you will learn and contribute the API by the way, the procedure is way too easy.

Im very lazy thats why im not adding all the functions, but as i said before, it can be easily coded by taking one of the already coded functions as a template and capture the request.

Regards!

**Comment by RageBrahimi** [comment]
Hold up @mgp25, you've already made this available! @putraxor you should ready the [Instagram.php](https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L260)
```
direct_share($media_id, $recipients, $text = null)
```

**Comment by dfanara** [comment]
I believe that functionality is for sharing a publically available post via direct message. I may be wrong though.

**Comment by RageBrahimi** [comment]
@dfanara You're right. However, you're still able to send a message with the **$text** - it's better than no option.

**Comment by dfanara** [comment]
@RageBrahimi fair enough.

**Comment by DevWellington** [comment]
It is possible to read the messages that were sent by the followers?

**Comment by anilgiriglobussoft123** [comment]
hey Guys 
for Direct message i use like this but getting error 400 (Text missing).Is any one help me
url = https://i.instagram.com/api/v1/direct_v2/threads/broadcast/text/ 
body = recipient_users=[user id]&client_context=[divceid]&text=How&thread_ids=0
Post hit

**Comment by alibehroozi** [comment]
Any one did something with "Text missing" ??? It's very important for me ... Please help

**Comment by SteveJobzniak** [comment]
This is already fixed in `dev-master`. Do not bump old issues.
