### ISSUE TITLE
Is there a way to search for recent media by tag?

### ISSUE THREAD

**Issue by jasoncartercs** [mgp25/Instagram-API#720]
I am trying to use this API to search for recent media by tag using the following url:
https://api.instagram.com/v1/tags/{tag-name}/media/recent?access_token=ACCESS-TOKEN.

Is this possible? If it is not, is this feature planned?

**Comment by mgp25** [comment]
```php
    public function getHashtagFeed($hashtagString, $maxid = null)
```

Please, check wiki and read the code before opening an issue

Regards
