### ISSUE TITLE
login error: sentry_block

### ISSUE THREAD

**Issue by FFServices** [mgp25/Instagram-API#721]
hi,

i got this during login: 
400 108B RESPONSE: {"status": "fail", "message": "Sorry, there was a problem with your request.", "error_type": "sentry_block"} InstagramAPI\LoginResponse : Sorry, there was a problem with your request.

can anybody help?

**Comment by mgp25** [comment]
@FFServices not API issue

Regards

**Comment by FFServices** [comment]
i can login with instagram android app, but not with this api

**Comment by torv** [comment]
@FFServices Can you share the Android api which works.

**Comment by FFServices** [comment]
@torv not api but the official instagram android apP

**Comment by beshoo1** [comment]
@mgp25  is this error mean that instagram block his account ? sentry_block?

**Comment by MMrR0b0TT** [comment]
Did you get any answer about it?

**Comment by FFServices** [comment]
No, nothing

**Comment by MarkoSulamagi** [comment]
In case anybody is struggling with it. It's basically an IP block. After you change your IP, the account should work.

**Comment by invisor** [comment]
A have the same problem

**Comment by imlemeci** [comment]
A have the same problem. Help me ?

**Comment by mrtcnnccn** [comment]
I think it is not just an IP block. Because I can login with one app but can't with another where both of them uses the same api documented here.

**Comment by vasiledoe** [comment]
it's not about IP, they just banned your account for this mobile API but still working on web side

**Comment by msmoosa** [comment]
@vasiledoe What do you mean by this mobile API? 
- this version of the API
or totally blocked from mobile apps. 
Currently for one particular account i cant login through my iphone or android phone
