### ISSUE TITLE
DM-thread-pagination? Or use DM-websocket?

### ISSUE THREAD

**Issue by z11labs** [mgp25/Instagram-API#724]
Hey, first of all: **thanks for this great repository!**

I was figuring out, how to load more direct-messaging-threads than the ones via `$i->getv2Inbox()`. While I didn't found any `nextMaxId` (also looked at the full response), I just saw something that looked like a websocket-authentication-code, but I don't know which api-endpoints are used by the instagram-websocket.

After proxying the traffic of the instagram-app, I saw that instagram was using a ssl-websocket, but because of the ssl-pinning I was not able to see the communication inside of the websocket. This took me to the tought, that maybe instagram is using the websocket for direct-messaging by now and that could be the reason for that there is no `nextMaxId` in the api-methods of this repository.

Takes me to the following question:
**Is there a way to get more direct-messaging-threads or do you know how to use the websocket?**

Thanks a lot for your answer :)

If you already answered this question and I were just too dumb to find it: I'm sorry, please don't be mad at me.

PS: English is not my native language.

**Comment by mgp25** [comment]
@z11labs everything can be captured, disable / bypass cert pinning. And use a proxy, you will be able to capture and see all traffic, also thread related too

Regards

**Comment by z11labs** [comment]
@mgp25 thanks for your answer! :)

I disabled cert-pinning (via [Android-SSL-TrustKiller](https://github.com/iSECPartners/Android-SSL-TrustKiller)) and I am able to see all the traffic now. The only traffic I do not see, is the websocket-traffic. I am using Fiddler as a proxy and it just shows that there is a tunnel which I can not look inside.

Are you able to see the websocket-traffic as well? And if yes, which proxy do you use for it?

Have a nice day :)
