### ISSUE TITLE
Update Instagram

### ISSUE THREAD

**Issue by frrakn** [mgp25/Instagram-API#727]
Think this is fixed with a new Instagram version + IG_SIG_KEY. I'm not near a USB-C cable right now, but will try to fix this later. Feel free to beat me to it :P

Edit: looks like I'm using cookies from `9.6.7`, so this is my fault, but still going to try to update the version.

**Comment by mgp25** [comment]
@frrakn feel free to send a pull request, ill merge it 

Thanks!
