### ISSUE TITLE
MediaInfoResponse doesn't include media's location info

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#728]
Hi!

When requesting mediaInfo() of a mediaId, the response use to include a LocationItem object with latitude, longitude and so on. Right now I get the mediaInfoReponse but no location info is included and I am sure I am checking it with a mediaId that has location info attached. Is there another way of getting it now or is it a bug?

Thanks!

**Comment by mgp25** [comment]
@joseflorido post debug log of the response

**Comment by joseflorido** [comment]
Sorry It's not an API issue. I just found out that to get the location info you need to get the fullResponse, like this:
$i->mediaInfo($mediaId)->getFullResponse()->items[0]->location;
