### ISSUE TITLE
Uploaded photo still can't be shared by direct message

### ISSUE THREAD

**Issue by rpw98** [mgp25/Instagram-API#73]
It always shows "This photo is unavailable right now"...

**Comment by RageBrahimi** [comment]
It's a similar case scenario when you try find an uploaded image (using this API) on a hashtag. It seems Instagram can detect it's not uploaded natively therefore it's probably restricted.

**Comment by mgp25** [comment]
@rpw98 i'll fix that eventually, i know where the issue is

Maybe in next release will be fixed

Regards

**Comment by rpw98** [comment]
@mgp25 Thank you! can't wait for the update!

**Comment by sinnus** [comment]
@mgp25 can you tell where problem is?
Thank you.

**Comment by rpw98** [comment]
@mgp25 have you found time to fix it? Or would you mind giving a hint on how to fix it?
Thank you!

**Comment by mgp25** [comment]
@rpw98 right now im very busy with exams and i wont be free again for 1 month or so :/ if no one update this i'll do it eventually when i have free time

Regards
