### ISSUE TITLE
[Support] How to return an Instagram object from Setting ?

### ISSUE THREAD

**Issue by mdtuyen** [mgp25/Instagram-API#732]
Hi,

After I login to Instagram API will save all session to `$username-cookies.dat` and `settings-$username.dat`
Now, I want retried complete an Instagram object from it. to create another request that user don't need login again.

How do I implement it ?

**Comment by mgp25** [comment]
@mdtuyen you dont need to call `login` function again, session is stored and you can keep working without logging in again, this is already implemented in the API

You can get info from settings like this:

https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L74

**Comment by mdtuyen** [comment]
Thank for your answer !
