### ISSUE TITLE
media view count

### ISSUE THREAD

**Issue by aliebrash** [mgp25/Instagram-API#734]
after Watch Video How to send view req to instagram to Increase the number of ViewCount of video

**Comment by mgp25** [comment]
@aliebrash Im not going to implement this

Regards

**Comment by aliebrash** [comment]
i really need it , can you help me to implement it ?

**Comment by mgp25** [comment]
No, will never implement this or help anyone to get this. Spoofing video views is not a good idea

**Comment by aliebrash** [comment]
no , my Target is not Spoofing  , by this function this project can 
More like the instagram ,this function can use like other function Without Spoofing  , this function can be like like_function by using  ( '_uuid'   '_uid' , '_csrftoken' , 'media_id'  ) and no Spoofing !!

**Comment by mgp25** [comment]
Im not going to do it

**Comment by aliebrash** [comment]
ok , tnx , but Without this item this project is Incomplete and instagram's Structure will
Disassemble , Because u and me watch a video but view_count of video not Increase and it make instagram's 
Facts Mistake . Good luck

**Comment by mgp25** [comment]
I dont mind, and i think Instagram wants it this way better, i can do it, but it wont be good for any of us

**Comment by aliebrash** [comment]
According to what I learned from this project This function such as like_function is controlled by Posted data and No one can fool instagram , Because instagram Understands Who applied , so u can make this function Without fear of abuse of this Ability !

**Comment by mgp25** [comment]
I know how Instagram works, you are not going to convince me

**Comment by aliebrash** [comment]
So it is a bug in instagram.. Thanks for the information..

**Comment by mgp25** [comment]
sigh... im tired of this
