### ISSUE TITLE
Edit Media Taggged Users

### ISSUE THREAD

**Issue by aleks63** [mgp25/Instagram-API#735]
Make possible tag an user through media edit.

**Comment by mgp25** [comment]
@aleks63 will do, it is added now on projects to do!

Regards

**Comment by zerotolerance** [comment]
Hello there,

I am using version 2.0. In the editMedia function I am experiencing problems in user tagging.

```
$userTags = '{"removed":[],"in":[{"position":[0.47097720202318,0.46537839732884],"user_id":"22154174"},{"position":[0.62168992664162,0.74074071616942],"user_id":"375789493"}]}'

editMedia($mediaId, $captionText, $userTags)
```


I will run it as above. I have not returned any errors. However, the user is not tagged.

I also only tag one user when I use the tagUser function. Does not tag more than 1 user.

Best regards
