### ISSUE TITLE
story of usrname_id

### ISSUE THREAD

**Issue by aliebrash** [mgp25/Instagram-API#737]
how can i get story of a username_id ?

**Comment by mgp25** [comment]
@aliebrash not implemented yet. Iterate items in the feed for now

Regards

**Comment by aliebrash** [comment]
it will implement ? when?

**Comment by mgp25** [comment]
Maybe, maybe not, i do this for free so there is no ETA. You can also do this by yourself, send a PR and ill merge it

Regards

**Comment by ahmdrz** [comment]
@mgp25 How did you wrote this library ? We want to get stories , So can you help us to wrote this code ?
For example , How did you see what follow button work?

**Comment by aliebrash** [comment]
Dadash in dahanesh baste hast..  Khodamo koshtam ye methode khas behem
ndad!!

**Comment by ahmdrz** [comment]
@aliebrash vali karesh doroste ! kheyli khoob kar karde , dada manam boodm in hame issue dashtam khodamo migereftam :))
to midoni chejori neveshte ?

**Comment by aliebrash** [comment]
@Ahmadreza na vaghean karesh doroste vali nemige chejori fahmide..kheyli chizasho midoone ama az amd naneveshte.. 
shoma chio daghighan mikhay bedoni?

**Comment by ahmdrz** [comment]
@aliebrash ke chejori android ro decode karde ... ye kari shabih MITM fek mikonm karde - ya inke omade khode source android ro baz karde

**Comment by aliebrash** [comment]
@Ahmadreza age doos dari bia telegram sohbat konim id : ebra59ali
