### ISSUE TITLE
block list's

### ISSUE THREAD

**Issue by sara89pr** [mgp25/Instagram-API#739]
hi , how can i get list of 'users that blocked me' and 'users that i blocked them' ?

**Comment by mgp25** [comment]
@sara89pr has Instagram app that feature? If not, then the API is the same. If the answer is yes, then, its not implemented. You can see friendship statuses.

Regards

**Comment by sara89pr** [comment]
in instagram app i just find 'users that i blocked them' in Options->Blocked Users , so you can create this
