### ISSUE TITLE
Method to get suggested users?

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#741]
Hi, is there a method to get suggested users to follow based on a particular user? Something like similar users.

The app has the functionality, so I wonder if it's already doable with the existing code but couldn't find it.

Thanks

**Comment by mgp25** [comment]
@joseflorido not implemented, but you can capture the request and send a pull request

Regards

**Comment by joseflorido** [comment]
Will give it a try, thanks!
