### ISSUE TITLE
registration tool issues

### ISSUE THREAD

**Issue by alexandrei892** [mgp25/Instagram-API#742]
Hi,
there are some issues with the registration tool
```

{ instagram }  » php registrationTool.php
###########################
#                         #
# Instagram Register Tool #
#                         #
###########################

Username: myUser

Fatal error: Call to a member function setSignedPost() on array in C:\projects\instagram\vendor\mgp25\instagram-php\src\InstagramRegistration.php on line 89
PHP Fatal error:  Call to a member function setSignedPost() on array in C:\projects\instagram\vendor\mgp25\instagram-php\src\InstagramRegistration.php on line 89
```

Which is because the **request** method from **InstagramRegistration** returns an array.
I did try to come with a solution but I don't have anything to show for my efforts :(

**Comment by mgp25** [comment]
@alexandrei892 it requires an update, i guess it will be updated someday this week. You can create account manually using device meanwhile

Regards
