### ISSUE TITLE
Problem posting text with emoji and newline

### ISSUE THREAD

**Issue by tantita** [mgp25/Instagram-API#744]
Whenever I post a text using the API containing and emoji and a newline, d emoji posts successfully, but the newline is truncated. I have tried various solutions to this but no success.

Please note that my table/field uses utf8mb4 encoding

**Comment by yazhog** [comment]
i think its not this API issue
I have many times faced with the same problem in official instagram app on my android device

try to upload a photo to Instagram with the same text and emoji through a original application
