### ISSUE TITLE
See unread thread (message)

### ISSUE THREAD

**Issue by riddict** [mgp25/Instagram-API#755]
Hi it's me again
Can someone tell me how to see if a thread is unread/unseen? I can get number of unseen thread/message. But I can't define if a thread is unseen or not. 
At first I thought that the value of "has_newer" is the answer but turn out even the unseen messages/threads have false value.
Thanks.

Ahh also I haven't found the way to post a comment in media. I keep getting this error
```
InvalidArgumentException in JsonMapper.php line 126:
JsonMapper::map() requires first argument to be an object, NULL given.
```
here is the debug result
```
POST: media/ 1361172910135754702_33801695/comment/ DATA: ig_sig_key_version=4&signed_body=532c9c206ca418cd38311b963317490c69604fdbecd918e9bb41cc13e5254892.{"_uuid":"b2271fc0-ebb5-4629-adea-cf3dc6e2899e","_uid":"xxxxxxxx","_csrftoken":"Ov6es3zFBDwCnCSY331c2s2gLT5qExxxx","comment_text":"tes dulu"} ← 400 105B RESPONSE:
5xx Server Error
```
I am using the latest commit.

**Comment by mgp25** [comment]
@riddict 

if you receive 5xx Server Error

 Instagram is refusing your connection or somethng bad in your server configuration or request, not API issue.

Regards

**Comment by riddict** [comment]
@mgp25 than, how can we get the unread status or unseen for a thread?
