### ISSUE TITLE
Upload post with user_name and access_token

### ISSUE THREAD

**Issue by codewp** [mgp25/Instagram-API#757]
I checked your codes and saw that it's works with user_name and password to posting.

Is it possible to send photo to Instagram with user_name and user_id and access_token, by changing your codes?

My app has access to user_name and user_id and access_token of users, now I want to add a feature to the app to upload photo to Instagram but I saw that your API works with user_name and password, so please let me know can I upload photo by user_name and user_id and access_token or no?

Best Regards.

**Comment by mgp25** [comment]
@codewp nope, only way to upload photo is using an account (username and password) like in the device

Regards
