### ISSUE TITLE
getUsernameId($username) error

### ISSUE THREAD

**Issue by z11labs** [mgp25/Instagram-API#760]
Hey :)

I updated to the newest commit-version and changed some of my code to work with the new version of this api-library.

Now it gives me the error `"Wrong function getUsernameId"`. I figured out which function gave me this error and wrote a testing-script to find out where exactly I've made the mistake. The code is the following:

```php
<?php
    
    require("./../vendor/autoload.php");

    $username = "someusername";
    $password = "somepassword";

    $instagram = new \InstagramAPI\Instagram();
    $instagram->setUser($username, $password);
    $instagram->login();

    echo "<pre>";
    $user = $instagram->getUsernameId($username);
    echo "</pre>";
    
?>
```
I filled in my credentials for `$username` and `$password` of course.

But it gives me the following error:

```
Fatal error:  Uncaught exception 'Exception' with message 'Wrong function getUsernameId' in /var/www/vendor/mgp25/instagram-php/src/Utils/AutoResponseFunctionSetter.php:19
Stack trace:
#0 /var/www/vendor/mgp25/instagram-php/src/Instagram.php(1117): InstagramAPI\AutoResponseFunctionSetter->__call('getUsernameId', Array)
#1 /var/www/vendor/mgp25/instagram-php/src/Instagram.php(1117): InstagramAPI\UsernameInfoResponse->getUsernameId()
#2 /var/www/html/test.php(13): InstagramAPI\Instagram->getUsernameId('someusername')
#3 {main}
  thrown in /var/www/vendor/mgp25/instagram-php/src/Utils/AutoResponseFunctionSetter.php on line 19
```
Am I wrong or is this error telling me, that the function named `getUsernameId` is not existing? I instantly checked this via
```php
print_r(get_class_methods($instagram));
```
and the function is existing. Therefore I'm asking myself what I did wrong or if it is an error of this api-library. 

**Can someone reproduce this error or has the same problem?**
**& how can I fix this?**

Thanks for your answer.

**Comment by mgp25** [comment]
@z11labs make sure you are using latest commit from master, it is working

Regards

**Comment by z11labs** [comment]
@mgp25 used `dev-master`, now its working
