### ISSUE TITLE
jsonmapper

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#762]
jsonmapper breaks my autoloader. `/item.php` against `Services\Instagram\http\Response\Objects\Item`

autoloader:

```php
function autoload($className)
{
    $className = ltrim($className, '\\'); // Удаляет символы из начала строки
    $fileName  = '';   // имя файла
    $namespace = '';   // область
    if ($lastNsPos = strrpos($className, '\\')) {       // есть ли обатные слеши
        $namespace = substr($className, 0, $lastNsPos);
        $className = substr($className, $lastNsPos + 1);
        $fileName  = str_replace('\\', DIRECTORY_SEPARATOR, $namespace) . DIRECTORY_SEPARATOR;
    }
    $fileName .= str_replace('', DIRECTORY_SEPARATOR, $className) . '.php';
    $fileName = str_replace('modules', '', $fileName);

    if (strrpos($fileName, '/', -strlen($fileName)) === false) {
        $fileName = '/' . $fileName;
    }

    print_r($fileName.'<br>');
    /*if ($fileName == '/Response.php'){
        var_dump(debug_backtrace());
    }            */
    require_once __DIR__ . $fileName;
}

spl_autoload_register('autoload');
```

Why do we need this jsonmapper ???
Breaks when the check class. || `is_subclass_of ($ type, 'ArrayObject')`

Now we have to rewrite jsonmapper.
For fun, check how it works with autoloaders

**Comment by cweiske** [comment]
Your autoloader is doing it wrong. Autoloaders are meant to be chained, which means that any autoloader must not fail if it cannot find a class. Use `file_exists` before using `require_once`.

**Comment by Triden** [comment]
Maybe you even tell. The class exists. Wrong looking for. Example. $ This-> mapper = new JsonMapper (); Seeking JsonMapper class. If screening.
$ This-> mapper = new \ JsonMapper (); already looking for the class 'Services \ Instagram \ http \ Response \ Objects \ JsonMapper'
This is how: $ rc = new \ ReflectionClass ($ object);
It does not work: $ rc = new ReflectionClass ($ object);
I do not speak English well. Can you suggest something?

**Comment by Triden** [comment]
I use
use Services \ Instagram \ http \ Response \ Objects \ Item;
is_subclass_of ignoring it.

**Comment by Triden** [comment]
I did not know what kind of magic. The file has ConfigureResponse.php
     / **
      * @var Item
      * /

Why does it fall into the autoloader. He was looking for this class. Removing this comment all was working well. I am submitting again looking for. But this is a comment documentation. Why did he then played a role.

**Comment by mgp25** [comment]
jsonmapper uses it, it reads the comments to interpret the data. Use composer

**Comment by jpmoney5065** [comment]
This works for me.
Class needs to be in current directory or a sub directory

```
const EXCLUDE_DIRS  = 'data';


spl_autoload_register(function ($className,$exclude = EXCLUDE_DIRS) {

    if (strpos($className, "\\") !== false) {
        $classPos   = strrpos($className, "\\");
        $className  = substr($className,$classPos+1);
    }

    $dirs       = getAllSubDirectories(realpath( dirname( __FILE__ )).DIRECTORY_SEPARATOR,$exclude);

    foreach($dirs as $dadir){
        $file = "{$dadir}{$className}.php";
        if (is_readable($file)) {
            require_once $file;
        }
    }
});

function getAllSubDirectories( $directory,$exclude=null ){
    $directory_seperator = DIRECTORY_SEPARATOR;
    $dirs = array_map( function($item)use($directory_seperator){ return $item . $directory_seperator;}, array_filter( glob( $directory . '*' ), 'is_dir') );
    $dirs =  array_values($dirs);
    foreach( $dirs AS $key=>$dir ){
        if(!is_null($exclude)){
            if(!is_array($exclude)) {$exclude = array($exclude);}
            foreach ($exclude as $ex){
                if (strpos($dir, DIRECTORY_SEPARATOR.$ex.DIRECTORY_SEPARATOR) !== false) {
                    unset($dirs[$key]);
                    continue 2;
                }
            }
        }
        $dirs = array_merge( $dirs, getAllSubDirectories( $dir,$exclude ) );
    }
    $dirs[]=$directory;
    $dirs=array_unique($dirs);
    return $dirs;
}
```

**Comment by samet05203** [comment]
Class needs to be in current directory or a sub directory 
you said that in which directory what can I do

**Comment by samet05203** [comment]
may you update your api mgp25
