### ISSUE TITLE
Uploaded image isn't in the right format

### ISSUE THREAD

**Issue by golches** [mgp25/Instagram-API#763]
POST: upload/video/ → 0B ← 0 0B RESPONSE: POST: upload/photo/ → 0B ← 0 0B RESPONSE: POST: upload/photo/ → 765B ← 200 46B RESPONSE: {"status": "ok", "upload_id": "1481275289670"} POST: media/configure/? DATA: ig_sig_key_version=4&signed_body=ec32ce6570cb4de9ab0266e320e09cbd93fb889e228c9cc675ca0b2da4cb3890.{"_csrftoken":"9MnaJ0ftBbreOi9DG6NIb61nLcKkCvI4","media_folder":"Instagram","source_type":4,"_uid":"3960926562","_uuid":"15eedaf4-03c9-495c-a358-209ef6498959","caption":"also video now","upload_id":"1481275289670","device":{"manufacturer":"Doro","model":"Doro 8031","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":null,"source_height":null}} ← 400 73B RESPONSE: {"status": "fail", "message": "Uploaded image isn't in the right format"} 

i tryed a lot of instagram video and video saved from my phone, but always i got the same error even when i convert profile to baseline

**Comment by mgp25** [comment]
@golches make sure ffmpeg is working fine. Try to debug lines where ffmpeg return data. Also,  check that `$size = getimagesize($photo)[0];` is returning the size of the preview image, if its null as i see in the debug log:

```json
"crop_original_size":[null,null]
```

Seems to be an ffmpeg issue

Regards

**Comment by golches** [comment]
ok thank you for quick response

when you said ffmpeg i went to my server wher ffmpeg is insalled and i get a new error : You did not specify image.

with this debug


POST: upload/video/ → 496B ← 200 2.52kB RESPONSE: {
"status": "ok",
 "upload_id": "1481279997652",
 "video_upload_urls": [
{
"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c22\u0026vx_token=307\u0026staging_in_tao=0",
 "job": "AQDpzT1NS3U0xL5J8w4vn_hX5i-UiB44LzPV_VpsKOg2NbuTlHpZQLO7j0eCZtDZKUxnaydyF45wWOiI1hGER9KEeodfR8OMLRuEqlG-kmhsnq1N9PzwyQjFTJnEXjTWiwxtnNQ6GKT_us6NjJInx6zWsQ7xZuk5m2VyMVN_ouibQhocGhlyE5N7rPytp6xRDZSksX-s60fvftgM_a20BrUEq9OlmbPlir4E84SpPLXFdzOXmPfgfIcfpUex7z_2moRcAZUpqmGJuZ0naRpd8td2avtNkPIx_r_KWIue5k1DRld5hhf5M7jgncaIJzAFedklzN1w2mtLVWpGRnfPaXP0VMnh0nRROVboJTx41kOdCxrfI1rkJn1END8eUsL8ikbHTQZ_wb-5UZdE3_tD6fM009P0-RlT17lt4EP8TRyHcR4SvDcKxbrPBnXNw2xFyM5xIa5W5GahTNeqB_Dzk0h9",
 "expires": 1796639997.972183},
 {
"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c27\u0026vx_token=311\u0026staging_in_tao=0",
 "job": "AQATNp1T6qxlYAZAEBxTJNqe7f1v8z0vOiRrnPpVYoG6dWwzWFFTqnhLEGC2voj5BKcxJ-0iBZ7UpIxxau1HY5gQN8XxoKdwgnA9VpccWo_mws0lpD4uS3kwarOzSCVrkWvko28czy04SZrLLgJz493PtJIf2ui1BVgBcSgIAeI6vqI4mnd0bro1_bMLImC0uf7L9X_JtsnvKdtx4i2T30_V8rJWpQO0vWZWTCD-D1eJDarIXDp9BdPh2LcOXpgMhAbMU0C61gOtudyXQDwoVBsO19BkuFPTGaaP9hIk3993AwWVFml30mU8-DScE3I4pIvGtWH-lwmjZX19Y7QnMhCKq6Bz8LsMPiWI4Z5TK2k3w1NfBis6oOaNM0Z0i9cP_lvQ2zOsLbznQTi2Zd5hJwu3BxTUnLFi4VTc5ag80Dj7cOXXFX7Sg_ItK42grbgXByatVFaDPn-xTv9JO4Fzgfc0",
 "expires": 1796639997.973118},
 {
"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c22\u0026vx_token=308\u0026staging_in_tao=0",
 "job": "AQB--jaWAZfmR0jueo6Uoj6IXK3udqCvwMPAPav2EjwwKxlTex0oV8Quuynfmbe3wuVeCZoeat8QK-Od-orl9Ukngj7SLIGPMZHtX4r9WtmXZu3HcSkEaM_P2er8VmYkJAKprEF0rz_HwiU10sZ1dPzvnle362tv_lZ2j3eosPCrUOWlv_Pw3sPRzggBkiwaKmlNlW9ht7V6kcx4ZTtAzBw5Y2JVdgcZ2d8C9_eUaf8_cR-Mh8IgEzuI3Bq801m31F0RIarOCc-xymi0cBrNyH04WbFiuX1YQaAW6hmy4rL8-lAk1dj9ZfuNS9yIv--PjH-v2LUf3Eq_j__lLVNOx7dFDIAUTJYH_XzzvGFpkfUa1NZjUYw3r6tOoA-74UhnXKh1W6FfQO46hBYjsqjl7eWn5F2qW8IjzqYupzGoUOwrNr_m5t_Apz-dbzveD-YxLAmHTfRTtxBaPTZtdjbEeBqI",
 "expires": 1796639997.974125},
 {
"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c27\u0026vx_token=102\u0026staging_in_tao=0",
 "job": "AQDelpiKT5b6gJEuxUPuAEuaV_47wiB4vl6lWyds5RKjVWJ8lXIF-5sZKitB4YJSxzvdEncOkYIHB3K-xe-kUUMokki-Hxw_kjM_iNGHhHFHwchwx8I9_yPLxzEJ4QJKb9lZJCC8iYlZcendo2qAJrfySBvd2LSs0Wuv-pWiLvpKGb99jBOYHcMoyZWxgqfhQGmHboHsPAh1ZRlOxY5GF8Q6PffLKBUZ0dDXHmhOUg55Cn7FR0i9L_LAfBo8YgTO3GTrk7xCpEEGImPUDZJRheJJnlRxVoQ9fjYHgzuPPpId6HN4HP5VswnZf5bPQxbYK-8jfk4v8KgIh-NzXqBm54bpY2IFTz6-oJmkZAsvNyM-a6CuDfn6-LtR-XrAQPvRdCuIYuHDrAU10nM-hnC2R2MX3AHaj_fY2ZcjL6flLO69-Ek9BV4AJjOFNd7k6x-LaS2Htl_rQ7O42EJrh50HC9yb",
 "expires": 1796639997.975115}
]
}
 POST: https://upload.instagram.com/api/v1/stage/video/?target=prn1c27&vx_token=102&staging_in_tao=0 → 499.99kB ← 201 16B RESPONSE: 0-511988/2047957 POST: https://upload.instagram.com/api/v1/stage/video/?target=prn1c27&vx_token=102&staging_in_tao=0 → 999.98kB ← 201 17B RESPONSE: 0-1023977/2047957 POST: https://upload.instagram.com/api/v1/stage/video/?target=prn1c27&vx_token=102&staging_in_tao=0 → 999.98kB ← 201 17B RESPONSE: 0-1535966/2047957 POST: https://upload.instagram.com/api/v1/stage/video/?target=prn1c27&vx_token=102&staging_in_tao=0 → 499.99kB ← 200 70B RESPONSE: {
"status": "ok",
 "result": "deprecated",
 "configure_delay_ms": "6500"}
 POST: upload/video/ ← 201 23B RESPONSE: 1535967-2047956/2047957 Error: You did not specify image.
