### ISSUE TITLE
update uploadvideo

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#765]
I'm a little upgraded video upload. I suggest you upgrade it. Now you can download the video only if the video on your server. You can not download the link from instagram, for example. I propose to do here are the changes:
 public function uploadVideo ($ video, $ caption = null, $ customPreview = null)
    {
        $ VideoData = file_get_contents ($ video);
        file_put_contents (sys_get_temp_dir () '/' md5 ($ video) 'mp4.', $ videoData...);

public static function createVideoIcon ($ file)
    {
        / * Should install ffmpeg for the method to work successfully * /
        $ Ffmpeg = self :: checkFFMPEG ();
        if ($ ffmpeg) {
            // Generate thumbnail
            .. $ Preview = sys_get_temp_dir () '/' md5 ($ file) 'jpg.'.;
            @unlink ($ preview);

            $ File = sys_get_temp_dir () '/' md5 ($ file) 'mp4.'...;
            // Capture video preview
            $ Command = $ ffmpeg. ' -i " '. $ file.'" -f mjpeg -ss 00:00:01 -vframes 1 " '$ preview..'" 2> & 1 ';
            @exec ($ command, $ a, $ b);
            print_r ([$ a, $ b, $ file]);
            return file_get_contents ($ preview);
        }
    }

This will upload the video link. I got a vps is the only way to do it

**Comment by mgp25** [comment]
@Triden send a pr
