### ISSUE TITLE
Nth elelment in array.

### ISSUE THREAD

**Issue by Instaerror** [mgp25/Instagram-API#768]
Great Repository!
 
Apologies for post, I need a small push in the right direction,

But cant i get say the first returned Pk from getUserFollowers with something like this?

$target_id = '1111111111';
$a = $i->getUserFollowers($target_id);
echo $a[0]->getPk();

**Comment by mgp25** [comment]
@Instaerror i guess, check what `$a` has with `var_dump` and the rest its quite easy.

If you need more help in programming: https://secure.php.net/manual/en/index.php

Regards

**Comment by Instaerror** [comment]
Thanks for the tips, it should be something like this;

$a = $i->getUserFollowers($target_id);
echo $a['users'][0]['pk'];

object(InstagramAPI\FollowerResponse)#171 (5) {
  ["users"]=>
  array(200) {
    [0]=>
    object(InstagramAPI\User)#972 (46) {
      ["username"]=>
      string(11) "soyabraham_"
      ["has_anonymous_profile_picture"]=>
      bool(false)
      ["is_favorite"]=>
      bool(false)
      ["profile_pic_url"]=>
      string(110) "http://instagram.flhr2-2.fna.fbcdn.net/t51.2885-19/s150x150/15276504_670582896_a.jpg"
      ["full_name"]=>
      string(14) "xxxxxx"
      ["pk"]=>
      int(11111112233)

**Comment by mgp25** [comment]
@Instaerror not exactly.

You can do this:

`$i->getUserFollowers()->getUsers()`

Then you can iterate them and the use `->getPk()`

Regards

**Comment by Instaerror** [comment]
Got it!

echo '>>> '.$a[0]->getPk()."\n";

**Comment by Instaerror** [comment]
@mgp25 always returns null any ideas?

$helper = null;
$following = [];

try {
    do {
        if (is_null($helper)) {
            $helper = $i->getSelfUsersFollowing();
        } else {
            $helper = $i->getSelfUsersFollowing($helper->getNextMaxId());
        }
        $following = array_merge($following, $helper->getFollowings());
    } while (!is_null($helper->getNextMaxId()));

    var_dump($following);

**Comment by mgp25** [comment]
Check this example: https://github.com/mgp25/Instagram-API/blob/master/examples/PaginationExample.php

Set `$debug` to `true`, to see requests and responses, that way you will be able to know what could happen

**Comment by Instaerror** [comment]
The pagination example works fine for self followers, only get null on the getSelfUsersFollowing.
