### ISSUE TITLE
classloader

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#769]
my autoloader does not see @var User !! On this correctly, they must be removed. Because this does not work AutoResponseFunctionSetter !!! Why it was necessary to do? Not all are using your autoloader. Is it possible to use the two autoloader simultaneously? Yours and mine?

**Comment by mgp25** [comment]
https://lmgtfy.com/?q=Is+it+possible+to+use+the+two+autoloader+simultaneously%3F

Regards
