### ISSUE TITLE
Like Media

### ISSUE THREAD

**Issue by kripsbro** [mgp25/Instagram-API#77]
Response {
    error = "";
    response =     {
        message = "Sorry, you cannot like this media";
        status = fail;
    };
} , but if this media is mine, like works

**Comment by RageBrahimi** [comment]
Show us the code, also the debug.

**Comment by kripsbro** [comment]
Hello, just found :D i  was send invalid Media ID, thanks :)

**Comment by TinBoyko** [comment]
Are you getting media id from url? I have same problem.
