### ISSUE TITLE
construct failed

### ISSUE THREAD

**Issue by MAXVELL2010** [mgp25/Instagram-API#771]
PHP Fatal error:  Uncaught Error: Class 'InstagramAPI\JsonMapper' not found in ...\vendor\mgp25\instagram-php\src\Instagram.php:53
Stack trace:
#0 ...\vendor\mgp25\instagram-php\examples\uploadPhoto.php(17): InstagramAPI\Instagram->__construct(false)
#1 {main}
  thrown in ...\vendor\mgp25\instagram-php\src\Instagram.php on line 53

I am install project to composer and want upload photo, but I hame fatal error, why? help me please
Using version v1.6.0.2 for mgp25/instagram-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing netresearch/jsonmapper (v1.1.0)
    Downloading: 100%

  - Installing mgp25/instagram-php (v1.6.0.2)
    Downloading: 100%

Writing lock file
Generating autoload files

**Comment by mgp25** [comment]
@MAXVELL2010 try

` composer dump-autoload`

And then it should work. This issue is because JsonMapper is not found:

```
PHP Fatal error: Uncaught Error: Class 'InstagramAPI\JsonMapper' not found in ...\vendor\mgp25\instagram-php\src\Instagram.php:53
```

Regards

**Comment by MAXVELL2010** [comment]
> And then it should work. This issue is because JsonMapper is not found
But this is fail in folder, why it seen
