### ISSUE TITLE
 Class 'JsonMapper' not found

### ISSUE THREAD

**Issue by MAXVELL2010** [mgp25/Instagram-API#772]
I am use: composer dump-autoload
C:\Users\max\Documents\SeoInsta\SourceCode\new inst\vendor\mgp25\instagram-php>composer dump-autoload
Generating autoload files

all good, but nothing gon`t work
PHP Fatal error:  Uncaught Error: Class 'JsonMapper' not found in C:\Users\max\Documents\SeoInsta\SourceCode\new inst\vendor\mgp25\instagram-php\src\Instagram.php:53
what am I doing wrong?
 thanks

**Comment by Syr0kx** [comment]
same issue here :/

**Comment by Syr0kx** [comment]
sorry didn't read README.md ...

**Comment by mgp25** [comment]
Use this: https://github.com/mgp25/Instagram-API/issues/762#issuecomment-266050674
