### ISSUE TITLE
stable version?

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#773]
There is some sort of a stable version? Which works without jsonmapper. Without UsernameInfoResponse and so on. D. Paul has rewritten the code. Well, do not operate your @var adequately. He writes, "is not found." Even manually connect these modules still can not see classes !!!!!! For 2 nights stayed.

**Comment by Triden** [comment]
How to get a property without UsernameInfoResponse?

**Comment by Triden** [comment]
Make an ordinary inheritance without @var, please! It is a gathering anrial

**Comment by Triden** [comment]
I found how to bypass response
$ UserInfo-> user-> profile pic_url

**Comment by Triden** [comment]
Why do I need to write a parser and so getProfile_pic_url, if you can just
$UserInfo-> user->profile_pic_url?

**Comment by mgp25** [comment]
oh my god... this is not a forum, there is no reason to spam with many posts. just click and edit your own comment.

Edit the code the way you like, you already know how to make it work
