### ISSUE TITLE
getUserFollowing ( use next_max_id )

### ISSUE THREAD

**Issue by sara89pr** [mgp25/Instagram-API#775]
when i use getUserFollowing function with next_max_id , reurned rerun response !
how to fix it ?

**Comment by mgp25** [comment]
Have you give more details in what you mean? Like debug, response etc etc etc...

**Comment by sara89pr** [comment]
for users that have more than 200 following , we must use next_max_id to get rest of the following list , when i send The second request with next_max_id , The result have Different next_max_id but the users not change and first list users returned !

**Comment by mgp25** [comment]
@sara89pr normal behaviour. It happens the same in the Instagram app

Regards
