### ISSUE TITLE
Follow, possible flaw.

### ISSUE THREAD

**Issue by Instaerror** [mgp25/Instagram-API#777]
I have tried a few different private API systems and they all seem to have this one flaw where after a short while the follow is blocked with no error message or error response just 200's as normal. When I then go to my android phone I cannot then follow anyone for a short period of a time, generally a few hours, but you can on a browser. Try it yourself follow with say a 2minute gap inbetween so only 30 follows an hour, then after a while it will just stop following. Unfollow is fine and so is like and everything else.

**Comment by mgp25** [comment]
Is okay, expected behaviour

Regards

**Comment by Instaerror** [comment]
Anyway of fixing this bug?

**Comment by mgp25** [comment]
@Instaerror is not a bug, is an expected behaviour. You need to understand how Instagram works so you can understand api responses etc

**Comment by Instaerror** [comment]
No mention in the wiki, is this documented somewhere else?
