### ISSUE TITLE
Wrong function getUploadId

### ISSUE THREAD

**Issue by hakanbolat** [mgp25/Instagram-API#778]
I'm trying to upload photos.
i think every things is true. but i get this error. could u help me?
POST:  upload/photo/
→ 233.44kB
← 200 	 46B
RESPONSE: {"status": "ok", "upload_id": "1481708063049"}
Wrong function getUploadId

**Comment by mgp25** [comment]
Debug log seems okay, for further support post your code

Regards

**Comment by hakanbolat** [comment]
I just use the example folder. uploadsPhoto.php. its like this,
<?php

include __DIR__.'/../../../../vendor/autoload.php';
require '../src/Instagram.php';

/////// CONFIG ///////
$username = 'MY_USER_NAME';
$password = 'MY_PASSWORD';
$debug = true;

$photo = 'E30.jpg';     // path to the photo
$caption = 'Bmw e30';     // caption
//////////////////////

$i = new \InstagramAPI\Instagram($debug);
//print_r(get_class_methods($i));

$i->setUser($username, $password);

try {
    $i->login();
} catch (Exception $e) {
    echo $e->getMessage();
    exit();
}

try {
    $i->uploadPhoto($photo, $caption);
    echo "Success...";
} catch (Exception $e) {
    echo $e->getMessage();
}

**Comment by mgp25** [comment]
@hakanbolat are you using latest commit from master?

**Comment by hakanbolat** [comment]
Yes, I merge it half an hour ago. i did use composer require mgp25/instagram-php dev-master
am i wrong?

**Comment by hakanbolat** [comment]
First I got this error Wrong function  getLoggedInUser in Instagram.php line 150, then i changed this line my user name id. like this: $this->username_id = 42632xxxx;

**Comment by mgp25** [comment]
@hakanbolat line 150 should be:

```php
            $this->username_id = $response->getLoggedInUser()->getPk();
```

Are you sure you are using latest commit?

**Comment by hakanbolat** [comment]
i know. if i dont change this line i get this error Wrong function getLoggedInUser . so i changed it like this: $this->username_id = 42632xxxx; then i get this error Wrong function getUploadId.
I deleted all files and install with composer require mgp25/instagram-php dev-master
same error Wrong function getLoggedInUser.

**Comment by mgp25** [comment]
@hakanbolat after you have used composer require, use this: `composer dump-autoload`

And then try the code again

**Comment by hakanbolat** [comment]
i did it. same errors.
