### ISSUE TITLE
Instagram Views

### ISSUE THREAD

**Issue by pentatonicfunk** [mgp25/Instagram-API#78]
As we already knew, there is views count on instagram video, how to increase it ? because **like** method on the code, not adding view too

**Comment by mgp25** [comment]
In this case just by watching it, will increment the counter, i guess there should be an endpoint, i'll add this probablr in the next release

Regards

**Comment by jerry317** [comment]
@mgp25 When will you add this feature? Thanks.

**Comment by mgp25** [comment]
@jerry317 maybe never

**Comment by kurtisane** [comment]
@mgp26 is this not possible or what is the reason behind it ?

I really do need it.

**Comment by mgp25** [comment]
The reason i dont want to do it, is spammers. If you need it, do it yourself
