### ISSUE TITLE
images are blocked from the search

### ISSUE THREAD

**Issue by baum1234** [mgp25/Instagram-API#780]
When I upload a image with a hashtag and search for the hashtag on my phone with a second account I can't find the image that I just uploaded. Or if I press on the hashtag under the image then the image is not show, with a second account as well. Do I something wrong?

**Comment by mgp25** [comment]
@baum1234 it is okay, expected behaviour

Regards

**Comment by baum1234** [comment]
@mgp25 really? could you please explain why?
