### ISSUE TITLE
pagination for getRecentActivity

### ISSUE THREAD

**Issue by noorzaie** [mgp25/Instagram-API#782]
In the `getRecentActivity()` function, we don't have any max_id for getting next page of recent activities. 

`$activity = new ActivityNewsResponse($this->http->request('news/inbox/?activity_module=all')[1]);`

How should I get next page ??

**Comment by mgp25** [comment]
Maybe it has the `max_id` attriv, try it by adding it in the url. If it doesnt work, you should use a proxy and compare the requests with the ones in the API

Regards

**Comment by noorzaie** [comment]
but there is no max_id in instagram's response!
