### ISSUE TITLE
Class 'InstagramAPI\Exception' not found in AdaptImage.php on line 21

### ISSUE THREAD

**Issue by TzoLy** [mgp25/Instagram-API#784]
Hi there,
I've got this error trying to upload a video
`[16-Dec-2016 00:03:44 Europe/Helsinki] PHP Fatal error:  Class 'InstagramAPI\Exception' not found in /home/cipriant/public_html/ig/angels_magazine/src/Utils/AdaptImage.php on line 21
`
Any ideas how to solve this problem?

**Comment by mgp25** [comment]
@TzoLy use dev-master code

Regards

**Comment by TzoLy** [comment]
Well.. i get this error now after using dev-master code
`PHP Fatal error:  Class 'JsonMapper' not found in C:\wamp\www\instagram\v1.3\vendor\mgp25\instagram-php\src\Instagram.php on line 48`
