### ISSUE TITLE
error on upload video

### ISSUE THREAD

**Issue by sajad2745** [mgp25/Instagram-API#786]
hi
i get this error on uploading video 
i use default example for uploading video
>   Fatal error: Uncaught exception 'InvalidArgumentException' with message 'JsonMapper::map() requires first argument to be an object, NULL given.' in E:\xampp\htdocs\testss\insta\Instagram-API-master\vendor\netresearch\jsonmapper\src\JsonMapper.php:126 Stack trace: #0 E:\xampp\htdocs\testss\insta\Instagram-API-master\src\http\HttpInterface.php(120): JsonMapper->map(NULL, Object(InstagramAPI\UploadJobVideoResponse)) #1 E:\xampp\htdocs\testss\insta\Instagram-API-master\src\http\HttpInterface.php(347): InstagramAPI\HttpInterface->getResponseWithResult(Object(InstagramAPI\UploadJobVideoResponse), NULL) #2 E:\xampp\htdocs\testss\insta\Instagram-API-master\src\Instagram.php(415): InstagramAPI\HttpInterface->uploadVideo('./video.mp4', '', NULL) #3 E:\xampp\htdocs\testss\insta\Instagram-API-master\examples\uploadVideo.php(21): InstagramAPI\Instagram->uploadVideo('./video.mp4', '') #4 {main} thrown in E:\xampp\htdocs\testss\insta\Instagram-API-master\vendor\netresearch\jsonmapper\src\JsonMapper.php on line 126

**Comment by msmoosa** [comment]
This generally happens when you're requests ended up with 500 internal server error.
Please post the debug logs so we can know where it failed.
Also, make sure you have ffmpeg installed

**Comment by mgp25** [comment]
@sajad2745 null was the output of the request make sure everything is configured right.

Not API issue

Regards
