### ISSUE TITLE
Paramaters for Signature Key extracted from Instagram 10.3.0

### ISSUE THREAD

**Issue by taylorkarras** [mgp25/Instagram-API#787]
I recently bought a burner phone and extracted Instagram's signature key through there so I can have my own source for a plugin I'm developing. Unfortunately I don't know what settings to use since I used the latest version; I keep getting an "invalid request" from the API servers and I don't know what I'm doing wrong.

Please help.

**Comment by mgp25** [comment]
Check api requests and compare whats left

Regards
