### ISSUE TITLE
getMediaLikers() return 1000 users only

### ISSUE THREAD

**Issue by camb0leg** [mgp25/Instagram-API#788]
request:
`$i->getMediaLikers($usermedia->getPk())`
`

respond:
```object(InstagramAPI\MediaLikersResponse)#261 (5) {
  ["user_count"]=>
  int(1344)
  ["users"]=>
  array(1000) {
    [0]=>
    object(InstagramAPI\User)#1490 (46) {
...
```

**Comment by ovs1** [comment]
If i don't miss call there is a limit for this request. so nothing wrong with the code.

**Comment by mgp25** [comment]
Normal behaviour. It is limited. It's the same in Instagram app

Regards
