### ISSUE TITLE
User with infinity phones

### ISSUE THREAD

**Issue by Enelar** [mgp25/Instagram-API#79]
This is bad idea, on every single request change phone id.
It suspicious. And detectable.

**Comment by dfanara** [comment]
I agree, the phoneId, and uuid should be stored across sessions to make it less detectable. I have been working on a Java implementation and have implemented this in order to decrease the likelihood of getting the accounts banned.

**Comment by Enelar** [comment]
@dfanara uuid should be const too?

**Comment by dfanara** [comment]
@Enelar I believe so. I also made the device id and phone id constant too. I suppose I could be wrong, it just seemed to keep them the same throughout the duration of the session.

**Comment by Enelar** [comment]
@dfanara This seems senseless to me. I expect uuid be random every single login. Traffic sniff required.

**Comment by mgp25** [comment]
It doesn't matter if the uuid changed, uuid represents the device unique id. So we can be in many scecenarios, i could be rich and have 1000 thousand devices, each one has its own uuid and i can login to Instagram with all of them, see the example?

You can make it static but it wouldn't make any difference.

Regards

**Comment by Enelar** [comment]
@mgp25 ??? what about device_id?
