### ISSUE TITLE
Is there any way to know How many post in Location 

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#790]
As you know when you search for Tags you can know how many POST in this Tag.
Is this available in Location , !

Location Response does not include any count !

If it is not available , is there any work around

**Comment by mgp25** [comment]
Amm... sure, use `count()` function.

Reference: https://secure.php.net/manual/en/function.count.php

**Comment by beshoo1** [comment]
I am sorry i dont like this kind of replay , 
I am serious!
and count will not count ALL Posted Media by All users in the world
