### ISSUE TITLE
qe/sync invalid request

### ISSUE THREAD

**Issue by berkayk** [mgp25/Instagram-API#791]
I am receiving invalid request response after calling sync method. What could be missing?
Thanks.

Headers: 

`{"Connection":"close","Accept":"*/*","X-IG-Capabilities":"3ToAAA==","X-IG-Connection-Type":"WIFI","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8","Accept-Language":"en-US"}`

Body Sent:

`ig_sig_key_version=4&signed_body=0ceb8691fde711e386d6a3d2d73bab2536946db50737fd5508448fb4c42fd0c1.%7B%22id%22%3A%22fb9add50-c5e2-11e6-9b9b-df4f0b1b4c81%22%2C%22experiments%22%3A%22ig_android_reg_login_btn_active_state%2Cig_android_ci_opt_in_at_reg%2Cig_android_one_click_in_old_flow%2Cig_android_merge_fb_and_ci_friends_page%2Cig_android_non_fb_sso%2Cig_android_mandatory_full_name%2Cig_android_reg_enable_login_password_btn%2Cig_android_reg_phone_email_active_state%2Cig_android_analytics_data_loss%2Cig_fbns_blocked%2Cig_android_contact_point_triage%2Cig_android_reg_next_btn_active_state%2Cig_android_prefill_phone_number%2Cig_android_show_fb_social_context_in_nux%2Cig_android_one_tap_login_upsell%2Cig_fbns_push%2Cig_android_phoneid_sync_interval%22%7D`

Response received: 

`{"type":"default","status":400,"ok":false,"headers":{"map":{"pragma":["no-cache"],"set-cookie":["csrftoken=KADF4io2otLOsEELzrmzcfwwuYvTPv4d; expires=Mon, 18-Dec-2017 10:57:54 GMT; Max-Age=31449600; Path=/; secure"],"content-type":["application/json"],"content-language":["en"],"expires":["Sat, 01 Jan 2000 00:00:00 GMT"],"date":["Mon, 19 Dec 2016 10:57:54 GMT"],"content-length":["48"],"cache-control":["private, no-cache, no-store, must-revalidate"],"vary":["Cookie, Accept-Language"]}},"url":"https://i.instagram.com/api/v1/qe/sync/","_bodyInit":"{\"status\": \"fail\", \"message\": \"invalid request\"}","_bodyText":"{\"status\": \"fail\", \"message\": \"invalid request\"}"}`

**Comment by mgp25** [comment]
@berkayk use latest commit, works perfectly 

Regards

**Comment by berkayk** [comment]
I am using the latest version (the commit that is 8 days ago). Still getting the same response.
