### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by miladsalehi** [mgp25/Instagram-API#792]
Hi,
When i run library on server get this error:

```
FatalErrorException in Instagram.php line 25:
syntax error, unexpected '.', expecting ']'
```

server:
php version : PHP 5.6.29-1+deb.sury.org~trusty+1 (cli) 
ubuntu
laravel framwork
nginx

**Comment by mgp25** [comment]
Make sure you use latest commit from dev-master. Check line 25.

Not API issue

Regards

**Comment by fventurini** [comment]
having this problem me too
