### ISSUE TITLE
getSelfUserFeed prints RESPONSE

### ISSUE THREAD

**Issue by miladsalehi** [mgp25/Instagram-API#797]
Hi,

When i use getSelfUserFeed funtion,prints response like this:
GET:  feed/user/<id...>/?rank_token=36847703_33a1ab8d-95e6-4661-88aa-d7844d7fdcbf&ranked_content=true&max_id=&min_timestamp=
← 200 	 63.65kB

How can i disable this?

Thanks.

**Comment by miladsalehi** [comment]
I commented print functions in Debug.php file and problem solved.

**Comment by mgp25** [comment]
Did you even read the wiki????????
