### ISSUE TITLE
Why does it neutralize username/password -> device correlation?

### ISSUE THREAD

**Issue by MMrR0b0TT** [mgp25/Instagram-API#798]
I'm trying to understand and propose some improvements,and I'd like to know better why does you neutralize it?

// Neutralize username/password -> device correlation
https://github.com/mgp25/Instagram-API/blob/master/src/SignatureUtils.php#L16-L17

**Comment by mgp25** [comment]
You can use any other method

Regards

**Comment by MMrR0b0TT** [comment]
But is required? I guess...in instagram api, what is required?
