### ISSUE TITLE
challengeSMS Ability

### ISSUE THREAD

**Issue by mangledbottles** [mgp25/Instagram-API#799]
Hello @mgp25 ,
I am trying to test with the challengeSMS.php script but I see its CLI...
When I view on web server, it shows Instagram's website with a Website could not be found.
Is there a way to convert it to web server? You have built this whole source code from top to bottom, so anything to lead me on the right track will help!

Thanks :) 👍

**Comment by mgp25** [comment]
@mangledbottles as you have said, it is a cli tool, it is meant to be used with command line. Yes, but we dont provide that kind of support. Only API issues

Regards

**Comment by mangledbottles** [comment]
@mgp25 could you maybe set me in the right direction? I'm quite lost about it, even what to google as I've tried "Convert php CLI to php web server", but got not luck with that.

Thanks :)

**Comment by mgp25** [comment]
@matheuseduardo there is no such thing as "Convert php CLI to php web server". What you can do is to change the cli inputs and do any query (get, post..) to will the forms if thats what you are willing to do

**Comment by mangledbottles** [comment]
@mgp25  I am willing to code to make it work, what do you mean by change the CLI inputs and do any query? Sorry if all of this is going a bit off topic.. but I learn so much from this :D

Thanks :)
