### ISSUE TITLE
self follower list next cursor

### ISSUE THREAD

**Issue by hadivip** [mgp25/Instagram-API#8]
when i ask for the self followers list i got a big list with a next cursor String. how can i use this to get my next 200 users?

**Comment by mgp25** [comment]
I don't know, as i dont have more than 200 followers. You can use a proxy, get the request and sent it to me, and ill implement it in the API

Regards

**Comment by yazhog** [comment]
for example try:
```php 
getUserFollowers('507102035')
```

in end of answer:
```php
[page_size] => 200
[next_max_id] => AQD50_hBsWhS-cY-mr8wyoU99t9yxy0EJLi2R_jtPUoj3kjmiQbqJ0J6t129IB4j-_VtUjLMsqRme-7JV68Sm7t__YrFz2pbJ4xv12GXFklg-VGN36v5nkt0_ZpbPP5TmNt69Blh11uHHBoGb2W6HTINLNMIbHf3yUkqbykGm-YiAQ
```

**Comment by hadivip** [comment]
@mgp25 I've emailed you a user&pass for an I account that I use for testing porpose . it does have more that 1000 followers/following.

**Comment by hadivip** [comment]
@mgp25 I've tried to send you an email to inform you the account that I've emailed you is OK and you should try again with spelling. but i keep getting the error that you haven't received the email by Hotmail service
