### ISSUE TITLE
Ability to send photos as part of direct messages

### ISSUE THREAD

**Issue by zachlloyd** [mgp25/Instagram-API#800]
I don't believe this is currently supported.  Would be a great feature if possible.

Thanks

**Comment by mgp25** [comment]
Yes, its implemented

Regards

**Comment by zachlloyd** [comment]
What's the method?

I see direct_share, which takes a media_id, but that is different than attaching an image to a direct message because the media needs to already be posted.

i also see direct_message, but that doesn't take an image as an argument.

is there a method i'm missing?  ideally it would be an image argument on direct_message.

you can do this from the app, so i think the api exists on the instagram side.

thanks

**Comment by zachlloyd** [comment]
@mgp25 did you see this question?  i'm not convinced the api supports what i'm talking about.

thanks
