### ISSUE TITLE
sentry_block

### ISSUE THREAD

**Issue by MMrR0b0TT** [mgp25/Instagram-API#802]
Does anyone know about this error?
Can be something about spam, or normal issue in the Instagram?

https://i.instagram.com/api/v1/accounts/login/ - HTTP 400 {"status": "fail", "message": "Sorry, there was a problem with your request.", "error_type": "sentry_block"}

**Comment by mgp25** [comment]
Spam / bot detection, normal stuff

Regards

**Comment by MMrR0b0TT** [comment]
@mgp25 thanks...do you think that instagram has some restriction for IP/requests?

**Comment by mgp25** [comment]
Yes, but i wont give support in bypassing any of these measures Instagram has

**Comment by eli-pavlov** [comment]
@mgp25, thanks for code. How you want to give the support and how soon? It will be local markdown-page? I catch the blocks constantly with some of API methods.
