### ISSUE TITLE
How long time expire the Confirm access url?

### ISSUE THREAD

**Issue by MMrR0b0TT** [mgp25/Instagram-API#805]

**Comment by mgp25** [comment]
I dont know what confirm access url are you talking about. When you open an issue, make sure you post all details in it.

Regards

**Comment by MMrR0b0TT** [comment]
Sorry @mgp25, I was asking about the checkpoint_url. Do you know for how long it works?

**Comment by mgp25** [comment]
Nope, i guess it will last until the cookie expires, but you can try yourself checking and comparing with the http headers, if it has any code, maybe little time, but im not sure

Regards
