### ISSUE TITLE
API usage and opinions

### ISSUE THREAD

**Issue by mgp25** [mgp25/Instagram-API#806]
I want to ask you what do you think about the API, if you find it easy to use and what would you change or add.

Happy Xmas ☃️ 

_mgp25_

**Comment by mangledbottles** [comment]
Hi @mgp25 
Thank you so much for making this GitHub, I have learned so much from it and developing personal platforms to help me manage my social media. I think I might soon be able to reverse engineer an API!
When I first came across your GitHub, I was a bit confused, but after working with it I got the hang of it.
One thing that I would like to say is, that some people ask for things such as Instagram Views amount other things and you say no as thinking of spam, but not everyone here is here to spam.

Thanks again 👍 :)

**Comment by ping** [comment]
This is not specifically about the API, but I think it would be nice to have a CONTRIBUTING.md for devs who are interested to chip in. 

Previously the lib was simpler and it was relatively straightforward to add a new endpoint/method. Now each new endpoint requires the addition of a relevant "Response" class, and I'm not very certain what else.

It will be great if there is some simple guidance on the "right" way to add new endpoints. I wrote a private python lib that works similarly, and when I started out, your lib was a very useful reference. I've since expanded my lib to cover more endpoints, some of which aren't here yet. I would be happy to contibute back upstream if there is some basic guidance without wading through the code.

Thanks for all your work, and Happy 2017 🎉

**Comment by mgp25** [comment]
@ping https://github.com/mgp25/Instagram-API/blob/master/CONTRIBUTING.md

**Comment by ovs1** [comment]
I would love to have some more examples with the new responses how to use the getters and a list of the getters to obtain data from the objects.

And i would love to see some updates on checkpoints but i know you said you wont update them anymore.

So more examples would be awesome! Maybe some example how to grab success response or failed response. Part from that its very straight forward.

Happy 2017!

**Comment by maximTartachnik** [comment]
Hi there!!!
First of all thank you for your work. Its great!!!!
Maybe its would be great for do some investigating in "Direct Messages".
AFAIK in the `getv2Inbox()` respose we see a WSS url.
Maybe we can connect to inbox via WebSockets?

**Comment by ping** [comment]
@mgp25 Thanks for the guide, it was helpful and I managed to send in a few PRs.

I have a question about the "getters" when it's an associative array, e.g. for endpoint ``feed/reels_media/ `` which takes a ``user_ids`` post param (comma-separated list of user ids), and in turn returns reels for each user specified.

Response:
![igapi_feedreelsmedia](https://cloud.githubusercontent.com/assets/104607/21537634/45eba06c-cdcf-11e6-9b0b-6cf8df6bcbb5.png)

``$reels`` is actually an associative array (key=user_id) of ``Reel`` objects (created in #817), but I'm not sure how to declare it accordingly.

**Comment by mgp25** [comment]
@ping send a PR with the endpoint and response, and i test it, since im not sure how to do it, after i solve it, i'll post it here

**Comment by ping** [comment]
@mgp25 Submitted as #818

**Comment by mgp25** [comment]
@ping that kind of associative arrays works too with

```php
    /**
     * @var Reel[]
     */
    public $reels;
```

Just merged the commit, check it, and let me now if its okay

Regards

**Comment by mgp25** [comment]
@ovs1 i'll add more examples in the next couple days

@maximTartachnik that could be a great future, but im already looking for new projects and i dont want to spent too much time on that, maybe other API user can help doing that feature

Regards

**Comment by maximTartachnik** [comment]
@mgp25 I was trying to do this, but no luck :( 
I think I did something wrong with capturing and unpinning SSL.
Maybe you can share with us the a "secret info" about how you capture requests :)

**Comment by ping** [comment]
@mgp25 Works 👍

**Comment by Taytus** [comment]
I think you did a great job and I thank you for all the time spent developing this.
Instagram is adding new functionalities all the time, specially the last couple of months. Likes, story, etc. And I know you might not have the time to keep pace with all these features/endpoints. If I had a CLEAR tutorial about how to capture endpoints/requests I could (and I bet others too) help adding new functionality.
To me, what @mangledbottles is not clear at all, sorry mate.
A simple youtube tutorial would be fantastic.

**Comment by mgp25** [comment]
@Taytus your argument is invalid, examples and wiki provide all the documentation required. If you need more, then you need to research in your own way, there is a lot of info in google

**Comment by Taytus** [comment]
@mgp25 just because you disagree doesn't make it invalid. In this very same thread you can see other people having issues capturing endpoints. 

I think you are being extra defensive, and I don't understand why.

Anyway, thank you.

**Comment by joseflorido** [comment]
@mgp25 Thanks again for this project and all your work!

I think a good idea maybe to start a Google Group or similar where API users can offer support and help to each other and we can all discuss about the API, usage strategies, ask questions, etc. I think the issues section of github is not a great place to ask for help.

Also, by having some support group you will take some of the burden of helping people about how to use the API and how to fix their code from you and let the rest of the community help.

Just my 2 cents.

**Comment by mgp25** [comment]
@Taytus im not saying that i disagree. This repository is about Instagram API, for other tools like proxies, a lot of guides can be found over the internet searching in Google, even in Youtube. Thats why here is not explained, because out there, are a lot of nice guides

**Comment by mgp25** [comment]
@ovs1 i just added an example on how to use getters https://github.com/mgp25/Instagram-API/commit/817febbdaec8b3000e223bc6a7f99d462dda7ed0
