### ISSUE TITLE
syncFromAddress

### ISSUE THREAD

**Issue by macr243** [mgp25/Instagram-API#807]
Hello, the last week I was using an old version of this project, but when I update to the latest version ocurred a problem, when I was calling syncFromAdressBook returns some like this:
```php
array
(
    "status" => "ok",
    "items" => array
     (
        0 => array
        (
            "large_urls" => array
             (
             ),
             "caption" => "",
             "user" => array
              (
                  "username" => "username",
                  "has_anonymous_profile_picture" => "",
                  "profile_pic_url" => "http://blabla.com",
                  "profile_pic_id" => "1...2",
                  "full_name" => "Jonh",
                  "pk" => "3...3",
                  "is_verified" => "",
                  "is_private" => ""
             ), 
            "thumbnail_urls" => array
             (
             )
        )
    )
);
```
and now with the same code returns this:
```php
array
(
    "status" => "ok",
    "items" => array
    (
    )
);
```

**Comment by mangledbottles** [comment]
I just checked the endpoint from iOS App and it returns the old ("working") version you had.
What parameters are you sending & send full debug

**Comment by macr243** [comment]
that's my parameters
```php
$contacts = array( 
    array(
         "phone_numbers" => array("34123456789"),
         "first_name" => "somebbody",
         "email_addresses" => array('somebody@example.com')
     )
);
```

**Comment by mgp25** [comment]
@macr243 check latest commit: https://github.com/mgp25/Instagram-API/commit/8b927f959a39ef5f775e571f36319298aed4caba

Let me know if that worked

Regards

**Comment by macr243** [comment]
POST:  address_book/link/?include=extra_display_name,thumbnails
DATA: contacts=[{"phone_numbers":["34123456789"],"first_name":"Jonh","email_addresses":["somebody@example.com"]},{"phone_numbers":["123456789111"],"first_name":"Charles","email_addresses":["some@example.com"]}]
← 200 	 29B
RESPONSE: {"status": "ok", "items": []}
```php
InstagramAPI\AddressBookResponse Object
(
    [items] => Array
        (
        )

    [status] => ok
    [message] => 
    [fullResponse] => stdClass Object
        (
            [status] => ok
            [items] => Array
                (
                )

        )

)
```
That's the result and some debugs
Regards

**Comment by mgp25** [comment]
@macr243 seems okay then, perfect!

Regards

**Comment by Nazarii76** [comment]
how to call syncFromAdressBook


`PHP Fatal error:  Uncaught Error: Call to undefined method InstagramAPI\Instagram::syncFromAdressBook() in C:\xampp\htdocs\King.php:32
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\King.php on line 32`
