### ISSUE TITLE
searchLocation video upload

### ISSUE THREAD

**Issue by golches** [mgp25/Instagram-API#809]
search location work only for photo upload even if the picture doesn't appear after upload, but for video upload searchLocation doesn't work, even when i try to add it to photoupload of the video configuration but doesn't work

**Comment by mgp25** [comment]
Im not sure what do you mean, but https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1028 is for already uploaded media

Regards

**Comment by golches** [comment]
search location not work with upload video

**Comment by mgp25** [comment]
@golches ill check

**Comment by golches** [comment]
i am waiting please
