### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by tantita** [mgp25/Instagram-API#820]
I am using the latest commit and whenever i try to login
```
$ig = new InstagramAPI\Instagram();
$ig->setUser('username','password');
$ig->login()
```
I get the following error
PHP warning:  Missing argument 1 for InstagramAPI\ChallengeResponse::__construct(), called in /home/ajibola/php/igbots/vendor/mgp25/instagram-php/src/Instagram.php on line 138 and defined in /home/ajibola/php/igbots/vendor/mgp25/instagram-php/src/http/Response/ChallengeResponse.php on line 9

**Comment by danleyb2** [comment]
You are able to login, this is just a PHP warning, try setting `debug = true` and see
created a fix [PR](https://github.com/mgp25/Instagram-API/pull/822)
