### ISSUE TITLE
Login failed need upgrade

### ISSUE THREAD

**Issue by putraxor** [mgp25/Instagram-API#821]
I write similar code in kotlin but it raise error which is need to upgrade app. The user-agent of http client has been change to Instagram app user-agent:
`Instagram ${KEY.APP_VERSION} Android (22/6.0.1; 424dpi; 1080x1920; LGE; LG-H779; aka; en_US)`
I also use this signature version
```
    val SIG_KEY = "5ad7d6f013666cc93c88fc8af940348bd067b68f0dce3c85122a923f4f74b251";
    val SIG_VERSION = "4"
    val APP_VERSION = "10.3.2"
```
Do you know what's wrong with my code?

**Comment by mgp25** [comment]
Make sure signature, request type and headers are equal. If you change cURL options, you can set verbose to true and check all the response and compare it with yours

Regards!
