### ISSUE TITLE
add source.

### ISSUE THREAD

**Issue by mjxaone** [mgp25/Instagram-API#823]
If possible, I would appreciate it if you add it.
Thank you.

There is no problem without this code.
This code is **Option**.

But I am using it.

ps. Sorry.. i don't know **git pull request** ... ;)

=====================
**change comment function**

```php
function comment($mediaId, $commentText)
{
  return $this->request("media/$mediaId/comment/")
  ->addPost('user_breadcrumb', generateUserBreadcrumb(strlen($commentText)))
  ->addPost('idempotence_token', generateUUID(true))
  ->addPost('_uuid', $this->uuid)
  ->addPost('_uid', $this->username_id)
  ->addPost('_csrftoken', $this->token)
  ->addPost('comment_text', $commentText)
  ->addPost('containermodule', "comments_feed_timeline")
  ->getResponse(new CommentResponse());
}
```

=====================

=====================
**add function**
```php
function generateUserBreadcrumb($size) {
  $key = 'iN4$aGr0m';
  $date = new DateTime ();
  
  // typing time
  $term = 3000 + $size * 2000;
  
  // android EditText change event ouccr count
  $text_change_event_count = $size / 3;
  if ($text_change_event_count == 0)
    $text_change_event_count = 1;
  
  // generate typing data
  $data = $size . " " . $term . " " . $text_change_event_count . " " . $date->getTimestamp () . "\n";
  
  // echo $data;
  return base64_encode ( hash_hmac ( "sha256", $data, $key, true ) ) . base64_encode ( $data ) . "\n";
}
```

=====================

**Comment by mgp25** [comment]
@mjxaone can you explain what is the change + the function + that key?

Regards

**Comment by mjxaone** [comment]
get code Reverse engine.

Applied to the latest version of Instagram.
It is expected that user experience data collection purpose.
It seems to be the purpose of analyzing user's comment input time.

ps.
Although there is no problem in operation without it,
I liked perfection and applied it.

**Comment by mgp25** [comment]
@mjxaone good to know. Im going to add it now

Thanks

Regards

**Comment by mjxaone** [comment]
user_breadcrumb is 
data = (comment size) + (text input microsecond) + (android "EditTextView" Text change event occurred count)

user_breadcrumb = base64(sha256(data, 'iN4$aGr0m')) + base64(data);

**Comment by ping** [comment]
I think this line needs to be fixed https://github.com/mgp25/Instagram-API/commit/4564de474adb405f6eec5dfe5dee3ee91a33f38e#diff-627375c8f624282d6cfe666001988e42R18 because I'm seeing InstagramAPI\DateTime class not found error and also warnings if timezone is not specified.

```php
$date = new \DateTime('UTC');
```

But even with the php errors resolved, IG is rejecting the api call that contains the new params.

```
RESPONSE: {"status": "fail", "message": "Sorry, the comment data may have been corrupted."}

InstagramAPI\CommentResponse : Sorry, the comment data may have been corrupted.
```

**Comment by mgp25** [comment]
@ping i havent tested it, my fault, let me check
