### ISSUE TITLE
not avalible details of likedmedia

### ISSUE THREAD

**Issue by irshad9998** [mgp25/Instagram-API#827]
i have called this `$i->getLikedMedia($maxid = $next_id);` method not showing any details

`foreach ($helper->getItems() as $follower) {
                $media_type = $follower->getMediaType();
}`
here is error ouccurs

> Fatal error: Call to a member function getItems() on array in /home/irshadmemon/api.safehandsecurity.in/instaCleaner/test/likedmedia.php on line 19

**Comment by mgp25** [comment]
@irshad9998 is not an API issue. Check your code, you are calling `getItems()` on array, an instead you should call it in the object.

Regards

**Comment by irshad9998** [comment]
How can i do this?
