### ISSUE TITLE
Instagram Checkpoint Issue in sending photo

### ISSUE THREAD

**Issue by codewp** [mgp25/Instagram-API#828]
I will get below response from Instagram when I want to send post to Instagram via my server.
`POST:  qe/sync/
DATA: ig_sig_key_version=4&signed_body=0b8e6ccf6be7765a657f661ab5c4a7ba436760008abe1912ed5c91e57ff140d8.{"id":"7a30a032-0c96-4bba-9eb2-66690e95d0c5","experiments":"ig_android_reg_login_btn_active_state,ig_android_ci_opt_in_at_reg,ig_android_one_click_in_old_flow,ig_android_merge_fb_and_ci_friends_page,ig_android_non_fb_sso,ig_android_mandatory_full_name,ig_android_reg_enable_login_password_btn,ig_android_reg_phone_email_active_state,ig_android_analytics_data_loss,ig_fbns_blocked,ig_android_contact_point_triage,ig_android_reg_next_btn_active_state,ig_android_prefill_phone_number,ig_android_show_fb_social_context_in_nux,ig_android_one_tap_login_upsell,ig_fbns_push,ig_android_phoneid_sync_interval"}
← 200 	 1.37kB
RESPONSE: {"status": "ok", "experiments": [{"params": [{"name": "button_filled", "value": "false"}, {"name": "outline_opaque", "value": "false"}, {"name": "button_filled_fade_in", "value": "false"}], "group": "control_20160830", "name": "ig_android_reg_login_btn_active_state"}, {"params": [{"name": "opt_in_at_username_page", "value": "2"}], "group": "test_button_at_username_20161116", "name": "ig_android_ci_opt_in_at_reg"}, {"params": [{"name": "support_non_fb_sso", "value": "true"}], "group": "test_20160629", "name": "ig_android_non_fb_sso"}, {"params": [{"name": "is_enabled", "value": "enabled"}, {"name": "phone_first", "value": "enabled"}], "group": "test_with_phone_first_20160322", "name": "ig_android_contact_point_triage"}, {"params": [{"name": "button_filled", "value": "false"}, {"name": "outline_opaque", "value": "false"}, {"name": "button_filled_fade_in", "value": "true"}], "group": "filled_fade_in_20160830", "name": "ig_android_reg_next_btn_active_state"}, {"params": [{"name": "prefill_phone", "value": "true"}], "group": "launch", "name": "ig_android_prefill_phone_number"}, {"params": [{"name": "show_context", "value": "true"}], "group": "control_20160713", "name": "ig_android_show_fb_social_context_in_nux"}, {"params": [{"name": "fully_synced", "value": "604800"}, {"name": "partially_synced", "value": "21600"}], "group": "test_6_hours", "name": "ig_android_phoneid_sync_interval"}]}

GET:  si/fetch_headers?challenge_type=signup&guid=0b9b454db1594ee5872f350b6ac89b10
← 200 	 16B
RESPONSE: {"status": "ok"}

POST:  accounts/login/
DATA: ig_sig_key_version=4&signed_body=1c4c5e52fc3f23549a969472ac0378c4936fb63016d736f0bcf05ee81694d283.{"phone_id":"8cee662d-af6f-41d5-9554-acfaa29daeac","_csrftoken":"Set-Cookie: csrftoken=2SiM5od33i","username":"*******","guid":"****","device_id":"android-bf61966b0dfec13d","password":"******","login_attempt_count":0}
← 400 	 265B
RESPONSE: {"status": "fail", "lock": true, "message": "checkpoint_required", "error_type": "checkpoint_logged_out", "checkpoint_url": "https://i.instagram.com/integrity/checkpoint/checkpoint_logged_out_main/4292923221/Pjw6gHYM9D/?next=instagram%3A%2F%2Fcheckpoint%2Fdismiss"}`

But when I test it in my local it sends photos successfully.

Also I should say that my server is in https protocol but in local I use http protocol.

I tried to solving this issue by verify me but after I verified and send again a photo I get same error again.

Please let me know how can I fix this issue?

**Comment by mgp25** [comment]
@codewp you need to login via browser or use checkpoint file from examples. That will pass the checkpoint from Instagram, is just a security measure they have.

Regards

**Comment by codewp** [comment]
@mgp25 

Are there any other solutions for it? because I verify my accounts from browser, but when I try to send photo to Instagram via my app on the server Instagram locks my account and it did not sent photo to Instagram and above error returned from request.

Best Regards.
