### ISSUE TITLE
hello - upload video err

### ISSUE THREAD

**Issue by Arsintorabi** [mgp25/Instagram-API#829]
Upload Started ...
string(16) "0-426111/1704451" string(16) "0-852223/1704451" string(17) "0-1278335/1704451" string(70) "{"status": "ok", "result": "deprecated", "configure_delay_ms": "6500"}" array(2) { ["status"]=> string(4) "fail" ["message"]=> string(39) "Other media configure error: yEmZkUpAj4" }

**Comment by mgp25** [comment]
@Arsintorabi you are not uploading the video in the right format http://support.schedugr.am/support/solutions/articles/1000201572-instagram-video-specifications

Regards

**Comment by jonatanfroes** [comment]
@mgp25 @Arsintorabi, 
I got the same error in only one IG account: [@nerddofuturo](https://www.instagram.com/nerddofuturo)

- I can't upload any video to this IG through API, but I can upload using Instagram app;
- The same Vídeo works fine in any other IG.

Sometimes Strange things happens :fearful:

**Comment by Arsintorabi** [comment]
need ffmpeg??

**Comment by jonatanfroes** [comment]
@mgp25  @Arsintorabi 
I got this error in only one IG account: [@nerddofuturo](https://www.instagram.com/nerddofuturo/):

- I can't upload any video through this API in this account, but it works fine on instagram app;
- I can upload the same video to any other IG account using this API;

Strangers things :fearful:
