### ISSUE TITLE
Error Syntax

### ISSUE THREAD

**Issue by rizkihape** [mgp25/Instagram-API#83]
Hello, thanks for this script.
i have a problem and i can't fix this.

how to fix this problem
**Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\Instagram\Oauth\Instagram.php on line 39**
`$this->uuid = $this->generateUUID(true);
      $this->device_id = 'android-'.str_split(md5(rand(1000, 9999)), 16)[rand(0, 1)];`

Thanks :)

**Comment by mgp25** [comment]
Use php 5.6

**Comment by rizkihape** [comment]
thanks its run, but how to get ig_sig_key ?
please help me

**Comment by mgp25** [comment]
check the wiki
