### ISSUE TITLE
Error adding location

### ISSUE THREAD

**Issue by SubodhDahal** [mgp25/Instagram-API#832]
I get an `Call to undefined method stdClass::getExternalIdSource()` error while passing `getVenues()[2]` as the last parameter to `uploadPhoto`. Following is the code I used:

    ...
    $locations = $i->searchLocation($input['location']['latitude'], $input['location']['longitude']);
    $i->uploadPhoto($photo, $caption, null, null, $locations->getVenues()[2]);

The method `$locations->getVenues()[2]` does contain a valid `stdClass` object.

**Comment by mgp25** [comment]
@SubodhDahal `venues` object requires to be added in order to make this work

Regards

**Comment by SubodhDahal** [comment]
I'm sorry I don't get you.
Could you please provide a basic example for it?
Thanks
