### ISSUE TITLE
Error 500?

### ISSUE THREAD

**Issue by jztflokzz** [mgp25/Instagram-API#834]
I'm trying to make a PHP script and access it from browser, but its just giving me error 500.

CODE:
<?php
require("/var/www/html/vendor/autoload.php");
require("/var/www/html/Instagram-API/src/Instagram.php")
/////// CONFIG ///////
$username = $_GET["username"];
$password = $_GET["password"];
$debug = false;

$photo = '';     // path to the photo
$caption = '';     // caption
//////////////////////

$i = new \InstagramAPI\Instagram($debug);

$i->setUser($username, $password);

try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}

try {
    $i->uploadPhoto($photo, $caption);
} catch (Exception $e) {
    echo $e->getMessage();
}

**Comment by mgp25** [comment]
no API issue, check your webserver configuration, something is wrong there

Regards
