### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by jztflokzz** [mgp25/Instagram-API#835]
Recieving http error 500...
code: 
http://pastebin.com/k2B5iyKb
Try for yourself: http://5.196.197.149/Instagram-API/uploadphoto.php

**Comment by mgp25** [comment]
https://github.com/mgp25/Instagram-API/issues/834#issuecomment-270732016

**Comment by jztflokzz** [comment]
I'm getting a different error now.. 
PHP Parse error:  syntax error, unexpected '$username' (T_VARIABLE) in /var/www/html/Instagram-API/uploadphoto.php on line 5

**Comment by mgp25** [comment]
@jztflokzz do you know php? Do you know what `$argv` is used for?

I see you are new to PHP, i would recommend you this manual as starter: https://secure.php.net/docs.php

`$argv` is only valid when using the script in CLI (Command Line Interface), better add the username directly as a string.

By the way, you are now using `$argv`, before you were using `$_GET`, if you were using `$_GET` you are not passing the correct parameters via url to the script, for example: `?username=whatever&password=secret`

Regards
