### ISSUE TITLE
No response from server, connection or configure error

### ISSUE THREAD

**Issue by Kruizi** [mgp25/Instagram-API#839]
Hey.
who knows what went wrong?
![2017-01-06_13-42-49](https://cloud.githubusercontent.com/assets/11752811/21709746/0b425ca6-d416-11e6-8015-8646d25d6f25.png)

**Comment by Kruizi** [comment]
![2017-01-06_13-47-05](https://cloud.githubusercontent.com/assets/11752811/21709823/a379ecb4-d416-11e6-84c1-051a3ea28aa3.png)

**Comment by mgp25** [comment]
@Kruizi exactly what the error says, connection issue,  Instagram is refusing your requests, thats why you get null responses. The second error comes from the first one. 

Regards

**Comment by AntonMedvedev** [comment]
Hi, video don't uploaded, but photo uploaded succesfuly. This is Problem in Instagram server side?

**Comment by Virr** [comment]
The same error. Upload photos works, but getUserFollowers returns:
"No response from server, connection or configure error". 

Any suggestions?

**Comment by Virr** [comment]
I resolved problem, I pass instagram user's name, not ID.

**Comment by lazyboy1801** [comment]
I also encounter the same error.
Upload successful photo, but upload video error, help me !

**Comment by lazyboy1801** [comment]
@Virr Can you tell me more about how to fix it. I also have a similar error. thank you !
