### ISSUE TITLE
Username not available always

### ISSUE THREAD

**Issue by infoquestsolutions** [mgp25/Instagram-API#84]
Hi 

It shows me username not available every time . Here are logs and i am using windows .

Username: iamLegend1984
funcREQUEST: users/check_username/
DATA: ig_sig_key_version=4&signed_body=e3ae4207792ffb06ffe3f580af6223d6a63b673915b14d31ce060f64717e6782.%7B%22_uuid%22%3A%220620da7b-595d-483b-9529-4bf53df4e72e%22%2C%22username%22%3A%22iamLegend1984%22%2C%22_csrftoken%22%3A%22missing%22%7D
RESPONSE:

Username iamLegend1984 not available, try with another one

Thanks

**Comment by mgp25** [comment]
@infoquestsolutions that means that username is already taken...

_sigh..._

**Comment by infoquestsolutions** [comment]
Check url https://www.instagram.com/iamLegend1984124/ as this is not taken by anyone but still same results. I have gd and curl enabled on windows if anything else required ?

Username: iamLegend1984124
 funcREQUEST: users/check_username/
DATA: ig_sig_key_version=4&signed_body=a37eee5f5367ed9e78f92e591f93747a675993e6db338af349bc19d612176207.%7B%22_uuid%22%3A%220620da7b-595d-483b-9529-4bf53df4e72e%22%2C%22username%22%3A%22iamLegend1984124%22%2C%22_csrftoken%22%3A%22missing%22%7D
RESPONSE:

Username iamLegend1984124 not available, try with another one

**Comment by mgp25** [comment]
@infoquestsolutions then its very possible that Instagram has flagged your account because of illicit activities with this API

**Comment by infoquestsolutions** [comment]
I am trying to create account without login in to system, i am getting empty response any ideas around it.

**Comment by dfanara** [comment]
I was having issues with that, but luckily I had a /64 subnet of IPv6
addresses on my vps. You can specify the outbound IP address in the curl
request using the CURLOPT_INTERFACE setting. Changing your outbound address
will make instagram see you as a different user :P. Proxies also work, but
when you have 18 quadrillion IP addresses, might as well use those too.

**Comment by infoquestsolutions** [comment]
@dfanara I am not very well versed with php. So please explain a bit more .

And tried to run on another computer with another Internet connection  result was same.

@mgp25  can you look at it please may something was updated.
