### ISSUE TITLE
Server connection

### ISSUE THREAD

**Issue by snippet** [mgp25/Instagram-API#842]
I cant conncect in server

`POST: qe/sync/ DATA: ig_sig_key_version=4&signed_body=a51f9d7ef3f0c5cc7657eb0f5fa9c416fcedaf997c386adba5220bc530341548.{"id":"10757583-8176-4500-ad12-15323d17680c","experiments":"ig_android_reg_login_btn_active_state,ig_android_ci_opt_in_at_reg,ig_android_one_click_in_old_flow,ig_android_merge_fb_and_ci_friends_page,ig_android_non_fb_sso,ig_android_mandatory_full_name,ig_android_reg_enable_login_password_btn,ig_android_reg_phone_email_active_state,ig_android_analytics_data_loss,ig_fbns_blocked,ig_android_contact_point_triage,ig_android_reg_next_btn_active_state,ig_android_prefill_phone_number,ig_android_show_fb_social_context_in_nux,ig_android_one_tap_login_upsell,ig_fbns_push,ig_android_phoneid_sync_interval"} ← 0 0B RESPONSE: something went wrong No response from server, connection or configure error`

Why does this happen?
I need use a proxy?

**Comment by mgp25** [comment]
@snippet Instagram is refusing your requests. Your IP its likely to be flagged. Try from other IP/network/Configuration

Regards
