### ISSUE TITLE
login_required

### ISSUE THREAD

**Issue by Multiby7e** [mgp25/Instagram-API#844]
Good morning, I am having some problems retrieving the followers list. I already checked for similar issues, but the problem is I'm not using php and it's not the same thing, I am using C#.
I tried both GET and POST requests, but I keep getting this response:
**_{"status": "fail", "message": "login_required"}_**

**_C# code:_**
`byte[] bytes = Encoding.UTF8.GetBytes("");
HttpWebRequest wRequest = (HttpWebRequest)WebRequest.Create("http://i.instagram.com/api/v1/friendships/1612128459/followers/?rank_token=1315117990_" + Global._uuid);
            WebHeaderCollection wHeaderCollection = wRequest.Headers;
            wRequest.Method = "POST";
            wRequest.Host = "i.instagram.com";
            wRequest.UserAgent = "Instagram 8.4.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)";
            wRequest.Accept = "*/*";
            wRequest.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
            wRequest.KeepAlive = false;
            wRequest.CookieContainer = Cookies;
            wHeaderCollection.Add("Cookie2", "$Version=1");
            wHeaderCollection.Add("Accept-Language", "en-US");
            Stream wStream = wRequest.GetRequestStream();
            wStream.Write(bytes, 0, bytes.Length);
            wStream.Close();
            HttpWebResponse wResponse = (HttpWebResponse)wRequest.GetResponse();
            StreamReader sReader = new StreamReader(wResponse.GetResponseStream());
            string Response = sReader.ReadToEnd();`
**Pastebin:** http://pastebin.com/rrJ5S3wd

**_Fiddler request:_**
`POST http://i.instagram.com/api/v1/friendships/1612128459/followers/?rank_token=1315117990_whwkm4zs-ik3g-5k5h-bxzk-7713usz2ao6a HTTP/1.1
User-Agent: Instagram 8.4.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)
Accept: */*
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie2: $Version=1
Accept-Language: en-US
Host: i.instagram.com
Cookie: ds_user_id=1315117990; mid=WHI9IgABAAFN9DYnriNKedntAqag; ds_user=moha_rekik
Content-Length: 0
Connection: Close`
**Pastebin:** http://pastebin.com/Jr5gFsLK

It's been two days since I'm trying to solve it, thank you in advance for any help!

**Comment by mgp25** [comment]
@Multiby7e hello, this is only for Instagram API issues using the code we provide.

```json
 {"status": "fail", "message": "login_required"}
```

Means you need to login first.

Regards
