### ISSUE TITLE
The login takes too long

### ISSUE THREAD

**Issue by miladsalehi** [mgp25/Instagram-API#846]
Hi,
When is use login function,that takes too long to respond!

>   $debug = false;
        $i = new Instagram($debug);
        $i->setUser($user_name, $password);
        $login_obj = $i->login();

How can i fix that?
Thanks.

**Comment by BTopbas** [comment]
I have same problem. I have a ssd vps 2gb ram. I run only this. No websites or anything. Querys take too long time. All time i get 504 gateway timeout. Get user id from username and follow user always 504.

**Comment by mgp25** [comment]
It is **NOT** an API issue.

Regards

**Comment by miladsalehi** [comment]
@mgp25 Can you help us what is that for?how we can fix that?
Thanks

**Comment by BTopbas** [comment]
I change vps server and everything seems works perfectly. Try localhost. I think my problem is using OVH server.

**Comment by miladsalehi** [comment]
On localhost i have problem too.trying to solve...

**Comment by miladsalehi** [comment]
@BTopbas Login time fixed?

**Comment by beshoo1** [comment]
it has to take long time on first login , but after that it will use saved session

**Comment by mgp25** [comment]
sigh... login just takes 1 second and this is NOT an API issue

**Comment by beshoo1** [comment]
@mgp25 , sorry i forgot to say , if server is outside of USA.

**Comment by mgp25** [comment]
@beshoo1 im outside of USA...

**Comment by beshoo1** [comment]
Then , there is something wrong !
you remember that i reported about the login speed , you told me there is a misconfiguration with my server networks , and there is not !

but i note some delay in the ping output

`64 bytes from instagram-p3-shv-01-mia1.fbcdn.net (31.13.73.52): icmp_seq=1 ttl=82 **time=102 ms**` 

But when i ping google.com

`64 bytes from ams16s30-in-f14.1e100.net (172.217.17.78): icmp_seq=1 ttl=56 **time=0.696 ms**
`


so i am not sure , you side it take 1 second on a fresh first time login ,  i test this scenario on 10 servers around the words but not USA  , all reported 10 ~ 15 sec login time , but after this . when i use saved session files , login take just 1 sec . 

I am not sure what the special network setting you may have in your network .

it will be kind of you if you share these settings

**Comment by miladsalehi** [comment]
Hi,
I have pinged instagram and google and the result is:
Instagram ping:
64 bytes from instagram-p3-shv-01-mia1.fbcdn.net (31.13.73.52): icmp_seq=4 ttl=81 time=280 ms
google ping:
64 bytes from fra16s08-in-f14.1e100.net (172.217.16.206): icmp_seq=5 ttl=49 time=130 ms
*Server is outside of USA.

@mgp25 please if there is any special network setting share that.

Thanks

**Comment by miladsalehi** [comment]
I have implemented Instagram API in android client side(java) and my problem solved.

**Comment by wlisesrivas** [comment]
I had the same problem, this is related to **guzzle** library. On linux, probably you miss cUrl for PHP.
> sudo apt-get install php7.0-curl
Hope this will help you.
