### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by ilyapt** [mgp25/Instagram-API#849]
I've tried to use Instagram-API with proxy and saw following:

Where I set user before proxy its worked fine
```
require("vendor/autoload.php");
$instagram = new \InstagramAPI\Instagram(true,false);

$instagram->setUser($user, $password);
$instagram->setProxy('http://217.106.239.125:10241');
$instagram->login();
```
```
# netstat -na|grep ESTABLISHED
tcp        0      0 172.17.0.7:38046        217.106.239.125:10241     ESTABLISHED
```

In case where I set proxy first its worked **without proxy**
```
require("vendor/autoload.php");
$instagram = new \InstagramAPI\Instagram(true,false);

$instagram->setProxy('http://217.106.239.125:10241');
$instagram->setUser($user, $password);
$instagram->login();
```
```
# netstat -na|grep ESTABLISHED
tcp        0      0 172.17.0.7:59434        31.13.93.52:443         ESTABLISHED
```
Its going directly to instagram server.

If you cant fix this issue fast maybe add info to the wiki.
I think here was same issue https://github.com/mgp25/Instagram-API/issues/789 

Thanks for your job.

**Comment by DragonStar01** [comment]
yeah `$instagram->setProxy(');`
Doesn't work for me too.
It send request without using proxy

**Comment by ovs1** [comment]
You need to send the port as INT
$instagram->setProxy(string,int);

If i don't recall wrong.

**Comment by mgp25** [comment]
Please check the code before opening an issue: https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L104

Regards

**Comment by ewwink** [comment]
sorry for reopening this issue, here the fix
in `Instagram.php` remove `http `from `$this->http->proxy['xxx']`
in `HttpInterface.php` change `$this->proxy` to `$this->parent->proxy`

**Comment by LanchaBasualdo** [comment]
@ilyapt @mgp25 @ewwink 
guys, what are the pross of setting up the proxy?

**Comment by mrrradical899** [comment]
Hi i used it too but it made an error

> I've tried to use Instagram-API with proxy and saw following:
> 
> Where I set user before proxy its worked fine
> 
> ```
> require("vendor/autoload.php");
> $instagram = new \InstagramAPI\Instagram(true,false);
> 
> $instagram->setUser($user, $password);
> $instagram->setProxy('http://217.106.239.125:10241');
> $instagram->login();
> ```
> 
> ```
> # netstat -na|grep ESTABLISHED
> tcp        0      0 172.17.0.7:38046        217.106.239.125:10241     ESTABLISHED
> ```
> 
> In case where I set proxy first its worked **without proxy**
> 
> ```
> require("vendor/autoload.php");
> $instagram = new \InstagramAPI\Instagram(true,false);
> 
> $instagram->setProxy('http://217.106.239.125:10241');
> $instagram->setUser($user, $password);
> $instagram->login();
> ```
> 
> ```
> # netstat -na|grep ESTABLISHED
> tcp        0      0 172.17.0.7:59434        31.13.93.52:443         ESTABLISHED
> ```
> 
> Its going directly to instagram server.
> 
> If you cant fix this issue fast maybe add info to the wiki.
> I think here was same issue #789
> 
> Thanks for your job.

include 'instagram.class.php';

$username = '';   // your username
$password = '';   // your password
//==========================================================
$insta = new instagram();
$insta->setProxy('http://217.106.239.125:10241');
$response = $insta->Login($username, $password);

Please specify the proxy setting function from your file require ("vendor / autoload.php");
Send me thanks
