### ISSUE TITLE
Add Link To Wiki

### ISSUE THREAD

**Issue by dfanara** [mgp25/Instagram-API#85]
I think that this link would be extremely useful for anyone who is not positive about how to view the HTTPS traffic between the device and Instagram. https://medium.com/@rotxed/how-to-debug-http-s-traffic-on-android-7fbe5d2a34#.hco4frh7a I think it would be useful to add to the Wiki for future reference.

**Comment by djstanley** [comment]
Does this successfully remove ssl certificate pinning? Have you tested this with instagram? When I've tried in the past the traffic remains encrypted

**Comment by mgp25** [comment]
Not required, not API related.

Regards
