### ISSUE TITLE
getHashtagFeed : not "top posts" but "most recent"

### ISSUE THREAD

**Issue by kboirel** [mgp25/Instagram-API#850]
Hello,

I would like to fetch recent medias with an hashtag, but I only can have "Top posts", in other words the 9 first. (Excuse my english)

I'm sorry but I didn't find answers in the issues section ...

Maybe I have to "play" with $maxid, but I don't know how...

This is what I did:

```
$hashtagString = "fitfrenchies";
$feed = $i->getHashtagFeed($hashtagString, $maxid = null);
$items = $feed->ranked_items;

$tableFeed = [];

$o = 0;
for ($o; $o < 10; $o++){
    $tableFeed[] = $items[$o]->id;
}

var_dump($tableFeed);
```

Thanks in advance

**Comment by mangledbottles** [comment]
Var_dump($items) and send it here
I just checked the enpoint requests with my phone and it should be ok

**Comment by joseflorido** [comment]
This works for me:

$taggedMedia = $i->getHashtagFeed($tag);
$recentTaggedMedia = $taggedMedia->getItems();
$topTaggedMedia = $taggedMedia->getRankedItems();

Some tags may not have recent items or may not have top items, you need to
check.

**Comment by kboirel** [comment]
Oh yes ! I was wrong by trying to get "ranked items" that's my fault sorry !
Thank you very much !
