### ISSUE TITLE
IP-related transcode timeout

### ISSUE THREAD

**Issue by romalytvynenko** [mgp25/Instagram-API#851]
Good day! First of all I want to thank you for the great library!

While using this library I've faced interesting issue. I have 2 accounts. One is for testing and other one is my personal Instagram account. 

I have 2 cases. Uploading photo and video to this accounts via my IP, and via proxy. 

When I'm uploading stuff via my IP everything is fine. Photo and video upload working like a charm. In case when video is long I have "Transcode timeout", but this error fixed by repeating configure request to API (as researched from previous opened issues).

But when I'm uploading via proxy something strange happens. Photo uploading works well for both accounts. But video upload is working only for test account. When I'm trying to upload video to my personal account I have "Transcode timeout" on `media/configure/` step every time. Even with waiting, as proposed in previously opened issues.

Thank you for your attention, I hope we will find solution.

Kind regards,
Roman.

**Comment by mgp25** [comment]
Post requests and responses of the related requestes

Regards

**Comment by mgp25** [comment]
@romalytvynenko closed due to inactivity

Regards
