### ISSUE TITLE
Checkpoint problem on some of servers when trying to post to Instagram

### ISSUE THREAD

**Issue by mnajafzadeh** [mgp25/Instagram-API#855]
We have the same issue that is explained here: https://github.com/mgp25/Instagram-API/issues/852
You have locked all the conversations to this issue so I wrote this new one.

Please, consider that I can already post to Instagram from my computer but, I can not post from many other computers/servers using this library and get the checkpoint require message. When I go to my account and click "Yes" and try again, it gives me the same error again and again.

I also tried to use the solution @GuilhermeFM has mentioned but, I couldn't find a "Two factor verification" section in my Instagram account area!

I can provide you my server to test and see what is happening on our side.

Please, help.

**Comment by mgp25** [comment]
@mnajafzadeh if it works in other servers, you know the issue. Instagram flagged/banned them

Regards

**Comment by mnajafzadeh** [comment]
I think you only like to close everything as soon as possible. I doesn't mean resolving problems.

**Comment by mgp25** [comment]
I told you the problem. Not API issue.

Regards
