### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by rizkihape** [mgp25/Instagram-API#86]
Hy .
please share tutorial for use this script, i'am a beginner :)
just step by step please.

Thanks :)

**Comment by RageBrahimi** [comment]
With all due respect @rizkihape - a lot of the code on the source is self explanatory and it's just the case of you reading it and understanding it. Additionally, there an example folder, which does the work for you (obviously, you need to amend it based on your needs).

**Comment by mgp25** [comment]
Use google, check examples and learn basic knowledge of PHP

Regards
