### ISSUE TITLE
Get user's images (self or userId) | Question

### ISSUE THREAD

**Issue by rakhimzhanov** [mgp25/Instagram-API#860]
Good day!

I have a question related user's information.
Is there possible to get user's uploaded images?
For example, I logged in and I would like to see my images (uploaded)

I am using your library only a day and I didn't find code related with my question
Thank you for the awesome library

Regards,

**Comment by mgp25** [comment]
@rakhimzhanov yes, you can:

- Get username's feed: https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1335

- get yourself's feed: https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1407

- Backup your photos: https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1567

Regards

**Comment by geobotsar** [comment]
Hi, i have the same requirement, is there a code sample for this?

**Comment by aitte2** [comment]
@geobotsar Updated links:

- Get username's feed:

https://github.com/mgp25/Instagram-API/blob/96b02ec73256c865cfc5930d8b629d8dc7762bda/src/Request/Timeline.php#L301-L311

- Get your own feed:

https://github.com/mgp25/Instagram-API/blob/96b02ec73256c865cfc5930d8b629d8dc7762bda/src/Request/Timeline.php#L324-L333

- Backup your photos and videos:

https://github.com/mgp25/Instagram-API/blob/96b02ec73256c865cfc5930d8b629d8dc7762bda/src/Request/Timeline.php#L401-L416

Just install the latest code (see readme) and look at the examples and then modify the examples to call any of these functions.
