### ISSUE TITLE
login required

### ISSUE THREAD

**Issue by Flayor** [mgp25/Instagram-API#863]
Hi

I have a problem,

I have test this & all work BUT,

After I change my password nothing work, i get this error 
(Change on Instagram & on the variable $password)

GET: feed/timeline?rank_token=3662675416_8292fffd-a3b9-4971-9169-733170ef3df5&ranked_content=true ← 400 47B RESPONSE: {"status": "fail", "message": "login_required"} InstagramAPI\TimelineFeedResponse : login_required

How to resolved this ?

**Comment by ping** [comment]
Try deleting the folders/files in ``data/``

**Comment by Flayor** [comment]
Great ! 

Thanks it's work :)
