### ISSUE TITLE
Version 10.5.0

### ISSUE THREAD

**Issue by GHXST01** [mgp25/Instagram-API#866]
Anyone that has experience with patching certificate pinning that wants to take a look at 10.5.0 ?
They implemented a bypass for wifi proxy settings and seem to detect a MITM.

Probably cert pinning or something of this nature but I cannot locate the functionality.
There's no files popping up with `checkClientTrusted`, `checkServerTrusted` etc.

Both fiddler and charles show _zero_, no connection attempts, _nothing_.
I don't have a wireshark setup to check for other packets, but I am positive the app is not making any connection.

In-app I am getting a network error.

**Comment by mgp25** [comment]
@GHXST01 not API issue.

Regards

**Comment by GHXST01** [comment]
It will be when support gets dropped for the version you are currently using.

**Comment by GHXST01** [comment]
On top of that your current API is already missing parameters for some endpoints. @mgp25

**Comment by mgp25** [comment]
@GHXST01 there is a lot of technical information out there, check how to bypass it or patch it

Regards

**Comment by GHXST01** [comment]
@mgp25 I am aware of most documentation and have tried using those as guidelines.
However this lead to no result as mentioned in the OP.

This has been an issue since 10.4.0 and seeing as you are currently on 10.3.x it might be worth looking into, as they are not using a straight forward approach to cert pinning.

I am not aware of anyone that has been able to patch 10.4.0 + to allow for a successful MITM.

**Comment by mgp25** [comment]
@GHXST01 it takes 5 minutes to patch latest version, its very easy. I can't post any guides since i dont want to get in trouble

Regards

**Comment by GHXST01** [comment]
@mgp25 Have you checked 10.5.0 ?
I know I am an amateur in regards to reverse engineering but I have a hard time believing you found and patched the certificate pinning functionality in 5 minutes.

You might have disassembled the APK and found the methods in `smali\com\facebook\c\a\l.smali` but this is not the file that require patching to allow for a MITM.

I tried patching this file by `return-void` in `checkClientTrusted`, `checkServerTrusted` and `getAcceptedIssuers` but the issue persisted.

I've done a binary search for the public key of the certificate as provided by the *.instagram.com website but this search yielded no results, which is why I am thinking they are not using a straight forward way of cert pinning.

Don't we aim to be people that are dedicated to relentlessly pursue knowledge and selflessly share it with others?

If your wish is to not share knowledge on this subject publicly, which I respect, I would still like to learn what they are doing and how to patch this.

I've encountered certificate pinning before but would at least still find either exceptions in logcat, (failed) connection attempts in charles / fiddler / OWASP ZAP or others.

This time around there's not much to go off and I am at a stand still.

**Comment by GHXST01** [comment]
@mgp25 I emailed you, I am excited to learn from you.

**Comment by GHXST01** [comment]
@mgp25 Did you receive my email ?

**Comment by glazkoman** [comment]
Hi there

@GHXST01  did you managed to patch new version of ig app to sniff traffic?

Thank You
