### ISSUE TITLE
[ASK] Unread Inbox Message

### ISSUE THREAD

**Issue by nubinter** [mgp25/Instagram-API#868]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
---

### How to see unread messages?

I know how to return the unread count of message. But I don't know how to mark the unread messages.

**Comment by mgp25** [comment]
@nubinter is not implemented yet

Regards
