### ISSUE TITLE
post-login: how necessary is it to fetch timeline, inbox, recentActivity?

### ISSUE THREAD

**Issue by milesrichardson** [mgp25/Instagram-API#87]
In the case of logging into an account with cached credentials (i.e. the `username.dat` file exists), is it necessary to make these requests post-login?:

```php
$this->timelineFeed();
$this->getv2Inbox();
$this->getRecentActivity();
```

I assume you included that code for a reason. Did you notice accounts getting banned if they did not call those requests after login?

It would obviously be more efficient to *not* make those requests, so I'm just wondering how safe that is.

**Comment by mgp25** [comment]
Everything is done for a reason. Capture traffic and you will know

Regards

**Comment by milesrichardson** [comment]
I have captured traffic and didn't see anything necessary... perhaps because I was using a cached login? I've been commenting out those lines on cached logins and it seems to work fine.

**Comment by mgp25** [comment]
You can do whatever you want, if i do it like that its because of something
