### ISSUE TITLE
follow stopped working

### ISSUE THREAD

**Issue by noorzaie** [mgp25/Instagram-API#878]
I can't follow, it was working until now, but now it not works. instagram returns no error, just it returns "following":false in response :

`{"status":"ok","friendship_status":{"incoming_request":false,"outgoing_request":false,"following":false,"is_private":false,"blocking":false,"followed_by":false}}`

it is not blocking problem, because I can follow from instagram app. what's the problem??

**Comment by mgp25** [comment]
@noorzaie that happens when Instagram has flagged your account, flagged doesnt mean blocked, it means that Instagram has detected weird activity and therefore blocked you some features.

The API is not perfect yet, so thats why it works later on app. 

Regards
