### ISSUE TITLE
Empty Response on Upload Photo

### ISSUE THREAD

**Issue by Taytus** [mgp25/Instagram-API#879]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [X ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ X] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include below *code* that will replicate the error, and the *error log/traceback*.

Code:

```php
// Please provide your own code here

 $i=new  Instagram();

 $i->setUser($user,$password));
//login


 try {
            $i->login();
        } catch (Exception $e) {
            echo $e->getMessage();
          
            return false;
            exit();
        };


//post
try {
                   $res_upload=$i->uploadPhoto($photo, $description);
                    if($res_upload->status=="ok"){
                          //do something


                        }
                } catch (Exception $e) {
                 

                    echo  $e->getMessage();


                };


```

Error/Log/var_dump:

```php
// Please provide your error log/dump here


POST:  upload/photo/
→ 128.9kB
← 200 	 46B
RESPONSE: {"status": "ok", "upload_id": "1485385237760"}

POST:  media/configure/
DATA: ig_sig_key_version=4&signed_body=900c13dcfe92a10a7a7d3bb92d4af0f46a787d9f29286afaebd88c3980aecbb0.{"_csrftoken":"frwPJAKeoYYqhax2GvkwiLlcdzEdwXNV","media_folder":"Instagram","source_type":4,"_uid":"3407179635","_uuid":"14267c85-b10f-4791-a7a6-2936b04ba6ec","caption":"  ","upload_id":"1485385237760","device":{"manufacturer":"Panasonic","model":"Panasonic KX-PRXA15","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[1080,1080],"crop_center":[0,0],"crop_zoom":1},"extra":{"source_width":1080,"source_height":1080}}
← 0 	 0B
RESPONSE: 



```

### Describe your issue

THIS ISSUE HAS BEEN RESOLVED CHANGING THE IP, BUT....

The issue was that I was *successfully* uploading the images but without *ANY* notification.

Once I changed the IP, started working again. So my question is, if this was a bug, considering that the post was successful, and if we can receive some type of message when this occurs again.

Thank you!!

**Comment by mgp25** [comment]
@Taytus that happens when you are using a proxy or it takes more than it should to get the response. In other words, connectivity issues.

You can add an exception to catch when response is null and it shouldnt

Regards

**Comment by Taytus** [comment]
@mgp25  I actually ended up doing that :)


This is my question: When I send the post, it triggers two calls right?


POST:  upload/photo/
→ 128.9kB
← 200 	 46B
RESPONSE: {"status": "ok", "upload_id": "1485385237760"}

AND the media/configure.

How/where can I save that upload_id from the first call? I'd like to access to it as  $i->failed_id or something like that.

Thank you!!
