### ISSUE TITLE
proxy don't work?

### ISSUE THREAD

**Issue by Chinyaev** [mgp25/Instagram-API#882]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include below *code* that will replicate the error, and the *error log/traceback*.

Code:

```php
$i = new \InstagramAPI\Instagram(false);
...
$i->setProxy($proxyHost, $proxyPort, $proxyUser, $proxyPass); // 185.183.162.253, 12826, qolQMG, bCaM0Q
$i->setUser($login, $pass); 
try {
    $log = $i->like($mediaId); // mediaId = 1362139346614108318_1305927887
} catch (\Exception $e) {
Log::info($e->getMessage()); // InstagramAPI\Response : feedback_required
}
```

---

### Describe your issue

Hello!

Excuse me for my english.
I have a problem. First Like = Ban. But, when i follow or unfollow = not ban.
When i try do like with other PC - not ban too. I think instagram give ban for IP. Proxy not working.

**Comment by Chinyaev** [comment]
Now i'm not get ban. But error feedback_required with all proxy. 

If proxy https, right use:
1) 185.183.162.253
2) http://185.183.162.253
3) https://185.183.162.253
?

And how check proxy in api?

**Comment by mgp25** [comment]
@Chinyaev proxy works perfectly with the API. If it tells you `feedback_required`, you need to use `Checkpoint`. I recommend you to read related issues, where this is explained very detailed.

Regards
