### ISSUE TITLE
isPrivate() not working

### ISSUE THREAD

**Issue by joluch** [mgp25/Instagram-API#883]
Hi. I know this is probably not an issue but i dont know where else to ask it. I was trying to access is_private but its not working... I have tried 
**getIsPrivate()** **isPrivate()** and **user->is_private**. 
But none of them are working. Thanks for any responses

**Comment by frrakn** [comment]
Can you paste your code?

**Comment by joluch** [comment]
$i = new \InstagramAPI\Instagram($debug);

$i->setUser($username, $password);

try {
    $i->login();
} catch (Exception $e) {
    echo 'something went wrong '.$e->getMessage()."\n";
    exit(0);
}
  $user = $i->getSelfUsernameInfo();

  if($user->is_private) {
    echo "User is private";
  }

**Comment by frrakn** [comment]
`getSelfUsernameInfo` returns a UsernameInfoResponse. You call `getUser` on that to get the user object, which you can then call `getIsPrivate` on.

**Comment by joluch** [comment]
Thank you so much
