### ISSUE TITLE
Video upload issue in instagram

### ISSUE THREAD

**Issue by TestDemo198** [mgp25/Instagram-API#886]
Hello,
I have used your latest Instagram API for video uploading

I am getting errors {"result": "deprecated", "configure_delay_ms": "6500", "status": "ok"}
Please Let me know i but i do to fix this problem
Kind Regards

**Comment by mgp25** [comment]
@TestDemo198 that response is okay, not an error

Regards

**Comment by TestDemo198** [comment]
thanks for reply but video not upload on Instagram

**Comment by mgp25** [comment]
@TestDemo198 If video is not uploaded, probably Instagram has flagged your account

**Comment by TestDemo198** [comment]
please let me to fix this problem
