### ISSUE TITLE
Cannot access variable after login

### ISSUE THREAD

**Issue by zarulizham** [mgp25/Instagram-API#887]
$i = new \InstagramAPI\Instagram(false);
`

	$i->setUser($username, $password);
	echo $i->username; // value is printed out
	if ($i->isLoggedIn) {
		echo 'Logged in';
	} else {
		echo 'Not logged in'; // value is printed out
	}

	try {
		$i->login();
		echo $i->username; // value is not printed out

		if ($i->isLoggedIn) {
			echo 'Logged in'; // value is not printed out
		} else {
			echo 'Not logged in';
		}
	} catch (Exception $e) {
	    $e->getMessage();
	    exit();
	}
`

Another variable also cannot be printed out.

**Comment by joluch** [comment]
I'm no master at this. But what are you trying to do here?
**echo $i->username;**

**Comment by joluch** [comment]
Im no master at this but to get your username use 
**$user = $i->getSelfUsernameInfo();
echo $user->getUsername();**

**Comment by zarulizham** [comment]
Hi @joluch 

I added those lines, nothing came out too.

**Comment by joluch** [comment]
This may not be what you are after but it will search a hashtag feed and display the username of the first user
    
    $i->setUser($username, $password);
    try {
    $i->login();
    } catch (Exception $e) {
    echo 'something went wrong '.$e->getMessage()."\n";
    exit(0);
    }

    $a = $i->getHashtagFeed("instagram", $maxid = null);
    $items = $a->getItems();

    $user = $items[0]->getUser();
    $userName = $user->getUsername();
    echo $user->getUsername();

**Comment by zarulizham** [comment]
Thanks for the code @joluch 

But at the first place my aim just want to know whether the login is succeed or not, so that I can proceed with next functions.

**Comment by mgp25** [comment]
@zarulizham if login went wrong, exception is catched and you can handle everything there

**Comment by zarulizham** [comment]
I cannot access variable for example:


		
		$a = $i->getPopularFeed();
		print_r($a);  // have result as array
		echo $a['auto_load_more_enabled'][0]['pk']; // no value printed


This is example of print_r($a).
![screen shot 2017-01-28 at 22 46 13](https://cloud.githubusercontent.com/assets/10229855/22397425/03d1c626-e5ac-11e6-8ac3-3ae1783c3e76.png)

**Comment by mgp25** [comment]
@zarulizham have you read the wiki or examples? Because what you are telling makes no sense.

First of all, get the items (`getItems`), now you can get the first one of the array. And then get pk (`getPk`).

Please read wiki and examples

Regards

**Comment by jpmoney5065** [comment]
Quick question for the php experts that came up in this issue, but doesn't deserve it's own thread:

Is there a reason to use the "get function"s over just calling the property? (they are all public now, right?)

example:
```
$a = $i->getPopularFeed();
$items = $a->getItems();
$firstItem_image_versions = $items[0]->getImageVersions2()->getCandidates()[0]->getUrl();

// All together
$bigUrl = $i->getPopularFeed()->getItems()[0]->getImageVersions2()->getCandidates()[0]->getUrl();

```

vs.

```
$a = $i->getPopularFeed();
$items = $a->items;
$firstItem_image_versions = $items[0]->image_versions2->candidates[0]->url;

// All together
$bigUrl = $i->getPopularFeed()->$items[0]->image_versions2->candidates[0]->url;
```

Seems they just complicate things with changing the capitalizations and missing underscores...

**Comment by mgp25** [comment]
Im closing this repo

**Comment by zarulizham** [comment]
@mgp25 

I just understand how to use it. Thank you very much 😁
