### ISSUE TITLE
Photo Upload

### ISSUE THREAD

**Issue by djstanley** [mgp25/Instagram-API#89]
When trying to upload a photo, it gives the following error:

`HTTP/1.1 502 Error parsing server response`

I have cleared cookies/auth files and tried with different images (including photos taken from Instagram), but the issue remains. Here is the debug log:

`REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=22414afbabdd2071bfe6cf3045fdfebf9b249e5d7d65545391c0943ff21fbc2d.{"upload_id":null,"camera_model":"HM1S","source_type":3,"date_time_original":"2016:03:10 14:23:51","camera_make":"XIAOMI","edits":{"crop_original_size":[640,640],"crop_zoom":1.3333334,"crop_center":[0.0,-0.0]},"extra":{"source_width":640,"source_height":640},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"d3512649d695a94c0bdd54d431b548b2","_uuid":null,"_uid":"1377417084","caption":"ITS LIT"}`

`RESPONSE: Oops, an error occurred.`

Is this a problem for anybody else?

**Comment by mgp25** [comment]
@djstanley upload did not complete, thats why `upload_id` its null. API works fine, double check your code and network

**Comment by djstanley** [comment]
@mgp25 Code is fine, I am using uploadPhoto from examples folder with strong internet.

$instagram->uuid is null, could that be why?

**Comment by VitalikShalamay** [comment]
i have this problem
