### ISSUE TITLE
Getting same response 

### ISSUE THREAD

**Issue by irshad9998** [mgp25/Instagram-API#890]
> `$i->usersFriendship($following_array);` when i use this method every time i got same response as below

   
    `[1980129715] => InstagramAPI\FriendshipStatus Object
        (
            [following] => 1
            [followed_by] => 
            [incoming_request] => 
            [outgoing_request] => 
            [is_private] => 
            [is_blocking_reel] => 
            [is_muting_reel] => 
            [blocking] => 
            [status] => 
            [message] => 
            [fullResponse] => 
        )`

    [1173606927] => InstagramAPI\FriendshipStatus Object
        ( 
            [following] => 1
            [followed_by] => 
            [incoming_request] => 
            [outgoing_request] => 
            [is_private] => 
            [is_blocking_reel] => 
            [is_muting_reel] => 
            [blocking] => 
            [status] => 
            [message] => 
            [fullResponse] => 
        )`

**Comment by mgp25** [comment]
@irshad9998 can you provide your code script and debug log please?

**Comment by irshad9998** [comment]
ok

**Comment by irshad9998** [comment]
`<?php
  
    $i = new \InstagramAPI\Instagram(false);
 
    $i->setUser($username, $pass);
     
    try {
    $a = $i->getUsernameId($username);
    
    $helper1 = null;
    $followings = [];
    
    $following_array = array();
    $id_array = array();
    
    do {
        if (is_null($helper1)) {
            $helper1 = $i->getSelfUsersFollowing();
        } else {
            $helper1 = $i->getSelfUsersFollowing($helper1->getNextMaxId());
        }
        
        
        $followings = array_merge($followings, $helper1->getUsers());
    } while (!is_null($helper1->getNextMaxId()));
    
    foreach ($followings as $follower) {
        $id = $follower->getPk();

        array_push($following_array,$id);
           }
    
    $status = $i->usersFriendship($following_array);
    
    print_r($status->getFriendshipStatuses());
   
    
    
} catch (Exception $e) {
}
?>`

**Comment by irshad9998** [comment]
Logs

> GET: users/second.pixster/usernameinfo/ ← 200 1.21kB RESPONSE: {"status": "ok", "user": {"hd_profile_pic_url_info": {"url": "http://scontent.cdninstagram.com/t51.2885-19/15056744_154610045013108_1508418511792242688_a.jpg", "width": 640, "height": 640}, "usertags_count": 0, "is_verified": false, "username": "second.pixster", "external_url": "", "show_feed_biz_conversion_icon": false, "usertag_review_enabled": false, "full_name": "second", "pk": 3196032959, "has_anonymous_profile_picture": false, "has_chaining": true, "media_count": 44, "can_boost_post": false, "follower_count": 22, "can_see_organic_insights": false, "show_insights_terms": false, "is_private": false, "show_conversion_edit_entry": true, "following_count": 8, "hd_profile_pic_versions": [{"url": "http://scontent.cdninstagram.com/t51.2885-19/s320x320/15056744_154610045013108_1508418511792242688_a.jpg", "width": 320, "height": 320}, {"url": "http://scontent.cdninstagram.com/t51.2885-19/s640x640/15056744_154610045013108_1508418511792242688_a.jpg", "width": 640, "height": 640}], "can_convert_to_business": true, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/15056744_154610045013108_1508418511792242688_a.jpg", "profile_pic_id": "1388422814956332371_3196032959", "is_business": false, "biography": ""}} GET: friendships/3196032959/following/?rank_token=3196032959_3eadebed-ddf1-48fa-a590-d6672587394f ← 200 2.67kB RESPONSE: {"page_size": 200, "status": "ok", "users": [{"has_anonymous_profile_picture": false, "is_private": false, "is_verified": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/11356615_756477584460868_1064524161_a.jpg", "pk": 2033511422, "full_name": "Irshad Memon", "username": "memon.irshad", "is_favorite": false}, {"has_anonymous_profile_picture": false, "profile_pic_id": "1421132643784838821_2413289296", "is_private": true, "is_verified": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/15802213_597259733802160_2719387079225114624_n.jpg", "pk": 2413289296, "full_name": "Riyaz Memon", "username": "riyazmemon_roy", "is_favorite": false}, {"has_anonymous_profile_picture": true, "is_private": false, "is_verified": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11906329_960233084022564_1448528159_a.jpg", "pk": 4221302827, "full_name": "aiyubpixster3", "username": "aiyubpixster3", "is_favorite": false}, {"has_anonymous_profile_picture": false, "profile_pic_id": "1356512088708748660_3920937922", "is_private": false, "is_verified": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/14515676_1750967491822509_1220506517271216128_a.jpg", "pk": 3920937922, "full_name": "Andrea campins", "username": "campins09", "is_favorite": false}, {"has_anonymous_profile_picture": false, "profile_pic_id": "1346577059002233754_3259769673", "is_private": true, "is_verified": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/14271979_612919582214664_6136825443493347328_a.jpg", "pk": 3259769673, "full_name": "jatinpatel003", "username": "jatinpatel003", "is_favorite": false}, {"has_anonymous_profile_picture": false, "is_private": false, "is_verified": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/12960010_1525961487711830_121043771_a.jpg", "pk": 3126365193, "full_name": "Aiyub", "username": "aiyubmunshi22", "is_favorite": false}, {"has_anonymous_profile_picture": false, "is_private": false, "is_verified": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/11821808_1656487027970117_1147284087_a.jpg", "pk": 335715881, "full_name": "\ud83d\udc8b\ud83d\udc8bTylor Swift\ud83d\udc8b\ud83d\udc8b", "username": "tylor_swift", "is_favorite": false}, {"has_anonymous_profile_picture": false, "profile_pic_id": "1363297343591875448_208560325", "is_private": false, "is_verified": true, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/14677463_1311437935541706_555720926461689856_a.jpg", "pk": 208560325, "full_name": "Khlo\u00e9", "username": "khloekardashian", "is_favorite": false}], "big_list": false} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"followed_by": true, "status": "ok", "outgoing_request": false, "incoming_request": false, "is_private": true, "is_muting_reel": false, "is_blocking_reel": false, "blocking": false, "following": true} GET: friendships/show/2033511422/ ← 200 203B RESPONSE: {"is_blocking_reel": false, "outgoing_request": false, "is_private": false, "followed_by": false, "status": "ok", "is_muting_reel": false, "blocking": false, "following": true, "incoming_request": false} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"is_muting_reel": false, "blocking": false, "status": "ok", "incoming_request": false, "following": true, "outgoing_request": false, "followed_by": true, "is_private": true, "is_blocking_reel": false} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"status": "ok", "is_muting_reel": false, "following": true, "followed_by": true, "incoming_request": false, "is_blocking_reel": false, "is_private": true, "blocking": false, "outgoing_request": false} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"is_private": true, "incoming_request": false, "status": "ok", "followed_by": true, "is_muting_reel": false, "following": true, "outgoing_request": false, "blocking": false, "is_blocking_reel": false} GET: friendships/show/4221302827/ ← 200 202B RESPONSE: {"blocking": false, "incoming_request": false, "status": "ok", "is_blocking_reel": false, "outgoing_request": false, "followed_by": true, "is_muting_reel": false, "is_private": false, "following": true} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"is_blocking_reel": false, "is_private": true, "blocking": false, "outgoing_request": false, "is_muting_reel": false, "following": true, "incoming_request": false, "followed_by": true, "status": "ok"} GET: friendships/show/3920937922/ ← 200 202B RESPONSE: {"is_private": false, "blocking": false, "is_muting_reel": false, "following": true, "outgoing_request": false, "is_blocking_reel": false, "incoming_request": false, "followed_by": true, "status": "ok"} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"blocking": false, "followed_by": true, "is_private": true, "is_blocking_reel": false, "following": true, "outgoing_request": false, "status": "ok", "is_muting_reel": false, "incoming_request": false} GET: friendships/show/3259769673/ ← 200 201B RESPONSE: {"incoming_request": false, "is_private": true, "followed_by": true, "blocking": false, "is_muting_reel": false, "status": "ok", "outgoing_request": false, "following": true, "is_blocking_reel": false} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"following": true, "status": "ok", "outgoing_request": false, "is_private": true, "blocking": false, "followed_by": true, "is_muting_reel": false, "is_blocking_reel": false, "incoming_request": false} GET: friendships/show/3126365193/ ← 200 202B RESPONSE: {"is_private": false, "following": true, "incoming_request": false, "status": "ok", "is_muting_reel": false, "outgoing_request": false, "followed_by": true, "is_blocking_reel": false, "blocking": false} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"is_private": true, "status": "ok", "following": true, "outgoing_request": false, "is_muting_reel": false, "followed_by": true, "incoming_request": false, "blocking": false, "is_blocking_reel": false} GET: friendships/show/335715881/ ← 200 203B RESPONSE: {"is_blocking_reel": false, "incoming_request": false, "followed_by": false, "is_muting_reel": false, "following": true, "is_private": false, "blocking": false, "status": "ok", "outgoing_request": false} GET: friendships/show/2413289296/ ← 200 201B RESPONSE: {"is_muting_reel": false, "outgoing_request": false, "following": true, "status": "ok", "followed_by": true, "is_private": true, "is_blocking_reel": false, "incoming_request": false, "blocking": false} GET: friendships/show/208560325/ ← 200 203B RESPONSE: {"following": true, "incoming_request": false, "blocking": false, "is_muting_reel": false, "is_blocking_reel": false, "followed_by": false, "is_private": false, "outgoing_request": false, "status": "ok"}

**Comment by BTopbas** [comment]
same here. I cant get response usersfriendship() command.

My code

`require 'vendor/autoload.php';
$i = new \InstagramAPI\Instagram(true,false);
$i->setUser("myusername", "mypassword");
$i->login();
$a = $i->getUsernameId('anyuserusername');
$s = $i->usersFriendship($a);
print_r($s);`

Log says

`POST: friendships/show_many/ DATA: _uuid=a1d96d6g-32bf-4cc8-83cd-f352c53f2485&_csrftoken=o1VG6d6s2Tq1otUOy6qDNhArEHwFx0pD ← 400 51B RESPONSE: {"message": "Invalid parameters", "status": "fail"}`

**Comment by mgp25** [comment]
Works perfectly, please dump the object and you will see its values

Regards

**Comment by irshad9998** [comment]
Issue is not solve getting same response

**Comment by irshad9998** [comment]
> POST: friendships/show_many/ DATA: _uuid=f0b7a0f5-674d-4ae0-8c8c-6a47f39c98c6&user_ids=3090300779&_csrftoken=AL33Cpz77hzW4Og1GvU2k7MoEMvaZIhz ← 200 152B RESPONSE: {"friendship_statuses": {"3090300779": {"outgoing_request": false, "incoming_request": false, "is_private": false, "following": false}}, "status": "ok"}

getting same response problem not solve

**Comment by irshad9998** [comment]
> http://www.api.safehandsecurity.in/instaCleaner/test/following.php?user=aiyub.pixster&pass=pixster1234

here is link you will check , What i am saying.

> [followed_by] =>  every time is return nil vlaue

Same as every request when i change user name and password also
