### ISSUE TITLE
Live Story

### ISSUE THREAD

**Issue by erfansahaf** [mgp25/Instagram-API#895]
Hi,

Can you support send comment or like in the live stories?
Thanks.

**Comment by mgp25** [comment]
Maybe in the future, but i cant tell you when because im not really insterested in Instagram anymore

Regards

**Comment by erfansahaf** [comment]
It means you will not support this library anymore? 😢

**Comment by mgp25** [comment]
@erfansahaf it means i have other projects in mind. Remember that all what i do is for free, no one pays for it

**Comment by erfansahaf** [comment]
I know, and I thank you for all of these libraries. I just wanted to know this repo will be updated in future or not.
Anyway, thank you, soo much!
