### ISSUE TITLE
Fetch Contact Details from Profile

### ISSUE THREAD

**Issue by samaybhavsar** [mgp25/Instagram-API#896]
## How to Fetch Contact Details - Email and Phone from Business Profiles

Instagram business profiles have contact details. Can we have a way to fetch the same? It is only visible in the app and not on the web interface.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

**Comment by mgp25** [comment]
@samaybhavsar is not implemented, and i dont think ill ever do it, but pull requests are welcome, if you implement this feature we will add it.

Regards
