### ISSUE TITLE
getPopularFeed() returns empy array

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#897]
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

Code:

```php
require("vendor/autoload.php");

$i = new \InstagramAPI\Instagram(true, true);
$i->setUser("xxx", "yyy");

try {
  $popular_media = $i->getPopularFeed();
} catch (Exception $e) {
  echo $e->getMessage();
}

print_r($popular_media->getItems());
```

Error/Log/var_dump:
```php
GET: feed/popular/?people_teaser_supported=1&rank_token=3738309866_ec79bccb-4d00-4d8c-91ba-989c4a4db543&ranked_content=true ← 200 47B RESPONSE: {"status": "ok", "items": [], "num_results": 0}
```

---

### Describe your issue
Most of the times, when calling  getPopularFeed, getItems returns an empty array, sometimes a 1 element array. Thanks!

**Comment by mgp25** [comment]
@joseflorido seems everything okay, look at the response:

```json
 RESPONSE: {"status": "ok", "items": [], "num_results": 0}
```

We handle Instagram responses, if Instagram response is an empty array, the object will contain an empty array when calling `getItems`

**Comment by joseflorido** [comment]
But.. how can be there 0 items on the Popular Feed? Is it different per
user? This is the endpoint for “explore” tab in the app, where you can
always find new content, right?
