### ISSUE TITLE
Search similar to IG possible?

### ISSUE THREAD

**Issue by XeroEB** [mgp25/Instagram-API#898]
Is it possible to return a search list like this? http://i.imgur.com/vmuAgF3.png

Using searchUsers("fashion") returns a list like:

`[{"media_count":336856904,"name":"fashion","id":1.7841592771073e+16,"status":null,"message":null,"fullResponse":null},{"media_count":1083427,"name":"fashionph","id":1.7841548983106e+16,"status":null,"message":null,"fullResponse":null},{"media_count":31795614,"name":"fashionblogger","id":1.7843830906017e+16,"status":null,"message":null,"fullResponse":null},{"media_count":1433802,"name":"fashionbag","id":1.7843806024054e+16,"status":null,"message":null,"fullResponse":null},{"media_count":738113,"name":"fashions","id":1.7843890609016e+16,"status":null,"message":null,"fullResponse":null},{"media_count":822330,"name":"fashionmen","id":1.7841561193125e+16,"status":null,"message":null,"fullResponse":null},{"media_count":600959,"name":"fashionart","id":1.7841562813096e+16,"status":null,"message":null,"fullResponse":null},{"media_count":506306,"name":"fashionist","id":1.784379441701e+16,"status":null,"message":null,"fullResponse":null},{"media_count":370907,"name":"fashionman","id":1.7843798371046e+16,"status":null,"message":null,"fullResponse":null},{"media_count":6653065,"name":"fashionweek","id":1.7843766205019e+16,"status":null,"message":null,"fullResponse":null},{"media_count":11274963,"name":"fashionable","id":1.7843860726042e+16,"status":null,"message":null,"fullResponse":null},{"media_count":9800076,"name":"fashionblog","id":1.7843865292026e+16,"status":null,"message":null,"fullResponse":null},{"media_count":8285302,"name":"fashiongram","id":1.784378240206e+16,"status":null,"message":null,"fullResponse":null},{"media_count":5453722,"name":"fashionkids","id":1.7841601468078e+16,"status":null,"message":null,"fullResponse":null},{"media_count":5209410,"name":"fashionshow","id":1.7843777167012e+16,"status":null,"message":null,"fullResponse":null},{"media_count":5221525,"name":"fashionpost","id":1.784154592611e+16,"status":null,"message":null,"fullResponse":null},{"media_count":1107342,"name":"fashionbaby","id":1.7841563560105e+16,"status":null,"message":null,"fullResponse":null},{"media_count":1918822,"name":"fashiongirl","id":1.7843853274054e+16,"status":null,"message":null,"fullResponse":null},{"media_count":37210850,"name":"fashionista","id":1.7843742502018e+16,"status":null,"message":null,"fullResponse":null},{"media_count":819581,"name":"fashionlove","id":1.7841562990102e+16,"status":null,"message":null,"fullResponse":null},{"media_count":722023,"name":"fashionlook","id":1.7841545722112e+16,"status":null,"message":null,"fullResponse":null},{"media_count":927786,"name":"fashionpria","id":1.7841552571091e+16,"status":null,"message":null,"fullResponse":null},`

**Comment by XeroEB** [comment]
Website wise uses -> https://www.instagram.com/web/search/topsearch/?context=blended&query=fashion&rank_token=0.5608812966555072 

which returns

`{"hashtags": [{"position": 1, "hashtag": {"name": "fashion", "media_count": 336857447, "id": 17841592771073334}}], "status": "ok", "has_more": true, "places": [], "users": [{"position": 0, "user": {"username": "fashionvideo.s", "unseen_count": 17, "full_name": "FASHION MAKEUP NAILS DIY HAIR", "has_anonymous_profile_picture": false, "search_social_context": "Following", "profile_pic_url": "https://ig-s-b-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-19/s150x150/15803510_1466911423349725_466188205712998400_a.jpg", "following": true, "mutual_followers_count": 6.0, "pk": "1720123900", "follower_count": 7024648, "is_private": true, "outgoing_request": false, "byline": "7.0m followers", "profile_pic_id": "1417610896683093530_1720123900", "social_context": "Following", "is_verified": false}}, {"position": 2, "user": {"username": "fashion.selection", "unseen_count": 30, "full_name": "Fashion Selection \ud83e\udd84\ud83d\udc95", "has_anonymous_profile_picture": false, "profile_pic_url": "https://ig-s-a-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-19/s150x150/13129256_845176455610556_914069560_a.jpg", "following": false, "mutual_followers_count": 1.0, "pk": "1552641372", "follower_count": 1573394, "is_private": false, "outgoing_request": false, "byline": "1.5m followers", "profile_pic_id": "1239161198660122417_1552641372", "is_verified": false}}, {"position": 3, "user": {"username": "fashionschics", "unseen_count": 39, "full_name": "\ud83d\udc8eF A S H I O N T R E N D S\u00ae\ud83d\udc8e", "has_anonymous_profile_picture": false, "search_social_context": "Following", "profile_pic_url": "https://ig-s-c-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-19/s150x150/14240881_1764980320433346_2132696114_a.jpg", "following": true, "mutual_followers_count": 0.0, "pk": "2921795795", "follower_count": 858169, "is_private": false, "outgoing_request": false, "byline": "858k followers", "profile_pic_id": "1332188108179046138_2921795795", "social_context": "Following", "is_verified": false}}, {"position": 4, "user": {"username": "fashiongoalsz", "unseen_count": 17, "full_name": "Fashionaddict", "has_anonymous_profile_picture": false, `

**Comment by XeroEB** [comment]
fbUserSearch will work for now - I'll add a normal user search and commit the changes later :)

**Comment by mgp25** [comment]
@XeroEB thanks, i close this issue as its solved i guess. Let me know if you have any doubt.

Regards
