### ISSUE TITLE
Photo wont upload

### ISSUE THREAD

**Issue by losdivinos** [mgp25/Instagram-API#90]
Hey, I've checked to see that login works just fine. I can retrieve feed and all that stuff.
Also tried to remove the three .dat-files in data-folder.

I still keep getting this error though. Tried with different images in different sizes (png, jpg. 1080x1080, 500x500, 640x640)

`RESPONSE: 

REQUEST: media/configure/
DATA: ig_sig_key_version=4&signed_body=e0b1ed43262a22d1e0badcaf9cae6cc601e226a8bd86ef2898a478f2a400514e.{"upload_id":null,"camera_model":"HM1S","source_type":3,"date_time_original":"2016:03:13 11:54:51","camera_make":"XIAOMI","edits":{"crop_original_size":[640,640],"crop_zoom":1.3333334,"crop_center":[0.0,-0.0]},"extra":{"source_width":640,"source_height":640},"device":{"manufacturer":"Xiaomi","model":"HM 1SW","android_version":18,"android_release":"4.3"},"_csrftoken":"5bc69dbb350af3a6897fb5fa93ea70fb","_uuid":"351ef7d6-a143-4a6b-b2ab-0a0a0c919c90","_uid":3030264456,"caption":null}
RESPONSE: Oops, an error occurred.`

**Comment by mgp25** [comment]
@losdivinos your upload its wrong check your response: `"upload_id":null`. It works perfect for me. Don't use proxy. If it doesnt work, then your account maybe is flagged.

Check the upload request.

Regards
