### ISSUE TITLE
Latest update throwing a php warning

### ISSUE THREAD

**Issue by jpmoney5065** [mgp25/Instagram-API#905]
Latest update throwing a php warning:
`PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in /xxx/vendor/mgp25/instagram-php/src/Instagram.php on line 45`

Using unmodified latest push.

**Comment by irshad9998** [comment]
I have same issue

**Comment by mgp25** [comment]
@irshad9998 @jpmoney5065 

`Line 41`
```php
        $longOpts = ['settings_adapter::'];
        $options = getopt('', $longOpts);
```

Can you add a `var_dump` after `$options` ?

Expected result should be an empty array:

```
array(0) {
}
```

**Comment by jpmoney5065** [comment]
`bool(false)`

on PHP Version 7.0.15

**Comment by mgp25** [comment]
I dont have that issue, anyway i added a check to make an empty array if `$options` is false
