### ISSUE TITLE
Invalid request in "qe/sync/". Technical questions

### ISSUE THREAD

**Issue by Gourmentt** [mgp25/Instagram-API#907]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Hi, I'm very thankful for your API thing, it helped me to play with this API. 
I have rewrote it to ruby, but when it was in version 7.0. Today I updated my ruby code base (endpoints addresses, request params, body params). And when I'm trying to make qe/sync request - I am getting 'invalid request' message.

So I am asking you:

Reques to this endpoint should be performed? 
- Via POST, right? As I see in code, all requests that contains data $post - going via POST.
- It accepts in POST *body* signed JSON, yep? Only few endpoints required data in request params (se/fetch_headers for example).

Reproducing:

`curl -d "ig_sig_key_version=4&signed_body=aec455c063b13c4792e1360683e5adee1011b94f8acafb091c7f5a45d9488505.%7B%22id%22:%22ba8fb546-b156-4364-a25f-865f29191e7f%22,%22experiments%22:%22ig_android_reg_login_btn_active_state,ig_android_ci_opt_in_at_reg,ig_android_one_click_in_old_flow,ig_android_merge_fb_and_ci_friends_page,ig_android_non_fb_sso,ig_android_mandatory_full_name,ig_android_reg_enable_login_password_btn,ig_android_reg_phone_email_active_state,ig_android_analytics_data_loss,ig_fbns_blocked,ig_android_contact_point_triage,ig_android_reg_next_btn_active_state,ig_android_prefill_phone_number,ig_android_show_fb_social_context_in_nux,ig_android_one_tap_login_upsell,ig_fbns_push,ig_android_phoneid_sync_interval%22%7D" https://i.instagram.com/api/v1/qe/sync/`

I have latest sig_key `5ad7d6f013666cc93c88fc8af940348bd067b68f0dce3c85122a923f4f74b251`,
User-Agent is: `'Instagram 10.3.2 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)'`

**Comment by mgp25** [comment]
@Gourmentt Sorry this is only for API issues. I recommend you to see verbose logs in the API, and compare the request with yours, and then adapt your command/code to it

Regards

**Comment by Gourmentt** [comment]
Okay, thanks, it can help me a lot. I will made github repo later to share my work with others

**Comment by remon** [comment]
@Gourmentt  I am trying to make it also in ruby and I can't do it , if you made any progress in that , kindly help me 
thanks
