### ISSUE TITLE
Sending direct message

### ISSUE THREAD

**Issue by pohmelie** [mgp25/Instagram-API#908]
This code work fine:
```php
$i->setUser($username, $password);
$i->login();
$i->direct_message("12345678", "Hello!");
```

This code work only first DM, second DM return 200 response, but not work:
```php
$i->setUser($username, $password);
$i->login();
$i->direct_message("12345678", "Hello 1!");
$i->direct_message("12345678", "Hello 2!");
```

Should i make some other request between two DM?

**Comment by jpmoney5065** [comment]
> Should i make some other request between two DM?

Yes. Or sleep your script. You can't send too many request too quickly.
