### ISSUE TITLE
Sending direct message [2]

### ISSUE THREAD

**Issue by pohmelie** [mgp25/Instagram-API#909]
Don't get why #908 was closed, since I did not response that suggestion work or not.
@jpmoney5065
``` php
$i->setUser($username, $password);
$i->login();
$i->direct_message("12345678", "Hello 1!");
sleep(30);
$i->direct_message("12345678", "Hello 2!");
```
Again, only first DM sended successfully.

**Comment by jpmoney5065** [comment]
Try waiting longer, 5-10 minutes, your account is probably already flagged for spam from testing.

**Comment by pohmelie** [comment]
@jpmoney5065 
If I restart the whole script first DM sended again. It looks like there should be something between `direct_message` calls.

**Comment by mgp25** [comment]
I closed it because what you are doing is considered as spam (by Instagram).

Regards

**Comment by pohmelie** [comment]
@mgp25 
What am I doing? It is part of your open source library and it is question about it. You have method `direct_message` and I'm just trying to use it. Code in first post is just simplified abstract example.

**Comment by mgp25** [comment]
@pohmelie you are saying why the second request doesnt work.

Answer: Instagram anti-spam measures

Is not an API bug is that what you are saying

**Comment by pohmelie** [comment]
@mgp25 If so, why restart works?

**Comment by mgp25** [comment]
Try to emulate human behaviour, check how you control Instagram etc etc etc and then code something similar

**Comment by pohmelie** [comment]
Ok, I got you. Thanks.

**Comment by dmussaku** [comment]
So did it work?
