### ISSUE TITLE
Path to settings files is broken.

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [mgp25/Instagram-API#910]
This change is breaking whole system!!!

https://github.com/mgp25/Instagram-API/commit/b7a222397fb227fbfe800ce93a8cad1666da724b
```
const DATA_DIR = __DIR__.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR;
```
and in current codebase... 
```
$this->setting = new SettingsFile($username, Constants::DATA_DIR);
```

You fixed the path to settings file, and nobody can change it because it's a constant and you give no way to supply different path.
This path points to vendors/... folder and will be rewritten after every update and all settings for all accounts will disappear. 
Am i missing something or it's a huge fail????

**Comment by mgp25** [comment]
No reason to be dramatic, go back a couple commit until i fix it

Regards

**Comment by Vasiliy-Bondarenko** [comment]
Well, I have some trouble with users today. So it's kind of dramatic for me :))
Thanx.
You make some breaking changes. It's hard to keep up :)
I think i will end up writing tests for everything... I can not test manually every time or just throw the code to production and hope it will work :)

**Comment by mgp25** [comment]
Rolled back to previous code, does it works now?

**Comment by Vasiliy-Bondarenko** [comment]
yes. sure.

**Comment by mgp25** [comment]
@Vasiliy-Bondarenko oks let me know if everything is okay now

**Comment by Vasiliy-Bondarenko** [comment]
well, it's working! thanx.

**Comment by mgp25** [comment]
@Vasiliy-Bondarenko ill be more careful next time so users dont merge code that breaks backwards compatibility

Regards

**Comment by Vasiliy-Bondarenko** [comment]
@mgp25 fixed. now i can update and switch the path. actually you renamed it - it was settingsAdopter :) but it's an easy fix. no problem.
Thanks a lot. You doing a great job. Really appreciated.

**Comment by frrakn** [comment]
Out of curiosity - how were you setting this?

I set it as a constant because aside from actually changing the code I didn't see a way to pass in the settings path. I'm happy to fix my commit - just not sure where you were passing this in.

**Comment by Vasiliy-Bondarenko** [comment]
@frrakn I just extend Instagram class and making all the tweaks i need. In this case - change public property settingsAdapter.

```
class Insta2 extends Instagram
{
    /**
     * @var Account
     */
    protected $acc;
    /**
     * @var Instagram
     */
    protected $insta;

    public function __construct(Account $acc, $checkForDisabledAccount = true)
    {
        // some code skipped...

        parent::__construct(config('insta.original_api_debug'));

        $this->settingsAdapter = [
            'type' => 'file',
            'path' => config('insta.path')
        ];

        $this->setUser($acc->login, $acc->password);

        $this->setProxy("{$acc->proxy_protocol}://{$acc->proxy_host}", (int)$acc->proxy_port, $acc->proxy_username, $acc->proxy_password);

        $this->http = new MyHttpInterface($this);
    }
```
you can see in the last line, that also i'm extending HttpInterface to make some tweaks like error handling, temporary fix incorrect endpoints, fix logging, etc.

@mgp25, the main problem for me with this package is that classes do not use Dependency Injection, so it's very hard to fix some issues. 

Example: you use printing debug information in HttpInterface@request directly to console. So when debug is enabled all json calls i make will fail: [http://joxi.ru/Dr8KLX3t4v1d1A](http://joxi.ru/Dr8KLX3t4v1d1A) 
And there is no way to inject my own Debug class with debugging to log file, SQL, or somewhere else. And by the way - you use direct "echo" call in this method when throttling. So solution for me was extend HttpInterface class, disable debug forever and make my own logging method and throttling also, which is not very elegant solution :)

So it would be much better to depend on interfaces and supply dependencies in constructor or some config.
I planned to work on this issue and make a PR, but i don't have time right now. May be a little later.

**Comment by frrakn** [comment]
@vasiliy_bondarenko I would say to address your needs in customizing each topic:
Error handling - my last set of commits were around assigning error codes especially for this reason, but I think it's the packages responsibility to recognize errors and then propagate them to parent program
Temporary fixes - should just commit to this / temporary fork if you need in production
Logging / debug - dependency injection makes a lot of sense here. Seems like a pretty trivial fix to allow Instagram to take a callback `log($message)` and then replace all instances of `print` or `echo` with that.

@mgp25 the MySQL adapter commit does not break his code. It was renaming `SettingsAdopter` to `SettingsAdapter`. Can we please undo the rollback?

**Comment by mgp25** [comment]
@frrakn yes, send PR that keeps backwards compatibility.

I think best option, would be setting the data path from the constructor. 

Aditionally, if any of you want to add the following fix (`transcode error`), the  solution comes to do this:

If we get `transcode error` or `timeout`, we do a `sleep(1)` and retry the configure request, with 2 attemps as max limit.

Regards

**Comment by frrakn** [comment]
@mgp25 got it, will get you a PR in ~30 min

**Comment by Vasiliy-Bondarenko** [comment]
> Error handling - my last set of commits were around assigning error codes especially for this reason, but I think it's the packages responsibility to recognize errors and then propagate them to parent program

yes. you are almost recreating a lot of my extra code. i came to same idea - just throw exceptions and catch in controllers. now i will delete parts of my code when code will become stable.

> Logging / debug - dependency injection makes a lot of sense here. Seems like a pretty trivial fix to allow Instagram to take a callback log($message) and then replace all instances of print or echo with that.

we can do something like this for not breaking backwards compatibility.

```php
interface LoggerInterface {
    public function log();
}

class DefaultLogger implements LoggerInterface {
    public function log() {}
    
    protected function anyOtherFunction() {}
}

class Instagram {
    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct($debug = false, $truncatedDebug = false)
    {
        // original code skipped
        $this->logger = new DefaultLogger();
    }

    public function injectLogger(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }
}
```

after that it will be very easy to swap implementation of logger and inject it in the class. just don't use injected classes in constructor! :) 

if it is possible to break compatibility - the best way is just inject in constructor

```php
class Instagram2 {
    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct($debug = false, $truncatedDebug = false, LoggerInterface $logger)
    {
        $this->logger = $logger;
    }
}
```

after that everyone will must provide concrete implementation of the logger.
```php
$insta = new Instagram(true, true, new DefaultLogger);
```
the same for any other dependency.
