### ISSUE TITLE
Instagram 10.6.0/10.7.0 

### ISSUE THREAD

**Issue by codeninjacode** [mgp25/Instagram-API#916]
Hi, 
Does anyone have the updated key for Instagram 10.7.0 (48891) ?

Thanks in advance!

**Comment by MMrR0b0TT** [comment]
How are you getting your endpoints?

**Comment by frrakn** [comment]
Getting updated sig key explained here: https://github.com/mgp25/Instagram-API/wiki/Technical-information.

Please read the wiki.

**Comment by codeninjacode** [comment]
I haven't started reversing 10.6.0/10.7.0 yet. Have the endpoints been updated? Has the api been migrated to v3?

**Comment by MMrR0b0TT** [comment]
"You will need a proxy, there are a lot, so use the one you prefer. You will find a lot of information in Google." this doesn't help @frrakn

**Comment by frrakn** [comment]
Looks like this issue was originally brought up around getting a new Instagram sig key, which is explained specifically in that document. If you're looking to capture endpoints, I suggest https://www.charlesproxy.com/. If you Google "capture" and "proxy" it will give you a lot more.

**Comment by MMrR0b0TT** [comment]
tks for your reply @frrakn 
I've used with the fiddler, but now I need a way to find the endpoints in the new version thats using pinning ssl. I need to find a way to patch that apk or something like that

**Comment by mangledbottles** [comment]
Maybe look at SSLunpinning :P http://seclist.us/sslunpinning-android-app-to-bypass-ssl-certificate-validation-certificate-pinning.html

**Comment by maximTartachnik** [comment]
Any luck with unpinning new versions of instagram?
