### ISSUE TITLE
Class 'InstagramAPI\Settings' not found

### ISSUE THREAD

**Issue by mangledbottles** [mgp25/Instagram-API#919]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Code:

```php

include __DIR__.'../../../../autoload.php';
require_once __DIR__.'/../src/ChallengeSMS.php';

$debug = true;

echo "#####################\n";
echo "#                   #\n";
echo "#   SMS CHALLENGE   #\n";
echo "#                   #\n";
echo "#####################\n";

echo "\n\nYour username: ";
$username = trim(fgets(STDIN));
echo $username."\n";

if ($username == '') {
    echo "\n\nYou have to set your username\n";
    exit();
}

echo "\n\nYour settings path folder ([ENTER] if dedault): ";
$settingsPath = trim(fgets(STDIN));

if ($settingsPath == '') {
    $settingsPath = null;
}

$c = new \InstagramAPI\ChallengeSMS($username, $settingsPath, $debug);

$c->startChallenge();

while ($c->getStep() < 3) {
    switch ($c->getStep()) {
        case 1:
            echo "\n\nInsert Phone number: ";
            $code = trim(fgets(STDIN));
            $c->setPhone($code);
            break;

        case 2:
            echo "\n\nInsert Security Code (leavy empty to reset): ";
            $code = trim(fgets(STDIN));
            if ('' == $code) {
                $c->reset();
            } else {
                $c->setCode($code);
            }
            break;

        default:
            echo "No function for this! Press Y to reset, enter to retry\n";
            $code = trim(fgets(STDIN));
            if ($code == 'Y') {
                $c->reset();
            } else {
                $c->startChallenge();
            }
            break;
    }
}

echo "\n\nDone";

```

Error/Log/var_dump:

```php cli
Your settings path folder ([ENTER] if dedault): C:\wamp\www\dev 11\vendor\mgp25\instagram-php\src\data\ifollowzfree\

Fatal error: Class 'InstagramAPI\Settings' not found in C:\wamp\www\dev 11\vendor\mgp25\instagram-php\src\ChallengeSMS.php on line 30

C:\wamp\www\dev 11\vendor\mgp25\instagram-php\examples>
```

---

### Describe your issue

File: examples/challengeSMS.php
I tried running this CLI, input the username but when it asks for settings path; always returns with 
" Fatal error: Class 'InstagramAPI\Settings' not found in C:\wamp\www\dev 11\vendor\mgp25\instagram-php\src\ChallengeSMS.php on line 30" class not found.

This is the line of code it is refering to: 
```php
$this->settings = new Settings($this->settingsPath.'settings-'.$username.'.dat');
```
Thanks :)

**Comment by mangledbottles** [comment]
I created a Settings class in the src/ChallengeSMS.php which works for me

```
class Settings{
    public function __construct($username){
        // $settingsPath = 'C:\wamp\www\dev 11\vendor\mgp25\instagram-php\src\data'.DIRECTORY_SEPARATOR.$username.DIRECTORY_SEPARATOR.'settings-'.$username.'.dat';
           $settingsPath = __DIR__.'/data'.DIRECTORY_SEPARATOR.$username.DIRECTORY_SEPARATOR.'settings-'.$username.'.dat';


        $sets = [];
        if (file_exists($settingsPath)) {
            $fp = fopen($settingsPath, 'r');
            while ($line = fgets($fp, 2048)) {
                $line = trim($line, ' ');
                if ($line[0] == '#') {
                    continue;
                }
                $kv = explode('=', $line, 2);
                $sets[$kv[0]] = trim($kv[1], "\r\n ");
            }
            $this->token = $kv[1];
            fclose($fp);
        } else{
            echo 'file doesnt exist!';
        }

    }

}
```

I will put it in PR

**Comment by mangledbottles** [comment]
Thanks @frrakn 

UPDATE: challengeSMS.php is outdated, Instagram has updated how it works...
Looking at endpoints now

**Comment by mgp25** [comment]
@mangledbottles when solved. Send a PR and ill merge it. Yes, checkpoint should be rewritted

Regards
