### ISSUE TITLE
Account Edit Doesn't Work When Username is Not All Lowercase

### ISSUE THREAD

**Issue by thefish2010** [mgp25/Instagram-API#92]
Editing account profile information does not work when the username has any uppercase characters in it at all.  Line 650 of instagram.php should be changed to this:

'username'      => strtolower($this->username),

from 

'username'      => $this->username,

**Comment by mgp25** [comment]
Send a pull request

Regards

**Comment by RageBrahimi** [comment]
Instagram doesn't have uppercase usernames. They're all lowercase.

**Comment by thefish2010** [comment]
That's precisely the point.  Although Instagram does not have them, a simply typo can cause the username to be of mixed or uppercase.  This corrects it for all cases.
