### ISSUE TITLE
Cannot pass the checkpoint

### ISSUE THREAD

**Issue by lewisqic** [mgp25/Instagram-API#924]
I am getting hung up on the checkpoint issue.  Whenever I try to login via the API, I get the "checkpoint_required" response.  I then go to my instagram page and login and complete the checkpoint verification.  But immediately after when I try to login again via the API, I get the same "checkpoint_required" response as before.  When I tried to implemented the Checkpoint.php API feature, it throws a 404 error on the endpoint, so it's unable to even attempt to request a reset code.  Please help me know what is happening and why I'm suddenly unable to login at all.  Thanks!

**Comment by DmitryMakanin** [comment]
+1
the same issue

**Comment by mgp25** [comment]
@lewisqic Checkpoint is outdated, it required to be updated. If you are using a proxy, there is a high chance to get `checkpoint_required` and therefore to be flagged by Instagram server.

My recommendation, dont use proxy.

And when i fell motivated, i'll update the checkpoint script

Regards!

**Comment by lewisqic** [comment]
I'm not using a proxy, never have, and yet I still get the checkpoint_required issue every time I attempt to login via the API.  I have tested it locally as well as on two separate servers, and it's the same issue on all of them.

**Comment by lewisqic** [comment]
Can you please help me know what I need to do to get around the checkpoint_required issue that I've described?  You suggested to not use a proxy, but you didn't offer any advice on what to do if I'm not using a proxy at all.

**Comment by mgp25** [comment]
@lewisqic maybe your accounts have been flagged. Log in to your device normally, once done, remove stored files inside `data` folder and try logging in again.

If the IP is different, for example if you login from an US IP and then from an EU IP, it will lead to flag too.

I always use it locally and i dont have any issue.

Regards
