### ISSUE TITLE
No exception returned.

### ISSUE THREAD

**Issue by hxhjx** [mgp25/Instagram-API#925]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Hi,

my problem is that on some requests I don't receive an error code if they fail and also no proper exception. I was looking in the issues section how to get proper exception codes and I found only this code:

```
catch (Exception $e) 
{
	print_r($e) . PHP_EOL;
}
```

In my example I am running **getHashtagFeed** . 

```
InstagramAPI\InstagramException Object
(
    [message:protected] =>

    [string:Exception:private] =>

```

As you can see the Exception message and the exception string is empty. Is there a way to get different types of errors in 10/10 cases? I would prefer a generic error message then none.

The reason why I need proper error messages is that I want to send myself an SMS if the script died because of problems.

I hope i explained my problem in detail enough. Thank you a lot for the help and the time spend reading.

**Comment by hxhjx** [comment]
Another question, related to this ticket. I activated debug in the constructor.

`$i = new \InstagramAPI\Instagram(true);`

How can receive the debug? The Wiki and other issues only indicate how to activate it, but not where to find the debug results.

**Comment by DmitryMakanin** [comment]
debug results are passed by `echo`

**Comment by hxhjx** [comment]
^ How does that work?

At the moment I am using this for debugging `file_put_contents('hashtag.log', print_r($feed, True));`

**Comment by mgp25** [comment]
@hxhjx hello, it seems you are new to PHP.

In order to get debug, it is supposed you are using the script in command line. If you do it:

`php myScript.php`

All the debug will be printed out. Remember to set debug to `true`.

```php
$i = new \InstagramAPI\Instagram(true);
```

Once you get it post it here.

And depends how your code is, the try and catch code could have more inside, and maybe isnt the function the one is failing, instead some code of yours. Once you post debug log, i can tell you more.

Regards

**Comment by hxhjx** [comment]
@mgp25 Thank you for your detailed response. While I am not new to PHP, I am terrible new to OOP :)

I am using Putty on a CentOS-72-64-minimal Server.

```
require("vendor/autoload.php");
$i = new \InstagramAPI\Instagram(true);
```

This is my code:

```
<?php

# DATABASE
$dbHost = 'localhost'; $dbUser = 'dev'; $dbPass = '***'; $dbName = '***';

try {
	$dbh = new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4", $dbUser, $dbPass);
	$dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch(PDOException $e) {
	die('Exception: ' . $e->getMessage());
}

require("vendor/autoload.php");
$i = new \InstagramAPI\Instagram(true);

$i->setUser('***', '***');
#$i->setUser('***', '***');
# $i->login();

# next_max_id
# more_available
# more_available
# num_results

function reverseScrape($niche, $max_id = Null)
{
	global $i, $dbh;
		
	$feed = $i->getHashtagFeed($niche, $max_id)->getFullResponse();
	# print_r($feed);
	file_put_contents('content.log', print_r($feed, True));
	
	foreach ($feed['items'] as $key => $value) {
		
			$id 			= $value['id'];
			$likes 			= (int)$value['like_count'];
			$comments 		= (int)$value['comment_count'];
			$type 			= (int)$value['media_type'];
			$text 			= $value['caption']['text'];
			$created 		= (int)$value['taken_at'];
			$created_device	= (int)$value['device_timestamp'];
			$code 			= $value['code'];
			
			if($type == 2) 
			{
				# video
				 $views = (int)$value['view_count'];
				 $url = preg_replace("/\?ig_cache_key=(.*)/", "", $value['video_versions'][0]['url']);
			} 
			else 
			{
				# picture
				 $views = 0; 
				 $url = preg_replace("/\?ig_cache_key=(.*)/", "", $value['image_versions2']['candidates'][0]['url']);
			}

			echo $url."\n";
			
			$username = $value['user']['username'];
			$userid = $value['user']['pk'];
			
			$sth = $dbh->prepare("SELECT ig_id FROM scrapeInterface WHERE ig_id = :ig_id");
			$sth->execute(array( 'ig_id'=>$id ));
			
			if(!$sth->rowCount() > 0)
			{
				$sth = $dbh->prepare("INSERT INTO scrapeInterface (ig_id, url, type, ig_code) VALUES (:ig_id, :url, :type, :code)");
				$sth->execute(array( 'ig_id'=>$id, 'url'=>$url, 'type'=>$type, 'code'=>$code ));
			}
	}

	if($feed['more_available'])
	{		
		reverseScrape($niche, $feed['next_max_id']);
		sleep(rand(2,8));	
	}
}

try 
{
	reverseScrape('funny');
} 
catch (Exception $e) 
{
	print_r($e) . PHP_EOL;
}
```

I am not getting any additional output in the console.

Again I am sorry if I am missing some important part here. The library is really awesome and the work the contributors put into. I am always trying to read the issues or the source code first. But my OOP Fu is a bit weak :)

Thanks in advance.

**Comment by mgp25** [comment]
@hxhjx it seems not an API issue. Anyway, send me and email (check my profile) and ill help you.

Regards
