### ISSUE TITLE
Search Hashtags

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#927]
The latest news on the hashtag. They made a lot of different experiences. Able to do so. Intercepted request to post the official publication of the application and its substituted picture. In search, it is not shown. If you do not replace all the displays. This proves that the image data is important. What's stored is not found. There are no assumptions about you? Exif, who was able to get empty.

**Comment by mgp25** [comment]
@Triden test the following thing: Upload a photo with your device. Download that image using the API, and then reupload the image with the API. Since you have downloaded the imagen from the app, it should contain the exif, and therefore it should work.

Try it.

**Comment by Triden** [comment]
It does not make sense. When loaded, the server overwrites this data and change a photo. We intercepted on the proxy level. And there copy a photo bits. Restores the image of bits. Viewed in photo, but have not been able to find. But! This image appears in the search! But! If the proxy level to replace the image. Override bits on his own. It be published, but in the search to no find it! It is difficult to explain in English. By this I concluded. The fact that the picture is why it is important. Do you understand me?

**Comment by mgp25** [comment]
@Triden im not going to research it or do it either. If you want this, someone else or you should do it.

As i said before, i lost interest in Instagram

Regards

**Comment by Triden** [comment]
It is sad. I'm understood, thank you.

**Comment by mgp25** [comment]
@Triden you can always do it yourself, research about it, reverse engineer, and code, it will take you some time, but you will get what you want

Regards

**Comment by ppeixoto** [comment]
@Triden Seems they are using OpenGL to encode the image somehow. I think this is the way Instagram knows if the image was posted from the original App or not.
