### ISSUE TITLE
searchFBLocation response null when search Japanese location

### ISSUE THREAD

**Issue by letungit90** [mgp25/Instagram-API#929]
For example when search with keyword 恵比寿 it will return null response.
It is not match when search with same keyword in Instagram ios apply.

**Comment by mgp25** [comment]
@letungit90 maybe is this what you are looking for?     

```php
$i->searchFBLocation(utf8_decode('恵比寿'));
```

Im not sure, but test it

**Comment by letungit90** [comment]
use utf8_decode('恵比寿') can return list of location but the result location list and the keyword location is difference. I tried to catch ios app api, it used url_encode to encode keyword, but when i encode by url_encode the result is null
