### ISSUE TITLE
Update Instagram in the app store to sign up. Your version of the app is out of date. 

### ISSUE THREAD

**Issue by GoldenEagle66** [mgp25/Instagram-API#93]
When you register an error
`{"status":"ok","errors":{"version":[{"Update App to Sign Up":["Update Instagram in the app store to sign up. Your version of the app is out of date. "]}]},"account_created":false}`

**Comment by mgp25** [comment]
Updated https://github.com/mgp25/Instagram-API/commit/970b1e2ef97b0a2fff23d7e632d4ee618d291cbb
