### ISSUE TITLE
Get thread id from usernameId [question]

### ISSUE THREAD

**Issue by agustinjch** [mgp25/Instagram-API#930]
First, thanks for all the work you've done so far, it's amazing.

I've been checking the API and there may be an endpoint that your are missing.

When you get into an user profile, you can send a direct message from there, where the app redirects you to the user thread right away. I don't know if the app search in the whole inbox and try to match the user pk (which I don't think so), or there is an endpoint where, given a user id, it returns you the conversation thread id with this user.

Thanks in advance and congrats again!

**Comment by agustinjch** [comment]
Just checked, and it was just cached data in the phone app.

Closing the issue :)

**Comment by NoahGaeta** [comment]
Please tell me how you got this haha, I am clueless on how to get the threadId which I need
