### ISSUE TITLE
About getFollower or getFollowing

### ISSUE THREAD

**Issue by dleviathan** [mgp25/Instagram-API#931]
When get list follower from user i had error below:

> PHP Fatal error:  Call to a member function request() on null in /Applications/XAMPP/xamppfiles/htdocs/****/vendor/mgp25/instagram-php/src/Instagram.php on line 1840

at `$response = $instagramObj->http->request($endPoint, $post, $this->requireLogin, $this->floodWait, false);`

when i debug i find this request return httpcode is **403** and response is html page with content is
>
><div class="error-container -cx-PRIVATE-ErrorPage__errorContainer">
><h2>Error</h2> 
><p>Sorry, too many requests. Please try again later.</p></div>

And i think you shouldn't set time to retry request is 2s after get error "many request", it's short!!
you should throw code error(httpcode !=200) when request for user can custom (e.g change proxy, etc...).
 Thanks for nice lib ❤️

**Comment by mgp25** [comment]
@dleviathan make sure you are using latest code from master. Glad you like the API. Send PR and ill review the changes

Regards!
