### ISSUE TITLE
Proxy Exception (No I am not banned or flagged)

### ISSUE THREAD

**Issue by hxhjx** [mgp25/Instagram-API#934]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hi,

before I posted this Issue I looked through all the issues, the wiki and installed a fresh version via composer. 

I am trying to setup the proxy details like everyone else does in the issues I found.

```
require("vendor/autoload.php");
$i = new \InstagramAPI\Instagram(True, False);

$i->setProxy('123.38.151.100', 3035, 'sfsefes', 'sefsefe');

$i->setUser('sefeesaf', 'seffsgrg');

$i->login();

print_r( $i->getUsernameInfo(234532634) );
```

```
PHP Fatal error:  Uncaught InstagramAPI\InstagramException: Proxy host error. Please check ip address and port of proxy. in /root/***/vendor/mgp25/instagram-php/src/Instagram.php:140
Stack trace:
#0 /root/***/test.php(8): InstagramAPI\Instagram->setProxy(Array, 3035, '***', '***')
#1 {main}
  thrown in /root/***/vendor/mgp25/instagram-php/src/Instagram.php on line 140
```

I also checked the code itself for setProxy. Can anyone explain me this? Especially that the host in an Array... ?

If I use http:// for the host I am getting this exception:

`InstagramAPI\InstagramException: Couldn't get challenge, check your connection`

As a note, the IG account is already running on that IP daily successfully.

Thanks alot.

**Comment by jpmoney5065** [comment]
> #0 /root/***/test.php(8): InstagramAPI\Instagram->setProxy(Array, 3035, '***', '***')

First parameter in `setProxy()` should be a string not an array.

**Comment by hxhjx** [comment]
$i->setProxy('123.38.151.100', 3035, 'sfsefes', 'sefsefe');

I didn't set it as array...

**Comment by mgp25** [comment]
I tried your code and i had no issue. I dont know what you did but the code is working fine. If you still face this issue send me an email for further support

Regards
