### ISSUE TITLE
HTTPS Proxy and Latest CURL

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#938]
Dear @mgp25 , As you know there is 2 type of proxy .
HTTP / HTTPS

unfortunately  php dos not support "HTTPS" proxy type
    `curl_setopt($ch, CURLOPT_PROXYTYPE, 'HTTPS'); // this is not supported till now` 
And to solve this problem i have to call curl directly from command line : 

curl --proxy  https://User:Password@123.123.123.123 --proxy-insecure http://whatismyip.org
Note , curl 7.52 has to be installed.

now , the HTTP lib Instagram-API dos not support https proxy , im ready to port all CURL command to be use `shell_exec(curl.....);`
 may it interest you to merge it with the API ?

**Comment by ewwink** [comment]
why not add this line?

`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); `

**Comment by beshoo1** [comment]
it will not work .. try it your self.
here is a https proxy with username and password

`https://0f5ee342326fecbfb582ed3dc3495fb10f8ebd56:4F11C6A666BF2B9F922309B29CC486F4CC48CA2900E7B7F8679D69E42786EA21@68.71.55.53:443`

**Comment by ewwink** [comment]
tried in firefox and proxy checker and your proxy seem not working, here test using another https proxy.

![curl-https](https://cloud.githubusercontent.com/assets/760764/22788011/d5d84fa6-ef10-11e6-960c-0441fba4987c.jpg)

**Comment by beshoo1** [comment]
My proxy works without any problem please have a look : 

```
root@server [/root]# curl -D - --proxy  https://0f5ee342326fecbfb582ed3dc3495fb10f8ebd56:4F11C6A666BF2B9F922309B29CC486F4CC48CA2900E7B7F8679D69E42786EA21@68.71.55.53:443 --proxy-insecure http://whatismyip.org
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/html
Date: Thu, 09 Feb 2017 21:07:07 GMT
Server: Apache/2.2.22 (Debian)
Set-Cookie: ipcook=1; expires=Thu, 09-Feb-2017 21:17:07 GMT
Vary: Accept-Encoding
X-Powered-By: PHP/5.4.36-0+deb7u3
Transfer-Encoding: chunked
```
but you have to test it under curl 7.52.x

**Comment by beshoo1** [comment]
i am working on this , i will update it..

**Comment by beshoo1** [comment]
Dear @mgp25 
i am working on the "`uploadPhoto()`" function , When i pass  $data ,  `$data = $this->buildBody($bodies, $boundary);`
to the Curl Command Line as POST 

```
       //curl_setopt($ch, CURLOPT_POST, true);
        //curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        $ch_curl['option'][] = '--data "' . $data . '"';
 
```
curl Retrun this error : 
```
sh: -c: line 17: unexpected EOF while looking for matching
sh: -c: line 22: syntax error: unexpected end of file
```

That because $data is not in one line , and it content ( " and ' );

any idea ?

**Comment by beshoo1** [comment]
I managed to save $data to a tmp file and post the file .. but i can not see the image in the instagram 
`
root@server [/home/user/www/panel/boot]# curl -s -D - --user-agent "Instagram 10.3.2 Android (18/4.3; 320dpi; 720x1280; Lanix; ILIUM_L200; ILIUM L200; qcom; en_US)" -L --header "X-IG-Capabilities: 3ToAAA==" --header "X-IG-Connection-Type: WIFI" --header "Content-Type: multipart/form-data; boundary=80afa4ae-3644-4af3-97bc-34fdb955cc86" --header "Content-Length: 41577" --header "Accept-Language: en-US" --header "Accept-Encoding: gzip, deflate" --header "Connection: close" --cookie /home/user/public_html/panel/boot/vendor/mgp25/instagram-php/src/data/bnt_jada/bnt_jada-cookies.dat --cookie-jar /home/user/public_html/panel/boot/vendor/mgp25/instagram-php/src/data/bnt_jada/bnt_jada-cookies.dat --data-binary @/tmp/curl_photo_8e296a067a37563370ded05f5a3bf3ec -w '__curl_information__ http_code:%{http_code} http_connect:%{http_connect} time_total:%{time_total} time_pretransfer:%{time_pretransfer} time_starttransfer:%{time_starttransfer} size_download:%{size_download} size_upload:%{size_upload} size_request:%{size_request} content_type:%{content_type} size_header:%{size_header}' https://i.instagram.com/api/v1/upload/photo/`

HTTP/1.1 100 Continue
Date: Mon, 13 Feb 2017 08:48:54 GMT
```

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 13 Feb 2017 08:48:54 GMT
Content-Type: application/json
Content-Language: en
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Cache-Control: private, no-cache, no-store, must-revalidate
Vary: Cookie, Accept-Language
Set-Cookie: ds_user_id=3022235489; expires=Sun, 14-May-2017 08:48:54 GMT; Max-Age=7776000; Path=/
Set-Cookie: csrftoken=Nuyuslsb6dU6pBumI8B9WFqgUfBr7aLX; expires=Mon, 12-Feb-2018 08:48:54 GMT; Max-Age=31449600; Path=/; Secure
Connection: close
Content-Length: 46
```

`{"status": "ok", "upload_id": "1486975432848"}__curl_information__ http_code:200 http_connect:000 time_total:0.862229 time_pretransfer:0.377242 time_starttransfer:0.499139 size_download:46 size_upload:41577 size_request:1178 content_type:application/json size_header:604root@server 
`

**Comment by mgp25** [comment]
@beshoo1 do all requests

**Comment by beshoo1** [comment]
@mgp25  kindly may you clarify what do you mean by do all requests, what is missing in the curl call , please note that the $data is stored in a file , the content of the file is : 

[](http://beshoo.com/curl_photo_8e296a067a37563370ded05f5a3bf3ec.txt)

**Comment by beshoo1** [comment]
@mgp25 , Strange ! we are a developer ! and we do help each other , closing the issue will help ? i am not sure.

you said one word as an advice  " do all requests " , and i did "All requests" ! 

Please Advice

**Comment by mgp25** [comment]
@beshoo1 that's only one request. Please the the upload photo flow

**Comment by beshoo1** [comment]
We only have ONE flow , here is the log for the original API without any modification

```

POST:  upload/photo/
→ 40.6kB
← 200    46B
RESPONSE: {"upload_id": "1487039541483", "status": "ok"}

POST:  media/configure/
DATA: ig_sig_key_version=4&signed_body=11964b1e1d35f2a88620456d40a44a1313918fe667db90b605125e5252b8ee46.{"_csrftoken":"3hQUpSbi0ZoaV98qUTwvgegvsjtCjKwF","media_folder":"Instagram","source_type":4,"_uid":"3022235489","_uuid":"6492e79c-9fe6-4790-a42c-a51ce404409b","caption":"\u0645\u062c\u0627\u0646\u0627  \u0648\u0627\u0644\u0628\u0644\u0627\u0634 \u0627\u062d\u0644\u0627 \u0634\u064a","upload_id":"1487039541483","device":{"manufacturer":"Garmin","model":"nuvi 3592","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[320,320],"crop_center":[0,0],"crop_zoom":1},"extra":{"source_width":320,"source_height":320}}
← 200    1.12kB
RESPONSE: {"media": {"taken_at": 1487039542, "pk": 1449715214940586430, "id": "1449715214940586430_3022235489", "device_timestamp": 1487039541483, "media_type": 1, "code": "BQebE6cA0G-GduMKzsptknP6ykFc5wgAfEhIn00", "client_cache_key": "MTQ0OTcxNTIxNDk0MDU4NjQzMA==.2", "filter_type": 0, "image_versions2": {"candidates": [{"height": 320, "url": "http://scontent.cdninstagram.com/t51.2885-15/e35/16464152_634394256761363_3495587750940246016_n.jpg?ig_cache_key=MTQ0OTcxNTIxNDk0MDU4NjQzMA%3D%3D.2", "width": 320}, {"height": 240, "url": "http://scontent.cdninstagram.com/t51.2885-15/s240x240/e35/16464152_634394256761363_3495587750940246016_n.jpg?ig_cache_key=MTQ0OTcxNTIxNDk0MDU4NjQzMA%3D%3D.2", "width": 240}, {"height": 150, "url": "http://scontent.cdninstagram.com/t51.2885-15/s150x150/e35/16464152_634394256761363_3495587750940246016_n.jpg?ig_cache_key=MTQ0OTcxNTIxNDk0MDU4NjQzMA%3D%3D.2", "width": 150}]}, "original_width": 320, "original_height": 320, "user": {"show_insights_terms": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/15802398_251291628638754_8720154908038266880_a.jpg", "has_anonymous_profile_picture": false, "is_unpublished": false, "profile_pic_id": "1416782557529444664_3022235489", "can_boost_post": false, "full_name": "\u0628\u0646\u062a \u062c\u062f\u0629", "can_see_organic_insights": false, "pk": 3022235489, "is_private": true, "username": "bnt_jada"}, "organic_tracking_token": "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7InNlcnZlcl90b2tlbiI6IjE0ODcwMzk1NDM1MDR8MTQ0OTcxNTIxNDk0MDU4NjQzMHwzMDIyMjM1NDg5fGExZTVlZGY4ZmUwOWViNjBiZGFjODNkODc3MDhkOWM3YTkxZjRkNjc4YTI5ZmNlZTk3YTMxYzQ0YWJmNGIxNjMiLCJpc19hbmFseXRpY3NfdHJhY2tlZCI6ZmFsc2UsInV1aWQiOiI2MDRlYWFjMGE5ZWI0ODA3ODIxM2E0NjBkZGNjYzE2MjE0NDk3MTUyMTQ5NDA1ODY0MzAifSwic2lnbmF0dXJlIjoiIn0=", "has_liked": false, "comment_likes_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 4, "preview_comments": [], "comment_count": 0, "caption": {"bit_flags": 0, "type": 1, "text": "\u0645\u062c\u0627\u0646\u0627  \u0648\u0627\u0644\u0628\u0644\u0627\u0634 \u0627\u062d\u0644\u0627 \u0634\u064a", "created_at_utc": 1487039543, "status": "Active", "media_id": 1449715214940586430, "user": {"show_insights_terms": false, "profile_pic_url": "http://scontent.cdninstagram.com/t51.2885-19/s150x150/15802398_251291628638754_8720154908038266880_a.jpg", "has_anonymous_profile_picture": false, "is_unpublished": false, "profile_pic_id": "1416782557529444664_3022235489", "can_boost_post": false, "full_name": "\u0628\u0646\u062a \u062c\u062f\u0629", "can_see_organic_insights": false, "pk": 3022235489, "is_private": true, "username": "bnt_jada"}, "has_translation": true, "content_type": "comment", "user_id": 3022235489, "pk": 17861247754115221, "created_at": 1487039543}, "caption_is_edited": false, "photo_of_you": false, "can_viewer_save": true}, "status": "ok", "upload_id": "1487039541483"}

```

**Comment by beshoo1** [comment]
@mgp25 , Correct it helped a lot.
Thank you ,

Regards.
