### ISSUE TITLE
like is not working.

### ISSUE THREAD

**Issue by mochfaizal** [mgp25/Instagram-API#939]
Why when I run function and the like can not always emerge error in feedback required, how do you let me function like can be used without a request feedback

(https://cloud.githubusercontent.com/assets/20994211/22813489/900cc9ac-ef7e-11e6-8cd2-d7eb448fb0cb.png)

**Comment by mgp25** [comment]
@mochfaizal next time, use issue template, and post debug log. Duplicate issue, it is working but your account is flagged

**Comment by mochfaizal** [comment]
@frrakn
