### ISSUE TITLE
Other media configure error: b'E3v4zLVnwi'

### ISSUE THREAD

**Issue by soisme** [mgp25/Instagram-API#940]
Hi,
I often got the error Other media configure error: b'E3v4zLVnwi' when uploading certain photos like this one: http://imgur.com/a/sJ0fu
It's not happening to all photos. Just some. Any ideas why?

Thanks

**Comment by mgp25** [comment]
@soisme because of the aspect ratio, format or size. Sometimes doing a second configure request after it fails solves the issue.

Please, next time post debug log.

Regards

**Comment by Gourmentt** [comment]
Also in some cases you should use image-magick's strip command which purifies image from EXIF metadata. It helped me

**Comment by azureatlas** [comment]
I used to have this problem with some photos, I confirm it was solved by pre-processing the photos with:
exiftool -all= *.jpg

**Comment by oroszgergely** [comment]
This issue started to show up in a few hours ago, even if i try to upload the same photo, same caption as it used to work with it (yesterday), using the new API.
If i revert back to the old API, the upload is OK with the same photo, caption.

**Comment by wiktormazur** [comment]
I have the same problem. I have tried to fix exif metadata but the problem still appears:

On my temporary account: 

POST:  upload/photo/
→ 48.57kB
← 200 	 46B
RESPONSE: {"upload_id": "1490177282527", "status": "ok"}

POST:  media/configure/
DATA: ig_sig_key_version=4&signed_body=8eaf71d823a83099d448d84d7049b7983077ae2f3ffd45a846f3a6169e327937.{"_csrftoken":"toWlEadeDpe2oQM0PW4CyAOSYEE6fZAQ","client_shared_at":1490177283,"source_type":3,"configure_mode":1,"_uid":"2983636099","_uuid":"701c837d-d515-4bcf-a0cb-c36166c6a4e7","caption":{"caption":""},"client_timestamp":1490177283,"device":{"manufacturer":"samsung","model":"SM-G930F","android_version":"23","android_release":"6.0.1"},"upload_id":"1490177282527"}
← 500 	 75B
RESPONSE: {"status": "fail", "message": "Other media configure error: b'RjqdfiDWUA'"}

**Comment by mgp25** [comment]
woah, hold on there, i dont know what you are doing but looking at the caption `caption":{"caption":""}` that looks horrible, i dont know if it was a bug in previous releases, but i recommend you to use latest code @ master branch and check your checkpoint

Regards

**Comment by wiktormazur** [comment]
Yep, you are right. I use the latest code but I have copied the line from the example (31):
https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php
There is an array and should be string: ['caption' => $captionText] to $captionText
Thanks.

**Comment by SteveJobzniak** [comment]
@wiktormazur I am going to guess you've made $captionText into an array with ['caption' => ''] in it, so you are sending us ['caption' => ['caption' => '']].

**Comment by SteveJobzniak** [comment]
The uploadPhoto.php example is right. Your code is wrong for sure, if you're using master.

2nd parameter to uploadTimelinePhoto is a metadata array with things like 'caption' among other things. And the value of caption must be a string if you provide that parameter.

**Comment by instagramlover** [comment]
@SteveJobzniak i am using v2.0 , and i have the same problem and here is my upload log : 
```

POST:  upload/photo/
→ 245.84kB
← 200    46B
RESPONSE: {"upload_id": "1497393199754", "status": "ok"}

POST:  media/configure/
DATA: ig_sig_key_version=4&signed_body=9b8853f8e5db49849d1817966863860566675983abbe5b50269813eac932f75e.{"_csrftoken":"yPpG6Oq4AY2uQOFiP6Gcmz03FwLyd0Yl","_uid":"5459650662","_uuid":"3a85668e-a1e1-4c9b-8323-7c061464254e","edits":{"crop_original_size":[800,600],"crop_zoom":1,"crop_center":[0,0]},"device":{"manufacturer":"samsung","model":"SM-G935F","android_version":"23","android_release":"6.0.1"},"extra":{"source_width":800,"source_height":600},"caption":"#pool #dreamresort #vacation #view","source_type":4,"media_folder":"Camera","upload_id":"1497393199754"}
← 500    75B
RESPONSE: {"message": "Other media configure error: b'E3v4zLVnwi'", "status": "fail"}


```

**Comment by mgp25** [comment]
@instagramlover use latest code from master

**Comment by instagramlover** [comment]
@mgp25  Thank you for your reply ,
Well i did install the latest master : 
here is the log : 
```

POST:  upload/photo/
→ 245.81kB
← 200    46B
RESPONSE: {"upload_id": "1497403998146", "status": "ok"}

POST:  media/configure/
DATA: signed_body=81b9a6598234f1f19fd1c6d90ca81210570652bc81b446a2899f9f8e4d2761dc.{"device":{"manufacturer":"samsung","model":"SM-G935F","android_version":"23","android_release":"6.0.1"},"_csrftoken":"YUCyQ79FsmM7iLMwNc5PE9Wu4LU47MkJ","media_folder":"Camera","source_type":"4","_uid":"5459650662","_uuid":"3a85668e-a1e1-4c9b-8323-7c061464254e","edits":{"crop_original_size":[800,600],"crop_zoom":1,"crop_center":[0,0]},"extra":{"source_width":800,"source_height":600},"caption":"#pool #dreamresort #vacation #view","upload_id":"1497403998146"}&ig_sig_key_version=4
← 500    75B
RESPONSE: {"message": "Other media configure error: b'E3v4zLVnwi'", "status": "fail"}

upload#exception 'InstagramAPI\Exception\EndpointException' with message 'InstagramAPI\Response\ConfigureResponse: Other media configure error: b'E3v4zLVnwi'.' in /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:119
Stack trace:
#0 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Client.php(575): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'Other media con...', Object(InstagramAPI\Response\ConfigureResponse))
#1 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Request.php(296): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\ConfigureResponse), Object(stdClass))
#2 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Request/Internal.php(263): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\ConfigureResponse))
#3 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Request/Internal.php(68): InstagramAPI\Request\Internal->configureSinglePhoto('timeline', Array, Array)
#4 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Request/Timeline.php(34): InstagramAPI\Request\Internal->uploadSinglePhoto('timeline', '/home/myinstara...', Array, Array)
#5 /home/instagramlover/public_html/panel/libgram/include/job.php(2049): InstagramAPI\Request\Timeline->uploadPhoto('/home/myinstara...', Array)
#6 /home/instagramlover/public_html/panel/libgram/include/job.php(161): Job->upload()
#7 /home/instagramlover/public_html/panel/libgram/worker.php(84): Job->startJob()
#8 [internal function]: sendWork('cb78d979799990d...')
#9 /home/instagramlover/public_html/panel/libgram/worker.php(13): call_user_func('sendWork', 'cb78d979799990d...')
#10 {main}
_____________________________________________________________________________
photoUpload
InstagramAPI\Response\ConfigureResponse: Other media configure error: b'E3v4zLVnwi'.

```

**Comment by instagramlover** [comment]
@mgp25 do you like me to attach the photo i am uploading ? is that may help ?
