### ISSUE TITLE
usersFriendship Same Response

### ISSUE THREAD

**Issue by volkanaldas** [mgp25/Instagram-API#941]
$i->usersFriendship($uids) when i use this method every time i got same response as below

>[4292251308] => InstagramAPI\FriendshipStatus Object
                (
                    [following:protected] => 1
                    [followed_by:protected] => 
                    [incoming_request:protected] => 
                    [outgoing_request:protected] => 
                    [is_private:protected] => 1
                    [is_blocking_reel:protected] => 
                    [is_muting_reel:protected] => 
                    [blocking:protected] => 
                )

My code is =>

> <?php

include 'vendor/autoload.php';

$username = $_GET['username'];
$password = $_GET['password'];
$debug = false;
$truncatedDebug = false;

$i = new \InstagramAPI\Instagram($debug,$truncatedDebug);
$i->setUser($username, $password);

if (!$i->isLoggedIn) {
  $i->login();
}

try {

  $uids = array();

  array_push($uids,$i->getUsernameId('emirhan_kose0826'));

  $friendship =  $i->usersFriendship($uids);

  print_r($friendship);

} catch (Exception $e) {
  echo $e->getMessage();
}

**Comment by mgp25** [comment]
@volkanaldas the response is okay, use `var_dump` instead of `print_r`

Regards

**Comment by volkanaldas** [comment]
followed_by always return null

**Comment by mgp25** [comment]
Post debug log

**Comment by volkanaldas** [comment]
how to print debug ?

**Comment by volkanaldas** [comment]
GET:  users/emirhan_kose0826/usernameinfo/
← 200 	 1.07kB
RESPONSE: {"status": "ok", "user": {"username": "emirhan_kose0826", "media_count": 7, "pk": 4292251308, "profile_pic_id": "1409307157731483733_4292251308", "following_count": 34, "is_private": true, "has_anonymous_profile_picture": false, "external_url": "", "geo_media_count": 2, "is_verified": false, "biography": "", "follower_count": 6, "hd_profile_pic_url_info": {"height": 796, "url": "http://scontent-lht6-1.cdninstagram.com/t51.2885-19/15538960_1814665048773053_3391714121505308672_a.jpg", "width": 796}, "usertags_count": 0, "is_favorite": false, "is_business": false, "hd_profile_pic_versions": [{"height": 320, "url": "http://scontent-lht6-1.cdninstagram.com/t51.2885-19/s320x320/15538960_1814665048773053_3391714121505308672_a.jpg", "width": 320}, {"height": 640, "url": "http://scontent-lht6-1.cdninstagram.com/t51.2885-19/s640x640/15538960_1814665048773053_3391714121505308672_a.jpg", "width": 640}], "full_name": "Emirhan K\u00f6se", "profile_pic_url": "http://scontent-lht6-1.cdninstagram.com/t...

GET:  users/cabbarusta/usernameinfo/
← 200 	 1004B
RESPONSE: {"user": {"has_anonymous_profile_picture": false, "hd_profile_pic_versions": [{"height": 320, "width": 320, "url": "http://scontent-lht6-1.cdninstagram.com/t51.2885-19/s320x320/12907281_1400499933582835_1020311100_a.jpg"}, {"height": 640, "width": 640, "url": "http://scontent-lht6-1.cdninstagram.com/t51.2885-19/s640x640/12907281_1400499933582835_1020311100_a.jpg"}], "full_name": "cabbar ozturk", "profile_pic_url": "http://scontent-lht6-1.cdninstagram.com/t51.2885-19/s150x150/12907281_1400499933582835_1020311100_a.jpg", "username": "cabbarusta", "is_business": false, "media_count": 81, "is_verified": false, "biography": "", "follower_count": 102, "external_url": "", "is_favorite": false, "geo_media_count": 3, "is_private": true, "following_count": 425, "usertags_count": 0, "pk": 1738278699, "has_chaining": true, "hd_profile_pic_url_info": {"height": 1080, "width": 1080, "url": "http://scontent-lht6-1.cdninstagram.com/t51.2885-19/12907281_1400499933582835_1020311100_a.jpg"}}, "status": "...

POST:  friendships/show_many/
DATA: _csrftoken=3Yp9sGlON9ml6jetkpsuO6hWuoJnz3HI&user_ids=4292251308,1738278699&_uuid=4174c339-cd9b-4d5c-be40-fbe4bff65b04
← 200 	 259B
RESPONSE: {"status": "ok", "friendship_statuses": {"1738278699": {"outgoing_request": false, "is_private": true, "following": true, "incoming_request": false}, "4292251308": {"outgoing_request": false, "is_private": true, "following": true, "incoming_request": false}}}

**Comment by irshad9998** [comment]
followed_by always return null how can i solve this @mgp25
