### ISSUE TITLE
media deleted

### ISSUE THREAD

**Issue by golches** [mgp25/Instagram-API#944]
POST: upload/video/ → 496B ← 200 2.12kB RESPONSE: {"status": "ok", "video_upload_urls": [{"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn2c17\u0026vx_token=10000\u0026staging_in_tao=0", "expires": 1802218243.659822, "job": "AQBxR38ZRokb2sdOZCovHQ8hcEYMK1Q-GGihB67sYsmUORQEHur8CRX-mT2g-YxAQSCZW1tZfSft4esel8NuSJjilJghJ_f3xpQVaqpmtq-F-6Dq8NN-IAtjGY1-KY7-wNgt10FC8esKOnkZ3vaH5oTvPlwhh1VT9qWXixECIYoPnCsnpG8Ssx-Y4v71z8Gl1GMyObdt1KVrTuCulC5MDhpSlRdJ-yLY6qAfrLgvBk6VDM24SaSQTL5XSyxNmDLPHQoXY0T2UsH7vppzcI5iV_FLkqbHRBj8h7_bc1wza4G0kmh30zYzKyV-Hp0n1VxAQZxN10-FD9Ihngi2AQ81YgLc8JbhAJks_r9KpwHOkO1zPg"}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c22\u0026vx_token=10003\u0026staging_in_tao=0", "expires": 1802218243.6607027, "job": "AQDRqckK8jHxji4hoWp7ft9Jw0YTnGmUAgeOuZlRdaH67JJRNWagWn1s2NIhWtzV6LEOyA_pEHZrvo3JhA4d5YaNfBaybpTAgvs8u36jEuRkucrkzzE-23uUDPgZ6DZFOMUetefi-vQHvlkADfXgJ543GAtyuf5XrQdcoxNNXmoRKb5tohqYbZBt8299r7nHZHmsTSrp1k08o8z16NohjwWmmlST77-acBBSr-EYryOveRu9N6LuNEz395Ft3Teo3GMWZHSAnfeeuCz4HSZX-Drs0HScOme7D4zI-SEIWhJk2jlwRX3MW53dCaT6eAy_9Jw95GDAB48bSuedWD5GwX-rxH2Sp5UVeriENy110AljcQ"}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn1c27\u0026vx_token=10002\u0026staging_in_tao=0", "expires": 1802218243.6615884, "job": "AQCRRbeY64A019R7uAlBy5e5FWsjb9iPe5G5Y6KOs1ywI9nYZCS4OCablqqosvmTmH5lLYJk3Fl2n-XsaOWnh7oQE8ujtUllIFk7G8xgCEMlGyKe97UzPTKurW400AT9IDWML1Tia4bQdOqlXuStDytQiNckeaRGveKs1Yz0riHYF25AIrxtpj-D2RDRDaTTKncgu7Jp7ib-zKcfI6kV0sPC4q-5BUW6qf1ldfxroID01SH4r64b5MGfC_mthMwCp0akMM0yOA-hSSBmifsbVsjNDnVbR1ijFcrK7yyjZqkCTaehWO-rN1mqs3cRxV2mdiO-genzivDTAQVYcfMcm0RLeff08uL6elCMqiidm7qBcQ"}, {"url": "https://upload.instagram.com/api/v1/stage/video/?target=prn2c17\u0026vx_token=10012\u0026staging_in_tao=0", "expires": 1802218243.6625128, "job": "AQDeDOEKOHXWd7OaEQjrDzZ3nHpay1JGGCj0RZbRCJJ_KEBPZKiteWVeBtVL9UErdliiTzOlX96jm_unhiS0gwrTuM-2xvlCkbhVtEfM85Dfsn17tlo1AJ4qy06D0ksUfUuLrLGcDckX_MRrW1hq3fbPvOCHz_o21MtBdQW5jCuEi9ofKpX5bLFCG9yKyzuCLIY1II-CP6secstEp1MpM8anq4DjLzBia6I3RP_ps21iRjaRmeD-2qYwYJe2wQHoxuMn1Pnit1blHP9veUrZu0jmMxjC3TXgDw-8qD1U3nlcwxhdvradVv_JZsoG81yiBBNfEXBbEAyf0y_8CYrc35A-Uw5_I6K5r0vRPOh7QSjFBQ"}], "upload_id": "1486858241407"} POST: upload/photo/ → 154kB ← 201 20B RESPONSE: 473070-630760/630761 POST: upload/photo/ → 22.34kB ← 200 46B RESPONSE: {"status": "ok", "upload_id": "1486858241407"} POST: media/configure/? DATA: ig_sig_key_version=4&signed_body=e868d2407839aa931ccf9b3196823581e686fec7e7d9ffb16e4b28e4fc4537e5.{"_csrftoken":"3Yrao1QEMLwjHeD4UZdQ6jIyABaHrIyr","media_folder":"Instagram","source_type":4,"_uid":"3960926562","_uuid":"8fbde320-672e-414f-b80e-31034562468d","caption":"","upload_id":"1486858241407","device":{"manufacturer":"HTC","model":"HTC_0PKV1","android_version":18,"android_release":"4.3"},"edits":{"crop_original_size":[null,null],"crop_center":[0.0,-0.0],"crop_zoom":1.0},"extra":{"source_width":null,"source_height":null}} ← 200 3.56kB RESPONSE: {"upload_id": "1486858241407", "media": {"taken_at": 1486858466, "pk": 1448196241665532531, "id": "1448196241665532531_3960926562", "device_timestamp": 1486858241407, "media_type": 2, "code": "BQZBs8Vh6Jz", "client_cache_key": "MTQ0ODE5NjI0MTY2NTUzMjUzMQ==.2", "filter_type": 0, "image_versions2": {"candidates": [{"url": "http://ig-s-d-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-15/e15/16463990_119177498601159_2501674224918200320_n.jpg?ig_cache_key=MTQ0ODE5NjI0MTY2NTUzMjUzMQ%3D%3D.2", "height": 360, "width": 640}, {"url": "http://ig-s-d-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-15/s480x480/e15/16463990_119177498601159_2501674224918200320_n.jpg?ig_cache_key=MTQ0ODE5NjI0MTY2NTUzMjUzMQ%3D%3D.2", "height": 270, "width": 480}, {"url": "http://ig-s-d-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-15/s320x320/e15/16463990_119177498601159_2501674224918200320_n.jpg?ig_cache_key=MTQ0ODE5NjI0MTY2NTUzMjUzMQ%3D%3D.2", "height": 180, "width": 320}, {"url": "http://ig-s-d-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-15/s240x240/e15/16463990_119177498601159_2501674224918200320_n.jpg?ig_cache_key=MTQ0ODE5NjI0MTY2NTUzMjUzMQ%3D%3D.2", "height": 135, "width": 240}, {"url": "http://ig-s-d-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-15/s150x150/e15/16463990_119177498601159_2501674224918200320_n.jpg?ig_cache_key=MTQ0ODE5NjI0MTY2NTUzMjUzMQ%3D%3D.2", "height": 84, "width": 150}, {"url": "http://ig-s-d-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-15/s320x320/e15/c140.0.360.360/16463990_119177498601159_2501674224918200320_n.jpg?ig_cache_key=MTQ0ODE5NjI0MTY2NTUzMjUzMQ%3D%3D.2.c", "height": 320, "width": 320}, {"url": "http://ig-s-d-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-15/s240x240/e15/c140.0.360.360/16463990_119177498601159_2501674224918200320_n.jpg?ig_cache_key=MTQ0ODE5NjI0MTY2NTUzMjUzMQ%3D%3D.2.c", "height": 240, "width": 240}, {"url": "http://ig-s-d-a.akamaihd.net/hphotos-ak-xpa1/t51.2885-15/s150x150/e15/c140.0.360.360/16463990_119177498601159_2501674224918200320_n.jpg?ig_cache_key=MTQ0ODE5NjI0MTY2NTUzMjUzMQ%3D%3D.2.c", "height": 150, "width": 150}]}, "original_width": 640, "original_height": 360, "view_count": 0.0, "user": {"show_insights_terms": false, "full_name": "mohamed iskander kebaili", "is_unpublished": false, "has_anonymous_profile_picture": true, "can_see_organic_insights": false, "username": "golches", "pk": 3960926562, "is_private": false, "can_boost_post": false, "profile_pic_url": "http://instagram.fmad3-4.fna.fbcdn.net/t51.2885-19/11906329_960233084022564_1448528159_a.jpg"}, "organic_tracking_token": "eyJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwic2VydmVyX3Rva2VuIjoiMTQ4Njg1ODQ2NzUxNXwxNDQ4MTk2MjQxNjY1NTMyNTMxfDM5NjA5MjY1NjJ8NjcxNzQ5YTM2ZGE0OTZiOWJlNzg2YTcwMWZlNzU4YTZkOWJlZGVlZjJlYzE3ZWNiNDA2ZDc4NGM2Njk1YmFhOSIsInV1aWQiOiIxZTAxNDA2MTEyNjc0YmIwOTFjMWM3MTk1ZGFiZGU0NTE0NDgxOTYyNDE2NjU1MzI1MzEifSwidmVyc2lvbiI6NSwic2lnbmF0dXJlIjoiIn0=", "has_liked": false, "comment_likes_enabled": false, "has_more_comments": false, "max_num_visible_preview_comments": 4, "preview_comments": [], "comment_count": 0, "caption": null, "caption_is_edited": false, "photo_of_you": false, "video_versions": [{"type": 101, "height": 270, "url": "http://scontent-mrs1-1.cdninstagram.com/t50.2886-16/16712874_1226988864022823_2249617635291430912_n.mp4", "width": 480}, {"type": 102, "height": 270, "url": "http://scontent-mrs1-1.cdninstagram.com/t50.2886-16/16712874_1226988864022823_2249617635291430912_n.mp4", "width": 480}, {"type": 103, "height": 270, "url": "http://scontent-mrs1-1.cdninstagram.com/t50.2886-16/16712874_1226988864022823_2249617635291430912_n.mp4", "width": 480}], "has_audio": false, "video_duration": 11.345}, "status": "ok"} POST: media/configure/?video=1 DATA: ig_sig_key_version=4&signed_body=2c870a44b3c31d9fbad77164a06d8adacbab27c1f6cd0c4359c4a005b0a9df91.{"upload_id":1486858241407,"source_type":"3","poster_frame_index":0,"length":0.00,"audio_muted":false,"filter_type":"0","video_result":"deprecated","clips":{"length":20,"source_type":"3","camera_position":"back"},"extra":{"source_width":960,"source_height":1280},"device":{"manufacturer":"HTC","model":"HTC_0PKV1","android_version":18,"android_release":"4.3"},"_csrftoken":"3Yrao1QEMLwjHeD4UZdQ6jIyABaHrIyr","_uuid":"8fbde320-672e-414f-b80e-31034562468d","_uid":"3960926562","caption":""} ← 400 47B RESPONSE: {"status": "fail", "message": "Media deleted."} 

new error and never seen

**Comment by mgp25** [comment]
@golches media couldnt been configured because it was deleted.

**Comment by centhacker** [comment]
i am facing the same issue. can you please explain why it is being deleted?
