### ISSUE TITLE
How do you bypassing ssl pinning?

### ISSUE THREAD

**Issue by baimurzin** [mgp25/Instagram-API#945]
Hello guys! can comeone explain me how to bypass ssl pinning using fiddler. I'm trying to sniff some apps and can't do that.

**Comment by mgp25** [comment]
Hello, sorry, not an API issue

Regards

**Comment by mangledbottles** [comment]
Try patching the APK; https://serializethoughts.com/2016/08/18/bypassing-ssl-pinning-in-android-applications/

**Comment by kevinjon27** [comment]
Any idea how to unpinning ssl?

**Comment by baimurzin** [comment]
@kevinjon27 write to me I found some of ways to do that.
