### ISSUE TITLE
Get and set cookies and token?

### ISSUE THREAD

**Issue by ange007** [mgp25/Instagram-API#946]
Hello.

Whether there is an opportunity to read out and write cookies and a token, for storage directly in applications DB?
Or it is deprived of a sense?

**Comment by estgold** [comment]
Hello! you can store a cookies at DB. But i think you must use a something type of cache, like a Memcache or Redis.
P.S. if you use a cache for storing cookies and using username for a key. Delete a non supported symbols from it, I use a MD5.

**Comment by ange007** [comment]
It is clear.
But how to read cookies from \InstagramAPI\Instagram and to write them back for authorization?

**Comment by mgp25** [comment]
@ange007 its managed automatically by the API

Regards
