### ISSUE TITLE
Memory + Connection Leak

### ISSUE THREAD

**Issue by frrakn** [mgp25/Instagram-API#950]
Hate submitting issues without an answer, but I can't think of a simple one at the moment.

The `\InstagramAPI\Instagram` class has a circular reference with `HttpInterface`.
For example,

```
$i = new \InstagramAPI\Instagram();
$i->setUser("user", "password");
var_dump($i); // $i->http->parent refers back to $i
```

All in all, this is a small memory leak, and not a huge deal. However, coupled with the MySQL SettingAdapter, this keeps the `SettingsMysql` instance alive, and therefore starts leaking DB connections for every `\InstagramAPI\Instagram` instance.

Easily fixed (temporarily) by enabling cyclic garbage collection `gc_enable()` and forcing a cycle collect `gc_collect_cycles()` in the parent script, but was wondering what would be a better long-term fix.

**Comment by jpmoney5065** [comment]
Could pass PDO object into instagram constructor instead of making so many connections.

https://github.com/jpmoney5065/Instagram-API/commit/28b0f4ce086110d99c3576fd42370d46e8f96b72

**Comment by frrakn** [comment]
mmm sure that would work, but injecting a PDO instance kinda forces a dependency on PDO, and restricts how we can manipulate the API in the future

**Comment by jpmoney5065** [comment]
mmm well you have implemented like 4 different ways of setting the settings already, just an option for a 5th way that would solve the terrible amount of connections it currently tries to make.

**Comment by mgp25** [comment]
Have you thought any idea with this?

**Comment by frrakn** [comment]
Haven't really gotten around to it, but having a singleton PDO instance should work in this case. Something like this:
https://gist.github.com/rob-murray/5454707

Feel free to close if you think this is cluttering the Issues, page, although I do think the memory leak is something that should eventually be addressed.

**Comment by mgp25** [comment]
@frrakn i close this issue, but if you have any solution or come with an idea, send a PR and will review if this solves the problem

Regards
