### ISSUE TITLE
How can get all data in the response

### ISSUE THREAD

**Issue by wowDaiver** [mgp25/Instagram-API#951]
I'm so sorry for my question but I in a despair...

In all response we have a lot of fields with nulled values. Why?
How i can get username info (count of followers) in the response of followers list?

For example, we need to know relationship (following) in the my followers (who mutual)...

**Comment by mgp25** [comment]
@wowDaiver you will find some null values and other set values. Imagine i do a request, and the response is A

My object contains A, B and C, but only A will be set, the rest will be null.

In case you dont receive anything (look at the debug log), it could be a connection issue like using a proxy etc

Regards

**Comment by LanchaBasualdo** [comment]
@wowDaiver try `var_dump()` on the response and you'll see them
