### ISSUE TITLE
getTimeline Fatal error

### ISSUE THREAD

**Issue by bisht-sanjeet** [mgp25/Instagram-API#954]
Hey 
I'm getting this error.
`Fatal error:  Call to undefined method InstagramAPI\Instagram::getTimeline() `

When checking file [https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php](https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php)
I can't find any function getTimeline in the instagram.php file but this function is in wiki.
I'm using your latest code.

**Comment by mgp25** [comment]
`timelineFeed`
