### ISSUE TITLE
Go port (goinsta) of this library fetches old feed

### ISSUE THREAD

**Issue by sourcesoft** [mgp25/Instagram-API#955]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I'm having an issue created earlier in [goinsta](https://github.com/ahmdrz/goinsta/issues/14) and PR created for it [here](https://github.com/ahmdrz/goinsta/pull/15).
We couldn't fix it there and don't know what we got left to add.

Summary (original problem from the Go port):

> I have created this user in Instagram and followed a few public celebrities normally from my phone. After Login() and then Timeline() method works just fine and I can fetch feed and paginate. But after a while when I'm sure there's new posts, running Timeline() again keeps giving me the same feed over and over.
> I realized after opening Instagram timeline on my phone and viewing new posts once, next time I run the Go program, Timeline method fetches all the new feeds successfully and I can paginate and everything works just fine.
> It feels like opening Instagram on phone triggers sth that let Timeline() fetch new items not the old cached ones.

We have `$this->syncFeatures();`, `$this->autoCompleteUserList();`, `$this->timelineFeed();` just like the PHP version and not sure why we're experiencing this behaviour.

**Comment by mgp25** [comment]
@sourcesoft have you tried the same with PHP version? Maybe this API does the same ( i really haven't tried it ). In that case it would be as easy as capturing the request does send an ack or read status to each item in the feed

But first of all, you need to check in this behaviour happens in this API first.

Regards

**Comment by sourcesoft** [comment]
@mgp25 I think if this has happened before with the PHP version too, someone should have found it by now. I'm going to try do the same with PHP API and report back. Thank you 👍

**Comment by mgp25** [comment]
@sourcesoft since this is not an API issue (this one), if you have any question issue, send me an email

Regards
