### ISSUE TITLE
taken_at VS device_timestamp

### ISSUE THREAD

**Issue by LanchaBasualdo** [mgp25/Instagram-API#957]
hi, this is not an issue, just looking for some information:
do you guys no what's the difference between [device_timestamp] ad [taken_at]?
Ex:
                    [taken_at] => 1471800574
                    [pk] => 1321881485787928625
                    [id] => 1321881485787928625_217618667
                    [device_timestamp] => 1471800456

I can see the timestamp is just a few second behind on device_timestamp. 
I'm trying to find what the time was locally at the moment the user uploaded the media, not the UTC time.

**Comment by mgp25** [comment]
@LanchaBasualdo 

`taken_at` when photo was done

`device_timestamp` when upload started

Regards

**Comment by LanchaBasualdo** [comment]
@mgp25 
for the next time, where can I ask a question without submitting an issue?
