### ISSUE TITLE
SettingsAdapter with Mysql type stopped working

### ISSUE THREAD

**Issue by joseflorido** [mgp25/Instagram-API#958]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include below *code* that will replicate the error, and the *error log/traceback*.

Code:

```php
// Please provide your own code here
$i = new \InstagramAPI\Instagram($debug);
$i->settingsAdapter = array(
  "type"       => "mysql",
  "username"   => "zzz",
  "password"   => "xxx",
  "host"       => "localhost",
  "database"   => "yyy"
);
```

Error/Log/var_dump:

```php
// Please provide your error log/dump here
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)' in src/Utils/SettingsMysql.php:93 
```

---

### Describe your issue

Code used to work before. Updated to master branch and stopped working. Did the way an options array is passed to constructor changed?

Thanks!

**Comment by joseflorido** [comment]
I was ale to make it work again by defining DB details with env variables:

putenv('DB_USERNAME=xxx');
putenv('DB_PASSWORD=zzz');
putenv('DB_HOST=localhost');
putenv('DB_NAME=yyy');

$i = new \InstagramAPI\Instagram($debug);
$i->settingsAdapter = array(
  "type"       => "mysql"
);

But still, seems to be a bug somewhere with the options array.

**Comment by frrakn** [comment]
check line 31 of `SettingsAdapter`:

```
$name = array_key_exists('name', $config) ? $config['name'] : array_key_exists('db_name', $options) ? options['db_name'] : $env_name !== false ? $env_name : null;
```

you should be using
```
$i->settingsAdapter = array(
  "type"       => "mysql",
  "username"   => "zzz",
  "password"   => "xxx",
  "host"       => "localhost",
  "name"   => "yyy"
);
```
instead of
```
$i->settingsAdapter = array(
  "type"       => "mysql",
  "username"   => "zzz",
  "password"   => "xxx",
  "host"       => "localhost",
  "database"   => "yyy"
);
```

I suppose this is a little confusing. You can change it to look for "database", and maybe also check for "name" to preserve backwards compatibility.
