### ISSUE TITLE
Upload Video Error (JsonMapper)

### ISSUE THREAD

**Issue by pitt123** [mgp25/Instagram-API#959]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [X ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include below *code* that will replicate the error, and the *error log/traceback*.

Code:

Using the latest master without changes (besides the setting of username / password / caption text and path to local mp4 file)

Error/Log/var_dump:

```php
// Please provide your error log/dump here

ET: feed / timeline ? rank_token = XXXX & ranked_content = true← 200 56.31 kB RESPONSE : {
    "next_max_id": "hidden",
    "is_direct_v2_enabled": true,
    "auto_load_more_enabled": true,
    "more_available": true,
    "num_results": 7,
    "status": "ok",
    "feed_items": [....]
}
GET: friendships / autocomplete_user_list / ? version = 2← 429 82 B RESPONSE : {
    "status": "fail",
    "message": "Sorry, too many requests. Please try again later."
}
GET: feed / reels_tray / ←200 46 B RESPONSE: {
    "broadcasts": [],
    "tray": [],
    "status": "ok"
}
GET: direct_v2 / ranked_recipients ? show_threads = true← 200 1.09 kB RESPONSE : {
    "ranked_recipients": [...],
    "status": "ok",
    "expires": 7200,
    "filtered": true
}
GET: direct_share / recent_recipients / ←200 72 B RESPONSE: {
    "expiration_interval": 259200,
    "recent_recipients": [],
    "status": "ok"
}
POST: megaphone / log / DATA: type = feed_aysf & action = seen & reason = & _uuid = XX & device_id = YYY & _csrftoken = ZZZ & uuid = KKK ← 200 33 B RESPONSE: {
    "status": "ok",
    "success": true
}
GET: direct_v2 / inbox / ←200 409 B RESPONSE: {
    "inbox": {
        "has_older": false,
        "unseen_count_ts": 1487680224748799,
        "unseen_count": 0,
        "threads": []
    },
    "status": "ok",
    "pending_requests_total": 0,
    "seq_id": 0,
    "pending_requests_users": [],
    "subscription": {
        "sequence": "hidden",
        "auth": "hidden",
        "url": "wss://telegraph-ash.instagram.com/rt",
        "topic": "hidden"
    }
}
GET: news / inbox / ? activity_module = all← 200 32.66 kB RESPONSE : {
    "continuation_token": 0,
    "counts": {
        "photos_of_you": 0,
        "relationships": 0,
        "requests": 16
    },
    "subscription": null,
    "friend_request_stories": [...],
    "old_stories": [...],
    "status": "ok",
    "new_stories": []
}
GET: discover / explore / ←200 128.56 kB RESPONSE: {
    "next_max_id": "0",
    "max_id": "0",
    "more_available": true,
    "num_results": 20,
    "auto_load_more_enabled": true,
    "status": "ok",
    "items": [...]
}
JsonMapper::map() requires first argument to be an object, NULL given.


```

---

### Describe your issue

When running the upload video (mp4) I get the error above but photos work just fine. I've seen other issues regarding this same error here but they mention the VPS being refused and to try another one, I have no idea what that means, can you please help?

**Comment by mgp25** [comment]
VPS means virtual private server. Im not sure why but people have issues when uploading videos while on specific server, in other cases like localhost works like a charm. In a few days ill check the source code and try to rewrite some things that i think are left to do, this is one of the, so keep tuned!

Also be sure to use commits on master branch, sometimes i dont make a new release until i feel its pretty stable but master has always the latests fixes and so.

And if you have any issue henceforth send me an email and ill try to solve it

Regards
