### ISSUE TITLE
Notice: Undefined index: created_user in ..... Response\AccountCreationResponse.php on line 35

### ISSUE THREAD

**Issue by servettuncel** [mgp25/Instagram-API#961]
Hello. I trying to create a new user. But returned this error;

Notice: Undefined index: created_user in C:\xampp\htdocs\instagram\vendor\mgp25\instagram-php\src\http\Response\AccountCreationResponse.php on line 35

Can you help me ?

**Comment by servettuncel** [comment]
Ok. i used check's and error is nothing. But do not work registration :)

**Comment by mgp25** [comment]
@servettuncel ill eventually will review this, its not my main priority

Regards
