### ISSUE TITLE
searchLocation $query condition incorrect

### ISSUE THREAD

**Issue by bmardock** [mgp25/Instagram-API#965]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Code:

```php
// Please provide your own code here
       if (!is_null($query)) {
            $locationQuery['timestamp'] = time();
        } else {
            $locationQuery['search_query'] = $query;
        }
```
---

### Describe your issue

searchLocation() function does not pass $query value to location_search request
/src/Instagram.php#1184
Please update the if condition to the following:
```php
       if (is_null($query)) {
```
to set $locationQuery['search_query'].

**Comment by mgp25** [comment]
@bmardock use master brach, it seems you have outdated commits

Regards

**Comment by BerkayTutal** [comment]
It looks like master branch still has this problem. I've been looking for this nearly 3 hours now

https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1235
