### ISSUE TITLE
Support Instagram Slideshow feature

### ISSUE THREAD

**Issue by bmardock** [mgp25/Instagram-API#966]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Describe your issue

Add the ability to upload more than one photo to uploadPhoto() method.

**Comment by jpmoney5065** [comment]
Would be really cool if someone could figure out a way to integrate guzzle into the http connection so we could set up pools of concurrent requests instead of 1 at a time!

**Comment by mgp25** [comment]
@bmardock ill eventually do it

@jpmoney5065 you can use https://github.com/php-curl-class/php-curl-class

Regards
