### ISSUE TITLE
Transcode timeout

### ISSUE THREAD

**Issue by DaveOff** [mgp25/Instagram-API#967]
I Have 2 Accounts, Account 1 Successfuly work and video uploaded but on account 2 i get error :  Transcode timeout

**Response**

```json
edits":{"crop_original_size":[null,null],"crop_center":[0,0],"crop_zoom":1},"extra":{"source_width":null,"source_height":null}}
 ← 202 50B RESPONSE: {"status": "fail", "message": "Transcode timeout"} InstagramAPI\ConfigureResponse : Transcode timeout
```

**code**
```php
include __DIR__.'/vendor/autoload.php';
/////// CONFIG ///////
$username = 'ali.bavafa2020';
$password = '**********';
$debug = false;
$video = '1.mov';     // path to the video
$caption = 'fdsgdfgdf';     // caption
//////////////////////
$i = new \InstagramAPI\Instagram($debug);
$i->setUser($username, $password);
try {
    $i->login();
} catch (Exception $e) {
    echo $e->getMessage();
    exit();
}
try {
    $i->uploadVideo($video, $caption, '1.jpg');
} catch (Exception $e) {
    echo $e->getMessage();
}
```

**Comment by romalytvynenko** [comment]
Hello!

Please check video upload responses when you upload in chunks. And show debug here. Maybe we can deal with this problem.

**Comment by Triden** [comment]
@romalytvynenko, hello. I am Russian, and I would be easier to talk to you in Russian. I have a couple similar problems. Can get you  the contact?

**Comment by mgp25** [comment]
@DaveOff Can you post here the exact same video you are trying to upload?

Regards

**Comment by icanary** [comment]
I have the same problem. almost with every mp4 video.
Maybe there is some changes in api?

**Comment by mgp25** [comment]
Seems to be working fine now!

Regards
