### ISSUE TITLE
Unable to get user's Media

### ISSUE THREAD

**Issue by farhanansari** [mgp25/Instagram-API#971]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include below *code* that will replicate the error, and the *error log/traceback*.

Code:

```php
include 'Instagram-API-master/vendor/autoload.php';
require 'Instagram-API-master/src/Instagram.php';

$i = new \InstagramAPI\Instagram($debug);

$i->setUser($username, $password);

try {
    $i->login();
} catch (Exception $e) {
    echo 'something went wrong '.$e->getMessage()."\n";
    exit(0);
}

###########################
// Get User Media 
###########################
$usernameId = $i->getUsernameId('miapreconstruction');
$helper = $i->getGeoMedia($usernameId);
print_r($helper->getFullResponse());
//print_r($helper->getFullResponse()->geo_media[0]->media_id);
//print_r($i->getMediaLikers($helper->getFullResponse()->geo_media[0]->media_id));
```

Error/Log/var_dump:

php test.php 

=========================
stdClass Object
(
    [geo_media] => Array
        (
        )

    [status] => ok
)

=========================
---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

Few weeks ago I was able to do $i->getGeoMedia($usernameId) and able to get all media of a user.  Since last night I am unable to pull anything for any user.  Wondering if anything has changed.  I am trying to pull all or top 20 posts/media for a user.

Thanks

**Comment by SteveJobzniak** [comment]
getGeoMedia calls some /maps/ endpoint.

The correct endpoint to get a user's timeline is `/v1/feed/user/<USERID>/`. Which is done via getUserFeed().

YOU'RE WELCOME! :)
