### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by thegliga** [mgp25/Instagram-API#972]
Actually I can't send DM's because of this error. Here is the code:

```
<?php

include __DIR__.'/vendor/autoload.php';
require '/vendor/mgp25/instagram-php/src/Instagram.php';

/////// CONFIG ///////
$username = '';
$password = '';
$debug = true;
$caption = '';
$rec = "";
//////////////////////

$i = new \InstagramAPI\Instagram($debug);

$i->setUser($username, $password);
try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}

try {
    $i->direct_message($caption, $rec);
} catch (Exception $e) {
    echo $e->getMessage();
}

?>
```

Here is the error:

Warning: Missing argument 2 for InstagramAPI\Instagram::__construct(), called in C:\wamp\www\instagram-bot\index.php on line 11 and defined in C:\wamp\www\instagram-bot\vendor\mgp25\instagram-php\src\Instagram.php on line 34

Notice: Undefined variable: password in C:\wamp\www\instagram-bot\vendor\mgp25\instagram-php\src\Instagram.php on line 38

Notice: Undefined variable: password in C:\wamp\www\instagram-bot\vendor\mgp25\instagram-php\src\Instagram.php on line 54

Fatal error: Call to undefined function InstagramAPI\curl_init() in C:\wamp\www\instagram-bot\vendor\mgp25\instagram-php\src\http\HttpInterface.php on line 35

**Comment by mgp25** [comment]
@thegliga please read wiki, requirements ans issues. This is not an API issue

Regards
