### ISSUE TITLE
Redeclare Class Objects/Item.php

### ISSUE THREAD

**Issue by DaveOff** [mgp25/Instagram-API#980]
i have one problem, after 

`$startInsta->uploadVideo($video, $caption, $coverPath);`

i get : 

` PHP Fatal error:  Cannot redeclare class InstagramAPI\Item in/vendor/mgp25/instagram-php/src/http/Response/Objects/Item.php on line 0
`

**Comment by kholmukhamedovme** [comment]
I see by path you have installed library through "compose require ...", right? It didn't work for me too.
I just git cloned the repository and run "composer install --prefer-source --no-interaction". Just try it out.
