### ISSUE TITLE
Video views not increasing

### ISSUE THREAD

**Issue by newfolders** [mgp25/Instagram-API#986]
I can like videos with:

$i->like($mediaid);

But when I like it, it doesn't increase video views count. Till this day I thought when I like a video, it automatically views the video too. But it doesn't. How can I do that?

**Comment by mgp25** [comment]
Im not doing this feature 

Regards

**Comment by newfolders** [comment]
Of course. I just thought this feature is already in the php-api somewhere. Thank you very much.

**Comment by mgp25** [comment]
@newfolders maybe in future, but not doing it because of people spamming :/
