### ISSUE TITLE
Not install composer   

### ISSUE THREAD

**Issue by CHIRAG153** [mgp25/Instagram-API#992]
composer require mgp25/instagram-php
when i run this command  give me a error

 **./composer.json has been updated
Loading composer repositories with package information
The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)**

**Comment by mgp25** [comment]
@CHIRAG153 it doesnt seem to be an API issue, check this:

```
composer diagnose
```

and 

```
composer self-update -vvv
```

Regards
