### ISSUE TITLE
Acctual time of publication of media

### ISSUE THREAD

**Issue by LanchaBasualdo** [mgp25/Instagram-API#997]
When we get the response for a certain media we get this info among others: 
`    [taken_at] => 1483908933 ` and  `[device_timestamp] => 1483908856`
Im having some trouble understanding what time was at the place where the user uploaded the media, disregarding the difference between the `[taken_at]` and `[device_timestamp]`.
Can we manage to know this?

**Comment by SteveJobzniak** [comment]
`taken_at` = Unix timestamp when the user uploaded the media via the app. Instagram has misnamed this value in my opinion. It's not when the media was taken/photographed. It's when it was uploaded.

`device_timestamp` = Not sure. Never used it.

If I convert your taken_at via http://www.unixtimestamp.com/index.php, I get:
```
1483908933
Is equivalent to:
01/08/2017 @ 8:55pm (UTC)
```

**Comment by LanchaBasualdo** [comment]
I understand the convertion, thing is what if this person uploaded the photo in the US or if he is in australia? How can we know where was he when he uploaded it or what time was it when he pressed the shared button?

**Comment by SteveJobzniak** [comment]
All Unix timestamps are in UTC+0 time regardless of where in the world the uploader is.

There is no way for us to know what timezone the uploader is in.

So display the taken_at time in your own local timezone, or in UTC+0 if you want to render it totally universally.

**Comment by LanchaBasualdo** [comment]
Ok thanks
