### ISSUE TITLE
Warning about Curl library (HttpInterface rewrite)

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#999]
Hi there @mgp25 !

I see that you are rewriting this to use the `Curl` class instead of the raw `curl_*` interfaces. That's a good change.

I come from another project, Instagram-SDK-PHP, but I'm going to migrate to this library instead and will be helping out with development here! You've built a fantastic library and I admire your work.

Thought I'd start out my contributions by giving you a few Curl class warnings that we've learned in the other project:

- First of all, if it's not too late, **_strongly_** consider switching to [Guzzle](https://github.com/guzzle/guzzle) right now instead. It's the world's number one HTTP library for PHP. It's _far_ better than Curl, and has incredible code structure, supports advanced streaming of disk-data to support any filesizes (you can upload/download huge files without putting it all in memory with file_get_contents), it uses pooling of connections for great speed, it re-uses cURL handles (instead of constantly releasing and initializing handles like Curl does), and it has modern HTTP exception support. One of the goals of Instagram is actually to move _away_ from Curl to Guzzle. And now you guys are moving to Curl. Ouch. ;-) The Curl library isn't terrible, but it's not great either.
- Anyway, if you stick with Curl, I can see that you've introduced a bug that I've previously fixed in Instagram. Which is: Every time `request()` is called, you run `$this->curl = new Curl();`. This leads to a resource and file handle leak that [kills any system that runs long Instagram scripts]. The cURL handles don't get released. The solution is to wrap everything in a `try{}finally{}` to ensure a 100% guaranteed release of the cURL handle whenever the `request()` function ends. See here and search for `finally` to see how the release is ensured: 
- Furthermore, be aware that your HTTPS connections to the Instagram API will often break mid-request. It happens quite frequently since Instagram is a very overloaded API service. So just be aware of that. So we _must_ look at the value of `curl->curlError`. There's going to be errors there very often (perhaps 1 in every 150-300 requests). Again, look at our `Request.php` which I linked above and search for the word "curlError" to see how to handles Curl class transfer errors, and be sure to add handling to this library. The check must be made immediately after the execution of Curl's `get()` / `post()`. Currently you aren't checking for any errors at all.
- Lastly, I strongly suggest throwing exceptions whenever there's a cURL error. That way the caller can decide what to do when their Instagram-API attempt failed. Such as deciding to retry, or not. I see that you've got a hardcoded "retry X times" mechanism but that is limiting to those that want more freedom. With exceptions, the users of this library can decide to retry manually with any advanced logic they prefer, such as "mark this in our DB for retry next time our script runs".
- And if you do decide to throw exceptions, be sure to give both `$curl->errorMessage` and `$curl->errorCode` to the caller in the exception message. The message portion can come from any SSL library, whereas the cURL error code is more accurate at telling you what went wrong. Both are necessary for figuring out what went wrong. More explanation here: https://github.com/liamcottle/Instagram-SDK-PHP/commit/6fc18db6f178035365667b3b3614f305543dc89b

Alright mgp, I hope this information comes in handy in your rewrite! Thank you again for all the hard work you've put into this library. It's going to be a joy to port my projects to it and to help out here!

**Comment by mgp25** [comment]
@SteveJobzniak thanks for your recommendations, since i recently moved to curl, i dont mind move to guzzle, ill check it and i hope around this weekend, API will be moved to guzzle. I took notes of all points, and ill try to do all of them, if i forget any of them, just remind me in the future commits.

Probably Friday-Saturdary will be done

Regards

**Comment by SteveJobzniak** [comment]
@mgp25 Sounds good to me. Guzzle is absolutely stunning and I bet you'll fall in love with it. ;-)

I'm happy to be onboard and focusing my energy on your project from now on, with this vibrant community of contributors you've built. And the structure of your project is very nice!

Take care.

**Comment by SteveJobzniak** [comment]
@mgp25 Oh and by the way, one more tip: When using Guzzle, you will benefit from storing the `$client = new \GuzzleHttp\Client();` instance in a class somewhere. From a single Guzzle Client instance, you can do infinite `request()` calls. It automatically handles all cURL pooling and connection re-use and other clever optimizations for you! So there won't be any need to create new Clients on every request() call. ;-)

**Comment by jpmoney5065** [comment]
+1 for Guzzle!

**Comment by mgp25** [comment]
@SteveJobzniak can you reach me by mail?

**Comment by SteveJobzniak** [comment]
@mgp25 I would be happy to!

And FYI: http://docs.guzzlephp.org/en/latest/request-options.html#proxy-option

Because @beshoo1 keeps talking about proxies. This is how to do that in Guzzle. But that's a later question long after porting to Guzzle. Maybe he can contribute that code himself after this library uses Guzze.

**Comment by beshoo1** [comment]
@SteveJobzniak Thank you in advance ,
please have a look to this and see that HTTPS proxy has some problem with **GuzzleHttp** , im not sure at least it dos not work with me : 

```
<?php
ini_set("display_errors", "1");
error_reporting(E_ALL);
require './vendor/autoload.php';

$client = new GuzzleHttp\Client();
# i tryed tcp:// and https:// same thing , and to prove that the proxy is working 
$res = $client->request('GET', 'whatismyip.org', [
'proxy' => [
        'https' => 'tcp://38ab6bab3ee10a17df7272fd0f5c3a469ff2b312:D32CC998147689418ED01C3706C5676B625B6B4BCF86D4BBF66B9335A51276B1@162.253.130.147:443'
    ]
]);
echo $res->getStatusCode();
// "200"
echo $res->getHeader('content-type');
// 'application/json; charset=utf8'
echo $res->getBody();
```
it returned my server ip address!

To prove that proxy is working just fine : 
ps: curl has to be  >= "**curl 7.52.1**"

root@server [~/download/guzzlephp]# /usr/local/bin/curl -V
**curl 7.52.1** (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.1e zlib/1.2.3 c-ares/1.11.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets **HTTPS-proxy**
root@server [~/download/guzzlephp]#

`
/usr/local/bin/curl --proxy https://38ab6bab3ee10a17df7272fd0f5c3a469ff2b312:D32CC998147689418ED01C3706C5676B625B6B4BCF86D4BBF66B9335A51276B1@162.253.130.147:443 --proxy-insecure  http://whatismyip.org
`
you can see the returned ip is the proxy ip address.

Please advice.

**Comment by SteveJobzniak** [comment]
@beshoo1 Many problems above. Here's how far I got fixing it:

```php
<?php
ini_set("display_errors", "1");
error_reporting(E_ALL);
require './vendor/autoload.php';

$client = new GuzzleHttp\Client();
// i tryed tcp:// and https:// same thing  
$res = $client->request('GET', 'https://ipecho.net/plain', [
    'proxy' => [
        'https' => 'https://38ab6bab3ee10a17df7272fd0f5c3a469ff2b312:D32CC998147689418ED01C3706C5676B625B6B4BCF86D4BBF66B9335A51276B1@162.253.130.147:443'
    ]
]);
echo $res->getStatusCode().PHP_EOL;
// "200"
echo $res->getHeaderLine(‘Content-Type').PHP_EOL;
// 'application/json; charset=utf8'
echo $res->getBody().PHP_EOL;
```

Problem is that the proxy has invalid SSL certificate. You are supposed to be able to disable SSL verification in cURL, and Guzzle is a wrapper around cURL, so I am sure there's a way. Good luck.

**Comment by beshoo1** [comment]
No you can not "disable SSL verification in cURL" since the proxy is https.
any way here is the code with disabled  SSL verification .

```
<?php
ini_set("display_errors", "1");
error_reporting(E_ALL);
require './vendor/autoload.php';

$client = new GuzzleHttp\Client();
// i tryed tcp:// and https:// same thing

$res = $client->request('GET', 'ipecho.net/plain', [
'verify' => false,
'debug' => true,
'proxy' => [
        'https' => 'tcp://38ab6bab3ee10a17df7272fd0f5c3a469ff2b312:D32CC998147689418ED01C3706C5676B625B6B4BCF86D4BBF66B9335A51276B1@162.253.130.147:443'
    ]
]);

echo $res->getStatusCode().PHP_EOL;
echo $res->getBody().PHP_EOL;

```
debug information

```
* About to connect() to ipecho.net port 80 (#0)
*   Trying 5.12.46.85... * connected
* Connected to ipecho.net (5.12.46.85) port 80 (#0)
> GET /plain HTTP/1.1
Host: ipecho.net
User-Agent: GuzzleHttp/6.2.1 curl/7.19.7 PHP/5.6.30

< HTTP/1.1 200 OK
< Server: nginx/1.10.2
< Date: Thu, 02 Mar 2017 01:54:54 GMT
< Content-Type: text/plain
< Transfer-Encoding: chunked
< Connection: keep-alive
< Expires: Wed, 02 Mar 2016 01:54:54 GMT
< Cache-Control: no-cache
<
* Connection #0 to host ipecho.net left intact
```
200text/plain
107.xxx.xxx.xxx <=== **which is my server ip address**

**Comment by SteveJobzniak** [comment]
@beshoo1 Dude you are doing the exact same mistake again.

```php
$res = $client->request('GET', 'ipecho.net/plain', [
```

See anything wrong? Guess how to make a https request. ;-) Hint: Not like `'ipecho.net/plain'`!

**Comment by beshoo1** [comment]
```
* Proxy CONNECT aborted
* Closing connection #0

```

I am reading about handler , maybe other Handler support https !

**Comment by SteveJobzniak** [comment]
Are you a bit retarded? :-P

**Comment by SteveJobzniak** [comment]
Here, for the 3rd time I'll fix your code. If you don't see the necessary changes this time then I have no idea what else to do to help you.

```php
<?php
ini_set("display_errors", "1");
error_reporting(E_ALL);
require './vendor/autoload.php';

$client = new GuzzleHttp\Client();
// i tryed tcp:// and https:// same thing

$res = $client->request('GET', 'https://ipecho.net/plain', [
'verify' => false,
'debug' => true,
'proxy' => [
        'https' => 'https://38ab6bab3ee10a17df7272fd0f5c3a469ff2b312:D32CC998147689418ED01C3706C5676B625B6B4BCF86D4BBF66B9335A51276B1@162.253.130.147:443'
    ]
]);

echo $res->getStatusCode().PHP_EOL;
echo $res->getBody().PHP_EOL;
```

Now... Bedtime!... ;-)

**Comment by beshoo1** [comment]
Thank you and i did test it and i did report what is the error , did you test it in your box ?

```

root@server [~/download/guzzlephp]# php phptest.php
* About to connect() to proxy 162.253.130.147 port 443 (#0)
*   Trying 162.253.130.147... * connected
* Connected to 162.253.130.147 (162.253.130.147) port 443 (#0)
* Establish HTTP proxy tunnel to ipecho.net:443
* Proxy auth using Basic with user '38ab6bab3ee10a17df7272fd0f5c3a469ff2b312'
> CONNECT ipecho.net:443 HTTP/1.1
Proxy-Authorization: Basic MzhhYjZiYWIzZWUxMGExN2RmNzI3MmZkMGY1YzNhNDY5ZmYyYjMxMjpEMzJDQzk5ODE0NzY4OTQxOEVEMDFDMzcwNkM1Njc2QjYyNUI2QjRCQ0Y4NkQ0QkJGNjZCOTMzNUE1MTI3NkIx
Proxy-Connection: Keep-Alive
User-Agent: GuzzleHttp/6.2.1 curl/7.19.7 PHP/5.6.30
Host: ipecho.net

* Proxy CONNECT aborted
* Closing connection #0
<font color=ff0000>
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 56: Proxy CONNECT aborted (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /root/download/guzzlephp/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Stack trace:
#0 /root/download/guzzlephp/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /root/download/guzzlephp/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /root/download/guzzlephp/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /root/download/guzzlephp/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): Guzz in /root/download/guzzlephp/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187
root@server [~/download/guzzlephp]#

```

**Comment by SteveJobzniak** [comment]
@beshoo1 

```
+ $ php test.php 
*   Trying 162.253.130.147...
* TCP_NODELAY set
* Connected to 162.253.130.147 (162.253.130.147) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Proxy certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.opera-proxy.net
*  start date: Feb  2 00:00:00 2016 GMT
*  expire date: Feb  1 23:59:59 2019 GMT
*  subjectAltName does not match 162.253.130.147
* SSL: no alternative certificate subject name matches target host name '162.253.130.147'
* Closing connection 0
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 51: SSL: no alternative certificate subject name matches target host name '162.253.130.147' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in ......
```

**Comment by beshoo1** [comment]
I got same "PHP Fatal error" , and as you can see HTTPS proxy has some problems with curl and certification.

**Comment by SteveJobzniak** [comment]
The main problem is the proxy you are using. It is bad.

You are using an IP. The proxy's HTTPS port has a certificate for a domain name (*.opera-proxy.net).

So it gets rejected.

**Comment by SteveJobzniak** [comment]
Okay I figured out what you are doing.

You couldn't get the invalid proxy certificate to validate, so you just removed "https://" from the proxy itself. But you kept the ":443" (SSL port). So now I did the same and get the same error as you.

Please stop this and just get a working proxy with a proper domain name!

**Comment by SteveJobzniak** [comment]
Here is what you are trying to do:

```
curl --verbose --proxy http://38ab6bab3ee10a17df7272fd0f5c3a469ff2b312:D32CC998147689418ED01C3706C5676B625B6B4BCF86D4BBF66B9335A51276B1@162.253.130.147:443 http://ipecho.net/plain
```

See. The problem you are blaming Guzzle for is your own bad proxy's fault:

```
*   Trying 162.253.130.147...
* TCP_NODELAY set
* Connected to 162.253.130.147 (162.253.130.147) port 443 (#0)
* Proxy auth using Basic with user '38ab6bab3ee10a17df7272fd0f5c3a469ff2b312'
> GET http://ipecho.net/plain HTTP/1.1
> Host: ipecho.net
> Proxy-Authorization: Basic MzhhYjZiYWIzZWUxMGExN2RmNzI3MmZkMGY1YzNhNDY5ZmYyYjMxMjpEMzJDQzk5ODE0NzY4OTQxOEVEMDFDMzcwNkM1Njc2QjYyNUI2QjRCQ0Y4NkQ0QkJGNjZCOTMzNUE1MTI3NkIx
> User-Agent: curl/7.51.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 

* Curl_http_done: called premature == 0
* Connection #0 to host 162.253.130.147 left intact
```

**Comment by beshoo1** [comment]
Please note , i used `--proxy-insecure` in the command line in order to make the connection go through

**Comment by SteveJobzniak** [comment]
@beshoo1 `--proxy-insecure` doesn't exist in PHP's cURL. It only accepts valid proxies. You can see the list of verify-related options in PHP's cURL here: http://php.net/curl_setopt

**Comment by beshoo1** [comment]
That what i side more and more ! please review my posts ! any way , thank you very much for your time.

**Comment by SteveJobzniak** [comment]
@beshoo1 Well we tried. :) But the good news is that https proxies DO work in Guzzle. Just needs a working one! ;-)

**Comment by beshoo1** [comment]
Well , as you know opera provide FREE https proxy . and i like to use it , i will try to find the subdomain behind the ip address :)
**CN=*.opera-proxy.net**

**Comment by beshoo1** [comment]
Ok i found it .
ping de.opera-proxy.net , you got an ip address which is the https proxy , but if you ping it once more time you got a new ip address , LOL instagram will love to show checkpoint :)

**Comment by SteveJobzniak** [comment]
@beshoo1 Yeah... You finally found its real hostname (de.opera-proxy.net). Now everything works perfectly since the certificate matches! Here's the final code.

Except as you say, Opera always chooses a random route for its output so your IP changes every request. But well... good luck with that! ;-)

```php
<?php
ini_set("display_errors", "1");
error_reporting(E_ALL);
require './vendor/autoload.php';

$client = new GuzzleHttp\Client();
$res = $client->request('GET', 'http://ipecho.net/plain', [
'debug' => true,
'proxy' => [
        'http' => 'https://38ab6bab3ee10a17df7272fd0f5c3a469ff2b312:D32CC998147689418ED01C3706C5676B625B6B4BCF86D4BBF66B9335A51276B1@de.opera-proxy.net:443'
    ]
]);

echo $res->getStatusCode().PHP_EOL;
echo $res->getBody().PHP_EOL;
```

**Comment by beshoo1** [comment]
Dear @SteveJobzniak after long search, it seem there is no way yo use the opera proxy but by providing the hostname which wll cose a problem sinse it provides a random ip address. 

I am really frustrated that php curl dos not support --proxy-insecure. 

Now @mgp25 change to GuzzleHttp which is very good option, but in this case which is important in my scenario. 

I do appreciate if you can help me in order to find a solution to use any workaround to support 
 --proxy-insecure. 

I am very sorry, but what can i say, implementing a curl command line handler is not supported in GuzzleHttp. 

Please advise

**Comment by SteveJobzniak** [comment]
@beshoo1 Contact Guzzle and ask if there's any way to force insecure proxies in Guzzle/PHP-cURL.

Go here: https://github.com/guzzle/guzzle/issues

But it does not seem to ever be possible to force PHP-cURL to allow invalid proxies, sorry. Therefore there is nothing we can do. So don't ask us anymore. Ask Guzzle. And if **they** say it's possible, we'll look at it again.

Good luck.
